RELIC: include/relic_pp.h File Reference
relic_pp.h File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_fpx.h"
#include "relic_epx.h"
#include "relic_types.h"
Macros
#define pp_add_k1(L, M, R, P, Q)
#define pp_add_k2_projc(L, R, P, Q)
#define pp_add_k2(L, R, P, Q)
#define pp_add_k8_projc(L, R, Q, P)
#define pp_add_k8(L, R, Q, P)
#define pp_add_k12_projc(L, R, Q, P)
#define pp_add_k12(L, R, Q, P)
#define pp_add_k16_projc(L, R, Q, P)
#define pp_add_k16(L, R, Q, P)
#define pp_add_k18_projc(L, R, Q, P)
#define pp_add_k18(L, R, Q, P)
#define pp_add_k24(L, R, Q, P)
#define pp_add_k48(L, R, Q, P)
#define pp_add_k54(L, RX, RY, RZ, QX, QY, P)
#define pp_dbl_k1(L, M, R, P, Q)
#define pp_dbl_k2_projc(L, R, P, Q)
#define pp_dbl_k2(L, R, P, Q)
#define pp_dbl_k8_projc(L, R, Q, P)
#define pp_dbl_k8(L, R, Q, P)
#define pp_dbl_k12_projc(L, R, Q, P)
#define pp_dbl_k12(L, R, Q, P)
#define pp_dbl_k16_projc(L, R, Q, P)
#define pp_dbl_k16(L, R, Q, P)
#define pp_dbl_k18_projc(L, R, Q, P)
#define pp_dbl_k18(L, R, Q, P)
#define pp_dbl_k24(L, R, Q, P)
#define pp_dbl_k48(L, R, Q, P)
#define pp_dbl_k54(L, RX, RY, RZ, P)
#define pp_map_k1(R, P, Q)
#define pp_map_k2(R, P, Q)
#define pp_map_k8(R, P, Q)
#define pp_map_k12(R, P, Q)
#define pp_map_k16(R, P, Q)
#define pp_map_k18(R, P, Q)
#define pp_map_sim_k1(R, P, Q, M)
#define pp_map_sim_k2(R, P, Q, M)
#define pp_map_sim_k8(R, P, Q, M)
#define pp_map_sim_k12(R, P, Q, M)
#define pp_map_sim_k16(R, P, Q, M)
#define pp_map_sim_k18(R, P, Q, M)
Functions
void pp_map_init (void)
void pp_map_clean (void)
void pp_add_k1_basic (fp_t l, fp_t m, ep_t r, const ep_t p, const ep_t q)
void pp_add_k1_projc (fp_t l, fp_t m, ep_t r, const ep_t p, const ep_t q)
void pp_add_k2_basic (fp2_t l, ep_t r, const ep_t p, const ep_t q)
void pp_add_k2_projc_basic (fp2_t l, ep_t r, const ep_t p, const ep_t q)
void pp_add_k2_projc_lazyr (fp2_t l, ep_t r, const ep_t p, const ep_t q)
void pp_add_k8_basic (fp8_t l, ep2_t r, const ep2_t q, const ep_t p)
void pp_add_k8_projc_basic (fp8_t l, ep2_t r, const ep2_t q, const ep_t p)
void pp_add_k8_projc_lazyr (fp8_t l, ep2_t r, const ep2_t q, const ep_t p)
void pp_add_k12_basic (fp12_t l, ep2_t r, const ep2_t q, const ep_t p)
void pp_add_k12_projc_basic (fp12_t l, ep2_t r, const ep2_t q, const ep_t p)
void pp_add_k12_projc_lazyr (fp12_t l, ep2_t r, const ep2_t q, const ep_t p)
void pp_add_lit_k12 (fp12_t l, ep_t r, const ep_t p, const ep2_t q)
void pp_add_k16_basic (fp16_t l, ep4_t r, const ep4_t q, const ep_t p)
void pp_add_k16_projc_basic (fp16_t l, ep4_t r, const ep4_t q, const ep_t p)
void pp_add_k16_projc_lazyr (fp16_t l, ep4_t r, const ep4_t q, const ep_t p)
void pp_add_lit_k16 (fp16_t l, ep_t r, const ep_t p, const ep4_t q)
void pp_add_k18_basic (fp18_t l, ep3_t r, const ep3_t q, const ep_t p)
void pp_add_k18_projc_basic (fp18_t l, ep3_t r, const ep3_t q, const ep_t p)
void pp_add_k18_projc_lazyr (fp18_t l, ep3_t r, const ep3_t q, const ep_t p)
void pp_add_lit_k18 (fp18_t l, ep_t r, const ep_t p, const ep3_t q)
void pp_add_k24_basic (fp24_t l, ep4_t r, const ep4_t q, const ep_t p)
void pp_add_k24_projc (fp24_t l, ep4_t r, const ep4_t q, const ep_t p)
void pp_add_k48_basic (fp48_t l, ep8_t r, const ep8_t q, const ep_t p)
void pp_add_k48_projc (fp48_t l, ep8_t r, const ep8_t q, const ep_t p)
void pp_add_k54_basic (fp54_t l, fp9_t rx, fp9_t ry, const fp9_t qx, const fp9_t qy, const ep_t p)
void pp_add_k54_projc (fp54_t l, fp9_t rx, fp9_t ry, fp9_t rz, const fp9_t qx, const fp9_t qy, const ep_t p)
void pp_dbl_k1_basic (fp_t l, fp_t m, ep_t r, const ep_t p, const ep_t q)
void pp_dbl_k1_projc (fp_t l, fp_t m, ep_t r, const ep_t p, const ep_t q)
void pp_dbl_k2_basic (fp2_t l, ep_t r, const ep_t p, const ep_t q)
void pp_dbl_k2_projc_basic (fp2_t l, ep_t r, const ep_t p, const ep_t q)
void pp_dbl_k2_projc_lazyr (fp2_t l, ep_t r, const ep_t p, const ep_t q)
void pp_dbl_k8_basic (fp8_t l, ep2_t r, const ep2_t q, const ep_t p)
void pp_dbl_k8_projc_basic (fp8_t l, ep2_t r, const ep2_t q, const ep_t p)
void pp_dbl_k8_projc_lazyr (fp8_t l, ep2_t r, const ep2_t q, const ep_t p)
void pp_dbl_k12_basic (fp12_t l, ep2_t r, const ep2_t q, const ep_t p)
void pp_dbl_k12_projc_basic (fp12_t l, ep2_t r, const ep2_t q, const ep_t p)
void pp_dbl_k12_projc_lazyr (fp12_t l, ep2_t r, const ep2_t q, const ep_t p)
void pp_dbl_k16_basic (fp16_t l, ep4_t r, const ep4_t q, const ep_t p)
void pp_dbl_k16_projc_basic (fp16_t l, ep4_t r, const ep4_t q, const ep_t p)
void pp_dbl_k16_projc_lazyr (fp16_t l, ep4_t r, const ep4_t q, const ep_t p)
void pp_dbl_k18_basic (fp18_t l, ep3_t r, const ep3_t q, const ep_t p)
void pp_dbl_k18_projc_basic (fp18_t l, ep3_t r, const ep3_t q, const ep_t p)
void pp_dbl_k18_projc_lazyr (fp18_t l, ep3_t r, const ep3_t q, const ep_t p)
void pp_dbl_k24_basic (fp24_t l, ep4_t r, const ep4_t q, const ep_t p)
void pp_dbl_k24_projc (fp24_t l, ep4_t r, const ep4_t q, const ep_t p)
void pp_dbl_k48_basic (fp48_t l, ep8_t r, const ep8_t q, const ep_t p)
void pp_dbl_k48_projc (fp48_t l, ep8_t r, const ep8_t q, const ep_t p)
void pp_dbl_k54_basic (fp54_t l, fp9_t rx, fp9_t ry, const ep_t p)
void pp_dbl_k54_projc (fp54_t l, fp9_t rx, fp9_t ry, fp9_t rz, const ep_t p)
void pp_dbl_lit_k12 (fp12_t l, ep_t r, const ep_t p, const ep2_t q)
void pp_dbl_lit_k16 (fp16_t l, ep_t r, const ep_t p, const ep4_t q)
void pp_dbl_lit_k18 (fp18_t l, ep_t r, const ep_t p, const ep3_t q)
void pp_exp_k1 (fp_t c, fp_t a)
void pp_exp_k2 (fp2_t c, fp2_t a)
void pp_exp_k8 (fp8_t c, fp8_t a)
void pp_exp_k12 (fp12_t c, fp12_t a)
void pp_exp_k16 (fp16_t c, fp16_t a)
void pp_exp_k18 (fp18_t c, fp18_t a)
void pp_exp_k24 (fp24_t c, fp24_t a)
void pp_exp_k48 (fp48_t c, fp48_t a)
void pp_exp_k54 (fp54_t c, fp54_t a)
void pp_norm_k1 (ep_t c, const ep_t a)
void pp_norm_k2 (ep_t c, const ep_t a)
void pp_norm_k8 (ep2_t c, const ep2_t a)
void pp_norm_k12 (ep2_t c, const ep2_t a)
void pp_norm_k16 (ep4_t c, const ep4_t a)
void pp_norm_k18 (ep3_t c, const ep3_t a)
void pp_norm_k24 (ep4_t c, const ep4_t a)
void pp_norm_k48 (ep8_t c, const ep8_t a)
void pp_map_tatep_k1 (fp_t r, const ep_t p, const ep_t q)
void pp_map_sim_tatep_k1 (fp_t r, const ep_t *p, const ep_t *q, int m)
void pp_map_tatep_k2 (fp2_t r, const ep_t p, const ep_t q)
void pp_map_sim_tatep_k2 (fp2_t r, const ep_t *p, const ep_t *q, int m)
void pp_map_weilp_k1 (fp_t r, const ep_t p, const ep_t q)
void pp_map_sim_weilp_k1 (fp_t r, const ep_t *p, const ep_t *q, int m)
void pp_map_weilp_k2 (fp2_t r, const ep_t p, const ep_t q)
void pp_map_sim_weilp_k2 (fp2_t r, const ep_t *p, const ep_t *q, int m)
void pp_map_oatep_k8 (fp8_t r, const ep_t p, const ep2_t q)
void pp_map_sim_oatep_k8 (fp8_t r, const ep_t *p, const ep2_t *q, int m)
void pp_map_tatep_k12 (fp12_t r, const ep_t p, const ep2_t q)
void pp_map_sim_tatep_k12 (fp12_t r, const ep_t *p, const ep2_t *q, int m)
void pp_map_weilp_k12 (fp12_t r, const ep_t p, const ep2_t q)
void pp_map_sim_weilp_k12 (fp12_t r, const ep_t *p, const ep2_t *q, int m)
void pp_map_oatep_k12 (fp12_t r, const ep_t p, const ep2_t q)
void pp_map_sim_oatep_k12 (fp12_t r, const ep_t *p, const ep2_t *q, int m)
void pp_map_tatep_k16 (fp16_t r, const ep_t p, const ep4_t q)
void pp_map_sim_tatep_k16 (fp16_t r, const ep_t *p, const ep4_t *q, int m)
void pp_map_weilp_k16 (fp16_t r, const ep_t p, const ep4_t q)
void pp_map_sim_weilp_k16 (fp16_t r, const ep_t *p, const ep4_t *q, int m)
void pp_map_oatep_k16 (fp16_t r, const ep_t p, const ep4_t q)
void pp_map_sim_oatep_k16 (fp16_t r, const ep_t *p, const ep4_t *q, int m)
void pp_map_tatep_k18 (fp18_t r, const ep_t p, const ep3_t q)
void pp_map_sim_tatep_k18 (fp18_t r, const ep_t *p, const ep3_t *q, int m)
void pp_map_weilp_k18 (fp18_t r, const ep_t p, const ep3_t q)
void pp_map_sim_weilp_k18 (fp18_t r, const ep_t *p, const ep3_t *q, int m)
void pp_map_oatep_k18 (fp18_t r, const ep_t p, const ep3_t q)
void pp_map_sim_oatep_k18 (fp18_t r, const ep_t *p, const ep3_t *q, int m)
void pp_map_k24 (fp24_t r, const ep_t p, const ep4_t q)
void pp_map_sim_k24 (fp24_t r, const ep_t *p, const ep4_t *q, int m)
void pp_map_k48 (fp48_t r, const ep_t p, const ep8_t q)
void pp_map_sim_k48 (fp48_t r, const ep_t *p, const ep8_t *q, int m)
void pp_map_k54 (fp54_t r, const ep_t p, const fp9_t qx, const fp9_t qy)
Detailed Description
Interface of the module for computing bilinear pairings over prime elliptic curves.
Definition in file relic_pp.h.
Macro Definition Documentation
pp_add_k1
#define pp_add_k1 (L, M, R, P, Q)
Value:
pp_add_k1_projc(L, M, R, P, Q)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 1.
Parameters
[out] L - the numerator of the result of the evaluation.
[out] M - the denominator of the result of the evaluation.
[in,out] R - the resulting point and first point to add.
[in] P - the second point to add.
[in] Q - the affine point to evaluate the line function.
Definition at line 61 of file relic_pp.h.
Referenced by pp_mil_k1().
pp_add_k2_projc
#define pp_add_k2_projc (L, R, P, Q)
Value:
pp_add_k2_projc_lazyr(L, R, P, Q)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 2 using projective coordinates.
Parameters
[out] L - the result of the evaluation.
[in,out] R - the resulting point and first point to add.
[in] P - the second point to add.
[in] Q - the affine point to evaluate the line function.
Definition at line 77 of file relic_pp.h.
pp_add_k2
#define pp_add_k2 (L, R, P, Q)
Value:
pp_add_k2_projc(L, R, P, Q)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 2.
Parameters
[out] L - the result of the evaluation.
[in,out] R - the resulting point and first point to add.
[in] P - the second point to add.
[in] Q - the affine point to evaluate the line function.
Definition at line 92 of file relic_pp.h.
Referenced by pp_mil_k2(), and pp_mil_lit_k2().
pp_add_k8_projc
#define pp_add_k8_projc (L, R, Q, P)
Value:
pp_add_k8_projc_lazyr(L, R, Q, P)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 8 using projective coordinates.
Parameters
[out] L - the result of the evaluation.
[in,out] R - the resulting point and first point to add.
[in] Q - the second point to add.
[in] P - the affine point to evaluate the line function.
Definition at line 108 of file relic_pp.h.
pp_add_k8
#define pp_add_k8 (L, R, Q, P)
Value:
pp_add_k8_projc(L, R, Q, P)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 8.
Parameters
[out] L - the result of the evaluation.
[in,out] R - the resulting point and first point to add.
[in] Q - the second point to add.
[in] P - the affine point to evaluate the line function.
Definition at line 123 of file relic_pp.h.
Referenced by pp_mil_k8().
pp_add_k12_projc
#define pp_add_k12_projc (L, R, Q, P)
Value:
pp_add_k12_projc_lazyr(L, R, Q, P)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using projective coordinates.
Parameters
[out] L - the result of the evaluation.
[in,out] R - the resulting point and first point to add.
[in] Q - the second point to add.
[in] P - the affine point to evaluate the line function.
Definition at line 139 of file relic_pp.h.
pp_add_k12
#define pp_add_k12 (L, R, Q, P)
Value:
pp_add_k12_projc(L, R, Q, P)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12.
Parameters
[out] L - the result of the evaluation.
[in,out] R - the resulting point and first point to add.
[in] Q - the second point to add.
[in] P - the affine point to evaluate the line function.
Definition at line 154 of file relic_pp.h.
Referenced by pp_fin_k12_oatep(), and pp_mil_k12().
pp_add_k16_projc
#define pp_add_k16_projc (L, R, Q, P)
Value:
pp_add_k16_projc_lazyr(L, R, Q, P)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 16 using projective coordinates.
Parameters
[out] L - the result of the evaluation.
[in,out] R - the resulting point and first point to add.
[in] Q - the second point to add.
[in] P - the affine point to evaluate the line function.
Definition at line 170 of file relic_pp.h.
pp_add_k16
#define pp_add_k16 (L, R, Q, P)
Value:
pp_add_k16_projc(L, R, Q, P)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 16.
Parameters
[out] L - the result of the evaluation.
[in,out] R - the resulting point and first point to add.
[in] Q - the second point to add.
[in] P - the affine point to evaluate the line function.
Definition at line 185 of file relic_pp.h.
Referenced by pp_fin_k16_oatep(), and pp_mil_k16().
pp_add_k18_projc
#define pp_add_k18_projc (L, R, Q, P)
Value:
pp_add_k18_projc_lazyr(L, R, Q, P)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 18 using projective coordinates.
Parameters
[out] L - the result of the evaluation.
[in,out] R - the resulting point and first point to add.
[in] Q - the second point to add.
[in] P - the affine point to evaluate the line function.
Definition at line 201 of file relic_pp.h.
pp_add_k18
#define pp_add_k18 (L, R, Q, P)
Value:
pp_add_k18_projc(L, R, Q, P)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 18.
Parameters
[out] L - the result of the evaluation.
[in,out] R - the resulting point and first point to add.
[in] Q - the second point to add.
[in] P - the affine point to evaluate the line function.
Definition at line 216 of file relic_pp.h.
Referenced by pp_fin_k18_oatep(), and pp_mil_k18().
pp_add_k24
#define pp_add_k24 (L, R, Q, P)
Value:
pp_add_k24_projc(L, R, Q, P)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 24.
Parameters
[out] L - the result of the evaluation.
[in,out] R - the resulting point and first point to add.
[in] Q - the second point to add.
[in] P - the affine point to evaluate the line function.
Definition at line 231 of file relic_pp.h.
Referenced by pp_mil_k24().
pp_add_k48
#define pp_add_k48 (L, R, Q, P)
Value:
pp_add_k48_projc(L, R, Q, P)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 48.
Parameters
[out] L - the result of the evaluation.
[in,out] R - the resulting point and first point to add.
[in] Q - the second point to add.
[in] P - the affine point to evaluate the line function.
Definition at line 246 of file relic_pp.h.
Referenced by pp_mil_k48().
pp_add_k54
#define pp_add_k54 (L, RX, RY, RZ, QX, QY, P)
Value:
pp_add_k54_projc(L, RX, RY, RZ, QX, QY, P)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 54.
Parameters
[out] L - the result of the evaluation.
[in,out] R - the resulting point and first point to add.
[in] Q - the second point to add.
[in] P - the affine point to evaluate the line function.
Definition at line 261 of file relic_pp.h.
Referenced by pp_mil_k54().
pp_dbl_k1
#define pp_dbl_k1 (L, M, R, P, Q)
Value:
pp_dbl_k1_projc(L, M, R, P, Q)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 1.
Parameters
[out] L - the numerator of the result of the evaluation.
[out] M - the denominator of the result of the evaluation.
[out] R - the resulting point.
[in] P - the point to double.
[in] Q - the affine point to evaluate the line function.
Definition at line 277 of file relic_pp.h.
Referenced by pp_mil_k1().
pp_dbl_k2_projc
#define pp_dbl_k2_projc (L, R, P, Q)
Value:
pp_dbl_k2_projc_lazyr(L, R, P, Q)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 2 using projective coordinates.
Parameters
[out] L - the result of the evaluation.
[in,out] R - the resulting point.
[in] Q - the point to double.
[in] P - the affine point to evaluate the line function.
Definition at line 293 of file relic_pp.h.
pp_dbl_k2
#define pp_dbl_k2 (L, R, P, Q)
Value:
pp_dbl_k2_projc(L, R, P, Q)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 2.
Parameters
[out] L - the result of the evaluation.
[out] R - the resulting point.
[in] P - the point to double.
[in] Q - the affine point to evaluate the line function.
Definition at line 308 of file relic_pp.h.
Referenced by pp_mil_k2(), and pp_mil_lit_k2().
pp_dbl_k8_projc
#define pp_dbl_k8_projc (L, R, Q, P)
Value:
pp_dbl_k8_projc_lazyr(L, R, Q, P)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using projective coordinates.
Parameters
[out] L - the result of the evaluation.
[in,out] R - the resulting point.
[in] Q - the point to double.
[in] P - the affine point to evaluate the line function.
Definition at line 324 of file relic_pp.h.
pp_dbl_k8
#define pp_dbl_k8 (L, R, Q, P)
Value:
pp_dbl_k8_projc(L, R, Q, P)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 8.
Parameters
[out] L - the result of the evaluation.
[out] R - the resulting point.
[in] Q - the point to double.
[in] P - the affine point to evaluate the line function.
Definition at line 339 of file relic_pp.h.
Referenced by pp_mil_k8().
pp_dbl_k12_projc
#define pp_dbl_k12_projc (L, R, Q, P)
Value:
pp_dbl_k12_projc_lazyr(L, R, Q, P)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using projective coordinates.
Parameters
[out] L - the result of the evaluation.
[in,out] R - the resulting point.
[in] Q - the point to double.
[in] P - the affine point to evaluate the line function.
Definition at line 355 of file relic_pp.h.
pp_dbl_k12
#define pp_dbl_k12 (L, R, Q, P)
Value:
pp_dbl_k12_projc(L, R, Q, P)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12.
Parameters
[out] L - the result of the evaluation.
[out] R - the resulting point.
[in] Q - the point to double.
[in] P - the affine point to evaluate the line function.
Definition at line 370 of file relic_pp.h.
Referenced by pp_mil_k12().
pp_dbl_k16_projc
#define pp_dbl_k16_projc (L, R, Q, P)
Value:
pp_dbl_k16_projc_lazyr(L, R, Q, P)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 16 using projective coordinates.
Parameters
[out] L - the result of the evaluation.
[in,out] R - the resulting point.
[in] Q - the point to double.
[in] P - the affine point to evaluate the line function.
Definition at line 386 of file relic_pp.h.
pp_dbl_k16
#define pp_dbl_k16 (L, R, Q, P)
Value:
pp_dbl_k16_projc(L, R, Q, P)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 16.
Parameters
[out] L - the result of the evaluation.
[out] R - the resulting point.
[in] Q - the point to double.
[in] P - the affine point to evaluate the line function.
Definition at line 401 of file relic_pp.h.
Referenced by pp_fin_k16_oatep(), and pp_mil_k16().
pp_dbl_k18_projc
#define pp_dbl_k18_projc (L, R, Q, P)
Value:
pp_dbl_k18_projc_lazyr(L, R, Q, P)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 18 using projective coordinates.
Parameters
[out] L - the result of the evaluation.
[in,out] R - the resulting point.
[in] Q - the point to double.
[in] P - the affine point to evaluate the line function.
Definition at line 417 of file relic_pp.h.
pp_dbl_k18
#define pp_dbl_k18 (L, R, Q, P)
Value:
pp_dbl_k18_projc(L, R, Q, P)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 18.
Parameters
[out] L - the result of the evaluation.
[out] R - the resulting point.
[in] Q - the point to double.
[in] P - the affine point to evaluate the line function.
Definition at line 432 of file relic_pp.h.
Referenced by pp_fin_k18_oatep(), and pp_mil_k18().
pp_dbl_k24
#define pp_dbl_k24 (L, R, Q, P)
Value:
pp_dbl_k24_projc(L, R, Q, P)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 24.
Parameters
[out] L - the result of the evaluation.
[out] R - the resulting point.
[in] Q - the point to double.
[in] P - the affine point to evaluate the line function.
Definition at line 447 of file relic_pp.h.
Referenced by pp_mil_k24().
pp_dbl_k48
#define pp_dbl_k48 (L, R, Q, P)
Value:
pp_dbl_k48_projc(L, R, Q, P)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 48.
Parameters
[out] L - the result of the evaluation.
[out] R - the resulting point.
[in] Q - the point to double.
[in] P - the affine point to evaluate the line function.
Definition at line 462 of file relic_pp.h.
Referenced by pp_mil_k48().
pp_dbl_k54
#define pp_dbl_k54 (L, RX, RY, RZ, P)
Value:
pp_dbl_k54_projc(L, RX, RY, RZ, P)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 54.
Parameters
[out] L - the result of the evaluation.
[out] R - the resulting point.
[in] Q - the point to double.
[in] P - the affine point to evaluate the line function.
Definition at line 477 of file relic_pp.h.
Referenced by pp_mil_k54().
pp_map_k1
#define pp_map_k1 (R, P, Q)
Value:
pp_map_tatep_k1(R, P, Q)
Computes a pairing of two prime elliptic curve points defined on an elliptic curves of embedding degree 1. Computes e(P, Q).
Parameters
[out] R - the result.
[in] P - the first elliptic curve point.
[in] Q - the second elliptic curve point.
Definition at line 493 of file relic_pp.h.
pp_map_k2
#define pp_map_k2 (R, P, Q)
Value:
pp_map_tatep_k2(R, P, Q)
Computes a pairing of two prime elliptic curve points defined on an elliptic curves of embedding degree 2. Computes e(P, Q).
Parameters
[out] R - the result.
[in] P - the first elliptic curve point.
[in] Q - the second elliptic curve point.
Definition at line 509 of file relic_pp.h.
pp_map_k8
#define pp_map_k8 (R, P, Q)
Value:
pp_map_oatep_k8(R, P, Q)
Computes a pairing of two prime elliptic curve points defined on an elliptic curves of embedding degree 8. Computes e(P, Q).
Parameters
[out] R - the result.
[in] P - the first elliptic curve point.
[in] Q - the second elliptic curve point.
Definition at line 520 of file relic_pp.h.
pp_map_k12
#define pp_map_k12 (R, P, Q)
Value:
pp_map_oatep_k12(R, P, Q)
Computes a pairing of two prime elliptic curve points defined on an elliptic curve of embedding degree 12. Computes e(P, Q).
Parameters
[out] R - the result.
[in] P - the first elliptic curve point.
[in] Q - the second elliptic curve point.
Definition at line 535 of file relic_pp.h.
pp_map_k16
#define pp_map_k16 (R, P, Q)
Value:
pp_map_oatep_k16(R, P, Q)
Computes a pairing of two prime elliptic curve points defined on an elliptic curve of embedding degree 16. Computes e(P, Q).
Parameters
[out] R - the result.
[in] P - the first elliptic curve point.
[in] Q - the second elliptic curve point.
Definition at line 551 of file relic_pp.h.
pp_map_k18
#define pp_map_k18 (R, P, Q)
Value:
pp_map_oatep_k18(R, P, Q)
Computes a pairing of two prime elliptic curve points defined on an elliptic curve of embedding degree 18. Computes e(P, Q).
Parameters
[out] R - the result.
[in] P - the first elliptic curve point.
[in] Q - the second elliptic curve point.
Definition at line 567 of file relic_pp.h.
pp_map_sim_k1
#define pp_map_sim_k1 (R, P, Q, M)
Value:
pp_map_sim_tatep_k1(R, P, Q, M)
Computes a multi-pairing of elliptic curve points defined on an elliptic curve of embedding degree 1. Computes \prod e(P_i, Q_i).
Parameters
[out] R - the result.
[in] P - the first pairing arguments.
[in] Q - the second pairing arguments.
[in] M - the number of pairings to evaluate.
Definition at line 582 of file relic_pp.h.
pp_map_sim_k2
#define pp_map_sim_k2 (R, P, Q, M)
Value:
pp_map_sim_tatep_k2(R, P, Q, M)
Computes a multi-pairing of elliptic curve points defined on an elliptic curve of embedding degree 2. Computes \prod e(P_i, Q_i).
Parameters
[out] R - the result.
[in] P - the first pairing arguments.
[in] Q - the second pairing arguments.
[in] M - the number of pairings to evaluate.
Definition at line 597 of file relic_pp.h.
pp_map_sim_k8
#define pp_map_sim_k8 (R, P, Q, M)
Value:
pp_map_sim_oatep_k8(R, P, Q, M)
Computes a multi-pairing of elliptic curve points defined on an elliptic curve of embedding degree 8. Computes \prod e(P_i, Q_i).
Parameters
[out] R - the result.
[in] P - the first pairing arguments.
[in] Q - the second pairing arguments.
[in] M - the number of pairings to evaluate.
Definition at line 609 of file relic_pp.h.
pp_map_sim_k12
#define pp_map_sim_k12 (R, P, Q, M)
Value:
pp_map_sim_oatep_k12(R, P, Q, M)
Computes a multi-pairing of elliptic curve points defined on an elliptic curve of embedding degree 12. Computes \prod e(P_i, Q_i).
Parameters
[out] R - the result.
[in] P - the first pairing arguments.
[in] Q - the second pairing arguments.
[in] M - the number of pairings to evaluate.
Definition at line 625 of file relic_pp.h.
pp_map_sim_k16
#define pp_map_sim_k16 (R, P, Q, M)
Value:
pp_map_sim_oatep_k16(R, P, Q, M)
Computes a multi-pairing of elliptic curve points defined on an elliptic curve of embedding degree 16. Computes \prod e(P_i, Q_i).
Parameters
[out] R - the result.
[in] P - the first pairing arguments.
[in] Q - the second pairing arguments.
[in] M - the number of pairings to evaluate.
Definition at line 642 of file relic_pp.h.
pp_map_sim_k18
#define pp_map_sim_k18 (R, P, Q, M)
Value:
pp_map_sim_oatep_k18(R, P, Q, M)
Computes a multi-pairing of elliptic curve points defined on an elliptic curve of embedding degree 18. Computes \prod e(P_i, Q_i).
Parameters
[out] R - the result.
[in] P - the first pairing arguments.
[in] Q - the second pairing arguments.
[in] M - the number of pairings to evaluate.
Definition at line 659 of file relic_pp.h.
Function Documentation
pp_map_init()
void pp_map_init (void)
Initializes the pairing over prime fields.
Definition at line 40 of file relic_pp_map.c.
References ep2_curve_init(), ep3_curve_init(), ep4_curve_init(), and ep8_curve_init().
Referenced by core_init().
pp_map_clean()
void pp_map_clean (void)
Finalizes the pairing over prime fields.
Definition at line 47 of file relic_pp_map.c.
References ep2_curve_clean(), ep3_curve_clean(), ep4_curve_clean(), and ep8_curve_clean().
Referenced by core_clean().
pp_add_k1_basic()
void pp_add_k1_basic (fp_t l, fp_t m, ep_t r, const ep_t p, const ep_t q)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 1 using affine coordinates.
Parameters
[out] l - the numerator of the result of the evaluation.
[out] m - the denominator of the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] p - the second point to add.
[in] q - the affine point to evaluate the line function.
Definition at line 44 of file relic_pp_add_k1.c.
References ep_add_slp_basic(), ERR_CAUGHT, fp_cmp(), fp_free, fp_is_zero(), fp_mul, fp_new, fp_null, fp_set_dig(), fp_sub, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_add_k1_projc()
void pp_add_k1_projc (fp_t l, fp_t m, ep_t r, const ep_t p, const ep_t q)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 1 using projective coordinates.
Parameters
[out] l - the numerator of the result of the evaluation.
[out] m - the denominator of the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] p - the second point to add.
[in] q - the affine point to evaluate the line function.
Definition at line 77 of file relic_pp_add_k1.c.
References ERR_CAUGHT, fp_cmp(), fp_dbl, fp_free, fp_is_zero(), fp_mul, fp_new, fp_null, fp_set_dig(), fp_sqr, fp_sub, JACOB, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_add_k2_basic()
void pp_add_k2_basic (fp2_t l, ep_t r, const ep_t p, const ep_t q)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 2 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] p - the second point to add.
[in] q - the affine point to evaluate the line function.
Definition at line 44 of file relic_pp_add_k2.c.
References ep_add_slp_basic(), ep_copy(), ep_free, ep_new, ep_null, ERR_CAUGHT, fp_add, fp_free, fp_mul, fp_neg, fp_new, fp_null, fp_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_add_k2_projc_basic()
void pp_add_k2_projc_basic (fp2_t l, ep_t r, const ep_t p, const ep_t q)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] p - the second point to add.
[in] q - the affine point to evaluate the line function.
Definition at line 75 of file relic_pp_add_k2.c.
References ERR_CAUGHT, fp_add, fp_dbl, fp_free, fp_hlv, fp_mul, fp_new, fp_null, fp_sqr, fp_sub, JACOB, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_add_k2_projc_lazyr()
void pp_add_k2_projc_lazyr (fp2_t l, ep_t r, const ep_t p, const ep_t q)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using projective coordinates and lazy reduction.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] p - the second point to add.
[in] q - the affine point to evaluate the line function.
Definition at line 157 of file relic_pp_add_k2.c.
References dv_free, dv_new, dv_null, ERR_CAUGHT, fp_add, fp_dbl, fp_free, fp_hlv, fp_mul, fp_muln_low(), fp_new, fp_null, fp_rdcn_low(), fp_sqr, fp_sub, fp_subc_low(), JACOB, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_add_k8_basic()
void pp_add_k8_basic (fp8_t l, ep2_t r, const ep2_t q, const ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 8 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 44 of file relic_pp_add_k8.c.
References ep2_add_slp_basic(), ep2_copy(), ep2_curve_is_twist(), ep2_free, ep2_new, ep2_null, ERR_CAUGHT, fp2_free, fp2_mul, fp2_new, fp2_null, fp2_sub, fp_copy(), fp_mul, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_add_k8_projc_basic()
void pp_add_k8_projc_basic (fp8_t l, ep2_t r, const ep2_t q, const ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 8 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 85 of file relic_pp_add_k8.c.
References ep2_curve_is_twist(), ERR_CAUGHT, fp2_add, fp2_copy(), fp2_dbl, fp2_free, fp2_mul, fp2_new, fp2_null, fp2_sqr, fp2_sub, fp_mul, PROJC, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_add_k8_projc_lazyr()
void pp_add_k8_projc_lazyr (fp8_t l, ep2_t r, const ep2_t q, const ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 8 using projective coordinates and lazy reduction.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 178 of file relic_pp_add_k8.c.
References ep2_curve_is_twist(), ERR_CAUGHT, fp2_add, fp2_copy(), fp2_dbl, fp2_free, fp2_mul, fp2_new, fp2_null, fp2_sqr, fp2_sub, fp_mul, PROJC, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_add_k12_basic()
void pp_add_k12_basic (fp12_t l, ep2_t r, const ep2_t q, const ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 44 of file relic_pp_add_k12.c.
References ep2_add_slp_basic(), ep2_copy(), ep2_curve_is_twist(), ep2_free, ep2_new, ep2_null, ERR_CAUGHT, fp2_free, fp2_mul, fp2_new, fp2_null, fp2_sub, fp_mul, fp_neg, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_add_k12_projc_basic()
void pp_add_k12_projc_basic (fp12_t l, ep2_t r, const ep2_t q, const ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 85 of file relic_pp_add_k12.c.
References ep2_curve_is_twist(), ERR_CAUGHT, fp2_add, fp2_free, fp2_mul, fp2_new, fp2_null, fp2_sqr, fp2_sub, fp_mul, fp_neg, PROJC, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_add_k12_projc_lazyr()
void pp_add_k12_projc_lazyr (fp12_t l, ep2_t r, const ep2_t q, const ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using projective coordinates and lazy reduction.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 173 of file relic_pp_add_k12.c.
References dv2_free, dv2_new, dv2_null, ep2_curve_is_twist(), ERR_CAUGHT, fp2_add, fp2_free, fp2_mul, fp2_muln_low(), fp2_new, fp2_null, fp2_rdcn_low(), fp2_sqr, fp2_sub, fp2_subc_low(), fp_mul, fp_neg, PROJC, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_add_lit_k12()
void pp_add_lit_k12 (fp12_t l, ep_t r, const ep_t p, const ep2_t q)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve twist with embedding degree 12 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] p - the second point to add.
[in] q - the affine point to evaluate the line function.
Definition at line 254 of file relic_pp_add_k12.c.
References ep2_curve_is_twist(), ERR_CAUGHT, fp2_neg(), fp_add, fp_free, fp_mul, fp_new, fp_null, fp_sqr, fp_sub, PROJC, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_mil_lit_k12().
pp_add_k16_basic()
void pp_add_k16_basic (fp16_t l, ep4_t r, const ep4_t q, const ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 16 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 44 of file relic_pp_add_k16.c.
References ep4_add_slp_basic(), ep4_copy(), ep4_curve_is_twist(), ep4_free, ep4_new, ep4_null, ERR_CAUGHT, fp4_free, fp4_mul, fp4_new, fp4_null, fp4_sub(), fp_copy(), fp_mul, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_add_k16_projc_basic()
void pp_add_k16_projc_basic (fp16_t l, ep4_t r, const ep4_t q, const ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 16 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 87 of file relic_pp_add_k16.c.
References ep4_curve_is_twist(), ERR_CAUGHT, fp4_add(), fp4_copy(), fp4_dbl(), fp4_free, fp4_mul, fp4_new, fp4_null, fp4_sqr, fp4_sub(), fp_mul, PROJC, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_add_k16_projc_lazyr()
void pp_add_k16_projc_lazyr (fp16_t l, ep4_t r, const ep4_t q, const ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 16 using projective coordinates and lazy reduction.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 184 of file relic_pp_add_k16.c.
References ep4_curve_is_twist(), ERR_CAUGHT, fp4_add(), fp4_copy(), fp4_dbl(), fp4_free, fp4_mul, fp4_new, fp4_null, fp4_sqr, fp4_sub(), fp_mul, PROJC, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_add_lit_k16()
void pp_add_lit_k16 (fp16_t l, ep_t r, const ep_t p, const ep4_t q)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve twist with embedding degree 16 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] p - the second point to add.
[in] q - the affine point to evaluate the line function.
Definition at line 281 of file relic_pp_add_k16.c.
References ep4_curve_is_twist(), ERR_CAUGHT, fp4_neg(), fp_add, fp_free, fp_mul, fp_new, fp_null, fp_sqr, fp_sub, PROJC, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_mil_lit_k16().
pp_add_k18_basic()
void pp_add_k18_basic (fp18_t l, ep3_t r, const ep3_t q, const ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 18 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 44 of file relic_pp_add_k18.c.
References ep3_add_slp_basic(), ep3_copy(), ep3_curve_is_twist(), ep3_free, ep3_new, ep3_null, ERR_CAUGHT, fp3_free, fp3_mul, fp3_new, fp3_null, fp3_sub, fp_mul, fp_neg, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_add_k18_projc_basic()
void pp_add_k18_projc_basic (fp18_t l, ep3_t r, const ep3_t q, const ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 18 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 86 of file relic_pp_add_k18.c.
References ep3_curve_is_twist(), ERR_CAUGHT, fp3_add, fp3_free, fp3_mul, fp3_new, fp3_null, fp3_sqr, fp3_sub, fp_mul, fp_neg, PROJC, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_add_k18_projc_lazyr()
void pp_add_k18_projc_lazyr (fp18_t l, ep3_t r, const ep3_t q, const ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 18 using projective coordinates and lazy reduction.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 176 of file relic_pp_add_k18.c.
References dv3_free, dv3_new, dv3_null, ep3_curve_is_twist(), ERR_CAUGHT, fp3_add, fp3_free, fp3_mul, fp3_muln_low(), fp3_new, fp3_null, fp3_rdcn_low(), fp3_sqr, fp3_sub, fp3_subc_low(), fp_mul, fp_neg, PROJC, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_add_lit_k18()
void pp_add_lit_k18 (fp18_t l, ep_t r, const ep_t p, const ep3_t q)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve twist with embedding degree 18 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] p - the second point to add.
[in] q - the affine point to evaluate the line function.
Definition at line 259 of file relic_pp_add_k18.c.
References ERR_CAUGHT, fp3_neg(), fp_add, fp_free, fp_mul, fp_new, fp_null, fp_sqr, fp_sub, PROJC, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_mil_lit_k18().
pp_add_k24_basic()
void pp_add_k24_basic (fp24_t l, ep4_t r, const ep4_t q, const ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 24 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 42 of file relic_pp_add_k24.c.
References ep4_add_slp_basic(), ep4_copy(), ep4_curve_is_twist(), ep4_free, ep4_new, ep4_null, ERR_CAUGHT, fp4_free, fp4_mul, fp4_mul_art(), fp4_new, fp4_null, fp4_sub(), fp_mul, fp_neg, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_add_k24_projc()
void pp_add_k24_projc (fp24_t l, ep4_t r, const ep4_t q, const ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 24 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 89 of file relic_pp_add_k24.c.
References ep4_curve_is_twist(), ERR_CAUGHT, fp4_add(), fp4_free, fp4_mul, fp4_mul_art(), fp4_new, fp4_null, fp4_sqr, fp4_sub(), fp_mul, fp_neg, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_add_k48_basic()
void pp_add_k48_basic (fp48_t l, ep8_t r, const ep8_t q, const ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 48 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 42 of file relic_pp_add_k48.c.
References ep8_add_slp_basic(), ep8_copy(), ep8_free, ep8_new, ep8_null, ERR_CAUGHT, fp48_zero(), fp8_free, fp8_mul, fp8_new, fp8_null, fp8_sub(), fp_mul, fp_neg, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_add_k48_projc()
void pp_add_k48_projc (fp48_t l, ep8_t r, const ep8_t q, const ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 48 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 84 of file relic_pp_add_k48.c.
References ERR_CAUGHT, fp8_add(), fp8_free, fp8_mul, fp8_new, fp8_null, fp8_sqr, fp8_sub(), fp_mul, fp_neg, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_add_k54_basic()
void pp_add_k54_basic (fp54_t l, fp9_t rx, fp9_t ry, const fp9_t qx, const fp9_t qy, const ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 54 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 107 of file relic_pp_add_k54.c.
References ep9_add_basic(), ERR_CAUGHT, fp54_zero(), fp9_copy(), fp9_free, fp9_mul, fp9_new, fp9_null, fp9_sub(), fp_mul, fp_neg, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_add_k54_projc()
void pp_add_k54_projc (fp54_t l, fp9_t rx, fp9_t ry, fp9_t rz, const fp9_t qx, const fp9_t qy, const ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 54 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 153 of file relic_pp_add_k54.c.
References ERR_CAUGHT, fp9_add(), fp9_free, fp9_mul, fp9_new, fp9_null, fp9_sqr, fp9_sub(), fp_mul, fp_neg, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_dbl_k1_basic()
void pp_dbl_k1_basic (fp_t l, fp_t m, ep_t r, const ep_t p, const ep_t q)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 1 using affine coordinates.
Parameters
[out] l - the numerator of the result of the evaluation.
[out] m - the denominator of the result of the evaluation.
[in,out] r - the resulting point.
[in] p - the point to double.
[in] q - the affine point to evaluate the line function.
Definition at line 47 of file relic_pp_dbl_k1.c.
References ep_dbl_slp_basic(), ERR_CAUGHT, fp_add, fp_free, fp_is_zero(), fp_mul, fp_new, fp_null, fp_set_dig(), fp_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_dbl_k1_projc()
void pp_dbl_k1_projc (fp_t l, fp_t m, ep_t r, const ep_t p, const ep_t q)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 1 using projective coordinates.
Parameters
[out] l - the numerator of the result of the evaluation.
[out] m - the denominator of the result of the evaluation.
[in,out] r - the resulting point.
[in] p - the point to double.
[in] q - the affine point to evaluate the line function.
Definition at line 74 of file relic_pp_dbl_k1.c.
References ep_curve_get_a(), ERR_CAUGHT, fp_add, fp_dbl, fp_free, fp_is_zero(), fp_mul, fp_new, fp_null, fp_set_dig(), fp_sqr, fp_sub, JACOB, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_dbl_k2_basic()
void pp_dbl_k2_basic (fp2_t l, ep_t r, const ep_t p, const ep_t q)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 2 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] p - the point to double.
[in] q - the affine point to evaluate the line function.
Definition at line 44 of file relic_pp_dbl_k2.c.
References ep_copy(), ep_dbl_slp_basic(), ep_free, ep_new, ep_null, ERR_CAUGHT, fp_add, fp_copy(), fp_free, fp_mul, fp_new, fp_null, fp_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_dbl_k2_projc_basic()
void pp_dbl_k2_projc_basic (fp2_t l, ep_t r, const ep_t p, const ep_t q)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 2 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] p - the point to double.
[in] q - the affine point to evaluate the line function.
Definition at line 75 of file relic_pp_dbl_k2.c.
References ERR_CAUGHT, fp_add, fp_dbl, fp_free, fp_mul, fp_new, fp_null, fp_sqr, fp_sub, JACOB, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_dbl_k2_projc_lazyr()
void pp_dbl_k2_projc_lazyr (fp2_t l, ep_t r, const ep_t p, const ep_t q)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 2 using projective coordinates and lazy reduction.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] p - the point to double.
[in] q - the affine point to evaluate the line function.
Definition at line 164 of file relic_pp_dbl_k2.c.
References dv_free, dv_new, dv_null, ERR_CAUGHT, fp_add, fp_addc_low(), fp_dbl, fp_free, fp_mul, fp_muln_low(), fp_new, fp_null, fp_rdcn_low(), fp_sqr, fp_sqrn_low(), fp_sub, fp_subc_low(), fp_subm_low(), JACOB, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_dbl_k8_basic()
void pp_dbl_k8_basic (fp8_t l, ep2_t r, const ep2_t q, const ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 8 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 44 of file relic_pp_dbl_k8.c.
References ep2_copy(), ep2_curve_is_twist(), ep2_dbl_slp_basic(), ep2_free, ep2_new, ep2_null, ERR_CAUGHT, fp2_free, fp2_mul, fp2_new, fp2_null, fp2_sub, fp_copy(), fp_mul, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_dbl_k8_projc_basic()
void pp_dbl_k8_projc_basic (fp8_t l, ep2_t r, const ep2_t q, const ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 8 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 153 of file relic_pp_dbl_k8.c.
References ep2_curve_is_twist(), ep2_curve_mul_a(), ERR_CAUGHT, fp2_add, fp2_dbl, fp2_free, fp2_mul, fp2_new, fp2_null, fp2_sqr, fp2_sub, fp_mul, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_dbl_k8_projc_lazyr()
void pp_dbl_k8_projc_lazyr (fp8_t l, ep2_t r, const ep2_t q, const ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 8 using projective coordinates and lazy reduction.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 243 of file relic_pp_dbl_k8.c.
References dv2_free, dv2_new, dv2_null, ep2_curve_is_twist(), ep2_curve_mul_a(), ERR_CAUGHT, fp2_add, fp2_dbl, fp2_free, fp2_mul, fp2_new, fp2_null, fp2_sqr, fp2_sub, fp_mul, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_dbl_k12_basic()
void pp_dbl_k12_basic (fp12_t l, ep2_t r, const ep2_t q, const ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 44 of file relic_pp_dbl_k12.c.
References ep2_copy(), ep2_curve_is_twist(), ep2_dbl_slp_basic(), ep2_free, ep2_new, ep2_null, ERR_CAUGHT, fp2_free, fp2_mul, fp2_new, fp2_null, fp2_sub, fp_copy(), fp_mul, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_dbl_k12_projc_basic()
void pp_dbl_k12_projc_basic (fp12_t l, ep2_t r, const ep2_t q, const ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 84 of file relic_pp_dbl_k12.c.
References ep2_curve_get_b(), ep2_curve_is_twist(), ep_curve_opt_b(), ERR_CAUGHT, fp2_add, fp2_dbl, fp2_free, fp2_mul, fp2_new, fp2_null, fp2_sqr, fp2_sub, fp_add, fp_hlv, fp_mul, fp_sub, PROJC, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, RLC_TRY, and RLC_TWO.
pp_dbl_k12_projc_lazyr()
void pp_dbl_k12_projc_lazyr (fp12_t l, ep2_t r, const ep2_t q, const ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using projective coordinates and lazy reduction.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 237 of file relic_pp_dbl_k12.c.
References dv2_free, dv2_new, dv2_null, ep2_curve_get_b(), ep2_curve_is_twist(), ep_curve_opt_b(), ERR_CAUGHT, fp2_add, fp2_addd_low(), fp2_dbl, fp2_free, fp2_mul, fp2_new, fp2_null, fp2_rdcn_low(), fp2_sqr, fp2_sqrn_low(), fp2_sub, fp2_subc_low(), fp_add, fp_hlv, fp_mul, fp_sub, PROJC, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, RLC_TRY, and RLC_TWO.
pp_dbl_k16_basic()
void pp_dbl_k16_basic (fp16_t l, ep4_t r, const ep4_t q, const ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 16 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 44 of file relic_pp_dbl_k16.c.
References ep4_copy(), ep4_curve_is_twist(), ep4_dbl_slp_basic(), ep4_free, ep4_new, ep4_null, ERR_CAUGHT, fp4_free, fp4_mul, fp4_new, fp4_null, fp4_sub(), fp_copy(), fp_mul, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_dbl_k16_projc_basic()
void pp_dbl_k16_projc_basic (fp16_t l, ep4_t r, const ep4_t q, const ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 16 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 86 of file relic_pp_dbl_k16.c.
References ep4_curve_is_twist(), ep4_curve_mul_a(), ERR_CAUGHT, fp4_add(), fp4_dbl(), fp4_free, fp4_mul, fp4_new, fp4_null, fp4_sqr, fp4_sub(), fp_mul, PROJC, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_dbl_k16_projc_lazyr()
void pp_dbl_k16_projc_lazyr (fp16_t l, ep4_t r, const ep4_t q, const ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 16 using projective coordinates and lazy reduction.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 182 of file relic_pp_dbl_k16.c.
References dv4_free, dv4_new, dv4_null, ep4_curve_is_twist(), ep4_curve_mul_a(), ERR_CAUGHT, fp4_add(), fp4_dbl(), fp4_free, fp4_mul, fp4_new, fp4_null, fp4_sqr, fp4_sub(), fp_mul, PROJC, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_dbl_k18_basic()
void pp_dbl_k18_basic (fp18_t l, ep3_t r, const ep3_t q, const ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 18 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 44 of file relic_pp_dbl_k18.c.
References ep3_copy(), ep3_curve_is_twist(), ep3_dbl_slp_basic(), ep3_free, ep3_new, ep3_null, ERR_CAUGHT, fp3_free, fp3_mul, fp3_new, fp3_null, fp3_sub, fp_copy(), fp_mul, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_dbl_k18_projc_basic()
void pp_dbl_k18_projc_basic (fp18_t l, ep3_t r, const ep3_t q, const ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 18 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 85 of file relic_pp_dbl_k18.c.
References ep3_curve_get_b(), ep3_curve_is_twist(), ERR_CAUGHT, fp3_add, fp3_dbl, fp3_free, fp3_mul, fp3_new, fp3_null, fp3_sqr, fp3_sub, fp_mul, PROJC, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_dbl_k18_projc_lazyr()
void pp_dbl_k18_projc_lazyr (fp18_t l, ep3_t r, const ep3_t q, const ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 18 using projective coordinates and lazy reduction.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 189 of file relic_pp_dbl_k18.c.
References dv2_free, dv2_new, dv2_null, ep3_curve_get_b(), ep3_curve_is_twist(), ERR_CAUGHT, fp3_add, fp3_dbl, fp3_free, fp3_mul, fp3_new, fp3_null, fp3_sqr, fp3_sub, fp_mul, PROJC, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_dbl_k24_basic()
void pp_dbl_k24_basic (fp24_t l, ep4_t r, const ep4_t q, const ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 24 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 42 of file relic_pp_dbl_k24.c.
References ep4_copy(), ep4_curve_is_twist(), ep4_dbl_slp_basic(), ep4_free, ep4_new, ep4_null, ERR_CAUGHT, fp24_zero(), fp2_free, fp4_mul, fp4_mul_art(), fp4_new, fp4_null, fp4_sub(), fp_copy(), fp_mul, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_dbl_k24_projc()
void pp_dbl_k24_projc (fp24_t l, ep4_t r, const ep4_t q, const ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 24 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 89 of file relic_pp_dbl_k24.c.
References ep4_curve_get_b(), ep4_curve_is_twist(), ERR_CAUGHT, fp4_add(), fp4_dbl(), fp4_free, fp4_mul, fp4_mul_art(), fp4_new, fp4_null, fp4_sqr, fp4_sub(), fp_mul, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_dbl_k48_basic()
void pp_dbl_k48_basic (fp48_t l, ep8_t r, const ep8_t q, const ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 48 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 42 of file relic_pp_dbl_k48.c.
References ep8_copy(), ep8_dbl_slp_basic(), ep8_free, ep8_new, ep8_null, ERR_CAUGHT, fp48_zero(), fp8_free, fp8_mul, fp8_new, fp8_null, fp8_sub(), fp_copy(), fp_mul, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_dbl_k48_projc()
void pp_dbl_k48_projc (fp48_t l, ep8_t r, const ep8_t q, const ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 48 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 83 of file relic_pp_dbl_k48.c.
References ep8_curve_get_b(), ERR_CAUGHT, fp8_add(), fp8_dbl(), fp8_free, fp8_mul, fp8_new, fp8_null, fp8_sqr, fp8_sub(), fp_mul, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_dbl_k54_basic()
void pp_dbl_k54_basic (fp54_t l, fp9_t rx, fp9_t ry, const ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 54 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 101 of file relic_pp_dbl_k54.c.
References ep9_dbl_basic(), ERR_CAUGHT, fp54_zero(), fp9_copy(), fp9_free, fp9_mul, fp9_new, fp9_null, fp9_sub(), fp_copy(), fp_mul, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_dbl_k54_projc()
void pp_dbl_k54_projc (fp54_t l, fp9_t rx, fp9_t ry, fp9_t rz, const ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 54 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 146 of file relic_pp_dbl_k54.c.
References ep_curve_get_b(), ERR_CAUGHT, fp9_add(), fp9_dbl(), fp9_free, fp9_mul, fp9_new, fp9_null, fp9_sqr, fp9_sub(), fp9_zero(), fp_copy(), fp_mul, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_dbl_lit_k12()
void pp_dbl_lit_k12 (fp12_t l, ep_t r, const ep_t p, const ep2_t q)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve twist with embedding degree 12 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] p - the point to double.
[in] q - the affine point to evaluate the line function.
Definition at line 405 of file relic_pp_dbl_k12.c.
References ep2_curve_is_twist(), ep_curve_get_b(), ERR_CAUGHT, fp2_add, fp2_dbl, fp_add, fp_dbl, fp_free, fp_mul, fp_new, fp_null, fp_sqr, fp_sub, fp_zero(), PROJC, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_mil_lit_k12().
pp_dbl_lit_k16()
void pp_dbl_lit_k16 (fp16_t l, ep_t r, const ep_t p, const ep4_t q)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve twist with embedding degree 16 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] p - the point to double.
[in] q - the affine point to evaluate the line function.
Definition at line 284 of file relic_pp_dbl_k16.c.
References ep4_curve_is_twist(), ep_curve_get_b(), ERR_CAUGHT, fp4_add(), fp4_dbl(), fp_add, fp_dbl, fp_free, fp_mul, fp_new, fp_null, fp_sqr, fp_sub, PROJC, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_mil_lit_k16().
pp_dbl_lit_k18()
void pp_dbl_lit_k18 (fp18_t l, ep_t r, const ep_t p, const ep3_t q)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve twist with embedding degree 18 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] p - the point to double.
[in] q - the affine point to evaluate the line function.
Definition at line 300 of file relic_pp_dbl_k18.c.
References ep_curve_get_b(), ERR_CAUGHT, fp3_add, fp3_dbl, fp_add, fp_dbl, fp_free, fp_mul, fp_new, fp_null, fp_sqr, fp_sub, PROJC, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_mil_lit_k18().
pp_exp_k1()
void pp_exp_k1 (fp_t c, fp_t a)
Computes the final exponentiation for a pairing defined over curves of embedding degree 1. Computes c = a^(p - 1)/r.
Parameters
[out] c - the result.
[in] a - the extension field element to exponentiate.
Definition at line 40 of file relic_pp_exp_k1.c.
References bn_div(), bn_free, bn_new, bn_null, bn_read_raw(), bn_sub_dig(), ep_curve_get_ord(), ERR_CAUGHT, fp_exp, fp_prime_get(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
Referenced by gt_rand(), pp_map_sim_tatep_k1(), and pp_map_tatep_k1().
pp_exp_k2()
void pp_exp_k2 (fp2_t c, fp2_t a)
Computes the final exponentiation for a pairing defined over curves of embedding degree 2. Computes c = a^(p^2 - 1)/r.
Parameters
[out] c - the result.
[in] a - the extension field element to exponentiate.
Definition at line 40 of file relic_pp_exp_k2.c.
References bn_add_dig(), bn_div(), bn_free, bn_new, bn_null, dv_copy(), ep_curve_get_ord(), ERR_CAUGHT, fp2_conv_cyc(), fp2_exp_cyc(), fp_prime_get(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_POS, RLC_THROW, and RLC_TRY.
Referenced by gt_rand(), pp_map_sim_tatep_k2(), and pp_map_tatep_k2().
pp_exp_k8()
void pp_exp_k8 (fp8_t c, fp8_t a)
Computes the final exponentiation for a pairing defined over curves of embedding degree 8. Computes c = a^(p^8 - 1)/r.
Parameters
[out] c - the result.
[in] a - the extension field element to exponentiate.
Definition at line 40 of file relic_pp_exp_k8.c.
References bn_add_dig(), bn_free, bn_lsh(), bn_new, bn_null, bn_rsh(), bn_set_dig(), ERR_CAUGHT, fp8_conv_cyc(), fp8_copy(), fp8_exp_cyc(), fp8_frb(), fp8_free, fp8_inv_cyc(), fp8_mul, fp8_new, fp8_null, fp8_sqr_cyc(), fp_prime_get_par(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by gt_rand(), pp_map_oatep_k8(), and pp_map_sim_oatep_k8().
pp_exp_k12()
void pp_exp_k12 (fp12_t c, fp12_t a)
Computes the final exponentiation for a pairing defined over curves of embedding degree 12. Computes c = a^(p^12 - 1)/r.
Parameters
[out] c - the result.
[in] a - the extension field element to exponentiate.
Definition at line 340 of file relic_pp_exp_k12.c.
References EP_B12, EP_BN, ep_curve_is_pairf(), ep_param_get(), pp_exp_b12(), pp_exp_bn(), pp_exp_sm9(), and SM9_P256.
Referenced by gt_rand(), pp_map_oatep_k12(), pp_map_sim_oatep_k12(), pp_map_sim_tatep_k12(), and pp_map_tatep_k12().
pp_exp_k16()
void pp_exp_k16 (fp16_t c, fp16_t a)
Computes the final exponentiation for a pairing defined over curves of embedding degree 16. Computes c = a^(p^16 - 1)/r.
Parameters
[out] c - the result.
[in] a - the extension field element to exponentiate.
Definition at line 436 of file relic_pp_exp_k16.c.
References EP_AFG16, ep_curve_is_pairf(), EP_FM16, EP_K16, pp_exp_afg16(), pp_exp_fm16(), and pp_exp_kss().
Referenced by gt_rand(), pp_map_oatep_k16(), pp_map_sim_oatep_k16(), pp_map_sim_tatep_k16(), and pp_map_tatep_k16().
pp_exp_k18()
void pp_exp_k18 (fp18_t c, fp18_t a)
Computes the final exponentiation for a pairing defined over curves of embedding degree 18. Computes c = a^(p^18 - 1)/r.
Parameters
[out] c - the result.
[in] a - the extension field element to exponentiate.
Definition at line 376 of file relic_pp_exp_k18.c.
References ep_curve_is_pairf(), EP_FM18, EP_K18, EP_SG18, pp_exp_fm(), pp_exp_kss(), and pp_exp_sg().
Referenced by gt_rand(), pp_map_oatep_k18(), pp_map_sim_oatep_k18(), pp_map_sim_tatep_k18(), and pp_map_tatep_k18().
pp_exp_k24()
void pp_exp_k24 (fp24_t c, fp24_t a)
Computes the final exponentiation for a pairing defined over curves of embedding degree 24. Computes c = a^(p^24 - 1)/r.
Parameters
[out] c - the result.
[in] a - the extension field element to exponentiate.
Definition at line 40 of file relic_pp_exp_k24.c.
References bn_free, bn_new, bn_null, bn_sign(), ERR_CAUGHT, fp24_conv_cyc(), fp24_exp_cyc_sps(), fp24_frb(), fp24_free, fp24_inv_cyc(), fp24_mul, fp24_new, fp24_null, fp24_sqr_cyc, fp_prime_get_par(), fp_prime_get_par_sps(), RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_POS, RLC_THROW, and RLC_TRY.
Referenced by gt_rand(), pp_map_k24(), and pp_map_sim_k24().
pp_exp_k48()
void pp_exp_k48 (fp48_t c, fp48_t a)
Computes the final exponentiation for a pairing defined over curves of embedding degree 48. Computes c = a^(p^48 - 1)/r.
Parameters
[out] c - the result.
[in] a - the extension field element to exponentiate.
Definition at line 40 of file relic_pp_exp_k48.c.
References bn_free, bn_new, bn_null, bn_sign(), ERR_CAUGHT, fp48_conv_cyc(), fp48_exp_cyc_sps(), fp48_frb(), fp48_free, fp48_inv_cyc(), fp48_mul, fp48_new, fp48_null, fp48_sqr_cyc, fp_prime_get_par(), fp_prime_get_par_sps(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by gt_rand(), pp_map_k48(), and pp_map_sim_k48().
pp_exp_k54()
void pp_exp_k54 (fp54_t c, fp54_t a)
Computes the final exponentiation for a pairing defined over curves of embedding degree 54. Computes c = a^(p^54 - 1)/r.
Parameters
[out] c - the result.
[in] a - the extension field element to exponentiate.
Definition at line 41 of file relic_pp_exp_k54.c.
References bn_free, bn_new, bn_null, bn_sign(), ERR_CAUGHT, fp54_conv_cyc(), fp54_copy(), fp54_exp_cyc_sps(), fp54_frb(), fp54_free, fp54_inv_cyc(), fp54_mul, fp54_new, fp54_null, fp54_sqr, fp54_sqr_cyc, fp_prime_get_par(), fp_prime_get_par_sps(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_map_k54().
pp_norm_k1()
void pp_norm_k1 (ep_t c, const ep_t a)
Normalizes the accumulator point used inside pairing computation defined over curves of embedding degree 1.
Parameters
[out] r - the resulting point.
[in] p - the point to normalize.
Definition at line 42 of file relic_pp_norm.c.
References ep_norm().
pp_norm_k2()
void pp_norm_k2 (ep_t c, const ep_t a)
Normalizes the accumulator point used inside pairing computation defined over curves of embedding degree 2.
Parameters
[out] r - the resulting point.
[in] p - the point to normalize.
Definition at line 46 of file relic_pp_norm.c.
References ep_norm().
pp_norm_k8()
void pp_norm_k8 (ep2_t c, const ep2_t a)
Normalizes the accumulator point used inside pairing computation defined over curves of embedding degree 8.
Parameters
[out] r - the resulting point.
[in] p - the point to normalize.
Definition at line 50 of file relic_pp_norm.c.
References BASIC, ep2_copy(), ep2_is_infty(), ep2_set_infty(), fp2_inv(), fp2_mul, and fp2_set_dig().
pp_norm_k12()
void pp_norm_k12 (ep2_t c, const ep2_t a)
Normalizes the accumulator point used inside pairing computation defined over curves of embedding degree 12.
Parameters
[out] r - the resulting point.
[in] p - the point to normalize.
Definition at line 70 of file relic_pp_norm.c.
References BASIC, ep2_copy(), ep2_is_infty(), ep2_set_infty(), fp2_inv(), fp2_mul, and fp2_set_dig().
pp_norm_k16()
void pp_norm_k16 (ep4_t c, const ep4_t a)
Normalizes the accumulator point used inside pairing computation defined over curves of embedding degree 16.
Parameters
[out] r - the resulting point.
[in] p - the point to normalize.
Definition at line 89 of file relic_pp_norm.c.
References BASIC, ep4_copy(), ep4_is_infty(), ep4_set_infty(), ep_curve_opt_b(), fp4_inv(), fp4_mul, fp4_set_dig(), and RLC_ZERO.
pp_norm_k18()
void pp_norm_k18 (ep3_t c, const ep3_t a)
Normalizes the accumulator point used inside pairing computation defined over curves of embedding degree 18.
Parameters
[out] r - the resulting point.
[in] p - the point to normalize.
Definition at line 111 of file relic_pp_norm.c.
References BASIC, ep3_copy(), ep3_is_infty(), ep3_set_infty(), fp3_inv(), fp3_mul, and fp3_set_dig().
Referenced by pp_fin_k18_oatep().
pp_norm_k24()
void pp_norm_k24 (ep4_t c, const ep4_t a)
Normalizes the accumulator point used inside pairing computation defined over curves of embedding degree 24.
Parameters
[out] r - the resulting point.
[in] p - the point to normalize.
Definition at line 130 of file relic_pp_norm.c.
References BASIC, ep4_copy(), ep4_is_infty(), ep4_set_infty(), fp4_inv(), fp4_mul, and fp4_set_dig().
pp_norm_k48()
void pp_norm_k48 (ep8_t c, const ep8_t a)
Normalizes the accumulator point used inside pairing computation defined over curves of embedding degree 48.
Parameters
[out] r - the resulting point.
[in] p - the point to normalize.
Definition at line 149 of file relic_pp_norm.c.
References BASIC, ep8_copy(), ep8_is_infty(), ep8_set_infty(), fp8_inv(), fp8_mul, and fp8_set_dig().
pp_map_tatep_k1()
void pp_map_tatep_k1 (fp_t r, const ep_t p, const ep_t q)
Computes the Tate pairing of two points in a parameterized elliptic curve with embedding degree 1.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 106 of file relic_pp_map_k1.c.
References bn_free, bn_new, bn_null, ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, fp_set_dig(), pp_exp_k1(), pp_mil_k1(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_map_sim_tatep_k1()
void pp_map_sim_tatep_k1 (fp_t r, const ep_t * p, const ep_t * q, int m)
Computes the Tate multi-pairing in a parameterized elliptic curve with embedding degree 1.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 140 of file relic_pp_map_k1.c.
References bn_free, bn_new, bn_null, ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp_set_dig(), pp_exp_k1(), pp_mil_k1(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
pp_map_tatep_k2()
void pp_map_tatep_k2 (fp2_t r, const ep_t p, const ep_t q)
Computes the Tate pairing of two points in a parameterized elliptic curve with embedding degree 2.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 161 of file relic_pp_map_k2.c.
References bn_free, bn_new, bn_null, bn_sub_dig(), ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, fp2_set_dig(), pp_exp_k2(), pp_mil_k2(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_map_sim_tatep_k2()
void pp_map_sim_tatep_k2 (fp2_t r, const ep_t * p, const ep_t * q, int m)
Computes the Tate multi-pairing in a parameterized elliptic curve with embedding degree 2.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 197 of file relic_pp_map_k2.c.
References bn_free, bn_new, bn_null, bn_sub_dig(), ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp2_set_dig(), pp_exp_k2(), pp_mil_k2(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
pp_map_weilp_k1()
void pp_map_weilp_k1 (fp_t r, const ep_t p, const ep_t q)
Computes the Weil pairing of two points in a parameterized elliptic curve with embedding degree 1.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 197 of file relic_pp_map_k1.c.
References bn_free, bn_new, bn_null, ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, fp_cmp(), fp_free, fp_inv, fp_mul, fp_neg, fp_new, fp_null, fp_set_dig(), pp_mil_k1(), RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_map_sim_weilp_k1()
void pp_map_sim_weilp_k1 (fp_t r, const ep_t * p, const ep_t * q, int m)
Computes the Weil multi-pairing in a parameterized elliptic curve with embedding degree 1.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 250 of file relic_pp_map_k1.c.
References bn_free, bn_new, bn_null, bn_sub_dig(), ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp_free, fp_inv, fp_mul, fp_new, fp_null, fp_set_dig(), pp_mil_k1(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
pp_map_weilp_k2()
void pp_map_weilp_k2 (fp2_t r, const ep_t p, const ep_t q)
Computes the Weil pairing of two points in a parameterized elliptic curve with embedding degree 2.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 255 of file relic_pp_map_k2.c.
References bn_free, bn_new, bn_null, bn_sub_dig(), ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, fp2_free, fp2_inv(), fp2_inv_cyc(), fp2_mul, fp2_new, fp2_null, fp2_set_dig(), pp_mil_k2(), pp_mil_lit_k2(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_map_sim_weilp_k2()
void pp_map_sim_weilp_k2 (fp2_t r, const ep_t * p, const ep_t * q, int m)
Computes the Weil multi-pairing in a parameterized elliptic curve with embedding degree 2.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 309 of file relic_pp_map_k2.c.
References bn_free, bn_new, bn_null, bn_sub_dig(), ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp2_free, fp2_inv(), fp2_inv_cyc(), fp2_mul, fp2_new, fp2_null, fp2_set_dig(), pp_mil_k2(), pp_mil_lit_k2(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
pp_map_oatep_k8()
void pp_map_oatep_k8 (fp8_t r, const ep_t p, const ep2_t q)
Computes the optimal ate pairing of two points in a parameterized elliptic curve with embedding degree 8.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 124 of file relic_pp_map_k8.c.
References bn_free, bn_new, bn_null, bn_sign(), ep2_free, ep2_is_infty(), ep2_neg(), ep2_new, ep2_norm(), ep2_null, ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, fp8_inv_cyc(), fp8_set_dig(), fp_prime_get_par(), pp_exp_k8(), pp_mil_k8(), RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
pp_map_sim_oatep_k8()
void pp_map_sim_oatep_k8 (fp8_t r, const ep_t * p, const ep2_t * q, int m)
Computes the optimal ate multi-pairing in a parameterized elliptic curve with embedding degree 8.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 167 of file relic_pp_map_k8.c.
References bn_free, bn_new, bn_null, bn_sign(), ep2_is_infty(), ep2_neg(), ep2_new, ep2_norm(), ep2_null, ep4_free, ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp8_inv_cyc(), fp8_set_dig(), fp_prime_get_par(), pp_exp_k8(), pp_mil_k8(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.
pp_map_tatep_k12()
void pp_map_tatep_k12 (fp12_t r, const ep_t p, const ep2_t q)
Computes the Tate pairing of two points in a parameterized elliptic curve with embedding degree 12.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 239 of file relic_pp_map_k12.c.
References bn_free, bn_new, bn_null, ep2_free, ep2_is_infty(), ep2_new, ep2_norm(), ep2_null, ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, fp12_set_dig(), pp_exp_k12(), pp_mil_lit_k12(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_map_sim_tatep_k12()
void pp_map_sim_tatep_k12 (fp12_t r, const ep_t * p, const ep2_t * q, int m)
Computes the Tate multi-pairing in a parameterized elliptic curve with embedding degree 12.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 276 of file relic_pp_map_k12.c.
References bn_free, bn_new, bn_null, ep2_free, ep2_is_infty(), ep2_new, ep2_norm(), ep2_null, ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp12_set_dig(), pp_exp_k12(), pp_mil_lit_k12(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
pp_map_weilp_k12()
void pp_map_weilp_k12 (fp12_t r, const ep_t p, const ep2_t q)
Computes the Weil pairing of two points in a parameterized elliptic curve with embedding degree 12.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 333 of file relic_pp_map_k12.c.
References bn_free, bn_new, bn_null, bn_sub_dig(), ep2_free, ep2_is_infty(), ep2_new, ep2_norm(), ep2_null, ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, fp12_free, fp12_inv(), fp12_inv_cyc(), fp12_mul, fp12_new, fp12_null, fp12_set_dig(), pp_mil_k12(), pp_mil_lit_k12(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_map_sim_weilp_k12()
void pp_map_sim_weilp_k12 (fp12_t r, const ep_t * p, const ep2_t * q, int m)
Computes the Weil multi-pairing in a parameterized elliptic curve with embedding degree 12.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 387 of file relic_pp_map_k12.c.
References bn_free, bn_new, bn_null, bn_sub_dig(), ep2_free, ep2_is_infty(), ep2_new, ep2_norm(), ep2_null, ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp12_free, fp12_inv(), fp12_inv_cyc(), fp12_mul, fp12_new, fp12_null, fp12_set_dig(), pp_mil_k12(), pp_mil_lit_k12(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
pp_map_oatep_k12()
void pp_map_oatep_k12 (fp12_t r, const ep_t p, const ep2_t q)
Computes the optimal ate pairing of two points in a parameterized elliptic curve with embedding degree 12.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 463 of file relic_pp_map_k12.c.
References bn_add_dig(), bn_free, bn_mul_dig(), bn_new, bn_null, bn_sign(), ep2_free, ep2_is_infty(), ep2_neg(), ep2_new, ep2_norm(), ep2_null, EP_B12, EP_BN, ep_curve_is_pairf(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, fp12_inv_cyc(), fp12_set_dig(), fp_prime_get_par(), pp_exp_k12(), pp_fin_k12_oatep(), pp_mil_k12(), RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
pp_map_sim_oatep_k12()
void pp_map_sim_oatep_k12 (fp12_t r, const ep_t * p, const ep2_t * q, int m)
Computes the optimal ate multi-pairing in a parameterized elliptic curve with embedding degree 12.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 523 of file relic_pp_map_k12.c.
References bn_add_dig(), bn_free, bn_mul_dig(), bn_new, bn_null, bn_sign(), ep2_free, ep2_is_infty(), ep2_neg(), ep2_new, ep2_norm(), ep2_null, EP_B12, EP_BN, ep_curve_is_pairf(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp12_inv_cyc(), fp12_set_dig(), fp_prime_get_par(), pp_exp_k12(), pp_fin_k12_oatep(), pp_mil_k12(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.
pp_map_tatep_k16()
void pp_map_tatep_k16 (fp16_t r, const ep_t p, const ep4_t q)
Computes the Tate pairing of two points in a parameterized elliptic curve with embedding degree 16.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 249 of file relic_pp_map_k16.c.
References bn_free, bn_new, bn_null, ep4_free, ep4_is_infty(), ep4_new, ep4_norm(), ep4_null, ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, fp16_set_dig(), pp_exp_k16(), pp_mil_lit_k16(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_map_sim_tatep_k16()
void pp_map_sim_tatep_k16 (fp16_t r, const ep_t * p, const ep4_t * q, int m)
Computes the Tate multi-pairing in a parameterized elliptic curve with embedding degree 16.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 286 of file relic_pp_map_k16.c.
References bn_free, bn_new, bn_null, ep4_free, ep4_is_infty(), ep4_new, ep4_norm(), ep4_null, ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp16_set_dig(), pp_exp_k16(), pp_mil_lit_k16(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
pp_map_weilp_k16()
void pp_map_weilp_k16 (fp16_t r, const ep_t p, const ep4_t q)
Computes the Weil pairing of two points in a parameterized elliptic curve with embedding degree 16.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 344 of file relic_pp_map_k16.c.
References bn_free, bn_new, bn_null, bn_sub_dig(), ep4_free, ep4_is_infty(), ep4_new, ep4_norm(), ep4_null, ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, fp16_free, fp16_inv(), fp16_inv_cyc(), fp16_mul, fp16_new, fp16_null, fp16_set_dig(), fp16_sqr, pp_mil_k16(), pp_mil_lit_k16(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_map_sim_weilp_k16()
void pp_map_sim_weilp_k16 (fp16_t r, const ep_t * p, const ep4_t * q, int m)
Computes the Weil multi-pairing in a parameterized elliptic curve with embedding degree 16.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 400 of file relic_pp_map_k16.c.
References bn_free, bn_new, bn_null, bn_sub_dig(), ep4_free, ep4_is_infty(), ep4_new, ep4_norm(), ep4_null, ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp16_free, fp16_inv(), fp16_inv_cyc(), fp16_mul, fp16_new, fp16_null, fp16_set_dig(), fp16_sqr, pp_mil_k16(), pp_mil_lit_k16(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
pp_map_oatep_k16()
void pp_map_oatep_k16 (fp16_t r, const ep_t p, const ep4_t q)
Computes the optimal ate pairing of two points in a parameterized elliptic curve with embedding degree 16.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 477 of file relic_pp_map_k16.c.
References bn_free, bn_new, bn_null, bn_sign(), ep4_free, ep4_is_infty(), ep4_neg(), ep4_new, ep4_norm(), ep4_null, EP_AFG16, ep_curve_is_pairf(), EP_FM16, ep_free, ep_is_infty(), EP_K16, ep_new, ep_norm(), ep_null, ERR_CAUGHT, fp16_frb(), fp16_inv_cyc(), fp16_set_dig(), fp_prime_get_par(), pp_exp_k16(), pp_fin_k16_oatep(), pp_mil_k16(), RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
pp_map_sim_oatep_k16()
void pp_map_sim_oatep_k16 (fp16_t r, const ep_t * p, const ep4_t * q, int m)
Computes the optimal ate multi-pairing in a parameterized elliptic curve with embedding degree 16.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 538 of file relic_pp_map_k16.c.
References bn_free, bn_new, bn_null, bn_sign(), ep4_free, ep4_is_infty(), ep4_neg(), ep4_new, ep4_norm(), ep4_null, EP_AFG16, ep_curve_is_pairf(), EP_FM16, ep_free, ep_is_infty(), EP_K16, ep_new, ep_norm(), ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp16_frb(), fp16_inv_cyc(), fp16_set_dig(), fp_prime_get_par(), pp_exp_k16(), pp_fin_k16_oatep(), pp_mil_k16(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.
pp_map_tatep_k18()
void pp_map_tatep_k18 (fp18_t r, const ep_t p, const ep3_t q)
Computes the Tate pairing of two points in a parameterized elliptic curve with embedding degree 18.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 269 of file relic_pp_map_k18.c.
References bn_free, bn_new, bn_null, core_get(), ep3_frb(), ep3_free, ep3_is_infty(), ep3_new, ep3_norm(), ep3_null, ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, fp18_set_dig(), fp3_mul, pp_exp_k18(), pp_mil_lit_k18(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_map_sim_tatep_k18()
void pp_map_sim_tatep_k18 (fp18_t r, const ep_t * p, const ep3_t * q, int m)
Computes the Tate multi-pairing in a parameterized elliptic curve with embedding degree 18.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 308 of file relic_pp_map_k18.c.
References bn_free, bn_new, bn_null, core_get(), ep3_frb(), ep3_free, ep3_is_infty(), ep3_new, ep3_norm(), ep3_null, ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp18_set_dig(), fp3_mul, pp_exp_k18(), pp_mil_lit_k18(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
pp_map_weilp_k18()
void pp_map_weilp_k18 (fp18_t r, const ep_t p, const ep3_t q)
Computes the Weil pairing of two points in a parameterized elliptic curve with embedding degree 18.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 368 of file relic_pp_map_k18.c.
References bn_free, bn_new, bn_null, bn_sub_dig(), core_get(), ep3_frb(), ep3_free, ep3_is_infty(), ep3_new, ep3_norm(), ep3_null, ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, fp18_free, fp18_inv(), fp18_inv_cyc(), fp18_mul, fp18_new, fp18_null, fp18_set_dig(), fp18_sqr, fp3_mul, pp_mil_k18(), pp_mil_lit_k18(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_map_sim_weilp_k18()
void pp_map_sim_weilp_k18 (fp18_t r, const ep_t * p, const ep3_t * q, int m)
Computes the Weil multi-pairing in a parameterized elliptic curve with embedding degree 18.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 426 of file relic_pp_map_k18.c.
References bn_free, bn_new, bn_null, bn_sub_dig(), core_get(), ep3_frb(), ep3_free, ep3_is_infty(), ep3_new, ep3_norm(), ep3_null, ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp18_free, fp18_inv(), fp18_inv_cyc(), fp18_mul, fp18_new, fp18_null, fp18_set_dig(), fp18_sqr, fp3_mul, pp_mil_k18(), pp_mil_lit_k18(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
pp_map_oatep_k18()
void pp_map_oatep_k18 (fp18_t r, const ep_t p, const ep3_t q)
Computes the optimal ate pairing of two points in a parameterized elliptic curve with embedding degree 18.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 507 of file relic_pp_map_k18.c.
References bn_free, bn_new, bn_null, bn_sign(), ep3_free, ep3_is_infty(), ep3_neg(), ep3_new, ep3_norm(), ep3_null, ep_curve_is_pairf(), EP_FM18, ep_free, ep_is_infty(), EP_K18, ep_new, ep_norm(), ep_null, EP_SG18, ERR_CAUGHT, fp18_inv_cyc(), fp18_set_dig(), fp_prime_get_par(), pp_exp_k18(), pp_fin_k18_oatep(), pp_mil_k18(), RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
pp_map_sim_oatep_k18()
void pp_map_sim_oatep_k18 (fp18_t r, const ep_t * p, const ep3_t * q, int m)
Computes the optimal ate multi-pairing in a parameterized elliptic curve with embedding degree 18.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 577 of file relic_pp_map_k18.c.
References bn_free, bn_new, bn_null, bn_sign(), ep3_free, ep3_is_infty(), ep3_neg(), ep3_new, ep3_norm(), ep3_null, ep_curve_is_pairf(), EP_FM18, ep_free, ep_is_infty(), EP_K18, ep_new, ep_norm(), ep_null, EP_SG18, ERR_CAUGHT, ERR_NO_MEMORY, fp18_inv_cyc(), fp18_set_dig(), fp_prime_get_par(), pp_exp_k18(), pp_fin_k18_oatep(), pp_mil_k18(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.
pp_map_k24()
void pp_map_k24 (fp24_t r, const ep_t p, const ep4_t q)
Computes the Optimal Ate pairing of two points in a parameterized elliptic curve with embedding degree 24.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 142 of file relic_pp_map_k24.c.
References bn_free, bn_new, bn_null, bn_sign(), ep4_free, ep4_is_infty(), ep4_new, ep4_norm(), ep4_null, EP_B24, ep_curve_is_pairf(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, fp24_inv_cyc(), fp24_set_dig(), fp_prime_get_par(), pp_exp_k24(), pp_mil_k24(), RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
pp_map_sim_k24()
void pp_map_sim_k24 (fp24_t r, const ep_t * p, const ep4_t * q, int m)
Computes the optimal ate multi-pairing in a parameterized elliptic curve with embedding degree 24.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 188 of file relic_pp_map_k24.c.
References bn_free, bn_new, bn_null, bn_sign(), ep4_free, ep4_is_infty(), ep4_new, ep4_norm(), ep4_null, EP_B24, ep_curve_is_pairf(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp24_inv_cyc(), fp24_set_dig(), fp_prime_get_par(), pp_exp_k24(), pp_mil_k24(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.
pp_map_k48()
void pp_map_k48 (fp48_t r, const ep_t p, const ep8_t q)
Computes the Optimal Ate pairing of two points in a parameterized elliptic curve with embedding degree 48.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 142 of file relic_pp_map_k48.c.
References bn_free, bn_new, bn_null, bn_sign(), ep8_free, ep8_is_infty(), ep8_new, ep8_norm(), ep8_null, EP_B48, ep_curve_is_pairf(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, fp48_inv_cyc(), fp48_set_dig(), fp_prime_get_par(), pp_exp_k48(), pp_mil_k48(), RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
pp_map_sim_k48()
void pp_map_sim_k48 (fp48_t r, const ep_t * p, const ep8_t * q, int m)
Computes the optimal ate multi-pairing in a parameterized elliptic curve with embedding degree 48.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 188 of file relic_pp_map_k48.c.
References bn_free, bn_new, bn_null, bn_sign(), ep8_free, ep8_is_infty(), ep8_new, ep8_norm(), ep8_null, EP_B48, ep_curve_is_pairf(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp48_inv_cyc(), fp48_set_dig(), fp_prime_get_par(), pp_exp_k48(), pp_mil_k48(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.
pp_map_k54()
void pp_map_k54 (fp54_t r, const ep_t p, const fp9_t qx, const fp9_t qy)
Computes the Optimal Ate pairing of two points in a parameterized elliptic curve with embedding degree 54.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 165 of file relic_pp_map_k54.c.
References bn_free, bn_new, bn_null, bn_sign(), ep_curve_is_pairf(), ep_is_infty(), EP_SG54, ERR_CAUGHT, fp54_inv_cyc(), fp54_set_dig(), fp9_is_zero(), fp_prime_get_par(), pp_exp_k54(), pp_mil_k54(), RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.