RELIC: src/fp/relic_fp_inv.c File Reference
relic_fp_inv.c File Reference
Prime field arithmetic
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_bn_low.h"
Functions
static dis_t jumpdivstep (dis_t m[4], dis_t delta, dig_t f, dig_t g, int s)
void fp_inv_basic (fp_t c, const fp_t a)
void fp_inv_binar (fp_t c, const fp_t a)
void fp_inv_monty (fp_t c, const fp_t a)
void fp_inv_exgcd (fp_t c, const fp_t a)
void fp_inv_divst (fp_t c, const fp_t a)
void fp_inv_jmpds (fp_t c, const fp_t a)
void fp_inv_lower (fp_t c, const fp_t a)
void fp_inv_sim (fp_t *c, const fp_t *a, int n)
Detailed Description
Implementation of the prime field inversion functions.
Definition in file relic_fp_inv.c.
Function Documentation
jumpdivstep()
static dis_t jumpdivstep (dis_t m[4], dis_t delta, dig_t f, dig_t g, int s) static
Definition at line 52 of file relic_fp_inv.c.
References RLC_DIG.
Referenced by fp_inv_jmpds().
fp_inv_basic()
void fp_inv_basic (fp_t c, const fp_t a)
Inverts a prime field element using Fermat's Little Theorem.
Parameters
[out] c - the result.
[in] a - the prime field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 93 of file relic_fp_inv.c.
References bn_free, bn_new, bn_null, bn_sub_dig(), dv_copy(), ERR_CAUGHT, ERR_NO_VALID, fp_exp, fp_is_zero(), fp_prime_get(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
fp_inv_binar()
void fp_inv_binar (fp_t c, const fp_t a)
Inverts a prime field element using the binary method.
Parameters
[out] c - the result.
[in] a - the prime field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 124 of file relic_fp_inv.c.
References bn_add(), bn_cmp(), bn_cmp_dig(), bn_copy(), bn_free, bn_hlv(), bn_new, bn_null, bn_set_dig(), bn_sign(), bn_sub(), bn_zero(), dv_copy(), ERR_CAUGHT, ERR_NO_VALID, fp_is_zero(), fp_prime_back(), fp_prime_conv(), fp_prime_get(), fp_rsh1_low(), RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FP_DIGS, RLC_GT, RLC_LT, RLC_NEG, RLC_THROW, and RLC_TRY.
fp_inv_monty()
void fp_inv_monty (fp_t c, const fp_t a)
Inverts a prime field element using Montgomery inversion.
Parameters
[out] c - the result.
[in] a - the prime field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 241 of file relic_fp_inv.c.
References bn_add(), bn_cmp(), bn_dbl(), bn_free, bn_is_zero(), bn_mod_monty_back(), bn_mod_monty_conv(), bn_new, bn_null, bn_read_raw(), bn_set_2b(), bn_set_dig(), bn_sub1_low(), bn_subn_low(), bn_trim(), bn_zero(), dv_cmp(), dv_copy(), dv_zero(), ERR_CAUGHT, ERR_NO_VALID, fp_copy(), fp_is_zero(), fp_mul, fp_prime_get(), fp_prime_get_conv(), fp_rsh1_low(), fp_subn_low(), fp_zero(), RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FP_DIGS, RLC_GT, RLC_LT, RLC_THROW, and RLC_TRY.
fp_inv_exgcd()
void fp_inv_exgcd (fp_t c, const fp_t a)
Inverts a prime field element using the Euclidean Extended Algorithm.
Parameters
[out] c - the result.
[in] a - the prime field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 375 of file relic_fp_inv.c.
References bn_add(), bn_cmp_dig(), bn_copy(), bn_div_rem(), bn_free, bn_mul, bn_new, bn_null, bn_set_dig(), bn_sign(), bn_sub(), bn_zero(), dv_copy(), ERR_CAUGHT, ERR_NO_VALID, fp_is_zero(), fp_prime_back(), fp_prime_conv(), fp_prime_get(), RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FP_DIGS, RLC_NEG, RLC_THROW, and RLC_TRY.
fp_inv_divst()
void fp_inv_divst (fp_t c, const fp_t a)
Inverts a prime field element using the constant-time division step approach by Bernstein and Bo-Yin Yang.
Parameters
[out] c - the result.
[in] a - the prime field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 446 of file relic_fp_inv.c.
References bn_add_dig(), bn_addn_low(), bn_free, bn_lsh(), bn_new, bn_null, bn_set_dig(), dv_copy(), dv_copy_sec(), dv_free, dv_new, dv_null, dv_swap_sec(), dv_zero(), ERR_CAUGHT, ERR_NO_VALID, fp_add1_low(), fp_add_dig(), fp_addm_low(), fp_copy(), fp_copy_sec(), fp_dblm_low(), fp_exp, fp_free, fp_hlv, fp_is_zero(), fp_mul, fp_neg, fp_negm_low(), fp_new, fp_null, FP_PRIME, fp_prime_get(), fp_rdcn_low(), fp_rsh1_low(), fp_set_dig(), fp_zero(), RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FP_DIGS, RLC_POS, RLC_SEL, RLC_THROW, and RLC_TRY.
fp_inv_jmpds()
void fp_inv_jmpds (fp_t c, const fp_t a)
Inverts a prime field element using the constant-time jump division step by Bernstein and Bo-Yin Yang.
Parameters
[out] c - the result.
[in] a - the prime field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 562 of file relic_fp_inv.c.
References bn_addn_low(), bn_muls_low(), bn_negs_low(), bn_rshs_low(), core_get(), dv_copy(), dv_copy_sec(), dv_free, dv_new, dv_null, dv_zero(), ERR_CAUGHT, ERR_NO_VALID, fp_add, fp_addd_low(), fp_copy(), fp_copy_sec(), fp_free, fp_is_zero(), fp_mul, fp_neg, fp_negm_low(), fp_new, fp_null, FP_PRIME, fp_prime_get(), fp_rdc, fp_rdcn_low(), fp_subd_low(), jumpdivstep(), RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FP_DIGS, RLC_MASK, RLC_POS, RLC_SEL, RLC_SIGN, RLC_THROW, and RLC_TRY.
fp_inv_lower()
void fp_inv_lower (fp_t c, const fp_t a)
Inverts a prime field element using a direct call to the lower layer.
Parameters
[out] c - the result.
[in] a - the prime field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 809 of file relic_fp_inv.c.
References ERR_NO_VALID, fp_invm_low(), fp_is_zero(), and RLC_THROW.
fp_inv_sim()
void fp_inv_sim (fp_t * c, const fp_t * a, int n)
Inverts multiple prime field elements simultaneously.
Parameters
[out] c - the result.
[in] a - the prime field elements to invert.
[in] n - the number of elements.
Definition at line 820 of file relic_fp_inv.c.
References ERR_CAUGHT, ERR_NO_MEMORY, fp_copy(), fp_free, fp_inv, fp_mul, fp_new, fp_null, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by ed_norm_sim(), ep_map_swift_impl(), and ep_norm_sim().