RELIC: src/epx/relic_ep2_dbl.c File Reference
relic_ep2_dbl.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
#include "relic_ep_dbl_tmpl.h"
Functions
TMPL_DBL_BASIC_IMP (ep2, fp2)
TMPL_DBL_PROJC_IMP (ep2, fp2)
TMPL_DBL_JACOB_IMP (ep2, fp2)
void ep2_dbl_basic (ep2_t r, const ep2_t p)
void ep2_dbl_slp_basic (ep2_t r, fp2_t s, const ep2_t p)
void ep2_dbl_projc (ep2_t r, const ep2_t p)
void ep2_dbl_jacob (ep2_t r, const ep2_t p)
Detailed Description
Implementation of doubling on elliptic prime curves over a quadratic extension field.
Definition in file relic_ep2_dbl.c.
Function Documentation
TMPL_DBL_BASIC_IMP()
TMPL_DBL_BASIC_IMP (ep2 , fp2)
Doubles a point represented in affine coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the point to double.
TMPL_DBL_PROJC_IMP()
TMPL_DBL_PROJC_IMP (ep2 , fp2)
Doubles a point represented in projective coordinates on an ordinary prime elliptic curve.
Parameters
r - the result.
p - the point to double.
TMPL_DBL_JACOB_IMP()
TMPL_DBL_JACOB_IMP (ep2 , fp2)
Doubles a point represented in Jacobian coordinates on an ordinary prime elliptic curve.
Parameters
r - the result.
p - the point to double.
ep2_dbl_basic()
void ep2_dbl_basic (ep2_t r, const ep2_t p)
Doubles a point represented in affine coordinates in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[int] p - the point to double.
Definition at line 86 of file relic_ep2_dbl.c.
References ep2_is_infty(), and ep2_set_infty().
ep2_dbl_slp_basic()
void ep2_dbl_slp_basic (ep2_t r, fp2_t s, const ep2_t p)
Doubles a point represented in affine coordinates in an elliptic curve over a quadratic extension and returns the computed slope.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the point to double.
Definition at line 94 of file relic_ep2_dbl.c.
References ep2_is_infty(), and ep2_set_infty().
Referenced by pp_dbl_k12_basic(), and pp_dbl_k8_basic().
ep2_dbl_projc()
void ep2_dbl_projc (ep2_t r, const ep2_t p)
Doubles a point represented in projective coordinates in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 107 of file relic_ep2_dbl.c.
References ep2_is_infty(), and ep2_set_infty().
ep2_dbl_jacob()
void ep2_dbl_jacob (ep2_t r, const ep2_t p)
Doubles a point represented in Jacobian coordinates in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 120 of file relic_ep2_dbl.c.
References ep2_is_infty(), and ep2_set_infty().