RELIC: src/fpx/relic_fp3_sqr.c File Reference
relic_fp3_sqr.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
Functions
void fp3_sqr_basic (fp3_t c, const fp3_t a)
void fp3_sqr_integ (fp3_t c, const fp3_t a)
Detailed Description
Implementation of squaring in a cubic extension of a prime field.
Definition in file relic_fp3_sqr.c.
Function Documentation
fp3_sqr_basic()
void fp3_sqr_basic (fp3_t c, const fp3_t a)
Computes the square of a cubic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the cubic extension field element to square.
Definition at line 42 of file relic_fp3_sqr.c.
References dv_free, dv_new, dv_null, ERR_CAUGHT, fp_add, fp_addc_low(), fp_addd_low(), fp_dbl, fp_hlvd_low(), fp_muln_low(), fp_prime_get_cnr(), fp_rdc, fp_sqrn_low(), fp_sub, fp_subc_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp3_sqr_integ()
void fp3_sqr_integ (fp3_t c, const fp3_t a)
Computes the square of a cubic extension field element using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the cubic extension field element to square.
Definition at line 126 of file relic_fp3_sqr.c.
References fp3_sqrm_low().