RELIC: src/bn/relic_bn_cmp.c File Reference
relic_bn_cmp.c File Reference
Multiple precision integer arithmetic
#include "relic_core.h"
#include "relic_bn_low.h"
Functions
int bn_cmp_abs (const bn_t a, const bn_t b)
int bn_cmp_dig (const bn_t a, dig_t b)
int bn_cmp (const bn_t a, const bn_t b)
Detailed Description
Implementation of the multiple precision comparison functions.
Definition in file relic_bn_cmp.c.
Function Documentation
bn_cmp_abs()
int bn_cmp_abs (const bn_t a, const bn_t b)
Returns the result of an unsigned comparison between two multiple precision integers.
Parameters
[in] a - the first multiple precision integer.
[in] b - the second multiple precision integer.
Returns
RLC_LT if a < b, RLC_EQ if a == b and RLC_GT if a > b.
Definition at line 39 of file relic_bn_cmp.c.
References bn_is_zero(), dv_cmp(), RLC_EQ, RLC_GT, and RLC_LT.
Referenced by bn_add(), bn_cmp(), bn_div_imp(), bn_gcd_ext_binar(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_lehme(), bn_lcm(), bn_mod_barrt(), bn_mod_monty_basic(), bn_mod_monty_comba(), bn_mod_pmers(), bn_rand_mod(), and bn_sub().
bn_cmp_dig()
int bn_cmp_dig (const bn_t a, dig_t b)
Returns the result of a signed comparison between a multiple precision integer and a digit.
Parameters
[in] a - the multiple precision integer.
[in] b - the digit.
Returns
RLC_LT if a < b, RLC_EQ if a == b and RLC_GT if a > b.
Definition at line 55 of file relic_bn_cmp.c.
References RLC_EQ, RLC_GT, RLC_LT, and RLC_NEG.
Referenced by bn_factor(), bn_is_prime_basic(), bn_is_prime_rabin(), bn_is_prime_solov(), bn_mod_inv(), bn_mxp_basic(), bn_mxp_dig(), bn_mxp_monty(), bn_mxp_sim_few(), bn_mxp_sim_lot(), bn_mxp_slide(), bn_smb_jac(), bn_smb_leg(), bn_srt(), cp_bdpe_gen(), cp_ghpe_gen(), cp_rabin_gen(), cp_rsa_gen(), cp_rsapsi_gen(), cp_shipsi_gen(), eb_mul_halve(), ep_param_set(), fp_inv_binar(), fp_inv_exgcd(), g1_is_valid(), and pad_pkcs2().
bn_cmp()
int bn_cmp (const bn_t a, const bn_t b)
Returns the result of a signed comparison between two multiple precision integers.
Parameters
[in] a - the first multiple precision integer.
[in] b - the second multiple precision integer.
Returns
RLC_LT if a < b, RLC_EQ if a == b and RLC_GT if a > b.
Definition at line 75 of file relic_bn_cmp.c.
References bn_cmp_abs(), bn_is_zero(), RLC_EQ, RLC_GT, RLC_LT, RLC_NEG, and RLC_POS.
Referenced by bn_factor(), bn_gcd_binar(), bn_gcd_ext_binar(), bn_gcd_ext_mid(), bn_is_prime_rabin(), bn_is_prime_solov(), bn_mod_barrt(), bn_smb_leg(), bn_srt(), cp_bdpe_dec(), cp_ecdsa_ver(), cp_ecss_ver(), cp_ghpe_gen(), cp_mklhs_onv(), cp_mklhs_ver(), cp_phpe_gen(), cp_pokdl_ver(), cp_rabin_dec(), cp_rabin_gen(), cp_rsa_gen(), cp_rsapsi_gen(), cp_rsapsi_int(), cp_shipsi_gen(), cp_shipsi_int(), cp_shpe_gen(), cp_sokdl_ver(), cp_vbnn_ver(), ep2_pck(), ep2_upk(), ep_pck(), ep_upk(), fp_inv_binar(), fp_inv_monty(), and fp_read_bin().