RELIC: include/low/relic_bn_low.h File Reference
relic_bn_low.h File Reference
Multiple precision integer arithmetic
#include "relic_types.h"
Functions
dig_t bn_add1_low (dig_t *c, const dig_t *a, const dig_t digit, size_t size)
dig_t bn_addn_low (dig_t *c, const dig_t *a, const dig_t *b, size_t size)
dig_t bn_sub1_low (dig_t *c, const dig_t *a, dig_t digit, size_t size)
dig_t bn_subn_low (dig_t *c, const dig_t *a, const dig_t *b, size_t size)
dig_t bn_negs_low (dig_t *c, const dig_t *a, dig_t sa, size_t size)
int bn_cmp1_low (dig_t a, dig_t b)
int bn_cmpn_low (const dig_t *a, const dig_t *b, size_t size)
dig_t bn_lsh1_low (dig_t *c, const dig_t *a, size_t size)
dig_t bn_lshb_low (dig_t *c, const dig_t *a, size_t size, uint_t bits)
dig_t bn_rsh1_low (dig_t *c, const dig_t *a, size_t size)
dig_t bn_rshb_low (dig_t *c, const dig_t *a, size_t size, uint_t bits)
dig_t bn_rshs_low (dig_t *c, const dig_t *a, size_t size, uint_t bits)
dig_t bn_mula_low (dig_t *c, const dig_t *a, dig_t digit, size_t size)
dig_t bn_mul1_low (dig_t *c, const dig_t *a, dig_t digit, size_t size)
dig_t bn_muls_low (dig_t *c, const dig_t *a, dig_t sa, dis_t digit, size_t size)
void bn_muln_low (dig_t *c, const dig_t *a, const dig_t *b, size_t size)
void bn_muld_low (dig_t *c, const dig_t *a, size_t sa, const dig_t *b, size_t sb, uint_t low, uint_t high)
dig_t bn_sqra_low (dig_t *c, const dig_t *a, size_t size)
void bn_sqrn_low (dig_t *c, const dig_t *a, size_t size)
void bn_divn_low (dig_t *c, dig_t *d, dig_t *a, size_t sa, dig_t *b, size_t sb)
void bn_div1_low (dig_t *c, dig_t *d, const dig_t *a, dig_t digit, size_t size)
void bn_modn_low (dig_t *c, const dig_t *a, size_t sa, const dig_t *m, size_t sm, dig_t u)
Detailed Description
Interface of the low-level multiple precision integer arithmetic module.
All functions assume that the destination has enough capacity to store the result of the computation.
Definition in file relic_bn_low.h.
Function Documentation
bn_add1_low()
dig_t bn_add1_low (dig_t * c, const dig_t * a, const dig_t digit, size_t size)
Adds a digit to a digit vector. Computes c = a + digit.
Parameters
[out] c - the result.
[in] a - the first digit vector to add.
[in] digit - the digit to add.
[in] size - the number of digits in the first operand.
Returns
the carry of the last digit addition.
Referenced by bn_add_dig(), bn_add_imp(), bn_sub_dig(), fp_mul_karat_imp(), and fp_sqr_karat_imp().
bn_addn_low()
dig_t bn_addn_low (dig_t * c, const dig_t * a, const dig_t * b, size_t size)
Adds two digit vectors of the same size. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first digit vector to add.
[in] b - the second digit vector to add.
[in] size - the number of digits to add.
Returns
the carry of the last digit addition.
Referenced by bn_add_imp(), bn_mod_monty_basic(), fp_inv_divst(), fp_inv_jmpds(), fp_mul_karat_imp(), fp_smb_binar(), fp_smb_divst(), fp_smb_jmpds(), and fp_sqr_karat_imp().
bn_sub1_low()
dig_t bn_sub1_low (dig_t * c, const dig_t * a, dig_t digit, size_t size)
Subtracts a digit from a digit vector. Computes c = a - digit.
Parameters
[out] c - the result.
[in] a - the digit vector.
[in] digit - the digit to subtract.
[in] size - the number of digits in a.
Returns
the carry of the last digit subtraction.
Referenced by bn_add_dig(), bn_sub_dig(), bn_sub_imp(), fp_inv_monty(), fp_mul_karat_imp(), and fp_sqr_karat_imp().
bn_subn_low()
dig_t bn_subn_low (dig_t * c, const dig_t * a, const dig_t * b, size_t size)
Subtracts a digit vector from another digit vector. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the digit vector.
[in] b - the digit vector to subtract.
[in] size - the number of digits to subtract.
Returns
the carry of the last digit subtraction.
Referenced by bn_mod_monty_basic(), bn_sub_imp(), fp_inv_monty(), fp_mul_karat_imp(), and fp_sqr_karat_imp().
bn_negs_low()
dig_t bn_negs_low (dig_t * c, const dig_t * a, dig_t sa, size_t size)
Conditionally negate a digit vector using two's complement representation.
Parameters
[out] c - the result.
[in] a - the digit vector to conditionally negate.
[in] sa - the sign of the digit vector.
[in] n - the number of digits to conditionally negate.
Returns
the carry of the last digit negation.
Referenced by fp_inv_jmpds(), fp_smb_binar(), fp_smb_divst(), and fp_smb_jmpds().
bn_cmp1_low()
int bn_cmp1_low (dig_t a, dig_t b)
Compares two digits.
Parameters
[in] a - the first digit to compare.
[in] b - the second digit to compare.
Returns
BN_LT if a < b, BN_EQ if a == b and BN_GT if a > b.
bn_cmpn_low()
int bn_cmpn_low (const dig_t * a, const dig_t * b, size_t size)
Compares two digit vectors of the same size.
Parameters
[in] a - the first digit vector to compare.
[in] b - the second digit vector to compare.
[in] size - the number of digits to compare.
Returns
BN_LT if a < b, BN_EQ if a == b and BN_GT if a > b.
bn_lsh1_low()
dig_t bn_lsh1_low (dig_t * c, const dig_t * a, size_t size)
Shifts a digit vector to the left by 1 bit. Computes c = a << 1.
Parameters
[out] c - the result
[in] a - the digit vector to shift.
[in] size - the number of digits to shift.
Returns
the carry of the last digit shift.
Referenced by bn_dbl().
bn_lshb_low()
dig_t bn_lshb_low (dig_t * c, const dig_t * a, size_t size, uint_t bits)
Shifts a digit vector to the left by an amount smaller than a digit. Computes c = a << bits.
Parameters
[out] c - the result
[in] a - the digit vector to shift.
[in] size - the number of digits to shift.
[in] bits - the shift amount.
Returns
the carry of the last digit shift.
Referenced by bn_lsh().
bn_rsh1_low()
dig_t bn_rsh1_low (dig_t * c, const dig_t * a, size_t size)
Shifts a digit vector to the right by 1 bit. Computes c = a >> 1.
Parameters
[out] c - the result
[in] a - the digit vector to shift.
[in] size - the number of digits to shift.
Returns
the carry of the last digit shift.
Referenced by bn_hlv(), fb_inv_almos(), and fb_inv_binar().
bn_rshb_low()
dig_t bn_rshb_low (dig_t * c, const dig_t * a, size_t size, uint_t bits)
Shifts a digit vector to the right by an amount smaller than a digit. Computes c = a >> bits.
Parameters
[out] c - the result
[in] a - the digit vector to shift.
[in] size - the number of digits to shift.
[in] bits - the shift amount.
Returns
the carry of the last digit shift.
Referenced by bn_rsh(), and fp_smb_binar().
bn_rshs_low()
dig_t bn_rshs_low (dig_t * c, const dig_t * a, size_t size, uint_t bits)
Shifts a signed digit vector to the right by an amount smaller than a digit. Computes c = a >> bits.
Parameters
[out] c - the result
[in] a - the signed digit vector to shift.
[in] size - the number of digits to shift.
[in] bits - the shift amount.
Returns
the carry of the last digit shift.
Referenced by fp_inv_jmpds(), and fp_smb_jmpds().
bn_mula_low()
dig_t bn_mula_low (dig_t * c, const dig_t * a, dig_t digit, size_t size)
Multiplies a digit vector by a digit and adds this result to another digit vector. Computes c = c + a * digit.
Parameters
[out] c - the result.
[in] a - the digit vector to multiply.
[in] digit - the digit to multiply.
[in] size - the number of digits to multiply.
Returns
the carry of the last addition.
Referenced by bn_mod_monty_basic(), bn_mul_basic(), and fp_mul_karat_imp().
bn_mul1_low()
dig_t bn_mul1_low (dig_t * c, const dig_t * a, dig_t digit, size_t size)
Multiplies a digit vector by a digit and stores this result in another digit vector. Computes c = a * digit.
Parameters
[out] c - the result.
[in] a - the first digit vector to multiply.
[in] digit - the digit to multiply.
[in] size - the number of digits to multiply.
Returns
the most significant digit.
Referenced by bn_mul_dig().
bn_muls_low()
dig_t bn_muls_low (dig_t * c, const dig_t * a, dig_t sa, dis_t digit, size_t size)
Multiplies a signed digit vector by a signed digit and stores this result in another digit vector. Computes c = (-1)^sa * a * digit.
Parameters
[out] c - the result.
[in] a - the first digit vector to multiply.
[in] sa - the sign of the first digit vector.
[in] digit - the digit to multiply.
[in] size - the number of digits to multiply.
Returns
the most significant digit.
Referenced by fp_inv_jmpds(), fp_smb_binar(), and fp_smb_jmpds().
bn_muln_low()
void bn_muln_low (dig_t * c, const dig_t * a, const dig_t * b, size_t size)
Multiplies two digit vectors of the same size. Computes c = a * b.
Parameters
[out] c - the result.
[in] a - the first digit vector to multiply.
[in] b - the second digit vector to multiply.
[in] size - the number of digits to multiply.
Referenced by bn_mul_comba(), fp_mul_karat_imp(), and fp_sqr_karat_imp().
bn_muld_low()
void bn_muld_low (dig_t * c, const dig_t * a, size_t sa, const dig_t * b, size_t sb, uint_t low, uint_t high)
Multiplies two digit vectors of different sizes, with sa > sb. Computes c = a * b. This function outputs as result only the digits between low and high, inclusive, with high > sa and low < sb.
Parameters
[out] c - the result.
[in] a - the first digit vector to multiply.
[in] b - the second digit vector to multiply.
[in] sa - the number of digits in the first operand.
[in] sb - the number of digits in the second operand.
[in] low - the first digit to compute.
[in] high - the last digit to compute.
Referenced by bn_mod_barrt(), and bn_mul_comba().
bn_sqra_low()
dig_t bn_sqra_low (dig_t * c, const dig_t * a, size_t size)
Squares a digit vector and adds this result to another digit vector. Computes c = c + a * a.
Parameters
[out] c - the result.
[in] a - the digit vector to square.
[in] size - the number of digits to square.
Returns
the carry of the last addition.
Referenced by bn_sqr_basic(), fp_sqr_basic(), and fp_sqr_karat_imp().
bn_sqrn_low()
void bn_sqrn_low (dig_t * c, const dig_t * a, size_t size)
Squares a digit vector. Computes c = a * a.
Parameters
[out] c - the result.
[in] a - the digit vector to square.
[in] size - the number of digits to square.
Referenced by bn_sqr_comba(), and fp_sqr_karat_imp().
bn_divn_low()
void bn_divn_low (dig_t * c, dig_t * d, dig_t * a, size_t sa, dig_t * b, size_t sb)
Divides a digit vector by another digit vector. Computes c = floor(a / b) and d = a mod b. The dividend and divisor may be destroyed inside the function.
Parameters
[out] c - the quotient.
[out] d - the remainder.
[in,out] a - the dividend.
[in] sa - the size of the dividend.
[in,out] b - the divisor.
[in] sb - the size of the divisor.
Referenced by bn_div_imp(), and fp_rdc_basic().
bn_div1_low()
void bn_div1_low (dig_t * c, dig_t * d, const dig_t * a, dig_t digit, size_t size)
Divides a digit vector by a digit. Computes c = floor(a / digit) and d = a mod digit.
Parameters
[out] c - the quotient.
[out] d - the remainder.
[in] a - the dividend.
[in] size - the size of the dividend.
[in] digit - the divisor.
Referenced by bn_div_dig(), and bn_div_rem_dig().
bn_modn_low()
void bn_modn_low (dig_t * c, const dig_t * a, size_t sa, const dig_t * m, size_t sm, dig_t u)
Reduces a digit vector modulo m by Montgomery's algorithm.
Parameters
[out] c - the result.
[in] a - the digit vector to reduce.
[in] sa - the number of digits to reduce
[in] m - the modulus.
[in] sm - the size of the modulus.
[in] u - the reciprocal of the modulus.
Referenced by bn_mod_monty_comba().