RELIC: src/ep/relic_ep_mul.c File Reference
relic_ep_mul.c File Reference
Elliptic curves over binary fields
#include "relic_core.h"
Functions
static void ep_mul_glv_imp (ep_t r, const ep_t p, const bn_t k)
static void ep_mul_naf_imp (ep_t r, const ep_t p, const bn_t k)
static void ep_mul_reg_glv (ep_t r, const ep_t p, const bn_t k)
static void ep_mul_reg_imp (ep_t r, const ep_t p, const bn_t k)
void ep_mul_basic (ep_t r, const ep_t p, const bn_t k)
void ep_mul_slide (ep_t r, const ep_t p, const bn_t k)
void ep_mul_monty (ep_t r, const ep_t p, const bn_t k)
void ep_mul_lwnaf (ep_t r, const ep_t p, const bn_t k)
void ep_mul_lwreg (ep_t r, const ep_t p, const bn_t k)
void ep_mul_gen (ep_t r, const bn_t k)
void ep_mul_dig (ep_t r, const ep_t p, dig_t k)
Detailed Description
Implementation of the point multiplication on prime elliptic curves.
Definition in file relic_ep_mul.c.
Function Documentation
ep_mul_glv_imp()
static void ep_mul_glv_imp (ep_t r, const ep_t p, const bn_t k) static
Definition at line 42 of file relic_ep_mul.c.
References bn_free, bn_mod, bn_new, bn_null, bn_rec_glv(), bn_rec_naf(), bn_sign(), ep_add, ep_curve_get_ord(), ep_curve_get_v1(), ep_curve_get_v2(), ep_dbl, ep_free, ep_neg(), ep_new, ep_norm(), ep_null, ep_psi(), ep_set_infty(), ep_sub(), ep_tab(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_POS, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by ep_mul_lwnaf().
ep_mul_naf_imp()
static void ep_mul_naf_imp (ep_t r, const ep_t p, const bn_t k) static
Definition at line 150 of file relic_ep_mul.c.
References bn_free, bn_mod, bn_new, bn_null, bn_rec_naf(), ep_add, ep_curve_get_ord(), ep_dbl, ep_free, ep_new, ep_norm(), ep_null, ep_set_infty(), ep_sub(), ep_tab(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by ep_mul_lwnaf().
ep_mul_reg_glv()
static void ep_mul_reg_glv (ep_t r, const ep_t p, const bn_t k) static
Definition at line 212 of file relic_ep_mul.c.
References BASIC, bn_abs(), bn_bits(), bn_free, bn_is_even(), bn_mod, bn_new, bn_null, bn_rec_glv(), bn_rec_reg(), bn_sign(), dv_copy_sec(), EP_ADD, ep_add, ep_curve_get_ord(), ep_curve_get_v1(), ep_curve_get_v2(), ep_dbl, ep_free, ep_neg(), ep_new, ep_norm(), ep_null, ep_psi(), ep_set_infty(), ep_sub(), ep_tab(), ERR_CAUGHT, fp_copy_sec(), fp_set_dig(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_FP_DIGS, RLC_POS, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by ep_mul_lwreg().
ep_mul_reg_imp()
static void ep_mul_reg_imp (ep_t r, const ep_t p, const bn_t k) static
Definition at line 350 of file relic_ep_mul.c.
References BASIC, bn_abs(), bn_bits(), bn_free, bn_is_even(), bn_new, bn_null, bn_rec_reg(), bn_sign(), EP_ADD, ep_add, ep_curve_get_ord(), ep_dbl, ep_free, ep_neg(), ep_new, ep_norm(), ep_null, ep_set_infty(), ep_sub(), ep_tab(), ERR_CAUGHT, fp_copy_sec(), fp_set_dig(), RLC_CATCH_ANY, RLC_CEIL, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by ep_mul_lwreg().
ep_mul_basic()
void ep_mul_basic (ep_t r, const ep_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the binary method. There is no restriction on the scalar.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 440 of file relic_ep_mul.c.
References bn_bits(), bn_is_zero(), bn_rec_naf(), bn_sign(), ep_add, ep_dbl, ep_free, ep_is_infty(), ep_mul_dig(), ep_neg(), ep_new, ep_norm(), ep_null, ep_set_infty(), ep_sub(), ERR_CAUGHT, ERR_NO_BUFFER, RLC_ALLOCA, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by ep_curve_set_endom(), and ep_mul_cof().
ep_mul_slide()
void ep_mul_slide (ep_t r, const ep_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the sliding window method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 498 of file relic_ep_mul.c.
References bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, bn_rec_slw(), ep_add, ep_copy(), ep_curve_get_ord(), ep_dbl, ep_free, ep_is_infty(), ep_new, ep_norm(), ep_norm_sim(), ep_null, ep_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_THROW, RLC_TRY, RLC_WIDTH, and util_bits_dig().
ep_mul_monty()
void ep_mul_monty (ep_t r, const ep_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the constant-time Montgomery ladder point multiplication method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 574 of file relic_ep_mul.c.
References bn_abs(), bn_add(), bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_new, bn_null, dv_swap_sec(), ep_add, ep_blind(), ep_curve_get_ord(), ep_dbl, ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ep_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_MAX, RLC_SEL, RLC_THROW, and RLC_TRY.
ep_mul_lwnaf()
void ep_mul_lwnaf (ep_t r, const ep_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the w-NAF method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 644 of file relic_ep_mul.c.
References bn_is_zero(), ep_curve_is_endom(), ep_is_infty(), ep_mul_glv_imp(), ep_mul_naf_imp(), and ep_set_infty().
ep_mul_lwreg()
void ep_mul_lwreg (ep_t r, const ep_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using a regular method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 666 of file relic_ep_mul.c.
References bn_is_zero(), ep_curve_is_endom(), ep_is_infty(), ep_mul_reg_glv(), ep_mul_reg_imp(), and ep_set_infty().
ep_mul_gen()
void ep_mul_gen (ep_t r, const bn_t k)
Multiplies the generator of a prime elliptic curve by an integer.
Parameters
[out] r - the result.
[in] k - the integer.
Definition at line 684 of file relic_ep_mul.c.
References bn_is_zero(), ep_curve_get_gen(), ep_curve_get_tab(), ep_free, ep_mul, ep_mul_fix, ep_new, ep_null, ep_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep_mul_sim_gen(), and ep_rand().
ep_mul_dig()
void ep_mul_dig (ep_t r, const ep_t p, dig_t k)
Multiplies a prime elliptic point by a small positive integer.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 711 of file relic_ep_mul.c.
References bn_free, bn_new, bn_null, bn_rec_naf(), bn_set_dig(), ep_add, ep_dbl, ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ep_set_infty(), ep_sub(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep_mul_basic(), and ep_mul_cof().