RELIC: include/low/relic_fp_low.h File Reference
relic_fp_low.h File Reference
Prime field arithmetic
Functions
dig_t fp_add1_low (dig_t *c, const dig_t *a, dig_t digit)
dig_t fp_addn_low (dig_t *c, const dig_t *a, const dig_t *b)
void fp_addm_low (dig_t *c, const dig_t *a, const dig_t *b)
dig_t fp_addd_low (dig_t *c, const dig_t *a, const dig_t *b)
void fp_addc_low (dig_t *c, const dig_t *a, const dig_t *b)
dig_t fp_sub1_low (dig_t *c, const dig_t *a, dig_t digit)
dig_t fp_subn_low (dig_t *c, const dig_t *a, const dig_t *b)
void fp_subm_low (dig_t *c, const dig_t *a, const dig_t *b)
dig_t fp_subd_low (dig_t *c, const dig_t *a, const dig_t *b)
void fp_subc_low (dig_t *c, const dig_t *a, const dig_t *b)
void fp_negm_low (dig_t *c, const dig_t *a)
dig_t fp_dbln_low (dig_t *c, const dig_t *a)
void fp_dblm_low (dig_t *c, const dig_t *a)
void fp_hlvm_low (dig_t *c, const dig_t *a)
void fp_hlvd_low (dig_t *c, const dig_t *a)
dig_t fp_lsh1_low (dig_t *c, const dig_t *a)
dig_t fp_lshb_low (dig_t *c, const dig_t *a, uint_t bits)
dig_t fp_rsh1_low (dig_t *c, const dig_t *a)
dig_t fp_rshb_low (dig_t *c, const dig_t *a, uint_t bits)
dig_t fp_mula_low (dig_t *c, const dig_t *a, dig_t digit)
dig_t fp_mul1_low (dig_t *c, const dig_t *a, dig_t digit)
void fp_muln_low (dig_t *c, const dig_t *a, const dig_t *b)
void fp_mulm_low (dig_t *c, const dig_t *a, const dig_t *b)
void fp_sqrn_low (dig_t *c, const dig_t *a)
void fp_sqrm_low (dig_t *c, const dig_t *a)
void fp_rdcs_low (dig_t *c, const dig_t *a, const dig_t *m)
void fp_rdcn_low (dig_t *c, dig_t *a)
void fp_invm_low (dig_t *c, const dig_t *a)
int fp_smbm_low (const dig_t *a)
Detailed Description
Interface of the low-level prime field arithmetic module.
Definition in file relic_fp_low.h.
Function Documentation
fp_add1_low()
dig_t fp_add1_low (dig_t * c, const dig_t * a, dig_t digit)
Adds a digit vector and a digit. Computes c = a + digit.
Parameters
[out] c - the result.
[in] a - the digit vector to add.
[in] digit - the digit to add.
Returns
the carry of the last digit addition.
Referenced by fp_add_dig(), fp_inv_divst(), and fp_smb_divst().
fp_addn_low()
dig_t fp_addn_low (dig_t * c, const dig_t * a, const dig_t * b)
Adds two digit vectors of the same size. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first digit vector to add.
[in] b - the second digit vector to add.
Returns
the carry of the last digit addition.
Referenced by fp_add_basic(), fp_hlv_basic(), fp_sub_basic(), and fp_sub_dig().
fp_addm_low()
void fp_addm_low (dig_t * c, const dig_t * a, const dig_t * b)
Adds two digit vectors of the same size with integrated modular reduction. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first digit vector to add.
[in] b - the second digit vector to add.
Referenced by fp_add_integ(), fp_inv_divst(), and fp_rdc_monty_basic().
fp_addd_low()
dig_t fp_addd_low (dig_t * c, const dig_t * a, const dig_t * b)
Adds two double-length digit vectors. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first digit vector to add.
[in] b - the second digit vector to add.
Returns
the carry of the last digit addition.
Referenced by fp3_mul_basic(), fp3_sqr_basic(), and fp_inv_jmpds().
fp_addc_low()
void fp_addc_low (dig_t * c, const dig_t * a, const dig_t * b)
Adds two double-length digit vectors and reduces modulo p * R. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first digit vector to add.
[in] b - the second digit vector to add.
Referenced by fp2_mul_basic(), fp3_mul_basic(), fp3_sqr_basic(), and pp_dbl_k2_projc_lazyr().
fp_sub1_low()
dig_t fp_sub1_low (dig_t * c, const dig_t * a, dig_t digit)
Subtracts a digit from a digit vector. Computes c = a - digit.
Parameters
[out] c - the result.
[in] a - the digit vector.
[in] digit - the digit to subtract.
Returns
the carry of the last digit subtraction.
Referenced by fp_sub_dig().
fp_subn_low()
dig_t fp_subn_low (dig_t * c, const dig_t * a, const dig_t * b)
Subtracts a digit vector from another digit vector. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the digit vector.
[in] b - the digit vector to subtract.
Returns
the carry of the last digit subtraction.
Referenced by fp_add_basic(), fp_add_dig(), fp_dbl_basic(), fp_inv_monty(), fp_neg_basic(), fp_norm(), fp_smb_divst(), and fp_sub_basic().
fp_subm_low()
void fp_subm_low (dig_t * c, const dig_t * a, const dig_t * b)
Subtracts two digit vectors of the same size with integrated modular reduction. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the first digit vector to add.
[in] b - the second digit vector to add.
Referenced by fp_rand(), fp_sub_integ(), and pp_dbl_k2_projc_lazyr().
fp_subd_low()
dig_t fp_subd_low (dig_t * c, const dig_t * a, const dig_t * b)
Subtracts a double-length digit vector from another digit vector. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the first digit vector to add.
[in] b - the second digit vector to add.
Returns
the carry of the last digit subtraction.
Referenced by fp_inv_jmpds().
fp_subc_low()
void fp_subc_low (dig_t * c, const dig_t * a, const dig_t * b)
Subtracts a double-length digit vector from another digit vector. Computes c = a - b. This version of the function should handle possible carries by adding p * R.
Parameters
[out] c - the result.
[in] a - the first digit vector to add.
[in] b - the second digit vector to add.
Referenced by fp2_mul_basic(), fp3_mul_basic(), fp3_sqr_basic(), pp_add_k2_projc_lazyr(), and pp_dbl_k2_projc_lazyr().
fp_negm_low()
void fp_negm_low (dig_t * c, const dig_t * a)
Negates a digit vector. Computes c = -a.
Parameters
[out] c - the result.
[out] a - the prime field element to negate.
Referenced by fp_inv_divst(), fp_inv_jmpds(), and fp_neg_integ().
fp_dbln_low()
dig_t fp_dbln_low (dig_t * c, const dig_t * a)
Doubles a digit vector. Computes c = a + a.
Parameters
[out] c - the result.
[in] a - the digit vector.
Returns
the carry of the last digit doubling.
fp_dblm_low()
void fp_dblm_low (dig_t * c, const dig_t * a)
Doubles a digit vector with integrated modular reduction. Computes c = a + a.
Parameters
[out] c - the result.
[in] a - the first digit vector to add.
Referenced by fp_dbl_integ(), and fp_inv_divst().
fp_hlvm_low()
void fp_hlvm_low (dig_t * c, const dig_t * a)
Halves a digit vector with integrated modular reduction. Computes c = a/2.
Parameters
[out] c - the result.
[in] a - the digit vector to halve.
Referenced by fp_hlv_integ().
fp_hlvd_low()
void fp_hlvd_low (dig_t * c, const dig_t * a)
Halves a double-precision digit vector. Computes c = a/2.
Parameters
[out] c - the result.
[in] a - the digit vector to halve.
Referenced by fp12_sqr_unr(), fp24_sqr_unr(), fp3_sqr_basic(), fp6_sqr_unr(), fp9_sqr_unr(), and pp_dbl_k8_projc_lazyr_new().
fp_lsh1_low()
dig_t fp_lsh1_low (dig_t * c, const dig_t * a)
Shifts a digit vector to the left by 1 bits. Computes c = a << 1.
Parameters
[out] c - the result.
[in] a - the digit vector to shift.
Returns
the carry of the last digit shift.
Referenced by fp_dbl_basic(), and fp_lsh().
fp_lshb_low()
dig_t fp_lshb_low (dig_t * c, const dig_t * a, uint_t bits)
Shifts a digit vector to the left by an amount smaller than a digit. Computes c = a << bits.
Parameters
[out] c - the result.
[in] a - the digit vector to shift.
[in] bits - the shift amount.
Returns
the carry of the last digit shift.
Referenced by fp_lsh().
fp_rsh1_low()
dig_t fp_rsh1_low (dig_t * c, const dig_t * a)
Shifts a digit vector to the right by 1 bit. Computes c = a >> 1.
Parameters
[out] c - the result.
[in] a - the digit vector to shift.
Returns
the carry of the last digit shift.
Referenced by fp_hlv_basic(), fp_inv_binar(), fp_inv_divst(), fp_inv_monty(), fp_rsh(), and fp_smb_divst().
fp_rshb_low()
dig_t fp_rshb_low (dig_t * c, const dig_t * a, uint_t bits)
Shifts a digit vector to the right by an amount smaller than a digit. Computes c = a >> bits.
Parameters
[out] c - the result.
[in] a - the digit vector to shift.
[in] bits - the shift amount.
Returns
the carry of the last digit shift.
Referenced by fp_rsh().
fp_mula_low()
dig_t fp_mula_low (dig_t * c, const dig_t * a, dig_t digit)
Multiplies a digit vector by a digit and adds this result to another digit vector. Computes c = c + a * digit.
Parameters
[out] c - the result.
[in] a - the digit vector to multiply.
[in] digit - the digit to multiply.
Returns
the carry of the addition.
Referenced by fp_mul_basic(), and fp_rdc_monty_basic().
fp_mul1_low()
dig_t fp_mul1_low (dig_t * c, const dig_t * a, dig_t digit)
Multiplies a digit vector by a digit and stores this result in another digit vector. Computes c = a * digit.
Parameters
[out] c - the result.
[in] a - the digit vector to multiply.
[in] digit - the digit to multiply.
Returns
the most significant digit.
Referenced by fp_prime_conv_dig().
fp_muln_low()
void fp_muln_low (dig_t * c, const dig_t * a, const dig_t * b)
Multiplies two digit vectors of the same size. Computes c = a * b.
Parameters
[out] c - the result.
[in] a - the first digit vector to multiply.
[in] b - the second digit vector to multiply.
Referenced by fp12_mul_dxs_lazyr(), fp16_mul_dxs_lazyr(), fp18_mul_dxs_lazyr(), fp2_mul_basic(), fp3_mul_basic(), fp3_sqr_basic(), fp_mul_comba(), fp_mul_karat(), pp_add_k2_projc_lazyr(), and pp_dbl_k2_projc_lazyr().
fp_mulm_low()
void fp_mulm_low (dig_t * c, const dig_t * a, const dig_t * b)
Multiplies two digit vectors of the same size with embedded modular reduction. Computes c = (a * b) mod p.
Parameters
[out] c - the result.
[in] a - the first digit vector to multiply.
[in] b - the second digit vector to multiply.
Referenced by fp_mul_integ(), and fp_prime_set().
fp_sqrn_low()
void fp_sqrn_low (dig_t * c, const dig_t * a)
Squares a digit vector. Computes c = a * a.
Parameters
[out] c - the result.
[in] a - the digit vector to square.
Referenced by fp3_sqr_basic(), fp_sqr_comba(), fp_sqr_karat(), and pp_dbl_k2_projc_lazyr().
fp_sqrm_low()
void fp_sqrm_low (dig_t * c, const dig_t * a)
Squares a digit vector with embedded modular reduction.
Parameters
[out] c - the result.
[in] a - the digit vector to square.
Referenced by fp_sqr_integ().
fp_rdcs_low()
void fp_rdcs_low (dig_t * c, const dig_t * a, const dig_t * m)
Reduces a digit vector modulo m represented in special form. Computes c = a mod m.
Parameters
[out] c - the result.
[in] a - the digit vector to reduce.
[in] m - the modulus.
Referenced by fp_rdc_quick().
fp_rdcn_low()
void fp_rdcn_low (dig_t * c, dig_t * a)
Reduces a digit vector modulo the configured prime p. Computes c = a mod p.
Parameters
[out] c - the result.
[in] a - the digit vector to reduce.
Referenced by fp_inv_divst(), fp_inv_jmpds(), fp_rdc_monty_comba(), fp_smb_binar(), fp_smb_divst(), fp_smb_jmpds(), pp_add_k2_projc_lazyr(), and pp_dbl_k2_projc_lazyr().
fp_invm_low()
void fp_invm_low (dig_t * c, const dig_t * a)
Inverts a digit vector modulo the configured prime.
Parameters
[out] c - the result.
[in] a - the digit vector to invert.
Referenced by fp_inv_lower().
fp_smbm_low()
int fp_smbm_low (const dig_t * a)
Computes the Legendre symbol of a digit vector and the configured prime.
Parameters
[in] a - the digit vector to invert.
Returns
the result.
Referenced by fp_smb_lower().