RELIC: src/ed/relic_ed_mul_sim.c File Reference
relic_ed_mul_sim.c File Reference
Edwards curves over prime fields.
#include "relic_core.h"
Functions
static void ed_mul_sim_plain (ed_t r, const ed_t p, const bn_t k, const ed_t q, const bn_t m, const ed_t *t)
void ed_mul_sim_basic (ed_t r, const ed_t p, const bn_t k, const ed_t q, const bn_t m)
void ed_mul_sim_trick (ed_t r, const ed_t p, const bn_t k, const ed_t q, const bn_t m)
void ed_mul_sim_inter (ed_t r, const ed_t p, const bn_t k, const ed_t q, const bn_t m)
void ed_mul_sim_joint (ed_t r, const ed_t p, const bn_t k, const ed_t q, const bn_t m)
void ed_mul_sim_gen (ed_t r, const bn_t k, const ed_t q, const bn_t m)
void ed_mul_sim_lot (ed_t r, const ed_t p[], const bn_t k[], int n)
Detailed Description
Implementation of simultaneous point multiplication on binary elliptic curves.
Version
$Id$
Definition in file relic_ed_mul_sim.c.
Function Documentation
ed_mul_sim_plain()
static void ed_mul_sim_plain (ed_t r, const ed_t p, const bn_t k, const ed_t q, const bn_t m, const ed_t * t) static
Multiplies and adds two prime elliptic curve points simultaneously, optionally choosing the first point as the generator depending on an optional table of precomputed points.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer.
[in] t - the pointer to the precomputed table.
Definition at line 54 of file relic_ed_mul_sim.c.
References bn_rec_naf(), bn_sign(), ed_add, ed_dbl, ed_free, ed_new, ed_norm(), ed_null, ed_set_infty(), ed_sub, ed_tab(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by ed_mul_sim_gen(), and ed_mul_sim_inter().
ed_mul_sim_basic()
void ed_mul_sim_basic (ed_t r, const ed_t p, const bn_t k, const ed_t q, const bn_t m)
Multiplies and adds two Edwards elliptic curve points simultaneously using scalar multiplication and point addition.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 150 of file relic_ed_mul_sim.c.
References ed_add, ed_free, ed_mul, ed_new, ed_norm(), ed_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ed_mul_sim_trick()
void ed_mul_sim_trick (ed_t r, const ed_t p, const bn_t k, const ed_t q, const bn_t m)
Multiplies and adds two Edwards elliptic curve points simultaneously using shamir's trick.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 175 of file relic_ed_mul_sim.c.
References bn_free, bn_is_zero(), bn_new, bn_null, bn_rec_win(), bn_sign(), ed_add, ed_copy(), ed_curve_get_ord(), ed_dbl, ed_free, ed_is_infty(), ed_mul, ed_neg, ed_new, ed_norm(), ed_norm_sim(), ed_null, ed_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_CEIL, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
ed_mul_sim_inter()
void ed_mul_sim_inter (ed_t r, const ed_t p, const bn_t k, const ed_t q, const bn_t m)
Multiplies and adds two Edwards elliptic curve points simultaneously using interleaving of NAFs.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 267 of file relic_ed_mul_sim.c.
References bn_is_zero(), ed_is_infty(), ed_mul, and ed_mul_sim_plain().
ed_mul_sim_joint()
void ed_mul_sim_joint (ed_t r, const ed_t p, const bn_t k, const ed_t q, const bn_t m)
Multiplies and adds two Edwards elliptic curve points simultaneously using Solinas' Joint Sparse Form.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 286 of file relic_ed_mul_sim.c.
References bn_bits(), bn_is_zero(), bn_rec_jsf(), bn_sign(), ed_add, ed_copy(), ed_dbl, ed_free, ed_is_infty(), ed_mul, ed_neg, ed_new, ed_norm(), ed_norm_sim(), ed_null, ed_set_infty(), ed_sub, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, and RLC_TRY.
ed_mul_sim_gen()
void ed_mul_sim_gen (ed_t r, const bn_t k, const ed_t q, const bn_t m)
Multiplies and adds the generator and an Edwards elliptic curve point simultaneously. Computes R = [k]G + [m]Q.
Parameters
[out] r - the result.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer.
Definition at line 361 of file relic_ed_mul_sim.c.
References bn_is_zero(), ed_curve_get_gen(), ed_curve_get_tab(), ed_free, ed_is_infty(), ed_mul, ed_mul_gen(), ed_mul_sim, ed_mul_sim_plain(), ed_new, ed_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ed_mul_sim_lot()
void ed_mul_sim_lot (ed_t r, const ed_t p[], const bn_t k[], int n)
Multiplies and adds multiple Edwards elliptic curve points simultaneously. Computes R = \Sum_i=0..n [k_i]P_i.
Parameters
[out] r - the result.
[out] p - the elements to multiply.
[out] k - the integer scalars.
[out] n - the number of elements to multiply.
Definition at line 394 of file relic_ed_mul_sim.c.
References bn_bits(), bn_rec_naf(), bn_sign(), ed_add, ed_dbl, ed_free, ed_neg, ed_new, ed_norm(), ed_null, ed_set_infty(), ed_sub, ERR_CAUGHT, ERR_NO_MEMORY, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_MAX, RLC_NEG, RLC_THROW, and RLC_TRY.