RELIC: src/fpx/relic_fp48_mul.c File Reference
relic_fp48_mul.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
Functions
void fp48_mul_basic (fp48_t c, const fp48_t a, const fp48_t b)
void fp48_mul_lazyr (fp48_t c, const fp48_t a, const fp48_t b)
void fp48_mul_dxs (fp48_t c, const fp48_t a, const fp48_t b)
void fp48_mul_art (fp48_t c, const fp48_t a)
Detailed Description
Implementation of multiplication in a 48-degree extension of a prime field.
Definition in file relic_fp48_mul.c.
Function Documentation
fp48_mul_basic()
void fp48_mul_basic (fp48_t c, const fp48_t a, const fp48_t b)
Multiples two 48-extension field elements using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the 48-extension field element.
[in] b - the 48-extension field element.
Definition at line 42 of file relic_fp48_mul.c.
References ERR_CAUGHT, fp24_add(), fp24_free, fp24_mul, fp24_mul_art(), fp24_new, fp24_null, fp24_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp48_mul_lazyr()
void fp48_mul_lazyr (fp48_t c, const fp48_t a, const fp48_t b)
Multiples two 48-extension field elements using lazy reduction.
Parameters
[out] c - the result.
[in] a - the 48-extension field element.
[in] b - the 48-extension field element.
Definition at line 87 of file relic_fp48_mul.c.
References ERR_CAUGHT, fp24_add(), fp24_free, fp24_mul, fp24_mul_art(), fp24_new, fp24_null, fp24_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp48_mul_dxs()
void fp48_mul_dxs (fp48_t c, const fp48_t a, const fp48_t b)
Multiples a dense 48-extension field element by a sparse element using basic arithmetic. Computes C = A * B.
Parameters
[out] c - the result.
[in] a - the dense 48-extension field element.
[in] b - the sparse 48-extension field element.
Definition at line 131 of file relic_fp48_mul.c.
References ERR_CAUGHT, fp24_add(), fp24_free, fp24_mul_art(), fp24_mul_dxs(), fp24_new, fp24_null, fp24_sub(), fp8_add(), fp8_copy(), fp8_mul, fp_add, fp_mul, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_mil_k48().
fp48_mul_art()
void fp48_mul_art (fp48_t c, const fp48_t a)
Multiplies a 48-extension field element by the adjoined root.
Parameters
[out] c - the result.
[in] a - the 48-extension field element to multiply.
Definition at line 194 of file relic_fp48_mul.c.
References ERR_CAUGHT, fp24_copy(), fp24_free, fp24_mul_art(), fp24_new, fp24_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.