RELIC: src/fpx/relic_fp8_mul.c File Reference
relic_fp8_mul.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
Functions
void fp8_mul_basic (fp8_t c, const fp8_t a, const fp8_t b)
static void fp4_mul_dxs_unr (dv4_t c, const fp4_t a, const fp4_t b)
void fp8_mul_dxs (fp8_t c, const fp8_t a, const fp8_t b)
void fp8_mul_unr (dv8_t c, const fp8_t a, const fp8_t b)
void fp8_mul_lazyr (fp8_t c, const fp8_t a, const fp8_t b)
void fp8_mul_art (fp8_t c, const fp8_t a)
void fp8_mul_frb (fp8_t c, const fp8_t a, int i, int j)
void fp8_mul_dig (fp8_t c, const fp8_t a, dig_t b)
Detailed Description
Implementation of multiplication in an octic extension of a prime field.
Definition in file relic_fp8_mul.c.
Function Documentation
fp8_mul_basic()
void fp8_mul_basic (fp8_t c, const fp8_t a, const fp8_t b)
Multiples two octic extension field elements.
Parameters
[out] c - the result.
[in] a - the octic extension field element.
[in] b - the octic extension field element.
Definition at line 42 of file relic_fp8_mul.c.
References ERR_CAUGHT, fp4_add(), fp4_free, fp4_mul, fp4_mul_art(), fp4_new, fp4_null, fp4_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp4_mul_dxs_unr()
static void fp4_mul_dxs_unr (dv4_t c, const fp4_t a, const fp4_t b) static
Definition at line 87 of file relic_fp8_mul.c.
References dv2_free, dv2_new, dv2_null, ERR_CAUGHT, fp2_addm_low(), fp2_free, fp2_muln_low(), fp2_new, fp2_norh_low(), fp2_null, fp2_subc_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp8_mul_dxs().
fp8_mul_dxs()
void fp8_mul_dxs (fp8_t c, const fp8_t a, const fp8_t b)
Multiples a dense octic extension field element by a sparse element.
Parameters
[out] c - the result.
[in] a - an octic extension field element.
[in] b - a sparse octic extension field element.
Definition at line 119 of file relic_fp8_mul.c.
References dv4_free, dv4_new, dv4_null, dv_copy(), ERR_CAUGHT, fp2_addc_low(), fp2_nord_low(), fp2_rdcn_low(), fp2_subc_low(), fp4_add(), fp4_free, fp4_mul_dxs_unr(), fp4_mul_unr(), fp4_new, fp4_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
Referenced by pp_mil_k8().
fp8_mul_unr()
void fp8_mul_unr (dv8_t c, const fp8_t a, const fp8_t b)
Multiples two octic extension field elements without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the octic extension field element.
[in] b - the octic extension field element.
Definition at line 177 of file relic_fp8_mul.c.
References dv4_free, dv4_new, dv4_null, dv_copy(), ERR_CAUGHT, fp2_addc_low(), fp2_nord_low(), fp2_subc_low(), fp4_add(), fp4_free, fp4_mul_unr(), fp4_new, fp4_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
Referenced by fp16_mul_dxs_lazyr(), fp16_mul_unr(), fp24_mul_unr(), fp24_sqr_unr(), and fp8_mul_lazyr().
fp8_mul_lazyr()
void fp8_mul_lazyr (fp8_t c, const fp8_t a, const fp8_t b)
Multiples two octic extension field elements using lazy reduction.
Parameters
[out] c - the result.
[in] a - the octic extension field element.
[in] b - the octic extension field element.
Definition at line 229 of file relic_fp8_mul.c.
References dv8_free, dv8_new, dv8_null, ERR_CAUGHT, fp2_rdcn_low(), fp8_mul_unr(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp8_mul_art()
void fp8_mul_art (fp8_t c, const fp8_t a)
Multiplies an octic extension field element by the adjoined root.
Parameters
[out] c - the result.
[in] a - the octic extension field element to multiply.
Definition at line 250 of file relic_fp8_mul.c.
References ERR_CAUGHT, fp4_copy(), fp4_free, fp4_mul_art(), fp4_new, fp4_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp16_frb(), fp16_inv(), fp16_mul_art(), fp16_mul_basic(), fp16_mul_dxs_basic(), fp16_sqr_basic(), fp16_sqr_cyc(), fp16_srt(), fp24_inv(), fp24_mul_art(), fp24_mul_basic(), fp24_mul_dxs(), fp24_sqr_basic(), fp48_back_cyc(), fp48_back_cyc_sim(), fp48_frb(), fp48_sqr_cyc_basic(), fp48_sqr_cyc_lazyr(), fp48_sqr_pck_basic(), fp48_sqr_pck_lazyr(), fp8_field_init(), and fp8_mul_frb().
fp8_mul_frb()
void fp8_mul_frb (fp8_t c, const fp8_t a, int i, int j)
Multiplies an octic extension field element by a power of the constant needed to compute a power of the Frobenius map.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
[in] i - the power of the Frobenius map.
[in] j - the power of the constant.
Definition at line 269 of file relic_fp8_mul.c.
References core_get(), ERR_CAUGHT, ERR_NO_VALID, fp2_mul, fp2_null, fp4_free, fp4_new, fp8_copy(), fp8_mul_art(), fp_copy(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep8_frb().
fp8_mul_dig()
void fp8_mul_dig (fp8_t c, const fp8_t a, dig_t b)
Multiplies an octic extension field element by a digit. Computes c = a * b.
Parameters
[out] c - the result.
[in] a - the octic extension field element.
[in] b - the digit to multiply.
Definition at line 302 of file relic_fp8_mul.c.
References fp4_mul_dig().
Referenced by ep8_curve_mul_a(), and ep8_curve_mul_b().