RELIC: src/cp/relic_cp_vbnn.c File Reference
relic_cp_vbnn.c File Reference
Cryptographic protocols
#include "relic.h"
Functions
int cp_vbnn_gen (bn_t msk, ec_t mpk)
int cp_vbnn_gen_prv (bn_t sk, ec_t pk, const bn_t msk, const uint8_t *id, size_t id_len)
int cp_vbnn_sig (ec_t r, bn_t z, bn_t h, const uint8_t *id, size_t id_len, const uint8_t *msg, int msg_len, const bn_t sk, const ec_t pk)
int cp_vbnn_ver (const ec_t r, const bn_t z, const bn_t h, const uint8_t *id, size_t id_len, const uint8_t *msg, int msg_len, const ec_t mpk)
Detailed Description
Implementation of the vBNN-IBS idenenty-based signature algorithm.
Paper: "IMBAS: id-based multi-user broadcast authentication in wireless sensor networks"
Version
$Id$
Definition in file relic_cp_vbnn.c.
Function Documentation
cp_vbnn_gen()
int cp_vbnn_gen (bn_t msk, ec_t mpk)
Generates a vBNN-IBS key generation center (KGC).
Parameters
[out] msk - the KGC master key.
[out] mpk - the KGC public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 41 of file relic_cp_vbnn.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), ec_curve_get_ord, ec_mul_gen, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_vbnn_gen_prv()
int cp_vbnn_gen_prv (bn_t sk, ec_t pk, const bn_t msk, const uint8_t * id, size_t id_len)
Extract a user key from an identity and a vBNN-IBS key generation center.
Parameters
[out] sk - the extracted vBNN-IBS user private key.
[out] pk - the extracted vBNN-IBS user public key.
[in] msk - the KGC master key.
[in] id - the identity used for extraction.
[in] id_len - the identity length in bytes.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 73 of file relic_cp_vbnn.c.
References bn_add(), bn_free, bn_mod, bn_mul, bn_new, bn_null, bn_rand_mod(), bn_read_bin(), ec_curve_get_ord, ec_mul_gen, ec_size_bin, ec_write_bin, ERR_NO_MEMORY, md_map, RLC_ALLOCA, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_FREE, RLC_MD_LEN, RLC_OK, RLC_THROW, and RLC_TRY.
cp_vbnn_sig()
int cp_vbnn_sig (ec_t r, bn_t z, bn_t h, const uint8_t * id, size_t id_len, const uint8_t * msg, int msg_len, const bn_t sk, const ec_t pk)
Signs a message using the vBNN-IBS scheme.
Parameters
[out] r - the R value of the signature.
[out] z - the z value of the signature.
[out] h - the h value of the signature.
[in] id - the identity buffer.
[in] id_len - the size of identity buffer.
[in] msg - the message buffer to sign.
[in] msg_len - the size of message buffer.
[in] sk - the signer private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 127 of file relic_cp_vbnn.c.
References bn_add(), bn_free, bn_mod, bn_mul, bn_new, bn_null, bn_rand_mod(), bn_read_bin(), ec_copy, ec_curve_get_ord, ec_free, ec_mul_gen, ec_new, ec_null, ec_size_bin, ec_write_bin, ERR_NO_MEMORY, md_map, RLC_ALLOCA, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_FREE, RLC_MD_LEN, RLC_OK, RLC_THROW, and RLC_TRY.
cp_vbnn_ver()
int cp_vbnn_ver (const ec_t r, const bn_t z, const bn_t h, const uint8_t * id, size_t id_len, const uint8_t * msg, int msg_len, const ec_t mpk)
Verifies a signature and message using the vBNN-IBS scheme.
Parameters
[in] r - the R value of the signature.
[in] z - the z value of the signature.
[in] h - the h value of the signature.
[in] id - the identity buffer.
[in] id_len - the size of identity buffer.
[in] msg - the message buffer to sign.
[in] msg_len - the size of message buffer.
[in] mpk - the master public key of the generation center.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 192 of file relic_cp_vbnn.c.
References bn_cmp(), bn_free, bn_mod, bn_new, bn_null, bn_read_bin(), ec_add, ec_curve_get_ord, ec_free, ec_mul, ec_mul_gen, ec_new, ec_norm, ec_null, ec_size_bin, ec_sub, ec_write_bin, ERR_CAUGHT, ERR_NO_MEMORY, md_map, RLC_ALLOCA, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FREE, RLC_MD_LEN, RLC_THROW, and RLC_TRY.