RELIC: include/relic_fpx.h File Reference
relic_fpx.h File Reference
Prime field extensions.
#include "relic_fp.h"
#include "relic_types.h"
Macros
#define dv2_null(A)
#define dv2_new(A)
#define dv2_free(A)
#define fp2_null(A)
#define fp2_new(A)
#define fp2_free(A)
#define fp2_add(C, A, B)
#define fp2_sub(C, A, B)
#define fp2_dbl(C, A)
#define fp2_mul(C, A, B)
#define fp2_mul_nor(C, A)
#define fp2_sqr(C, A)
#define dv3_null(A)
#define dv3_new(A)
#define dv3_free(A)
#define fp3_null(A)
#define fp3_new(A)
#define fp3_free(A)
#define fp3_add(C, A, B)
#define fp3_sub(C, A, B)
#define fp3_dbl(C, A)
#define fp3_mul(C, A, B)
#define fp3_sqr(C, A)
#define dv4_null(A)
#define dv4_new(A)
#define dv4_free(A)
#define fp4_null(A)
#define fp4_new(A)
#define fp4_free(A)
#define fp4_mul(C, A, B)
#define fp4_sqr(C, A)
#define dv6_null(A)
#define dv6_new(A)
#define dv6_free(A)
#define fp6_null(A)
#define fp6_new(A)
#define fp6_free(A)
#define fp6_mul(C, A, B)
#define fp6_sqr(C, A)
#define dv8_null(A)
#define dv8_new(A)
#define dv8_free(A)
#define fp8_null(A)
#define fp8_new(A)
#define fp8_free(A)
#define fp8_mul(C, A, B)
#define fp8_sqr(C, A)
#define dv9_null(A)
#define dv9_new(A)
#define dv9_free(A)
#define fp9_null(A)
#define fp9_new(A)
#define fp9_free(A)
#define fp9_mul(C, A, B)
#define fp9_sqr(C, A)
#define dv12_null(A)
#define dv12_new(A)
#define dv12_free(A)
#define fp12_null(A)
#define fp12_new(A)
#define fp12_free(A)
#define fp12_mul(C, A, B)
#define fp12_mul_dxs(C, A, B)
#define fp12_sqr(C, A)
#define fp12_sqr_cyc(C, A)
#define fp12_sqr_pck(C, A)
#define dv16_null(A)
#define dv16_new(A)
#define dv16_free(A)
#define fp16_null(A)
#define fp16_new(A)
#define fp16_free(A)
#define fp16_mul(C, A, B)
#define fp16_mul_dxs(C, A, B)
#define fp16_sqr(C, A)
#define dv18_null(A)
#define dv18_new(A)
#define dv18_free(A)
#define fp18_null(A)
#define fp18_new(A)
#define fp18_free(A)
#define fp18_mul(C, A, B)
#define fp18_mul_dxs(C, A, B)
#define fp18_sqr(C, A)
#define fp18_sqr_cyc(C, A)
#define fp18_sqr_pck(C, A)
#define dv24_null(A)
#define dv24_new(A)
#define dv24_free(A)
#define fp24_null(A)
#define fp24_new(A)
#define fp24_free(A)
#define fp24_mul(C, A, B)
#define fp24_sqr(C, A)
#define fp24_sqr_cyc(C, A)
#define fp24_sqr_pck(C, A)
#define dv48_null(A)
#define dv48_new(A)
#define dv48_free(A)
#define fp48_null(A)
#define fp48_new(A)
#define fp48_free(A)
#define fp48_mul(C, A, B)
#define fp48_sqr(C, A)
#define fp48_sqr_cyc(C, A)
#define fp48_sqr_pck(C, A)
#define dv54_null(A)
#define dv54_new(A)
#define dv54_free(A)
#define fp54_null(A)
#define fp54_new(A)
#define fp54_free(A)
#define fp54_mul(C, A, B)
#define fp54_sqr(C, A)
#define fp54_sqr_cyc(C, A)
#define fp54_sqr_pck(C, A)
Typedefs
typedef fp_t fp2_t[2]
typedef dv_t dv2_t[2]
typedef fp_st fp2_st[2]
typedef fp_t fp3_t[3]
typedef dv_t dv3_t[3]
typedef fp_st fp3_st[3]
typedef fp2_t fp4_t[2]
typedef dv2_t dv4_t[2]
typedef fp2_st fp4_st[2]
typedef fp2_t fp6_t[3]
typedef dv2_t dv6_t[3]
typedef fp2_st fp6_st[3]
typedef fp4_t fp8_t[2]
typedef dv4_t dv8_t[2]
typedef fp4_st fp8_st[2]
typedef fp3_t fp9_t[3]
typedef dv3_t dv9_t[3]
typedef fp3_st fp9_st[3]
typedef fp6_t fp12_t[2]
typedef dv6_t dv12_t[2]
typedef fp8_t fp16_t[2]
typedef dv8_t dv16_t[2]
typedef fp8_st fp16_st[2]
typedef fp9_t fp18_t[2]
typedef dv9_t dv18_t[2]
typedef fp8_t fp24_t[3]
typedef dv8_t dv24_t[3]
typedef fp24_t fp48_t[2]
typedef fp18_t fp54_t[3]
Functions
void fp2_field_init (void)
int fp2_field_get_qnr (void)
void fp2_copy (fp2_t c, const fp2_t a)
void fp2_copy_sec (fp2_t c, const fp2_t a, dig_t bit)
void fp2_zero (fp2_t a)
int fp2_is_zero (const fp2_t a)
void fp2_rand (fp2_t a)
void fp2_print (const fp2_t a)
int fp2_size_bin (fp2_t a, int pack)
void fp2_read_bin (fp2_t a, const uint8_t *bin, size_t len)
void fp2_write_bin (uint8_t *bin, size_t len, const fp2_t a, int pack)
int fp2_cmp (const fp2_t a, const fp2_t b)
int fp2_cmp_dig (const fp2_t a, const dig_t b)
void fp2_set_dig (fp2_t a, const dig_t b)
void fp2_add_basic (fp2_t c, const fp2_t a, const fp2_t b)
void fp2_add_integ (fp2_t c, const fp2_t a, const fp2_t b)
void fp2_add_dig (fp2_t c, const fp2_t a, dig_t b)
void fp2_sub_basic (fp2_t c, const fp2_t a, const fp2_t b)
void fp2_sub_integ (fp2_t c, const fp2_t a, const fp2_t b)
void fp2_sub_dig (fp2_t c, const fp2_t a, dig_t b)
void fp2_neg (fp2_t c, const fp2_t a)
void fp2_dbl_basic (fp2_t c, const fp2_t a)
void fp2_dbl_integ (fp2_t c, const fp2_t a)
void fp2_mul_basic (fp2_t c, const fp2_t a, const fp2_t b)
void fp2_mul_integ (fp2_t c, const fp2_t a, const fp2_t b)
void fp2_mul_art (fp2_t c, const fp2_t a)
void fp2_mul_nor_basic (fp2_t c, const fp2_t a)
void fp2_mul_nor_integ (fp2_t c, const fp2_t a)
void fp2_mul_frb (fp2_t c, const fp2_t a, int i, int j)
void fp2_mul_dig (fp2_t c, const fp2_t a, dig_t b)
void fp2_sqr_basic (fp2_t c, const fp2_t a)
void fp2_sqr_integ (fp2_t c, const fp2_t a)
void fp2_inv (fp2_t c, const fp2_t a)
void fp2_inv_cyc (fp2_t c, const fp2_t a)
void fp2_inv_sim (fp2_t *c, const fp2_t *a, int n)
int fp2_test_cyc (const fp2_t a)
void fp2_conv_cyc (fp2_t c, const fp2_t a)
void fp2_exp (fp2_t c, const fp2_t a, const bn_t b)
void fp2_exp_dig (fp2_t c, const fp2_t a, dig_t b)
void fp2_exp_cyc (fp2_t c, const fp2_t a, const bn_t b)
void fp2_exp_cyc_sim (fp2_t e, const fp2_t a, const bn_t b, const fp2_t c, const bn_t d)
void fp2_frb (fp2_t c, const fp2_t a, int i)
int fp2_is_sqr (const fp2_t a)
int fp2_srt (fp2_t c, const fp2_t a)
void fp2_pck (fp2_t c, const fp2_t a)
int fp2_upk (fp2_t c, const fp2_t a)
void fp3_field_init (void)
int fp3_field_get_cnr (void)
void fp3_copy (fp3_t c, const fp3_t a)
void fp3_copy_sec (fp3_t c, const fp3_t a, dig_t bit)
void fp3_zero (fp3_t a)
int fp3_is_zero (const fp3_t a)
void fp3_rand (fp3_t a)
void fp3_print (const fp3_t a)
int fp3_size_bin (fp3_t a)
void fp3_read_bin (fp3_t a, const uint8_t *bin, size_t len)
void fp3_write_bin (uint8_t *bin, size_t len, const fp3_t a)
int fp3_cmp (const fp3_t a, const fp3_t b)
int fp3_cmp_dig (const fp3_t a, const dig_t b)
void fp3_set_dig (fp3_t a, const dig_t b)
void fp3_add_basic (fp3_t c, const fp3_t a, const fp3_t b)
void fp3_add_integ (fp3_t c, const fp3_t a, const fp3_t b)
void fp3_add_dig (fp3_t c, const fp3_t a, dig_t b)
void fp3_sub_basic (fp3_t c, const fp3_t a, const fp3_t b)
void fp3_sub_integ (fp3_t c, const fp3_t a, const fp3_t b)
void fp3_sub_dig (fp3_t c, const fp3_t a, dig_t b)
void fp3_neg (fp3_t c, const fp3_t a)
void fp3_dbl_basic (fp3_t c, const fp3_t a)
void fp3_dbl_integ (fp3_t c, const fp3_t a)
void fp3_mul_basic (fp3_t c, const fp3_t a, const fp3_t b)
void fp3_mul_integ (fp3_t c, const fp3_t a, const fp3_t b)
void fp3_mul_art (fp3_t c, const fp3_t a)
void fp3_mul_nor (fp3_t c, const fp3_t a)
void fp3_mul_frb (fp3_t c, const fp3_t a, int i, int j)
void fp3_mul_dig (fp3_t c, const fp3_t a, dig_t b)
void fp3_sqr_basic (fp3_t c, const fp3_t a)
void fp3_sqr_integ (fp3_t c, const fp3_t a)
void fp3_inv (fp3_t c, const fp3_t a)
void fp3_inv_sim (fp3_t *c, const fp3_t *a, int n)
void fp3_exp (fp3_t c, const fp3_t a, const bn_t b)
void fp3_frb (fp3_t c, const fp3_t a, int i)
int fp3_is_sqr (const fp3_t a)
int fp3_srt (fp3_t c, const fp3_t a)
void fp4_field_init (void)
void fp4_copy (fp4_t c, const fp4_t a)
void fp4_copy_sec (fp4_t c, const fp4_t a, dig_t bit)
void fp4_zero (fp4_t a)
int fp4_is_zero (const fp4_t a)
void fp4_rand (fp4_t a)
void fp4_print (const fp4_t a)
int fp4_size_bin (fp4_t a)
void fp4_read_bin (fp4_t a, const uint8_t *bin, size_t len)
void fp4_write_bin (uint8_t *bin, size_t len, const fp4_t a)
int fp4_cmp (const fp4_t a, const fp4_t b)
int fp4_cmp_dig (const fp4_t a, const dig_t b)
void fp4_set_dig (fp4_t a, const dig_t b)
void fp4_add (fp4_t c, const fp4_t a, const fp4_t b)
void fp4_add_dig (fp4_t c, const fp4_t a, dig_t b)
void fp4_sub (fp4_t c, const fp4_t a, const fp4_t b)
void fp4_sub_dig (fp4_t c, const fp4_t a, dig_t b)
void fp4_neg (fp4_t c, const fp4_t a)
void fp4_dbl (fp4_t c, const fp4_t a)
void fp4_mul_unr (dv4_t c, const fp4_t a, const fp4_t b)
void fp4_mul_basic (fp4_t c, const fp4_t a, const fp4_t b)
void fp4_mul_lazyr (fp4_t c, const fp4_t a, const fp4_t b)
void fp4_mul_art (fp4_t c, const fp4_t a)
void fp4_mul_frb (fp4_t c, const fp4_t a, int i, int j)
void fp4_mul_dig (fp4_t c, const fp4_t a, dig_t b)
void fp4_mul_dxs (fp4_t c, const fp4_t a, const fp4_t b)
void fp4_sqr_unr (dv4_t c, const fp4_t a)
void fp4_sqr_basic (fp4_t c, const fp4_t a)
void fp4_sqr_lazyr (fp4_t c, const fp4_t a)
void fp4_inv (fp4_t c, const fp4_t a)
void fp4_inv_sim (fp4_t *c, const fp4_t *a, int n)
void fp4_inv_cyc (fp4_t c, const fp4_t a)
void fp4_exp (fp4_t c, const fp4_t a, const bn_t b)
void fp4_frb (fp4_t c, const fp4_t a, int i)
int fp4_is_sqr (const fp4_t a)
int fp4_srt (fp4_t c, const fp4_t a)
void fp6_copy (fp6_t c, const fp6_t a)
void fp6_copy_sec (fp6_t c, const fp6_t a, dig_t bit)
void fp6_zero (fp6_t a)
int fp6_is_zero (const fp6_t a)
void fp6_rand (fp6_t a)
void fp6_print (const fp6_t a)
int fp6_size_bin (fp6_t a)
void fp6_read_bin (fp6_t a, const uint8_t *bin, size_t len)
void fp6_write_bin (uint8_t *bin, size_t len, const fp6_t a)
int fp6_cmp (const fp6_t a, const fp6_t b)
int fp6_cmp_dig (const fp6_t a, const dig_t b)
void fp6_set_dig (fp6_t a, const dig_t b)
void fp6_add (fp6_t c, const fp6_t a, const fp6_t b)
void fp6_sub (fp6_t c, const fp6_t a, const fp6_t b)
void fp6_neg (fp6_t c, const fp6_t a)
void fp6_dbl (fp6_t c, const fp6_t a)
void fp6_mul_unr (dv6_t c, const fp6_t a, const fp6_t b)
void fp6_mul_basic (fp6_t c, const fp6_t a, const fp6_t b)
void fp6_mul_lazyr (fp6_t c, const fp6_t a, const fp6_t b)
void fp6_mul_art (fp6_t c, const fp6_t a)
void fp6_mul_dxs (fp6_t c, const fp6_t a, const fp6_t b)
void fp6_sqr_unr (dv6_t c, const fp6_t a)
void fp6_sqr_basic (fp6_t c, const fp6_t a)
void fp6_sqr_lazyr (fp6_t c, const fp6_t a)
void fp6_inv (fp6_t c, const fp6_t a)
void fp6_exp (fp6_t c, const fp6_t a, const bn_t b)
void fp6_frb (fp6_t c, const fp6_t a, int i)
void fp8_field_init (void)
void fp8_copy (fp8_t c, const fp8_t a)
void fp8_copy_sec (fp8_t c, const fp8_t a, dig_t bit)
void fp8_zero (fp8_t a)
int fp8_is_zero (const fp8_t a)
void fp8_rand (fp8_t a)
void fp8_print (const fp8_t a)
int fp8_size_bin (fp8_t a, int pack)
void fp8_read_bin (fp8_t a, const uint8_t *bin, size_t len)
void fp8_write_bin (uint8_t *bin, size_t len, const fp8_t a, int pack)
int fp8_cmp (const fp8_t a, const fp8_t b)
int fp8_cmp_dig (const fp8_t a, const dig_t b)
void fp8_set_dig (fp8_t a, const dig_t b)
void fp8_add (fp8_t c, const fp8_t a, const fp8_t b)
void fp8_sub (fp8_t c, const fp8_t a, const fp8_t b)
void fp8_neg (fp8_t c, const fp8_t a)
void fp8_dbl (fp8_t c, const fp8_t a)
void fp8_mul_unr (dv8_t c, const fp8_t a, const fp8_t b)
void fp8_mul_basic (fp8_t c, const fp8_t a, const fp8_t b)
void fp8_mul_lazyr (fp8_t c, const fp8_t a, const fp8_t b)
void fp8_mul_art (fp8_t c, const fp8_t a)
void fp8_mul_frb (fp8_t c, const fp8_t a, int i, int j)
void fp8_mul_dig (fp8_t c, const fp8_t a, dig_t b)
void fp8_mul_dxs (fp8_t c, const fp8_t a, const fp8_t b)
void fp8_sqr_unr (dv8_t c, const fp8_t a)
void fp8_sqr_basic (fp8_t c, const fp8_t a)
void fp8_sqr_lazyr (fp8_t c, const fp8_t a)
void fp8_sqr_cyc (fp8_t c, const fp8_t a)
void fp8_inv (fp8_t c, const fp8_t a)
void fp8_inv_cyc (fp8_t c, const fp8_t a)
void fp8_inv_sim (fp8_t *c, const fp8_t *a, int n)
int fp8_test_cyc (const fp8_t a)
void fp8_conv_cyc (fp8_t c, const fp8_t a)
void fp8_exp (fp8_t c, const fp8_t a, const bn_t b)
void fp8_exp_dig (fp8_t c, const fp8_t a, dig_t b)
void fp8_exp_cyc (fp8_t c, const fp8_t a, const bn_t b)
void fp8_exp_cyc_sim (fp8_t e, const fp8_t a, const bn_t b, const fp8_t c, const bn_t d)
void fp8_frb (fp8_t c, const fp8_t a, int i)
int fp8_is_sqr (const fp8_t a)
int fp8_srt (fp8_t c, const fp8_t a)
void fp9_copy (fp9_t c, const fp9_t a)
void fp9_copy_sec (fp9_t c, const fp9_t a, dig_t bit)
void fp9_zero (fp9_t a)
int fp9_is_zero (const fp9_t a)
void fp9_rand (fp9_t a)
void fp9_print (const fp9_t a)
int fp9_size_bin (fp9_t a)
void fp9_read_bin (fp9_t a, const uint8_t *bin, size_t len)
void fp9_write_bin (uint8_t *bin, size_t len, const fp9_t a)
int fp9_cmp (const fp9_t a, const fp9_t b)
int fp9_cmp_dig (const fp9_t a, const dig_t b)
void fp9_set_dig (fp9_t a, const dig_t b)
void fp9_add (fp9_t c, const fp9_t a, const fp9_t b)
void fp9_sub (fp9_t c, const fp9_t a, const fp9_t b)
void fp9_neg (fp9_t c, const fp9_t a)
void fp9_dbl (fp9_t c, const fp9_t a)
void fp9_mul_unr (dv9_t c, const fp9_t a, const fp9_t b)
void fp9_mul_basic (fp9_t c, const fp9_t a, const fp9_t b)
void fp9_mul_lazyr (fp9_t c, const fp9_t a, const fp9_t b)
void fp9_mul_art (fp9_t c, const fp9_t a)
void fp9_mul_dxs (fp9_t c, const fp9_t a, const fp9_t b)
void fp9_sqr_unr (dv9_t c, const fp9_t a)
void fp9_sqr_basic (fp9_t c, const fp9_t a)
void fp9_sqr_lazyr (fp9_t c, const fp9_t a)
void fp9_inv (fp9_t c, const fp9_t a)
void fp9_inv_sim (fp9_t *c, const fp9_t *a, int n)
void fp9_exp (fp9_t c, const fp9_t a, const bn_t b)
void fp9_frb (fp9_t c, const fp9_t a, int i)
void fp12_copy (fp12_t c, const fp12_t a)
void fp12_copy_sec (fp12_t c, const fp12_t a, dig_t bit)
void fp12_zero (fp12_t a)
int fp12_is_zero (const fp12_t a)
void fp12_rand (fp12_t a)
void fp12_print (const fp12_t a)
int fp12_size_bin (fp12_t a, int pack)
void fp12_read_bin (fp12_t a, const uint8_t *bin, size_t len)
void fp12_write_bin (uint8_t *bin, size_t len, const fp12_t a, int pack)
int fp12_cmp (const fp12_t a, const fp12_t b)
int fp12_cmp_dig (const fp12_t a, const dig_t b)
void fp12_set_dig (fp12_t a, const dig_t b)
void fp12_add (fp12_t c, const fp12_t a, const fp12_t b)
void fp12_sub (fp12_t c, const fp12_t a, const fp12_t b)
void fp12_neg (fp12_t c, const fp12_t a)
void fp12_dbl (fp12_t c, const fp12_t a)
void fp12_mul_unr (dv12_t c, const fp12_t a, const fp12_t b)
void fp12_mul_basic (fp12_t c, const fp12_t a, const fp12_t b)
void fp12_mul_lazyr (fp12_t c, const fp12_t a, const fp12_t b)
void fp12_mul_art (fp12_t c, const fp12_t a)
void fp12_mul_dxs_basic (fp12_t c, const fp12_t a, const fp12_t b)
void fp12_mul_dxs_lazyr (fp12_t c, const fp12_t a, const fp12_t b)
void fp12_sqr_unr (dv12_t c, const fp12_t a)
void fp12_sqr_basic (fp12_t c, const fp12_t a)
void fp12_sqr_lazyr (fp12_t c, const fp12_t a)
void fp12_sqr_cyc_basic (fp12_t c, const fp12_t a)
void fp12_sqr_cyc_lazyr (fp12_t c, const fp12_t a)
void fp12_sqr_pck_basic (fp12_t c, const fp12_t a)
void fp12_sqr_pck_lazyr (fp12_t c, const fp12_t a)
int fp12_test_cyc (const fp12_t a)
void fp12_conv_cyc (fp12_t c, const fp12_t a)
void fp12_back_cyc (fp12_t c, const fp12_t a)
void fp12_back_cyc_sim (fp12_t *c, const fp12_t *a, int n)
void fp12_inv (fp12_t c, const fp12_t a)
void fp12_inv_cyc (fp12_t c, const fp12_t a)
void fp12_frb (fp12_t c, const fp12_t a, int i)
void fp12_exp (fp12_t c, const fp12_t a, const bn_t b)
void fp12_exp_dig (fp12_t c, const fp12_t a, dig_t b)
void fp12_exp_cyc (fp12_t c, const fp12_t a, const bn_t b)
void fp12_exp_cyc_gls (fp12_t c, const fp12_t a, const bn_t b)
void fp12_exp_cyc_sim (fp12_t e, const fp12_t a, const bn_t b, const fp12_t c, const bn_t d)
void fp12_exp_cyc_sps (fp12_t c, const fp12_t a, const int *b, size_t l, int s)
void fp12_pck (fp12_t c, const fp12_t a)
int fp12_upk (fp12_t c, const fp12_t a)
void fp12_pck_max (fp12_t c, const fp12_t a)
int fp12_upk_max (fp12_t c, const fp12_t a)
void fp16_field_init (void)
void fp16_copy (fp16_t c, const fp16_t a)
void fp16_copy_sec (fp16_t c, const fp16_t a, dig_t bit)
void fp16_zero (fp16_t a)
int fp16_is_zero (const fp16_t a)
void fp16_rand (fp16_t a)
void fp16_print (const fp16_t a)
int fp16_size_bin (fp16_t a, int pack)
void fp16_read_bin (fp16_t a, const uint8_t *bin, size_t len)
void fp16_write_bin (uint8_t *bin, size_t len, const fp16_t a, int pack)
int fp16_cmp (const fp16_t a, const fp16_t b)
int fp16_cmp_dig (const fp16_t a, const dig_t b)
void fp16_set_dig (fp16_t a, const dig_t b)
void fp16_add (fp16_t c, const fp16_t a, const fp16_t b)
void fp16_sub (fp16_t c, const fp16_t a, const fp16_t b)
void fp16_neg (fp16_t c, const fp16_t a)
void fp16_dbl (fp16_t c, const fp16_t a)
void fp16_mul_unr (dv16_t c, const fp16_t a, const fp16_t b)
void fp16_mul_basic (fp16_t c, const fp16_t a, const fp16_t b)
void fp16_mul_lazyr (fp16_t c, const fp16_t a, const fp16_t b)
void fp16_mul_art (fp16_t c, const fp16_t a)
void fp16_mul_frb (fp16_t c, const fp16_t a, int i, int j)
void fp16_mul_dxs (fp16_t c, const fp16_t a, const fp16_t b)
void fp16_sqr_unr (dv16_t c, const fp16_t a)
void fp16_sqr_basic (fp16_t c, const fp16_t a)
void fp16_sqr_lazyr (fp16_t c, const fp16_t a)
void fp16_sqr_cyc (fp16_t c, const fp16_t a)
void fp16_inv (fp16_t c, const fp16_t a)
void fp16_inv_cyc (fp16_t c, const fp16_t a)
void fp16_inv_sim (fp16_t *c, const fp16_t *a, int n)
int fp16_test_cyc (const fp16_t a)
void fp16_conv_cyc (fp16_t c, const fp16_t a)
void fp16_exp (fp16_t c, const fp16_t a, const bn_t b)
void fp16_exp_dig (fp16_t c, const fp16_t a, dig_t b)
void fp16_exp_cyc (fp16_t c, const fp16_t a, const bn_t b)
void fp16_exp_cyc_gls (fp16_t c, const fp16_t a, const bn_t b)
void fp16_exp_cyc_sim (fp16_t e, const fp16_t a, const bn_t b, const fp16_t c, const bn_t d)
void fp16_frb (fp16_t c, const fp16_t a, int i)
int fp16_is_sqr (const fp16_t a)
int fp16_srt (fp16_t c, const fp16_t a)
void fp18_copy (fp18_t c, const fp18_t a)
void fp18_copy_sec (fp18_t c, const fp18_t a, dig_t bit)
void fp18_zero (fp18_t a)
int fp18_is_zero (const fp18_t a)
void fp18_rand (fp18_t a)
void fp18_print (const fp18_t a)
int fp18_size_bin (fp18_t a, int pack)
void fp18_read_bin (fp18_t a, const uint8_t *bin, size_t len)
void fp18_write_bin (uint8_t *bin, size_t len, const fp18_t a, int pack)
int fp18_cmp (const fp18_t a, const fp18_t b)
int fp18_cmp_dig (const fp18_t a, const dig_t b)
void fp18_set_dig (fp18_t a, const dig_t b)
void fp18_add (fp18_t c, const fp18_t a, const fp18_t b)
void fp18_sub (fp18_t c, const fp18_t a, const fp18_t b)
void fp18_neg (fp18_t c, const fp18_t a)
void fp18_dbl (fp18_t c, const fp18_t a)
void fp18_mul_unr (dv18_t c, const fp18_t a, const fp18_t b)
void fp18_mul_basic (fp18_t c, const fp18_t a, const fp18_t b)
void fp18_mul_lazyr (fp18_t c, const fp18_t a, const fp18_t b)
void fp18_mul_art (fp18_t c, const fp18_t a)
void fp18_mul_dxs_basic (fp18_t c, const fp18_t a, const fp18_t b)
void fp18_mul_dxs_lazyr (fp18_t c, const fp18_t a, const fp18_t b)
void fp18_sqr_unr (dv18_t c, const fp18_t a)
void fp18_sqr_basic (fp18_t c, const fp18_t a)
void fp18_sqr_lazyr (fp18_t c, const fp18_t a)
void fp18_sqr_cyc_basic (fp18_t c, const fp18_t a)
void fp18_sqr_cyc_lazyr (fp18_t c, const fp18_t a)
void fp18_sqr_pck_basic (fp18_t c, const fp18_t a)
void fp18_sqr_pck_lazyr (fp18_t c, const fp18_t a)
int fp18_test_cyc (const fp18_t a)
void fp18_conv_cyc (fp18_t c, const fp18_t a)
void fp18_back_cyc (fp18_t c, const fp18_t a)
void fp18_back_cyc_sim (fp18_t *c, const fp18_t *a, int n)
void fp18_inv (fp18_t c, const fp18_t a)
void fp18_inv_cyc (fp18_t c, const fp18_t a)
void fp18_frb (fp18_t c, const fp18_t a, int i)
void fp18_exp (fp18_t c, const fp18_t a, const bn_t b)
void fp18_exp_dig (fp18_t c, const fp18_t a, dig_t b)
void fp18_exp_cyc (fp18_t c, const fp18_t a, const bn_t b)
void fp18_exp_cyc_gls (fp18_t c, const fp18_t a, const bn_t b)
void fp18_exp_cyc_sim (fp18_t e, const fp18_t a, const bn_t b, const fp18_t c, const bn_t d)
void fp18_exp_cyc_sps (fp18_t c, const fp18_t a, const int *b, int l, int s)
void fp18_pck (fp18_t c, const fp18_t a)
int fp18_upk (fp18_t c, const fp18_t a)
void fp18_pck_max (fp18_t c, const fp18_t a)
int fp18_upk_max (fp18_t c, const fp18_t a)
void fp24_copy (fp24_t c, const fp24_t a)
void fp24_copy_sec (fp24_t c, const fp24_t a, dig_t bit)
void fp24_zero (fp24_t a)
int fp24_is_zero (const fp24_t a)
void fp24_rand (fp24_t a)
void fp24_print (const fp24_t a)
int fp24_size_bin (fp24_t a, int pack)
void fp24_read_bin (fp24_t a, const uint8_t *bin, size_t len)
void fp24_write_bin (uint8_t *bin, size_t len, const fp24_t a, int pack)
int fp24_cmp (const fp24_t a, const fp24_t b)
int fp24_cmp_dig (const fp24_t a, const dig_t b)
void fp24_set_dig (fp24_t a, const dig_t b)
void fp24_add (fp24_t c, const fp24_t a, const fp24_t b)
void fp24_sub (fp24_t c, const fp24_t a, const fp24_t b)
void fp24_neg (fp24_t c, const fp24_t a)
void fp24_dbl (fp24_t c, const fp24_t a)
void fp24_mul_unr (dv24_t c, const fp24_t a, const fp24_t b)
void fp24_mul_basic (fp24_t c, const fp24_t a, const fp24_t b)
void fp24_mul_lazyr (fp24_t c, const fp24_t a, const fp24_t b)
void fp24_mul_art (fp24_t c, const fp24_t a)
void fp24_mul_dxs (fp24_t c, const fp24_t a, const fp24_t b)
void fp24_sqr_unr (dv24_t c, const fp24_t a)
void fp24_sqr_basic (fp24_t c, const fp24_t a)
void fp24_sqr_lazyr (fp24_t c, const fp24_t a)
void fp24_sqr_cyc_basic (fp24_t c, const fp24_t a)
void fp24_sqr_cyc_lazyr (fp24_t c, const fp24_t a)
void fp24_sqr_pck_basic (fp24_t c, const fp24_t a)
void fp24_sqr_pck_lazyr (fp24_t c, const fp24_t a)
int fp24_test_cyc (const fp24_t a)
void fp24_conv_cyc (fp24_t c, const fp24_t a)
void fp24_back_cyc (fp24_t c, const fp24_t a)
void fp24_back_cyc_sim (fp24_t *c, const fp24_t *a, int n)
void fp24_inv (fp24_t c, const fp24_t a)
void fp24_inv_cyc (fp24_t c, const fp24_t a)
void fp24_frb (fp24_t c, const fp24_t a, int i)
void fp24_exp (fp24_t c, const fp24_t a, const bn_t b)
void fp24_exp_dig (fp24_t c, const fp24_t a, dig_t b)
void fp24_exp_cyc (fp24_t c, const fp24_t a, const bn_t b)
void fp24_exp_cyc_gls (fp24_t c, const fp24_t a, const bn_t b)
void fp24_exp_cyc_sim (fp24_t e, const fp24_t a, const bn_t b, const fp24_t c, const bn_t d)
void fp24_exp_cyc_sps (fp24_t c, const fp24_t a, const int *b, size_t l, int s)
void fp24_pck (fp24_t c, const fp24_t a)
int fp24_upk (fp24_t c, const fp24_t a)
void fp48_copy (fp48_t c, const fp48_t a)
void fp48_copy_sec (fp48_t c, const fp48_t a, dig_t bit)
void fp48_zero (fp48_t a)
int fp48_is_zero (const fp48_t a)
void fp48_rand (fp48_t a)
void fp48_print (const fp48_t a)
int fp48_size_bin (fp48_t a, int pack)
void fp48_read_bin (fp48_t a, const uint8_t *bin, size_t len)
void fp48_write_bin (uint8_t *bin, size_t len, const fp48_t a, int pack)
int fp48_cmp (const fp48_t a, const fp48_t b)
int fp48_cmp_dig (const fp48_t a, const dig_t b)
void fp48_set_dig (fp48_t a, const dig_t b)
void fp48_add (fp48_t c, const fp48_t a, const fp48_t b)
void fp48_sub (fp48_t c, const fp48_t a, const fp48_t b)
void fp48_neg (fp48_t c, const fp48_t a)
void fp48_dbl (fp48_t c, const fp48_t a)
void fp48_mul_basic (fp48_t c, const fp48_t a, const fp48_t b)
void fp48_mul_lazyr (fp48_t c, const fp48_t a, const fp48_t b)
void fp48_mul_art (fp48_t c, const fp48_t a)
void fp48_mul_dxs (fp48_t c, const fp48_t a, const fp48_t b)
void fp48_sqr_basic (fp48_t c, const fp48_t a)
void fp48_sqr_lazyr (fp48_t c, const fp48_t a)
void fp48_sqr_cyc_basic (fp48_t c, const fp48_t a)
void fp48_sqr_cyc_lazyr (fp48_t c, const fp48_t a)
void fp48_sqr_pck_basic (fp48_t c, const fp48_t a)
void fp48_sqr_pck_lazyr (fp48_t c, const fp48_t a)
int fp48_test_cyc (const fp48_t a)
void fp48_conv_cyc (fp48_t c, const fp48_t a)
void fp48_back_cyc (fp48_t c, const fp48_t a)
void fp48_back_cyc_sim (fp48_t *c, const fp48_t *a, int n)
void fp48_inv (fp48_t c, const fp48_t a)
void fp48_inv_cyc (fp48_t c, const fp48_t a)
void fp48_frb (fp48_t c, const fp48_t a, int i)
void fp48_exp (fp48_t c, const fp48_t a, const bn_t b)
void fp48_exp_dig (fp48_t c, const fp48_t a, dig_t b)
void fp48_exp_cyc (fp48_t c, const fp48_t a, const bn_t b)
void fp48_exp_cyc_gls (fp48_t c, const fp48_t a, const bn_t b)
void fp48_exp_cyc_sps (fp48_t c, const fp48_t a, const int *b, size_t l, int s)
void fp48_exp_cyc_sim (fp48_t e, const fp48_t a, const bn_t b, const fp48_t c, const bn_t d)
void fp48_pck (fp48_t c, const fp48_t a)
int fp48_upk (fp48_t c, const fp48_t a)
void fp54_copy (fp54_t c, const fp54_t a)
void fp54_copy_sec (fp54_t c, const fp54_t a, dig_t bit)
void fp54_zero (fp54_t a)
int fp54_is_zero (const fp54_t a)
void fp54_rand (fp54_t a)
void fp54_print (const fp54_t a)
int fp54_size_bin (fp54_t a, int pack)
void fp54_read_bin (fp54_t a, const uint8_t *bin, size_t len)
void fp54_write_bin (uint8_t *bin, size_t len, const fp54_t a, int pack)
int fp54_cmp (const fp54_t a, const fp54_t b)
int fp54_cmp_dig (const fp54_t a, const dig_t b)
void fp54_set_dig (fp54_t a, const dig_t b)
void fp54_add (fp54_t c, const fp54_t a, const fp54_t b)
void fp54_sub (fp54_t c, const fp54_t a, const fp54_t b)
void fp54_neg (fp54_t c, const fp54_t a)
void fp54_dbl (fp54_t c, const fp54_t a)
void fp54_mul_basic (fp54_t c, const fp54_t a, const fp54_t b)
void fp54_mul_lazyr (fp54_t c, const fp54_t a, const fp54_t b)
void fp54_mul_art (fp54_t c, const fp54_t a)
void fp54_mul_dxs (fp54_t c, const fp54_t a, const fp54_t b)
void fp54_sqr_basic (fp54_t c, const fp54_t a)
void fp54_sqr_lazyr (fp54_t c, const fp54_t a)
void fp54_sqr_cyc_basic (fp54_t c, const fp54_t a)
void fp54_sqr_cyc_lazyr (fp54_t c, const fp54_t a)
void fp54_sqr_pck_basic (fp54_t c, const fp54_t a)
void fp54_sqr_pck_lazyr (fp54_t c, const fp54_t a)
int fp54_test_cyc (const fp54_t a)
void fp54_conv_cyc (fp54_t c, const fp54_t a)
void fp54_back_cyc (fp54_t c, const fp54_t a)
void fp54_back_cyc_sim (fp54_t *c, const fp54_t *a, int n)
void fp54_inv (fp54_t c, const fp54_t a)
void fp54_inv_cyc (fp54_t c, const fp54_t a)
void fp54_frb (fp54_t c, const fp54_t a, int i)
void fp54_exp (fp54_t c, const fp54_t a, const bn_t b)
void fp54_exp_dig (fp54_t c, const fp54_t a, dig_t b)
void fp54_exp_cyc (fp54_t c, const fp54_t a, const bn_t b)
void fp54_exp_cyc_sps (fp54_t c, const fp54_t a, const int *b, size_t l, int s)
void fp54_pck (fp54_t c, const fp54_t a)
int fp54_upk (fp54_t c, const fp54_t a)
Detailed Description
Interface of the module for prime extension field arithmetic.
Definition in file relic_fpx.h.
Macro Definition Documentation
dv2_null
#define dv2_null (A)
Value:
        dv_null(A[0]); dv_null(A[1]);                                       \
Initializes a double-precision quadratic extension field element with null.
Parameters
[out] A - the quadratic extension element to initialize.
Definition at line 242 of file relic_fpx.h.
Referenced by fp12_sqr_cyc_lazyr(), fp12_sqr_pck_lazyr(), fp4_mul_dxs_unr(), fp4_mul_unr(), fp4_sqr_unr(), fp6_mul_dxs_unr_lazyr(), fp6_mul_unr(), fp6_sqr_unr(), pp_add_k12_projc_lazyr(), pp_dbl_k12_projc_lazyr(), pp_dbl_k18_projc_lazyr(), pp_dbl_k8_projc_lazyr(), and pp_dbl_k8_projc_lazyr_new().
dv2_new
#define dv2_new (A)
Value:
        dv_new(A[0]); dv_new(A[1]);                                         \
Allocates a double-precision quadratic extension field element.
Parameters
[out] A - the new quadratic extension field element.
Definition at line 251 of file relic_fpx.h.
Referenced by fp12_sqr_cyc_lazyr(), fp12_sqr_pck_lazyr(), fp4_mul_dxs_unr(), fp4_mul_unr(), fp4_sqr_unr(), fp6_mul_dxs_unr_lazyr(), fp6_mul_unr(), fp6_sqr_unr(), pp_add_k12_projc_lazyr(), pp_dbl_k12_projc_lazyr(), pp_dbl_k18_projc_lazyr(), pp_dbl_k8_projc_lazyr(), and pp_dbl_k8_projc_lazyr_new().
dv2_free
#define dv2_free (A)
Value:
        dv_free(A[0]); dv_free(A[1]);                                       \
Frees a double-precision quadratic extension field element.
Parameters
[out] A - the quadratic extension field element to free.
Definition at line 259 of file relic_fpx.h.
Referenced by fp12_sqr_cyc_lazyr(), fp12_sqr_pck_lazyr(), fp4_mul_dxs_unr(), fp4_mul_unr(), fp4_sqr_unr(), fp6_mul_dxs_unr_lazyr(), fp6_mul_unr(), fp6_sqr_unr(), pp_add_k12_projc_lazyr(), pp_dbl_k12_projc_lazyr(), pp_dbl_k18_projc_lazyr(), and pp_dbl_k8_projc_lazyr().
fp2_null
#define fp2_null (A)
Value:
        fp_null(A[0]); fp_null(A[1]);                                       \
Initializes a quadratic extension field element with null.
Parameters
[out] A - the quadratic extension element to initialize.
Definition at line 267 of file relic_fpx.h.
Referenced by detect_opt(), ep2_blind(), ep2_curve_set_twist(), ep2_map_basic(), ep2_map_from_field(), ep2_map_swift(), ep2_norm_imp(), ep2_norm_sim(), ep2_rhs(), ep2_upk(), fp12_back_cyc(), fp12_back_cyc_sim(), fp12_sqr_cyc_basic(), fp12_sqr_cyc_lazyr(), fp12_sqr_pck_basic(), fp12_sqr_pck_lazyr(), fp2_conv_cyc(), fp2_exp(), fp2_exp_cyc(), fp2_exp_cyc_sim(), fp2_exp_dig(), fp2_field_init(), fp2_inv_sim(), fp2_is_sqr(), fp2_mul_frb(), fp2_mul_nor_basic(), fp2_srt(), fp2_test_cyc(), fp2_write_bin(), fp4_inv(), fp4_mul_art(), fp4_mul_basic(), fp4_mul_dxs_unr(), fp4_mul_frb(), fp4_mul_unr(), fp4_sqr_basic(), fp4_sqr_unr(), fp4_srt(), fp6_inv(), fp6_mul_art(), fp6_mul_basic(), fp6_mul_dxs(), fp6_mul_dxs_unr_lazyr(), fp6_mul_unr(), fp6_sqr_basic(), fp6_sqr_unr(), fp8_mul_frb(), pp_add_k12_basic(), pp_add_k12_projc_basic(), pp_add_k12_projc_lazyr(), pp_add_k8_basic(), pp_add_k8_projc_basic(), pp_add_k8_projc_lazyr(), pp_dbl_k12_basic(), pp_dbl_k12_projc_basic(), pp_dbl_k12_projc_lazyr(), pp_dbl_k8_basic(), pp_dbl_k8_projc_basic(), pp_dbl_k8_projc_lazyr(), pp_dbl_k8_projc_lazyr_new(), pp_dbl_k8_projc_new(), pp_map_sim_weilp_k2(), pp_map_weilp_k2(), pp_mil_k2(), and pp_mil_lit_k2().
fp2_new
#define fp2_new (A)
Value:
        fp_new(A[0]); fp_new(A[1]);                                         \
Allocates a quadratic extension field element.
Parameters
[out] A - the new quadratic extension field element.
Definition at line 275 of file relic_fpx.h.
Referenced by detect_opt(), ep2_blind(), ep2_curve_init(), ep2_curve_set_twist(), ep2_map_basic(), ep2_map_from_field(), ep2_map_swift(), ep2_norm_imp(), ep2_norm_sim(), ep2_rhs(), ep2_upk(), fp12_back_cyc(), fp12_back_cyc_sim(), fp12_sqr_cyc_basic(), fp12_sqr_cyc_lazyr(), fp12_sqr_pck_basic(), fp12_sqr_pck_lazyr(), fp2_conv_cyc(), fp2_exp(), fp2_exp_cyc(), fp2_exp_cyc_sim(), fp2_exp_dig(), fp2_field_init(), fp2_inv_sim(), fp2_is_sqr(), fp2_mul_frb(), fp2_mul_nor_basic(), fp2_srt(), fp2_test_cyc(), fp2_write_bin(), fp4_inv(), fp4_mul_art(), fp4_mul_basic(), fp4_mul_dxs_unr(), fp4_mul_frb(), fp4_mul_unr(), fp4_sqr_basic(), fp4_sqr_unr(), fp4_srt(), fp6_inv(), fp6_mul_art(), fp6_mul_basic(), fp6_mul_dxs(), fp6_mul_dxs_unr_lazyr(), fp6_mul_unr(), fp6_sqr_basic(), fp6_sqr_unr(), pp_add_k12_basic(), pp_add_k12_projc_basic(), pp_add_k12_projc_lazyr(), pp_add_k8_basic(), pp_add_k8_projc_basic(), pp_add_k8_projc_lazyr(), pp_dbl_k12_basic(), pp_dbl_k12_projc_basic(), pp_dbl_k12_projc_lazyr(), pp_dbl_k8_basic(), pp_dbl_k8_projc_basic(), pp_dbl_k8_projc_lazyr(), pp_dbl_k8_projc_lazyr_new(), pp_dbl_k8_projc_new(), pp_map_sim_weilp_k2(), pp_map_weilp_k2(), pp_mil_k2(), and pp_mil_lit_k2().
fp2_free
#define fp2_free (A)
Value:
        fp_free(A[0]); fp_free(A[1]);                                       \
Frees a quadratic extension field element.
Parameters
[out] A - the quadratic extension field element to free.
Definition at line 283 of file relic_fpx.h.
Referenced by detect_opt(), ep2_blind(), ep2_curve_clean(), ep2_curve_set_twist(), ep2_map_basic(), ep2_map_from_field(), ep2_map_swift(), ep2_norm_imp(), ep2_norm_sim(), ep2_rhs(), ep2_upk(), fp12_back_cyc(), fp12_back_cyc_sim(), fp12_sqr_cyc_basic(), fp12_sqr_cyc_lazyr(), fp12_sqr_pck_basic(), fp12_sqr_pck_lazyr(), fp2_conv_cyc(), fp2_exp(), fp2_exp_cyc(), fp2_exp_cyc_sim(), fp2_exp_dig(), fp2_field_init(), fp2_inv_sim(), fp2_is_sqr(), fp2_mul_frb(), fp2_mul_nor_basic(), fp2_srt(), fp2_test_cyc(), fp2_write_bin(), fp4_inv(), fp4_mul_art(), fp4_mul_basic(), fp4_mul_dxs_unr(), fp4_mul_frb(), fp4_mul_unr(), fp4_sqr_basic(), fp4_sqr_unr(), fp4_srt(), fp6_inv(), fp6_mul_art(), fp6_mul_basic(), fp6_mul_dxs(), fp6_mul_dxs_unr_lazyr(), fp6_mul_unr(), fp6_sqr_basic(), fp6_sqr_unr(), pp_add_k12_basic(), pp_add_k12_projc_basic(), pp_add_k12_projc_lazyr(), pp_add_k8_basic(), pp_add_k8_projc_basic(), pp_add_k8_projc_lazyr(), pp_dbl_k12_basic(), pp_dbl_k12_projc_basic(), pp_dbl_k12_projc_lazyr(), pp_dbl_k24_basic(), pp_dbl_k8_basic(), pp_dbl_k8_projc_basic(), pp_dbl_k8_projc_lazyr(), pp_dbl_k8_projc_lazyr_new(), pp_dbl_k8_projc_new(), pp_map_sim_weilp_k2(), pp_map_weilp_k2(), pp_mil_k2(), and pp_mil_lit_k2().
fp2_add
#define fp2_add (C, A, B)
Value:
fp2_add_integ(C, A, B)
Adds two quadratic extension field elements. Computes C = A + B.
Parameters
[out] C - the result.
[in] A - the first quadratic extension field element.
[in] B - the second quadratic extension field element.
Definition at line 296 of file relic_fpx.h.
Referenced by ep2_curve_set_map(), ep2_map_swift(), ep2_rhs(), fp12_back_cyc(), fp12_back_cyc_sim(), fp12_mul_dxs_basic(), fp12_mul_dxs_lazyr(), fp12_sqr_cyc_basic(), fp12_sqr_pck_basic(), fp2_mul_nor_basic(), fp4_add(), fp4_mul_basic(), fp4_sqr_basic(), fp4_srt(), fp6_add(), fp6_inv(), fp6_mul_basic(), fp6_mul_dxs(), fp6_sqr_basic(), pp_add_k12_projc_basic(), pp_add_k12_projc_lazyr(), pp_add_k8_projc_basic(), pp_add_k8_projc_lazyr(), pp_dbl_k12_projc_basic(), pp_dbl_k12_projc_lazyr(), pp_dbl_k8_projc_basic(), pp_dbl_k8_projc_lazyr(), pp_dbl_k8_projc_new(), and pp_dbl_lit_k12().
fp2_sub
#define fp2_sub (C, A, B)
Value:
fp2_sub_integ(C, A, B)
Subtracts a quadratic extension field element from another. Computes C = A - B.
Parameters
[out] C - the result.
[in] A - the first quadratic extension field element.
[in] B - the second quadratic extension field element.
Definition at line 310 of file relic_fpx.h.
Referenced by ep2_map_swift(), fp12_back_cyc(), fp12_back_cyc_sim(), fp12_sqr_cyc_basic(), fp12_sqr_pck_basic(), fp4_inv(), fp4_mul_basic(), fp4_sqr_basic(), fp4_srt(), fp4_sub(), fp6_inv(), fp6_mul_basic(), fp6_mul_dxs(), fp6_sqr_basic(), fp6_sub(), pp_add_k12_basic(), pp_add_k12_projc_basic(), pp_add_k12_projc_lazyr(), pp_add_k8_basic(), pp_add_k8_projc_basic(), pp_add_k8_projc_lazyr(), pp_dbl_k12_basic(), pp_dbl_k12_projc_basic(), pp_dbl_k12_projc_lazyr(), pp_dbl_k8_basic(), pp_dbl_k8_projc_basic(), pp_dbl_k8_projc_lazyr(), pp_dbl_k8_projc_lazyr_new(), and pp_dbl_k8_projc_new().
fp2_dbl
#define fp2_dbl (C, A)
Value:
fp2_dbl_integ(C, A)
ffp8 Doubles a quadratic extension field element. Computes C = A + A.
Parameters
[out] C - the result.
[in] A - the quadratic extension field element.
Definition at line 322 of file relic_fpx.h.
Referenced by ep2_curve_mul_a(), ep2_curve_set_map(), ep2_map_swift(), fp12_back_cyc(), fp12_back_cyc_sim(), fp12_sqr_cyc_basic(), fp12_sqr_pck_basic(), fp2_mul_nor_basic(), fp4_dbl(), fp4_sqr_basic(), fp4_srt(), fp6_dbl(), fp6_sqr_basic(), pp_add_k8_projc_basic(), pp_add_k8_projc_lazyr(), pp_dbl_k12_projc_basic(), pp_dbl_k12_projc_lazyr(), pp_dbl_k8_projc_basic(), pp_dbl_k8_projc_lazyr(), and pp_dbl_lit_k12().
fp2_mul
#define fp2_mul (C, A, B)
Value:
fp2_mul_integ(C, A, B)
Multiplies two quadratic extension field elements. Computes C = A * B.
Parameters
[out] C - the result.
[in] A - the first quadratic extension field element.
[in] B - the second quadratic extension field element.
Definition at line 335 of file relic_fpx.h.
Referenced by ep2_blind(), ep2_cmp(), ep2_curve_mul_a(), ep2_curve_mul_b(), ep2_curve_set_map(), ep2_frb(), ep2_map_swift(), ep2_norm_imp(), ep2_rhs(), fp12_back_cyc(), fp12_back_cyc_sim(), fp12_mul_dxs_basic(), fp2_conv_cyc(), fp2_exp(), fp2_exp_cyc(), fp2_exp_cyc_sim(), fp2_exp_dig(), fp2_field_init(), fp2_inv_sim(), fp2_is_sqr(), fp2_mul_frb(), fp2_test_cyc(), fp4_inv(), fp4_mul_basic(), fp4_mul_frb(), fp4_sqr_basic(), fp4_srt(), fp6_inv(), fp6_mul_basic(), fp6_mul_dxs(), fp6_sqr_basic(), fp8_mul_frb(), pp_add_k12_basic(), pp_add_k12_projc_basic(), pp_add_k12_projc_lazyr(), pp_add_k8_basic(), pp_add_k8_projc_basic(), pp_add_k8_projc_lazyr(), pp_dbl_k12_basic(), pp_dbl_k12_projc_basic(), pp_dbl_k12_projc_lazyr(), pp_dbl_k8_basic(), pp_dbl_k8_projc_basic(), pp_dbl_k8_projc_lazyr(), pp_dbl_k8_projc_lazyr_new(), pp_dbl_k8_projc_new(), pp_map_sim_weilp_k2(), pp_map_weilp_k2(), pp_mil_k2(), pp_mil_lit_k2(), pp_norm_k12(), and pp_norm_k8().
fp2_mul_nor
#define fp2_mul_nor (C, A)
Value:
fp2_mul_nor_integ(C, A)
Multiplies a quadratic extension field by the quadratic/cubic non-residue. Computes C = A * E, where E is a non-square/non-cube in the quadratic extension field.
Parameters
[out] C - the result.
[in] A - the quadratic extension field element to multiply.
Definition at line 349 of file relic_fpx.h.
Referenced by fp12_back_cyc(), fp12_back_cyc_sim(), fp12_mul_dxs_basic(), fp12_sqr_cyc_basic(), fp12_sqr_pck_basic(), fp2_field_init(), fp4_inv(), fp4_mul_art(), fp4_mul_basic(), fp4_sqr_basic(), fp4_srt(), fp6_inv(), fp6_mul_art(), fp6_mul_basic(), fp6_mul_dxs(), and fp6_sqr_basic().
fp2_sqr
#define fp2_sqr (C, A)
Value:
fp2_sqr_integ(C, A)
Squares a quadratic extension field element. Computes C = A * A.
Parameters
[out] C - the result.
[in] A - the quadratic extension field element to square.
Definition at line 361 of file relic_fpx.h.
Referenced by ep2_blind(), ep2_cmp(), ep2_curve_set_map(), ep2_map_swift(), ep2_norm_imp(), ep2_on_curve(), ep2_rhs(), fp12_back_cyc(), fp12_back_cyc_sim(), fp12_sqr_cyc_basic(), fp12_sqr_pck_basic(), fp2_exp(), fp2_exp_cyc(), fp2_exp_cyc_sim(), fp2_exp_dig(), fp2_field_init(), fp2_srt(), fp4_inv(), fp4_srt(), fp6_inv(), fp6_sqr_basic(), pp_add_k12_projc_basic(), pp_add_k12_projc_lazyr(), pp_add_k8_projc_basic(), pp_add_k8_projc_lazyr(), pp_dbl_k12_projc_basic(), pp_dbl_k12_projc_lazyr(), pp_dbl_k8_projc_basic(), pp_dbl_k8_projc_lazyr(), pp_dbl_k8_projc_lazyr_new(), pp_dbl_k8_projc_new(), pp_mil_k2(), and pp_mil_lit_k2().
dv3_null
#define dv3_null (A)
Value:
        dv_null(A[0]); dv_null(A[1]); dv_null(A[2]);                        \
Initializes a double-precision cubic extension field element with a null value.
Parameters
[out] A - the cubic extension element to initialize.
Definition at line 370 of file relic_fpx.h.
Referenced by fp18_sqr_cyc_lazyr(), fp18_sqr_pck_lazyr(), fp9_mul_dxs_unr_lazyr(), fp9_mul_unr(), fp9_sqr_unr(), and pp_add_k18_projc_lazyr().
dv3_new
#define dv3_new (A)
Value:
        dv_new(A[0]); dv_new(A[1]); dv_new(A[2]);                           \
Allocates a double-precision cubic extension field element.
Parameters
[out] A - the new cubic extension field element.
Definition at line 378 of file relic_fpx.h.
Referenced by fp18_sqr_cyc_lazyr(), fp18_sqr_pck_lazyr(), fp9_mul_dxs_unr_lazyr(), fp9_mul_unr(), fp9_sqr_unr(), and pp_add_k18_projc_lazyr().
dv3_free
#define dv3_free (A)
Value:
        dv_free(A[0]); dv_free(A[1]); dv_free(A[2]);                        \
Frees a double-precision cubic extension field element.
Parameters
[out] A - the cubic extension field element to free.
Definition at line 386 of file relic_fpx.h.
Referenced by fp18_sqr_cyc_lazyr(), fp18_sqr_pck_lazyr(), fp9_mul_dxs_unr_lazyr(), fp9_mul_unr(), fp9_sqr_unr(), and pp_add_k18_projc_lazyr().
fp3_null
#define fp3_null (A)
Value:
        fp_null(A[0]); fp_null(A[1]); fp_null(A[2]);                        \
Initializes a cubic extension field element with null.
Parameters
[out] A - the cubic extension element to initialize.
Definition at line 394 of file relic_fpx.h.
Referenced by detect_opt(), ep3_blind(), ep3_curve_set_twist(), ep3_map(), ep3_norm_imp(), ep3_norm_sim(), ep3_rhs(), fp18_back_cyc(), fp18_back_cyc_sim(), fp18_sqr_cyc_basic(), fp18_sqr_cyc_lazyr(), fp18_sqr_pck_basic(), fp18_sqr_pck_lazyr(), fp3_exp(), fp3_field_init(), fp3_inv_sim(), fp3_is_sqr(), fp3_mul_frb(), fp3_mul_nor(), fp3_srt(), fp9_inv(), fp9_mul_art(), fp9_mul_basic(), fp9_mul_dxs(), fp9_mul_dxs_unr_lazyr(), fp9_mul_unr(), fp9_sqr_basic(), fp9_sqr_unr(), pp_add_k18_basic(), pp_add_k18_projc_basic(), pp_add_k18_projc_lazyr(), pp_dbl_k18_basic(), pp_dbl_k18_projc_basic(), and pp_dbl_k18_projc_lazyr().
fp3_new
#define fp3_new (A)
Value:
        fp_new(A[0]); fp_new(A[1]); fp_new(A[2]);                           \
Allocates a cubic extension field element.
Parameters
[out] A - the new cubic extension field element.
Definition at line 402 of file relic_fpx.h.
Referenced by detect_opt(), ep3_blind(), ep3_curve_init(), ep3_curve_set_twist(), ep3_map(), ep3_norm_imp(), ep3_norm_sim(), ep3_rhs(), fp18_back_cyc(), fp18_back_cyc_sim(), fp18_sqr_cyc_basic(), fp18_sqr_cyc_lazyr(), fp18_sqr_pck_basic(), fp18_sqr_pck_lazyr(), fp3_exp(), fp3_field_init(), fp3_inv_sim(), fp3_is_sqr(), fp3_mul_frb(), fp3_mul_nor(), fp3_srt(), fp9_inv(), fp9_mul_art(), fp9_mul_basic(), fp9_mul_dxs(), fp9_mul_dxs_unr_lazyr(), fp9_mul_unr(), fp9_sqr_basic(), fp9_sqr_unr(), pp_add_k18_basic(), pp_add_k18_projc_basic(), pp_add_k18_projc_lazyr(), pp_dbl_k18_basic(), pp_dbl_k18_projc_basic(), and pp_dbl_k18_projc_lazyr().
fp3_free
#define fp3_free (A)
Value:
        fp_free(A[0]); fp_free(A[1]); fp_free(A[2]);                        \
Frees a cubic extension field element.
Parameters
[out] A - the cubic extension field element to free.
Definition at line 410 of file relic_fpx.h.
Referenced by detect_opt(), ep3_blind(), ep3_curve_clean(), ep3_curve_set_twist(), ep3_map(), ep3_norm_imp(), ep3_norm_sim(), ep3_rhs(), fp18_back_cyc(), fp18_back_cyc_sim(), fp18_sqr_cyc_basic(), fp18_sqr_cyc_lazyr(), fp18_sqr_pck_basic(), fp18_sqr_pck_lazyr(), fp3_exp(), fp3_field_init(), fp3_inv_sim(), fp3_is_sqr(), fp3_mul_frb(), fp3_mul_nor(), fp3_srt(), fp9_inv(), fp9_mul_art(), fp9_mul_basic(), fp9_mul_dxs(), fp9_mul_dxs_unr_lazyr(), fp9_mul_unr(), fp9_sqr_basic(), fp9_sqr_unr(), pp_add_k18_basic(), pp_add_k18_projc_basic(), pp_add_k18_projc_lazyr(), pp_dbl_k18_basic(), pp_dbl_k18_projc_basic(), and pp_dbl_k18_projc_lazyr().
fp3_add
#define fp3_add (C, A, B)
Value:
fp3_add_integ(C, A, B)
Adds two cubic extension field elements. Computes C = A + B.
Parameters
[out] C - the result.
[in] A - the first cubic extension field element.
[in] B - the second cubic extension field element.
Definition at line 423 of file relic_fpx.h.
Referenced by ep3_map(), ep3_rhs(), fp18_back_cyc(), fp18_back_cyc_sim(), fp18_mul_dxs_basic(), fp18_mul_dxs_lazyr(), fp18_sqr_cyc_basic(), fp18_sqr_pck_basic(), fp3_mul_nor(), fp9_add(), fp9_inv(), fp9_mul_basic(), fp9_mul_dxs(), fp9_sqr_basic(), pp_add_k18_projc_basic(), pp_add_k18_projc_lazyr(), pp_dbl_k18_projc_basic(), pp_dbl_k18_projc_lazyr(), and pp_dbl_lit_k18().
fp3_sub
#define fp3_sub (C, A, B)
Value:
fp3_sub_integ(C, A, B)
Subtracts a cubic extension field element from another. Computes C = A - B.
Parameters
[out] C - the result.
[in] A - the first cubic extension field element.
[in] B - the second cubic extension field element.
Definition at line 437 of file relic_fpx.h.
Referenced by ep3_map(), fp18_back_cyc(), fp18_back_cyc_sim(), fp18_sqr_cyc_basic(), fp18_sqr_pck_basic(), fp3_mul_nor(), fp9_inv(), fp9_mul_basic(), fp9_mul_dxs(), fp9_sqr_basic(), fp9_sub(), pp_add_k18_basic(), pp_add_k18_projc_basic(), pp_add_k18_projc_lazyr(), pp_dbl_k18_basic(), pp_dbl_k18_projc_basic(), and pp_dbl_k18_projc_lazyr().
fp3_dbl
#define fp3_dbl (C, A)
Value:
fp3_dbl_integ(C, A)
Doubles a cubic extension field element. Computes C = A + A.
Parameters
[out] C - the result.
[in] A - the cubic extension field element.
Definition at line 449 of file relic_fpx.h.
Referenced by ep3_curve_mul_a(), ep3_map(), fp18_back_cyc(), fp18_back_cyc_sim(), fp18_sqr_cyc_basic(), fp18_sqr_pck_basic(), fp3_mul_nor(), fp3_srt(), fp9_dbl(), fp9_sqr_basic(), pp_dbl_k18_projc_basic(), pp_dbl_k18_projc_lazyr(), and pp_dbl_lit_k18().
fp3_mul
#define fp3_mul (C, A, B)
Value:
fp3_mul_integ(C, A, B)
Multiplies two cubic extension field elements. Computes C = A * B.
Parameters
[out] C - the result.
[in] A - the first cubic extension field element.
[in] B - the second cubic extension field element.
Definition at line 462 of file relic_fpx.h.
Referenced by ep3_blind(), ep3_cmp(), ep3_curve_mul_a(), ep3_curve_mul_b(), ep3_frb(), ep3_map(), ep3_norm_imp(), ep3_rhs(), fp18_back_cyc(), fp18_back_cyc_sim(), fp18_mul_dxs_basic(), fp3_exp(), fp3_field_init(), fp3_inv_sim(), fp3_is_sqr(), fp3_mul_frb(), fp3_srt(), fp9_inv(), fp9_mul_basic(), fp9_mul_dxs(), fp9_sqr_basic(), pp_add_k18_basic(), pp_add_k18_projc_basic(), pp_add_k18_projc_lazyr(), pp_dbl_k18_basic(), pp_dbl_k18_projc_basic(), pp_dbl_k18_projc_lazyr(), pp_map_sim_tatep_k18(), pp_map_sim_weilp_k18(), pp_map_tatep_k18(), pp_map_weilp_k18(), pp_mil_k54(), and pp_norm_k18().
fp3_sqr
#define fp3_sqr (C, A)
Value:
fp3_sqr_integ(C, A)
Squares a cubic extension field element. Computes C = A * A.
Parameters
[out] C - the result.
[in] A - the cubic extension field element to square.
Definition at line 474 of file relic_fpx.h.
Referenced by ep3_blind(), ep3_cmp(), ep3_map(), ep3_norm_imp(), ep3_on_curve(), ep3_rhs(), fp18_back_cyc(), fp18_back_cyc_sim(), fp18_sqr_cyc_basic(), fp18_sqr_pck_basic(), fp3_exp(), fp3_field_init(), fp3_srt(), fp9_inv(), fp9_sqr_basic(), pp_add_k18_projc_basic(), pp_add_k18_projc_lazyr(), pp_dbl_k18_projc_basic(), and pp_dbl_k18_projc_lazyr().
dv4_null
#define dv4_null (A)
Value:
        dv2_null(A[0]); dv2_null(A[1]);                                     \
Initializes a double-precision quartic extension field with null.
Parameters
[out] A - the quartic extension element to initialize.
Definition at line 482 of file relic_fpx.h.
Referenced by fp12_sqr_unr(), fp24_sqr_cyc_lazyr(), fp24_sqr_pck_lazyr(), fp4_mul_lazyr(), fp4_sqr_lazyr(), fp8_mul_dxs(), fp8_mul_unr(), fp8_sqr_unr(), and pp_dbl_k16_projc_lazyr().
dv4_new
#define dv4_new (A)
Value:
        dv2_new(A[0]); dv2_new(A[1]);                                       \
Allocates a double-precision quartic extension field element.
Parameters
[out] A - the new quartic extension field element.
Definition at line 490 of file relic_fpx.h.
Referenced by fp12_sqr_unr(), fp24_sqr_cyc_lazyr(), fp24_sqr_pck_lazyr(), fp4_mul_lazyr(), fp4_sqr_lazyr(), fp8_mul_dxs(), fp8_mul_unr(), fp8_sqr_unr(), and pp_dbl_k16_projc_lazyr().
dv4_free
#define dv4_free (A)
Value:
        dv2_free(A[0]); dv2_free(A[1]);                                     \
Frees a double-precision quartic extension field element.
Parameters
[out] A - the quartic extension field element to free.
Definition at line 498 of file relic_fpx.h.
Referenced by fp12_sqr_unr(), fp24_sqr_cyc_lazyr(), fp24_sqr_pck_lazyr(), fp4_mul_lazyr(), fp4_sqr_lazyr(), fp8_mul_dxs(), fp8_mul_unr(), fp8_sqr_unr(), and pp_dbl_k16_projc_lazyr().
fp4_null
#define fp4_null (A)
Value:
        fp2_null(A[0]); fp2_null(A[1]);                                     \
Initializes a quartic extension field with null.
Parameters
[out] A - the quartic extension element to initialize.
Definition at line 506 of file relic_fpx.h.
Referenced by detect_opt(), ep4_blind(), ep4_curve_set_twist(), ep4_map(), ep4_norm_imp(), ep4_norm_sim(), ep4_rhs(), fp12_sqr_unr(), fp24_back_cyc(), fp24_back_cyc_sim(), fp24_sqr_cyc_basic(), fp24_sqr_cyc_lazyr(), fp24_sqr_pck_basic(), fp24_sqr_pck_lazyr(), fp4_exp(), fp4_field_init(), fp4_inv_sim(), fp4_is_sqr(), fp8_inv(), fp8_mul_art(), fp8_mul_basic(), fp8_mul_dxs(), fp8_mul_unr(), fp8_sqr_basic(), fp8_sqr_cyc(), fp8_sqr_unr(), fp8_srt(), pp_add_k16_basic(), pp_add_k16_projc_basic(), pp_add_k16_projc_lazyr(), pp_add_k24_basic(), pp_add_k24_projc(), pp_dbl_k16_basic(), pp_dbl_k16_projc_basic(), pp_dbl_k16_projc_lazyr(), pp_dbl_k24_basic(), and pp_dbl_k24_projc().
fp4_new
#define fp4_new (A)
Value:
        fp2_new(A[0]); fp2_new(A[1]);                                       \
Allocates a quartic extension field element.
Parameters
[out] A - the new quartic extension field element.
Definition at line 514 of file relic_fpx.h.
Referenced by detect_opt(), ep4_blind(), ep4_curve_init(), ep4_curve_set_twist(), ep4_map(), ep4_norm_imp(), ep4_norm_sim(), ep4_rhs(), fp12_sqr_unr(), fp24_back_cyc(), fp24_back_cyc_sim(), fp24_sqr_cyc_basic(), fp24_sqr_cyc_lazyr(), fp24_sqr_pck_basic(), fp24_sqr_pck_lazyr(), fp4_exp(), fp4_field_init(), fp4_inv_sim(), fp4_is_sqr(), fp8_inv(), fp8_mul_art(), fp8_mul_basic(), fp8_mul_dxs(), fp8_mul_frb(), fp8_mul_unr(), fp8_sqr_basic(), fp8_sqr_cyc(), fp8_sqr_unr(), fp8_srt(), pp_add_k16_basic(), pp_add_k16_projc_basic(), pp_add_k16_projc_lazyr(), pp_add_k24_basic(), pp_add_k24_projc(), pp_dbl_k16_basic(), pp_dbl_k16_projc_basic(), pp_dbl_k16_projc_lazyr(), pp_dbl_k24_basic(), and pp_dbl_k24_projc().
fp4_free
#define fp4_free (A)
Value:
        fp2_free(A[0]); fp2_free(A[1]);                                     \
Frees a quartic extension field element.
Parameters
[out] A - the quartic extension field element to free.
Definition at line 522 of file relic_fpx.h.
Referenced by detect_opt(), ep4_blind(), ep4_curve_clean(), ep4_curve_set_twist(), ep4_map(), ep4_norm_imp(), ep4_norm_sim(), ep4_rhs(), fp12_sqr_unr(), fp24_back_cyc(), fp24_back_cyc_sim(), fp24_sqr_cyc_basic(), fp24_sqr_cyc_lazyr(), fp24_sqr_pck_basic(), fp24_sqr_pck_lazyr(), fp4_exp(), fp4_field_init(), fp4_inv_sim(), fp4_is_sqr(), fp8_inv(), fp8_mul_art(), fp8_mul_basic(), fp8_mul_dxs(), fp8_mul_frb(), fp8_mul_unr(), fp8_sqr_basic(), fp8_sqr_cyc(), fp8_sqr_unr(), fp8_srt(), pp_add_k16_basic(), pp_add_k16_projc_basic(), pp_add_k16_projc_lazyr(), pp_add_k24_basic(), pp_add_k24_projc(), pp_dbl_k16_basic(), pp_dbl_k16_projc_basic(), pp_dbl_k16_projc_lazyr(), and pp_dbl_k24_projc().
fp4_mul
#define fp4_mul (C, A, B)
Value:
fp4_mul_lazyr(C, A, B)
Multiplies two quartic extension field elements. Computes C = A * B.
Parameters
[out] C - the result.
[in] A - the first quartic extension field element.
[in] B - the second quartic extension field element.
Definition at line 535 of file relic_fpx.h.
Referenced by ep4_blind(), ep4_cmp(), ep4_curve_mul_a(), ep4_curve_mul_b(), ep4_map(), ep4_norm_imp(), ep4_rhs(), fp16_mul_dxs_basic(), fp24_back_cyc(), fp24_back_cyc_sim(), fp4_exp(), fp4_inv_sim(), fp4_is_sqr(), fp8_inv(), fp8_mul_basic(), fp8_sqr_basic(), fp8_srt(), pp_add_k16_basic(), pp_add_k16_projc_basic(), pp_add_k16_projc_lazyr(), pp_add_k24_basic(), pp_add_k24_projc(), pp_dbl_k16_basic(), pp_dbl_k16_projc_basic(), pp_dbl_k16_projc_lazyr(), pp_dbl_k24_basic(), pp_dbl_k24_projc(), pp_norm_k16(), and pp_norm_k24().
fp4_sqr
#define fp4_sqr (C, A)
Value:
fp4_sqr_lazyr(C, A)
Squares a quartic extension field element. Computes C = A * A.
Parameters
[out] C - the result.
[in] A - the quartic extension field element to square.
Definition at line 547 of file relic_fpx.h.
Referenced by ep4_blind(), ep4_cmp(), ep4_map(), ep4_norm_imp(), ep4_on_curve(), ep4_rhs(), fp24_back_cyc(), fp24_back_cyc_sim(), fp24_sqr_cyc_basic(), fp24_sqr_cyc_lazyr(), fp24_sqr_pck_basic(), fp24_sqr_pck_lazyr(), fp4_exp(), fp8_inv(), fp8_sqr_cyc(), fp8_srt(), pp_add_k16_projc_basic(), pp_add_k16_projc_lazyr(), pp_add_k24_projc(), pp_dbl_k16_projc_basic(), pp_dbl_k16_projc_lazyr(), and pp_dbl_k24_projc().
dv6_null
#define dv6_null (A)
Value:
        dv2_null(A[0]); dv2_null(A[1]); dv2_null(A[2]);                     \
Initializes a double-precision sextic extension field with null.
Parameters
[out] A - the sextic extension element to initialize.
Definition at line 555 of file relic_fpx.h.
Referenced by fp12_mul_dxs_lazyr(), fp12_mul_unr(), fp6_mul_lazyr(), and fp6_sqr_lazyr().
dv6_new
#define dv6_new (A)
Value:
        dv2_new(A[0]); dv2_new(A[1]); dv2_new(A[2]);                        \
Allocates a double-precision sextic extension field element.
Parameters
[out] A - the new sextic extension field element.
Definition at line 563 of file relic_fpx.h.
Referenced by fp12_mul_dxs_lazyr(), fp12_mul_unr(), fp6_mul_lazyr(), and fp6_sqr_lazyr().
dv6_free
#define dv6_free (A)
Value:
        dv2_free(A[0]); dv2_free(A[1]); dv2_free(A[2]);                     \
Frees a double-precision sextic extension field element.
Parameters
[out] A - the sextic extension field element to free.
Definition at line 571 of file relic_fpx.h.
Referenced by fp12_mul_dxs_lazyr(), fp12_mul_unr(), fp6_mul_lazyr(), and fp6_sqr_lazyr().
fp6_null
#define fp6_null (A)
Value:
        fp2_null(A[0]); fp2_null(A[1]); fp2_null(A[2]);                     \
Initializes a sextic extension field with null.
Parameters
[out] A - the sextic extension element to initialize.
Definition at line 579 of file relic_fpx.h.
Referenced by fp12_inv(), fp12_mul_art(), fp12_mul_basic(), fp12_mul_dxs_basic(), fp12_mul_dxs_lazyr(), fp12_mul_unr(), fp12_sqr_basic(), and fp6_exp().
fp6_new
#define fp6_new (A)
Value:
        fp2_new(A[0]); fp2_new(A[1]); fp2_new(A[2]);                        \
Allocates a sextic extension field element.
Parameters
[out] A - the new sextic extension field element.
Definition at line 587 of file relic_fpx.h.
Referenced by fp12_inv(), fp12_mul_art(), fp12_mul_basic(), fp12_mul_dxs_basic(), fp12_mul_dxs_lazyr(), fp12_mul_unr(), fp12_sqr_basic(), and fp6_exp().
fp6_free
#define fp6_free (A)
Value:
        fp2_free(A[0]); fp2_free(A[1]); fp2_free(A[2]);                     \
Frees a sextic extension field element.
Parameters
[out] A - the sextic extension field element to free.
Definition at line 595 of file relic_fpx.h.
Referenced by fp12_inv(), fp12_mul_art(), fp12_mul_basic(), fp12_mul_dxs_basic(), fp12_mul_dxs_lazyr(), fp12_mul_unr(), fp12_sqr_basic(), and fp6_exp().
fp6_mul
#define fp6_mul (C, A, B)
Value:
fp6_mul_lazyr(C, A, B)
Multiplies two sextic extension field elements. Computes C = A * B.
Parameters
[out] C - the result.
[in] A - the first sextic extension field element.
[in] B - the second sextic extension field element.
Definition at line 608 of file relic_fpx.h.
Referenced by fp12_inv(), fp12_mul_basic(), fp12_pck_max(), fp12_sqr_basic(), and fp6_exp().
fp6_sqr
#define fp6_sqr (C, A)
Value:
fp6_sqr_lazyr(C, A)
Squares a sextic extension field element. Computes C = A * A.
Parameters
[out] C - the result.
[in] A - the sextic extension field element to square.
Definition at line 620 of file relic_fpx.h.
Referenced by fp12_inv(), and fp6_exp().
dv8_null
#define dv8_null (A)
Value:
        dv4_null(A[0]); dv4_null(A[1]);                                     \
Initializes a double-precision octic extension field with null.
Parameters
[out] A - the octic extension element to initialize.
Definition at line 628 of file relic_fpx.h.
Referenced by fp16_mul_dxs_lazyr(), fp16_mul_unr(), fp16_sqr_unr(), fp24_mul_unr(), fp24_sqr_unr(), fp48_sqr_pck_lazyr(), fp8_mul_lazyr(), and fp8_sqr_lazyr().
dv8_new
#define dv8_new (A)
Value:
        dv4_new(A[0]); dv4_new(A[1]);                                       \
Allocates a double-precision octic extension field element.
Parameters
[out] A - the new octic extension field element.
Definition at line 636 of file relic_fpx.h.
Referenced by fp16_mul_dxs_lazyr(), fp16_mul_unr(), fp16_sqr_unr(), fp24_mul_unr(), fp24_sqr_unr(), fp48_sqr_pck_lazyr(), fp8_mul_lazyr(), and fp8_sqr_lazyr().
dv8_free
#define dv8_free (A)
Value:
        dv4_free(A[0]); dv4_free(A[1]);                                     \
Frees a double-precision octic extension field element.
Parameters
[out] A - the octic extension field element to free.
Definition at line 644 of file relic_fpx.h.
Referenced by fp16_mul_dxs_lazyr(), fp16_mul_unr(), fp16_sqr_unr(), fp24_mul_unr(), fp24_sqr_unr(), fp48_sqr_pck_lazyr(), fp8_mul_lazyr(), and fp8_sqr_lazyr().
fp8_null
#define fp8_null (A)
Value:
        fp4_null(A[0]); fp4_null(A[1]);                                     \
Initializes an octic extension field with null.
Parameters
[out] A - the octic extension element to initialize.
Definition at line 652 of file relic_fpx.h.
Referenced by detect_opt(), ep8_blind(), ep8_curve_set_twist(), ep8_map(), ep8_norm_imp(), ep8_norm_sim(), ep8_rhs(), fp16_inv(), fp16_mul_art(), fp16_mul_basic(), fp16_mul_dxs_basic(), fp16_mul_dxs_lazyr(), fp16_mul_unr(), fp16_sqr_basic(), fp16_sqr_cyc(), fp16_sqr_unr(), fp16_srt(), fp24_inv(), fp24_mul_art(), fp24_mul_basic(), fp24_mul_dxs(), fp24_mul_unr(), fp24_sqr_basic(), fp24_sqr_unr(), fp48_back_cyc(), fp48_back_cyc_sim(), fp48_sqr_cyc_basic(), fp48_sqr_cyc_lazyr(), fp48_sqr_pck_basic(), fp48_sqr_pck_lazyr(), fp8_conv_cyc(), fp8_exp(), fp8_exp_cyc(), fp8_exp_cyc_sim(), fp8_exp_dig(), fp8_field_init(), fp8_inv_sim(), fp8_is_sqr(), fp8_test_cyc(), pp_add_k48_basic(), pp_add_k48_projc(), pp_dbl_k48_basic(), pp_dbl_k48_projc(), pp_exp_k8(), and pp_mil_k8().
fp8_new
#define fp8_new (A)
Value:
        fp4_new(A[0]); fp4_new(A[1]);                                       \
Allocates an octic extension field element.
Parameters
[out] A - the new octic extension field element.
Definition at line 660 of file relic_fpx.h.
Referenced by detect_opt(), ep8_blind(), ep8_curve_init(), ep8_curve_set_twist(), ep8_map(), ep8_norm_imp(), ep8_norm_sim(), ep8_rhs(), fp16_inv(), fp16_mul_art(), fp16_mul_basic(), fp16_mul_dxs_basic(), fp16_mul_dxs_lazyr(), fp16_mul_unr(), fp16_sqr_basic(), fp16_sqr_cyc(), fp16_sqr_unr(), fp16_srt(), fp24_inv(), fp24_mul_art(), fp24_mul_basic(), fp24_mul_dxs(), fp24_mul_unr(), fp24_sqr_basic(), fp24_sqr_unr(), fp48_back_cyc(), fp48_back_cyc_sim(), fp48_sqr_cyc_basic(), fp48_sqr_cyc_lazyr(), fp48_sqr_pck_basic(), fp48_sqr_pck_lazyr(), fp8_conv_cyc(), fp8_exp(), fp8_exp_cyc(), fp8_exp_cyc_sim(), fp8_exp_dig(), fp8_field_init(), fp8_inv_sim(), fp8_is_sqr(), fp8_test_cyc(), pp_add_k48_basic(), pp_add_k48_projc(), pp_dbl_k48_basic(), pp_dbl_k48_projc(), pp_exp_k8(), and pp_mil_k8().
fp8_free
#define fp8_free (A)
Value:
        fp4_free(A[0]); fp4_free(A[1]);                                     \
Frees an octic extension field element.
Parameters
[out] A - the octic extension field element to free.
Definition at line 668 of file relic_fpx.h.
Referenced by detect_opt(), ep8_blind(), ep8_curve_clean(), ep8_curve_set_twist(), ep8_map(), ep8_norm_imp(), ep8_norm_sim(), ep8_rhs(), fp16_inv(), fp16_mul_art(), fp16_mul_basic(), fp16_mul_dxs_basic(), fp16_mul_dxs_lazyr(), fp16_mul_unr(), fp16_sqr_basic(), fp16_sqr_cyc(), fp16_sqr_unr(), fp16_srt(), fp24_inv(), fp24_mul_art(), fp24_mul_basic(), fp24_mul_dxs(), fp24_mul_unr(), fp24_sqr_basic(), fp24_sqr_unr(), fp48_back_cyc(), fp48_back_cyc_sim(), fp48_sqr_cyc_basic(), fp48_sqr_cyc_lazyr(), fp48_sqr_pck_basic(), fp48_sqr_pck_lazyr(), fp8_conv_cyc(), fp8_exp(), fp8_exp_cyc(), fp8_exp_cyc_sim(), fp8_exp_dig(), fp8_field_init(), fp8_inv_sim(), fp8_is_sqr(), fp8_test_cyc(), pp_add_k48_basic(), pp_add_k48_projc(), pp_dbl_k48_basic(), pp_dbl_k48_projc(), pp_exp_k8(), and pp_mil_k8().
fp8_mul
#define fp8_mul (C, A, B)
Value:
fp8_mul_lazyr(C, A, B)
Multiplies two octic extension field elements. Computes C = A * B.
Parameters
[out] C - the result.
[in] A - the first octic extension field element.
[in] B - the second octic extension field element.
Definition at line 681 of file relic_fpx.h.
Referenced by ep8_blind(), ep8_cmp(), ep8_curve_mul_a(), ep8_curve_mul_b(), ep8_map(), ep8_norm_imp(), ep8_rhs(), fp16_inv(), fp16_mul_basic(), fp16_mul_dxs_basic(), fp16_sqr_basic(), fp16_srt(), fp24_inv(), fp24_mul_basic(), fp24_mul_dxs(), fp24_sqr_basic(), fp48_back_cyc(), fp48_back_cyc_sim(), fp48_mul_dxs(), fp8_conv_cyc(), fp8_exp(), fp8_exp_cyc(), fp8_exp_cyc_sim(), fp8_exp_dig(), fp8_inv_sim(), fp8_is_sqr(), fp8_test_cyc(), pp_add_k48_basic(), pp_add_k48_projc(), pp_dbl_k48_basic(), pp_dbl_k48_projc(), pp_exp_k8(), pp_mil_k8(), and pp_norm_k48().
fp8_sqr
#define fp8_sqr (C, A)
Value:
fp8_sqr_lazyr(C, A)
Squares an octic extension field element. Computes C = A * A.
Parameters
[out] C - the result.
[in] A - the octic extension field element to square.
Definition at line 693 of file relic_fpx.h.
Referenced by ep8_blind(), ep8_cmp(), ep8_map(), ep8_norm_imp(), ep8_on_curve(), ep8_rhs(), fp16_inv(), fp16_sqr_cyc(), fp16_srt(), fp24_inv(), fp24_sqr_basic(), fp48_back_cyc(), fp48_back_cyc_sim(), fp48_sqr_cyc_basic(), fp48_sqr_cyc_lazyr(), fp48_sqr_pck_basic(), fp48_sqr_pck_lazyr(), fp8_exp(), fp8_exp_cyc_sim(), fp8_exp_dig(), pp_add_k48_projc(), pp_dbl_k48_projc(), and pp_mil_k8().
dv9_null
#define dv9_null (A)
Value:
        dv3_null(A[0]); dv3_null(A[1]); dv3_null(A[2]);                     \
Initializes a double-precision nonic extension field with null.
Parameters
[out] A - the octic extension element to initialize.
Definition at line 701 of file relic_fpx.h.
Referenced by fp18_mul_dxs_lazyr(), fp18_mul_unr(), fp18_sqr_unr(), fp54_sqr_pck_lazyr(), fp9_mul_lazyr(), and fp9_sqr_lazyr().
dv9_new
#define dv9_new (A)
Value:
        dv3_new(A[0]); dv3_new(A[1]); dv3_new(A[2]);                        \
Allocates a double-precision nonic extension field element.
Parameters
[out] A - the new nonic extension field element.
Definition at line 709 of file relic_fpx.h.
Referenced by fp18_mul_dxs_lazyr(), fp18_mul_unr(), fp18_sqr_unr(), fp54_sqr_pck_lazyr(), fp9_mul_lazyr(), and fp9_sqr_lazyr().
dv9_free
#define dv9_free (A)
Value:
        dv3_free(A[0]); dv3_free(A[1]); dv3_free(A[2]);                     \
Frees a double-precision nonic extension field element.
Parameters
[out] A - the nonic extension field element to free.
Definition at line 717 of file relic_fpx.h.
Referenced by fp18_mul_dxs_lazyr(), fp18_mul_unr(), fp18_sqr_unr(), fp54_sqr_pck_lazyr(), fp9_mul_lazyr(), and fp9_sqr_lazyr().
fp9_null
#define fp9_null (A)
Value:
        fp3_null(A[0]); fp3_null(A[1]); fp3_null(A[2]);                     \
Initializes a nonic extension field with null.
Parameters
[out] A - the nonic extension element to initialize.
Definition at line 725 of file relic_fpx.h.
Referenced by ep9_add_basic(), ep9_dbl_basic(), fp18_inv(), fp18_mul_art(), fp18_mul_basic(), fp18_mul_dxs_basic(), fp18_mul_dxs_lazyr(), fp18_mul_unr(), fp18_sqr_basic(), fp18_sqr_unr(), fp54_back_cyc(), fp54_back_cyc_sim(), fp54_sqr_cyc_basic(), fp54_sqr_cyc_lazyr(), fp54_sqr_pck_basic(), fp54_sqr_pck_lazyr(), fp9_exp(), fp9_inv_sim(), pp_add_k54_basic(), pp_add_k54_projc(), pp_dbl_k54_basic(), pp_dbl_k54_projc(), and pp_mil_k54().
fp9_new
#define fp9_new (A)
Value:
        fp3_new(A[0]); fp3_new(A[1]); fp3_new(A[2]);                        \
Allocates a nonic extension field element.
Parameters
[out] A - the new nonic extension field element.
Definition at line 733 of file relic_fpx.h.
Referenced by ep9_add_basic(), ep9_dbl_basic(), fp18_inv(), fp18_mul_art(), fp18_mul_basic(), fp18_mul_dxs_basic(), fp18_mul_dxs_lazyr(), fp18_mul_unr(), fp18_sqr_basic(), fp18_sqr_unr(), fp54_back_cyc(), fp54_back_cyc_sim(), fp54_sqr_cyc_basic(), fp54_sqr_cyc_lazyr(), fp54_sqr_pck_basic(), fp54_sqr_pck_lazyr(), fp9_exp(), fp9_inv_sim(), pp_add_k54_basic(), pp_add_k54_projc(), pp_dbl_k54_basic(), pp_dbl_k54_projc(), and pp_mil_k54().
fp9_free
#define fp9_free (A)
Value:
        fp3_free(A[0]); fp3_free(A[1]); fp3_free(A[2]);                     \
Frees a nonic extension field element.
Parameters
[out] A - the nonic extension field element to free.
Definition at line 741 of file relic_fpx.h.
Referenced by ep9_add_basic(), ep9_dbl_basic(), fp18_inv(), fp18_mul_art(), fp18_mul_basic(), fp18_mul_dxs_basic(), fp18_mul_dxs_lazyr(), fp18_mul_unr(), fp18_sqr_basic(), fp18_sqr_unr(), fp54_back_cyc(), fp54_back_cyc_sim(), fp54_sqr_cyc_basic(), fp54_sqr_cyc_lazyr(), fp54_sqr_pck_basic(), fp54_sqr_pck_lazyr(), fp9_exp(), fp9_inv_sim(), pp_add_k54_basic(), pp_add_k54_projc(), pp_dbl_k54_basic(), pp_dbl_k54_projc(), and pp_mil_k54().
fp9_mul
#define fp9_mul (C, A, B)
Value:
fp9_mul_lazyr(C, A, B)
Multiplies two nonic extension field elements. Computes C = A * B.
Parameters
[out] C - the result.
[in] A - the first nonic extension field element.
[in] B - the second nonic extension field element.
Definition at line 754 of file relic_fpx.h.
Referenced by ep9_add_basic(), ep9_dbl_basic(), fp18_inv(), fp18_mul_basic(), fp18_sqr_basic(), fp54_back_cyc(), fp54_back_cyc_sim(), fp54_mul_dxs(), fp9_exp(), fp9_inv_sim(), pp_add_k54_basic(), pp_add_k54_projc(), pp_dbl_k54_basic(), pp_dbl_k54_projc(), and pp_mil_k54().
fp9_sqr
#define fp9_sqr (C, A)
Value:
fp9_sqr_lazyr(C, A)
Squares a nonic extension field element. Computes C = A * A.
Parameters
[out] C - the result.
[in] A - the nonic extension field element to square.
Definition at line 766 of file relic_fpx.h.
Referenced by ep9_add_basic(), ep9_dbl_basic(), fp18_inv(), fp54_back_cyc(), fp54_back_cyc_sim(), fp54_sqr_cyc_basic(), fp54_sqr_cyc_lazyr(), fp54_sqr_pck_basic(), fp54_sqr_pck_lazyr(), fp9_exp(), pp_add_k54_projc(), and pp_dbl_k54_projc().
dv12_null
#define dv12_null (A)
Value:
        dv6_null(A[0]); dv6_null(A[1]);                                     \
Initializes a double-precision dodecic extension field with null.
Parameters
[out] A - the dodecic extension element to initialize.
Definition at line 774 of file relic_fpx.h.
Referenced by fp12_mul_lazyr(), and fp12_sqr_lazyr().
dv12_new
#define dv12_new (A)
Value:
        dv6_new(A[0]); dv6_new(A[1]);                                       \
Allocates a double-precision dodecic extension field element.
Parameters
[out] A - the new dodecic extension field element.
Definition at line 782 of file relic_fpx.h.
Referenced by fp12_mul_lazyr(), and fp12_sqr_lazyr().
dv12_free
#define dv12_free (A)
Value:
        dv6_free(A[0]); dv6_free(A[1]);                                     \
Frees a double-precision dodecic extension field element.
Parameters
[out] A - the dodecic extension field element to free.
Definition at line 790 of file relic_fpx.h.
Referenced by fp12_mul_lazyr(), and fp12_sqr_lazyr().
fp12_null
#define fp12_null (A)
Value:
        fp6_null(A[0]); fp6_null(A[1]);                                     \
Initializes a dodecic extension field with null.
Parameters
[out] A - the dodecic extension element to initialize.
Definition at line 798 of file relic_fpx.h.
Referenced by fp12_conv_cyc(), fp12_exp(), fp12_exp_cyc(), fp12_exp_cyc_sim(), fp12_exp_cyc_sps(), fp12_exp_dig(), fp12_test_cyc(), fp12_upk_max(), fp12_write_bin(), pp_exp_b12(), pp_exp_bn(), pp_exp_sm9(), pp_fin_k12_oatep(), pp_map_sim_weilp_k12(), pp_map_weilp_k12(), pp_mil_k12(), and pp_mil_lit_k12().
fp12_new
#define fp12_new (A)
Value:
        fp6_new(A[0]); fp6_new(A[1]);                                       \
Allocates a dodecic extension field element.
Parameters
[out] A - the new dodecic extension field element.
Definition at line 806 of file relic_fpx.h.
Referenced by fp12_conv_cyc(), fp12_exp(), fp12_exp_cyc(), fp12_exp_cyc_sim(), fp12_exp_cyc_sps(), fp12_exp_dig(), fp12_test_cyc(), fp12_upk_max(), fp12_write_bin(), pp_exp_b12(), pp_exp_bn(), pp_exp_sm9(), pp_fin_k12_oatep(), pp_map_sim_weilp_k12(), pp_map_weilp_k12(), pp_mil_k12(), and pp_mil_lit_k12().
fp12_free
#define fp12_free (A)
Value:
        fp6_free(A[0]); fp6_free(A[1]);                                     \
Frees a dodecic extension field element.
Parameters
[out] A - the dodecic extension field element to free.
Definition at line 814 of file relic_fpx.h.
Referenced by fp12_conv_cyc(), fp12_exp(), fp12_exp_cyc(), fp12_exp_cyc_sim(), fp12_exp_cyc_sps(), fp12_exp_dig(), fp12_test_cyc(), fp12_upk_max(), fp12_write_bin(), pp_exp_b12(), pp_exp_bn(), pp_exp_sm9(), pp_fin_k12_oatep(), pp_map_sim_weilp_k12(), pp_map_weilp_k12(), pp_mil_k12(), and pp_mil_lit_k12().
fp12_mul
#define fp12_mul (C, A, B)
Value:
fp12_mul_lazyr(C, A, B)
Multiplies two dodecic extension field elements. Computes C = A * B.
Parameters
[out] C - the result.
[in] A - the first dodecic extension field element.
[in] B - the second dodecic extension field element.
Definition at line 827 of file relic_fpx.h.
Referenced by fp12_conv_cyc(), fp12_exp(), fp12_exp_cyc(), fp12_exp_cyc_sim(), fp12_exp_cyc_sps(), fp12_exp_dig(), fp12_test_cyc(), fp12_upk_max(), pp_exp_b12(), pp_exp_bn(), pp_exp_sm9(), pp_map_sim_weilp_k12(), pp_map_weilp_k12(), and pp_mil_lit_k12().
fp12_mul_dxs
#define fp12_mul_dxs (C, A, B)
Value:
fp12_mul_dxs_lazyr(C, A, B)
Multiplies a dense and a sparse dodecic extension field elements. Computes C = A * B.
Parameters
[out] C - the result.
[in] A - the dense dodecic extension field element.
[in] B - the sparse dodecic extension field element.
Definition at line 841 of file relic_fpx.h.
Referenced by pp_fin_k12_oatep(), and pp_mil_k12().
fp12_sqr
#define fp12_sqr (C, A)
Value:
fp12_sqr_lazyr(C, A)
Squares a dodecic extension field element. Computes C = A * A.
Parameters
[out] C - the result.
[in] A - the dodecic extension field element to square.
Definition at line 853 of file relic_fpx.h.
Referenced by fp12_exp(), fp12_exp_dig(), pp_mil_k12(), and pp_mil_lit_k12().
fp12_sqr_cyc
#define fp12_sqr_cyc (C, A)
Value:
fp12_sqr_cyc_lazyr(C, A)
Squares a dodecic extension field element in the cyclotomic subgroup. Computes C = A * A.
Parameters
[out] C - the result.
[in] A - the dodecic extension field element to square.
Definition at line 866 of file relic_fpx.h.
Referenced by fp12_exp_cyc(), fp12_exp_cyc_sim(), fp12_exp_dig(), pp_exp_b12(), pp_exp_bn(), and pp_exp_sm9().
fp12_sqr_pck
#define fp12_sqr_pck (C, A)
Value:
fp12_sqr_pck_lazyr(C, A)
Squares a dodecic extension field element in the cyclotomic subgroup in compressed form. Computes C = A * A.
Parameters
[out] C - the result.
[in] A - the dodecic extension field element to square.
Definition at line 879 of file relic_fpx.h.
Referenced by fp12_exp_cyc(), and fp12_exp_cyc_sps().
dv16_null
#define dv16_null (A)
Value:
        dv8_null(A[0]); dv8_null(A[1]);                                     \
Initializes a double-precision sextadecic extension field with null.
Parameters
[out] A - the sextadecic extension element to initialize.
Definition at line 887 of file relic_fpx.h.
Referenced by fp16_mul_dxs_lazyr(), fp16_mul_lazyr(), and fp16_sqr_lazyr().
dv16_new
#define dv16_new (A)
Value:
        dv8_new(A[0]); dv8_new(A[1]);                                       \
Allocates a double-precision sextadecic extension field element.
Parameters
[out] A - the new sextadecic extension field element.
Definition at line 895 of file relic_fpx.h.
Referenced by fp16_mul_dxs_lazyr(), fp16_mul_lazyr(), and fp16_sqr_lazyr().
dv16_free
#define dv16_free (A)
Value:
        dv8_free(A[0]); dv8_free(A[1]);                                     \
Frees a double-precision sextadecic extension field element.
Parameters
[out] A - the sextadecic extension field element to free.
Definition at line 903 of file relic_fpx.h.
Referenced by fp16_mul_dxs_lazyr(), fp16_mul_lazyr(), and fp16_sqr_lazyr().
fp16_null
#define fp16_null (A)
Value:
        fp8_null(A[0]); fp8_null(A[1]);                                     \
Initializes an sextadecic extension field with null.
Parameters
[out] A - the sextadecic extension element to initialize.
Definition at line 911 of file relic_fpx.h.
Referenced by fp16_conv_cyc(), fp16_exp(), fp16_exp_cyc(), fp16_exp_cyc_sim(), fp16_exp_dig(), fp16_inv_sim(), fp16_is_sqr(), fp16_test_cyc(), pp_exp_afg16(), pp_exp_fm16(), pp_exp_kss(), pp_fin_k16_oatep(), pp_map_sim_weilp_k16(), pp_map_weilp_k16(), pp_mil_k16(), and pp_mil_lit_k16().
fp16_new
#define fp16_new (A)
Value:
        fp8_new(A[0]); fp8_new(A[1]);                                       \
Allocates an sextadecic extension field element.
Parameters
[out] A - the new sextadecic extension field element.
Definition at line 919 of file relic_fpx.h.
Referenced by fp16_conv_cyc(), fp16_exp(), fp16_exp_cyc(), fp16_exp_cyc_sim(), fp16_exp_dig(), fp16_inv_sim(), fp16_is_sqr(), fp16_test_cyc(), pp_exp_afg16(), pp_exp_fm16(), pp_exp_kss(), pp_fin_k16_oatep(), pp_map_sim_weilp_k16(), pp_map_weilp_k16(), pp_mil_k16(), and pp_mil_lit_k16().
fp16_free
#define fp16_free (A)
Value:
        fp8_free(A[0]); fp8_free(A[1]);                                     \
Frees an sextadecic extension field element.
Parameters
[out] A - the sextadecic extension field element to free.
Definition at line 927 of file relic_fpx.h.
Referenced by fp16_conv_cyc(), fp16_exp(), fp16_exp_cyc(), fp16_exp_cyc_sim(), fp16_exp_dig(), fp16_inv_sim(), fp16_is_sqr(), fp16_test_cyc(), pp_exp_afg16(), pp_exp_fm16(), pp_exp_kss(), pp_fin_k16_oatep(), pp_map_sim_weilp_k16(), pp_map_weilp_k16(), pp_mil_k16(), and pp_mil_lit_k16().
fp16_mul
#define fp16_mul (C, A, B)
Value:
fp16_mul_lazyr(C, A, B)
Multiplies two sextadecic extension field elements. Computes C = A * B.
Parameters
[out] C - the result.
[in] A - the first sextadecic extension field element.
[in] B - the second sextadecic extension field element.
Definition at line 940 of file relic_fpx.h.
Referenced by fp16_conv_cyc(), fp16_exp(), fp16_exp_cyc(), fp16_exp_cyc_sim(), fp16_exp_dig(), fp16_inv_sim(), fp16_is_sqr(), fp16_test_cyc(), pp_exp_afg16(), pp_exp_fm16(), pp_exp_kss(), pp_map_sim_weilp_k16(), pp_map_weilp_k16(), and pp_mil_lit_k16().
fp16_mul_dxs
#define fp16_mul_dxs (C, A, B)
Value:
fp16_mul_dxs_lazyr(C, A, B)
Multiplies a dense and a sparse sextic extension field elements. Computes C = A * B.
Parameters
[out] C - the result.
[in] A - the dense dodecic extension field element.
[in] B - the sparse dodecic extension field element.
Definition at line 954 of file relic_fpx.h.
Referenced by pp_fin_k16_oatep(), and pp_mil_k16().
fp16_sqr
#define fp16_sqr (C, A)
Value:
fp16_sqr_lazyr(C, A)
Squares an sextadecic extension field element. Computes C = A * A.
Parameters
[out] C - the result.
[in] A - the sextadecic extension field element to square.
Definition at line 966 of file relic_fpx.h.
Referenced by fp16_exp(), fp16_exp_cyc_sim(), fp16_exp_dig(), pp_map_sim_weilp_k16(), pp_map_weilp_k16(), pp_mil_k16(), and pp_mil_lit_k16().
dv18_null
#define dv18_null (A)
Value:
        dv9_null(A[0]); dv9_null(A[1]);                                     \
Initializes a double-precision sextic extension field with null.
Parameters
[out] A - the sextic extension element to initialize.
Definition at line 974 of file relic_fpx.h.
Referenced by fp18_mul_lazyr(), and fp18_sqr_lazyr().
dv18_new
#define dv18_new (A)
Value:
        dv9_new(A[0]); dv9_new(A[1]);                                       \
Allocates a double-precision sextic extension field element.
Parameters
[out] A - the new sextic extension field element.
Definition at line 982 of file relic_fpx.h.
Referenced by fp18_mul_lazyr(), and fp18_sqr_lazyr().
dv18_free
#define dv18_free (A)
Value:
        dv9_free(A[0]); dv9_free(A[1]);                                     \
Frees a double-precision sextic extension field element.
Parameters
[out] A - the sextic extension field element to free.
Definition at line 990 of file relic_fpx.h.
Referenced by fp18_mul_lazyr(), and fp18_sqr_lazyr().
fp18_null
#define fp18_null (A)
Value:
        fp9_null(A[0]); fp9_null(A[1]);                                     \
Initializes an octdecic extension field with null.
Parameters
[out] A - the octdecic extension element to initialize.
Definition at line 998 of file relic_fpx.h.
Referenced by ep3_curve_set_twist(), fp18_conv_cyc(), fp18_exp(), fp18_exp_cyc(), fp18_exp_cyc_sim(), fp18_exp_cyc_sps(), fp18_exp_dig(), fp18_test_cyc(), fp18_write_bin(), fp54_inv(), fp54_mul_art(), fp54_mul_basic(), fp54_mul_dxs(), fp54_mul_lazyr(), fp54_sqr_basic(), fp54_sqr_lazyr(), pp_exp_fm(), pp_exp_kss(), pp_exp_sg(), pp_fin_k18_oatep(), pp_map_sim_weilp_k18(), pp_map_weilp_k18(), pp_mil_k18(), and pp_mil_lit_k18().
fp18_new
#define fp18_new (A)
Value:
        fp9_new(A[0]); fp9_new(A[1]);                                       \
Allocates an octdecic extension field element.
Parameters
[out] A - the new octdecic extension field element.
Definition at line 1006 of file relic_fpx.h.
Referenced by ep3_curve_set_twist(), fp18_conv_cyc(), fp18_exp(), fp18_exp_cyc(), fp18_exp_cyc_sim(), fp18_exp_cyc_sps(), fp18_exp_dig(), fp18_test_cyc(), fp18_write_bin(), fp54_inv(), fp54_mul_art(), fp54_mul_basic(), fp54_mul_dxs(), fp54_mul_lazyr(), fp54_sqr_basic(), fp54_sqr_lazyr(), pp_exp_fm(), pp_exp_kss(), pp_exp_sg(), pp_fin_k18_oatep(), pp_map_sim_weilp_k18(), pp_map_weilp_k18(), pp_mil_k18(), and pp_mil_lit_k18().
fp18_free
#define fp18_free (A)
Value:
        fp9_free(A[0]); fp9_free(A[1]);                                     \
Frees an octdecic extension field element.
Parameters
[out] A - the octdecic extension field element to free.
Definition at line 1014 of file relic_fpx.h.
Referenced by ep3_curve_set_twist(), fp18_conv_cyc(), fp18_exp(), fp18_exp_cyc(), fp18_exp_cyc_sim(), fp18_exp_cyc_sps(), fp18_exp_dig(), fp18_test_cyc(), fp18_write_bin(), fp54_inv(), fp54_mul_art(), fp54_mul_basic(), fp54_mul_dxs(), fp54_mul_lazyr(), fp54_sqr_basic(), fp54_sqr_lazyr(), pp_exp_fm(), pp_exp_kss(), pp_exp_sg(), pp_fin_k18_oatep(), pp_map_sim_weilp_k18(), pp_map_weilp_k18(), pp_mil_k18(), and pp_mil_lit_k18().
fp18_mul
#define fp18_mul (C, A, B)
Value:
fp18_mul_lazyr(C, A, B)
Multiplies two octdecic extension field elements. Computes C = A * B.
Parameters
[out] C - the result.
[in] A - the first octdecic extension field element.
[in] B - the second octdecic extension field element.
Definition at line 1027 of file relic_fpx.h.
Referenced by fp18_conv_cyc(), fp18_exp(), fp18_exp_cyc(), fp18_exp_cyc_sim(), fp18_exp_cyc_sps(), fp18_exp_dig(), fp18_test_cyc(), fp54_inv(), fp54_mul_basic(), fp54_mul_dxs(), fp54_mul_lazyr(), fp54_sqr_basic(), fp54_sqr_lazyr(), pp_exp_fm(), pp_exp_kss(), pp_exp_sg(), pp_fin_k18_oatep(), pp_map_sim_weilp_k18(), pp_map_weilp_k18(), and pp_mil_lit_k18().
fp18_mul_dxs
#define fp18_mul_dxs (C, A, B)
Value:
fp18_mul_dxs_lazyr(C, A, B)
Multiplies a dense and a sparse octdecic extension field elements. Computes C = A * B.
Parameters
[out] C - the result.
[in] A - the dense octdecic extension field element.
[in] B - the sparse octdecic extension field element.
Definition at line 1041 of file relic_fpx.h.
Referenced by fp54_mul_dxs(), pp_fin_k18_oatep(), and pp_mil_k18().
fp18_sqr
#define fp18_sqr (C, A)
Value:
fp18_sqr_lazyr(C, A)
Squares an octdecic extension field element. Computes C = A * A.
Parameters
[out] C - the result.
[in] A - the octdecic extension field element to square.
Definition at line 1053 of file relic_fpx.h.
Referenced by fp18_exp(), fp18_exp_cyc_sim(), fp18_exp_dig(), fp54_inv(), fp54_sqr_basic(), fp54_sqr_lazyr(), pp_exp_sg(), pp_map_sim_weilp_k18(), pp_map_weilp_k18(), pp_mil_k18(), and pp_mil_lit_k18().
fp18_sqr_cyc
#define fp18_sqr_cyc (C, A)
Value:
fp18_sqr_cyc_lazyr(C, A)
Squares an octdecic extension field element in the cyclotomic subgroup. Computes C = A * A.
Parameters
[out] C - the result.
[in] A - the an octdecic extension field element to square.
Definition at line 1066 of file relic_fpx.h.
Referenced by fp18_exp_cyc(), fp18_exp_dig(), pp_exp_fm(), pp_exp_kss(), and pp_exp_sg().
fp18_sqr_pck
#define fp18_sqr_pck (C, A)
Value:
fp18_sqr_pck_lazyr(C, A)
Squares an octdecic extension field element in the cyclotomic subgroup in compressed form. Computes C = A * A.
Parameters
[out] C - the result.
[in] A - the octdecic extension field element to square.
Definition at line 1079 of file relic_fpx.h.
Referenced by fp18_exp_cyc(), and fp18_exp_cyc_sps().
dv24_null
#define dv24_null (A)
Value:
        dv8_null(A[0]); dv8_null(A[1]); dv8_null(A[2]);                     \
Initializes a double-precision 24-degree extension field with null.
Parameters
[out] A - the 24-degree extension element to initialize.
Definition at line 1087 of file relic_fpx.h.
Referenced by fp24_mul_lazyr(), and fp24_sqr_lazyr().
dv24_new
#define dv24_new (A)
Value:
        dv8_new(A[0]); dv8_new(A[1]); dv8_new(A[2]);                        \
Allocates a double-precision 24-degree extension field element.
Parameters
[out] A - the new 24-degree extension field element.
Definition at line 1095 of file relic_fpx.h.
Referenced by fp24_mul_lazyr(), and fp24_sqr_lazyr().
dv24_free
#define dv24_free (A)
Value:
        dv8_free(A[0]); dv8_free(A[1]); dv8_free(A[2]);                     \
Frees a double-precision 24-degree extension field element.
Parameters
[out] A - the 24-degree extension field element to free.
Definition at line 1103 of file relic_fpx.h.
Referenced by fp24_mul_lazyr(), and fp24_sqr_lazyr().
fp24_null
#define fp24_null (A)
Value:
        fp8_null(A[0]); fp8_null(A[1]); fp8_null(A[2]);                     \
Initializes a 24-degree extension field with null.
Parameters
[out] A - the 24-degree extension element to initialize.
Definition at line 1111 of file relic_fpx.h.
Referenced by fp24_conv_cyc(), fp24_exp(), fp24_exp_cyc(), fp24_exp_cyc_sim(), fp24_exp_cyc_sps(), fp24_exp_dig(), fp24_test_cyc(), fp24_write_bin(), fp48_inv(), fp48_mul_art(), fp48_mul_basic(), fp48_mul_dxs(), fp48_mul_lazyr(), fp48_sqr_basic(), fp48_sqr_lazyr(), pp_exp_k24(), and pp_mil_k24().
fp24_new
#define fp24_new (A)
Value:
        fp8_new(A[0]); fp8_new(A[1]); fp8_new(A[2]);                        \
Allocates a 24-degree extension field element.
Parameters
[out] A - the new 24-degree extension field element.
Definition at line 1119 of file relic_fpx.h.
Referenced by fp24_conv_cyc(), fp24_exp(), fp24_exp_cyc(), fp24_exp_cyc_sim(), fp24_exp_cyc_sps(), fp24_exp_dig(), fp24_test_cyc(), fp24_write_bin(), fp48_inv(), fp48_mul_art(), fp48_mul_basic(), fp48_mul_dxs(), fp48_mul_lazyr(), fp48_sqr_basic(), fp48_sqr_lazyr(), pp_exp_k24(), and pp_mil_k24().
fp24_free
#define fp24_free (A)
Value:
        fp8_free(A[0]); fp8_free(A[1]); fp8_free(A[2]);                     \
Frees a 24-degree extension field element.
Parameters
[out] A - the 24-degree extension field element to free.
Definition at line 1127 of file relic_fpx.h.
Referenced by fp24_conv_cyc(), fp24_exp(), fp24_exp_cyc(), fp24_exp_cyc_sim(), fp24_exp_cyc_sps(), fp24_exp_dig(), fp24_test_cyc(), fp24_write_bin(), fp48_inv(), fp48_mul_art(), fp48_mul_basic(), fp48_mul_dxs(), fp48_mul_lazyr(), fp48_sqr_basic(), fp48_sqr_lazyr(), pp_exp_k24(), and pp_mil_k24().
fp24_mul
#define fp24_mul (C, A, B)
Value:
fp24_mul_lazyr(C, A, B)
Multiplies two 24-degree extension field elements. Computes C = A * B.
Parameters
[out] C - the result.
[in] A - the first 24-degree extension field element.
[in] B - the second 24-degree extension field element.
Definition at line 1140 of file relic_fpx.h.
Referenced by fp24_conv_cyc(), fp24_exp(), fp24_exp_cyc(), fp24_exp_cyc_sim(), fp24_exp_cyc_sps(), fp24_exp_dig(), fp24_test_cyc(), fp48_inv(), fp48_mul_basic(), fp48_mul_lazyr(), fp48_sqr_basic(), fp48_sqr_lazyr(), and pp_exp_k24().
fp24_sqr
#define fp24_sqr (C, A)
Value:
fp24_sqr_lazyr(C, A)
Squares a 24-degree extension field element. Computes C = A * A.
Parameters
[out] C - the result.
[in] A - the 24-degree extension field element to square.
Definition at line 1152 of file relic_fpx.h.
Referenced by fp24_exp(), fp24_exp_cyc_sim(), fp24_exp_dig(), fp48_inv(), and pp_mil_k24().
fp24_sqr_cyc
#define fp24_sqr_cyc (C, A)
Value:
fp24_sqr_cyc_lazyr(C, A)
Squares a 24-degree extension field element in the cyclotomic subgroup. Computes C = A * A.
Parameters
[out] C - the result.
[in] A - the 24-degree extension field element to square.
Definition at line 1165 of file relic_fpx.h.
Referenced by fp24_exp_cyc(), fp24_exp_dig(), and pp_exp_k24().
fp24_sqr_pck
#define fp24_sqr_pck (C, A)
Value:
fp24_sqr_pck_lazyr(C, A)
Squares a 24-degree extension field element in the cyclotomic subgroup in compressed form. Computes C = A * A.
Parameters
[out] C - the result.
[in] A - the 24-degree extension field element to square.
Definition at line 1178 of file relic_fpx.h.
Referenced by fp24_exp_cyc(), and fp24_exp_cyc_sps().
dv48_null
#define dv48_null (A)
Value:
        dv24_null(A[0]); dv24_null(A[1]);                                   \
Initializes a double-precision 48-degree extension field with null.
Parameters
[out] A - the 48-degree extension element to initialize.
Definition at line 1186 of file relic_fpx.h.
dv48_new
#define dv48_new (A)
Value:
        dv24_new(A[0]); dv24_new(A[1]);                                     \
Allocates a double-precision 48-degree extension field element.
Parameters
[out] A - the new 48-degree extension field element.
Definition at line 1194 of file relic_fpx.h.
dv48_free
#define dv48_free (A)
Value:
        dv24_free(A[0]); dv24_free(A[1]);                                   \
Frees a double-precision 48-degree extension field element.
Parameters
[out] A - the 48-degree extension field element to free.
Definition at line 1202 of file relic_fpx.h.
fp48_null
#define fp48_null (A)
Value:
        fp24_null(A[0]); fp24_null(A[1]);                                   \
Initializes a 48-degree extension field with null.
Parameters
[out] A - the 48-degree extension element to initialize.
Definition at line 1210 of file relic_fpx.h.
Referenced by fp48_conv_cyc(), fp48_exp(), fp48_exp_cyc(), fp48_exp_cyc_sim(), fp48_exp_cyc_sps(), fp48_exp_dig(), fp48_test_cyc(), fp48_write_bin(), pp_exp_k48(), and pp_mil_k48().
fp48_new
#define fp48_new (A)
Value:
        fp24_new(A[0]); fp24_new(A[1]);                                     \
Allocates a 48-degree extension field element.
Parameters
[out] A - the new 48-degree extension field element.
Definition at line 1218 of file relic_fpx.h.
Referenced by fp48_conv_cyc(), fp48_exp(), fp48_exp_cyc(), fp48_exp_cyc_sim(), fp48_exp_cyc_sps(), fp48_exp_dig(), fp48_test_cyc(), fp48_write_bin(), pp_exp_k48(), and pp_mil_k48().
fp48_free
#define fp48_free (A)
Value:
        fp24_free(A[0]); fp24_free(A[1]);                                   \
Frees a 48-degree extension field element.
Parameters
[out] A - the 48-degree extension field element to free.
Definition at line 1226 of file relic_fpx.h.
Referenced by fp48_conv_cyc(), fp48_exp(), fp48_exp_cyc(), fp48_exp_cyc_sim(), fp48_exp_cyc_sps(), fp48_exp_dig(), fp48_test_cyc(), fp48_write_bin(), pp_exp_k48(), and pp_mil_k48().
fp48_mul
#define fp48_mul (C, A, B)
Value:
fp48_mul_lazyr(C, A, B)
Multiplies two 48-degree extension field elements. Computes C = A * B.
Parameters
[out] C - the result.
[in] A - the first 48-degree extension field element.
[in] B - the second 48-degree extension field element.
Definition at line 1239 of file relic_fpx.h.
Referenced by fp48_conv_cyc(), fp48_exp(), fp48_exp_cyc(), fp48_exp_cyc_sim(), fp48_exp_cyc_sps(), fp48_exp_dig(), fp48_test_cyc(), and pp_exp_k48().
fp48_sqr
#define fp48_sqr (C, A)
Value:
fp48_sqr_lazyr(C, A)
Squares a 48-degree extension field element. Computes C = A * A.
Parameters
[out] C - the result.
[in] A - the 48-degree extension field element to square.
Definition at line 1251 of file relic_fpx.h.
Referenced by fp48_exp(), fp48_exp_cyc_sim(), fp48_exp_dig(), and pp_mil_k48().
fp48_sqr_cyc
#define fp48_sqr_cyc (C, A)
Value:
fp48_sqr_cyc_lazyr(C, A)
Squares a 48-degree extension field element in the cyclotomic subgroup. Computes C = A * A.
Parameters
[out] C - the result.
[in] A - the 48-degree extension field element to square.
Definition at line 1264 of file relic_fpx.h.
Referenced by fp48_exp_cyc(), fp48_exp_dig(), and pp_exp_k48().
fp48_sqr_pck
#define fp48_sqr_pck (C, A)
Value:
fp48_sqr_pck_lazyr(C, A)
Squares a 48-degree extension field element in the cyclotomic subgroup in compressed form. Computes C = A * A.
Parameters
[out] C - the result.
[in] A - the 48-degree extension field element to square.
Definition at line 1277 of file relic_fpx.h.
Referenced by fp48_exp_cyc(), and fp48_exp_cyc_sps().
dv54_null
#define dv54_null (A)
Value:
        dv18_null(A[0]); dv18_null(A[1]); dv18_null(A[2]);                  \
Initializes a double-precision 54-degree extension field with null.
Parameters
[out] A - the 54-degree extension element to initialize.
Definition at line 1285 of file relic_fpx.h.
dv54_new
#define dv54_new (A)
Value:
        dv18_new(A[0]); dv18_new(A[1]); dv18_new(A[2]);                     \
Allocates a double-precision 54-degree extension field element.
Parameters
[out] A - the new 54-degree extension field element.
Definition at line 1293 of file relic_fpx.h.
dv54_free
#define dv54_free (A)
Value:
        dv18_free(A[0]); dv18_free(A[1]); dv18_free(A[2]);                  \
Frees a double-precision 54-degree extension field element.
Parameters
[out] A - the 54-degree extension field element to free.
Definition at line 1301 of file relic_fpx.h.
fp54_null
#define fp54_null (A)
Value:
        fp18_null(A[0]); fp18_null(A[1]); fp18_null(A[2]);                  \
Initializes a 54-degree extension field with null.
Parameters
[out] A - the 54-degree extension element to initialize.
Definition at line 1309 of file relic_fpx.h.
Referenced by fp54_conv_cyc(), fp54_exp(), fp54_exp_cyc(), fp54_exp_cyc_sps(), fp54_exp_dig(), fp54_test_cyc(), fp54_write_bin(), pp_exp_k54(), and pp_mil_k54().
fp54_new
#define fp54_new (A)
Value:
        fp18_new(A[0]); fp18_new(A[1]); fp18_new(A[2]);                     \
Allocates a 54-degree extension field element.
Parameters
[out] A - the new 54-degree extension field element.
Definition at line 1317 of file relic_fpx.h.
Referenced by fp54_conv_cyc(), fp54_exp(), fp54_exp_cyc(), fp54_exp_cyc_sps(), fp54_exp_dig(), fp54_test_cyc(), fp54_write_bin(), pp_exp_k54(), and pp_mil_k54().
fp54_free
#define fp54_free (A)
Value:
        fp18_free(A[0]); fp18_free(A[1]); fp18_free(A[2]);                  \
Frees a 54-degree extension field element.
Parameters
[out] A - the 54-degree extension field element to free.
Definition at line 1325 of file relic_fpx.h.
Referenced by fp54_conv_cyc(), fp54_exp(), fp54_exp_cyc(), fp54_exp_cyc_sps(), fp54_exp_dig(), fp54_test_cyc(), fp54_write_bin(), pp_exp_k54(), and pp_mil_k54().
fp54_mul
#define fp54_mul (C, A, B)
Value:
fp54_mul_lazyr(C, A, B)
Multiplies two 54-degree extension field elements. Computes C = A * B.
Parameters
[out] C - the result.
[in] A - the first 54-degree extension field element.
[in] B - the second 54-degree extension field element.
Definition at line 1338 of file relic_fpx.h.
Referenced by fp54_conv_cyc(), fp54_exp(), fp54_exp_cyc(), fp54_exp_cyc_sps(), fp54_exp_dig(), fp54_test_cyc(), pp_exp_k54(), and pp_mil_k54().
fp54_sqr
#define fp54_sqr (C, A)
Value:
fp54_sqr_lazyr(C, A)
Squares a 54-degree extension field element. Computes C = A * A.
Parameters
[out] C - the result.
[in] A - the 54-degree extension field element to square.
Definition at line 1350 of file relic_fpx.h.
Referenced by fp54_exp(), fp54_exp_dig(), pp_exp_k54(), and pp_mil_k54().
fp54_sqr_cyc
#define fp54_sqr_cyc (C, A)
Value:
fp54_sqr_cyc_lazyr(C, A)
Squares a 54-degree extension field element in the cyclotomic subgroup. Computes C = A * A.
Parameters
[out] C - the result.
[in] A - the 54-degree extension field element to square.
Definition at line 1363 of file relic_fpx.h.
Referenced by fp54_exp_cyc(), fp54_exp_dig(), and pp_exp_k54().
fp54_sqr_pck
#define fp54_sqr_pck (C, A)
Value:
fp54_sqr_pck_lazyr(C, A)
Squares a 54-degree extension field element in the cyclotomic subgroup in compressed form. Computes C = A * A.
Parameters
[out] C - the result.
[in] A - the 54-degree extension field element to square.
Definition at line 1376 of file relic_fpx.h.
Referenced by fp54_exp_cyc(), and fp54_exp_cyc_sps().
Typedef Documentation
fp2_t
typedef fp_t fp2_t[2]
Represents a quadratic extension prime field element.
This extension is constructed with the basis {1, i}, where i is an adjoined square root in the prime field.
Definition at line 52 of file relic_fpx.h.
dv2_t
typedef dv_t dv2_t[2]
Represents a double-precision quadratic extension field element.
Definition at line 57 of file relic_fpx.h.
fp2_st
typedef fp_st fp2_st[2]
Represents a quadratic extension field element with automatic memory allocation.
Definition at line 63 of file relic_fpx.h.
fp3_t
typedef fp_t fp3_t[3]
Represents a cubic extension prime field element.
This extension is constructed with the basis {1, j, j^2}, where j is an adjoined cube root in the prime field.
Definition at line 71 of file relic_fpx.h.
dv3_t
typedef dv_t dv3_t[3]
Represents a double-precision cubic extension field element.
Definition at line 76 of file relic_fpx.h.
fp3_st
typedef fp_st fp3_st[3]
Represents a cubic extension field element with automatic memory allocation.
Definition at line 82 of file relic_fpx.h.
fp4_t
typedef fp2_t fp4_t[2]
Represents a quartic extension prime field element.
This extension is constructed with the basis {1, s}, where s^2 = E is an adjoined root in the underlying quadratic extension.
Definition at line 90 of file relic_fpx.h.
dv4_t
typedef dv2_t dv4_t[2]
Represents a double-precision quartic extension field element.
Definition at line 95 of file relic_fpx.h.
fp4_st
typedef fp2_st fp4_st[2]
Represents a quartic extension field element with automatic memory allocation.
Definition at line 101 of file relic_fpx.h.
fp6_t
typedef fp2_t fp6_t[3]
Represents a sextic extension field element.
This extension is constructed with the basis {1, v, v^2}, where v^3 = E is an adjoined root in the underlying quadratic extension.
Definition at line 109 of file relic_fpx.h.
dv6_t
typedef dv2_t dv6_t[3]
Represents a double-precision sextic extension field element.
Definition at line 114 of file relic_fpx.h.
fp6_st
typedef fp2_st fp6_st[3]
Represents a sextic extension field element with automatic memory allocation.
Definition at line 119 of file relic_fpx.h.
fp8_t
typedef fp4_t fp8_t[2]
Represents an octic extension prime field element.
This extension is constructed with the basis {1, v}, where v^2 = s is an adjoined root in the underlying quadratic extension.
Definition at line 127 of file relic_fpx.h.
dv8_t
typedef dv4_t dv8_t[2]
Represents a double-precision octic extension field element.
Definition at line 132 of file relic_fpx.h.
fp8_st
typedef fp4_st fp8_st[2]
Represents an octic extension field element with automatic memory allocation.
Definition at line 138 of file relic_fpx.h.
fp9_t
typedef fp3_t fp9_t[3]
Represents an octic extension prime field element.
This extension is constructed with the basis {1, v, v^2}, where v^3 = j is an adjoined root in the underlying quadratic extension.
Definition at line 146 of file relic_fpx.h.
dv9_t
typedef dv3_t dv9_t[3]
Represents a double-precision octic extension field element.
Definition at line 151 of file relic_fpx.h.
fp9_st
typedef fp3_st fp9_st[3]
Represents an octic extension field element with automatic memory allocation.
Definition at line 157 of file relic_fpx.h.
fp12_t
typedef fp6_t fp12_t[2]
Represents a dodecic extension field element.
This extension is constructed with the basis {1, w}, where w^2 = v is an adjoined root in the underlying sextic extension.
Definition at line 165 of file relic_fpx.h.
dv12_t
typedef dv6_t dv12_t[2]
Represents a double-precision dodecic extension field element.
Definition at line 170 of file relic_fpx.h.
fp16_t
typedef fp8_t fp16_t[2]
Represents an octic extension prime field element.
This extension is constructed with the basis {1, w}, where v^2 = v is an adjoined root in the underlying octic extension.
Definition at line 178 of file relic_fpx.h.
dv16_t
typedef dv8_t dv16_t[2]
Represents a double-precision octic extension field element.
Definition at line 183 of file relic_fpx.h.
fp16_st
typedef fp8_st fp16_st[2]
Represents an octic extension field element with automatic memory allocation.
Definition at line 189 of file relic_fpx.h.
fp18_t
typedef fp9_t fp18_t[2]
Represents an octdecic extension field element.
This extension is constructed with the basis {1, w}, where w^2 = v is an adjoined root in the underlying nonic extension.
Definition at line 197 of file relic_fpx.h.
dv18_t
typedef dv9_t dv18_t[2]
Represents a double-precision octdecic extension field element.
Definition at line 202 of file relic_fpx.h.
fp24_t
typedef fp8_t fp24_t[3]
Represents a 24-degree extension field element.
This extension is constructed with the basis {1, t, t^2}, where t^3 = v is an adjoined root in the underlying octic extension.
Definition at line 210 of file relic_fpx.h.
dv24_t
typedef dv8_t dv24_t[3]
Represents a double-precision 24-degree extension field element.
Definition at line 215 of file relic_fpx.h.
fp48_t
typedef fp24_t fp48_t[2]
Represents a 48-degree extension field element.
This extension is constructed with the basis {1, u}, where u^2 = t is an adjoined root in the underlying extension of degree 24.
Definition at line 223 of file relic_fpx.h.
fp54_t
typedef fp18_t fp54_t[3]
Represents a 54-degree extension field element.
This extension is constructed with the basis {1, u, u^2}, where u^3 = t is an adjoined root in the underlying octdecic extension.
Definition at line 231 of file relic_fpx.h.
Function Documentation
fp2_field_init()
void fp2_field_init (void)
Initializes the quadratic extension field arithmetic module.
Definition at line 65 of file relic_fpx_field.c.
References bn_div_dig(), bn_free, bn_new, bn_null, bn_sub_dig(), core_get(), dv_copy(), ERR_CAUGHT, fp2_exp(), fp2_free, fp2_mul, fp2_mul_nor, fp2_new, fp2_null, _ctx_t::fp2_p1, _ctx_t::fp2_p2, fp2_set_dig(), fp2_sqr, fp2_srt(), fp_copy(), fp_prime_get(), fp_set_dig(), fp_zero(), _ctx_t::qnr2, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, RLC_TRY, and util_bits_dig().
Referenced by fp_prime_calc().
fp2_field_get_qnr()
int fp2_field_get_qnr (void)
Return the integer part (u) of the quadratic non-residue (i + u).
Definition at line 39 of file relic_fpx_field.c.
References core_get(), and _ctx_t::qnr2.
Referenced by fp2_mul_nor_basic().
fp2_copy()
void fp2_copy (fp2_t c, const fp2_t a)
Copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to copy.
Definition at line 39 of file relic_fpx_util.c.
References fp_copy().
Referenced by ep2_copy(), ep2_curve_mul_a(), ep2_curve_mul_b(), ep2_curve_set(), ep2_curve_set_map(), ep2_curve_set_twist(), ep2_map_swift(), ep2_neg(), ep2_norm_imp(), ep2_norm_sim(), ep2_pck(), ep2_rhs(), ep2_upk(), fp12_back_cyc(), fp12_back_cyc_sim(), fp12_mul_dxs_basic(), fp12_mul_dxs_lazyr(), fp12_sqr_unr(), fp2_exp(), fp2_exp_cyc(), fp2_exp_cyc_sim(), fp2_exp_dig(), fp2_frb(), fp2_inv_sim(), fp2_mul_frb(), fp2_mul_nor_basic(), fp2_pck(), fp2_srt(), fp2_upk(), fp4_add_dig(), fp4_copy(), fp4_inv_cyc(), fp4_mul_art(), fp4_srt(), fp4_sub_dig(), fp6_copy(), fp6_mul_art(), fp6_mul_basic(), fp6_mul_dxs(), pp_add_k8_projc_basic(), and pp_add_k8_projc_lazyr().
fp2_copy_sec()
void fp2_copy_sec (fp2_t c, const fp2_t a, dig_t bit)
Conditionally copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to copy.
[in] bit - the condition bit to evaluate.
Definition at line 44 of file relic_fpx_util.c.
References fp_copy_sec().
Referenced by ep2_map_swift(), ep2_mul_reg_gls(), ep2_mul_reg_imp(), fp12_back_cyc(), fp12_back_cyc_sim(), fp2_srt(), fp4_copy_sec(), fp4_srt(), and fp6_copy_sec().
fp2_zero()
void fp2_zero (fp2_t a)
Assigns zero to a quadratic extension field element.
Parameters
[out] a - the quadratic extension field element to zero.
Definition at line 49 of file relic_fpx_util.c.
References fp_zero().
Referenced by ep2_curve_mul_a(), ep2_curve_mul_b(), ep2_curve_set_twist(), ep2_map_basic(), ep2_pck(), ep2_read_bin(), ep2_set_infty(), ep4_curve_set_twist(), fp12_pck(), fp12_read_bin(), fp18_pck(), fp2_srt(), fp4_set_dig(), fp4_srt(), fp4_zero(), fp6_set_dig(), fp6_zero(), and pp_mil_k2().
fp2_is_zero()
int fp2_is_zero (const fp2_t a)
Tests if a quadratic extension field element is zero or not.
Parameters
[in] a - the quadratic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 54 of file relic_fpx_util.c.
References fp_is_zero().
Referenced by detect_opt(), detect_opt(), detect_opt(), ep2_is_infty(), ep2_map_swift(), ep4_curve_set_twist(), ep4_map(), fp12_back_cyc(), fp12_back_cyc_sim(), fp12_upk(), fp18_upk(), fp2_srt(), fp4_cmp_dig(), fp4_field_init(), fp4_is_zero(), fp4_srt(), fp6_cmp_dig(), and fp6_is_zero().
fp2_rand()
void fp2_rand (fp2_t a)
Assigns a random value to a quadratic extension field element.
Parameters
[out] a - the quadratic extension field element to assign.
Definition at line 58 of file relic_fpx_util.c.
References fp_rand().
Referenced by ep2_blind(), fp4_rand(), and fp6_rand().
fp2_print()
void fp2_print (const fp2_t a)
Prints a quadratic extension field element to standard output.
Parameters
[in] a - the quadratic extension field element to print.
Definition at line 63 of file relic_fpx_util.c.
References fp_print().
Referenced by ep2_print(), fp4_print(), and fp6_print().
fp2_size_bin()
int fp2_size_bin (fp2_t a, int pack)
Returns the number of bytes necessary to store a quadratic extension field element.
Parameters
[in] a - the extension field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 68 of file relic_fpx_util.c.
References fp2_test_cyc(), and RLC_FP_BYTES.
fp2_read_bin()
void fp2_read_bin (fp2_t a, const uint8_t * bin, size_t len)
Reads a quadratic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 80 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp2_upk(), fp_read_bin(), fp_set_bit(), fp_zero(), RLC_FP_BYTES, and RLC_THROW.
Referenced by ep2_read_bin(), fp12_read_bin(), fp4_read_bin(), and fp6_read_bin().
fp2_write_bin()
void fp2_write_bin (uint8_t * bin, size_t len, const fp2_t a, int pack)
Writes a quadratic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
[in] pack - the flag to indicate compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 97 of file relic_fpx_util.c.
References ERR_CAUGHT, ERR_NO_BUFFER, fp2_free, fp2_new, fp2_null, fp2_pck(), fp2_test_cyc(), fp_get_bit(), fp_write_bin(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.
Referenced by ep2_write_bin(), fp12_write_bin(), fp4_write_bin(), and fp6_write_bin().
fp2_cmp()
int fp2_cmp (const fp2_t a, const fp2_t b)
Returns the result of a comparison between two quadratic extension field elements.
Parameters
[in] a - the first quadratic extension field element.
[in] b - the second quadratic extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 39 of file relic_fpx_cmp.c.
References fp_cmp(), RLC_EQ, and RLC_NE.
Referenced by detect_opt(), ep2_cmp(), ep2_on_curve(), fp2_srt(), fp4_cmp(), and fp6_cmp().
fp2_cmp_dig()
int fp2_cmp_dig (const fp2_t a, const dig_t b)
Returns the result of a signed comparison between a quadratic extension field element and a digit.
Parameters
[in] a - the quadratic extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 44 of file relic_fpx_cmp.c.
References fp_cmp_dig(), fp_is_zero(), RLC_EQ, and RLC_NE.
Referenced by detect_opt(), fp2_test_cyc(), fp4_cmp_dig(), and fp6_cmp_dig().
fp2_set_dig()
void fp2_set_dig (fp2_t a, const dig_t b)
Assigns a quadratic extension field element to a digit.
Parameters
[in] a - the quadratic extension field element.
[in] b - the digit.
Definition at line 131 of file relic_fpx_util.c.
References fp_set_dig(), and fp_zero().
Referenced by detect_opt(), ep2_curve_set_map(), ep2_curve_set_twist(), ep2_map_basic(), ep2_map_swift(), ep2_mul_reg_gls(), ep2_mul_reg_imp(), ep2_norm_imp(), ep2_read_bin(), fp12_back_cyc(), fp12_back_cyc_sim(), fp2_exp(), fp2_exp_cyc(), fp2_exp_cyc_sim(), fp2_exp_dig(), fp2_field_init(), fp4_set_dig(), fp4_srt(), fp6_set_dig(), pp_fin_k12_oatep(), pp_map_sim_tatep_k2(), pp_map_sim_weilp_k2(), pp_map_tatep_k2(), pp_map_weilp_k2(), pp_norm_k12(), and pp_norm_k8().
fp2_add_basic()
void fp2_add_basic (fp2_t c, const fp2_t a, const fp2_t b)
Adds two quadratic extension field elements using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the first quadratic extension field element.
[in] b - the second quadratic extension field element.
Definition at line 41 of file relic_fpx_add.c.
References fp_add.
fp2_add_integ()
void fp2_add_integ (fp2_t c, const fp2_t a, const fp2_t b)
Adds two quadratic extension field elements using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the first quadratic extension field element.
[in] b - the second quadratic extension field element.
Definition at line 61 of file relic_fpx_add.c.
References fp2_addm_low().
fp2_add_dig()
void fp2_add_dig (fp2_t c, const fp2_t a, dig_t b)
Adds a quadratic extension field element and a digit. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element.
[in] b - the digit to add.
Definition at line 75 of file relic_fpx_add.c.
References fp_add_dig(), and fp_copy().
Referenced by ep2_map_basic(), ep2_map_swift(), ep2_rhs(), fp12_pck_max(), and fp4_add_dig().
fp2_sub_basic()
void fp2_sub_basic (fp2_t c, const fp2_t a, const fp2_t b)
Subtracts a quadratic extension field element from another using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the first quadratic extension field element.
[in] b - the second quadratic extension field element.
Definition at line 46 of file relic_fpx_add.c.
References fp_sub.
fp2_sub_integ()
void fp2_sub_integ (fp2_t c, const fp2_t a, const fp2_t b)
Subtracts a quadratic extension field element from another using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the first quadratic extension field element.
[in] b - the second quadratic extension field element.
Definition at line 65 of file relic_fpx_add.c.
References fp2_subm_low().
fp2_sub_dig()
void fp2_sub_dig (fp2_t c, const fp2_t a, dig_t b)
Subtracts a quadratic extension field element and a digit. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element.
[in] b - the digit to subtract.
Definition at line 80 of file relic_fpx_add.c.
References fp_copy(), and fp_sub_dig().
Referenced by ep2_map_swift(), ep2_rhs(), and fp4_sub_dig().
fp2_neg()
void fp2_neg (fp2_t c, const fp2_t a)
Negates a quadratic extension field element.
Parameters
[out] c - the result.
[out] a - the quadratic extension field element to negate.
Definition at line 85 of file relic_fpx_add.c.
References fp_neg.
Referenced by detect_opt(), ep2_curve_set_map(), ep2_map_swift(), ep2_neg(), ep2_upk(), fp4_inv(), fp4_inv_cyc(), fp4_neg(), fp6_neg(), and pp_add_lit_k12().
fp2_dbl_basic()
void fp2_dbl_basic (fp2_t c, const fp2_t a)
Doubles a quadratic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to double.
Definition at line 51 of file relic_fpx_add.c.
References fp_dbl.
fp2_dbl_integ()
void fp2_dbl_integ (fp2_t c, const fp2_t a)
Doubles a quadratic extension field element using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to double.
Definition at line 69 of file relic_fpx_add.c.
References fp2_dblm_low().
fp2_mul_basic()
void fp2_mul_basic (fp2_t c, const fp2_t a, const fp2_t b)
Multiples two quadratic extension field elements using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the first quadratic extension field element.
[in] b - the second quadratic extension field element.
Definition at line 42 of file relic_fp2_mul.c.
References dv_free, dv_new, dv_null, ERR_CAUGHT, fp_add, fp_addc_low(), fp_muln_low(), fp_prime_get_qnr(), fp_rdc, fp_subc_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp2_mul_integ()
void fp2_mul_integ (fp2_t c, const fp2_t a, const fp2_t b)
Multiples two quadratic extension field elements using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the first quadratic extension field element.
[in] b - the second quadratic extension field element.
Definition at line 167 of file relic_fp2_mul.c.
References fp2_mulm_low().
fp2_mul_art()
void fp2_mul_art (fp2_t c, const fp2_t a)
Multiplies a quadratic extension field element by the adjoined root. Computes c = a * i.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to multiply.
Definition at line 177 of file relic_fp2_mul.c.
References ERR_CAUGHT, fp_add, fp_copy(), fp_free, fp_neg, fp_new, fp_null, fp_prime_get_qnr(), fp_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep2_curve_mul_a(), fp2_mul_nor_basic(), and pp_dbl_k8_projc_new().
fp2_mul_nor_basic()
void fp2_mul_nor_basic (fp2_t c, const fp2_t a)
Multiplies a quadratic extension field element by a quadratic/cubic non-residue.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to multiply.
Definition at line 104 of file relic_fp2_mul.c.
References bn_free, bn_new, bn_null, ERR_CAUGHT, ERR_NO_VALID, fp2_add, fp2_copy(), fp2_dbl, fp2_field_get_qnr(), fp2_free, fp2_mul_art(), fp2_new, fp2_null, fp_add, fp_neg, fp_prime_get_mod8(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp2_mul_nor_integ()
void fp2_mul_nor_integ (fp2_t c, const fp2_t a)
Multiplies a quadratic extension field element by a quadratic/cubic non-residue using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to multiply.
Definition at line 171 of file relic_fp2_mul.c.
References fp2_norm_low().
fp2_mul_frb()
void fp2_mul_frb (fp2_t c, const fp2_t a, int i, int j)
Multiplies a quadratic extension field element by a power of the constant needed to compute a power of the Frobenius map.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
[in] i - the power of the Frobenius map.
[in] j - the power of the constant.
Definition at line 211 of file relic_fp2_mul.c.
References core_get(), ERR_CAUGHT, fp2_copy(), fp2_free, fp2_mul, fp2_new, fp2_null, _ctx_t::fp2_p1, _ctx_t::fp2_p2, fp_copy(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp12_frb(), fp16_frb(), fp24_frb(), fp48_frb(), fp4_frb(), fp6_frb(), and fp8_frb().
fp2_mul_dig()
void fp2_mul_dig (fp2_t c, const fp2_t a, dig_t b)
Multiplies a quadratic extension field element by a digit. Computes c = a * b.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element.
[in] b - the digit to multiply.
Definition at line 254 of file relic_fp2_mul.c.
References fp_mul_dig().
Referenced by ep2_curve_mul_a(), ep2_curve_mul_b(), ep2_curve_set_map(), ep2_map_swift(), ep2_rhs(), and fp4_mul_dig().
fp2_sqr_basic()
void fp2_sqr_basic (fp2_t c, const fp2_t a)
Computes the square of a quadratic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to square.
Definition at line 41 of file relic_fp2_sqr.c.
References ERR_CAUGHT, fp_add, fp_dbl, fp_free, fp_mul, fp_new, fp_null, fp_prime_get_qnr(), fp_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp2_sqr_integ()
void fp2_sqr_integ (fp2_t c, const fp2_t a)
Computes the square of a quadratic extension field element using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to square.
Definition at line 105 of file relic_fp2_sqr.c.
References fp2_sqrm_low().
fp2_inv()
void fp2_inv (fp2_t c, const fp2_t a)
Inverts a quadratic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to invert.
Definition at line 39 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp_add, fp_dbl, fp_free, fp_inv, fp_mul, fp_mul_dig(), fp_neg, fp_new, fp_null, fp_prime_get_qnr(), fp_sqr, fp_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep2_curve_set_map(), ep2_curve_set_twist(), ep2_map_swift(), ep2_norm_imp(), fp12_back_cyc(), fp2_conv_cyc(), fp2_exp(), fp2_inv_sim(), fp4_inv(), fp4_srt(), fp6_inv(), pp_map_sim_weilp_k2(), pp_map_weilp_k2(), pp_norm_k12(), and pp_norm_k8().
fp2_inv_cyc()
void fp2_inv_cyc (fp2_t c, const fp2_t a)
Computes the inverse of a cyclotomic quadratic extension field element.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to invert.
Definition at line 92 of file relic_fpx_inv.c.
References fp_copy(), and fp_neg.
Referenced by fp2_conv_cyc(), fp2_exp_cyc(), fp2_exp_cyc_sim(), fp2_test_cyc(), pp_map_sim_weilp_k2(), and pp_map_weilp_k2().
fp2_inv_sim()
void fp2_inv_sim (fp2_t * c, const fp2_t * a, int n)
Inverts multiple quadratic extension field elements simultaneously.
Parameters
[out] c - the result.
[in] a - the quadratic extension field elements to invert.
[in] n - the number of elements.
Definition at line 97 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp2_copy(), fp2_free, fp2_inv(), fp2_mul, fp2_new, fp2_null, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by ep2_map_swift(), ep2_norm_sim(), and fp12_back_cyc_sim().
fp2_test_cyc()
int fp2_test_cyc (const fp2_t a)
Tests if a quadratic extension field element is cyclotomic.
Parameters
[in] a - the quadratic extension field element to test.
Returns
1 if the extension field element is cyclotomic, 0 otherwise.
Definition at line 62 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp2_cmp_dig(), fp2_free, fp2_inv_cyc(), fp2_mul, fp2_new, fp2_null, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp2_pck(), fp2_size_bin(), and fp2_write_bin().
fp2_conv_cyc()
void fp2_conv_cyc (fp2_t c, const fp2_t a)
Converts a quadratic extension field element to a cyclotomic element. Computes c = a^(p - 1).
Parameters
[out] c - the result.
[in] a - the quadratic extension field element.
Definition at line 39 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp2_free, fp2_inv(), fp2_inv_cyc(), fp2_mul, fp2_new, fp2_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_exp_k2().
fp2_exp()
void fp2_exp (fp2_t c, const fp2_t a, const bn_t b)
Computes a power of a quadratic extension field element.
Parameters
[out] c - the result.
[in] a - the quadratic extension element to exponentiate.
[in] b - the exponent.
Definition at line 38 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), ERR_CAUGHT, fp2_copy(), fp2_free, fp2_inv(), fp2_mul, fp2_new, fp2_null, fp2_set_dig(), fp2_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by fp2_field_init().
fp2_exp_dig()
void fp2_exp_dig (fp2_t c, const fp2_t a, dig_t b)
Computes a power of a quadratic extension field element by a small exponent.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 73 of file relic_fpx_exp.c.
References ERR_CAUGHT, fp2_copy(), fp2_free, fp2_mul, fp2_new, fp2_null, fp2_set_dig(), fp2_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, RLC_TRY, and util_bits_dig().
Referenced by fp2_exp_cyc().
fp2_exp_cyc()
void fp2_exp_cyc (fp2_t c, const fp2_t a, const bn_t b)
Computes a power of a cyclotomic quadratic extension field element.
Parameters
[out] c - the result.
[in] a - the cyclotomic element to exponentiate.
[in] b - the exponent.
Definition at line 84 of file relic_fpx_cyc.c.
References bn_bits(), bn_is_zero(), bn_rec_naf(), bn_sign(), ERR_CAUGHT, fp2_copy(), fp2_exp_dig(), fp2_free, fp2_inv_cyc(), fp2_mul, fp2_new, fp2_null, fp2_set_dig(), fp2_sqr, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by fp2_exp_cyc_sim(), and pp_exp_k2().
fp2_exp_cyc_sim()
void fp2_exp_cyc_sim (fp2_t e, const fp2_t a, const bn_t b, const fp2_t c, const bn_t d)
Computes a power of two cyclotomic quadratic extension field elements.
Parameters
[out] e - the result.
[in] a - the first element to exponentiate.
[in] b - the first exponent.
[in] c - the second element to exponentiate.
[in] d - the second exponent.
Definition at line 156 of file relic_fpx_cyc.c.
References bn_is_zero(), bn_rec_naf(), bn_sign(), ERR_CAUGHT, fp2_copy(), fp2_exp_cyc(), fp2_free, fp2_inv_cyc(), fp2_mul, fp2_new, fp2_null, fp2_set_dig(), fp2_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
fp2_frb()
void fp2_frb (fp2_t c, const fp2_t a, int i)
Computes a power of the Frobenius map of a quadratic extension field element. When i is odd, this is the same as computing the conjugate of the extension field element.
Parameters
[out] c - the result.
[in] a - the quadratic extension element to conjugate.
[in] i - the power of the Frobenius map.
Definition at line 39 of file relic_fpx_frb.c.
References fp2_copy(), fp_copy(), and fp_neg.
Referenced by ep2_frb(), fp12_frb(), fp2_is_sqr(), fp4_frb(), and fp6_frb().
fp2_is_sqr()
int fp2_is_sqr (const fp2_t a)
Tests if a quadratic extension field element is a quadratic residue.
Parameters
[in] a - the prime field element to test.
Returns
1 if the argument is even, 0 otherwise.
Definition at line 39 of file relic_fpx_srt.c.
References ERR_CAUGHT, fp2_frb(), fp2_free, fp2_mul, fp2_new, fp2_null, fp_is_sqr(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep2_map_basic(), ep2_map_swift(), and fp4_srt().
fp2_srt()
int fp2_srt (fp2_t c, const fp2_t a)
Extracts the square root of a quadratic extension field element. Computes c = sqrt(a). The other square root is the negation of c. The output value shall not be used in case 0 is returned.
Parameters
[out] c - the result.
[in] a - the extension field element.
Returns
- 1 if there is a square root, 0 otherwise.
Definition at line 64 of file relic_fpx_srt.c.
References bn_add_dig(), bn_free, bn_new, bn_null, bn_rsh(), bn_sub_dig(), dv_copy(), ERR_CAUGHT, ERR_NO_VALID, fp2_cmp(), fp2_copy(), fp2_copy_sec(), fp2_free, fp2_is_zero(), fp2_new, fp2_null, fp2_sqr, fp2_zero(), fp_add, fp_copy(), fp_copy_sec(), fp_dbl, fp_exp, fp_hlv, fp_inv, fp_is_sqr(), fp_is_zero(), fp_mul, fp_neg, fp_prime_get(), fp_prime_get_mod8(), fp_prime_get_qnr(), fp_set_dig(), fp_sqr, fp_srt(), fp_sub, fp_zero(), RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
Referenced by ep2_curve_set_map(), ep2_map_basic(), ep2_map_swift(), ep2_upk(), fp2_field_init(), and fp4_srt().
fp2_pck()
void fp2_pck (fp2_t c, const fp2_t a)
Compresses an extension field element.
Parameters
[out] c - the result.
[in] a - the extension field element to compress.
Definition at line 38 of file relic_fpx_pck.c.
References fp2_copy(), fp2_test_cyc(), fp_copy(), fp_get_bit(), fp_set_bit(), and fp_zero().
Referenced by fp2_write_bin().
fp2_upk()
int fp2_upk (fp2_t c, const fp2_t a)
Decompresses a quadratic extension field element.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element.
Returns
if the decompression was successful
Definition at line 48 of file relic_fpx_pck.c.
References ERR_CAUGHT, fp2_copy(), fp_bits(), fp_copy(), fp_free, fp_get_bit(), fp_neg, fp_new, fp_null, fp_sqr, fp_srt(), fp_sub_dig(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp2_read_bin().
fp3_field_init()
void fp3_field_init (void)
Initializes the cubic extension field arithmetic module.
Definition at line 173 of file relic_fpx_field.c.
References bn_div_dig(), bn_free, bn_new, bn_null, bn_read_raw(), _ctx_t::cnr3, core_get(), ERR_CAUGHT, fp3_exp(), fp3_field_get_cnr(), fp3_free, fp3_mul, fp3_mul_nor(), fp3_new, fp3_null, _ctx_t::fp3_p0, _ctx_t::fp3_p1, _ctx_t::fp3_p2, fp3_set_dig(), fp3_sqr, fp3_srt(), fp_copy(), fp_exp, fp_is_zero(), fp_neg, fp_prime_get(), fp_prime_get_cnr(), fp_set_dig(), fp_sqr, fp_zero(), _ctx_t::frb3, _ctx_t::qnr2, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, RLC_TRY, and util_bits_dig().
Referenced by fp_prime_calc().
fp3_field_get_cnr()
int fp3_field_get_cnr (void)
Return the integer part (u) of the cubic non-residue (j + u).
Definition at line 52 of file relic_fpx_field.c.
References _ctx_t::cnr3, core_get(), fp_param_get(), and K18_638.
Referenced by fp3_field_init(), fp3_mul_frb(), and fp3_mul_nor().
fp3_copy()
void fp3_copy (fp3_t c, const fp3_t a)
Copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the cubic extension field element to copy.
Definition at line 136 of file relic_fpx_util.c.
References fp_copy().
Referenced by ep3_copy(), ep3_curve_mul_a(), ep3_curve_mul_b(), ep3_curve_set(), ep3_curve_set_twist(), ep3_map(), ep3_neg(), ep3_norm_imp(), ep3_norm_sim(), ep3_rhs(), fp18_back_cyc(), fp18_back_cyc_sim(), fp18_mul_dxs_basic(), fp18_mul_dxs_lazyr(), fp3_exp(), fp3_frb(), fp3_inv_sim(), fp3_mul_frb(), fp3_mul_nor(), fp3_srt(), fp9_copy(), fp9_mul_art(), fp9_mul_basic(), and fp9_mul_dxs().
fp3_copy_sec()
void fp3_copy_sec (fp3_t c, const fp3_t a, dig_t bit)
Conditionally copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the cubic extension field element to copy.
[in] bit - the condition bit to evaluate.
Definition at line 142 of file relic_fpx_util.c.
References fp_copy_sec().
Referenced by ep3_map(), ep3_mul_reg_gls(), ep3_mul_reg_imp(), fp18_back_cyc(), fp18_back_cyc_sim(), fp3_srt(), and fp9_copy_sec().
fp3_zero()
void fp3_zero (fp3_t a)
Assigns zero to a cubic extension field element.
Parameters
[out] a - the cubic extension field element to zero.
Definition at line 148 of file relic_fpx_util.c.
References fp_zero().
Referenced by ep3_curve_mul_a(), ep3_curve_mul_b(), ep3_curve_set_twist(), ep3_set_infty(), fp18_read_bin(), fp3_srt(), fp9_set_dig(), and fp9_zero().
fp3_is_zero()
int fp3_is_zero (const fp3_t a)
Tests if a cubic extension field element is zero or not.
Parameters
[in] a - the cubic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 154 of file relic_fpx_util.c.
References fp_is_zero().
Referenced by detect_opt(), ep3_is_infty(), ep3_map(), fp18_back_cyc(), fp18_back_cyc_sim(), fp3_srt(), fp9_cmp_dig(), and fp9_is_zero().
fp3_rand()
void fp3_rand (fp3_t a)
Assigns a random value to a cubic extension field element.
Parameters
[out] a - the cubic extension field element to assign.
Definition at line 158 of file relic_fpx_util.c.
References fp_rand().
Referenced by ep3_blind(), and fp9_rand().
fp3_print()
void fp3_print (const fp3_t a)
Prints a cubic extension field element to standard output.
Parameters
[in] a - the cubic extension field element to print.
Definition at line 164 of file relic_fpx_util.c.
References fp_print().
Referenced by ep3_print(), and fp9_print().
fp3_size_bin()
int fp3_size_bin (fp3_t a)
Returns the number of bytes necessary to store a cubic extension field element.
Parameters
[out] size - the result.
[in] a - the extension field element.
Definition at line 170 of file relic_fpx_util.c.
References RLC_FP_BYTES.
fp3_read_bin()
void fp3_read_bin (fp3_t a, const uint8_t * bin, size_t len)
Reads a cubic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 174 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp_read_bin(), RLC_FP_BYTES, and RLC_THROW.
Referenced by ep3_read_bin(), fp18_read_bin(), and fp9_read_bin().
fp3_write_bin()
void fp3_write_bin (uint8_t * bin, size_t len, const fp3_t a)
Writes a cubic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 184 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp_write_bin(), RLC_FP_BYTES, and RLC_THROW.
Referenced by ep3_write_bin(), fp18_write_bin(), and fp9_write_bin().
fp3_cmp()
int fp3_cmp (const fp3_t a, const fp3_t b)
Returns the result of a comparison between two cubic extension field elements.
Parameters
[in] a - the first cubic extension field element.
[in] b - the second cubic extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 49 of file relic_fpx_cmp.c.
References fp_cmp(), RLC_EQ, and RLC_NE.
Referenced by detect_opt(), ep3_cmp(), ep3_on_curve(), fp3_srt(), and fp9_cmp().
fp3_cmp_dig()
int fp3_cmp_dig (const fp3_t a, const dig_t b)
Returns the result of a signed comparison between a cubic extension field element and a digit.
Parameters
[in] a - the cubic extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 54 of file relic_fpx_cmp.c.
References fp_cmp_dig(), fp_is_zero(), RLC_EQ, and RLC_NE.
Referenced by detect_opt(), fp3_srt(), and fp9_cmp_dig().
fp3_set_dig()
void fp3_set_dig (fp3_t a, const dig_t b)
Assigns a cubic extension field element to a digit.
Parameters
[in] a - the cubic extension field element.
[in] b - the digit.
Definition at line 194 of file relic_fpx_util.c.
References fp_set_dig(), and fp_zero().
Referenced by detect_opt(), ep3_curve_set_twist(), ep3_map(), ep3_mul_gls_imp(), ep3_mul_reg_gls(), ep3_mul_reg_imp(), ep3_norm_imp(), ep3_read_bin(), fp18_back_cyc(), fp18_back_cyc_sim(), fp3_exp(), fp3_field_init(), fp9_set_dig(), pp_mil_k54(), and pp_norm_k18().
fp3_add_basic()
void fp3_add_basic (fp3_t c, const fp3_t a, const fp3_t b)
Adds two cubic extension field elements using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the first cubic extension field element.
[in] b - the second cubic extension field element.
Definition at line 92 of file relic_fpx_add.c.
References fp_add.
fp3_add_integ()
void fp3_add_integ (fp3_t c, const fp3_t a, const fp3_t b)
Adds two cubic extension field elements using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the first cubic extension field element.
[in] b - the second cubic extension field element.
Definition at line 133 of file relic_fpx_add.c.
References fp3_addm_low().
fp3_add_dig()
void fp3_add_dig (fp3_t c, const fp3_t a, dig_t b)
Adds a cubic extension field element and a digit. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the cubic extension field element.
[in] b - the digit to add.
Definition at line 113 of file relic_fpx_add.c.
References fp_add_dig(), and fp_copy().
Referenced by ep3_rhs().
fp3_sub_basic()
void fp3_sub_basic (fp3_t c, const fp3_t a, const fp3_t b)
Subtracts a cubic extension field element from another using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the first cubic extension field element.
[in] b - the second cubic extension field element.
Definition at line 98 of file relic_fpx_add.c.
References fp_sub.
fp3_sub_integ()
void fp3_sub_integ (fp3_t c, const fp3_t a, const fp3_t b)
Subtracts a cubic extension field element from another using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the first cubic extension field element.
[in] b - the second cubic extension field element.
Definition at line 137 of file relic_fpx_add.c.
References fp3_subm_low().
fp3_sub_dig()
void fp3_sub_dig (fp3_t c, const fp3_t a, dig_t b)
Subtracts a cubic extension field element and a digit. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the cubic extension field element.
[in] b - the digit to subtract.
Definition at line 119 of file relic_fpx_add.c.
References fp_copy(), and fp_sub_dig().
Referenced by ep3_rhs().
fp3_neg()
void fp3_neg (fp3_t c, const fp3_t a)
Negates a cubic extension field element. Computes c = -a.
Parameters
[out] c - the result.
[out] a - the cubic extension field element to negate.
Definition at line 125 of file relic_fpx_add.c.
References fp_neg.
Referenced by detect_opt(), ep3_map(), ep3_neg(), fp9_neg(), and pp_add_lit_k18().
fp3_dbl_basic()
void fp3_dbl_basic (fp3_t c, const fp3_t a)
Doubles a cubic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the cubic extension field element to double.
Definition at line 104 of file relic_fpx_add.c.
References fp_dbl.
fp3_dbl_integ()
void fp3_dbl_integ (fp3_t c, const fp3_t a)
Doubles a cubic extension field element using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the cubic extension field element to double.
Definition at line 141 of file relic_fpx_add.c.
References fp3_dblm_low().
fp3_mul_basic()
void fp3_mul_basic (fp3_t c, const fp3_t a, const fp3_t b)
Multiples two cubic extension field elements using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the first cubic extension field element.
[in] b - the second cubic extension field element.
Definition at line 42 of file relic_fp3_mul.c.
References dv_free, dv_new, dv_null, ERR_CAUGHT, fp_add, fp_addc_low(), fp_addd_low(), fp_muln_low(), fp_prime_get_cnr(), fp_rdc, fp_subc_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp3_mul_integ()
void fp3_mul_integ (fp3_t c, const fp3_t a, const fp3_t b)
Multiples two cubic extension field elements using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the first cubic extension field element.
[in] b - the second cubic extension field element.
Definition at line 146 of file relic_fp3_mul.c.
References fp3_mulm_low().
fp3_mul_art()
void fp3_mul_art (fp3_t c, const fp3_t a)
Multiplies a cubic extension field element by the adjoined root. Computes c = a * j.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to multiply.
Definition at line 152 of file relic_fp3_mul.c.
References ERR_CAUGHT, fp_add, fp_copy(), fp_free, fp_new, fp_null, fp_prime_get_cnr(), fp_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep3_curve_set_twist(), and fp3_mul_nor().
fp3_mul_nor()
void fp3_mul_nor (fp3_t c, const fp3_t a)
Multiplies a cubic extension field element by a cubic non-residue.
Parameters
[out] c - the result.
[in] a - the cubic extension field element to multiply.
Definition at line 180 of file relic_fp3_mul.c.
References ERR_CAUGHT, fp3_add, fp3_copy(), fp3_dbl, fp3_field_get_cnr(), fp3_free, fp3_mul_art(), fp3_new, fp3_null, fp3_sub, fp_prime_get_mod18(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp18_back_cyc(), fp18_back_cyc_sim(), fp18_mul_dxs_basic(), fp18_sqr_cyc_basic(), fp18_sqr_cyc_lazyr(), fp18_sqr_pck_basic(), fp18_sqr_pck_lazyr(), fp3_field_init(), fp3_mul_frb(), fp9_inv(), fp9_mul_art(), fp9_mul_basic(), fp9_mul_dxs(), fp9_sqr_basic(), and pp_mil_k54().
fp3_mul_frb()
void fp3_mul_frb (fp3_t c, const fp3_t a, int i, int j)
Multiplies a cubic extension field element by a power of the constant needed to compute a power of the Frobenius map. If the flag is zero, the map is computed on the cubic extension directly; otherwise the map is computed on a higher extension.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
[in] i - the power of the Frobenius map.
[in] j - the power of the constant.
Definition at line 226 of file relic_fp3_mul.c.
References core_get(), ERR_CAUGHT, fp3_copy(), fp3_field_get_cnr(), fp3_free, fp3_mul, fp3_mul_nor(), fp3_new, fp3_null, _ctx_t::fp3_p0, _ctx_t::fp3_p1, _ctx_t::fp3_p2, fp_copy(), fp_mul, _ctx_t::frb3, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp18_frb(), fp3_frb(), fp54_frb(), and fp9_frb().
fp3_mul_dig()
void fp3_mul_dig (fp3_t c, const fp3_t a, dig_t b)
Multiplies a cubic extension field element by a digit. Computes c = a * b.
Parameters
[out] c - the result.
[in] a - the cubic extension field element.
[in] b - the digit to multiply.
Definition at line 303 of file relic_fp3_mul.c.
References fp_mul_dig().
Referenced by ep3_curve_mul_a(), ep3_curve_mul_b(), and ep3_rhs().
fp3_sqr_basic()
void fp3_sqr_basic (fp3_t c, const fp3_t a)
Computes the square of a cubic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the cubic extension field element to square.
Definition at line 42 of file relic_fp3_sqr.c.
References dv_free, dv_new, dv_null, ERR_CAUGHT, fp_add, fp_addc_low(), fp_addd_low(), fp_dbl, fp_hlvd_low(), fp_muln_low(), fp_prime_get_cnr(), fp_rdc, fp_sqrn_low(), fp_sub, fp_subc_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp3_sqr_integ()
void fp3_sqr_integ (fp3_t c, const fp3_t a)
Computes the square of a cubic extension field element using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the cubic extension field element to square.
Definition at line 126 of file relic_fp3_sqr.c.
References fp3_sqrm_low().
fp3_inv()
void fp3_inv (fp3_t c, const fp3_t a)
Inverts a cubic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the cubic extension field element to invert.
Definition at line 140 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp_add, fp_copy(), fp_free, fp_inv, fp_mul, fp_new, fp_null, fp_prime_get_cnr(), fp_sqr, fp_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep3_curve_set_twist(), ep3_map(), ep3_norm_imp(), fp18_back_cyc(), fp3_exp(), fp3_inv_sim(), fp9_inv(), and pp_norm_k18().
fp3_inv_sim()
void fp3_inv_sim (fp3_t * c, const fp3_t * a, int n)
Inverts multiple cubic extension field elements simultaneously.
Parameters
[out] c - the result.
[in] a - the cubic extension field elements to invert.
[in] n - the number of elements.
Definition at line 223 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp3_copy(), fp3_free, fp3_inv(), fp3_mul, fp3_new, fp3_null, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by ep3_norm_sim(), and fp18_back_cyc_sim().
fp3_exp()
void fp3_exp (fp3_t c, const fp3_t a, const bn_t b)
Computes a power of a cubic extension field element. Computes c = a^b.
Parameters
[out] c - the result.
[in] a - the cubic extension element to exponentiate.
[in] b - the exponent.
Definition at line 104 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), ERR_CAUGHT, fp3_copy(), fp3_free, fp3_inv(), fp3_mul, fp3_new, fp3_null, fp3_set_dig(), fp3_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by fp3_field_init(), and fp3_srt().
fp3_frb()
void fp3_frb (fp3_t c, const fp3_t a, int i)
Computes a power of the Frobenius map of a cubic extension field element.
Parameters
[out] c - the result.
[in] a - the cubic extension element to exponentiate.
[in] i - the power of the Frobenius map.
Definition at line 52 of file relic_fpx_frb.c.
References fp3_copy(), and fp3_mul_frb().
Referenced by ep3_frb(), fp18_frb(), fp3_is_sqr(), fp3_srt(), and fp9_frb().
fp3_is_sqr()
int fp3_is_sqr (const fp3_t a)
Tests if a cubic extension field element is a quadratic residue.
Parameters
[in] a - the prime field element to test.
Returns
1 if the argument is even, 0 otherwise.
Definition at line 186 of file relic_fpx_srt.c.
References ERR_CAUGHT, fp3_frb(), fp3_free, fp3_mul, fp3_new, fp3_null, fp_is_sqr(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep3_map().
fp3_srt()
int fp3_srt (fp3_t c, const fp3_t a)
Extracts the square root of a cubic extension field element. Computes c = sqrt(a). The other square root is the negation of c. The output value shall not be used in case 0 is returned.
Parameters
[out] c - the result.
[in] a - the extension field element.
Returns
- 1 if there is a square root, 0 otherwise.
Definition at line 212 of file relic_fpx_srt.c.
References bn_add(), bn_div_dig(), bn_free, bn_new, bn_null, bn_rsh(), bn_sqr, bn_sub_dig(), dv_copy(), ERR_CAUGHT, fp3_cmp(), fp3_cmp_dig(), fp3_copy(), fp3_copy_sec(), fp3_dbl, fp3_exp(), fp3_frb(), fp3_free, fp3_is_zero(), fp3_mul, fp3_new, fp3_null, fp3_sqr, fp3_zero(), fp_free, fp_mul, fp_new, fp_null, fp_prime_get(), fp_prime_get_2ad(), fp_prime_get_mod8(), fp_prime_get_srt(), fp_sqr, fp_sub_dig(), RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
Referenced by ep3_map(), and fp3_field_init().
fp4_field_init()
void fp4_field_init (void)
Initializes the quartic extension field arithmetic module.
Definition at line 303 of file relic_fpx_field.c.
References bn_div_dig(), bn_free, bn_new, bn_null, bn_sub_dig(), core_get(), dv_copy(), ERR_CAUGHT, fp2_is_zero(), fp4_exp(), fp4_free, fp4_mul_art(), fp4_new, fp4_null, _ctx_t::fp4_p1, fp4_set_dig(), fp_copy(), fp_prime_get(), _ctx_t::frb4, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
Referenced by fp_prime_calc().
fp4_copy()
void fp4_copy (fp4_t c, const fp4_t a)
Copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the quartic extension field element to copy.
Definition at line 200 of file relic_fpx_util.c.
References fp2_copy().
Referenced by ep4_copy(), ep4_curve_mul_a(), ep4_curve_mul_b(), ep4_curve_set(), ep4_curve_set_twist(), ep4_map(), ep4_neg(), ep4_norm_imp(), ep4_norm_sim(), ep4_rhs(), fp24_back_cyc(), fp24_back_cyc_sim(), fp4_exp(), fp4_frb(), fp4_inv_sim(), fp4_mul_frb(), fp8_copy(), fp8_inv_cyc(), fp8_mul_art(), fp8_srt(), pp_add_k16_projc_basic(), and pp_add_k16_projc_lazyr().
fp4_copy_sec()
void fp4_copy_sec (fp4_t c, const fp4_t a, dig_t bit)
Conditionally copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the quartic extension field element to copy.
[in] bit - the condition bit to evaluate.
Definition at line 205 of file relic_fpx_util.c.
References fp2_copy_sec().
Referenced by ep4_map(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), fp24_back_cyc(), fp24_back_cyc_sim(), fp8_copy_sec(), and fp8_srt().
fp4_zero()
void fp4_zero (fp4_t a)
Assigns zero to a quartic extension field element.
Parameters
[out] a - the quartic extension field element to zero.
Definition at line 210 of file relic_fpx_util.c.
References fp2_zero().
Referenced by ep4_curve_mul_a(), ep4_curve_mul_b(), ep4_curve_set_twist(), ep4_map(), ep4_set_infty(), fp24_pck(), fp24_read_bin(), fp4_srt(), fp8_set_dig(), fp8_srt(), and fp8_zero().
fp4_is_zero()
int fp4_is_zero (const fp4_t a)
Tests if a quartic extension field element is zero or not.
Parameters
[in] a - the quartic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 215 of file relic_fpx_util.c.
References fp2_is_zero().
Referenced by detect_opt(), detect_opt(), ep4_is_infty(), ep4_map(), ep8_map(), fp16_mul_dxs_basic(), fp16_mul_dxs_lazyr(), fp24_back_cyc(), fp24_back_cyc_sim(), fp24_upk(), fp4_srt(), fp8_cmp_dig(), fp8_field_init(), fp8_is_zero(), and fp8_srt().
fp4_rand()
void fp4_rand (fp4_t a)
Assigns a random value to a quartic extension field element.
Parameters
[out] a - the quartic extension field element to assign.
Definition at line 219 of file relic_fpx_util.c.
References fp2_rand().
Referenced by ep4_blind(), and fp8_rand().
fp4_print()
void fp4_print (const fp4_t a)
Prints a quartic extension field element to standard output.
Parameters
[in] a - the quartic extension field element to print.
Definition at line 224 of file relic_fpx_util.c.
References fp2_print().
Referenced by ep4_print(), and fp8_print().
fp4_size_bin()
int fp4_size_bin (fp4_t a)
Returns the number of bytes necessary to store a quartic extension field element.
Parameters
[out] size - the result.
[in] a - the extension field element.
Definition at line 229 of file relic_fpx_util.c.
References RLC_FP_BYTES.
fp4_read_bin()
void fp4_read_bin (fp4_t a, const uint8_t * bin, size_t len)
Reads a quartic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 233 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp2_read_bin(), RLC_FP_BYTES, and RLC_THROW.
Referenced by ep4_read_bin(), fp24_read_bin(), and fp8_read_bin().
fp4_write_bin()
void fp4_write_bin (uint8_t * bin, size_t len, const fp4_t a)
Writes a quartic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 242 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp2_write_bin(), RLC_FP_BYTES, and RLC_THROW.
Referenced by ep4_write_bin(), fp24_write_bin(), and fp8_write_bin().
fp4_cmp()
int fp4_cmp (const fp4_t a, const fp4_t b)
Returns the result of a comparison between two quartic extension field elements.
Parameters
[in] a - the first quartic extension field element.
[in] b - the second quartic extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 59 of file relic_fpx_cmp.c.
References fp2_cmp(), RLC_EQ, and RLC_NE.
Referenced by detect_opt(), ep4_cmp(), ep4_on_curve(), and fp8_cmp().
fp4_cmp_dig()
int fp4_cmp_dig (const fp4_t a, const dig_t b)
Returns the result of a signed comparison between a quartic extension field element and a digit.
Parameters
[in] a - the quartic extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 64 of file relic_fpx_cmp.c.
References fp2_cmp_dig(), fp2_is_zero(), RLC_EQ, and RLC_NE.
Referenced by detect_opt(), and fp8_cmp_dig().
fp4_set_dig()
void fp4_set_dig (fp4_t a, const dig_t b)
Assigns a quartic extension field element to a digit.
Parameters
[in] a - the quartic extension field element.
[in] b - the digit.
Definition at line 251 of file relic_fpx_util.c.
References fp2_set_dig(), and fp2_zero().
Referenced by detect_opt(), ep4_curve_set_twist(), ep4_map(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), ep4_norm_imp(), ep4_read_bin(), fp24_back_cyc(), fp24_back_cyc_sim(), fp4_exp(), fp4_field_init(), fp8_set_dig(), fp8_srt(), pp_norm_k16(), and pp_norm_k24().
fp4_add()
void fp4_add (fp4_t c, const fp4_t a, const fp4_t b)
Adds two quartic extension field elements. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first quartic extension field element.
[in] b - the second quartic extension field element.
Definition at line 147 of file relic_fpx_add.c.
References fp2_add.
Referenced by ep4_map(), ep4_rhs(), fp16_mul_dxs_basic(), fp16_mul_dxs_lazyr(), fp24_back_cyc(), fp24_back_cyc_sim(), fp24_sqr_cyc_basic(), fp24_sqr_cyc_lazyr(), fp24_sqr_pck_basic(), fp24_sqr_pck_lazyr(), fp8_add(), fp8_mul_basic(), fp8_mul_dxs(), fp8_mul_unr(), fp8_sqr_basic(), fp8_sqr_cyc(), fp8_sqr_unr(), fp8_srt(), pp_add_k16_projc_basic(), pp_add_k16_projc_lazyr(), pp_add_k24_projc(), pp_dbl_k16_projc_basic(), pp_dbl_k16_projc_lazyr(), pp_dbl_k24_projc(), and pp_dbl_lit_k16().
fp4_add_dig()
void fp4_add_dig (fp4_t c, const fp4_t a, dig_t b)
Adds a quartic extension field element and a digit. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the quartic extension field element.
[in] b - the digit to add.
Definition at line 163 of file relic_fpx_add.c.
References fp2_add_dig(), and fp2_copy().
fp4_sub()
void fp4_sub (fp4_t c, const fp4_t a, const fp4_t b)
Subtracts a quartic extension field element from another. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the quartic extension field element.
[in] b - the quartic extension field element.
Definition at line 152 of file relic_fpx_add.c.
References fp2_sub.
Referenced by ep4_map(), fp16_mul_dxs_basic(), fp24_back_cyc(), fp24_back_cyc_sim(), fp24_sqr_cyc_basic(), fp24_sqr_cyc_lazyr(), fp24_sqr_pck_basic(), fp24_sqr_pck_lazyr(), fp8_inv(), fp8_mul_basic(), fp8_sqr_basic(), fp8_sqr_cyc(), fp8_srt(), fp8_sub(), pp_add_k16_basic(), pp_add_k16_projc_basic(), pp_add_k16_projc_lazyr(), pp_add_k24_basic(), pp_add_k24_projc(), pp_dbl_k16_basic(), pp_dbl_k16_projc_basic(), pp_dbl_k16_projc_lazyr(), pp_dbl_k24_basic(), and pp_dbl_k24_projc().
fp4_sub_dig()
void fp4_sub_dig (fp4_t c, const fp4_t a, dig_t b)
Subtracts a quartic extension field element and a digit. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the quartic extension field element.
[in] b - the digit to subtract.
Definition at line 168 of file relic_fpx_add.c.
References fp2_copy(), and fp2_sub_dig().
fp4_neg()
void fp4_neg (fp4_t c, const fp4_t a)
Negates a quartic extension field element. Computes c = -a.
Parameters
[out] c - the result.
[out] a - the quartic extension field element to negate.
Definition at line 173 of file relic_fpx_add.c.
References fp2_neg().
Referenced by detect_opt(), ep4_map(), ep4_neg(), fp8_inv(), fp8_inv_cyc(), fp8_neg(), and pp_add_lit_k16().
fp4_dbl()
void fp4_dbl (fp4_t c, const fp4_t a)
Doubles a quartic extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the quartic extension field element to double.
Definition at line 157 of file relic_fpx_add.c.
References fp2_dbl.
Referenced by ep4_curve_mul_a(), ep4_map(), fp24_back_cyc(), fp24_back_cyc_sim(), fp24_sqr_cyc_basic(), fp24_sqr_cyc_lazyr(), fp24_sqr_pck_basic(), fp24_sqr_pck_lazyr(), fp8_dbl(), fp8_sqr_basic(), fp8_sqr_cyc(), fp8_srt(), pp_add_k16_projc_basic(), pp_add_k16_projc_lazyr(), pp_dbl_k16_projc_basic(), pp_dbl_k16_projc_lazyr(), pp_dbl_k24_projc(), and pp_dbl_lit_k16().
fp4_mul_unr()
void fp4_mul_unr (dv4_t c, const fp4_t a, const fp4_t b)
Multiples two quartic extension field elements without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the quartic extension field element.
[in] b - the quartic extension field element.
Definition at line 87 of file relic_fp4_mul.c.
References dv2_free, dv2_new, dv2_null, ERR_CAUGHT, fp2_addc_low(), fp2_addm_low(), fp2_free, fp2_muln_low(), fp2_new, fp2_nord_low(), fp2_null, fp2_subc_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp12_sqr_unr(), fp16_mul_dxs_lazyr(), fp4_mul_lazyr(), fp8_mul_dxs(), and fp8_mul_unr().
fp4_mul_basic()
void fp4_mul_basic (fp4_t c, const fp4_t a, const fp4_t b)
Multiples two quartic extension field elements.
Parameters
[out] c - the result.
[in] a - the quartic extension field element.
[in] b - the quartic extension field element.
Definition at line 42 of file relic_fp4_mul.c.
References ERR_CAUGHT, fp2_add, fp2_free, fp2_mul, fp2_mul_nor, fp2_new, fp2_null, fp2_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp4_mul_lazyr()
void fp4_mul_lazyr (fp4_t c, const fp4_t a, const fp4_t b)
Multiples two quartic extension field elements using lazy reduction.
Parameters
[out] c - the result.
[in] a - the quartic extension field element.
[in] b - the quartic extension field element.
Definition at line 123 of file relic_fp4_mul.c.
References dv4_free, dv4_new, dv4_null, ERR_CAUGHT, fp2_rdcn_low(), fp4_mul_unr(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp4_mul_art()
void fp4_mul_art (fp4_t c, const fp4_t a)
Multiplies a quartic extension field element by the adjoined root.
Parameters
[out] c - the result.
[in] a - the quartic extension field element to multiply.
Definition at line 142 of file relic_fp4_mul.c.
References ERR_CAUGHT, fp2_copy(), fp2_free, fp2_mul_nor, fp2_new, fp2_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep4_curve_mul_a(), fp16_frb(), fp16_mul_dxs_basic(), fp24_back_cyc(), fp24_back_cyc_sim(), fp24_frb(), fp24_sqr_cyc_basic(), fp24_sqr_cyc_lazyr(), fp24_sqr_pck_basic(), fp24_sqr_pck_lazyr(), fp48_frb(), fp4_field_init(), fp4_mul_frb(), fp8_frb(), fp8_inv(), fp8_mul_art(), fp8_mul_basic(), fp8_sqr_basic(), fp8_sqr_cyc(), fp8_srt(), pp_add_k24_basic(), pp_add_k24_projc(), pp_dbl_k24_basic(), and pp_dbl_k24_projc().
fp4_mul_frb()
void fp4_mul_frb (fp4_t c, const fp4_t a, int i, int j)
Multiplies a quartic extension field element by a power of the constant needed to compute a power of the Frobenius map.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
[in] i - the power of the Frobenius map.
[in] j - the power of the constant.
Definition at line 161 of file relic_fp4_mul.c.
References core_get(), ep_curve_is_pairf(), EP_FM16, ERR_CAUGHT, ERR_NO_VALID, fp2_free, fp2_mul, fp2_new, fp2_null, fp4_copy(), fp4_mul_art(), fp_copy(), fp_prime_get_mod18(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep4_frb().
fp4_mul_dig()
void fp4_mul_dig (fp4_t c, const fp4_t a, dig_t b)
Multiplies a quartic extension field element by a digit. Computes c = a * b.
Parameters
[out] c - the result.
[in] a - the quartic extension field element.
[in] b - the digit to multiply.
Definition at line 199 of file relic_fp4_mul.c.
References fp2_mul_dig().
Referenced by ep4_curve_mul_a(), ep4_curve_mul_b(), ep4_map(), ep4_rhs(), and fp8_mul_dig().
fp4_mul_dxs()
void fp4_mul_dxs (fp4_t c, const fp4_t a, const fp4_t b)
Multiples a dense quartic extension field element by a sparse element.
Parameters
[out] c - the result.
[in] a - a quartic extension field element.
[in] b - a sparse quartic extension field element.
fp4_sqr_unr()
void fp4_sqr_unr (dv4_t c, const fp4_t a)
Computes the square of a quartic extension field element without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the quartic extension field element to square.
Definition at line 73 of file relic_fp4_sqr.c.
References dv2_free, dv2_new, dv2_null, ERR_CAUGHT, fp2_addc_low(), fp2_addm_low(), fp2_free, fp2_new, fp2_norh_low(), fp2_null, fp2_sqrn_low(), fp2_subc_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp12_sqr_unr(), fp24_sqr_cyc_lazyr(), fp24_sqr_pck_lazyr(), fp4_sqr_lazyr(), and fp8_sqr_unr().
fp4_sqr_basic()
void fp4_sqr_basic (fp4_t c, const fp4_t a)
Computes the squares of a quartic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the quartic extension field element to square.
Definition at line 42 of file relic_fp4_sqr.c.
References ERR_CAUGHT, fp2_add, fp2_dbl, fp2_free, fp2_mul, fp2_mul_nor, fp2_new, fp2_null, fp2_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp4_sqr_lazyr()
void fp4_sqr_lazyr (fp4_t c, const fp4_t a)
Computes the square of a quartic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the quartic extension field element to square.
Definition at line 110 of file relic_fp4_sqr.c.
References dv4_free, dv4_new, dv4_null, ERR_CAUGHT, fp2_rdcn_low(), fp4_sqr_unr(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp4_inv()
void fp4_inv (fp4_t c, const fp4_t a)
Inverts a quartic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the quartic extension field element to invert.
Definition at line 271 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp2_free, fp2_inv(), fp2_mul, fp2_mul_nor, fp2_neg(), fp2_new, fp2_null, fp2_sqr, fp2_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep4_curve_set_twist(), ep4_map(), ep4_norm_imp(), fp24_back_cyc(), fp4_exp(), fp4_inv_sim(), fp8_inv(), fp8_srt(), pp_norm_k16(), and pp_norm_k24().
fp4_inv_sim()
void fp4_inv_sim (fp4_t * c, const fp4_t * a, int n)
Inverts multiple quartic extension field elements simultaneously.
Parameters
[out] c - the result.
[in] a - the quartic extension field elements to invert.
[in] n - the number of elements.
Definition at line 299 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp4_copy(), fp4_free, fp4_inv(), fp4_mul, fp4_new, fp4_null, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by ep4_map(), ep4_norm_sim(), and fp24_back_cyc_sim().
fp4_inv_cyc()
void fp4_inv_cyc (fp4_t c, const fp4_t a)
Computes the inverse of a cyclotomic quartic extension field element.
For cyclotomic elements, this is equivalent to computing the conjugate. A cyclotomic element is one previously raised to the (p^2 - 1)-th power.
Parameters
[out] c - the result.
[in] a - the quartic extension field element to invert.
Definition at line 266 of file relic_fpx_inv.c.
References fp2_copy(), and fp2_neg().
fp4_exp()
void fp4_exp (fp4_t c, const fp4_t a, const bn_t b)
Computes a power of a quartic extension field element. Computes c = a^b.
Parameters
[out] c - the result.
[in] a - the quartic extension element to exponentiate.
[in] b - the exponent.
Definition at line 140 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), ERR_CAUGHT, fp4_copy(), fp4_free, fp4_inv(), fp4_mul, fp4_new, fp4_null, fp4_set_dig(), fp4_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by fp4_field_init().
fp4_frb()
void fp4_frb (fp4_t c, const fp4_t a, int i)
Computes a power of the Frobenius endomorphism of a quartic extension field element. Computes c = a^p^i.
Parameters
[out] c - the result.
[in] a - a quartic extension field element.
[in] i - the power of the Frobenius map.
Definition at line 64 of file relic_fpx_frb.c.
References fp2_frb(), fp2_mul_frb(), fp4_copy(), and fp_prime_get_mod18().
Referenced by ep4_frb(), fp4_is_sqr(), and fp8_frb().
fp4_is_sqr()
int fp4_is_sqr (const fp4_t a)
Tests if a quartic extension field element is a quadratic residue.
Parameters
[in] a - the prime field element to test.
Returns
1 if the argument is even, 0 otherwise.
Definition at line 352 of file relic_fpx_srt.c.
References ERR_CAUGHT, fp4_frb(), fp4_free, fp4_mul, fp4_new, fp4_null, fp_is_sqr(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep4_map(), and fp8_srt().
fp4_srt()
int fp4_srt (fp4_t c, const fp4_t a)
Extracts the square root of a quartic extension field element. Computes c = sqrt(a). The other square root is the negation of c. The output value shall not be used in case 0 is returned.
Parameters
[out] c - the result.
[in] a - the extension field element.
Returns
- 1 if there is a square root, 0 otherwise.
Definition at line 380 of file relic_fpx_srt.c.
References ERR_CAUGHT, ERR_NO_VALID, fp2_add, fp2_copy(), fp2_copy_sec(), fp2_dbl, fp2_free, fp2_inv(), fp2_is_sqr(), fp2_is_zero(), fp2_mul, fp2_mul_nor, fp2_new, fp2_null, fp2_set_dig(), fp2_sqr, fp2_srt(), fp2_sub, fp2_zero(), fp4_is_zero(), fp4_zero(), fp_hlv, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep4_map(), and fp8_srt().
fp6_copy()
void fp6_copy (fp6_t c, const fp6_t a)
Copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the sextic extension field element to copy.
Definition at line 256 of file relic_fpx_util.c.
References fp2_copy().
Referenced by fp12_copy(), fp12_inv_cyc(), fp12_mul_art(), fp12_upk_max(), fp6_exp(), and fp6_frb().
fp6_copy_sec()
void fp6_copy_sec (fp6_t c, const fp6_t a, dig_t bit)
Conditionally copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the sextic extension field element to copy.
[in] bit - the condition bit to evaluate.
Definition at line 262 of file relic_fpx_util.c.
References fp2_copy_sec().
Referenced by fp12_copy_sec().
fp6_zero()
void fp6_zero (fp6_t a)
Assigns zero to a sextic extension field element.
Parameters
[out] a - the sextic extension field element to zero.
Definition at line 268 of file relic_fpx_util.c.
References fp2_zero().
Referenced by fp12_pck_max(), fp12_set_dig(), fp12_upk_max(), and fp12_zero().
fp6_is_zero()
int fp6_is_zero (const fp6_t a)
Tests if a sextic extension field element is zero or not.
Parameters
[in] a - the sextic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 274 of file relic_fpx_util.c.
References fp2_is_zero().
Referenced by fp12_cmp_dig(), fp12_is_zero(), and fp12_upk_max().
fp6_rand()
void fp6_rand (fp6_t a)
Assigns a random value to a sextic extension field element.
Parameters
[out] a - the sextic extension field element to assign.
Definition at line 278 of file relic_fpx_util.c.
References fp2_rand().
Referenced by fp12_rand().
fp6_print()
void fp6_print (const fp6_t a)
Prints a sextic extension field element to standard output.
Parameters
[in] a - the sextic extension field element to print.
Definition at line 284 of file relic_fpx_util.c.
References fp2_print().
Referenced by fp12_print().
fp6_size_bin()
int fp6_size_bin (fp6_t a)
Returns the number of bytes necessary to store a quadratic extension field element.
Parameters
[out] size - the result.
[in] a - the extension field element.
Definition at line 290 of file relic_fpx_util.c.
References RLC_FP_BYTES.
fp6_read_bin()
void fp6_read_bin (fp6_t a, const uint8_t * bin, size_t len)
Reads a quadratic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 294 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp2_read_bin(), RLC_FP_BYTES, and RLC_THROW.
Referenced by fp12_read_bin().
fp6_write_bin()
void fp6_write_bin (uint8_t * bin, size_t len, const fp6_t a)
Writes a sextic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 304 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp2_write_bin(), RLC_FP_BYTES, and RLC_THROW.
Referenced by fp12_write_bin().
fp6_cmp()
int fp6_cmp (const fp6_t a, const fp6_t b)
Returns the result of a comparison between two sextic extension field elements.
Parameters
[in] a - the first sextic extension field element.
[in] b - the second sextic extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 69 of file relic_fpx_cmp.c.
References fp2_cmp(), RLC_EQ, and RLC_NE.
Referenced by fp12_cmp().
fp6_cmp_dig()
int fp6_cmp_dig (const fp6_t a, const dig_t b)
Returns the result of a signed comparison between a sextic extension field element and a digit.
Parameters
[in] a - the sextic extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 74 of file relic_fpx_cmp.c.
References fp2_cmp_dig(), fp2_is_zero(), RLC_EQ, and RLC_NE.
Referenced by fp12_cmp_dig().
fp6_set_dig()
void fp6_set_dig (fp6_t a, const dig_t b)
Assigns a sextic extension field element to a digit.
Parameters
[in] a - the sextic extension field element.
[in] b - the digit.
Definition at line 314 of file relic_fpx_util.c.
References fp2_set_dig(), and fp2_zero().
Referenced by fp12_set_dig(), fp12_upk_max(), and fp6_exp().
fp6_add()
void fp6_add (fp6_t c, const fp6_t a, const fp6_t b)
Adds two sextic extension field elements. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first sextic extension field element.
[in] b - the second sextic extension field element.
Definition at line 178 of file relic_fpx_add.c.
References fp2_add.
Referenced by fp12_add(), fp12_mul_basic(), fp12_mul_dxs_basic(), fp12_mul_dxs_lazyr(), fp12_mul_unr(), and fp12_sqr_basic().
fp6_sub()
void fp6_sub (fp6_t c, const fp6_t a, const fp6_t b)
Subtracts a sextic extension field element from another. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the sextic extension field element.
[in] b - the sextic extension field element.
Definition at line 184 of file relic_fpx_add.c.
References fp2_sub.
Referenced by fp12_inv(), fp12_mul_basic(), fp12_mul_dxs_basic(), fp12_sqr_basic(), and fp12_sub().
fp6_neg()
void fp6_neg (fp6_t c, const fp6_t a)
Negates a sextic extension field element. Computes c = -a.
Parameters
[out] c - the result.
[out] a - the sextic extension field element to negate.
Definition at line 196 of file relic_fpx_add.c.
References fp2_neg().
Referenced by fp12_inv(), fp12_inv_cyc(), and fp12_neg().
fp6_dbl()
void fp6_dbl (fp6_t c, const fp6_t a)
Doubles a sextic extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the sextic extension field element to double.
Definition at line 190 of file relic_fpx_add.c.
References fp2_dbl.
Referenced by fp12_dbl(), and fp12_sqr_basic().
fp6_mul_unr()
void fp6_mul_unr (dv6_t c, const fp6_t a, const fp6_t b)
Multiples two sextic extension field elements without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the sextic extension field element.
[in] b - the sextic extension field element.
Definition at line 113 of file relic_fp6_mul.c.
References dv2_free, dv2_new, dv2_null, ERR_CAUGHT, fp2_addc_low(), fp2_addm_low(), fp2_addn_low(), fp2_free, fp2_muln_low(), fp2_new, fp2_nord_low(), fp2_null, fp2_subc_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp12_mul_unr(), and fp6_mul_lazyr().
fp6_mul_basic()
void fp6_mul_basic (fp6_t c, const fp6_t a, const fp6_t b)
Multiples two sextic extension field elements.
Parameters
[out] c - the result.
[in] a - the sextic extension field element.
[in] b - the sextic extension field element.
Definition at line 41 of file relic_fp6_mul.c.
References ERR_CAUGHT, fp2_add, fp2_copy(), fp2_free, fp2_mul, fp2_mul_nor, fp2_new, fp2_null, fp2_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp6_mul_lazyr()
void fp6_mul_lazyr (fp6_t c, const fp6_t a, const fp6_t b)
Multiples two sextic extension field elements using lazy reduction.
Parameters
[out] c - the result.
[in] a - the sextic extension field element.
[in] b - the sextic extension field element.
Definition at line 191 of file relic_fp6_mul.c.
References dv6_free, dv6_new, dv6_null, ERR_CAUGHT, fp2_rdcn_low(), fp6_mul_unr(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp6_mul_art()
void fp6_mul_art (fp6_t c, const fp6_t a)
Multiplies a sextic extension field element by the adjoined root.
Parameters
[out] c - the result.
[in] a - the sextic extension field element to multiply.
Definition at line 268 of file relic_fp6_mul.c.
References ERR_CAUGHT, fp2_copy(), fp2_free, fp2_mul_nor, fp2_new, fp2_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp12_inv(), fp12_mul_art(), fp12_mul_basic(), fp12_mul_dxs_basic(), and fp12_sqr_basic().
fp6_mul_dxs()
void fp6_mul_dxs (fp6_t c, const fp6_t a, const fp6_t b)
Multiples a dense sextic extension field element by a sparse element.
Parameters
[out] c - the result.
[in] a - a sextic extension field element.
[in] b - a sparse sextic extension field element.
Definition at line 211 of file relic_fp6_mul.c.
References ERR_CAUGHT, fp2_add, fp2_copy(), fp2_free, fp2_mul, fp2_mul_nor, fp2_new, fp2_null, fp2_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp12_mul_dxs_basic().
fp6_sqr_unr()
void fp6_sqr_unr (dv6_t c, const fp6_t a)
Computes the square of a sextic extension field element without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the sextic extension field element to square.
Definition at line 114 of file relic_fp6_sqr.c.
References dv2_free, dv2_new, dv2_null, ERR_CAUGHT, fp2_addc_low(), fp2_addm_low(), fp2_dblm_low(), fp2_free, fp2_muln_low(), fp2_new, fp2_nord_low(), fp2_null, fp2_sqrn_low(), fp2_subc_low(), fp2_subm_low(), fp_hlvd_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp6_sqr_lazyr().
fp6_sqr_basic()
void fp6_sqr_basic (fp6_t c, const fp6_t a)
Computes the squares of a sextic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the sextic extension field element to square.
Definition at line 42 of file relic_fp6_sqr.c.
References ERR_CAUGHT, fp2_add, fp2_dbl, fp2_free, fp2_mul, fp2_mul_nor, fp2_new, fp2_null, fp2_sqr, fp2_sub, fp_hlv, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp6_sqr_lazyr()
void fp6_sqr_lazyr (fp6_t c, const fp6_t a)
Computes the square of a sextic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the sextic extension field element to square.
Definition at line 200 of file relic_fp6_sqr.c.
References dv6_free, dv6_new, dv6_null, ERR_CAUGHT, fp2_rdcn_low(), fp6_sqr_unr(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp6_inv()
void fp6_inv (fp6_t c, const fp6_t a)
Inverts a sextic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the sextic extension field element to invert.
Definition at line 342 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp2_add, fp2_free, fp2_inv(), fp2_mul, fp2_mul_nor, fp2_new, fp2_null, fp2_sqr, fp2_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp12_inv(), fp12_pck_max(), and fp6_exp().
fp6_exp()
void fp6_exp (fp6_t c, const fp6_t a, const bn_t b)
Computes a power of a sextic extension field element. Computes c = a^b.
Parameters
[out] c - the result.
[in] a - the sextic extension element to exponentiate.
[in] b - the exponent.
Definition at line 176 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), ERR_CAUGHT, fp6_copy(), fp6_free, fp6_inv(), fp6_mul, fp6_new, fp6_null, fp6_set_dig(), fp6_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
fp6_frb()
void fp6_frb (fp6_t c, const fp6_t a, int i)
Computes a power of the Frobenius endomorphism of a sextic extension field element. Computes c = a^p^i.
Parameters
[out] c - the result.
[in] a - a sextic extension field element.
[in] i - the power of the Frobenius map.
Definition at line 79 of file relic_fpx_frb.c.
References fp2_frb(), fp2_mul_frb(), and fp6_copy().
Referenced by fp12_frb().
fp8_field_init()
void fp8_field_init (void)
Initializes the octic extension field arithmetic module.
Definition at line 339 of file relic_fpx_field.c.
References bn_div_dig(), bn_free, bn_new, bn_null, bn_sub_dig(), core_get(), dv_copy(), ERR_CAUGHT, fp4_is_zero(), fp8_exp(), fp8_free, fp8_mul_art(), fp8_new, fp8_null, _ctx_t::fp8_p1, fp8_set_dig(), fp_copy(), fp_prime_get(), _ctx_t::frb8, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
Referenced by fp_prime_calc().
fp8_copy()
void fp8_copy (fp8_t c, const fp8_t a)
Copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the octic extension field element to copy.
Definition at line 320 of file relic_fpx_util.c.
References fp4_copy().
Referenced by ep8_copy(), ep8_curve_mul_a(), ep8_curve_mul_b(), ep8_curve_set(), ep8_curve_set_twist(), ep8_map(), ep8_neg(), ep8_norm_imp(), ep8_norm_sim(), ep8_rhs(), fp16_copy(), fp16_inv_cyc(), fp16_mul_art(), fp16_srt(), fp24_copy(), fp24_mul_art(), fp24_mul_basic(), fp24_mul_dxs(), fp48_back_cyc(), fp48_back_cyc_sim(), fp48_mul_dxs(), fp8_exp(), fp8_exp_cyc(), fp8_exp_cyc_sim(), fp8_exp_dig(), fp8_frb(), fp8_inv_sim(), fp8_mul_frb(), and pp_exp_k8().
fp8_copy_sec()
void fp8_copy_sec (fp8_t c, const fp8_t a, dig_t bit)
Conditionally copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the octic extension field element to copy.
[in] bit - the condition bit to evaluate.
Definition at line 325 of file relic_fpx_util.c.
References fp4_copy_sec().
Referenced by ep8_map(), ep8_mul_reg_gls(), ep8_mul_reg_imp(), fp16_copy_sec(), fp24_copy_sec(), fp48_back_cyc(), and fp48_back_cyc_sim().
fp8_zero()
void fp8_zero (fp8_t a)
Assigns zero to an octic extension field element.
Parameters
[out] a - the octic extension field element to zero.
Definition at line 330 of file relic_fpx_util.c.
References fp4_zero().
Referenced by ep8_curve_mul_a(), ep8_curve_mul_b(), ep8_curve_set_twist(), ep8_set_infty(), fp16_set_dig(), fp16_srt(), fp16_zero(), fp24_set_dig(), fp24_zero(), fp48_pck(), fp48_read_bin(), fp8_srt(), and pp_mil_k8().
fp8_is_zero()
int fp8_is_zero (const fp8_t a)
Tests if an octic extension field element is zero or not.
Parameters
[in] a - the octic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 335 of file relic_fpx_util.c.
References fp4_is_zero().
Referenced by detect_opt(), ep8_is_infty(), ep8_map(), fp16_cmp_dig(), fp16_is_zero(), fp16_srt(), fp24_cmp_dig(), fp24_is_zero(), fp24_mul_dxs(), fp48_back_cyc(), fp48_back_cyc_sim(), fp48_upk(), and fp8_srt().
fp8_rand()
void fp8_rand (fp8_t a)
Assigns a random value to an octic extension field element.
Parameters
[out] a - the octic extension field element to assign.
Definition at line 339 of file relic_fpx_util.c.
References fp4_rand().
Referenced by ep8_blind(), fp16_rand(), and fp24_rand().
fp8_print()
void fp8_print (const fp8_t a)
Prints an octic extension field element to standard output.
Parameters
[in] a - the octic extension field element to print.
Definition at line 344 of file relic_fpx_util.c.
References fp4_print().
Referenced by ep8_print(), fp16_print(), and fp24_print().
fp8_size_bin()
int fp8_size_bin (fp8_t a, int pack)
Returns the number of bytes necessary to store an octic extension field element.
Parameters
[in] a - the extension field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 349 of file relic_fpx_util.c.
References fp8_test_cyc(), and RLC_FP_BYTES.
fp8_read_bin()
void fp8_read_bin (fp8_t a, const uint8_t * bin, size_t len)
Reads an octic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 361 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp4_read_bin(), RLC_FP_BYTES, and RLC_THROW.
Referenced by ep8_read_bin(), fp16_read_bin(), fp24_read_bin(), and fp48_read_bin().
fp8_write_bin()
void fp8_write_bin (uint8_t * bin, size_t len, const fp8_t a, int pack)
Writes an octic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
[in] pack - the flag to indicate compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 370 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp4_write_bin(), RLC_FP_BYTES, and RLC_THROW.
Referenced by ep8_write_bin(), fp16_write_bin(), fp24_write_bin(), and fp48_write_bin().
fp8_cmp()
int fp8_cmp (const fp8_t a, const fp8_t b)
Returns the result of a comparison between two octic extension field elements.
Parameters
[in] a - the first octic extension field element.
[in] b - the second octic extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 89 of file relic_fpx_cmp.c.
References fp4_cmp(), RLC_EQ, and RLC_NE.
Referenced by detect_opt(), ep8_cmp(), ep8_on_curve(), fp16_cmp(), and fp24_cmp().
fp8_cmp_dig()
int fp8_cmp_dig (const fp8_t a, const dig_t b)
Returns the result of a signed comparison between an octic extension field element and a digit.
Parameters
[in] a - the octic extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 94 of file relic_fpx_cmp.c.
References fp4_cmp_dig(), fp4_is_zero(), RLC_EQ, and RLC_NE.
Referenced by detect_opt(), fp16_cmp_dig(), fp24_cmp_dig(), and fp8_test_cyc().
fp8_set_dig()
void fp8_set_dig (fp8_t a, const dig_t b)
Assigns an octic extension field element to a digit.
Parameters
[in] a - the octic extension field element.
[in] b - the digit.
Definition at line 379 of file relic_fpx_util.c.
References fp4_set_dig(), and fp4_zero().
Referenced by detect_opt(), ep8_curve_set_twist(), ep8_map(), ep8_mul_reg_gls(), ep8_mul_reg_imp(), ep8_norm_imp(), ep8_read_bin(), fp16_set_dig(), fp16_srt(), fp24_set_dig(), fp48_back_cyc(), fp48_back_cyc_sim(), fp8_exp(), fp8_exp_cyc(), fp8_exp_cyc_sim(), fp8_exp_dig(), fp8_field_init(), pp_map_oatep_k8(), pp_map_sim_oatep_k8(), and pp_norm_k48().
fp8_add()
void fp8_add (fp8_t c, const fp8_t a, const fp8_t b)
Adds two octic extension field elements. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first octic extension field element.
[in] b - the second octic extension field element.
Definition at line 202 of file relic_fpx_add.c.
References fp4_add().
Referenced by ep8_map(), ep8_rhs(), fp16_add(), fp16_mul_basic(), fp16_mul_dxs_basic(), fp16_mul_dxs_lazyr(), fp16_mul_unr(), fp16_sqr_basic(), fp16_sqr_cyc(), fp16_sqr_unr(), fp16_srt(), fp24_add(), fp24_inv(), fp24_mul_basic(), fp24_mul_dxs(), fp24_mul_unr(), fp24_sqr_basic(), fp24_sqr_unr(), fp48_back_cyc(), fp48_back_cyc_sim(), fp48_mul_dxs(), fp48_sqr_cyc_basic(), fp48_sqr_cyc_lazyr(), fp48_sqr_pck_basic(), fp48_sqr_pck_lazyr(), pp_add_k48_projc(), and pp_dbl_k48_projc().
fp8_sub()
void fp8_sub (fp8_t c, const fp8_t a, const fp8_t b)
Subtracts an octic extension field element from another. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the octic extension field element.
[in] b - the octic extension field element.
Definition at line 207 of file relic_fpx_add.c.
References fp4_sub().
Referenced by ep8_map(), fp16_inv(), fp16_mul_basic(), fp16_mul_dxs_basic(), fp16_sqr_basic(), fp16_sqr_cyc(), fp16_srt(), fp16_sub(), fp24_inv(), fp24_mul_basic(), fp24_mul_dxs(), fp24_sqr_basic(), fp24_sqr_unr(), fp24_sub(), fp48_back_cyc(), fp48_back_cyc_sim(), fp48_sqr_cyc_basic(), fp48_sqr_cyc_lazyr(), fp48_sqr_pck_basic(), fp48_sqr_pck_lazyr(), pp_add_k48_basic(), pp_add_k48_projc(), pp_dbl_k48_basic(), and pp_dbl_k48_projc().
fp8_neg()
void fp8_neg (fp8_t c, const fp8_t a)
Negates an octic extension field element. Computes c = -a.
Parameters
[out] c - the result.
[out] a - the octic extension field element to negate.
Definition at line 217 of file relic_fpx_add.c.
References fp4_neg().
Referenced by detect_opt(), ep8_map(), ep8_neg(), fp16_inv(), fp16_inv_cyc(), fp16_neg(), fp24_inv_cyc(), and fp24_neg().
fp8_dbl()
void fp8_dbl (fp8_t c, const fp8_t a)
Doubles an octic extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the octic extension field element to double.
Definition at line 212 of file relic_fpx_add.c.
References fp4_dbl().
Referenced by ep8_curve_mul_a(), ep8_map(), fp16_dbl(), fp16_sqr_basic(), fp16_sqr_cyc(), fp16_srt(), fp24_dbl(), fp24_sqr_basic(), fp48_back_cyc(), fp48_back_cyc_sim(), fp48_sqr_cyc_basic(), fp48_sqr_cyc_lazyr(), fp48_sqr_pck_basic(), fp48_sqr_pck_lazyr(), and pp_dbl_k48_projc().
fp8_mul_unr()
void fp8_mul_unr (dv8_t c, const fp8_t a, const fp8_t b)
Multiples two octic extension field elements without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the octic extension field element.
[in] b - the octic extension field element.
Definition at line 177 of file relic_fp8_mul.c.
References dv4_free, dv4_new, dv4_null, dv_copy(), ERR_CAUGHT, fp2_addc_low(), fp2_nord_low(), fp2_subc_low(), fp4_add(), fp4_free, fp4_mul_unr(), fp4_new, fp4_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
Referenced by fp16_mul_dxs_lazyr(), fp16_mul_unr(), fp24_mul_unr(), fp24_sqr_unr(), and fp8_mul_lazyr().
fp8_mul_basic()
void fp8_mul_basic (fp8_t c, const fp8_t a, const fp8_t b)
Multiples two octic extension field elements.
Parameters
[out] c - the result.
[in] a - the octic extension field element.
[in] b - the octic extension field element.
Definition at line 42 of file relic_fp8_mul.c.
References ERR_CAUGHT, fp4_add(), fp4_free, fp4_mul, fp4_mul_art(), fp4_new, fp4_null, fp4_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp8_mul_lazyr()
void fp8_mul_lazyr (fp8_t c, const fp8_t a, const fp8_t b)
Multiples two octic extension field elements using lazy reduction.
Parameters
[out] c - the result.
[in] a - the octic extension field element.
[in] b - the octic extension field element.
Definition at line 229 of file relic_fp8_mul.c.
References dv8_free, dv8_new, dv8_null, ERR_CAUGHT, fp2_rdcn_low(), fp8_mul_unr(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp8_mul_art()
void fp8_mul_art (fp8_t c, const fp8_t a)
Multiplies an octic extension field element by the adjoined root.
Parameters
[out] c - the result.
[in] a - the octic extension field element to multiply.
Definition at line 250 of file relic_fp8_mul.c.
References ERR_CAUGHT, fp4_copy(), fp4_free, fp4_mul_art(), fp4_new, fp4_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp16_frb(), fp16_inv(), fp16_mul_art(), fp16_mul_basic(), fp16_mul_dxs_basic(), fp16_sqr_basic(), fp16_sqr_cyc(), fp16_srt(), fp24_inv(), fp24_mul_art(), fp24_mul_basic(), fp24_mul_dxs(), fp24_sqr_basic(), fp48_back_cyc(), fp48_back_cyc_sim(), fp48_frb(), fp48_sqr_cyc_basic(), fp48_sqr_cyc_lazyr(), fp48_sqr_pck_basic(), fp48_sqr_pck_lazyr(), fp8_field_init(), and fp8_mul_frb().
fp8_mul_frb()
void fp8_mul_frb (fp8_t c, const fp8_t a, int i, int j)
Multiplies an octic extension field element by a power of the constant needed to compute a power of the Frobenius map.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
[in] i - the power of the Frobenius map.
[in] j - the power of the constant.
Definition at line 269 of file relic_fp8_mul.c.
References core_get(), ERR_CAUGHT, ERR_NO_VALID, fp2_mul, fp2_null, fp4_free, fp4_new, fp8_copy(), fp8_mul_art(), fp_copy(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep8_frb().
fp8_mul_dig()
void fp8_mul_dig (fp8_t c, const fp8_t a, dig_t b)
Multiplies an octic extension field element by a digit. Computes c = a * b.
Parameters
[out] c - the result.
[in] a - the octic extension field element.
[in] b - the digit to multiply.
Definition at line 302 of file relic_fp8_mul.c.
References fp4_mul_dig().
Referenced by ep8_curve_mul_a(), and ep8_curve_mul_b().
fp8_mul_dxs()
void fp8_mul_dxs (fp8_t c, const fp8_t a, const fp8_t b)
Multiples a dense octic extension field element by a sparse element.
Parameters
[out] c - the result.
[in] a - an octic extension field element.
[in] b - a sparse octic extension field element.
Definition at line 119 of file relic_fp8_mul.c.
References dv4_free, dv4_new, dv4_null, dv_copy(), ERR_CAUGHT, fp2_addc_low(), fp2_nord_low(), fp2_rdcn_low(), fp2_subc_low(), fp4_add(), fp4_free, fp4_mul_dxs_unr(), fp4_mul_unr(), fp4_new, fp4_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
Referenced by pp_mil_k8().
fp8_sqr_unr()
void fp8_sqr_unr (dv8_t c, const fp8_t a)
Computes the square of an octic extension field element without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the octic extension field element to square.
Definition at line 73 of file relic_fp8_sqr.c.
References dv4_free, dv4_new, dv4_null, dv_copy(), ERR_CAUGHT, fp2_addc_low(), fp2_nord_low(), fp2_subc_low(), fp4_add(), fp4_free, fp4_new, fp4_null, fp4_sqr_unr(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
Referenced by fp16_sqr_unr(), fp24_sqr_unr(), fp48_sqr_pck_lazyr(), and fp8_sqr_lazyr().
fp8_sqr_basic()
void fp8_sqr_basic (fp8_t c, const fp8_t a)
Computes the squares of an octic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the octic extension field element to square.
Definition at line 42 of file relic_fp8_sqr.c.
References ERR_CAUGHT, fp4_add(), fp4_dbl(), fp4_free, fp4_mul, fp4_mul_art(), fp4_new, fp4_null, fp4_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp8_sqr_lazyr()
void fp8_sqr_lazyr (fp8_t c, const fp8_t a)
Computes the square of an octic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the octic extension field element to square.
Definition at line 119 of file relic_fp8_sqr.c.
References dv8_free, dv8_new, dv8_null, ERR_CAUGHT, fp2_rdcn_low(), fp8_sqr_unr(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp8_sqr_cyc()
void fp8_sqr_cyc (fp8_t c, const fp8_t a)
Computes the square of a cyclotomic octic extension field element.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 140 of file relic_fp8_sqr.c.
References ERR_CAUGHT, fp4_add(), fp4_dbl(), fp4_free, fp4_mul_art(), fp4_new, fp4_null, fp4_sqr, fp4_sub(), fp_add_dig(), fp_sub_dig(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp8_exp_cyc(), fp8_exp_dig(), and pp_exp_k8().
fp8_inv()
void fp8_inv (fp8_t c, const fp8_t a)
Inverts an octic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the octic extension field element to invert.
Definition at line 406 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp4_free, fp4_inv(), fp4_mul, fp4_mul_art(), fp4_neg(), fp4_new, fp4_null, fp4_sqr, fp4_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep8_curve_set_twist(), ep8_map(), ep8_norm_imp(), fp16_inv(), fp16_srt(), fp24_inv(), fp48_back_cyc(), fp8_conv_cyc(), fp8_exp(), fp8_inv_sim(), and pp_norm_k48().
fp8_inv_cyc()
void fp8_inv_cyc (fp8_t c, const fp8_t a)
Computes the inverse of a cyclotomic octic extension field element.
For cyclotomic elements, this is equivalent to computing the conjugate. A cyclotomic element is one previously raised to the (p^4 - 1)-th power.
Parameters
[out] c - the result.
[in] a - the octic extension field element to invert.
Definition at line 401 of file relic_fpx_inv.c.
References fp4_copy(), and fp4_neg().
Referenced by fp24_inv_cyc(), fp8_conv_cyc(), fp8_exp_cyc(), fp8_exp_cyc_sim(), fp8_exp_dig(), fp8_test_cyc(), pp_exp_k8(), pp_map_oatep_k8(), and pp_map_sim_oatep_k8().
fp8_inv_sim()
void fp8_inv_sim (fp8_t * c, const fp8_t * a, int n)
Inverts multiple octic extension field elements simultaneously.
Parameters
[out] c - the result.
[in] a - the octic extension field elements to invert.
[in] n - the number of elements.
Definition at line 434 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp8_copy(), fp8_free, fp8_inv(), fp8_mul, fp8_new, fp8_null, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by ep8_norm_sim(), and fp48_back_cyc_sim().
fp8_test_cyc()
int fp8_test_cyc (const fp8_t a)
Tests if an octic extension field element is cyclotomic.
Parameters
[in] a - the octic extension field element to test.
Returns
1 if the extension field element is cyclotomic, 0 otherwise.
Definition at line 281 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp8_cmp_dig(), fp8_free, fp8_inv_cyc(), fp8_mul, fp8_new, fp8_null, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp8_exp(), fp8_exp_dig(), and fp8_size_bin().
fp8_conv_cyc()
void fp8_conv_cyc (fp8_t c, const fp8_t a)
Converts an octic extension field element to a cyclotomic element. Computes c = a^(p^4 - 1).
Parameters
[out] c - the result.
[in] a - the octic extension field element.
Definition at line 258 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp8_free, fp8_inv(), fp8_inv_cyc(), fp8_mul, fp8_new, fp8_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_exp_k8().
fp8_exp()
void fp8_exp (fp8_t c, const fp8_t a, const bn_t b)
Computes a power of an octic extension field element. Computes c = a^b.
Parameters
[out] c - the result.
[in] a - the octic extension element to exponentiate.
[in] b - the exponent.
Definition at line 212 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), ERR_CAUGHT, fp8_copy(), fp8_exp_cyc(), fp8_free, fp8_inv(), fp8_mul, fp8_new, fp8_null, fp8_set_dig(), fp8_sqr, fp8_test_cyc(), RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by fp8_field_init().
fp8_exp_dig()
void fp8_exp_dig (fp8_t c, const fp8_t a, dig_t b)
Computes a power of an octic extension field element by a small exponent.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 252 of file relic_fpx_exp.c.
References bn_bits(), bn_free, bn_new, bn_null, bn_rec_naf(), bn_set_dig(), ERR_CAUGHT, fp8_copy(), fp8_free, fp8_inv_cyc(), fp8_mul, fp8_new, fp8_null, fp8_set_dig(), fp8_sqr, fp8_sqr_cyc(), fp8_test_cyc(), RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_THROW, RLC_TRY, and util_bits_dig().
fp8_exp_cyc()
void fp8_exp_cyc (fp8_t c, const fp8_t a, const bn_t b)
Computes a power of a cyclotomic octic extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 303 of file relic_fpx_cyc.c.
References bn_bits(), bn_is_zero(), bn_rec_naf(), bn_sign(), ERR_CAUGHT, fp8_copy(), fp8_free, fp8_inv_cyc(), fp8_mul, fp8_new, fp8_null, fp8_set_dig(), fp8_sqr_cyc(), RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by fp8_exp(), fp8_exp_cyc_sim(), and pp_exp_k8().
fp8_exp_cyc_sim()
void fp8_exp_cyc_sim (fp8_t e, const fp8_t a, const bn_t b, const fp8_t c, const bn_t d)
Computes a power of two cyclotomic octic extension field elements.
Parameters
[out] e - the result.
[in] a - the first element to exponentiate.
[in] b - the first exponent.
[in] c - the second element to exponentiate.
[in] d - the second exponent.
Definition at line 371 of file relic_fpx_cyc.c.
References bn_is_zero(), bn_rec_naf(), bn_sign(), ERR_CAUGHT, fp8_copy(), fp8_exp_cyc(), fp8_free, fp8_inv_cyc(), fp8_mul, fp8_new, fp8_null, fp8_set_dig(), fp8_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
fp8_frb()
void fp8_frb (fp8_t c, const fp8_t a, int i)
Computes a power of the Frobenius endomorphism of an octic extension field element. Computes c = a^p^i.
Parameters
[out] c - the result.
[in] a - an octic extension field element.
[in] i - the power of the Frobenius map.
Definition at line 91 of file relic_fpx_frb.c.
References fp2_mul_frb(), fp4_frb(), fp4_mul_art(), fp8_copy(), and fp_prime_get_mod8().
Referenced by ep8_frb(), fp16_frb(), fp24_frb(), fp8_is_sqr(), and pp_exp_k8().
fp8_is_sqr()
int fp8_is_sqr (const fp8_t a)
Tests if an octic extension field element is a quadratic residue.
Parameters
[in] a - the prime field element to test.
Returns
1 if the argument is even, 0 otherwise.
Definition at line 458 of file relic_fpx_srt.c.
References ERR_CAUGHT, fp8_frb(), fp8_free, fp8_mul, fp8_new, fp8_null, fp_is_sqr(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep8_map(), and fp16_srt().
fp8_srt()
int fp8_srt (fp8_t c, const fp8_t a)
Extracts the square root of an octic extension field element. Computes c = sqrt(a). The other square root is the negation of c. The output value shall not be used in case 0 is returned.
Parameters
[out] c - the result.
[in] a - the extension field element.
Returns
- 1 if there is a square root, 0 otherwise.
Definition at line 486 of file relic_fpx_srt.c.
References ERR_CAUGHT, ERR_NO_VALID, fp4_add(), fp4_copy(), fp4_copy_sec(), fp4_dbl(), fp4_free, fp4_inv(), fp4_is_sqr(), fp4_is_zero(), fp4_mul, fp4_mul_art(), fp4_new, fp4_null, fp4_set_dig(), fp4_sqr, fp4_srt(), fp4_sub(), fp4_zero(), fp8_is_zero(), fp8_zero(), fp_hlv, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep8_map(), and fp16_srt().
fp9_copy()
void fp9_copy (fp9_t c, const fp9_t a)
Copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the nonic extension field element to copy.
Definition at line 384 of file relic_fpx_util.c.
References fp3_copy().
Referenced by ep9_add_basic(), ep9_dbl_basic(), fp18_copy(), fp18_inv_cyc(), fp18_mul_art(), fp54_back_cyc(), fp54_back_cyc_sim(), fp54_mul_dxs(), fp9_exp(), fp9_frb(), fp9_inv_sim(), pp_add_k54_basic(), pp_dbl_k54_basic(), and pp_mil_k54().
fp9_copy_sec()
void fp9_copy_sec (fp9_t c, const fp9_t a, dig_t bit)
Conditionally copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the nonic extension field element to copy.
[in] bit - the condition bit to evaluate.
Definition at line 390 of file relic_fpx_util.c.
References fp3_copy_sec().
Referenced by fp18_copy_sec(), fp54_back_cyc(), and fp54_back_cyc_sim().
fp9_zero()
void fp9_zero (fp9_t a)
Assigns zero to a nonic extension field element.
Parameters
[out] a - the nonic extension field element to zero.
Definition at line 396 of file relic_fpx_util.c.
References fp3_zero().
Referenced by ep9_add_basic(), fp18_set_dig(), fp18_zero(), fp54_pck(), fp54_read_bin(), pp_dbl_k54_projc(), and pp_mil_k54().
fp9_is_zero()
int fp9_is_zero (const fp9_t a)
Tests if a nonic extension field element is zero or not.
Parameters
[in] a - the nonic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 402 of file relic_fpx_util.c.
References fp3_is_zero().
Referenced by ep9_add_basic(), fp18_cmp_dig(), fp18_is_zero(), fp54_back_cyc(), fp54_back_cyc_sim(), fp54_upk(), and pp_map_k54().
fp9_rand()
void fp9_rand (fp9_t a)
Assigns a random value to a nonic extension field element.
Parameters
[out] a - the nonic extension field element to assign.
Definition at line 406 of file relic_fpx_util.c.
References fp3_rand().
Referenced by fp18_rand().
fp9_print()
void fp9_print (const fp9_t a)
Prints a nonic extension field element to standard output.
Parameters
[in] a - the nonic extension field element to print.
Definition at line 412 of file relic_fpx_util.c.
References fp3_print().
Referenced by fp18_print().
fp9_size_bin()
int fp9_size_bin (fp9_t a)
Returns the number of bytes necessary to store a quadratic extension field element.
Parameters
[out] size - the result.
[in] a - the extension field element.
Definition at line 418 of file relic_fpx_util.c.
References RLC_FP_BYTES.
fp9_read_bin()
void fp9_read_bin (fp9_t a, const uint8_t * bin, size_t len)
Reads a quadratic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 422 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp3_read_bin(), RLC_FP_BYTES, and RLC_THROW.
Referenced by fp18_read_bin(), and fp54_read_bin().
fp9_write_bin()
void fp9_write_bin (uint8_t * bin, size_t len, const fp9_t a)
Writes a nonic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 432 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp3_write_bin(), RLC_FP_BYTES, and RLC_THROW.
Referenced by fp18_write_bin(), and fp54_write_bin().
fp9_cmp()
int fp9_cmp (const fp9_t a, const fp9_t b)
Returns the result of a comparison between two nonic extension field elements.
Parameters
[in] a - the first nonic extension field element.
[in] b - the second nonic extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 79 of file relic_fpx_cmp.c.
References fp3_cmp(), RLC_EQ, and RLC_NE.
Referenced by fp18_cmp().
fp9_cmp_dig()
int fp9_cmp_dig (const fp9_t a, const dig_t b)
Returns the result of a signed comparison between a nonic extension field element and a digit.
Parameters
[in] a - the nonic extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 84 of file relic_fpx_cmp.c.
References fp3_cmp_dig(), fp3_is_zero(), RLC_EQ, and RLC_NE.
Referenced by fp18_cmp_dig().
fp9_set_dig()
void fp9_set_dig (fp9_t a, const dig_t b)
Assigns a nonic extension field element to a digit.
Parameters
[in] a - the nonic extension field element.
[in] b - the digit.
Definition at line 442 of file relic_fpx_util.c.
References fp3_set_dig(), and fp3_zero().
Referenced by ep3_curve_set_twist(), fp18_set_dig(), fp54_back_cyc(), fp54_back_cyc_sim(), fp9_exp(), and pp_mil_k54().
fp9_add()
void fp9_add (fp9_t c, const fp9_t a, const fp9_t b)
Adds two nonic extension field elements. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first nonic extension field element.
[in] b - the second nonic extension field element.
Definition at line 222 of file relic_fpx_add.c.
References fp3_add.
Referenced by ep9_dbl_basic(), fp18_add(), fp18_mul_basic(), fp18_mul_dxs_basic(), fp18_mul_dxs_lazyr(), fp18_mul_unr(), fp18_sqr_basic(), fp18_sqr_unr(), fp54_back_cyc(), fp54_back_cyc_sim(), fp54_mul_dxs(), fp54_sqr_cyc_basic(), fp54_sqr_cyc_lazyr(), fp54_sqr_pck_basic(), fp54_sqr_pck_lazyr(), pp_add_k54_projc(), and pp_dbl_k54_projc().
fp9_sub()
void fp9_sub (fp9_t c, const fp9_t a, const fp9_t b)
Subtracts a nonic extension field element from another. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the nonic extension field element.
[in] b - the nonic extension field element.
Definition at line 228 of file relic_fpx_add.c.
References fp3_sub.
Referenced by ep9_add_basic(), ep9_dbl_basic(), fp18_inv(), fp18_mul_basic(), fp18_mul_dxs_basic(), fp18_sqr_basic(), fp18_sub(), fp54_back_cyc(), fp54_back_cyc_sim(), fp54_sqr_cyc_basic(), fp54_sqr_cyc_lazyr(), fp54_sqr_pck_basic(), fp54_sqr_pck_lazyr(), pp_add_k54_basic(), pp_add_k54_projc(), pp_dbl_k54_basic(), and pp_dbl_k54_projc().
fp9_neg()
void fp9_neg (fp9_t c, const fp9_t a)
Negates a nonic extension field element. Computes c = -a.
Parameters
[out] c - the result.
[out] a - the nonic extension field element to negate.
Definition at line 240 of file relic_fpx_add.c.
References fp3_neg().
Referenced by fp18_inv(), fp18_inv_cyc(), fp18_neg(), and pp_mil_k54().
fp9_dbl()
void fp9_dbl (fp9_t c, const fp9_t a)
Doubles a nonic extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the nonic extension field element to double.
Definition at line 234 of file relic_fpx_add.c.
References fp3_dbl.
Referenced by ep9_dbl_basic(), fp18_dbl(), fp18_sqr_basic(), fp54_back_cyc(), fp54_back_cyc_sim(), fp54_sqr_cyc_basic(), fp54_sqr_cyc_lazyr(), fp54_sqr_pck_basic(), fp54_sqr_pck_lazyr(), and pp_dbl_k54_projc().
fp9_mul_unr()
void fp9_mul_unr (dv9_t c, const fp9_t a, const fp9_t b)
Multiples two nonic extension field elements without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the nonic extension field element.
[in] b - the nonic extension field element.
Definition at line 112 of file relic_fp9_mul.c.
References dv3_free, dv3_new, dv3_null, ERR_CAUGHT, fp3_addc_low(), fp3_addm_low(), fp3_free, fp3_muln_low(), fp3_new, fp3_nord_low(), fp3_null, fp3_subc_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp18_mul_unr(), and fp9_mul_lazyr().
fp9_mul_basic()
void fp9_mul_basic (fp9_t c, const fp9_t a, const fp9_t b)
Multiples two nonic extension field elements.
Parameters
[out] c - the result.
[in] a - the nonic extension field element.
[in] b - the nonic extension field element.
Definition at line 41 of file relic_fp9_mul.c.
References ERR_CAUGHT, fp3_add, fp3_copy(), fp3_free, fp3_mul, fp3_mul_nor(), fp3_new, fp3_null, fp3_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp9_mul_lazyr()
void fp9_mul_lazyr (fp9_t c, const fp9_t a, const fp9_t b)
Multiples two nonic extension field elements using lazy reduction.
Parameters
[out] c - the result.
[in] a - the nonic extension field element.
[in] b - the nonic extension field element.
Definition at line 185 of file relic_fp9_mul.c.
References dv9_free, dv9_new, dv9_null, ERR_CAUGHT, fp3_rdcn_low(), fp9_mul_unr(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp9_mul_art()
void fp9_mul_art (fp9_t c, const fp9_t a)
Multiplies a nonic extension field element by the adjoined root.
Parameters
[out] c - the result.
[in] a - the nonic extension field element to multiply.
Definition at line 262 of file relic_fp9_mul.c.
References ERR_CAUGHT, fp3_copy(), fp3_free, fp3_mul_nor(), fp3_new, fp3_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp18_inv(), fp18_mul_art(), fp18_mul_basic(), fp18_mul_dxs_basic(), fp18_sqr_basic(), fp54_back_cyc(), fp54_back_cyc_sim(), fp54_frb(), fp54_sqr_cyc_basic(), fp54_sqr_cyc_lazyr(), fp54_sqr_pck_basic(), and fp54_sqr_pck_lazyr().
fp9_mul_dxs()
void fp9_mul_dxs (fp9_t c, const fp9_t a, const fp9_t b)
Multiples a dense nonic extension field element by a sparse element.
Parameters
[out] c - the result.
[in] a - a nonic extension field element.
[in] b - a sparse nonic extension field element.
Definition at line 205 of file relic_fp9_mul.c.
References ERR_CAUGHT, fp3_add, fp3_copy(), fp3_free, fp3_mul, fp3_mul_nor(), fp3_new, fp3_null, fp3_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp18_mul_dxs_basic().
fp9_sqr_unr()
void fp9_sqr_unr (dv9_t c, const fp9_t a)
Computes the square of a nonic extension field element without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the nonic extension field element to square.
Definition at line 115 of file relic_fp9_sqr.c.
References dv3_free, dv3_new, dv3_null, ERR_CAUGHT, fp3_addc_low(), fp3_addm_low(), fp3_dblm_low(), fp3_free, fp3_muln_low(), fp3_new, fp3_nord_low(), fp3_null, fp3_sqrn_low(), fp3_subc_low(), fp3_subm_low(), fp_hlvd_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp18_sqr_unr(), fp54_sqr_pck_lazyr(), and fp9_sqr_lazyr().
fp9_sqr_basic()
void fp9_sqr_basic (fp9_t c, const fp9_t a)
Computes the squares of a nonic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the nonic extension field element to square.
Definition at line 42 of file relic_fp9_sqr.c.
References ERR_CAUGHT, fp3_add, fp3_dbl, fp3_free, fp3_mul, fp3_mul_nor(), fp3_new, fp3_null, fp3_sqr, fp3_sub, fp_hlv, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp9_sqr_lazyr()
void fp9_sqr_lazyr (fp9_t c, const fp9_t a)
Computes the square of a nonic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the nonic extension field element to square.
Definition at line 204 of file relic_fp9_sqr.c.
References dv9_free, dv9_new, dv9_null, ERR_CAUGHT, fp3_rdcn_low(), fp9_sqr_unr(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp9_inv()
void fp9_inv (fp9_t c, const fp9_t a)
Inverts a nonic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the nonic extension field element to invert.
Definition at line 477 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp3_add, fp3_free, fp3_inv(), fp3_mul, fp3_mul_nor(), fp3_new, fp3_null, fp3_sqr, fp3_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep9_add_basic(), ep9_dbl_basic(), fp18_inv(), fp54_back_cyc(), fp9_exp(), fp9_inv_sim(), and pp_mil_k54().
fp9_inv_sim()
void fp9_inv_sim (fp9_t * c, const fp9_t * a, int n)
Inverts multiple noinc extension field elements simultaneously.
Parameters
[out] c - the result.
[in] a - the nonic extension field elements to invert.
[in] n - the number of elements.
Definition at line 536 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp9_copy(), fp9_free, fp9_inv(), fp9_mul, fp9_new, fp9_null, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by fp54_back_cyc_sim().
fp9_exp()
void fp9_exp (fp9_t c, const fp9_t a, const bn_t b)
Computes a power of a nonic extension field element. Computes c = a^b.
Parameters
[out] c - the result.
[in] a - the nonic extension element to exponentiate.
[in] b - the exponent.
Definition at line 312 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), ERR_CAUGHT, fp9_copy(), fp9_free, fp9_inv(), fp9_mul, fp9_new, fp9_null, fp9_set_dig(), fp9_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
fp9_frb()
void fp9_frb (fp9_t c, const fp9_t a, int i)
Computes a power of the Frobenius endomorphism of a nonic extension field element. Computes c = a^p^i.
Parameters
[out] c - the result.
[in] a - a nonic extension field element.
[in] i - the power of the Frobenius map.
Definition at line 105 of file relic_fpx_frb.c.
References fp3_frb(), fp3_mul_frb(), and fp9_copy().
Referenced by fp18_frb(), and pp_mil_k54().
fp12_copy()
void fp12_copy (fp12_t c, const fp12_t a)
Copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to copy.
Definition at line 448 of file relic_fpx_util.c.
References fp6_copy().
Referenced by fp12_exp(), fp12_exp_cyc(), fp12_exp_cyc_sim(), fp12_exp_cyc_sps(), fp12_exp_dig(), fp12_frb(), fp12_pck(), fp12_pck_max(), fp12_upk(), fp12_upk_max(), and pp_exp_sm9().
fp12_copy_sec()
void fp12_copy_sec (fp12_t c, const fp12_t a, dig_t bit)
Conditionally copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to copy.
[in] bit - the condition bit to evaluate.
Definition at line 453 of file relic_fpx_util.c.
References fp6_copy_sec().
fp12_zero()
void fp12_zero (fp12_t a)
Assigns zero to a dodecic extension field element.
Parameters
[out] a - the dodecic extension field element to zero.
Definition at line 458 of file relic_fpx_util.c.
References fp6_zero().
Referenced by pp_fin_k12_oatep(), pp_mil_k12(), and pp_mil_lit_k12().
fp12_is_zero()
int fp12_is_zero (const fp12_t a)
Tests if a dodecic extension field element is zero or not.
Parameters
[in] a - the dodecic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 463 of file relic_fpx_util.c.
References fp6_is_zero().
fp12_rand()
void fp12_rand (fp12_t a)
Assigns a random value to a dodecic extension field element.
Parameters
[out] a - the dodecic extension field element to assign.
Definition at line 467 of file relic_fpx_util.c.
References fp6_rand().
fp12_print()
void fp12_print (const fp12_t a)
Prints a dodecic extension field element to standard output.
Parameters
[in] a - the dodecic extension field element to print.
Definition at line 472 of file relic_fpx_util.c.
References fp6_print().
fp12_size_bin()
int fp12_size_bin (fp12_t a, int pack)
Returns the number of bytes necessary to store a dodecic extension field element.
Parameters
[in] a - the extension field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 477 of file relic_fpx_util.c.
References fp12_test_cyc(), and RLC_FP_BYTES.
fp12_read_bin()
void fp12_read_bin (fp12_t a, const uint8_t * bin, size_t len)
Reads a dodecic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 489 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp12_back_cyc(), fp2_read_bin(), fp2_zero(), fp6_read_bin(), RLC_FP_BYTES, and RLC_THROW.
fp12_write_bin()
void fp12_write_bin (uint8_t * bin, size_t len, const fp12_t a, int pack)
Writes a dodecic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
[in] pack - the flag to indicate compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 509 of file relic_fpx_util.c.
References ERR_CAUGHT, ERR_NO_BUFFER, fp12_free, fp12_new, fp12_null, fp12_pck(), fp2_write_bin(), fp6_write_bin(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.
fp12_cmp()
int fp12_cmp (const fp12_t a, const fp12_t b)
Returns the result of a comparison between two dodecic extension field elements.
Parameters
[in] a - the first dodecic extension field element.
[in] b - the second dodecic extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 99 of file relic_fpx_cmp.c.
References fp6_cmp(), RLC_EQ, and RLC_NE.
Referenced by fp12_test_cyc().
fp12_cmp_dig()
int fp12_cmp_dig (const fp12_t a, const dig_t b)
Returns the result of a signed comparison between a dodecic extension field element and a digit.
Parameters
[in] a - the dodecic extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 104 of file relic_fpx_cmp.c.
References fp6_cmp_dig(), fp6_is_zero(), RLC_EQ, and RLC_NE.
Referenced by fp12_back_cyc(), and fp12_back_cyc_sim().
fp12_set_dig()
void fp12_set_dig (fp12_t a, const dig_t b)
Assigns a dodecic extension field element to a digit.
Parameters
[in] a - the dodecic extension field element.
[in] b - the digit.
Definition at line 540 of file relic_fpx_util.c.
References fp6_set_dig(), and fp6_zero().
Referenced by fp12_exp(), fp12_exp_cyc(), fp12_exp_cyc_sim(), fp12_exp_cyc_sps(), fp12_exp_dig(), pp_map_oatep_k12(), pp_map_sim_oatep_k12(), pp_map_sim_tatep_k12(), pp_map_sim_weilp_k12(), pp_map_tatep_k12(), and pp_map_weilp_k12().
fp12_add()
void fp12_add (fp12_t c, const fp12_t a, const fp12_t b)
Adds two dodecic extension field elements. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first dodecic extension field element.
[in] b - the second dodecic extension field element.
Definition at line 246 of file relic_fpx_add.c.
References fp6_add().
fp12_sub()
void fp12_sub (fp12_t c, const fp12_t a, const fp12_t b)
Subtracts a dodecic extension field element from another. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the first dodecic extension field element.
[in] b - the second dodecic extension field element.
Definition at line 251 of file relic_fpx_add.c.
References fp6_sub().
fp12_neg()
void fp12_neg (fp12_t c, const fp12_t a)
Negates a dodecic extension field element.
Parameters
[out] c - the result.
[out] a - the dodecic extension field element to negate.
Definition at line 256 of file relic_fpx_add.c.
References fp6_neg().
fp12_dbl()
void fp12_dbl (fp12_t c, const fp12_t a)
Doubles a dodecic extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to double.
Definition at line 261 of file relic_fpx_add.c.
References fp6_dbl().
fp12_mul_unr()
void fp12_mul_unr (dv12_t c, const fp12_t a, const fp12_t b)
Multiples two dodecic extension field elements without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element.
[in] b - the dodecic extension field element.
Definition at line 227 of file relic_fp12_mul.c.
References dv6_free, dv6_new, dv6_null, ERR_CAUGHT, fp2_addc_low(), fp2_nord_low(), fp2_subc_low(), fp6_add(), fp6_free, fp6_mul_unr(), fp6_new, fp6_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp12_mul_lazyr().
fp12_mul_basic()
void fp12_mul_basic (fp12_t c, const fp12_t a, const fp12_t b)
Multiples two dodecic extension field elements using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element.
[in] b - the dodecic extension field element.
Definition at line 99 of file relic_fp12_mul.c.
References ERR_CAUGHT, fp6_add(), fp6_free, fp6_mul, fp6_mul_art(), fp6_new, fp6_null, fp6_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp12_mul_lazyr()
void fp12_mul_lazyr (fp12_t c, const fp12_t a, const fp12_t b)
Multiples two dodecic extension field elements using lazy reduction.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element.
[in] b - the dodecic extension field element.
Definition at line 280 of file relic_fp12_mul.c.
References dv12_free, dv12_new, dv12_null, ERR_CAUGHT, fp12_mul_unr(), fp2_rdcn_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp12_mul_art()
void fp12_mul_art (fp12_t c, const fp12_t a)
Multiplies a dodecic extension field element by the adjoined root.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to multiply.
Definition at line 398 of file relic_fp12_mul.c.
References ERR_CAUGHT, fp6_copy(), fp6_free, fp6_mul_art(), fp6_new, fp6_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp12_mul_dxs_basic()
void fp12_mul_dxs_basic (fp12_t c, const fp12_t a, const fp12_t b)
Multiples a dense dodecic extension field element by a sparse element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the dense dodecic extension field element.
[in] b - the sparse dodecic extension field element.
Definition at line 140 of file relic_fp12_mul.c.
References ep2_curve_is_twist(), ERR_CAUGHT, fp2_add, fp2_copy(), fp2_mul, fp2_mul_nor, fp6_add(), fp6_free, fp6_mul_art(), fp6_mul_dxs(), fp6_new, fp6_null, fp6_sub(), fp_add, fp_copy(), fp_mul, RLC_CATCH_ANY, RLC_EP_DTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp12_mul_dxs_lazyr()
void fp12_mul_dxs_lazyr (fp12_t c, const fp12_t a, const fp12_t b)
Multiples a dense dodecic extension field element by a sparse element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the dense dodecic extension field element.
[in] b - the sparse dodecic extension field element.
Definition at line 299 of file relic_fp12_mul.c.
References dv6_free, dv6_new, dv6_null, ep2_curve_is_twist(), ERR_CAUGHT, fp2_add, fp2_addc_low(), fp2_copy(), fp2_muln_low(), fp2_nord_low(), fp2_rdcn_low(), fp2_subc_low(), fp6_add(), fp6_free, fp6_mul_dxs_unr_lazyr(), fp6_new, fp6_null, fp_add, fp_copy(), fp_muln_low(), RLC_CATCH_ANY, RLC_EP_DTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp12_sqr_unr()
void fp12_sqr_unr (dv12_t c, const fp12_t a)
Computes the square of a dodecic extension field element without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to square.
Definition at line 237 of file relic_fp12_sqr.c.
References dv4_free, dv4_new, dv4_null, ERR_CAUGHT, fp2_addc_low(), fp2_addd_low(), fp2_addm_low(), fp2_copy(), fp2_nord_low(), fp2_subc_low(), fp2_subm_low(), fp4_free, fp4_mul_unr(), fp4_new, fp4_null, fp4_sqr_unr(), fp_hlvd_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp12_sqr_lazyr().
fp12_sqr_basic()
void fp12_sqr_basic (fp12_t c, const fp12_t a)
Computes the square of a dodecic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to square.
Definition at line 42 of file relic_fp12_sqr.c.
References ERR_CAUGHT, fp6_add(), fp6_dbl(), fp6_free, fp6_mul, fp6_mul_art(), fp6_new, fp6_null, fp6_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp12_sqr_lazyr()
void fp12_sqr_lazyr (fp12_t c, const fp12_t a)
Computes the square of a dodecic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to square.
Definition at line 340 of file relic_fp12_sqr.c.
References dv12_free, dv12_new, dv12_null, ERR_CAUGHT, fp12_sqr_unr(), fp2_rdcn_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp12_sqr_cyc_basic()
void fp12_sqr_cyc_basic (fp12_t c, const fp12_t a)
Computes the square of a cyclotomic dodecic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 69 of file relic_fp12_sqr.c.
References ERR_CAUGHT, fp2_add, fp2_dbl, fp2_free, fp2_mul_nor, fp2_new, fp2_null, fp2_sqr, fp2_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp12_sqr_cyc_lazyr()
void fp12_sqr_cyc_lazyr (fp12_t c, const fp12_t a)
Computes the square of a cyclotomic dodecic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 359 of file relic_fp12_sqr.c.
References dv2_free, dv2_new, dv2_null, ERR_CAUGHT, fp2_addc_low(), fp2_addm_low(), fp2_dblm_low(), fp2_free, fp2_new, fp2_norh_low(), fp2_norm_low(), fp2_null, fp2_rdcn_low(), fp2_sqrm_low(), fp2_sqrn_low(), fp2_subc_low(), fp2_subm_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp12_sqr_pck_basic()
void fp12_sqr_pck_basic (fp12_t c, const fp12_t a)
Computes the square of a compressed cyclotomic extension field element.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 163 of file relic_fp12_sqr.c.
References ERR_CAUGHT, fp2_add, fp2_dbl, fp2_free, fp2_mul_nor, fp2_new, fp2_null, fp2_sqr, fp2_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp12_sqr_pck_lazyr()
void fp12_sqr_pck_lazyr (fp12_t c, const fp12_t a)
Computes the square of a compressed cyclotomic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 455 of file relic_fp12_sqr.c.
References dv2_free, dv2_new, dv2_null, ERR_CAUGHT, fp2_addc_low(), fp2_addm_low(), fp2_dblm_low(), fp2_free, fp2_new, fp2_norh_low(), fp2_norm_low(), fp2_null, fp2_rdcn_low(), fp2_sqrm_low(), fp2_sqrn_low(), fp2_subc_low(), fp2_subm_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp12_test_cyc()
int fp12_test_cyc (const fp12_t a)
Tests if a dodecic extension field element belongs to the cyclotomic subgroup.
A cyclotomic element is one raised to the (p^6 - 1)(p^2 + 1)-th power.
Parameters
[in] a - the dodecic extension field element to test.
Returns
1 if the extension field element is in the subgroup, 0 otherwise.
Definition at line 504 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp12_cmp(), fp12_frb(), fp12_free, fp12_mul, fp12_new, fp12_null, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp12_exp(), fp12_exp_dig(), fp12_pck(), fp12_pck_max(), fp12_size_bin(), fp12_upk(), fp12_upk_max(), and gt_is_valid().
fp12_conv_cyc()
void fp12_conv_cyc (fp12_t c, const fp12_t a)
Converts a dodecic extension field element to a cyclotomic element. Computes c = a^(p^6 - 1)*(p^2 + 1).
Parameters
[out] c - the result.
[in] a - a dodecic extension field element.
Definition at line 473 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp12_frb(), fp12_free, fp12_inv(), fp12_inv_cyc(), fp12_mul, fp12_new, fp12_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_exp_b12(), pp_exp_bn(), and pp_exp_sm9().
fp12_back_cyc()
void fp12_back_cyc (fp12_t c, const fp12_t a)
Decompresses a compressed cyclotomic extension field element.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to decompress.
Definition at line 533 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp12_cmp_dig(), fp2_add, fp2_copy(), fp2_copy_sec(), fp2_dbl, fp2_free, fp2_inv(), fp2_is_zero(), fp2_mul, fp2_mul_nor, fp2_new, fp2_null, fp2_set_dig(), fp2_sqr, fp2_sub, fp_add_dig(), RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp12_read_bin(), and fp12_upk().
fp12_back_cyc_sim()
void fp12_back_cyc_sim (fp12_t * c, const fp12_t * a, int n)
Decompresses multiple compressed cyclotomic extension field elements.
Parameters
[out] c - the result.
[in] a - the dodecic field elements to decompress.
[in] n - the number of field elements to decompress.
fp12_inv()
void fp12_inv (fp12_t c, const fp12_t a)
Inverts a dodecic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to invert.
Definition at line 579 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp6_free, fp6_inv(), fp6_mul, fp6_mul_art(), fp6_neg(), fp6_new, fp6_null, fp6_sqr, fp6_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp12_conv_cyc(), fp12_exp(), fp12_upk_max(), pp_map_sim_weilp_k12(), and pp_map_weilp_k12().
fp12_inv_cyc()
void fp12_inv_cyc (fp12_t c, const fp12_t a)
Computes the inverse of a cyclotomic dodecic extension field element. For unitary elements, this is equivalent to computing the conjugate. A unitary element is one previously raised to the (p^6 - 1)-th power.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to invert.
Definition at line 607 of file relic_fpx_inv.c.
References fp6_copy(), and fp6_neg().
Referenced by fp12_conv_cyc(), fp12_exp_cyc(), fp12_exp_cyc_sim(), fp12_exp_cyc_sps(), fp12_exp_dig(), pp_exp_b12(), pp_exp_bn(), pp_exp_sm9(), pp_map_oatep_k12(), pp_map_sim_oatep_k12(), pp_map_sim_weilp_k12(), and pp_map_weilp_k12().
fp12_frb()
void fp12_frb (fp12_t c, const fp12_t a, int i)
Computes the Frobenius endomorphism of a dodecic extension element. Computes c = a^p.
Parameters
[out] c - the result.
[in] a - a dodecic extension field element.
[in] i - the power of the Frobenius map.
Definition at line 117 of file relic_fpx_frb.c.
References fp12_copy(), fp2_frb(), fp2_mul_frb(), and fp6_frb().
Referenced by fp12_conv_cyc(), fp12_exp_cyc_sim(), fp12_test_cyc(), pp_exp_b12(), pp_exp_bn(), and pp_exp_sm9().
fp12_exp()
void fp12_exp (fp12_t c, const fp12_t a, const bn_t b)
Computes a power of a dodecic extension field element. Faster formulas are used if the extension field element is cyclotomic.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 348 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), ERR_CAUGHT, fp12_copy(), fp12_exp_cyc(), fp12_free, fp12_inv(), fp12_mul, fp12_new, fp12_null, fp12_set_dig(), fp12_sqr, fp12_test_cyc(), RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
fp12_exp_dig()
void fp12_exp_dig (fp12_t c, const fp12_t a, dig_t b)
Computes a power of a dodecic extension field element by a small exponent. Faster formulas are used if the extension field element is cyclotomic.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 388 of file relic_fpx_exp.c.
References bn_bits(), bn_free, bn_new, bn_null, bn_rec_naf(), bn_set_dig(), ERR_CAUGHT, fp12_copy(), fp12_free, fp12_inv_cyc(), fp12_mul, fp12_new, fp12_null, fp12_set_dig(), fp12_sqr, fp12_sqr_cyc, fp12_test_cyc(), RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_THROW, RLC_TRY, and util_bits_dig().
fp12_exp_cyc()
void fp12_exp_cyc (fp12_t c, const fp12_t a, const bn_t b)
Computes a power of a cyclotomic dodecic extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 691 of file relic_fpx_cyc.c.
References bn_bits(), bn_get_bit(), bn_ham(), bn_is_even(), bn_is_zero(), bn_rec_naf(), bn_sign(), ERR_CAUGHT, ERR_NO_MEMORY, fp12_back_cyc_sim(), fp12_copy(), fp12_free, fp12_inv_cyc(), fp12_mul, fp12_new, fp12_null, fp12_set_dig(), fp12_sqr_cyc, fp12_sqr_pck, RLC_ALLOCA, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FP_BITS, RLC_FREE, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by fp12_exp(), and fp12_exp_cyc_sim().
fp12_exp_cyc_gls()
void fp12_exp_cyc_gls (fp12_t c, const fp12_t a, const bn_t b)
Computes a power of a cyclotomic dodecic extension field element in the prime-order subgroup.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
fp12_exp_cyc_sim()
void fp12_exp_cyc_sim (fp12_t e, const fp12_t a, const bn_t b, const fp12_t c, const bn_t d)
Computes a power of two cyclotomic dodecic extension field elements.
Parameters
[out] e - the result.
[in] a - the first element to exponentiate.
[in] b - the first exponent.
[in] c - the second element to exponentiate.
[in] d - the second exponent.
Definition at line 819 of file relic_fpx_cyc.c.
References bn_abs(), bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_neg(), bn_new, bn_null, bn_rec_frb(), bn_sign(), EP_BN, ep_curve_embed(), ep_curve_get_ord(), ep_curve_is_pairf(), ERR_CAUGHT, fp12_copy(), fp12_exp_cyc(), fp12_frb(), fp12_free, fp12_inv_cyc(), fp12_mul, fp12_new, fp12_null, fp12_set_dig(), fp12_sqr_cyc, fp_prime_get_par(), RLC_CATCH_ANY, RLC_FINALLY, RLC_MAX, RLC_NEG, RLC_THROW, and RLC_TRY.
fp12_exp_cyc_sps()
void fp12_exp_cyc_sps (fp12_t c, const fp12_t a, const int * b, size_t l, int s)
Computes a power of a cyclotomic dodecic extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent in sparse form.
[in] l - the length of the exponent in sparse form.
[in] s - the sign of the exponent.
Definition at line 932 of file relic_fpx_cyc.c.
References ERR_CAUGHT, ERR_NO_MEMORY, fp12_back_cyc_sim(), fp12_copy(), fp12_free, fp12_inv_cyc(), fp12_mul, fp12_new, fp12_null, fp12_set_dig(), fp12_sqr_pck, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by gt_is_valid(), pp_exp_b12(), pp_exp_bn(), and pp_exp_sm9().
fp12_pck()
void fp12_pck (fp12_t c, const fp12_t a)
Compresses a dodecic extension field element.
Parameters
[out] r - the result.
[in] p - the dodecic extension field element to compress.
Definition at line 87 of file relic_fpx_pck.c.
References fp12_copy(), fp12_test_cyc(), and fp2_zero().
Referenced by fp12_write_bin().
fp12_upk()
int fp12_upk (fp12_t c, const fp12_t a)
Decompresses a dodecic extension field element.
Parameters
[out] r - the result.
[in] p - the dodecic extension field element to decompress.
Returns
if the decompression was successful
Definition at line 95 of file relic_fpx_pck.c.
References fp12_back_cyc(), fp12_copy(), fp12_test_cyc(), and fp2_is_zero().
fp12_pck_max()
void fp12_pck_max (fp12_t c, const fp12_t a)
Compresses a dodecic extension field element at the maximum rate.
Parameters
[out] r - the result.
[in] p - the dodecic extension field element to compress.
Definition at line 109 of file relic_fpx_pck.c.
References fp12_copy(), fp12_test_cyc(), fp2_add_dig(), fp6_inv(), fp6_mul, and fp6_zero().
fp12_upk_max()
int fp12_upk_max (fp12_t c, const fp12_t a)
Decompresses a dodecic extension field element at the maximum rate.
Parameters
[out] r - the result.
[in] p - the dodecic extension field element to decompress.
Returns
if the decompression was successful
Definition at line 122 of file relic_fpx_pck.c.
References ERR_CAUGHT, fp12_copy(), fp12_free, fp12_inv(), fp12_mul, fp12_new, fp12_null, fp12_test_cyc(), fp6_copy(), fp6_is_zero(), fp6_set_dig(), fp6_zero(), fp_neg, fp_set_dig(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp16_field_init()
void fp16_field_init (void)
Initializes the sextadecic extension field arithmetic module.
fp16_copy()
void fp16_copy (fp16_t c, const fp16_t a)
Copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the sextadecic extension field element to copy.
Definition at line 545 of file relic_fpx_util.c.
References fp8_copy().
Referenced by fp16_exp(), fp16_exp_cyc(), fp16_exp_cyc_sim(), fp16_exp_dig(), fp16_frb(), fp16_inv_sim(), and pp_exp_afg16().
fp16_copy_sec()
void fp16_copy_sec (fp16_t c, const fp16_t a, dig_t bit)
Conditionally copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the sextadecic extension field element to copy.
[in] bit - the condition bit to evaluate.
Definition at line 550 of file relic_fpx_util.c.
References fp8_copy_sec().
fp16_zero()
void fp16_zero (fp16_t a)
Assigns zero to an sextadecic extension field element.
Parameters
[out] a - the sextadecic extension field element to zero.
Definition at line 555 of file relic_fpx_util.c.
References fp8_zero().
Referenced by fp16_srt(), pp_fin_k16_oatep(), pp_mil_k16(), and pp_mil_lit_k16().
fp16_is_zero()
int fp16_is_zero (const fp16_t a)
Tests if an sextadecic extension field element is zero or not.
Parameters
[in] a - the sextadecic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 560 of file relic_fpx_util.c.
References fp8_is_zero().
Referenced by fp16_srt().
fp16_rand()
void fp16_rand (fp16_t a)
Assigns a random value to an sextadecic extension field element.
Parameters
[out] a - the sextadecic extension field element to assign.
Definition at line 564 of file relic_fpx_util.c.
References fp8_rand().
fp16_print()
void fp16_print (const fp16_t a)
Prints an sextadecic extension field element to standard output.
Parameters
[in] a - the sextadecic extension field element to print.
Definition at line 569 of file relic_fpx_util.c.
References fp8_print().
fp16_size_bin()
int fp16_size_bin (fp16_t a, int pack)
Returns the number of bytes necessary to store an sextadecic extension field element.
Parameters
[in] a - the extension field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 574 of file relic_fpx_util.c.
References fp16_test_cyc(), and RLC_FP_BYTES.
fp16_read_bin()
void fp16_read_bin (fp16_t a, const uint8_t * bin, size_t len)
Reads an sextadecic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 586 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp8_read_bin(), RLC_FP_BYTES, and RLC_THROW.
fp16_write_bin()
void fp16_write_bin (uint8_t * bin, size_t len, const fp16_t a, int pack)
Writes an sextadecic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
[in] pack - the flag to indicate compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 595 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp8_write_bin(), RLC_FP_BYTES, and RLC_THROW.
fp16_cmp()
int fp16_cmp (const fp16_t a, const fp16_t b)
Returns the result of a comparison between two sextadecic extension field elements.
Parameters
[in] a - the first sextadecic extension field element.
[in] b - the second sextadecic extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 109 of file relic_fpx_cmp.c.
References fp8_cmp(), RLC_EQ, and RLC_NE.
fp16_cmp_dig()
int fp16_cmp_dig (const fp16_t a, const dig_t b)
Returns the result of a signed comparison between an sextadecic extension field element and a digit.
Parameters
[in] a - the sextadecic extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 114 of file relic_fpx_cmp.c.
References fp8_cmp_dig(), fp8_is_zero(), RLC_EQ, and RLC_NE.
Referenced by fp16_test_cyc().
fp16_set_dig()
void fp16_set_dig (fp16_t a, const dig_t b)
Assigns an sextadecic extension field element to a digit.
Parameters
[in] a - the sextadecic extension field element.
[in] b - the digit.
Definition at line 604 of file relic_fpx_util.c.
References fp8_set_dig(), and fp8_zero().
Referenced by fp16_exp(), fp16_exp_cyc(), fp16_exp_cyc_sim(), fp16_exp_dig(), pp_map_oatep_k16(), pp_map_sim_oatep_k16(), pp_map_sim_tatep_k16(), pp_map_sim_weilp_k16(), pp_map_tatep_k16(), and pp_map_weilp_k16().
fp16_add()
void fp16_add (fp16_t c, const fp16_t a, const fp16_t b)
Adds two sextadecic extension field elements. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first sextadecic extension field element.
[in] b - the second sextadecic extension field element.
Definition at line 266 of file relic_fpx_add.c.
References fp8_add().
fp16_sub()
void fp16_sub (fp16_t c, const fp16_t a, const fp16_t b)
Subtracts an sextadecic extension field element from another. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the sextadecic extension field element.
[in] b - the sextadecic extension field element.
Definition at line 271 of file relic_fpx_add.c.
References fp8_sub().
fp16_neg()
void fp16_neg (fp16_t c, const fp16_t a)
Negates an sextadecic extension field element. Computes c = -a.
Parameters
[out] c - the result.
[out] a - the sextadecic extension field element to negate.
Definition at line 281 of file relic_fpx_add.c.
References fp8_neg().
fp16_dbl()
void fp16_dbl (fp16_t c, const fp16_t a)
Doubles an sextadecic extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the sextadecic extension field element to double.
Definition at line 276 of file relic_fpx_add.c.
References fp8_dbl().
fp16_mul_unr()
void fp16_mul_unr (dv16_t c, const fp16_t a, const fp16_t b)
Multiples two sextadecic extension field elements without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the sextadecic extension field element.
[in] b - the sextadecic extension field element.
Definition at line 153 of file relic_fp16_mul.c.
References dv8_free, dv8_new, dv8_null, dv_copy(), ERR_CAUGHT, fp2_addc_low(), fp2_nord_low(), fp2_subc_low(), fp8_add(), fp8_free, fp8_mul_unr(), fp8_new, fp8_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
Referenced by fp16_mul_lazyr().
fp16_mul_basic()
void fp16_mul_basic (fp16_t c, const fp16_t a, const fp16_t b)
Multiples two sextadecic extension field elements.
Parameters
[out] c - the result.
[in] a - the sextadecic extension field element.
[in] b - the sextadecic extension field element.
Definition at line 42 of file relic_fp16_mul.c.
References ERR_CAUGHT, fp8_add(), fp8_free, fp8_mul, fp8_mul_art(), fp8_new, fp8_null, fp8_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp16_mul_lazyr()
void fp16_mul_lazyr (fp16_t c, const fp16_t a, const fp16_t b)
Multiples two sextadecic extension field elements using lazy reduction.
Parameters
[out] c - the result.
[in] a - the sextadecic extension field element.
[in] b - the sextadecic extension field element.
Definition at line 216 of file relic_fp16_mul.c.
References dv16_free, dv16_new, dv16_null, ERR_CAUGHT, fp16_mul_unr(), fp2_rdcn_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp16_mul_art()
void fp16_mul_art (fp16_t c, const fp16_t a)
Multiplies an sextadecic extension field element by the adjoined root.
Parameters
[out] c - the result.
[in] a - the sextadecic extension field element to multiply.
Definition at line 343 of file relic_fp16_mul.c.
References ERR_CAUGHT, fp8_copy(), fp8_free, fp8_mul_art(), fp8_new, fp8_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp16_mul_frb()
void fp16_mul_frb (fp16_t c, const fp16_t a, int i, int j)
Multiplies an sextadecic extension field element by a power of the constant needed to compute a power of the Frobenius map.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
[in] i - the power of the Frobenius map.
[in] j - the power of the constant.
fp16_mul_dxs()
void fp16_mul_dxs (fp16_t c, const fp16_t a, const fp16_t b)
Multiples a dense sextadecic extension field element by a sparse element.
Parameters
[out] c - the result.
[in] a - an sextadecic extension field element.
[in] b - a sparse sextadecic extension field element.
fp16_sqr_unr()
void fp16_sqr_unr (dv16_t c, const fp16_t a)
Computes the square of an sextadecic extension field element without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the sextadecic extension field element to square.
Definition at line 73 of file relic_fp16_sqr.c.
References dv8_free, dv8_new, dv8_null, dv_copy(), ERR_CAUGHT, fp2_addc_low(), fp2_nord_low(), fp2_subc_low(), fp8_add(), fp8_free, fp8_new, fp8_null, fp8_sqr_unr(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
Referenced by fp16_sqr_lazyr().
fp16_sqr_basic()
void fp16_sqr_basic (fp16_t c, const fp16_t a)
Computes the squares of an sextadecic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the sextadecic extension field element to square.
Definition at line 42 of file relic_fp16_sqr.c.
References ERR_CAUGHT, fp8_add(), fp8_dbl(), fp8_free, fp8_mul, fp8_mul_art(), fp8_new, fp8_null, fp8_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp16_sqr_lazyr()
void fp16_sqr_lazyr (fp16_t c, const fp16_t a)
Computes the square of an sextadecic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the sextadecic extension field element to square.
Definition at line 129 of file relic_fp16_sqr.c.
References dv16_free, dv16_new, dv16_null, ERR_CAUGHT, fp16_sqr_unr(), fp2_rdcn_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp16_sqr_cyc()
void fp16_sqr_cyc (fp16_t c, const fp16_t a)
Computes the square of a cyclotomic sextadecic extension field element.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 153 of file relic_fp16_sqr.c.
References ERR_CAUGHT, fp8_add(), fp8_dbl(), fp8_free, fp8_mul_art(), fp8_new, fp8_null, fp8_sqr, fp8_sub(), fp_add_dig(), fp_sub_dig(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp16_exp_cyc(), fp16_exp_cyc_sim(), fp16_exp_dig(), pp_exp_afg16(), and pp_exp_kss().
fp16_inv()
void fp16_inv (fp16_t c, const fp16_t a)
Inverts an sextadecic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the sextadecic extension field element to invert.
Definition at line 617 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp8_free, fp8_inv(), fp8_mul, fp8_mul_art(), fp8_neg(), fp8_new, fp8_null, fp8_sqr, fp8_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp16_conv_cyc(), fp16_exp(), fp16_inv_sim(), pp_map_sim_weilp_k16(), and pp_map_weilp_k16().
fp16_inv_cyc()
void fp16_inv_cyc (fp16_t c, const fp16_t a)
Computes the inverse of a cyclotomic sextadecic extension field element.
For cyclotomic elements, this is equivalent to computing the conjugate. A cyclotomic element is one previously raised to the (p^4 - 1)-th power.
Parameters
[out] c - the result.
[in] a - the sextadecic extension field element to invert.
Definition at line 612 of file relic_fpx_inv.c.
References fp8_copy(), and fp8_neg().
Referenced by fp16_conv_cyc(), fp16_exp_cyc(), fp16_exp_cyc_sim(), fp16_exp_dig(), fp16_test_cyc(), pp_exp_afg16(), pp_exp_kss(), pp_map_oatep_k16(), pp_map_sim_oatep_k16(), pp_map_sim_weilp_k16(), and pp_map_weilp_k16().
fp16_inv_sim()
void fp16_inv_sim (fp16_t * c, const fp16_t * a, int n)
Inverts multiple sextadecic extension field elements simultaneously.
Parameters
[out] c - the result.
[in] a - the sextadecic extension field elements to invert.
[in] n - the number of elements.
Definition at line 645 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp16_copy(), fp16_free, fp16_inv(), fp16_mul, fp16_new, fp16_null, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
fp16_test_cyc()
int fp16_test_cyc (const fp16_t a)
Tests if an sextadecic extension field element is cyclotomic.
Parameters
[in] a - the sextadecic extension field element to test.
Returns
1 if the extension field element is cyclotomic, 0 otherwise.
Definition at line 1035 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp16_cmp_dig(), fp16_free, fp16_inv_cyc(), fp16_mul, fp16_new, fp16_null, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp16_exp(), fp16_exp_dig(), fp16_size_bin(), and gt_is_valid().
fp16_conv_cyc()
void fp16_conv_cyc (fp16_t c, const fp16_t a)
Converts an sextadecic extension field element to a cyclotomic element. Computes c = a^(p^8 - 1).
Parameters
[out] c - the result.
[in] a - the sextadecic extension field element.
Definition at line 1012 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp16_free, fp16_inv(), fp16_inv_cyc(), fp16_mul, fp16_new, fp16_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_exp_afg16(), pp_exp_fm16(), and pp_exp_kss().
fp16_exp()
void fp16_exp (fp16_t c, const fp16_t a, const bn_t b)
Computes a power of an sextadecic extension field element. Computes c = a^b.
Parameters
[out] c - the result.
[in] a - the sextadecic extension element to exponentiate.
[in] b - the exponent.
Definition at line 448 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), ERR_CAUGHT, fp16_copy(), fp16_exp_cyc(), fp16_free, fp16_inv(), fp16_mul, fp16_new, fp16_null, fp16_set_dig(), fp16_sqr, fp16_test_cyc(), RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
fp16_exp_dig()
void fp16_exp_dig (fp16_t c, const fp16_t a, dig_t b)
Computes a power of a sextic extension field element by a small exponent. Faster formulas are used if the extension field element is cyclotomic.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 488 of file relic_fpx_exp.c.
References bn_bits(), bn_free, bn_new, bn_null, bn_rec_naf(), bn_set_dig(), ERR_CAUGHT, fp16_copy(), fp16_free, fp16_inv_cyc(), fp16_mul, fp16_new, fp16_null, fp16_set_dig(), fp16_sqr, fp16_sqr_cyc(), fp16_test_cyc(), RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_THROW, RLC_TRY, and util_bits_dig().
fp16_exp_cyc()
void fp16_exp_cyc (fp16_t c, const fp16_t a, const bn_t b)
Computes a power of a cyclotomic sextadecic extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 1057 of file relic_fpx_cyc.c.
References bn_bits(), bn_is_zero(), bn_rec_naf(), bn_sign(), ERR_CAUGHT, fp16_copy(), fp16_free, fp16_inv_cyc(), fp16_mul, fp16_new, fp16_null, fp16_set_dig(), fp16_sqr_cyc(), RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by fp16_exp(), fp16_exp_cyc_sim(), pp_exp_afg16(), pp_exp_fm16(), and pp_exp_kss().
fp16_exp_cyc_gls()
void fp16_exp_cyc_gls (fp16_t c, const fp16_t a, const bn_t b)
Computes a power of a cyclotomic sextadecic extension field element in the prime-order subgroup.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
fp16_exp_cyc_sim()
void fp16_exp_cyc_sim (fp16_t e, const fp16_t a, const bn_t b, const fp16_t c, const bn_t d)
Computes a power of two cyclotomic sextadecic extension field elements.
Parameters
[out] e - the result.
[in] a - the first element to exponentiate.
[in] b - the first exponent.
[in] c - the second element to exponentiate.
[in] d - the second exponent.
Definition at line 1124 of file relic_fpx_cyc.c.
References bn_is_zero(), bn_rec_naf(), bn_sign(), ERR_CAUGHT, fp16_copy(), fp16_exp_cyc(), fp16_free, fp16_inv_cyc(), fp16_mul, fp16_new, fp16_null, fp16_set_dig(), fp16_sqr, fp16_sqr_cyc(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
fp16_frb()
void fp16_frb (fp16_t c, const fp16_t a, int i)
Computes a power of the Frobenius endomorphism of an sextadecic extension field element. Computes c = a^p^i.
Parameters
[out] c - the result.
[in] a - an sextadecic extension field element.
[in] i - the power of the Frobenius map.
Definition at line 131 of file relic_fpx_frb.c.
References fp16_copy(), fp2_mul_frb(), fp4_mul_art(), fp8_frb(), fp8_mul_art(), and fp_prime_get_mod8().
Referenced by fp16_is_sqr(), pp_exp_afg16(), pp_exp_fm16(), pp_exp_kss(), pp_fin_k16_oatep(), pp_map_oatep_k16(), and pp_map_sim_oatep_k16().
fp16_is_sqr()
int fp16_is_sqr (const fp16_t a)
Tests if an sextadecic extension field element is a quadratic residue.
Parameters
[in] a - the prime field element to test.
Returns
1 if the argument is even, 0 otherwise.
Definition at line 568 of file relic_fpx_srt.c.
References ERR_CAUGHT, fp16_frb(), fp16_free, fp16_mul, fp16_new, fp16_null, fp_is_sqr(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp16_srt()
int fp16_srt (fp16_t c, const fp16_t a)
Extracts the square root of an sextadecic extension field element. Computes c = sqrt(a). The other square root is the negation of c. The output value shall not be used in case 0 is returned.
Parameters
[out] c - the result.
[in] a - the extension field element.
Returns
- 1 if there is a square root, 0 otherwise.
Definition at line 596 of file relic_fpx_srt.c.
References ERR_CAUGHT, ERR_NO_VALID, fp16_is_zero(), fp16_zero(), fp8_add(), fp8_copy(), fp8_dbl(), fp8_free, fp8_inv(), fp8_is_sqr(), fp8_is_zero(), fp8_mul, fp8_mul_art(), fp8_new, fp8_null, fp8_set_dig(), fp8_sqr, fp8_srt(), fp8_sub(), fp8_zero(), fp_copy_sec(), fp_hlv, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp18_copy()
void fp18_copy (fp18_t c, const fp18_t a)
Copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element to copy.
Definition at line 609 of file relic_fpx_util.c.
References fp9_copy().
Referenced by fp18_exp(), fp18_exp_cyc(), fp18_exp_cyc_sim(), fp18_exp_cyc_sps(), fp18_exp_dig(), fp18_frb(), fp18_pck(), fp18_upk(), fp54_copy(), fp54_mul_art(), fp54_mul_basic(), fp54_mul_dxs(), fp54_mul_lazyr(), and pp_exp_sg().
fp18_copy_sec()
void fp18_copy_sec (fp18_t c, const fp18_t a, dig_t bit)
Conditionally copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element to copy.
[in] bit - the condition bit to evaluate.
Definition at line 614 of file relic_fpx_util.c.
References fp9_copy_sec().
Referenced by fp54_copy_sec().
fp18_zero()
void fp18_zero (fp18_t a)
Assigns zero to an octdecic extension field element.
Parameters
[out] a - the octdecic extension field element to zero.
Definition at line 619 of file relic_fpx_util.c.
References fp9_zero().
Referenced by ep3_curve_set_twist(), fp54_set_dig(), fp54_zero(), pp_fin_k18_oatep(), pp_mil_k18(), and pp_mil_lit_k18().
fp18_is_zero()
int fp18_is_zero (const fp18_t a)
Tests if an octdecic extension field element is zero or not.
Parameters
[in] a - the octdecic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 624 of file relic_fpx_util.c.
References fp9_is_zero().
Referenced by fp54_cmp_dig(), and fp54_is_zero().
fp18_rand()
void fp18_rand (fp18_t a)
Assigns a random value to an octdecic extension field element.
Parameters
[out] a - the octdecic extension field element to assign.
Definition at line 628 of file relic_fpx_util.c.
References fp9_rand().
Referenced by fp54_rand().
fp18_print()
void fp18_print (const fp18_t a)
Prints an octdecic extension field element to standard output.
Parameters
[in] A - the octdecic extension field element to print.
Definition at line 633 of file relic_fpx_util.c.
References fp9_print().
Referenced by fp54_print().
fp18_size_bin()
int fp18_size_bin (fp18_t a, int pack)
Returns the number of bytes necessary to store a octdecic extension field element.
Parameters
[in] a - the extension field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 638 of file relic_fpx_util.c.
References fp18_test_cyc(), and RLC_FP_BYTES.
fp18_read_bin()
void fp18_read_bin (fp18_t a, const uint8_t * bin, size_t len)
Reads a octdecic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 650 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp18_back_cyc(), fp3_read_bin(), fp3_zero(), fp9_read_bin(), RLC_FP_BYTES, and RLC_THROW.
Referenced by fp54_read_bin().
fp18_write_bin()
void fp18_write_bin (uint8_t * bin, size_t len, const fp18_t a, int pack)
Writes a octdecic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
[in] pack - the flag to indicate compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 670 of file relic_fpx_util.c.
References ERR_CAUGHT, ERR_NO_BUFFER, fp18_free, fp18_new, fp18_null, fp18_pck(), fp3_write_bin(), fp9_write_bin(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.
Referenced by fp54_write_bin().
fp18_cmp()
int fp18_cmp (const fp18_t a, const fp18_t b)
Returns the result of a comparison between two octdecic extension field elements.
Parameters
[in] a - the first octdecic extension field element.
[in] b - the second octdecic extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 119 of file relic_fpx_cmp.c.
References fp9_cmp(), RLC_EQ, and RLC_NE.
Referenced by fp18_test_cyc(), and fp54_cmp().
fp18_cmp_dig()
int fp18_cmp_dig (const fp18_t a, const dig_t b)
Returns the result of a signed comparison between an octdecic extension field element and a digit.
Parameters
[in] a - the octdecic extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 124 of file relic_fpx_cmp.c.
References fp9_cmp_dig(), fp9_is_zero(), RLC_EQ, and RLC_NE.
Referenced by fp18_back_cyc(), fp18_back_cyc_sim(), and fp54_cmp_dig().
fp18_set_dig()
void fp18_set_dig (fp18_t a, const dig_t b)
Assigns an octdecic extension field element to a digit.
Parameters
[in] a - the octdecic extension field element.
[in] b - the digit.
Definition at line 701 of file relic_fpx_util.c.
References fp9_set_dig(), and fp9_zero().
Referenced by fp18_exp(), fp18_exp_cyc(), fp18_exp_cyc_sim(), fp18_exp_cyc_sps(), fp18_exp_dig(), fp54_set_dig(), pp_map_oatep_k18(), pp_map_sim_oatep_k18(), pp_map_sim_tatep_k18(), pp_map_sim_weilp_k18(), pp_map_tatep_k18(), and pp_map_weilp_k18().
fp18_add()
void fp18_add (fp18_t c, const fp18_t a, const fp18_t b)
Adds two octdecic extension field elements. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first octdecic extension field element.
[in] b - the second octdecic extension field element.
Definition at line 286 of file relic_fpx_add.c.
References fp9_add().
Referenced by fp54_add(), fp54_inv(), fp54_mul_basic(), fp54_mul_dxs(), fp54_mul_lazyr(), fp54_sqr_basic(), and fp54_sqr_lazyr().
fp18_sub()
void fp18_sub (fp18_t c, const fp18_t a, const fp18_t b)
Subtracts an octdecic extension field element from another. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the first octdecic extension field element.
[in] b - the second octdecic extension field element.
Definition at line 291 of file relic_fpx_add.c.
References fp9_sub().
Referenced by fp54_inv(), fp54_mul_basic(), fp54_mul_dxs(), fp54_mul_lazyr(), fp54_sqr_basic(), fp54_sqr_lazyr(), and fp54_sub().
fp18_neg()
void fp18_neg (fp18_t c, const fp18_t a)
Negates an octdecic extension field element.
Parameters
[out] c - the result.
[out] a - the octdecic extension field element to negate.
Definition at line 301 of file relic_fpx_add.c.
References fp9_neg().
Referenced by fp54_inv_cyc(), and fp54_neg().
fp18_dbl()
void fp18_dbl (fp18_t c, const fp18_t a)
Doubles an octdecic extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element to double.
Definition at line 296 of file relic_fpx_add.c.
References fp9_dbl().
Referenced by fp54_dbl(), fp54_sqr_basic(), and fp54_sqr_lazyr().
fp18_mul_unr()
void fp18_mul_unr (dv18_t c, const fp18_t a, const fp18_t b)
Multiples two octdecic extension field elements without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element.
[in] b - the octdecic extension field element.
Definition at line 203 of file relic_fp18_mul.c.
References dv9_free, dv9_new, dv9_null, ERR_CAUGHT, fp3_addc_low(), fp3_nord_low(), fp3_subc_low(), fp9_add(), fp9_free, fp9_mul_unr(), fp9_new, fp9_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp18_mul_lazyr().
fp18_mul_basic()
void fp18_mul_basic (fp18_t c, const fp18_t a, const fp18_t b)
Multiples two octdecic extension field elements using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element.
[in] b - the octdecic extension field element.
Definition at line 99 of file relic_fp18_mul.c.
References ERR_CAUGHT, fp9_add(), fp9_free, fp9_mul, fp9_mul_art(), fp9_new, fp9_null, fp9_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp18_mul_lazyr()
void fp18_mul_lazyr (fp18_t c, const fp18_t a, const fp18_t b)
Multiples two octdecic extension field elements using lazy reduction.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element.
[in] b - the octdecic extension field element.
Definition at line 256 of file relic_fp18_mul.c.
References dv18_free, dv18_new, dv18_null, ERR_CAUGHT, fp18_mul_unr(), fp3_rdcn_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp18_mul_art()
void fp18_mul_art (fp18_t c, const fp18_t a)
Multiplies an octdecic extension field element by the adjoined root.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element to multiply.
Definition at line 380 of file relic_fp18_mul.c.
References ERR_CAUGHT, fp9_copy(), fp9_free, fp9_mul_art(), fp9_new, fp9_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp54_inv(), fp54_mul_art(), fp54_mul_basic(), fp54_mul_dxs(), fp54_mul_lazyr(), fp54_sqr_basic(), and fp54_sqr_lazyr().
fp18_mul_dxs_basic()
void fp18_mul_dxs_basic (fp18_t c, const fp18_t a, const fp18_t b)
Multiples a dense octdecic extension field element by a sparse element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the dense octdecic extension field element.
[in] b - the sparse octdecic extension field element.
Definition at line 140 of file relic_fp18_mul.c.
References ERR_CAUGHT, fp3_add, fp3_copy(), fp3_mul, fp3_mul_nor(), fp9_add(), fp9_free, fp9_mul_art(), fp9_mul_dxs(), fp9_new, fp9_null, fp9_sub(), fp_add, fp_copy(), fp_mul, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp18_mul_dxs_lazyr()
void fp18_mul_dxs_lazyr (fp18_t c, const fp18_t a, const fp18_t b)
Multiples a dense octdecic extension field element by a sparse element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the dense octdecic extension field element.
[in] b - the sparse octdecic extension field element.
Definition at line 276 of file relic_fp18_mul.c.
References dv9_free, dv9_new, dv9_null, ep3_curve_is_twist(), ERR_CAUGHT, fp3_add, fp3_addc_low(), fp3_copy(), fp3_muln_low(), fp3_nord_low(), fp3_rdcn_low(), fp3_subc_low(), fp9_add(), fp9_free, fp9_mul_dxs_unr_lazyr(), fp9_new, fp9_null, fp_add, fp_copy(), fp_muln_low(), RLC_CATCH_ANY, RLC_EP_DTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp18_sqr_unr()
void fp18_sqr_unr (dv18_t c, const fp18_t a)
Computes the square of an octdecic extension field element without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element to square.
Definition at line 237 of file relic_fp18_sqr.c.
References dv9_free, dv9_new, dv9_null, dv_copy(), ERR_CAUGHT, fp3_addc_low(), fp3_nord_low(), fp3_subc_low(), fp9_add(), fp9_free, fp9_new, fp9_null, fp9_sqr_unr(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
Referenced by fp18_sqr_lazyr().
fp18_sqr_basic()
void fp18_sqr_basic (fp18_t c, const fp18_t a)
Computes the square of an octdecic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element to square.
Definition at line 42 of file relic_fp18_sqr.c.
References ERR_CAUGHT, fp9_add(), fp9_dbl(), fp9_free, fp9_mul, fp9_mul_art(), fp9_new, fp9_null, fp9_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp18_sqr_lazyr()
void fp18_sqr_lazyr (fp18_t c, const fp18_t a)
Computes the square of an octdecic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element to square.
Definition at line 290 of file relic_fp18_sqr.c.
References dv18_free, dv18_new, dv18_null, ERR_CAUGHT, fp18_sqr_unr(), fp3_rdcn_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp18_sqr_cyc_basic()
void fp18_sqr_cyc_basic (fp18_t c, const fp18_t a)
Computes the square of a cyclotomic dodecic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 69 of file relic_fp18_sqr.c.
References ERR_CAUGHT, fp3_add, fp3_dbl, fp3_free, fp3_mul_nor(), fp3_new, fp3_null, fp3_sqr, fp3_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp18_sqr_cyc_lazyr()
void fp18_sqr_cyc_lazyr (fp18_t c, const fp18_t a)
Computes the square of a cyclotomic dodecic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 309 of file relic_fp18_sqr.c.
References dv3_free, dv3_new, dv3_null, ERR_CAUGHT, fp3_addc_low(), fp3_addm_low(), fp3_dblm_low(), fp3_free, fp3_mul_nor(), fp3_new, fp3_nord_low(), fp3_null, fp3_rdcn_low(), fp3_sqrm_low(), fp3_sqrn_low(), fp3_subc_low(), fp3_subm_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp18_sqr_pck_basic()
void fp18_sqr_pck_basic (fp18_t c, const fp18_t a)
Computes the square of a compressed cyclotomic extension field element.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 163 of file relic_fp18_sqr.c.
References ERR_CAUGHT, fp3_add, fp3_dbl, fp3_free, fp3_mul_nor(), fp3_new, fp3_null, fp3_sqr, fp3_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp18_sqr_pck_lazyr()
void fp18_sqr_pck_lazyr (fp18_t c, const fp18_t a)
Computes the square of a compressed cyclotomic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 405 of file relic_fp18_sqr.c.
References dv3_free, dv3_new, dv3_null, ERR_CAUGHT, fp3_addc_low(), fp3_addm_low(), fp3_dblm_low(), fp3_free, fp3_mul_nor(), fp3_new, fp3_nord_low(), fp3_null, fp3_rdcn_low(), fp3_sqrm_low(), fp3_sqrn_low(), fp3_subc_low(), fp3_subm_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp18_test_cyc()
int fp18_test_cyc (const fp18_t a)
Tests if an octdecic extension field element belongs to the cyclotomic subgroup.
A cyclotomic element is one raised to the (p^9 - 1)(p^3 + 1)-th power.
Parameters
[in] a - the octdecic extension field element to test.
Returns
1 if the extension field element is in the subgroup, 0 otherwise.
Definition at line 1257 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp18_cmp(), fp18_frb(), fp18_free, fp18_mul, fp18_new, fp18_null, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp18_exp_dig(), fp18_pck(), fp18_size_bin(), fp18_upk(), and gt_is_valid().
fp18_conv_cyc()
void fp18_conv_cyc (fp18_t c, const fp18_t a)
Converts an octdecic field element to a cyclotomic element. Computes c = a^(p^9 - 1)*(p^3 + 1).
Parameters
[out] c - the result.
[in] a - the octdecic extension field element.
Definition at line 1226 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp18_frb(), fp18_free, fp18_inv(), fp18_inv_cyc(), fp18_mul, fp18_new, fp18_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_exp_fm(), pp_exp_kss(), and pp_exp_sg().
fp18_back_cyc()
void fp18_back_cyc (fp18_t c, const fp18_t a)
Decompresses a compressed cyclotomic extension field element.
Parameters
[out] c - the result.
[in] a - the octdecic field element to decompress.
Definition at line 1286 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp18_cmp_dig(), fp3_add, fp3_copy(), fp3_copy_sec(), fp3_dbl, fp3_free, fp3_inv(), fp3_is_zero(), fp3_mul, fp3_mul_nor(), fp3_new, fp3_null, fp3_set_dig(), fp3_sqr, fp3_sub, fp_add_dig(), RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp18_read_bin(), and fp18_upk().
fp18_back_cyc_sim()
void fp18_back_cyc_sim (fp18_t * c, const fp18_t * a, int n)
Decompresses multiple compressed cyclotomic extension field elements.
Parameters
[out] c - the result.
[in] a - the octdecic field elements to decompress.
[in] n - the number of field elements to decompress.
fp18_inv()
void fp18_inv (fp18_t c, const fp18_t a)
Inverts an octdecic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element to invert.
Definition at line 688 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp9_free, fp9_inv(), fp9_mul, fp9_mul_art(), fp9_neg(), fp9_new, fp9_null, fp9_sqr, fp9_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep3_curve_set_twist(), fp18_conv_cyc(), fp18_exp(), fp54_inv(), pp_map_sim_weilp_k18(), and pp_map_weilp_k18().
fp18_inv_cyc()
void fp18_inv_cyc (fp18_t c, const fp18_t a)
Computes the inverse of a cyclotomic octdecic extension field element. For unitary elements, this is equivalent to computing the conjugate. A unitary element is one previously raised to the (p^9 - 1)-th power.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element to invert.
Definition at line 716 of file relic_fpx_inv.c.
References fp9_copy(), and fp9_neg().
Referenced by fp18_conv_cyc(), fp18_exp_cyc(), fp18_exp_cyc_sim(), fp18_exp_cyc_sps(), fp18_exp_dig(), fp54_inv_cyc(), pp_exp_fm(), pp_exp_kss(), pp_exp_sg(), pp_map_oatep_k18(), pp_map_sim_oatep_k18(), pp_map_sim_weilp_k18(), and pp_map_weilp_k18().
fp18_frb()
void fp18_frb (fp18_t c, const fp18_t a, int i)
Computes the Frobenius endomorphism of an octdecic extension element. Computes c = a^(p^i).
Parameters
[out] c - the result.
[in] a - an octdecic extension field element.
[in] i - the power of the Frobenius map.
Definition at line 151 of file relic_fpx_frb.c.
References fp18_copy(), fp3_frb(), fp3_mul_frb(), and fp9_frb().
Referenced by fp18_conv_cyc(), fp18_test_cyc(), fp54_frb(), pp_exp_fm(), pp_exp_kss(), pp_exp_sg(), and pp_fin_k18_oatep().
fp18_exp()
void fp18_exp (fp18_t c, const fp18_t a, const bn_t b)
Computes a power of an octdecic extension field element. Faster formulas are used if the field element is cyclotomic.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 548 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), ERR_CAUGHT, fp18_copy(), fp18_free, fp18_inv(), fp18_mul, fp18_new, fp18_null, fp18_set_dig(), fp18_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
fp18_exp_dig()
void fp18_exp_dig (fp18_t c, const fp18_t a, dig_t b)
Computes a power of a octdecic extension field element by a small exponent. Faster formulas are used if the extension field element is cyclotomic.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 584 of file relic_fpx_exp.c.
References bn_bits(), bn_free, bn_new, bn_null, bn_rec_naf(), bn_set_dig(), ERR_CAUGHT, fp18_copy(), fp18_free, fp18_inv_cyc(), fp18_mul, fp18_new, fp18_null, fp18_set_dig(), fp18_sqr, fp18_sqr_cyc, fp18_test_cyc(), RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_THROW, RLC_TRY, and util_bits_dig().
fp18_exp_cyc()
void fp18_exp_cyc (fp18_t c, const fp18_t a, const bn_t b)
Computes a power of a cyclotomic octdecic extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 1444 of file relic_fpx_cyc.c.
References bn_bits(), bn_get_bit(), bn_ham(), bn_is_even(), bn_is_zero(), bn_rec_naf(), bn_sign(), ERR_CAUGHT, ERR_NO_MEMORY, fp18_back_cyc_sim(), fp18_copy(), fp18_free, fp18_inv_cyc(), fp18_mul, fp18_new, fp18_null, fp18_set_dig(), fp18_sqr_cyc, fp18_sqr_pck, RLC_ALLOCA, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FP_BITS, RLC_FREE, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by fp18_exp_cyc_sim(), and pp_exp_fm().
fp18_exp_cyc_gls()
void fp18_exp_cyc_gls (fp18_t c, const fp18_t a, const bn_t b)
Computes a power of a cyclotomic octdecic extension field element in the prime-order subgroup.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
fp18_exp_cyc_sim()
void fp18_exp_cyc_sim (fp18_t e, const fp18_t a, const bn_t b, const fp18_t c, const bn_t d)
Computes a power of two cyclotomic octdecic extension field elements.
Parameters
[out] e - the result.
[in] a - the first element to exponentiate.
[in] b - the first exponent.
[in] c - the second element to exponentiate.
[in] d - the second exponent.
Definition at line 1575 of file relic_fpx_cyc.c.
References bn_is_zero(), bn_rec_naf(), bn_sign(), ERR_CAUGHT, fp18_copy(), fp18_exp_cyc(), fp18_free, fp18_inv_cyc(), fp18_mul, fp18_new, fp18_null, fp18_set_dig(), fp18_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
fp18_exp_cyc_sps()
void fp18_exp_cyc_sps (fp18_t c, const fp18_t a, const int * b, int l, int s)
Computes a power of a cyclotomic octdecic extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent in sparse form.
[in] l - the length of the exponent in sparse form.
[in] s - the sign of the exponent.
Definition at line 1677 of file relic_fpx_cyc.c.
References ERR_CAUGHT, ERR_NO_MEMORY, fp18_back_cyc_sim(), fp18_copy(), fp18_free, fp18_inv_cyc(), fp18_mul, fp18_new, fp18_null, fp18_set_dig(), fp18_sqr_pck, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by gt_is_valid(), pp_exp_fm(), pp_exp_kss(), and pp_exp_sg().
fp18_pck()
void fp18_pck (fp18_t c, const fp18_t a)
Compresses a octdecic extension field element.
Parameters
[out] r - the result.
[in] p - the octdecic extension field element to compress.
Definition at line 158 of file relic_fpx_pck.c.
References fp18_copy(), fp18_test_cyc(), and fp2_zero().
Referenced by fp18_write_bin().
fp18_upk()
int fp18_upk (fp18_t c, const fp18_t a)
Decompresses a octdecic extension field element.
Parameters
[out] r - the result.
[in] p - the octdecic extension field element to decompress.
Returns
if the decompression was successful
Definition at line 166 of file relic_fpx_pck.c.
References fp18_back_cyc(), fp18_copy(), fp18_test_cyc(), and fp2_is_zero().
fp18_pck_max()
void fp18_pck_max (fp18_t c, const fp18_t a)
Compresses a octdecic extension field element at the maximum rate.
Parameters
[out] r - the result.
[in] p - the octdecic extension field element to compress.
fp18_upk_max()
int fp18_upk_max (fp18_t c, const fp18_t a)
Decompresses a octdecic extension field element at the maximum rate.
Parameters
[out] r - the result.
[in] p - the octdecic extension field element to decompress.
Returns
if the decompression was successful
fp24_copy()
void fp24_copy (fp24_t c, const fp24_t a)
Copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the 24-degree extension field element to copy.
Definition at line 706 of file relic_fpx_util.c.
References fp8_copy().
Referenced by fp24_exp(), fp24_exp_cyc(), fp24_exp_cyc_sim(), fp24_exp_cyc_sps(), fp24_exp_dig(), fp24_frb(), fp24_pck(), fp24_upk(), fp48_copy(), fp48_inv_cyc(), and fp48_mul_art().
fp24_copy_sec()
void fp24_copy_sec (fp24_t c, const fp24_t a, dig_t bit)
Conditionally copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the 24-degree extension field element to copy.
[in] bit - the condition bit to evaluate.
Definition at line 712 of file relic_fpx_util.c.
References fp8_copy_sec().
Referenced by fp48_copy_sec().
fp24_zero()
void fp24_zero (fp24_t a)
Assigns zero to a 24-degree extension field element.
Parameters
[out] a - the 24-degree extension field element to zero.
Definition at line 718 of file relic_fpx_util.c.
References fp8_zero().
Referenced by fp48_set_dig(), fp48_zero(), pp_dbl_k24_basic(), and pp_mil_k24().
fp24_is_zero()
int fp24_is_zero (const fp24_t a)
Tests if a 24-degree extension field element is zero or not.
Parameters
[in] a - the 24-degree extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 724 of file relic_fpx_util.c.
References fp8_is_zero().
Referenced by fp48_cmp_dig(), and fp48_is_zero().
fp24_rand()
void fp24_rand (fp24_t a)
Assigns a random value to a 24-degree extension field element.
Parameters
[out] A - the 24-degree extension field element to assign.
Definition at line 728 of file relic_fpx_util.c.
References fp8_rand().
Referenced by fp48_rand().
fp24_print()
void fp24_print (const fp24_t a)
Prints a 24-degree extension field element to standard output.
Parameters
[in] A - the 24-degree extension field element to print.
Definition at line 734 of file relic_fpx_util.c.
References fp8_print().
Referenced by fp48_print().
fp24_size_bin()
int fp24_size_bin (fp24_t a, int pack)
Returns the number of bytes necessary to store a 24-degree extension field element.
Parameters
[in] a - the extension field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 740 of file relic_fpx_util.c.
References fp24_test_cyc(), and RLC_FP_BYTES.
fp24_read_bin()
void fp24_read_bin (fp24_t a, const uint8_t * bin, size_t len)
Reads a 24-degree extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 752 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp24_back_cyc(), fp4_read_bin(), fp4_zero(), fp8_read_bin(), RLC_FP_BYTES, and RLC_THROW.
Referenced by fp48_read_bin().
fp24_write_bin()
void fp24_write_bin (uint8_t * bin, size_t len, const fp24_t a, int pack)
Writes a 24-degree extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
[in] pack - the flag to indicate compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 773 of file relic_fpx_util.c.
References ERR_CAUGHT, ERR_NO_BUFFER, fp24_free, fp24_new, fp24_null, fp24_pck(), fp4_write_bin(), fp8_write_bin(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.
Referenced by fp48_write_bin().
fp24_cmp()
int fp24_cmp (const fp24_t a, const fp24_t b)
Returns the result of a comparison between two 24-degree extension field elements.
Parameters
[in] a - the first 24-degree extension field element.
[in] b - the second 24-degree extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 129 of file relic_fpx_cmp.c.
References fp8_cmp(), RLC_EQ, and RLC_NE.
Referenced by fp24_test_cyc(), and fp48_cmp().
fp24_cmp_dig()
int fp24_cmp_dig (const fp24_t a, const dig_t b)
Returns the result of a signed comparison between a 24-degree extension field element and a digit.
Parameters
[in] a - the 24-degree extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 134 of file relic_fpx_cmp.c.
References fp8_cmp_dig(), fp8_is_zero(), RLC_EQ, and RLC_NE.
Referenced by fp24_back_cyc(), fp24_back_cyc_sim(), and fp48_cmp_dig().
fp24_set_dig()
void fp24_set_dig (fp24_t a, const dig_t b)
Assigns a 24-degree extension field element to a digit.
Parameters
[in] a - the 24-degree extension field element.
[in] b - the digit.
Definition at line 805 of file relic_fpx_util.c.
References fp8_set_dig(), and fp8_zero().
Referenced by fp24_exp(), fp24_exp_cyc(), fp24_exp_cyc_sim(), fp24_exp_cyc_sps(), fp24_exp_dig(), fp48_set_dig(), pp_map_k24(), and pp_map_sim_k24().
fp24_add()
void fp24_add (fp24_t c, const fp24_t a, const fp24_t b)
Adds two 24-degree extension field elements. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first 24-degree extension field element.
[in] b - the second 24-degree extension field element.
Definition at line 306 of file relic_fpx_add.c.
References fp8_add().
Referenced by fp48_add(), fp48_mul_basic(), fp48_mul_dxs(), fp48_mul_lazyr(), fp48_sqr_basic(), and fp48_sqr_lazyr().
fp24_sub()
void fp24_sub (fp24_t c, const fp24_t a, const fp24_t b)
Subtracts a 24-degree extension field element from another. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the first 24-degree extension field element.
[in] b - the second 24-degree extension field element.
Definition at line 312 of file relic_fpx_add.c.
References fp8_sub().
Referenced by fp48_inv(), fp48_mul_basic(), fp48_mul_dxs(), fp48_mul_lazyr(), fp48_sqr_basic(), fp48_sqr_lazyr(), and fp48_sub().
fp24_neg()
void fp24_neg (fp24_t c, const fp24_t a)
Negates a 24-degree extension field element.
Parameters
[out] c - the result.
[out] a - the 24-degree extension field element to negate.
Definition at line 318 of file relic_fpx_add.c.
References fp8_neg().
Referenced by fp48_inv(), fp48_inv_cyc(), and fp48_neg().
fp24_dbl()
void fp24_dbl (fp24_t c, const fp24_t a)
Doubles a 24-degree extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the octic extension field element to double.
Definition at line 324 of file relic_fpx_add.c.
References fp8_dbl().
Referenced by fp48_dbl(), fp48_sqr_basic(), and fp48_sqr_lazyr().
fp24_mul_unr()
void fp24_mul_unr (dv24_t c, const fp24_t a, const fp24_t b)
Multiples two 24-degree extension field elements without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the 24-degree extension field element.
[in] b - the 24-degree extension field element.
Definition at line 109 of file relic_fp24_mul.c.
References dv8_free, dv8_new, dv8_null, dv_copy(), ERR_CAUGHT, fp2_addc_low(), fp2_nord_low(), fp2_subc_low(), fp8_add(), fp8_free, fp8_mul_unr(), fp8_new, fp8_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
Referenced by fp24_mul_lazyr().
fp24_mul_basic()
void fp24_mul_basic (fp24_t c, const fp24_t a, const fp24_t b)
Multiples two 24-degree extension field elements using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the 24-degree extension field element.
[in] b - the 24-degree extension field element.
Definition at line 42 of file relic_fp24_mul.c.
References ERR_CAUGHT, fp8_add(), fp8_copy(), fp8_free, fp8_mul, fp8_mul_art(), fp8_new, fp8_null, fp8_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp24_mul_lazyr()
void fp24_mul_lazyr (fp24_t c, const fp24_t a, const fp24_t b)
Multiples two 24-degree extension field elements using lazy reduction.
Parameters
[out] c - the result.
[in] a - the 24-degree extension field element.
[in] b - the 24-degree extension field element.
Definition at line 197 of file relic_fp24_mul.c.
References dv24_free, dv24_new, dv24_null, ERR_CAUGHT, fp24_mul_unr(), fp2_rdcn_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp24_mul_art()
void fp24_mul_art (fp24_t c, const fp24_t a)
Multiplies a 24-degree extension field element by the adjoined root.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to multiply.
Definition at line 220 of file relic_fp24_mul.c.
References ERR_CAUGHT, fp8_copy(), fp8_free, fp8_mul_art(), fp8_new, fp8_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp48_inv(), fp48_mul_art(), fp48_mul_basic(), fp48_mul_dxs(), fp48_mul_lazyr(), fp48_sqr_basic(), and fp48_sqr_lazyr().
fp24_mul_dxs()
void fp24_mul_dxs (fp24_t c, const fp24_t a, const fp24_t b)
Multiples a dense 24-degree extension field element by a sparse element.
Parameters
[out] c - the result.
[in] a - a 24-degree extension field element.
[in] b - a 24-degree quartic extension field element.
Definition at line 240 of file relic_fp24_mul.c.
References ERR_CAUGHT, fp8_add(), fp8_copy(), fp8_free, fp8_is_zero(), fp8_mul, fp8_mul_art(), fp8_new, fp8_null, fp8_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp48_mul_dxs(), and pp_mil_k24().
fp24_sqr_unr()
void fp24_sqr_unr (dv24_t c, const fp24_t a)
Computes the square of a 24-degree extension field element without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the 24-degree extension field element to square.
Definition at line 277 of file relic_fp24_sqr.c.
References dv8_free, dv8_new, dv8_null, dv_copy(), ERR_CAUGHT, fp2_addc_low(), fp2_nord_low(), fp2_subc_low(), fp8_add(), fp8_free, fp8_mul_unr(), fp8_new, fp8_null, fp8_sqr_unr(), fp8_sub(), fp_hlvd_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
Referenced by fp24_sqr_lazyr().
fp24_sqr_basic()
void fp24_sqr_basic (fp24_t c, const fp24_t a)
Computes the square of a 24-degree extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the 24-degree extension field element to square.
Definition at line 42 of file relic_fp24_sqr.c.
References ERR_CAUGHT, fp8_add(), fp8_dbl(), fp8_free, fp8_mul, fp8_mul_art(), fp8_new, fp8_null, fp8_sqr, fp8_sub(), fp_hlv, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp24_sqr_lazyr()
void fp24_sqr_lazyr (fp24_t c, const fp24_t a)
Computes the square of a 24-degree extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the 24-degree extension field element to square.
Definition at line 378 of file relic_fp24_sqr.c.
References dv24_free, dv24_new, dv24_null, ERR_CAUGHT, fp24_sqr_unr(), fp2_rdcn_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp24_sqr_cyc_basic()
void fp24_sqr_cyc_basic (fp24_t c, const fp24_t a)
Computes the square of a cyclotomic 24-extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 114 of file relic_fp24_sqr.c.
References ERR_CAUGHT, fp4_add(), fp4_dbl(), fp4_free, fp4_mul_art(), fp4_new, fp4_null, fp4_sqr, fp4_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp24_sqr_cyc_lazyr()
void fp24_sqr_cyc_lazyr (fp24_t c, const fp24_t a)
Computes the square of a cyclotomic 24-extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 399 of file relic_fp24_sqr.c.
References dv4_free, dv4_new, dv4_null, ERR_CAUGHT, fp2_addc_low(), fp2_nord_low(), fp2_rdcn_low(), fp2_subc_low(), fp4_add(), fp4_dbl(), fp4_free, fp4_mul_art(), fp4_new, fp4_null, fp4_sqr, fp4_sqr_unr(), fp4_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp24_sqr_pck_basic()
void fp24_sqr_pck_basic (fp24_t c, const fp24_t a)
Computes the square of a compressed cyclotomic extension field element.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 203 of file relic_fp24_sqr.c.
References ERR_CAUGHT, fp4_add(), fp4_dbl(), fp4_free, fp4_mul_art(), fp4_new, fp4_null, fp4_sqr, fp4_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp24_sqr_pck_lazyr()
void fp24_sqr_pck_lazyr (fp24_t c, const fp24_t a)
Computes the square of a compressed cyclotomic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 506 of file relic_fp24_sqr.c.
References dv4_free, dv4_new, dv4_null, ERR_CAUGHT, fp2_addc_low(), fp2_nord_low(), fp2_rdcn_low(), fp2_subc_low(), fp4_add(), fp4_dbl(), fp4_free, fp4_mul_art(), fp4_new, fp4_null, fp4_sqr, fp4_sqr_unr(), fp4_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp24_test_cyc()
int fp24_test_cyc (const fp24_t a)
Tests if a 24-extension field element belongs to the cyclotomic subgroup.
A cyclotomic element is one raised to the (p^8 - 1)(p^4 + 1)-th power.
Parameters
[in] a - the 24-extension field element to test.
Returns
1 if the extension field element is in the subgroup, 0 otherwise.
Definition at line 1788 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp24_cmp(), fp24_frb(), fp24_free, fp24_mul, fp24_new, fp24_null, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp24_exp_dig(), fp24_pck(), fp24_size_bin(), fp24_upk(), and gt_is_valid().
fp24_conv_cyc()
void fp24_conv_cyc (fp24_t c, const fp24_t a)
Converts a 24-extension field element to a cyclotomic element. Computes c = a^(p^8 - 1)*(p^4 + 1).
Parameters
[out] c - the result.
[in] a - a 24-extension field element.
Definition at line 1757 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp24_frb(), fp24_free, fp24_inv(), fp24_inv_cyc(), fp24_mul, fp24_new, fp24_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_exp_k24().
fp24_back_cyc()
void fp24_back_cyc (fp24_t c, const fp24_t a)
Decompresses a compressed cyclotomic extension field element.
Parameters
[out] c - the result.
[in] a - the 24-extension field element to decompress.
Definition at line 1817 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp24_cmp_dig(), fp4_add(), fp4_copy(), fp4_copy_sec(), fp4_dbl(), fp4_free, fp4_inv(), fp4_is_zero(), fp4_mul, fp4_mul_art(), fp4_new, fp4_null, fp4_set_dig(), fp4_sqr, fp4_sub(), fp_add_dig(), RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp24_read_bin(), and fp24_upk().
fp24_back_cyc_sim()
void fp24_back_cyc_sim (fp24_t * c, const fp24_t * a, int n)
Decompresses multiple compressed cyclotomic extension field elements.
Parameters
[out] c - the result.
[in] a - the 24 field elements to decompress.
[in] n - the number of field elements to decompress.
fp24_inv()
void fp24_inv (fp24_t c, const fp24_t a)
Inverts a 24-degree extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the 24-degree extension field element to invert.
Definition at line 721 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp8_add(), fp8_free, fp8_inv(), fp8_mul, fp8_mul_art(), fp8_new, fp8_null, fp8_sqr, fp8_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp24_conv_cyc(), fp24_exp(), and fp48_inv().
fp24_inv_cyc()
void fp24_inv_cyc (fp24_t c, const fp24_t a)
Computes the inverse of a cyclotomic octdecic extension field element. For unitary elements, this is equivalent to computing the conjugate. A unitary element is one previously raised to the (p^12 - 1)-th power.
Parameters
[out] c - the result.
[in] a - the 24-degree extension field element to invert.
Definition at line 780 of file relic_fpx_inv.c.
References fp8_inv_cyc(), and fp8_neg().
Referenced by fp24_conv_cyc(), fp24_exp_cyc(), fp24_exp_cyc_sim(), fp24_exp_cyc_sps(), fp24_exp_dig(), pp_exp_k24(), pp_map_k24(), and pp_map_sim_k24().
fp24_frb()
void fp24_frb (fp24_t c, const fp24_t a, int i)
Computes the Frobenius endomorphism of a 24-degree extension element. Computes c = a^p.
Parameters
[out] c - the result.
[in] a - a 24-degree extension field element.
[in] i - the power of the Frobenius map.
Definition at line 165 of file relic_fpx_frb.c.
References fp24_copy(), fp2_mul_frb(), fp4_mul_art(), fp8_frb(), and fp_prime_get_mod8().
Referenced by fp24_conv_cyc(), fp24_test_cyc(), fp48_frb(), and pp_exp_k24().
fp24_exp()
void fp24_exp (fp24_t c, const fp24_t a, const bn_t b)
Computes a power of a 24-degree extension field element. Faster formulas are used if the extension field element is cyclotomic.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 644 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), ERR_CAUGHT, fp24_copy(), fp24_free, fp24_inv(), fp24_mul, fp24_new, fp24_null, fp24_set_dig(), fp24_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
fp24_exp_dig()
void fp24_exp_dig (fp24_t c, const fp24_t a, dig_t b)
Computes a power of a 24-extension field element by a small exponent. Faster formulas are used if the extension field element is cyclotomic.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 680 of file relic_fpx_exp.c.
References bn_bits(), bn_free, bn_new, bn_null, bn_rec_naf(), bn_set_dig(), ERR_CAUGHT, fp24_copy(), fp24_free, fp24_inv_cyc(), fp24_mul, fp24_new, fp24_null, fp24_set_dig(), fp24_sqr, fp24_sqr_cyc, fp24_test_cyc(), RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_THROW, RLC_TRY, and util_bits_dig().
fp24_exp_cyc()
void fp24_exp_cyc (fp24_t c, const fp24_t a, const bn_t b)
Computes a power of a cyclotomic 24-extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 1974 of file relic_fpx_cyc.c.
References bn_bits(), bn_get_bit(), bn_ham(), bn_is_even(), bn_is_zero(), bn_rec_naf(), bn_sign(), ERR_CAUGHT, ERR_NO_MEMORY, fp24_back_cyc_sim(), fp24_copy(), fp24_free, fp24_inv_cyc(), fp24_mul, fp24_new, fp24_null, fp24_set_dig(), fp24_sqr_cyc, fp24_sqr_pck, RLC_ALLOCA, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FP_BITS, RLC_FREE, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by fp24_exp_cyc_sim().
fp24_exp_cyc_gls()
void fp24_exp_cyc_gls (fp24_t c, const fp24_t a, const bn_t b)
Computes a power of a cyclotomic 24-extension field element in the prime-order subgroup.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
fp24_exp_cyc_sim()
void fp24_exp_cyc_sim (fp24_t e, const fp24_t a, const bn_t b, const fp24_t c, const bn_t d)
Computes a power of two cyclotomic dodecic extension field elements.
Parameters
[out] e - the result.
[in] a - the first element to exponentiate.
[in] b - the first exponent.
[in] c - the second element to exponentiate.
[in] d - the second exponent.
Definition at line 2105 of file relic_fpx_cyc.c.
References bn_is_zero(), bn_rec_naf(), bn_sign(), ERR_CAUGHT, fp24_copy(), fp24_exp_cyc(), fp24_free, fp24_inv_cyc(), fp24_mul, fp24_new, fp24_null, fp24_set_dig(), fp24_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
fp24_exp_cyc_sps()
void fp24_exp_cyc_sps (fp24_t c, const fp24_t a, const int * b, size_t l, int s)
Computes a power of a cyclotomic 24-extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent in sparse form.
[in] l - the length of the exponent in sparse form.
[in] s - the sign of the exponent.
Definition at line 2207 of file relic_fpx_cyc.c.
References ERR_CAUGHT, ERR_NO_MEMORY, fp24_back_cyc_sim(), fp24_copy(), fp24_free, fp24_inv_cyc(), fp24_mul, fp24_new, fp24_null, fp24_set_dig(), fp24_sqr_pck, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by gt_is_valid(), and pp_exp_k24().
fp24_pck()
void fp24_pck (fp24_t c, const fp24_t a)
Compresses a 24-extension field element.
Parameters
[out] c - the result.
[in] a - the 24-extension field element to compress.
Definition at line 180 of file relic_fpx_pck.c.
References fp24_copy(), fp24_test_cyc(), and fp4_zero().
Referenced by fp24_write_bin().
fp24_upk()
int fp24_upk (fp24_t c, const fp24_t a)
Decompresses a 24-extension field element.
Parameters
[out] c - the result.
[in] a - the 24-extension field element to decompress.
Returns
if the decompression was successful
Definition at line 188 of file relic_fpx_pck.c.
References fp24_back_cyc(), fp24_copy(), fp24_test_cyc(), and fp4_is_zero().
fp48_copy()
void fp48_copy (fp48_t c, const fp48_t a)
Copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the 48-extension field element to copy.
Definition at line 811 of file relic_fpx_util.c.
References fp24_copy().
Referenced by fp48_exp(), fp48_exp_cyc(), fp48_exp_cyc_sim(), fp48_exp_cyc_sps(), fp48_exp_dig(), fp48_frb(), fp48_pck(), and fp48_upk().
fp48_copy_sec()
void fp48_copy_sec (fp48_t c, const fp48_t a, dig_t bit)
Conditionally copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the 48-degree extension field element to copy.
[in] bit - the condition bit to evaluate.
Definition at line 816 of file relic_fpx_util.c.
References fp24_copy_sec().
fp48_zero()
void fp48_zero (fp48_t a)
Assigns zero to a 48-extension field element.
Parameters
[out] a - the 48-extension field element to zero.
Definition at line 821 of file relic_fpx_util.c.
References fp24_zero().
Referenced by pp_add_k48_basic(), pp_dbl_k48_basic(), and pp_mil_k48().
fp48_is_zero()
int fp48_is_zero (const fp48_t a)
Tests if a 48-extension field element is zero or not.
Parameters
[in] a - the 48-extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 826 of file relic_fpx_util.c.
References fp24_is_zero().
fp48_rand()
void fp48_rand (fp48_t a)
Assigns a random value to a 48-extension field element.
Parameters
[out] a - the 48-extension field element to assign.
Definition at line 830 of file relic_fpx_util.c.
References fp24_rand().
fp48_print()
void fp48_print (const fp48_t a)
Prints a 48-extension field element to standard output.
Parameters
[in] a - the 48-extension field element to print.
Definition at line 835 of file relic_fpx_util.c.
References fp24_print().
fp48_size_bin()
int fp48_size_bin (fp48_t a, int pack)
Returns the number of bytes necessary to store a 48-extension field element.
Parameters
[in] a - the extension field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 840 of file relic_fpx_util.c.
References fp48_test_cyc(), and RLC_FP_BYTES.
fp48_read_bin()
void fp48_read_bin (fp48_t a, const uint8_t * bin, size_t len)
Reads a 48-extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 852 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp24_read_bin(), fp48_back_cyc(), fp8_read_bin(), fp8_zero(), RLC_FP_BYTES, and RLC_THROW.
fp48_write_bin()
void fp48_write_bin (uint8_t * bin, size_t len, const fp48_t a, int pack)
Writes a 48-extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
[in] pack - the flag to indicate compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 872 of file relic_fpx_util.c.
References ERR_CAUGHT, ERR_NO_BUFFER, fp24_write_bin(), fp48_free, fp48_new, fp48_null, fp48_pck(), fp8_write_bin(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.
fp48_cmp()
int fp48_cmp (const fp48_t a, const fp48_t b)
Returns the result of a comparison between two 48-extension field elements.
Parameters
[in] a - the first 48-extension field element.
[in] b - the second 48-extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 139 of file relic_fpx_cmp.c.
References fp24_cmp(), RLC_EQ, and RLC_NE.
Referenced by fp48_test_cyc().
fp48_cmp_dig()
int fp48_cmp_dig (const fp48_t a, const dig_t b)
Returns the result of a signed comparison between a 48-extension field element and a digit.
Parameters
[in] a - the 48-extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 144 of file relic_fpx_cmp.c.
References fp24_cmp_dig(), fp24_is_zero(), RLC_EQ, and RLC_NE.
Referenced by fp48_back_cyc(), and fp48_back_cyc_sim().
fp48_set_dig()
void fp48_set_dig (fp48_t a, const dig_t b)
Assigns a 48-extension field element to a digit.
Parameters
[in] a - the 48-extension field element.
[in] b - the digit.
Definition at line 903 of file relic_fpx_util.c.
References fp24_set_dig(), and fp24_zero().
Referenced by fp48_exp(), fp48_exp_cyc(), fp48_exp_cyc_sim(), fp48_exp_cyc_sps(), fp48_exp_dig(), pp_map_k48(), and pp_map_sim_k48().
fp48_add()
void fp48_add (fp48_t c, const fp48_t a, const fp48_t b)
Adds two 48-extension field elements. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first 48-extension field element.
[in] b - the second 48-extension field element.
Definition at line 330 of file relic_fpx_add.c.
References fp24_add().
fp48_sub()
void fp48_sub (fp48_t c, const fp48_t a, const fp48_t b)
Subtracts a 48-extension field element from another. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the first 48-extension field element.
[in] b - the second 48-extension field element.
Definition at line 335 of file relic_fpx_add.c.
References fp24_sub().
fp48_neg()
void fp48_neg (fp48_t c, const fp48_t a)
Negates a 48-extension field element.
Parameters
[out] c - the result.
[out] a - the 48-extension field element to negate.
Definition at line 340 of file relic_fpx_add.c.
References fp24_neg().
fp48_dbl()
void fp48_dbl (fp48_t c, const fp48_t a)
Doubles a 48-extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the 48-extension field element to double.
Definition at line 345 of file relic_fpx_add.c.
References fp24_dbl().
fp48_mul_basic()
void fp48_mul_basic (fp48_t c, const fp48_t a, const fp48_t b)
Multiples two 48-extension field elements using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the 48-extension field element.
[in] b - the 48-extension field element.
Definition at line 42 of file relic_fp48_mul.c.
References ERR_CAUGHT, fp24_add(), fp24_free, fp24_mul, fp24_mul_art(), fp24_new, fp24_null, fp24_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp48_mul_lazyr()
void fp48_mul_lazyr (fp48_t c, const fp48_t a, const fp48_t b)
Multiples two 48-extension field elements using lazy reduction.
Parameters
[out] c - the result.
[in] a - the 48-extension field element.
[in] b - the 48-extension field element.
Definition at line 87 of file relic_fp48_mul.c.
References ERR_CAUGHT, fp24_add(), fp24_free, fp24_mul, fp24_mul_art(), fp24_new, fp24_null, fp24_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp48_mul_art()
void fp48_mul_art (fp48_t c, const fp48_t a)
Multiplies a 48-extension field element by the adjoined root.
Parameters
[out] c - the result.
[in] a - the 48-extension field element to multiply.
Definition at line 194 of file relic_fp48_mul.c.
References ERR_CAUGHT, fp24_copy(), fp24_free, fp24_mul_art(), fp24_new, fp24_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp48_mul_dxs()
void fp48_mul_dxs (fp48_t c, const fp48_t a, const fp48_t b)
Multiples a dense 48-extension field element by a sparse element using basic arithmetic. Computes C = A * B.
Parameters
[out] c - the result.
[in] a - the dense 48-extension field element.
[in] b - the sparse 48-extension field element.
Definition at line 131 of file relic_fp48_mul.c.
References ERR_CAUGHT, fp24_add(), fp24_free, fp24_mul_art(), fp24_mul_dxs(), fp24_new, fp24_null, fp24_sub(), fp8_add(), fp8_copy(), fp8_mul, fp_add, fp_mul, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_mil_k48().
fp48_sqr_basic()
void fp48_sqr_basic (fp48_t c, const fp48_t a)
Computes the square of a 48-extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the 48-extension field element to square.
Definition at line 42 of file relic_fp48_sqr.c.
References ERR_CAUGHT, fp24_add(), fp24_dbl(), fp24_free, fp24_mul, fp24_mul_art(), fp24_new, fp24_null, fp24_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp48_sqr_lazyr()
void fp48_sqr_lazyr (fp48_t c, const fp48_t a)
Computes the square of a 48-extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the 48-extension field element to square.
Definition at line 232 of file relic_fp48_sqr.c.
References ERR_CAUGHT, fp24_add(), fp24_dbl(), fp24_free, fp24_mul, fp24_mul_art(), fp24_new, fp24_null, fp24_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp48_sqr_cyc_basic()
void fp48_sqr_cyc_basic (fp48_t c, const fp48_t a)
Computes the square of a cyclotomic 48-extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 69 of file relic_fp48_sqr.c.
References ERR_CAUGHT, fp8_add(), fp8_dbl(), fp8_free, fp8_mul_art(), fp8_new, fp8_null, fp8_sqr, fp8_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp48_sqr_cyc_lazyr()
void fp48_sqr_cyc_lazyr (fp48_t c, const fp48_t a)
Computes the square of a cyclotomic 48-extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 260 of file relic_fp48_sqr.c.
References ERR_CAUGHT, fp8_add(), fp8_dbl(), fp8_free, fp8_mul_art(), fp8_new, fp8_null, fp8_sqr, fp8_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp48_sqr_pck_basic()
void fp48_sqr_pck_basic (fp48_t c, const fp48_t a)
Computes the square of a compressed cyclotomic extension field element.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 158 of file relic_fp48_sqr.c.
References ERR_CAUGHT, fp8_add(), fp8_dbl(), fp8_free, fp8_mul_art(), fp8_new, fp8_null, fp8_sqr, fp8_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp48_sqr_pck_lazyr()
void fp48_sqr_pck_lazyr (fp48_t c, const fp48_t a)
Computes the square of a compressed cyclotomic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 349 of file relic_fp48_sqr.c.
References dv8_free, dv8_new, dv8_null, ERR_CAUGHT, fp2_addc_low(), fp2_nord_low(), fp2_rdcn_low(), fp2_subc_low(), fp8_add(), fp8_dbl(), fp8_free, fp8_mul_art(), fp8_new, fp8_null, fp8_sqr, fp8_sqr_unr(), fp8_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp48_test_cyc()
int fp48_test_cyc (const fp48_t a)
Tests if a 48-extension field element belongs to the cyclotomic subgroup.
A cyclotomic element is one raised to the (p^16 - 1)(p^8 + 1)-th power.
Parameters
[in] a - the 48-extension field element to test.
Returns
1 if the extension field element is in the subgroup, 0 otherwise.
Definition at line 2318 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp48_cmp(), fp48_frb(), fp48_free, fp48_mul, fp48_new, fp48_null, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp48_exp(), fp48_exp_dig(), fp48_pck(), fp48_size_bin(), fp48_upk(), and gt_is_valid().
fp48_conv_cyc()
void fp48_conv_cyc (fp48_t c, const fp48_t a)
Converts a 48-extension field element to a cyclotomic element. Computes c = a^(p^16 - 1)*(p^8 + 1).
Parameters
[out] c - the result.
[in] a - a 48-extension field element.
Definition at line 2287 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp48_frb(), fp48_free, fp48_inv(), fp48_inv_cyc(), fp48_mul, fp48_new, fp48_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_exp_k48().
fp48_back_cyc()
void fp48_back_cyc (fp48_t c, const fp48_t a)
Decompresses a compressed cyclotomic extension field element.
Parameters
[out] c - the result.
[in] a - the 48-extension field element to decompress.
Definition at line 2347 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp48_cmp_dig(), fp8_add(), fp8_copy(), fp8_copy_sec(), fp8_dbl(), fp8_free, fp8_inv(), fp8_is_zero(), fp8_mul, fp8_mul_art(), fp8_new, fp8_null, fp8_set_dig(), fp8_sqr, fp8_sub(), fp_add_dig(), RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp48_read_bin(), and fp48_upk().
fp48_back_cyc_sim()
void fp48_back_cyc_sim (fp48_t * c, const fp48_t * a, int n)
Decompresses multiple compressed cyclotomic extension field elements.
Parameters
[out] c - the result.
[in] a - the 48 field elements to decompress.
[in] n - the number of field elements to decompress.
fp48_inv()
void fp48_inv (fp48_t c, const fp48_t a)
Inverts a 48-extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the 48-extension field element to invert.
Definition at line 787 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp24_free, fp24_inv(), fp24_mul, fp24_mul_art(), fp24_neg(), fp24_new, fp24_null, fp24_sqr, fp24_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp48_conv_cyc(), and fp48_exp().
fp48_inv_cyc()
void fp48_inv_cyc (fp48_t c, const fp48_t a)
Computes the inverse of a cyclotomic 48-extension field element.
For unitary elements, this is equivalent to computing the conjugate. A unitary element is one previously raised to the (p^24 - 1)-th power.
Parameters
[out] c - the result.
[in] a - the 48-extension field element to invert.
Definition at line 815 of file relic_fpx_inv.c.
References fp24_copy(), and fp24_neg().
Referenced by fp48_conv_cyc(), fp48_exp_cyc(), fp48_exp_cyc_sim(), fp48_exp_cyc_sps(), fp48_exp_dig(), pp_exp_k48(), pp_map_k48(), and pp_map_sim_k48().
fp48_frb()
void fp48_frb (fp48_t c, const fp48_t a, int i)
Computes the Frobenius endomorphism of a 48-extension element. Computes c = a^p.
Parameters
[out] c - the result.
[in] a - a 48-extension field element.
[in] i - the power of the Frobenius map.
Definition at line 184 of file relic_fpx_frb.c.
References fp24_frb(), fp2_mul_frb(), fp48_copy(), fp4_mul_art(), fp8_mul_art(), and fp_prime_get_mod8().
Referenced by fp48_conv_cyc(), fp48_test_cyc(), and pp_exp_k48().
fp48_exp()
void fp48_exp (fp48_t c, const fp48_t a, const bn_t b)
Computes a power of a 48-extension field element. Faster formulas are used if the extension field element is cyclotomic.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 740 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), ERR_CAUGHT, fp48_copy(), fp48_exp_cyc(), fp48_free, fp48_inv(), fp48_mul, fp48_new, fp48_null, fp48_set_dig(), fp48_sqr, fp48_test_cyc(), RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
fp48_exp_dig()
void fp48_exp_dig (fp48_t c, const fp48_t a, dig_t b)
Computes a power of a 48-extension field element by a small exponent. Faster formulas are used if the extension field element is cyclotomic.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 780 of file relic_fpx_exp.c.
References bn_bits(), bn_free, bn_new, bn_null, bn_rec_naf(), bn_set_dig(), ERR_CAUGHT, fp48_copy(), fp48_free, fp48_inv_cyc(), fp48_mul, fp48_new, fp48_null, fp48_set_dig(), fp48_sqr, fp48_sqr_cyc, fp48_test_cyc(), RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_THROW, RLC_TRY, and util_bits_dig().
fp48_exp_cyc()
void fp48_exp_cyc (fp48_t c, const fp48_t a, const bn_t b)
Computes a power of a cyclotomic 48-extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 2505 of file relic_fpx_cyc.c.
References bn_bits(), bn_get_bit(), bn_ham(), bn_is_even(), bn_is_zero(), bn_rec_naf(), bn_sign(), ERR_CAUGHT, ERR_NO_MEMORY, fp48_back_cyc_sim(), fp48_copy(), fp48_free, fp48_inv_cyc(), fp48_mul, fp48_new, fp48_null, fp48_set_dig(), fp48_sqr_cyc, fp48_sqr_pck, RLC_ALLOCA, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FP_BITS, RLC_FREE, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by fp48_exp(), and fp48_exp_cyc_sim().
fp48_exp_cyc_gls()
void fp48_exp_cyc_gls (fp48_t c, const fp48_t a, const bn_t b)
Computes a power of a cyclotomic 48-extension field element in the prime-order subgroup.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
fp48_exp_cyc_sps()
void fp48_exp_cyc_sps (fp48_t c, const fp48_t a, const int * b, size_t l, int s)
Computes a power of a cyclotomic 48-extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent in sparse form.
[in] l - the length of the exponent in sparse form.
[in] s - the sign of the exponent.
Definition at line 2738 of file relic_fpx_cyc.c.
References ERR_CAUGHT, ERR_NO_MEMORY, fp48_back_cyc_sim(), fp48_copy(), fp48_free, fp48_inv_cyc(), fp48_mul, fp48_new, fp48_null, fp48_set_dig(), fp48_sqr_pck, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by gt_is_valid(), and pp_exp_k48().
fp48_exp_cyc_sim()
void fp48_exp_cyc_sim (fp48_t e, const fp48_t a, const bn_t b, const fp48_t c, const bn_t d)
Computes a power of two cyclotomic 48-extension field elements.
Parameters
[out] e - the result.
[in] a - the first element to exponentiate.
[in] b - the first exponent.
[in] c - the second element to exponentiate.
[in] d - the second exponent.
Definition at line 2636 of file relic_fpx_cyc.c.
References bn_is_zero(), bn_rec_naf(), bn_sign(), ERR_CAUGHT, fp48_copy(), fp48_exp_cyc(), fp48_free, fp48_inv_cyc(), fp48_mul, fp48_new, fp48_null, fp48_set_dig(), fp48_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
fp48_pck()
void fp48_pck (fp48_t c, const fp48_t a)
Compresses a 48-extension field element.
Parameters
[out] c - the result.
[in] a - the 48-extension field element to compress.
Definition at line 202 of file relic_fpx_pck.c.
References fp48_copy(), fp48_test_cyc(), and fp8_zero().
Referenced by fp48_write_bin().
fp48_upk()
int fp48_upk (fp48_t c, const fp48_t a)
Decompresses a 48-extension field element.
Parameters
[out] c - the result.
[in] a - the 48-extension field element to decompress.
Returns
if the decompression was successful
Definition at line 210 of file relic_fpx_pck.c.
References fp48_back_cyc(), fp48_copy(), fp48_test_cyc(), and fp8_is_zero().
fp54_copy()
void fp54_copy (fp54_t c, const fp54_t a)
Copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the 54-extension field element to copy.
Definition at line 908 of file relic_fpx_util.c.
References fp18_copy().
Referenced by fp54_exp(), fp54_exp_cyc(), fp54_exp_cyc_sps(), fp54_exp_dig(), fp54_frb(), fp54_pck(), fp54_upk(), and pp_exp_k54().
fp54_copy_sec()
void fp54_copy_sec (fp54_t c, const fp54_t a, dig_t bit)
Conditionally copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the 54-degree extension field element to copy.
[in] bit - the condition bit to evaluate.
Definition at line 914 of file relic_fpx_util.c.
References fp18_copy_sec().
fp54_zero()
void fp54_zero (fp54_t a)
Assigns zero to a 54-extension field element.
Parameters
[out] a - the 54-extension field element to zero.
Definition at line 920 of file relic_fpx_util.c.
References fp18_zero().
Referenced by pp_add_k54_basic(), pp_dbl_k54_basic(), and pp_mil_k54().
fp54_is_zero()
int fp54_is_zero (const fp54_t a)
Tests if a 54-extension field element is zero or not.
Parameters
[in] a - the 54-extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 926 of file relic_fpx_util.c.
References fp18_is_zero().
fp54_rand()
void fp54_rand (fp54_t a)
Assigns a random value to a 54-extension field element.
Parameters
[out] a - the 54-extension field element to assign.
Definition at line 930 of file relic_fpx_util.c.
References fp18_rand().
fp54_print()
void fp54_print (const fp54_t a)
Prints a 54-extension field element to standard output.
Parameters
[in] a - the 54-extension field element to print.
Definition at line 936 of file relic_fpx_util.c.
References fp18_print().
fp54_size_bin()
int fp54_size_bin (fp54_t a, int pack)
Returns the number of bytes necessary to store a 54-extension field element.
Parameters
[in] a - the extension field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 942 of file relic_fpx_util.c.
References fp54_test_cyc(), and RLC_FP_BYTES.
fp54_read_bin()
void fp54_read_bin (fp54_t a, const uint8_t * bin, size_t len)
Reads a 54-extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 954 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp18_read_bin(), fp54_back_cyc(), fp9_read_bin(), fp9_zero(), RLC_FP_BYTES, and RLC_THROW.
fp54_write_bin()
void fp54_write_bin (uint8_t * bin, size_t len, const fp54_t a, int pack)
Writes a 54-extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
[in] pack - the flag to indicate compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 975 of file relic_fpx_util.c.
References ERR_CAUGHT, ERR_NO_BUFFER, fp18_write_bin(), fp54_free, fp54_new, fp54_null, fp54_pck(), fp9_write_bin(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.
fp54_cmp()
int fp54_cmp (const fp54_t a, const fp54_t b)
Returns the result of a comparison between two 54-extension field elements.
Parameters
[in] a - the first 54-extension field element.
[in] b - the second 54-extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 149 of file relic_fpx_cmp.c.
References fp18_cmp(), RLC_EQ, and RLC_NE.
Referenced by fp54_test_cyc().
fp54_cmp_dig()
int fp54_cmp_dig (const fp54_t a, const dig_t b)
Returns the result of a signed comparison between a 54-extension field element and a digit.
Parameters
[in] a - the 54-extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 154 of file relic_fpx_cmp.c.
References fp18_cmp_dig(), fp18_is_zero(), RLC_EQ, and RLC_NE.
Referenced by fp54_back_cyc(), and fp54_back_cyc_sim().
fp54_set_dig()
void fp54_set_dig (fp54_t a, const dig_t b)
Assigns a 54-extension field element to a digit.
Parameters
[in] a - the 54-extension field element.
[in] b - the digit.
Definition at line 1007 of file relic_fpx_util.c.
References fp18_set_dig(), and fp18_zero().
Referenced by fp54_exp(), fp54_exp_cyc(), fp54_exp_cyc_sps(), fp54_exp_dig(), and pp_map_k54().
fp54_add()
void fp54_add (fp54_t c, const fp54_t a, const fp54_t b)
Adds two 54-extension field elements. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first 54-extension field element.
[in] b - the second 54-extension field element.
Definition at line 350 of file relic_fpx_add.c.
References fp18_add().
fp54_sub()
void fp54_sub (fp54_t c, const fp54_t a, const fp54_t b)
Subtracts a 54-extension field element from another. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the first 54-extension field element.
[in] b - the second 54-extension field element.
Definition at line 356 of file relic_fpx_add.c.
References fp18_sub().
fp54_neg()
void fp54_neg (fp54_t c, const fp54_t a)
Negates a 54-extension field element.
Parameters
[out] c - the result.
[out] a - the 54-extension field element to negate.
Definition at line 362 of file relic_fpx_add.c.
References fp18_neg().
fp54_dbl()
void fp54_dbl (fp54_t c, const fp54_t a)
Doubles a 54-extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the 54-extension field element to double.
Definition at line 368 of file relic_fpx_add.c.
References fp18_dbl().
fp54_mul_basic()
void fp54_mul_basic (fp54_t c, const fp54_t a, const fp54_t b)
Multiples two 54-extension field elements using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the 54-extension field element.
[in] b - the 54-extension field element.
Definition at line 42 of file relic_fp54_mul.c.
References ERR_CAUGHT, fp18_add(), fp18_copy(), fp18_free, fp18_mul, fp18_mul_art(), fp18_new, fp18_null, fp18_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp54_mul_lazyr()
void fp54_mul_lazyr (fp54_t c, const fp54_t a, const fp54_t b)
Multiples two 54-extension field elements using lazy reduction.
Parameters
[out] c - the result.
[in] a - the 54-extension field element.
[in] b - the 54-extension field element.
Definition at line 109 of file relic_fp54_mul.c.
References ERR_CAUGHT, fp18_add(), fp18_copy(), fp18_free, fp18_mul, fp18_mul_art(), fp18_new, fp18_null, fp18_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp54_mul_art()
void fp54_mul_art (fp54_t c, const fp54_t a)
Multiplies a 54-extension field element by the adjoined root.
Parameters
[out] c - the result.
[in] a - the 54-extension field element to multiply.
Definition at line 243 of file relic_fp54_mul.c.
References ERR_CAUGHT, fp18_copy(), fp18_free, fp18_mul_art(), fp18_new, fp18_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp54_mul_dxs()
void fp54_mul_dxs (fp54_t c, const fp54_t a, const fp54_t b)
Multiples a dense 54-extension field element by a sparse element using basic arithmetic. Computes C = A * B.
Parameters
[out] c - the result.
[in] a - the dense 54-extension field element.
[in] b - the sparse 54-extension field element.
Definition at line 175 of file relic_fp54_mul.c.
References ERR_CAUGHT, fp18_add(), fp18_copy(), fp18_free, fp18_mul, fp18_mul_art(), fp18_mul_dxs, fp18_new, fp18_null, fp18_sub(), fp9_add(), fp9_copy(), fp9_mul, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_mil_k54().
fp54_sqr_basic()
void fp54_sqr_basic (fp54_t c, const fp54_t a)
Computes the square of a 54-extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the 54-extension field element to square.
Definition at line 42 of file relic_fp54_sqr.c.
References ERR_CAUGHT, fp18_add(), fp18_dbl(), fp18_free, fp18_mul, fp18_mul_art(), fp18_new, fp18_null, fp18_sqr, fp18_sub(), fp_hlv, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp54_sqr_lazyr()
void fp54_sqr_lazyr (fp54_t c, const fp54_t a)
Computes the square of a 54-extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the 54-extension field element to square.
Definition at line 277 of file relic_fp54_sqr.c.
References ERR_CAUGHT, fp18_add(), fp18_dbl(), fp18_free, fp18_mul, fp18_mul_art(), fp18_new, fp18_null, fp18_sqr, fp18_sub(), fp_hlv, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp54_sqr_cyc_basic()
void fp54_sqr_cyc_basic (fp54_t c, const fp54_t a)
Computes the square of a cyclotomic 54-extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 114 of file relic_fp54_sqr.c.
References ERR_CAUGHT, fp9_add(), fp9_dbl(), fp9_free, fp9_mul_art(), fp9_new, fp9_null, fp9_sqr, fp9_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp54_sqr_cyc_lazyr()
void fp54_sqr_cyc_lazyr (fp54_t c, const fp54_t a)
Computes the square of a cyclotomic 54-extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 350 of file relic_fp54_sqr.c.
References ERR_CAUGHT, fp9_add(), fp9_dbl(), fp9_free, fp9_mul_art(), fp9_new, fp9_null, fp9_sqr, fp9_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp54_sqr_pck_basic()
void fp54_sqr_pck_basic (fp54_t c, const fp54_t a)
Computes the square of a compressed cyclotomic extension field element.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 203 of file relic_fp54_sqr.c.
References ERR_CAUGHT, fp9_add(), fp9_dbl(), fp9_free, fp9_mul_art(), fp9_new, fp9_null, fp9_sqr, fp9_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp54_sqr_pck_lazyr()
void fp54_sqr_pck_lazyr (fp54_t c, const fp54_t a)
Computes the square of a compressed cyclotomic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 440 of file relic_fp54_sqr.c.
References dv9_free, dv9_new, dv9_null, ERR_CAUGHT, fp3_addc_low(), fp3_nord_low(), fp3_rdcn_low(), fp3_subc_low(), fp9_add(), fp9_dbl(), fp9_free, fp9_mul_art(), fp9_new, fp9_null, fp9_sqr, fp9_sqr_unr(), fp9_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp54_test_cyc()
int fp54_test_cyc (const fp54_t a)
Tests if a 54-extension field element belongs to the cyclotomic subgroup.
A cyclotomic element is one raised to the (p^18 - 1)(p^9 + 1)-th power.
Parameters
[in] a - the 54-extension field element to test.
Returns
1 if the extension field element is in the subgroup, 0 otherwise.
Definition at line 2849 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp54_cmp(), fp54_frb(), fp54_free, fp54_mul, fp54_new, fp54_null, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp54_exp_dig(), fp54_pck(), fp54_size_bin(), and fp54_upk().
fp54_conv_cyc()
void fp54_conv_cyc (fp54_t c, const fp54_t a)
Converts a 54-extension field element to a cyclotomic element. Computes c = a^(p^18 - 1)*(p^9 + 1).
Parameters
[out] c - the result.
[in] a - a 54-extension field element.
Definition at line 2818 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp54_frb(), fp54_free, fp54_inv(), fp54_inv_cyc(), fp54_mul, fp54_new, fp54_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_exp_k54().
fp54_back_cyc()
void fp54_back_cyc (fp54_t c, const fp54_t a)
Decompresses a compressed cyclotomic extension field element.
Parameters
[out] c - the result.
[in] a - the 54-extension field element to decompress.
Definition at line 2877 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp54_cmp_dig(), fp9_add(), fp9_copy(), fp9_copy_sec(), fp9_dbl(), fp9_free, fp9_inv(), fp9_is_zero(), fp9_mul, fp9_mul_art(), fp9_new, fp9_null, fp9_set_dig(), fp9_sqr, fp9_sub(), fp_add_dig(), RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp54_read_bin(), and fp54_upk().
fp54_back_cyc_sim()
void fp54_back_cyc_sim (fp54_t * c, const fp54_t * a, int n)
Decompresses multiple compressed cyclotomic extension field elements.
Parameters
[out] c - the result.
[in] a - the 54 field elements to decompress.
[in] n - the number of field elements to decompress.
fp54_inv()
void fp54_inv (fp54_t c, const fp54_t a)
Inverts a 54-extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the 54-extension field element to invert.
Definition at line 820 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp18_add(), fp18_free, fp18_inv(), fp18_mul, fp18_mul_art(), fp18_new, fp18_null, fp18_sqr, fp18_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp54_conv_cyc(), and fp54_exp().
fp54_inv_cyc()
void fp54_inv_cyc (fp54_t c, const fp54_t a)
Computes the inverse of a cyclotomic 54-extension field element.
For unitary elements, this is equivalent to computing the conjugate. A unitary element is one previously raised to the (p^24 - 1)-th power.
Parameters
[out] c - the result.
[in] a - the 54-extension field element to invert.
Definition at line 879 of file relic_fpx_inv.c.
References fp18_inv_cyc(), and fp18_neg().
Referenced by fp54_conv_cyc(), fp54_exp_cyc(), fp54_exp_cyc_sps(), fp54_exp_dig(), pp_exp_k54(), and pp_map_k54().
fp54_frb()
void fp54_frb (fp54_t c, const fp54_t a, int i)
Computes the Frobenius endomorphism of a 54-extension element. Computes c = a^p.
Parameters
[out] c - the result.
[in] a - a 54-extension field element.
[in] i - the power of the Frobenius map.
Definition at line 206 of file relic_fpx_frb.c.
References fp18_frb(), fp3_mul_frb(), fp54_copy(), and fp9_mul_art().
Referenced by fp54_conv_cyc(), fp54_test_cyc(), and pp_exp_k54().
fp54_exp()
void fp54_exp (fp54_t c, const fp54_t a, const bn_t b)
Computes a power of a 54-extension field element. Faster formulas are used if the extension field element is cyclotomic.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 840 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), ERR_CAUGHT, fp54_copy(), fp54_free, fp54_inv(), fp54_mul, fp54_new, fp54_null, fp54_set_dig(), fp54_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
fp54_exp_dig()
void fp54_exp_dig (fp54_t c, const fp54_t a, dig_t b)
Computes a power of a 54-extension field element by a small exponent. Faster formulas are used if the extension field element is cyclotomic.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 876 of file relic_fpx_exp.c.
References bn_bits(), bn_free, bn_new, bn_null, bn_rec_naf(), bn_set_dig(), ERR_CAUGHT, fp54_copy(), fp54_free, fp54_inv_cyc(), fp54_mul, fp54_new, fp54_null, fp54_set_dig(), fp54_sqr, fp54_sqr_cyc, fp54_test_cyc(), RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_THROW, RLC_TRY, and util_bits_dig().
fp54_exp_cyc()
void fp54_exp_cyc (fp54_t c, const fp54_t a, const bn_t b)
Computes a power of a cyclotomic 54-extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 3037 of file relic_fpx_cyc.c.
References bn_bits(), bn_get_bit(), bn_ham(), bn_is_even(), bn_is_zero(), bn_sign(), ERR_CAUGHT, ERR_NO_MEMORY, fp54_back_cyc_sim(), fp54_copy(), fp54_free, fp54_inv_cyc(), fp54_mul, fp54_new, fp54_null, fp54_set_dig(), fp54_sqr_cyc, fp54_sqr_pck, RLC_ALLOCA, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.
fp54_exp_cyc_sps()
void fp54_exp_cyc_sps (fp54_t c, const fp54_t a, const int * b, size_t l, int s)
Computes a power of a cyclotomic 54-extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent in sparse form.
[in] l - the length of the exponent in sparse form.
[in] s - the sign of the exponent.
Definition at line 3133 of file relic_fpx_cyc.c.
References ERR_CAUGHT, ERR_NO_MEMORY, fp54_back_cyc_sim(), fp54_copy(), fp54_free, fp54_inv_cyc(), fp54_mul, fp54_new, fp54_null, fp54_set_dig(), fp54_sqr_pck, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by pp_exp_k54().
fp54_pck()
void fp54_pck (fp54_t c, const fp54_t a)
Compresses a 54-extension field element.
Parameters
[out] c - the result.
[in] a - the 54-extension field element to compress.
Definition at line 224 of file relic_fpx_pck.c.
References fp54_copy(), fp54_test_cyc(), and fp9_zero().
Referenced by fp54_write_bin().
fp54_upk()
int fp54_upk (fp54_t c, const fp54_t a)
Decompresses a 54-extension field element.
Parameters
[out] c - the result.
[in] a - the 54-extension field element to decompress.
Returns
if the decompression was successful
Definition at line 232 of file relic_fpx_pck.c.
References fp54_back_cyc(), fp54_copy(), fp54_test_cyc(), and fp9_is_zero().