RELIC: src/pp/relic_pp_exp_k12.c File Reference
relic_pp_exp_k12.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_util.h"
Functions
static void pp_exp_bn (fp12_t c, fp12_t a)
static void pp_exp_sm9 (fp12_t c, fp12_t a)
static void pp_exp_b12 (fp12_t c, fp12_t a)
void pp_exp_k12 (fp12_t c, fp12_t a)
Detailed Description
Implementation of the final exponentiation for curves of embedding degree 12.
Definition in file relic_pp_exp_k12.c.
Function Documentation
pp_exp_bn()
static void pp_exp_bn (fp12_t c, fp12_t a) static
Computes the final exponentiation of a pairing defined over a Barreto-Naehrig curve.
Parameters
[out] c - the result.
[in] a - the extension field element to exponentiate.
Definition at line 47 of file relic_pp_exp_k12.c.
References bn_free, bn_new, bn_null, bn_sign(), ERR_CAUGHT, fp12_conv_cyc(), fp12_exp_cyc_sps(), fp12_frb(), fp12_free, fp12_inv_cyc(), fp12_mul, fp12_new, fp12_null, fp12_sqr_cyc, fp_prime_get_par(), fp_prime_get_par_sps(), RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_POS, RLC_THROW, and RLC_TRY.
Referenced by pp_exp_k12().
pp_exp_sm9()
static void pp_exp_sm9 (fp12_t c, fp12_t a) static
Computes the final exponentiation of a pairing defined over the SM9 curve.
Parameters
[out] c - the result.
[in] a - the extension field element to exponentiate.
Definition at line 134 of file relic_pp_exp_k12.c.
References bn_free, bn_new, bn_null, ERR_CAUGHT, fp12_conv_cyc(), fp12_copy(), fp12_exp_cyc_sps(), fp12_frb(), fp12_free, fp12_inv_cyc(), fp12_mul, fp12_new, fp12_null, fp12_sqr_cyc, fp_prime_get_par(), fp_prime_get_par_sps(), RLC_CATCH_ANY, RLC_FINALLY, RLC_POS, RLC_THROW, and RLC_TRY.
Referenced by pp_exp_k12().
pp_exp_b12()
static void pp_exp_b12 (fp12_t c, fp12_t a) static
Computes the final exponentiation of a pairing defined over a Barreto-Lynn-Scott curve.
Parameters
[out] c - the result.
[in] a - the extension field element to exponentiate.
Definition at line 233 of file relic_pp_exp_k12.c.
References bn_free, bn_new, bn_null, bn_sign(), ERR_CAUGHT, fp12_conv_cyc(), fp12_exp_cyc_sps(), fp12_frb(), fp12_free, fp12_inv_cyc(), fp12_mul, fp12_new, fp12_null, fp12_sqr_cyc, fp_prime_get_par(), fp_prime_get_par_sps(), RLC_CATCH_ANY, RLC_FINALLY, RLC_TERMS, RLC_THROW, and RLC_TRY.
Referenced by pp_exp_k12().
pp_exp_k12()
void pp_exp_k12 (fp12_t c, fp12_t a)
Computes the final exponentiation for a pairing defined over curves of embedding degree 12. Computes c = a^(p^12 - 1)/r.
Parameters
[out] c - the result.
[in] a - the extension field element to exponentiate.
Definition at line 340 of file relic_pp_exp_k12.c.
References EP_B12, EP_BN, ep_curve_is_pairf(), ep_param_get(), pp_exp_b12(), pp_exp_bn(), pp_exp_sm9(), and SM9_P256.
Referenced by gt_rand(), pp_map_oatep_k12(), pp_map_sim_oatep_k12(), pp_map_sim_tatep_k12(), and pp_map_tatep_k12().