RELIC: src/cp/relic_cp_ecies.c File Reference
relic_cp_ecies.c File Reference
Cryptographic protocols
#include "relic.h"
Functions
int cp_ecies_gen (bn_t d, ec_t q)
int cp_ecies_enc (ec_t r, uint8_t *out, size_t *out_len, const uint8_t *in, size_t in_len, const ec_t q)
int cp_ecies_dec (uint8_t *out, size_t *out_len, const ec_t r, const uint8_t *in, size_t in_len, const bn_t d)
Detailed Description
Implementation of the ECIES cryptosystem.
Definition in file relic_cp_ecies.c.
Function Documentation
cp_ecies_gen()
int cp_ecies_gen (bn_t d, ec_t q)
Generates an ECIES key pair.
Parameters
[out] d - the private key.
[in] q - the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_ecies.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), ec_curve_get_ord, ec_mul_gen, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_ecies_enc()
int cp_ecies_enc (ec_t r, uint8_t * out, size_t * out_len, const uint8_t * in, size_t in_len, const ec_t q)
Encrypts using the ECIES cryptosystem.
Parameters
[out] r - the resulting elliptic curve point.
[out] out - the output buffer.
[in,out] out_len - the buffer capacity and number of bytes written.
[in] in - the input buffer.
[in] in_len - the number of bytes to encrypt.
[in] iv - the block cipher initialization vector.
[in] q - the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 61 of file relic_cp_ecies.c.
References bc_aes_cbc_enc(), bn_bits(), bn_free, bn_new, bn_null, bn_rand_mod(), bn_size_bin(), bn_write_bin(), ec_curve_get_ord, ec_free, ec_get_x, ec_mul, ec_mul_gen, ec_new, ec_null, ec_param_level, md_hmac(), md_kdf(), RLC_BC_LEN, RLC_CATCH_ANY, RLC_CEIL, RLC_ERR, RLC_FC_BYTES, RLC_FINALLY, RLC_MAX, RLC_MD_LEN, RLC_OK, and RLC_TRY.
cp_ecies_dec()
int cp_ecies_dec (uint8_t * out, size_t * out_len, const ec_t r, const uint8_t * in, size_t in_len, const bn_t d)
Decrypts using the ECIES cryptosystem.
Parameters
[out] out - the output buffer.
[in,out] out_len - the buffer capacity and number of bytes written.
[in] in - the input buffer.
[in] in_len - the number of bytes to encrypt.
[in] iv - the block cipher initialization vector.
[in] d - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 115 of file relic_cp_ecies.c.
References bc_aes_cbc_dec(), bn_bits(), bn_free, bn_new, bn_null, bn_size_bin(), bn_write_bin(), ec_free, ec_get_x, ec_mul, ec_new, ec_null, ec_param_level, md_hmac(), md_kdf(), RLC_BC_LEN, RLC_CATCH_ANY, RLC_CEIL, RLC_ERR, RLC_FC_BYTES, RLC_FINALLY, RLC_MAX, RLC_MD_LEN, RLC_OK, RLC_TRY, and util_cmp_sec().