RELIC: include/relic_ep.h File Reference
relic_ep.h File Reference
Elliptic curves over prime fields
#include "relic_fp.h"
#include "relic_bn.h"
#include "relic_types.h"
#include "relic_label.h"
Data Structures
struct ep_st
struct iso_st
Macros
#define RLC_EP_DTYPE 1
#define RLC_EP_MTYPE 2
#define RLC_EP_TABLE_BASIC (RLC_FP_BITS + 1)
#define RLC_EP_TABLE_COMBS (1 << RLC_DEPTH)
#define RLC_EP_TABLE_COMBD (1 << (RLC_DEPTH + 1))
#define RLC_EP_TABLE_LWNAF (1 << (RLC_DEPTH - 2))
#define RLC_EP_TABLE RLC_EP_TABLE_COMBS
#define RLC_EP_TABLE_MAX RLC_MAX(RLC_EP_TABLE_BASIC, RLC_EP_TABLE_COMBD)
#define RLC_EP_CTMAP_MAX 16
#define ep_null(A)
#define ep_new(A)
#define ep_free(A)
#define ep_add(R, P, Q)
#define ep_dbl(R, P)
#define ep_mul(R, P, K)
#define ep_mul_pre(T, P)
#define ep_mul_fix(R, T, K)
#define ep_mul_sim(R, P, K, Q, M)
#define ep_mul_big(R, P, K)
#define ep_map(R, S, L)
Typedefs
typedef ep_st ep_t[1]
typedef iso_st * iso_t
Enumerations
enum {
EP_K1 = 1 , EP_SS2 , EP_BN , EP_GMT8 ,
EP_B12 , EP_AFG16 , EP_FM16 , EP_K16 ,
EP_K18 , EP_FM18 , EP_SG18 , EP_B24 ,
EP_B48 , EP_SG54
}
enum {
SECG_P160 = 1 , SECG_K160 , NIST_P192 , SECG_K192 ,
CURVE_22103 , NIST_P224 , SECG_K224 , CURVE_4417 ,
CURVE_1174 , CURVE_25519 , TWEEDLEDUM , NIST_P256 ,
BSI_P256 , SECG_K256 , SM2_P256 , CURVE_67254 ,
CURVE_383187 , NIST_P384 , CURVE_511187 , NIST_P521 ,
BN_P158 , BN_P254 , BN_P256 , SM9_P256 ,
B24_P315 , B24_P317 , K16_P330 , K18_P354 ,
B12_P377 , B12_P381 , BN_P382 , B12_P383 ,
BN_P446 , B12_P446 , B12_P455 , K18_P508 ,
B24_P509 , AFG16_P510 , OT8_P511 , GMT8_P544 ,
SG54_P569 , B48_P575 , BN_P638 , B12_P638 ,
K18_P638 , SG18_P638 , FM16_P765 , K16_P766 ,
AFG16_P766 , FM18_P768 , B12_P1150 , SS_P1536 ,
K1_P3072
}
Functions
void ep_curve_init (void)
void ep_curve_clean (void)
dig_t * ep_curve_get_a (void)
dig_t * ep_curve_get_b (void)
dig_t * ep_curve_get_b3 (void)
dig_t * ep_curve_get_beta (void)
void ep_curve_get_v1 (bn_t v[])
void ep_curve_get_v2 (bn_t v[])
int ep_curve_opt_a (void)
int ep_curve_opt_b (void)
void ep_curve_mul_a (fp_t c, const fp_t a)
void ep_curve_mul_b (fp_t c, const fp_t a)
int ep_curve_is_endom (void)
int ep_curve_is_super (void)
int ep_curve_is_pairf (void)
int ep_curve_is_ctmap (void)
void ep_curve_get_gen (ep_t g)
const ep_t * ep_curve_get_tab (void)
void ep_curve_get_ord (bn_t n)
void ep_curve_get_cof (bn_t h)
iso_t ep_curve_get_iso (void)
void ep_curve_set_plain (const fp_t a, const fp_t b, const ep_t g, const bn_t r, const bn_t h, int ctmap)
void ep_curve_set_super (const fp_t a, const fp_t b, const ep_t g, const bn_t r, const bn_t h, int ctmap)
void ep_curve_set_endom (const fp_t a, const fp_t b, const ep_t g, const bn_t r, const bn_t h, const fp_t beta, const bn_t l, int ctmap)
int ep_curve_embed (void)
int ep_curve_frdim (void)
void ep_param_set (int param)
int ep_param_set_any (void)
int ep_param_set_any_plain (void)
int ep_param_set_any_endom (void)
int ep_param_set_any_super (void)
int ep_param_set_any_pairf (void)
int ep_param_get (void)
void ep_param_print (void)
int ep_param_level (void)
int ep_is_infty (const ep_t p)
void ep_set_infty (ep_t p)
void ep_copy (ep_t r, const ep_t p)
int ep_cmp (const ep_t p, const ep_t q)
void ep_rand (ep_t p)
void ep_blind (ep_t r, const ep_t p)
void ep_rhs (fp_t rhs, const fp_t x)
int ep_on_curve (const ep_t p)
void ep_tab (ep_t *t, const ep_t p, int w)
void ep_print (const ep_t p)
size_t ep_size_bin (const ep_t a, int pack)
void ep_read_bin (ep_t a, const uint8_t *bin, size_t len)
void ep_write_bin (uint8_t *bin, size_t len, const ep_t a, int pack)
void ep_neg (ep_t r, const ep_t p)
void ep_add_basic (ep_t r, const ep_t p, const ep_t q)
void ep_add_slp_basic (ep_t r, fp_t s, const ep_t p, const ep_t q)
void ep_add_projc (ep_t r, const ep_t p, const ep_t q)
void ep_add_jacob (ep_t r, const ep_t p, const ep_t q)
void ep_sub (ep_t r, const ep_t p, const ep_t q)
void ep_dbl_basic (ep_t r, const ep_t p)
void ep_dbl_slp_basic (ep_t r, fp_t s, const ep_t p)
void ep_dbl_projc (ep_t r, const ep_t p)
void ep_dbl_jacob (ep_t r, const ep_t p)
void ep_psi (ep_t r, const ep_t p)
void ep_mul_basic (ep_t r, const ep_t p, const bn_t k)
void ep_mul_slide (ep_t r, const ep_t p, const bn_t k)
void ep_mul_monty (ep_t r, const ep_t p, const bn_t k)
void ep_mul_lwnaf (ep_t r, const ep_t p, const bn_t k)
void ep_mul_lwreg (ep_t r, const ep_t p, const bn_t k)
void ep_mul_gen (ep_t r, const bn_t k)
void ep_mul_dig (ep_t r, const ep_t p, dig_t k)
void ep_mul_cof (ep_t r, const ep_t p)
void ep_mul_pre_basic (ep_t *t, const ep_t p)
void ep_mul_pre_yaowi (ep_t *t, const ep_t p)
void ep_mul_pre_nafwi (ep_t *t, const ep_t p)
void ep_mul_pre_combs (ep_t *t, const ep_t p)
void ep_mul_pre_combd (ep_t *t, const ep_t p)
void ep_mul_pre_lwnaf (ep_t *t, const ep_t p)
void ep_mul_fix_basic (ep_t r, const ep_t *t, const bn_t k)
void ep_mul_fix_yaowi (ep_t r, const ep_t *t, const bn_t k)
void ep_mul_fix_nafwi (ep_t r, const ep_t *t, const bn_t k)
void ep_mul_fix_combs (ep_t r, const ep_t *t, const bn_t k)
void ep_mul_fix_combd (ep_t r, const ep_t *t, const bn_t k)
void ep_mul_fix_lwnaf (ep_t r, const ep_t *t, const bn_t k)
void ep_mul_sim_basic (ep_t r, const ep_t p, const bn_t k, const ep_t q, const bn_t m)
void ep_mul_sim_trick (ep_t r, const ep_t p, const bn_t k, const ep_t q, const bn_t m)
void ep_mul_sim_inter (ep_t r, const ep_t p, const bn_t k, const ep_t q, const bn_t m)
void ep_mul_sim_joint (ep_t r, const ep_t p, const bn_t k, const ep_t q, const bn_t m)
void ep_mul_sim_lot (ep_t r, const ep_t p[], const bn_t k[], int n)
void ep_mul_sim_gen (ep_t r, const bn_t k, const ep_t q, const bn_t m)
void ep_mul_sim_dig (ep_t r, const ep_t p[], const dig_t k[], int n)
void ep_norm (ep_t r, const ep_t p)
void ep_norm_sim (ep_t *r, const ep_t *t, int n)
void ep_map_basic (ep_t p, const uint8_t *msg, size_t len)
void ep_map_sswum (ep_t p, const uint8_t *msg, size_t len)
void ep_map_swift (ep_t p, const uint8_t *msg, size_t len)
void ep_map_rnd (ep_t p, const uint8_t *uniform_bytes, size_t len)
void ep_pck (ep_t r, const ep_t p)
int ep_upk (ep_t r, const ep_t p)
Detailed Description
Interface of the module for arithmetic on prime elliptic curves.
The scalar multiplication functions are only guaranteed to work in the large prime order subgroup. If you need a generic scalar multiplication function, use ep_mul_basic.
Definition in file relic_ep.h.
Macro Definition Documentation
RLC_EP_DTYPE
#define RLC_EP_DTYPE 1
Denotes a divisive twist.
Definition at line 205 of file relic_ep.h.
Referenced by ep2_curve_set_twist(), ep3_curve_set_twist(), ep4_curve_set_twist(), ep8_curve_set_twist(), ep_param_set_any_pairf(), fp12_mul_dxs_basic(), fp12_mul_dxs_lazyr(), and fp18_mul_dxs_lazyr().
RLC_EP_MTYPE
#define RLC_EP_MTYPE 2
Denotes a multiplicative twist.
Definition at line 210 of file relic_ep.h.
Referenced by ep2_curve_mul_a(), ep2_curve_set_twist(), ep3_curve_set_twist(), ep4_curve_mul_a(), ep4_curve_set_twist(), ep8_curve_set_twist(), ep_param_set_any_pairf(), pp_add_k12_basic(), pp_add_k12_projc_basic(), pp_add_k12_projc_lazyr(), pp_add_k16_basic(), pp_add_k16_projc_basic(), pp_add_k16_projc_lazyr(), pp_add_k18_basic(), pp_add_k18_projc_basic(), pp_add_k18_projc_lazyr(), pp_add_k24_basic(), pp_add_k24_projc(), pp_add_k8_basic(), pp_add_k8_projc_basic(), pp_add_k8_projc_lazyr(), pp_add_lit_k12(), pp_add_lit_k16(), pp_dbl_k12_basic(), pp_dbl_k12_projc_basic(), pp_dbl_k12_projc_lazyr(), pp_dbl_k16_basic(), pp_dbl_k16_projc_basic(), pp_dbl_k16_projc_lazyr(), pp_dbl_k18_basic(), pp_dbl_k18_projc_basic(), pp_dbl_k18_projc_lazyr(), pp_dbl_k24_basic(), pp_dbl_k24_projc(), pp_dbl_k8_basic(), pp_dbl_k8_projc_basic(), pp_dbl_k8_projc_lazyr(), pp_dbl_k8_projc_lazyr_new(), pp_dbl_k8_projc_new(), pp_dbl_lit_k12(), and pp_dbl_lit_k16().
RLC_EP_TABLE_BASIC
#define RLC_EP_TABLE_BASIC (RLC_FP_BITS + 1)
Size of a precomputation table using the binary method.
Definition at line 215 of file relic_ep.h.
RLC_EP_TABLE_COMBS
#define RLC_EP_TABLE_COMBS (1 << RLC_DEPTH)
Size of a precomputation table using the single-table comb method.
Definition at line 220 of file relic_ep.h.
Referenced by ep2_mul_pre_combs(), ep3_mul_pre_combs(), ep4_mul_pre_combs(), ep8_mul_pre_combs(), and ep_mul_pre_combs().
RLC_EP_TABLE_COMBD
#define RLC_EP_TABLE_COMBD (1 << (RLC_DEPTH + 1))
Size of a precomputation table using the double-table comb method.
Definition at line 225 of file relic_ep.h.
Referenced by ep2_mul_pre_combd(), ep3_mul_pre_combd(), ep4_mul_pre_combd(), and ep8_mul_pre_combd().
RLC_EP_TABLE_LWNAF
#define RLC_EP_TABLE_LWNAF (1 << (RLC_DEPTH - 2))
Size of a precomputation table using the w-NAF method.
Definition at line 230 of file relic_ep.h.
RLC_EP_TABLE
#define RLC_EP_TABLE RLC_EP_TABLE_COMBS
Size of a precomputation table using the chosen algorithm.
Definition at line 238 of file relic_ep.h.
Referenced by ep2_curve_clean(), ep2_curve_init(), ep3_curve_clean(), ep3_curve_init(), ep4_curve_clean(), ep4_curve_init(), ep8_curve_clean(), ep8_curve_init(), and ep_curve_init().
RLC_EP_TABLE_MAX
#define RLC_EP_TABLE_MAX RLC_MAX(RLC_EP_TABLE_BASIC, RLC_EP_TABLE_COMBD)
Maximum size of a precomputation table.
Definition at line 251 of file relic_ep.h.
RLC_EP_CTMAP_MAX
#define RLC_EP_CTMAP_MAX 16
Maximum number of coefficients of an isogeny map polynomial. RLC_TERMS of value 16 is sufficient for a degree-11 isogeny polynomial.
Definition at line 258 of file relic_ep.h.
Referenced by ep_param_get_coeffs().
ep_null
#define ep_null (A)
Value:
/* empty */
Initializes a point on a prime elliptic curve with a null value.
Parameters
[out] A - the point to initialize.
Definition at line 332 of file relic_ep.h.
Referenced by ep_cmp(), ep_curve_set_endom(), ep_map_sswum_impl(), ep_mul_basic(), ep_mul_cof(), ep_mul_combs_endom(), ep_mul_dig(), ep_mul_gen(), ep_mul_glv_imp(), ep_mul_monty(), ep_mul_naf_imp(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_mul_sim_basic(), ep_mul_sim_dig(), ep_mul_sim_endom(), ep_mul_sim_gen(), ep_mul_sim_joint(), ep_mul_sim_lot_endom(), ep_mul_sim_lot_plain(), ep_mul_sim_plain(), ep_mul_sim_trick(), ep_mul_slide(), ep_on_curve(), ep_param_set(), ep_sub(), ep_write_bin(), pp_add_k2_basic(), pp_dbl_k2_basic(), pp_fin_k16_oatep(), pp_fin_k18_oatep(), pp_map_k24(), pp_map_k48(), pp_map_oatep_k12(), pp_map_oatep_k16(), pp_map_oatep_k18(), pp_map_oatep_k8(), pp_map_sim_k24(), pp_map_sim_k48(), pp_map_sim_oatep_k12(), pp_map_sim_oatep_k16(), pp_map_sim_oatep_k18(), pp_map_sim_oatep_k8(), pp_map_sim_tatep_k1(), pp_map_sim_tatep_k12(), pp_map_sim_tatep_k16(), pp_map_sim_tatep_k18(), pp_map_sim_tatep_k2(), pp_map_sim_weilp_k1(), pp_map_sim_weilp_k12(), pp_map_sim_weilp_k16(), pp_map_sim_weilp_k18(), pp_map_sim_weilp_k2(), pp_map_tatep_k1(), pp_map_tatep_k12(), pp_map_tatep_k16(), pp_map_tatep_k18(), pp_map_tatep_k2(), pp_map_weilp_k1(), pp_map_weilp_k12(), pp_map_weilp_k16(), pp_map_weilp_k18(), pp_map_weilp_k2(), pp_mil_k12(), pp_mil_k16(), pp_mil_k18(), pp_mil_k2(), pp_mil_k24(), pp_mil_k48(), pp_mil_k54(), pp_mil_k8(), and pp_mil_lit_k2().
ep_new
#define ep_new (A)
Value:
/* empty */
Calls a function to allocate a point on a prime elliptic curve.
Parameters
[out] A - the new point.
Exceptions
ERR_NO_MEMORY - if there is no available memory.
Definition at line 351 of file relic_ep.h.
Referenced by ep_cmp(), ep_curve_set_endom(), ep_map_sswum_impl(), ep_mul_basic(), ep_mul_cof(), ep_mul_combs_endom(), ep_mul_dig(), ep_mul_gen(), ep_mul_glv_imp(), ep_mul_monty(), ep_mul_naf_imp(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_mul_sim_basic(), ep_mul_sim_dig(), ep_mul_sim_endom(), ep_mul_sim_gen(), ep_mul_sim_joint(), ep_mul_sim_lot_endom(), ep_mul_sim_lot_plain(), ep_mul_sim_plain(), ep_mul_sim_trick(), ep_mul_slide(), ep_on_curve(), ep_param_set(), ep_sub(), ep_write_bin(), pp_add_k2_basic(), pp_dbl_k2_basic(), pp_fin_k16_oatep(), pp_fin_k18_oatep(), pp_map_k24(), pp_map_k48(), pp_map_oatep_k12(), pp_map_oatep_k16(), pp_map_oatep_k18(), pp_map_oatep_k8(), pp_map_sim_k24(), pp_map_sim_k48(), pp_map_sim_oatep_k12(), pp_map_sim_oatep_k16(), pp_map_sim_oatep_k18(), pp_map_sim_oatep_k8(), pp_map_sim_tatep_k1(), pp_map_sim_tatep_k12(), pp_map_sim_tatep_k16(), pp_map_sim_tatep_k18(), pp_map_sim_tatep_k2(), pp_map_sim_weilp_k1(), pp_map_sim_weilp_k12(), pp_map_sim_weilp_k16(), pp_map_sim_weilp_k18(), pp_map_sim_weilp_k2(), pp_map_tatep_k1(), pp_map_tatep_k12(), pp_map_tatep_k16(), pp_map_tatep_k18(), pp_map_tatep_k2(), pp_map_weilp_k1(), pp_map_weilp_k12(), pp_map_weilp_k16(), pp_map_weilp_k18(), pp_map_weilp_k2(), pp_mil_k12(), pp_mil_k16(), pp_mil_k18(), pp_mil_k2(), pp_mil_k24(), pp_mil_k48(), pp_mil_k54(), pp_mil_k8(), and pp_mil_lit_k2().
ep_free
#define ep_free (A)
Value:
/* empty */
Calls a function to clean and free a point on a prime elliptic curve.
Parameters
[out] A - the point to free.
Definition at line 368 of file relic_ep.h.
Referenced by ed_cmp(), ep_cmp(), ep_curve_set_endom(), ep_map_sswum_impl(), ep_mul_basic(), ep_mul_cof(), ep_mul_combs_endom(), ep_mul_dig(), ep_mul_gen(), ep_mul_glv_imp(), ep_mul_monty(), ep_mul_naf_imp(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_mul_sim_basic(), ep_mul_sim_dig(), ep_mul_sim_endom(), ep_mul_sim_gen(), ep_mul_sim_joint(), ep_mul_sim_lot_endom(), ep_mul_sim_lot_plain(), ep_mul_sim_plain(), ep_mul_sim_trick(), ep_mul_slide(), ep_on_curve(), ep_param_set(), ep_sub(), ep_write_bin(), pp_add_k2_basic(), pp_dbl_k2_basic(), pp_fin_k16_oatep(), pp_fin_k18_oatep(), pp_map_k24(), pp_map_k48(), pp_map_oatep_k12(), pp_map_oatep_k16(), pp_map_oatep_k18(), pp_map_oatep_k8(), pp_map_sim_k24(), pp_map_sim_k48(), pp_map_sim_oatep_k12(), pp_map_sim_oatep_k16(), pp_map_sim_oatep_k18(), pp_map_sim_oatep_k8(), pp_map_sim_tatep_k1(), pp_map_sim_tatep_k12(), pp_map_sim_tatep_k16(), pp_map_sim_tatep_k18(), pp_map_sim_tatep_k2(), pp_map_sim_weilp_k1(), pp_map_sim_weilp_k12(), pp_map_sim_weilp_k16(), pp_map_sim_weilp_k18(), pp_map_sim_weilp_k2(), pp_map_tatep_k1(), pp_map_tatep_k12(), pp_map_tatep_k16(), pp_map_tatep_k18(), pp_map_tatep_k2(), pp_map_weilp_k1(), pp_map_weilp_k12(), pp_map_weilp_k16(), pp_map_weilp_k18(), pp_map_weilp_k2(), pp_mil_k12(), pp_mil_k16(), pp_mil_k18(), pp_mil_k2(), pp_mil_k24(), pp_mil_k48(), pp_mil_k54(), and pp_mil_k8().
ep_add
#define ep_add (R, P, Q)
Value:
ep_add_projc(R, P, Q)
Adds two prime elliptic curve points. Computes R = P + Q.
Parameters
[out] R - the result.
[in] P - the first point to add.
[in] Q - the second point to add.
Definition at line 382 of file relic_ep.h.
Referenced by ep_map_sswum_impl(), ep_mul_basic(), ep_mul_cof(), ep_mul_combs_endom(), ep_mul_combs_plain(), ep_mul_dig(), ep_mul_fix_basic(), ep_mul_fix_combd(), ep_mul_fix_plain(), ep_mul_glv_imp(), ep_mul_monty(), ep_mul_naf_imp(), ep_mul_pre_combd(), ep_mul_pre_combs(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_mul_sim_basic(), ep_mul_sim_dig(), ep_mul_sim_endom(), ep_mul_sim_joint(), ep_mul_sim_lot_endom(), ep_mul_sim_lot_plain(), ep_mul_sim_plain(), ep_mul_sim_trick(), ep_mul_slide(), ep_sub(), and ep_tab().
ep_dbl
#define ep_dbl (R, P)
Value:
ep_dbl_projc(R, P)
Doubles a prime elliptic curve point. Computes R = 2P.
Parameters
[out] R - the result.
[in] P - the point to double.
Definition at line 396 of file relic_ep.h.
Referenced by ep_mul_basic(), ep_mul_cof(), ep_mul_combs_endom(), ep_mul_combs_plain(), ep_mul_dig(), ep_mul_fix_combd(), ep_mul_fix_plain(), ep_mul_glv_imp(), ep_mul_monty(), ep_mul_naf_imp(), ep_mul_pre_basic(), ep_mul_pre_combd(), ep_mul_pre_combs(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_mul_sim_dig(), ep_mul_sim_endom(), ep_mul_sim_joint(), ep_mul_sim_lot_endom(), ep_mul_sim_lot_plain(), ep_mul_sim_plain(), ep_mul_sim_trick(), ep_mul_slide(), and ep_tab().
ep_mul
#define ep_mul (R, P, K)
Value:
ep_mul_lwnaf(R, P, K)
Multiplies a prime elliptic curve point by an integer. Computes R = [k]P.
Parameters
[out] R - the result.
[in] P - the point to multiply.
[in] K - the integer.
Definition at line 415 of file relic_ep.h.
Referenced by ep_mul_gen(), ep_mul_sim_basic(), ep_mul_sim_gen(), ep_mul_sim_inter(), ep_mul_sim_joint(), and ep_mul_sim_trick().
ep_mul_pre
#define ep_mul_pre (T, P)
Value:
ep_mul_pre_combs(T, P)
Builds a precomputation table for multiplying a fixed prime elliptic point.
Parameters
[out] T - the precomputation table.
[in] P - the point to multiply.
Definition at line 429 of file relic_ep.h.
Referenced by ep_curve_set().
ep_mul_fix
#define ep_mul_fix (R, T, K)
Value:
ep_mul_fix_combs(R, T, K)
Multiplies a fixed prime elliptic point using a precomputation table. Computes R = [k]P.
Parameters
[out] R - the result.
[in] T - the precomputation table.
[in] K - the integer.
Definition at line 447 of file relic_ep.h.
Referenced by ep_mul_gen().
ep_mul_sim
#define ep_mul_sim (R, P, K, Q, M)
Value:
ep_mul_sim_inter(R, P, K, Q, M)
Multiplies and adds two prime elliptic curve points simultaneously. Computes R = [k]P + [m]Q.
Parameters
[out] R - the result.
[in] P - the first point to multiply.
[in] K - the first integer.
[in] Q - the second point to multiply.
[in] M - the second integer,
Definition at line 469 of file relic_ep.h.
Referenced by ep_mul_sim_gen().
ep_mul_big
#define ep_mul_big (R, P, K)
Value:
ep_mul_basic(R, P, K)
Multiplies a point in an elliptic curve over by an unrestricted scalar. Computes R = [k]P.
Parameters
[out] R - the result.
[in] P - the point to multiply.
[in] K - the integer.
Definition at line 482 of file relic_ep.h.
Referenced by ep_mul_cof().
ep_map
#define ep_map (R, S, L)
Value:
ep_map_sswum(R, S, L)
Hashes a byte string to a prime elliptic point or the right order. Computes R = H(s).
Parameters
[out] R - the result.
[in] S - the string to hash.
[in] L - the string length.
Definition at line 495 of file relic_ep.h.
Typedef Documentation
ep_t
typedef ep_st ep_t[1]
Pointer to an elliptic curve point.
Definition at line 282 of file relic_ep.h.
iso_t
typedef iso_st* iso_t
Pointer to isogeny map coefficients.
Definition at line 320 of file relic_ep.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Pairing-friendly elliptic curve identifiers.
Enumerator
EP_K1
Ordinary curves with embedding degree 1.
EP_SS2
Supersingular curves with embedding degree 2.
EP_BN
Barreto-Naehrig.
EP_GMT8
EP_B12
EP_AFG16
EP_FM16
EP_K16
EP_K18
EP_FM18
EP_SG18
EP_B24
EP_B48
EP_SG54
Scott-Guillevic family with embedding degree 54.
Definition at line 55 of file relic_ep.h.
anonymous enum
anonymous enum
Prime elliptic curve identifiers.
Enumerator
SECG_P160
SECG P-160 prime curve.
SECG_K160
SECG K-160 prime curve.
NIST_P192
NIST P-192 prime curve.
SECG_K192
SECG K-192 prime curve.
CURVE_22103
Curve22103 prime curve.
NIST_P224
NIST P-224 prime curve.
SECG_K224
SECG K-224 prime curve.
CURVE_4417
Curve4417 prime curve.
CURVE_1174
Curve1147 prime curve.
CURVE_25519
Curve25519 prime curve.
TWEEDLEDUM
Curve Tweedledum given by Daira Hopwoord at https://github.com/daira/tweedle
NIST_P256
NIST P-256 prime curve.
BSI_P256
Brainpool P256r1 curve.
SECG_K256
SECG K-256 prime curve.
SM2_P256
SM2 P-256 prime curve.
CURVE_67254
Curve67254 prime curve.
CURVE_383187
Curve383187 prime curve.
NIST_P384
NIST P-384 prime curve.
CURVE_511187
Curve 511187 prime curve.
NIST_P521
NIST P-521 prime curve.
BN_P158
Barreto-Naehrig curve with positive x
BN_P254
Barreto-Naehrig curve with negative x (found by Nogami et al.).
BN_P256
Barreto-Naehrig curve with negative x.
SM9_P256
Barreto-Naehrig curve standardized in China.
B24_P315
Barreto-Lynn-Scott curve with embedding degree 24 (SNARK curve).
B24_P317
Barreto-Lynn-Scott curve with embedding degree 24 (SNARK curve).
K16_P330
Kachisa-Schaefer-Scott with embedding degree 16.
K18_P354
Kachisa-Schaefer-Scott curve with embedding degree 18.
B12_P377
Barreto-Lynn-Scott curve with embedding degree 12 (SNARK curve).
B12_P381
Barreto-Lynn-Scott curve with embedding degree 12 (ZCash curve).
BN_P382
Barreto-Naehrig curve with negative x.
B12_P383
Barreto-Lynn-Scott curve with embedding degree 12 (GT-strong).
BN_P446
Barreto-Naehrig curve with embedding degree 12.
B12_P446
Barreto-Lynn-Scott curve with embedding degree 12.
B12_P455
Barreto-Lynn-Scott curve with embedding degree 12.
K18_P508
Kachisa-Schaefer-Scott with negative x.
B24_P509
Barreto-Lynn-Scott curve with embedding degree 24.
AFG16_P510
New family with embeeding degree 16.
OT8_P511
Optimal TNFS-secure curve with embedding degree 8.
GMT8_P544
Cocks-pinch curve with embedding degree 8.
SG54_P569
Kachisa-Scott-Schaefer curve with embedding degree 54.
B48_P575
Barreto-Lynn-Scott curve with embedding degree 48.
BN_P638
Barreto-Naehrig curve with positive x.
B12_P638
Barreto-Lynn-Scott curve with embedding degree 12.
K18_P638
Kachisa-Scott-Schaefer curve with embedding degree 18.
SG18_P638
Scott-Guillevic curve with embedding degree 18.
FM16_P765
K16_P766
Kachisa-Schaefer-Scott with embedding degree 16.
AFG16_P766
New family with embeeding degree 16.
FM18_P768
B12_P1150
Barreto-Lynn-Scott curve with embedding degree 12.
SS_P1536
1536-bit supersingular curve.
K1_P3072
3072-bit supersingular curve.
Definition at line 89 of file relic_ep.h.
Function Documentation
ep_curve_init()
void ep_curve_init (void)
Initializes the prime elliptic curve arithmetic module.
Definition at line 229 of file relic_ep_curve.c.
References bn_make(), core_get(), _ctx_t::ep_g, _ctx_t::ep_h, _ctx_t::ep_pre, _ctx_t::ep_ptr, _ctx_t::ep_r, ep_set_infty(), _ctx_t::ep_v1, _ctx_t::ep_v2, RLC_EP_TABLE, and RLC_FP_DIGS.
Referenced by core_init().
ep_curve_clean()
void ep_curve_clean (void)
Finalizes the prime elliptic curve arithmetic module.
Definition at line 247 of file relic_ep_curve.c.
References bn_clean(), core_get(), _ctx_t::ep_h, _ctx_t::ep_r, _ctx_t::ep_v1, and _ctx_t::ep_v2.
Referenced by core_clean().
ep_curve_get_a()
dig_t * ep_curve_get_a (void)
Returns the a-coefficient of the currently configured prime elliptic curve.
Returns
the a-coefficient of the elliptic curve.
Definition at line 261 of file relic_ep_curve.c.
References core_get(), and _ctx_t::ep_a.
Referenced by ep2_curve_mul_a(), ep_map_swift_impl(), ep_rhs(), and pp_dbl_k1_projc().
ep_curve_get_b()
dig_t * ep_curve_get_b (void)
Returns the b-coefficient of the currently configured prime elliptic curve.
Returns
the b-coefficient of the elliptic curve.
Definition at line 265 of file relic_ep_curve.c.
References core_get(), and _ctx_t::ep_b.
Referenced by ep_rhs(), pp_dbl_k54_projc(), pp_dbl_lit_k12(), pp_dbl_lit_k16(), and pp_dbl_lit_k18().
ep_curve_get_b3()
dig_t * ep_curve_get_b3 (void)
Returns the b3 = 3*b value used in elliptic curve arithmetic.
Returns
the value b3 used in elliptic curve arithmetic.
ep_curve_get_beta()
dig_t * ep_curve_get_beta (void)
Returns the efficient endormorphism associated with the prime curve.
Definition at line 271 of file relic_ep_curve.c.
References _ctx_t::beta, and core_get().
Referenced by ep_psi().
ep_curve_get_v1()
void ep_curve_get_v1 (bn_t v[])
Returns the parameter V1 of the prime curve.
Definition at line 275 of file relic_ep_curve.c.
References bn_copy(), core_get(), and _ctx_t::ep_v1.
Referenced by ep_mul_combs_endom(), ep_mul_glv_imp(), ep_mul_reg_glv(), ep_mul_sim_endom(), and ep_mul_sim_lot_endom().
ep_curve_get_v2()
void ep_curve_get_v2 (bn_t v[])
Returns the parameter V2 of the prime curve.
Definition at line 282 of file relic_ep_curve.c.
References bn_copy(), core_get(), and _ctx_t::ep_v2.
Referenced by ep_mul_combs_endom(), ep_mul_glv_imp(), ep_mul_reg_glv(), ep_mul_sim_endom(), and ep_mul_sim_lot_endom().
ep_curve_opt_a()
int ep_curve_opt_a (void)
Returns a optimization identifier based on the a-coefficient of the curve.
Returns
the optimization identifier.
Definition at line 291 of file relic_ep_curve.c.
References core_get(), and _ctx_t::ep_opt_a.
Referenced by ep2_curve_mul_a(), ep2_map_swift(), ep4_map(), ep_curve_set_map(), ep_map_rnd(), ep_map_sswum(), ep_map_swift_impl(), ep_psi(), and ep_rhs().
ep_curve_opt_b()
int ep_curve_opt_b (void)
Returns a optimization identifier based on the b-coefficient of the curve.
Returns
the optimization identifier.
Definition at line 295 of file relic_ep_curve.c.
References core_get(), and _ctx_t::ep_opt_b.
Referenced by ep4_map(), ep_curve_set_map(), ep_map_rnd(), ep_map_sswum(), ep_map_swift_impl(), ep_rhs(), pp_dbl_k12_projc_basic(), pp_dbl_k12_projc_lazyr(), and pp_norm_k16().
ep_curve_mul_a()
void ep_curve_mul_a (fp_t c, const fp_t a)
Multiplies a field element by the a-coefficient of the curve.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
Definition at line 299 of file relic_ep_curve.c.
References core_get(), _ctx_t::ep_a, _ctx_t::ep_opt_a, fp_copy(), fp_dbl, fp_mul, fp_mul_dig(), fp_zero(), RLC_ONE, RLC_TINY, RLC_TWO, and RLC_ZERO.
ep_curve_mul_b()
void ep_curve_mul_b (fp_t c, const fp_t a)
Multiplies a field element by the b-coefficient of the curve.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
Definition at line 322 of file relic_ep_curve.c.
References core_get(), _ctx_t::ep_b, _ctx_t::ep_opt_b, fp_copy(), fp_mul, fp_mul_dig(), fp_zero(), RLC_ONE, RLC_TINY, and RLC_ZERO.
ep_curve_is_endom()
int ep_curve_is_endom (void)
Tests if the configured prime elliptic curve is a Koblitz curve.
Returns
1 if the prime elliptic curve is a Koblitz curve, 0 otherwise.
Definition at line 342 of file relic_ep_curve.c.
References core_get(), and _ctx_t::ep_is_endom.
Referenced by ep2_mul_lwnaf(), ep2_mul_lwreg(), ep2_mul_sim_gen(), ep2_mul_sim_inter(), ep3_mul_lwnaf(), ep3_mul_lwreg(), ep4_mul_lwnaf(), ep4_mul_lwreg(), ep8_mul_lwnaf(), ep8_mul_lwreg(), ep_mul_fix_combs(), ep_mul_lwnaf(), ep_mul_lwreg(), ep_mul_pre_combs(), ep_mul_sim_gen(), ep_mul_sim_inter(), and ep_mul_sim_lot().
ep_curve_is_super()
int ep_curve_is_super (void)
Tests if the configured prime elliptic curve is supersingular.
Returns
1 if the prime elliptic curve is supersingular, 0 otherwise.
Definition at line 346 of file relic_ep_curve.c.
References core_get(), and _ctx_t::ep_is_super.
Referenced by ep_curve_set_map(), and ep_map_swift().
ep_curve_is_pairf()
int ep_curve_is_pairf (void)
Tests if the configured prime elliptic curve is pairing-friendly.
Returns
0 if the prime elliptic curve is not pairing-friendly, and the family identifier otherwise.
Definition at line 350 of file relic_ep_curve.c.
References core_get(), and _ctx_t::ep_is_pairf.
Referenced by bn_rec_sac(), ep2_mul_cof(), ep2_mul_gls_imp(), ep2_mul_reg_gls(), ep2_mul_sim_endom(), ep2_mul_sim_lot(), ep3_mul_cof(), ep3_mul_gls_imp(), ep3_mul_reg_gls(), ep3_mul_sim_lot(), ep3_psi(), ep4_mul_cof(), ep4_mul_gls_imp(), ep4_mul_reg_gls(), ep4_mul_sim_lot(), ep4_psi(), ep8_mul_gls_imp(), ep8_mul_reg_gls(), ep8_mul_sim_lot(), ep_mul_cof(), ep_pck(), ep_upk(), fp12_exp_cyc_sim(), fp4_mul_frb(), g1_is_valid(), g2_is_valid(), gt_exp_gls_naf(), gt_exp_gls_sac(), gt_exp_reg_gls(), gt_exp_reg_sac(), gt_is_valid(), gt_psi(), pp_exp_k12(), pp_exp_k16(), pp_exp_k18(), pp_fin_k18_oatep(), pp_map_k24(), pp_map_k48(), pp_map_k54(), pp_map_oatep_k12(), pp_map_oatep_k16(), pp_map_oatep_k18(), pp_map_sim_k24(), pp_map_sim_k48(), pp_map_sim_oatep_k12(), pp_map_sim_oatep_k16(), and pp_map_sim_oatep_k18().
ep_curve_is_ctmap()
int ep_curve_is_ctmap (void)
Tests if the current curve should use an isogeny map for the SSWU map.
Returns
1 if the curve uses an isogeny, and 0 otherwise.
Definition at line 354 of file relic_ep_curve.c.
References core_get(), and _ctx_t::ep_is_ctmap.
Referenced by ep_curve_set_map(), ep_map_rnd(), and ep_map_sswum().
ep_curve_get_gen()
void ep_curve_get_gen (ep_t g)
Returns the generator of the group of points in the prime elliptic curve.
Parameters
[out] g - the returned generator.
Definition at line 358 of file relic_ep_curve.c.
References core_get(), and ep_copy().
Referenced by ep_mul_gen(), and ep_mul_sim_gen().
ep_curve_get_tab()
const ep_t * ep_curve_get_tab (void)
Returns the precomputation table for the generator.
Returns
the table.
Definition at line 370 of file relic_ep_curve.c.
References core_get(), and _ctx_t::ep_ptr.
Referenced by ep_curve_set(), ep_mul_gen(), and ep_mul_sim_gen().
ep_curve_get_ord()
void ep_curve_get_ord (bn_t n)
Returns the order of the group of points in the prime elliptic curve.
Parameters
[out] r - the returned order.
Definition at line 362 of file relic_ep_curve.c.
References bn_copy(), and core_get().
Referenced by ep2_curve_get_ord(), ep3_curve_get_ord(), ep3_mul_sim_lot(), ep4_curve_get_ord(), ep4_mul_sim_lot(), ep8_curve_get_ord(), ep8_mul_sim_lot(), ep_mul_combs_endom(), ep_mul_combs_plain(), ep_mul_fix_basic(), ep_mul_fix_combd(), ep_mul_fix_lwnaf(), ep_mul_glv_imp(), ep_mul_monty(), ep_mul_naf_imp(), ep_mul_pre_basic(), ep_mul_pre_combd(), ep_mul_pre_combs(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_mul_sim_endom(), ep_mul_sim_gen(), ep_mul_sim_inter(), ep_mul_sim_joint(), ep_mul_sim_lot_endom(), ep_mul_sim_trick(), ep_mul_slide(), ep_rand(), fp12_exp_cyc_sim(), pp_exp_k1(), pp_exp_k2(), pp_map_sim_tatep_k1(), pp_map_sim_tatep_k12(), pp_map_sim_tatep_k16(), pp_map_sim_tatep_k18(), pp_map_sim_tatep_k2(), pp_map_sim_weilp_k1(), pp_map_sim_weilp_k12(), pp_map_sim_weilp_k16(), pp_map_sim_weilp_k18(), pp_map_sim_weilp_k2(), pp_map_tatep_k1(), pp_map_tatep_k12(), pp_map_tatep_k16(), pp_map_tatep_k18(), pp_map_tatep_k2(), pp_map_weilp_k1(), pp_map_weilp_k12(), pp_map_weilp_k16(), pp_map_weilp_k18(), and pp_map_weilp_k2().
ep_curve_get_cof()
void ep_curve_get_cof (bn_t h)
Returns the cofactor of the binary elliptic curve.
Parameters
[out] n - the returned cofactor.
Definition at line 366 of file relic_ep_curve.c.
References bn_copy(), and core_get().
Referenced by ep_mul_cof(), and g1_is_valid().
ep_curve_get_iso()
iso_t ep_curve_get_iso (void)
Returns the isogeny map coefficients for use with the SSWU map.
Definition at line 387 of file relic_ep_curve.c.
References core_get(), and _ctx_t::ep_iso.
Referenced by ep_param_set_ctmap().
ep_curve_set_plain()
void ep_curve_set_plain (const fp_t a, const fp_t b, const ep_t g, const bn_t r, const bn_t h, int ctmap)
Configures a prime elliptic curve without endomorphisms by its coefficients and generator.
Parameters
[in] a - the a-coefficient of the curve.
[in] b - the b-coefficient of the curve.
[in] g - the generator.
[in] r - the order of the group of points.
[in] h - the cofactor of the group order.
[in] ctmap - true if this curve will use an isogeny for mapping.
Definition at line 397 of file relic_ep_curve.c.
References _ctx_t::beta, core_get(), ep_curve_set(), _ctx_t::ep_is_endom, _ctx_t::ep_is_pairf, _ctx_t::ep_is_super, fp_neg, fp_set_dig(), and fp_srt().
Referenced by ep_param_set().
ep_curve_set_super()
void ep_curve_set_super (const fp_t a, const fp_t b, const ep_t g, const bn_t r, const bn_t h, int ctmap)
Configures a supersingular prime elliptic curve by its coefficients and generator.
Parameters
[in] a - the a-coefficient of the curve.
[in] b - the b-coefficient of the curve.
[in] g - the generator.
[in] r - the order of the group of points.
[in] h - the cofactor of the group order.
[in] ctmap - true if this curve will use an isogeny for mapping.
Definition at line 421 of file relic_ep_curve.c.
References core_get(), ep_curve_set(), _ctx_t::ep_is_endom, and _ctx_t::ep_is_super.
Referenced by ep_param_set().
ep_curve_set_endom()
void ep_curve_set_endom (const fp_t a, const fp_t b, const ep_t g, const bn_t r, const bn_t h, const fp_t beta, const bn_t l, int ctmap)
Configures a prime elliptic curve with endomorphisms by its coefficients and generator.
Parameters
[in] a - the a-coefficient of the curve.
[in] b - the b-coefficient of the curve.
[in] g - the generator.
[in] r - the order of the group of points.
[in] beta - the constant associated with the endomorphism.
[in] l - the exponent corresponding to the endomorphism.
[in] h - the cofactor of the group order.
[in] ctmap - true if this curve will use an isogeny for mapping.
Definition at line 434 of file relic_ep_curve.c.
References _ctx_t::beta, bn_add(), bn_add_dig(), bn_bits(), bn_copy(), bn_dbl(), bn_div(), bn_free, bn_gcd_ext_mid(), bn_hlv(), bn_lsh(), bn_mul, bn_neg(), bn_new, bn_null, bn_sign(), bn_sub(), core_get(), ep_cmp(), ep_curve_set(), ep_free, _ctx_t::ep_is_endom, _ctx_t::ep_is_super, ep_mul_basic(), ep_new, ep_null, ep_psi(), _ctx_t::ep_v1, _ctx_t::ep_v2, ERR_CAUGHT, ERR_NO_VALID, fp_copy(), fp_is_zero(), fp_neg, fp_sub_dig(), RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_NEG, RLC_POS, RLC_THROW, and RLC_TRY.
Referenced by ep_param_set().
ep_curve_embed()
int ep_curve_embed (void)
Returns the embedding degree of the currently configured elliptic curve.
Definition at line 525 of file relic_ep_curve.c.
References core_get(), EP_AFG16, EP_B12, EP_B24, EP_B48, EP_BN, EP_FM16, EP_FM18, EP_GMT8, EP_K1, EP_K16, EP_K18, EP_SG18, EP_SG54, and EP_SS2.
Referenced by ep_curve_frdim(), fp12_exp_cyc_sim(), gt_exp(), and gt_exp_gls_naf().
ep_curve_frdim()
int ep_curve_frdim (void)
Returns the dimension of Frobenius expansions of the currently configured elliptic curve.
Definition at line 554 of file relic_ep_curve.c.
References ep_curve_embed().
Referenced by gt_exp(), and gt_exp_sec().
ep_param_set()
void ep_param_set (int param)
Configures a prime elliptic curve by its parameter identifier.
Parameters
- the parameter identifier.
Definition at line 908 of file relic_ep_param.c.
References AFG16_510, AFG16_766, AFG16_P510, AFG16_P766, ASSIGN, ASSIGNK, ASSIGNM, B12_1150, B12_377, B12_381, B12_383, B12_446, B12_455, B12_638, B12_P1150, B12_P377, B12_P381, B12_P383, B12_P446, B12_P455, B12_P638, B24_315, B24_317, B24_509, B24_P315, B24_P317, B24_P509, B48_575, B48_P575, BASIC, BN_158, BN_254, BN_256, BN_382, BN_446, BN_638, bn_add_dig(), bn_cmp_dig(), bn_div_dig(), bn_free, bn_is_zero(), bn_mul, bn_mul_dig(), bn_mxp, bn_neg(), bn_new, bn_null, BN_P158, BN_P254, BN_P256, BN_P382, BN_P446, BN_P638, bn_set_dig(), bn_sign(), bn_sqr, bn_sub(), bn_sub_dig(), bn_zero(), BSI_256, BSI_P256, core_get(), CURVE_1174, CURVE_22103, CURVE_25519, CURVE_383187, CURVE_4417, CURVE_511187, CURVE_67254, EP_AFG16, EP_B12, EP_B24, EP_B48, EP_BN, ep_curve_set_endom(), ep_curve_set_plain(), ep_curve_set_super(), EP_FM16, EP_FM18, ep_free, EP_GMT8, _ctx_t::ep_id, _ctx_t::ep_is_pairf, EP_K1, EP_K16, EP_K18, ep_new, ep_null, EP_SG18, EP_SG54, EP_SS2, ERR_CAUGHT, ERR_NO_VALID, FM16_765, FM16_P765, FM18_768, FM18_P768, fp_free, fp_hlv, fp_is_zero(), fp_neg, fp_new, fp_null, fp_prime_get_par(), fp_set_dig(), fp_srt(), fp_sub_dig(), fp_zero(), GMT8_544, GMT8_P544, K16_330, K16_766, K16_P330, K16_P766, K18_354, K18_508, K18_638, K18_P354, K18_P508, K18_P638, K1_3072, K1_P3072, NIST_192, NIST_224, NIST_256, NIST_384, NIST_521, NIST_P192, NIST_P224, NIST_P256, NIST_P384, NIST_P521, PRIME_22103, PRIME_22605, PRIME_25109, PRIME_25519, PRIME_382105, PRIME_383187, PRIME_511187, PRIME_H2ADC, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FP_BYTES, RLC_NEG, RLC_THROW, RLC_TRY, SECG_160, SECG_160D, SECG_192, SECG_224, SECG_256, SECG_K160, SECG_K192, SECG_K224, SECG_K256, SECG_P160, SG18_638, SG18_P638, SG54_569, SG54_P569, SM2_256, SM2_P256, SM9_256, SM9_P256, SS_1536, SS_P1536, and TWEEDLEDUM.
Referenced by ep_param_set_any_endom(), ep_param_set_any_pairf(), ep_param_set_any_plain(), and ep_param_set_any_super().
ep_param_set_any()
int ep_param_set_any (void)
Configures some set of curve parameters for the current security level.
Definition at line 1428 of file relic_ep_param.c.
References ep_param_set_any_endom(), ep_param_set_any_pairf(), ep_param_set_any_plain(), RLC_ERR, and RLC_OK.
ep_param_set_any_plain()
int ep_param_set_any_plain (void)
Configures some set of ordinary curve parameters for the current security level.
Returns
RLC_OK if there is a curve at this security level, RLC_ERR otherwise.
Definition at line 1442 of file relic_ep_param.c.
References CURVE_1174, CURVE_22103, CURVE_25519, CURVE_383187, CURVE_4417, CURVE_67254, ep_param_set(), NIST_P192, NIST_P224, NIST_P256, NIST_P384, NIST_P521, RLC_ERR, RLC_OK, and SECG_P160.
Referenced by ep_param_set_any().
ep_param_set_any_endom()
int ep_param_set_any_endom (void)
Configures some set of Koblitz curve parameters for the current security level.
Returns
RLC_OK if there is a curve at this security level, RLC_ERR otherwise.
Definition at line 1478 of file relic_ep_param.c.
References AFG16_P510, AFG16_P766, B12_P1150, B12_P377, B12_P381, B12_P383, B12_P446, B12_P455, B12_P638, B24_P315, B24_P317, B24_P509, BN_P158, BN_P254, BN_P382, BN_P446, ep_param_set(), FM16_P765, FM18_P768, GMT8_P544, K16_P330, K18_P354, K18_P508, K18_P638, RLC_ERR, RLC_OK, SECG_K160, SECG_K192, SECG_K224, SECG_K256, and TWEEDLEDUM.
Referenced by ep_param_set_any().
ep_param_set_any_super()
int ep_param_set_any_super (void)
Configures some set of supersingular curve parameters for the current security level.
Returns
RLC_OK if there is a curve at this security level, RLC_ERR otherwise.
Definition at line 1552 of file relic_ep_param.c.
References ep_param_set(), RLC_ERR, RLC_OK, and SS_P1536.
ep_param_set_any_pairf()
int ep_param_set_any_pairf (void)
Configures some set of pairing-friendly curve parameters for the current security level.
Returns
RLC_OK if there is a curve at this security level, RLC_ERR otherwise.
Definition at line 1565 of file relic_ep_param.c.
References AFG16_P510, AFG16_P766, B12_P1150, B12_P377, B12_P381, B12_P383, B12_P446, B12_P455, B12_P638, B24_P315, B24_P317, B24_P509, B48_P575, BN_P158, BN_P254, BN_P256, BN_P382, BN_P446, ep2_curve_set_twist(), ep3_curve_set_twist(), ep4_curve_set_twist(), ep8_curve_set_twist(), ep_param_set(), FM16_P765, FM18_P768, GMT8_P544, K16_P330, K18_P354, K18_P508, K18_P638, K1_P3072, pc_core_calc(), RLC_EP_DTYPE, RLC_EP_MTYPE, RLC_ERR, RLC_OK, SG54_P569, and SS_P1536.
Referenced by ep_param_set_any().
ep_param_get()
int ep_param_get (void)
Returns the parameter identifier of the currently configured prime elliptic curve.
Returns
the parameter identifier.
Definition at line 904 of file relic_ep_param.c.
References core_get(), and _ctx_t::ep_id.
Referenced by ep2_curve_set_twist(), ep3_curve_set_twist(), ep4_curve_set_twist(), ep8_curve_set_twist(), ep_param_level(), ep_param_print(), and pp_exp_k12().
ep_param_print()
void ep_param_print (void)
Prints the current configured prime elliptic curve.
Definition at line 1720 of file relic_ep_param.c.
References AFG16_P510, AFG16_P766, B12_P1150, B12_P377, B12_P381, B12_P383, B12_P446, B12_P455, B12_P638, B24_P315, B24_P317, B24_P509, B48_P575, BN_P158, BN_P254, BN_P256, BN_P382, BN_P446, BN_P638, BSI_P256, CURVE_1174, CURVE_25519, CURVE_383187, CURVE_511187, ep_param_get(), FM16_P765, FM18_P768, GMT8_P544, K16_P330, K16_P766, K18_P354, K18_P508, K18_P638, K1_P3072, NIST_P192, NIST_P224, NIST_P256, NIST_P384, NIST_P521, SECG_K160, SECG_K192, SECG_K224, SECG_K256, SECG_P160, SG18_P638, SG54_P569, SM2_P256, SM9_P256, SS_P1536, TWEEDLEDUM, and util_banner.
ep_param_level()
int ep_param_level (void)
Returns the current security level.
Definition at line 1872 of file relic_ep_param.c.
References AFG16_P510, B12_P1150, B12_P377, B12_P381, B12_P383, B12_P446, B12_P455, B12_P638, B24_P315, B24_P317, B24_P509, BN_P158, BN_P254, BN_P256, BN_P382, BN_P446, BN_P638, CURVE_25519, ep_param_get(), FM16_P765, FM18_P768, GMT8_P544, K16_P330, K16_P766, K18_P354, K18_P508, K18_P638, NIST_P192, NIST_P224, NIST_P256, NIST_P384, NIST_P521, SECG_K160, SECG_K192, SECG_K224, SECG_K256, SECG_P160, SM2_P256, SM9_P256, SS_P1536, and TWEEDLEDUM.
Referenced by ep2_map_from_field(), ep2_map_sswum(), ep2_map_swift(), ep3_map(), ep4_map(), ep8_map(), ep_map_basic(), ep_map_sswum(), ep_map_sswum_impl(), and ep_map_swift().
ep_is_infty()
int ep_is_infty (const ep_t p)
Tests if a point on a prime elliptic curve is at the infinity.
Parameters
[in] p - the point to test.
Returns
1 if the point is at infinity, 0 otherise.
Definition at line 39 of file relic_ep_util.c.
References fp_is_zero().
Referenced by ep_add_basic(), ep_add_jacob(), ep_add_projc(), ep_add_slp_basic(), ep_cmp(), ep_dbl_basic(), ep_dbl_jacob(), ep_dbl_projc(), ep_dbl_slp_basic(), ep_mul_basic(), ep_mul_dig(), ep_mul_lwnaf(), ep_mul_lwreg(), ep_mul_monty(), ep_mul_sim_gen(), ep_mul_sim_inter(), ep_mul_sim_joint(), ep_mul_sim_trick(), ep_mul_slide(), ep_neg(), ep_norm(), ep_norm_sim(), ep_on_curve(), ep_psi(), ep_size_bin(), ep_write_bin(), pp_map_k24(), pp_map_k48(), pp_map_k54(), pp_map_oatep_k12(), pp_map_oatep_k16(), pp_map_oatep_k18(), pp_map_oatep_k8(), pp_map_sim_k24(), pp_map_sim_k48(), pp_map_sim_oatep_k12(), pp_map_sim_oatep_k16(), pp_map_sim_oatep_k18(), pp_map_sim_oatep_k8(), pp_map_sim_tatep_k1(), pp_map_sim_tatep_k12(), pp_map_sim_tatep_k16(), pp_map_sim_tatep_k18(), pp_map_sim_tatep_k2(), pp_map_sim_weilp_k1(), pp_map_sim_weilp_k12(), pp_map_sim_weilp_k16(), pp_map_sim_weilp_k18(), pp_map_sim_weilp_k2(), pp_map_tatep_k1(), pp_map_tatep_k12(), pp_map_tatep_k16(), pp_map_tatep_k18(), pp_map_tatep_k2(), pp_map_weilp_k1(), pp_map_weilp_k12(), pp_map_weilp_k16(), pp_map_weilp_k18(), and pp_map_weilp_k2().
ep_set_infty()
void ep_set_infty (ep_t p)
Assigns a prime elliptic curve point to the point at infinity.
Parameters
[out] p - the point to assign.
Definition at line 43 of file relic_ep_util.c.
References BASIC, and fp_zero().
Referenced by ep_curve_init(), ep_dbl_basic(), ep_dbl_jacob(), ep_dbl_projc(), ep_dbl_slp_basic(), ep_map_swift_impl(), ep_mul_basic(), ep_mul_combs_endom(), ep_mul_dig(), ep_mul_fix_basic(), ep_mul_fix_combd(), ep_mul_fix_combs(), ep_mul_fix_lwnaf(), ep_mul_gen(), ep_mul_glv_imp(), ep_mul_lwnaf(), ep_mul_lwreg(), ep_mul_monty(), ep_mul_naf_imp(), ep_mul_pre_combd(), ep_mul_pre_combs(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_mul_sim_dig(), ep_mul_sim_endom(), ep_mul_sim_joint(), ep_mul_sim_lot(), ep_mul_sim_lot_endom(), ep_mul_sim_lot_plain(), ep_mul_sim_plain(), ep_mul_sim_trick(), ep_mul_slide(), ep_neg(), ep_norm(), ep_psi(), ep_read_bin(), and ep_sub().
ep_copy()
void ep_copy (ep_t r, const ep_t p)
Copies the second argument to the first argument.
Parameters
[out] q - the result.
[in] p - the prime elliptic curve point to copy.
Definition at line 50 of file relic_ep_util.c.
References fp_copy().
Referenced by ep_add_basic(), ep_add_jacob(), ep_add_projc(), ep_add_slp_basic(), ep_blind(), ep_cmp(), ep_curve_get_gen(), ep_mul_combs_endom(), ep_mul_combs_plain(), ep_mul_fix_plain(), ep_mul_pre_basic(), ep_mul_pre_combd(), ep_mul_pre_combs(), ep_mul_sim_joint(), ep_mul_sim_lot_endom(), ep_mul_sim_trick(), ep_mul_slide(), ep_norm(), ep_norm_imp(), ep_psi(), ep_tab(), g1_is_valid(), pp_add_k2_basic(), pp_dbl_k2_basic(), pp_mil_k1(), pp_mil_k2(), pp_mil_lit_k12(), pp_mil_lit_k16(), pp_mil_lit_k18(), and pp_mil_lit_k2().
ep_cmp()
int ep_cmp (const ep_t p, const ep_t q)
Compares two prime elliptic curve points.
Parameters
[in] p - the first prime elliptic curve point.
[in] q - the second prime elliptic curve point.
Returns
RLC_EQ if p == q and RLC_NE if p != q.
Definition at line 38 of file relic_ep_cmp.c.
References ep_copy(), ep_free, ep_is_infty(), ep_new, ep_null, ERR_CAUGHT, fp_cmp(), fp_mul, fp_sqr, JACOB, PROJC, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_NE, RLC_THROW, and RLC_TRY.
Referenced by ep_curve_set_endom().
ep_rand()
void ep_rand (ep_t p)
Assigns a random value to a prime elliptic curve point.
Parameters
[out] p - the prime elliptic curve point to assign.
Definition at line 57 of file relic_ep_util.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), ep_curve_get_ord(), ep_mul_gen(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep_blind()
void ep_blind (ep_t r, const ep_t p)
Randomizes coordinates of a prime elliptic curve point.
Parameters
[out] r - the blinded prime elliptic curve point.
[in] p - the prime elliptic curve point to blind.
Definition at line 79 of file relic_ep_util.c.
References ep_copy(), ERR_CAUGHT, fp_free, fp_mul, fp_new, fp_null, fp_rand(), fp_sqr, JACOB, PROJC, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep_mul_monty().
ep_rhs()
void ep_rhs (fp_t rhs, const fp_t x)
Computes the right-hand side of the elliptic curve equation at the x-coordinate of a certain prime elliptic curve point.
Parameters
[out] rhs - the result.
[in] x - the x-coordinate of the point.
Definition at line 110 of file relic_ep_util.c.
References ep_curve_get_a(), ep_curve_get_b(), ep_curve_opt_a(), ep_curve_opt_b(), ERR_CAUGHT, fp_add, fp_add_dig(), fp_copy(), fp_free, fp_mul, fp_new, fp_null, fp_sqr, fp_sub_dig(), RLC_CATCH_ANY, RLC_FINALLY, RLC_MIN3, RLC_ONE, RLC_THROW, RLC_TINY, RLC_TRY, RLC_TWO, and RLC_ZERO.
Referenced by ep_map_basic_impl(), ep_map_swift_impl(), ep_on_curve(), and ep_upk().
ep_on_curve()
int ep_on_curve (const ep_t p)
Tests if a point is in the curve.
Parameters
[in] p - the point to test.
Definition at line 178 of file relic_ep_util.c.
References ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ep_rhs(), ERR_CAUGHT, fp_cmp(), fp_sqr, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep_read_bin().
ep_tab()
void ep_tab (ep_t * t, const ep_t p, int w)
Builds a precomputation table for multiplying a random prime elliptic point.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
[in] w - the window width.
Definition at line 199 of file relic_ep_util.c.
References ep_add, ep_copy(), ep_dbl, ep_norm(), and ep_norm_sim().
Referenced by ep_mul_glv_imp(), ep_mul_naf_imp(), ep_mul_pre_lwnaf(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_mul_sim_endom(), and ep_mul_sim_plain().
ep_print()
void ep_print (const ep_t p)
Prints a prime elliptic curve point.
Parameters
[in] p - the prime elliptic curve point to print.
Definition at line 220 of file relic_ep_util.c.
References fp_print().
ep_size_bin()
size_t ep_size_bin (const ep_t a, int pack)
Returns the number of bytes necessary to store a prime elliptic curve point with optional point compression.
Parameters
[in] a - the prime field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 226 of file relic_ep_util.c.
References ep_is_infty(), and RLC_FP_BYTES.
ep_read_bin()
void ep_read_bin (ep_t a, const uint8_t * bin, size_t len)
Reads a prime elliptic curve point from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_VALID - if the encoded point is invalid.
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 241 of file relic_ep_util.c.
References BASIC, ep_on_curve(), ep_set_infty(), ep_upk(), ERR_NO_BUFFER, ERR_NO_VALID, fp_read_bin(), fp_set_bit(), fp_set_dig(), fp_zero(), RLC_FP_BYTES, and RLC_THROW.
ep_write_bin()
void ep_write_bin (uint8_t * bin, size_t len, const ep_t a, int pack)
Writes a prime elliptic curve point to a byte vector in big-endian format with optional point compression.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the prime elliptic curve point to write.
[in] pack - the flag to indicate point compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 291 of file relic_ep_util.c.
References ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ep_pck(), ERR_CAUGHT, ERR_NO_BUFFER, fp_get_bit(), fp_write_bin(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.
ep_neg()
void ep_neg (ep_t r, const ep_t p)
Negates a prime elliptic curve point.
Parameters
[out] r - the result.
[in] p - the point to negate.
Definition at line 38 of file relic_ep_neg.c.
References ep_is_infty(), ep_set_infty(), fp_copy(), and fp_neg.
Referenced by ep_mul_basic(), ep_mul_cof(), ep_mul_fix_plain(), ep_mul_glv_imp(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_mul_sim_endom(), ep_mul_sim_joint(), ep_mul_sim_lot_endom(), ep_mul_sim_lot_plain(), ep_sub(), pp_fin_k16_oatep(), pp_fin_k18_oatep(), pp_mil_k12(), pp_mil_k16(), pp_mil_k18(), pp_mil_k2(), pp_mil_k24(), pp_mil_k48(), pp_mil_k54(), pp_mil_k8(), and pp_mil_lit_k2().
ep_add_basic()
void ep_add_basic (ep_t r, const ep_t p, const ep_t q)
Adds two prime elliptic curve points represented in affine coordinates.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 108 of file relic_ep_add.c.
References ep_copy(), and ep_is_infty().
ep_add_slp_basic()
void ep_add_slp_basic (ep_t r, fp_t s, const ep_t p, const ep_t q)
Adds two prime elliptic curve points represented in affine coordinates and returns the computed slope.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 122 of file relic_ep_add.c.
References ep_copy(), and ep_is_infty().
Referenced by pp_add_k1_basic(), and pp_add_k2_basic().
ep_add_projc()
void ep_add_projc (ep_t r, const ep_t p, const ep_t q)
Adds two prime elliptic curve points represented in projective coordinates.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 140 of file relic_ep_add.c.
References ep_copy(), and ep_is_infty().
ep_add_jacob()
void ep_add_jacob (ep_t r, const ep_t p, const ep_t q)
Adds two prime elliptic curve points represented in Jacobian coordinates.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 158 of file relic_ep_add.c.
References ep_copy(), and ep_is_infty().
ep_sub()
void ep_sub (ep_t r, const ep_t p, const ep_t q)
Subtracts a prime elliptic curve point from another.
Parameters
[out] r - the result.
[in] p - the first point.
[in] q - the second point.
Definition at line 174 of file relic_ep_add.c.
References ep_add, ep_free, ep_neg(), ep_new, ep_null, ep_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep_mul_basic(), ep_mul_cof(), ep_mul_combs_endom(), ep_mul_dig(), ep_mul_fix_plain(), ep_mul_glv_imp(), ep_mul_naf_imp(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_mul_sim_endom(), ep_mul_sim_joint(), ep_mul_sim_lot_endom(), ep_mul_sim_lot_plain(), and ep_mul_sim_plain().
ep_dbl_basic()
void ep_dbl_basic (ep_t r, const ep_t p)
Doubles a prime elliptic curve point represented in affine coordinates.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 85 of file relic_ep_dbl.c.
References ep_is_infty(), and ep_set_infty().
ep_dbl_slp_basic()
void ep_dbl_slp_basic (ep_t r, fp_t s, const ep_t p)
Doubles a prime elliptic curve point represented in affine coordinates and returns the computed slope.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the point to double.
Definition at line 93 of file relic_ep_dbl.c.
References ep_is_infty(), and ep_set_infty().
Referenced by pp_dbl_k1_basic(), and pp_dbl_k2_basic().
ep_dbl_projc()
void ep_dbl_projc (ep_t r, const ep_t p)
Doubles a prime elliptic curve point represented in projective coordinates.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 106 of file relic_ep_dbl.c.
References ep_is_infty(), and ep_set_infty().
ep_dbl_jacob()
void ep_dbl_jacob (ep_t r, const ep_t p)
Doubles a prime elliptic curve point represented in Jacobian projective coordinates.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 119 of file relic_ep_dbl.c.
References ep_is_infty(), and ep_set_infty().
ep_psi()
void ep_psi (ep_t r, const ep_t p)
Computes the endomorphism map of a prime elliptic curve point. Computes R = \psi(P).
Parameters
[out] r - the result.
[in] p - the point.
Definition at line 39 of file relic_ep_psi.c.
References ep_copy(), ep_curve_get_beta(), ep_curve_opt_a(), ep_is_infty(), ep_set_infty(), fp_mul, fp_neg, and RLC_ZERO.
Referenced by ep_curve_set_endom(), ep_mul_cof(), ep_mul_combs_endom(), ep_mul_glv_imp(), ep_mul_reg_glv(), ep_mul_sim_endom(), ep_mul_sim_lot_endom(), and g1_is_valid().
ep_mul_basic()
void ep_mul_basic (ep_t r, const ep_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the binary method. There is no restriction on the scalar.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 440 of file relic_ep_mul.c.
References bn_bits(), bn_is_zero(), bn_rec_naf(), bn_sign(), ep_add, ep_dbl, ep_free, ep_is_infty(), ep_mul_dig(), ep_neg(), ep_new, ep_norm(), ep_null, ep_set_infty(), ep_sub(), ERR_CAUGHT, ERR_NO_BUFFER, RLC_ALLOCA, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by ep_curve_set_endom(), and ep_mul_cof().
ep_mul_slide()
void ep_mul_slide (ep_t r, const ep_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the sliding window method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 498 of file relic_ep_mul.c.
References bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, bn_rec_slw(), ep_add, ep_copy(), ep_curve_get_ord(), ep_dbl, ep_free, ep_is_infty(), ep_new, ep_norm(), ep_norm_sim(), ep_null, ep_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_THROW, RLC_TRY, RLC_WIDTH, and util_bits_dig().
ep_mul_monty()
void ep_mul_monty (ep_t r, const ep_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the constant-time Montgomery ladder point multiplication method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 574 of file relic_ep_mul.c.
References bn_abs(), bn_add(), bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_new, bn_null, dv_swap_sec(), ep_add, ep_blind(), ep_curve_get_ord(), ep_dbl, ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ep_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_MAX, RLC_SEL, RLC_THROW, and RLC_TRY.
ep_mul_lwnaf()
void ep_mul_lwnaf (ep_t r, const ep_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the w-NAF method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 644 of file relic_ep_mul.c.
References bn_is_zero(), ep_curve_is_endom(), ep_is_infty(), ep_mul_glv_imp(), ep_mul_naf_imp(), and ep_set_infty().
ep_mul_lwreg()
void ep_mul_lwreg (ep_t r, const ep_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using a regular method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 666 of file relic_ep_mul.c.
References bn_is_zero(), ep_curve_is_endom(), ep_is_infty(), ep_mul_reg_glv(), ep_mul_reg_imp(), and ep_set_infty().
ep_mul_gen()
void ep_mul_gen (ep_t r, const bn_t k)
Multiplies the generator of a prime elliptic curve by an integer.
Parameters
[out] r - the result.
[in] k - the integer.
Definition at line 684 of file relic_ep_mul.c.
References bn_is_zero(), ep_curve_get_gen(), ep_curve_get_tab(), ep_free, ep_mul, ep_mul_fix, ep_new, ep_null, ep_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep_mul_sim_gen(), and ep_rand().
ep_mul_dig()
void ep_mul_dig (ep_t r, const ep_t p, dig_t k)
Multiplies a prime elliptic point by a small positive integer.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 711 of file relic_ep_mul.c.
References bn_free, bn_new, bn_null, bn_rec_naf(), bn_set_dig(), ep_add, ep_dbl, ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ep_set_infty(), ep_sub(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep_mul_basic(), and ep_mul_cof().
ep_mul_cof()
void ep_mul_cof (ep_t r, const ep_t p)
Multiplies a point in an elliptic curve over by the curve cofactor. In short, it takes a point in the curve to the large prime-order subgroup.
Parameters
[out] R - the result.
[in] P - the point to multiply.
Definition at line 40 of file relic_ep_mul_cof.c.
References bn_add(), bn_add_dig(), bn_div_dig(), bn_free, bn_hlv(), bn_is_even(), bn_mul, bn_mul_dig(), bn_neg(), bn_new, bn_null, bn_sqr, bn_sub_dig(), ep_add, EP_AFG16, EP_B12, EP_B24, EP_B48, EP_BN, ep_curve_get_cof(), ep_curve_is_pairf(), ep_dbl, EP_FM16, EP_FM18, ep_free, EP_K16, EP_K18, ep_mul_basic(), ep_mul_big, ep_mul_dig(), ep_neg(), ep_new, ep_norm(), ep_null, ep_psi(), EP_SG18, ep_sub(), ERR_CAUGHT, fp_prime_get_par(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep_map_basic_impl(), ep_map_sswum_impl(), and ep_map_swift_impl().
ep_mul_pre_basic()
void ep_mul_pre_basic (ep_t * t, const ep_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the binary method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 270 of file relic_ep_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, ep_copy(), ep_curve_get_ord(), ep_dbl, ep_norm_sim(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep_mul_pre_yaowi()
void ep_mul_pre_yaowi (ep_t * t, const ep_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using Yao's windowing method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
ep_mul_pre_nafwi()
void ep_mul_pre_nafwi (ep_t * t, const ep_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the NAF windowing method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
ep_mul_pre_combs()
void ep_mul_pre_combs (ep_t * t, const ep_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the single-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 332 of file relic_ep_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, ep_add, ep_copy(), ep_curve_get_ord(), ep_curve_is_endom(), ep_dbl, ep_norm(), ep_norm_sim(), ep_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_CEIL, RLC_DEPTH, RLC_EP_TABLE_COMBS, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep_mul_pre_combd()
void ep_mul_pre_combd (ep_t * t, const ep_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the double-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 397 of file relic_ep_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, ep_add, ep_copy(), ep_curve_get_ord(), ep_dbl, ep_norm(), ep_norm_sim(), ep_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_CEIL, RLC_DEPTH, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep_mul_pre_lwnaf()
void ep_mul_pre_lwnaf (ep_t * t, const ep_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the w-(T)NAF method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 508 of file relic_ep_mul_fix.c.
References ep_tab(), and RLC_DEPTH.
ep_mul_fix_basic()
void ep_mul_fix_basic (ep_t r, const ep_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the binary method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 295 of file relic_ep_mul_fix.c.
References bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_new, bn_null, ep_add, ep_curve_get_ord(), ep_norm(), ep_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep_mul_fix_yaowi()
void ep_mul_fix_yaowi (ep_t r, const ep_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and Yao's windowing method
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
ep_mul_fix_nafwi()
void ep_mul_fix_nafwi (ep_t r, const ep_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the w-(T)NAF method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
ep_mul_fix_combs()
void ep_mul_fix_combs (ep_t r, const ep_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the single-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 376 of file relic_ep_mul_fix.c.
References bn_is_zero(), ep_curve_is_endom(), ep_mul_combs_endom(), ep_mul_combs_plain(), and ep_set_infty().
ep_mul_fix_combd()
void ep_mul_fix_combd (ep_t r, const ep_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the double-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 444 of file relic_ep_mul_fix.c.
References bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_new, bn_null, ep_add, ep_curve_get_ord(), ep_dbl, ep_norm(), ep_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_CEIL, RLC_DEPTH, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep_mul_fix_lwnaf()
void ep_mul_fix_lwnaf (ep_t r, const ep_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the w-(T)NAF method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 512 of file relic_ep_mul_fix.c.
References bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, ep_curve_get_ord(), ep_mul_fix_plain(), ep_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep_mul_sim_basic()
void ep_mul_sim_basic (ep_t r, const ep_t p, const bn_t k, const ep_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using scalar multiplication and point addition.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 654 of file relic_ep_mul_sim.c.
References ep_add, ep_free, ep_mul, ep_new, ep_norm(), ep_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep_mul_sim_trick()
void ep_mul_sim_trick (ep_t r, const ep_t p, const bn_t k, const ep_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using shamir's trick.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 679 of file relic_ep_mul_sim.c.
References bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, bn_rec_win(), ep_add, ep_copy(), ep_curve_get_ord(), ep_dbl, ep_free, ep_is_infty(), ep_mul, ep_new, ep_norm(), ep_norm_sim(), ep_null, ep_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_CEIL, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_THROW, RLC_TRY, and RLC_WIDTH.
ep_mul_sim_inter()
void ep_mul_sim_inter (ep_t r, const ep_t p, const bn_t k, const ep_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using interleaving of NAFs.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 773 of file relic_ep_mul_sim.c.
References bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, ep_curve_get_ord(), ep_curve_is_endom(), ep_is_infty(), ep_mul, ep_mul_sim_endom(), ep_mul_sim_plain(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep_mul_sim_joint()
void ep_mul_sim_joint (ep_t r, const ep_t p, const bn_t k, const ep_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using Solinas' Joint Sparse Form.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 828 of file relic_ep_mul_sim.c.
References bn_bits(), bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, bn_rec_jsf(), bn_sign(), ep_add, ep_copy(), ep_curve_get_ord(), ep_dbl, ep_free, ep_is_infty(), ep_mul, ep_neg(), ep_new, ep_norm(), ep_norm_sim(), ep_null, ep_set_infty(), ep_sub(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, and RLC_TRY.
ep_mul_sim_lot()
void ep_mul_sim_lot (ep_t r, const ep_t p[], const bn_t k[], int n)
Multiplies and adds multiple elliptic curve points simultaneously. Computes R = \Sum_i=0..n [k_i]P_i.
Parameters
[out] r - the result.
[out] p - the elements to multiply.
[out] k - the integer scalars.
[out] n - the number of elements to multiply.
Definition at line 1017 of file relic_ep_mul_sim.c.
References ep_curve_is_endom(), ep_mul_sim_lot_endom(), ep_mul_sim_lot_plain(), and ep_set_infty().
ep_mul_sim_gen()
void ep_mul_sim_gen (ep_t r, const bn_t k, const ep_t q, const bn_t m)
Multiplies and adds the generator and a prime elliptic curve point simultaneously. Computes R = [k]G + [m]Q.
Parameters
[out] r - the result.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer.
Definition at line 918 of file relic_ep_mul_sim.c.
References bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, ep_curve_get_gen(), ep_curve_get_ord(), ep_curve_get_tab(), ep_curve_is_endom(), ep_free, ep_is_infty(), ep_mul, ep_mul_gen(), ep_mul_sim, ep_mul_sim_endom(), ep_mul_sim_plain(), ep_new, ep_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep_mul_sim_dig()
void ep_mul_sim_dig (ep_t r, const ep_t p[], const dig_t k[], int n)
Multiplies prime elliptic curve points by small scalars. Computes R = \Sum_i=0..n [k_i]P_i.
Parameters
[out] r - the result.
[in] p - the points to multiply.
[in] k - the small scalars.
[in] n - the number of points to multiply.
Definition at line 983 of file relic_ep_mul_sim.c.
References ep_add, ep_dbl, ep_free, ep_new, ep_norm(), ep_null, ep_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_MAX, RLC_THROW, RLC_TRY, and util_bits_dig().
ep_norm()
void ep_norm (ep_t r, const ep_t p)
Converts a point to affine coordinates.
Parameters
[out] r - the result.
[in] p - the point to convert.
Definition at line 96 of file relic_ep_norm.c.
References BASIC, ep_copy(), ep_is_infty(), ep_norm_imp(), and ep_set_infty().
Referenced by ep_curve_set(), ep_map_sswum_impl(), ep_mul_basic(), ep_mul_cof(), ep_mul_combs_endom(), ep_mul_combs_plain(), ep_mul_dig(), ep_mul_fix_basic(), ep_mul_fix_combd(), ep_mul_fix_plain(), ep_mul_glv_imp(), ep_mul_monty(), ep_mul_naf_imp(), ep_mul_pre_combd(), ep_mul_pre_combs(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_mul_sim_basic(), ep_mul_sim_dig(), ep_mul_sim_endom(), ep_mul_sim_joint(), ep_mul_sim_lot_endom(), ep_mul_sim_lot_plain(), ep_mul_sim_plain(), ep_mul_sim_trick(), ep_mul_slide(), ep_on_curve(), ep_tab(), ep_write_bin(), pp_map_k24(), pp_map_k48(), pp_map_oatep_k12(), pp_map_oatep_k16(), pp_map_oatep_k18(), pp_map_oatep_k8(), pp_map_sim_k24(), pp_map_sim_k48(), pp_map_sim_oatep_k12(), pp_map_sim_oatep_k16(), pp_map_sim_oatep_k18(), pp_map_sim_oatep_k8(), pp_map_sim_tatep_k1(), pp_map_sim_tatep_k12(), pp_map_sim_tatep_k16(), pp_map_sim_tatep_k18(), pp_map_sim_tatep_k2(), pp_map_sim_weilp_k1(), pp_map_sim_weilp_k12(), pp_map_sim_weilp_k16(), pp_map_sim_weilp_k18(), pp_map_sim_weilp_k2(), pp_map_tatep_k1(), pp_map_tatep_k12(), pp_map_tatep_k16(), pp_map_tatep_k18(), pp_map_tatep_k2(), pp_map_weilp_k1(), pp_map_weilp_k12(), pp_map_weilp_k16(), pp_map_weilp_k18(), pp_map_weilp_k2(), pp_norm_k1(), and pp_norm_k2().
ep_norm_sim()
void ep_norm_sim (ep_t * r, const ep_t * t, int n)
Converts multiple points to affine coordinates.
Parameters
[out] r - the result.
[in] t - the points to convert.
[in] n - the number of points.
Definition at line 112 of file relic_ep_norm.c.
References ep_is_infty(), ep_norm_imp(), ERR_CAUGHT, ERR_NO_MEMORY, fp_copy(), fp_free, fp_inv_sim(), fp_new, fp_null, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by ep_mul_pre_basic(), ep_mul_pre_combd(), ep_mul_pre_combs(), ep_mul_sim_joint(), ep_mul_sim_trick(), ep_mul_slide(), and ep_tab().
ep_map_basic()
void ep_map_basic (ep_t p, const uint8_t * msg, size_t len)
Maps a byte array to a point in a prime elliptic curve using the hash and increment approach.
Parameters
[out] p - the result.
[in] msg - the byte array to map.
[in] len - the array length in bytes.
Definition at line 442 of file relic_ep_map.c.
References ep_map_basic_impl(), ep_param_level(), ERR_CAUGHT, FP_PRIME, MAP_STRING, md_xmd, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
ep_map_sswum()
void ep_map_sswum (ep_t p, const uint8_t * msg, size_t len)
Maps a byte array to a point in a prime elliptic curve using the (Simplified) Shallue-van de Woestijne-Ulas map.
Parameters
[out] p - the result.
[in] msg - the byte array to map.
[in] len - the array length in bytes.
Definition at line 463 of file relic_ep_map.c.
References ep_curve_is_ctmap(), ep_curve_opt_a(), ep_curve_opt_b(), ep_map_sswum_impl(), ep_param_level(), ERR_CAUGHT, FP_PRIME, MAP_STRING, md_xmd, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, RLC_TRY, and RLC_ZERO.
ep_map_swift()
void ep_map_swift (ep_t p, const uint8_t * msg, size_t len)
Maps a byte array to a point in a prime elliptic curve using the SwiftEC approach.
Parameters
[out] p - the result.
[in] msg - the byte array to map.
[in] len - the array length in bytes.
Definition at line 494 of file relic_ep_map.c.
References core_get(), ep_curve_is_super(), ep_map_swift_impl(), ep_param_level(), ERR_CAUGHT, ERR_NO_CONFIG, FP_PRIME, MAP_STRING, md_xmd, _ctx_t::mod18, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
ep_map_rnd()
void ep_map_rnd (ep_t p, const uint8_t * uniform_bytes, size_t len)
Maps a random byte array to a point in a prime elliptic curve.
Parameters
[out] p - the result.
[in] uniform_bytes - the random byte array to map.
[in] len - the array length in bytes.
Definition at line 527 of file relic_ep_map.c.
References ep_curve_is_ctmap(), ep_curve_opt_a(), ep_curve_opt_b(), ep_map_basic_impl(), ep_map_sswum_impl(), ep_map_swift_impl(), and RLC_ZERO.
ep_pck()
void ep_pck (ep_t r, const ep_t p)
Compresses a point.
Parameters
[out] r - the result.
[in] p - the point to compress.
Definition at line 38 of file relic_ep_pck.c.
References BASIC, bn_cmp(), bn_free, bn_hlv(), bn_new, bn_null, dv_copy(), ep_curve_is_pairf(), ERR_CAUGHT, fp_copy(), fp_get_bit(), fp_prime_back(), fp_prime_get(), fp_set_bit(), fp_set_dig(), fp_zero(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_GT, RLC_THROW, and RLC_TRY.
Referenced by ep_write_bin().
ep_upk()
int ep_upk (ep_t r, const ep_t p)
Decompresses a point.
Parameters
[out] r - the result.
[in] p - the point to decompress.
Returns
a boolean value indicating if the decompression was successful.
Definition at line 77 of file relic_ep_pck.c.
References BASIC, bn_cmp(), bn_free, bn_hlv(), bn_new, bn_null, dv_copy(), ep_curve_is_pairf(), ep_rhs(), ERR_CAUGHT, fp_copy(), fp_free, fp_get_bit(), fp_neg, fp_new, fp_null, fp_prime_back(), fp_prime_get(), fp_set_dig(), fp_srt(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_GT, RLC_THROW, and RLC_TRY.
Referenced by ep_read_bin().