RELIC: src/fpx/relic_fpx_inv.c File Reference
relic_fpx_inv.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fpx_low.h"
Functions
void fp2_inv (fp2_t c, const fp2_t a)
void fp2_inv_cyc (fp2_t c, const fp2_t a)
void fp2_inv_sim (fp2_t *c, const fp2_t *a, int n)
void fp3_inv (fp3_t c, const fp3_t a)
void fp3_inv_sim (fp3_t *c, const fp3_t *a, int n)
void fp4_inv_cyc (fp4_t c, const fp4_t a)
void fp4_inv (fp4_t c, const fp4_t a)
void fp4_inv_sim (fp4_t *c, const fp4_t *a, int n)
void fp6_inv (fp6_t c, const fp6_t a)
void fp8_inv_cyc (fp8_t c, const fp8_t a)
void fp8_inv (fp8_t c, const fp8_t a)
void fp8_inv_sim (fp8_t *c, const fp8_t *a, int n)
void fp9_inv (fp9_t c, const fp9_t a)
void fp9_inv_sim (fp9_t *c, const fp9_t *a, int n)
void fp12_inv (fp12_t c, const fp12_t a)
void fp12_inv_cyc (fp12_t c, const fp12_t a)
void fp16_inv_cyc (fp16_t c, const fp16_t a)
void fp16_inv (fp16_t c, const fp16_t a)
void fp16_inv_sim (fp16_t *c, const fp16_t *a, int n)
void fp18_inv (fp18_t c, const fp18_t a)
void fp18_inv_cyc (fp18_t c, const fp18_t a)
void fp24_inv (fp24_t c, const fp24_t a)
void fp24_inv_cyc (fp24_t c, const fp24_t a)
void fp48_inv (fp48_t c, const fp48_t a)
void fp48_inv_cyc (fp48_t c, const fp48_t a)
void fp54_inv (fp54_t c, const fp54_t a)
void fp54_inv_cyc (fp54_t c, const fp54_t a)
Detailed Description
Implementation of inversion in extensions defined over prime fields.
Definition in file relic_fpx_inv.c.
Function Documentation
fp2_inv()
void fp2_inv (fp2_t c, const fp2_t a)
Inverts a quadratic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to invert.
Definition at line 39 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp_add, fp_dbl, fp_free, fp_inv, fp_mul, fp_mul_dig(), fp_neg, fp_new, fp_null, fp_prime_get_qnr(), fp_sqr, fp_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep2_curve_set_map(), ep2_curve_set_twist(), ep2_map_swift(), ep2_norm_imp(), fp12_back_cyc(), fp2_conv_cyc(), fp2_exp(), fp2_inv_sim(), fp4_inv(), fp4_srt(), fp6_inv(), pp_map_sim_weilp_k2(), pp_map_weilp_k2(), pp_norm_k12(), and pp_norm_k8().
fp2_inv_cyc()
void fp2_inv_cyc (fp2_t c, const fp2_t a)
Computes the inverse of a cyclotomic quadratic extension field element.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to invert.
Definition at line 92 of file relic_fpx_inv.c.
References fp_copy(), and fp_neg.
Referenced by fp2_conv_cyc(), fp2_exp_cyc(), fp2_exp_cyc_sim(), fp2_test_cyc(), pp_map_sim_weilp_k2(), and pp_map_weilp_k2().
fp2_inv_sim()
void fp2_inv_sim (fp2_t * c, const fp2_t * a, int n)
Inverts multiple quadratic extension field elements simultaneously.
Parameters
[out] c - the result.
[in] a - the quadratic extension field elements to invert.
[in] n - the number of elements.
Definition at line 97 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp2_copy(), fp2_free, fp2_inv(), fp2_mul, fp2_new, fp2_null, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by ep2_map_swift(), ep2_norm_sim(), and fp12_back_cyc_sim().
fp3_inv()
void fp3_inv (fp3_t c, const fp3_t a)
Inverts a cubic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the cubic extension field element to invert.
Definition at line 140 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp_add, fp_copy(), fp_free, fp_inv, fp_mul, fp_new, fp_null, fp_prime_get_cnr(), fp_sqr, fp_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep3_curve_set_twist(), ep3_map(), ep3_norm_imp(), fp18_back_cyc(), fp3_exp(), fp3_inv_sim(), fp9_inv(), and pp_norm_k18().
fp3_inv_sim()
void fp3_inv_sim (fp3_t * c, const fp3_t * a, int n)
Inverts multiple cubic extension field elements simultaneously.
Parameters
[out] c - the result.
[in] a - the cubic extension field elements to invert.
[in] n - the number of elements.
Definition at line 223 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp3_copy(), fp3_free, fp3_inv(), fp3_mul, fp3_new, fp3_null, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by ep3_norm_sim(), and fp18_back_cyc_sim().
fp4_inv_cyc()
void fp4_inv_cyc (fp4_t c, const fp4_t a)
Computes the inverse of a cyclotomic quartic extension field element.
For cyclotomic elements, this is equivalent to computing the conjugate. A cyclotomic element is one previously raised to the (p^2 - 1)-th power.
Parameters
[out] c - the result.
[in] a - the quartic extension field element to invert.
Definition at line 266 of file relic_fpx_inv.c.
References fp2_copy(), and fp2_neg().
fp4_inv()
void fp4_inv (fp4_t c, const fp4_t a)
Inverts a quartic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the quartic extension field element to invert.
Definition at line 271 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp2_free, fp2_inv(), fp2_mul, fp2_mul_nor, fp2_neg(), fp2_new, fp2_null, fp2_sqr, fp2_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep4_curve_set_twist(), ep4_map(), ep4_norm_imp(), fp24_back_cyc(), fp4_exp(), fp4_inv_sim(), fp8_inv(), fp8_srt(), pp_norm_k16(), and pp_norm_k24().
fp4_inv_sim()
void fp4_inv_sim (fp4_t * c, const fp4_t * a, int n)
Inverts multiple quartic extension field elements simultaneously.
Parameters
[out] c - the result.
[in] a - the quartic extension field elements to invert.
[in] n - the number of elements.
Definition at line 299 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp4_copy(), fp4_free, fp4_inv(), fp4_mul, fp4_new, fp4_null, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by ep4_map(), ep4_norm_sim(), and fp24_back_cyc_sim().
fp6_inv()
void fp6_inv (fp6_t c, const fp6_t a)
Inverts a sextic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the sextic extension field element to invert.
Definition at line 342 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp2_add, fp2_free, fp2_inv(), fp2_mul, fp2_mul_nor, fp2_new, fp2_null, fp2_sqr, fp2_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp12_inv(), fp12_pck_max(), and fp6_exp().
fp8_inv_cyc()
void fp8_inv_cyc (fp8_t c, const fp8_t a)
Computes the inverse of a cyclotomic octic extension field element.
For cyclotomic elements, this is equivalent to computing the conjugate. A cyclotomic element is one previously raised to the (p^4 - 1)-th power.
Parameters
[out] c - the result.
[in] a - the octic extension field element to invert.
Definition at line 401 of file relic_fpx_inv.c.
References fp4_copy(), and fp4_neg().
Referenced by fp24_inv_cyc(), fp8_conv_cyc(), fp8_exp_cyc(), fp8_exp_cyc_sim(), fp8_exp_dig(), fp8_test_cyc(), pp_exp_k8(), pp_map_oatep_k8(), and pp_map_sim_oatep_k8().
fp8_inv()
void fp8_inv (fp8_t c, const fp8_t a)
Inverts an octic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the octic extension field element to invert.
Definition at line 406 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp4_free, fp4_inv(), fp4_mul, fp4_mul_art(), fp4_neg(), fp4_new, fp4_null, fp4_sqr, fp4_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep8_curve_set_twist(), ep8_map(), ep8_norm_imp(), fp16_inv(), fp16_srt(), fp24_inv(), fp48_back_cyc(), fp8_conv_cyc(), fp8_exp(), fp8_inv_sim(), and pp_norm_k48().
fp8_inv_sim()
void fp8_inv_sim (fp8_t * c, const fp8_t * a, int n)
Inverts multiple octic extension field elements simultaneously.
Parameters
[out] c - the result.
[in] a - the octic extension field elements to invert.
[in] n - the number of elements.
Definition at line 434 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp8_copy(), fp8_free, fp8_inv(), fp8_mul, fp8_new, fp8_null, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by ep8_norm_sim(), and fp48_back_cyc_sim().
fp9_inv()
void fp9_inv (fp9_t c, const fp9_t a)
Inverts a nonic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the nonic extension field element to invert.
Definition at line 477 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp3_add, fp3_free, fp3_inv(), fp3_mul, fp3_mul_nor(), fp3_new, fp3_null, fp3_sqr, fp3_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep9_add_basic(), ep9_dbl_basic(), fp18_inv(), fp54_back_cyc(), fp9_exp(), fp9_inv_sim(), and pp_mil_k54().
fp9_inv_sim()
void fp9_inv_sim (fp9_t * c, const fp9_t * a, int n)
Inverts multiple noinc extension field elements simultaneously.
Parameters
[out] c - the result.
[in] a - the nonic extension field elements to invert.
[in] n - the number of elements.
Definition at line 536 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp9_copy(), fp9_free, fp9_inv(), fp9_mul, fp9_new, fp9_null, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by fp54_back_cyc_sim().
fp12_inv()
void fp12_inv (fp12_t c, const fp12_t a)
Inverts a dodecic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to invert.
Definition at line 579 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp6_free, fp6_inv(), fp6_mul, fp6_mul_art(), fp6_neg(), fp6_new, fp6_null, fp6_sqr, fp6_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp12_conv_cyc(), fp12_exp(), fp12_upk_max(), pp_map_sim_weilp_k12(), and pp_map_weilp_k12().
fp12_inv_cyc()
void fp12_inv_cyc (fp12_t c, const fp12_t a)
Computes the inverse of a cyclotomic dodecic extension field element. For unitary elements, this is equivalent to computing the conjugate. A unitary element is one previously raised to the (p^6 - 1)-th power.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to invert.
Definition at line 607 of file relic_fpx_inv.c.
References fp6_copy(), and fp6_neg().
Referenced by fp12_conv_cyc(), fp12_exp_cyc(), fp12_exp_cyc_sim(), fp12_exp_cyc_sps(), fp12_exp_dig(), pp_exp_b12(), pp_exp_bn(), pp_exp_sm9(), pp_map_oatep_k12(), pp_map_sim_oatep_k12(), pp_map_sim_weilp_k12(), and pp_map_weilp_k12().
fp16_inv_cyc()
void fp16_inv_cyc (fp16_t c, const fp16_t a)
Computes the inverse of a cyclotomic sextadecic extension field element.
For cyclotomic elements, this is equivalent to computing the conjugate. A cyclotomic element is one previously raised to the (p^4 - 1)-th power.
Parameters
[out] c - the result.
[in] a - the sextadecic extension field element to invert.
Definition at line 612 of file relic_fpx_inv.c.
References fp8_copy(), and fp8_neg().
Referenced by fp16_conv_cyc(), fp16_exp_cyc(), fp16_exp_cyc_sim(), fp16_exp_dig(), fp16_test_cyc(), pp_exp_afg16(), pp_exp_kss(), pp_map_oatep_k16(), pp_map_sim_oatep_k16(), pp_map_sim_weilp_k16(), and pp_map_weilp_k16().
fp16_inv()
void fp16_inv (fp16_t c, const fp16_t a)
Inverts an sextadecic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the sextadecic extension field element to invert.
Definition at line 617 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp8_free, fp8_inv(), fp8_mul, fp8_mul_art(), fp8_neg(), fp8_new, fp8_null, fp8_sqr, fp8_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp16_conv_cyc(), fp16_exp(), fp16_inv_sim(), pp_map_sim_weilp_k16(), and pp_map_weilp_k16().
fp16_inv_sim()
void fp16_inv_sim (fp16_t * c, const fp16_t * a, int n)
Inverts multiple sextadecic extension field elements simultaneously.
Parameters
[out] c - the result.
[in] a - the sextadecic extension field elements to invert.
[in] n - the number of elements.
Definition at line 645 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp16_copy(), fp16_free, fp16_inv(), fp16_mul, fp16_new, fp16_null, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
fp18_inv()
void fp18_inv (fp18_t c, const fp18_t a)
Inverts an octdecic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element to invert.
Definition at line 688 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp9_free, fp9_inv(), fp9_mul, fp9_mul_art(), fp9_neg(), fp9_new, fp9_null, fp9_sqr, fp9_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep3_curve_set_twist(), fp18_conv_cyc(), fp18_exp(), fp54_inv(), pp_map_sim_weilp_k18(), and pp_map_weilp_k18().
fp18_inv_cyc()
void fp18_inv_cyc (fp18_t c, const fp18_t a)
Computes the inverse of a cyclotomic octdecic extension field element. For unitary elements, this is equivalent to computing the conjugate. A unitary element is one previously raised to the (p^9 - 1)-th power.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element to invert.
Definition at line 716 of file relic_fpx_inv.c.
References fp9_copy(), and fp9_neg().
Referenced by fp18_conv_cyc(), fp18_exp_cyc(), fp18_exp_cyc_sim(), fp18_exp_cyc_sps(), fp18_exp_dig(), fp54_inv_cyc(), pp_exp_fm(), pp_exp_kss(), pp_exp_sg(), pp_map_oatep_k18(), pp_map_sim_oatep_k18(), pp_map_sim_weilp_k18(), and pp_map_weilp_k18().
fp24_inv()
void fp24_inv (fp24_t c, const fp24_t a)
Inverts a 24-degree extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the 24-degree extension field element to invert.
Definition at line 721 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp8_add(), fp8_free, fp8_inv(), fp8_mul, fp8_mul_art(), fp8_new, fp8_null, fp8_sqr, fp8_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp24_conv_cyc(), fp24_exp(), and fp48_inv().
fp24_inv_cyc()
void fp24_inv_cyc (fp24_t c, const fp24_t a)
Computes the inverse of a cyclotomic octdecic extension field element. For unitary elements, this is equivalent to computing the conjugate. A unitary element is one previously raised to the (p^12 - 1)-th power.
Parameters
[out] c - the result.
[in] a - the 24-degree extension field element to invert.
Definition at line 780 of file relic_fpx_inv.c.
References fp8_inv_cyc(), and fp8_neg().
Referenced by fp24_conv_cyc(), fp24_exp_cyc(), fp24_exp_cyc_sim(), fp24_exp_cyc_sps(), fp24_exp_dig(), pp_exp_k24(), pp_map_k24(), and pp_map_sim_k24().
fp48_inv()
void fp48_inv (fp48_t c, const fp48_t a)
Inverts a 48-extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the 48-extension field element to invert.
Definition at line 787 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp24_free, fp24_inv(), fp24_mul, fp24_mul_art(), fp24_neg(), fp24_new, fp24_null, fp24_sqr, fp24_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp48_conv_cyc(), and fp48_exp().
fp48_inv_cyc()
void fp48_inv_cyc (fp48_t c, const fp48_t a)
Computes the inverse of a cyclotomic 48-extension field element.
For unitary elements, this is equivalent to computing the conjugate. A unitary element is one previously raised to the (p^24 - 1)-th power.
Parameters
[out] c - the result.
[in] a - the 48-extension field element to invert.
Definition at line 815 of file relic_fpx_inv.c.
References fp24_copy(), and fp24_neg().
Referenced by fp48_conv_cyc(), fp48_exp_cyc(), fp48_exp_cyc_sim(), fp48_exp_cyc_sps(), fp48_exp_dig(), pp_exp_k48(), pp_map_k48(), and pp_map_sim_k48().
fp54_inv()
void fp54_inv (fp54_t c, const fp54_t a)
Inverts a 54-extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the 54-extension field element to invert.
Definition at line 820 of file relic_fpx_inv.c.
References ERR_CAUGHT, fp18_add(), fp18_free, fp18_inv(), fp18_mul, fp18_mul_art(), fp18_new, fp18_null, fp18_sqr, fp18_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp54_conv_cyc(), and fp54_exp().
fp54_inv_cyc()
void fp54_inv_cyc (fp54_t c, const fp54_t a)
Computes the inverse of a cyclotomic 54-extension field element.
For unitary elements, this is equivalent to computing the conjugate. A unitary element is one previously raised to the (p^24 - 1)-th power.
Parameters
[out] c - the result.
[in] a - the 54-extension field element to invert.
Definition at line 879 of file relic_fpx_inv.c.
References fp18_inv_cyc(), and fp18_neg().
Referenced by fp54_conv_cyc(), fp54_exp_cyc(), fp54_exp_cyc_sps(), fp54_exp_dig(), pp_exp_k54(), and pp_map_k54().