RELIC: src/epx/relic_ep2_pck.c File Reference
relic_ep2_pck.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
void ep2_pck (ep2_t r, const ep2_t p)
int ep2_upk (ep2_t r, const ep2_t p)
Detailed Description
Implementation of point compression on prime elliptic curves over a quadratic extension field.
Definition in file relic_ep2_pck.c.
Function Documentation
ep2_pck()
void ep2_pck (ep2_t r, const ep2_t p)
Compresses a point in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[in] p - the point to compress.
Definition at line 39 of file relic_ep2_pck.c.
References BASIC, bn_cmp(), bn_free, bn_hlv(), bn_new, bn_null, dv_copy(), ERR_CAUGHT, fp2_copy(), fp2_zero(), fp_prime_back(), fp_prime_get(), fp_set_bit(), fp_set_dig(), fp_zero(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_GT, RLC_THROW, and RLC_TRY.
Referenced by ep2_write_bin().
ep2_upk()
int ep2_upk (ep2_t r, const ep2_t p)
Decompresses a point in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[in] p - the point to decompress.
Returns
if the decompression was successful
Definition at line 73 of file relic_ep2_pck.c.
References BASIC, bn_cmp(), bn_free, bn_hlv(), bn_is_zero(), bn_new, bn_null, dv_copy(), ep2_rhs(), ERR_CAUGHT, fp2_copy(), fp2_free, fp2_neg(), fp2_new, fp2_null, fp2_srt(), fp_get_bit(), fp_prime_back(), fp_prime_get(), fp_set_dig(), fp_zero(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_GT, RLC_THROW, and RLC_TRY.
Referenced by ep2_read_bin().