RELIC: src/ep/relic_ep_util.c File Reference
relic_ep_util.c File Reference
Elliptic curves over prime fields
#include "relic_core.h"
Functions
int ep_is_infty (const ep_t p)
void ep_set_infty (ep_t p)
void ep_copy (ep_t r, const ep_t p)
void ep_rand (ep_t p)
void ep_blind (ep_t r, const ep_t p)
void ep_rhs (fp_t rhs, const fp_t x)
int ep_on_curve (const ep_t p)
void ep_tab (ep_t *t, const ep_t p, int w)
void ep_print (const ep_t p)
size_t ep_size_bin (const ep_t a, int pack)
void ep_read_bin (ep_t a, const uint8_t *bin, size_t len)
void ep_write_bin (uint8_t *bin, size_t len, const ep_t a, int pack)
Detailed Description
Implementation of the prime elliptic curve utilities.
Version
$Id$
Definition in file relic_ep_util.c.
Function Documentation
ep_is_infty()
int ep_is_infty (const ep_t p)
Tests if a point on a prime elliptic curve is at the infinity.
Parameters
[in] p - the point to test.
Returns
1 if the point is at infinity, 0 otherise.
Definition at line 39 of file relic_ep_util.c.
References fp_is_zero().
Referenced by ep_add_basic(), ep_add_jacob(), ep_add_projc(), ep_add_slp_basic(), ep_cmp(), ep_dbl_basic(), ep_dbl_jacob(), ep_dbl_projc(), ep_dbl_slp_basic(), ep_mul_basic(), ep_mul_dig(), ep_mul_lwnaf(), ep_mul_lwreg(), ep_mul_monty(), ep_mul_sim_gen(), ep_mul_sim_inter(), ep_mul_sim_joint(), ep_mul_sim_trick(), ep_mul_slide(), ep_neg(), ep_norm(), ep_norm_sim(), ep_on_curve(), ep_psi(), ep_size_bin(), ep_write_bin(), pp_map_k24(), pp_map_k48(), pp_map_k54(), pp_map_oatep_k12(), pp_map_oatep_k16(), pp_map_oatep_k18(), pp_map_oatep_k8(), pp_map_sim_k24(), pp_map_sim_k48(), pp_map_sim_oatep_k12(), pp_map_sim_oatep_k16(), pp_map_sim_oatep_k18(), pp_map_sim_oatep_k8(), pp_map_sim_tatep_k1(), pp_map_sim_tatep_k12(), pp_map_sim_tatep_k16(), pp_map_sim_tatep_k18(), pp_map_sim_tatep_k2(), pp_map_sim_weilp_k1(), pp_map_sim_weilp_k12(), pp_map_sim_weilp_k16(), pp_map_sim_weilp_k18(), pp_map_sim_weilp_k2(), pp_map_tatep_k1(), pp_map_tatep_k12(), pp_map_tatep_k16(), pp_map_tatep_k18(), pp_map_tatep_k2(), pp_map_weilp_k1(), pp_map_weilp_k12(), pp_map_weilp_k16(), pp_map_weilp_k18(), and pp_map_weilp_k2().
ep_set_infty()
void ep_set_infty (ep_t p)
Assigns a prime elliptic curve point to the point at infinity.
Parameters
[out] p - the point to assign.
Definition at line 43 of file relic_ep_util.c.
References BASIC, and fp_zero().
Referenced by ep_curve_init(), ep_dbl_basic(), ep_dbl_jacob(), ep_dbl_projc(), ep_dbl_slp_basic(), ep_map_swift_impl(), ep_mul_basic(), ep_mul_combs_endom(), ep_mul_dig(), ep_mul_fix_basic(), ep_mul_fix_combd(), ep_mul_fix_combs(), ep_mul_fix_lwnaf(), ep_mul_gen(), ep_mul_glv_imp(), ep_mul_lwnaf(), ep_mul_lwreg(), ep_mul_monty(), ep_mul_naf_imp(), ep_mul_pre_combd(), ep_mul_pre_combs(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_mul_sim_dig(), ep_mul_sim_endom(), ep_mul_sim_joint(), ep_mul_sim_lot(), ep_mul_sim_lot_endom(), ep_mul_sim_lot_plain(), ep_mul_sim_plain(), ep_mul_sim_trick(), ep_mul_slide(), ep_neg(), ep_norm(), ep_psi(), ep_read_bin(), and ep_sub().
ep_copy()
void ep_copy (ep_t r, const ep_t p)
Copies the second argument to the first argument.
Parameters
[out] q - the result.
[in] p - the prime elliptic curve point to copy.
Definition at line 50 of file relic_ep_util.c.
References fp_copy().
Referenced by ep_add_basic(), ep_add_jacob(), ep_add_projc(), ep_add_slp_basic(), ep_blind(), ep_cmp(), ep_curve_get_gen(), ep_mul_combs_endom(), ep_mul_combs_plain(), ep_mul_fix_plain(), ep_mul_pre_basic(), ep_mul_pre_combd(), ep_mul_pre_combs(), ep_mul_sim_joint(), ep_mul_sim_lot_endom(), ep_mul_sim_trick(), ep_mul_slide(), ep_norm(), ep_norm_imp(), ep_psi(), ep_tab(), g1_is_valid(), pp_add_k2_basic(), pp_dbl_k2_basic(), pp_mil_k1(), pp_mil_k2(), pp_mil_lit_k12(), pp_mil_lit_k16(), pp_mil_lit_k18(), and pp_mil_lit_k2().
ep_rand()
void ep_rand (ep_t p)
Assigns a random value to a prime elliptic curve point.
Parameters
[out] p - the prime elliptic curve point to assign.
Definition at line 57 of file relic_ep_util.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), ep_curve_get_ord(), ep_mul_gen(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep_blind()
void ep_blind (ep_t r, const ep_t p)
Randomizes coordinates of a prime elliptic curve point.
Parameters
[out] r - the blinded prime elliptic curve point.
[in] p - the prime elliptic curve point to blind.
Definition at line 79 of file relic_ep_util.c.
References ep_copy(), ERR_CAUGHT, fp_free, fp_mul, fp_new, fp_null, fp_rand(), fp_sqr, JACOB, PROJC, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep_mul_monty().
ep_rhs()
void ep_rhs (fp_t rhs, const fp_t x)
Computes the right-hand side of the elliptic curve equation at the x-coordinate of a certain prime elliptic curve point.
Parameters
[out] rhs - the result.
[in] x - the x-coordinate of the point.
Definition at line 110 of file relic_ep_util.c.
References ep_curve_get_a(), ep_curve_get_b(), ep_curve_opt_a(), ep_curve_opt_b(), ERR_CAUGHT, fp_add, fp_add_dig(), fp_copy(), fp_free, fp_mul, fp_new, fp_null, fp_sqr, fp_sub_dig(), RLC_CATCH_ANY, RLC_FINALLY, RLC_MIN3, RLC_ONE, RLC_THROW, RLC_TINY, RLC_TRY, RLC_TWO, and RLC_ZERO.
Referenced by ep_map_basic_impl(), ep_map_swift_impl(), ep_on_curve(), and ep_upk().
ep_on_curve()
int ep_on_curve (const ep_t p)
Tests if a point is in the curve.
Parameters
[in] p - the point to test.
Definition at line 178 of file relic_ep_util.c.
References ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ep_rhs(), ERR_CAUGHT, fp_cmp(), fp_sqr, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep_read_bin().
ep_tab()
void ep_tab (ep_t * t, const ep_t p, int w)
Builds a precomputation table for multiplying a random prime elliptic point.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
[in] w - the window width.
Definition at line 199 of file relic_ep_util.c.
References ep_add, ep_copy(), ep_dbl, ep_norm(), and ep_norm_sim().
Referenced by ep_mul_glv_imp(), ep_mul_naf_imp(), ep_mul_pre_lwnaf(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_mul_sim_endom(), and ep_mul_sim_plain().
ep_print()
void ep_print (const ep_t p)
Prints a prime elliptic curve point.
Parameters
[in] p - the prime elliptic curve point to print.
Definition at line 220 of file relic_ep_util.c.
References fp_print().
ep_size_bin()
size_t ep_size_bin (const ep_t a, int pack)
Returns the number of bytes necessary to store a prime elliptic curve point with optional point compression.
Parameters
[in] a - the prime field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 226 of file relic_ep_util.c.
References ep_is_infty(), and RLC_FP_BYTES.
ep_read_bin()
void ep_read_bin (ep_t a, const uint8_t * bin, size_t len)
Reads a prime elliptic curve point from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_VALID - if the encoded point is invalid.
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 241 of file relic_ep_util.c.
References BASIC, ep_on_curve(), ep_set_infty(), ep_upk(), ERR_NO_BUFFER, ERR_NO_VALID, fp_read_bin(), fp_set_bit(), fp_set_dig(), fp_zero(), RLC_FP_BYTES, and RLC_THROW.
ep_write_bin()
void ep_write_bin (uint8_t * bin, size_t len, const ep_t a, int pack)
Writes a prime elliptic curve point to a byte vector in big-endian format with optional point compression.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the prime elliptic curve point to write.
[in] pack - the flag to indicate point compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 291 of file relic_ep_util.c.
References ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ep_pck(), ERR_CAUGHT, ERR_NO_BUFFER, fp_get_bit(), fp_write_bin(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.