RELIC: src/eb/relic_eb_dbl.c File Reference
relic_eb_dbl.c File Reference
Elliptic curves over binary fields
#include "string.h"
#include "relic_core.h"
#include "relic_eb.h"
Functions
static void eb_dbl_basic_imp (eb_t r, const eb_t p)
static void eb_dbl_projc_imp (eb_t r, const eb_t p)
void eb_dbl_basic (eb_t r, const eb_t p)
void eb_dbl_projc (eb_t r, const eb_t p)
Detailed Description
Implementation of point doubling on binary elliptic curves.
Definition in file relic_eb_dbl.c.
Function Documentation
eb_dbl_basic_imp()
static void eb_dbl_basic_imp (eb_t r, const eb_t p) static
Doubles a point represented in affine coordinates on an ordinary binary elliptic curve.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 50 of file relic_eb_dbl.c.
References BASIC, eb_curve_get_a(), eb_curve_opt_a(), ERR_CAUGHT, fb_add(), fb_add_dig(), fb_copy(), fb_free, fb_inv, fb_mul, fb_new, fb_null, fb_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_ONE, RLC_THROW, RLC_TINY, RLC_TRY, and RLC_ZERO.
Referenced by eb_dbl_basic().
eb_dbl_projc_imp()
static void eb_dbl_projc_imp (eb_t r, const eb_t p) static
Doubles a point represented in projective coordinates on an ordinary binary elliptic curve.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 124 of file relic_eb_dbl.c.
References BASIC, eb_curve_get_a(), eb_curve_opt_a(), ERR_CAUGHT, fb_add(), fb_copy(), fb_free, fb_mul, fb_mul_dig(), fb_new, fb_null, fb_sqr, PROJC, RLC_CATCH_ANY, RLC_FINALLY, RLC_ONE, RLC_THROW, RLC_TINY, RLC_TRY, and RLC_ZERO.
Referenced by eb_dbl_projc().
eb_dbl_basic()
void eb_dbl_basic (eb_t r, const eb_t p)
Doubles a binary elliptic curve point represented in affine coordinates.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 204 of file relic_eb_dbl.c.
References eb_dbl_basic_imp(), eb_is_infty(), and eb_set_infty().
Referenced by eb_add_basic_imp().
eb_dbl_projc()
void eb_dbl_projc (eb_t r, const eb_t p)
Doubles a binary elliptic curve point represented in projective coordinates.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 217 of file relic_eb_dbl.c.
References eb_dbl_projc_imp(), eb_is_infty(), and eb_set_infty().
Referenced by eb_add_projc_imp(), and eb_add_projc_mix().