RELIC: src/relic_util.c File Reference
relic_util.c File Reference
Core functions
#include <stdio.h>
#include <stdarg.h>
#include <ctype.h>
#include <inttypes.h>
#include "relic_core.h"
#include "relic_conf.h"
#include "relic_util.h"
#include "relic_types.h"
Functions
uint32_t util_conv_endian (uint32_t i)
uint32_t util_conv_big (uint32_t i)
uint32_t util_conv_little (uint32_t i)
char util_conv_char (dig_t i)
size_t util_bits_dig (dig_t a)
int util_cmp_sec (const void *a, const void *b, size_t size)
void util_perm (uint_t p[], size_t n)
void util_print (const char *format,...)
void util_print_dig (dig_t a, int pad)
Detailed Description
Implementation of useful configuration routines.
Definition in file relic_util.c.
Function Documentation
util_conv_endian()
uint32_t util_conv_endian (uint32_t i)
Buffer to hold printed messages.
Definition at line 85 of file relic_util.c.
Referenced by util_conv_big(), and util_conv_little().
util_conv_big()
uint32_t util_conv_big (uint32_t i)
Convert a digit to big-endian.
Definition at line 96 of file relic_util.c.
References util_conv_endian().
Referenced by nist_kdf(), and rand_hash().
util_conv_little()
uint32_t util_conv_little (uint32_t i)
Convert a digit to little-endian.
Definition at line 104 of file relic_util.c.
References util_conv_endian().
util_conv_char()
char util_conv_char (dig_t i)
Converts a small digit to a character.
Definition at line 112 of file relic_util.c.
Referenced by bn_read_str(), bn_write_str(), and fb_write_str().
util_bits_dig()
size_t util_bits_dig (dig_t a)
Returns the highest bit set on a digit.
Parameters
[in] a - the digit.
Returns
the position of the highest bit set.
Definition at line 137 of file relic_util.c.
References arch_lzcnt(), and RLC_DIG.
Referenced by bn_bits(), bn_mxp_dig(), bn_mxp_slide(), bn_read_str(), cp_bdpe_gen(), eb_mul_dig(), ed_mul_slide(), ep2_mul_reg_gls(), ep2_mul_sim_dig(), ep2_mul_sim_lot(), ep2_mul_slide(), ep3_mul_gls_imp(), ep3_mul_reg_gls(), ep3_mul_sim_dig(), ep3_mul_sim_lot(), ep3_mul_slide(), ep4_mul_reg_gls(), ep4_mul_sim_dig(), ep4_mul_sim_lot(), ep4_mul_slide(), ep8_mul_reg_gls(), ep8_mul_sim_dig(), ep8_mul_sim_lot(), ep8_mul_slide(), ep_mul_sim_dig(), ep_mul_sim_lot_endom(), ep_mul_slide(), fb_bits(), fb_exp_slide(), fb_inv_exgcd(), fp12_exp_dig(), fp16_exp_dig(), fp18_exp_dig(), fp24_exp_dig(), fp2_exp_dig(), fp2_field_init(), fp3_field_init(), fp48_exp_dig(), fp54_exp_dig(), fp8_exp_dig(), fp_bits(), fp_exp_dig(), fp_exp_slide(), fp_smb_binar(), gt_exp_gls_sac(), and gt_exp_reg_sac().
util_cmp_sec()
int util_cmp_sec (const void * a, const void * b, size_t n)
Compares two buffers in constant time.
Parameters
[in] a - the first buffer.
[in] b - the second buffer.
[in] n - the length in bytes of the buffers.
Returns
RLC_EQ if they are equal and RLC_NE otherwise.
Definition at line 141 of file relic_util.c.
References RLC_EQ, and RLC_NE.
Referenced by cp_ecies_dec(), and cp_rsa_ver().
util_perm()
void util_perm (uint_t p[], size_t n)
Computes a random permutation in [0, n-1].
Parameters
[out] p - the resulting permutation.
[in] n - the size of the permutation.
Definition at line 154 of file relic_util.c.
References rand_bytes().
Referenced by cp_pbpsi_ans(), cp_rsapsi_ans(), and cp_shipsi_ans().
util_print()
void util_print (const char * format, ...)
Definition at line 166 of file relic_util.c.
util_print_dig()
void util_print_dig (dig_t a, int pad)
Prints a digit.
Parameters
[in] a - the digit to print.
[in] pad - the flag to indicate if the digit must be padded with zeroes.
Definition at line 201 of file relic_util.c.
References util_print.
Referenced by bn_print(), dv_print(), fb_print(), and fp_print().