RELIC: src/epx/relic_ep2_norm.c File Reference
relic_ep2_norm.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
static void ep2_norm_imp (ep2_t r, const ep2_t p, int inv)
void ep2_norm (ep2_t r, const ep2_t p)
void ep2_norm_sim (ep2_t *r, const ep2_t *t, int n)
Detailed Description
Implementation of point normalization on prime elliptic curves over a quadratic extension.
Definition in file relic_ep2_norm.c.
Function Documentation
ep2_norm_imp()
static void ep2_norm_imp (ep2_t r, const ep2_t p, int inv) static
Normalizes a point represented in projective coordinates.
Parameters
r - the result.
p - the point to normalize.
inv - the flag to indicate if z is already inverted.
Definition at line 48 of file relic_ep2_norm.c.
References BASIC, ep2_copy(), ERR_CAUGHT, fp2_copy(), fp2_free, fp2_inv(), fp2_mul, fp2_new, fp2_null, fp2_set_dig(), fp2_sqr, JACOB, PROJC, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep2_norm(), and ep2_norm_sim().
ep2_norm()
void ep2_norm (ep2_t r, const ep2_t p)
Converts a point to affine coordinates.
Parameters
[out] r - the result.
[in] p - the point to convert.
Definition at line 97 of file relic_ep2_norm.c.
References BASIC, ep2_copy(), ep2_is_infty(), ep2_norm_imp(), and ep2_set_infty().
Referenced by ep2_curve_set(), ep2_map_from_field(), ep2_mul_basic(), ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep2_mul_dig(), ep2_mul_fix_basic(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_fix_plain(), ep2_mul_gls_imp(), ep2_mul_monty(), ep2_mul_naf_imp(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_reg_gls(), ep2_mul_reg_imp(), ep2_mul_sim_basic(), ep2_mul_sim_dig(), ep2_mul_sim_endom(), ep2_mul_sim_joint(), ep2_mul_sim_lot(), ep2_mul_sim_plain(), ep2_mul_sim_trick(), ep2_mul_slide(), ep2_on_curve(), ep2_size_bin(), ep2_tab(), ep2_write_bin(), pp_map_oatep_k12(), pp_map_oatep_k8(), pp_map_sim_oatep_k12(), pp_map_sim_oatep_k8(), pp_map_sim_tatep_k12(), pp_map_sim_weilp_k12(), pp_map_tatep_k12(), and pp_map_weilp_k12().
ep2_norm_sim()
void ep2_norm_sim (ep2_t * r, const ep2_t * t, int n)
Converts multiple points to affine coordinates.
Parameters
[out] r - the result.
[in] t - the points to convert.
[in] n - the number of points.
Definition at line 113 of file relic_ep2_norm.c.
References ep2_is_infty(), ep2_norm_imp(), ERR_CAUGHT, ERR_NO_MEMORY, fp2_copy(), fp2_free, fp2_inv_sim(), fp2_new, fp2_null, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by ep2_mul_reg_gls(), ep2_mul_sim_joint(), ep2_mul_sim_trick(), ep2_mul_slide(), and ep2_tab().