RELIC: src/eb/relic_eb_map.c File Reference
relic_eb_map.c File Reference
Elliptic curves over binary fields
#include "relic_core.h"
#include "relic_md.h"
#include "relic_eb.h"
Functions
void eb_map (eb_t p, const uint8_t *msg, size_t len)
Detailed Description
Implementation of hashing to a binary elliptic curve.
Definition in file relic_eb_map.c.
Function Documentation
eb_map()
void eb_map (eb_t p, const uint8_t * msg, size_t len)
Maps a byte array to a point in a binary elliptic curve.
Parameters
[out] p - the result.
[in] msg - the byte array to map.
[in] len - the array length in bytes.
Definition at line 40 of file relic_eb_map.c.
References BASIC, bn_add_dig(), bn_bits(), bn_free, bn_mod_2b(), bn_new, bn_null, bn_read_bin(), dv_copy(), eb_curve_get_cof(), eb_mul, eb_mul_dig(), eb_rhs(), ERR_CAUGHT, fb_free, fb_inv, fb_mul, fb_new, fb_null, fb_set_dig(), fb_slv, fb_sqr, fb_trc, md_map, RLC_CATCH_ANY, RLC_DIG, RLC_FB_BITS, RLC_FB_BYTES, RLC_FB_DIGS, RLC_FINALLY, RLC_MD_LEN, RLC_MIN, RLC_THROW, and RLC_TRY.