RELIC: src/ep/relic_ep_pck.c File Reference
relic_ep_pck.c File Reference
Elliptic curves over prime fields
#include "relic_core.h"
Functions
void ep_pck (ep_t r, const ep_t p)
int ep_upk (ep_t r, const ep_t p)
Detailed Description
Implementation of point compression on prime elliptic curves.
Definition in file relic_ep_pck.c.
Function Documentation
ep_pck()
void ep_pck (ep_t r, const ep_t p)
Compresses a point.
Parameters
[out] r - the result.
[in] p - the point to compress.
Definition at line 38 of file relic_ep_pck.c.
References BASIC, bn_cmp(), bn_free, bn_hlv(), bn_new, bn_null, dv_copy(), ep_curve_is_pairf(), ERR_CAUGHT, fp_copy(), fp_get_bit(), fp_prime_back(), fp_prime_get(), fp_set_bit(), fp_set_dig(), fp_zero(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_GT, RLC_THROW, and RLC_TRY.
Referenced by ep_write_bin().
ep_upk()
int ep_upk (ep_t r, const ep_t p)
Decompresses a point.
Parameters
[out] r - the result.
[in] p - the point to decompress.
Returns
a boolean value indicating if the decompression was successful.
Definition at line 77 of file relic_ep_pck.c.
References BASIC, bn_cmp(), bn_free, bn_hlv(), bn_new, bn_null, dv_copy(), ep_curve_is_pairf(), ep_rhs(), ERR_CAUGHT, fp_copy(), fp_free, fp_get_bit(), fp_neg, fp_new, fp_null, fp_prime_back(), fp_prime_get(), fp_set_dig(), fp_srt(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_GT, RLC_THROW, and RLC_TRY.
Referenced by ep_read_bin().