RELIC: src/cp/relic_cp_bls.c File Reference
relic_cp_bls.c File Reference
Cryptographic protocols
#include "relic.h"
Functions
int cp_bls_gen (bn_t d, g2_t q)
int cp_bls_sig (g1_t s, const uint8_t *msg, size_t len, const bn_t d)
int cp_bls_ver (const g1_t s, const uint8_t *msg, size_t len, const g2_t q)
Detailed Description
Implementation of the Boneh-Lynn-Schacham short signature protocol.
Definition in file relic_cp_bls.c.
Function Documentation
cp_bls_gen()
int cp_bls_gen (bn_t d, g2_t q)
Generates a key pair for the Boneh-Lynn-Schacham (BLS) signature protocol.
Parameters
[out] d - the private key.
[out] q - the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_bls.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), g2_mul_gen(), pc_get_ord, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
Referenced by cp_cmlhs_gen().
cp_bls_sig()
int cp_bls_sig (g1_t s, const uint8_t * msg, size_t len, const bn_t d)
Signs a message using the BLS protocol.
Parameters
[out] s - the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] d - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 60 of file relic_cp_bls.c.
References g1_free, g1_map, g1_mul_sec, g1_new, g1_null, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
Referenced by cp_cmlhs_sig().
cp_bls_ver()
int cp_bls_ver (const g1_t s, const uint8_t * msg, size_t len, const g2_t q)
Verifies a message signed with BLS protocol.
Parameters
[out] s - the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] q - the public key.
Returns
a boolean value indicating if the signature is valid.
Definition at line 80 of file relic_cp_bls.c.
References ERR_CAUGHT, g1_copy, g1_free, g1_map, g1_new, g1_null, g2_copy, g2_free, g2_get_gen, g2_is_valid(), g2_neg, g2_new, g2_null, gt_free, gt_is_unity, gt_new, gt_null, pc_map_sim, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by cp_cmlhs_onv(), and cp_cmlhs_ver().