RELIC: src/bc/rijndael-api-fst.c File Reference
rijndael-api-fst.c File Reference
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include "rijndael-alg-fst.h"
#include "rijndael-api-fst.h"
Functions
int makeKey (keyInstance *key, BYTE direction, int keyLen, char *keyMaterial)
int makeKey2 (keyInstance *key, BYTE direction, int keyLen, char *keyMaterial)
int cipherInit (cipherInstance *cipher, BYTE mode, char *IV)
int blockEncrypt (cipherInstance *cipher, keyInstance *key, BYTE *input, int inputLen, BYTE *outBuffer)
int padEncrypt (cipherInstance *cipher, keyInstance *key, BYTE *input, int inputOctets, BYTE *outBuffer)
int blockDecrypt (cipherInstance *cipher, keyInstance *key, BYTE *input, int inputLen, BYTE *outBuffer)
int padDecrypt (cipherInstance *cipher, keyInstance *key, BYTE *input, int inputOctets, BYTE *outBuffer)
Function Documentation
makeKey()
int makeKey (keyInstance * key, BYTE direction, int keyLen, char * keyMaterial)
rijndael-api-fst.c
Version
2.9 (December 2000)
Optimised ANSI C code for the Rijndael cipher (now AES)
Author
Vincent Rijmen vince.nosp@m.nt.r.nosp@m.ijmen.nosp@m.@esa.nosp@m.t.kul.nosp@m.euve.nosp@m.n.ac..nosp@m.be
Antoon Bosselaers antoo.nosp@m.n.bo.nosp@m.ssela.nosp@m.ers@.nosp@m.esat..nosp@m.kule.nosp@m.uven..nosp@m.ac.b.nosp@m.e
Paulo Barreto paulo.nosp@m..bar.nosp@m.reto@.nosp@m.terr.nosp@m.a.com.nosp@m..br
This code is hereby placed in the public domain.
THIS SOFTWARE IS PROVIDED BY THE AUTHORS ''AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHORS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Acknowledgements:
We are deeply indebted to the following people for their bug reports, fixes, and improvement suggestions to this implementation. Though we tried to list all contributions, we apologise in advance for any missing reference.
Andrew Bales Andre.nosp@m.w.Ba.nosp@m.les@H.nosp@m.oney.nosp@m.well..nosp@m.com Markus Friedl marku.nosp@m.s.fr.nosp@m.iedl@.nosp@m.info.nosp@m.rmati.nosp@m.k.un.nosp@m.i-erl.nosp@m.ange.nosp@m.n.de John Skodon skodo.nosp@m.nj@w.nosp@m.ebqui.nosp@m.ll.c.nosp@m.om
Definition at line 46 of file rijndael-api-fst.c.
References BAD_KEY_DIR, BAD_KEY_INSTANCE, BAD_KEY_MAT, DIR_DECRYPT, DIR_ENCRYPT, keyInstance::direction, keyInstance::ek, keyInstance::keyLen, keyInstance::keyMaterial, MAXKB, keyInstance::Nr, rijndaelKeySetupDec(), rijndaelKeySetupEnc(), keyInstance::rk, and TRUE.
makeKey2()
int makeKey2 (keyInstance * key, BYTE direction, int keyLen, char * keyMaterial)
Definition at line 108 of file rijndael-api-fst.c.
References BAD_KEY_DIR, BAD_KEY_INSTANCE, BAD_KEY_MAT, DIR_DECRYPT, DIR_ENCRYPT, keyInstance::direction, keyInstance::ek, keyInstance::keyLen, keyInstance::keyMaterial, MAXKB, keyInstance::Nr, rijndaelKeySetupDec(), rijndaelKeySetupEnc(), keyInstance::rk, and TRUE.
Referenced by bc_aes_cbc_dec(), and bc_aes_cbc_enc().
cipherInit()
int cipherInit (cipherInstance * cipher, BYTE mode, char * IV)
Definition at line 148 of file rijndael-api-fst.c.
References BAD_CIPHER_INSTANCE, BAD_CIPHER_MODE, cipherInstance::IV, MAX_IV_SIZE, cipherInstance::mode, MODE_CBC, MODE_CFB1, MODE_ECB, and TRUE.
Referenced by bc_aes_cbc_dec(), and bc_aes_cbc_enc().
blockEncrypt()
int blockEncrypt (cipherInstance * cipher, keyInstance * key, BYTE * input, int inputLen, BYTE * outBuffer)
Definition at line 187 of file rijndael-api-fst.c.
References BAD_CIPHER_STATE, DIR_DECRYPT, keyInstance::direction, keyInstance::ek, cipherInstance::IV, cipherInstance::mode, MODE_CBC, MODE_CFB1, MODE_ECB, keyInstance::Nr, rijndaelEncrypt(), and keyInstance::rk.
padEncrypt()
int padEncrypt (cipherInstance * cipher, keyInstance * key, BYTE * input, int inputOctets, BYTE * outBuffer)
Encrypt data partitioned in octets, using RFC 2040-like padding.
Parameters
input data to be encrypted (octet sequence)
inputOctets input length in octets (not bits)
outBuffer encrypted output data
Returns
length in octets (not bits) of the encrypted output buffer.
Definition at line 270 of file rijndael-api-fst.c.
References BAD_CIPHER_STATE, DIR_DECRYPT, keyInstance::direction, cipherInstance::IV, cipherInstance::mode, MODE_CBC, MODE_ECB, keyInstance::Nr, rijndaelEncrypt(), and keyInstance::rk.
Referenced by bc_aes_cbc_enc().
blockDecrypt()
int blockDecrypt (cipherInstance * cipher, keyInstance * key, BYTE * input, int inputLen, BYTE * outBuffer)
Definition at line 340 of file rijndael-api-fst.c.
References BAD_CIPHER_STATE, DIR_ENCRYPT, keyInstance::direction, keyInstance::ek, cipherInstance::IV, cipherInstance::mode, MODE_CBC, MODE_CFB1, MODE_ECB, keyInstance::Nr, rijndaelDecrypt(), rijndaelEncrypt(), and keyInstance::rk.
padDecrypt()
int padDecrypt (cipherInstance * cipher, keyInstance * key, BYTE * input, int inputOctets, BYTE * outBuffer)
Definition at line 416 of file rijndael-api-fst.c.
References BAD_CIPHER_STATE, BAD_DATA, DIR_ENCRYPT, keyInstance::direction, cipherInstance::IV, cipherInstance::mode, MODE_CBC, MODE_ECB, keyInstance::Nr, rijndaelDecrypt(), and keyInstance::rk.
Referenced by bc_aes_cbc_dec().