RELIC: src/fbx/relic_fb2_mul.c File Reference
relic_fb2_mul.c File Reference
Binary field extensions.
#include "relic_core.h"
#include "relic_fbx.h"
#include "relic_fb_low.h"
Functions
void fb2_mul (fb2_t c, const fb2_t a, const fb2_t b)
void fb2_mul_nor (fb2_t c, const fb2_t a)
Detailed Description
Implementation of multiplication in quadratic extensions of binary fields.
Definition in file relic_fb2_mul.c.
Function Documentation
fb2_mul()
void fb2_mul (fb2_t c, const fb2_t a, const fb2_t b)
Multiples two quadratic extension field elements. Computes c = a * b.
Parameters
[out] c - the result.
[in] a - the quadratic extension binary field element.
[in] b - the quadratic extension binary field element.
Definition at line 40 of file relic_fb2_mul.c.
References ERR_CAUGHT, fb_add(), fb_free, fb_mul, fb_new, fb_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fb2_mul_nor()
void fb2_mul_nor (fb2_t c, const fb2_t a)
Multiples a quadratic extension field element by a quadratic non-residue. Computes c = a * s.
Parameters
[out] c - the result.
[in] a - the quadratic extension binary field element.
[in] b - the quadratic extension binary field element.
Definition at line 70 of file relic_fb2_mul.c.
References ERR_CAUGHT, fb_add(), fb_copy(), fb_free, fb_new, fb_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.