RELIC: src/eb/relic_eb_neg.c File Reference
relic_eb_neg.c File Reference
Elliptic curves over binary fields
#include "string.h"
#include "relic_core.h"
#include "relic_eb.h"
Functions
void eb_neg_basic (eb_t r, const eb_t p)
void eb_neg_projc (eb_t r, const eb_t p)
Detailed Description
Implementation of point negation on binary elliptic curves.
Definition in file relic_eb_neg.c.
Function Documentation
eb_neg_basic()
void eb_neg_basic (eb_t r, const eb_t p)
Negates a binary elliptic curve point represented by affine coordinates.
Parameters
[out] r - the result.
[in] p - the point to negate.
Definition at line 43 of file relic_eb_neg.c.
References BASIC, eb_is_infty(), eb_set_infty(), fb_add(), and fb_copy().
Referenced by eb_sub_basic().
eb_neg_projc()
void eb_neg_projc (eb_t r, const eb_t p)
Negates a binary elliptic curve point represented by projective coordinates.
Parameters
[out] r - the result.
[in] p - the point to negate.
Definition at line 63 of file relic_eb_neg.c.
References BASIC, eb_is_infty(), eb_set_infty(), ERR_CAUGHT, fb_add(), fb_copy(), fb_free, fb_mul, fb_new, fb_null, PROJC, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by eb_sub_projc().