RELIC: src/fb/relic_fb_itr.c File Reference
relic_fb_itr.c File Reference
Binary field arithmetic
#include <string.h>
#include "relic_core.h"
#include "relic_conf.h"
#include "relic_fb.h"
#include "relic_fb_low.h"
#include "relic_bn_low.h"
#include "relic_util.h"
Functions
void fb_itr_basic (fb_t c, const fb_t a, int b)
void fb_itr_pre_quick (fb_st *t, int b)
void fb_itr_quick (fb_t c, const fb_t a, const fb_st *t)
Detailed Description
Implementation of the iterated squaring/square-root of a binary field element.
Definition in file relic_fb_itr.c.
Function Documentation
fb_itr_basic()
void fb_itr_basic (fb_t c, const fb_t a, int b)
Computes the iterated squaring/square-root of a binary field element by consecutive squaring/square-root. Computes c = a^(2^b).
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 46 of file relic_fb_itr.c.
References fb_copy(), fb_sqr, and fb_srt.
fb_itr_pre_quick()
void fb_itr_pre_quick (fb_st * t, int b)
Precomputes a table for iterated squaring/square-root of a binary field element.
Parameters
[out] t - the precomputed table.
[in] b - the exponent.
Definition at line 59 of file relic_fb_itr.c.
References ERR_CAUGHT, fb_copy(), fb_free, fb_lsh(), fb_new, fb_null, fb_set_dig(), fb_sqr, fb_srt, fb_zero(), RLC_CATCH_ANY, RLC_DIG, RLC_FB_DIGS, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fb_itr_quick()
void fb_itr_quick (fb_t c, const fb_t a, const fb_st * t)
Computes the iterated squaring/square-root of a binary field element by a table based method. Computes c = a^(2^b).
Parameters
[out] c - the result.
[in] a - the basis.
[in] t - the precomputed table.
Definition at line 93 of file relic_fb_itr.c.
References fb_itrn_low().