RELIC: src/cp/relic_cp_cls.c File Reference
relic_cp_cls.c File Reference
Cryptographic protocols
#include "relic.h"
Functions
int cp_cls_gen (bn_t r, bn_t s, g2_t x, g2_t y)
int cp_cls_sig (g1_t a, g1_t b, g1_t c, const uint8_t *msg, size_t len, const bn_t r, const bn_t s)
int cp_cls_ver (const g1_t a, const g1_t b, const g1_t c, const uint8_t *msg, size_t len, const g2_t x, const g2_t y)
int cp_cli_gen (bn_t t, bn_t u, bn_t v, g2_t x, g2_t y, g2_t z)
int cp_cli_sig (g1_t a, g1_t A, g1_t b, g1_t B, g1_t c, const uint8_t *msg, size_t len, const bn_t r, const bn_t t, const bn_t u, const bn_t v)
int cp_cli_ver (g1_t a, g1_t A, g1_t b, g1_t B, g1_t c, const uint8_t *msg, size_t len, const bn_t r, const g2_t x, const g2_t y, const g2_t z)
int cp_clb_gen (bn_t t, bn_t u, bn_t v[], g2_t x, g2_t y, g2_t z[], size_t l)
int cp_clb_sig (g1_t a, g1_t A[], g1_t b, g1_t B[], g1_t c, const uint8_t *ms[], const size_t ls[], const bn_t t, const bn_t u, const bn_t v[], size_t l)
int cp_clb_ver (const g1_t a, const g1_t A[], const g1_t b, const g1_t B[], const g1_t c, const uint8_t *ms[], const size_t ls[], const g2_t x, const g2_t y, const g2_t z[], size_t l)
Detailed Description
Implementation of the Camenisch-Lysyanskaya signature protocols.
Definition in file relic_cp_cls.c.
Function Documentation
cp_cls_gen()
int cp_cls_gen (bn_t u, bn_t v, g2_t x, g2_t y)
Generates a key pair for the Camenisch-Lysyanskaya simple signature (CLS) protocol.
Parameters
[out] u - the first part of the private key.
[out] v - the second part of the private key.
[out] x - the first part of the public key.
[out] y - the second part of the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_cls.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), g2_mul_gen(), pc_get_ord, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_cls_sig()
int cp_cls_sig (g1_t a, g1_t b, g1_t c, const uint8_t * msg, size_t len, const bn_t u, const bn_t v)
Signs a message using the CLS protocol.
Parameters
[out] a - the first part of the signature.
[out] b - the second part of the signature.
[out] c - the third part of the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] u - the first part of the private key.
[in] v - the second part of the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 62 of file relic_cp_cls.c.
References bn_add(), bn_free, bn_mod, bn_mul, bn_new, bn_null, bn_read_bin(), g1_mul(), g1_rand, pc_get_ord, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_cls_ver()
int cp_cls_ver (const g1_t a, const g1_t b, const g1_t c, const uint8_t * msg, size_t len, const g2_t x, const g2_t y)
Verifies a signature using the CLS protocol.
Parameters
[in] a - the first part of the signature.
[in] b - the second part of the signature.
[in] c - the third part of the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] u - the first part of the public key.
[in] v - the second part of the public key.
Returns
a boolean value indicating the verification result.
Definition at line 99 of file relic_cp_cls.c.
References bn_free, bn_mod, bn_new, bn_null, bn_read_bin(), ERR_CAUGHT, g1_add, g1_copy, g1_free, g1_is_infty, g1_mul(), g1_new, g1_norm, g1_null, g2_copy, g2_free, g2_get_gen, g2_neg, g2_new, g2_null, gt_free, gt_is_unity, gt_new, gt_null, pc_get_ord, pc_map_sim, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
cp_cli_gen()
int cp_cli_gen (bn_t t, bn_t u, bn_t v, g2_t x, g2_t y, g2_t z)
Generates a key pair for the Camenisch-Lysyanskaya message-independent (CLI) signature protocol.
Parameters
[out] t - the first part of the private key.
[out] u - the second part of the private key.
[out] v - the third part of the private key.
[out] x - the first part of the public key.
[out] y - the second part of the public key.
[out] z - the third part of the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 168 of file relic_cp_cls.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), g2_mul_gen(), pc_get_ord, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_cli_sig()
int cp_cli_sig (g1_t a, g1_t A, g1_t b, g1_t B, g1_t c, const uint8_t * msg, size_t len, const bn_t r, const bn_t t, const bn_t u, const bn_t v)
Signs a message using the CLI protocol.
Parameters
[out] a - one of the components of the signature.
[out] A - one of the components of the signature.
[out] b - one of the components of the signature.
[out] B - one of the components of the signature.
[out] c - one of the components of the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] r - the per-message randomness.
[in] t - the first part of the private key.
[in] u - the second part of the private key.
[in] v - the third part of the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 194 of file relic_cp_cls.c.
References bn_add(), bn_free, bn_mod, bn_mul, bn_new, bn_null, bn_read_bin(), g1_add, g1_mul(), g1_norm, g1_rand, pc_get_ord, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_cli_ver()
int cp_cli_ver (g1_t a, g1_t A, g1_t b, g1_t B, g1_t c, const uint8_t * msg, size_t len, const bn_t r, const g2_t x, const g2_t y, const g2_t z)
Verifies a message signed using the CLI protocol.
Parameters
[in] a - one of the components of the signature.
[in] A - one of the components of the signature.
[in] b - one of the components of the signature.
[in] B - one of the components of the signature.
[in] c - one of the components of the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] r - the per-message randomness.
[in] x - the first part of the public key.
[in] y - the second part of the public key.
[in] z - the third part of the public key.
Returns
a boolean value indicating the verification result.
Definition at line 242 of file relic_cp_cls.c.
References bn_free, bn_mod, bn_new, bn_null, bn_read_bin(), ERR_CAUGHT, g1_add, g1_copy, g1_free, g1_is_infty, g1_mul_sim, g1_new, g1_norm, g1_null, g2_copy, g2_free, g2_get_gen, g2_neg, g2_new, g2_null, gt_free, gt_is_unity, gt_new, gt_null, pc_get_ord, pc_map_sim, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
cp_clb_gen()
int cp_clb_gen (bn_t t, bn_t u, bn_t v[], g2_t x, g2_t y, g2_t z[], size_t l)
Definition at line 328 of file relic_cp_cls.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), g2_mul_gen(), pc_get_ord, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_clb_sig()
int cp_clb_sig (g1_t a, g1_t A[], g1_t b, g1_t B[], g1_t c, const uint8_t * ms[], const size_t ls[], const bn_t t, const bn_t u, const bn_t v[], size_t l)
Definition at line 356 of file relic_cp_cls.c.
References bn_add(), bn_free, bn_mod, bn_mul, bn_new, bn_null, bn_read_bin(), g1_add, g1_mul(), g1_norm, g1_rand, pc_get_ord, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_clb_ver()
int cp_clb_ver (const g1_t a, const g1_t A[], const g1_t b, const g1_t B[], const g1_t c, const uint8_t * ms[], const size_t ls[], const g2_t x, const g2_t y, const g2_t z[], size_t l)
Definition at line 409 of file relic_cp_cls.c.
References bn_free, bn_mod, bn_new, bn_null, bn_read_bin(), ERR_CAUGHT, g1_add, g1_copy, g1_free, g1_is_infty, g1_mul(), g1_new, g1_norm, g1_null, g2_copy, g2_free, g2_get_gen, g2_neg, g2_new, g2_null, gt_free, gt_is_unity, gt_new, gt_null, pc_get_ord, pc_map_sim, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.