RELIC: src/ed/relic_ed_add.c File Reference
relic_ed_add.c File Reference
Edwards curves over prime fields.
#include <assert.h>
#include "relic_core.h"
#include "relic_label.h"
Functions
void ed_add_basic (ed_t r, const ed_t p, const ed_t q)
void ed_sub_basic (ed_t r, const ed_t p, const ed_t q)
void ed_add_projc (ed_t r, const ed_t p, const ed_t q)
void ed_sub_projc (ed_t r, const ed_t p, const ed_t q)
void ed_add_extnd (ed_t r, const ed_t p, const ed_t q)
void ed_sub_extnd (ed_t r, const ed_t p, const ed_t q)
Detailed Description
Implementation of the point addition on prime elliptic twisted Edwards curves.
Version
$Id$
Definition in file relic_ed_add.c.
Function Documentation
ed_add_basic()
void ed_add_basic (ed_t r, const ed_t p, const ed_t q)
Adds two Edwards elliptic curve points represented in affine coordinates.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 44 of file relic_ed_add.c.
References BASIC, core_get(), ERR_CAUGHT, fp_add, fp_add_dig(), fp_copy(), fp_free, fp_inv, fp_mul, fp_neg, fp_new, fp_null, fp_sub, fp_sub_dig(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ed_sub_basic().
ed_sub_basic()
void ed_sub_basic (ed_t r, const ed_t p, const ed_t q)
Subtracts an Edwards elliptic curve point from another, both points represented by affine coordinates..
Parameters
[out] r - the result.
[in] p - the first point.
[in] q - the second point.
Definition at line 96 of file relic_ed_add.c.
References BASIC, ed_add_basic(), ed_free, ed_neg_basic(), ed_new, ed_null, ed_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ed_add_projc()
void ed_add_projc (ed_t r, const ed_t p, const ed_t q)
Adds two Edwards elliptic curve points represented in projective coordinates.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 125 of file relic_ed_add.c.
References core_get(), ERR_CAUGHT, fp_add, fp_free, fp_mul, fp_new, fp_null, fp_sqr, fp_sub, PROJC, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ed_sub_projc().
ed_sub_projc()
void ed_sub_projc (ed_t r, const ed_t p, const ed_t q)
Subtracts an Edwards elliptic curve point from another, both represented by projective coordinates.
Parameters
[out] r - the result.
[in] p - the first point.
[in] q - the second point.
Definition at line 202 of file relic_ed_add.c.
References ed_add_projc(), ed_free, ed_neg_projc(), ed_new, ed_null, ed_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ed_add_extnd()
void ed_add_extnd (ed_t r, const ed_t p, const ed_t q)
Adds two Edwards elliptic curve points represented in exteded coordinates.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 230 of file relic_ed_add.c.
References core_get(), ERR_CAUGHT, EXTND, fp_add, fp_free, fp_mul, fp_new, fp_null, fp_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ed_sub_extnd().
ed_sub_extnd()
void ed_sub_extnd (ed_t r, const ed_t p, const ed_t q)
Subtracts an Edwards elliptic curve point from another, both represented by extended coordinates.
Parameters
[out] r - the result.
[in] p - the first point.
[in] q - the second point.
Definition at line 296 of file relic_ed_add.c.
References ed_add_extnd(), ed_free, ed_neg_projc(), ed_new, ed_null, ed_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.