RELIC: src/fp/relic_fp_prime.c File Reference
relic_fp_prime.c File Reference
Prime field arithmetic
#include "relic_core.h"
#include "relic_ep.h"
#include "relic_fpx.h"
#include "relic_bn_low.h"
#include "relic_fp_low.h"
Functions
static void fp_prime_set (const bn_t p)
void fp_prime_init (void)
void fp_prime_clean (void)
const dig_t * fp_prime_get (void)
const dig_t * fp_prime_get_rdc (void)
void fp_prime_get_par (bn_t x)
const int * fp_prime_get_par_sps (int *len)
const int * fp_prime_get_sps (int *len)
const dig_t * fp_prime_get_conv (void)
const dig_t * fp_prime_get_srt (void)
const dig_t * fp_prime_get_crt (void)
dig_t fp_prime_get_mod8 (void)
dig_t fp_prime_get_mod18 (void)
int fp_prime_get_qnr (void)
int fp_prime_get_cnr (void)
int fp_prime_get_2ad (void)
void fp_prime_set_dense (const bn_t p)
void fp_prime_set_pairf (const bn_t x, int pairf)
void fp_prime_set_pmers (const int *f, size_t len)
void fp_prime_calc (void)
void fp_prime_conv (fp_t c, const bn_t a)
void fp_prime_conv_dig (fp_t c, dig_t a)
void fp_prime_back (bn_t c, const fp_t a)
Detailed Description
Implementation of the prime field prime manipulation functions.
Definition in file relic_fp_prime.c.
Function Documentation
fp_prime_set()
static void fp_prime_set (const bn_t p) static
Assigns the prime field modulus.
Parameters
[in] p - the new prime field modulus.
Definition at line 47 of file relic_fp_prime.c.
References _ctx_t::ad2, bn_add_dig(), bn_copy(), bn_div_dig(), bn_free, bn_hlv(), bn_is_even(), bn_lsh(), bn_mod, bn_mod_dig(), bn_mod_pre_monty(), bn_new, bn_null, bn_set_2b(), bn_set_dig(), bn_sub_dig(), bn_trim(), _ctx_t::cnr, _ctx_t::conv, core_get(), _ctx_t::crt, bn_st::dp, dv_copy(), ERR_CAUGHT, ERR_NO_VALID, fp_add, fp_add_dig(), fp_exp, fp_free, fp_hlv, fp_is_cub(), fp_is_sqr(), fp_mul, fp_mulm_low(), fp_neg, fp_new, fp_null, fp_param_get(), FP_PRIME, fp_prime_calc(), fp_prime_get(), fp_prime_get_cnr(), fp_set_dig(), _ctx_t::inv, K18_638, _ctx_t::mod18, _ctx_t::mod8, _ctx_t::one, _ctx_t::over3, _ctx_t::prime, _ctx_t::qnr, RLC_CATCH_ANY, RLC_DIG, RLC_DIG_LOG, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, RLC_TRY, _ctx_t::srt, _ctx_t::u, and bn_st::used.
Referenced by fp_prime_set_dense(), and fp_prime_set_pmers().
fp_prime_init()
void fp_prime_init (void)
Initializes the prime field arithmetic layer.
Definition at line 238 of file relic_fp_prime.c.
References bn_make(), _ctx_t::conv, core_get(), _ctx_t::crt, _ctx_t::fp_id, _ctx_t::inv, _ctx_t::one, _ctx_t::over3, _ctx_t::par, _ctx_t::prime, RLC_FP_DIGS, _ctx_t::sps, _ctx_t::sps_len, and _ctx_t::srt.
Referenced by core_init().
fp_prime_clean()
void fp_prime_clean (void)
Finalizes the prime field arithmetic layer.
Definition at line 259 of file relic_fp_prime.c.
References bn_clean(), _ctx_t::conv, core_get(), _ctx_t::crt, _ctx_t::fp_id, _ctx_t::inv, _ctx_t::one, _ctx_t::over3, _ctx_t::par, _ctx_t::prime, _ctx_t::sps, _ctx_t::sps_len, and _ctx_t::srt.
Referenced by core_clean().
fp_prime_get()
const dig_t * fp_prime_get (void)
Returns the order of the prime field.
Returns
the order of the prime field.
Definition at line 282 of file relic_fp_prime.c.
References core_get(), bn_st::dp, and _ctx_t::prime.
Referenced by ed_map_ell2_5mod8(), ed_param_set(), ep2_pck(), ep2_upk(), ep_pck(), ep_upk(), fp2_field_init(), fp2_srt(), fp3_field_init(), fp3_srt(), fp4_field_init(), fp8_field_init(), fp_add_basic(), fp_add_dig(), fp_crt(), fp_dbl_basic(), fp_hlv_basic(), fp_inv_basic(), fp_inv_binar(), fp_inv_divst(), fp_inv_exgcd(), fp_inv_jmpds(), fp_inv_monty(), fp_is_cub(), fp_is_zero(), fp_neg_basic(), fp_norm(), fp_prime_set(), fp_print(), fp_rand(), fp_rdc_basic(), fp_rdc_monty_basic(), fp_rdc_quick(), fp_smb_basic(), fp_smb_binar(), fp_smb_divst(), fp_smb_jmpds(), fp_srt(), fp_sub_basic(), fp_sub_dig(), pp_exp_k1(), and pp_exp_k2().
fp_prime_get_rdc()
const dig_t * fp_prime_get_rdc (void)
Returns the additional value used for modular reduction.
Returns
the additional value used for modular reduction.
Definition at line 286 of file relic_fp_prime.c.
References core_get(), and _ctx_t::u.
Referenced by fp_rdc_monty_basic().
fp_prime_get_par()
void fp_prime_get_par (bn_t x)
Returns the variable used to parametrize the given prime modulus.
Parameters
[out] x - the integer parameter.
Definition at line 290 of file relic_fp_prime.c.
References bn_copy(), and core_get().
Referenced by bn_rec_sac(), ep2_frb(), ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep2_mul_gls_imp(), ep2_mul_reg_gls(), ep2_mul_sim_endom(), ep2_mul_sim_lot(), ep3_mul_cof_fm18(), ep3_mul_cof_k18(), ep3_mul_cof_sg18(), ep3_mul_gls_imp(), ep3_mul_reg_gls(), ep3_mul_sim_lot(), ep4_mul_cof_afg16(), ep4_mul_cof_b24(), ep4_mul_cof_fm16(), ep4_mul_cof_k16(), ep4_mul_gls_imp(), ep4_mul_reg_gls(), ep4_mul_sim_lot(), ep8_mul_cof(), ep8_mul_gls_imp(), ep8_mul_reg_gls(), ep8_mul_sim_lot(), ep_mul_cof(), ep_param_set(), fp12_exp_cyc_sim(), g1_is_valid(), g2_is_valid(), gt_exp_gls_naf(), gt_exp_gls_sac(), gt_exp_reg_gls(), gt_exp_reg_sac(), gt_is_valid(), pp_exp_afg16(), pp_exp_b12(), pp_exp_bn(), pp_exp_fm(), pp_exp_fm16(), pp_exp_k24(), pp_exp_k48(), pp_exp_k54(), pp_exp_k8(), pp_exp_kss(), pp_exp_kss(), pp_exp_sg(), pp_exp_sm9(), pp_map_k24(), pp_map_k48(), pp_map_k54(), pp_map_oatep_k12(), pp_map_oatep_k16(), pp_map_oatep_k18(), pp_map_oatep_k8(), pp_map_sim_k24(), pp_map_sim_k48(), pp_map_sim_oatep_k12(), pp_map_sim_oatep_k16(), pp_map_sim_oatep_k18(), and pp_map_sim_oatep_k8().
fp_prime_get_par_sps()
const int * fp_prime_get_par_sps (int * len)
Returns the absolute value of the variable used to parameterize the given prime modulus in sparse form.
Parameters
[out] len - the length of the representation.
Definition at line 294 of file relic_fp_prime.c.
References core_get(), _ctx_t::par_len, and _ctx_t::par_sps.
Referenced by gt_is_valid(), pp_exp_b12(), pp_exp_bn(), pp_exp_fm(), pp_exp_k24(), pp_exp_k48(), pp_exp_k54(), pp_exp_kss(), pp_exp_sg(), and pp_exp_sm9().
fp_prime_get_sps()
const int * fp_prime_get_sps (int * len)
Returns the prime stored in special form. The most significant bit is RLC_FP_BITS.
Parameters
[out] len - the number of returned bits, can be NULL.
Returns
the prime represented by it non-zero bits.
Definition at line 308 of file relic_fp_prime.c.
References core_get(), RLC_TERMS, _ctx_t::sps, and _ctx_t::sps_len.
fp_prime_get_conv()
const dig_t * fp_prime_get_conv (void)
Returns the additional value used for conversion from multiple precision integer to prime field element.
Returns
the additional value used for importing integers.
Definition at line 327 of file relic_fp_prime.c.
References _ctx_t::conv, core_get(), and bn_st::dp.
Referenced by fp_inv_monty().
fp_prime_get_srt()
const dig_t * fp_prime_get_srt (void)
Returns a 2^f-root of unity modulo the prime field modulus, for the maximum f such that 2^f divides (p-1).
Returns
the root of unity.
Definition at line 335 of file relic_fp_prime.c.
References core_get(), bn_st::dp, and _ctx_t::srt.
Referenced by fp3_srt(), and fp_srt().
fp_prime_get_crt()
const dig_t * fp_prime_get_crt (void)
Returns a 3^f-root of unity modulo the prime field modulus, for the maximum f such that 3^f divides (p-1).
Returns
the root of unity.
Definition at line 339 of file relic_fp_prime.c.
References core_get(), _ctx_t::crt, and bn_st::dp.
Referenced by fp_crt().
fp_prime_get_mod8()
dig_t fp_prime_get_mod8 (void)
Returns the result of prime order mod 8.
Returns
the result of prime order mod 8.
Definition at line 343 of file relic_fp_prime.c.
References core_get(), and _ctx_t::mod8.
Referenced by fp16_frb(), fp24_frb(), fp2_mul_nor_basic(), fp2_srt(), fp3_srt(), fp48_frb(), fp8_frb(), fp_param_set_any_tower(), and fp_srt().
fp_prime_get_mod18()
dig_t fp_prime_get_mod18 (void)
Returns the result of prime order mod 18.
Returns
the result of prime order mod 18.
Definition at line 347 of file relic_fp_prime.c.
References core_get(), and _ctx_t::mod18.
Referenced by fp3_mul_nor(), fp4_frb(), fp4_mul_frb(), fp_crt(), fp_is_cub(), and fp_param_set_any_tower().
fp_prime_get_qnr()
int fp_prime_get_qnr (void)
Returns a non-quadratic residue in the prime field.
Returns
the non-quadratic residue.
Definition at line 351 of file relic_fp_prime.c.
References core_get(), and _ctx_t::qnr.
Referenced by fp2_inv(), fp2_mul_art(), fp2_mul_basic(), fp2_sqr_basic(), fp2_srt(), and fp_prime_calc().
fp_prime_get_cnr()
int fp_prime_get_cnr (void)
Returns a non-cubic residue in the prime field.
Returns
the non-cubic residue.
Definition at line 355 of file relic_fp_prime.c.
References _ctx_t::cnr, and core_get().
Referenced by fp3_field_init(), fp3_inv(), fp3_mul_art(), fp3_mul_basic(), fp3_sqr_basic(), fp_prime_calc(), and fp_prime_set().
fp_prime_get_2ad()
int fp_prime_get_2ad (void)
Returns the 2-adicity of the prime modulus.
Returns
the 2-adicity of the modulus.
Definition at line 359 of file relic_fp_prime.c.
References _ctx_t::ad2, and core_get().
Referenced by ed_param_set(), fp3_srt(), and fp_srt().
fp_prime_set_dense()
void fp_prime_set_dense (const bn_t p)
Assigns the prime field modulus to a non-sparse prime.
Parameters
[in] p - the new prime field modulus.
Definition at line 363 of file relic_fp_prime.c.
References ERR_NO_CONFIG, fp_prime_set(), and RLC_THROW.
Referenced by fp_param_set(), fp_param_set_any_dense(), and fp_prime_set_pairf().
fp_prime_set_pairf()
void fp_prime_set_pairf (const bn_t x, int pairf)
Assigns the prime field modulus to a parametrization from a family of pairing-friendly curves.
Definition at line 370 of file relic_fp_prime.c.
References bn_add(), bn_add_dig(), bn_bits(), bn_copy(), bn_div(), bn_div_dig(), bn_free, bn_lsh(), bn_mul, bn_mul_dig(), bn_new, bn_null, bn_rec_naf(), bn_set_dig(), bn_sqr, bn_sub(), bn_sub_dig(), core_get(), EP_AFG16, EP_B12, EP_B24, EP_B48, EP_BN, EP_FM16, EP_FM18, EP_K16, EP_K18, EP_SG18, EP_SG54, ERR_CAUGHT, ERR_NO_VALID, fp_prime_set_dense(), _ctx_t::par, _ctx_t::par_len, _ctx_t::par_sps, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_TERMS, RLC_THROW, and RLC_TRY.
Referenced by fp_param_set().
fp_prime_set_pmers()
void fp_prime_set_pmers (const int * spars, size_t len)
Assigns the prime field modulus to a special form sparse prime.
Parameters
[in] spars - the list of powers of 2 describing the prime.
[in] len - the number of powers.
Definition at line 676 of file relic_fp_prime.c.
References bn_add(), bn_add_dig(), bn_free, bn_new, bn_null, bn_set_2b(), bn_sub(), bn_sub_dig(), core_get(), ERR_CAUGHT, ERR_NO_VALID, fp_prime_set(), RLC_CATCH_ANY, RLC_FINALLY, RLC_TERMS, RLC_THROW, RLC_TRY, _ctx_t::sps, and _ctx_t::sps_len.
Referenced by fp_param_set().
fp_prime_calc()
void fp_prime_calc (void)
Computes the constants needed for evaluating Frobenius maps in higher extension fields.
Definition at line 727 of file relic_fp_prime.c.
References fp2_field_init(), fp3_field_init(), fp4_field_init(), fp8_field_init(), fp_prime_get_cnr(), and fp_prime_get_qnr().
Referenced by fp_prime_set().
fp_prime_conv()
void fp_prime_conv (fp_t c, const bn_t a)
Imports a multiple precision integer as a prime field element, doing the necessary conversion.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to import.
Definition at line 740 of file relic_fp_prime.c.
References bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, core_get(), dv_copy(), dv_zero(), ERR_CAUGHT, fp_mul, fp_zero(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
Referenced by cp_cmlhs_sig(), ep2_map_basic(), ep2_map_swift(), ep3_map(), ep4_map(), ep8_map(), ep_map_basic_impl(), ep_map_swift_impl(), fp_inv_binar(), fp_inv_exgcd(), fp_read_bin(), and fp_read_str().
fp_prime_conv_dig()
void fp_prime_conv_dig (fp_t c, dig_t a)
Imports a single digit as a prime field element, doing the necessary conversion.
Parameters
[out] c - the result.
[in] a - the digit to import.
Definition at line 770 of file relic_fp_prime.c.
References bn_null, _ctx_t::conv, core_get(), bn_st::dp, dv_copy(), dv_free, dv_new, dv_zero(), ERR_CAUGHT, fp_mul1_low(), fp_rdc, fp_zero(), _ctx_t::one, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
Referenced by detect_opt(), fp_cmp_dig(), fp_mul_dig(), fp_read_bin(), fp_read_str(), and fp_set_dig().
fp_prime_back()
void fp_prime_back (bn_t c, const fp_t a)
Exports a prime field element as a multiple precision integer, doing the necessary conversion.
Parameters
[out] c - the result.
[in] a - the prime field element to export.
Definition at line 801 of file relic_fp_prime.c.
References bn_grow(), bn_trim(), dv_copy(), dv_free, dv_new, dv_null, dv_zero(), ERR_CAUGHT, fp_norm(), fp_rdc, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_POS, RLC_THROW, and RLC_TRY.
Referenced by cp_cmlhs_onv(), cp_cmlhs_ver(), ed_map_ell2_5mod8(), ed_param_set(), ep2_curve_set_map(), ep2_map_swift(), ep2_pck(), ep2_upk(), ep3_map(), ep4_map(), ep8_map(), ep_curve_set_map(), ep_pck(), ep_upk(), fp2_sgn0(), fp_inv_binar(), fp_inv_exgcd(), fp_is_even(), fp_print(), fp_size_str(), fp_write_bin(), and fp_write_str().