RELIC: include/low/relic_fpx_low.h File Reference
relic_fpx_low.h File Reference
Prime field extensions.
#include "relic_fpx.h"
Functions
void fp2_addn_low (fp2_t c, const fp2_t a, const fp2_t b)
void fp2_addm_low (fp2_t c, const fp2_t a, const fp2_t b)
void fp2_addd_low (dv2_t c, dv2_t a, dv2_t b)
void fp2_addc_low (dv2_t c, dv2_t a, dv2_t b)
void fp2_subn_low (fp2_t c, const fp2_t a, const fp2_t b)
void fp2_subm_low (fp2_t c, const fp2_t a, const fp2_t b)
void fp2_subd_low (dv2_t c, dv2_t a, dv2_t b)
void fp2_subc_low (dv2_t c, dv2_t a, dv2_t b)
void fp2_dbln_low (fp2_t c, const fp2_t a)
void fp2_dblm_low (fp2_t c, const fp2_t a)
void fp2_norm_low (fp2_t c, const fp2_t a)
void fp2_norh_low (dv2_t c, dv2_t a)
void fp2_nord_low (dv2_t c, dv2_t a)
void fp2_muln_low (dv2_t c, const fp2_t a, const fp2_t b)
void fp2_mulm_low (fp2_t c, const fp2_t a, const fp2_t b)
void fp2_sqrn_low (dv2_t c, const fp2_t a)
void fp2_sqrm_low (fp2_t c, const fp2_t a)
void fp2_rdcn_low (fp2_t c, dv2_t a)
void fp3_addn_low (fp3_t c, const fp3_t a, const fp3_t b)
void fp3_addm_low (fp3_t c, const fp3_t a, const fp3_t b)
void fp3_addd_low (dv3_t c, dv3_t a, dv3_t b)
void fp3_addc_low (dv3_t c, dv3_t a, dv3_t b)
void fp3_subn_low (fp3_t c, const fp3_t a, const fp3_t b)
void fp3_subm_low (fp3_t c, const fp3_t a, const fp3_t b)
void fp3_subd_low (dv3_t c, dv3_t a, dv3_t b)
void fp3_subc_low (dv3_t c, dv3_t a, dv3_t b)
void fp3_dbln_low (fp3_t c, const fp3_t a)
void fp3_dblm_low (fp3_t c, const fp3_t a)
void fp3_nord_low (dv3_t c, dv3_t a)
void fp3_muln_low (dv3_t c, const fp3_t a, const fp3_t b)
void fp3_mulc_low (dv3_t c, const fp3_t a, const fp3_t b)
void fp3_mulm_low (fp3_t c, const fp3_t a, const fp3_t b)
void fp3_sqrn_low (dv3_t c, const fp3_t a)
void fp3_sqrm_low (fp3_t c, const fp3_t a)
void fp3_rdcn_low (fp3_t c, dv3_t a)
Detailed Description
Interface of the low-level prime extension field arithmetic module.
Definition in file relic_fpx_low.h.
Function Documentation
fp2_addn_low()
void fp2_addn_low (fp2_t c, const fp2_t a, const fp2_t b)
Adds two quadratic extension field elements of the same size. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first field element to add.
[in] b - the second field element to add.
Referenced by fp6_mul_unr().
fp2_addm_low()
void fp2_addm_low (fp2_t c, const fp2_t a, const fp2_t b)
Adds two quadratic extension field elements of the same size with integrated modular reduction. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first field element to add.
[in] b - the second field element to add.
Referenced by fp12_sqr_cyc_lazyr(), fp12_sqr_pck_lazyr(), fp12_sqr_unr(), fp2_add_integ(), fp4_mul_dxs_unr(), fp4_mul_unr(), fp4_sqr_unr(), fp6_mul_dxs_unr_lazyr(), fp6_mul_unr(), and fp6_sqr_unr().
fp2_addd_low()
void fp2_addd_low (dv2_t c, dv2_t a, dv2_t b)
Adds two double-precision quadratic extension field elements of the same size. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first field element to add.
[in] b - the second field element to add.
Referenced by fp12_sqr_unr(), and pp_dbl_k12_projc_lazyr().
fp2_addc_low()
void fp2_addc_low (dv2_t c, dv2_t a, dv2_t b)
Adds two double-precision quadratic extension field elements of the same size and corrects the result by conditionally adding 2^(RLC_FP_DIGS * WSIZE) * p. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first field element to add.
[in] b - the second field element to add.
Referenced by fp12_mul_dxs_lazyr(), fp12_mul_unr(), fp12_sqr_cyc_lazyr(), fp12_sqr_pck_lazyr(), fp12_sqr_unr(), fp16_mul_dxs_lazyr(), fp16_mul_unr(), fp16_sqr_unr(), fp24_mul_unr(), fp24_sqr_cyc_lazyr(), fp24_sqr_pck_lazyr(), fp24_sqr_unr(), fp48_sqr_pck_lazyr(), fp4_mul_unr(), fp4_sqr_unr(), fp6_mul_dxs_unr_lazyr(), fp6_mul_unr(), fp6_sqr_unr(), fp8_mul_dxs(), fp8_mul_unr(), fp8_sqr_unr(), and pp_dbl_k8_projc_lazyr_new().
fp2_subn_low()
void fp2_subn_low (fp2_t c, const fp2_t a, const fp2_t b)
Subtracts a quadratic extension field element from another of the same size. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the first field element.
[in] b - the field element to subtract.
fp2_subm_low()
void fp2_subm_low (fp2_t c, const fp2_t a, const fp2_t b)
Subtracts a quadratic extension field element from another of the same size with integrated modular reduction. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the first field element.
[in] b - the field element to subtract.
Referenced by fp12_sqr_cyc_lazyr(), fp12_sqr_pck_lazyr(), fp12_sqr_unr(), fp2_sub_integ(), and fp6_sqr_unr().
fp2_subd_low()
void fp2_subd_low (dv2_t c, dv2_t a, dv2_t b)
Subtracts a double-precision quadratic extension field element from another of the same size. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the first field element to add.
[in] b - the second field element to add.
fp2_subc_low()
void fp2_subc_low (dv2_t c, dv2_t a, dv2_t b)
Subtracts a double-precision quadratic extension field element from another of the same size and corrects the result by conditionally adding 2^(RLC_FP_DIGS * WSIZE) * p. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the first field element to add.
[in] b - the second field element to add.
Referenced by fp12_mul_dxs_lazyr(), fp12_mul_unr(), fp12_sqr_cyc_lazyr(), fp12_sqr_pck_lazyr(), fp12_sqr_unr(), fp16_mul_dxs_lazyr(), fp16_mul_unr(), fp16_sqr_unr(), fp24_mul_unr(), fp24_sqr_cyc_lazyr(), fp24_sqr_pck_lazyr(), fp24_sqr_unr(), fp48_sqr_pck_lazyr(), fp4_mul_dxs_unr(), fp4_mul_unr(), fp4_sqr_unr(), fp6_mul_dxs_unr_lazyr(), fp6_mul_unr(), fp6_sqr_unr(), fp8_mul_dxs(), fp8_mul_unr(), fp8_sqr_unr(), pp_add_k12_projc_lazyr(), pp_dbl_k12_projc_lazyr(), and pp_dbl_k8_projc_lazyr_new().
fp2_dbln_low()
void fp2_dbln_low (fp2_t c, const fp2_t a)
Doubles a quadratic extension field element. Computes c = a + a.
Parameters
[out] c - the result.
[in] a - the first field element to multiply.
fp2_dblm_low()
void fp2_dblm_low (fp2_t c, const fp2_t a)
Doubles a quadratic extension field element with integrated modular reduction. Computes c = a + a.
Parameters
[out] c - the result.
[in] a - the field element to double.
Referenced by fp12_sqr_cyc_lazyr(), fp12_sqr_pck_lazyr(), fp2_dbl_integ(), and fp6_sqr_unr().
fp2_norm_low()
void fp2_norm_low (fp2_t c, const fp2_t a)
Multiplies a quadratic extension field element by the quadratic non-residue. Computes c = a * E.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
Referenced by fp12_sqr_cyc_lazyr(), fp12_sqr_pck_lazyr(), and fp2_mul_nor_integ().
fp2_norh_low()
void fp2_norh_low (dv2_t c, dv2_t a)
Multiplies a double-precision quadratic extension field element by the quadratic non-residue, reducing only half of the result. Computes c = a * E.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
Referenced by fp12_sqr_cyc_lazyr(), fp12_sqr_pck_lazyr(), fp4_mul_dxs_unr(), and fp4_sqr_unr().
fp2_nord_low()
void fp2_nord_low (dv2_t c, dv2_t a)
Multiplies a double-precision quadratic extension field element by the quadratic non-residue. Computes c = a * E.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
Referenced by fp12_mul_dxs_lazyr(), fp12_mul_unr(), fp12_sqr_unr(), fp16_mul_dxs_lazyr(), fp16_mul_unr(), fp16_sqr_unr(), fp24_mul_unr(), fp24_sqr_cyc_lazyr(), fp24_sqr_pck_lazyr(), fp24_sqr_unr(), fp48_sqr_pck_lazyr(), fp4_mul_unr(), fp6_mul_dxs_unr_lazyr(), fp6_mul_unr(), fp6_sqr_unr(), fp8_mul_dxs(), fp8_mul_unr(), fp8_sqr_unr(), and pp_dbl_k8_projc_lazyr_new().
fp2_muln_low()
void fp2_muln_low (dv2_t c, const fp2_t a, const fp2_t b)
Multiplies two quadratic extension field elements of the same size. Computes c = a * b.
Parameters
[out] c - the result.
[in] a - the first field element to multiply.
[in] b - the second field element to multiply.
Referenced by fp12_mul_dxs_lazyr(), fp4_mul_dxs_unr(), fp4_mul_unr(), fp6_mul_dxs_unr_lazyr(), fp6_mul_unr(), fp6_sqr_unr(), pp_add_k12_projc_lazyr(), and pp_dbl_k8_projc_lazyr_new().
fp2_mulm_low()
void fp2_mulm_low (fp2_t c, const fp2_t a, const fp2_t b)
Multiplies two quadratic extension field elements of the same size with embedded modular reduction. Computes c = (a * b) mod p.
Parameters
[out] c - the result.
[in] a - the first field element to multiply.
[in] b - the second field element to multiply.
Referenced by fp2_mul_integ().
fp2_sqrn_low()
void fp2_sqrn_low (dv2_t c, const fp2_t a)
Squares a quadratic extension element. Computes c = a * a.
Parameters
[out] c - the result.
[in] a - the field element to square.
Referenced by fp12_sqr_cyc_lazyr(), fp12_sqr_pck_lazyr(), fp4_sqr_unr(), fp6_sqr_unr(), pp_dbl_k12_projc_lazyr(), and pp_dbl_k8_projc_lazyr_new().
fp2_sqrm_low()
void fp2_sqrm_low (fp2_t c, const fp2_t a)
Squares a quadratic extension field element with integrated modular reduction. Computes c = (a * a) mod p.
Parameters
[out] c - the result.
[in] a - the field element to square.
Referenced by fp12_sqr_cyc_lazyr(), fp12_sqr_pck_lazyr(), and fp2_sqr_integ().
fp2_rdcn_low()
void fp2_rdcn_low (fp2_t c, dv2_t a)
Reduces a quadratic extension element modulo the configured prime p. Computes c = a mod p.
Parameters
[out] c - the result.
[in] a - the digit vector to reduce.
Referenced by fp12_mul_dxs_lazyr(), fp12_mul_lazyr(), fp12_sqr_cyc_lazyr(), fp12_sqr_lazyr(), fp12_sqr_pck_lazyr(), fp16_mul_dxs_lazyr(), fp16_mul_lazyr(), fp16_sqr_lazyr(), fp24_mul_lazyr(), fp24_sqr_cyc_lazyr(), fp24_sqr_lazyr(), fp24_sqr_pck_lazyr(), fp2_rdc_integ(), fp48_sqr_pck_lazyr(), fp4_mul_lazyr(), fp4_sqr_lazyr(), fp6_mul_lazyr(), fp6_sqr_lazyr(), fp8_mul_dxs(), fp8_mul_lazyr(), fp8_sqr_lazyr(), pp_add_k12_projc_lazyr(), pp_dbl_k12_projc_lazyr(), and pp_dbl_k8_projc_lazyr_new().
fp3_addn_low()
void fp3_addn_low (fp3_t c, const fp3_t a, const fp3_t b)
Adds two cubic extension field elements of the same size. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first field element to add.
[in] b - the second field element to add.
fp3_addm_low()
void fp3_addm_low (fp3_t c, const fp3_t a, const fp3_t b)
Adds two cubic extension field elements of the same size with integrated modular reduction. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first field element to add.
[in] b - the second field element to add.
Referenced by fp18_sqr_cyc_lazyr(), fp18_sqr_pck_lazyr(), fp3_add_integ(), fp9_mul_dxs_unr_lazyr(), fp9_mul_unr(), and fp9_sqr_unr().
fp3_addd_low()
void fp3_addd_low (dv3_t c, dv3_t a, dv3_t b)
Adds two double-precision cubic extension field elements of the same size. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first field element to add.
[in] b - the second field element to add.
fp3_addc_low()
void fp3_addc_low (dv3_t c, dv3_t a, dv3_t b)
Adds two double-precision cubic extension field elements of the same size and corrects the result by conditionally adding 3^(RLC_FP_DIGS * WSIZE) * p. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first field element to add.
[in] b - the second field element to add.
Referenced by fp18_mul_dxs_lazyr(), fp18_mul_unr(), fp18_sqr_cyc_lazyr(), fp18_sqr_pck_lazyr(), fp18_sqr_unr(), fp54_sqr_pck_lazyr(), fp9_mul_dxs_unr_lazyr(), fp9_mul_unr(), and fp9_sqr_unr().
fp3_subn_low()
void fp3_subn_low (fp3_t c, const fp3_t a, const fp3_t b)
Subtracts a cubic extension field element from another of the same size. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the first field element.
[in] b - the field element to subtract.
fp3_subm_low()
void fp3_subm_low (fp3_t c, const fp3_t a, const fp3_t b)
Subtracts a cubic extension field element from another of the same size with integrated modular reduction. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the first field element.
[in] b - the field element to subtract.
Referenced by fp18_sqr_cyc_lazyr(), fp18_sqr_pck_lazyr(), fp3_sub_integ(), and fp9_sqr_unr().
fp3_subd_low()
void fp3_subd_low (dv3_t c, dv3_t a, dv3_t b)
Subtracts a double-precision cubic extension field element from another of the same size. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the first field element to add.
[in] b - the second field element to add.
fp3_subc_low()
void fp3_subc_low (dv3_t c, dv3_t a, dv3_t b)
Subtracts a double-precision cubic extension field element from another of the same size and corrects the result by conditionally adding 3^(RLC_FP_DIGS * WSIZE) * p. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the first field element to add.
[in] b - the second field element to add.
Referenced by fp18_mul_dxs_lazyr(), fp18_mul_unr(), fp18_sqr_cyc_lazyr(), fp18_sqr_pck_lazyr(), fp18_sqr_unr(), fp54_sqr_pck_lazyr(), fp9_mul_dxs_unr_lazyr(), fp9_mul_unr(), fp9_sqr_unr(), and pp_add_k18_projc_lazyr().
fp3_dbln_low()
void fp3_dbln_low (fp3_t c, const fp3_t a)
Doubles a cubic extension field element. Computes c = a + a.
Parameters
[out] c - the result.
[in] a - the first field element to multiply.
fp3_dblm_low()
void fp3_dblm_low (fp3_t c, const fp3_t a)
Doubles a cubic extension field element with integrated modular reduction. Computes c = a + a.
Parameters
[out] c - the result.
[in] a - the field element to double.
Referenced by fp18_sqr_cyc_lazyr(), fp18_sqr_pck_lazyr(), fp3_dbl_integ(), and fp9_sqr_unr().
fp3_nord_low()
void fp3_nord_low (dv3_t c, dv3_t a)
Multiplies a double-precision cubic extension field element by the cubic non-residue. Computes c = a * E.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
Referenced by fp18_mul_dxs_lazyr(), fp18_mul_unr(), fp18_sqr_cyc_lazyr(), fp18_sqr_pck_lazyr(), fp18_sqr_unr(), fp54_sqr_pck_lazyr(), fp9_mul_dxs_unr_lazyr(), fp9_mul_unr(), and fp9_sqr_unr().
fp3_muln_low()
void fp3_muln_low (dv3_t c, const fp3_t a, const fp3_t b)
Multiplies two cubic extension field elements of the same size. Computes c = a * b.
Parameters
[out] c - the result.
[in] a - the first field element to multiply.
[in] b - the second field element to multiply.
Referenced by fp18_mul_dxs_lazyr(), fp9_mul_dxs_unr_lazyr(), fp9_mul_unr(), fp9_sqr_unr(), and pp_add_k18_projc_lazyr().
fp3_mulc_low()
void fp3_mulc_low (dv3_t c, const fp3_t a, const fp3_t b)
Multiplies two cubic extension elements of the same size and corrects the result by adding (2^(RLC_FP_DIGS * WSIZE) * p)/4. This function should be used when the RLC_FP_ROOM optimization is detected. Computes c = a * b.
Parameters
[out] c - the result.
[in] a - the first field element to multiply.
[in] b - the second field element to multiply.
fp3_mulm_low()
void fp3_mulm_low (fp3_t c, const fp3_t a, const fp3_t b)
Multiplies two cubic extension field elements of the same size with embedded modular reduction. Computes c = (a * b) mod p.
Parameters
[out] c - the result.
[in] a - the first field element to multiply.
[in] b - the second field element to multiply.
Referenced by fp3_mul_integ().
fp3_sqrn_low()
void fp3_sqrn_low (dv3_t c, const fp3_t a)
Squares a cubic extension element. Computes c = a * a.
Parameters
[out] c - the result.
[in] a - the field element to square.
Referenced by fp18_sqr_cyc_lazyr(), fp18_sqr_pck_lazyr(), and fp9_sqr_unr().
fp3_sqrm_low()
void fp3_sqrm_low (fp3_t c, const fp3_t a)
Squares a cubic extension field element with integrated modular reduction. Computes c = (a * a) mod p.
Parameters
[out] c - the result.
[in] a - the field element to square.
Referenced by fp18_sqr_cyc_lazyr(), fp18_sqr_pck_lazyr(), and fp3_sqr_integ().
fp3_rdcn_low()
void fp3_rdcn_low (fp3_t c, dv3_t a)
Reduces a cubic extension element modulo the configured prime p. Computes c = a mod p.
Parameters
[out] c - the result.
[in] a - the digit vector to reduce.
Referenced by fp18_mul_dxs_lazyr(), fp18_mul_lazyr(), fp18_sqr_cyc_lazyr(), fp18_sqr_lazyr(), fp18_sqr_pck_lazyr(), fp3_rdc_integ(), fp54_sqr_pck_lazyr(), fp9_mul_lazyr(), fp9_sqr_lazyr(), and pp_add_k18_projc_lazyr().