RELIC: src/cp/relic_cp_ibe.c File Reference
relic_cp_ibe.c File Reference
Cryptographic protocols
#include "relic.h"
Functions
int cp_ibe_gen (bn_t master, g1_t pub)
int cp_ibe_gen_prv (g2_t prv, const char *id, const bn_t master)
int cp_ibe_enc (uint8_t *out, size_t *out_len, const uint8_t *in, size_t in_len, const char *id, const g1_t pub)
int cp_ibe_dec (uint8_t *out, size_t *out_len, const uint8_t *in, size_t in_len, const g2_t prv)
Detailed Description
Implementation of the Boneh-Franklin indentity-based encryption.
Definition in file relic_cp_ibe.c.
Function Documentation
cp_ibe_gen()
int cp_ibe_gen (bn_t master, g1_t pub)
Generates a master key for a Private Key Generator (PKG) in the Boneh-Franklin Identity-Based Encryption (BF-IBE).
Parameters
[out] master - the master key.
[out] pub - the public key of the private key generator.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_ibe.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), g1_mul_gen(), pc_get_ord, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_ibe_gen_prv()
int cp_ibe_gen_prv (g2_t prv, const char * id, const bn_t master)
Generates a private key for a user in the BF-IBE protocol.
Parameters
[out] prv - the private key.
[in] id - the identity.
[in] s - the master key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 62 of file relic_cp_ibe.c.
References g2_map, g2_mul(), and RLC_OK.
cp_ibe_enc()
int cp_ibe_enc (uint8_t * out, size_t * out_len, const uint8_t * in, size_t in_len, const char * id, const g1_t pub)
Encrypts a message using the BF-IBE protocol.
Parameters
[out] out - the output buffer.
[in,out] out_len - the buffer capacity and number of bytes written.
[in] in - the input buffer.
[in] in_len - the number of bytes to encrypt.
[in] id - the identity.
[in] pub - the public key of the PKG.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 68 of file relic_cp_ibe.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), ERR_NO_MEMORY, g1_free, g1_mul_gen(), g1_new, g1_null, g1_write_bin, g2_free, g2_map, g2_new, g2_null, gt_exp(), gt_free, gt_new, gt_null, gt_size_bin, gt_write_bin, md_map, pc_get_ord, pc_map, RLC_ALLOCA, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_FP_BYTES, RLC_FREE, RLC_MD_LEN, RLC_MIN, RLC_OK, RLC_THROW, and RLC_TRY.
cp_ibe_dec()
int cp_ibe_dec (uint8_t * out, size_t * out_len, const uint8_t * in, size_t in_len, const g2_t prv)
Decrypts a message using the BF-IBE protocol.
Parameters
[out] out - the output buffer.
[in,out] out_len - the buffer capacity and number of bytes written.
[in] in - the input buffer.
[in] in_len - the number of bytes to decrypt.
[in] pub - the private key of the user.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 145 of file relic_cp_ibe.c.
References ERR_NO_MEMORY, g1_free, g1_new, g1_null, g1_read_bin, gt_free, gt_new, gt_null, gt_size_bin, gt_write_bin, md_map, pc_map, RLC_ALLOCA, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_FP_BYTES, RLC_FREE, RLC_MD_LEN, RLC_MIN, RLC_OK, RLC_THROW, and RLC_TRY.