RELIC: src/bn/relic_bn_mul.c File Reference
relic_bn_mul.c File Reference
Multiple precision integer arithmetic
#include "relic_core.h"
#include "relic_bn_low.h"
Functions
static void bn_mul_karat_imp (bn_t c, const bn_t a, const bn_t b, uint_t level)
void bn_mul_dig (bn_t c, const bn_t a, dig_t b)
void bn_mul_basic (bn_t c, const bn_t a, const bn_t b)
void bn_mul_comba (bn_t c, const bn_t a, const bn_t b)
void bn_mul_karat (bn_t c, const bn_t a, const bn_t b)
Detailed Description
Implementation of the multiple precision multiplication functions.
Definition in file relic_bn_mul.c.
Function Documentation
bn_mul_karat_imp()
static void bn_mul_karat_imp (bn_t c, const bn_t a, const bn_t b, uint_t level) static
Multiplies two multiple precision integers using recursive Karatsuba multiplication.
Parameters
[out] c - the result.
[in] a - the first multiple precision integer.
[in] b - the second multiple precision integer.
[in] level - the number of Karatsuba steps to apply.
Definition at line 50 of file relic_bn_mul.c.
References bn_add(), bn_copy(), bn_free, bn_lsh(), bn_mul_basic(), bn_mul_comba(), bn_mul_karat_imp(), bn_new, bn_new_size, bn_null, bn_sub(), bn_trim(), dv_copy(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_MIN, RLC_THROW, and RLC_TRY.
Referenced by bn_mul_karat(), and bn_mul_karat_imp().
bn_mul_dig()
void bn_mul_dig (bn_t c, const bn_t a, dig_t b)
Multiplies a multiple precision integer by a digit. Computes c = a * b.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to multiply.
[in] b - the digit to multiply.
Definition at line 158 of file relic_bn_mul.c.
References bn_grow(), bn_mul1_low(), bn_trim(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_THROW, and RLC_TRY.
Referenced by bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_lehme(), bn_gen_prime_stron(), bn_mod_pmers(), bn_read_str(), bn_rec_frb(), bn_smb_jac(), cp_bdpe_gen(), cp_mklhs_fun(), ep3_mul_cof_sg18(), ep_mul_cof(), ep_param_set(), fp_param_set(), fp_prime_set_pairf(), g1_is_valid(), g2_is_valid(), gt_is_valid(), pp_map_oatep_k12(), and pp_map_sim_oatep_k12().
bn_mul_basic()
void bn_mul_basic (bn_t c, const bn_t a, const bn_t b)
Multiplies two multiple precision integers using Schoolbook multiplication.
Parameters
[out] c - the result.
[in] a - the first multiple precision integer to multiply.
[in] b - the second multiple precision integer to multiply.
Definition at line 172 of file relic_bn_mul.c.
References bn_copy(), bn_free, bn_mula_low(), bn_new_size, bn_null, bn_trim(), bn_zero(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by bn_mul_karat_imp().
bn_mul_comba()
void bn_mul_comba (bn_t c, const bn_t a, const bn_t b)
Multiplies two multiple precision integers using Comba multiplication.
Parameters
[out] c - the result.
[in] a - the first multiple precision integer to multiply.
[in] b - the second multiple precision integer to multiply.
Definition at line 207 of file relic_bn_mul.c.
References bn_copy(), bn_free, bn_muld_low(), bn_muln_low(), bn_new_size, bn_null, bn_trim(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by bn_mul_karat_imp(), and bn_sqr_karat_imp().
bn_mul_karat()
void bn_mul_karat (bn_t c, const bn_t a, const bn_t b)
Multiplies two multiple precision integers using Karatsuba multiplication.
Parameters
[out] c - the result.
[in] a - the first multiple precision integer to multiply.
[in] b - the second multiple precision integer to multiply.
Definition at line 243 of file relic_bn_mul.c.
References BN_KARAT, and bn_mul_karat_imp().