RELIC: include/relic_bc.h File Reference
relic_bc.h File Reference
Block ciphers
#include "relic_conf.h"
#include "relic_types.h"
#include "relic_label.h"
Macros
#define RLC_BC_LEN 16
Functions
int bc_aes_cbc_enc (uint8_t *out, size_t *out_len, const uint8_t *in, size_t in_len, const uint8_t *key, size_t key_len, const uint8_t *iv)
int bc_aes_cbc_dec (uint8_t *out, size_t *out_len, const uint8_t *in, size_t in_len, const uint8_t *key, size_t key_len, const uint8_t *iv)
Detailed Description
Interface of the module for encrypting with block ciphers.
Definition in file relic_bc.h.
Macro Definition Documentation
RLC_BC_LEN
#define RLC_BC_LEN 16
Length in bytes of the default block cipher length.
Definition at line 50 of file relic_bc.h.
Referenced by bc_aes_cbc_dec(), bc_aes_cbc_enc(), cp_ecies_dec(), and cp_ecies_enc().
Function Documentation
bc_aes_cbc_enc()
int bc_aes_cbc_enc (uint8_t * out, size_t * out_len, const uint8_t * in, size_t in_len, const uint8_t * key, size_t key_len, const uint8_t * iv)
Encrypts with AES in CBC mode.
Parameters
[out] out - the resulting ciphertext.
[in,out] out_len - the buffer capacity and number of bytes written.
[in] in - the bytes to be encrypted.
[in] in_len - the number of bytes to encrypt.
[in] key - the key.
[in] key_len - the key size in bytes.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 43 of file relic_bc_aes.c.
References cipherInit(), DIR_ENCRYPT, cipherInstance::IV, makeKey2(), MODE_CBC, padEncrypt(), RLC_BC_LEN, RLC_ERR, RLC_OK, and TRUE.
Referenced by cp_ecies_enc().
bc_aes_cbc_dec()
int bc_aes_cbc_dec (uint8_t * out, size_t * out_len, const uint8_t * in, size_t in_len, const uint8_t * key, size_t key_len, const uint8_t * iv)
Decrypts with AES in CBC mode.
Parameters
[out] out - the resulting plaintext.
[in,out] out_len - the buffer capacity and number of bytes written.
[in] in - the bytes to be decrypted.
[in] in_len - the number of bytes to decrypt.
[in] key - the key.
[in] key_len - the key size in bytes.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 71 of file relic_bc_aes.c.
References cipherInit(), DIR_DECRYPT, cipherInstance::IV, makeKey2(), MODE_CBC, padDecrypt(), RLC_BC_LEN, RLC_ERR, RLC_OK, and TRUE.
Referenced by cp_ecies_dec().