RELIC: include/relic_fp.h File Reference
relic_fp.h File Reference
Prime field arithmetic
#include "relic_dv.h"
#include "relic_bn.h"
#include "relic_conf.h"
#include "relic_types.h"
Macros
#define RLC_FP_BITS ((size_t)FP_PRIME)
#define RLC_FP_DIGS ((size_t)RLC_CEIL(RLC_FP_BITS, RLC_DIG))
#define RLC_FP_BYTES ((size_t)RLC_CEIL(RLC_FP_BITS, 8))
#define fp_null(A)
#define fp_new(A)
#define fp_free(A)
#define fp_add(C, A, B)
#define fp_sub(C, A, B)
#define fp_neg(C, A)
#define fp_dbl(C, A)
#define fp_hlv(C, A)
#define fp_mul(C, A, B)
#define fp_sqr(C, A)
#define fp_rdc(C, A)
#define fp_rdc_monty(C, A)
#define fp_inv(C, A)
#define fp_smb(A)
#define fp_exp(C, A, B)
Typedefs
typedef rlc_align dig_t fp_t[RLC_FP_DIGS+RLC_PAD(RLC_FP_BYTES)/(RLC_DIG/8)]
typedef rlc_align dig_t fp_st[RLC_FP_DIGS+RLC_PAD(RLC_FP_BYTES)/(RLC_DIG/8)]
Enumerations
enum {
MP_127 = 1 , SECG_160 , SECG_160D , NIST_192 ,
SECG_192 , PRIME_22103 , NIST_224 , SECG_224 ,
PRIME_22605 , PRIME_25109 , SQI_251 , PRIME_H2ADC ,
PRIME_25519 , NIST_256 , BSI_256 , SECG_256 ,
SM2_256 , PRIME_382105 , PRIME_383187 , NIST_384 ,
PRIME_448 , CTIDH_511 , PRIME_511187 , NIST_521 ,
BN_158 , BN_254 , BN_256 , SM9_256 ,
B24_315 , B24_317 , K16_330 , B12_377 ,
K18_354 , B12_381 , BN_382 , B12_383 ,
BN_446 , B12_446 , B12_455 , K18_508 ,
B24_509 , AFG16_510 , GMT8_544 , SG54_569 ,
B48_575 , BN_638 , B12_638 , K18_638 ,
SG18_638 , FM16_765 , K16_766 , AFG16_766 ,
FM18_768 , CTIDH_1024 , B12_1150 , SS_1536 ,
CTIDH_2048 , K1_3072 , SQALE_4096
}
Functions
void fp_prime_init (void)
void fp_prime_clean (void)
const dig_t * fp_prime_get (void)
const dig_t * fp_prime_get_rdc (void)
const dig_t * fp_prime_get_conv (void)
const dig_t * fp_prime_get_srt (void)
const dig_t * fp_prime_get_crt (void)
dig_t fp_prime_get_mod8 (void)
dig_t fp_prime_get_mod18 (void)
const int * fp_prime_get_sps (int *len)
int fp_prime_get_qnr (void)
int fp_prime_get_cnr (void)
int fp_prime_get_2ad (void)
int fp_param_get (void)
void fp_prime_set_dense (const bn_t p)
void fp_prime_set_pmers (const int *spars, size_t len)
void fp_prime_set_pairf (const bn_t x, int pairf)
void fp_prime_calc (void)
void fp_prime_conv (fp_t c, const bn_t a)
void fp_prime_conv_dig (fp_t c, dig_t a)
void fp_prime_back (bn_t c, const fp_t a)
void fp_param_set (int param)
int fp_param_set_any (void)
int fp_param_set_any_dense (void)
int fp_param_set_any_pmers (void)
int fp_param_set_any_tower (void)
int fp_param_set_any_h2adc (void)
void fp_param_print (void)
void fp_prime_get_par (bn_t x)
const int * fp_prime_get_par_sps (int *len)
void fp_param_get_sps (int *s, int *len)
void fp_copy (fp_t c, const fp_t a)
void fp_copy_sec (fp_t c, const fp_t a, dig_t bit)
void fp_zero (fp_t a)
int fp_is_zero (const fp_t a)
int fp_is_even (const fp_t a)
int fp_get_bit (const fp_t a, uint_t bit)
void fp_set_bit (fp_t a, uint_t bit, int value)
void fp_set_dig (fp_t c, dig_t a)
size_t fp_bits (const fp_t a)
void fp_rand (fp_t a)
void fp_norm (fp_t c, const fp_t a)
void fp_print (const fp_t a)
size_t fp_size_str (const fp_t a, uint_t radix)
void fp_read_str (fp_t a, const char *str, size_t len, uint_t radix)
void fp_write_str (char *str, size_t len, const fp_t a, uint_t radix)
void fp_read_bin (fp_t a, const uint8_t *bin, size_t len)
void fp_write_bin (uint8_t *bin, size_t len, const fp_t a)
int fp_cmp (const fp_t a, const fp_t b)
int fp_cmp_dig (const fp_t a, dig_t b)
void fp_add_basic (fp_t c, const fp_t a, const fp_t b)
void fp_add_integ (fp_t c, const fp_t a, const fp_t b)
void fp_add_dig (fp_t c, const fp_t a, dig_t b)
void fp_sub_basic (fp_t c, const fp_t a, const fp_t b)
void fp_sub_integ (fp_t c, const fp_t a, const fp_t b)
void fp_sub_dig (fp_t c, const fp_t a, dig_t b)
void fp_neg_basic (fp_t c, const fp_t a)
void fp_neg_integ (fp_t c, const fp_t a)
void fp_dbl_basic (fp_t c, const fp_t a)
void fp_dbl_integ (fp_t c, const fp_t a)
void fp_hlv_basic (fp_t c, const fp_t a)
void fp_hlv_integ (fp_t c, const fp_t a)
void fp_trs (fp_t c, const fp_t a)
void fp_mul_basic (fp_t c, const fp_t a, const fp_t b)
void fp_mul_comba (fp_t c, const fp_t a, const fp_t b)
void fp_mul_integ (fp_t c, const fp_t a, const fp_t b)
void fp_mul_karat (fp_t c, const fp_t a, const fp_t b)
void fp_mul_dig (fp_t c, const fp_t a, dig_t b)
void fp_sqr_basic (fp_t c, const fp_t a)
void fp_sqr_comba (fp_t c, const fp_t a)
void fp_sqr_integ (fp_t c, const fp_t a)
void fp_sqr_karat (fp_t c, const fp_t a)
void fp_lsh (fp_t c, const fp_t a, uint_t bits)
void fp_rsh (fp_t c, const fp_t a, uint_t bits)
void fp_rdc_basic (fp_t c, dv_t a)
void fp_rdc_monty_basic (fp_t c, dv_t a)
void fp_rdc_monty_comba (fp_t c, dv_t a)
void fp_rdc_quick (fp_t c, dv_t a)
void fp_inv_basic (fp_t c, const fp_t a)
void fp_inv_binar (fp_t c, const fp_t a)
void fp_inv_monty (fp_t c, const fp_t a)
void fp_inv_exgcd (fp_t c, const fp_t a)
void fp_inv_divst (fp_t c, const fp_t a)
void fp_inv_jmpds (fp_t c, const fp_t a)
void fp_inv_lower (fp_t c, const fp_t a)
void fp_inv_sim (fp_t *c, const fp_t *a, int n)
int fp_smb_basic (const fp_t a)
int fp_smb_binar (const fp_t a)
int fp_smb_divst (const fp_t a)
int fp_smb_jmpds (const fp_t a)
int fp_smb_lower (const fp_t a)
void fp_exp_basic (fp_t c, const fp_t a, const bn_t b)
void fp_exp_slide (fp_t c, const fp_t a, const bn_t b)
void fp_exp_monty (fp_t c, const fp_t a, const bn_t b)
void fp_exp_dig (fp_t c, const fp_t a, dig_t b)
int fp_is_sqr (const fp_t a)
int fp_srt (fp_t c, const fp_t a)
int fp_is_cub (const fp_t a)
int fp_crt (fp_t c, const fp_t a)
Detailed Description
Interface of the module for prime field arithmetic.
Definition in file relic_fp.h.
Macro Definition Documentation
RLC_FP_BITS
#define RLC_FP_BITS ((size_t)FP_PRIME)
Precision in bits of a prime field element.
Definition at line 51 of file relic_fp.h.
Referenced by conf_print(), ed_mul_fix_plain(), ed_mul_naf_imp(), ed_mul_reg_imp(), ed_mul_sim_joint(), ed_mul_sim_plain(), ed_mul_sim_trick(), ed_mul_slide(), ep2_mul_fix_plain(), ep2_mul_gls_imp(), ep2_mul_naf_imp(), ep2_mul_reg_gls(), ep2_mul_reg_imp(), ep2_mul_sim_endom(), ep2_mul_sim_joint(), ep2_mul_sim_lot(), ep2_mul_sim_plain(), ep2_mul_sim_trick(), ep2_mul_slide(), ep3_mul_fix_plain(), ep3_mul_gls_imp(), ep3_mul_naf_imp(), ep3_mul_reg_gls(), ep3_mul_reg_imp(), ep3_mul_sim_joint(), ep3_mul_sim_lot(), ep3_mul_sim_plain(), ep3_mul_sim_trick(), ep3_mul_slide(), ep4_mul_fix_ordin(), ep4_mul_gls_imp(), ep4_mul_naf_imp(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), ep4_mul_sim_joint(), ep4_mul_sim_lot(), ep4_mul_sim_plain(), ep4_mul_sim_trick(), ep4_mul_slide(), ep8_mul_fix_ordin(), ep8_mul_gls_imp(), ep8_mul_naf_imp(), ep8_mul_reg_gls(), ep8_mul_reg_imp(), ep8_mul_sim_joint(), ep8_mul_sim_lot(), ep8_mul_sim_plain(), ep8_mul_sim_trick(), ep8_mul_slide(), ep_mul_fix_plain(), ep_mul_glv_imp(), ep_mul_naf_imp(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_mul_sim_endom(), ep_mul_sim_joint(), ep_mul_sim_lot_endom(), ep_mul_sim_plain(), ep_mul_sim_trick(), ep_mul_slide(), fp12_exp_cyc(), fp16_exp_cyc(), fp16_exp_cyc_sim(), fp18_exp_cyc(), fp18_exp_cyc_sim(), fp24_exp_cyc(), fp24_exp_cyc_sim(), fp2_exp_cyc(), fp2_exp_cyc_sim(), fp48_exp_cyc(), fp48_exp_cyc_sim(), fp8_exp_cyc(), fp8_exp_cyc_sim(), fp_exp_slide(), fp_param_set_any_dense(), fp_prime_set_pairf(), fp_rand(), g1_is_valid(), gt_exp_gls_naf(), gt_exp_gls_sac(), gt_exp_reg_gls(), gt_exp_reg_sac(), pp_mil_k12(), pp_mil_k16(), pp_mil_k18(), pp_mil_k24(), pp_mil_k48(), pp_mil_k54(), and pp_mil_k8().
RLC_FP_DIGS
#define RLC_FP_DIGS ((size_t)RLC_CEIL(RLC_FP_BITS, RLC_DIG))
Size in digits of a block sufficient to store a prime field element.
Definition at line 56 of file relic_fp.h.
Referenced by conf_print(), ed_curve_init(), ed_map_ell2_5mod8(), ed_mul_monty(), ed_param_set(), ep2_curve_init(), ep2_mul_monty(), ep2_pck(), ep2_upk(), ep3_curve_init(), ep3_mul_monty(), ep4_curve_init(), ep4_mul_monty(), ep8_curve_init(), ep8_mul_monty(), ep_curve_init(), ep_mul_monty(), ep_mul_reg_glv(), ep_pck(), ep_upk(), fp16_mul_dxs_lazyr(), fp16_mul_unr(), fp16_sqr_unr(), fp18_sqr_unr(), fp24_mul_unr(), fp24_sqr_unr(), fp2_field_init(), fp2_srt(), fp3_field_init(), fp3_srt(), fp4_field_init(), fp8_field_init(), fp8_mul_dxs(), fp8_mul_unr(), fp8_sqr_unr(), fp_add_basic(), fp_add_dig(), fp_bits(), fp_copy(), fp_copy_sec(), fp_crt(), fp_dbl_basic(), fp_exp_monty(), fp_hlv_basic(), fp_inv_basic(), fp_inv_binar(), fp_inv_divst(), fp_inv_exgcd(), fp_inv_jmpds(), fp_inv_monty(), fp_is_cub(), fp_is_zero(), fp_lsh(), fp_mul_basic(), fp_mul_karat(), fp_norm(), fp_prime_back(), fp_prime_conv(), fp_prime_conv_dig(), fp_prime_init(), fp_prime_set(), fp_print(), fp_rand(), fp_rdc_basic(), fp_rdc_monty_basic(), fp_rsh(), fp_smb_basic(), fp_smb_binar(), fp_smb_divst(), fp_smb_jmpds(), fp_sqr_basic(), fp_sqr_karat(), fp_srt(), fp_trs(), fp_zero(), pp_exp_k1(), and pp_exp_k2().
RLC_FP_BYTES
#define RLC_FP_BYTES ((size_t)RLC_CEIL(RLC_FP_BITS, 8))
Size in bytes of a block sufficient to store a binary field element.
Definition at line 61 of file relic_fp.h.
Referenced by cp_ibe_dec(), cp_ibe_enc(), ed_param_set(), ed_read_bin(), ed_size_bin(), ed_write_bin(), ep2_curve_set_twist(), ep2_map_basic(), ep2_read_bin(), ep2_size_bin(), ep2_write_bin(), ep3_curve_set_twist(), ep3_read_bin(), ep3_size_bin(), ep3_write_bin(), ep4_curve_set_twist(), ep4_read_bin(), ep4_size_bin(), ep4_write_bin(), ep8_curve_set_twist(), ep8_read_bin(), ep8_size_bin(), ep8_write_bin(), ep_param_set(), ep_read_bin(), ep_size_bin(), ep_write_bin(), fp12_read_bin(), fp12_size_bin(), fp12_write_bin(), fp16_read_bin(), fp16_size_bin(), fp16_write_bin(), fp18_read_bin(), fp18_size_bin(), fp18_write_bin(), fp24_read_bin(), fp24_size_bin(), fp24_write_bin(), fp2_read_bin(), fp2_size_bin(), fp2_write_bin(), fp3_read_bin(), fp3_size_bin(), fp3_write_bin(), fp48_read_bin(), fp48_size_bin(), fp48_write_bin(), fp4_read_bin(), fp4_size_bin(), fp4_write_bin(), fp54_read_bin(), fp54_size_bin(), fp54_write_bin(), fp6_read_bin(), fp6_size_bin(), fp6_write_bin(), fp8_read_bin(), fp8_size_bin(), fp8_write_bin(), fp9_read_bin(), fp9_size_bin(), fp9_write_bin(), fp_read_bin(), and fp_write_bin().
fp_null
#define fp_null (A)
Value:
/* empty */
Initializes a binary field element with a null value.
Parameters
[out] A - the binary field element to initialize.
Definition at line 233 of file relic_fp.h.
Referenced by detect_opt(), ed_add_basic(), ed_add_extnd(), ed_add_projc(), ed_blind(), ed_dbl_basic(), ed_dbl_extnd(), ed_dbl_projc(), ed_map_dst(), ed_map_ell2_5mod8(), ed_norm_sim(), ed_upk(), ep_blind(), ep_map_basic_impl(), ep_map_sswum_impl(), ep_map_swift_impl(), ep_norm_imp(), ep_norm_sim(), ep_param_set(), ep_rhs(), ep_upk(), fp2_inv(), fp2_mul_art(), fp2_sqr_basic(), fp2_upk(), fp3_inv(), fp3_mul_art(), fp3_srt(), fp_add_dig(), fp_cmp(), fp_cmp_dig(), fp_crt(), fp_exp_basic(), fp_exp_dig(), fp_exp_monty(), fp_exp_slide(), fp_inv_divst(), fp_inv_jmpds(), fp_inv_sim(), fp_prime_set(), fp_srt(), fp_sub_dig(), fp_trs(), pp_add_k1_basic(), pp_add_k1_projc(), pp_add_k2_basic(), pp_add_k2_projc_basic(), pp_add_k2_projc_lazyr(), pp_add_lit_k12(), pp_add_lit_k16(), pp_add_lit_k18(), pp_dbl_k1_basic(), pp_dbl_k1_projc(), pp_dbl_k2_basic(), pp_dbl_k2_projc_basic(), pp_dbl_k2_projc_lazyr(), pp_dbl_lit_k12(), pp_dbl_lit_k16(), pp_dbl_lit_k18(), pp_map_sim_weilp_k1(), pp_map_weilp_k1(), and pp_mil_k1().
fp_new
#define fp_new (A)
Value:
/* empty */
Calls a function to allocate and initialize a prime field element.
Parameters
[out] A - the new prime field element.
Definition at line 246 of file relic_fp.h.
Referenced by detect_opt(), ed_add_basic(), ed_add_extnd(), ed_add_projc(), ed_blind(), ed_dbl_basic(), ed_dbl_extnd(), ed_dbl_projc(), ed_map_dst(), ed_map_ell2_5mod8(), ed_norm_sim(), ed_upk(), ep_blind(), ep_map_basic_impl(), ep_map_sswum_impl(), ep_map_swift_impl(), ep_norm_imp(), ep_norm_sim(), ep_param_set(), ep_rhs(), ep_upk(), fp2_inv(), fp2_mul_art(), fp2_sqr_basic(), fp2_upk(), fp3_inv(), fp3_mul_art(), fp3_srt(), fp_add_dig(), fp_cmp(), fp_cmp_dig(), fp_crt(), fp_exp_basic(), fp_exp_dig(), fp_exp_monty(), fp_exp_slide(), fp_inv_divst(), fp_inv_jmpds(), fp_inv_sim(), fp_prime_set(), fp_srt(), fp_sub_dig(), fp_trs(), pp_add_k1_basic(), pp_add_k1_projc(), pp_add_k2_basic(), pp_add_k2_projc_basic(), pp_add_k2_projc_lazyr(), pp_add_lit_k12(), pp_add_lit_k16(), pp_add_lit_k18(), pp_dbl_k1_basic(), pp_dbl_k1_projc(), pp_dbl_k2_basic(), pp_dbl_k2_projc_basic(), pp_dbl_k2_projc_lazyr(), pp_dbl_lit_k12(), pp_dbl_lit_k16(), pp_dbl_lit_k18(), pp_map_sim_weilp_k1(), pp_map_weilp_k1(), and pp_mil_k1().
fp_free
#define fp_free (A)
Value:
/* empty */
Calls a function to clean and free a prime field element.
Parameters
[out] A - the prime field element to clean and free.
Definition at line 257 of file relic_fp.h.
Referenced by detect_opt(), ed_add_basic(), ed_add_extnd(), ed_add_projc(), ed_blind(), ed_dbl_basic(), ed_dbl_extnd(), ed_dbl_projc(), ed_map_dst(), ed_map_ell2_5mod8(), ed_norm_sim(), ed_upk(), ep_blind(), ep_map_basic_impl(), ep_map_sswum_impl(), ep_map_swift_impl(), ep_norm_imp(), ep_norm_sim(), ep_param_set(), ep_rhs(), ep_upk(), fp2_inv(), fp2_mul_art(), fp2_sqr_basic(), fp2_upk(), fp3_inv(), fp3_mul_art(), fp3_srt(), fp_add_dig(), fp_cmp(), fp_cmp_dig(), fp_crt(), fp_exp_basic(), fp_exp_dig(), fp_exp_monty(), fp_exp_slide(), fp_inv_divst(), fp_inv_jmpds(), fp_inv_sim(), fp_prime_set(), fp_sqr_basic(), fp_sqr_comba(), fp_srt(), fp_sub_dig(), fp_trs(), pp_add_k1_basic(), pp_add_k1_projc(), pp_add_k2_basic(), pp_add_k2_projc_basic(), pp_add_k2_projc_lazyr(), pp_add_lit_k12(), pp_add_lit_k16(), pp_add_lit_k18(), pp_dbl_k1_basic(), pp_dbl_k1_projc(), pp_dbl_k2_basic(), pp_dbl_k2_projc_basic(), pp_dbl_k2_projc_lazyr(), pp_dbl_lit_k12(), pp_dbl_lit_k16(), pp_dbl_lit_k18(), pp_map_sim_weilp_k1(), pp_map_weilp_k1(), and pp_mil_k1().
fp_add
#define fp_add (C, A, B)
Value:
fp_add_integ(C, A, B)
Adds two prime field elements. Computes c = a + b.
Parameters
[out] C - the result.
[in] A - the first prime field element.
[in] B - the second prime field element.
Definition at line 270 of file relic_fp.h.
Referenced by ed_add_basic(), ed_add_extnd(), ed_add_projc(), ed_dbl_extnd(), ed_dbl_projc(), ed_map_ell2_5mod8(), ep_curve_set_map(), ep_map_swift_impl(), ep_rhs(), fp12_mul_dxs_basic(), fp12_mul_dxs_lazyr(), fp18_mul_dxs_basic(), fp18_mul_dxs_lazyr(), fp2_add_basic(), fp2_inv(), fp2_mul_art(), fp2_mul_basic(), fp2_mul_nor_basic(), fp2_sqr_basic(), fp2_srt(), fp3_add_basic(), fp3_inv(), fp3_mul_art(), fp3_mul_basic(), fp3_sqr_basic(), fp48_mul_dxs(), fp_add_dig(), fp_inv_jmpds(), fp_prime_set(), pp_add_k2_basic(), pp_add_k2_projc_basic(), pp_add_k2_projc_lazyr(), pp_add_lit_k12(), pp_add_lit_k16(), pp_add_lit_k18(), pp_dbl_k12_projc_basic(), pp_dbl_k12_projc_lazyr(), pp_dbl_k1_basic(), pp_dbl_k1_projc(), pp_dbl_k2_basic(), pp_dbl_k2_projc_basic(), pp_dbl_k2_projc_lazyr(), pp_dbl_lit_k12(), pp_dbl_lit_k16(), pp_dbl_lit_k18(), pp_fin_k18_oatep(), pp_mil_k12(), pp_mil_k18(), pp_mil_k24(), pp_mil_k48(), and pp_mil_k54().
fp_sub
#define fp_sub (C, A, B)
Value:
fp_sub_integ(C, A, B)
Subtracts a prime field element from another. Computes C = A - B.
Parameters
[out] C - the result.
[in] A - the first prime field element.
[in] B - the second prime field element.
Definition at line 283 of file relic_fp.h.
Referenced by ed_add_basic(), ed_add_extnd(), ed_add_projc(), ed_dbl_basic(), ed_dbl_extnd(), ed_dbl_projc(), ed_map_ell2_5mod8(), ed_upk(), ep_map_swift_impl(), fp2_inv(), fp2_mul_art(), fp2_sqr_basic(), fp2_srt(), fp2_sub_basic(), fp3_inv(), fp3_mul_art(), fp3_sqr_basic(), fp3_sub_basic(), fp_cmp(), fp_sub_dig(), fp_trs(), pp_add_k1_basic(), pp_add_k1_projc(), pp_add_k2_basic(), pp_add_k2_projc_basic(), pp_add_k2_projc_lazyr(), pp_add_lit_k12(), pp_add_lit_k16(), pp_add_lit_k18(), pp_dbl_k12_projc_basic(), pp_dbl_k12_projc_lazyr(), pp_dbl_k1_basic(), pp_dbl_k1_projc(), pp_dbl_k2_basic(), pp_dbl_k2_projc_basic(), pp_dbl_k2_projc_lazyr(), pp_dbl_lit_k12(), pp_dbl_lit_k16(), and pp_dbl_lit_k18().
fp_neg
#define fp_neg (C, A)
Value:
fp_neg_integ(C, A)
Negates a prime field element from another. Computes C = -A.
Parameters
[out] C - the result.
[in] A - the prime field element to negate.
Definition at line 295 of file relic_fp.h.
Referenced by detect_opt(), ed_add_basic(), ed_dbl_basic(), ed_map_ell2_5mod8(), ed_neg_basic(), ed_neg_projc(), ed_param_set(), ed_upk(), ep_curve_set_endom(), ep_curve_set_map(), ep_curve_set_plain(), ep_map_swift_impl(), ep_neg(), ep_param_set(), ep_psi(), ep_upk(), fp12_upk_max(), fp2_frb(), fp2_inv(), fp2_inv_cyc(), fp2_mul_art(), fp2_mul_nor_basic(), fp2_neg(), fp2_srt(), fp2_upk(), fp3_field_init(), fp3_neg(), fp_inv_divst(), fp_inv_jmpds(), fp_prime_set(), fp_read_str(), fp_smb_basic(), fp_srt(), pp_add_k12_basic(), pp_add_k12_projc_basic(), pp_add_k12_projc_lazyr(), pp_add_k18_basic(), pp_add_k18_projc_basic(), pp_add_k18_projc_lazyr(), pp_add_k24_basic(), pp_add_k24_projc(), pp_add_k2_basic(), pp_add_k48_basic(), pp_add_k48_projc(), pp_add_k54_basic(), pp_add_k54_projc(), pp_fin_k16_oatep(), pp_fin_k18_oatep(), pp_map_weilp_k1(), pp_mil_k12(), pp_mil_k16(), pp_mil_k18(), pp_mil_k24(), pp_mil_k48(), pp_mil_k54(), and pp_mil_k8().
fp_dbl
#define fp_dbl (C, A)
Value:
fp_dbl_integ(C, A)
Doubles a prime field element. Computes C = A + A.
Parameters
[out] C - the result.
[in] A - the first prime field element.
Definition at line 307 of file relic_fp.h.
Referenced by ed_dbl_basic(), ed_dbl_extnd(), ed_dbl_projc(), ed_map_ell2_5mod8(), ep_curve_mul_a(), ep_map_swift_impl(), fp2_dbl_basic(), fp2_inv(), fp2_sqr_basic(), fp2_srt(), fp3_dbl_basic(), fp3_sqr_basic(), pp_add_k1_projc(), pp_add_k2_projc_basic(), pp_add_k2_projc_lazyr(), pp_dbl_k1_projc(), pp_dbl_k2_projc_basic(), pp_dbl_k2_projc_lazyr(), pp_dbl_lit_k12(), pp_dbl_lit_k16(), and pp_dbl_lit_k18().
fp_hlv
#define fp_hlv (C, A)
Value:
fp_hlv_integ(C, A)
Halves a prime field element. Computes C = A/2.
Parameters
[out] C - the result.
[in] A - the first prime field element.
Definition at line 319 of file relic_fp.h.
Referenced by ep2_map_swift(), ep4_map(), ep_curve_set_map(), ep_map_swift_impl(), ep_param_set(), fp16_srt(), fp24_sqr_basic(), fp2_srt(), fp4_srt(), fp54_sqr_basic(), fp54_sqr_lazyr(), fp6_sqr_basic(), fp8_srt(), fp9_sqr_basic(), fp_inv_divst(), fp_prime_set(), pp_add_k2_projc_basic(), pp_add_k2_projc_lazyr(), pp_dbl_k12_projc_basic(), pp_dbl_k12_projc_lazyr(), and pp_dbl_k8_projc_new().
fp_mul
#define fp_mul (C, A, B)
Value:
fp_mul_integ(C, A, B)
Multiples two prime field elements. Computes C = A * B.
Parameters
[out] C - the result.
[in] A - the first prime field element.
[in] B - the second prime field element.
Definition at line 336 of file relic_fp.h.
Referenced by ed_add_basic(), ed_add_extnd(), ed_add_projc(), ed_blind(), ed_cmp(), ed_dbl_basic(), ed_dbl_extnd(), ed_dbl_projc(), ed_map_dst(), ed_map_ell2_5mod8(), ed_norm_imp(), ed_on_curve(), ed_param_set(), ed_read_bin(), ed_rhs(), ed_upk(), ep2_curve_mul_a(), ep2_map_swift(), ep3_map(), ep4_map(), ep8_map(), ep_blind(), ep_cmp(), ep_curve_mul_a(), ep_curve_mul_b(), ep_curve_set_map(), ep_map_swift_impl(), ep_norm_imp(), ep_psi(), ep_rhs(), fp12_mul_dxs_basic(), fp16_mul_dxs_basic(), fp18_mul_dxs_basic(), fp2_inv(), fp2_sqr_basic(), fp2_srt(), fp3_inv(), fp3_mul_frb(), fp3_srt(), fp48_mul_dxs(), fp_crt(), fp_exp_basic(), fp_exp_dig(), fp_exp_monty(), fp_exp_slide(), fp_inv_divst(), fp_inv_jmpds(), fp_inv_monty(), fp_inv_sim(), fp_mul_dig(), fp_prime_conv(), fp_prime_set(), fp_srt(), pp_add_k12_basic(), pp_add_k12_projc_basic(), pp_add_k12_projc_lazyr(), pp_add_k16_basic(), pp_add_k16_projc_basic(), pp_add_k16_projc_lazyr(), pp_add_k18_basic(), pp_add_k18_projc_basic(), pp_add_k18_projc_lazyr(), pp_add_k1_basic(), pp_add_k1_projc(), pp_add_k24_basic(), pp_add_k24_projc(), pp_add_k2_basic(), pp_add_k2_projc_basic(), pp_add_k2_projc_lazyr(), pp_add_k48_basic(), pp_add_k48_projc(), pp_add_k54_basic(), pp_add_k54_projc(), pp_add_k8_basic(), pp_add_k8_projc_basic(), pp_add_k8_projc_lazyr(), pp_add_lit_k12(), pp_add_lit_k16(), pp_add_lit_k18(), pp_dbl_k12_basic(), pp_dbl_k12_projc_basic(), pp_dbl_k12_projc_lazyr(), pp_dbl_k16_basic(), pp_dbl_k16_projc_basic(), pp_dbl_k16_projc_lazyr(), pp_dbl_k18_basic(), pp_dbl_k18_projc_basic(), pp_dbl_k18_projc_lazyr(), pp_dbl_k1_basic(), pp_dbl_k1_projc(), pp_dbl_k24_basic(), pp_dbl_k24_projc(), pp_dbl_k2_basic(), pp_dbl_k2_projc_basic(), pp_dbl_k2_projc_lazyr(), pp_dbl_k48_basic(), pp_dbl_k48_projc(), pp_dbl_k54_basic(), pp_dbl_k54_projc(), pp_dbl_k8_basic(), pp_dbl_k8_projc_basic(), pp_dbl_k8_projc_lazyr(), pp_dbl_k8_projc_lazyr_new(), pp_dbl_k8_projc_new(), pp_dbl_lit_k12(), pp_dbl_lit_k16(), pp_dbl_lit_k18(), pp_map_sim_weilp_k1(), pp_map_weilp_k1(), pp_mil_k1(), and pp_mil_k54().
fp_sqr
#define fp_sqr (C, A)
Value:
fp_sqr_integ(C, A)
Squares a prime field element. Computes C = A * A.
Parameters
[out] C - the result.
[in] A - the prime field element to square.
Definition at line 354 of file relic_fp.h.
Referenced by ed_add_projc(), ed_dbl_basic(), ed_dbl_extnd(), ed_dbl_projc(), ed_map_ell2_5mod8(), ed_on_curve(), ed_read_bin(), ed_rhs(), ed_upk(), ep_blind(), ep_cmp(), ep_curve_set_map(), ep_map_swift_impl(), ep_norm_imp(), ep_on_curve(), ep_rhs(), fp2_inv(), fp2_srt(), fp2_upk(), fp3_field_init(), fp3_inv(), fp3_srt(), fp_crt(), fp_exp_basic(), fp_exp_dig(), fp_exp_monty(), fp_exp_slide(), fp_srt(), pp_add_k1_projc(), pp_add_k2_projc_basic(), pp_add_k2_projc_lazyr(), pp_add_lit_k12(), pp_add_lit_k16(), pp_add_lit_k18(), pp_dbl_k1_projc(), pp_dbl_k2_projc_basic(), pp_dbl_k2_projc_lazyr(), pp_dbl_lit_k12(), pp_dbl_lit_k16(), pp_dbl_lit_k18(), and pp_mil_k1().
fp_rdc
#define fp_rdc (C, A)
Value:
fp_rdc_monty(C, A)
Reduces a multiplication result modulo a prime field order. Computes C = A mod p.
Parameters
[out] C - the result.
[in] A - the multiplication result to reduce.
Definition at line 367 of file relic_fp.h.
Referenced by fp2_mul_basic(), fp2_rdc_basic(), fp3_mul_basic(), fp3_rdc_basic(), fp3_sqr_basic(), fp_inv_jmpds(), fp_mul_basic(), fp_mul_comba(), fp_mul_karat(), fp_prime_back(), fp_prime_conv_dig(), fp_sqr_basic(), fp_sqr_comba(), and fp_sqr_karat().
fp_rdc_monty
#define fp_rdc_monty (C, A)
Value:
fp_rdc_monty_comba(C, A)
Reduces a multiplication result modulo a prime field order using Montgomery modular reduction.
Parameters
[out] C - the result.
[in] A - the multiplication result to reduce.
Definition at line 382 of file relic_fp.h.
fp_inv
#define fp_inv (C, A)
Value:
fp_inv_monty(C, A)
Inverts a prime field element. Computes C = A^{-1}.
Parameters
[out] C - the result.
[in] A - the prime field element to invert.
Definition at line 396 of file relic_fp.h.
Referenced by ed_add_basic(), ed_dbl_basic(), ed_map_ell2_5mod8(), ed_norm_imp(), ed_upk(), ep_curve_set_map(), ep_map_swift_impl(), ep_norm_imp(), fp2_inv(), fp2_srt(), fp3_inv(), fp_crt(), fp_exp_basic(), fp_exp_monty(), fp_exp_slide(), fp_inv_sim(), pp_map_sim_weilp_k1(), pp_map_weilp_k1(), and pp_mil_k1().
fp_smb
#define fp_smb (A)
Value:
fp_smb_jmpds(A)
Computes the Legendre symbol of a prime field element. Computes C = (A|P).
Parameters
[out] C - the result.
[in] A - the prime field element to compute.
Definition at line 420 of file relic_fp.h.
Referenced by ep_map_basic_impl(), and fp_is_sqr().
fp_exp
#define fp_exp (C, A, B)
Value:
fp_exp_slide(C, A, B)
Exponentiates a prime field element. Computes C = A^B (mod p).
Parameters
[out] C - the result.
[in] A - the basis.
[in] B - the exponent.
Definition at line 435 of file relic_fp.h.
Referenced by ed_map_ell2_5mod8(), ed_param_set(), fp2_srt(), fp3_field_init(), fp_crt(), fp_inv_basic(), fp_inv_divst(), fp_is_cub(), fp_prime_set(), fp_smb_basic(), fp_srt(), and pp_exp_k1().
Typedef Documentation
fp_t
typedef rlc_align dig_t fp_t[RLC_FP_DIGS+RLC_PAD(RLC_FP_BYTES)/(RLC_DIG/8)]
Constant used to indicate that there's some room left in the storage of prime field elements. This can be used to avoid carries. Represents a prime field element.
A field element is represented as a digit vector. These digits are organized in little-endian format, that is, the least significant digits are stored in the first positions of the vector.
Definition at line 213 of file relic_fp.h.
fp_st
typedef rlc_align dig_t fp_st[RLC_FP_DIGS+RLC_PAD(RLC_FP_BYTES)/(RLC_DIG/8)]
Represents a prime field element with automatic memory allocation.
Definition at line 221 of file relic_fp.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MP_127
Mersenne prime with 127 bits.
SECG_160
SECG 160-bit fast reduction prime.
SECG_160D
SECG 160-bit denser reduction prime.
NIST_192
NIST 192-bit fast reduction prime.
SECG_192
SECG 192-bit denser reduction prime.
PRIME_22103
Curve22103 221-bit prime modulus.
NIST_224
NIST 224-bit fast reduction polynomial.
SECG_224
SECG 224-bit denser reduction prime.
PRIME_22605
Curve4417 226-bit prime modulus.
PRIME_25109
SQI_251
PRIME_H2ADC
Prime with high 2-adicity for curve Tweedledum.
PRIME_25519
Curve25519 255-bit prime modulus.
NIST_256
NIST 256-bit fast reduction polynomial.
BSI_256
Brainpool random 256-bit prime.
SECG_256
SECG 256-bit denser reduction prime.
SM2_256
SM2 256-bit prime modulus standardized in China.
PRIME_382105
Curve67254 382-bit prime modulus.
PRIME_383187
Curve383187 383-bit prime modulus.
NIST_384
NIST 384-bit fast reduction polynomial.
PRIME_448
Curve448 prime.
CTIDH_511
511-bit prime for CTIDH.
PRIME_511187
Curve511187 511-bit prime modulus.
NIST_521
NIST 521-bit fast reduction polynomial.
BN_158
158-bit prime for BN curve.
BN_254
254-bit prime provided in Nogami et al. for BN curves.
BN_256
256-bit prime provided in Barreto et al. for BN curves.
SM9_256
256-bit prime provided for BN curve standardized in China.
B24_315
315-bit prime for BLS curve of embedding degree 24 (SNARKs).
B24_317
317-bit prime for BLS curve of embedding degree 24 (SNARKs).
K16_330
330-bit prime for KSS curve with embedding degree 16.
B12_377
381-bit prime for BLS curve of embedding degree 12 (SNARKs).
K18_354
354-bit prime for KSS curve of embedding degree 18.
B12_381
381-bit prime for BLS curve of embedding degree 12 (Zcash).
BN_382
382-bit prime provided by Barreto for BN curve.
B12_383
383-bit prime for GT-strong BLS curve of embedding degree 12.
BN_446
446-bit prime provided by Barreto for BN curve.
B12_446
446-bit prime for BLS curve of embedding degree 12.
B12_455
455-bit prime for BLS curve of embedding degree 12.
K18_508
508-bit prime for KSS16 curve.
B24_509
477-bit prime for BLS curve of embedding degree 24.
AFG16_510
510-bit prime for new family with embedding degree 16.
GMT8_544
Random 544-bit prime for Cocks-Pinch curve with embedding degree 8.
SG54_569
569-bit prime for SG curve with embedding degree 54.
B48_575
575-bit prime for BLS curve with embedding degree 48.
BN_638
638-bit prime provided in Barreto et al. for BN curve.
B12_638
638-bit prime for BLS curve with embedding degree 12.
K18_638
638-bit prime for KSS curve with embedding degree 18.
SG18_638
638-bit prime for SG curve with embedding degree 18.
FM16_765
765-bit prime for FM curve with embedding degree 16.
K16_766
766-bit prime for KSS curve with embedding degree 16.
AFG16_766
766-bit prime for new family with embedding degree 16.
FM18_768
768-bit prime for FM curve with embedding degree 18.
CTIDH_1024
1024-bit prime for CTIDH.
B12_1150
1150-bit prime for BLS curve with embedding degree 12.
SS_1536
1536-bit prime for supersingular curve with embedding degree k = 2.
CTIDH_2048
2048-bit prime for CTDIH.
K1_3072
3072-bit prime for supersingular curve with embedding degree k = 1.
SQALE_4096
4096-bit prime for SQALE.
Definition at line 66 of file relic_fp.h.
Function Documentation
fp_prime_init()
void fp_prime_init (void)
Initializes the prime field arithmetic layer.
Definition at line 238 of file relic_fp_prime.c.
References bn_make(), _ctx_t::conv, core_get(), _ctx_t::crt, _ctx_t::fp_id, _ctx_t::inv, _ctx_t::one, _ctx_t::over3, _ctx_t::par, _ctx_t::prime, RLC_FP_DIGS, _ctx_t::sps, _ctx_t::sps_len, and _ctx_t::srt.
Referenced by core_init().
fp_prime_clean()
void fp_prime_clean (void)
Finalizes the prime field arithmetic layer.
Definition at line 259 of file relic_fp_prime.c.
References bn_clean(), _ctx_t::conv, core_get(), _ctx_t::crt, _ctx_t::fp_id, _ctx_t::inv, _ctx_t::one, _ctx_t::over3, _ctx_t::par, _ctx_t::prime, _ctx_t::sps, _ctx_t::sps_len, and _ctx_t::srt.
Referenced by core_clean().
fp_prime_get()
const dig_t * fp_prime_get (void)
Returns the order of the prime field.
Returns
the order of the prime field.
Definition at line 282 of file relic_fp_prime.c.
References core_get(), bn_st::dp, and _ctx_t::prime.
Referenced by ed_map_ell2_5mod8(), ed_param_set(), ep2_pck(), ep2_upk(), ep_pck(), ep_upk(), fp2_field_init(), fp2_srt(), fp3_field_init(), fp3_srt(), fp4_field_init(), fp8_field_init(), fp_add_basic(), fp_add_dig(), fp_crt(), fp_dbl_basic(), fp_hlv_basic(), fp_inv_basic(), fp_inv_binar(), fp_inv_divst(), fp_inv_exgcd(), fp_inv_jmpds(), fp_inv_monty(), fp_is_cub(), fp_is_zero(), fp_neg_basic(), fp_norm(), fp_prime_set(), fp_print(), fp_rand(), fp_rdc_basic(), fp_rdc_monty_basic(), fp_rdc_quick(), fp_smb_basic(), fp_smb_binar(), fp_smb_divst(), fp_smb_jmpds(), fp_srt(), fp_sub_basic(), fp_sub_dig(), pp_exp_k1(), and pp_exp_k2().
fp_prime_get_rdc()
const dig_t * fp_prime_get_rdc (void)
Returns the additional value used for modular reduction.
Returns
the additional value used for modular reduction.
Definition at line 286 of file relic_fp_prime.c.
References core_get(), and _ctx_t::u.
Referenced by fp_rdc_monty_basic().
fp_prime_get_conv()
const dig_t * fp_prime_get_conv (void)
Returns the additional value used for conversion from multiple precision integer to prime field element.
Returns
the additional value used for importing integers.
Definition at line 327 of file relic_fp_prime.c.
References _ctx_t::conv, core_get(), and bn_st::dp.
Referenced by fp_inv_monty().
fp_prime_get_srt()
const dig_t * fp_prime_get_srt (void)
Returns a 2^f-root of unity modulo the prime field modulus, for the maximum f such that 2^f divides (p-1).
Returns
the root of unity.
Definition at line 335 of file relic_fp_prime.c.
References core_get(), bn_st::dp, and _ctx_t::srt.
Referenced by fp3_srt(), and fp_srt().
fp_prime_get_crt()
const dig_t * fp_prime_get_crt (void)
Returns a 3^f-root of unity modulo the prime field modulus, for the maximum f such that 3^f divides (p-1).
Returns
the root of unity.
Definition at line 339 of file relic_fp_prime.c.
References core_get(), _ctx_t::crt, and bn_st::dp.
Referenced by fp_crt().
fp_prime_get_mod8()
dig_t fp_prime_get_mod8 (void)
Returns the result of prime order mod 8.
Returns
the result of prime order mod 8.
Definition at line 343 of file relic_fp_prime.c.
References core_get(), and _ctx_t::mod8.
Referenced by fp16_frb(), fp24_frb(), fp2_mul_nor_basic(), fp2_srt(), fp3_srt(), fp48_frb(), fp8_frb(), fp_param_set_any_tower(), and fp_srt().
fp_prime_get_mod18()
dig_t fp_prime_get_mod18 (void)
Returns the result of prime order mod 18.
Returns
the result of prime order mod 18.
Definition at line 347 of file relic_fp_prime.c.
References core_get(), and _ctx_t::mod18.
Referenced by fp3_mul_nor(), fp4_frb(), fp4_mul_frb(), fp_crt(), fp_is_cub(), and fp_param_set_any_tower().
fp_prime_get_sps()
const int * fp_prime_get_sps (int * len)
Returns the prime stored in special form. The most significant bit is RLC_FP_BITS.
Parameters
[out] len - the number of returned bits, can be NULL.
Returns
the prime represented by it non-zero bits.
Definition at line 308 of file relic_fp_prime.c.
References core_get(), RLC_TERMS, _ctx_t::sps, and _ctx_t::sps_len.
fp_prime_get_qnr()
int fp_prime_get_qnr (void)
Returns a non-quadratic residue in the prime field.
Returns
the non-quadratic residue.
Definition at line 351 of file relic_fp_prime.c.
References core_get(), and _ctx_t::qnr.
Referenced by fp2_inv(), fp2_mul_art(), fp2_mul_basic(), fp2_sqr_basic(), fp2_srt(), and fp_prime_calc().
fp_prime_get_cnr()
int fp_prime_get_cnr (void)
Returns a non-cubic residue in the prime field.
Returns
the non-cubic residue.
Definition at line 355 of file relic_fp_prime.c.
References _ctx_t::cnr, and core_get().
Referenced by fp3_field_init(), fp3_inv(), fp3_mul_art(), fp3_mul_basic(), fp3_sqr_basic(), fp_prime_calc(), and fp_prime_set().
fp_prime_get_2ad()
int fp_prime_get_2ad (void)
Returns the 2-adicity of the prime modulus.
Returns
the 2-adicity of the modulus.
Definition at line 359 of file relic_fp_prime.c.
References _ctx_t::ad2, and core_get().
Referenced by ed_param_set(), fp3_srt(), and fp_srt().
fp_param_get()
int fp_param_get (void)
Returns the prime field parameter identifier.
Returns
the parameter identifier.
Definition at line 99 of file relic_fp_param.c.
References core_get(), and _ctx_t::fp_id.
Referenced by fp3_field_get_cnr(), and fp_prime_set().
fp_prime_set_dense()
void fp_prime_set_dense (const bn_t p)
Assigns the prime field modulus to a non-sparse prime.
Parameters
[in] p - the new prime field modulus.
Definition at line 363 of file relic_fp_prime.c.
References ERR_NO_CONFIG, fp_prime_set(), and RLC_THROW.
Referenced by fp_param_set(), fp_param_set_any_dense(), and fp_prime_set_pairf().
fp_prime_set_pmers()
void fp_prime_set_pmers (const int * spars, size_t len)
Assigns the prime field modulus to a special form sparse prime.
Parameters
[in] spars - the list of powers of 2 describing the prime.
[in] len - the number of powers.
Definition at line 676 of file relic_fp_prime.c.
References bn_add(), bn_add_dig(), bn_free, bn_new, bn_null, bn_set_2b(), bn_sub(), bn_sub_dig(), core_get(), ERR_CAUGHT, ERR_NO_VALID, fp_prime_set(), RLC_CATCH_ANY, RLC_FINALLY, RLC_TERMS, RLC_THROW, RLC_TRY, _ctx_t::sps, and _ctx_t::sps_len.
Referenced by fp_param_set().
fp_prime_set_pairf()
void fp_prime_set_pairf (const bn_t x, int pairf)
Assigns the prime field modulus to a parametrization from a family of pairing-friendly curves.
Definition at line 370 of file relic_fp_prime.c.
References bn_add(), bn_add_dig(), bn_bits(), bn_copy(), bn_div(), bn_div_dig(), bn_free, bn_lsh(), bn_mul, bn_mul_dig(), bn_new, bn_null, bn_rec_naf(), bn_set_dig(), bn_sqr, bn_sub(), bn_sub_dig(), core_get(), EP_AFG16, EP_B12, EP_B24, EP_B48, EP_BN, EP_FM16, EP_FM18, EP_K16, EP_K18, EP_SG18, EP_SG54, ERR_CAUGHT, ERR_NO_VALID, fp_prime_set_dense(), _ctx_t::par, _ctx_t::par_len, _ctx_t::par_sps, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_TERMS, RLC_THROW, and RLC_TRY.
Referenced by fp_param_set().
fp_prime_calc()
void fp_prime_calc (void)
Computes the constants needed for evaluating Frobenius maps in higher extension fields.
Definition at line 727 of file relic_fp_prime.c.
References fp2_field_init(), fp3_field_init(), fp4_field_init(), fp8_field_init(), fp_prime_get_cnr(), and fp_prime_get_qnr().
Referenced by fp_prime_set().
fp_prime_conv()
void fp_prime_conv (fp_t c, const bn_t a)
Imports a multiple precision integer as a prime field element, doing the necessary conversion.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to import.
Definition at line 740 of file relic_fp_prime.c.
References bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, core_get(), dv_copy(), dv_zero(), ERR_CAUGHT, fp_mul, fp_zero(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
Referenced by cp_cmlhs_sig(), ep2_map_basic(), ep2_map_swift(), ep3_map(), ep4_map(), ep8_map(), ep_map_basic_impl(), ep_map_swift_impl(), fp_inv_binar(), fp_inv_exgcd(), fp_read_bin(), and fp_read_str().
fp_prime_conv_dig()
void fp_prime_conv_dig (fp_t c, dig_t a)
Imports a single digit as a prime field element, doing the necessary conversion.
Parameters
[out] c - the result.
[in] a - the digit to import.
Definition at line 770 of file relic_fp_prime.c.
References bn_null, _ctx_t::conv, core_get(), bn_st::dp, dv_copy(), dv_free, dv_new, dv_zero(), ERR_CAUGHT, fp_mul1_low(), fp_rdc, fp_zero(), _ctx_t::one, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
Referenced by detect_opt(), fp_cmp_dig(), fp_mul_dig(), fp_read_bin(), fp_read_str(), and fp_set_dig().
fp_prime_back()
void fp_prime_back (bn_t c, const fp_t a)
Exports a prime field element as a multiple precision integer, doing the necessary conversion.
Parameters
[out] c - the result.
[in] a - the prime field element to export.
Definition at line 801 of file relic_fp_prime.c.
References bn_grow(), bn_trim(), dv_copy(), dv_free, dv_new, dv_null, dv_zero(), ERR_CAUGHT, fp_norm(), fp_rdc, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_POS, RLC_THROW, and RLC_TRY.
Referenced by cp_cmlhs_onv(), cp_cmlhs_ver(), ed_map_ell2_5mod8(), ed_param_set(), ep2_curve_set_map(), ep2_map_swift(), ep2_pck(), ep2_upk(), ep3_map(), ep4_map(), ep8_map(), ep_curve_set_map(), ep_pck(), ep_upk(), fp2_sgn0(), fp_inv_binar(), fp_inv_exgcd(), fp_is_even(), fp_print(), fp_size_str(), fp_write_bin(), and fp_write_str().
fp_param_set()
void fp_param_set (int param)
Assigns a prime modulus based on its identifier.
Definition at line 103 of file relic_fp_param.c.
References AFG16_510, AFG16_766, B12_1150, B12_377, B12_381, B12_383, B12_446, B12_455, B12_638, B24_315, B24_317, B24_509, B48_575, BN_158, BN_254, BN_256, BN_382, BN_446, BN_638, bn_add(), bn_add_dig(), bn_dbl(), bn_free, bn_lsh(), bn_mul, bn_mul_dig(), bn_neg(), bn_new, bn_null, bn_read_str(), bn_set_2b(), bn_set_bit(), bn_set_dig(), bn_sqr, bn_sub(), bn_sub_dig(), BSI_256, core_get(), CTIDH_1024, CTIDH_2048, CTIDH_511, EP_AFG16, EP_B12, EP_B24, EP_B48, EP_BN, EP_FM16, EP_FM18, EP_GMT8, EP_K1, EP_K16, EP_K18, EP_SG18, EP_SG54, EP_SS2, ERR_CAUGHT, FM16_765, FM18_768, _ctx_t::fp_id, fp_param_set_any_dense(), fp_prime_set_dense(), fp_prime_set_pairf(), fp_prime_set_pmers(), GMT8_544, K16_330, K16_766, K18_354, K18_508, K18_638, K1_3072, MP_127, NIST_192, NIST_224, NIST_256, NIST_384, NIST_521, PRIME_22103, PRIME_22605, PRIME_25109, PRIME_25519, PRIME_382105, PRIME_383187, PRIME_448, PRIME_511187, PRIME_H2ADC, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, RLC_TRY, SECG_160, SECG_160D, SECG_192, SECG_224, SECG_256, SG18_638, SG54_569, SM2_256, SM9_256, SQALE_4096, SQI_251, SS_1536, and STR_P256.
Referenced by fp_param_set_any_h2adc(), fp_param_set_any_pmers(), and fp_param_set_any_tower().
fp_param_set_any()
int fp_param_set_any (void)
Assigns any pre-defined parameter as the prime modulus.
Returns
RLC_OK if no errors occurred; RLC_ERR otherwise.
Definition at line 727 of file relic_fp_param.c.
References fp_param_set_any_dense(), fp_param_set_any_h2adc(), fp_param_set_any_pmers(), fp_param_set_any_tower(), RLC_ERR, and RLC_OK.
fp_param_set_any_dense()
int fp_param_set_any_dense (void)
Assigns the order of the prime field to any non-sparse prime.
Returns
RLC_OK if no errors occurred; RLC_ERR otherwise.
Definition at line 744 of file relic_fp_param.c.
References bn_free, bn_gen_prime, bn_is_prime(), bn_new, bn_null, ERR_CAUGHT, fp_prime_set_dense(), RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_FP_BITS, RLC_OK, RLC_THROW, and RLC_TRY.
Referenced by fp_param_set(), fp_param_set_any(), and fp_param_set_any_tower().
fp_param_set_any_pmers()
int fp_param_set_any_pmers (void)
Assigns the order of the prime field to any sparse prime.
Returns
RLC_OK if no errors occurred; RLC_ERR otherwise.
Definition at line 774 of file relic_fp_param.c.
References fp_param_set(), MP_127, NIST_192, NIST_224, NIST_256, NIST_384, NIST_521, PRIME_25519, PRIME_448, RLC_ERR, RLC_OK, SECG_160, and SQI_251.
Referenced by fp_param_set_any().
fp_param_set_any_tower()
int fp_param_set_any_tower (void)
Assigns the order of the prime field to any towering-friendly prime.
Returns
RLC_OK if no errors occurred; RLC_ERR otherwise.
Definition at line 810 of file relic_fp_param.c.
References AFG16_510, AFG16_766, B12_1150, B12_377, B12_381, B12_383, B12_446, B12_455, B12_638, B24_315, B24_317, B24_509, B48_575, BN_158, BN_254, BN_256, BN_382, BN_446, CTIDH_511, FM16_765, FM18_768, fp_param_set(), fp_param_set_any_dense(), fp_prime_get_mod18(), fp_prime_get_mod8(), GMT8_544, K16_330, K18_354, K18_508, K18_638, K1_3072, RLC_OK, SG54_569, SQALE_4096, and SS_1536.
Referenced by fp_param_set_any().
fp_param_set_any_h2adc()
int fp_param_set_any_h2adc (void)
Assigns the order of the prime field to a prime with high 2-adicity..
Returns
RLC_OK if no errors occurred; RLC_ERR otherwise.
Definition at line 801 of file relic_fp_param.c.
References fp_param_set(), PRIME_H2ADC, RLC_ERR, and RLC_OK.
Referenced by fp_param_set_any().
fp_param_print()
void fp_param_print (void)
Prints the currently configured prime modulus.
Definition at line 889 of file relic_fp_param.c.
References bn_print(), core_get(), util_banner, and util_print.
fp_prime_get_par()
void fp_prime_get_par (bn_t x)
Returns the variable used to parametrize the given prime modulus.
Parameters
[out] x - the integer parameter.
Definition at line 290 of file relic_fp_prime.c.
References bn_copy(), and core_get().
Referenced by bn_rec_sac(), ep2_frb(), ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep2_mul_gls_imp(), ep2_mul_reg_gls(), ep2_mul_sim_endom(), ep2_mul_sim_lot(), ep3_mul_cof_fm18(), ep3_mul_cof_k18(), ep3_mul_cof_sg18(), ep3_mul_gls_imp(), ep3_mul_reg_gls(), ep3_mul_sim_lot(), ep4_mul_cof_afg16(), ep4_mul_cof_b24(), ep4_mul_cof_fm16(), ep4_mul_cof_k16(), ep4_mul_gls_imp(), ep4_mul_reg_gls(), ep4_mul_sim_lot(), ep8_mul_cof(), ep8_mul_gls_imp(), ep8_mul_reg_gls(), ep8_mul_sim_lot(), ep_mul_cof(), ep_param_set(), fp12_exp_cyc_sim(), g1_is_valid(), g2_is_valid(), gt_exp_gls_naf(), gt_exp_gls_sac(), gt_exp_reg_gls(), gt_exp_reg_sac(), gt_is_valid(), pp_exp_afg16(), pp_exp_b12(), pp_exp_bn(), pp_exp_fm(), pp_exp_fm16(), pp_exp_k24(), pp_exp_k48(), pp_exp_k54(), pp_exp_k8(), pp_exp_kss(), pp_exp_kss(), pp_exp_sg(), pp_exp_sm9(), pp_map_k24(), pp_map_k48(), pp_map_k54(), pp_map_oatep_k12(), pp_map_oatep_k16(), pp_map_oatep_k18(), pp_map_oatep_k8(), pp_map_sim_k24(), pp_map_sim_k48(), pp_map_sim_oatep_k12(), pp_map_sim_oatep_k16(), pp_map_sim_oatep_k18(), and pp_map_sim_oatep_k8().
fp_prime_get_par_sps()
const int * fp_prime_get_par_sps (int * len)
Returns the absolute value of the variable used to parameterize the given prime modulus in sparse form.
Parameters
[out] len - the length of the representation.
Definition at line 294 of file relic_fp_prime.c.
References core_get(), _ctx_t::par_len, and _ctx_t::par_sps.
Referenced by gt_is_valid(), pp_exp_b12(), pp_exp_bn(), pp_exp_fm(), pp_exp_k24(), pp_exp_k48(), pp_exp_k54(), pp_exp_kss(), pp_exp_sg(), and pp_exp_sm9().
fp_param_get_sps()
void fp_param_get_sps (int * s, int * len)
Returns the absolute value of the variable used to parameterize the currently configured prime modulus in sparse form. The first argument must be an array of size (RLC_TERMS + 1).
Parameters
[out] s - the parameter in sparse form.
[out] len - the length of the parameter in sparse form.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
ERR_NO_VALID - if the current configuration is invalid.
Returns
the integer parameter in sparse form.
fp_copy()
void fp_copy (fp_t c, const fp_t a)
Copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the prime field element to copy.
Definition at line 39 of file relic_fp_util.c.
References dv_copy(), and RLC_FP_DIGS.
Referenced by ed_add_basic(), ed_copy(), ed_dbl_basic(), ed_neg_basic(), ed_neg_projc(), ed_norm_imp(), ed_norm_sim(), ed_pck(), ed_upk(), ep2_curve_set_twist(), ep3_curve_set_twist(), ep4_curve_set_twist(), ep8_curve_set_twist(), ep_copy(), ep_curve_mul_a(), ep_curve_mul_b(), ep_curve_set(), ep_curve_set_endom(), ep_curve_set_map(), ep_neg(), ep_norm_imp(), ep_norm_sim(), ep_pck(), ep_rhs(), ep_upk(), fp12_mul_dxs_basic(), fp12_mul_dxs_lazyr(), fp18_mul_dxs_basic(), fp18_mul_dxs_lazyr(), fp2_add_dig(), fp2_copy(), fp2_field_init(), fp2_frb(), fp2_inv_cyc(), fp2_mul_art(), fp2_mul_frb(), fp2_pck(), fp2_srt(), fp2_sub_dig(), fp2_upk(), fp3_add_dig(), fp3_copy(), fp3_field_init(), fp3_inv(), fp3_mul_art(), fp3_mul_frb(), fp3_sub_dig(), fp4_field_init(), fp4_mul_frb(), fp8_field_init(), fp8_mul_frb(), fp_crt(), fp_exp_basic(), fp_exp_dig(), fp_exp_monty(), fp_exp_slide(), fp_hlv_basic(), fp_inv_divst(), fp_inv_jmpds(), fp_inv_monty(), fp_inv_sim(), fp_lsh(), fp_norm(), fp_rdc_basic(), fp_rsh(), fp_smb_binar(), fp_smb_divst(), fp_smb_jmpds(), fp_srt(), fp_trs(), pp_add_k16_basic(), pp_add_k8_basic(), pp_dbl_k12_basic(), pp_dbl_k16_basic(), pp_dbl_k18_basic(), pp_dbl_k24_basic(), pp_dbl_k2_basic(), pp_dbl_k48_basic(), pp_dbl_k54_basic(), pp_dbl_k54_projc(), pp_dbl_k8_basic(), pp_fin_k16_oatep(), pp_mil_k16(), pp_mil_k54(), pp_mil_k8(), and pp_mil_lit_k2().
fp_copy_sec()
void fp_copy_sec (fp_t c, const fp_t a, dig_t bit)
Conditionally copies a field element to another field element.
Parameters
[out] c - the destination. @paraim[in] a - the source.
[in] bit - the condition bit to evaluate.
Definition at line 43 of file relic_fp_util.c.
References dv_copy_sec(), and RLC_FP_DIGS.
Referenced by ed_map_ell2_5mod8(), ed_mul_reg_imp(), ep2_mul_reg_imp(), ep3_mul_reg_imp(), ep4_mul_reg_imp(), ep8_mul_reg_imp(), ep_map_swift_impl(), ep_mul_reg_glv(), ep_mul_reg_imp(), fp16_srt(), fp2_copy_sec(), fp2_srt(), fp3_copy_sec(), fp_inv_divst(), fp_inv_jmpds(), fp_smb_divst(), fp_srt(), and fp_trs().
fp_zero()
void fp_zero (fp_t a)
Assigns zero to a prime field element.
Parameters
[out] a - the prime field element to asign.
Definition at line 47 of file relic_fp_util.c.
References dv_zero(), and RLC_FP_DIGS.
Referenced by ed_pck(), ed_read_bin(), ed_set_infty(), ep2_pck(), ep2_read_bin(), ep2_upk(), ep_curve_mul_a(), ep_curve_mul_b(), ep_param_set(), ep_pck(), ep_read_bin(), ep_set_infty(), fp2_field_init(), fp2_pck(), fp2_read_bin(), fp2_set_dig(), fp2_srt(), fp2_zero(), fp3_field_init(), fp3_set_dig(), fp3_zero(), fp_crt(), fp_inv_divst(), fp_inv_monty(), fp_neg_basic(), fp_prime_conv(), fp_prime_conv_dig(), fp_read_bin(), fp_read_str(), fp_smb_divst(), fp_smb_jmpds(), fp_srt(), and pp_dbl_lit_k12().
fp_is_zero()
int fp_is_zero (const fp_t a)
Tests if a prime field element is zero or not.
Parameters
[in] a - the prime field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 51 of file relic_fp_util.c.
References fp_prime_get(), and RLC_FP_DIGS.
Referenced by detect_opt(), detect_opt(), detect_opt(), detect_opt(), detect_opt(), ed_is_infty(), ed_map_ell2_5mod8(), ed_on_curve(), ep2_curve_set_map(), ep2_map_swift(), ep3_map(), ep4_map(), ep8_map(), ep_curve_set_endom(), ep_curve_set_map(), ep_is_infty(), ep_map_swift_impl(), ep_param_set(), fp2_cmp_dig(), fp2_is_zero(), fp2_sgn0(), fp2_srt(), fp3_cmp_dig(), fp3_field_init(), fp3_is_zero(), fp_cmp(), fp_crt(), fp_inv_basic(), fp_inv_binar(), fp_inv_divst(), fp_inv_exgcd(), fp_inv_jmpds(), fp_inv_lower(), fp_inv_monty(), fp_is_cub(), fp_is_sqr(), fp_neg_basic(), fp_smb_binar(), fp_smb_divst(), fp_srt(), pp_add_k1_basic(), pp_add_k1_projc(), pp_dbl_k1_basic(), pp_dbl_k1_projc(), and pp_mil_k1().
fp_is_even()
int fp_is_even (const fp_t a)
Tests if a prime field element is even or odd.
Parameters
[in] a - the prime field element to test.
Returns
1 if the argument is even, 0 otherwise.
Definition at line 66 of file relic_fp_util.c.
References bn_free, bn_is_even(), bn_new, bn_null, ERR_CAUGHT, fp_prime_back(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep2_map_swift(), ep4_map(), ep_map_swift_impl(), and fp_srt().
fp_get_bit()
int fp_get_bit (const fp_t a, uint_t bit)
Reads the bit stored in the given position on a prime field element.
Parameters
[in] a - the prime field element.
[in] bit - the bit position.
Returns
the bit value.
Definition at line 87 of file relic_fp_util.c.
References RLC_RIP.
Referenced by ed_pck(), ed_upk(), ed_write_bin(), ep2_upk(), ep2_write_bin(), ep_pck(), ep_upk(), ep_write_bin(), fp2_pck(), fp2_upk(), and fp2_write_bin().
fp_set_bit()
void fp_set_bit (fp_t a, uint_t bit, int value)
Stores a bit in a given position on a prime field element.
Parameters
[out] a - the prime field element.
[in] bit - the bit position.
[in] value - the bit value.
Definition at line 95 of file relic_fp_util.c.
References RLC_RIP.
Referenced by ed_pck(), ed_read_bin(), ep2_pck(), ep2_read_bin(), ep_pck(), ep_read_bin(), fp2_pck(), and fp2_read_bin().
fp_set_dig()
void fp_set_dig (fp_t c, dig_t a)
Assigns a small positive constant to a prime field element.
The constant must fit on a multiple precision digit, or dig_t type using only the number of bits specified on RLC_DIG.
Parameters
[out] c - the result.
[in] a - the constant to assign.
Definition at line 120 of file relic_fp_util.c.
References fp_prime_conv_dig().
Referenced by cp_cmlhs_sig(), cp_cmlhs_ver(), ed_map_ell2_5mod8(), ed_norm_imp(), ed_param_set(), ed_pck(), ed_read_bin(), ed_set_infty(), ed_upk(), ep2_pck(), ep2_upk(), ep_curve_set_map(), ep_curve_set_plain(), ep_map_basic_impl(), ep_map_swift_impl(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_norm_imp(), ep_param_set(), ep_pck(), ep_read_bin(), ep_upk(), fp12_upk_max(), fp2_field_init(), fp2_set_dig(), fp2_srt(), fp3_field_init(), fp3_set_dig(), fp_add_dig(), fp_crt(), fp_exp_basic(), fp_exp_dig(), fp_exp_monty(), fp_exp_slide(), fp_inv_divst(), fp_prime_set(), fp_sub_dig(), pp_add_k1_basic(), pp_add_k1_projc(), pp_dbl_k1_basic(), pp_dbl_k1_projc(), pp_map_sim_tatep_k1(), pp_map_sim_weilp_k1(), pp_map_tatep_k1(), pp_map_weilp_k1(), and pp_mil_k1().
fp_bits()
size_t fp_bits (const fp_t a)
Returns the number of bits of a prime field element.
Parameters
[in] a - the prime field element.
Returns
the number of bits.
Definition at line 110 of file relic_fp_util.c.
References RLC_DIG_LOG, RLC_FP_DIGS, and util_bits_dig().
Referenced by detect_opt(), detect_opt(), detect_opt(), detect_opt(), detect_opt(), and fp2_upk().
fp_rand()
void fp_rand (fp_t a)
Assigns a random value to a prime field element.
Parameters
[out] a - the prime field element to assign.
Definition at line 124 of file relic_fp_util.c.
References dv_cmp(), fp_prime_get(), fp_subm_low(), rand_bytes(), RLC_FP_BITS, RLC_FP_DIGS, RLC_LT, and RLC_RIP.
Referenced by ed_blind(), ep_blind(), fp2_rand(), and fp3_rand().
fp_norm()
void fp_norm (fp_t c, const fp_t a)
Normalizes a prime field element to a representative in [0, p - 1].
Parameters
[out] c - the normalized field element.
[in] a - the field element to normalize-
Definition at line 140 of file relic_fp_util.c.
References dv_cmp(), fp_copy(), fp_prime_get(), fp_subn_low(), RLC_FP_DIGS, and RLC_LT.
Referenced by ed_pck(), ed_upk(), fp_cmp(), fp_prime_back(), and fp_print().
fp_print()
void fp_print (const fp_t a)
Prints a prime field element to standard output.
Parameters
[in] a - the prime field element to print.
Definition at line 147 of file relic_fp_util.c.
References bn_free, bn_new, bn_null, bn_read_raw(), bn_trim(), ERR_CAUGHT, fp_norm(), fp_prime_back(), fp_prime_get(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, RLC_TRY, util_print, and util_print_dig().
Referenced by ed_print(), ep_print(), fp2_print(), and fp3_print().
fp_size_str()
size_t fp_size_str (const fp_t a, uint_t radix)
Returns the number of digits in radix necessary to store a multiple precision integer. The radix must be a power of 2 included in the interval [2, 64].
Parameters
[in] a - the prime field element.
[in] radix - the radix.
Exceptions
ERR_NO_VALID - if the radix is invalid.
Returns
the number of digits in the given radix.
Definition at line 187 of file relic_fp_util.c.
References bn_free, bn_new, bn_null, bn_size_str(), ERR_CAUGHT, fp_prime_back(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp_read_str()
void fp_read_str (fp_t a, const char * str, size_t len, uint_t radix)
Reads a prime field element from a string in a given radix. The radix must be a power of 2 included in the interval [2, 64].
Parameters
[out] a - the result.
[in] str - the string.
[in] len - the size of the string.
[in] radix - the radix.
Exceptions
ERR_NO_VALID - if the radix is invalid.
Definition at line 209 of file relic_fp_util.c.
References bn_free, bn_is_zero(), bn_new, bn_null, bn_read_str(), bn_sign(), ERR_CAUGHT, fp_neg, fp_prime_conv(), fp_prime_conv_dig(), fp_zero(), RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by ed_param_set(), ep2_curve_get_coeffs(), ep2_curve_set_ctmap(), ep_param_get_coeffs(), and ep_param_set_ctmap().
fp_write_str()
void fp_write_str (char * str, size_t len, const fp_t a, uint_t radix)
Writes a prime field element to a string in a given radix. The radix must be a power of 2 included in the interval [2, 64].
Parameters
[out] str - the string.
[in] len - the buffer capacity.
[in] a - the prime field element to write.
[in] radix - the radix.
Exceptions
ERR_BUFFER - if the buffer capacity is insufficient.
ERR_NO_VALID - if the radix is invalid.
Definition at line 238 of file relic_fp_util.c.
References bn_free, bn_new, bn_null, bn_write_str(), ERR_CAUGHT, fp_prime_back(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp_read_bin()
void fp_read_bin (fp_t a, const uint8_t * bin, size_t len)
Reads a prime field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not RLC_FP_BYTES.
Definition at line 257 of file relic_fp_util.c.
References bn_cmp(), bn_free, bn_is_zero(), bn_new, bn_null, bn_read_bin(), bn_sign(), core_get(), ERR_CAUGHT, ERR_NO_BUFFER, ERR_NO_VALID, fp_prime_conv(), fp_prime_conv_dig(), fp_zero(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_LT, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by ed_read_bin(), ep_read_bin(), fp2_read_bin(), and fp3_read_bin().
fp_write_bin()
void fp_write_bin (uint8_t * bin, size_t len, const fp_t a)
Writes a prime field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the prime field element to write.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not RLC_FP_BYTES.
Definition at line 294 of file relic_fp_util.c.
References bn_free, bn_new, bn_null, bn_write_bin(), ERR_CAUGHT, ERR_NO_BUFFER, fp_prime_back(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.
Referenced by ed_write_bin(), ep_write_bin(), fp2_write_bin(), and fp3_write_bin().
fp_cmp()
int fp_cmp (const fp_t a, const fp_t b)
Returns the result of a comparison between two prime field elements.
Parameters
[in] a - the first prime field element.
[in] b - the second prime field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 57 of file relic_fp_cmp.c.
References ERR_CAUGHT, fp_free, fp_is_zero(), fp_new, fp_norm(), fp_null, fp_sub, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_NE, RLC_THROW, and RLC_TRY.
Referenced by detect_opt(), ed_cmp(), ed_is_infty(), ed_map_ell2_5mod8(), ed_on_curve(), ep_cmp(), ep_on_curve(), fp2_cmp(), fp3_cmp(), fp_cmp_dig(), fp_crt(), fp_srt(), pp_add_k1_basic(), pp_add_k1_projc(), and pp_map_weilp_k1().
fp_cmp_dig()
int fp_cmp_dig (const fp_t a, dig_t b)
Returns the result of a signed comparison between a prime field element and a digit.
Parameters
[in] a - the prime field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 38 of file relic_fp_cmp.c.
References ERR_CAUGHT, fp_cmp(), fp_free, fp_new, fp_null, fp_prime_conv_dig(), RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by detect_opt(), ed_is_infty(), fp2_cmp_dig(), fp3_cmp_dig(), fp_crt(), fp_is_cub(), fp_smb_basic(), and fp_srt().
fp_add_basic()
void fp_add_basic (fp_t c, const fp_t a, const fp_t b)
Adds two prime field elements using basic addition. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first prime field element to add.
[in] b - the second prime field element to add.
Definition at line 41 of file relic_fp_add.c.
References dv_cmp(), fp_addn_low(), fp_prime_get(), fp_subn_low(), RLC_FP_DIGS, and RLC_LT.
fp_add_integ()
void fp_add_integ (fp_t c, const fp_t a, const fp_t b)
Adds two prime field elements with integrated modular reduction. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first prime field element to add.
[in] b - the second prime field element to add.
Definition at line 54 of file relic_fp_add.c.
References fp_addm_low().
fp_add_dig()
void fp_add_dig (fp_t c, const fp_t a, dig_t b)
Adds a prime field element and a digit. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first prime field element to add.
[in] b - the digit to add.
Definition at line 60 of file relic_fp_add.c.
References core_get(), dv_cmp(), ERR_CAUGHT, fp_add, fp_add1_low(), fp_free, fp_new, fp_null, fp_prime_get(), fp_set_dig(), fp_subn_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_LT, RLC_THROW, and RLC_TRY.
Referenced by ed_add_basic(), ed_dbl_basic(), ed_map_ell2_5mod8(), ed_param_set(), ep3_rhs(), ep4_rhs(), ep8_rhs(), ep_curve_set_map(), ep_map_basic_impl(), ep_map_swift_impl(), ep_rhs(), fp12_back_cyc(), fp12_back_cyc_sim(), fp16_sqr_cyc(), fp18_back_cyc(), fp18_back_cyc_sim(), fp24_back_cyc(), fp24_back_cyc_sim(), fp2_add_dig(), fp3_add_dig(), fp48_back_cyc(), fp48_back_cyc_sim(), fp54_back_cyc(), fp54_back_cyc_sim(), fp8_sqr_cyc(), fp_inv_divst(), and fp_prime_set().
fp_sub_basic()
void fp_sub_basic (fp_t c, const fp_t a, const fp_t b)
Subtracts a prime field element from another using basic subtraction. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the prime field element.
[in] b - the prime field element to subtract.
Definition at line 92 of file relic_fp_add.c.
References fp_addn_low(), fp_prime_get(), and fp_subn_low().
fp_sub_integ()
void fp_sub_integ (fp_t c, const fp_t a, const fp_t b)
Subtracts a prime field element from another with integrated modular reduction. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the prime field element.
[in] b - the prime field element to subtract.
Definition at line 105 of file relic_fp_add.c.
References fp_subm_low().
fp_sub_dig()
void fp_sub_dig (fp_t c, const fp_t a, dig_t b)
Subtracts a digit from a prime field element. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the prime field element.
[in] b - the digit to subtract.
Definition at line 111 of file relic_fp_add.c.
References core_get(), ERR_CAUGHT, fp_addn_low(), fp_free, fp_new, fp_null, fp_prime_get(), fp_set_dig(), fp_sub, fp_sub1_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ed_add_basic(), ed_dbl_basic(), ed_on_curve(), ed_rhs(), ed_upk(), ep2_map_swift(), ep3_rhs(), ep4_map(), ep4_rhs(), ep8_rhs(), ep_curve_set_endom(), ep_map_swift_impl(), ep_param_set(), ep_rhs(), fp16_sqr_cyc(), fp2_sub_dig(), fp2_upk(), fp3_srt(), fp3_sub_dig(), and fp8_sqr_cyc().
fp_neg_basic()
void fp_neg_basic (fp_t c, const fp_t a)
Negates a prime field element using basic negation.
Parameters
[out] c - the result.
[out] a - the prime field element to negate.
Definition at line 143 of file relic_fp_add.c.
References fp_is_zero(), fp_prime_get(), fp_subn_low(), and fp_zero().
fp_neg_integ()
void fp_neg_integ (fp_t c, const fp_t a)
Negates a prime field element using integrated negation.
Parameters
[out] c - the result.
[out] a - the prime field element to negate.
Definition at line 155 of file relic_fp_add.c.
References fp_negm_low().
fp_dbl_basic()
void fp_dbl_basic (fp_t c, const fp_t a)
Doubles a prime field element using basic addition.
Parameters
[out] c - the result.
[in] a - the first prime field element to add.
Definition at line 163 of file relic_fp_add.c.
References dv_cmp(), fp_lsh1_low(), fp_prime_get(), fp_subn_low(), RLC_FP_DIGS, and RLC_LT.
fp_dbl_integ()
void fp_dbl_integ (fp_t c, const fp_t a)
Doubles a prime field element with integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the first prime field element to add.
Definition at line 176 of file relic_fp_add.c.
References fp_dblm_low().
fp_hlv_basic()
void fp_hlv_basic (fp_t c, const fp_t a)
Halves a prime field element.
Parameters
[out] c - the result.
[in] a - the prime field element to halve.
Definition at line 41 of file relic_fp_div.c.
References fp_addn_low(), fp_copy(), fp_prime_get(), fp_rsh1_low(), RLC_DIG, and RLC_FP_DIGS.
fp_hlv_integ()
void fp_hlv_integ (fp_t c, const fp_t a)
Halves a prime field element with integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the prime field element to halve.
Definition at line 59 of file relic_fp_div.c.
References fp_hlvm_low().
fp_trs()
void fp_trs (fp_t c, const fp_t a)
Divides a prime field element by 3 (trisecting). Computes C = A/3.
Parameters
[out] C - the result.
[in] A - the first prime field element.
Definition at line 65 of file relic_fp_div.c.
References core_get(), ERR_CAUGHT, fp_copy(), fp_copy_sec(), fp_free, fp_new, fp_null, fp_sub, RLC_3MASK, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_MUL_DIG, RLC_THROW, and RLC_TRY.
fp_mul_basic()
void fp_mul_basic (fp_t c, const fp_t a, const fp_t b)
Multiples two prime field elements using Schoolbook multiplication.
Parameters
[out] c - the result.
[in] a - the first prime field element to multiply.
[in] b - the second prime field element to multiply.
Definition at line 181 of file relic_fp_mul.c.
References dv_free, dv_new, dv_null, dv_zero(), ERR_CAUGHT, fp_mula_low(), fp_rdc, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
fp_mul_comba()
void fp_mul_comba (fp_t c, const fp_t a, const fp_t b)
Multiples two prime field elements using Comba multiplication.
Parameters
[out] c - the result.
[in] a - the first prime field element to multiply.
[in] b - the second prime field element to multiply.
Definition at line 211 of file relic_fp_mul.c.
References dv_free, dv_new, dv_null, ERR_CAUGHT, fp_muln_low(), fp_rdc, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp_mul_integ()
void fp_mul_integ (fp_t c, const fp_t a, const fp_t b)
Multiples two prime field elements using multiplication integrated with modular reduction.
Parameters
[out] c - the result.
[in] a - the first prime field element to multiply.
[in] b - the second prime field element to multiply.
Definition at line 235 of file relic_fp_mul.c.
References fp_mulm_low().
fp_mul_karat()
void fp_mul_karat (fp_t c, const fp_t a, const fp_t b)
Multiples two prime field elements using Karatsuba multiplication.
Parameters
[out] c - the result.
[in] a - the first prime field element to multiply.
[in] b - the second prime field element to multiply.
Definition at line 243 of file relic_fp_mul.c.
References dv_free, dv_new, dv_null, dv_zero(), ERR_CAUGHT, FP_KARAT, fp_mul_karat_imp(), fp_muln_low(), fp_rdc, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
fp_mul_dig()
void fp_mul_dig (fp_t c, const fp_t a, dig_t b)
Multiplies a prime field element by a digit. Computes c = a * b.
Parameters
[out] c - the result.
[in] a - the prime field element.
[in] b - the digit to multiply.
Definition at line 162 of file relic_fp_mul.c.
References dv_free, dv_new, dv_null, ERR_CAUGHT, fp_mul, fp_prime_conv_dig(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep_curve_mul_a(), ep_curve_mul_b(), ep_curve_set_map(), ep_map_swift_impl(), fp2_inv(), fp2_mul_dig(), and fp3_mul_dig().
fp_sqr_basic()
void fp_sqr_basic (fp_t c, const fp_t a)
Squares a prime field element using Schoolbook squaring.
Parameters
[out] c - the result.
[in] a - the prime field element to square.
Definition at line 165 of file relic_fp_sqr.c.
References bn_sqra_low(), dv_new, dv_null, dv_zero(), ERR_CAUGHT, fp_free, fp_rdc, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
fp_sqr_comba()
void fp_sqr_comba (fp_t c, const fp_t a)
Squares a prime field element using Comba squaring.
Parameters
[out] c - the result.
[in] a - the prime field element to square.
Definition at line 195 of file relic_fp_sqr.c.
References dv_new, dv_null, ERR_CAUGHT, fp_free, fp_rdc, fp_sqrn_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp_sqr_integ()
void fp_sqr_integ (fp_t c, const fp_t a)
Squares two prime field elements using squaring integrated with modular reduction.
Parameters
[out] c - the result.
[in] a - the binary field element to square.
Definition at line 218 of file relic_fp_sqr.c.
References fp_sqrm_low().
fp_sqr_karat()
void fp_sqr_karat (fp_t c, const fp_t a)
Squares a prime field element using Karatsuba squaring.
Parameters
[out] c - the result.
[in] a - the prime field element to square.
Definition at line 226 of file relic_fp_sqr.c.
References dv_free, dv_new, dv_null, dv_zero(), ERR_CAUGHT, FP_KARAT, fp_rdc, fp_sqr_karat_imp(), fp_sqrn_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
fp_lsh()
void fp_lsh (fp_t c, const fp_t a, uint_t bits)
Shifts a prime field element number to the left. Computes c = a * 2^bits.
Parameters
[out] c - the result.
[in] a - the prime field element to shift.
[in] bits - the number of bits to shift.
Definition at line 39 of file relic_fp_shift.c.
References dv_lshd(), fp_copy(), fp_lsh1_low(), fp_lshb_low(), RLC_FP_DIGS, and RLC_RIP.
fp_rsh()
void fp_rsh (fp_t c, const fp_t a, uint_t bits)
Shifts a prime field element to the right. Computes c = floor(a / 2^bits).
Parameters
[out] c - the result.
[in] a - the prime field element to shift.
[in] bits - the number of bits to shift.
Definition at line 65 of file relic_fp_shift.c.
References dv_rshd(), fp_copy(), fp_rsh1_low(), fp_rshb_low(), RLC_FP_DIGS, and RLC_RIP.
fp_rdc_basic()
void fp_rdc_basic (fp_t c, dv_t a)
Reduces a multiplication result modulo the prime field modulo using division-based reduction.
Parameters
[out] c - the result.
[in] a - the multiplication result to reduce.
Definition at line 42 of file relic_fp_rdc.c.
References bn_divn_low(), dv_copy(), dv_free, dv_new, dv_null, ERR_CAUGHT, fp_copy(), fp_prime_get(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
fp_rdc_monty_basic()
void fp_rdc_monty_basic (fp_t c, dv_t a)
Reduces a multiplication result modulo the prime field order using Shoolbook Montgomery reduction.
Parameters
[out] c - the result.
[in] a - the multiplication result to reduce.
Definition at line 77 of file relic_fp_rdc.c.
References fp_addm_low(), fp_mula_low(), fp_prime_get(), fp_prime_get_rdc(), and RLC_FP_DIGS.
fp_rdc_monty_comba()
void fp_rdc_monty_comba (fp_t c, dv_t a)
Reduces a multiplication result modulo the prime field order using Comba Montgomery reduction.
Parameters
[out] c - the result.
[in] a - the multiplication result to reduce.
Definition at line 94 of file relic_fp_rdc.c.
References fp_rdcn_low().
fp_rdc_quick()
void fp_rdc_quick (fp_t c, dv_t a)
Reduces a multiplication result modulo the prime field modulo using fast reduction.
Parameters
[out] c - the result.
[in] a - the multiplication result to reduce.
Definition at line 104 of file relic_fp_rdc.c.
References fp_prime_get(), and fp_rdcs_low().
fp_inv_basic()
void fp_inv_basic (fp_t c, const fp_t a)
Inverts a prime field element using Fermat's Little Theorem.
Parameters
[out] c - the result.
[in] a - the prime field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 93 of file relic_fp_inv.c.
References bn_free, bn_new, bn_null, bn_sub_dig(), dv_copy(), ERR_CAUGHT, ERR_NO_VALID, fp_exp, fp_is_zero(), fp_prime_get(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
fp_inv_binar()
void fp_inv_binar (fp_t c, const fp_t a)
Inverts a prime field element using the binary method.
Parameters
[out] c - the result.
[in] a - the prime field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 124 of file relic_fp_inv.c.
References bn_add(), bn_cmp(), bn_cmp_dig(), bn_copy(), bn_free, bn_hlv(), bn_new, bn_null, bn_set_dig(), bn_sign(), bn_sub(), bn_zero(), dv_copy(), ERR_CAUGHT, ERR_NO_VALID, fp_is_zero(), fp_prime_back(), fp_prime_conv(), fp_prime_get(), fp_rsh1_low(), RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FP_DIGS, RLC_GT, RLC_LT, RLC_NEG, RLC_THROW, and RLC_TRY.
fp_inv_monty()
void fp_inv_monty (fp_t c, const fp_t a)
Inverts a prime field element using Montgomery inversion.
Parameters
[out] c - the result.
[in] a - the prime field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 241 of file relic_fp_inv.c.
References bn_add(), bn_cmp(), bn_dbl(), bn_free, bn_is_zero(), bn_mod_monty_back(), bn_mod_monty_conv(), bn_new, bn_null, bn_read_raw(), bn_set_2b(), bn_set_dig(), bn_sub1_low(), bn_subn_low(), bn_trim(), bn_zero(), dv_cmp(), dv_copy(), dv_zero(), ERR_CAUGHT, ERR_NO_VALID, fp_copy(), fp_is_zero(), fp_mul, fp_prime_get(), fp_prime_get_conv(), fp_rsh1_low(), fp_subn_low(), fp_zero(), RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FP_DIGS, RLC_GT, RLC_LT, RLC_THROW, and RLC_TRY.
fp_inv_exgcd()
void fp_inv_exgcd (fp_t c, const fp_t a)
Inverts a prime field element using the Euclidean Extended Algorithm.
Parameters
[out] c - the result.
[in] a - the prime field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 375 of file relic_fp_inv.c.
References bn_add(), bn_cmp_dig(), bn_copy(), bn_div_rem(), bn_free, bn_mul, bn_new, bn_null, bn_set_dig(), bn_sign(), bn_sub(), bn_zero(), dv_copy(), ERR_CAUGHT, ERR_NO_VALID, fp_is_zero(), fp_prime_back(), fp_prime_conv(), fp_prime_get(), RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FP_DIGS, RLC_NEG, RLC_THROW, and RLC_TRY.
fp_inv_divst()
void fp_inv_divst (fp_t c, const fp_t a)
Inverts a prime field element using the constant-time division step approach by Bernstein and Bo-Yin Yang.
Parameters
[out] c - the result.
[in] a - the prime field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 446 of file relic_fp_inv.c.
References bn_add_dig(), bn_addn_low(), bn_free, bn_lsh(), bn_new, bn_null, bn_set_dig(), dv_copy(), dv_copy_sec(), dv_free, dv_new, dv_null, dv_swap_sec(), dv_zero(), ERR_CAUGHT, ERR_NO_VALID, fp_add1_low(), fp_add_dig(), fp_addm_low(), fp_copy(), fp_copy_sec(), fp_dblm_low(), fp_exp, fp_free, fp_hlv, fp_is_zero(), fp_mul, fp_neg, fp_negm_low(), fp_new, fp_null, FP_PRIME, fp_prime_get(), fp_rdcn_low(), fp_rsh1_low(), fp_set_dig(), fp_zero(), RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FP_DIGS, RLC_POS, RLC_SEL, RLC_THROW, and RLC_TRY.
fp_inv_jmpds()
void fp_inv_jmpds (fp_t c, const fp_t a)
Inverts a prime field element using the constant-time jump division step by Bernstein and Bo-Yin Yang.
Parameters
[out] c - the result.
[in] a - the prime field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 562 of file relic_fp_inv.c.
References bn_addn_low(), bn_muls_low(), bn_negs_low(), bn_rshs_low(), core_get(), dv_copy(), dv_copy_sec(), dv_free, dv_new, dv_null, dv_zero(), ERR_CAUGHT, ERR_NO_VALID, fp_add, fp_addd_low(), fp_copy(), fp_copy_sec(), fp_free, fp_is_zero(), fp_mul, fp_neg, fp_negm_low(), fp_new, fp_null, FP_PRIME, fp_prime_get(), fp_rdc, fp_rdcn_low(), fp_subd_low(), jumpdivstep(), RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FP_DIGS, RLC_MASK, RLC_POS, RLC_SEL, RLC_SIGN, RLC_THROW, and RLC_TRY.
fp_inv_lower()
void fp_inv_lower (fp_t c, const fp_t a)
Inverts a prime field element using a direct call to the lower layer.
Parameters
[out] c - the result.
[in] a - the prime field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 809 of file relic_fp_inv.c.
References ERR_NO_VALID, fp_invm_low(), fp_is_zero(), and RLC_THROW.
fp_inv_sim()
void fp_inv_sim (fp_t * c, const fp_t * a, int n)
Inverts multiple prime field elements simultaneously.
Parameters
[out] c - the result.
[in] a - the prime field elements to invert.
[in] n - the number of elements.
Definition at line 820 of file relic_fp_inv.c.
References ERR_CAUGHT, ERR_NO_MEMORY, fp_copy(), fp_free, fp_inv, fp_mul, fp_new, fp_null, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by ed_norm_sim(), ep_map_swift_impl(), and ep_norm_sim().
fp_smb_basic()
int fp_smb_basic (const fp_t a)
Computes Legendre symbol of a prime field element using exponentiation.
Parameters
[in] a - the prime field element to compute.
Returns
the result.
Definition at line 239 of file relic_fp_smb.c.
References bn_free, bn_hlv(), bn_new, bn_null, bn_sub_dig(), dv_copy(), ERR_CAUGHT, fp_cmp_dig(), fp_exp, fp_neg, fp_prime_get(), RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FP_DIGS, RLC_POS, RLC_SEL, RLC_THROW, and RLC_TRY.
fp_smb_binar()
int fp_smb_binar (const fp_t a)
Computes Legendre symbol of a prime field element using the binary method.
Parameters
[in] a - the prime field element to compute.
Returns
the result.
Definition at line 276 of file relic_fp_smb.c.
References bn_addn_low(), bn_muls_low(), bn_negs_low(), bn_rshb_low(), dv_copy(), dv_free, dv_new, dv_null, dv_zero(), ERR_CAUGHT, fp_copy(), fp_is_zero(), fp_prime_get(), fp_rdcn_low(), porninstep(), RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FP_DIGS, RLC_LSH, RLC_POS, RLC_SIGN, RLC_THROW, RLC_TRY, and util_bits_dig().
fp_smb_divst()
int fp_smb_divst (const fp_t a)
Computes Legendre symbol of a prime field element using the constant-time division step approach by Bernstein and Bo-Yin Yang.
Parameters
[in] a - the prime field element to compute.
Returns
the result.
Definition at line 364 of file relic_fp_smb.c.
References bn_add_dig(), bn_addn_low(), bn_free, bn_lsh(), bn_negs_low(), bn_new, bn_null, bn_set_dig(), dv_cmp(), dv_cmp_sec(), dv_copy(), dv_free, dv_new, dv_null, dv_zero(), ERR_CAUGHT, fp_add1_low(), fp_copy(), fp_copy_sec(), fp_is_zero(), FP_PRIME, fp_prime_get(), fp_rdcn_low(), fp_rsh1_low(), fp_subn_low(), fp_zero(), RLC_CATCH_ANY, RLC_DIG, RLC_EQ, RLC_FINALLY, RLC_FP_DIGS, RLC_LT, RLC_POS, RLC_SEL, RLC_THROW, and RLC_TRY.
fp_smb_jmpds()
int fp_smb_jmpds (const fp_t a)
Computes Legendre symbol of a prime field element using the constant-time jump division step approach by Bernstein and Bo-Yin Yang.
Parameters
[in] a - the prime field element to compute.
Returns
the result.
Definition at line 470 of file relic_fp_smb.c.
References bn_addn_low(), bn_muls_low(), bn_negs_low(), bn_rshs_low(), dv_cmp_sec(), dv_copy(), dv_free, dv_new, dv_null, dv_zero(), ERR_CAUGHT, fp_copy(), FP_PRIME, fp_prime_get(), fp_rdcn_low(), fp_zero(), jumpdivstep(), RLC_CATCH_ANY, RLC_DIG, RLC_EQ, RLC_FINALLY, RLC_FP_DIGS, RLC_SEL, RLC_SIGN, RLC_THROW, and RLC_TRY.
fp_smb_lower()
int fp_smb_lower (const fp_t a)
Computes Legendre symbol a prime field element using a direct call to the lower layer.
Parameters
[in] a - the prime field element to invert.
Returns
the result.
Definition at line 574 of file relic_fp_smb.c.
References fp_smbm_low().
fp_exp_basic()
void fp_exp_basic (fp_t c, const fp_t a, const bn_t b)
Exponentiates a prime field element using the binary method.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 41 of file relic_fp_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), ERR_CAUGHT, fp_copy(), fp_free, fp_inv, fp_mul, fp_new, fp_null, fp_set_dig(), fp_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
fp_exp_slide()
void fp_exp_slide (fp_t c, const fp_t a, const bn_t b)
Exponentiates a prime field element using the sliding window method.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 84 of file relic_fp_exp.c.
References bn_is_zero(), bn_rec_slw(), bn_sign(), ERR_CAUGHT, fp_copy(), fp_free, fp_inv, fp_mul, fp_new, fp_null, fp_set_dig(), fp_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_THROW, RLC_TRY, RLC_WIDTH, and util_bits_dig().
fp_exp_monty()
void fp_exp_monty (fp_t c, const fp_t a, const bn_t b)
Exponentiates a prime field element using the constant-time Montgomery powering ladder method.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 151 of file relic_fp_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), dv_swap_sec(), ERR_CAUGHT, fp_copy(), fp_free, fp_inv, fp_mul, fp_new, fp_null, fp_set_dig(), fp_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_NEG, RLC_THROW, and RLC_TRY.
fp_exp_dig()
void fp_exp_dig (fp_t c, const fp_t a, dig_t b)
Computes a power of a field element by a small exponent.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 193 of file relic_fp_exp.c.
References ERR_CAUGHT, fp_copy(), fp_free, fp_mul, fp_new, fp_null, fp_set_dig(), fp_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, RLC_TRY, and util_bits_dig().
fp_is_sqr()
int fp_is_sqr (const fp_t a)
Tests if a prime field element is a quadratic residue.
Parameters
[in] a - the prime field element to test.
Returns
1 if the argument is even, 0 otherwise.
Definition at line 38 of file relic_fp_srt.c.
References fp_is_zero(), and fp_smb.
Referenced by ep_curve_set_map(), ep_map_swift_impl(), fp16_is_sqr(), fp2_is_sqr(), fp2_srt(), fp3_is_sqr(), fp4_is_sqr(), fp8_is_sqr(), fp_prime_set(), and fp_srt().
fp_srt()
int fp_srt (fp_t c, const fp_t a)
Extracts the square root of a prime field element. Computes c = sqrt(a). The other square root is the negation of c.
Parameters
[out] c - the result.
[in] a - the prime field element.
Returns
- 1 if there is a square root, 0 otherwise.
Definition at line 46 of file relic_fp_srt.c.
References bn_add_dig(), bn_free, bn_new, bn_null, bn_rsh(), dv_copy(), ERR_CAUGHT, fp_cmp(), fp_cmp_dig(), fp_copy(), fp_copy_sec(), fp_exp, fp_free, fp_is_even(), fp_is_sqr(), fp_is_zero(), fp_mul, fp_neg, fp_new, fp_null, fp_prime_get(), fp_prime_get_2ad(), fp_prime_get_mod8(), fp_prime_get_srt(), fp_sqr, fp_zero(), RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
Referenced by ed_param_set(), ed_upk(), ep_curve_set_map(), ep_curve_set_plain(), ep_map_basic_impl(), ep_map_swift_impl(), ep_param_set(), ep_upk(), fp2_srt(), and fp2_upk().
fp_is_cub()
int fp_is_cub (const fp_t a)
Tests if a prime field element is a cubic residue.
Parameters
[in] a - the prime field element to test.
Returns
1 if the argument is even, 0 otherwise.
Definition at line 38 of file relic_fp_crt.c.
References bn_div_dig(), bn_free, bn_new, bn_null, bn_sub_dig(), dv_copy(), ERR_CAUGHT, fp_cmp_dig(), fp_exp, fp_is_zero(), fp_prime_get(), fp_prime_get_mod18(), RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FP_DIGS, RLC_POS, RLC_THROW, and RLC_TRY.
Referenced by fp_crt(), and fp_prime_set().
fp_crt()
int fp_crt (fp_t c, const fp_t a)
Extracts the cube root of a prime field element. Computes c = crt(a). The other cube root is the square of c.
Parameters
[out] c - the result.
[in] a - the prime field element.
Returns
- 1 if there is a cube root, 0 otherwise.
Definition at line 70 of file relic_fp_crt.c.
References bn_add_dig(), bn_dbl(), bn_div_dig(), bn_free, bn_mod_dig(), bn_new, bn_null, bn_sub_dig(), dv_copy(), ERR_CAUGHT, fp_cmp(), fp_cmp_dig(), fp_copy(), fp_exp, fp_free, fp_inv, fp_is_cub(), fp_is_zero(), fp_mul, fp_new, fp_null, fp_prime_get(), fp_prime_get_crt(), fp_prime_get_mod18(), fp_set_dig(), fp_sqr, fp_zero(), RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.