RELIC: src/eb/relic_eb_mul_sim.c File Reference
relic_eb_mul_sim.c File Reference
Elliptic curves over binary fields
#include "relic_core.h"
Functions
static void eb_mul_sim_kbltz (eb_t r, const eb_t p, const bn_t k, const eb_t q, const bn_t m, const eb_t *t)
static void eb_mul_sim_plain (eb_t r, const eb_t p, const bn_t k, const eb_t q, const bn_t m, const eb_t *t)
void eb_mul_sim_basic (eb_t r, const eb_t p, const bn_t k, const eb_t q, const bn_t m)
void eb_mul_sim_trick (eb_t r, const eb_t p, const bn_t k, const eb_t q, const bn_t m)
void eb_mul_sim_inter (eb_t r, const eb_t p, const bn_t k, const eb_t q, const bn_t m)
void eb_mul_sim_joint (eb_t r, const eb_t p, const bn_t k, const eb_t q, const bn_t m)
void eb_mul_sim_gen (eb_t r, const bn_t k, const eb_t q, const bn_t m)
Detailed Description
Implementation of simultaneous point multiplication on binary elliptic curves.
Definition in file relic_eb_mul_sim.c.
Function Documentation
eb_mul_sim_kbltz()
static void eb_mul_sim_kbltz (eb_t r, const eb_t p, const bn_t k, const eb_t q, const bn_t m, const eb_t * t) static
Multiplies and adds two binary elliptic curve points simultaneously, optionally choosing the first point as the generator depending on an optional table of precomputed points.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer.
[in] t - the pointer to a precomputed table.
Definition at line 55 of file relic_eb_mul_sim.c.
References BASIC, bn_rec_tnaf(), bn_sign(), eb_add, eb_curve_opt_a(), eb_frb(), eb_free, eb_new, eb_norm(), eb_null, eb_set_infty(), eb_sub, eb_tab(), ERR_CAUGHT, fb_set_bit(), RLC_CATCH_ANY, RLC_DEPTH, RLC_FB_BITS, RLC_FINALLY, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, RLC_WIDTH, and RLC_ZERO.
Referenced by eb_mul_sim_gen(), and eb_mul_sim_inter().
eb_mul_sim_plain()
static void eb_mul_sim_plain (eb_t r, const eb_t p, const bn_t k, const eb_t q, const bn_t m, const eb_t * t) static
Multiplies and adds two binary elliptic curve points simultaneously, optionally choosing the first point as the generator depending on an optional table of precomputed points.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer.
[in] t - the pointer to a precomputed table.
Definition at line 179 of file relic_eb_mul_sim.c.
References bn_rec_naf(), bn_sign(), eb_add, eb_dbl, eb_free, eb_new, eb_norm(), eb_null, eb_set_infty(), eb_sub, eb_tab(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_FB_BITS, RLC_FINALLY, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by eb_mul_sim_gen(), and eb_mul_sim_inter().
eb_mul_sim_basic()
void eb_mul_sim_basic (eb_t r, const eb_t p, const bn_t k, const eb_t q, const bn_t m)
Multiplies and adds two binary elliptic curve points simultaneously using scalar multiplication and point addition.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 281 of file relic_eb_mul_sim.c.
References eb_add, eb_free, eb_mul, eb_new, eb_norm(), eb_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
eb_mul_sim_trick()
void eb_mul_sim_trick (eb_t r, const eb_t p, const bn_t k, const eb_t q, const bn_t m)
Multiplies and adds two binary elliptic curve points simultaneously using shamir's trick.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 305 of file relic_eb_mul_sim.c.
References bn_free, bn_is_zero(), bn_new, bn_null, bn_rec_win(), bn_sign(), eb_add, eb_copy(), eb_curve_get_ord(), eb_dbl, eb_free, eb_is_infty(), eb_mul, eb_neg, eb_new, eb_norm(), eb_norm_sim(), eb_null, eb_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_CEIL, RLC_FB_BITS, RLC_FINALLY, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
eb_mul_sim_inter()
void eb_mul_sim_inter (eb_t r, const eb_t p, const bn_t k, const eb_t q, const bn_t m)
Multiplies and adds two binary elliptic curve points simultaneously using interleaving of NAFs.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 397 of file relic_eb_mul_sim.c.
References bn_is_zero(), eb_curve_is_kbltz(), eb_is_infty(), eb_mul, eb_mul_sim_kbltz(), and eb_mul_sim_plain().
eb_mul_sim_joint()
void eb_mul_sim_joint (eb_t r, const eb_t p, const bn_t k, const eb_t q, const bn_t m)
Multiplies and adds two binary elliptic curve points simultaneously using Solinas' Joint Sparse Form.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 425 of file relic_eb_mul_sim.c.
References bn_bits(), bn_is_zero(), bn_rec_jsf(), bn_sign(), eb_add, eb_copy(), eb_dbl, eb_free, eb_is_infty(), eb_mul, eb_neg, eb_new, eb_norm(), eb_norm_sim(), eb_null, eb_set_infty(), eb_sub, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FB_BITS, RLC_FINALLY, RLC_MAX, RLC_NEG, RLC_THROW, and RLC_TRY.
eb_mul_sim_gen()
void eb_mul_sim_gen (eb_t r, const bn_t k, const eb_t q, const bn_t m)
Multiplies and adds the generator and a binary elliptic curve point simultaneously. Computes R = [k]G + [m]Q.
Parameters
[out] r - the result.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer.
Definition at line 499 of file relic_eb_mul_sim.c.
References bn_is_zero(), eb_curve_get_gen(), eb_curve_get_tab(), eb_curve_is_kbltz(), eb_free, eb_is_infty(), eb_mul, eb_mul_gen(), eb_mul_sim, eb_mul_sim_kbltz(), eb_mul_sim_plain(), eb_new, eb_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.