RELIC: src/ep/relic_ep_curve.c File Reference
relic_ep_curve.c File Reference
Elliptic curves over prime fields
#include "relic_core.h"
Functions
static void detect_opt (int *opt, fp_t a)
static void ep_curve_set_map (void)
static void ep_curve_set (const fp_t a, const fp_t b, const ep_t g, const bn_t r, const bn_t h, int ctmap)
void ep_curve_init (void)
void ep_curve_clean (void)
dig_t * ep_curve_get_a (void)
dig_t * ep_curve_get_b (void)
dig_t * ep_curve_get_beta (void)
void ep_curve_get_v1 (bn_t v[])
void ep_curve_get_v2 (bn_t v[])
int ep_curve_opt_a (void)
int ep_curve_opt_b (void)
void ep_curve_mul_a (fp_t c, const fp_t a)
void ep_curve_mul_b (fp_t c, const fp_t a)
int ep_curve_is_endom (void)
int ep_curve_is_super (void)
int ep_curve_is_pairf (void)
int ep_curve_is_ctmap (void)
void ep_curve_get_gen (ep_t g)
void ep_curve_get_ord (bn_t n)
void ep_curve_get_cof (bn_t h)
const ep_t * ep_curve_get_tab (void)
iso_t ep_curve_get_iso ()
void ep_curve_set_plain (const fp_t a, const fp_t b, const ep_t g, const bn_t r, const bn_t h, int ctmap)
void ep_curve_set_super (const fp_t a, const fp_t b, const ep_t g, const bn_t r, const bn_t h, int ctmap)
void ep_curve_set_endom (const fp_t a, const fp_t b, const ep_t g, const bn_t r, const bn_t h, const fp_t beta, const bn_t l, int ctmap)
int ep_curve_embed (void)
int ep_curve_frdim (void)
Detailed Description
f
Implementation of the prime elliptic curve utilities.
Definition in file relic_ep_curve.c.
Function Documentation
detect_opt()
static void detect_opt (int * opt, fp_t a) static
Detects an optimization based on the curve coefficients.
Parameters
[out] opt - the resulting optimization.
[in] a - the curve coefficient.
Definition at line 44 of file relic_ep_curve.c.
References ERR_CAUGHT, fp_bits(), fp_cmp(), fp_cmp_dig(), fp_free, fp_is_zero(), fp_neg, fp_new, fp_null, fp_prime_conv_dig(), RLC_CATCH_ANY, RLC_DIG, RLC_EQ, RLC_FINALLY, RLC_HUGE, RLC_MIN3, RLC_ONE, RLC_THROW, RLC_TINY, RLC_TRY, RLC_TWO, and RLC_ZERO.
Referenced by ep_curve_set().
ep_curve_set_map()
static void ep_curve_set_map (void) static
Computes the constants neded to evaluate the hash-to-curve map.
Parameters
[in] u - the non-square used for hashing to this curve.
[in] ctmap - true if this curve will use an isogeny for mapping.
Definition at line 82 of file relic_ep_curve.c.
References iso_st::a, iso_st::b, bn_free, bn_get_bit(), bn_new, bn_null, core_get(), _ctx_t::ep_a, _ctx_t::ep_b, ep_curve_is_ctmap(), ep_curve_is_super(), ep_curve_opt_a(), ep_curve_opt_b(), _ctx_t::ep_iso, _ctx_t::ep_map_c, _ctx_t::ep_map_u, ERR_CAUGHT, ERR_NO_VALID, fp_add, fp_add_dig(), fp_copy(), fp_hlv, fp_inv, fp_is_sqr(), fp_is_zero(), fp_mul, fp_mul_dig(), fp_neg, fp_prime_back(), fp_set_dig(), fp_sqr, fp_srt(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, RLC_TRY, and RLC_ZERO.
Referenced by ep_curve_set().
ep_curve_set()
static void ep_curve_set (const fp_t a, const fp_t b, const ep_t g, const bn_t r, const bn_t h, int ctmap) static
Configures a prime elliptic curve by its coefficients and generator.
Parameters
[in] a - the 'a' coefficient of the curve.
[in] b - the 'b' coefficient of the curve.
[in] g - the generator.
[in] r - the order of the group of points.
[in] h - the cofactor of the group order.
[in] u - the non-square used for hashing to this curve.
[in] ctmap - true if this curve will use an isogeny for mapping.
Definition at line 203 of file relic_ep_curve.c.
References bn_copy(), core_get(), detect_opt(), _ctx_t::ep_a, _ctx_t::ep_b, ep_curve_get_tab(), ep_curve_set_map(), _ctx_t::ep_g, _ctx_t::ep_h, _ctx_t::ep_is_ctmap, ep_mul_pre, ep_norm(), _ctx_t::ep_opt_a, _ctx_t::ep_opt_b, _ctx_t::ep_r, and fp_copy().
Referenced by ep_curve_set_endom(), ep_curve_set_plain(), and ep_curve_set_super().
ep_curve_init()
void ep_curve_init (void)
Initializes the prime elliptic curve arithmetic module.
Definition at line 229 of file relic_ep_curve.c.
References bn_make(), core_get(), _ctx_t::ep_g, _ctx_t::ep_h, _ctx_t::ep_pre, _ctx_t::ep_ptr, _ctx_t::ep_r, ep_set_infty(), _ctx_t::ep_v1, _ctx_t::ep_v2, RLC_EP_TABLE, and RLC_FP_DIGS.
Referenced by core_init().
ep_curve_clean()
void ep_curve_clean (void)
Finalizes the prime elliptic curve arithmetic module.
Definition at line 247 of file relic_ep_curve.c.
References bn_clean(), core_get(), _ctx_t::ep_h, _ctx_t::ep_r, _ctx_t::ep_v1, and _ctx_t::ep_v2.
Referenced by core_clean().
ep_curve_get_a()
dig_t * ep_curve_get_a (void)
Returns the a-coefficient of the currently configured prime elliptic curve.
Returns
the a-coefficient of the elliptic curve.
Definition at line 261 of file relic_ep_curve.c.
References core_get(), and _ctx_t::ep_a.
Referenced by ep2_curve_mul_a(), ep_map_swift_impl(), ep_rhs(), and pp_dbl_k1_projc().
ep_curve_get_b()
dig_t * ep_curve_get_b (void)
Returns the b-coefficient of the currently configured prime elliptic curve.
Returns
the b-coefficient of the elliptic curve.
Definition at line 265 of file relic_ep_curve.c.
References core_get(), and _ctx_t::ep_b.
Referenced by ep_rhs(), pp_dbl_k54_projc(), pp_dbl_lit_k12(), pp_dbl_lit_k16(), and pp_dbl_lit_k18().
ep_curve_get_beta()
dig_t * ep_curve_get_beta (void)
Returns the efficient endormorphism associated with the prime curve.
Definition at line 271 of file relic_ep_curve.c.
References _ctx_t::beta, and core_get().
Referenced by ep_psi().
ep_curve_get_v1()
void ep_curve_get_v1 (bn_t v[])
Returns the parameter V1 of the prime curve.
Definition at line 275 of file relic_ep_curve.c.
References bn_copy(), core_get(), and _ctx_t::ep_v1.
Referenced by ep_mul_combs_endom(), ep_mul_glv_imp(), ep_mul_reg_glv(), ep_mul_sim_endom(), and ep_mul_sim_lot_endom().
ep_curve_get_v2()
void ep_curve_get_v2 (bn_t v[])
Returns the parameter V2 of the prime curve.
Definition at line 282 of file relic_ep_curve.c.
References bn_copy(), core_get(), and _ctx_t::ep_v2.
Referenced by ep_mul_combs_endom(), ep_mul_glv_imp(), ep_mul_reg_glv(), ep_mul_sim_endom(), and ep_mul_sim_lot_endom().
ep_curve_opt_a()
int ep_curve_opt_a (void)
Returns a optimization identifier based on the a-coefficient of the curve.
Returns
the optimization identifier.
Definition at line 291 of file relic_ep_curve.c.
References core_get(), and _ctx_t::ep_opt_a.
Referenced by ep2_curve_mul_a(), ep2_map_swift(), ep4_map(), ep_curve_set_map(), ep_map_rnd(), ep_map_sswum(), ep_map_swift_impl(), ep_psi(), and ep_rhs().
ep_curve_opt_b()
int ep_curve_opt_b (void)
Returns a optimization identifier based on the b-coefficient of the curve.
Returns
the optimization identifier.
Definition at line 295 of file relic_ep_curve.c.
References core_get(), and _ctx_t::ep_opt_b.
Referenced by ep4_map(), ep_curve_set_map(), ep_map_rnd(), ep_map_sswum(), ep_map_swift_impl(), ep_rhs(), pp_dbl_k12_projc_basic(), pp_dbl_k12_projc_lazyr(), and pp_norm_k16().
ep_curve_mul_a()
void ep_curve_mul_a (fp_t c, const fp_t a)
Multiplies a field element by the a-coefficient of the curve.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
Definition at line 299 of file relic_ep_curve.c.
References core_get(), _ctx_t::ep_a, _ctx_t::ep_opt_a, fp_copy(), fp_dbl, fp_mul, fp_mul_dig(), fp_zero(), RLC_ONE, RLC_TINY, RLC_TWO, and RLC_ZERO.
ep_curve_mul_b()
void ep_curve_mul_b (fp_t c, const fp_t a)
Multiplies a field element by the b-coefficient of the curve.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
Definition at line 322 of file relic_ep_curve.c.
References core_get(), _ctx_t::ep_b, _ctx_t::ep_opt_b, fp_copy(), fp_mul, fp_mul_dig(), fp_zero(), RLC_ONE, RLC_TINY, and RLC_ZERO.
ep_curve_is_endom()
int ep_curve_is_endom (void)
Tests if the configured prime elliptic curve is a Koblitz curve.
Returns
1 if the prime elliptic curve is a Koblitz curve, 0 otherwise.
Definition at line 342 of file relic_ep_curve.c.
References core_get(), and _ctx_t::ep_is_endom.
Referenced by ep2_mul_lwnaf(), ep2_mul_lwreg(), ep2_mul_sim_gen(), ep2_mul_sim_inter(), ep3_mul_lwnaf(), ep3_mul_lwreg(), ep4_mul_lwnaf(), ep4_mul_lwreg(), ep8_mul_lwnaf(), ep8_mul_lwreg(), ep_mul_fix_combs(), ep_mul_lwnaf(), ep_mul_lwreg(), ep_mul_pre_combs(), ep_mul_sim_gen(), ep_mul_sim_inter(), and ep_mul_sim_lot().
ep_curve_is_super()
int ep_curve_is_super (void)
Tests if the configured prime elliptic curve is supersingular.
Returns
1 if the prime elliptic curve is supersingular, 0 otherwise.
Definition at line 346 of file relic_ep_curve.c.
References core_get(), and _ctx_t::ep_is_super.
Referenced by ep_curve_set_map(), and ep_map_swift().
ep_curve_is_pairf()
int ep_curve_is_pairf (void)
Tests if the configured prime elliptic curve is pairing-friendly.
Returns
0 if the prime elliptic curve is not pairing-friendly, and the family identifier otherwise.
Definition at line 350 of file relic_ep_curve.c.
References core_get(), and _ctx_t::ep_is_pairf.
Referenced by bn_rec_sac(), ep2_mul_cof(), ep2_mul_gls_imp(), ep2_mul_reg_gls(), ep2_mul_sim_endom(), ep2_mul_sim_lot(), ep3_mul_cof(), ep3_mul_gls_imp(), ep3_mul_reg_gls(), ep3_mul_sim_lot(), ep3_psi(), ep4_mul_cof(), ep4_mul_gls_imp(), ep4_mul_reg_gls(), ep4_mul_sim_lot(), ep4_psi(), ep8_mul_gls_imp(), ep8_mul_reg_gls(), ep8_mul_sim_lot(), ep_mul_cof(), ep_pck(), ep_upk(), fp12_exp_cyc_sim(), fp4_mul_frb(), g1_is_valid(), g2_is_valid(), gt_exp_gls_naf(), gt_exp_gls_sac(), gt_exp_reg_gls(), gt_exp_reg_sac(), gt_is_valid(), gt_psi(), pp_exp_k12(), pp_exp_k16(), pp_exp_k18(), pp_fin_k18_oatep(), pp_map_k24(), pp_map_k48(), pp_map_k54(), pp_map_oatep_k12(), pp_map_oatep_k16(), pp_map_oatep_k18(), pp_map_sim_k24(), pp_map_sim_k48(), pp_map_sim_oatep_k12(), pp_map_sim_oatep_k16(), and pp_map_sim_oatep_k18().
ep_curve_is_ctmap()
int ep_curve_is_ctmap (void)
Tests if the current curve should use an isogeny map for the SSWU map.
Returns
1 if the curve uses an isogeny, and 0 otherwise.
Definition at line 354 of file relic_ep_curve.c.
References core_get(), and _ctx_t::ep_is_ctmap.
Referenced by ep_curve_set_map(), ep_map_rnd(), and ep_map_sswum().
ep_curve_get_gen()
void ep_curve_get_gen (ep_t g)
Returns the generator of the group of points in the prime elliptic curve.
Parameters
[out] g - the returned generator.
Definition at line 358 of file relic_ep_curve.c.
References core_get(), and ep_copy().
Referenced by ep_mul_gen(), and ep_mul_sim_gen().
ep_curve_get_ord()
void ep_curve_get_ord (bn_t n)
Returns the order of the group of points in the prime elliptic curve.
Parameters
[out] r - the returned order.
Definition at line 362 of file relic_ep_curve.c.
References bn_copy(), and core_get().
Referenced by ep2_curve_get_ord(), ep3_curve_get_ord(), ep3_mul_sim_lot(), ep4_curve_get_ord(), ep4_mul_sim_lot(), ep8_curve_get_ord(), ep8_mul_sim_lot(), ep_mul_combs_endom(), ep_mul_combs_plain(), ep_mul_fix_basic(), ep_mul_fix_combd(), ep_mul_fix_lwnaf(), ep_mul_glv_imp(), ep_mul_monty(), ep_mul_naf_imp(), ep_mul_pre_basic(), ep_mul_pre_combd(), ep_mul_pre_combs(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_mul_sim_endom(), ep_mul_sim_gen(), ep_mul_sim_inter(), ep_mul_sim_joint(), ep_mul_sim_lot_endom(), ep_mul_sim_trick(), ep_mul_slide(), ep_rand(), fp12_exp_cyc_sim(), pp_exp_k1(), pp_exp_k2(), pp_map_sim_tatep_k1(), pp_map_sim_tatep_k12(), pp_map_sim_tatep_k16(), pp_map_sim_tatep_k18(), pp_map_sim_tatep_k2(), pp_map_sim_weilp_k1(), pp_map_sim_weilp_k12(), pp_map_sim_weilp_k16(), pp_map_sim_weilp_k18(), pp_map_sim_weilp_k2(), pp_map_tatep_k1(), pp_map_tatep_k12(), pp_map_tatep_k16(), pp_map_tatep_k18(), pp_map_tatep_k2(), pp_map_weilp_k1(), pp_map_weilp_k12(), pp_map_weilp_k16(), pp_map_weilp_k18(), and pp_map_weilp_k2().
ep_curve_get_cof()
void ep_curve_get_cof (bn_t h)
Returns the cofactor of the binary elliptic curve.
Parameters
[out] n - the returned cofactor.
Definition at line 366 of file relic_ep_curve.c.
References bn_copy(), and core_get().
Referenced by ep_mul_cof(), and g1_is_valid().
ep_curve_get_tab()
const ep_t * ep_curve_get_tab (void)
Returns the precomputation table for the generator.
Returns
the table.
Definition at line 370 of file relic_ep_curve.c.
References core_get(), and _ctx_t::ep_ptr.
Referenced by ep_curve_set(), ep_mul_gen(), and ep_mul_sim_gen().
ep_curve_get_iso()
iso_t ep_curve_get_iso (void)
Returns the isogeny map coefficients for use with the SSWU map.
Definition at line 387 of file relic_ep_curve.c.
References core_get(), and _ctx_t::ep_iso.
Referenced by ep_param_set_ctmap().
ep_curve_set_plain()
void ep_curve_set_plain (const fp_t a, const fp_t b, const ep_t g, const bn_t r, const bn_t h, int ctmap)
Configures a prime elliptic curve without endomorphisms by its coefficients and generator.
Parameters
[in] a - the a-coefficient of the curve.
[in] b - the b-coefficient of the curve.
[in] g - the generator.
[in] r - the order of the group of points.
[in] h - the cofactor of the group order.
[in] ctmap - true if this curve will use an isogeny for mapping.
Definition at line 397 of file relic_ep_curve.c.
References _ctx_t::beta, core_get(), ep_curve_set(), _ctx_t::ep_is_endom, _ctx_t::ep_is_pairf, _ctx_t::ep_is_super, fp_neg, fp_set_dig(), and fp_srt().
Referenced by ep_param_set().
ep_curve_set_super()
void ep_curve_set_super (const fp_t a, const fp_t b, const ep_t g, const bn_t r, const bn_t h, int ctmap)
Configures a supersingular prime elliptic curve by its coefficients and generator.
Parameters
[in] a - the a-coefficient of the curve.
[in] b - the b-coefficient of the curve.
[in] g - the generator.
[in] r - the order of the group of points.
[in] h - the cofactor of the group order.
[in] ctmap - true if this curve will use an isogeny for mapping.
Definition at line 421 of file relic_ep_curve.c.
References core_get(), ep_curve_set(), _ctx_t::ep_is_endom, and _ctx_t::ep_is_super.
Referenced by ep_param_set().
ep_curve_set_endom()
void ep_curve_set_endom (const fp_t a, const fp_t b, const ep_t g, const bn_t r, const bn_t h, const fp_t beta, const bn_t l, int ctmap)
Configures a prime elliptic curve with endomorphisms by its coefficients and generator.
Parameters
[in] a - the a-coefficient of the curve.
[in] b - the b-coefficient of the curve.
[in] g - the generator.
[in] r - the order of the group of points.
[in] beta - the constant associated with the endomorphism.
[in] l - the exponent corresponding to the endomorphism.
[in] h - the cofactor of the group order.
[in] ctmap - true if this curve will use an isogeny for mapping.
Definition at line 434 of file relic_ep_curve.c.
References _ctx_t::beta, bn_add(), bn_add_dig(), bn_bits(), bn_copy(), bn_dbl(), bn_div(), bn_free, bn_gcd_ext_mid(), bn_hlv(), bn_lsh(), bn_mul, bn_neg(), bn_new, bn_null, bn_sign(), bn_sub(), core_get(), ep_cmp(), ep_curve_set(), ep_free, _ctx_t::ep_is_endom, _ctx_t::ep_is_super, ep_mul_basic(), ep_new, ep_null, ep_psi(), _ctx_t::ep_v1, _ctx_t::ep_v2, ERR_CAUGHT, ERR_NO_VALID, fp_copy(), fp_is_zero(), fp_neg, fp_sub_dig(), RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_NEG, RLC_POS, RLC_THROW, and RLC_TRY.
Referenced by ep_param_set().
ep_curve_embed()
int ep_curve_embed (void)
Returns the embedding degree of the currently configured elliptic curve.
Definition at line 525 of file relic_ep_curve.c.
References core_get(), EP_AFG16, EP_B12, EP_B24, EP_B48, EP_BN, EP_FM16, EP_FM18, EP_GMT8, EP_K1, EP_K16, EP_K18, EP_SG18, EP_SG54, and EP_SS2.
Referenced by ep_curve_frdim(), fp12_exp_cyc_sim(), gt_exp(), and gt_exp_gls_naf().
ep_curve_frdim()
int ep_curve_frdim (void)
Returns the dimension of Frobenius expansions of the currently configured elliptic curve.
Definition at line 554 of file relic_ep_curve.c.
References ep_curve_embed().
Referenced by gt_exp(), and gt_exp_sec().