RELIC: src/pp/relic_pp_add_k12.c File Reference
relic_pp_add_k12.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
#include "relic_util.h"
Functions
void pp_add_k12_basic (fp12_t l, ep2_t r, const ep2_t q, const ep_t p)
void pp_add_k12_projc_basic (fp12_t l, ep2_t r, const ep2_t q, const ep_t p)
void pp_add_k12_projc_lazyr (fp12_t l, ep2_t r, const ep2_t q, const ep_t p)
void pp_add_lit_k12 (fp12_t l, ep_t r, const ep_t p, const ep2_t q)
Detailed Description
Implementation of Miller addition for curves of embedding degree 12.
Definition in file relic_pp_add_k12.c.
Function Documentation
pp_add_k12_basic()
void pp_add_k12_basic (fp12_t l, ep2_t r, const ep2_t q, const ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 44 of file relic_pp_add_k12.c.
References ep2_add_slp_basic(), ep2_copy(), ep2_curve_is_twist(), ep2_free, ep2_new, ep2_null, ERR_CAUGHT, fp2_free, fp2_mul, fp2_new, fp2_null, fp2_sub, fp_mul, fp_neg, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_add_k12_projc_basic()
void pp_add_k12_projc_basic (fp12_t l, ep2_t r, const ep2_t q, const ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 85 of file relic_pp_add_k12.c.
References ep2_curve_is_twist(), ERR_CAUGHT, fp2_add, fp2_free, fp2_mul, fp2_new, fp2_null, fp2_sqr, fp2_sub, fp_mul, fp_neg, PROJC, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_add_k12_projc_lazyr()
void pp_add_k12_projc_lazyr (fp12_t l, ep2_t r, const ep2_t q, const ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using projective coordinates and lazy reduction.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 173 of file relic_pp_add_k12.c.
References dv2_free, dv2_new, dv2_null, ep2_curve_is_twist(), ERR_CAUGHT, fp2_add, fp2_free, fp2_mul, fp2_muln_low(), fp2_new, fp2_null, fp2_rdcn_low(), fp2_sqr, fp2_sub, fp2_subc_low(), fp_mul, fp_neg, PROJC, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_add_lit_k12()
void pp_add_lit_k12 (fp12_t l, ep_t r, const ep_t p, const ep2_t q)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve twist with embedding degree 12 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] p - the second point to add.
[in] q - the affine point to evaluate the line function.
Definition at line 254 of file relic_pp_add_k12.c.
References ep2_curve_is_twist(), ERR_CAUGHT, fp2_neg(), fp_add, fp_free, fp_mul, fp_new, fp_null, fp_sqr, fp_sub, PROJC, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_mil_lit_k12().