RELIC: src/fpx/relic_fp24_sqr.c File Reference
relic_fp24_sqr.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
Functions
void fp24_sqr_basic (fp24_t c, const fp24_t a)
void fp24_sqr_cyc_basic (fp24_t c, const fp24_t a)
void fp24_sqr_pck_basic (fp24_t c, const fp24_t a)
void fp24_sqr_unr (dv24_t c, const fp24_t a)
void fp24_sqr_lazyr (fp24_t c, const fp24_t a)
void fp24_sqr_cyc_lazyr (fp24_t c, const fp24_t a)
void fp24_sqr_pck_lazyr (fp24_t c, const fp24_t a)
Detailed Description
Implementation of squaring in a 24-degree extension of a prime field.
Definition in file relic_fp24_sqr.c.
Function Documentation
fp24_sqr_basic()
void fp24_sqr_basic (fp24_t c, const fp24_t a)
Computes the square of a 24-degree extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the 24-degree extension field element to square.
Definition at line 42 of file relic_fp24_sqr.c.
References ERR_CAUGHT, fp8_add(), fp8_dbl(), fp8_free, fp8_mul, fp8_mul_art(), fp8_new, fp8_null, fp8_sqr, fp8_sub(), fp_hlv, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp24_sqr_cyc_basic()
void fp24_sqr_cyc_basic (fp24_t c, const fp24_t a)
Computes the square of a cyclotomic 24-extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 114 of file relic_fp24_sqr.c.
References ERR_CAUGHT, fp4_add(), fp4_dbl(), fp4_free, fp4_mul_art(), fp4_new, fp4_null, fp4_sqr, fp4_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp24_sqr_pck_basic()
void fp24_sqr_pck_basic (fp24_t c, const fp24_t a)
Computes the square of a compressed cyclotomic extension field element.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 203 of file relic_fp24_sqr.c.
References ERR_CAUGHT, fp4_add(), fp4_dbl(), fp4_free, fp4_mul_art(), fp4_new, fp4_null, fp4_sqr, fp4_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp24_sqr_unr()
void fp24_sqr_unr (dv24_t c, const fp24_t a)
Computes the square of a 24-degree extension field element without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the 24-degree extension field element to square.
Definition at line 277 of file relic_fp24_sqr.c.
References dv8_free, dv8_new, dv8_null, dv_copy(), ERR_CAUGHT, fp2_addc_low(), fp2_nord_low(), fp2_subc_low(), fp8_add(), fp8_free, fp8_mul_unr(), fp8_new, fp8_null, fp8_sqr_unr(), fp8_sub(), fp_hlvd_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
Referenced by fp24_sqr_lazyr().
fp24_sqr_lazyr()
void fp24_sqr_lazyr (fp24_t c, const fp24_t a)
Computes the square of a 24-degree extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the 24-degree extension field element to square.
Definition at line 378 of file relic_fp24_sqr.c.
References dv24_free, dv24_new, dv24_null, ERR_CAUGHT, fp24_sqr_unr(), fp2_rdcn_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp24_sqr_cyc_lazyr()
void fp24_sqr_cyc_lazyr (fp24_t c, const fp24_t a)
Computes the square of a cyclotomic 24-extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 399 of file relic_fp24_sqr.c.
References dv4_free, dv4_new, dv4_null, ERR_CAUGHT, fp2_addc_low(), fp2_nord_low(), fp2_rdcn_low(), fp2_subc_low(), fp4_add(), fp4_dbl(), fp4_free, fp4_mul_art(), fp4_new, fp4_null, fp4_sqr, fp4_sqr_unr(), fp4_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp24_sqr_pck_lazyr()
void fp24_sqr_pck_lazyr (fp24_t c, const fp24_t a)
Computes the square of a compressed cyclotomic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 506 of file relic_fp24_sqr.c.
References dv4_free, dv4_new, dv4_null, ERR_CAUGHT, fp2_addc_low(), fp2_nord_low(), fp2_rdcn_low(), fp2_subc_low(), fp4_add(), fp4_dbl(), fp4_free, fp4_mul_art(), fp4_new, fp4_null, fp4_sqr, fp4_sqr_unr(), fp4_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.