RELIC: src/fb/relic_fb_shift.c File Reference
relic_fb_shift.c File Reference
Binary field arithmetic
#include "relic_core.h"
#include "relic_fb.h"
#include "relic_fb_low.h"
#include "relic_util.h"
Functions
void fb_lsh (fb_t c, const fb_t a, uint_t bits)
void fb_rsh (fb_t c, const fb_t a, uint_t bits)
Detailed Description
Implementation of the binary field multiplication by the basis.
Definition in file relic_fb_shift.c.
Function Documentation
fb_lsh()
void fb_lsh (fb_t c, const fb_t a, uint_t bits)
Shifts a binary field element to the left. Computes c = a * z^bits mod f(z).
Parameters
[out] c - the result.
[in] a - the binary field element to shift.
[in] bits - the number of bits to shift.
Definition at line 41 of file relic_fb_shift.c.
References dv_lshd(), fb_copy(), fb_lsh1_low(), fb_lshb_low(), RLC_FB_DIGS, and RLC_RIP.
Referenced by fb_inv_bruch(), and fb_itr_pre_quick().
fb_rsh()
void fb_rsh (fb_t c, const fb_t a, uint_t bits)
Shifts a binary field element to the right. Computes c = a / (z^bits).
Parameters
[out] c - the result.
[in] a - the binary field element to shift.
[in] bits - the number of bits to shift.
Definition at line 66 of file relic_fb_shift.c.
References dv_rshd(), fb_copy(), fb_rsh1_low(), fb_rshb_low(), RLC_FB_DIGS, and RLC_RIP.
Referenced by fb_inv_bruch(), fb_inv_ctaia(), and find_solve().