RELIC: src/fpx/relic_fp54_sqr.c File Reference
relic_fp54_sqr.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
Functions
void fp54_sqr_basic (fp54_t c, const fp54_t a)
void fp54_sqr_cyc_basic (fp54_t c, const fp54_t a)
void fp54_sqr_pck_basic (fp54_t c, const fp54_t a)
void fp54_sqr_lazyr (fp54_t c, const fp54_t a)
void fp54_sqr_cyc_lazyr (fp54_t c, const fp54_t a)
void fp54_sqr_pck_lazyr (fp54_t c, const fp54_t a)
Detailed Description
Implementation of squaring in a 54-degree extension of a prime field.
Definition in file relic_fp54_sqr.c.
Function Documentation
fp54_sqr_basic()
void fp54_sqr_basic (fp54_t c, const fp54_t a)
Computes the square of a 54-extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the 54-extension field element to square.
Definition at line 42 of file relic_fp54_sqr.c.
References ERR_CAUGHT, fp18_add(), fp18_dbl(), fp18_free, fp18_mul, fp18_mul_art(), fp18_new, fp18_null, fp18_sqr, fp18_sub(), fp_hlv, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp54_sqr_cyc_basic()
void fp54_sqr_cyc_basic (fp54_t c, const fp54_t a)
Computes the square of a cyclotomic 54-extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 114 of file relic_fp54_sqr.c.
References ERR_CAUGHT, fp9_add(), fp9_dbl(), fp9_free, fp9_mul_art(), fp9_new, fp9_null, fp9_sqr, fp9_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp54_sqr_pck_basic()
void fp54_sqr_pck_basic (fp54_t c, const fp54_t a)
Computes the square of a compressed cyclotomic extension field element.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 203 of file relic_fp54_sqr.c.
References ERR_CAUGHT, fp9_add(), fp9_dbl(), fp9_free, fp9_mul_art(), fp9_new, fp9_null, fp9_sqr, fp9_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp54_sqr_lazyr()
void fp54_sqr_lazyr (fp54_t c, const fp54_t a)
Computes the square of a 54-extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the 54-extension field element to square.
Definition at line 277 of file relic_fp54_sqr.c.
References ERR_CAUGHT, fp18_add(), fp18_dbl(), fp18_free, fp18_mul, fp18_mul_art(), fp18_new, fp18_null, fp18_sqr, fp18_sub(), fp_hlv, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp54_sqr_cyc_lazyr()
void fp54_sqr_cyc_lazyr (fp54_t c, const fp54_t a)
Computes the square of a cyclotomic 54-extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 350 of file relic_fp54_sqr.c.
References ERR_CAUGHT, fp9_add(), fp9_dbl(), fp9_free, fp9_mul_art(), fp9_new, fp9_null, fp9_sqr, fp9_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp54_sqr_pck_lazyr()
void fp54_sqr_pck_lazyr (fp54_t c, const fp54_t a)
Computes the square of a compressed cyclotomic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 440 of file relic_fp54_sqr.c.
References dv9_free, dv9_new, dv9_null, ERR_CAUGHT, fp3_addc_low(), fp3_nord_low(), fp3_rdcn_low(), fp3_subc_low(), fp9_add(), fp9_dbl(), fp9_free, fp9_mul_art(), fp9_new, fp9_null, fp9_sqr, fp9_sqr_unr(), fp9_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.