RELIC: src/pp/relic_pp_add_k54.c File Reference
relic_pp_add_k54.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_util.h"
Functions
static void ep9_add_basic (fp9_t s, fp9_t rx, fp9_t ry, const fp9_t qx, const fp9_t qy)
void pp_add_k54_basic (fp54_t l, fp9_t rx, fp9_t ry, const fp9_t qx, const fp9_t qy, const ep_t p)
void pp_add_k54_projc (fp54_t l, fp9_t rx, fp9_t ry, fp9_t rz, const fp9_t qx, const fp9_t qy, const ep_t p)
Detailed Description
Implementation of pairing computation for curves with embedding degree 54.
Definition in file relic_pp_add_k54.c.
Function Documentation
ep9_add_basic()
static void ep9_add_basic (fp9_t s, fp9_t rx, fp9_t ry, const fp9_t qx, const fp9_t qy) static
Definition at line 40 of file relic_pp_add_k54.c.
References ERR_CAUGHT, ERR_NO_VALID, fp9_copy(), fp9_free, fp9_inv(), fp9_is_zero(), fp9_mul, fp9_new, fp9_null, fp9_sqr, fp9_sub(), fp9_zero(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_add_k54_basic().
pp_add_k54_basic()
void pp_add_k54_basic (fp54_t l, fp9_t rx, fp9_t ry, const fp9_t qx, const fp9_t qy, const ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 54 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 107 of file relic_pp_add_k54.c.
References ep9_add_basic(), ERR_CAUGHT, fp54_zero(), fp9_copy(), fp9_free, fp9_mul, fp9_new, fp9_null, fp9_sub(), fp_mul, fp_neg, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_add_k54_projc()
void pp_add_k54_projc (fp54_t l, fp9_t rx, fp9_t ry, fp9_t rz, const fp9_t qx, const fp9_t qy, const ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 54 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 153 of file relic_pp_add_k54.c.
References ERR_CAUGHT, fp9_add(), fp9_free, fp9_mul, fp9_new, fp9_null, fp9_sqr, fp9_sub(), fp_mul, fp_neg, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.