RELIC: src/rand/relic_rand_core.c File Reference
relic_rand_core.c File Reference
Pseudo-random number generators.
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include "relic_conf.h"
#include "relic_core.h"
#include "relic_label.h"
#include "relic_rand.h"
#include "relic_md.h"
#include "relic_err.h"
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
Macros
#define RLC_RAND_PATH "/dev/urandom"
#define RAND_REP 6
Functions
void rand_init (void)
int rand_check (uint8_t *buf, size_t size)
void rand_clean (void)
Detailed Description
Implementation of utilities for pseudo-random number generation.
Definition in file relic_rand_core.c.
Macro Definition Documentation
RLC_RAND_PATH
#define RLC_RAND_PATH "/dev/urandom"
The path to the char device that supplies entropy.
Definition at line 75 of file relic_rand_core.c.
Referenced by rand_init().
RAND_REP
#define RAND_REP 6
The maximum number of bytes that can be repeated in the output.
Definition at line 79 of file relic_rand_core.c.
Referenced by rand_check().
Function Documentation
rand_init()
void rand_init (void)
Initializes the pseudo-random number generator.
Definition at line 85 of file relic_rand_core.c.
References core_get(), ERR_NO_FILE, ERR_NO_READ, rand_seed(), RLC_RAND_PATH, RLC_RAND_SEED, RLC_THROW, and _ctx_t::seeded.
Referenced by core_init().
rand_check()
int rand_check (uint8_t * buf, size_t size)
Performs a basic self-test in the pseudo-random number generator output, and raises an exception in case a string of identifical bytes is found.
Parameters
[out] buf - the buffer to check.
[in] size - the number of bytes to check.
Exceptions
ERR_NO_RAND - if the pseudo-random number generator is stuck.
Definition at line 186 of file relic_rand_core.c.
References RAND_REP, RLC_ERR, and RLC_OK.
rand_clean()
void rand_clean (void)
Finishes the pseudo-random number generator.
Definition at line 203 of file relic_rand_core.c.
References core_get(), _ctx_t::rand, and _ctx_t::seeded.
Referenced by core_clean().