RELIC: include/relic_arch.h File Reference
relic_arch.h File Reference
Architecture-dependent utilities
#include "relic_types.h"
#include "relic_label.h"
Macros
#define RLC_STR(S)
#define RLC_GET(S, ID, L)
Functions
void arch_init (void)
void arch_clean (void)
ull_t arch_cycles (void)
uint_t arch_lzcnt (dig_t)
uint_t arch_tzcnt (dig_t)
Detailed Description
Interface of architecture-dependent functions.
Definition in file relic_arch.h.
Macro Definition Documentation
RLC_STR
#define RLC_STR (S)
Value:
S
Chooses a proper way to store a string in the target architecture.
Parameters
[in] S - the string to store.
Definition at line 58 of file relic_arch.h.
RLC_GET
#define RLC_GET (S, ID, L)
Value:
memcpy(S, ID, L);
Fetches a constant string to be used by the library.
Parameters
[out] S - the resulting prepared parameter.
[in] ID - the parameter represented as a string.
[in] L - the length of the string.
Definition at line 71 of file relic_arch.h.
Function Documentation
arch_init()
void arch_init (void)
Performs architecture-dependent initialization.
Definition at line 176 of file relic_arch_a64.c.
References core_get(), _ctx_t::lzcnt_ptr, and _ctx_t::tzcnt_ptr.
Referenced by core_init().
arch_clean()
void arch_clean (void)
Performs architecture-dependent finalization.
Definition at line 200 of file relic_arch_a64.c.
References core_get(), _ctx_t::lzcnt_ptr, and _ctx_t::tzcnt_ptr.
Referenced by core_clean().
arch_cycles()
ull_t arch_cycles (void)
Return the number of elapsed cycles.
Definition at line 209 of file relic_arch_a64.c.
Referenced by bench_after(), and bench_before().
arch_lzcnt()
uint_t arch_lzcnt (dig_t x)
Return the number of leading zeros in an integer.
Definition at line 237 of file relic_arch_a64.c.
References core_get(), _ctx_t::lzcnt_ptr, and WSIZE.
arch_tzcnt()
uint_t arch_tzcnt (dig_t x)
Return the number of trailing zeros in an integer.
Definition at line 241 of file relic_arch_a64.c.
References core_get(), and _ctx_t::tzcnt_ptr.