RELIC: src/ep/relic_ep_param.c File Reference
relic_ep_param.c File Reference
Elliptic curves over prime fields
#include "relic_core.h"
#include "relic_epx.h"
Macros
#define ASSIGN(CURVE, FIELD)
#define ASSIGNK(CURVE, FIELD)
#define ASSIGNM(CURVE)
#define NIST_P256_A "-3"
#define NIST_P256_B "5AC635D8AA3A93E7B3EBBD55769886BC651D06B0CC53B0F63BCE3C3E27D2604B"
#define NIST_P256_X "6B17D1F2E12C4247F8BCE6E563A440F277037D812DEB33A0F4A13945D898C296"
#define NIST_P256_Y "4FE342E2FE1A7F9B8EE7EB4A7C0F9E162BCE33576B315ECECBB6406837BF51F5"
#define NIST_P256_R "FFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551"
#define NIST_P256_H "1"
#define BSI_P256_A "7D5A0975FC2C3057EEF67530417AFFE7FB8055C126DC5C6CE94A4B44F330B5D9"
#define BSI_P256_B "26DC5C6CE94A4B44F330B5D9BBD77CBF958416295CF7E1CE6BCCDC18FF8C07B6"
#define BSI_P256_X "8BD2AEB9CB7E57CB2C4B482FFC81B7AFB9DE27E1E3BD23C23A4453BD9ACE3262"
#define BSI_P256_Y "547EF835C3DAC4FD97F8461A14611DC9C27745132DED8E545C1D54C72F046997"
#define BSI_P256_R "A9FB57DBA1EEA9BC3E660A909D838D718C397AA3B561A6F7901E0E82974856A7"
#define BSI_P256_H "1"
#define SECG_K256_A "0"
#define SECG_K256_B "7"
#define SECG_K256_X "79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798"
#define SECG_K256_Y "483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8"
#define SECG_K256_R "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141"
#define SECG_K256_H "1"
#define SM2_P256_A "FFFFFFFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000FFFFFFFFFFFFFFFC"
#define SM2_P256_B "28E9FA9E9D9F5E344D5A9E4BCF6509A7F39789F515AB8F92DDBCBD414D940E93"
#define SM2_P256_X "32C4AE2C1F1981195F9904466A39C9948FE30BBFF2660BE1715A4589334C74C7"
#define SM2_P256_Y "BC3736A2F4F6779C59BDCEE36B692153D0A9877CC62A474002DF32E52139F0A0"
#define SM2_P256_R "FFFFFFFEFFFFFFFFFFFFFFFFFFFFFFFF7203DF6B21C6052B53BBF40939D54123"
#define SM2_P256_H "1"
#define BN_P256_A "0"
#define BN_P256_B "11"
#define BN_P256_X "B64000000000FF2F2200000085FD5480B0001F44B6B88BF142BC818F95E3E6AE"
#define BN_P256_Y "4"
#define BN_P256_R "B64000000000FF2F2200000085FD547FD8001F44B6B7F4B7C2BC818F7B6BEF99"
#define BN_P256_H "1"
#define SM9_P256_A "0"
#define SM9_P256_B "5"
#define SM9_P256_X "93DE051D62BF718FF5ED0704487D01D6E1E4086909DC3280E8C4E4817C66DDDD"
#define SM9_P256_Y "21FE8DDA4F21E607631065125C395BBC1C1C00CBFA6024350C464CD70A3EA616"
#define SM9_P256_R "B640000002A3A6F1D603AB4FF58EC74449F2934B18EA8BEEE56EE19CD69ECF25"
#define SM9_P256_H "1"
Functions
static int ep_param_get_coeffs (fp_st *coeffs, const char *str)
static void ep_param_set_ctmap (const char *a_str, const char *b_str, const char *xn_str, const char *xd_str, const char *yn_str, const char *yd_str, const char *u_str)
int ep_param_get (void)
void ep_param_set (int param)
int ep_param_set_any (void)
int ep_param_set_any_plain (void)
int ep_param_set_any_endom (void)
int ep_param_set_any_super (void)
int ep_param_set_any_pairf (void)
void ep_param_print (void)
int ep_param_level (void)
Detailed Description
Implementation of the prime elliptic curve parameters.
Definition in file relic_ep_param.c.
Macro Definition Documentation
NIST_P256_A
#define NIST_P256_A "-3"
Parameters for the NIST P-256 prime elliptic curve.
Definition at line 201 of file relic_ep_param.c.
NIST_P256_B
#define NIST_P256_B "5AC635D8AA3A93E7B3EBBD55769886BC651D06B0CC53B0F63BCE3C3E27D2604B"
Parameters for the NIST P-256 prime elliptic curve.
Definition at line 202 of file relic_ep_param.c.
NIST_P256_X
#define NIST_P256_X "6B17D1F2E12C4247F8BCE6E563A440F277037D812DEB33A0F4A13945D898C296"
Parameters for the NIST P-256 prime elliptic curve.
Definition at line 203 of file relic_ep_param.c.
NIST_P256_Y
#define NIST_P256_Y "4FE342E2FE1A7F9B8EE7EB4A7C0F9E162BCE33576B315ECECBB6406837BF51F5"
Parameters for the NIST P-256 prime elliptic curve.
Definition at line 204 of file relic_ep_param.c.
NIST_P256_R
#define NIST_P256_R "FFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551"
Parameters for the NIST P-256 prime elliptic curve.
Definition at line 205 of file relic_ep_param.c.
NIST_P256_H
#define NIST_P256_H "1"
Parameters for the NIST P-256 prime elliptic curve.
Definition at line 206 of file relic_ep_param.c.
BSI_P256_A
#define BSI_P256_A "7D5A0975FC2C3057EEF67530417AFFE7FB8055C126DC5C6CE94A4B44F330B5D9"
Parameters for the Brainpool P256r1 prime elliptic curve.
Definition at line 215 of file relic_ep_param.c.
BSI_P256_B
#define BSI_P256_B "26DC5C6CE94A4B44F330B5D9BBD77CBF958416295CF7E1CE6BCCDC18FF8C07B6"
Parameters for the Brainpool P256r1 prime elliptic curve.
Definition at line 216 of file relic_ep_param.c.
BSI_P256_X
#define BSI_P256_X "8BD2AEB9CB7E57CB2C4B482FFC81B7AFB9DE27E1E3BD23C23A4453BD9ACE3262"
Parameters for the Brainpool P256r1 prime elliptic curve.
Definition at line 217 of file relic_ep_param.c.
BSI_P256_Y
#define BSI_P256_Y "547EF835C3DAC4FD97F8461A14611DC9C27745132DED8E545C1D54C72F046997"
Parameters for the Brainpool P256r1 prime elliptic curve.
Definition at line 218 of file relic_ep_param.c.
BSI_P256_R
#define BSI_P256_R "A9FB57DBA1EEA9BC3E660A909D838D718C397AA3B561A6F7901E0E82974856A7"
Parameters for the Brainpool P256r1 prime elliptic curve.
Definition at line 219 of file relic_ep_param.c.
BSI_P256_H
#define BSI_P256_H "1"
Parameters for the Brainpool P256r1 prime elliptic curve.
Definition at line 220 of file relic_ep_param.c.
SECG_K256_A
#define SECG_K256_A "0"
Parameters for the SECG K-256 prime elliptic curve.
Definition at line 229 of file relic_ep_param.c.
SECG_K256_B
#define SECG_K256_B "7"
Parameters for the SECG K-256 prime elliptic curve.
Definition at line 230 of file relic_ep_param.c.
SECG_K256_X
#define SECG_K256_X "79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798"
Parameters for the SECG K-256 prime elliptic curve.
Definition at line 231 of file relic_ep_param.c.
SECG_K256_Y
#define SECG_K256_Y "483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8"
Parameters for the SECG K-256 prime elliptic curve.
Definition at line 232 of file relic_ep_param.c.
SECG_K256_R
#define SECG_K256_R "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141"
Parameters for the SECG K-256 prime elliptic curve.
Definition at line 233 of file relic_ep_param.c.
SECG_K256_H
#define SECG_K256_H "1"
Parameters for the SECG K-256 prime elliptic curve.
Definition at line 234 of file relic_ep_param.c.
SM2_P256_A
#define SM2_P256_A "FFFFFFFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000FFFFFFFFFFFFFFFC"
Parameters for the SM2 P-256 prime elliptic curve.
Definition at line 243 of file relic_ep_param.c.
SM2_P256_B
#define SM2_P256_B "28E9FA9E9D9F5E344D5A9E4BCF6509A7F39789F515AB8F92DDBCBD414D940E93"
Parameters for the SM2 P-256 prime elliptic curve.
Definition at line 244 of file relic_ep_param.c.
SM2_P256_X
#define SM2_P256_X "32C4AE2C1F1981195F9904466A39C9948FE30BBFF2660BE1715A4589334C74C7"
Parameters for the SM2 P-256 prime elliptic curve.
Definition at line 245 of file relic_ep_param.c.
SM2_P256_Y
#define SM2_P256_Y "BC3736A2F4F6779C59BDCEE36B692153D0A9877CC62A474002DF32E52139F0A0"
Parameters for the SM2 P-256 prime elliptic curve.
Definition at line 246 of file relic_ep_param.c.
SM2_P256_R
#define SM2_P256_R "FFFFFFFEFFFFFFFFFFFFFFFFFFFFFFFF7203DF6B21C6052B53BBF40939D54123"
Parameters for the SM2 P-256 prime elliptic curve.
Definition at line 247 of file relic_ep_param.c.
SM2_P256_H
#define SM2_P256_H "1"
Parameters for the SM2 P-256 prime elliptic curve.
Definition at line 248 of file relic_ep_param.c.
BN_P256_A
#define BN_P256_A "0"
Parameters for a 256-bit pairing-friendly prime curve.
Definition at line 369 of file relic_ep_param.c.
BN_P256_B
#define BN_P256_B "11"
Parameters for a 256-bit pairing-friendly prime curve.
Definition at line 370 of file relic_ep_param.c.
BN_P256_X
#define BN_P256_X "B64000000000FF2F2200000085FD5480B0001F44B6B88BF142BC818F95E3E6AE"
Parameters for a 256-bit pairing-friendly prime curve.
Definition at line 371 of file relic_ep_param.c.
BN_P256_Y
#define BN_P256_Y "4"
Parameters for a 256-bit pairing-friendly prime curve.
Definition at line 372 of file relic_ep_param.c.
BN_P256_R
#define BN_P256_R "B64000000000FF2F2200000085FD547FD8001F44B6B7F4B7C2BC818F7B6BEF99"
Parameters for a 256-bit pairing-friendly prime curve.
Definition at line 373 of file relic_ep_param.c.
BN_P256_H
#define BN_P256_H "1"
Parameters for a 256-bit pairing-friendly prime curve.
Definition at line 374 of file relic_ep_param.c.
SM9_P256_A
#define SM9_P256_A "0"
Parameters for a 256-bit pairing-friendly prime curve standardized in China.
Definition at line 383 of file relic_ep_param.c.
SM9_P256_B
#define SM9_P256_B "5"
Parameters for a 256-bit pairing-friendly prime curve standardized in China.
Definition at line 384 of file relic_ep_param.c.
SM9_P256_X
#define SM9_P256_X "93DE051D62BF718FF5ED0704487D01D6E1E4086909DC3280E8C4E4817C66DDDD"
Parameters for a 256-bit pairing-friendly prime curve standardized in China.
Definition at line 385 of file relic_ep_param.c.
SM9_P256_Y
#define SM9_P256_Y "21FE8DDA4F21E607631065125C395BBC1C1C00CBFA6024350C464CD70A3EA616"
Parameters for a 256-bit pairing-friendly prime curve standardized in China.
Definition at line 386 of file relic_ep_param.c.
SM9_P256_R
#define SM9_P256_R "B640000002A3A6F1D603AB4FF58EC74449F2934B18EA8BEEE56EE19CD69ECF25"
Parameters for a 256-bit pairing-friendly prime curve standardized in China.
Definition at line 387 of file relic_ep_param.c.
SM9_P256_H
#define SM9_P256_H "1"
Parameters for a 256-bit pairing-friendly prime curve standardized in China.
Definition at line 388 of file relic_ep_param.c.
ASSIGN
#define ASSIGN (CURVE, FIELD)
Value:
    fp_param_set(FIELD);                                                    \
    RLC_GET(str, CURVE##_A, sizeof(CURVE##_A));                             \
    fp_read_str(a, str, strlen(str), 16);                                   \
    RLC_GET(str, CURVE##_B, sizeof(CURVE##_B));                             \
    fp_read_str(b, str, strlen(str), 16);                                   \
    RLC_GET(str, CURVE##_X, sizeof(CURVE##_X));                             \
    fp_read_str(g->x, str, strlen(str), 16);                                \
    RLC_GET(str, CURVE##_Y, sizeof(CURVE##_Y));                             \
    fp_read_str(g->y, str, strlen(str), 16);                                \
    RLC_GET(str, CURVE##_R, sizeof(CURVE##_R));                             \
    bn_read_str(r, str, strlen(str), 16);                                   \
    RLC_GET(str, CURVE##_H, sizeof(CURVE##_H));                             \
    bn_read_str(h, str, strlen(str), 16);                                   \
Assigns a set of ordinary elliptic curve parameters.
Parameters
[in] CURVE - the curve parameters to assign.
[in] FIELD - the finite field identifier.
Definition at line 793 of file relic_ep_param.c.
Referenced by ep_param_set().
ASSIGNK
#define ASSIGNK (CURVE, FIELD)
Value:
    ASSIGN(CURVE, FIELD);                                                   \
    RLC_GET(str, CURVE##_BETA, sizeof(CURVE##_BETA));                       \
    fp_read_str(beta, str, strlen(str), 16);                                \
    RLC_GET(str, CURVE##_LAMB, sizeof(CURVE##_LAMB));                       \
    bn_read_str(lamb, str, strlen(str), 16);                                \
Assigns a set of parameters for an elliptic curve with endomorphisms.
Parameters
[in] CURVE - the curve parameters to assign.
[in] FIELD - the finite field identifier.
Definition at line 814 of file relic_ep_param.c.
Referenced by ep_param_set().
ASSIGNM
#define ASSIGNM (CURVE)
Value:
    ep_param_set_ctmap(CURVE##_ISO_A, CURVE##_ISO_B, CURVE##_ISO_XN,        \
            CURVE##_ISO_XD, CURVE##_ISO_YN, CURVE##_ISO_YD, CURVE##_MAPU)   \
Assigns the isogeny map parameters for hashing with SSWU map.
Parameters
[in] CURVE - the curve parameters to assign.
Definition at line 828 of file relic_ep_param.c.
Referenced by ep_param_set().
Function Documentation
ep_param_get_coeffs()
static int ep_param_get_coeffs (fp_st * coeffs, const char * str) static
Reads a sequence of polynomial coefficients from semicolon separated string.
Parameters
[out] coeffs - the resulting coefficients.
[in] str - the string to parse.
Definition at line 846 of file relic_ep_param.c.
References ERR_NO_VALID, fp_read_str(), RLC_EP_CTMAP_MAX, and RLC_THROW.
Referenced by ep_param_set_ctmap().
ep_param_set_ctmap()
static void ep_param_set_ctmap (const char * a_str, const char * b_str, const char * xn_str, const char * xd_str, const char * yn_str, const char * yd_str, const char * u_str) inline static
Configures a constant-time hash-to-curve function based on an isogeny map.
Parameters
[in] a_str - the string representing the 'a' coefficient.
[in] b_str - the string representing the 'b' coefficient.
[in] xn_str - the string representing the x numerator coefficients.
[in] xd_str - the string representing the x denominator coefficients.
[in] yn_str - the string representing the y numerator coefficients.
[in] yd_str - the string representing the y denominator coefficients.
Definition at line 882 of file relic_ep_param.c.
References core_get(), iso_st::deg_xd, iso_st::deg_xn, iso_st::deg_yd, iso_st::deg_yn, ep_curve_get_iso(), ep_param_get_coeffs(), fp_read_str(), iso_st::xd, iso_st::xn, iso_st::yd, and iso_st::yn.
ep_param_get()
int ep_param_get (void)
Returns the parameter identifier of the currently configured prime elliptic curve.
Returns
the parameter identifier.
Definition at line 904 of file relic_ep_param.c.
References core_get(), and _ctx_t::ep_id.
Referenced by ep2_curve_set_twist(), ep3_curve_set_twist(), ep4_curve_set_twist(), ep8_curve_set_twist(), ep_param_level(), ep_param_print(), and pp_exp_k12().
ep_param_set()
void ep_param_set (int param)
Configures a prime elliptic curve by its parameter identifier.
Parameters
- the parameter identifier.
Definition at line 908 of file relic_ep_param.c.
References AFG16_510, AFG16_766, AFG16_P510, AFG16_P766, ASSIGN, ASSIGNK, ASSIGNM, B12_1150, B12_377, B12_381, B12_383, B12_446, B12_455, B12_638, B12_P1150, B12_P377, B12_P381, B12_P383, B12_P446, B12_P455, B12_P638, B24_315, B24_317, B24_509, B24_P315, B24_P317, B24_P509, B48_575, B48_P575, BASIC, BN_158, BN_254, BN_256, BN_382, BN_446, BN_638, bn_add_dig(), bn_cmp_dig(), bn_div_dig(), bn_free, bn_is_zero(), bn_mul, bn_mul_dig(), bn_mxp, bn_neg(), bn_new, bn_null, BN_P158, BN_P254, BN_P256, BN_P382, BN_P446, BN_P638, bn_set_dig(), bn_sign(), bn_sqr, bn_sub(), bn_sub_dig(), bn_zero(), BSI_256, BSI_P256, core_get(), CURVE_1174, CURVE_22103, CURVE_25519, CURVE_383187, CURVE_4417, CURVE_511187, CURVE_67254, EP_AFG16, EP_B12, EP_B24, EP_B48, EP_BN, ep_curve_set_endom(), ep_curve_set_plain(), ep_curve_set_super(), EP_FM16, EP_FM18, ep_free, EP_GMT8, _ctx_t::ep_id, _ctx_t::ep_is_pairf, EP_K1, EP_K16, EP_K18, ep_new, ep_null, EP_SG18, EP_SG54, EP_SS2, ERR_CAUGHT, ERR_NO_VALID, FM16_765, FM16_P765, FM18_768, FM18_P768, fp_free, fp_hlv, fp_is_zero(), fp_neg, fp_new, fp_null, fp_prime_get_par(), fp_set_dig(), fp_srt(), fp_sub_dig(), fp_zero(), GMT8_544, GMT8_P544, K16_330, K16_766, K16_P330, K16_P766, K18_354, K18_508, K18_638, K18_P354, K18_P508, K18_P638, K1_3072, K1_P3072, NIST_192, NIST_224, NIST_256, NIST_384, NIST_521, NIST_P192, NIST_P224, NIST_P256, NIST_P384, NIST_P521, PRIME_22103, PRIME_22605, PRIME_25109, PRIME_25519, PRIME_382105, PRIME_383187, PRIME_511187, PRIME_H2ADC, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FP_BYTES, RLC_NEG, RLC_THROW, RLC_TRY, SECG_160, SECG_160D, SECG_192, SECG_224, SECG_256, SECG_K160, SECG_K192, SECG_K224, SECG_K256, SECG_P160, SG18_638, SG18_P638, SG54_569, SG54_P569, SM2_256, SM2_P256, SM9_256, SM9_P256, SS_1536, SS_P1536, and TWEEDLEDUM.
Referenced by ep_param_set_any_endom(), ep_param_set_any_pairf(), ep_param_set_any_plain(), and ep_param_set_any_super().
ep_param_set_any()
int ep_param_set_any (void)
Configures some set of curve parameters for the current security level.
Definition at line 1428 of file relic_ep_param.c.
References ep_param_set_any_endom(), ep_param_set_any_pairf(), ep_param_set_any_plain(), RLC_ERR, and RLC_OK.
ep_param_set_any_plain()
int ep_param_set_any_plain (void)
Configures some set of ordinary curve parameters for the current security level.
Returns
RLC_OK if there is a curve at this security level, RLC_ERR otherwise.
Definition at line 1442 of file relic_ep_param.c.
References CURVE_1174, CURVE_22103, CURVE_25519, CURVE_383187, CURVE_4417, CURVE_67254, ep_param_set(), NIST_P192, NIST_P224, NIST_P256, NIST_P384, NIST_P521, RLC_ERR, RLC_OK, and SECG_P160.
Referenced by ep_param_set_any().
ep_param_set_any_endom()
int ep_param_set_any_endom (void)
Configures some set of Koblitz curve parameters for the current security level.
Returns
RLC_OK if there is a curve at this security level, RLC_ERR otherwise.
Definition at line 1478 of file relic_ep_param.c.
References AFG16_P510, AFG16_P766, B12_P1150, B12_P377, B12_P381, B12_P383, B12_P446, B12_P455, B12_P638, B24_P315, B24_P317, B24_P509, BN_P158, BN_P254, BN_P382, BN_P446, ep_param_set(), FM16_P765, FM18_P768, GMT8_P544, K16_P330, K18_P354, K18_P508, K18_P638, RLC_ERR, RLC_OK, SECG_K160, SECG_K192, SECG_K224, SECG_K256, and TWEEDLEDUM.
Referenced by ep_param_set_any().
ep_param_set_any_super()
int ep_param_set_any_super (void)
Configures some set of supersingular curve parameters for the current security level.
Returns
RLC_OK if there is a curve at this security level, RLC_ERR otherwise.
Definition at line 1552 of file relic_ep_param.c.
References ep_param_set(), RLC_ERR, RLC_OK, and SS_P1536.
ep_param_set_any_pairf()
int ep_param_set_any_pairf (void)
Configures some set of pairing-friendly curve parameters for the current security level.
Returns
RLC_OK if there is a curve at this security level, RLC_ERR otherwise.
Definition at line 1565 of file relic_ep_param.c.
References AFG16_P510, AFG16_P766, B12_P1150, B12_P377, B12_P381, B12_P383, B12_P446, B12_P455, B12_P638, B24_P315, B24_P317, B24_P509, B48_P575, BN_P158, BN_P254, BN_P256, BN_P382, BN_P446, ep2_curve_set_twist(), ep3_curve_set_twist(), ep4_curve_set_twist(), ep8_curve_set_twist(), ep_param_set(), FM16_P765, FM18_P768, GMT8_P544, K16_P330, K18_P354, K18_P508, K18_P638, K1_P3072, pc_core_calc(), RLC_EP_DTYPE, RLC_EP_MTYPE, RLC_ERR, RLC_OK, SG54_P569, and SS_P1536.
Referenced by ep_param_set_any().
ep_param_print()
void ep_param_print (void)
Prints the current configured prime elliptic curve.
Definition at line 1720 of file relic_ep_param.c.
References AFG16_P510, AFG16_P766, B12_P1150, B12_P377, B12_P381, B12_P383, B12_P446, B12_P455, B12_P638, B24_P315, B24_P317, B24_P509, B48_P575, BN_P158, BN_P254, BN_P256, BN_P382, BN_P446, BN_P638, BSI_P256, CURVE_1174, CURVE_25519, CURVE_383187, CURVE_511187, ep_param_get(), FM16_P765, FM18_P768, GMT8_P544, K16_P330, K16_P766, K18_P354, K18_P508, K18_P638, K1_P3072, NIST_P192, NIST_P224, NIST_P256, NIST_P384, NIST_P521, SECG_K160, SECG_K192, SECG_K224, SECG_K256, SECG_P160, SG18_P638, SG54_P569, SM2_P256, SM9_P256, SS_P1536, TWEEDLEDUM, and util_banner.
ep_param_level()
int ep_param_level (void)
Returns the current security level.
Definition at line 1872 of file relic_ep_param.c.
References AFG16_P510, B12_P1150, B12_P377, B12_P381, B12_P383, B12_P446, B12_P455, B12_P638, B24_P315, B24_P317, B24_P509, BN_P158, BN_P254, BN_P256, BN_P382, BN_P446, BN_P638, CURVE_25519, ep_param_get(), FM16_P765, FM18_P768, GMT8_P544, K16_P330, K16_P766, K18_P354, K18_P508, K18_P638, NIST_P192, NIST_P224, NIST_P256, NIST_P384, NIST_P521, SECG_K160, SECG_K192, SECG_K224, SECG_K256, SECG_P160, SM2_P256, SM9_P256, SS_P1536, and TWEEDLEDUM.
Referenced by ep2_map_from_field(), ep2_map_sswum(), ep2_map_swift(), ep3_map(), ep4_map(), ep8_map(), ep_map_basic(), ep_map_sswum(), ep_map_sswum_impl(), and ep_map_swift().