RELIC: src/fpx/relic_fp6_sqr.c File Reference
relic_fp6_sqr.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
Functions
void fp6_sqr_basic (fp6_t c, const fp6_t a)
void fp6_sqr_unr (dv6_t c, const fp6_t a)
void fp6_sqr_lazyr (fp6_t c, const fp6_t a)
Detailed Description
Implementation of squaring in a sextic extension of a prime field.
Definition in file relic_fp6_sqr.c.
Function Documentation
fp6_sqr_basic()
void fp6_sqr_basic (fp6_t c, const fp6_t a)
Computes the squares of a sextic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the sextic extension field element to square.
Definition at line 42 of file relic_fp6_sqr.c.
References ERR_CAUGHT, fp2_add, fp2_dbl, fp2_free, fp2_mul, fp2_mul_nor, fp2_new, fp2_null, fp2_sqr, fp2_sub, fp_hlv, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp6_sqr_unr()
void fp6_sqr_unr (dv6_t c, const fp6_t a)
Computes the square of a sextic extension field element without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the sextic extension field element to square.
Definition at line 114 of file relic_fp6_sqr.c.
References dv2_free, dv2_new, dv2_null, ERR_CAUGHT, fp2_addc_low(), fp2_addm_low(), fp2_dblm_low(), fp2_free, fp2_muln_low(), fp2_new, fp2_nord_low(), fp2_null, fp2_sqrn_low(), fp2_subc_low(), fp2_subm_low(), fp_hlvd_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp6_sqr_lazyr().
fp6_sqr_lazyr()
void fp6_sqr_lazyr (fp6_t c, const fp6_t a)
Computes the square of a sextic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the sextic extension field element to square.
Definition at line 200 of file relic_fp6_sqr.c.
References dv6_free, dv6_new, dv6_null, ERR_CAUGHT, fp2_rdcn_low(), fp6_sqr_unr(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.