RELIC: src/fpx/relic_fp8_sqr.c File Reference
relic_fp8_sqr.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
Functions
void fp8_sqr_basic (fp8_t c, const fp8_t a)
void fp8_sqr_unr (dv8_t c, const fp8_t a)
void fp8_sqr_lazyr (fp8_t c, const fp8_t a)
void fp8_sqr_cyc (fp8_t c, const fp8_t a)
Detailed Description
Implementation of squaring in an octic extension of a prime field.
Definition in file relic_fp8_sqr.c.
Function Documentation
fp8_sqr_basic()
void fp8_sqr_basic (fp8_t c, const fp8_t a)
Computes the squares of an octic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the octic extension field element to square.
Definition at line 42 of file relic_fp8_sqr.c.
References ERR_CAUGHT, fp4_add(), fp4_dbl(), fp4_free, fp4_mul, fp4_mul_art(), fp4_new, fp4_null, fp4_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp8_sqr_unr()
void fp8_sqr_unr (dv8_t c, const fp8_t a)
Computes the square of an octic extension field element without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the octic extension field element to square.
Definition at line 73 of file relic_fp8_sqr.c.
References dv4_free, dv4_new, dv4_null, dv_copy(), ERR_CAUGHT, fp2_addc_low(), fp2_nord_low(), fp2_subc_low(), fp4_add(), fp4_free, fp4_new, fp4_null, fp4_sqr_unr(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
Referenced by fp16_sqr_unr(), fp24_sqr_unr(), fp48_sqr_pck_lazyr(), and fp8_sqr_lazyr().
fp8_sqr_lazyr()
void fp8_sqr_lazyr (fp8_t c, const fp8_t a)
Computes the square of an octic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the octic extension field element to square.
Definition at line 119 of file relic_fp8_sqr.c.
References dv8_free, dv8_new, dv8_null, ERR_CAUGHT, fp2_rdcn_low(), fp8_sqr_unr(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp8_sqr_cyc()
void fp8_sqr_cyc (fp8_t c, const fp8_t a)
Computes the square of a cyclotomic octic extension field element.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 140 of file relic_fp8_sqr.c.
References ERR_CAUGHT, fp4_add(), fp4_dbl(), fp4_free, fp4_mul_art(), fp4_new, fp4_null, fp4_sqr, fp4_sub(), fp_add_dig(), fp_sub_dig(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp8_exp_cyc(), fp8_exp_dig(), and pp_exp_k8().