RELIC: src/epx/relic_ep2_mul_fix.c File Reference
relic_ep2_mul_fix.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
static void ep2_mul_fix_plain (ep2_t r, const ep2_t *table, const bn_t k)
void ep2_mul_pre_basic (ep2_t *t, const ep2_t p)
void ep2_mul_fix_basic (ep2_t r, const ep2_t *t, const bn_t k)
void ep2_mul_pre_combs (ep2_t *t, const ep2_t p)
void ep2_mul_fix_combs (ep2_t r, const ep2_t *t, const bn_t k)
void ep2_mul_pre_combd (ep2_t *t, const ep2_t p)
void ep2_mul_fix_combd (ep2_t r, const ep2_t *t, const bn_t k)
void ep2_mul_pre_lwnaf (ep2_t *t, const ep2_t p)
void ep2_mul_fix_lwnaf (ep2_t r, const ep2_t *t, const bn_t k)
Detailed Description
Implementation of fixed point multiplication on a prime elliptic curve over a quadratic extension field.
Definition in file relic_ep2_mul_fix.c.
Function Documentation
ep2_mul_fix_plain()
static void ep2_mul_fix_plain (ep2_t r, const ep2_t * table, const bn_t k) static
Multiplies a binary elliptic curve point by an integer using the w-NAF method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 49 of file relic_ep2_mul_fix.c.
References bn_is_zero(), bn_rec_naf(), bn_sign(), ep2_add, ep2_dbl, ep2_neg(), ep2_norm(), ep2_set_infty(), ep2_sub(), RLC_DEPTH, RLC_FP_BITS, and RLC_NEG.
Referenced by ep2_mul_fix_lwnaf().
ep2_mul_pre_basic()
void ep2_mul_pre_basic (ep2_t * t, const ep2_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the binary method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 91 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, ep2_copy(), ep2_curve_get_ord(), ep2_dbl, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep2_mul_fix_basic()
void ep2_mul_fix_basic (ep2_t r, const ep2_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the binary method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 114 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_new, bn_null, ep2_add, ep2_curve_get_ord(), ep2_norm(), ep2_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep2_mul_pre_combs()
void ep2_mul_pre_combs (ep2_t * t, const ep2_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the single-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 151 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, ep2_add, ep2_copy(), ep2_curve_get_ord(), ep2_dbl, ep2_norm(), ep2_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_EP_TABLE_COMBS, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep2_mul_fix_combs()
void ep2_mul_fix_combs (ep2_t r, const ep2_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the single-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 193 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_new, bn_null, ep2_add, ep2_copy(), ep2_curve_get_ord(), ep2_dbl, ep2_norm(), ep2_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep2_mul_pre_combd()
void ep2_mul_pre_combd (ep2_t * t, const ep2_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the double-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 258 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, ep2_add, ep2_copy(), ep2_curve_get_ord(), ep2_dbl, ep2_norm(), ep2_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_EP_TABLE_COMBD, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep2_mul_fix_combd()
void ep2_mul_fix_combd (ep2_t r, const ep2_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the double-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 307 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_new, bn_null, ep2_add, ep2_curve_get_ord(), ep2_dbl, ep2_norm(), ep2_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep2_mul_pre_lwnaf()
void ep2_mul_pre_lwnaf (ep2_t * t, const ep2_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the w-(T)NAF method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 372 of file relic_ep2_mul_fix.c.
References ep2_tab(), and RLC_DEPTH.
ep2_mul_fix_lwnaf()
void ep2_mul_fix_lwnaf (ep2_t r, const ep2_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the w-(T)NAF method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 376 of file relic_ep2_mul_fix.c.
References bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, ep2_curve_get_ord(), ep2_mul_fix_plain(), ep2_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.