RELIC: src/arch/relic_arch_x64.c File Reference
relic_arch_x64.c File Reference
Architecture-dependent utilities
#include <stdio.h>
#include "relic_types.h"
#include "relic_arch.h"
#include "relic_core.h"
#include "lzcnt.inc"
#include "tzcnt.inc"
Macros
#define asm __asm__ volatile
Functions
void arch_init (void)
void arch_clean (void)
uint_t arch_lzcnt (dig_t x)
uint_t arch_tzcnt (dig_t x)
Detailed Description
Implementation of AMD64-dependent routines.
Definition in file relic_arch_x64.c.
Macro Definition Documentation
asm
#define asm __asm__ volatile
Renames the inline assembly macro to a prettier name.
Definition at line 44 of file relic_arch_x64.c.
Function Documentation
arch_init()
void arch_init (void)
Performs architecture-dependent initialization.
Definition at line 50 of file relic_arch_x64.c.
References core_get(), _ctx_t::lzcnt_ptr, and _ctx_t::tzcnt_ptr.
arch_clean()
void arch_clean (void)
Performs architecture-dependent finalization.
Definition at line 60 of file relic_arch_x64.c.
References core_get(), _ctx_t::lzcnt_ptr, and _ctx_t::tzcnt_ptr.
arch_lzcnt()
uint_t arch_lzcnt (dig_t x)
Return the number of leading zeros in an integer.
Definition at line 107 of file relic_arch_x64.c.
References core_get(), _ctx_t::lzcnt_ptr, and WSIZE.
arch_tzcnt()
uint_t arch_tzcnt (dig_t x)
Return the number of trailing zeros in an integer.
Definition at line 111 of file relic_arch_x64.c.
References core_get(), and _ctx_t::tzcnt_ptr.