RELIC: src/fpx/relic_fp24_mul.c File Reference
relic_fp24_mul.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
Functions
void fp24_mul_basic (fp24_t c, const fp24_t a, const fp24_t b)
void fp24_mul_unr (dv24_t c, const fp24_t a, const fp24_t b)
void fp24_mul_lazyr (fp24_t c, const fp24_t a, const fp24_t b)
void fp24_mul_art (fp24_t c, const fp24_t a)
void fp24_mul_dxs (fp24_t c, const fp24_t a, const fp24_t b)
Detailed Description
Implementation of multiplication in a 24-degree extension of a prime field.
Definition in file relic_fp24_mul.c.
Function Documentation
fp24_mul_basic()
void fp24_mul_basic (fp24_t c, const fp24_t a, const fp24_t b)
Multiples two 24-degree extension field elements using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the 24-degree extension field element.
[in] b - the 24-degree extension field element.
Definition at line 42 of file relic_fp24_mul.c.
References ERR_CAUGHT, fp8_add(), fp8_copy(), fp8_free, fp8_mul, fp8_mul_art(), fp8_new, fp8_null, fp8_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp24_mul_unr()
void fp24_mul_unr (dv24_t c, const fp24_t a, const fp24_t b)
Multiples two 24-degree extension field elements without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the 24-degree extension field element.
[in] b - the 24-degree extension field element.
Definition at line 109 of file relic_fp24_mul.c.
References dv8_free, dv8_new, dv8_null, dv_copy(), ERR_CAUGHT, fp2_addc_low(), fp2_nord_low(), fp2_subc_low(), fp8_add(), fp8_free, fp8_mul_unr(), fp8_new, fp8_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
Referenced by fp24_mul_lazyr().
fp24_mul_lazyr()
void fp24_mul_lazyr (fp24_t c, const fp24_t a, const fp24_t b)
Multiples two 24-degree extension field elements using lazy reduction.
Parameters
[out] c - the result.
[in] a - the 24-degree extension field element.
[in] b - the 24-degree extension field element.
Definition at line 197 of file relic_fp24_mul.c.
References dv24_free, dv24_new, dv24_null, ERR_CAUGHT, fp24_mul_unr(), fp2_rdcn_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp24_mul_art()
void fp24_mul_art (fp24_t c, const fp24_t a)
Multiplies a 24-degree extension field element by the adjoined root.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to multiply.
Definition at line 220 of file relic_fp24_mul.c.
References ERR_CAUGHT, fp8_copy(), fp8_free, fp8_mul_art(), fp8_new, fp8_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp48_inv(), fp48_mul_art(), fp48_mul_basic(), fp48_mul_dxs(), fp48_mul_lazyr(), fp48_sqr_basic(), and fp48_sqr_lazyr().
fp24_mul_dxs()
void fp24_mul_dxs (fp24_t c, const fp24_t a, const fp24_t b)
Multiples a dense 24-degree extension field element by a sparse element.
Parameters
[out] c - the result.
[in] a - a 24-degree extension field element.
[in] b - a 24-degree quartic extension field element.
Definition at line 240 of file relic_fp24_mul.c.
References ERR_CAUGHT, fp8_add(), fp8_copy(), fp8_free, fp8_is_zero(), fp8_mul, fp8_mul_art(), fp8_new, fp8_null, fp8_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp48_mul_dxs(), and pp_mil_k24().