RELIC: src/eb/relic_eb_mul_fix.c File Reference
relic_eb_mul_fix.c File Reference
Elliptic curves over binary fields
#include "relic_core.h"
Functions
static void eb_mul_fix_kbltz (eb_t r, const eb_t *t, const bn_t k)
static void eb_mul_fix_plain (eb_t r, const eb_t *t, const bn_t k)
void eb_mul_pre_basic (eb_t *t, const eb_t p)
void eb_mul_fix_basic (eb_t r, const eb_t *t, const bn_t k)
void eb_mul_pre_combs (eb_t *t, const eb_t p)
void eb_mul_fix_combs (eb_t r, const eb_t *t, const bn_t k)
void eb_mul_pre_combd (eb_t *t, const eb_t p)
void eb_mul_fix_combd (eb_t r, const eb_t *t, const bn_t k)
void eb_mul_pre_lwnaf (eb_t *t, const eb_t p)
void eb_mul_fix_lwnaf (eb_t r, const eb_t *t, const bn_t k)
Detailed Description
Implementation of fixed point multiplication on binary elliptic curves.
Definition in file relic_eb_mul_fix.c.
Function Documentation
eb_mul_fix_kbltz()
static void eb_mul_fix_kbltz (eb_t r, const eb_t * t, const bn_t k) static
Multiplies a binary elliptic curve point by an integer using the w-TNAF method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] t - the precomputed table.
[in] k - the integer.
Definition at line 51 of file relic_eb_mul_fix.c.
References bn_is_zero(), bn_rec_tnaf(), bn_sign(), eb_add, eb_copy(), eb_curve_opt_a(), eb_frb(), eb_neg, eb_norm(), eb_set_infty(), eb_sub, RLC_DEPTH, RLC_FB_BITS, RLC_NEG, and RLC_ZERO.
Referenced by eb_mul_fix_lwnaf().
eb_mul_fix_plain()
static void eb_mul_fix_plain (eb_t r, const eb_t * t, const bn_t k) static
Multiplies a binary elliptic curve point by an integer using the w-NAF method.
Parameters
[out] r - the result.
[in] t - the precomputed table.
[in] k - the integer.
Definition at line 109 of file relic_eb_mul_fix.c.
References bn_is_zero(), bn_rec_naf(), bn_sign(), eb_add, eb_copy(), eb_dbl, eb_neg, eb_norm(), eb_set_infty(), eb_sub, RLC_DEPTH, RLC_FB_BITS, and RLC_NEG.
Referenced by eb_mul_fix_lwnaf().
eb_mul_pre_basic()
void eb_mul_pre_basic (eb_t * t, const eb_t p)
Builds a precomputation table for multiplying a fixed binary elliptic point using the binary method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 156 of file relic_eb_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, eb_copy(), eb_curve_get_ord(), eb_dbl, eb_norm_sim(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
eb_mul_fix_basic()
void eb_mul_fix_basic (eb_t r, const eb_t * t, const bn_t k)
Multiplies a fixed binary elliptic point using a precomputation table and the binary method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 181 of file relic_eb_mul_fix.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), eb_add, eb_neg, eb_norm(), eb_set_infty(), and RLC_NEG.
eb_mul_pre_combs()
void eb_mul_pre_combs (eb_t * t, const eb_t p)
Builds a precomputation table for multiplying a fixed binary elliptic point using the single-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 203 of file relic_eb_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, eb_add, eb_copy(), eb_curve_get_ord(), eb_dbl, eb_norm(), eb_norm_sim(), eb_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_CEIL, RLC_DEPTH, RLC_EB_TABLE_COMBS, RLC_FINALLY, RLC_THROW, and RLC_TRY.
eb_mul_fix_combs()
void eb_mul_fix_combs (eb_t r, const eb_t * t, const bn_t k)
Multiplies a fixed binary elliptic point using a precomputation table and the single-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 241 of file relic_eb_mul_fix.c.
References bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_new, bn_null, bn_sign(), eb_add, eb_copy(), eb_curve_get_ord(), eb_dbl, eb_neg, eb_norm(), eb_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_CEIL, RLC_DEPTH, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
eb_mul_pre_combd()
void eb_mul_pre_combd (eb_t * t, const eb_t p)
Builds a precomputation table for multiplying a fixed binary elliptic point using the double-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 303 of file relic_eb_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, eb_add, eb_copy(), eb_curve_get_ord(), eb_dbl, eb_norm_sim(), eb_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_CEIL, RLC_DEPTH, RLC_FINALLY, RLC_THROW, and RLC_TRY.
eb_mul_fix_combd()
void eb_mul_fix_combd (eb_t r, const eb_t * t, const bn_t k)
Multiplies a fixed binary elliptic point using a precomputation table and the double-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 347 of file relic_eb_mul_fix.c.
References bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_new, bn_null, bn_sign(), eb_add, eb_curve_get_ord(), eb_dbl, eb_neg, eb_norm(), eb_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_CEIL, RLC_DEPTH, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
eb_mul_pre_lwnaf()
void eb_mul_pre_lwnaf (eb_t * t, const eb_t p)
Builds a precomputation table for multiplying a fixed binary elliptic point using the w-(T)NAF method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 411 of file relic_eb_mul_fix.c.
References eb_tab(), and RLC_DEPTH.
eb_mul_fix_lwnaf()
void eb_mul_fix_lwnaf (eb_t r, const eb_t * t, const bn_t k)
Multiplies a fixed binary elliptic point using a precomputation table and the w-(T)NAF method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 415 of file relic_eb_mul_fix.c.
References eb_curve_is_kbltz(), eb_mul_fix_kbltz(), and eb_mul_fix_plain().