RELIC: keyInstance Struct Reference
keyInstance Struct Reference
#include <src/bc/rijndael-api-fst.h>
Data Fields
BYTE direction
int keyLen
char keyMaterial [MAX_KEY_SIZE+1]
int Nr
u32 rk [4 *(MAXNR+1)]
u32 ek [4 *(MAXNR+1)]
Detailed Description
Definition at line 74 of file rijndael-api-fst.h.
Field Documentation
direction
BYTE keyInstance::direction
Definition at line 75 of file rijndael-api-fst.h.
Referenced by blockDecrypt(), blockEncrypt(), makeKey(), makeKey2(), padDecrypt(), and padEncrypt().
keyLen
int keyInstance::keyLen
Definition at line 76 of file rijndael-api-fst.h.
Referenced by makeKey(), and makeKey2().
keyMaterial
char keyInstance::keyMaterial[MAX_KEY_SIZE+1]
Definition at line 77 of file rijndael-api-fst.h.
Referenced by makeKey(), and makeKey2().
Nr
int keyInstance::Nr
Definition at line 78 of file rijndael-api-fst.h.
Referenced by blockDecrypt(), blockEncrypt(), makeKey(), makeKey2(), padDecrypt(), and padEncrypt().
rk
u32 keyInstance::rk[4 *(MAXNR+1)]
Definition at line 79 of file rijndael-api-fst.h.
Referenced by blockDecrypt(), blockEncrypt(), makeKey(), makeKey2(), padDecrypt(), and padEncrypt().
ek
u32 keyInstance::ek[4 *(MAXNR+1)]
Definition at line 80 of file rijndael-api-fst.h.
Referenced by blockDecrypt(), blockEncrypt(), makeKey(), and makeKey2().
The documentation for this struct was generated from the following file:
src/bc/rijndael-api-fst.h