RELIC: src/ed/relic_ed_mul.c File Reference
relic_ed_mul.c File Reference
Edwards curves over prime fields.
#include "relic_core.h"
Functions
static void ed_mul_naf_imp (ed_t r, const ed_t p, const bn_t k)
static void ed_mul_reg_imp (ed_t r, const ed_t p, const bn_t k)
void ed_mul_basic (ed_t r, const ed_t p, const bn_t k)
void ed_mul_slide (ed_t r, const ed_t p, const bn_t k)
void ed_mul_monty (ed_t r, const ed_t p, const bn_t k)
void ed_mul_lwnaf (ed_t r, const ed_t p, const bn_t k)
void ed_mul_lwreg (ed_t r, const ed_t p, const bn_t k)
void ed_mul_gen (ed_t r, const bn_t k)
void ed_mul_dig (ed_t r, const ed_t p, dig_t k)
Detailed Description
Implementation of the point multiplication on Twisted Edwards elliptic curves.
Version
$Id$
Definition in file relic_ed_mul.c.
Function Documentation
ed_mul_naf_imp()
static void ed_mul_naf_imp (ed_t r, const ed_t p, const bn_t k) static
Definition at line 41 of file relic_ed_mul.c.
References bn_is_zero(), bn_rec_naf(), bn_sign(), ed_add, ed_dbl, ed_free, ed_neg, ed_new, ed_norm(), ed_null, ed_set_infty(), ed_sub, ed_tab(), ERR_CAUGHT, EXTND, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by ed_mul_lwnaf().
ed_mul_reg_imp()
static void ed_mul_reg_imp (ed_t r, const ed_t p, const bn_t k) static
Definition at line 112 of file relic_ed_mul.c.
References bn_abs(), bn_free, bn_is_even(), bn_new, bn_null, bn_rec_reg(), bn_sign(), ed_add, ed_dbl, ed_free, ed_neg, ed_new, ed_norm(), ed_null, ed_set_infty(), ed_sub, ed_tab(), ERR_CAUGHT, fp_copy_sec(), RLC_CATCH_ANY, RLC_CEIL, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by ed_mul_lwreg().
ed_mul_basic()
void ed_mul_basic (ed_t r, const ed_t p, const bn_t k)
Multiplies an Edwards elliptic point by an integer using the binary method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 203 of file relic_ed_mul.c.
References bn_bits(), bn_is_zero(), bn_rec_naf(), bn_sign(), ed_add, ed_dbl, ed_free, ed_is_infty(), ed_neg, ed_new, ed_norm(), ed_null, ed_set_infty(), ed_sub, ERR_CAUGHT, ERR_NO_BUFFER, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.
ed_mul_slide()
void ed_mul_slide (ed_t r, const ed_t p, const bn_t k)
Multiplies an Edwards elliptic point by an integer using the sliding window method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 254 of file relic_ed_mul.c.
References bn_is_zero(), bn_rec_slw(), bn_sign(), ed_add, ed_copy(), ed_dbl, ed_free, ed_is_infty(), ed_neg, ed_new, ed_norm(), ed_norm_sim(), ed_null, ed_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_THROW, RLC_TRY, RLC_WIDTH, and util_bits_dig().
ed_mul_monty()
void ed_mul_monty (ed_t r, const ed_t p, const bn_t k)
Multiplies an Edwards elliptic point by an integer using the constant-time Montgomery ladder point multiplication method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 324 of file relic_ed_mul.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), dv_swap_sec(), ed_add, ed_copy(), ed_dbl, ed_free, ed_is_infty(), ed_neg, ed_new, ed_norm(), ed_null, ed_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_NEG, RLC_THROW, and RLC_TRY.
ed_mul_lwnaf()
void ed_mul_lwnaf (ed_t r, const ed_t p, const bn_t k)
Multiplies an Edwards elliptic point by an integer using the w-NAF method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 378 of file relic_ed_mul.c.
References bn_is_zero(), ed_is_infty(), ed_mul_naf_imp(), and ed_set_infty().
ed_mul_lwreg()
void ed_mul_lwreg (ed_t r, const ed_t p, const bn_t k)
Multiplies an Edwards elliptic point by an integer using a regular method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 391 of file relic_ed_mul.c.
References bn_is_zero(), ed_is_infty(), ed_mul_reg_imp(), and ed_set_infty().
ed_mul_gen()
void ed_mul_gen (ed_t r, const bn_t k)
Multiplies the generator of an Edwards elliptic curve by an integer.
Parameters
[out] r - the result.
[in] k - the integer.
Definition at line 402 of file relic_ed_mul.c.
References bn_is_zero(), ed_curve_get_gen(), ed_curve_get_tab(), ed_free, ed_mul, ed_mul_fix, ed_new, ed_null, ed_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ed_mul_sim_gen(), and ed_rand().
ed_mul_dig()
void ed_mul_dig (ed_t r, const ed_t p, dig_t k)
Multiplies an Edwards elliptic curve point by a small positive integer.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 428 of file relic_ed_mul.c.
References bn_free, bn_new, bn_null, bn_rec_naf(), bn_set_dig(), ed_add, ed_dbl, ed_free, ed_is_infty(), ed_new, ed_norm(), ed_null, ed_set_infty(), ed_sub, ERR_CAUGHT, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_THROW, and RLC_TRY.