RELIC: src/fpx/relic_fpx_srt.c File Reference
relic_fpx_srt.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fpx_low.h"
Functions
int fp2_is_sqr (const fp2_t a)
int fp2_srt (fp2_t c, const fp2_t a)
int fp3_is_sqr (const fp3_t a)
int fp3_srt (fp3_t c, const fp3_t a)
int fp4_is_sqr (const fp4_t a)
int fp4_srt (fp4_t c, const fp4_t a)
int fp8_is_sqr (const fp8_t a)
int fp8_srt (fp8_t c, const fp8_t a)
int fp16_is_sqr (const fp16_t a)
int fp16_srt (fp16_t c, const fp16_t a)
Detailed Description
Implementation of square root in extensions defined over prime fields.
Definition in file relic_fpx_srt.c.
Function Documentation
fp2_is_sqr()
int fp2_is_sqr (const fp2_t a)
Tests if a quadratic extension field element is a quadratic residue.
Parameters
[in] a - the prime field element to test.
Returns
1 if the argument is even, 0 otherwise.
Definition at line 39 of file relic_fpx_srt.c.
References ERR_CAUGHT, fp2_frb(), fp2_free, fp2_mul, fp2_new, fp2_null, fp_is_sqr(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep2_map_basic(), ep2_map_swift(), and fp4_srt().
fp2_srt()
int fp2_srt (fp2_t c, const fp2_t a)
Extracts the square root of a quadratic extension field element. Computes c = sqrt(a). The other square root is the negation of c. The output value shall not be used in case 0 is returned.
Parameters
[out] c - the result.
[in] a - the extension field element.
Returns
- 1 if there is a square root, 0 otherwise.
Definition at line 64 of file relic_fpx_srt.c.
References bn_add_dig(), bn_free, bn_new, bn_null, bn_rsh(), bn_sub_dig(), dv_copy(), ERR_CAUGHT, ERR_NO_VALID, fp2_cmp(), fp2_copy(), fp2_copy_sec(), fp2_free, fp2_is_zero(), fp2_new, fp2_null, fp2_sqr, fp2_zero(), fp_add, fp_copy(), fp_copy_sec(), fp_dbl, fp_exp, fp_hlv, fp_inv, fp_is_sqr(), fp_is_zero(), fp_mul, fp_neg, fp_prime_get(), fp_prime_get_mod8(), fp_prime_get_qnr(), fp_set_dig(), fp_sqr, fp_srt(), fp_sub, fp_zero(), RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
Referenced by ep2_curve_set_map(), ep2_map_basic(), ep2_map_swift(), ep2_upk(), fp2_field_init(), and fp4_srt().
fp3_is_sqr()
int fp3_is_sqr (const fp3_t a)
Tests if a cubic extension field element is a quadratic residue.
Parameters
[in] a - the prime field element to test.
Returns
1 if the argument is even, 0 otherwise.
Definition at line 186 of file relic_fpx_srt.c.
References ERR_CAUGHT, fp3_frb(), fp3_free, fp3_mul, fp3_new, fp3_null, fp_is_sqr(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep3_map().
fp3_srt()
int fp3_srt (fp3_t c, const fp3_t a)
Extracts the square root of a cubic extension field element. Computes c = sqrt(a). The other square root is the negation of c. The output value shall not be used in case 0 is returned.
Parameters
[out] c - the result.
[in] a - the extension field element.
Returns
- 1 if there is a square root, 0 otherwise.
Definition at line 212 of file relic_fpx_srt.c.
References bn_add(), bn_div_dig(), bn_free, bn_new, bn_null, bn_rsh(), bn_sqr, bn_sub_dig(), dv_copy(), ERR_CAUGHT, fp3_cmp(), fp3_cmp_dig(), fp3_copy(), fp3_copy_sec(), fp3_dbl, fp3_exp(), fp3_frb(), fp3_free, fp3_is_zero(), fp3_mul, fp3_new, fp3_null, fp3_sqr, fp3_zero(), fp_free, fp_mul, fp_new, fp_null, fp_prime_get(), fp_prime_get_2ad(), fp_prime_get_mod8(), fp_prime_get_srt(), fp_sqr, fp_sub_dig(), RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
Referenced by ep3_map(), and fp3_field_init().
fp4_is_sqr()
int fp4_is_sqr (const fp4_t a)
Tests if a quartic extension field element is a quadratic residue.
Parameters
[in] a - the prime field element to test.
Returns
1 if the argument is even, 0 otherwise.
Definition at line 352 of file relic_fpx_srt.c.
References ERR_CAUGHT, fp4_frb(), fp4_free, fp4_mul, fp4_new, fp4_null, fp_is_sqr(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep4_map(), and fp8_srt().
fp4_srt()
int fp4_srt (fp4_t c, const fp4_t a)
Extracts the square root of a quartic extension field element. Computes c = sqrt(a). The other square root is the negation of c. The output value shall not be used in case 0 is returned.
Parameters
[out] c - the result.
[in] a - the extension field element.
Returns
- 1 if there is a square root, 0 otherwise.
Definition at line 380 of file relic_fpx_srt.c.
References ERR_CAUGHT, ERR_NO_VALID, fp2_add, fp2_copy(), fp2_copy_sec(), fp2_dbl, fp2_free, fp2_inv(), fp2_is_sqr(), fp2_is_zero(), fp2_mul, fp2_mul_nor, fp2_new, fp2_null, fp2_set_dig(), fp2_sqr, fp2_srt(), fp2_sub, fp2_zero(), fp4_is_zero(), fp4_zero(), fp_hlv, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep4_map(), and fp8_srt().
fp8_is_sqr()
int fp8_is_sqr (const fp8_t a)
Tests if an octic extension field element is a quadratic residue.
Parameters
[in] a - the prime field element to test.
Returns
1 if the argument is even, 0 otherwise.
Definition at line 458 of file relic_fpx_srt.c.
References ERR_CAUGHT, fp8_frb(), fp8_free, fp8_mul, fp8_new, fp8_null, fp_is_sqr(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep8_map(), and fp16_srt().
fp8_srt()
int fp8_srt (fp8_t c, const fp8_t a)
Extracts the square root of an octic extension field element. Computes c = sqrt(a). The other square root is the negation of c. The output value shall not be used in case 0 is returned.
Parameters
[out] c - the result.
[in] a - the extension field element.
Returns
- 1 if there is a square root, 0 otherwise.
Definition at line 486 of file relic_fpx_srt.c.
References ERR_CAUGHT, ERR_NO_VALID, fp4_add(), fp4_copy(), fp4_copy_sec(), fp4_dbl(), fp4_free, fp4_inv(), fp4_is_sqr(), fp4_is_zero(), fp4_mul, fp4_mul_art(), fp4_new, fp4_null, fp4_set_dig(), fp4_sqr, fp4_srt(), fp4_sub(), fp4_zero(), fp8_is_zero(), fp8_zero(), fp_hlv, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep8_map(), and fp16_srt().
fp16_is_sqr()
int fp16_is_sqr (const fp16_t a)
Tests if an sextadecic extension field element is a quadratic residue.
Parameters
[in] a - the prime field element to test.
Returns
1 if the argument is even, 0 otherwise.
Definition at line 568 of file relic_fpx_srt.c.
References ERR_CAUGHT, fp16_frb(), fp16_free, fp16_mul, fp16_new, fp16_null, fp_is_sqr(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp16_srt()
int fp16_srt (fp16_t c, const fp16_t a)
Extracts the square root of an sextadecic extension field element. Computes c = sqrt(a). The other square root is the negation of c. The output value shall not be used in case 0 is returned.
Parameters
[out] c - the result.
[in] a - the extension field element.
Returns
- 1 if there is a square root, 0 otherwise.
Definition at line 596 of file relic_fpx_srt.c.
References ERR_CAUGHT, ERR_NO_VALID, fp16_is_zero(), fp16_zero(), fp8_add(), fp8_copy(), fp8_dbl(), fp8_free, fp8_inv(), fp8_is_sqr(), fp8_is_zero(), fp8_mul, fp8_mul_art(), fp8_new, fp8_null, fp8_set_dig(), fp8_sqr, fp8_srt(), fp8_sub(), fp8_zero(), fp_copy_sec(), fp_hlv, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.