RELIC: src/fp/relic_fp_srt.c File Reference
relic_fp_srt.c File Reference
Multiple precision integer arithmetic
#include "relic_core.h"
Functions
int fp_is_sqr (const fp_t a)
int fp_srt (fp_t c, const fp_t a)
Detailed Description
Implementation of the square root function.
Definition in file relic_fp_srt.c.
Function Documentation
fp_is_sqr()
int fp_is_sqr (const fp_t a)
Tests if a prime field element is a quadratic residue.
Parameters
[in] a - the prime field element to test.
Returns
1 if the argument is even, 0 otherwise.
Definition at line 38 of file relic_fp_srt.c.
References fp_is_zero(), and fp_smb.
Referenced by ep_curve_set_map(), ep_map_swift_impl(), fp16_is_sqr(), fp2_is_sqr(), fp2_srt(), fp3_is_sqr(), fp4_is_sqr(), fp8_is_sqr(), fp_prime_set(), and fp_srt().
fp_srt()
int fp_srt (fp_t c, const fp_t a)
Extracts the square root of a prime field element. Computes c = sqrt(a). The other square root is the negation of c.
Parameters
[out] c - the result.
[in] a - the prime field element.
Returns
- 1 if there is a square root, 0 otherwise.
Definition at line 46 of file relic_fp_srt.c.
References bn_add_dig(), bn_free, bn_new, bn_null, bn_rsh(), dv_copy(), ERR_CAUGHT, fp_cmp(), fp_cmp_dig(), fp_copy(), fp_copy_sec(), fp_exp, fp_free, fp_is_even(), fp_is_sqr(), fp_is_zero(), fp_mul, fp_neg, fp_new, fp_null, fp_prime_get(), fp_prime_get_2ad(), fp_prime_get_mod8(), fp_prime_get_srt(), fp_sqr, fp_zero(), RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
Referenced by ed_param_set(), ed_upk(), ep_curve_set_map(), ep_curve_set_plain(), ep_map_basic_impl(), ep_map_swift_impl(), ep_param_set(), ep_upk(), fp2_srt(), and fp2_upk().