RELIC: src/fpx/relic_fp18_sqr.c File Reference
relic_fp18_sqr.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
Functions
void fp18_sqr_basic (fp18_t c, const fp18_t a)
void fp18_sqr_cyc_basic (fp18_t c, const fp18_t a)
void fp18_sqr_pck_basic (fp18_t c, const fp18_t a)
void fp18_sqr_unr (dv18_t c, const fp18_t a)
void fp18_sqr_lazyr (fp18_t c, const fp18_t a)
void fp18_sqr_cyc_lazyr (fp18_t c, const fp18_t a)
void fp18_sqr_pck_lazyr (fp18_t c, const fp18_t a)
Detailed Description
Implementation of squaring in a octodecic extension of a prime field.
Definition in file relic_fp18_sqr.c.
Function Documentation
fp18_sqr_basic()
void fp18_sqr_basic (fp18_t c, const fp18_t a)
Computes the square of an octdecic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element to square.
Definition at line 42 of file relic_fp18_sqr.c.
References ERR_CAUGHT, fp9_add(), fp9_dbl(), fp9_free, fp9_mul, fp9_mul_art(), fp9_new, fp9_null, fp9_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp18_sqr_cyc_basic()
void fp18_sqr_cyc_basic (fp18_t c, const fp18_t a)
Computes the square of a cyclotomic dodecic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 69 of file relic_fp18_sqr.c.
References ERR_CAUGHT, fp3_add, fp3_dbl, fp3_free, fp3_mul_nor(), fp3_new, fp3_null, fp3_sqr, fp3_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp18_sqr_pck_basic()
void fp18_sqr_pck_basic (fp18_t c, const fp18_t a)
Computes the square of a compressed cyclotomic extension field element.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 163 of file relic_fp18_sqr.c.
References ERR_CAUGHT, fp3_add, fp3_dbl, fp3_free, fp3_mul_nor(), fp3_new, fp3_null, fp3_sqr, fp3_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp18_sqr_unr()
void fp18_sqr_unr (dv18_t c, const fp18_t a)
Computes the square of an octdecic extension field element without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element to square.
Definition at line 237 of file relic_fp18_sqr.c.
References dv9_free, dv9_new, dv9_null, dv_copy(), ERR_CAUGHT, fp3_addc_low(), fp3_nord_low(), fp3_subc_low(), fp9_add(), fp9_free, fp9_new, fp9_null, fp9_sqr_unr(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
Referenced by fp18_sqr_lazyr().
fp18_sqr_lazyr()
void fp18_sqr_lazyr (fp18_t c, const fp18_t a)
Computes the square of an octdecic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element to square.
Definition at line 290 of file relic_fp18_sqr.c.
References dv18_free, dv18_new, dv18_null, ERR_CAUGHT, fp18_sqr_unr(), fp3_rdcn_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp18_sqr_cyc_lazyr()
void fp18_sqr_cyc_lazyr (fp18_t c, const fp18_t a)
Computes the square of a cyclotomic dodecic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 309 of file relic_fp18_sqr.c.
References dv3_free, dv3_new, dv3_null, ERR_CAUGHT, fp3_addc_low(), fp3_addm_low(), fp3_dblm_low(), fp3_free, fp3_mul_nor(), fp3_new, fp3_nord_low(), fp3_null, fp3_rdcn_low(), fp3_sqrm_low(), fp3_sqrn_low(), fp3_subc_low(), fp3_subm_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp18_sqr_pck_lazyr()
void fp18_sqr_pck_lazyr (fp18_t c, const fp18_t a)
Computes the square of a compressed cyclotomic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 405 of file relic_fp18_sqr.c.
References dv3_free, dv3_new, dv3_null, ERR_CAUGHT, fp3_addc_low(), fp3_addm_low(), fp3_dblm_low(), fp3_free, fp3_mul_nor(), fp3_new, fp3_nord_low(), fp3_null, fp3_rdcn_low(), fp3_sqrm_low(), fp3_sqrn_low(), fp3_subc_low(), fp3_subm_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.