RELIC: include/relic_fbx.h File Reference
relic_fbx.h File Reference
Binary field extensions.
#include "relic_fb.h"
#include "relic_types.h"
Macros
#define fb2_null(A)
#define fb2_new(A)
#define fb2_free(A)
#define fb2_copy(C, A)
#define fb2_neg(C, A)
#define fb2_zero(A)
#define fb2_is_zero(A)
#define fb2_rand(A)
#define fb2_print(A)
#define fb2_cmp(A, B)
#define fb2_add(C, A, B)
Typedefs
typedef fb_t fb2_t[2]
Functions
void fb2_mul (fb2_t c, const fb2_t a, const fb2_t b)
void fb2_mul_nor (fb2_t c, const fb2_t a)
void fb2_sqr (fb2_t c, const fb2_t a)
void fb2_slv (fb2_t c, const fb2_t a)
void fb2_inv (fb2_t c, const fb2_t a)
Detailed Description
Interface of the module for extension field arithmetic over binary fields.
Definition in file relic_fbx.h.
Macro Definition Documentation
fb2_null
#define fb2_null (A)
Value:
        fb_null(A[0]); fb_null(A[1]);                                       \
Initializes a quadratic extension binary field with a null value.
Parameters
[out] A - the quadratic extension element to initialize.
Definition at line 63 of file relic_fbx.h.
fb2_new
#define fb2_new (A)
Value:
        fb_new(A[0]); fb_new(A[1]);                                         \
Calls a function to allocate a quadratic extension binary field element.
Parameters
[out] A - the new quadratic extension field element.
Definition at line 71 of file relic_fbx.h.
fb2_free
#define fb2_free (A)
Value:
        fb_free(A[0]); fb_free(A[1]);                                       \
Calls a function to free a quadratic extension binary field element.
Parameters
[out] A - the quadratic extension field element to free.
Definition at line 79 of file relic_fbx.h.
fb2_copy
#define fb2_copy (C, A)
Value:
        fb_copy(C[0], A[0]); fb_copy(C[1], A[1]);                           \
Copies the second argument to the first argument.
Parameters
[out] C - the result.
[in] A - the quadratic extension field element to copy.
Definition at line 88 of file relic_fbx.h.
fb2_neg
#define fb2_neg (C, A)
Value:
        fb_neg(C[0], A[0]); fb_neg(C[1], A[1]);                             \
Negates a quadratic extension field element.
f
Parameters
[out] C - the result.
[out] A - the quadratic extension field element to negate.
Definition at line 97 of file relic_fbx.h.
fb2_zero
#define fb2_zero (A)
Value:
        fb_zero(A[0]); fb_zero(A[1]);                                       \
Assigns zero to a quadratic extension field element.
Parameters
[out] A - the quadratic extension field element to zero.
Definition at line 105 of file relic_fbx.h.
fb2_is_zero
#define fb2_is_zero (A)
Value:
        (fb_is_zero(A[0]) && fb_is_zero(A[1]))                              \
Tests if a quadratic extension field element is zero or not.
Parameters
[in] A - the quadratic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 114 of file relic_fbx.h.
fb2_rand
#define fb2_rand (A)
Value:
        fb_rand(A[0]); fb_rand(A[1]);                                       \
Assigns a random value to a quadratic extension field element.
Parameters
[out] A - the quadratic extension field element to assign.
Definition at line 122 of file relic_fbx.h.
fb2_print
#define fb2_print (A)
Value:
        fb_print(A[0]); fb_print(A[1]);                                     \
Prints a quadratic extension field element to standard output.
Parameters
[in] A - the quadratic extension field element to print.
Definition at line 130 of file relic_fbx.h.
fb2_cmp
#define fb2_cmp (A, B)
Value:
        ((fb_cmp(A[0], B[0]) == RLC_EQ) && (fb_cmp(A[1], B[1]) == RLC_EQ)   \
        ? RLC_EQ : RLC_NE)                                                  \
Returns the result of a comparison between two quadratic extension field elements
Parameters
[in] A - the first quadratic extension field element.
[in] B - the second quadratic extension field element.
Returns
RLC_NE if a != b, RLC_EQ if a == b.
Definition at line 141 of file relic_fbx.h.
fb2_add
#define fb2_add (C, A, B)
Value:
        fb_add(C[0], A[0], B[0]); fb_add(C[1], A[1], B[1]);                 \
Adds two quadratic extension field elements. Computes c = a + b.
Parameters
[out] C - the result.
[in] A - the first quadratic extension field element.
[in] B - the second quadratic extension field element.
Definition at line 152 of file relic_fbx.h.
Typedef Documentation
fb2_t
typedef fb_t fb2_t[2]
Represents a quadratic extension binary field element.
This extension field is constructed with the basis {1, s}, where s is a quadratic non-residue in the binary field.
Definition at line 52 of file relic_fbx.h.
Function Documentation
fb2_mul()
void fb2_mul (fb2_t c, const fb2_t a, const fb2_t b)
Multiples two quadratic extension field elements. Computes c = a * b.
Parameters
[out] c - the result.
[in] a - the quadratic extension binary field element.
[in] b - the quadratic extension binary field element.
Definition at line 40 of file relic_fb2_mul.c.
References ERR_CAUGHT, fb_add(), fb_free, fb_mul, fb_new, fb_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fb2_mul_nor()
void fb2_mul_nor (fb2_t c, const fb2_t a)
Multiples a quadratic extension field element by a quadratic non-residue. Computes c = a * s.
Parameters
[out] c - the result.
[in] a - the quadratic extension binary field element.
[in] b - the quadratic extension binary field element.
Definition at line 70 of file relic_fb2_mul.c.
References ERR_CAUGHT, fb_add(), fb_copy(), fb_free, fb_new, fb_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fb2_sqr()
void fb2_sqr (fb2_t c, const fb2_t a)
Computes the square of a quadratic extension field element. Computes c = a * a.
Parameters
[out] c - the result.
[in] a - the binary field element to square.
Definition at line 39 of file relic_fb2_sqr.c.
References fb_add(), and fb_sqr.
fb2_slv()
void fb2_slv (fb2_t c, const fb2_t a)
Solves a quadratic equation for c, Tr(a) = 0. Computes c such that c^2 + c = a.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element.
Definition at line 39 of file relic_fb2_slv.c.
References fb_add(), fb_add_dig(), fb_slv, and fb_trc.
fb2_inv()
void fb2_inv (fb2_t c, const fb2_t a)
Inverts a quadratic extension field element. Computes c = a^{-1}.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to invert.
Definition at line 39 of file relic_fb2_inv.c.
References ERR_CAUGHT, fb_add(), fb_free, fb_inv, fb_mul, fb_new, fb_null, fb_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.