RELIC: src/epx/relic_ep2_neg.c File Reference
relic_ep2_neg.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
void ep2_neg (ep2_t r, const ep2_t p)
Detailed Description
Implementation of point negation on elliptic prime curves over a quadratic extension field.
Definition in file relic_ep2_neg.c.
Function Documentation
ep2_neg()
void ep2_neg (ep2_t r, const ep2_t p)
Negates a point represented in affine coordinates in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[out] p - the point to negate.
Definition at line 39 of file relic_ep2_neg.c.
References ep2_is_infty(), ep2_set_infty(), fp2_copy(), and fp2_neg().
Referenced by ep2_mul_basic(), ep2_mul_fix_plain(), ep2_mul_gls_imp(), ep2_mul_naf_imp(), ep2_mul_reg_gls(), ep2_mul_reg_imp(), ep2_mul_sim_endom(), ep2_mul_sim_joint(), ep2_mul_sim_lot(), ep2_mul_slide(), ep2_sub(), pp_fin_k12_oatep(), pp_map_oatep_k12(), pp_map_oatep_k8(), pp_map_sim_oatep_k12(), pp_map_sim_oatep_k8(), pp_mil_k12(), pp_mil_k8(), and pp_mil_lit_k12().