RELIC: src/relic_bench.c File Reference
relic_bench.c File Reference
Core functions
#include <stdio.h>
#include <string.h>
#include "relic_core.h"
#include "relic_conf.h"
Macros
#define CLOCK NULL
Functions
void bench_init (void)
void bench_reset (void)
void bench_before (void)
void bench_after (void)
void bench_compute (int benches)
void bench_print (void)
ull_t bench_total (void)
void bench_clean (void)
Detailed Description
Implementation of useful benchmark routines.
Definition in file relic_bench.c.
Macro Definition Documentation
CLOCK
#define CLOCK NULL
Shared parameter for these timer.
Definition at line 74 of file relic_bench.c.
Referenced by bench_after(), and bench_before().
Function Documentation
bench_init()
void bench_init (void)
Initializes the benchmarking module.
Definition at line 131 of file relic_bench.c.
References core_get(), ERR_NO_FILE, and RLC_THROW.
Referenced by core_init().
bench_reset()
void bench_reset (void)
Resets the benchmark data.
Parameters
[in] label - the benchmark label.
Definition at line 155 of file relic_bench.c.
References core_get(), and _ctx_t::total.
bench_before()
void bench_before (void)
Measures the time before a benchmark is executed.
Definition at line 161 of file relic_bench.c.
References arch_cycles(), _ctx_t::before, CLOCK, and core_get().
bench_after()
void bench_after (void)
Measures the time after a benchmark was started and adds it to the total.
Definition at line 175 of file relic_bench.c.
References _ctx_t::after, arch_cycles(), _ctx_t::before, CLOCK, core_get(), and _ctx_t::total.
bench_compute()
void bench_compute (int benches)
Computes the mean elapsed time between the start and the end of a benchmark.
Parameters
benches - the number of executed benchmarks.
Definition at line 206 of file relic_bench.c.
References core_get(), and _ctx_t::total.
bench_print()
void bench_print (void)
Prints the last benchmark.
Definition at line 219 of file relic_bench.c.
References core_get(), _ctx_t::total, and util_print.
bench_total()
ull_t bench_total (void)
Returns the result of the last benchmark.
Returns
the last benchmark.
Definition at line 236 of file relic_bench.c.
References core_get(), and _ctx_t::total.
bench_clean()
void bench_clean (void)
Finalizes the benchmarking module.
Definition at line 240 of file relic_bench.c.
References core_get().
Referenced by core_clean().