RELIC: src/relic_core.c File Reference
relic_core.c File Reference
Core functions
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "relic_core.h"
#include "relic_bench.h"
#include "relic_multi.h"
#include "relic_rand.h"
#include "relic_types.h"
#include "relic_err.h"
#include "relic_arch.h"
#include "relic_fp.h"
#include "relic_fb.h"
#include "relic_ep.h"
#include "relic_eb.h"
#include "relic_cp.h"
#include "relic_pp.h"
Macros
#define MSG_NO_MEMORY "not enough memory"
#define MSG_NO_PRECI "insufficient precision"
#define MSG_NO_FILE "file not found"
#define MSG_NO_READ "can't read bytes from file"
#define MSG_NO_VALID "invalid value passed as input"
#define MSG_NO_BUFFER "insufficient buffer capacity"
#define MSG_NO_FIELD "no finite field supported at this security level"
#define MSG_NO_CURVE "no curve supported at this security level"
#define MSG_NO_CONFIG "invalid library configuration"
#define MSG_NO_RAND "faulty pseudo-random number generator"
Functions
int core_init (void)
int core_clean (void)
ctx_t * core_get (void)
void core_set (ctx_t *ctx)
Variables
static ctx_t first_ctx
static ctx_t * core_ctx = NULL
Detailed Description
Implementation of the library basic functions.
Definition in file relic_core.c.
Macro Definition Documentation
MSG_NO_MEMORY
#define MSG_NO_MEMORY "not enough memory"
Error message respective to ERR_NO_MEMORY.
Definition at line 55 of file relic_core.c.
Referenced by core_init().
MSG_NO_PRECI
#define MSG_NO_PRECI "insufficient precision"
Error message respective to ERR_PRECISION.
Definition at line 57 of file relic_core.c.
Referenced by core_init().
MSG_NO_FILE
#define MSG_NO_FILE "file not found"
Error message respective to ERR_NO FILE.
Definition at line 59 of file relic_core.c.
Referenced by core_init().
MSG_NO_READ
#define MSG_NO_READ "can't read bytes from file"
Error message respective to ERR_NO_READ.
Definition at line 61 of file relic_core.c.
Referenced by core_init().
MSG_NO_VALID
#define MSG_NO_VALID "invalid value passed as input"
Error message respective to ERR_NO_VALID.
Definition at line 63 of file relic_core.c.
Referenced by core_init().
MSG_NO_BUFFER
#define MSG_NO_BUFFER "insufficient buffer capacity"
Error message respective to ERR_NO_BUFFER.
Definition at line 65 of file relic_core.c.
Referenced by core_init().
MSG_NO_FIELD
#define MSG_NO_FIELD "no finite field supported at this security level"
Error message respective to ERR_NO_FIELD.
Definition at line 67 of file relic_core.c.
Referenced by core_init().
MSG_NO_CURVE
#define MSG_NO_CURVE "no curve supported at this security level"
Error message respective to ERR_NO_CURVE.
Definition at line 69 of file relic_core.c.
Referenced by core_init().
MSG_NO_CONFIG
#define MSG_NO_CONFIG "invalid library configuration"
Error message respective to ERR_NO_CONFIG.
Definition at line 71 of file relic_core.c.
Referenced by core_init().
MSG_NO_RAND
#define MSG_NO_RAND "faulty pseudo-random number generator"
Error message respective to ERR_NO_CURVE.
Definition at line 73 of file relic_core.c.
Referenced by core_init().
Function Documentation
core_init()
int core_init (void)
Initializes the library.
Returns
RLC_OK if no error occurs, RLC_ERR otherwise.
Definition at line 102 of file relic_core.c.
References arch_init(), bench_init(), _ctx_t::code, core_ctx, eb_curve_init(), ed_curve_init(), ep_curve_init(), ERR_NO_BUFFER, ERR_NO_CONFIG, ERR_NO_CURVE, ERR_NO_FIELD, ERR_NO_FILE, ERR_NO_MEMORY, ERR_NO_PRECI, ERR_NO_RAND, ERR_NO_READ, ERR_NO_VALID, fb_poly_init(), first_ctx, fp_prime_init(), _ctx_t::last, MSG_NO_BUFFER, MSG_NO_CONFIG, MSG_NO_CURVE, MSG_NO_FIELD, MSG_NO_FILE, MSG_NO_MEMORY, MSG_NO_PRECI, MSG_NO_RAND, MSG_NO_READ, MSG_NO_VALID, pc_core_init(), pp_map_init(), rand_init(), _ctx_t::reason, RLC_CATCH_ANY, RLC_ERR, RLC_OK, and RLC_TRY.
core_clean()
int core_clean (void)
Finalizes the library with the current error condition.
Returns
RLC_OK if no error has occurred, RLC_ERR otherwise.
Definition at line 159 of file relic_core.c.
References arch_clean(), bench_clean(), _ctx_t::code, core_ctx, eb_curve_clean(), ed_curve_clean(), ep_curve_clean(), fb_poly_clean(), fp_prime_clean(), pc_core_clean(), pp_map_clean(), rand_clean(), and RLC_OK.
core_get()
ctx_t * core_get (void)
Returns a pointer to the current library context.
Returns
a pointer to the library context.
Definition at line 197 of file relic_core.c.
References core_ctx.
Referenced by arch_clean(), arch_init(), arch_lzcnt(), arch_tzcnt(), bench_after(), bench_before(), bench_clean(), bench_compute(), bench_init(), bench_print(), bench_reset(), bench_total(), eb_curve_clean(), eb_curve_get_a(), eb_curve_get_b(), eb_curve_get_cof(), eb_curve_get_gen(), eb_curve_get_ord(), eb_curve_get_tab(), eb_curve_init(), eb_curve_is_kbltz(), eb_curve_opt_a(), eb_curve_opt_b(), eb_curve_set(), eb_param_get(), eb_param_level(), eb_param_print(), eb_param_set(), ed_add_basic(), ed_add_extnd(), ed_add_projc(), ed_curve_clean(), ed_curve_get_cof(), ed_curve_get_gen(), ed_curve_get_ord(), ed_curve_get_tab(), ed_curve_init(), ed_dbl_basic(), ed_dbl_extnd(), ed_dbl_projc(), ed_map_ell2_5mod8(), ed_on_curve(), ed_param_get(), ed_param_set(), ed_rhs(), ed_upk(), ep2_curve_clean(), ep2_curve_get_a(), ep2_curve_get_b(), ep2_curve_get_cof(), ep2_curve_get_gen(), ep2_curve_get_iso(), ep2_curve_get_ord(), ep2_curve_get_tab(), ep2_curve_init(), ep2_curve_is_ctmap(), ep2_curve_is_twist(), ep2_curve_mul_a(), ep2_curve_mul_b(), ep2_curve_opt_a(), ep2_curve_opt_b(), ep2_curve_set(), ep2_curve_set_map(), ep2_curve_set_twist(), ep2_frb(), ep2_map_swift(), ep3_curve_clean(), ep3_curve_get_a(), ep3_curve_get_b(), ep3_curve_get_cof(), ep3_curve_get_gen(), ep3_curve_get_ord(), ep3_curve_get_tab(), ep3_curve_init(), ep3_curve_is_twist(), ep3_curve_mul_a(), ep3_curve_mul_b(), ep3_curve_opt_a(), ep3_curve_opt_b(), ep3_curve_set(), ep3_curve_set_twist(), ep3_frb(), ep3_map(), ep4_curve_clean(), ep4_curve_get_a(), ep4_curve_get_b(), ep4_curve_get_cof(), ep4_curve_get_gen(), ep4_curve_get_ord(), ep4_curve_get_tab(), ep4_curve_init(), ep4_curve_is_twist(), ep4_curve_mul_a(), ep4_curve_mul_b(), ep4_curve_opt_a(), ep4_curve_opt_b(), ep4_curve_set(), ep4_curve_set_twist(), ep4_map(), ep8_curve_clean(), ep8_curve_get_a(), ep8_curve_get_b(), ep8_curve_get_cof(), ep8_curve_get_gen(), ep8_curve_get_ord(), ep8_curve_get_tab(), ep8_curve_init(), ep8_curve_is_twist(), ep8_curve_mul_a(), ep8_curve_mul_b(), ep8_curve_opt_a(), ep8_curve_opt_b(), ep8_curve_set(), ep8_curve_set_twist(), ep8_map(), ep_curve_clean(), ep_curve_embed(), ep_curve_get_a(), ep_curve_get_b(), ep_curve_get_beta(), ep_curve_get_cof(), ep_curve_get_gen(), ep_curve_get_iso(), ep_curve_get_ord(), ep_curve_get_tab(), ep_curve_get_v1(), ep_curve_get_v2(), ep_curve_init(), ep_curve_is_ctmap(), ep_curve_is_endom(), ep_curve_is_pairf(), ep_curve_is_super(), ep_curve_mul_a(), ep_curve_mul_b(), ep_curve_opt_a(), ep_curve_opt_b(), ep_curve_set(), ep_curve_set_endom(), ep_curve_set_map(), ep_curve_set_plain(), ep_curve_set_super(), ep_map_swift(), ep_map_swift_impl(), ep_param_get(), ep_param_set(), ep_param_set_ctmap(), err_full_msg(), err_get_code(), err_get_msg(), err_simple_msg(), fb_param_get(), fb_param_set(), fb_poly_add(), fb_poly_get(), fb_poly_get_chain(), fb_poly_get_rdc(), fb_poly_get_slv(), fb_poly_get_srz(), fb_poly_get_trc(), fb_poly_init(), fb_poly_set(), fb_poly_set_dense(), fb_poly_set_penta(), fb_poly_set_trino(), fb_poly_tab_sqr(), fb_poly_tab_srz(), find_chain(), find_solve(), find_srz(), find_trace(), fp2_field_get_qnr(), fp2_field_init(), fp2_mul_frb(), fp3_field_get_cnr(), fp3_field_init(), fp3_mul_frb(), fp4_field_init(), fp4_mul_frb(), fp8_field_init(), fp8_mul_frb(), fp_add_dig(), fp_inv_jmpds(), fp_param_get(), fp_param_print(), fp_param_set(), fp_prime_clean(), fp_prime_conv(), fp_prime_conv_dig(), fp_prime_get(), fp_prime_get_2ad(), fp_prime_get_cnr(), fp_prime_get_conv(), fp_prime_get_crt(), fp_prime_get_mod18(), fp_prime_get_mod8(), fp_prime_get_par(), fp_prime_get_par_sps(), fp_prime_get_qnr(), fp_prime_get_rdc(), fp_prime_get_sps(), fp_prime_get_srt(), fp_prime_init(), fp_prime_set(), fp_prime_set_pairf(), fp_prime_set_pmers(), fp_read_bin(), fp_sub_dig(), fp_trs(), g2_is_valid(), gt_get_gen(), gt_is_valid(), pc_core_calc(), pc_core_clean(), pc_core_init(), pp_map_sim_tatep_k18(), pp_map_sim_weilp_k18(), pp_map_tatep_k18(), pp_map_weilp_k18(), pp_mil_k54(), rand_bytes(), rand_clean(), rand_gen(), rand_init(), and rand_seed().
core_set()
void core_set (ctx_t * ctx)
Switched the library context to a new context.
Parameters
[in] ctx - the new library context.
Definition at line 206 of file relic_core.c.
References core_ctx.
Variable Documentation
first_ctx
ctx_t first_ctx static
Default library context.
Definition at line 85 of file relic_core.c.
Referenced by core_init().
core_ctx
ctx_t* core_ctx = NULL static
Definition at line 99 of file relic_core.c.
Referenced by core_clean(), core_get(), core_init(), and core_set().