RELIC: src/fpx/relic_fpx_exp.c File Reference
relic_fpx_exp.c File Reference
Prime field extensions.
#include "relic_core.h"
Functions
void fp2_exp (fp2_t c, const fp2_t a, const bn_t b)
void fp2_exp_dig (fp2_t c, const fp2_t a, dig_t b)
void fp3_exp (fp3_t c, const fp3_t a, const bn_t b)
void fp4_exp (fp4_t c, const fp4_t a, const bn_t b)
void fp6_exp (fp6_t c, const fp6_t a, const bn_t b)
void fp8_exp (fp8_t c, const fp8_t a, const bn_t b)
void fp8_exp_dig (fp8_t c, const fp8_t a, dig_t b)
void fp9_exp (fp9_t c, const fp9_t a, const bn_t b)
void fp12_exp (fp12_t c, const fp12_t a, const bn_t b)
void fp12_exp_dig (fp12_t c, const fp12_t a, dig_t b)
void fp16_exp (fp16_t c, const fp16_t a, const bn_t b)
void fp16_exp_dig (fp16_t c, const fp16_t a, dig_t b)
void fp18_exp (fp18_t c, const fp18_t a, const bn_t b)
void fp18_exp_dig (fp18_t c, const fp18_t a, dig_t b)
void fp24_exp (fp24_t c, const fp24_t a, const bn_t b)
void fp24_exp_dig (fp24_t c, const fp24_t a, dig_t b)
void fp48_exp (fp48_t c, const fp48_t a, const bn_t b)
void fp48_exp_dig (fp48_t c, const fp48_t a, dig_t b)
void fp54_exp (fp54_t c, const fp54_t a, const bn_t b)
void fp54_exp_dig (fp54_t c, const fp54_t a, dig_t b)
Detailed Description
Implementation of exponentiation in extensions defined over prime fields.
Definition in file relic_fpx_exp.c.
Function Documentation
fp2_exp()
void fp2_exp (fp2_t c, const fp2_t a, const bn_t b)
Computes a power of a quadratic extension field element.
Parameters
[out] c - the result.
[in] a - the quadratic extension element to exponentiate.
[in] b - the exponent.
Definition at line 38 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), ERR_CAUGHT, fp2_copy(), fp2_free, fp2_inv(), fp2_mul, fp2_new, fp2_null, fp2_set_dig(), fp2_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by fp2_field_init().
fp2_exp_dig()
void fp2_exp_dig (fp2_t c, const fp2_t a, dig_t b)
Computes a power of a quadratic extension field element by a small exponent.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 73 of file relic_fpx_exp.c.
References ERR_CAUGHT, fp2_copy(), fp2_free, fp2_mul, fp2_new, fp2_null, fp2_set_dig(), fp2_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, RLC_TRY, and util_bits_dig().
Referenced by fp2_exp_cyc().
fp3_exp()
void fp3_exp (fp3_t c, const fp3_t a, const bn_t b)
Computes a power of a cubic extension field element. Computes c = a^b.
Parameters
[out] c - the result.
[in] a - the cubic extension element to exponentiate.
[in] b - the exponent.
Definition at line 104 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), ERR_CAUGHT, fp3_copy(), fp3_free, fp3_inv(), fp3_mul, fp3_new, fp3_null, fp3_set_dig(), fp3_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by fp3_field_init(), and fp3_srt().
fp4_exp()
void fp4_exp (fp4_t c, const fp4_t a, const bn_t b)
Computes a power of a quartic extension field element. Computes c = a^b.
Parameters
[out] c - the result.
[in] a - the quartic extension element to exponentiate.
[in] b - the exponent.
Definition at line 140 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), ERR_CAUGHT, fp4_copy(), fp4_free, fp4_inv(), fp4_mul, fp4_new, fp4_null, fp4_set_dig(), fp4_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by fp4_field_init().
fp6_exp()
void fp6_exp (fp6_t c, const fp6_t a, const bn_t b)
Computes a power of a sextic extension field element. Computes c = a^b.
Parameters
[out] c - the result.
[in] a - the sextic extension element to exponentiate.
[in] b - the exponent.
Definition at line 176 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), ERR_CAUGHT, fp6_copy(), fp6_free, fp6_inv(), fp6_mul, fp6_new, fp6_null, fp6_set_dig(), fp6_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
fp8_exp()
void fp8_exp (fp8_t c, const fp8_t a, const bn_t b)
Computes a power of an octic extension field element. Computes c = a^b.
Parameters
[out] c - the result.
[in] a - the octic extension element to exponentiate.
[in] b - the exponent.
Definition at line 212 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), ERR_CAUGHT, fp8_copy(), fp8_exp_cyc(), fp8_free, fp8_inv(), fp8_mul, fp8_new, fp8_null, fp8_set_dig(), fp8_sqr, fp8_test_cyc(), RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by fp8_field_init().
fp8_exp_dig()
void fp8_exp_dig (fp8_t c, const fp8_t a, dig_t b)
Computes a power of an octic extension field element by a small exponent.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 252 of file relic_fpx_exp.c.
References bn_bits(), bn_free, bn_new, bn_null, bn_rec_naf(), bn_set_dig(), ERR_CAUGHT, fp8_copy(), fp8_free, fp8_inv_cyc(), fp8_mul, fp8_new, fp8_null, fp8_set_dig(), fp8_sqr, fp8_sqr_cyc(), fp8_test_cyc(), RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_THROW, RLC_TRY, and util_bits_dig().
fp9_exp()
void fp9_exp (fp9_t c, const fp9_t a, const bn_t b)
Computes a power of a nonic extension field element. Computes c = a^b.
Parameters
[out] c - the result.
[in] a - the nonic extension element to exponentiate.
[in] b - the exponent.
Definition at line 312 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), ERR_CAUGHT, fp9_copy(), fp9_free, fp9_inv(), fp9_mul, fp9_new, fp9_null, fp9_set_dig(), fp9_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
fp12_exp()
void fp12_exp (fp12_t c, const fp12_t a, const bn_t b)
Computes a power of a dodecic extension field element. Faster formulas are used if the extension field element is cyclotomic.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 348 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), ERR_CAUGHT, fp12_copy(), fp12_exp_cyc(), fp12_free, fp12_inv(), fp12_mul, fp12_new, fp12_null, fp12_set_dig(), fp12_sqr, fp12_test_cyc(), RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
fp12_exp_dig()
void fp12_exp_dig (fp12_t c, const fp12_t a, dig_t b)
Computes a power of a dodecic extension field element by a small exponent. Faster formulas are used if the extension field element is cyclotomic.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 388 of file relic_fpx_exp.c.
References bn_bits(), bn_free, bn_new, bn_null, bn_rec_naf(), bn_set_dig(), ERR_CAUGHT, fp12_copy(), fp12_free, fp12_inv_cyc(), fp12_mul, fp12_new, fp12_null, fp12_set_dig(), fp12_sqr, fp12_sqr_cyc, fp12_test_cyc(), RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_THROW, RLC_TRY, and util_bits_dig().
fp16_exp()
void fp16_exp (fp16_t c, const fp16_t a, const bn_t b)
Computes a power of an sextadecic extension field element. Computes c = a^b.
Parameters
[out] c - the result.
[in] a - the sextadecic extension element to exponentiate.
[in] b - the exponent.
Definition at line 448 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), ERR_CAUGHT, fp16_copy(), fp16_exp_cyc(), fp16_free, fp16_inv(), fp16_mul, fp16_new, fp16_null, fp16_set_dig(), fp16_sqr, fp16_test_cyc(), RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
fp16_exp_dig()
void fp16_exp_dig (fp16_t c, const fp16_t a, dig_t b)
Computes a power of a sextic extension field element by a small exponent. Faster formulas are used if the extension field element is cyclotomic.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 488 of file relic_fpx_exp.c.
References bn_bits(), bn_free, bn_new, bn_null, bn_rec_naf(), bn_set_dig(), ERR_CAUGHT, fp16_copy(), fp16_free, fp16_inv_cyc(), fp16_mul, fp16_new, fp16_null, fp16_set_dig(), fp16_sqr, fp16_sqr_cyc(), fp16_test_cyc(), RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_THROW, RLC_TRY, and util_bits_dig().
fp18_exp()
void fp18_exp (fp18_t c, const fp18_t a, const bn_t b)
Computes a power of an octdecic extension field element. Faster formulas are used if the field element is cyclotomic.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 548 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), ERR_CAUGHT, fp18_copy(), fp18_free, fp18_inv(), fp18_mul, fp18_new, fp18_null, fp18_set_dig(), fp18_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
fp18_exp_dig()
void fp18_exp_dig (fp18_t c, const fp18_t a, dig_t b)
Computes a power of a octdecic extension field element by a small exponent. Faster formulas are used if the extension field element is cyclotomic.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 584 of file relic_fpx_exp.c.
References bn_bits(), bn_free, bn_new, bn_null, bn_rec_naf(), bn_set_dig(), ERR_CAUGHT, fp18_copy(), fp18_free, fp18_inv_cyc(), fp18_mul, fp18_new, fp18_null, fp18_set_dig(), fp18_sqr, fp18_sqr_cyc, fp18_test_cyc(), RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_THROW, RLC_TRY, and util_bits_dig().
fp24_exp()
void fp24_exp (fp24_t c, const fp24_t a, const bn_t b)
Computes a power of a 24-degree extension field element. Faster formulas are used if the extension field element is cyclotomic.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 644 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), ERR_CAUGHT, fp24_copy(), fp24_free, fp24_inv(), fp24_mul, fp24_new, fp24_null, fp24_set_dig(), fp24_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
fp24_exp_dig()
void fp24_exp_dig (fp24_t c, const fp24_t a, dig_t b)
Computes a power of a 24-extension field element by a small exponent. Faster formulas are used if the extension field element is cyclotomic.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 680 of file relic_fpx_exp.c.
References bn_bits(), bn_free, bn_new, bn_null, bn_rec_naf(), bn_set_dig(), ERR_CAUGHT, fp24_copy(), fp24_free, fp24_inv_cyc(), fp24_mul, fp24_new, fp24_null, fp24_set_dig(), fp24_sqr, fp24_sqr_cyc, fp24_test_cyc(), RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_THROW, RLC_TRY, and util_bits_dig().
fp48_exp()
void fp48_exp (fp48_t c, const fp48_t a, const bn_t b)
Computes a power of a 48-extension field element. Faster formulas are used if the extension field element is cyclotomic.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 740 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), ERR_CAUGHT, fp48_copy(), fp48_exp_cyc(), fp48_free, fp48_inv(), fp48_mul, fp48_new, fp48_null, fp48_set_dig(), fp48_sqr, fp48_test_cyc(), RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
fp48_exp_dig()
void fp48_exp_dig (fp48_t c, const fp48_t a, dig_t b)
Computes a power of a 48-extension field element by a small exponent. Faster formulas are used if the extension field element is cyclotomic.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 780 of file relic_fpx_exp.c.
References bn_bits(), bn_free, bn_new, bn_null, bn_rec_naf(), bn_set_dig(), ERR_CAUGHT, fp48_copy(), fp48_free, fp48_inv_cyc(), fp48_mul, fp48_new, fp48_null, fp48_set_dig(), fp48_sqr, fp48_sqr_cyc, fp48_test_cyc(), RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_THROW, RLC_TRY, and util_bits_dig().
fp54_exp()
void fp54_exp (fp54_t c, const fp54_t a, const bn_t b)
Computes a power of a 54-extension field element. Faster formulas are used if the extension field element is cyclotomic.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 840 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), ERR_CAUGHT, fp54_copy(), fp54_free, fp54_inv(), fp54_mul, fp54_new, fp54_null, fp54_set_dig(), fp54_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
fp54_exp_dig()
void fp54_exp_dig (fp54_t c, const fp54_t a, dig_t b)
Computes a power of a 54-extension field element by a small exponent. Faster formulas are used if the extension field element is cyclotomic.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 876 of file relic_fpx_exp.c.
References bn_bits(), bn_free, bn_new, bn_null, bn_rec_naf(), bn_set_dig(), ERR_CAUGHT, fp54_copy(), fp54_free, fp54_inv_cyc(), fp54_mul, fp54_new, fp54_null, fp54_set_dig(), fp54_sqr, fp54_sqr_cyc, fp54_test_cyc(), RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_THROW, RLC_TRY, and util_bits_dig().