RELIC: src/md/sha384-512.c File Reference
sha384-512.c File Reference
#include "sha.h"
Macros
#define SHA512_SHR(bits, word)
#define SHA512_ROTR(bits, word)
#define SHA512_SIGMA0(word)
#define SHA512_SIGMA1(word)
#define SHA512_sigma0(word)
#define SHA512_sigma1(word)
#define SHA384_512AddLength(context, length)
Functions
static void SHA384_512Finalize (SHA512Context *context, uint8_t Pad_Byte)
static void SHA384_512PadMessage (SHA512Context *context, uint8_t Pad_Byte)
static void SHA384_512ProcessMessageBlock (SHA512Context *context)
static int SHA384_512Reset (SHA512Context *context, uint64_t H0[])
static int SHA384_512ResultN (SHA512Context *context, uint8_t Message_Digest[], int HashSize)
int SHA384Reset (SHA384Context *context)
int SHA384Input (SHA384Context *context, const uint8_t *message_array, unsigned int length)
int SHA384FinalBits (SHA384Context *context, const uint8_t message_bits, unsigned int length)
int SHA384Result (SHA384Context *context, uint8_t Message_Digest[SHA384HashSize])
int SHA512Reset (SHA512Context *context)
int SHA512Input (SHA512Context *context, const uint8_t *message_array, unsigned int length)
int SHA512FinalBits (SHA512Context *context, const uint8_t message_bits, unsigned int length)
int SHA512Result (SHA512Context *context, uint8_t Message_Digest[SHA512HashSize])
Variables
static uint64_t SHA384_H0 []
static uint64_t SHA512_H0 []
Macro Definition Documentation
SHA512_SHR
#define SHA512_SHR (bits, word)
Value:
(((uint64_t)(word)) >> (bits))
Definition at line 257 of file sha384-512.c.
SHA512_ROTR
#define SHA512_ROTR (bits, word)
Value:
                                ((((uint64_t)(word)) >> (bits)) | \
                                (((uint64_t)(word)) << (64-(bits))))
Definition at line 258 of file sha384-512.c.
SHA512_SIGMA0
#define SHA512_SIGMA0 (word)
Value:
 (SHA512_ROTR(28,word) ^ SHA512_ROTR(34,word) ^ SHA512_ROTR(39,word))
Definition at line 262 of file sha384-512.c.
Referenced by SHA384_512ProcessMessageBlock().
SHA512_SIGMA1
#define SHA512_SIGMA1 (word)
Value:
 (SHA512_ROTR(14,word) ^ SHA512_ROTR(18,word) ^ SHA512_ROTR(41,word))
Definition at line 264 of file sha384-512.c.
Referenced by SHA384_512ProcessMessageBlock().
SHA512_sigma0
#define SHA512_sigma0 (word)
Value:
 (SHA512_ROTR( 1,word) ^ SHA512_ROTR( 8,word) ^ SHA512_SHR( 7,word))
Definition at line 266 of file sha384-512.c.
Referenced by SHA384_512ProcessMessageBlock().
SHA512_sigma1
#define SHA512_sigma1 (word)
Value:
 (SHA512_ROTR(19,word) ^ SHA512_ROTR(61,word) ^ SHA512_SHR( 6,word))
Definition at line 268 of file sha384-512.c.
Referenced by SHA384_512ProcessMessageBlock().
SHA384_512AddLength
#define SHA384_512AddLength (context, length)
Value:
   (addTemp = context->Length_Low, context->Corrupted =        \
    ((context->Length_Low += length) < addTemp) &&             \
    (++context->Length_High == 0) ? 1 : 0)
Definition at line 274 of file sha384-512.c.
Referenced by SHA512FinalBits(), and SHA512Input().
Function Documentation
SHA384_512Finalize()
static void SHA384_512Finalize (SHA512Context * context, uint8_t Pad_Byte) static
Definition at line 557 of file sha384-512.c.
References SHA512Context::Computed, SHA512Context::Length_High, SHA512Context::Length_Low, SHA512Context::Message_Block, SHA384_512PadMessage(), and SHA512_Message_Block_Size.
Referenced by SHA384_512ResultN(), and SHA512FinalBits().
SHA384_512PadMessage()
static void SHA384_512PadMessage (SHA512Context * context, uint8_t Pad_Byte) static
Definition at line 624 of file sha384-512.c.
References SHA512Context::Length_High, SHA512Context::Length_Low, SHA512Context::Message_Block, SHA512Context::Message_Block_Index, SHA384_512ProcessMessageBlock(), and SHA512_Message_Block_Size.
Referenced by SHA384_512Finalize().
SHA384_512ProcessMessageBlock()
static void SHA384_512ProcessMessageBlock (SHA512Context * context) static
Definition at line 708 of file sha384-512.c.
References G, SHA512Context::Intermediate_Hash, SHA512Context::Message_Block, SHA512Context::Message_Block_Index, SHA512_SIGMA0, SHA512_sigma0, SHA512_SIGMA1, SHA512_sigma1, SHA_Ch, and SHA_Maj.
Referenced by SHA384_512PadMessage(), and SHA512Input().
SHA384_512Reset()
static int SHA384_512Reset (SHA512Context * context, uint64_t H0[]) static
Definition at line 955 of file sha384-512.c.
References SHA512Context::Computed, SHA512Context::Corrupted, SHA512Context::Intermediate_Hash, SHA512Context::Length_High, SHA512Context::Length_Low, SHA512Context::Message_Block_Index, SHA512HashSize, shaNull, and shaSuccess.
Referenced by SHA384Reset(), and SHA512Reset().
SHA384_512ResultN()
static int SHA384_512ResultN (SHA512Context * context, uint8_t Message_Digest[], int HashSize) static
Definition at line 1004 of file sha384-512.c.
References SHA512Context::Computed, SHA512Context::Corrupted, SHA512Context::Intermediate_Hash, SHA384_512Finalize(), shaNull, and shaSuccess.
Referenced by SHA384Result(), and SHA512Result().
SHA384Reset()
int SHA384Reset (SHA384Context * context)
Definition at line 318 of file sha384-512.c.
References SHA384_512Reset(), and SHA384_H0.
Referenced by md_map_sh384().
SHA384Input()
int SHA384Input (SHA384Context * context, const uint8_t * message_array, unsigned int length)
Definition at line 343 of file sha384-512.c.
References SHA512Input().
Referenced by md_map_sh384().
SHA384FinalBits()
int SHA384FinalBits (SHA384Context * context, const uint8_t message_bits, unsigned int length)
Definition at line 369 of file sha384-512.c.
References SHA512FinalBits().
SHA384Result()
int SHA384Result (SHA384Context * context, uint8_t Message_Digest[SHA384HashSize])
Definition at line 394 of file sha384-512.c.
References SHA384_512ResultN(), and SHA384HashSize.
Referenced by md_map_sh384().
SHA512Reset()
int SHA512Reset (SHA512Context * context)
Definition at line 414 of file sha384-512.c.
References SHA384_512Reset(), and SHA512_H0.
Referenced by md_map_sh512().
SHA512Input()
int SHA512Input (SHA512Context * context, const uint8_t * message_array, unsigned int length)
Definition at line 439 of file sha384-512.c.
References SHA512Context::Computed, SHA512Context::Corrupted, SHA512Context::Message_Block, SHA512Context::Message_Block_Index, SHA384_512AddLength, SHA384_512ProcessMessageBlock(), SHA512_Message_Block_Size, shaNull, shaStateError, and shaSuccess.
Referenced by md_map_sh512(), and SHA384Input().
SHA512FinalBits()
int SHA512FinalBits (SHA512Context * context, const uint8_t message_bits, unsigned int length)
Definition at line 496 of file sha384-512.c.
References SHA512Context::Computed, SHA512Context::Corrupted, SHA384_512AddLength, SHA384_512Finalize(), shaNull, shaStateError, and shaSuccess.
Referenced by SHA384FinalBits().
SHA512Result()
int SHA512Result (SHA512Context * context, uint8_t Message_Digest[SHA512HashSize])
Definition at line 594 of file sha384-512.c.
References SHA384_512ResultN(), and SHA512HashSize.
Referenced by md_map_sh512().
Variable Documentation
SHA384_H0
uint64_t SHA384_H0[] static
Initial value:
= {
    0xCBBB9D5DC1059ED8ll, 0x629A292A367CD507ll, 0x9159015A3070DD17ll,
    0x152FECD8F70E5939ll, 0x67332667FFC00B31ll, 0x8EB44A8768581511ll,
    0xDB0C2E0D64F98FA7ll, 0x47B5481DBEFA4FA4ll
}
Definition at line 290 of file sha384-512.c.
Referenced by SHA384Reset().
SHA512_H0
uint64_t SHA512_H0[] static
Initial value:
= {
    0x6A09E667F3BCC908ll, 0xBB67AE8584CAA73Bll, 0x3C6EF372FE94F82Bll,
    0xA54FF53A5F1D36F1ll, 0x510E527FADE682D1ll, 0x9B05688C2B3E6C1Fll,
    0x1F83D9ABFB41BD6Bll, 0x5BE0CD19137E2179ll
}
Definition at line 295 of file sha384-512.c.
Referenced by SHA512Reset().