RELIC: include/relic_rand.h File Reference
relic_rand.h File Reference
Pseudo-random number generators.
#include "relic_rand.h"
Macros
#define RLC_RAND_SIZE (1 + 2*440/8)
#define RLC_RAND_SEED 64
Functions
void rand_init (void)
void rand_clean (void)
void rand_seed (void(*callback)(uint8_t *, size_t, void *), void *arg)
int rand_check (uint8_t *buf, size_t size)
void rand_bytes (uint8_t *buf, size_t size)
Detailed Description
Interface of the module for pseudo-random number generation.
Definition in file relic_rand.h.
Macro Definition Documentation
RLC_RAND_SIZE
#define RLC_RAND_SIZE (1 + 2*440/8)
Size of the PRNG internal state in bytes.
Definition at line 51 of file relic_rand.h.
Referenced by rand_bytes(), rand_gen(), and rand_seed().
RLC_RAND_SEED
#define RLC_RAND_SEED 64
Minimum size of the PRNG seed.
Definition at line 67 of file relic_rand.h.
Referenced by rand_init().
Function Documentation
rand_init()
void rand_init (void)
Initializes the pseudo-random number generator.
Definition at line 85 of file relic_rand_core.c.
References core_get(), ERR_NO_FILE, ERR_NO_READ, rand_seed(), RLC_RAND_PATH, RLC_RAND_SEED, RLC_THROW, and _ctx_t::seeded.
Referenced by core_init().
rand_clean()
void rand_clean (void)
Finishes the pseudo-random number generator.
Definition at line 203 of file relic_rand_core.c.
References core_get(), _ctx_t::rand, and _ctx_t::seeded.
Referenced by core_clean().
rand_seed()
void rand_seed (void(* callback)(uint8_t *, size_t, void *), void * arg)
Sets the initial state of the pseudo-random number generator as a function pointer.
Parameters
[in] callback - the callback to call.
[in] arg - the argument for the callback.
rand_check()
int rand_check (uint8_t * buf, size_t size)
Performs a basic self-test in the pseudo-random number generator output, and raises an exception in case a string of identifical bytes is found.
Parameters
[out] buf - the buffer to check.
[in] size - the number of bytes to check.
Exceptions
ERR_NO_RAND - if the pseudo-random number generator is stuck.
Definition at line 186 of file relic_rand_core.c.
References RAND_REP, RLC_ERR, and RLC_OK.
rand_bytes()
void rand_bytes (uint8_t * buf, size_t size)
Gathers pseudo-random bytes from the pseudo-random number generator.
Parameters
[out] buf - the buffer to write.
[in] size - the number of bytes to gather.
Exceptions
ERR_NO_VALID - if the required length is too large.
ERR_NO_READ - it the pseudo-random number generator cannot generate the specified number of bytes.
Definition at line 154 of file relic_rand_hashd.c.
References core_get(), _ctx_t::counter, ERR_NO_VALID, md_map, _ctx_t::rand, rand_add(), rand_gen(), rand_inc(), RLC_MD_LEN, RLC_RAND_SIZE, and RLC_THROW.
Referenced by bn_rand(), cp_cmlhs_gen(), fb_rand(), fp_rand(), pad_pkcs2(), and util_perm().