RELIC: include/relic_cp.h File Reference
relic_cp.h File Reference
Cryptographic protocols
#include "relic_conf.h"
#include "relic_types.h"
#include "relic_util.h"
#include "relic_bn.h"
#include "relic_ec.h"
#include "relic_pc.h"
#include "relic_mpc.h"
Data Structures
struct _rsa_st
struct shpe_st
struct bdpe_st
struct _sokaka
struct bgn_st
struct _ers_st
struct _smlers_st
struct _etrs_st
Macros
#define shpe_null(A)
#define shpe_new(A)
#define shpe_free(A)
#define rsa_null(A)
#define rsa_new(A)
#define rsa_free(A)
#define rabin_null(A)
#define rabin_new(A)
#define rabin_free(A)
#define phpe_null(A)
#define phpe_new(A)
#define phpe_free(A)
#define bdpe_null(A)
#define bdpe_new(A)
#define bdpe_free(A)
#define sokaka_null(A)
#define sokaka_new(A)
#define sokaka_free(A)
#define bgn_null(A)
#define bgn_new(A)
#define bgn_free(A)
#define ers_null(A)
#define ers_new(A)
#define ers_free(A)
#define smlers_null(A)
#define smlers_new(A)
#define smlers_free(A)
#define etrs_null(A)
#define etrs_new(A)
#define etrs_free(A)
Typedefs
typedef _rsa_st rsa_t[1]
typedef crt_st rabin_t[1]
typedef crt_st phpe_t[1]
typedef shpe_st shpe_t[1]
typedef bdpe_st bdpe_t[1]
typedef struct _sokaka sokaka_st
typedef sokaka_st sokaka_t[1]
typedef bgn_st bgn_t[1]
typedef struct _ers_st ers_st
typedef ers_st ers_t[1]
typedef struct _smlers_st smlers_st
typedef smlers_st smlers_t[1]
typedef struct _etrs_st etrs_st
typedef etrs_st etrs_t[1]
Functions
int cp_rsa_gen (rsa_t pub, rsa_t prv, size_t bits)
int cp_rsa_enc (uint8_t *out, size_t *out_len, const uint8_t *in, size_t in_len, const rsa_t pub)
int cp_rsa_dec (uint8_t *out, size_t *out_len, const uint8_t *in, size_t in_len, const rsa_t prv)
int cp_rsa_sig (uint8_t *sig, size_t *sig_len, const uint8_t *msg, size_t msg_len, int hash, const rsa_t prv)
int cp_rsa_ver (uint8_t *sig, size_t sig_len, const uint8_t *msg, size_t msg_len, int hash, const rsa_t pub)
int cp_rabin_gen (rabin_t pub, rabin_t prv, size_t bits)
int cp_rabin_enc (uint8_t *out, size_t *out_len, const uint8_t *in, size_t in_len, const rabin_t pub)
int cp_rabin_dec (uint8_t *out, size_t *out_len, const uint8_t *in, size_t in_len, const rabin_t prv)
int cp_bdpe_gen (bdpe_t pub, bdpe_t prv, dig_t block, size_t bits)
int cp_bdpe_enc (uint8_t *out, size_t *out_len, dig_t in, const bdpe_t pub)
int cp_bdpe_dec (dig_t *out, const uint8_t *in, size_t in_len, const bdpe_t prv)
int cp_phpe_gen (bn_t pub, phpe_t prv, size_t bits)
int cp_phpe_enc (bn_t c, const bn_t m, const bn_t pub)
int cp_phpe_add (bn_t r, const bn_t c, const bn_t d, const bn_t pub)
int cp_phpe_dec (bn_t m, const bn_t c, const phpe_t prv)
int cp_shpe_gen (shpe_t pub, shpe_t prv, size_t sbits, size_t nbits)
int cp_shpe_enc (bn_t c, const bn_t m, const shpe_t pub)
int cp_shpe_enc_prv (bn_t c, const bn_t m, const shpe_t prv)
int cp_shpe_dec (bn_t m, const bn_t c, const shpe_t prv)
int cp_ghpe_gen (bn_t pub, bn_t prv, size_t bits)
int cp_ghpe_enc (bn_t c, const bn_t m, const bn_t pub, size_t s)
int cp_ghpe_dec (bn_t m, const bn_t c, const bn_t pub, const bn_t prv, size_t s)
int cp_ecdh_gen (bn_t d, ec_t q)
int cp_ecdh_key (uint8_t *key, size_t key_len, const bn_t d, const ec_t q)
int cp_ecmqv_gen (bn_t d, ec_t q)
int cp_ecmqv_key (uint8_t *key, size_t key_len, const bn_t d1, const bn_t d2, const ec_t q2u, const ec_t q1v, const ec_t q2v)
int cp_ecies_gen (bn_t d, ec_t q)
int cp_ecies_enc (ec_t r, uint8_t *out, size_t *out_len, const uint8_t *in, size_t in_len, const ec_t q)
int cp_ecies_dec (uint8_t *out, size_t *out_len, const ec_t r, const uint8_t *in, size_t in_len, const bn_t d)
int cp_ecdsa_gen (bn_t d, ec_t q)
int cp_ecdsa_sig (bn_t r, bn_t s, const uint8_t *msg, size_t len, int hash, const bn_t d)
int cp_ecdsa_ver (const bn_t r, const bn_t s, const uint8_t *msg, size_t len, int hash, const ec_t q)
int cp_ecss_gen (bn_t d, ec_t q)
int cp_ecss_sig (bn_t e, bn_t s, const uint8_t *msg, size_t len, const bn_t d)
int cp_ecss_ver (bn_t e, bn_t s, const uint8_t *msg, size_t len, const ec_t q)
int cp_pdpub_gen (bn_t c, bn_t r, g1_t u1, g2_t u2, g2_t v2, gt_t e)
int cp_pdpub_ask (g1_t v1, g2_t w2, const g1_t p, const g2_t q, const bn_t c, const bn_t r, const g1_t u1, const g2_t u2, const g2_t v2)
int cp_pdpub_ans (gt_t g[3], const g1_t p, const g2_t q, const g1_t v1, const g2_t v2, const g2_t w2)
int cp_pdpub_ver (gt_t r, const gt_t g[3], const bn_t c, const gt_t e)
int cp_pdprv_gen (bn_t c, bn_t r[3], g1_t u1[2], g2_t u2[2], g2_t v2[4], gt_t e[2])
int cp_pdprv_ask (g1_t v1[3], g2_t w2[4], const g1_t p, const g2_t q, const bn_t c, const bn_t r[3], const g1_t u1[2], const g2_t u2[2], const g2_t v2[4])
int cp_pdprv_ans (gt_t g[4], const g1_t v1[3], const g2_t w2[4])
int cp_pdprv_ver (gt_t r, const gt_t g[4], const bn_t c, const gt_t e[2])
int cp_lvpub_gen (bn_t r, g1_t u1, g2_t u2, g2_t v2, gt_t e)
int cp_lvpub_ask (bn_t c, g1_t v1, g2_t w2, const g1_t p, const g2_t q, const bn_t r, const g1_t u1, const g2_t u2, const g2_t v2)
int cp_lvpub_ans (gt_t g[2], const g1_t p, const g2_t q, const g1_t v1, const g2_t v2, const g2_t w2)
int cp_lvpub_ver (gt_t r, const gt_t g[2], const bn_t c, const gt_t e)
int cp_lvprv_gen (bn_t c, bn_t r[3], g1_t u1[2], g2_t u2[2], g2_t v2[4], gt_t e[2])
int cp_lvprv_ask (g1_t v1[3], g2_t w2[4], const g1_t p, const g2_t q, const bn_t c, const bn_t r[3], const g1_t u1[2], const g2_t u2[2], const g2_t v2[4])
int cp_lvprv_ans (gt_t g[4], const g1_t v1[3], const g2_t w2[4])
int cp_lvprv_ver (gt_t r, const gt_t g[4], const bn_t c, const gt_t e[2])
int cp_sokaka_gen (bn_t master)
int cp_sokaka_gen_prv (sokaka_t k, const char *id, bn_t master)
int cp_sokaka_key (uint8_t *key, size_t key_len, const char *id1, const sokaka_t k, const char *id2)
int cp_bgn_gen (bgn_t pub, bgn_t prv)
int cp_bgn_enc1 (g1_t out[2], const dig_t in, const bgn_t pub)
int cp_bgn_dec1 (dig_t *out, const g1_t in[2], const bgn_t prv)
int cp_bgn_enc2 (g2_t out[2], const dig_t in, const bgn_t pub)
int cp_bgn_dec2 (dig_t *out, const g2_t in[2], const bgn_t prv)
int cp_bgn_add (gt_t e[4], const gt_t c[4], const gt_t d[4])
int cp_bgn_mul (gt_t e[4], const g1_t c[2], const g2_t d[2])
int cp_bgn_dec (dig_t *out, const gt_t in[4], const bgn_t prv)
int cp_ibe_gen (bn_t master, g1_t pub)
int cp_ibe_gen_prv (g2_t prv, const char *id, const bn_t master)
int cp_ibe_enc (uint8_t *out, size_t *out_len, const uint8_t *in, size_t in_len, const char *id, const g1_t pub)
int cp_ibe_dec (uint8_t *out, size_t *out_len, const uint8_t *in, size_t in_len, const g2_t prv)
int cp_bls_gen (bn_t d, g2_t q)
int cp_bls_sig (g1_t s, const uint8_t *msg, size_t len, const bn_t d)
int cp_bls_ver (const g1_t s, const uint8_t *msg, size_t len, const g2_t q)
int cp_bbs_gen (bn_t d, g2_t q, gt_t z)
int cp_bbs_sig (g1_t s, const uint8_t *msg, size_t len, int hash, const bn_t d)
int cp_bbs_ver (g1_t s, const uint8_t *msg, size_t len, int hash, const g2_t q, const gt_t z)
int cp_cls_gen (bn_t u, bn_t v, g2_t x, g2_t y)
int cp_cls_sig (g1_t a, g1_t b, g1_t c, const uint8_t *msg, size_t len, const bn_t u, const bn_t v)
int cp_cls_ver (const g1_t a, const g1_t b, const g1_t c, const uint8_t *msg, size_t len, const g2_t x, const g2_t y)
int cp_cli_gen (bn_t t, bn_t u, bn_t v, g2_t x, g2_t y, g2_t z)
int cp_cli_sig (g1_t a, g1_t A, g1_t b, g1_t B, g1_t c, const uint8_t *msg, size_t len, const bn_t r, const bn_t t, const bn_t u, const bn_t v)
int cp_cli_ver (g1_t a, g1_t A, g1_t b, g1_t B, g1_t c, const uint8_t *msg, size_t len, const bn_t r, const g2_t x, const g2_t y, const g2_t z)
int cp_clb_gen (bn_t t, bn_t u, bn_t *v, g2_t x, g2_t y, g2_t *z, size_t l)
int cp_clb_sig (g1_t a, g1_t *A, g1_t b, g1_t *B, g1_t c, const uint8_t *ms[], const size_t *ls, const bn_t t, const bn_t u, const bn_t *v, const size_t l)
int cp_clb_ver (const g1_t a, const g1_t *A, const g1_t b, const g1_t *B, const g1_t c, const uint8_t *ms[], const size_t *ls, const g2_t x, const g2_t y, const g2_t *z, size_t l)
int cp_pss_gen (bn_t u, bn_t v, g2_t g, g2_t x, g2_t y)
int cp_pss_sig (g1_t a, g1_t b, const bn_t m, const bn_t u, const bn_t v)
int cp_pss_ver (const g1_t a, const g1_t b, const bn_t m, const g2_t g, const g2_t x, const g2_t y)
int cp_mpss_gen (bn_t r[2], bn_t s[2], g2_t g, g2_t x[2], g2_t y[2])
int cp_mpss_sig (g1_t a, g1_t b[2], const bn_t m[2], const bn_t r[2], const bn_t s[2], const mt_t mul_tri[2], const mt_t sm_tri[2])
int cp_mpss_bct (g2_t x[2], g2_t y[2])
int cp_mpss_ver (gt_t e, const g1_t a, const g1_t b[2], const bn_t m[2], const g2_t h, const g2_t x, const g2_t y, const mt_t sm_tri[2], const pt_t pc_tri[2])
int cp_psb_gen (bn_t r, bn_t *s, g2_t g, g2_t x, g2_t *y, size_t l)
int cp_psb_sig (g1_t a, g1_t b, const bn_t *ms, const bn_t r, const bn_t *s, size_t l)
int cp_psb_ver (const g1_t a, const g1_t b, const bn_t *ms, const g2_t g, const g2_t x, const g2_t *y, size_t l)
int cp_mpsb_gen (bn_t r[2], bn_t s[][2], g2_t h, g2_t x[2], g2_t y[][2], size_t l)
int cp_mpsb_sig (g1_t a, g1_t b[2], const bn_t m[][2], const bn_t r[2], const bn_t s[][2], const mt_t mul_tri[2], const mt_t sm_tri[2], size_t l)
int cp_mpsb_bct (g2_t x[2], g2_t y[][2], size_t l)
int cp_mpsb_ver (gt_t e, const g1_t a, const g1_t b[2], const bn_t m[][2], const g2_t h, const g2_t x, const g2_t y[][2], const bn_t v[][2], const mt_t sm_tri[2], const pt_t pc_tri[2], size_t l)
int cp_zss_gen (bn_t d, g1_t q, gt_t z)
int cp_zss_sig (g2_t s, const uint8_t *msg, size_t len, int hash, const bn_t d)
int cp_zss_ver (const g2_t s, const uint8_t *msg, size_t len, int hash, const g1_t q, const gt_t z)
int cp_vbnn_gen (bn_t msk, ec_t mpk)
int cp_vbnn_gen_prv (bn_t sk, ec_t pk, const bn_t msk, const uint8_t *id, size_t id_len)
int cp_vbnn_sig (ec_t r, bn_t z, bn_t h, const uint8_t *id, size_t id_len, const uint8_t *msg, int msg_len, const bn_t sk, const ec_t pk)
int cp_vbnn_ver (const ec_t r, const bn_t z, const bn_t h, const uint8_t *id, size_t id_len, const uint8_t *msg, int msg_len, const ec_t mpk)
int cp_pokdl_prv (bn_t c, bn_t r, const ec_t y, const bn_t x)
int cp_pokdl_ver (const bn_t c, const bn_t r, const ec_t y)
int cp_pokor_prv (bn_t c[2], bn_t r[2], const ec_t y[2], const bn_t x)
int cp_pokor_ver (const bn_t c[2], const bn_t r[2], const ec_t y[2])
int cp_sokdl_sig (bn_t c, bn_t r, const uint8_t *msg, size_t len, const ec_t y, const bn_t x)
int cp_sokdl_ver (const bn_t c, const bn_t r, const uint8_t *msg, size_t len, const ec_t y)
int cp_sokor_sig (bn_t c[2], bn_t r[2], const uint8_t *msg, size_t len, const ec_t y[2], const ec_t g[2], const bn_t x, int first)
int cp_sokor_ver (const bn_t c[2], const bn_t r[2], const uint8_t *msg, size_t len, const ec_t y[2], const ec_t g[2])
int cp_ers_gen (ec_t pp)
int cp_ers_gen_key (bn_t sk, ec_t pk)
int cp_ers_sig (bn_t td, ers_t p, const uint8_t *msg, size_t len, const bn_t sk, const ec_t pk, const ec_t pp)
int cp_ers_ver (const bn_t td, const ers_t *s, size_t size, const uint8_t *msg, size_t len, const ec_t pp)
int cp_ers_ext (bn_t td, ers_t *p, size_t *size, const uint8_t *msg, size_t len, const ec_t pk, const ec_t pp)
int cp_smlers_sig (bn_t td, smlers_t p, const uint8_t *msg, size_t len, const bn_t sk, const ec_t pk, const ec_t pp)
int cp_smlers_ver (bn_t td, smlers_t *s, size_t size, const uint8_t *msg, size_t len, const ec_t pp)
int cp_smlers_ext (bn_t td, smlers_t *p, size_t *size, const uint8_t *msg, size_t len, const ec_t pk, const ec_t pp)
int cp_etrs_sig (bn_t *td, bn_t *y, size_t max, etrs_t p, const uint8_t *msg, size_t len, const bn_t sk, const ec_t pk, const ec_t pp)
int cp_etrs_ver (size_t thres, const bn_t *td, const bn_t *y, size_t max, const etrs_t *s, size_t size, const uint8_t *msg, size_t len, const ec_t pp)
int cp_etrs_ext (bn_t *td, bn_t *y, size_t max, etrs_t *p, size_t *size, const uint8_t *msg, size_t len, const ec_t pk, const ec_t pp)
int cp_etrs_uni (int thres, bn_t *td, bn_t *y, int max, etrs_t *p, size_t *size, const uint8_t *msg, size_t len, const bn_t sk, const ec_t pk, const ec_t pp)
int cp_cmlhs_init (g1_t h)
int cp_cmlhs_gen (bn_t *x, gt_t *hs, size_t len, uint8_t *prf, size_t plen, bn_t sk, g2_t pk, bn_t d, g2_t y, int bls)
int cp_cmlhs_sig (g1_t sig, g2_t z, g1_t a, g1_t c, g1_t r, g2_t s, const bn_t msg, const char *data, int label, const bn_t x, const g1_t h, const uint8_t *prf, size_t plen, const bn_t sk, const bn_t d, int bls)
int cp_cmlhs_fun (g1_t a, g1_t c, const g1_t as[], const g1_t cs[], const dig_t *f, size_t len)
int cp_cmlhs_evl (g1_t r, g2_t s, const g1_t rs[], const g2_t ss[], const dig_t *f, size_t len)
int cp_cmlhs_ver (const g1_t r, const g2_t s, const g1_t *sig, const g2_t *z, const g1_t *a, const g1_t *c, const bn_t m, const char *data, const g1_t h, const int *label, const gt_t *hs[], const dig_t *f[], const size_t *flen, const g2_t *y, const g2_t *pk, size_t slen, int bls)
void cp_cmlhs_off (gt_t vk, const g1_t h, const int *label, const gt_t *hs[], const dig_t *f[], const size_t *flen, size_t slen)
int cp_cmlhs_onv (const g1_t r, const g2_t s, const g1_t *sig, const g2_t *z, const g1_t *a, const g1_t *c, const bn_t msg, const char *data, const g1_t h, const gt_t vk, const g2_t *y, const g2_t *pk, size_t slen, int bls)
int cp_mklhs_gen (bn_t sk, g2_t pk)
int cp_mklhs_sig (g1_t s, const bn_t m, const char *data, const char *id, const char *tag, const bn_t sk)
int cp_mklhs_fun (bn_t mu, const bn_t *m, const dig_t *f, size_t len)
int cp_mklhs_evl (g1_t sig, const g1_t *s, const dig_t *f, size_t len)
int cp_mklhs_ver (const g1_t sig, const bn_t m, const bn_t *mu, const char *data, const char *id[], const char *tag[], const dig_t *f[], const size_t *flen, const g2_t *pk, size_t slen)
int cp_mklhs_off (g1_t *h, dig_t *ft, const char *id[], const char *tag[], const dig_t *f[], const size_t *flen, size_t slen)
int cp_mklhs_onv (const g1_t sig, const bn_t m, const bn_t *mu, const char *data, const char *id[], const g1_t *h, const dig_t *ft, const g2_t *pk, size_t slen)
int cp_rsapsi_gen (bn_t g, bn_t n, size_t bits)
int cp_rsapsi_ask (bn_t d, bn_t r, bn_t *p, const bn_t g, const bn_t n, const bn_t *x, size_t m)
int cp_rsapsi_ans (bn_t *t, bn_t *u, const bn_t d, const bn_t g, const bn_t n, const bn_t *y, size_t l)
int cp_rsapsi_int (bn_t *z, size_t *len, const bn_t r, const bn_t *p, const bn_t n, const bn_t *x, const size_t m, const bn_t *t, const bn_t *u, size_t l)
int cp_shipsi_gen (bn_t g, crt_t crt, size_t bits)
int cp_shipsi_ask (bn_t d, bn_t r, bn_t *p, const bn_t g, const bn_t n, const bn_t *x, size_t m)
int cp_shipsi_ans (bn_t *t, bn_t u, bn_t d, const bn_t g, const crt_t crt, const bn_t *y, const size_t n)
int cp_shipsi_int (bn_t *z, size_t *len, const bn_t r, const bn_t *p, const bn_t n, const bn_t *x, size_t m, const bn_t *t, const bn_t u, size_t l)
int cp_pbpsi_gen (bn_t sk, g1_t ss, g2_t *s, size_t m)
int cp_pbpsi_ask (g2_t *d, bn_t r, const bn_t *x, const g2_t *s, size_t m)
int cp_pbpsi_ans (gt_t *t, g1_t *u, const g1_t ss, const g2_t d, const bn_t *y, size_t n)
int cp_pbpsi_int (bn_t *z, size_t *len, const g2_t *d, const bn_t *x, size_t m, const gt_t *t, const g1_t *u, size_t n)
Detailed Description
Interface of cryptographic protocols.
Definition in file relic_cp.h.
Macro Definition Documentation
shpe_null
#define shpe_null (A)
Value:
RLC_NULL(A)
Initializes a Subgroup Paillier key pair with a null value.
Parameters
[out] A - the moduli to initialize.
Definition at line 274 of file relic_cp.h.
shpe_new
#define shpe_new (A)
Value:
    bn_new((A)->a);                                                         \
    bn_new((A)->b);                                                         \
    bn_new((A)->g);                                                         \
    bn_new((A)->gn);                                                        \
    crt_new((A)->crt);                                                      \
Calls a function to allocate and initialize a Subgroup Paillier key pair.
Parameters
[out] A - the new key pair.
Definition at line 294 of file relic_cp.h.
shpe_free
#define shpe_free (A)
Value:
/* empty */
Calls a function to clean and free a Subgroup Paillier key pair.
Parameters
[out] A - the key pair to clean and free.
Definition at line 321 of file relic_cp.h.
rsa_null
#define rsa_null (A)
Value:
RLC_NULL(A)
Initializes an RSA key pair with a null value.
Parameters
[out] A - the key pair to initialize.
Definition at line 330 of file relic_cp.h.
rsa_new
#define rsa_new (A)
Value:
    bn_new((A)->d);                                                         \
    bn_new((A)->e);                                                         \
    crt_new((A)->crt);                                                      \
Calls a function to allocate and initialize an RSA key pair.
Parameters
[out] A - the new key pair.
Definition at line 350 of file relic_cp.h.
rsa_free
#define rsa_free (A)
Value:
/* empty */
Calls a function to clean and free an RSA key pair.
Parameters
[out] A - the key pair to clean and free.
Definition at line 373 of file relic_cp.h.
rabin_null
#define rabin_null (A)
Value:
RLC_NULL(A)
Initializes a Rabin key pair with a null value.
Parameters
[out] A - the key pair to initialize.
Definition at line 382 of file relic_cp.h.
rabin_new
#define rabin_new (A)
Value:
crt_new(A)
Calls a function to allocate and initialize a Rabin key pair.
Parameters
[out] A - the new key pair.
Definition at line 389 of file relic_cp.h.
rabin_free
#define rabin_free (A)
Value:
crt_free(A)
Calls a function to clean and free a Rabin key pair.
Parameters
[out] A - the key pair to clean and free.
Definition at line 396 of file relic_cp.h.
phpe_null
#define phpe_null (A)
Value:
RLC_NULL(A)
Initializes a Paillier key pair with a null value.
Parameters
[out] A - the key pair to initialize.
Definition at line 403 of file relic_cp.h.
phpe_new
#define phpe_new (A)
Value:
crt_new(A)
Calls a function to allocate and initialize a Paillier key pair.
Parameters
[out] A - the new key pair.
Definition at line 410 of file relic_cp.h.
phpe_free
#define phpe_free (A)
Value:
crt_free(A)
Calls a function to clean and free a Paillier key pair.
Parameters
[out] A - the key pair to clean and free.
Definition at line 417 of file relic_cp.h.
bdpe_null
#define bdpe_null (A)
Value:
RLC_NULL(A)
Initializes a Benaloh's key pair with a null value.
Parameters
[out] A - the key pair to initialize.
Definition at line 424 of file relic_cp.h.
bdpe_new
#define bdpe_new (A)
Value:
    bn_new((A)->n);                                                         \
    bn_new((A)->y);                                                         \
    bn_new((A)->p);                                                         \
    bn_new((A)->q);                                                         \
    (A)->t = 0;                                                             \
Calls a function to allocate and initialize a Benaloh's key pair.
Parameters
[out] A - the new key pair.
Definition at line 444 of file relic_cp.h.
bdpe_free
#define bdpe_free (A)
Value:
/* empty */
Calls a function to clean and free a Benaloh's key pair.
Parameters
[out] A - the key pair to clean and free.
Definition at line 471 of file relic_cp.h.
sokaka_null
#define sokaka_null (A)
Value:
RLC_NULL(A)
Initializes a SOKAKA key pair with a null value.
Parameters
[out] A - the key pair to initialize.
Definition at line 479 of file relic_cp.h.
sokaka_new
#define sokaka_new (A)
Value:
/* empty */
Calls a function to allocate and initialize a SOKAKA key pair.
Parameters
[out] A - the new key pair.
Definition at line 496 of file relic_cp.h.
sokaka_free
#define sokaka_free (A)
Value:
/* empty */
Calls a function to clean and free a SOKAKA key pair.
Parameters
[out] A - the key pair to clean and free.
Definition at line 514 of file relic_cp.h.
bgn_null
#define bgn_null (A)
Value:
RLC_NULL(A)
Initializes a BGN key pair with a null value.
Parameters
[out] A - the key pair to initialize.
Definition at line 522 of file relic_cp.h.
bgn_new
#define bgn_new (A)
Value:
/* empty */
Calls a function to allocate and initialize a BGN key pair.
Parameters
[out] A - the new key pair.
Definition at line 546 of file relic_cp.h.
bgn_free
#define bgn_free (A)
Value:
/* empty */
Calls a function to clean and free a BGN key pair.
Parameters
[out] A - the key pair to clean and free.
Definition at line 571 of file relic_cp.h.
ers_null
#define ers_null (A)
Value:
RLC_NULL(A)
Initializes a BGN key pair with a null value.
Parameters
[out] A - the key pair to initialize.
Definition at line 579 of file relic_cp.h.
ers_new
#define ers_new (A)
Value:
/* empty */
Calls a function to allocate and initialize an extendable signature ring.
Parameters
[out] A - the new signature ring.
Definition at line 600 of file relic_cp.h.
ers_free
#define ers_free (A)
Value:
/* empty */
Calls a function to clean and free an extendable signature ring.
Parameters
[out] A - the signature ring to clean and free.
Definition at line 622 of file relic_cp.h.
smlers_null
#define smlers_null (A)
Value:
RLC_NULL(A)
Initializes a BGN key pair with a null value.
Parameters
[out] A - the key pair to initialize.
Definition at line 630 of file relic_cp.h.
smlers_new
#define smlers_new (A)
Value:
/* empty */
Calls a function to allocate and initialize an extendable signature ring.
Parameters
[out] A - the new signature ring.
Definition at line 651 of file relic_cp.h.
smlers_free
#define smlers_free (A)
Value:
/* empty */
Calls a function to clean and free an extendable signature ring.
Parameters
[out] A - the signature ring to clean and free.
Definition at line 673 of file relic_cp.h.
etrs_null
#define etrs_null (A)
Value:
RLC_NULL(A)
Initializes a BGN key pair with a null value.
Parameters
[out] A - the key pair to initialize.
Definition at line 681 of file relic_cp.h.
etrs_new
#define etrs_new (A)
Value:
/* empty */
Calls a function to allocate and initialize an extendable signature ring.
Parameters
[out] A - the new signature ring.
Definition at line 703 of file relic_cp.h.
etrs_free
#define etrs_free (A)
Value:
/* empty */
Calls a function to clean and free an extendable signature ring.
Parameters
[out] A - the signature ring to clean and free.
Definition at line 727 of file relic_cp.h.
Typedef Documentation
rsa_t
typedef _rsa_st rsa_t[1]
Pointer to an RSA key pair.
Definition at line 67 of file relic_cp.h.
rabin_t
typedef crt_st rabin_t[1]
Pointer to a Rabin key pair.
Definition at line 76 of file relic_cp.h.
phpe_t
typedef crt_st phpe_t[1]
Pointer to a Paillier's Homomorphic Probabilistic Encryption key pair.
Definition at line 85 of file relic_cp.h.
shpe_t
typedef shpe_st shpe_t[1]
Pointer to a Subgroup-Paillier's Homomorphic Probabilistic Encryption key pair.
Definition at line 111 of file relic_cp.h.
bdpe_t
typedef bdpe_st bdpe_t[1]
Pointer to a Benaloh's Dense Probabilistic Encryption key pair.
Definition at line 136 of file relic_cp.h.
sokaka_st
typedef struct _sokaka sokaka_st
Represents a SOKAKA key pair.
sokaka_t
typedef sokaka_st sokaka_t[1]
Pointer to SOKAKA key pair.
Definition at line 155 of file relic_cp.h.
bgn_t
typedef bgn_st bgn_t[1]
Pointer to a Boneh-Goh-Nissim cryptosystem key pair.
Definition at line 188 of file relic_cp.h.
ers_st
typedef struct _ers_st ers_st
Represents an extendable ring signature.
ers_t
typedef ers_st ers_t[1]
Pointer to an extendable ring signature.
Definition at line 211 of file relic_cp.h.
smlers_st
typedef struct _smlers_st smlers_st
Represents an extendable ring signature.
smlers_t
typedef smlers_st smlers_t[1]
Pointer to an extendable ring signature.
Definition at line 234 of file relic_cp.h.
etrs_st
typedef struct _etrs_st etrs_st
Represents an extendable threshold ring signature.
etrs_t
typedef etrs_st etrs_t[1]
Pointer to an extendable ring signature.
Definition at line 259 of file relic_cp.h.
Function Documentation
cp_rsa_gen()
int cp_rsa_gen (rsa_t pub, rsa_t prv, size_t bits)
Generates a key pair for the RSA cryptosystem. Generates additional values for the CRT optimization if CP_CRT is on.
Parameters
[out] pub - the public key.
[out] prv - the private key.
[in] bits - the key length in bits.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 584 of file relic_cp_rsa.c.
References bn_add(), bn_add_dig(), bn_cmp(), bn_cmp_dig(), bn_copy(), bn_free, bn_gcd_ext, bn_gen_prime, bn_mod, bn_mod_inv(), bn_mul, bn_new, bn_null, bn_set_2b(), bn_sign(), bn_sub_dig(), RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FINALLY, RLC_LT, RLC_NEG, RLC_OK, and RLC_TRY.
cp_rsa_enc()
int cp_rsa_enc (uint8_t * out, size_t * out_len, const uint8_t * in, size_t in_len, const rsa_t pub)
Encrypts using the RSA cryptosystem.
Parameters
[out] out - the output buffer.
[in,out] out_len - the buffer capacity and number of bytes written.
[in] in - the input buffer.
[in] in_len - the number of bytes to encrypt.
[in] pub - the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 669 of file relic_cp_rsa.c.
References bn_add(), bn_free, bn_mxp, bn_new, bn_null, bn_read_bin(), bn_size_bin(), bn_write_bin(), bn_zero(), pad_pkcs2(), RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, RLC_TRY, RSA_ENC, RSA_ENC_FIN, and RSA_PAD_LEN.
cp_rsa_dec()
int cp_rsa_dec (uint8_t * out, size_t * out_len, const uint8_t * in, size_t in_len, const rsa_t prv)
Decrypts using the RSA cryptosystem. Uses the CRT optimization if CP_CRT is on.
Parameters
[out] out - the output buffer.
[in,out] out_len - the buffer capacity and number of bytes written.
[in] in - the input buffer.
[in] in_len - the number of bytes to decrypt.
[in] prv - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 728 of file relic_cp_rsa.c.
References bn_free, bn_mxp, bn_mxp_crt(), bn_new, bn_null, bn_read_bin(), bn_size_bin(), bn_write_bin(), pad_pkcs2(), RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, RLC_TRY, RSA_DEC, and RSA_PAD_LEN.
cp_rsa_sig()
int cp_rsa_sig (uint8_t * sig, size_t * sig_len, const uint8_t * msg, size_t msg_len, int hash, const rsa_t prv)
Signs using the basic RSA signature algorithm. The flag must be non-zero if the message being signed is already a hash value. Uses the CRT optimization if CP_CRT is on.
Parameters
[out] sig - the signature
[out] sig_len - the number of bytes written in the signature.
[in] msg - the message to sign.
[in] msg_len - the number of bytes to sign.
[in] hash - the flag to indicate the message format.
[in] prv - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 785 of file relic_cp_rsa.c.
References bn_add(), bn_bits(), bn_copy(), bn_free, bn_mxp, bn_mxp_crt(), bn_new, bn_null, bn_read_bin(), bn_size_bin(), bn_write_bin(), bn_zero(), ERR_CAUGHT, md_map, pad_pkcs2(), RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_MD_LEN, RLC_OK, RLC_THROW, RLC_TRY, RSA_PAD_LEN, RSA_SIG, RSA_SIG_FIN, and RSA_SIG_HASH.
cp_rsa_ver()
int cp_rsa_ver (uint8_t * sig, size_t sig_len, const uint8_t * msg, size_t msg_len, int hash, const rsa_t pub)
Verifies an RSA signature. The flag must be non-zero if the message being signed is already a hash value.
Parameters
[in] sig - the signature to verify.
[in] sig_len - the signature length in bytes.
[in] msg - the signed message.
[in] msg_len - the message length in bytes.
[in] hash - the flag to indicate the message format.
[in] pub - the public key.
Returns
a boolean value indicating if the signature is valid.
Definition at line 875 of file relic_cp_rsa.c.
References bn_bits(), bn_free, bn_mxp, bn_new, bn_null, bn_read_bin(), bn_size_bin(), bn_write_bin(), md_map, pad_pkcs2(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FREE, RLC_MAX, RLC_MD_LEN, RLC_OK, RLC_TRY, RSA_PAD_LEN, RSA_VER, RSA_VER_HASH, and util_cmp_sec().
cp_rabin_gen()
int cp_rabin_gen (rabin_t pub, rabin_t prv, size_t bits)
Generates a key pair for the Rabin cryptosystem.
Parameters
[out] pub - the public key.
[out] prv - the private key,
[in] bits - the key length in bits.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 52 of file relic_cp_rabin.c.
References bn_cmp(), bn_cmp_dig(), bn_copy(), bn_free, bn_gcd_ext, bn_gen_prime, bn_mod_2b(), bn_mul, bn_new, bn_null, RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FINALLY, RLC_LT, RLC_OK, and RLC_TRY.
cp_rabin_enc()
int cp_rabin_enc (uint8_t * out, size_t * out_len, const uint8_t * in, size_t in_len, const rabin_t pub)
Encrypts using the Rabin cryptosystem.
Parameters
[out] out - the output buffer.
[in,out] out_len - the buffer capacity and number of bytes written.
[in] in - the input buffer.
[in] in_len - the number of bytes to encrypt.
[in] pub - the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 98 of file relic_cp_rabin.c.
References bn_add(), bn_add_dig(), bn_free, bn_lsh(), bn_mod, bn_mod_2b(), bn_new, bn_null, bn_read_bin(), bn_size_bin(), bn_sqr, bn_write_bin(), bn_zero(), RABIN_PAD, RABIN_PAD_LEN, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_rabin_dec()
int cp_rabin_dec (uint8_t * out, size_t * out_len, const uint8_t * in, size_t in_len, const rabin_t prv)
Decrypts using the Rabin cryptosystem.
Parameters
[out] out - the output buffer.
[in,out] out_len - the buffer capacity and number of bytes written.
[in] in - the input buffer.
[in] in_len - the number of bytes to decrypt.
[in] prv - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 150 of file relic_cp_rabin.c.
References bn_add(), bn_add_dig(), bn_cmp(), bn_free, bn_is_zero(), bn_mod, bn_mod_2b(), bn_mul, bn_mxp, bn_new, bn_null, bn_read_bin(), bn_rsh(), bn_sign(), bn_size_bin(), bn_sub(), bn_write_bin(), RABIN_PAD, RABIN_PAD_LEN, RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FINALLY, RLC_NEG, RLC_OK, and RLC_TRY.
cp_bdpe_gen()
int cp_bdpe_gen (bdpe_t pub, bdpe_t prv, dig_t block, size_t bits)
Generates a key pair for Benaloh's Dense Probabilistic Encryption.
Parameters
[out] pub - the public key.
[out] prv - the private key.
[in] block - the block size.
[in] bits - the key length in bits.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_bdpe.c.
References bn_add_dig(), bn_cmp_dig(), bn_copy(), bn_div_dig(), bn_free, bn_gcd_dig(), bn_gen_prime, bn_is_prime(), bn_is_prime_basic(), bn_mul, bn_mul_dig(), bn_mxp, bn_new, bn_null, bn_rand(), bn_set_dig(), bn_sub_dig(), ERR_NO_VALID, RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FINALLY, RLC_OK, RLC_POS, RLC_THROW, RLC_TRY, and util_bits_dig().
cp_bdpe_enc()
int cp_bdpe_enc (uint8_t * out, size_t * out_len, dig_t in, const bdpe_t pub)
Encrypts using Benaloh's cryptosystem.
Parameters
[out] out - the output buffer.
[in,out] out_len - the buffer capacity and number of bytes written.
[in] in - the plaintext as a small integer.
[in] pub - the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 110 of file relic_cp_bdpe.c.
References bn_free, bn_mod, bn_mul, bn_mxp, bn_mxp_dig(), bn_new, bn_null, bn_rand_mod(), bn_set_dig(), bn_size_bin(), bn_write_bin(), RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_bdpe_dec()
int cp_bdpe_dec (dig_t * out, const uint8_t * in, size_t in_len, const bdpe_t prv)
Decrypts using Benaloh's cryptosystem.
Parameters
[out] out - the decrypted small integer.
[in] in - the input buffer.
[in] in_len - the number of bytes to encrypt.
[in] prv - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 155 of file relic_cp_bdpe.c.
References bn_add_dig(), bn_cmp(), bn_div_dig(), bn_free, bn_mul, bn_mxp, bn_mxp_dig(), bn_new, bn_null, bn_read_bin(), bn_size_bin(), bn_sub(), RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_phpe_gen()
int cp_phpe_gen (bn_t pub, phpe_t prv, size_t bits)
Generates a key pair for Paillier's Homomorphic Probabilistic Encryption.
Parameters
[out] pub - the public key.
[out] prv - the private key.
[in] bits - the key length in bits.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_phpe.c.
References bn_cmp(), bn_copy(), bn_gen_prime, bn_mod, bn_mod_inv(), bn_mul, bn_sub_dig(), RLC_EQ, and RLC_OK.
cp_phpe_enc()
int cp_phpe_enc (bn_t c, const bn_t m, const bn_t pub)
Encrypts using the Paillier cryptosystem.
Parameters
[out] c - the ciphertext, represented as an integer.
[in] m - the plaintext as an integer.
[in] pub - the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 100 of file relic_cp_phpe.c.
References bn_add_dig(), bn_bits(), bn_free, bn_mod, bn_mul, bn_mxp, bn_new, bn_null, bn_rand_mod(), bn_sqr, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_phpe_add()
int cp_phpe_add (bn_t r, const bn_t c, const bn_t d, const bn_t pub)
Evaluated a homomorphic addition using the Paillier cryptosystem.
Parameters
[out] r - the resulting ciphertext.
[in] c - the first ciphertext as an integer to multiply.
[in] d - the second ciphertext as an integer to multiply.
[in] pub - the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 77 of file relic_cp_phpe.c.
References bn_free, bn_mod, bn_mul, bn_new, bn_null, bn_sqr, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_phpe_dec()
int cp_phpe_dec (bn_t m, const bn_t c, const phpe_t prv)
Decrypts using the Paillier cryptosystem.
Parameters
[out] m - the plaintext, represented as an integer.
[in] c - the ciphertex as an integer.
[in] prv - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 143 of file relic_cp_phpe.c.
References bn_bits(), bn_div(), bn_free, bn_mod, bn_mod_inv(), bn_mul, bn_mxp, bn_mxp_crt(), bn_new, bn_null, bn_sqr, bn_sub_dig(), RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_shpe_gen()
int cp_shpe_gen (shpe_t pub, shpe_t prv, size_t sbits, size_t nbits)
Generates a key pair for Paillier's Subgroup Homomorphic Probabilistic Encryption.
Parameters
[out] pub - the public key.
[out] prv - the private key.
[in] sbits - the subgroup order in bits.
[in] nbits - the key length in bits.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 39 of file relic_cp_shpe.c.
References bn_add_dig(), bn_cmp(), bn_copy(), bn_div(), bn_gen_prime, bn_gen_prime_factor(), bn_mod, bn_mod_inv(), bn_mul, bn_mxp, bn_sqr, bn_sub_dig(), RLC_EQ, RLC_ERR, and RLC_OK.
cp_shpe_enc()
int cp_shpe_enc (bn_t c, const bn_t m, const shpe_t pub)
Encrypts using the Subgroup Paillier cryptosystem.
Parameters
[out] c - the ciphertext, represented as an integer.
[in] m - the plaintext as an integer.
[in] pub - the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 149 of file relic_cp_shpe.c.
References bn_add(), bn_bits(), bn_free, bn_mul, bn_mxp, bn_new, bn_null, bn_rand_mod(), bn_sqr, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_shpe_enc_prv()
int cp_shpe_enc_prv (bn_t c, const bn_t m, const shpe_t prv)
Encrypts faster using the Subgroup Paillier cryptosystem if the private key is known.
Parameters
[out] c - the ciphertext represented as an integer.
[in] m - the plaintext as an integer.
[in] prv - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 101 of file relic_cp_shpe.c.
References bn_add_dig(), bn_bits(), bn_free, bn_mod, bn_mul, bn_mxp, bn_new, bn_null, bn_rand_mod(), bn_sqr, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_shpe_dec()
int cp_shpe_dec (bn_t m, const bn_t c, const shpe_t prv)
Decrypts using the Subgroup Paillier cryptosystem.
Parameters
[out] m - the plaintext, represented as an integer.
[in] c - the ciphertex as an integer.
[in] prv - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 191 of file relic_cp_shpe.c.
References bn_bits(), bn_div(), bn_free, bn_mod, bn_mod_inv(), bn_mul, bn_mxp, bn_mxp_crt(), bn_new, bn_null, bn_sqr, bn_sub_dig(), RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_ghpe_gen()
int cp_ghpe_gen (bn_t pub, bn_t prv, size_t bits)
Generates a key pair for Genealized Homomorphic Probabilistic Encryption.
Parameters
[out] pub - the public key.
[out] prv - the private key.
[in] bits - the key length in bits.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 39 of file relic_cp_ghpe.c.
References bn_add_dig(), bn_cmp(), bn_cmp_dig(), bn_free, bn_gen_prime, bn_mod_2b(), bn_mul, bn_new, bn_null, bn_sub_dig(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_OK, RLC_THROW, and RLC_TRY.
cp_ghpe_enc()
int cp_ghpe_enc (bn_t c, const bn_t m, const bn_t pub, size_t s)
Encrypts using the Generalized Paillier cryptosystem.
Parameters
[out] c - the ciphertext.
[in] m - the plaintext.
[in] pub - the public key.
[in] s - the block length parameter.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 81 of file relic_cp_ghpe.c.
References bn_add_dig(), bn_bits(), bn_copy(), bn_free, bn_mod, bn_mul, bn_mxp, bn_new, bn_null, bn_rand_mod(), RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_ghpe_dec()
int cp_ghpe_dec (bn_t m, const bn_t c, const bn_t pub, const bn_t prv, size_t s)
Decrypts using the Generalized Paillier cryptosystem.
Parameters
[out] m - the plaintext.
[in] c - the ciphertext.
[in] pub - the public key.
[in] s - the block length parameter.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 129 of file relic_cp_ghpe.c.
References bn_add(), bn_bits(), bn_copy(), bn_div(), bn_div_dig(), bn_free, bn_mod, bn_mod_inv(), bn_mul, bn_mxp, bn_new, bn_null, bn_sign(), bn_sqr, bn_sub(), bn_sub_dig(), bn_zero(), RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_NEG, RLC_OK, and RLC_TRY.
cp_ecdh_gen()
int cp_ecdh_gen (bn_t d, ec_t q)
Generates an ECDH key pair.
Parameters
[out] d - the private key.
[in] q - the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_ecdh.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), ec_curve_get_ord, ec_mul_gen, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_ecdh_key()
int cp_ecdh_key (uint8_t * key, size_t key_len, const bn_t d, const ec_t q)
Derives a shared secret using ECDH.
Parameters
[out] key - the shared key.
[int] key_len - the intended shared key length in bytes.
[in] d - the private key.
[in] q - the point received from the other party.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 61 of file relic_cp_ecdh.c.
References bn_bits(), bn_free, bn_new, bn_null, bn_size_bin(), bn_write_bin(), ec_curve_get_cof, ec_free, ec_get_x, ec_is_infty, ec_mul, ec_mul_dig, ec_new, ec_null, ERR_CAUGHT, md_kdf(), RLC_CATCH_ANY, RLC_DIG, RLC_ERR, RLC_FC_BYTES, RLC_FINALLY, RLC_OK, RLC_THROW, and RLC_TRY.
cp_ecmqv_gen()
int cp_ecmqv_gen (bn_t d, ec_t q)
Generate an ECMQV key pair.
Should also be used to generate the ephemeral key pair.
Parameters
[out] d - the private key.
[out] q - the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_ecmqv.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), ec_curve_get_ord, ec_mul_gen, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_ecmqv_key()
int cp_ecmqv_key (uint8_t * key, size_t key_len, const bn_t d1, const bn_t d2, const ec_t q2u, const ec_t q1v, const ec_t q2v)
Derives a shared secret using ECMQV.
Parameters
[out] key - the shared key.
[int] key_len - the intended shared key length in bytes.
[in] d1 - the private key.
[in] d2 - the ephemeral private key.
[in] q2u - the ephemeral public key.
[in] q1v - the point received from the other party.
[in] q2v - the ephemeral point received from the party.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 61 of file relic_cp_ecmqv.c.
References bn_add(), bn_bits(), bn_free, bn_mod, bn_mod_2b(), bn_mul, bn_new, bn_null, bn_set_bit(), bn_size_bin(), bn_write_bin(), ec_curve_get_ord, ec_free, ec_get_x, ec_mul_sim, ec_new, ec_null, md_kdf(), RLC_CATCH_ANY, RLC_ERR, RLC_FC_BYTES, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_ecies_gen()
int cp_ecies_gen (bn_t d, ec_t q)
Generates an ECIES key pair.
Parameters
[out] d - the private key.
[in] q - the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_ecies.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), ec_curve_get_ord, ec_mul_gen, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_ecies_enc()
int cp_ecies_enc (ec_t r, uint8_t * out, size_t * out_len, const uint8_t * in, size_t in_len, const ec_t q)
Encrypts using the ECIES cryptosystem.
Parameters
[out] r - the resulting elliptic curve point.
[out] out - the output buffer.
[in,out] out_len - the buffer capacity and number of bytes written.
[in] in - the input buffer.
[in] in_len - the number of bytes to encrypt.
[in] iv - the block cipher initialization vector.
[in] q - the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 61 of file relic_cp_ecies.c.
References bc_aes_cbc_enc(), bn_bits(), bn_free, bn_new, bn_null, bn_rand_mod(), bn_size_bin(), bn_write_bin(), ec_curve_get_ord, ec_free, ec_get_x, ec_mul, ec_mul_gen, ec_new, ec_null, ec_param_level, md_hmac(), md_kdf(), RLC_BC_LEN, RLC_CATCH_ANY, RLC_CEIL, RLC_ERR, RLC_FC_BYTES, RLC_FINALLY, RLC_MAX, RLC_MD_LEN, RLC_OK, and RLC_TRY.
cp_ecies_dec()
int cp_ecies_dec (uint8_t * out, size_t * out_len, const ec_t r, const uint8_t * in, size_t in_len, const bn_t d)
Decrypts using the ECIES cryptosystem.
Parameters
[out] out - the output buffer.
[in,out] out_len - the buffer capacity and number of bytes written.
[in] in - the input buffer.
[in] in_len - the number of bytes to encrypt.
[in] iv - the block cipher initialization vector.
[in] d - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 115 of file relic_cp_ecies.c.
References bc_aes_cbc_dec(), bn_bits(), bn_free, bn_new, bn_null, bn_size_bin(), bn_write_bin(), ec_free, ec_get_x, ec_mul, ec_new, ec_null, ec_param_level, md_hmac(), md_kdf(), RLC_BC_LEN, RLC_CATCH_ANY, RLC_CEIL, RLC_ERR, RLC_FC_BYTES, RLC_FINALLY, RLC_MAX, RLC_MD_LEN, RLC_OK, RLC_TRY, and util_cmp_sec().
cp_ecdsa_gen()
int cp_ecdsa_gen (bn_t d, ec_t q)
Generates an ECDSA key pair.
Parameters
[out] d - the private key.
[in] q - the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_ecdsa.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), ec_curve_get_ord, ec_mul_gen, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
Referenced by cp_cmlhs_gen().
cp_ecdsa_sig()
int cp_ecdsa_sig (bn_t r, bn_t s, const uint8_t * msg, size_t len, int hash, const bn_t d)
Signs a message using ECDSA.
Parameters
[out] r - the first component of the signature.
[out] s - the second component of the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] hash - the flag to indicate the message format.
[in] d - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 61 of file relic_cp_ecdsa.c.
References bn_add(), bn_bits(), bn_free, bn_is_zero(), bn_mod, bn_mod_inv(), bn_mul, bn_new, bn_null, bn_rand_mod(), bn_read_bin(), bn_rsh(), ec_curve_get_ord, ec_free, ec_get_x, ec_mul_gen, ec_new, ec_null, md_map, RLC_CATCH_ANY, RLC_CEIL, RLC_ERR, RLC_FINALLY, RLC_MD_LEN, RLC_OK, and RLC_TRY.
Referenced by cp_cmlhs_sig().
cp_ecdsa_ver()
int cp_ecdsa_ver (const bn_t r, const bn_t s, const uint8_t * msg, size_t len, int hash, const ec_t q)
Verifies a message signed with ECDSA using the basic method.
Parameters
[out] r - the first component of the signature.
[out] s - the second component of the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] hash - the flag to indicate the message format.
[in] q - the public key.
Returns
a boolean value indicating if the signature is valid.
Definition at line 125 of file relic_cp_ecdsa.c.
References bn_bits(), bn_cmp(), bn_free, bn_is_zero(), bn_mod, bn_mod_inv(), bn_mul, bn_new, bn_null, bn_read_bin(), bn_rsh(), bn_sign(), dv_cmp_sec(), ec_curve_get_ord, ec_free, ec_get_x, ec_is_infty, ec_mul_sim_gen, ec_new, ec_null, ec_on_curve, ERR_CAUGHT, md_map, RLC_CATCH_ANY, RLC_CEIL, RLC_FINALLY, RLC_LT, RLC_MD_LEN, RLC_MIN, RLC_NE, RLC_POS, RLC_THROW, and RLC_TRY.
Referenced by cp_cmlhs_onv(), and cp_cmlhs_ver().
cp_ecss_gen()
int cp_ecss_gen (bn_t d, ec_t q)
Generates an Elliptic Curve Schnorr Signature key pair.
Parameters
[out] d - the private key.
[in] q - the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_ecss.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), ec_curve_get_ord, ec_mul_gen, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_ecss_sig()
int cp_ecss_sig (bn_t e, bn_t s, const uint8_t * msg, size_t len, const bn_t d)
Signs a message using the Elliptic Curve Schnorr Signature.
Parameters
[out] r - the first component of the signature.
[out] s - the second component of the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] d - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 60 of file relic_cp_ecss.c.
References bn_add(), bn_bits(), bn_free, bn_is_zero(), bn_mod, bn_mul, bn_new, bn_null, bn_rand_mod(), bn_read_bin(), bn_rsh(), bn_sub(), bn_write_bin(), ec_curve_get_ord, ec_free, ec_get_x, ec_mul_gen, ec_new, ec_null, ERR_NO_MEMORY, md_map, RLC_ALLOCA, RLC_CATCH_ANY, RLC_CEIL, RLC_ERR, RLC_FC_BYTES, RLC_FINALLY, RLC_FREE, RLC_MD_LEN, RLC_OK, RLC_THROW, and RLC_TRY.
cp_ecss_ver()
int cp_ecss_ver (bn_t e, bn_t s, const uint8_t * msg, size_t len, const ec_t q)
Verifies a message signed with the Elliptic Curve Schnorr Signature using the basic method.
Parameters
[out] r - the first component of the signature.
[out] s - the second component of the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] q - the public key.
Returns
a boolean value indicating if the signature is valid.
Definition at line 125 of file relic_cp_ecss.c.
References bn_bits(), bn_cmp(), bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, bn_read_bin(), bn_rsh(), bn_sign(), bn_write_bin(), dv_cmp_sec(), ec_curve_get_ord, ec_free, ec_get_x, ec_mul_sim_gen, ec_new, ec_null, ERR_CAUGHT, ERR_NO_MEMORY, md_map, RLC_ALLOCA, RLC_CATCH_ANY, RLC_CEIL, RLC_FC_BYTES, RLC_FINALLY, RLC_FREE, RLC_LT, RLC_MD_LEN, RLC_MIN, RLC_NE, RLC_POS, RLC_THROW, and RLC_TRY.
cp_pdpub_gen()
int cp_pdpub_gen (bn_t c, bn_t r, g1_t u1, g2_t u2, g2_t v2, gt_t e)
Generate parameters for the DCKKS pairing delegation protocol described at "Secure and Efficient Delegationof Pairings with Online Inputs" (CARDIS 2020)
Parameters
[out] c - the challenge.
[out] r - the randomness.
[out] u1 - the U1 precomputed value in G_1.
[out] u2 - the U2 precomputed value in G_2.
[out] v2 - the image of the randomness in G_2.
[out] e - the precomputed values e(U1, U2).
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_pcdel.c.
References bn_free, bn_mod_inv(), bn_new, bn_null, bn_rand(), bn_rand_mod(), g1_rand, g2_mul(), g2_rand, pc_get_ord, pc_map, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, RLC_POS, and RLC_TRY.
cp_pdpub_ask()
int cp_pdpub_ask (g1_t v1, g2_t w2, const g1_t p, const g2_t q, const bn_t c, const bn_t r, const g1_t u1, const g2_t u2, const g2_t v2)
Execute the client-side request for the DCKKS pairing delegation protocol.
Parameters
[out] v1 - the blinded element in G_1.
[out] w2 - the blinded element in G_2.
[in] p - the first argument of the pairing.
[in] q - the second argument of the pairing.
[in] c - the challenge.
[in] r - the randomness.
[in] u1 - the U1 precomputed value in G_1.
[in] u2 - the U2 precomputed value in G_2.
[in] v2 - the image of the randomness in G_2.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 67 of file relic_cp_pcdel.c.
References g1_mul(), g1_sub, g2_add, g2_mul(), and RLC_OK.
cp_pdpub_ans()
int cp_pdpub_ans (gt_t g[3], const g1_t p, const g2_t q, const g1_t v1, const g2_t v2, const g2_t w2)
Execute the server-side response for the DCKKS pairing delegation protocol.
Parameters
[out] g - the group elements computed by the server.
[in] p - the first argument of the pairing.
[in] q - the second argument of the pairing.
[in] v1 - the blinded element in G_1.
[in] v2 - the image of the randomness in G_2.
[in] w2 - the blinded element in G_2.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 81 of file relic_cp_pcdel.c.
References pc_map, and RLC_OK.
cp_pdpub_ver()
int cp_pdpub_ver (gt_t r, const gt_t g[3], const bn_t c, const gt_t e)
Verifies the result of the DCKKS pairing delegation protocol.
Parameters
[out] r - the result of the computation.
[in] g - the group elements returned by the server.
[in] c - the challenge.
[in] e - the precomputed values e(U1, U2).
Returns
a boolean value indicating if the computation is correct.
Definition at line 90 of file relic_cp_pcdel.c.
References gt_cmp, gt_copy, gt_exp(), gt_free, gt_is_valid(), gt_mul, gt_new, gt_null, gt_set_unity, RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FINALLY, and RLC_TRY.
cp_pdprv_gen()
int cp_pdprv_gen (bn_t c, bn_t r[3], g1_t u1[2], g2_t u2[2], g2_t v2[4], gt_t e[2])
Generate parameters for the DCKKS pairing delegation protocol described at "Secure and Efficient Delegationof Pairings with Online Inputs" (CARDIS 2020)
Parameters
[out] c - the challenge.
[out] r - the randomness.
[out] u1 - the U1 precomputed value in G_1.
[out] u2 - the U2 precomputed value in G_2.
[out] v2 - the image of the randomness in G_2.
[out] e - the precomputed values e(U1, U2).
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 120 of file relic_cp_pcdel.c.
References bn_free, bn_mod_inv(), bn_new, bn_null, bn_rand(), bn_rand_mod(), g1_rand, g2_mul(), g2_neg, g2_rand, pc_get_ord, pc_map, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, RLC_POS, and RLC_TRY.
cp_pdprv_ask()
int cp_pdprv_ask (g1_t v1[3], g2_t w2[4], const g1_t p, const g2_t q, const bn_t c, const bn_t r[3], const g1_t u1[2], const g2_t u2[2], const g2_t v2[4])
Execute the client-side request for the DCKKS pairing delegation protocol.
Parameters
[out] v1 - the blinded element in G_1.
[out] w2 - the blinded element in G_2.
[in] p - the first argument of the pairing.
[in] q - the second argument of the pairing.
[in] c - the challenge.
[in] r - the randomness.
[in] u1 - the U1 precomputed value in G_1.
[in] u2 - the U2 precomputed value in G_2.
[in] v2 - the image of the randomness in G_2.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 157 of file relic_cp_pcdel.c.
References bn_free, bn_mod_inv(), bn_new, bn_null, ERR_CAUGHT, g1_mul(), g1_sub, g2_add, g2_copy, g2_mul(), pc_get_ord, RLC_CATCH_ANY, RLC_FINALLY, RLC_OK, RLC_THROW, and RLC_TRY.
cp_pdprv_ans()
int cp_pdprv_ans (gt_t g[4], const g1_t v1[3], const g2_t w2[4])
Execute the server-side response for the DCKKS pairing delegation protocol.
Parameters
[out] g - the group elements computed by the server.
[in] p - the first argument of the pairing.
[in] q - the second argument of the pairing.
[in] v1 - the blinded element in G_1.
[in] v2 - the image of the randomness in G_2.
[in] w2 - the blinded element in G_2.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 191 of file relic_cp_pcdel.c.
References pc_map, and RLC_OK.
cp_pdprv_ver()
int cp_pdprv_ver (gt_t r, const gt_t g[4], const bn_t c, const gt_t e[2])
Verifies the result of the DCKKS pairing delegation protocol.
Parameters
[out] r - the result of the computation.
[in] g - the group elements returned by the server.
[in] c - the challenge.
[in] e - the precomputed values e(U1, U2).
Returns
a boolean value indicating if the computation is correct.
Definition at line 200 of file relic_cp_pcdel.c.
References gt_cmp, gt_exp(), gt_free, gt_is_valid(), gt_mul, gt_new, gt_null, gt_set_unity, RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FINALLY, and RLC_TRY.
cp_lvpub_gen()
int cp_lvpub_gen (bn_t r, g1_t u1, g2_t u2, g2_t v2, gt_t e)
Generate parameters for the LOVE pairing delegation protocol with public inputs.
Parameters
[out] r - the randomness.
[out] u1 - the U1 precomputed value in G_1.
[out] u2 - the U2 precomputed value in G_2.
[out] v2 - the image of the randomness in G_2.
[out] e - the precomputed values e(U1, U2).
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 231 of file relic_cp_pcdel.c.
References bn_free, bn_mod_inv(), bn_new, bn_null, bn_rand_mod(), g1_rand, g2_mul(), g2_rand, pc_get_ord, pc_map, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_lvpub_ask()
int cp_lvpub_ask (bn_t c, g1_t v1, g2_t w2, const g1_t p, const g2_t q, const bn_t r, const g1_t u1, const g2_t u2, const g2_t v2)
Execute the client-side request for the LOVE pairing delegation protocol.
Parameters
[out] c - the challenge.
[out] v1 - the blinded element in G_1.
[out] w2 - the blinded element in G_2.
[in] p - the first argument of the pairing.
[in] q - the second argument of the pairing.
[in] c - the challenge.
[in] r - the randomness.
[in] u1 - the U1 precomputed value in G_1.
[in] u2 - the U2 precomputed value in G_2.
[in] v2 - the image of the randomness in G_2.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 259 of file relic_cp_pcdel.c.
References bn_rand(), g1_mul(), g1_sub, g2_add, g2_mul(), RLC_OK, and RLC_POS.
cp_lvpub_ans()
int cp_lvpub_ans (gt_t g[2], const g1_t p, const g2_t q, const g1_t v1, const g2_t v2, const g2_t w2)
Execute the server-side response for the LOVE pairing delegation protocol.
Parameters
[out] g - the group elements computed by the server.
[in] p - the first argument of the pairing.
[in] q - the second argument of the pairing.
[in] v1 - the blinded element in G_1.
[in] v2 - the image of the randomness in G_2.
[in] w2 - the blinded element in G_2.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 275 of file relic_cp_pcdel.c.
References ERR_CAUGHT, g1_copy, g1_free, g1_new, g1_null, g2_copy, g2_free, g2_neg, g2_new, g2_null, pc_map, pc_map_sim, RLC_CATCH_ANY, RLC_FINALLY, RLC_OK, RLC_THROW, and RLC_TRY.
cp_lvpub_ver()
int cp_lvpub_ver (gt_t r, const gt_t g[2], const bn_t c, const gt_t e)
Verifies the result of the LOVE pairing delegation protocol.
Parameters
[out] r - the result of the computation.
[in] g - the group elements returned by the server.
[in] c - the challenge.
[in] e - the precomputed values e(U1, U2).
Returns
a boolean value indicating if the computation is correct.
Definition at line 310 of file relic_cp_pcdel.c.
References gt_cmp, gt_copy, gt_exp(), gt_free, gt_inv, gt_is_valid(), gt_mul, gt_new, gt_null, gt_set_unity, RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FINALLY, and RLC_TRY.
cp_lvprv_gen()
int cp_lvprv_gen (bn_t c, bn_t r[3], g1_t u1[2], g2_t u2[2], g2_t v2[4], gt_t e[2])
Generate parameters for the LOVE pairing delegation protocol with private inputs.
Parameters
[out] c - the challenge.
[out] r - the randomness.
[out] u1 - the U1 precomputed value in G_1.
[out] u2 - the U2 precomputed value in G_2.
[out] v2 - the image of the randomness in G_2.
[out] e - the precomputed values e(U1, U2).
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 339 of file relic_cp_pcdel.c.
References bn_free, bn_mod_inv(), bn_new, bn_null, bn_rand(), bn_rand_mod(), g1_rand, g2_mul(), g2_neg, g2_rand, pc_get_ord, pc_map, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, RLC_POS, and RLC_TRY.
cp_lvprv_ask()
int cp_lvprv_ask (g1_t v1[3], g2_t w2[4], const g1_t p, const g2_t q, const bn_t c, const bn_t r[3], const g1_t u1[2], const g2_t u2[2], const g2_t v2[4])
Execute the client-side request for the LOVE pairing delegation protocol.
Parameters
[out] v1 - the blinded element in G_1.
[out] w2 - the blinded element in G_2.
[in] p - the first argument of the pairing.
[in] q - the second argument of the pairing.
[in] c - the challenge.
[in] r - the randomness.
[in] u1 - the U1 precomputed value in G_1.
[in] u2 - the U2 precomputed value in G_2.
[in] v2 - the image of the randomness in G_2.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 376 of file relic_cp_pcdel.c.
References bn_free, bn_mod_inv(), bn_new, bn_null, ERR_CAUGHT, g1_mul(), g1_sub, g2_add, g2_copy, g2_mul(), pc_get_ord, RLC_CATCH_ANY, RLC_FINALLY, RLC_OK, RLC_THROW, and RLC_TRY.
cp_lvprv_ans()
int cp_lvprv_ans (gt_t g[4], const g1_t v1[3], const g2_t w2[4])
Execute the server-side response for the LOVE pairing delegation protocol.
Parameters
[out] g - the group elements computed by the server.
[in] p - the first argument of the pairing.
[in] q - the second argument of the pairing.
[in] v1 - the blinded element in G_1.
[in] v2 - the image of the randomness in G_2.
[in] w2 - the blinded element in G_2.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 410 of file relic_cp_pcdel.c.
References ERR_CAUGHT, g1_copy, g1_free, g1_new, g1_null, g2_copy, g2_free, g2_new, g2_null, pc_map, pc_map_sim, RLC_CATCH_ANY, RLC_FINALLY, RLC_OK, RLC_THROW, and RLC_TRY.
cp_lvprv_ver()
int cp_lvprv_ver (gt_t r, const gt_t g[4], const bn_t c, const gt_t e[2])
Verifies the result of the LOVE pairing delegation protocol.
Parameters
[out] r - the result of the computation.
[in] g - the group elements returned by the server.
[in] c - the challenge.
[in] e - the precomputed values e(U1, U2).
Returns
a boolean value indicating if the computation is correct.
Definition at line 444 of file relic_cp_pcdel.c.
References gt_cmp, gt_exp(), gt_free, gt_is_valid(), gt_mul, gt_new, gt_null, gt_set_unity, RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FINALLY, and RLC_TRY.
cp_sokaka_gen()
int cp_sokaka_gen (bn_t master)
Generates a master key for the SOKAKA identity-based non-interactive authenticated key agreement protocol.
Parameters
[out] master - the master key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 39 of file relic_cp_sokaka.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), pc_get_ord, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_sokaka_gen_prv()
int cp_sokaka_gen_prv (sokaka_t k, const char * id, bn_t master)
Generates a private key for the SOKAKA protocol.
Parameters
[out] k - the private key.
[in] id - the identity.
[in] master - the master key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 60 of file relic_cp_sokaka.c.
References g1_map, g1_mul(), g2_map, g2_mul(), pc_map_is_type1, and RLC_OK.
cp_sokaka_key()
int cp_sokaka_key (uint8_t * key, size_t key_len, const char * id1, const sokaka_t k, const char * id2)
Computes a shared key between two entities.
Parameters
[out] key - the shared key.
[int] key_len - the intended shared key length in bytes.
[in] id1 - the first identity.
[in] k - the private key of the first identity.
[in] id2 - the second identity.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 73 of file relic_cp_sokaka.c.
References ERR_NO_MEMORY, ERR_NO_VALID, g1_free, g1_map, g1_new, g1_null, g2_free, g2_map, g2_new, g2_null, gt_free, gt_new, gt_null, gt_size_bin, gt_write_bin, md_kdf(), pc_map, pc_map_is_type1, RLC_ALLOCA, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_FREE, RLC_OK, RLC_THROW, and RLC_TRY.
cp_bgn_gen()
int cp_bgn_gen (bgn_t pub, bgn_t prv)
Generates a key pair for the Boneh-Go-Nissim (BGN) cryptosystem.
Parameters
[out] pub - the public key.
[out] prv - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 42 of file relic_cp_bgn.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), g1_mul_gen(), g2_mul_gen(), pc_get_ord, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_bgn_enc1()
int cp_bgn_enc1 (g1_t out[2], const dig_t in, const bgn_t pub)
Encrypts in G_1 using the BGN cryptosystem.
Parameters
[out] out - the ciphertext.
[in] in - the plaintext as a small integer.
[in] pub - the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 75 of file relic_cp_bgn.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), g1_add, g1_free, g1_mul(), g1_mul_dig, g1_mul_gen(), g1_new, g1_norm, g1_null, pc_get_ord, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_bgn_dec1()
int cp_bgn_dec1 (dig_t * out, const g1_t in[2], const bgn_t prv)
Decrypts in G_1 using the BGN cryptosystem.
Parameters
[out] out - the decrypted small integer.
[in] in - the ciphertext.
[in] prv - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 117 of file relic_cp_bgn.c.
References bn_free, bn_mod, bn_mul, bn_new, bn_null, bn_sub(), g1_add, g1_cmp, g1_copy, g1_free, g1_is_infty, g1_mul(), g1_mul_gen(), g1_new, g1_norm, g1_null, g1_sub, pc_get_ord, RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_bgn_enc2()
int cp_bgn_enc2 (g2_t out[2], const dig_t in, const bgn_t pub)
Encrypts in G_2 using the BGN cryptosystem.
Parameters
[out] c - the ciphertext.
[in] m - the plaintext as a small integer.
[in] pub - the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 175 of file relic_cp_bgn.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), g2_add, g2_free, g2_mul(), g2_mul_dig, g2_mul_gen(), g2_new, g2_norm, g2_null, pc_get_ord, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_bgn_dec2()
int cp_bgn_dec2 (dig_t * out, const g2_t in[2], const bgn_t prv)
Decrypts in G_2 using the BGN cryptosystem.
Parameters
[out] out - the decrypted small integer.
[in] c - the ciphertext.
[in] prv - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 216 of file relic_cp_bgn.c.
References bn_free, bn_mod, bn_mul, bn_new, bn_null, bn_sub(), g2_add, g2_cmp, g2_copy, g2_free, g2_is_infty, g2_mul(), g2_mul_gen(), g2_new, g2_norm, g2_null, g2_sub, pc_get_ord, RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_bgn_add()
int cp_bgn_add (gt_t e[4], const gt_t c[4], const gt_t d[4])
Adds homomorphically two BGN ciphertexts in G_T.
Parameters
[out] e - the resulting ciphertext.
[in] c - the first ciphertext to add.
[in] d - the second ciphertext to add.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 274 of file relic_cp_bgn.c.
References gt_mul, and RLC_OK.
cp_bgn_mul()
int cp_bgn_mul (gt_t e[4], const g1_t c[2], const g2_t d[2])
Multiplies homomorphically two BGN ciphertexts in G_T.
Parameters
[out] e - the resulting ciphertext.
[in] c - the first ciphertext to add.
[in] d - the second ciphertext to add.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 281 of file relic_cp_bgn.c.
References pc_map, and RLC_OK.
cp_bgn_dec()
int cp_bgn_dec (dig_t * out, const gt_t in[4], const bgn_t prv)
Decrypts in G_T using the BGN cryptosystem.
Parameters
[out] out - the decrypted small integer.
[in] c - the ciphertext.
[in] prv - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 290 of file relic_cp_bgn.c.
References bn_add(), bn_free, bn_mod, bn_mul, bn_new, bn_null, bn_sqr, bn_sub(), g1_free, g1_get_gen, g1_new, g1_null, g2_free, g2_get_gen, g2_new, g2_null, gt_cmp, gt_copy, gt_exp(), gt_free, gt_inv, gt_is_unity, gt_mul, gt_new, gt_null, pc_get_ord, pc_map, RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_ibe_gen()
int cp_ibe_gen (bn_t master, g1_t pub)
Generates a master key for a Private Key Generator (PKG) in the Boneh-Franklin Identity-Based Encryption (BF-IBE).
Parameters
[out] master - the master key.
[out] pub - the public key of the private key generator.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_ibe.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), g1_mul_gen(), pc_get_ord, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_ibe_gen_prv()
int cp_ibe_gen_prv (g2_t prv, const char * id, const bn_t master)
Generates a private key for a user in the BF-IBE protocol.
Parameters
[out] prv - the private key.
[in] id - the identity.
[in] s - the master key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 62 of file relic_cp_ibe.c.
References g2_map, g2_mul(), and RLC_OK.
cp_ibe_enc()
int cp_ibe_enc (uint8_t * out, size_t * out_len, const uint8_t * in, size_t in_len, const char * id, const g1_t pub)
Encrypts a message using the BF-IBE protocol.
Parameters
[out] out - the output buffer.
[in,out] out_len - the buffer capacity and number of bytes written.
[in] in - the input buffer.
[in] in_len - the number of bytes to encrypt.
[in] id - the identity.
[in] pub - the public key of the PKG.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 68 of file relic_cp_ibe.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), ERR_NO_MEMORY, g1_free, g1_mul_gen(), g1_new, g1_null, g1_write_bin, g2_free, g2_map, g2_new, g2_null, gt_exp(), gt_free, gt_new, gt_null, gt_size_bin, gt_write_bin, md_map, pc_get_ord, pc_map, RLC_ALLOCA, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_FP_BYTES, RLC_FREE, RLC_MD_LEN, RLC_MIN, RLC_OK, RLC_THROW, and RLC_TRY.
cp_ibe_dec()
int cp_ibe_dec (uint8_t * out, size_t * out_len, const uint8_t * in, size_t in_len, const g2_t prv)
Decrypts a message using the BF-IBE protocol.
Parameters
[out] out - the output buffer.
[in,out] out_len - the buffer capacity and number of bytes written.
[in] in - the input buffer.
[in] in_len - the number of bytes to decrypt.
[in] pub - the private key of the user.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 145 of file relic_cp_ibe.c.
References ERR_NO_MEMORY, g1_free, g1_new, g1_null, g1_read_bin, gt_free, gt_new, gt_null, gt_size_bin, gt_write_bin, md_map, pc_map, RLC_ALLOCA, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_FP_BYTES, RLC_FREE, RLC_MD_LEN, RLC_MIN, RLC_OK, RLC_THROW, and RLC_TRY.
cp_bls_gen()
int cp_bls_gen (bn_t d, g2_t q)
Generates a key pair for the Boneh-Lynn-Schacham (BLS) signature protocol.
Parameters
[out] d - the private key.
[out] q - the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_bls.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), g2_mul_gen(), pc_get_ord, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
Referenced by cp_cmlhs_gen().
cp_bls_sig()
int cp_bls_sig (g1_t s, const uint8_t * msg, size_t len, const bn_t d)
Signs a message using the BLS protocol.
Parameters
[out] s - the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] d - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 60 of file relic_cp_bls.c.
References g1_free, g1_map, g1_mul_sec, g1_new, g1_null, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
Referenced by cp_cmlhs_sig().
cp_bls_ver()
int cp_bls_ver (const g1_t s, const uint8_t * msg, size_t len, const g2_t q)
Verifies a message signed with BLS protocol.
Parameters
[out] s - the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] q - the public key.
Returns
a boolean value indicating if the signature is valid.
Definition at line 80 of file relic_cp_bls.c.
References ERR_CAUGHT, g1_copy, g1_free, g1_map, g1_new, g1_null, g2_copy, g2_free, g2_get_gen, g2_is_valid(), g2_neg, g2_new, g2_null, gt_free, gt_is_unity, gt_new, gt_null, pc_map_sim, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by cp_cmlhs_onv(), and cp_cmlhs_ver().
cp_bbs_gen()
int cp_bbs_gen (bn_t d, g2_t q, gt_t z)
Generates a key pair for the Boneh-Boyen (BB) signature protocol.
Parameters
[out] d - the private key.
[out] q - the first component of the public key.
[out] z - the second component of the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_bbs.c.
References bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, bn_rand(), g2_mul_gen(), gt_get_gen(), pc_get_ord, pc_param_level, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, RLC_POS, and RLC_TRY.
cp_bbs_sig()
int cp_bbs_sig (g1_t s, const uint8_t * msg, size_t len, int hash, const bn_t d)
Signs a message using the BB protocol.
Parameters
[out] s - the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] hash - the flag to indicate the message format.
[in] d - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 70 of file relic_cp_bbs.c.
References bn_add(), bn_free, bn_mod, bn_mod_inv(), bn_new, bn_null, bn_read_bin(), g1_mul_gen(), md_map, pc_get_ord, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_MD_LEN, RLC_OK, and RLC_TRY.
cp_bbs_ver()
int cp_bbs_ver (g1_t s, const uint8_t * msg, size_t len, int hash, const g2_t q, const gt_t z)
Verifies a message signed with the BB protocol.
Parameters
[in] s - the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] hash - the flag to indicate the message format.
[out] q - the first component of the public key.
[out] z - the second component of the public key.
Returns
a boolean value indicating the verification result.
Definition at line 112 of file relic_cp_bbs.c.
References bn_free, bn_mod, bn_new, bn_null, bn_read_bin(), ERR_CAUGHT, g1_is_valid(), g2_add, g2_free, g2_mul_gen(), g2_new, g2_norm, g2_null, gt_cmp, gt_free, gt_new, gt_null, md_map, pc_get_ord, pc_map, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_MD_LEN, RLC_THROW, and RLC_TRY.
cp_cls_gen()
int cp_cls_gen (bn_t u, bn_t v, g2_t x, g2_t y)
Generates a key pair for the Camenisch-Lysyanskaya simple signature (CLS) protocol.
Parameters
[out] u - the first part of the private key.
[out] v - the second part of the private key.
[out] x - the first part of the public key.
[out] y - the second part of the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_cls.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), g2_mul_gen(), pc_get_ord, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_cls_sig()
int cp_cls_sig (g1_t a, g1_t b, g1_t c, const uint8_t * msg, size_t len, const bn_t u, const bn_t v)
Signs a message using the CLS protocol.
Parameters
[out] a - the first part of the signature.
[out] b - the second part of the signature.
[out] c - the third part of the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] u - the first part of the private key.
[in] v - the second part of the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 62 of file relic_cp_cls.c.
References bn_add(), bn_free, bn_mod, bn_mul, bn_new, bn_null, bn_read_bin(), g1_mul(), g1_rand, pc_get_ord, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_cls_ver()
int cp_cls_ver (const g1_t a, const g1_t b, const g1_t c, const uint8_t * msg, size_t len, const g2_t x, const g2_t y)
Verifies a signature using the CLS protocol.
Parameters
[in] a - the first part of the signature.
[in] b - the second part of the signature.
[in] c - the third part of the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] u - the first part of the public key.
[in] v - the second part of the public key.
Returns
a boolean value indicating the verification result.
Definition at line 99 of file relic_cp_cls.c.
References bn_free, bn_mod, bn_new, bn_null, bn_read_bin(), ERR_CAUGHT, g1_add, g1_copy, g1_free, g1_is_infty, g1_mul(), g1_new, g1_norm, g1_null, g2_copy, g2_free, g2_get_gen, g2_neg, g2_new, g2_null, gt_free, gt_is_unity, gt_new, gt_null, pc_get_ord, pc_map_sim, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
cp_cli_gen()
int cp_cli_gen (bn_t t, bn_t u, bn_t v, g2_t x, g2_t y, g2_t z)
Generates a key pair for the Camenisch-Lysyanskaya message-independent (CLI) signature protocol.
Parameters
[out] t - the first part of the private key.
[out] u - the second part of the private key.
[out] v - the third part of the private key.
[out] x - the first part of the public key.
[out] y - the second part of the public key.
[out] z - the third part of the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 168 of file relic_cp_cls.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), g2_mul_gen(), pc_get_ord, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_cli_sig()
int cp_cli_sig (g1_t a, g1_t A, g1_t b, g1_t B, g1_t c, const uint8_t * msg, size_t len, const bn_t r, const bn_t t, const bn_t u, const bn_t v)
Signs a message using the CLI protocol.
Parameters
[out] a - one of the components of the signature.
[out] A - one of the components of the signature.
[out] b - one of the components of the signature.
[out] B - one of the components of the signature.
[out] c - one of the components of the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] r - the per-message randomness.
[in] t - the first part of the private key.
[in] u - the second part of the private key.
[in] v - the third part of the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 194 of file relic_cp_cls.c.
References bn_add(), bn_free, bn_mod, bn_mul, bn_new, bn_null, bn_read_bin(), g1_add, g1_mul(), g1_norm, g1_rand, pc_get_ord, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_cli_ver()
int cp_cli_ver (g1_t a, g1_t A, g1_t b, g1_t B, g1_t c, const uint8_t * msg, size_t len, const bn_t r, const g2_t x, const g2_t y, const g2_t z)
Verifies a message signed using the CLI protocol.
Parameters
[in] a - one of the components of the signature.
[in] A - one of the components of the signature.
[in] b - one of the components of the signature.
[in] B - one of the components of the signature.
[in] c - one of the components of the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] r - the per-message randomness.
[in] x - the first part of the public key.
[in] y - the second part of the public key.
[in] z - the third part of the public key.
Returns
a boolean value indicating the verification result.
Definition at line 242 of file relic_cp_cls.c.
References bn_free, bn_mod, bn_new, bn_null, bn_read_bin(), ERR_CAUGHT, g1_add, g1_copy, g1_free, g1_is_infty, g1_mul_sim, g1_new, g1_norm, g1_null, g2_copy, g2_free, g2_get_gen, g2_neg, g2_new, g2_null, gt_free, gt_is_unity, gt_new, gt_null, pc_get_ord, pc_map_sim, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
cp_clb_gen()
int cp_clb_gen (bn_t t, bn_t u, bn_t * v, g2_t x, g2_t y, g2_t * z, size_t l)
Generates a key pair for the Camenisch-Lysyanskaya message-block (CLB) signature protocol.
Parameters
[out] t - the first part of the private key.
[out] u - the second part of the private key.
[out] v - the remaining (l - 1) parts of the private key.
[out] x - the first part of the public key.
[out] y - the second part of the public key.
[out] z - the remaining (l - 1) parts of the public key.
[in] l - the number of messages to sign.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
cp_clb_sig()
int cp_clb_sig (g1_t a, g1_t * A, g1_t b, g1_t * B, g1_t c, const uint8_t * ms[], const size_t * ls, const bn_t t, const bn_t u, const bn_t * v, const size_t l)
Signs a block of messages using the CLB protocol.
Parameters
[out] a - the first component of the signature.
[out] A - the (l - 1) next components of the signature.
[out] b - the next component of the signature.
[out] B - the (l - 1) next components of the signature.
[out] c - the last component of the signature.
[in] ms - the l messages to sign.
[in] ls - the l message lengths in bytes.
[in] t - the first part of the private key.
[in] u - the second part of the private key.
[in] v - the remaining (l - 1) parts of the private key.
[in] l - the number of messages to sign.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
cp_clb_ver()
int cp_clb_ver (const g1_t a, const g1_t * A, const g1_t b, const g1_t * B, const g1_t c, const uint8_t * ms[], const size_t * ls, const g2_t x, const g2_t y, const g2_t * z, size_t l)
Verifies a block of messages signed using the CLB protocol.
Parameters
[out] a - the first component of the signature.
[out] A - the (l - 1) next components of the signature.
[out] b - the next component of the signature.
[out] B - the (l - 1) next components of the signature.
[out] c - the last component of the signature.
[in] ms - the l messages to sign.
[in] ls - the l message lengths in bytes.
[in] x - the first part of the public key.
[in] y - the second part of the public key.
[in] z - the remaining (l - 1) parts of the public key.
[in] l - the number of messages to sign.
Returns
a boolean value indicating the verification result.
cp_pss_gen()
int cp_pss_gen (bn_t u, bn_t v, g2_t g, g2_t x, g2_t y)
Generates a key pair for the Pointcheval-Sanders simple signature (PSS) protocol.
Parameters
[out] u - the first part of the private key.
[out] v - the second part of the private key.
[out] g - the first part of the public key.
[out] x - the secpmd part of the public key.
[out] y - the third part of the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_pss.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), g2_mul(), g2_rand, pc_get_ord, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_pss_sig()
int cp_pss_sig (g1_t a, g1_t b, const bn_t m, const bn_t u, const bn_t v)
Signs a message using the PSS protocol.
Parameters
[out] a - the first part of the signature.
[out] b - the second part of the signature.
[in] m - the message to sign.
[in] u - the first part of the private key.
[in] v - the second part of the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 63 of file relic_cp_pss.c.
References bn_add(), bn_free, bn_mod, bn_mul, bn_new, bn_null, g1_get_ord, g1_mul(), g1_rand, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_pss_ver()
int cp_pss_ver (const g1_t a, const g1_t b, const bn_t m, const g2_t g, const g2_t x, const g2_t y)
Verifies a signature using the PSS protocol.
Parameters
[in] a - the first part of the signature.
[in] b - the second part of the signature.
[in] m - the message to sign.
[in] g - the first part of the public key.
[in] u - the second part of the public key.
[in] v - the third part of the public key.
Returns
a boolean value indicating the verification result.
Definition at line 91 of file relic_cp_pss.c.
References ERR_CAUGHT, g1_copy, g1_free, g1_is_infty, g1_new, g1_null, g2_add, g2_copy, g2_free, g2_mul(), g2_neg, g2_new, g2_norm, g2_null, gt_free, gt_is_unity, gt_new, gt_null, pc_map_sim, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
cp_mpss_gen()
int cp_mpss_gen (bn_t r[2], bn_t s[2], g2_t g, g2_t x[2], g2_t y[2])
Generates a key pair for the multi-part version of the Pointcheval-Sanders simple signature (MPSS) protocol.
Parameters
[out] r - the first part of the private key.
[out] s - the second part of the private key.
[out] g - the first part of the public key.
[out] x - the second part of the public key.
[out] y - the third part of the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_mpss.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), g2_get_ord, g2_mul(), g2_rand, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_mpss_sig()
int cp_mpss_sig (g1_t a, g1_t b[2], const bn_t m[2], const bn_t r[2], const bn_t s[2], const mt_t mul_tri[2], const mt_t sm_tri[2])
Signs a message using the MPSS protocol operating over shares using triples.
Parameters
[out] a - the first part of the signature.
[out] b - the second part of the signature.
[in] m - the message to sign.
[in] r - the first part of the private key.
[in] s - the second part of the private key.
[in] mul_tri - the triple for the multiplication.
[in] sm_tri - the triple for the scalar multiplication.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 79 of file relic_cp_mpss.c.
References bn_add(), bn_free, bn_mod, bn_new, bn_null, g1_add, g1_get_ord, g1_mul(), g1_norm, g1_rand, mpc_mt_bct(), mpc_mt_lcl(), mpc_mt_mul(), RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_mpss_bct()
int cp_mpss_bct (g2_t x[2], g2_t y[2])
Opens public values in the MPSS protocols, in this case public keys.
Parameters
[in,out] x - the shares of the second part of the public key.
[in,out] y - the shares of the third part of the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 68 of file relic_cp_mpss.c.
References g2_add, g2_copy, g2_norm, and RLC_OK.
cp_mpss_ver()
int cp_mpss_ver (gt_t e, const g1_t a, const g1_t b[2], const bn_t m[2], const g2_t h, const g2_t x, const g2_t y, const mt_t sm_tri[2], const pt_t pc_tri[2])
Verifies a signature using the MPSS protocol operating over shares using triples.
Parameters
[out] e - the result of the verification.
[in] a - the first part of the signature.
[in] b - the second part of the signature.
[in] m - the message to sign.
[in] g - the first part of the public key.
[in] x - the second part of the public key.
[in] y - the third part of the public key.
[in] sm_tri - the triple for the scalar multiplication.
[in] pc_tri - the triple for the pairing computation.
Returns
a boolean value indicating the verification result.
Definition at line 124 of file relic_cp_mpss.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), g1_copy, g1_free, g1_get_ord, g1_is_infty, g1_neg, g1_new, g1_null, g2_add, g2_copy, g2_free, g2_mul(), g2_new, g2_norm, g2_null, gt_exp_bct(), gt_exp_lcl(), gt_exp_mpc(), gt_free, gt_mul, gt_new, gt_null, gt_rand(), pc_map_sim, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, and RLC_TRY.
cp_psb_gen()
int cp_psb_gen (bn_t r, bn_t * s, g2_t g, g2_t x, g2_t * y, size_t l)
Generates a key pair for the Pointcheval-Sanders block signature (PSB) protocol.
Parameters
[out] r - the first part of the private key.
[out] s - the second part of the private key.
[out] g - the first part of the public key.
[out] x - the secpmd part of the public key.
[out] y - the third part of the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
cp_psb_sig()
int cp_psb_sig (g1_t a, g1_t b, const bn_t * ms, const bn_t r, const bn_t * s, size_t l)
Signs a block of messages using the PSB protocol.
Parameters
[out] a - the first component of the signature.
[out] b - the second component of the signature.
[in] ms - the l messages to sign.
[in] r - the first part of the private key.
[in] s - the remaining l part of the private key.
[in] l - the number of messages to sign.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
cp_psb_ver()
int cp_psb_ver (const g1_t a, const g1_t b, const bn_t * ms, const g2_t g, const g2_t x, const g2_t * y, size_t l)
Verifies a block of messages signed using the PSB protocol.
Parameters
[out] a - the first component of the signature.
[out] b - the seconed component of the signature.
[in] ms - the l messages to sign.
[in] g - the first part of the public key.
[in] x - the second part of the public key.
[in] y - the remaining l parts of the public key.
[in] l - the number of messages to sign.
Returns
a boolean value indicating the verification result.
cp_mpsb_gen()
int cp_mpsb_gen (bn_t r[2], bn_t s[][2], g2_t h, g2_t x[2], g2_t y[][2], size_t l)
Generates a key pair for the multi-part version of the Pointcheval-Sanders simple signature (MPSS) protocol.
Parameters
[out] r - the first part of the private key.
[out] s - the second part of the private key.
[out] g - the first part of the public key.
[out] x - the second part of the public key.
[out] y - the third part of the public key.
[in] l - the number of messages to sign.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 213 of file relic_cp_mpss.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), g2_get_ord, g2_mul(), g2_rand, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_mpsb_sig()
int cp_mpsb_sig (g1_t a, g1_t b[2], const bn_t m[][2], const bn_t r[2], const bn_t s[][2], const mt_t mul_tri[2], const mt_t sm_tri[2], size_t l)
Signs a message using the MPSS protocol operating over shares using triples.
Parameters
[out] a - the first part of the signature.
[out] b - the second part of the signature.
[in] m - the messages to sign.
[in] r - the first part of the private key.
[in] s - the second parts of the private key.
[in] mul_tri - the triple for the multiplication.
[in] sm_tri - the triple for the scalar multiplication.
[in] l - the number of messages to sign.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 259 of file relic_cp_mpss.c.
References bn_add(), bn_free, bn_mod, bn_mul, bn_new, bn_null, bn_rand_mod(), bn_sign(), bn_sub(), bn_zero(), g1_add, g1_get_ord, g1_mul(), g1_norm, g1_rand, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_NEG, RLC_OK, and RLC_TRY.
cp_mpsb_bct()
int cp_mpsb_bct (g2_t x[2], g2_t y[][2], size_t l)
Opens public values in the MPSS protocols, in this case public keys.
Parameters
[in,out] x - the shares of the second part of the public key.
[in,out] y - the shares of the third part of the public key.
[in] l - the number of messages to sign.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 246 of file relic_cp_mpss.c.
References g2_add, g2_copy, g2_norm, and RLC_OK.
cp_mpsb_ver()
int cp_mpsb_ver (gt_t e, const g1_t a, const g1_t b[2], const bn_t m[][2], const g2_t h, const g2_t x, const g2_t y[][2], const bn_t v[][2], const mt_t sm_tri[2], const pt_t pc_tri[2], size_t l)
Verifies a signature using the MPSS protocol operating over shares using triples.
Parameters
[out] e - the result of the verification.
[in] a - the first part of the signature.
[in] b - the second part of the signature.
[in] m - the messages to sign.
[in] g - the first part of the public key.
[in] x - the second part of the public key.
[in] y - the third parts of the public key.
[in] sm_tri - the triple for the scalar multiplication.
[in] pc_tri - the triple for the pairing computation.
[in] v - the private keys, can be NULL.
[in] l - the number of messages to sign.
Returns
a boolean value indicating the verification result.
Definition at line 319 of file relic_cp_mpss.c.
References bn_add(), bn_copy(), bn_free, bn_mod, bn_mul, bn_new, bn_null, bn_rand_mod(), bn_sign(), bn_sub(), bn_zero(), ERR_NO_MEMORY, g1_copy, g1_free, g1_get_ord, g1_is_infty, g1_neg, g1_new, g1_null, g2_add, g2_copy, g2_free, g2_mul(), g2_mul_sim_lot, g2_new, g2_norm, g2_null, gt_exp_bct(), gt_exp_lcl(), gt_exp_mpc(), gt_free, gt_mul, gt_new, gt_null, gt_rand(), pc_map_sim, RLC_ALLOCA, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.
cp_zss_gen()
int cp_zss_gen (bn_t d, g1_t q, gt_t z)
Generates a Zhang-Safavi-Naini-Susilo (ZSS) key pair.
Parameters
[out] d - the private key.
[out] q - the first component of the public key.
[out] z - the second component of the public key.
Definition at line 38 of file relic_cp_zss.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), g1_mul_gen(), gt_get_gen(), pc_get_ord, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_zss_sig()
int cp_zss_sig (g2_t s, const uint8_t * msg, size_t len, int hash, const bn_t d)
Signs a message using ZSS scheme.
Parameters
[out] s - the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] hash - the flag to indicate the message format.
[in] d - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 64 of file relic_cp_zss.c.
References bn_add(), bn_free, bn_mod, bn_mod_inv(), bn_new, bn_null, bn_read_bin(), g2_mul_gen(), md_map, pc_get_ord, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_MD_LEN, RLC_OK, and RLC_TRY.
cp_zss_ver()
int cp_zss_ver (const g2_t s, const uint8_t * msg, size_t len, int hash, const g1_t q, const gt_t z)
Verifies a message signed with ZSS scheme.
Parameters
[in] s - the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] hash - the flag to indicate the message format.
[out] q - the first component of the public key.
[out] z - the second component of the public key.
Returns
a boolean value indicating the verification result.
Definition at line 111 of file relic_cp_zss.c.
References bn_free, bn_mod, bn_new, bn_null, bn_read_bin(), ERR_CAUGHT, g1_add, g1_free, g1_mul_gen(), g1_new, g1_norm, g1_null, gt_cmp, gt_free, gt_new, gt_null, md_map, pc_get_ord, pc_map, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_MD_LEN, RLC_THROW, and RLC_TRY.
cp_vbnn_gen()
int cp_vbnn_gen (bn_t msk, ec_t mpk)
Generates a vBNN-IBS key generation center (KGC).
Parameters
[out] msk - the KGC master key.
[out] mpk - the KGC public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 41 of file relic_cp_vbnn.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), ec_curve_get_ord, ec_mul_gen, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_vbnn_gen_prv()
int cp_vbnn_gen_prv (bn_t sk, ec_t pk, const bn_t msk, const uint8_t * id, size_t id_len)
Extract a user key from an identity and a vBNN-IBS key generation center.
Parameters
[out] sk - the extracted vBNN-IBS user private key.
[out] pk - the extracted vBNN-IBS user public key.
[in] msk - the KGC master key.
[in] id - the identity used for extraction.
[in] id_len - the identity length in bytes.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 73 of file relic_cp_vbnn.c.
References bn_add(), bn_free, bn_mod, bn_mul, bn_new, bn_null, bn_rand_mod(), bn_read_bin(), ec_curve_get_ord, ec_mul_gen, ec_size_bin, ec_write_bin, ERR_NO_MEMORY, md_map, RLC_ALLOCA, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_FREE, RLC_MD_LEN, RLC_OK, RLC_THROW, and RLC_TRY.
cp_vbnn_sig()
int cp_vbnn_sig (ec_t r, bn_t z, bn_t h, const uint8_t * id, size_t id_len, const uint8_t * msg, int msg_len, const bn_t sk, const ec_t pk)
Signs a message using the vBNN-IBS scheme.
Parameters
[out] r - the R value of the signature.
[out] z - the z value of the signature.
[out] h - the h value of the signature.
[in] id - the identity buffer.
[in] id_len - the size of identity buffer.
[in] msg - the message buffer to sign.
[in] msg_len - the size of message buffer.
[in] sk - the signer private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 127 of file relic_cp_vbnn.c.
References bn_add(), bn_free, bn_mod, bn_mul, bn_new, bn_null, bn_rand_mod(), bn_read_bin(), ec_copy, ec_curve_get_ord, ec_free, ec_mul_gen, ec_new, ec_null, ec_size_bin, ec_write_bin, ERR_NO_MEMORY, md_map, RLC_ALLOCA, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_FREE, RLC_MD_LEN, RLC_OK, RLC_THROW, and RLC_TRY.
cp_vbnn_ver()
int cp_vbnn_ver (const ec_t r, const bn_t z, const bn_t h, const uint8_t * id, size_t id_len, const uint8_t * msg, int msg_len, const ec_t mpk)
Verifies a signature and message using the vBNN-IBS scheme.
Parameters
[in] r - the R value of the signature.
[in] z - the z value of the signature.
[in] h - the h value of the signature.
[in] id - the identity buffer.
[in] id_len - the size of identity buffer.
[in] msg - the message buffer to sign.
[in] msg_len - the size of message buffer.
[in] mpk - the master public key of the generation center.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 192 of file relic_cp_vbnn.c.
References bn_cmp(), bn_free, bn_mod, bn_new, bn_null, bn_read_bin(), ec_add, ec_curve_get_ord, ec_free, ec_mul, ec_mul_gen, ec_new, ec_norm, ec_null, ec_size_bin, ec_sub, ec_write_bin, ERR_CAUGHT, ERR_NO_MEMORY, md_map, RLC_ALLOCA, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FREE, RLC_MD_LEN, RLC_THROW, and RLC_TRY.
cp_pokdl_prv()
int cp_pokdl_prv (bn_t c, bn_t r, const ec_t y, const bn_t x)
Computes the proof of knowledge of a discrete logarithm of an elliptic curve point to a generator. Proves that y = [x]G.
Parameters
[out] c - the challenge.
[out] r - the response.
[in] y - the elliptic curve point
[in] x - the discrete logarithm to prove.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 43 of file relic_cp_pok.c.
References bn_free, bn_mod, bn_mul, bn_new, bn_null, bn_rand_mod(), bn_read_bin(), bn_sub(), ec_curve_get_gen, ec_curve_get_ord, ec_free, ec_mul_gen, ec_new, ec_null, ec_size_bin, ec_write_bin, md_map, RLC_CATCH_ANY, RLC_ERR, RLC_FC_BYTES, RLC_FINALLY, RLC_MD_LEN, RLC_OK, and RLC_TRY.
cp_pokdl_ver()
int cp_pokdl_ver (const bn_t c, const bn_t r, const ec_t y)
Verifies the proof of knowledge of a discrete logarithm of an elliptic curve point to a generator. Verifies that y = [x]G.
Parameters
[in] c - the challenge.
[in] r - the response.
[in] y - the elliptic curve point.
Returns
a boolean value indicating the verification result.
Definition at line 90 of file relic_cp_pok.c.
References bn_cmp(), bn_free, bn_mod, bn_new, bn_null, bn_read_bin(), ec_curve_get_gen, ec_curve_get_ord, ec_free, ec_mul_sim_gen, ec_new, ec_null, ec_size_bin, ec_write_bin, md_map, RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FC_BYTES, RLC_FINALLY, RLC_MD_LEN, and RLC_TRY.
cp_pokor_prv()
int cp_pokor_prv (bn_t c[2], bn_t r[2], const ec_t y[2], const bn_t x)
Computes the proof of knowledge of a discrete logarithm of an elliptic curve point to a generator. Proves that y0 = [x]G or y[1] = [x]G.
Parameters
[out] c - the challenges.
[out] r - the responses.
[in] y - the elliptic curve points.
[in] x - the discrete logarithm to prove.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 137 of file relic_cp_pok.c.
References bn_copy(), bn_free, bn_mod, bn_mul, bn_new, bn_null, bn_rand_mod(), bn_read_bin(), bn_sub(), ec_curve_get_gen, ec_curve_get_ord, ec_free, ec_mul_gen, ec_mul_sim_gen, ec_new, ec_null, ec_size_bin, ec_write_bin, md_map, RLC_CATCH_ANY, RLC_ERR, RLC_FC_BYTES, RLC_FINALLY, RLC_MD_LEN, RLC_OK, and RLC_TRY.
cp_pokor_ver()
int cp_pokor_ver (const bn_t c[2], const bn_t r[2], const ec_t y[2])
Verifies the proof of knowledge of a discrete logarithm of an elliptic curve point to a generator. Verifies that y = [x]G.
Parameters
[in] c - the challenges.
[in] r - the responses.
[in] y - the elliptic curve points.
Returns
a boolean value indicating the verification result.
Definition at line 206 of file relic_cp_pok.c.
References bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, bn_read_bin(), bn_sub(), ec_curve_get_gen, ec_curve_get_ord, ec_free, ec_mul_sim_gen, ec_new, ec_null, ec_size_bin, ec_write_bin, md_map, RLC_CATCH_ANY, RLC_ERR, RLC_FC_BYTES, RLC_FINALLY, RLC_MD_LEN, and RLC_TRY.
cp_sokdl_sig()
int cp_sokdl_sig (bn_t c, bn_t r, const uint8_t * msg, size_t len, const ec_t y, const bn_t x)
Computes the proof of knowledge of a discrete logarithm of an elliptic curve point to a generator. Proves that y = [x]G.
Parameters
[out] c - the challenge.
[out] r - the response.
[in] msg - the message to sign.
[in] len - the length of the message.
[in] y - the elliptic curve point
[in] x - the discrete logarithm to prove.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 43 of file relic_cp_sok.c.
References bn_free, bn_mod, bn_mul, bn_new, bn_null, bn_rand_mod(), bn_read_bin(), bn_sub(), ec_curve_get_gen, ec_curve_get_ord, ec_free, ec_mul_gen, ec_new, ec_null, ec_size_bin, ec_write_bin, ERR_NO_MEMORY, md_map, RLC_ALLOCA, RLC_CATCH_ANY, RLC_ERR, RLC_FC_BYTES, RLC_FINALLY, RLC_FREE, RLC_MD_LEN, RLC_OK, RLC_THROW, and RLC_TRY.
cp_sokdl_ver()
int cp_sokdl_ver (const bn_t c, const bn_t r, const uint8_t * msg, size_t len, const ec_t y)
Verifies the proof of knowledge of a discrete logarithm of an elliptic curve point to a generator. Verifies that y = [x]G.
Parameters
[in] c - the challenge.
[in] r - the response.
[in] msg - the message to sign.
[in] len - the length of the message.
[in] y - the elliptic curve point.
Returns
a boolean value indicating the verification result.
Definition at line 101 of file relic_cp_sok.c.
References bn_cmp(), bn_free, bn_mod, bn_new, bn_null, bn_read_bin(), ec_curve_get_gen, ec_curve_get_ord, ec_free, ec_mul_sim_gen, ec_new, ec_null, ec_size_bin, ec_write_bin, ERR_NO_MEMORY, md_map, RLC_ALLOCA, RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FC_BYTES, RLC_FINALLY, RLC_FREE, RLC_MD_LEN, RLC_THROW, and RLC_TRY.
cp_sokor_sig()
int cp_sokor_sig (bn_t c[2], bn_t r[2], const uint8_t * msg, size_t len, const ec_t y[2], const ec_t g[2], const bn_t x, int first)
Computes the proof of knowledge of a discrete logarithm of an elliptic curve point to a generator. Proves that y0 = [x]G or y1 = [x]G.
Parameters
[out] c - the challenges.
[out] r - the responses.
[in] msg - the message to sign.
[in] len - the length of the message.
[in] y - the elliptic curve points.
[in] g - the elliptic curve generators.
[in] x - the discrete logarithm to prove.
[in] first - the flag to indicate the point for which the discrete logarithm is known.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 158 of file relic_cp_sok.c.
References bn_copy(), bn_free, bn_mod, bn_mul, bn_new, bn_null, bn_rand_mod(), bn_read_bin(), bn_sub(), ec_copy, ec_curve_get_gen, ec_curve_get_ord, ec_free, ec_mul, ec_mul_gen, ec_mul_sim, ec_mul_sim_gen, ec_new, ec_null, ec_size_bin, ec_write_bin, ERR_NO_MEMORY, md_map, RLC_ALLOCA, RLC_CATCH_ANY, RLC_ERR, RLC_FC_BYTES, RLC_FINALLY, RLC_FREE, RLC_MD_LEN, RLC_OK, RLC_THROW, and RLC_TRY.
Referenced by cp_ers_ext(), cp_ers_sig(), cp_etrs_ext(), cp_etrs_sig(), cp_etrs_uni(), cp_smlers_ext(), and cp_smlers_sig().
cp_sokor_ver()
int cp_sokor_ver (const bn_t c[2], const bn_t r[2], const uint8_t * msg, size_t len, const ec_t y[2], const ec_t g[2])
Verifies the proof of knowledge of a discrete logarithm of an elliptic curve point to a generator. Verifies that y = [x]G.
Parameters
[in] c - the challenges.
[in] r - the responses.
[in] msg - the message to sign.
[in] len - the length of the message.
[in] y - the elliptic curve points.
[in] g - the elliptic curve generators.
Returns
a boolean value indicating the verification result.
Definition at line 261 of file relic_cp_sok.c.
References bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, bn_read_bin(), bn_sub(), ec_copy, ec_curve_get_gen, ec_curve_get_ord, ec_free, ec_mul_sim, ec_mul_sim_gen, ec_new, ec_null, ec_size_bin, ec_write_bin, ERR_NO_MEMORY, md_map, RLC_ALLOCA, RLC_CATCH_ANY, RLC_ERR, RLC_FC_BYTES, RLC_FINALLY, RLC_FREE, RLC_MD_LEN, RLC_THROW, and RLC_TRY.
Referenced by cp_ers_ver(), cp_etrs_ver(), and cp_smlers_ver().
cp_ers_gen()
int cp_ers_gen (ec_t pp)
Generates the public parameters of the extendable ring signature.
@aram[out] pp - the public parameters.
Definition at line 38 of file relic_cp_ers.c.
References ec_rand, and RLC_OK.
cp_ers_gen_key()
int cp_ers_gen_key (bn_t sk, ec_t pk)
Generates a key pair for the extendable ring signature.
@aram[out] sk - the private key.
Parameters
[out] pk - the public key.
Definition at line 43 of file relic_cp_ers.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), ec_curve_get_ord, ec_mul_gen, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_ers_sig()
int cp_ers_sig (bn_t td, ers_t p, const uint8_t * msg, size_t len, const bn_t sk, const ec_t pk, const ec_t pp)
Signs a message using the extendable ring signature scheme.
Parameters
[out] td - the signature trapdoor.
[out] p - the resulting signature.
[in] msg - the message to sign.
[in] len - the message length.
[in] sk - the signer's private key.
[in] pk - the singer's public key.
[in] pp - the public parameters.
Definition at line 65 of file relic_cp_ers.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), cp_sokor_sig(), ec_copy, ec_curve_get_ord, ec_free, ec_mul_gen, ec_new, ec_norm, ec_null, ec_sub, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
Referenced by cp_smlers_sig().
cp_ers_ver()
int cp_ers_ver (const bn_t td, const ers_t * s, size_t size, const uint8_t * msg, size_t len, const ec_t pp)
Verifies an extendable ring signature scheme over some messages.
Parameters
[in] td - the signature trapdoor.
[in] s
the ring of signatures.
[in] size - the number of signatures in the ring.
[in] msg - the message to sign.
[in] len - the message length.
[in] pp - the public parameters.
Definition at line 105 of file relic_cp_ers.c.
References bn_free, bn_new, bn_null, cp_sokor_ver(), ec_add, ec_cmp, ec_copy, ec_curve_get_ord, ec_free, ec_mul_gen, ec_new, ec_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
cp_ers_ext()
int cp_ers_ext (bn_t td, ers_t * p, size_t * size, const uint8_t * msg, size_t len, const ec_t pk, const ec_t pp)
Extends an extendable ring signature with a new signature.
Parameters
[out] td - the signature trapdoor.
[in] p - the ring of signatures.
[in] size - the number of signatures in the ring.
[in] msg - the message to sign.
[in] len - the message length.
[in] pk - the singer's public key.
[in] pp - the public parameters.
Definition at line 150 of file relic_cp_ers.c.
References bn_free, bn_mod, bn_new, bn_null, bn_rand_mod(), bn_sub(), cp_sokor_sig(), ec_cmp, ec_copy, ec_curve_get_ord, ec_free, ec_mul_gen, ec_new, ec_null, RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_smlers_sig()
int cp_smlers_sig (bn_t td, smlers_t p, const uint8_t * msg, size_t len, const bn_t sk, const ec_t pk, const ec_t pp)
Signs a message using the same-message linkable extendable ring signature scheme.
Parameters
[out] td - the signature trapdoor.
[out] p - the resulting signature.
[in] msg - the message to sign.
[in] len - the message length.
[in] sk - the signer's private key.
[in] pk - the singer's public key.
[in] pp - the public parameters.
Definition at line 38 of file relic_cp_smlers.c.
References cp_ers_sig(), cp_sokor_sig(), ec_copy, ec_curve_get_gen, ec_free, ec_map, ec_mul, ec_new, ec_null, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_smlers_ver()
int cp_smlers_ver (bn_t td, smlers_t * s, size_t size, const uint8_t * msg, size_t len, const ec_t pp)
Verifies a same-message linkable extendable ring signature.
Parameters
[in] td - the signature trapdoor.
[in] s - the ring of signatures.
[in] size - the number of signatures in the ring.
[in] msg - the message to sign.
[in] len - the message length.
[in] pp - the public parameters.
Definition at line 76 of file relic_cp_smlers.c.
References bn_free, bn_new, bn_null, cp_sokor_ver(), ec_add, ec_cmp, ec_copy, ec_curve_get_gen, ec_curve_get_ord, ec_free, ec_map, ec_mul_gen, ec_new, ec_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
cp_smlers_ext()
int cp_smlers_ext (bn_t td, smlers_t * p, size_t * size, const uint8_t * msg, size_t len, const ec_t pk, const ec_t pp)
Extends a same-message extendable ring signature with a new signature.
Parameters
[out] td - the signature trapdoor.
[in] p - the ring of signatures.
[in] size - the number of signatures in the ring.
[in] msg - the message to sign.
[in] len - the message length.
[in] pk - the singer's public key.
[in] pp - the public parameters.
Definition at line 132 of file relic_cp_smlers.c.
References bn_free, bn_mod, bn_new, bn_null, bn_rand_mod(), bn_sub(), cp_sokor_sig(), ec_cmp, ec_copy, ec_curve_get_gen, ec_curve_get_ord, ec_free, ec_map, ec_mul_gen, ec_new, ec_null, RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_etrs_sig()
int cp_etrs_sig (bn_t * td, bn_t * y, size_t max, etrs_t p, const uint8_t * msg, size_t len, const bn_t sk, const ec_t pk, const ec_t pp)
Signs a message using the extendable threshold ring signature scheme.
Parameters
[out] td - the signature trapdoors.
[out] y - the signature randomness.
[out] max - the maximum number of extensions.
[out] p - the resulting signature.
[in] msg - the message to sign.
[in] len - the message length.
[in] sk - the signer's private key.
[in] pk - the singer's public key.
[in] pp - the public parametetrs.
Definition at line 38 of file relic_cp_etrs.c.
References bn_add(), bn_copy(), bn_free, bn_mod, bn_mod_inv_sim(), bn_mul, bn_new, bn_null, bn_rand_mod(), bn_set_dig(), bn_sub(), bn_zero(), cp_sokor_sig(), ec_copy, ec_curve_get_ord, ec_free, ec_mul, ec_mul_sim_gen, ec_new, ec_null, ERR_NO_MEMORY, RLC_ALLOCA, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_FREE, RLC_OK, RLC_THROW, and RLC_TRY.
cp_etrs_ver()
int cp_etrs_ver (size_t thres, const bn_t * td, const bn_t * y, size_t max, const etrs_t * s, size_t size, const uint8_t * msg, size_t len, const ec_t pp)
Verifies an extendable threshold ring signature scheme over some messages.
Parameters
[in] thres - the specified threshold.
[in] td - the signature trapdoors.
[in] y - the signature randomness.
[in] max - the maximum number of extensions.
[in] s - the ring of signatures.
[in] size - the number of signatures in the ring.
[in] msg - the message to sign.
[in] len - the message length.
[in] pp - the public parametetrs.
Definition at line 143 of file relic_cp_etrs.c.
References bn_copy(), bn_free, bn_mod, bn_mod_inv_sim(), bn_mul, bn_new, bn_null, bn_set_dig(), bn_sub(), cp_sokor_ver(), ec_cmp, ec_copy, ec_curve_get_ord, ec_free, ec_mul_gen, ec_mul_sim_lot, ec_new, ec_null, ec_set_infty, ERR_CAUGHT, ERR_NO_MEMORY, RLC_ALLOCA, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
cp_etrs_ext()
int cp_etrs_ext (bn_t * td, bn_t * y, size_t max, etrs_t * p, size_t * size, const uint8_t * msg, size_t len, const ec_t pk, const ec_t pp)
Extends an extendable threshold ring signature with a new signature.
Parameters
[out] td - the signature trapdoors.
[in] y - the signature randomness.
[in] max - the maximum number of extensions.
[in] p - the ring of signatures.
[in] size - the number of signatures in the ring.
[in] msg - the message to sign.
[in] len - the message length.
[in] pk - the singer's public key.
[in] pp - the public parametetrs.
Definition at line 245 of file relic_cp_etrs.c.
References bn_copy(), bn_free, bn_is_zero(), bn_new, bn_null, bn_zero(), cp_sokor_sig(), ec_cmp, ec_copy, ec_curve_get_ord, ec_free, ec_mul_gen, ec_new, ec_null, RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_etrs_uni()
int cp_etrs_uni (int thres, bn_t * td, bn_t * y, int max, etrs_t * p, size_t * size, const uint8_t * msg, size_t len, const bn_t sk, const ec_t pk, const ec_t pp)
Joins an extendable threshold ring signature with a new signature.
Parameters
[in] thres - the specified threshold.
[in] td - the signature trapdoors.
[in] y - the signature randomness.
[in] max - the maximum number of extensions.
[in] p - the ring of signatures.
[in] size - the number of signatures in the ring.
[in] msg - the message to sign.
[in] len - the message length.
[in] sk - the signer's private key.
[in] pk - the singer's public key.
[in] pp - the public parametetrs.
Definition at line 301 of file relic_cp_etrs.c.
References bn_copy(), bn_free, bn_mod, bn_mod_inv_sim(), bn_mul, bn_new, bn_null, bn_rand_mod(), bn_set_dig(), bn_sub(), cp_sokor_sig(), ec_add, ec_copy, ec_curve_get_ord, ec_free, ec_mul, ec_mul_gen, ec_new, ec_norm, ec_null, ec_set_infty, ERR_CAUGHT, ERR_NO_MEMORY, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_OK, RLC_THROW, and RLC_TRY.
cp_cmlhs_init()
int cp_cmlhs_init (g1_t h)
Initialize the Context-hiding Multi-key Homomorphic Signature scheme (CMLHS). The scheme due to Schabhuser et al. signs a vector of messages.
Parameters
[out] h - the random element (message as one component).
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_cmlhs.c.
References g1_rand, and RLC_OK.
cp_cmlhs_gen()
int cp_cmlhs_gen (bn_t * x, gt_t * hs, size_t len, uint8_t * prf, size_t plen, bn_t sk, g2_t pk, bn_t d, g2_t y, int bls)
Generates a key pair for the CMLHS scheme using BLS as underlying signature.
Parameters
[out] x - the exponent values, one per label.
[out] hs - the hash values, one per label.
[in] len - the number of possible labels.
[out] prf - the key for the pseudo-random function (PRF).
[out] plen - the PRF key length.
[out] sk - the private key for the BLS signature scheme.
[out] pk - the public key for the BLS signature scheme.
[out] d - the secret exponent.
[out] y - the corresponding public element.
[in] bls - the flag for selecting BLS or ECDSA.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
cp_cmlhs_sig()
int cp_cmlhs_sig (g1_t sig, g2_t z, g1_t a, g1_t c, g1_t r, g2_t s, const bn_t msg, const char * data, int label, const bn_t x, const g1_t h, const uint8_t * prf, size_t plen, const bn_t sk, const bn_t d, int bls)
Signs a message vector using the CMLHS.
Parameters
[out] sig - the resulting BLS signature.
[out] z - the power of the output of the PRF.
[out] a - the first component of the signature.
[out] c - the second component of the signature.
[out] r - the third component of the signature.
[out] s - the fourth component of the signature.
[in] msg - the message vector to sign (one component).
[in] data - the dataset identifier.
[in] label - the integer label.
[in] x - the exponent value for the label.
[in] h - the random value (message has one component).
[in] prf - the key for the pseudo-random function (PRF).
[in] plen - the PRF key length.
[in] sk - the private key for the signature scheme.
[in] d - the secret exponent.
[in] bls - the flag for selecting BLS or ECDSA.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
cp_cmlhs_fun()
int cp_cmlhs_fun (g1_t a, g1_t c, const g1_t as[], const g1_t cs[], const dig_t * f, size_t len)
Applies a function over a set of CMLHS signatures from the same user.
Parameters
[out] a - the resulting first component of the signature.
[out] c - the resulting second component of the signature.
[in] as - the vector of first components of the signatures.
[in] cs - the vector of second components of the signatures.
[in] f - the linear coefficients in the function.
[in] len - the number of coefficients.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
cp_cmlhs_evl()
int cp_cmlhs_evl (g1_t r, g2_t s, const g1_t rs[], const g2_t ss[], const dig_t * f, size_t len)
Evaluates a function over a set of CMLHS signatures.
Parameters
[out] r - the resulting third component of the signature.
[out] s - the resulting fourth component of the signature.
[in] rs - the vector of third components of the signatures.
[in] ss - the vector of fourth components of the signatures.
[in] f - the linear coefficients in the function.
[in] len - the number of coefficients.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
cp_cmlhs_ver()
int cp_cmlhs_ver (const g1_t r, const g2_t s, const g1_t * sig, const g2_t * z, const g1_t * a, const g1_t * c, const bn_t m, const char * data, const g1_t h, const int * label, const gt_t * hs[], const dig_t * f[], const size_t * flen, const g2_t * y, const g2_t * pk, size_t slen, int bls)
Verifies a CMLHS signature over a set of messages.
Parameters
[in] r - the first component of the homomorphic signature.
[in] s - the second component of the homomorphic signature.
[in] sig - the BLS signatures.
[in] z - the powers of the outputs of the PRF.
[in] a - the vector of first components of the signatures.
[in] c - the vector of second components of the signatures.
[in] msg - the combined message.
[in] data - the dataset identifier.
[in] h - the random element (message has one component).
[in] label - the integer labels.
[in] hs - the hash values, one per label.
[in] f - the linear coefficients in the function.
[in] flen - the number of coefficients.
[in] y - the public elements of the users.
[in] pk - the public keys of the users.
[in] slen - the number of signatures.
[in] bls - the flag for selecting BLS or ECDSA.
Returns
a boolean value indicating the verification result.
Definition at line 209 of file relic_cp_cmlhs.c.
References bn_free, bn_new, bn_null, cp_bls_ver(), cp_ecdsa_ver(), ERR_CAUGHT, ERR_NO_MEMORY, fp_prime_back(), fp_set_dig(), g1_add, g1_free, g1_get_gen, g1_mul(), g1_new, g1_norm, g1_null, g1_set_g2, g1_set_infty, g2_free, g2_get_gen, g2_new, g2_null, g2_size_bin, g2_write_bin, gt_cmp, gt_exp_dig(), gt_free, gt_mul, gt_new, gt_null, pc_get_ord, pc_map, pc_map_sim, RLC_ALLOCA, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
cp_cmlhs_off()
void cp_cmlhs_off (gt_t vk, const g1_t h, const int * label, const gt_t * hs[], const dig_t * f[], const size_t * flen, size_t slen)
Perform the offline verification of a CMLHS signature over a set of messages.
Parameters
[out] vk - the verification key.
[in] h - the random element (message has one component).
[in] label - the integer labels.
[in] hs - the hash values, one per label.
[in] f - the linear coefficients in the function.
[in] flen - the number of coefficients.
[in] y - the public elements of the users.
[in] pk - the public keys of the users.
[in] slen - the number of signatures.
Returns
a boolean value indicating the verification result.
cp_cmlhs_onv()
int cp_cmlhs_onv (const g1_t r, const g2_t s, const g1_t * sig, const g2_t * z, const g1_t * a, const g1_t * c, const bn_t msg, const char * data, const g1_t h, const gt_t vk, const g2_t * y, const g2_t * pk, size_t slen, int bls)
Perform the online verification of a CMLHS signature over a set of messages.
Parameters
[in] r - the first component of the homomorphic signature.
[in] s - the second component of the homomorphic signature.
[in] sig - the BLS signatures.
[in] z - the powers of the outputs of the PRF.
[in] a - the vector of first components of the signatures.
[in] c - the vector of second components of the signatures.
[in] msg - the combined message.
[in] data - the dataset identifier.
[in] h - the random element (message has one component).
[in] vk - the verification key.
[in] bls - the flag for selecting BLS or ECDSA.
Returns
a boolean value indicating the verification result.
cp_mklhs_gen()
int cp_mklhs_gen (bn_t sk, g2_t pk)
Generates a key pair for the Multi-Key Homomorphic Signature (MKLHS) scheme.
Parameters
[out] sk - the private key for the signature scheme.
[out] pk - the public key for the signature scheme.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_mklhs.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), g2_mul_gen(), pc_get_ord, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_mklhs_sig()
int cp_mklhs_sig (g1_t s, const bn_t m, const char * data, const char * id, const char * tag, const bn_t sk)
Signs a message using the MKLHS.
Parameters
[out] s - the resulting signature.
[in] m - the message to sign.
[in] data - the dataset identifier.
[in] id - the identity.
[in] tag - the tag.
[in] sk - the private key for the signature scheme.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 60 of file relic_cp_mklhs.c.
References bn_free, bn_new, bn_null, ERR_NO_MEMORY, g1_add, g1_free, g1_map, g1_mul_gen(), g1_mul_sec, g1_new, g1_norm, g1_null, pc_get_ord, RLC_ALLOCA, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_FREE, RLC_MAX, RLC_OK, RLC_THROW, and RLC_TRY.
cp_mklhs_fun()
int cp_mklhs_fun (bn_t mu, const bn_t * m, const dig_t * f, size_t len)
Applies a function over a set of messages from the same user.
Parameters
[out] mu - the combined message.
[in] m - the vector of individual messages.
[in] f - the linear coefficients in the function.
[in] len - the number of coefficients.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
cp_mklhs_evl()
int cp_mklhs_evl (g1_t sig, const g1_t * s, const dig_t * f, size_t len)
Evaluates a function over a set of MKLHS signatures.
Parameters
[out] sig - the resulting signature.
[in] s - the set of signatures.
[in] f - the linear coefficients in the function.
[in] len - the number of coefficients.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
cp_mklhs_ver()
int cp_mklhs_ver (const g1_t sig, const bn_t m, const bn_t * mu, const char * data, const char * id[], const char * tag[], const dig_t * f[], const size_t * flen, const g2_t * pk, size_t slen)
Verifies a MKLHS signature over a set of messages.
Parameters
[in] sig - the homomorphic signature to verify.
[in] m - the signed message.
[in] mu - the vector of signed messages per user.
[in] data - the dataset identifier.
[in] id - the vector of identities.
[in] tag - the vector of tags.
[in] f - the linear coefficients in the function.
[in] flen - the number of coefficients.
[in] pk - the public keys of the users.
[in] slen - the number of signatures.
Returns
a boolean value indicating the verification result.
cp_mklhs_off()
int cp_mklhs_off (g1_t * h, dig_t * ft, const char * id[], const char * tag[], const dig_t * f[], const size_t * flen, size_t slen)
Computes the offline part of veryfying a MKLHS signature over a set of messages.
Parameters
[out] h - the hashes of labels
[out] ft - the precomputed linear coefficients.
[in] id - the vector of identities.
[in] tag - the vector of tags.
[in] f - the linear coefficients in the function.
[in] flen - the number of coefficients.
[in] slen - the number of signatures.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
cp_mklhs_onv()
int cp_mklhs_onv (const g1_t sig, const bn_t m, const bn_t * mu, const char * data, const char * id[], const g1_t * h, const dig_t * ft, const g2_t * pk, size_t slen)
Computes the online part of veryfying a MKLHS signature over a set of messages.
Parameters
[in] sig - the homomorphic signature to verify.
[in] m - the signed message.
[in] mu - the vector of signed messages per user.
[in] data - the dataset identifier.
[in] id - the vector of identities.
[in] d - the hashes of labels.
[in] ft - the precomputed linear coefficients.
[in] pk - the public keys of the users.
[in] slen - the number of signatures.
Returns
a boolean value indicating the verification result.
cp_rsapsi_gen()
int cp_rsapsi_gen (bn_t g, bn_t n, size_t bits)
Generates the trusted setup parameters for the factoring-based laconic Private Set Intersection (RSA-PSI) protocol.
Parameters
[out] g - the generator.
[out] n - the modulus.
[in] bits - the precision in bits.
Definition at line 47 of file relic_cp_rsapsi.c.
References bn_cmp(), bn_cmp_dig(), bn_free, bn_gcd, bn_gen_prime, bn_mul, bn_new, bn_null, bn_rand_mod(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_OK, RLC_THROW, and RLC_TRY.
cp_rsapsi_ask()
int cp_rsapsi_ask (bn_t d, bn_t r, bn_t * p, const bn_t g, const bn_t n, const bn_t * x, size_t m)
Computes the receiver part of the RSA-PSI protocol, given its input set.
Parameters
[out] d - the resulting accumulator.
[out] r - the random nonce.
[out] p - the mapping of elements to prime numbers.
[in] g - the generator given by the trusted setup.
[in] n - the modulus given by the trusted setup.
[in] x - the receiver's input set.
[in] m - the receiver's input set size.
Definition at line 80 of file relic_cp_rsapsi.c.
References bn_add_dig(), bn_is_even(), bn_is_prime(), bn_mxp, bn_rand_mod(), bn_read_bin(), bn_write_bin(), md_map, RLC_BN_BITS, RLC_CEIL, RLC_MD_LEN, RLC_OK, and STAT_SEC.
cp_rsapsi_ans()
int cp_rsapsi_ans (bn_t * t, bn_t * u, const bn_t d, const bn_t g, const bn_t n, const bn_t * y, size_t l)
Computes the sender part of the RSA-PSI protocol, given its input set.
Parameters
[out] t - the accumulator results.
[out] u - the missing elements in the exponent.
[in] d - the receiver's accumulator.
[in] g - the generator given by the trusted setup.
[in] n - the modulus given by the trusted setup.
[in] y - the server's input set.
[in] l - the sender's input set size.
cp_rsapsi_int()
int cp_rsapsi_int (bn_t * z, size_t * len, const bn_t r, const bn_t * p, const bn_t n, const bn_t * x, const size_t m, const bn_t * t, const bn_t * u, size_t l)
Computes the intersection as the final part of the RSA-PSI protocol.
Parameters
[out] z - the elements in the intersection.
[out] len - the cardinality of the resulting intersection.
[in] r - the random nonce.
[in] p - the mapping of elements to prime numbers.
[in] n - the modulus given by the trusted setup.
[in] x - the receiver's input set.
[in] m - the receiver's input set size.
[in] t - the accumulator results.
[in] u - the missing elements in the exponent.
[in] l - the sender's input set size.
Definition at line 149 of file relic_cp_rsapsi.c.
References bn_cmp(), bn_copy(), bn_free, bn_mxp, bn_new, bn_null, RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_shipsi_gen()
int cp_shipsi_gen (bn_t g, crt_t crt, size_t bits)
Generates the trusted setup parameters for the factoring-based size-hiding Private Set Intersection (SHI-PSI) protocol.
Parameters
[out] g - the generator.
[in] crt - the parameters given by the trusted setup.
[in] bits - the precision in bits.
Definition at line 47 of file relic_cp_shipsi.c.
References bn_cmp(), bn_cmp_dig(), bn_copy(), bn_gcd, bn_gen_prime, bn_mod_inv(), bn_mul, bn_rand_mod(), bn_sub_dig(), RLC_EQ, RLC_LT, and RLC_OK.
cp_shipsi_ask()
int cp_shipsi_ask (bn_t d, bn_t r, bn_t * p, const bn_t g, const bn_t n, const bn_t * x, size_t m)
Computes the receiver part of the SHI-PSI protocol, given its input set.
Parameters
[out] d - the resulting accumulator.
[out] r - the random nonce.
[out] p - the mapping of elements to prime numbers.
[in] n - the modulus given by the trusted setup.
[in] crt - the parameters given by the trusted setup.
[in] x - the receiver's input set.
[in] m - the receiver's input set size.
cp_shipsi_ans()
int cp_shipsi_ans (bn_t * t, bn_t u, bn_t d, const bn_t g, const crt_t crt, const bn_t * y, const size_t n)
Computes the sender part of the SHI-PSI protocol, given its input set.
Parameters
[out] t - the accumulator results.
[out] u - the hint in the exponent.
[in] d - the receiver's accumulator.
[in] g - the generator given by the trusted setup.
[in] crt - the parameters given by the trusted setup.
[in] y - the server's input set.
[in] n - the sender's input set size.
cp_shipsi_int()
int cp_shipsi_int (bn_t * z, size_t * len, const bn_t r, const bn_t * p, const bn_t n, const bn_t * x, size_t m, const bn_t * t, const bn_t u, size_t l)
Computes the intersection as the final part of the SHI-PSI protocol.
Parameters
[out] z - the elements in the intersection.
[out] len - the cardinality of the resulting intersection.
[in] r - the random nonce.
[in] p - the mapping of elements to prime numbers.
[in] n - the modulus given by the trusted setup.
[in] x - the receiver's input set.
[in] m - the receiver's input set size.
[in] t - the accumulator results.
[in] u - the hint in the exponent.
[in] l - the sender's input set size.
cp_pbpsi_gen()
int cp_pbpsi_gen (bn_t sk, g1_t ss, g2_t * s, size_t m)
Generates the secrets and consecutive powers for the pairing-based laconic Private Set Intersection (PB-PSI) protocol, given the maximum set size.
Parameters
[out] sk - the sender's secret key.
[out] ss - the secret power in G_2.
[out] s - the consecutive powers in G_1.
[in] m - the maximum set size.
Definition at line 38 of file relic_cp_pbpsi.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), g1_mul_gen(), g2_get_gen, g2_mul(), pc_get_ord, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_pbpsi_ask()
int cp_pbpsi_ask (g2_t * d, bn_t r, const bn_t * x, const g2_t * s, size_t m)
Computes the receiver part of the PB-PSI protocol, given its input set.
Parameters
[out] d - the polynomial interpolations in the exponent.
[out] r - the random nonce.
[in] x - the receiver's input set.
[in] s - the consecutive powers.
[in] m - the receiver's input set size.
Definition at line 65 of file relic_cp_pbpsi.c.
References bn_copy(), bn_free, bn_lag(), bn_new, bn_null, bn_rand_mod(), ERR_NO_MEMORY, g2_mul(), g2_mul_gen(), g2_mul_sim_lot, pc_get_ord, RLC_ALLOCA, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_FREE, RLC_OK, RLC_THROW, and RLC_TRY.
cp_pbpsi_ans()
int cp_pbpsi_ans (gt_t * t, g1_t * u, const g1_t ss, const g2_t d, const bn_t * y, size_t n)
Computes the sender part of the PB-PSI protocol, given its input set.
Parameters
[out] t - the pairing results.
[out] u - the missing elements in the exponent.
[in] ss - the secret power.
[in] d - the polynomial interpolations in the exponent.
[in] y - the server's input set.
[in] n - the sender's input set size.
Definition at line 122 of file relic_cp_pbpsi.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), ERR_NO_MEMORY, g1_free, g1_mul(), g1_mul_gen(), g1_new, g1_null, g1_sub, g2_free, g2_get_gen, g2_new, g2_null, pc_get_ord, pc_map, RLC_ALLOCA, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_FREE, RLC_OK, RLC_THROW, RLC_TRY, and util_perm().
cp_pbpsi_int()
int cp_pbpsi_int (bn_t * z, size_t * len, const g2_t * d, const bn_t * x, size_t m, const gt_t * t, const g1_t * u, size_t n)
Computes the intersection as the final part of the PB-PSI protocol.
Parameters
[out] z - the elements in the intersection.
[out] len - the cardinality of the resulting intersection.
[in] d - the polynomial interpolations in the exponent.
[in] x - the receiver's input set.
[in] s - the consecutive powers.
[in] m - the receiver's input set size.
[in] t - the pairing results.
[in] u - the missing elements in the exponent.
[in] n - the sender's input set size.
Definition at line 170 of file relic_cp_pbpsi.c.
References bn_copy(), gt_cmp, gt_free, gt_is_unity, gt_new, gt_null, pc_map, RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.