RELIC: src/bn/relic_bn_rec.c File Reference
relic_bn_rec.c File Reference
Multiple precision integer arithmetic
#include "relic_core.h"
Macros
#define MOD_C 8
#define MOD_2TC (1 << MOD_C)
#define MOD_CMASK (MOD_2TC - 1)
Functions
static char get_bits (const bn_t a, size_t from, size_t to)
void bn_rec_win (uint8_t *win, size_t *len, const bn_t k, size_t w)
void bn_rec_slw (uint8_t *win, size_t *len, const bn_t k, size_t w)
void bn_rec_naf (int8_t *naf, size_t *len, const bn_t k, size_t w)
void bn_rec_tnaf_get (uint8_t *t, int8_t *beta, int8_t *gama, int8_t u, size_t w)
void bn_rec_tnaf_mod (bn_t r0, bn_t r1, const bn_t k, int u, size_t m)
void bn_rec_tnaf (int8_t *tnaf, size_t *len, const bn_t k, int8_t u, size_t m, size_t w)
void bn_rec_rtnaf (int8_t *tnaf, size_t *len, const bn_t k, int8_t u, size_t m, size_t w)
void bn_rec_reg (int8_t *naf, size_t *len, const bn_t k, size_t n, size_t w)
void bn_rec_jsf (int8_t *jsf, size_t *len, const bn_t k, const bn_t l)
void bn_rec_glv (bn_t k0, bn_t k1, const bn_t k, const bn_t n, const bn_t *v1, const bn_t *v2)
void bn_rec_sac (int8_t *b, size_t *len, bn_t *k, size_t c, size_t m, size_t n)
void bn_rec_frb (bn_t *ki, int sub, const bn_t k, const bn_t x, const bn_t n, int cof)
Detailed Description
Implementation of the multiple precision integer recoding functions.
Definition in file relic_bn_rec.c.
Macro Definition Documentation
MOD_C
#define MOD_C 8
Constant C for the partial reduction modulo (t^m - 1)/(t - 1).
Definition at line 78 of file relic_bn_rec.c.
MOD_2TC
#define MOD_2TC (1 << MOD_C)
Constant 2^C.
Definition at line 83 of file relic_bn_rec.c.
MOD_CMASK
#define MOD_CMASK (MOD_2TC - 1)
Mask to calculate reduction modulo 2^C.
Definition at line 88 of file relic_bn_rec.c.
Function Documentation
get_bits()
static char get_bits (const bn_t a, size_t from, size_t to) static
Returns a maximum of eight contiguous bits from a multiple precision integer.
Parameters
[in] a - the multiple precision integer.
[in] from - the first bit position.
[in] to - the last bit position, inclusive.
Returns
the bits in the chosen positions.
Definition at line 46 of file relic_bn_rec.c.
References RLC_DIG, RLC_DMASK, RLC_MASK, and RLC_RIP.
Referenced by bn_rec_slw(), and bn_rec_win().
bn_rec_win()
void bn_rec_win (uint8_t * win, size_t * len, const bn_t k, size_t w)
Recodes a positive integer in window form. If a negative integer is given instead, its absolute value is taken.
Parameters
[out] win - the recoded integer.
[out] len - the number of bytes written.
[in] k - the integer to recode.
[in] w - the window size in bits.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 94 of file relic_bn_rec.c.
References bn_bits(), ERR_NO_BUFFER, get_bits(), RLC_CEIL, and RLC_THROW.
Referenced by eb_mul_sim_trick(), ed_mul_sim_trick(), ep2_mul_sim_trick(), ep3_mul_sim_trick(), ep4_mul_sim_trick(), ep8_mul_sim_trick(), and ep_mul_sim_trick().
bn_rec_slw()
void bn_rec_slw (uint8_t * win, size_t * len, const bn_t k, size_t w)
Recodes a positive integer in sliding window form. If a negative integer is given instead, its absolute value is taken.
Parameters
[out] win - the recoded integer.
[out] len - the number of bytes written.
[in] k - the integer to recode.
[in] w - the window size in bits.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 115 of file relic_bn_rec.c.
References bn_bits(), bn_get_bit(), ERR_NO_BUFFER, get_bits(), RLC_MAX, and RLC_THROW.
Referenced by bn_mxp_slide(), ed_mul_slide(), ep2_mul_slide(), ep3_mul_slide(), ep4_mul_slide(), ep8_mul_slide(), ep_mul_slide(), fb_exp_slide(), and fp_exp_slide().
bn_rec_naf()
void bn_rec_naf (int8_t * naf, size_t * len, const bn_t k, size_t w)
Recodes a positive integer in width-w Non-Adjacent Form. If a negative integer is given instead, its absolute value is taken.
Parameters
[out] naf - the recoded integer.
[out] len - the number of bytes written.
[in] k - the integer to recode.
[in] w - the window size in bits.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 146 of file relic_bn_rec.c.
References bn_abs(), bn_add_dig(), bn_bits(), bn_free, bn_get_dig(), bn_hlv(), bn_is_even(), bn_is_zero(), bn_new, bn_null, bn_sub_dig(), ERR_CAUGHT, ERR_NO_BUFFER, RLC_CATCH_ANY, RLC_FINALLY, RLC_MASK, RLC_THROW, and RLC_TRY.
Referenced by eb_mul_basic(), eb_mul_fix_plain(), eb_mul_halve(), eb_mul_lnaf_imp(), eb_mul_rnaf_imp(), eb_mul_sim_plain(), ed_mul_basic(), ed_mul_dig(), ed_mul_fix_plain(), ed_mul_naf_imp(), ed_mul_sim_lot(), ed_mul_sim_plain(), ep2_mul_basic(), ep2_mul_dig(), ep2_mul_fix_plain(), ep2_mul_gls_imp(), ep2_mul_naf_imp(), ep2_mul_sim_endom(), ep2_mul_sim_lot(), ep2_mul_sim_plain(), ep3_mul_basic(), ep3_mul_dig(), ep3_mul_fix_plain(), ep3_mul_naf_imp(), ep3_mul_sim_lot(), ep3_mul_sim_plain(), ep4_mul_basic(), ep4_mul_dig(), ep4_mul_fix_ordin(), ep4_mul_gls_imp(), ep4_mul_naf_imp(), ep4_mul_sim_lot(), ep4_mul_sim_plain(), ep8_mul_basic(), ep8_mul_dig(), ep8_mul_fix_ordin(), ep8_mul_gls_imp(), ep8_mul_naf_imp(), ep8_mul_sim_lot(), ep8_mul_sim_plain(), ep_mul_basic(), ep_mul_dig(), ep_mul_fix_plain(), ep_mul_glv_imp(), ep_mul_naf_imp(), ep_mul_sim_endom(), ep_mul_sim_lot_endom(), ep_mul_sim_lot_plain(), ep_mul_sim_plain(), fp12_exp_cyc(), fp12_exp_dig(), fp16_exp_cyc(), fp16_exp_cyc_sim(), fp16_exp_dig(), fp18_exp_cyc(), fp18_exp_cyc_sim(), fp18_exp_dig(), fp24_exp_cyc(), fp24_exp_cyc_sim(), fp24_exp_dig(), fp2_exp_cyc(), fp2_exp_cyc_sim(), fp48_exp_cyc(), fp48_exp_cyc_sim(), fp48_exp_dig(), fp54_exp_dig(), fp8_exp_cyc(), fp8_exp_cyc_sim(), fp8_exp_dig(), fp_prime_set_pairf(), g1_is_valid(), gt_exp_dig(), gt_exp_gls_naf(), pp_mil_k12(), pp_mil_k16(), pp_mil_k18(), pp_mil_k24(), pp_mil_k48(), pp_mil_k54(), and pp_mil_k8().
bn_rec_tnaf_get()
void bn_rec_tnaf_get (uint8_t * t, int8_t * beta, int8_t * gama, int8_t u, size_t w)
Write the constants needed for \tau-NAF recoding as a set of \alpha_u = \beta_u + \gamma_u * \tau elements.
Parameters
[out] t - the integer corresponding to \tau.
[out] beta - the first coefficients of the constants.
[out] gama - the second coefficients of the constants.
[in] u - the u curve parameter.
[in] w - the window size in bits.
Definition at line 220 of file relic_bn_rec.c.
Referenced by bn_rec_rtnaf(), and bn_rec_tnaf().
bn_rec_tnaf_mod()
void bn_rec_tnaf_mod (bn_t r0, bn_t r1, const bn_t k, int u, size_t m)
Computes the partial reduction k partmod d = r0 + r1 * t, where d = (t^m - 1)/(t - 1).
Parameters
[out] r0 - the first half of the result.
[out] r1 - the second half of the result.
[in] k - the number to reduce.
[in] u - the u curve parameter.
[in] m - the extension degree of the binary field.
Definition at line 353 of file relic_bn_rec.c.
References bn_abs(), bn_add(), bn_dbl(), bn_free, bn_hlv(), bn_is_even(), bn_neg(), bn_new, bn_null, bn_set_dig(), bn_sub(), bn_sub_dig(), bn_zero(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by bn_rec_rtnaf(), and bn_rec_tnaf().
bn_rec_tnaf()
void bn_rec_tnaf (int8_t * tnaf, size_t * len, const bn_t k, int8_t u, size_t m, size_t w)
Recodes a positive integer in width-w \tau-NAF. If a negative integer is given instead, its absolute value is taken.
Parameters
[out] tnaf - the recoded integer.
[out] len - the number of bytes written.
[in] k - the integer to recode.
[in] u - the u curve parameter.
[in] m - the extension degree of the binary field.
[in] w - the window size in bits.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 425 of file relic_bn_rec.c.
References bn_abs(), bn_add(), bn_add_dig(), bn_bits(), bn_copy(), bn_free, bn_hlv(), bn_is_zero(), bn_new, bn_null, bn_rec_tnaf_get(), bn_rec_tnaf_mod(), bn_sign(), bn_sub(), bn_sub_dig(), ERR_CAUGHT, ERR_NO_BUFFER, RLC_CATCH_ANY, RLC_FINALLY, RLC_MASK, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by eb_mul_fix_kbltz(), eb_mul_ltnaf_imp(), eb_mul_rtnaf_imp(), and eb_mul_sim_kbltz().
bn_rec_rtnaf()
void bn_rec_rtnaf (int8_t * tnaf, size_t * len, const bn_t k, int8_t u, size_t m, size_t w)
Recodes a positive integer in regular fixed-length width-w \tau-NAF. If a negative integer is given instead, its absolute value is taken.
Parameters
[out] tnaf - the recoded integer.
[out] len - the number of bytes written.
[in] k - the integer to recode.
[in] u - the u curve parameter.
[in] m - the extension degree of the binary field.
[in] w - the window size in bits.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 556 of file relic_bn_rec.c.
References bn_abs(), bn_add(), bn_add_dig(), bn_bits(), bn_copy(), bn_free, bn_hlv(), bn_new, bn_null, bn_rec_tnaf_get(), bn_rec_tnaf_mod(), bn_sign(), bn_sub(), bn_sub_dig(), ERR_CAUGHT, ERR_NO_BUFFER, RLC_CATCH_ANY, RLC_CEIL, RLC_FINALLY, RLC_MASK, RLC_NEG, RLC_THROW, and RLC_TRY.
bn_rec_reg()
void bn_rec_reg (int8_t * naf, size_t * len, const bn_t k, size_t n, size_t w)
Recodes a positive integer in regular fixed-length width-w NAF. If a negative integer is given instead, its absolute value is taken.
Parameters
[out] naf - the recoded integer.
[out] len - the number of bytes written.
[in] k - the integer to recode.
[in] n - the length of the recoding.
[in] w - the window size in bits.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 699 of file relic_bn_rec.c.
References bn_abs(), bn_free, bn_get_dig(), bn_hlv(), bn_new, bn_null, bn_rsh(), ERR_CAUGHT, ERR_NO_BUFFER, RLC_CATCH_ANY, RLC_CEIL, RLC_FINALLY, RLC_MASK, RLC_THROW, and RLC_TRY.
Referenced by ed_mul_reg_imp(), ep2_mul_reg_imp(), ep3_mul_reg_imp(), ep4_mul_reg_imp(), ep8_mul_reg_imp(), ep_mul_reg_glv(), ep_mul_reg_imp(), and gt_exp_reg_gls().
bn_rec_jsf()
void bn_rec_jsf (int8_t * jsf, size_t * len, const bn_t k, const bn_t l)
Recodes of a pair of positive integers in Joint Sparse Form. If negative integers are given instead, takes their absolute value.
Parameters
[out] jsf - the recoded pair of integers.
[out] len - the number of bytes written.
[in] k - the first integer to recode.
[in] l - the second integer to recode.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 752 of file relic_bn_rec.c.
References bn_abs(), bn_bits(), bn_free, bn_get_dig(), bn_hlv(), bn_is_zero(), bn_new, bn_null, ERR_CAUGHT, ERR_NO_BUFFER, RLC_CATCH_ANY, RLC_FINALLY, RLC_MASK, RLC_MAX, RLC_THROW, and RLC_TRY.
Referenced by eb_mul_sim_joint(), ed_mul_sim_joint(), ep2_mul_sim_joint(), ep3_mul_sim_joint(), ep4_mul_sim_joint(), ep8_mul_sim_joint(), and ep_mul_sim_joint().
bn_rec_glv()
void bn_rec_glv (bn_t k0, bn_t k1, const bn_t k, const bn_t n, const bn_t * v1, const bn_t * v2)
Definition at line 831 of file relic_bn_rec.c.
References bn_abs(), bn_add(), bn_add_dig(), bn_bits(), bn_free, bn_get_bit(), bn_mul, bn_neg(), bn_new, bn_null, bn_rsh(), bn_sub(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep_mul_combs_endom(), ep_mul_glv_imp(), ep_mul_reg_glv(), ep_mul_sim_endom(), and ep_mul_sim_lot_endom().
bn_rec_sac()
void bn_rec_sac (int8_t * b, size_t * len, bn_t * k, size_t c, size_t m, size_t n)
Recodes subscalars in the signed aligned column representation..
Parameters
[out] b - the recoded subscalars.
[in] len - the length in bytes of the recoding.
[in] k - the subscalars to recode.
[in] c - the splitting factor.
[in] m - the number of subscalars to recode.
[in] n - the bit length of the group order.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 879 of file relic_bn_rec.c.
References bn_add_dig(), bn_bits(), bn_copy(), bn_free, bn_get_bit(), bn_hlv(), bn_new, bn_null, EP_BN, ep_curve_is_pairf(), ERR_CAUGHT, ERR_NO_BUFFER, ERR_NO_MEMORY, fp_prime_get_par(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_CEIL, RLC_FINALLY, RLC_FREE, RLC_MAX, RLC_THROW, and RLC_TRY.
Referenced by ep2_mul_reg_gls(), ep3_mul_gls_imp(), ep3_mul_reg_gls(), ep4_mul_reg_gls(), ep8_mul_reg_gls(), gt_exp_gls_sac(), and gt_exp_reg_sac().
bn_rec_frb()
void bn_rec_frb (bn_t * ki, int sub, const bn_t k, const bn_t x, const bn_t n, int cof)
Recodes a scalar in subscalars according to Frobenius endomorphism.
Parameters
[out] ki - the recoded subscalars.
[in] sub - the number of subscalars.
[in] k - the scalar to recode.
[in] x - the elliptic curve parameter.
[in] n - the elliptic curve group order.
[in] cof - flag to indicate if it is a curve with cofactor 1.
Definition at line 936 of file relic_bn_rec.c.
References bn_abs(), bn_add(), bn_add_dig(), bn_bits(), bn_copy(), bn_dbl(), bn_div(), bn_free, bn_mod, bn_mul, bn_mul_dig(), bn_neg(), bn_new, bn_null, bn_rsh(), bn_sign(), bn_sqr, bn_sub(), bn_sub_dig(), bn_zero(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_POS, RLC_THROW, and RLC_TRY.
Referenced by ep2_mul_gls_imp(), ep2_mul_reg_gls(), ep2_mul_sim_endom(), ep2_mul_sim_lot(), ep3_mul_gls_imp(), ep3_mul_reg_gls(), ep3_mul_sim_lot(), ep4_mul_gls_imp(), ep4_mul_reg_gls(), ep4_mul_sim_lot(), ep8_mul_gls_imp(), ep8_mul_reg_gls(), ep8_mul_sim_lot(), fp12_exp_cyc_sim(), gt_exp_gls_naf(), gt_exp_gls_sac(), gt_exp_reg_gls(), and gt_exp_reg_sac().