RELIC: src/fpx/relic_fpx_add.c File Reference
relic_fpx_add.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fpx_low.h"
Functions
void fp2_add_basic (fp2_t c, const fp2_t a, const fp2_t b)
void fp2_sub_basic (fp2_t c, const fp2_t a, const fp2_t b)
void fp2_dbl_basic (fp2_t c, const fp2_t a)
void fp2_add_integ (fp2_t c, const fp2_t a, const fp2_t b)
void fp2_sub_integ (fp2_t c, const fp2_t a, const fp2_t b)
void fp2_dbl_integ (fp2_t c, const fp2_t a)
void fp2_add_dig (fp2_t c, const fp2_t a, dig_t dig)
void fp2_sub_dig (fp2_t c, const fp2_t a, dig_t dig)
void fp2_neg (fp2_t c, const fp2_t a)
void fp3_add_basic (fp3_t c, const fp3_t a, const fp3_t b)
void fp3_sub_basic (fp3_t c, const fp3_t a, const fp3_t b)
void fp3_dbl_basic (fp3_t c, const fp3_t a)
void fp3_add_dig (fp3_t c, const fp3_t a, dig_t dig)
void fp3_sub_dig (fp3_t c, const fp3_t a, dig_t dig)
void fp3_neg (fp3_t c, const fp3_t a)
void fp3_add_integ (fp3_t c, const fp3_t a, const fp3_t b)
void fp3_sub_integ (fp3_t c, const fp3_t a, const fp3_t b)
void fp3_dbl_integ (fp3_t c, const fp3_t a)
void fp4_add (fp4_t c, const fp4_t a, const fp4_t b)
void fp4_sub (fp4_t c, const fp4_t a, const fp4_t b)
void fp4_dbl (fp4_t c, const fp4_t a)
void fp4_add_dig (fp4_t c, const fp4_t a, dig_t dig)
void fp4_sub_dig (fp4_t c, const fp4_t a, dig_t dig)
void fp4_neg (fp4_t c, const fp4_t a)
void fp6_add (fp6_t c, const fp6_t a, const fp6_t b)
void fp6_sub (fp6_t c, const fp6_t a, const fp6_t b)
void fp6_dbl (fp6_t c, const fp6_t a)
void fp6_neg (fp6_t c, const fp6_t a)
void fp8_add (fp8_t c, const fp8_t a, const fp8_t b)
void fp8_sub (fp8_t c, const fp8_t a, const fp8_t b)
void fp8_dbl (fp8_t c, const fp8_t a)
void fp8_neg (fp8_t c, const fp8_t a)
void fp9_add (fp9_t c, const fp9_t a, const fp9_t b)
void fp9_sub (fp9_t c, const fp9_t a, const fp9_t b)
void fp9_dbl (fp9_t c, const fp9_t a)
void fp9_neg (fp9_t c, const fp9_t a)
void fp12_add (fp12_t c, const fp12_t a, const fp12_t b)
void fp12_sub (fp12_t c, const fp12_t a, const fp12_t b)
void fp12_neg (fp12_t c, const fp12_t a)
void fp12_dbl (fp12_t c, const fp12_t a)
void fp16_add (fp16_t c, const fp16_t a, const fp16_t b)
void fp16_sub (fp16_t c, const fp16_t a, const fp16_t b)
void fp16_dbl (fp16_t c, const fp16_t a)
void fp16_neg (fp16_t c, const fp16_t a)
void fp18_add (fp18_t c, const fp18_t a, const fp18_t b)
void fp18_sub (fp18_t c, const fp18_t a, const fp18_t b)
void fp18_dbl (fp18_t c, const fp18_t a)
void fp18_neg (fp18_t c, const fp18_t a)
void fp24_add (fp24_t c, const fp24_t a, const fp24_t b)
void fp24_sub (fp24_t c, const fp24_t a, const fp24_t b)
void fp24_neg (fp24_t c, const fp24_t a)
void fp24_dbl (fp24_t c, const fp24_t a)
void fp48_add (fp48_t c, const fp48_t a, const fp48_t b)
void fp48_sub (fp48_t c, const fp48_t a, const fp48_t b)
void fp48_neg (fp48_t c, const fp48_t a)
void fp48_dbl (fp48_t c, const fp48_t a)
void fp54_add (fp54_t c, const fp54_t a, const fp54_t b)
void fp54_sub (fp54_t c, const fp54_t a, const fp54_t b)
void fp54_neg (fp54_t c, const fp54_t a)
void fp54_dbl (fp54_t c, const fp54_t a)
Detailed Description
Implementation of addition in extensions defined over prime fields.
Definition in file relic_fpx_add.c.
Function Documentation
fp2_add_basic()
void fp2_add_basic (fp2_t c, const fp2_t a, const fp2_t b)
Adds two quadratic extension field elements using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the first quadratic extension field element.
[in] b - the second quadratic extension field element.
Definition at line 41 of file relic_fpx_add.c.
References fp_add.
fp2_sub_basic()
void fp2_sub_basic (fp2_t c, const fp2_t a, const fp2_t b)
Subtracts a quadratic extension field element from another using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the first quadratic extension field element.
[in] b - the second quadratic extension field element.
Definition at line 46 of file relic_fpx_add.c.
References fp_sub.
fp2_dbl_basic()
void fp2_dbl_basic (fp2_t c, const fp2_t a)
Doubles a quadratic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to double.
Definition at line 51 of file relic_fpx_add.c.
References fp_dbl.
fp2_add_integ()
void fp2_add_integ (fp2_t c, const fp2_t a, const fp2_t b)
Adds two quadratic extension field elements using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the first quadratic extension field element.
[in] b - the second quadratic extension field element.
Definition at line 61 of file relic_fpx_add.c.
References fp2_addm_low().
fp2_sub_integ()
void fp2_sub_integ (fp2_t c, const fp2_t a, const fp2_t b)
Subtracts a quadratic extension field element from another using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the first quadratic extension field element.
[in] b - the second quadratic extension field element.
Definition at line 65 of file relic_fpx_add.c.
References fp2_subm_low().
fp2_dbl_integ()
void fp2_dbl_integ (fp2_t c, const fp2_t a)
Doubles a quadratic extension field element using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to double.
Definition at line 69 of file relic_fpx_add.c.
References fp2_dblm_low().
fp2_add_dig()
void fp2_add_dig (fp2_t c, const fp2_t a, dig_t b)
Adds a quadratic extension field element and a digit. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element.
[in] b - the digit to add.
Definition at line 75 of file relic_fpx_add.c.
References fp_add_dig(), and fp_copy().
Referenced by ep2_map_basic(), ep2_map_swift(), ep2_rhs(), fp12_pck_max(), and fp4_add_dig().
fp2_sub_dig()
void fp2_sub_dig (fp2_t c, const fp2_t a, dig_t b)
Subtracts a quadratic extension field element and a digit. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element.
[in] b - the digit to subtract.
Definition at line 80 of file relic_fpx_add.c.
References fp_copy(), and fp_sub_dig().
Referenced by ep2_map_swift(), ep2_rhs(), and fp4_sub_dig().
fp2_neg()
void fp2_neg (fp2_t c, const fp2_t a)
Negates a quadratic extension field element.
Parameters
[out] c - the result.
[out] a - the quadratic extension field element to negate.
Definition at line 85 of file relic_fpx_add.c.
References fp_neg.
Referenced by detect_opt(), ep2_curve_set_map(), ep2_map_swift(), ep2_neg(), ep2_upk(), fp4_inv(), fp4_inv_cyc(), fp4_neg(), fp6_neg(), and pp_add_lit_k12().
fp3_add_basic()
void fp3_add_basic (fp3_t c, const fp3_t a, const fp3_t b)
Adds two cubic extension field elements using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the first cubic extension field element.
[in] b - the second cubic extension field element.
Definition at line 92 of file relic_fpx_add.c.
References fp_add.
fp3_sub_basic()
void fp3_sub_basic (fp3_t c, const fp3_t a, const fp3_t b)
Subtracts a cubic extension field element from another using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the first cubic extension field element.
[in] b - the second cubic extension field element.
Definition at line 98 of file relic_fpx_add.c.
References fp_sub.
fp3_dbl_basic()
void fp3_dbl_basic (fp3_t c, const fp3_t a)
Doubles a cubic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the cubic extension field element to double.
Definition at line 104 of file relic_fpx_add.c.
References fp_dbl.
fp3_add_dig()
void fp3_add_dig (fp3_t c, const fp3_t a, dig_t b)
Adds a cubic extension field element and a digit. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the cubic extension field element.
[in] b - the digit to add.
Definition at line 113 of file relic_fpx_add.c.
References fp_add_dig(), and fp_copy().
Referenced by ep3_rhs().
fp3_sub_dig()
void fp3_sub_dig (fp3_t c, const fp3_t a, dig_t b)
Subtracts a cubic extension field element and a digit. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the cubic extension field element.
[in] b - the digit to subtract.
Definition at line 119 of file relic_fpx_add.c.
References fp_copy(), and fp_sub_dig().
Referenced by ep3_rhs().
fp3_neg()
void fp3_neg (fp3_t c, const fp3_t a)
Negates a cubic extension field element. Computes c = -a.
Parameters
[out] c - the result.
[out] a - the cubic extension field element to negate.
Definition at line 125 of file relic_fpx_add.c.
References fp_neg.
Referenced by detect_opt(), ep3_map(), ep3_neg(), fp9_neg(), and pp_add_lit_k18().
fp3_add_integ()
void fp3_add_integ (fp3_t c, const fp3_t a, const fp3_t b)
Adds two cubic extension field elements using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the first cubic extension field element.
[in] b - the second cubic extension field element.
Definition at line 133 of file relic_fpx_add.c.
References fp3_addm_low().
fp3_sub_integ()
void fp3_sub_integ (fp3_t c, const fp3_t a, const fp3_t b)
Subtracts a cubic extension field element from another using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the first cubic extension field element.
[in] b - the second cubic extension field element.
Definition at line 137 of file relic_fpx_add.c.
References fp3_subm_low().
fp3_dbl_integ()
void fp3_dbl_integ (fp3_t c, const fp3_t a)
Doubles a cubic extension field element using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the cubic extension field element to double.
Definition at line 141 of file relic_fpx_add.c.
References fp3_dblm_low().
fp4_add()
void fp4_add (fp4_t c, const fp4_t a, const fp4_t b)
Adds two quartic extension field elements. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first quartic extension field element.
[in] b - the second quartic extension field element.
Definition at line 147 of file relic_fpx_add.c.
References fp2_add.
Referenced by ep4_map(), ep4_rhs(), fp16_mul_dxs_basic(), fp16_mul_dxs_lazyr(), fp24_back_cyc(), fp24_back_cyc_sim(), fp24_sqr_cyc_basic(), fp24_sqr_cyc_lazyr(), fp24_sqr_pck_basic(), fp24_sqr_pck_lazyr(), fp8_add(), fp8_mul_basic(), fp8_mul_dxs(), fp8_mul_unr(), fp8_sqr_basic(), fp8_sqr_cyc(), fp8_sqr_unr(), fp8_srt(), pp_add_k16_projc_basic(), pp_add_k16_projc_lazyr(), pp_add_k24_projc(), pp_dbl_k16_projc_basic(), pp_dbl_k16_projc_lazyr(), pp_dbl_k24_projc(), and pp_dbl_lit_k16().
fp4_sub()
void fp4_sub (fp4_t c, const fp4_t a, const fp4_t b)
Subtracts a quartic extension field element from another. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the quartic extension field element.
[in] b - the quartic extension field element.
Definition at line 152 of file relic_fpx_add.c.
References fp2_sub.
Referenced by ep4_map(), fp16_mul_dxs_basic(), fp24_back_cyc(), fp24_back_cyc_sim(), fp24_sqr_cyc_basic(), fp24_sqr_cyc_lazyr(), fp24_sqr_pck_basic(), fp24_sqr_pck_lazyr(), fp8_inv(), fp8_mul_basic(), fp8_sqr_basic(), fp8_sqr_cyc(), fp8_srt(), fp8_sub(), pp_add_k16_basic(), pp_add_k16_projc_basic(), pp_add_k16_projc_lazyr(), pp_add_k24_basic(), pp_add_k24_projc(), pp_dbl_k16_basic(), pp_dbl_k16_projc_basic(), pp_dbl_k16_projc_lazyr(), pp_dbl_k24_basic(), and pp_dbl_k24_projc().
fp4_dbl()
void fp4_dbl (fp4_t c, const fp4_t a)
Doubles a quartic extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the quartic extension field element to double.
Definition at line 157 of file relic_fpx_add.c.
References fp2_dbl.
Referenced by ep4_curve_mul_a(), ep4_map(), fp24_back_cyc(), fp24_back_cyc_sim(), fp24_sqr_cyc_basic(), fp24_sqr_cyc_lazyr(), fp24_sqr_pck_basic(), fp24_sqr_pck_lazyr(), fp8_dbl(), fp8_sqr_basic(), fp8_sqr_cyc(), fp8_srt(), pp_add_k16_projc_basic(), pp_add_k16_projc_lazyr(), pp_dbl_k16_projc_basic(), pp_dbl_k16_projc_lazyr(), pp_dbl_k24_projc(), and pp_dbl_lit_k16().
fp4_add_dig()
void fp4_add_dig (fp4_t c, const fp4_t a, dig_t b)
Adds a quartic extension field element and a digit. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the quartic extension field element.
[in] b - the digit to add.
Definition at line 163 of file relic_fpx_add.c.
References fp2_add_dig(), and fp2_copy().
fp4_sub_dig()
void fp4_sub_dig (fp4_t c, const fp4_t a, dig_t b)
Subtracts a quartic extension field element and a digit. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the quartic extension field element.
[in] b - the digit to subtract.
Definition at line 168 of file relic_fpx_add.c.
References fp2_copy(), and fp2_sub_dig().
fp4_neg()
void fp4_neg (fp4_t c, const fp4_t a)
Negates a quartic extension field element. Computes c = -a.
Parameters
[out] c - the result.
[out] a - the quartic extension field element to negate.
Definition at line 173 of file relic_fpx_add.c.
References fp2_neg().
Referenced by detect_opt(), ep4_map(), ep4_neg(), fp8_inv(), fp8_inv_cyc(), fp8_neg(), and pp_add_lit_k16().
fp6_add()
void fp6_add (fp6_t c, const fp6_t a, const fp6_t b)
Adds two sextic extension field elements. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first sextic extension field element.
[in] b - the second sextic extension field element.
Definition at line 178 of file relic_fpx_add.c.
References fp2_add.
Referenced by fp12_add(), fp12_mul_basic(), fp12_mul_dxs_basic(), fp12_mul_dxs_lazyr(), fp12_mul_unr(), and fp12_sqr_basic().
fp6_sub()
void fp6_sub (fp6_t c, const fp6_t a, const fp6_t b)
Subtracts a sextic extension field element from another. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the sextic extension field element.
[in] b - the sextic extension field element.
Definition at line 184 of file relic_fpx_add.c.
References fp2_sub.
Referenced by fp12_inv(), fp12_mul_basic(), fp12_mul_dxs_basic(), fp12_sqr_basic(), and fp12_sub().
fp6_dbl()
void fp6_dbl (fp6_t c, const fp6_t a)
Doubles a sextic extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the sextic extension field element to double.
Definition at line 190 of file relic_fpx_add.c.
References fp2_dbl.
Referenced by fp12_dbl(), and fp12_sqr_basic().
fp6_neg()
void fp6_neg (fp6_t c, const fp6_t a)
Negates a sextic extension field element. Computes c = -a.
Parameters
[out] c - the result.
[out] a - the sextic extension field element to negate.
Definition at line 196 of file relic_fpx_add.c.
References fp2_neg().
Referenced by fp12_inv(), fp12_inv_cyc(), and fp12_neg().
fp8_add()
void fp8_add (fp8_t c, const fp8_t a, const fp8_t b)
Adds two octic extension field elements. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first octic extension field element.
[in] b - the second octic extension field element.
Definition at line 202 of file relic_fpx_add.c.
References fp4_add().
Referenced by ep8_map(), ep8_rhs(), fp16_add(), fp16_mul_basic(), fp16_mul_dxs_basic(), fp16_mul_dxs_lazyr(), fp16_mul_unr(), fp16_sqr_basic(), fp16_sqr_cyc(), fp16_sqr_unr(), fp16_srt(), fp24_add(), fp24_inv(), fp24_mul_basic(), fp24_mul_dxs(), fp24_mul_unr(), fp24_sqr_basic(), fp24_sqr_unr(), fp48_back_cyc(), fp48_back_cyc_sim(), fp48_mul_dxs(), fp48_sqr_cyc_basic(), fp48_sqr_cyc_lazyr(), fp48_sqr_pck_basic(), fp48_sqr_pck_lazyr(), pp_add_k48_projc(), and pp_dbl_k48_projc().
fp8_sub()
void fp8_sub (fp8_t c, const fp8_t a, const fp8_t b)
Subtracts an octic extension field element from another. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the octic extension field element.
[in] b - the octic extension field element.
Definition at line 207 of file relic_fpx_add.c.
References fp4_sub().
Referenced by ep8_map(), fp16_inv(), fp16_mul_basic(), fp16_mul_dxs_basic(), fp16_sqr_basic(), fp16_sqr_cyc(), fp16_srt(), fp16_sub(), fp24_inv(), fp24_mul_basic(), fp24_mul_dxs(), fp24_sqr_basic(), fp24_sqr_unr(), fp24_sub(), fp48_back_cyc(), fp48_back_cyc_sim(), fp48_sqr_cyc_basic(), fp48_sqr_cyc_lazyr(), fp48_sqr_pck_basic(), fp48_sqr_pck_lazyr(), pp_add_k48_basic(), pp_add_k48_projc(), pp_dbl_k48_basic(), and pp_dbl_k48_projc().
fp8_dbl()
void fp8_dbl (fp8_t c, const fp8_t a)
Doubles an octic extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the octic extension field element to double.
Definition at line 212 of file relic_fpx_add.c.
References fp4_dbl().
Referenced by ep8_curve_mul_a(), ep8_map(), fp16_dbl(), fp16_sqr_basic(), fp16_sqr_cyc(), fp16_srt(), fp24_dbl(), fp24_sqr_basic(), fp48_back_cyc(), fp48_back_cyc_sim(), fp48_sqr_cyc_basic(), fp48_sqr_cyc_lazyr(), fp48_sqr_pck_basic(), fp48_sqr_pck_lazyr(), and pp_dbl_k48_projc().
fp8_neg()
void fp8_neg (fp8_t c, const fp8_t a)
Negates an octic extension field element. Computes c = -a.
Parameters
[out] c - the result.
[out] a - the octic extension field element to negate.
Definition at line 217 of file relic_fpx_add.c.
References fp4_neg().
Referenced by detect_opt(), ep8_map(), ep8_neg(), fp16_inv(), fp16_inv_cyc(), fp16_neg(), fp24_inv_cyc(), and fp24_neg().
fp9_add()
void fp9_add (fp9_t c, const fp9_t a, const fp9_t b)
Adds two nonic extension field elements. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first nonic extension field element.
[in] b - the second nonic extension field element.
Definition at line 222 of file relic_fpx_add.c.
References fp3_add.
Referenced by ep9_dbl_basic(), fp18_add(), fp18_mul_basic(), fp18_mul_dxs_basic(), fp18_mul_dxs_lazyr(), fp18_mul_unr(), fp18_sqr_basic(), fp18_sqr_unr(), fp54_back_cyc(), fp54_back_cyc_sim(), fp54_mul_dxs(), fp54_sqr_cyc_basic(), fp54_sqr_cyc_lazyr(), fp54_sqr_pck_basic(), fp54_sqr_pck_lazyr(), pp_add_k54_projc(), and pp_dbl_k54_projc().
fp9_sub()
void fp9_sub (fp9_t c, const fp9_t a, const fp9_t b)
Subtracts a nonic extension field element from another. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the nonic extension field element.
[in] b - the nonic extension field element.
Definition at line 228 of file relic_fpx_add.c.
References fp3_sub.
Referenced by ep9_add_basic(), ep9_dbl_basic(), fp18_inv(), fp18_mul_basic(), fp18_mul_dxs_basic(), fp18_sqr_basic(), fp18_sub(), fp54_back_cyc(), fp54_back_cyc_sim(), fp54_sqr_cyc_basic(), fp54_sqr_cyc_lazyr(), fp54_sqr_pck_basic(), fp54_sqr_pck_lazyr(), pp_add_k54_basic(), pp_add_k54_projc(), pp_dbl_k54_basic(), and pp_dbl_k54_projc().
fp9_dbl()
void fp9_dbl (fp9_t c, const fp9_t a)
Doubles a nonic extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the nonic extension field element to double.
Definition at line 234 of file relic_fpx_add.c.
References fp3_dbl.
Referenced by ep9_dbl_basic(), fp18_dbl(), fp18_sqr_basic(), fp54_back_cyc(), fp54_back_cyc_sim(), fp54_sqr_cyc_basic(), fp54_sqr_cyc_lazyr(), fp54_sqr_pck_basic(), fp54_sqr_pck_lazyr(), and pp_dbl_k54_projc().
fp9_neg()
void fp9_neg (fp9_t c, const fp9_t a)
Negates a nonic extension field element. Computes c = -a.
Parameters
[out] c - the result.
[out] a - the nonic extension field element to negate.
Definition at line 240 of file relic_fpx_add.c.
References fp3_neg().
Referenced by fp18_inv(), fp18_inv_cyc(), fp18_neg(), and pp_mil_k54().
fp12_add()
void fp12_add (fp12_t c, const fp12_t a, const fp12_t b)
Adds two dodecic extension field elements. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first dodecic extension field element.
[in] b - the second dodecic extension field element.
Definition at line 246 of file relic_fpx_add.c.
References fp6_add().
fp12_sub()
void fp12_sub (fp12_t c, const fp12_t a, const fp12_t b)
Subtracts a dodecic extension field element from another. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the first dodecic extension field element.
[in] b - the second dodecic extension field element.
Definition at line 251 of file relic_fpx_add.c.
References fp6_sub().
fp12_neg()
void fp12_neg (fp12_t c, const fp12_t a)
Negates a dodecic extension field element.
Parameters
[out] c - the result.
[out] a - the dodecic extension field element to negate.
Definition at line 256 of file relic_fpx_add.c.
References fp6_neg().
fp12_dbl()
void fp12_dbl (fp12_t c, const fp12_t a)
Doubles a dodecic extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to double.
Definition at line 261 of file relic_fpx_add.c.
References fp6_dbl().
fp16_add()
void fp16_add (fp16_t c, const fp16_t a, const fp16_t b)
Adds two sextadecic extension field elements. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first sextadecic extension field element.
[in] b - the second sextadecic extension field element.
Definition at line 266 of file relic_fpx_add.c.
References fp8_add().
fp16_sub()
void fp16_sub (fp16_t c, const fp16_t a, const fp16_t b)
Subtracts an sextadecic extension field element from another. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the sextadecic extension field element.
[in] b - the sextadecic extension field element.
Definition at line 271 of file relic_fpx_add.c.
References fp8_sub().
fp16_dbl()
void fp16_dbl (fp16_t c, const fp16_t a)
Doubles an sextadecic extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the sextadecic extension field element to double.
Definition at line 276 of file relic_fpx_add.c.
References fp8_dbl().
fp16_neg()
void fp16_neg (fp16_t c, const fp16_t a)
Negates an sextadecic extension field element. Computes c = -a.
Parameters
[out] c - the result.
[out] a - the sextadecic extension field element to negate.
Definition at line 281 of file relic_fpx_add.c.
References fp8_neg().
fp18_add()
void fp18_add (fp18_t c, const fp18_t a, const fp18_t b)
Adds two octdecic extension field elements. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first octdecic extension field element.
[in] b - the second octdecic extension field element.
Definition at line 286 of file relic_fpx_add.c.
References fp9_add().
Referenced by fp54_add(), fp54_inv(), fp54_mul_basic(), fp54_mul_dxs(), fp54_mul_lazyr(), fp54_sqr_basic(), and fp54_sqr_lazyr().
fp18_sub()
void fp18_sub (fp18_t c, const fp18_t a, const fp18_t b)
Subtracts an octdecic extension field element from another. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the first octdecic extension field element.
[in] b - the second octdecic extension field element.
Definition at line 291 of file relic_fpx_add.c.
References fp9_sub().
Referenced by fp54_inv(), fp54_mul_basic(), fp54_mul_dxs(), fp54_mul_lazyr(), fp54_sqr_basic(), fp54_sqr_lazyr(), and fp54_sub().
fp18_dbl()
void fp18_dbl (fp18_t c, const fp18_t a)
Doubles an octdecic extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element to double.
Definition at line 296 of file relic_fpx_add.c.
References fp9_dbl().
Referenced by fp54_dbl(), fp54_sqr_basic(), and fp54_sqr_lazyr().
fp18_neg()
void fp18_neg (fp18_t c, const fp18_t a)
Negates an octdecic extension field element.
Parameters
[out] c - the result.
[out] a - the octdecic extension field element to negate.
Definition at line 301 of file relic_fpx_add.c.
References fp9_neg().
Referenced by fp54_inv_cyc(), and fp54_neg().
fp24_add()
void fp24_add (fp24_t c, const fp24_t a, const fp24_t b)
Adds two 24-degree extension field elements. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first 24-degree extension field element.
[in] b - the second 24-degree extension field element.
Definition at line 306 of file relic_fpx_add.c.
References fp8_add().
Referenced by fp48_add(), fp48_mul_basic(), fp48_mul_dxs(), fp48_mul_lazyr(), fp48_sqr_basic(), and fp48_sqr_lazyr().
fp24_sub()
void fp24_sub (fp24_t c, const fp24_t a, const fp24_t b)
Subtracts a 24-degree extension field element from another. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the first 24-degree extension field element.
[in] b - the second 24-degree extension field element.
Definition at line 312 of file relic_fpx_add.c.
References fp8_sub().
Referenced by fp48_inv(), fp48_mul_basic(), fp48_mul_dxs(), fp48_mul_lazyr(), fp48_sqr_basic(), fp48_sqr_lazyr(), and fp48_sub().
fp24_neg()
void fp24_neg (fp24_t c, const fp24_t a)
Negates a 24-degree extension field element.
Parameters
[out] c - the result.
[out] a - the 24-degree extension field element to negate.
Definition at line 318 of file relic_fpx_add.c.
References fp8_neg().
Referenced by fp48_inv(), fp48_inv_cyc(), and fp48_neg().
fp24_dbl()
void fp24_dbl (fp24_t c, const fp24_t a)
Doubles a 24-degree extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the octic extension field element to double.
Definition at line 324 of file relic_fpx_add.c.
References fp8_dbl().
Referenced by fp48_dbl(), fp48_sqr_basic(), and fp48_sqr_lazyr().
fp48_add()
void fp48_add (fp48_t c, const fp48_t a, const fp48_t b)
Adds two 48-extension field elements. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first 48-extension field element.
[in] b - the second 48-extension field element.
Definition at line 330 of file relic_fpx_add.c.
References fp24_add().
fp48_sub()
void fp48_sub (fp48_t c, const fp48_t a, const fp48_t b)
Subtracts a 48-extension field element from another. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the first 48-extension field element.
[in] b - the second 48-extension field element.
Definition at line 335 of file relic_fpx_add.c.
References fp24_sub().
fp48_neg()
void fp48_neg (fp48_t c, const fp48_t a)
Negates a 48-extension field element.
Parameters
[out] c - the result.
[out] a - the 48-extension field element to negate.
Definition at line 340 of file relic_fpx_add.c.
References fp24_neg().
fp48_dbl()
void fp48_dbl (fp48_t c, const fp48_t a)
Doubles a 48-extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the 48-extension field element to double.
Definition at line 345 of file relic_fpx_add.c.
References fp24_dbl().
fp54_add()
void fp54_add (fp54_t c, const fp54_t a, const fp54_t b)
Adds two 54-extension field elements. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first 54-extension field element.
[in] b - the second 54-extension field element.
Definition at line 350 of file relic_fpx_add.c.
References fp18_add().
fp54_sub()
void fp54_sub (fp54_t c, const fp54_t a, const fp54_t b)
Subtracts a 54-extension field element from another. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the first 54-extension field element.
[in] b - the second 54-extension field element.
Definition at line 356 of file relic_fpx_add.c.
References fp18_sub().
fp54_neg()
void fp54_neg (fp54_t c, const fp54_t a)
Negates a 54-extension field element.
Parameters
[out] c - the result.
[out] a - the 54-extension field element to negate.
Definition at line 362 of file relic_fpx_add.c.
References fp18_neg().
fp54_dbl()
void fp54_dbl (fp54_t c, const fp54_t a)
Doubles a 54-extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the 54-extension field element to double.
Definition at line 368 of file relic_fpx_add.c.
References fp18_dbl().