RELIC: src/cp/relic_cp_ecss.c File Reference
relic_cp_ecss.c File Reference
Cryptographic protocols
#include "relic.h"
Functions
int cp_ecss_gen (bn_t d, ec_t q)
int cp_ecss_sig (bn_t e, bn_t s, const uint8_t *msg, size_t len, const bn_t d)
int cp_ecss_ver (bn_t e, bn_t s, const uint8_t *msg, size_t len, const ec_t q)
Detailed Description
Implementation of the Schnorr protocol.
Definition in file relic_cp_ecss.c.
Function Documentation
cp_ecss_gen()
int cp_ecss_gen (bn_t d, ec_t q)
Generates an Elliptic Curve Schnorr Signature key pair.
Parameters
[out] d - the private key.
[in] q - the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_ecss.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), ec_curve_get_ord, ec_mul_gen, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_ecss_sig()
int cp_ecss_sig (bn_t e, bn_t s, const uint8_t * msg, size_t len, const bn_t d)
Signs a message using the Elliptic Curve Schnorr Signature.
Parameters
[out] r - the first component of the signature.
[out] s - the second component of the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] d - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 60 of file relic_cp_ecss.c.
References bn_add(), bn_bits(), bn_free, bn_is_zero(), bn_mod, bn_mul, bn_new, bn_null, bn_rand_mod(), bn_read_bin(), bn_rsh(), bn_sub(), bn_write_bin(), ec_curve_get_ord, ec_free, ec_get_x, ec_mul_gen, ec_new, ec_null, ERR_NO_MEMORY, md_map, RLC_ALLOCA, RLC_CATCH_ANY, RLC_CEIL, RLC_ERR, RLC_FC_BYTES, RLC_FINALLY, RLC_FREE, RLC_MD_LEN, RLC_OK, RLC_THROW, and RLC_TRY.
cp_ecss_ver()
int cp_ecss_ver (bn_t e, bn_t s, const uint8_t * msg, size_t len, const ec_t q)
Verifies a message signed with the Elliptic Curve Schnorr Signature using the basic method.
Parameters
[out] r - the first component of the signature.
[out] s - the second component of the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] q - the public key.
Returns
a boolean value indicating if the signature is valid.
Definition at line 125 of file relic_cp_ecss.c.
References bn_bits(), bn_cmp(), bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, bn_read_bin(), bn_rsh(), bn_sign(), bn_write_bin(), dv_cmp_sec(), ec_curve_get_ord, ec_free, ec_get_x, ec_mul_sim_gen, ec_new, ec_null, ERR_CAUGHT, ERR_NO_MEMORY, md_map, RLC_ALLOCA, RLC_CATCH_ANY, RLC_CEIL, RLC_FC_BYTES, RLC_FINALLY, RLC_FREE, RLC_LT, RLC_MD_LEN, RLC_MIN, RLC_NE, RLC_POS, RLC_THROW, and RLC_TRY.