RELIC: src/pp/relic_pp_exp_k8.c File Reference
relic_pp_exp_k8.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_util.h"
Functions
void pp_exp_k8 (fp8_t c, fp8_t a)
Detailed Description
Implementation of the final exponentiation for curves of embedding degree 8.
Definition in file relic_pp_exp_k8.c.
Function Documentation
pp_exp_k8()
void pp_exp_k8 (fp8_t c, fp8_t a)
Computes the final exponentiation for a pairing defined over curves of embedding degree 8. Computes c = a^(p^8 - 1)/r.
Parameters
[out] c - the result.
[in] a - the extension field element to exponentiate.
Definition at line 40 of file relic_pp_exp_k8.c.
References bn_add_dig(), bn_free, bn_lsh(), bn_new, bn_null, bn_rsh(), bn_set_dig(), ERR_CAUGHT, fp8_conv_cyc(), fp8_copy(), fp8_exp_cyc(), fp8_frb(), fp8_free, fp8_inv_cyc(), fp8_mul, fp8_new, fp8_null, fp8_sqr_cyc(), fp_prime_get_par(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by gt_rand(), pp_map_oatep_k8(), and pp_map_sim_oatep_k8().