RELIC: src/cp/relic_cp_sokaka.c File Reference
relic_cp_sokaka.c File Reference
#include "relic.h"
Functions
int cp_sokaka_gen (bn_t master)
int cp_sokaka_gen_prv (sokaka_t k, const char *id, bn_t master)
int cp_sokaka_key (uint8_t *key, size_t key_len, const char *id1, const sokaka_t k, const char *id2)
Detailed Description
Implementation of the Sakai-Ohgishi-Kasahara Identity-Based Non-Interactive Authenticated Key Agreement scheme.
Definition in file relic_cp_sokaka.c.
Function Documentation
cp_sokaka_gen()
int cp_sokaka_gen (bn_t master)
Generates a master key for the SOKAKA identity-based non-interactive authenticated key agreement protocol.
Parameters
[out] master - the master key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 39 of file relic_cp_sokaka.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), pc_get_ord, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_sokaka_gen_prv()
int cp_sokaka_gen_prv (sokaka_t k, const char * id, bn_t master)
Generates a private key for the SOKAKA protocol.
Parameters
[out] k - the private key.
[in] id - the identity.
[in] master - the master key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 60 of file relic_cp_sokaka.c.
References g1_map, g1_mul(), g2_map, g2_mul(), pc_map_is_type1, and RLC_OK.
cp_sokaka_key()
int cp_sokaka_key (uint8_t * key, size_t key_len, const char * id1, const sokaka_t k, const char * id2)
Computes a shared key between two entities.
Parameters
[out] key - the shared key.
[int] key_len - the intended shared key length in bytes.
[in] id1 - the first identity.
[in] k - the private key of the first identity.
[in] id2 - the second identity.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 73 of file relic_cp_sokaka.c.
References ERR_NO_MEMORY, ERR_NO_VALID, g1_free, g1_map, g1_new, g1_null, g2_free, g2_map, g2_new, g2_null, gt_free, gt_new, gt_null, gt_size_bin, gt_write_bin, md_kdf(), pc_map, pc_map_is_type1, RLC_ALLOCA, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_FREE, RLC_OK, RLC_THROW, and RLC_TRY.