RELIC: src/arch/relic_arch_avr.c File Reference
relic_arch_avr.c File Reference
Architecture-dependent utilities
#include <avr/pgmspace.h>
Functions
void arch_init (void)
void arch_clean (void)
void arch_copy_rom (char *dest, const char *src, size_t len)
uint_t arch_lzcnt ()
uint_t arch_tzcnt ()
Detailed Description
Implementation of AVR-dependent routines.
Definition in file relic_arch_avr.c.
Function Documentation
arch_init()
void arch_init (void)
Performs architecture-dependent initialization.
Definition at line 38 of file relic_arch_avr.c.
arch_clean()
void arch_clean (void)
Performs architecture-dependent finalization.
Definition at line 41 of file relic_arch_avr.c.
arch_copy_rom()
void arch_copy_rom (char * dest, const char * src, size_t len)
Definition at line 44 of file relic_arch_avr.c.
arch_lzcnt()
uint_t arch_lzcnt ()
Definition at line 54 of file relic_arch_avr.c.
Referenced by bn_smb_jac(), and util_bits_dig().
arch_tzcnt()
uint_t arch_tzcnt ()
Definition at line 66 of file relic_arch_avr.c.
Referenced by bn_smb_jac().