RELIC: src/fp/relic_fp_sqr.c File Reference
relic_fp_sqr.c File Reference
Prime field arithmetic
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_bn_low.h"
Functions
static void fp_sqr_karat_imp (dv_t c, const fp_t a, size_t size, uint_t level)
void fp_sqr_basic (fp_t c, const fp_t a)
void fp_sqr_comba (fp_t c, const fp_t a)
void fp_sqr_integ (fp_t c, const fp_t a)
void fp_sqr_karat (fp_t c, const fp_t a)
Detailed Description
Implementation of the multiple precision integer arithmetic squaring functions.
Definition in file relic_fp_sqr.c.
Function Documentation
fp_sqr_karat_imp()
static void fp_sqr_karat_imp (dv_t c, const fp_t a, size_t size, uint_t level) static
Computes the square of a multiple precision integer using recursive Karatsuba squaring.
Parameters
[out] c - the result.
[in] a - the prime field element to square.
[in] size - the number of digits to square.
[in] level - the number of Karatsuba steps to apply.
Definition at line 52 of file relic_fp_sqr.c.
References bn_add1_low(), bn_addn_low(), bn_muln_low(), bn_sqra_low(), bn_sqrn_low(), bn_sub1_low(), bn_subn_low(), dv_free, dv_new, dv_null, dv_zero(), ERR_CAUGHT, fp_sqr_karat_imp(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp_sqr_karat(), and fp_sqr_karat_imp().
fp_sqr_basic()
void fp_sqr_basic (fp_t c, const fp_t a)
Squares a prime field element using Schoolbook squaring.
Parameters
[out] c - the result.
[in] a - the prime field element to square.
Definition at line 165 of file relic_fp_sqr.c.
References bn_sqra_low(), dv_new, dv_null, dv_zero(), ERR_CAUGHT, fp_free, fp_rdc, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
fp_sqr_comba()
void fp_sqr_comba (fp_t c, const fp_t a)
Squares a prime field element using Comba squaring.
Parameters
[out] c - the result.
[in] a - the prime field element to square.
Definition at line 195 of file relic_fp_sqr.c.
References dv_new, dv_null, ERR_CAUGHT, fp_free, fp_rdc, fp_sqrn_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp_sqr_integ()
void fp_sqr_integ (fp_t c, const fp_t a)
Squares two prime field elements using squaring integrated with modular reduction.
Parameters
[out] c - the result.
[in] a - the binary field element to square.
Definition at line 218 of file relic_fp_sqr.c.
References fp_sqrm_low().
fp_sqr_karat()
void fp_sqr_karat (fp_t c, const fp_t a)
Squares a prime field element using Karatsuba squaring.
Parameters
[out] c - the result.
[in] a - the prime field element to square.
Definition at line 226 of file relic_fp_sqr.c.
References dv_free, dv_new, dv_null, dv_zero(), ERR_CAUGHT, FP_KARAT, fp_rdc, fp_sqr_karat_imp(), fp_sqrn_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.