RELIC: src/md/relic_md_hmac.c File Reference
relic_md_hmac.c File Reference
Hash functions
#include <string.h>
#include "relic_conf.h"
#include "relic_core.h"
#include "relic_util.h"
#include "relic_md.h"
Macros
#define BLOCK_SIZE 64
Functions
void md_hmac (uint8_t *mac, const uint8_t *in, size_t in_len, const uint8_t *key, size_t key_len)
Detailed Description
Implementation of Hash-based Message Authentication Code.
Definition in file relic_md_hmac.c.
Macro Definition Documentation
BLOCK_SIZE
#define BLOCK_SIZE 64
Referenced by md_hmac().
Function Documentation
md_hmac()
void md_hmac (uint8_t * mac, const uint8_t * in, size_t in_len, const uint8_t * key, size_t key_len)
Computes a Message Authentication Code through HMAC.
Parameters
[out] mac - the authentication.
[in] in - the date to authenticate.
[in] in_len - the number of bytes to authenticate.
[in] key - the cryptographic key.
[in] key_len - the size of the key in bytes.
Definition at line 43 of file relic_md_hmac.c.
References BLOCK_SIZE, ERR_NO_MEMORY, md_map, RLC_ALLOCA, RLC_FREE, RLC_MAX, RLC_MD_LEN, and RLC_THROW.
Referenced by cp_cmlhs_sig(), cp_ecies_dec(), and cp_ecies_enc().