RELIC: src/fp/relic_fp_exp.c File Reference
relic_fp_exp.c File Reference
Prime field arithmetic
#include "relic_core.h"
#include "relic_util.h"
Functions
void fp_exp_basic (fp_t c, const fp_t a, const bn_t b)
void fp_exp_slide (fp_t c, const fp_t a, const bn_t b)
void fp_exp_monty (fp_t c, const fp_t a, const bn_t b)
void fp_exp_dig (fp_t c, const fp_t a, dig_t b)
Detailed Description
Implementation of prime field exponentiation functions.
Definition in file relic_fp_exp.c.
Function Documentation
fp_exp_basic()
void fp_exp_basic (fp_t c, const fp_t a, const bn_t b)
Exponentiates a prime field element using the binary method.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 41 of file relic_fp_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), ERR_CAUGHT, fp_copy(), fp_free, fp_inv, fp_mul, fp_new, fp_null, fp_set_dig(), fp_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
fp_exp_slide()
void fp_exp_slide (fp_t c, const fp_t a, const bn_t b)
Exponentiates a prime field element using the sliding window method.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 84 of file relic_fp_exp.c.
References bn_is_zero(), bn_rec_slw(), bn_sign(), ERR_CAUGHT, fp_copy(), fp_free, fp_inv, fp_mul, fp_new, fp_null, fp_set_dig(), fp_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_THROW, RLC_TRY, RLC_WIDTH, and util_bits_dig().
fp_exp_monty()
void fp_exp_monty (fp_t c, const fp_t a, const bn_t b)
Exponentiates a prime field element using the constant-time Montgomery powering ladder method.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 151 of file relic_fp_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), dv_swap_sec(), ERR_CAUGHT, fp_copy(), fp_free, fp_inv, fp_mul, fp_new, fp_null, fp_set_dig(), fp_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_NEG, RLC_THROW, and RLC_TRY.
fp_exp_dig()
void fp_exp_dig (fp_t c, const fp_t a, dig_t b)
Computes a power of a field element by a small exponent.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 193 of file relic_fp_exp.c.
References ERR_CAUGHT, fp_copy(), fp_free, fp_mul, fp_new, fp_null, fp_set_dig(), fp_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, RLC_TRY, and util_bits_dig().