RELIC: src/epx/relic_ep2_frb.c File Reference
relic_ep2_frb.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
void ep2_frb (ep2_t r, const ep2_t p, int i)
Detailed Description
Implementation of frobenius action on prime elliptic curves over a quadratic extension field.
Definition in file relic_ep2_frb.c.
Function Documentation
ep2_frb()
void ep2_frb (ep2_t r, const ep2_t p, int i)
Computes a power of the Gailbraith-Lin-Scott homomorphism of a point represented in affine coordinates on a twisted elliptic curve over a quadratic exension. That is, Psi^i(P) = Twist(P)(Frob^i(unTwist(P)). On the trace-zero group of a quadratic twist, consists of a power of the Frobenius map of a point represented in affine coordinates in an elliptic curve over a quadratic exension. Computes Frob^i(P) = (p^i)P.
Parameters
[out] r - the result in affine coordinates.
[in] p - a point in affine coordinates.
[in] i - the power of the Frobenius map.
Definition at line 39 of file relic_ep2_frb.c.
References bn_free, bn_new, bn_null, core_get(), ep2_copy(), ep2_curve_opt_a(), _ctx_t::ep2_frb, ep2_mul_basic(), ERR_NO_MEMORY, fp2_frb(), fp2_mul, fp_prime_get_par(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, RLC_TRY, and RLC_ZERO.
Referenced by ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep2_mul_gls_imp(), ep2_mul_reg_gls(), ep2_mul_sim_endom(), ep2_mul_sim_lot(), and pp_fin_k12_oatep().