RELIC: src/fpx/relic_fp12_sqr.c File Reference
relic_fp12_sqr.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
Functions
void fp12_sqr_basic (fp12_t c, const fp12_t a)
void fp12_sqr_cyc_basic (fp12_t c, const fp12_t a)
void fp12_sqr_pck_basic (fp12_t c, const fp12_t a)
void fp12_sqr_unr (dv12_t c, const fp12_t a)
void fp12_sqr_lazyr (fp12_t c, const fp12_t a)
void fp12_sqr_cyc_lazyr (fp12_t c, const fp12_t a)
void fp12_sqr_pck_lazyr (fp12_t c, const fp12_t a)
Detailed Description
Implementation of squaring in a dodecic extension of a prime field.
Definition in file relic_fp12_sqr.c.
Function Documentation
fp12_sqr_basic()
void fp12_sqr_basic (fp12_t c, const fp12_t a)
Computes the square of a dodecic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to square.
Definition at line 42 of file relic_fp12_sqr.c.
References ERR_CAUGHT, fp6_add(), fp6_dbl(), fp6_free, fp6_mul, fp6_mul_art(), fp6_new, fp6_null, fp6_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp12_sqr_cyc_basic()
void fp12_sqr_cyc_basic (fp12_t c, const fp12_t a)
Computes the square of a cyclotomic dodecic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 69 of file relic_fp12_sqr.c.
References ERR_CAUGHT, fp2_add, fp2_dbl, fp2_free, fp2_mul_nor, fp2_new, fp2_null, fp2_sqr, fp2_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp12_sqr_pck_basic()
void fp12_sqr_pck_basic (fp12_t c, const fp12_t a)
Computes the square of a compressed cyclotomic extension field element.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 163 of file relic_fp12_sqr.c.
References ERR_CAUGHT, fp2_add, fp2_dbl, fp2_free, fp2_mul_nor, fp2_new, fp2_null, fp2_sqr, fp2_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp12_sqr_unr()
void fp12_sqr_unr (dv12_t c, const fp12_t a)
Computes the square of a dodecic extension field element without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to square.
Definition at line 237 of file relic_fp12_sqr.c.
References dv4_free, dv4_new, dv4_null, ERR_CAUGHT, fp2_addc_low(), fp2_addd_low(), fp2_addm_low(), fp2_copy(), fp2_nord_low(), fp2_subc_low(), fp2_subm_low(), fp4_free, fp4_mul_unr(), fp4_new, fp4_null, fp4_sqr_unr(), fp_hlvd_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp12_sqr_lazyr().
fp12_sqr_lazyr()
void fp12_sqr_lazyr (fp12_t c, const fp12_t a)
Computes the square of a dodecic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to square.
Definition at line 340 of file relic_fp12_sqr.c.
References dv12_free, dv12_new, dv12_null, ERR_CAUGHT, fp12_sqr_unr(), fp2_rdcn_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp12_sqr_cyc_lazyr()
void fp12_sqr_cyc_lazyr (fp12_t c, const fp12_t a)
Computes the square of a cyclotomic dodecic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 359 of file relic_fp12_sqr.c.
References dv2_free, dv2_new, dv2_null, ERR_CAUGHT, fp2_addc_low(), fp2_addm_low(), fp2_dblm_low(), fp2_free, fp2_new, fp2_norh_low(), fp2_norm_low(), fp2_null, fp2_rdcn_low(), fp2_sqrm_low(), fp2_sqrn_low(), fp2_subc_low(), fp2_subm_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp12_sqr_pck_lazyr()
void fp12_sqr_pck_lazyr (fp12_t c, const fp12_t a)
Computes the square of a compressed cyclotomic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 455 of file relic_fp12_sqr.c.
References dv2_free, dv2_new, dv2_null, ERR_CAUGHT, fp2_addc_low(), fp2_addm_low(), fp2_dblm_low(), fp2_free, fp2_new, fp2_norh_low(), fp2_norm_low(), fp2_null, fp2_rdcn_low(), fp2_sqrm_low(), fp2_sqrn_low(), fp2_subc_low(), fp2_subm_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.