RELIC: src/cp/relic_cp_bdpe.c File Reference
relic_cp_bdpe.c File Reference
Cryptographic protocols
#include "relic.h"
Functions
int cp_bdpe_gen (bdpe_t pub, bdpe_t prv, dig_t block, size_t bits)
int cp_bdpe_enc (uint8_t *out, size_t *out_len, dig_t in, const bdpe_t pub)
int cp_bdpe_dec (dig_t *out, const uint8_t *in, size_t in_len, const bdpe_t prv)
Detailed Description
Implementation of Benaloh's Dense Probabilistic Encryption cryptosystem.
Definition in file relic_cp_bdpe.c.
Function Documentation
cp_bdpe_gen()
int cp_bdpe_gen (bdpe_t pub, bdpe_t prv, dig_t block, size_t bits)
Generates a key pair for Benaloh's Dense Probabilistic Encryption.
Parameters
[out] pub - the public key.
[out] prv - the private key.
[in] block - the block size.
[in] bits - the key length in bits.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_bdpe.c.
References bn_add_dig(), bn_cmp_dig(), bn_copy(), bn_div_dig(), bn_free, bn_gcd_dig(), bn_gen_prime, bn_is_prime(), bn_is_prime_basic(), bn_mul, bn_mul_dig(), bn_mxp, bn_new, bn_null, bn_rand(), bn_set_dig(), bn_sub_dig(), ERR_NO_VALID, RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FINALLY, RLC_OK, RLC_POS, RLC_THROW, RLC_TRY, and util_bits_dig().
cp_bdpe_enc()
int cp_bdpe_enc (uint8_t * out, size_t * out_len, dig_t in, const bdpe_t pub)
Encrypts using Benaloh's cryptosystem.
Parameters
[out] out - the output buffer.
[in,out] out_len - the buffer capacity and number of bytes written.
[in] in - the plaintext as a small integer.
[in] pub - the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 110 of file relic_cp_bdpe.c.
References bn_free, bn_mod, bn_mul, bn_mxp, bn_mxp_dig(), bn_new, bn_null, bn_rand_mod(), bn_set_dig(), bn_size_bin(), bn_write_bin(), RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_bdpe_dec()
int cp_bdpe_dec (dig_t * out, const uint8_t * in, size_t in_len, const bdpe_t prv)
Decrypts using Benaloh's cryptosystem.
Parameters
[out] out - the decrypted small integer.
[in] in - the input buffer.
[in] in_len - the number of bytes to encrypt.
[in] prv - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 155 of file relic_cp_bdpe.c.
References bn_add_dig(), bn_cmp(), bn_div_dig(), bn_free, bn_mul, bn_mxp, bn_mxp_dig(), bn_new, bn_null, bn_read_bin(), bn_size_bin(), bn_sub(), RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.