RELIC: src/bc/rijndael-alg-fst.h File Reference
rijndael-alg-fst.h File Reference
Macros
#define MAXKC (256/32)
#define MAXKB (256/8)
#define MAXNR 14
Typedefs
typedef uint8_t u8
typedef uint16_t u16
typedef uint32_t u32
Functions
int rijndaelKeySetupEnc (u32 rk[], const u8 cipherKey[], int keyBits)
int rijndaelKeySetupDec (u32 rk[], const u8 cipherKey[], int keyBits)
void rijndaelEncrypt (const u32 rk[], int Nr, const u8 pt[16], u8 ct[16])
void rijndaelDecrypt (const u32 rk[], int Nr, const u8 ct[16], u8 pt[16])
Macro Definition Documentation
MAXKC
#define MAXKC (256/32)
rijndael-alg-fst.h
Version
3.0 (December 2000)
Optimised ANSI C code for the Rijndael cipher (now AES)
Author
Vincent Rijmen vince.nosp@m.nt.r.nosp@m.ijmen.nosp@m.@esa.nosp@m.t.kul.nosp@m.euve.nosp@m.n.ac..nosp@m.be
Antoon Bosselaers antoo.nosp@m.n.bo.nosp@m.ssela.nosp@m.ers@.nosp@m.esat..nosp@m.kule.nosp@m.uven..nosp@m.ac.b.nosp@m.e
Paulo Barreto paulo.nosp@m..bar.nosp@m.reto@.nosp@m.terr.nosp@m.a.com.nosp@m..br
This code is hereby placed in the public domain.
THIS SOFTWARE IS PROVIDED BY THE AUTHORS ''AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHORS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition at line 29 of file rijndael-alg-fst.h.
MAXKB
#define MAXKB (256/8)
Definition at line 30 of file rijndael-alg-fst.h.
Referenced by makeKey(), and makeKey2().
MAXNR
#define MAXNR 14
Definition at line 31 of file rijndael-alg-fst.h.
Typedef Documentation
u8
typedef uint8_t u8
Definition at line 33 of file rijndael-alg-fst.h.
u16
typedef uint16_t u16
Definition at line 34 of file rijndael-alg-fst.h.
u32
typedef uint32_t u32
Definition at line 35 of file rijndael-alg-fst.h.
Function Documentation
rijndaelKeySetupEnc()
int rijndaelKeySetupEnc (u32 rk[], const u8 cipherKey[], int keyBits)
Expand the cipher key into the encryption key schedule.
Returns
the number of rounds for the given cipher key size.
Definition at line 729 of file rijndael-alg-fst.c.
References GETU32, rcon, and Te4.
Referenced by makeKey(), makeKey2(), and rijndaelKeySetupDec().
rijndaelKeySetupDec()
int rijndaelKeySetupDec (u32 rk[], const u8 cipherKey[], int keyBits)
Expand the cipher key into the decryption key schedule.
Returns
the number of rounds for the given cipher key size.
Definition at line 815 of file rijndael-alg-fst.c.
References rijndaelKeySetupEnc(), Td0, Td1, Td2, Td3, and Te4.
Referenced by makeKey(), and makeKey2().
rijndaelEncrypt()
void rijndaelEncrypt (const u32 rk[], int Nr, const u8 pt[16], u8 ct[16])
Definition at line 855 of file rijndael-alg-fst.c.
References GETU32, PUTU32, Te0, Te1, Te2, Te3, and Te4.
Referenced by blockDecrypt(), blockEncrypt(), and padEncrypt().
rijndaelDecrypt()
void rijndaelDecrypt (const u32 rk[], int Nr, const u8 ct[16], u8 pt[16])
Definition at line 1036 of file rijndael-alg-fst.c.
References GETU32, PUTU32, Td0, Td1, Td2, Td3, and Td4.
Referenced by blockDecrypt(), and padDecrypt().