RELIC: src/ep/relic_ep_norm.c File Reference
relic_ep_norm.c File Reference
Elliptic curves over prime fields
#include "relic_core.h"
Functions
static void ep_norm_imp (ep_t r, const ep_t p, int inv)
void ep_norm (ep_t r, const ep_t p)
void ep_norm_sim (ep_t *r, const ep_t *t, int n)
Detailed Description
Implementation of point normalization on prime elliptic curves.
Definition in file relic_ep_norm.c.
Function Documentation
ep_norm_imp()
static void ep_norm_imp (ep_t r, const ep_t p, int inv) static
Normalizes a point represented in projective coordinates.
Parameters
r - the result.
p - the point to normalize.
inv - the flag to indicate if z is already inverted.
Definition at line 47 of file relic_ep_norm.c.
References BASIC, ep_copy(), ERR_CAUGHT, fp_copy(), fp_free, fp_inv, fp_mul, fp_new, fp_null, fp_set_dig(), fp_sqr, JACOB, PROJC, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep_norm(), and ep_norm_sim().
ep_norm()
void ep_norm (ep_t r, const ep_t p)
Converts a point to affine coordinates.
Parameters
[out] r - the result.
[in] p - the point to convert.
Definition at line 96 of file relic_ep_norm.c.
References BASIC, ep_copy(), ep_is_infty(), ep_norm_imp(), and ep_set_infty().
Referenced by ep_curve_set(), ep_map_sswum_impl(), ep_mul_basic(), ep_mul_cof(), ep_mul_combs_endom(), ep_mul_combs_plain(), ep_mul_dig(), ep_mul_fix_basic(), ep_mul_fix_combd(), ep_mul_fix_plain(), ep_mul_glv_imp(), ep_mul_monty(), ep_mul_naf_imp(), ep_mul_pre_combd(), ep_mul_pre_combs(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_mul_sim_basic(), ep_mul_sim_dig(), ep_mul_sim_endom(), ep_mul_sim_joint(), ep_mul_sim_lot_endom(), ep_mul_sim_lot_plain(), ep_mul_sim_plain(), ep_mul_sim_trick(), ep_mul_slide(), ep_on_curve(), ep_tab(), ep_write_bin(), pp_map_k24(), pp_map_k48(), pp_map_oatep_k12(), pp_map_oatep_k16(), pp_map_oatep_k18(), pp_map_oatep_k8(), pp_map_sim_k24(), pp_map_sim_k48(), pp_map_sim_oatep_k12(), pp_map_sim_oatep_k16(), pp_map_sim_oatep_k18(), pp_map_sim_oatep_k8(), pp_map_sim_tatep_k1(), pp_map_sim_tatep_k12(), pp_map_sim_tatep_k16(), pp_map_sim_tatep_k18(), pp_map_sim_tatep_k2(), pp_map_sim_weilp_k1(), pp_map_sim_weilp_k12(), pp_map_sim_weilp_k16(), pp_map_sim_weilp_k18(), pp_map_sim_weilp_k2(), pp_map_tatep_k1(), pp_map_tatep_k12(), pp_map_tatep_k16(), pp_map_tatep_k18(), pp_map_tatep_k2(), pp_map_weilp_k1(), pp_map_weilp_k12(), pp_map_weilp_k16(), pp_map_weilp_k18(), pp_map_weilp_k2(), pp_norm_k1(), and pp_norm_k2().
ep_norm_sim()
void ep_norm_sim (ep_t * r, const ep_t * t, int n)
Converts multiple points to affine coordinates.
Parameters
[out] r - the result.
[in] t - the points to convert.
[in] n - the number of points.
Definition at line 112 of file relic_ep_norm.c.
References ep_is_infty(), ep_norm_imp(), ERR_CAUGHT, ERR_NO_MEMORY, fp_copy(), fp_free, fp_inv_sim(), fp_new, fp_null, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by ep_mul_pre_basic(), ep_mul_pre_combd(), ep_mul_pre_combs(), ep_mul_sim_joint(), ep_mul_sim_trick(), ep_mul_slide(), and ep_tab().