RELIC: src/fpx/relic_fpx_frb.c File Reference
relic_fpx_frb.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fpx_low.h"
Functions
void fp2_frb (fp2_t c, const fp2_t a, int i)
void fp3_frb (fp3_t c, const fp3_t a, int i)
void fp4_frb (fp4_t c, const fp4_t a, int i)
void fp6_frb (fp6_t c, const fp6_t a, int i)
void fp8_frb (fp8_t c, const fp8_t a, int i)
void fp9_frb (fp9_t c, const fp9_t a, int i)
void fp12_frb (fp12_t c, const fp12_t a, int i)
void fp16_frb (fp16_t c, const fp16_t a, int i)
void fp18_frb (fp18_t c, const fp18_t a, int i)
void fp24_frb (fp24_t c, const fp24_t a, int i)
void fp48_frb (fp48_t c, const fp48_t a, int i)
void fp54_frb (fp54_t c, const fp54_t a, int i)
Detailed Description
Implementation of frobenius action in extensions defined over prime fields.
Definition in file relic_fpx_frb.c.
Function Documentation
fp2_frb()
void fp2_frb (fp2_t c, const fp2_t a, int i)
Computes a power of the Frobenius map of a quadratic extension field element. When i is odd, this is the same as computing the conjugate of the extension field element.
Parameters
[out] c - the result.
[in] a - the quadratic extension element to conjugate.
[in] i - the power of the Frobenius map.
Definition at line 39 of file relic_fpx_frb.c.
References fp2_copy(), fp_copy(), and fp_neg.
Referenced by ep2_frb(), fp12_frb(), fp2_is_sqr(), fp4_frb(), and fp6_frb().
fp3_frb()
void fp3_frb (fp3_t c, const fp3_t a, int i)
Computes a power of the Frobenius map of a cubic extension field element.
Parameters
[out] c - the result.
[in] a - the cubic extension element to exponentiate.
[in] i - the power of the Frobenius map.
Definition at line 52 of file relic_fpx_frb.c.
References fp3_copy(), and fp3_mul_frb().
Referenced by ep3_frb(), fp18_frb(), fp3_is_sqr(), fp3_srt(), and fp9_frb().
fp4_frb()
void fp4_frb (fp4_t c, const fp4_t a, int i)
Computes a power of the Frobenius endomorphism of a quartic extension field element. Computes c = a^p^i.
Parameters
[out] c - the result.
[in] a - a quartic extension field element.
[in] i - the power of the Frobenius map.
Definition at line 64 of file relic_fpx_frb.c.
References fp2_frb(), fp2_mul_frb(), fp4_copy(), and fp_prime_get_mod18().
Referenced by ep4_frb(), fp4_is_sqr(), and fp8_frb().
fp6_frb()
void fp6_frb (fp6_t c, const fp6_t a, int i)
Computes a power of the Frobenius endomorphism of a sextic extension field element. Computes c = a^p^i.
Parameters
[out] c - the result.
[in] a - a sextic extension field element.
[in] i - the power of the Frobenius map.
Definition at line 79 of file relic_fpx_frb.c.
References fp2_frb(), fp2_mul_frb(), and fp6_copy().
Referenced by fp12_frb().
fp8_frb()
void fp8_frb (fp8_t c, const fp8_t a, int i)
Computes a power of the Frobenius endomorphism of an octic extension field element. Computes c = a^p^i.
Parameters
[out] c - the result.
[in] a - an octic extension field element.
[in] i - the power of the Frobenius map.
Definition at line 91 of file relic_fpx_frb.c.
References fp2_mul_frb(), fp4_frb(), fp4_mul_art(), fp8_copy(), and fp_prime_get_mod8().
Referenced by ep8_frb(), fp16_frb(), fp24_frb(), fp8_is_sqr(), and pp_exp_k8().
fp9_frb()
void fp9_frb (fp9_t c, const fp9_t a, int i)
Computes a power of the Frobenius endomorphism of a nonic extension field element. Computes c = a^p^i.
Parameters
[out] c - the result.
[in] a - a nonic extension field element.
[in] i - the power of the Frobenius map.
Definition at line 105 of file relic_fpx_frb.c.
References fp3_frb(), fp3_mul_frb(), and fp9_copy().
Referenced by fp18_frb(), and pp_mil_k54().
fp12_frb()
void fp12_frb (fp12_t c, const fp12_t a, int i)
Computes the Frobenius endomorphism of a dodecic extension element. Computes c = a^p.
Parameters
[out] c - the result.
[in] a - a dodecic extension field element.
[in] i - the power of the Frobenius map.
Definition at line 117 of file relic_fpx_frb.c.
References fp12_copy(), fp2_frb(), fp2_mul_frb(), and fp6_frb().
Referenced by fp12_conv_cyc(), fp12_exp_cyc_sim(), fp12_test_cyc(), pp_exp_b12(), pp_exp_bn(), and pp_exp_sm9().
fp16_frb()
void fp16_frb (fp16_t c, const fp16_t a, int i)
Computes a power of the Frobenius endomorphism of an sextadecic extension field element. Computes c = a^p^i.
Parameters
[out] c - the result.
[in] a - an sextadecic extension field element.
[in] i - the power of the Frobenius map.
Definition at line 131 of file relic_fpx_frb.c.
References fp16_copy(), fp2_mul_frb(), fp4_mul_art(), fp8_frb(), fp8_mul_art(), and fp_prime_get_mod8().
Referenced by fp16_is_sqr(), pp_exp_afg16(), pp_exp_fm16(), pp_exp_kss(), pp_fin_k16_oatep(), pp_map_oatep_k16(), and pp_map_sim_oatep_k16().
fp18_frb()
void fp18_frb (fp18_t c, const fp18_t a, int i)
Computes the Frobenius endomorphism of an octdecic extension element. Computes c = a^(p^i).
Parameters
[out] c - the result.
[in] a - an octdecic extension field element.
[in] i - the power of the Frobenius map.
Definition at line 151 of file relic_fpx_frb.c.
References fp18_copy(), fp3_frb(), fp3_mul_frb(), and fp9_frb().
Referenced by fp18_conv_cyc(), fp18_test_cyc(), fp54_frb(), pp_exp_fm(), pp_exp_kss(), pp_exp_sg(), and pp_fin_k18_oatep().
fp24_frb()
void fp24_frb (fp24_t c, const fp24_t a, int i)
Computes the Frobenius endomorphism of a 24-degree extension element. Computes c = a^p.
Parameters
[out] c - the result.
[in] a - a 24-degree extension field element.
[in] i - the power of the Frobenius map.
Definition at line 165 of file relic_fpx_frb.c.
References fp24_copy(), fp2_mul_frb(), fp4_mul_art(), fp8_frb(), and fp_prime_get_mod8().
Referenced by fp24_conv_cyc(), fp24_test_cyc(), fp48_frb(), and pp_exp_k24().
fp48_frb()
void fp48_frb (fp48_t c, const fp48_t a, int i)
Computes the Frobenius endomorphism of a 48-extension element. Computes c = a^p.
Parameters
[out] c - the result.
[in] a - a 48-extension field element.
[in] i - the power of the Frobenius map.
Definition at line 184 of file relic_fpx_frb.c.
References fp24_frb(), fp2_mul_frb(), fp48_copy(), fp4_mul_art(), fp8_mul_art(), and fp_prime_get_mod8().
Referenced by fp48_conv_cyc(), fp48_test_cyc(), and pp_exp_k48().
fp54_frb()
void fp54_frb (fp54_t c, const fp54_t a, int i)
Computes the Frobenius endomorphism of a 54-extension element. Computes c = a^p.
Parameters
[out] c - the result.
[in] a - a 54-extension field element.
[in] i - the power of the Frobenius map.
Definition at line 206 of file relic_fpx_frb.c.
References fp18_frb(), fp3_mul_frb(), fp54_copy(), and fp9_mul_art().
Referenced by fp54_conv_cyc(), fp54_test_cyc(), and pp_exp_k54().