RELIC: src/fpx/relic_fpx_cmp.c File Reference
relic_fpx_cmp.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fpx_low.h"
Functions
int fp2_cmp (const fp2_t a, const fp2_t b)
int fp2_cmp_dig (const fp2_t a, const dig_t b)
int fp3_cmp (const fp3_t a, const fp3_t b)
int fp3_cmp_dig (const fp3_t a, const dig_t b)
int fp4_cmp (const fp4_t a, const fp4_t b)
int fp4_cmp_dig (const fp4_t a, const dig_t b)
int fp6_cmp (const fp6_t a, const fp6_t b)
int fp6_cmp_dig (const fp6_t a, const dig_t b)
int fp9_cmp (const fp9_t a, const fp9_t b)
int fp9_cmp_dig (const fp9_t a, const dig_t b)
int fp8_cmp (const fp8_t a, const fp8_t b)
int fp8_cmp_dig (const fp8_t a, const dig_t b)
int fp12_cmp (const fp12_t a, const fp12_t b)
int fp12_cmp_dig (const fp12_t a, const dig_t b)
int fp16_cmp (const fp16_t a, const fp16_t b)
int fp16_cmp_dig (const fp16_t a, const dig_t b)
int fp18_cmp (const fp18_t a, const fp18_t b)
int fp18_cmp_dig (const fp18_t a, const dig_t b)
int fp24_cmp (const fp24_t a, const fp24_t b)
int fp24_cmp_dig (const fp24_t a, const dig_t b)
int fp48_cmp (const fp48_t a, const fp48_t b)
int fp48_cmp_dig (const fp48_t a, const dig_t b)
int fp54_cmp (const fp54_t a, const fp54_t b)
int fp54_cmp_dig (const fp54_t a, const dig_t b)
Detailed Description
Implementation of comparison in extensions defined over prime fields.
Definition in file relic_fpx_cmp.c.
Function Documentation
fp2_cmp()
int fp2_cmp (const fp2_t a, const fp2_t b)
Returns the result of a comparison between two quadratic extension field elements.
Parameters
[in] a - the first quadratic extension field element.
[in] b - the second quadratic extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 39 of file relic_fpx_cmp.c.
References fp_cmp(), RLC_EQ, and RLC_NE.
Referenced by detect_opt(), ep2_cmp(), ep2_on_curve(), fp2_srt(), fp4_cmp(), and fp6_cmp().
fp2_cmp_dig()
int fp2_cmp_dig (const fp2_t a, const dig_t b)
Returns the result of a signed comparison between a quadratic extension field element and a digit.
Parameters
[in] a - the quadratic extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 44 of file relic_fpx_cmp.c.
References fp_cmp_dig(), fp_is_zero(), RLC_EQ, and RLC_NE.
Referenced by detect_opt(), fp2_test_cyc(), fp4_cmp_dig(), and fp6_cmp_dig().
fp3_cmp()
int fp3_cmp (const fp3_t a, const fp3_t b)
Returns the result of a comparison between two cubic extension field elements.
Parameters
[in] a - the first cubic extension field element.
[in] b - the second cubic extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 49 of file relic_fpx_cmp.c.
References fp_cmp(), RLC_EQ, and RLC_NE.
Referenced by detect_opt(), ep3_cmp(), ep3_on_curve(), fp3_srt(), and fp9_cmp().
fp3_cmp_dig()
int fp3_cmp_dig (const fp3_t a, const dig_t b)
Returns the result of a signed comparison between a cubic extension field element and a digit.
Parameters
[in] a - the cubic extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 54 of file relic_fpx_cmp.c.
References fp_cmp_dig(), fp_is_zero(), RLC_EQ, and RLC_NE.
Referenced by detect_opt(), fp3_srt(), and fp9_cmp_dig().
fp4_cmp()
int fp4_cmp (const fp4_t a, const fp4_t b)
Returns the result of a comparison between two quartic extension field elements.
Parameters
[in] a - the first quartic extension field element.
[in] b - the second quartic extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 59 of file relic_fpx_cmp.c.
References fp2_cmp(), RLC_EQ, and RLC_NE.
Referenced by detect_opt(), ep4_cmp(), ep4_on_curve(), and fp8_cmp().
fp4_cmp_dig()
int fp4_cmp_dig (const fp4_t a, const dig_t b)
Returns the result of a signed comparison between a quartic extension field element and a digit.
Parameters
[in] a - the quartic extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 64 of file relic_fpx_cmp.c.
References fp2_cmp_dig(), fp2_is_zero(), RLC_EQ, and RLC_NE.
Referenced by detect_opt(), and fp8_cmp_dig().
fp6_cmp()
int fp6_cmp (const fp6_t a, const fp6_t b)
Returns the result of a comparison between two sextic extension field elements.
Parameters
[in] a - the first sextic extension field element.
[in] b - the second sextic extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 69 of file relic_fpx_cmp.c.
References fp2_cmp(), RLC_EQ, and RLC_NE.
Referenced by fp12_cmp().
fp6_cmp_dig()
int fp6_cmp_dig (const fp6_t a, const dig_t b)
Returns the result of a signed comparison between a sextic extension field element and a digit.
Parameters
[in] a - the sextic extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 74 of file relic_fpx_cmp.c.
References fp2_cmp_dig(), fp2_is_zero(), RLC_EQ, and RLC_NE.
Referenced by fp12_cmp_dig().
fp9_cmp()
int fp9_cmp (const fp9_t a, const fp9_t b)
Returns the result of a comparison between two nonic extension field elements.
Parameters
[in] a - the first nonic extension field element.
[in] b - the second nonic extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 79 of file relic_fpx_cmp.c.
References fp3_cmp(), RLC_EQ, and RLC_NE.
Referenced by fp18_cmp().
fp9_cmp_dig()
int fp9_cmp_dig (const fp9_t a, const dig_t b)
Returns the result of a signed comparison between a nonic extension field element and a digit.
Parameters
[in] a - the nonic extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 84 of file relic_fpx_cmp.c.
References fp3_cmp_dig(), fp3_is_zero(), RLC_EQ, and RLC_NE.
Referenced by fp18_cmp_dig().
fp8_cmp()
int fp8_cmp (const fp8_t a, const fp8_t b)
Returns the result of a comparison between two octic extension field elements.
Parameters
[in] a - the first octic extension field element.
[in] b - the second octic extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 89 of file relic_fpx_cmp.c.
References fp4_cmp(), RLC_EQ, and RLC_NE.
Referenced by detect_opt(), ep8_cmp(), ep8_on_curve(), fp16_cmp(), and fp24_cmp().
fp8_cmp_dig()
int fp8_cmp_dig (const fp8_t a, const dig_t b)
Returns the result of a signed comparison between an octic extension field element and a digit.
Parameters
[in] a - the octic extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 94 of file relic_fpx_cmp.c.
References fp4_cmp_dig(), fp4_is_zero(), RLC_EQ, and RLC_NE.
Referenced by detect_opt(), fp16_cmp_dig(), fp24_cmp_dig(), and fp8_test_cyc().
fp12_cmp()
int fp12_cmp (const fp12_t a, const fp12_t b)
Returns the result of a comparison between two dodecic extension field elements.
Parameters
[in] a - the first dodecic extension field element.
[in] b - the second dodecic extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 99 of file relic_fpx_cmp.c.
References fp6_cmp(), RLC_EQ, and RLC_NE.
Referenced by fp12_test_cyc().
fp12_cmp_dig()
int fp12_cmp_dig (const fp12_t a, const dig_t b)
Returns the result of a signed comparison between a dodecic extension field element and a digit.
Parameters
[in] a - the dodecic extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 104 of file relic_fpx_cmp.c.
References fp6_cmp_dig(), fp6_is_zero(), RLC_EQ, and RLC_NE.
Referenced by fp12_back_cyc(), and fp12_back_cyc_sim().
fp16_cmp()
int fp16_cmp (const fp16_t a, const fp16_t b)
Returns the result of a comparison between two sextadecic extension field elements.
Parameters
[in] a - the first sextadecic extension field element.
[in] b - the second sextadecic extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 109 of file relic_fpx_cmp.c.
References fp8_cmp(), RLC_EQ, and RLC_NE.
fp16_cmp_dig()
int fp16_cmp_dig (const fp16_t a, const dig_t b)
Returns the result of a signed comparison between an sextadecic extension field element and a digit.
Parameters
[in] a - the sextadecic extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 114 of file relic_fpx_cmp.c.
References fp8_cmp_dig(), fp8_is_zero(), RLC_EQ, and RLC_NE.
Referenced by fp16_test_cyc().
fp18_cmp()
int fp18_cmp (const fp18_t a, const fp18_t b)
Returns the result of a comparison between two octdecic extension field elements.
Parameters
[in] a - the first octdecic extension field element.
[in] b - the second octdecic extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 119 of file relic_fpx_cmp.c.
References fp9_cmp(), RLC_EQ, and RLC_NE.
Referenced by fp18_test_cyc(), and fp54_cmp().
fp18_cmp_dig()
int fp18_cmp_dig (const fp18_t a, const dig_t b)
Returns the result of a signed comparison between an octdecic extension field element and a digit.
Parameters
[in] a - the octdecic extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 124 of file relic_fpx_cmp.c.
References fp9_cmp_dig(), fp9_is_zero(), RLC_EQ, and RLC_NE.
Referenced by fp18_back_cyc(), fp18_back_cyc_sim(), and fp54_cmp_dig().
fp24_cmp()
int fp24_cmp (const fp24_t a, const fp24_t b)
Returns the result of a comparison between two 24-degree extension field elements.
Parameters
[in] a - the first 24-degree extension field element.
[in] b - the second 24-degree extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 129 of file relic_fpx_cmp.c.
References fp8_cmp(), RLC_EQ, and RLC_NE.
Referenced by fp24_test_cyc(), and fp48_cmp().
fp24_cmp_dig()
int fp24_cmp_dig (const fp24_t a, const dig_t b)
Returns the result of a signed comparison between a 24-degree extension field element and a digit.
Parameters
[in] a - the 24-degree extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 134 of file relic_fpx_cmp.c.
References fp8_cmp_dig(), fp8_is_zero(), RLC_EQ, and RLC_NE.
Referenced by fp24_back_cyc(), fp24_back_cyc_sim(), and fp48_cmp_dig().
fp48_cmp()
int fp48_cmp (const fp48_t a, const fp48_t b)
Returns the result of a comparison between two 48-extension field elements.
Parameters
[in] a - the first 48-extension field element.
[in] b - the second 48-extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 139 of file relic_fpx_cmp.c.
References fp24_cmp(), RLC_EQ, and RLC_NE.
Referenced by fp48_test_cyc().
fp48_cmp_dig()
int fp48_cmp_dig (const fp48_t a, const dig_t b)
Returns the result of a signed comparison between a 48-extension field element and a digit.
Parameters
[in] a - the 48-extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 144 of file relic_fpx_cmp.c.
References fp24_cmp_dig(), fp24_is_zero(), RLC_EQ, and RLC_NE.
Referenced by fp48_back_cyc(), and fp48_back_cyc_sim().
fp54_cmp()
int fp54_cmp (const fp54_t a, const fp54_t b)
Returns the result of a comparison between two 54-extension field elements.
Parameters
[in] a - the first 54-extension field element.
[in] b - the second 54-extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 149 of file relic_fpx_cmp.c.
References fp18_cmp(), RLC_EQ, and RLC_NE.
Referenced by fp54_test_cyc().
fp54_cmp_dig()
int fp54_cmp_dig (const fp54_t a, const dig_t b)
Returns the result of a signed comparison between a 54-extension field element and a digit.
Parameters
[in] a - the 54-extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 154 of file relic_fpx_cmp.c.
References fp18_cmp_dig(), fp18_is_zero(), RLC_EQ, and RLC_NE.
Referenced by fp54_back_cyc(), and fp54_back_cyc_sim().