RELIC: src/epx/relic_ep2_curve.c File Reference
relic_ep2_curve.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Macros
#define ASSIGN(CURVE)
#define ASSIGNM(CURVE)
#define BN_P256_A0 "0"
#define BN_P256_A1 "0"
#define BN_P256_B0 "4"
#define BN_P256_B1 "B64000000000FF2F2200000085FD5480B0001F44B6B88BF142BC818F95E3E6AE"
#define BN_P256_X0 "0C77AE4A1D6E145166739CF23DAFACA9DD396E9046424FC5479BD57692904538"
#define BN_P256_X1 "8D1705B45D9EAAD78A9198FD8D76E2013D1BC119B4D95721A8D32F819A544F51"
#define BN_P256_Y0 "A906E963E4988478E458A4959EF7D61B570358814E28A04EF9B8C794064D73A7"
#define BN_P256_Y1 "A033144CA161E3E3271624B3F0CC1CE607ACD2CBCE9E9253C732CF3E1016DEE7"
#define BN_P256_R "B64000000000FF2F2200000085FD547FD8001F44B6B7F4B7C2BC818F7B6BEF99"
#define BN_P256_H "B64000000000FF2F2200000085FD548188001F44B6B9232AC2BC818FB05BDDC5"
#define BN_P256_MAPU0 "0"
#define BN_P256_MAPU1 "-1"
#define SM9_P256_A0 "0"
#define SM9_P256_A1 "0"
#define SM9_P256_B0 "0"
#define SM9_P256_B1 "5"
#define SM9_P256_X0 "3722755292130B08D2AAB97FD34EC120EE265948D19C17ABF9B7213BAF82D65B"
#define SM9_P256_X1 "85AEF3D078640C98597B6027B441A01FF1DD2C190F5E93C454806C11D8806141"
#define SM9_P256_Y0 "A7CF28D519BE3DA65F3170153D278FF247EFBA98A71A08116215BBA5C999A7C7"
#define SM9_P256_Y1 "17509B092E845C1266BA0D262CBEE6ED0736A96FA347C8BD856DC76B84EBEB96"
#define SM9_P256_R "B640000002A3A6F1D603AB4FF58EC74449F2934B18EA8BEEE56EE19CD69ECF25"
#define SM9_P256_H "B640000002A3A6F1D603AB4FF58EC745F9F2934B1C0B51C8E57054B2F003BBD5"
#define SM9_P256_MAPU0 "-1"
#define SM9_P256_MAPU1 "0"
Functions
static int ep2_curve_get_coeffs (fp2_t *coeffs, const char *str)
static void ep2_curve_set_ctmap (const char *a0_str, const char *a1_str, const char *b0_str, const char *b1_str, const char *xn_str, const char *xd_str, const char *yn_str, const char *yd_str)
static void ep2_curve_set_map (void)
static void detect_opt (int *opt, fp2_t a)
void ep2_curve_init (void)
void ep2_curve_clean (void)
int ep2_curve_opt_a (void)
int ep2_curve_opt_b (void)
void ep2_curve_mul_a (fp2_t c, const fp2_t a)
void ep2_curve_mul_b (fp2_t c, const fp2_t a)
int ep2_curve_is_twist (void)
int ep2_curve_is_ctmap (void)
void ep2_curve_get_gen (ep2_t g)
fp_t * ep2_curve_get_a (void)
fp_t * ep2_curve_get_b (void)
void ep2_curve_get_ord (bn_t n)
void ep2_curve_get_cof (bn_t h)
iso2_t ep2_curve_get_iso ()
ep2_t * ep2_curve_get_tab (void)
void ep2_curve_set_twist (int type)
void ep2_curve_set (const fp2_t a, const fp2_t b, const ep2_t g, const bn_t r, const bn_t h)
Detailed Description
Implementation of configuration of prime elliptic curves over a quadratic extension field.
Definition in file relic_ep2_curve.c.
Macro Definition Documentation
BN_P256_A0
#define BN_P256_A0 "0"
Parameters for a pairing-friendly prime curve over a quadratic extension.
Definition at line 80 of file relic_ep2_curve.c.
BN_P256_A1
#define BN_P256_A1 "0"
Parameters for a pairing-friendly prime curve over a quadratic extension.
Definition at line 81 of file relic_ep2_curve.c.
BN_P256_B0
#define BN_P256_B0 "4"
Parameters for a pairing-friendly prime curve over a quadratic extension.
Definition at line 82 of file relic_ep2_curve.c.
BN_P256_B1
#define BN_P256_B1 "B64000000000FF2F2200000085FD5480B0001F44B6B88BF142BC818F95E3E6AE"
Parameters for a pairing-friendly prime curve over a quadratic extension.
Definition at line 83 of file relic_ep2_curve.c.
BN_P256_X0
#define BN_P256_X0 "0C77AE4A1D6E145166739CF23DAFACA9DD396E9046424FC5479BD57692904538"
Parameters for a pairing-friendly prime curve over a quadratic extension.
Definition at line 84 of file relic_ep2_curve.c.
BN_P256_X1
#define BN_P256_X1 "8D1705B45D9EAAD78A9198FD8D76E2013D1BC119B4D95721A8D32F819A544F51"
Parameters for a pairing-friendly prime curve over a quadratic extension.
Definition at line 85 of file relic_ep2_curve.c.
BN_P256_Y0
#define BN_P256_Y0 "A906E963E4988478E458A4959EF7D61B570358814E28A04EF9B8C794064D73A7"
Parameters for a pairing-friendly prime curve over a quadratic extension.
Definition at line 86 of file relic_ep2_curve.c.
BN_P256_Y1
#define BN_P256_Y1 "A033144CA161E3E3271624B3F0CC1CE607ACD2CBCE9E9253C732CF3E1016DEE7"
Parameters for a pairing-friendly prime curve over a quadratic extension.
Definition at line 87 of file relic_ep2_curve.c.
BN_P256_R
#define BN_P256_R "B64000000000FF2F2200000085FD547FD8001F44B6B7F4B7C2BC818F7B6BEF99"
Parameters for a pairing-friendly prime curve over a quadratic extension.
Definition at line 88 of file relic_ep2_curve.c.
BN_P256_H
#define BN_P256_H "B64000000000FF2F2200000085FD548188001F44B6B9232AC2BC818FB05BDDC5"
Parameters for a pairing-friendly prime curve over a quadratic extension.
Definition at line 89 of file relic_ep2_curve.c.
BN_P256_MAPU0
#define BN_P256_MAPU0 "0"
Parameters for a pairing-friendly prime curve over a quadratic extension.
Definition at line 90 of file relic_ep2_curve.c.
BN_P256_MAPU1
#define BN_P256_MAPU1 "-1"
Parameters for a pairing-friendly prime curve over a quadratic extension.
Definition at line 91 of file relic_ep2_curve.c.
SM9_P256_A0
#define SM9_P256_A0 "0"
Definition at line 97 of file relic_ep2_curve.c.
SM9_P256_A1
#define SM9_P256_A1 "0"
Definition at line 98 of file relic_ep2_curve.c.
SM9_P256_B0
#define SM9_P256_B0 "0"
Definition at line 99 of file relic_ep2_curve.c.
SM9_P256_B1
#define SM9_P256_B1 "5"
Definition at line 100 of file relic_ep2_curve.c.
SM9_P256_X0
#define SM9_P256_X0 "3722755292130B08D2AAB97FD34EC120EE265948D19C17ABF9B7213BAF82D65B"
Definition at line 101 of file relic_ep2_curve.c.
SM9_P256_X1
#define SM9_P256_X1 "85AEF3D078640C98597B6027B441A01FF1DD2C190F5E93C454806C11D8806141"
Definition at line 102 of file relic_ep2_curve.c.
SM9_P256_Y0
#define SM9_P256_Y0 "A7CF28D519BE3DA65F3170153D278FF247EFBA98A71A08116215BBA5C999A7C7"
Definition at line 103 of file relic_ep2_curve.c.
SM9_P256_Y1
#define SM9_P256_Y1 "17509B092E845C1266BA0D262CBEE6ED0736A96FA347C8BD856DC76B84EBEB96"
Definition at line 104 of file relic_ep2_curve.c.
SM9_P256_R
#define SM9_P256_R "B640000002A3A6F1D603AB4FF58EC74449F2934B18EA8BEEE56EE19CD69ECF25"
Definition at line 105 of file relic_ep2_curve.c.
SM9_P256_H
#define SM9_P256_H "B640000002A3A6F1D603AB4FF58EC745F9F2934B1C0B51C8E57054B2F003BBD5"
Definition at line 106 of file relic_ep2_curve.c.
SM9_P256_MAPU0
#define SM9_P256_MAPU0 "-1"
Definition at line 107 of file relic_ep2_curve.c.
SM9_P256_MAPU1
#define SM9_P256_MAPU1 "0"
Definition at line 108 of file relic_ep2_curve.c.
ASSIGN
#define ASSIGN (CURVE)
Value:
    RLC_GET(str, CURVE##_A0, sizeof(CURVE##_A0));                           \
    fp_read_str(a[0], str, strlen(str), 16);                                \
    RLC_GET(str, CURVE##_A1, sizeof(CURVE##_A1));                           \
    fp_read_str(a[1], str, strlen(str), 16);                                \
    RLC_GET(str, CURVE##_B0, sizeof(CURVE##_B0));                           \
    fp_read_str(b[0], str, strlen(str), 16);                                \
    RLC_GET(str, CURVE##_B1, sizeof(CURVE##_B1));                           \
    fp_read_str(b[1], str, strlen(str), 16);                                \
    RLC_GET(str, CURVE##_X0, sizeof(CURVE##_X0));                           \
    fp_read_str(g->x[0], str, strlen(str), 16);                             \
    RLC_GET(str, CURVE##_X1, sizeof(CURVE##_X1));                           \
    fp_read_str(g->x[1], str, strlen(str), 16);                             \
    RLC_GET(str, CURVE##_Y0, sizeof(CURVE##_Y0));                           \
    fp_read_str(g->y[0], str, strlen(str), 16);                             \
    RLC_GET(str, CURVE##_Y1, sizeof(CURVE##_Y1));                           \
    fp_read_str(g->y[1], str, strlen(str), 16);                             \
    RLC_GET(str, CURVE##_R, sizeof(CURVE##_R));                             \
    bn_read_str(r, str, strlen(str), 16);                                   \
    RLC_GET(str, CURVE##_H, sizeof(CURVE##_H));                             \
    bn_read_str(h, str, strlen(str), 16);                                   \
    RLC_GET(str, CURVE##_MAPU0, sizeof(CURVE##_MAPU0));                     \
    fp_read_str(u[0], str, strlen(str), 16);                                \
    RLC_GET(str, CURVE##_MAPU1, sizeof(CURVE##_MAPU1));                     \
    fp_read_str(u[1], str, strlen(str), 16);
Assigns a set of ordinary elliptic curve parameters.
Parameters
[in] CURVE - the curve parameters to assign.
Definition at line 317 of file relic_ep2_curve.c.
Referenced by ep2_curve_set_twist().
ASSIGNM
#define ASSIGNM (CURVE)
Value:
    ep2_curve_set_ctmap(CURVE##_ISO_A0, CURVE##_ISO_A1, CURVE##_ISO_B0,     \
                        CURVE##_ISO_B1, CURVE##_ISO_XN, CURVE##_ISO_XD,     \
                        CURVE##_ISO_YN, CURVE##_ISO_YD)
Assigns the isogeny map parameters for hashing with SSWU map.
Parameters
[in] CURVE - the curve parameters to assign.
Definition at line 350 of file relic_ep2_curve.c.
Referenced by ep2_curve_set_twist().
Function Documentation
ep2_curve_get_coeffs()
static int ep2_curve_get_coeffs (fp2_t * coeffs, const char * str) static
Reads a sequence of polynomial coefficients from semicolon separated string.
Parameters
[out] coeffs - the resulting coefficients.
[in] str - the input string.
Definition at line 364 of file relic_ep2_curve.c.
References ERR_NO_VALID, fp_read_str(), RLC_EPX_CTMAP_MAX, and RLC_THROW.
Referenced by ep2_curve_set_ctmap().
ep2_curve_set_ctmap()
static void ep2_curve_set_ctmap (const char * a0_str, const char * a1_str, const char * b0_str, const char * b1_str, const char * xn_str, const char * xd_str, const char * yn_str, const char * yd_str) inline static
Configures a constant-time hash-to-curve function based on an isogeny map.
Parameters
[in] a0_str - the string representing the 1st element of the 'a' coefficient.
[in] a1_str - the string representing the 2nd element of the 'a' coefficient.
[in] b0_str - the string representing the 1st element of the 'b' coefficient.
[in] b1_str - the string representing the 2nd element of the 'b' coefficient.
[in] xn_str - the string representing the x numerator coefficients.
[in] xd_str - the string representing the x denominator coefficients.
[in] yn_str - the string representing the y numerator coefficients.
[in] yd_str - the string representing the y denominator coefficients.
Definition at line 415 of file relic_ep2_curve.c.
References iso2_st::a, iso2_st::b, iso2_st::deg_xd, iso2_st::deg_xn, iso2_st::deg_yd, iso2_st::deg_yn, ep2_curve_get_coeffs(), ep2_curve_get_iso(), fp_read_str(), iso2_st::xd, iso2_st::xn, iso2_st::yd, and iso2_st::yn.
ep2_curve_set_map()
static void ep2_curve_set_map (void) static
Precomputes constants used by the ep2_map function.
Definition at line 438 of file relic_ep2_curve.c.
References iso2_st::a, iso2_st::b, bn_free, bn_get_bit(), bn_new, bn_null, core_get(), _ctx_t::ep2_a, _ctx_t::ep2_b, ep2_curve_is_ctmap(), ep2_curve_opt_a(), ep2_curve_opt_b(), _ctx_t::ep2_iso, _ctx_t::ep2_map_c, _ctx_t::ep2_map_u, ERR_CAUGHT, ERR_NO_VALID, fp2_add, fp2_copy(), fp2_dbl, fp2_inv(), fp2_mul, fp2_mul_dig(), fp2_neg(), fp2_set_dig(), fp2_sqr, fp2_srt(), fp_is_zero(), fp_prime_back(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, RLC_TRY, and RLC_ZERO.
Referenced by ep2_curve_set_twist().
detect_opt()
static void detect_opt (int * opt, fp2_t a) static
Detects an optimization based on the curve coefficients.
Definition at line 527 of file relic_ep2_curve.c.
References ERR_CAUGHT, fp2_cmp(), fp2_cmp_dig(), fp2_free, fp2_is_zero(), fp2_neg(), fp2_new, fp2_null, fp2_set_dig(), fp_bits(), fp_is_zero(), RLC_CATCH_ANY, RLC_DIG, RLC_EQ, RLC_FINALLY, RLC_HUGE, RLC_MIN3, RLC_ONE, RLC_THROW, RLC_TINY, RLC_TRY, RLC_TWO, and RLC_ZERO.
Referenced by ep2_curve_set_twist().
ep2_curve_init()
void ep2_curve_init (void)
Initializes the elliptic curve over quadratic extension.
Definition at line 562 of file relic_ep2_curve.c.
References iso2_st::a, iso2_st::b, bn_make(), core_get(), _ctx_t::ep2_a, _ctx_t::ep2_b, ep2_curve_get_iso(), _ctx_t::ep2_frb, _ctx_t::ep2_g, _ctx_t::ep2_h, _ctx_t::ep2_map_c, _ctx_t::ep2_map_u, ep2_new, _ctx_t::ep2_pre, _ctx_t::ep2_ptr, _ctx_t::ep2_r, fp2_new, RLC_EP_TABLE, RLC_EPX_CTMAP_MAX, RLC_FP_DIGS, ep2_st::x, iso2_st::xd, iso2_st::xn, ep2_st::y, iso2_st::yd, iso2_st::yn, and ep2_st::z.
Referenced by pp_map_init().
ep2_curve_clean()
void ep2_curve_clean (void)
Finalizes the elliptic curve over quadratic extension.
Definition at line 615 of file relic_ep2_curve.c.
References iso2_st::a, iso2_st::b, bn_clean(), core_get(), _ctx_t::ep2_a, _ctx_t::ep2_b, ep2_curve_get_iso(), _ctx_t::ep2_frb, ep2_free, _ctx_t::ep2_g, _ctx_t::ep2_h, _ctx_t::ep2_map_c, _ctx_t::ep2_map_u, _ctx_t::ep2_pre, _ctx_t::ep2_r, fp2_free, RLC_EP_TABLE, RLC_EPX_CTMAP_MAX, ep2_st::x, iso2_st::xd, iso2_st::xn, ep2_st::y, iso2_st::yd, iso2_st::yn, and ep2_st::z.
Referenced by pp_map_clean().
ep2_curve_opt_a()
int ep2_curve_opt_a (void)
Returns a optimization identifier based on the 'a' coefficient of the curve.
Returns
the optimization identifier.
Definition at line 652 of file relic_ep2_curve.c.
References core_get(), and _ctx_t::ep2_opt_a.
Referenced by ep2_curve_set_map(), ep2_frb(), ep2_map_from_field(), ep2_map_swift(), and ep2_rhs().
ep2_curve_opt_b()
int ep2_curve_opt_b (void)
Returns b optimization identifier based on the 'b' coefficient of the curve.
Returns
the optimization identifier.
Definition at line 656 of file relic_ep2_curve.c.
References core_get(), and _ctx_t::ep2_opt_b.
Referenced by ep2_curve_set_map(), ep2_map_from_field(), ep2_map_swift(), and ep2_rhs().
ep2_curve_mul_a()
void ep2_curve_mul_a (fp2_t c, const fp2_t a)
Multiplies a field element by the a-coefficient of the curve.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
Definition at line 660 of file relic_ep2_curve.c.
References core_get(), _ctx_t::ep2_a, ep2_curve_is_twist(), _ctx_t::ep2_opt_a, ep_curve_get_a(), ep_curve_opt_a(), fp2_copy(), fp2_dbl, fp2_mul, fp2_mul_art(), fp2_mul_dig(), fp2_zero(), fp_mul, RLC_EP_MTYPE, RLC_ONE, RLC_TINY, RLC_TWO, and RLC_ZERO.
Referenced by pp_dbl_k8_projc_basic(), and pp_dbl_k8_projc_lazyr().
ep2_curve_mul_b()
void ep2_curve_mul_b (fp2_t c, const fp2_t a)
Multiplies a field element by the b-coefficient of the curve.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
Definition at line 703 of file relic_ep2_curve.c.
References core_get(), _ctx_t::ep2_b, _ctx_t::ep2_opt_b, fp2_copy(), fp2_mul, fp2_mul_dig(), fp2_zero(), RLC_ONE, RLC_TINY, and RLC_ZERO.
ep2_curve_is_twist()
int ep2_curve_is_twist (void)
Tests if the configured elliptic curve is a twist.
Returns
the type of the elliptic curve twist, 0 if non-twisted curve.
Definition at line 723 of file relic_ep2_curve.c.
References core_get(), and _ctx_t::ep2_is_twist.
Referenced by ep2_curve_mul_a(), fp12_mul_dxs_basic(), fp12_mul_dxs_lazyr(), pp_add_k12_basic(), pp_add_k12_projc_basic(), pp_add_k12_projc_lazyr(), pp_add_k8_basic(), pp_add_k8_projc_basic(), pp_add_k8_projc_lazyr(), pp_add_lit_k12(), pp_dbl_k12_basic(), pp_dbl_k12_projc_basic(), pp_dbl_k12_projc_lazyr(), pp_dbl_k8_basic(), pp_dbl_k8_projc_basic(), pp_dbl_k8_projc_lazyr(), pp_dbl_k8_projc_lazyr_new(), pp_dbl_k8_projc_new(), and pp_dbl_lit_k12().
ep2_curve_is_ctmap()
int ep2_curve_is_ctmap (void)
Tests if the current curve should use an isogeny map for the SSWU map.
Returns
1 if the curve uses an isogeny, and 0 otherwise.
Definition at line 727 of file relic_ep2_curve.c.
References core_get(), and _ctx_t::ep2_is_ctmap.
Referenced by ep2_curve_set_map(), and ep2_map_from_field().
ep2_curve_get_gen()
void ep2_curve_get_gen (ep2_t g)
Returns the generator of the group of points in the elliptic curve.
Parameters
[out] g - the returned generator.
Definition at line 731 of file relic_ep2_curve.c.
References core_get(), and ep2_copy().
Referenced by ep2_mul_gen(), and ep2_mul_sim_gen().
ep2_curve_get_a()
fp_t * ep2_curve_get_a (void)
Returns the 'a' coefficient of the currently configured elliptic curve.
Returns
the 'a' coefficient of the elliptic curve.
Definition at line 735 of file relic_ep2_curve.c.
References core_get(), and _ctx_t::ep2_a.
Referenced by ep2_map_swift(), and ep2_rhs().
ep2_curve_get_b()
fp_t * ep2_curve_get_b (void)
Returns the 'b' coefficient of the currently configured elliptic curve.
Parameters
[out] b - the 'b' coefficient of the elliptic curve.
Definition at line 739 of file relic_ep2_curve.c.
References core_get(), and _ctx_t::ep2_b.
Referenced by ep2_rhs(), pp_dbl_k12_projc_basic(), and pp_dbl_k12_projc_lazyr().
ep2_curve_get_ord()
void ep2_curve_get_ord (bn_t n)
Returns the order of the group of points in the elliptic curve.
Parameters
[out] n - the returned order.
Definition at line 743 of file relic_ep2_curve.c.
References bn_copy(), core_get(), _ctx_t::ep2_is_twist, _ctx_t::ep2_r, and ep_curve_get_ord().
Referenced by ep2_mul_fix_basic(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_fix_lwnaf(), ep2_mul_gls_imp(), ep2_mul_monty(), ep2_mul_pre_basic(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_reg_gls(), ep2_mul_reg_imp(), ep2_mul_sim_endom(), ep2_mul_sim_gen(), ep2_mul_sim_joint(), ep2_mul_sim_lot(), ep2_mul_sim_trick(), and ep2_rand().
ep2_curve_get_cof()
void ep2_curve_get_cof (bn_t h)
Returns the cofactor of the group order in the elliptic curve.
Parameters
[out] h - the returned cofactor.
Definition at line 752 of file relic_ep2_curve.c.
References bn_copy(), and core_get().
Referenced by ep2_mul_cof().
ep2_curve_get_iso()
iso2_t ep2_curve_get_iso (void)
Returns the isogeny map coefficients for use with the SSWU map.
Definition at line 756 of file relic_ep2_curve.c.
References core_get(), and _ctx_t::ep2_iso.
Referenced by ep2_curve_clean(), ep2_curve_init(), and ep2_curve_set_ctmap().
ep2_curve_get_tab()
ep2_t * ep2_curve_get_tab (void)
Returns the precomputation table for the generator.
Returns
the table.
Definition at line 766 of file relic_ep2_curve.c.
References core_get(), and _ctx_t::ep2_ptr.
Referenced by ep2_curve_set(), ep2_curve_set_twist(), ep2_mul_gen(), and ep2_mul_sim_gen().
ep2_curve_set_twist()
void ep2_curve_set_twist (int type)
Configures an elliptic curve by twisting the curve over the base prime field.
Parameters
- the type of twist (multiplicative or divisive)
Definition at line 776 of file relic_ep2_curve.c.
References ASSIGN, ASSIGNM, B12_P1150, B12_P377, B12_P381, B12_P383, B12_P446, B12_P455, B12_P638, BASIC, bn_copy(), bn_free, bn_new, bn_null, BN_P158, BN_P254, BN_P256, BN_P382, BN_P446, BN_P638, core_get(), detect_opt(), _ctx_t::ep2_a, _ctx_t::ep2_b, ep2_copy(), ep2_curve_get_tab(), ep2_curve_set_map(), _ctx_t::ep2_frb, ep2_free, _ctx_t::ep2_g, _ctx_t::ep2_h, _ctx_t::ep2_is_ctmap, _ctx_t::ep2_is_twist, _ctx_t::ep2_map_u, ep2_mul_pre, ep2_new, ep2_null, _ctx_t::ep2_opt_a, _ctx_t::ep2_opt_b, _ctx_t::ep2_r, ep_param_get(), ERR_CAUGHT, ERR_NO_VALID, fp2_copy(), fp2_free, fp2_inv(), fp2_new, fp2_null, _ctx_t::fp2_p1, fp2_set_dig(), fp2_zero(), fp_copy(), GMT8_P544, pc_core_calc(), RLC_CATCH_ANY, RLC_EP_DTYPE, RLC_EP_MTYPE, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, RLC_TRY, and SM9_P256.
Referenced by ep_param_set_any_pairf().
ep2_curve_set()
void ep2_curve_set (const fp2_t a, const fp2_t b, const ep2_t g, const bn_t r, const bn_t h)
Configures an elliptic curve over a quadratic extension by its coefficients.
Parameters
[in] a - the 'a' coefficient of the curve.
[in] b - the 'b' coefficient of the curve.
[in] g - the generator.
[in] r - the order of the group of points.
[in] h - the cofactor of the group order.
Definition at line 925 of file relic_ep2_curve.c.
References bn_copy(), core_get(), _ctx_t::ep2_a, _ctx_t::ep2_b, ep2_curve_get_tab(), _ctx_t::ep2_g, _ctx_t::ep2_h, _ctx_t::ep2_is_twist, ep2_mul_pre, ep2_norm(), _ctx_t::ep2_r, and fp2_copy().