RELIC: src/bn/relic_bn_div.c File Reference
relic_bn_div.c File Reference
Multiple precision integer arithmetic
#include "relic_core.h"
#include "relic_bn_low.h"
Functions
static void bn_div_imp (bn_t c, bn_t d, const bn_t a, const bn_t b)
void bn_div (bn_t c, const bn_t a, const bn_t b)
void bn_div_rem (bn_t c, bn_t d, const bn_t a, const bn_t b)
void bn_div_dig (bn_t c, const bn_t a, dig_t b)
void bn_div_rem_dig (bn_t c, dig_t *d, const bn_t a, dig_t b)
Detailed Description
Implementation of the multiple precision division functions.
Definition in file relic_bn_div.c.
Function Documentation
bn_div_imp()
static void bn_div_imp (bn_t c, bn_t d, const bn_t a, const bn_t b) static
Divides two multiple precision integers, computing the quotient and the remainder.
Parameters
[out] c - the quotient.
[out] d - the remainder.
[in] a - the dividend.
[in] b - the the divisor.
Definition at line 48 of file relic_bn_div.c.
References bn_abs(), bn_add(), bn_cmp_abs(), bn_copy(), bn_divn_low(), bn_free, bn_is_zero(), bn_neg(), bn_new_size, bn_null, bn_set_dig(), bn_sign(), bn_sub(), bn_sub_dig(), bn_trim(), bn_zero(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_LT, RLC_NEG, RLC_POS, RLC_THROW, and RLC_TRY.
Referenced by bn_div(), and bn_div_rem().
bn_div()
void bn_div (bn_t c, const bn_t a, const bn_t b)
Divides a multiple precision integer by another multiple precision integer without producing the positive remainder. Computes c = floor(a / b).
Parameters
[out] c - the resulting quotient.
[in] a - the dividend.
[in] b - the divisor.
Exceptions
ERR_NO_VALID - if the divisor is zero.
Definition at line 135 of file relic_bn_div.c.
References bn_div_imp(), bn_is_zero(), ERR_NO_VALID, and RLC_THROW.
Referenced by bn_gcd_ext_binar(), bn_gcd_ext_lehme(), bn_lcm(), bn_mod_pre_barrt(), bn_mxp_crt(), bn_rec_frb(), cp_ghpe_dec(), cp_phpe_dec(), cp_shpe_dec(), cp_shpe_gen(), ep_curve_set_endom(), fp_prime_set_pairf(), pp_exp_k1(), and pp_exp_k2().
bn_div_rem()
void bn_div_rem (bn_t c, bn_t d, const bn_t a, const bn_t b)
Divides a multiple precision integer by another multiple precision integer and produces a positive remainder. Computes c = floor(a / b) and d = a mod b.
Parameters
[out] c - the resulting quotient.
[out] d - the positive remainder.
[in] a - the dividend.
[in] b - the divisor.
Exceptions
ERR_NO_VALID - if the divisor is zero.
Definition at line 143 of file relic_bn_div.c.
References bn_div_imp(), bn_is_zero(), ERR_NO_VALID, and RLC_THROW.
Referenced by bn_gcd_ext_basic(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_mod_basic(), and fp_inv_exgcd().
bn_div_dig()
void bn_div_dig (bn_t c, const bn_t a, dig_t b)
Divides a multiple precision integers by a digit without computing the remainder. Computes c = floor(a / b).
Parameters
[out] c - the resulting quotient.
[out] d - the remainder.
[in] a - the dividend.
[in] b - the divisor.
Exceptions
ERR_NO_VALID - if the divisor is zero.
Definition at line 151 of file relic_bn_div.c.
References bn_copy(), bn_div1_low(), bn_free, bn_is_zero(), bn_new, bn_null, ERR_CAUGHT, ERR_NO_VALID, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by bn_size_str(), cp_bdpe_dec(), cp_bdpe_gen(), cp_ghpe_dec(), ep3_mul_cof_fm18(), ep3_mul_cof_sg18(), ep_mul_cof(), ep_param_set(), fp2_field_init(), fp3_field_init(), fp3_srt(), fp4_field_init(), fp8_field_init(), fp_crt(), fp_is_cub(), fp_prime_set(), fp_prime_set_pairf(), g1_is_valid(), g2_is_valid(), gt_is_valid(), and pp_exp_fm().
bn_div_rem_dig()
void bn_div_rem_dig (bn_t c, dig_t * d, const bn_t a, const dig_t b)
Divides a multiple precision integers by a digit. Computes c = floor(a / b) and d = a mod b.
Parameters
[out] c - the resulting quotient.
[out] d - the remainder.
[in] a - the dividend.
[in] b - the divisor.
Exceptions
ERR_NO_VALID - if the divisor is zero.
Definition at line 186 of file relic_bn_div.c.
References bn_copy(), bn_div1_low(), bn_free, bn_is_zero(), bn_new, bn_null, bn_sign(), ERR_CAUGHT, ERR_NO_VALID, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by bn_mod_dig(), and bn_write_str().