RELIC: src/fpx/relic_fpx_cyc.c File Reference
relic_fpx_cyc.c File Reference
Prime field extensions.
#include "relic_core.h"
Functions
void fp2_conv_cyc (fp2_t c, const fp2_t a)
int fp2_test_cyc (const fp2_t a)
void fp2_exp_cyc (fp2_t c, const fp2_t a, const bn_t b)
void fp2_exp_cyc_sim (fp2_t e, const fp2_t a, const bn_t b, const fp2_t c, const bn_t d)
void fp8_conv_cyc (fp8_t c, const fp8_t a)
int fp8_test_cyc (const fp8_t a)
void fp8_exp_cyc (fp8_t c, const fp8_t a, const bn_t b)
void fp8_exp_cyc_sim (fp8_t e, const fp8_t a, const bn_t b, const fp8_t c, const bn_t d)
void fp12_conv_cyc (fp12_t c, const fp12_t a)
int fp12_test_cyc (const fp12_t a)
void fp12_back_cyc (fp12_t c, const fp12_t a)
void fp12_back_cyc_sim (fp12_t c[], const fp12_t a[], int n)
void fp12_exp_cyc (fp12_t c, const fp12_t a, const bn_t b)
void fp12_exp_cyc_sim (fp12_t e, const fp12_t a, const bn_t b, const fp12_t c, const bn_t d)
void fp12_exp_cyc_sps (fp12_t c, const fp12_t a, const int *b, size_t len, int sign)
void fp16_conv_cyc (fp16_t c, const fp16_t a)
int fp16_test_cyc (const fp16_t a)
void fp16_exp_cyc (fp16_t c, const fp16_t a, const bn_t b)
void fp16_exp_cyc_sim (fp16_t e, const fp16_t a, const bn_t b, const fp16_t c, const bn_t d)
void fp18_conv_cyc (fp18_t c, const fp18_t a)
int fp18_test_cyc (const fp18_t a)
void fp18_back_cyc (fp18_t c, const fp18_t a)
void fp18_back_cyc_sim (fp18_t c[], const fp18_t a[], int n)
void fp18_exp_cyc (fp18_t c, const fp18_t a, const bn_t b)
void fp18_exp_cyc_sim (fp18_t e, const fp18_t a, const bn_t b, const fp18_t c, const bn_t d)
void fp18_exp_cyc_sps (fp18_t c, const fp18_t a, const int *b, int len, int sign)
void fp24_conv_cyc (fp24_t c, const fp24_t a)
int fp24_test_cyc (const fp24_t a)
void fp24_back_cyc (fp24_t c, const fp24_t a)
void fp24_back_cyc_sim (fp24_t c[], const fp24_t a[], int n)
void fp24_exp_cyc (fp24_t c, const fp24_t a, const bn_t b)
void fp24_exp_cyc_sim (fp24_t e, const fp24_t a, const bn_t b, const fp24_t c, const bn_t d)
void fp24_exp_cyc_sps (fp24_t c, const fp24_t a, const int *b, size_t len, int sign)
void fp48_conv_cyc (fp48_t c, const fp48_t a)
int fp48_test_cyc (const fp48_t a)
void fp48_back_cyc (fp48_t c, const fp48_t a)
void fp48_back_cyc_sim (fp48_t c[], const fp48_t a[], int n)
void fp48_exp_cyc (fp48_t c, const fp48_t a, const bn_t b)
void fp48_exp_cyc_sim (fp48_t e, const fp48_t a, const bn_t b, const fp48_t c, const bn_t d)
void fp48_exp_cyc_sps (fp48_t c, const fp48_t a, const int *b, size_t len, int sign)
void fp54_conv_cyc (fp54_t c, const fp54_t a)
int fp54_test_cyc (const fp54_t a)
void fp54_back_cyc (fp54_t c, const fp54_t a)
void fp54_back_cyc_sim (fp54_t c[], const fp54_t a[], int n)
void fp54_exp_cyc (fp54_t c, const fp54_t a, const bn_t b)
void fp54_exp_cyc_sps (fp54_t c, const fp54_t a, const int *b, size_t len, int sign)
Detailed Description
Implementation of exponentiation in cyclotomic subgroups of extensions defined over prime fields.
Definition in file relic_fpx_cyc.c.
Function Documentation
fp2_conv_cyc()
void fp2_conv_cyc (fp2_t c, const fp2_t a)
Converts a quadratic extension field element to a cyclotomic element. Computes c = a^(p - 1).
Parameters
[out] c - the result.
[in] a - the quadratic extension field element.
Definition at line 39 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp2_free, fp2_inv(), fp2_inv_cyc(), fp2_mul, fp2_new, fp2_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_exp_k2().
fp2_test_cyc()
int fp2_test_cyc (const fp2_t a)
Tests if a quadratic extension field element is cyclotomic.
Parameters
[in] a - the quadratic extension field element to test.
Returns
1 if the extension field element is cyclotomic, 0 otherwise.
Definition at line 62 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp2_cmp_dig(), fp2_free, fp2_inv_cyc(), fp2_mul, fp2_new, fp2_null, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp2_pck(), fp2_size_bin(), and fp2_write_bin().
fp2_exp_cyc()
void fp2_exp_cyc (fp2_t c, const fp2_t a, const bn_t b)
Computes a power of a cyclotomic quadratic extension field element.
Parameters
[out] c - the result.
[in] a - the cyclotomic element to exponentiate.
[in] b - the exponent.
Definition at line 84 of file relic_fpx_cyc.c.
References bn_bits(), bn_is_zero(), bn_rec_naf(), bn_sign(), ERR_CAUGHT, fp2_copy(), fp2_exp_dig(), fp2_free, fp2_inv_cyc(), fp2_mul, fp2_new, fp2_null, fp2_set_dig(), fp2_sqr, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by fp2_exp_cyc_sim(), and pp_exp_k2().
fp2_exp_cyc_sim()
void fp2_exp_cyc_sim (fp2_t e, const fp2_t a, const bn_t b, const fp2_t c, const bn_t d)
Computes a power of two cyclotomic quadratic extension field elements.
Parameters
[out] e - the result.
[in] a - the first element to exponentiate.
[in] b - the first exponent.
[in] c - the second element to exponentiate.
[in] d - the second exponent.
Definition at line 156 of file relic_fpx_cyc.c.
References bn_is_zero(), bn_rec_naf(), bn_sign(), ERR_CAUGHT, fp2_copy(), fp2_exp_cyc(), fp2_free, fp2_inv_cyc(), fp2_mul, fp2_new, fp2_null, fp2_set_dig(), fp2_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
fp8_conv_cyc()
void fp8_conv_cyc (fp8_t c, const fp8_t a)
Converts an octic extension field element to a cyclotomic element. Computes c = a^(p^4 - 1).
Parameters
[out] c - the result.
[in] a - the octic extension field element.
Definition at line 258 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp8_free, fp8_inv(), fp8_inv_cyc(), fp8_mul, fp8_new, fp8_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_exp_k8().
fp8_test_cyc()
int fp8_test_cyc (const fp8_t a)
Tests if an octic extension field element is cyclotomic.
Parameters
[in] a - the octic extension field element to test.
Returns
1 if the extension field element is cyclotomic, 0 otherwise.
Definition at line 281 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp8_cmp_dig(), fp8_free, fp8_inv_cyc(), fp8_mul, fp8_new, fp8_null, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp8_exp(), fp8_exp_dig(), and fp8_size_bin().
fp8_exp_cyc()
void fp8_exp_cyc (fp8_t c, const fp8_t a, const bn_t b)
Computes a power of a cyclotomic octic extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 303 of file relic_fpx_cyc.c.
References bn_bits(), bn_is_zero(), bn_rec_naf(), bn_sign(), ERR_CAUGHT, fp8_copy(), fp8_free, fp8_inv_cyc(), fp8_mul, fp8_new, fp8_null, fp8_set_dig(), fp8_sqr_cyc(), RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by fp8_exp(), fp8_exp_cyc_sim(), and pp_exp_k8().
fp8_exp_cyc_sim()
void fp8_exp_cyc_sim (fp8_t e, const fp8_t a, const bn_t b, const fp8_t c, const bn_t d)
Computes a power of two cyclotomic octic extension field elements.
Parameters
[out] e - the result.
[in] a - the first element to exponentiate.
[in] b - the first exponent.
[in] c - the second element to exponentiate.
[in] d - the second exponent.
Definition at line 371 of file relic_fpx_cyc.c.
References bn_is_zero(), bn_rec_naf(), bn_sign(), ERR_CAUGHT, fp8_copy(), fp8_exp_cyc(), fp8_free, fp8_inv_cyc(), fp8_mul, fp8_new, fp8_null, fp8_set_dig(), fp8_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
fp12_conv_cyc()
void fp12_conv_cyc (fp12_t c, const fp12_t a)
Converts a dodecic extension field element to a cyclotomic element. Computes c = a^(p^6 - 1)*(p^2 + 1).
Parameters
[out] c - the result.
[in] a - a dodecic extension field element.
Definition at line 473 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp12_frb(), fp12_free, fp12_inv(), fp12_inv_cyc(), fp12_mul, fp12_new, fp12_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_exp_b12(), pp_exp_bn(), and pp_exp_sm9().
fp12_test_cyc()
int fp12_test_cyc (const fp12_t a)
Tests if a dodecic extension field element belongs to the cyclotomic subgroup.
A cyclotomic element is one raised to the (p^6 - 1)(p^2 + 1)-th power.
Parameters
[in] a - the dodecic extension field element to test.
Returns
1 if the extension field element is in the subgroup, 0 otherwise.
Definition at line 504 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp12_cmp(), fp12_frb(), fp12_free, fp12_mul, fp12_new, fp12_null, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp12_exp(), fp12_exp_dig(), fp12_pck(), fp12_pck_max(), fp12_size_bin(), fp12_upk(), fp12_upk_max(), and gt_is_valid().
fp12_back_cyc()
void fp12_back_cyc (fp12_t c, const fp12_t a)
Decompresses a compressed cyclotomic extension field element.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to decompress.
Definition at line 533 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp12_cmp_dig(), fp2_add, fp2_copy(), fp2_copy_sec(), fp2_dbl, fp2_free, fp2_inv(), fp2_is_zero(), fp2_mul, fp2_mul_nor, fp2_new, fp2_null, fp2_set_dig(), fp2_sqr, fp2_sub, fp_add_dig(), RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp12_read_bin(), and fp12_upk().
fp12_back_cyc_sim()
void fp12_back_cyc_sim (fp12_t c[], const fp12_t a[], int n)
Definition at line 604 of file relic_fpx_cyc.c.
References ERR_CAUGHT, ERR_NO_MEMORY, fp12_cmp_dig(), fp2_add, fp2_copy(), fp2_copy_sec(), fp2_dbl, fp2_free, fp2_inv_sim(), fp2_is_zero(), fp2_mul, fp2_mul_nor, fp2_new, fp2_null, fp2_set_dig(), fp2_sqr, fp2_sub, fp_add_dig(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by fp12_exp_cyc(), and fp12_exp_cyc_sps().
fp12_exp_cyc()
void fp12_exp_cyc (fp12_t c, const fp12_t a, const bn_t b)
Computes a power of a cyclotomic dodecic extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 691 of file relic_fpx_cyc.c.
References bn_bits(), bn_get_bit(), bn_ham(), bn_is_even(), bn_is_zero(), bn_rec_naf(), bn_sign(), ERR_CAUGHT, ERR_NO_MEMORY, fp12_back_cyc_sim(), fp12_copy(), fp12_free, fp12_inv_cyc(), fp12_mul, fp12_new, fp12_null, fp12_set_dig(), fp12_sqr_cyc, fp12_sqr_pck, RLC_ALLOCA, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FP_BITS, RLC_FREE, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by fp12_exp(), and fp12_exp_cyc_sim().
fp12_exp_cyc_sim()
void fp12_exp_cyc_sim (fp12_t e, const fp12_t a, const bn_t b, const fp12_t c, const bn_t d)
Computes a power of two cyclotomic dodecic extension field elements.
Parameters
[out] e - the result.
[in] a - the first element to exponentiate.
[in] b - the first exponent.
[in] c - the second element to exponentiate.
[in] d - the second exponent.
Definition at line 819 of file relic_fpx_cyc.c.
References bn_abs(), bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_neg(), bn_new, bn_null, bn_rec_frb(), bn_sign(), EP_BN, ep_curve_embed(), ep_curve_get_ord(), ep_curve_is_pairf(), ERR_CAUGHT, fp12_copy(), fp12_exp_cyc(), fp12_frb(), fp12_free, fp12_inv_cyc(), fp12_mul, fp12_new, fp12_null, fp12_set_dig(), fp12_sqr_cyc, fp_prime_get_par(), RLC_CATCH_ANY, RLC_FINALLY, RLC_MAX, RLC_NEG, RLC_THROW, and RLC_TRY.
fp12_exp_cyc_sps()
void fp12_exp_cyc_sps (fp12_t c, const fp12_t a, const int * b, size_t l, int s)
Computes a power of a cyclotomic dodecic extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent in sparse form.
[in] l - the length of the exponent in sparse form.
[in] s - the sign of the exponent.
Definition at line 932 of file relic_fpx_cyc.c.
References ERR_CAUGHT, ERR_NO_MEMORY, fp12_back_cyc_sim(), fp12_copy(), fp12_free, fp12_inv_cyc(), fp12_mul, fp12_new, fp12_null, fp12_set_dig(), fp12_sqr_pck, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by gt_is_valid(), pp_exp_b12(), pp_exp_bn(), and pp_exp_sm9().
fp16_conv_cyc()
void fp16_conv_cyc (fp16_t c, const fp16_t a)
Converts an sextadecic extension field element to a cyclotomic element. Computes c = a^(p^8 - 1).
Parameters
[out] c - the result.
[in] a - the sextadecic extension field element.
Definition at line 1012 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp16_free, fp16_inv(), fp16_inv_cyc(), fp16_mul, fp16_new, fp16_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_exp_afg16(), pp_exp_fm16(), and pp_exp_kss().
fp16_test_cyc()
int fp16_test_cyc (const fp16_t a)
Tests if an sextadecic extension field element is cyclotomic.
Parameters
[in] a - the sextadecic extension field element to test.
Returns
1 if the extension field element is cyclotomic, 0 otherwise.
Definition at line 1035 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp16_cmp_dig(), fp16_free, fp16_inv_cyc(), fp16_mul, fp16_new, fp16_null, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp16_exp(), fp16_exp_dig(), fp16_size_bin(), and gt_is_valid().
fp16_exp_cyc()
void fp16_exp_cyc (fp16_t c, const fp16_t a, const bn_t b)
Computes a power of a cyclotomic sextadecic extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 1057 of file relic_fpx_cyc.c.
References bn_bits(), bn_is_zero(), bn_rec_naf(), bn_sign(), ERR_CAUGHT, fp16_copy(), fp16_free, fp16_inv_cyc(), fp16_mul, fp16_new, fp16_null, fp16_set_dig(), fp16_sqr_cyc(), RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by fp16_exp(), fp16_exp_cyc_sim(), pp_exp_afg16(), pp_exp_fm16(), and pp_exp_kss().
fp16_exp_cyc_sim()
void fp16_exp_cyc_sim (fp16_t e, const fp16_t a, const bn_t b, const fp16_t c, const bn_t d)
Computes a power of two cyclotomic sextadecic extension field elements.
Parameters
[out] e - the result.
[in] a - the first element to exponentiate.
[in] b - the first exponent.
[in] c - the second element to exponentiate.
[in] d - the second exponent.
Definition at line 1124 of file relic_fpx_cyc.c.
References bn_is_zero(), bn_rec_naf(), bn_sign(), ERR_CAUGHT, fp16_copy(), fp16_exp_cyc(), fp16_free, fp16_inv_cyc(), fp16_mul, fp16_new, fp16_null, fp16_set_dig(), fp16_sqr, fp16_sqr_cyc(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
fp18_conv_cyc()
void fp18_conv_cyc (fp18_t c, const fp18_t a)
Converts an octdecic field element to a cyclotomic element. Computes c = a^(p^9 - 1)*(p^3 + 1).
Parameters
[out] c - the result.
[in] a - the octdecic extension field element.
Definition at line 1226 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp18_frb(), fp18_free, fp18_inv(), fp18_inv_cyc(), fp18_mul, fp18_new, fp18_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_exp_fm(), pp_exp_kss(), and pp_exp_sg().
fp18_test_cyc()
int fp18_test_cyc (const fp18_t a)
Tests if an octdecic extension field element belongs to the cyclotomic subgroup.
A cyclotomic element is one raised to the (p^9 - 1)(p^3 + 1)-th power.
Parameters
[in] a - the octdecic extension field element to test.
Returns
1 if the extension field element is in the subgroup, 0 otherwise.
Definition at line 1257 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp18_cmp(), fp18_frb(), fp18_free, fp18_mul, fp18_new, fp18_null, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp18_exp_dig(), fp18_pck(), fp18_size_bin(), fp18_upk(), and gt_is_valid().
fp18_back_cyc()
void fp18_back_cyc (fp18_t c, const fp18_t a)
Decompresses a compressed cyclotomic extension field element.
Parameters
[out] c - the result.
[in] a - the octdecic field element to decompress.
Definition at line 1286 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp18_cmp_dig(), fp3_add, fp3_copy(), fp3_copy_sec(), fp3_dbl, fp3_free, fp3_inv(), fp3_is_zero(), fp3_mul, fp3_mul_nor(), fp3_new, fp3_null, fp3_set_dig(), fp3_sqr, fp3_sub, fp_add_dig(), RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp18_read_bin(), and fp18_upk().
fp18_back_cyc_sim()
void fp18_back_cyc_sim (fp18_t c[], const fp18_t a[], int n)
Definition at line 1357 of file relic_fpx_cyc.c.
References ERR_CAUGHT, ERR_NO_MEMORY, fp18_cmp_dig(), fp3_add, fp3_copy(), fp3_copy_sec(), fp3_dbl, fp3_free, fp3_inv_sim(), fp3_is_zero(), fp3_mul, fp3_mul_nor(), fp3_new, fp3_null, fp3_set_dig(), fp3_sqr, fp3_sub, fp_add_dig(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by fp18_exp_cyc(), and fp18_exp_cyc_sps().
fp18_exp_cyc()
void fp18_exp_cyc (fp18_t c, const fp18_t a, const bn_t b)
Computes a power of a cyclotomic octdecic extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 1444 of file relic_fpx_cyc.c.
References bn_bits(), bn_get_bit(), bn_ham(), bn_is_even(), bn_is_zero(), bn_rec_naf(), bn_sign(), ERR_CAUGHT, ERR_NO_MEMORY, fp18_back_cyc_sim(), fp18_copy(), fp18_free, fp18_inv_cyc(), fp18_mul, fp18_new, fp18_null, fp18_set_dig(), fp18_sqr_cyc, fp18_sqr_pck, RLC_ALLOCA, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FP_BITS, RLC_FREE, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by fp18_exp_cyc_sim(), and pp_exp_fm().
fp18_exp_cyc_sim()
void fp18_exp_cyc_sim (fp18_t e, const fp18_t a, const bn_t b, const fp18_t c, const bn_t d)
Computes a power of two cyclotomic octdecic extension field elements.
Parameters
[out] e - the result.
[in] a - the first element to exponentiate.
[in] b - the first exponent.
[in] c - the second element to exponentiate.
[in] d - the second exponent.
Definition at line 1575 of file relic_fpx_cyc.c.
References bn_is_zero(), bn_rec_naf(), bn_sign(), ERR_CAUGHT, fp18_copy(), fp18_exp_cyc(), fp18_free, fp18_inv_cyc(), fp18_mul, fp18_new, fp18_null, fp18_set_dig(), fp18_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
fp18_exp_cyc_sps()
void fp18_exp_cyc_sps (fp18_t c, const fp18_t a, const int * b, int l, int s)
Computes a power of a cyclotomic octdecic extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent in sparse form.
[in] l - the length of the exponent in sparse form.
[in] s - the sign of the exponent.
Definition at line 1677 of file relic_fpx_cyc.c.
References ERR_CAUGHT, ERR_NO_MEMORY, fp18_back_cyc_sim(), fp18_copy(), fp18_free, fp18_inv_cyc(), fp18_mul, fp18_new, fp18_null, fp18_set_dig(), fp18_sqr_pck, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by gt_is_valid(), pp_exp_fm(), pp_exp_kss(), and pp_exp_sg().
fp24_conv_cyc()
void fp24_conv_cyc (fp24_t c, const fp24_t a)
Converts a 24-extension field element to a cyclotomic element. Computes c = a^(p^8 - 1)*(p^4 + 1).
Parameters
[out] c - the result.
[in] a - a 24-extension field element.
Definition at line 1757 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp24_frb(), fp24_free, fp24_inv(), fp24_inv_cyc(), fp24_mul, fp24_new, fp24_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_exp_k24().
fp24_test_cyc()
int fp24_test_cyc (const fp24_t a)
Tests if a 24-extension field element belongs to the cyclotomic subgroup.
A cyclotomic element is one raised to the (p^8 - 1)(p^4 + 1)-th power.
Parameters
[in] a - the 24-extension field element to test.
Returns
1 if the extension field element is in the subgroup, 0 otherwise.
Definition at line 1788 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp24_cmp(), fp24_frb(), fp24_free, fp24_mul, fp24_new, fp24_null, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp24_exp_dig(), fp24_pck(), fp24_size_bin(), fp24_upk(), and gt_is_valid().
fp24_back_cyc()
void fp24_back_cyc (fp24_t c, const fp24_t a)
Decompresses a compressed cyclotomic extension field element.
Parameters
[out] c - the result.
[in] a - the 24-extension field element to decompress.
Definition at line 1817 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp24_cmp_dig(), fp4_add(), fp4_copy(), fp4_copy_sec(), fp4_dbl(), fp4_free, fp4_inv(), fp4_is_zero(), fp4_mul, fp4_mul_art(), fp4_new, fp4_null, fp4_set_dig(), fp4_sqr, fp4_sub(), fp_add_dig(), RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp24_read_bin(), and fp24_upk().
fp24_back_cyc_sim()
void fp24_back_cyc_sim (fp24_t c[], const fp24_t a[], int n)
Definition at line 1887 of file relic_fpx_cyc.c.
References ERR_CAUGHT, ERR_NO_MEMORY, fp24_cmp_dig(), fp4_add(), fp4_copy(), fp4_copy_sec(), fp4_dbl(), fp4_free, fp4_inv_sim(), fp4_is_zero(), fp4_mul, fp4_mul_art(), fp4_new, fp4_null, fp4_set_dig(), fp4_sqr, fp4_sub(), fp_add_dig(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by fp24_exp_cyc(), and fp24_exp_cyc_sps().
fp24_exp_cyc()
void fp24_exp_cyc (fp24_t c, const fp24_t a, const bn_t b)
Computes a power of a cyclotomic 24-extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 1974 of file relic_fpx_cyc.c.
References bn_bits(), bn_get_bit(), bn_ham(), bn_is_even(), bn_is_zero(), bn_rec_naf(), bn_sign(), ERR_CAUGHT, ERR_NO_MEMORY, fp24_back_cyc_sim(), fp24_copy(), fp24_free, fp24_inv_cyc(), fp24_mul, fp24_new, fp24_null, fp24_set_dig(), fp24_sqr_cyc, fp24_sqr_pck, RLC_ALLOCA, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FP_BITS, RLC_FREE, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by fp24_exp_cyc_sim().
fp24_exp_cyc_sim()
void fp24_exp_cyc_sim (fp24_t e, const fp24_t a, const bn_t b, const fp24_t c, const bn_t d)
Computes a power of two cyclotomic dodecic extension field elements.
Parameters
[out] e - the result.
[in] a - the first element to exponentiate.
[in] b - the first exponent.
[in] c - the second element to exponentiate.
[in] d - the second exponent.
Definition at line 2105 of file relic_fpx_cyc.c.
References bn_is_zero(), bn_rec_naf(), bn_sign(), ERR_CAUGHT, fp24_copy(), fp24_exp_cyc(), fp24_free, fp24_inv_cyc(), fp24_mul, fp24_new, fp24_null, fp24_set_dig(), fp24_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
fp24_exp_cyc_sps()
void fp24_exp_cyc_sps (fp24_t c, const fp24_t a, const int * b, size_t l, int s)
Computes a power of a cyclotomic 24-extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent in sparse form.
[in] l - the length of the exponent in sparse form.
[in] s - the sign of the exponent.
Definition at line 2207 of file relic_fpx_cyc.c.
References ERR_CAUGHT, ERR_NO_MEMORY, fp24_back_cyc_sim(), fp24_copy(), fp24_free, fp24_inv_cyc(), fp24_mul, fp24_new, fp24_null, fp24_set_dig(), fp24_sqr_pck, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by gt_is_valid(), and pp_exp_k24().
fp48_conv_cyc()
void fp48_conv_cyc (fp48_t c, const fp48_t a)
Converts a 48-extension field element to a cyclotomic element. Computes c = a^(p^16 - 1)*(p^8 + 1).
Parameters
[out] c - the result.
[in] a - a 48-extension field element.
Definition at line 2287 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp48_frb(), fp48_free, fp48_inv(), fp48_inv_cyc(), fp48_mul, fp48_new, fp48_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_exp_k48().
fp48_test_cyc()
int fp48_test_cyc (const fp48_t a)
Tests if a 48-extension field element belongs to the cyclotomic subgroup.
A cyclotomic element is one raised to the (p^16 - 1)(p^8 + 1)-th power.
Parameters
[in] a - the 48-extension field element to test.
Returns
1 if the extension field element is in the subgroup, 0 otherwise.
Definition at line 2318 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp48_cmp(), fp48_frb(), fp48_free, fp48_mul, fp48_new, fp48_null, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp48_exp(), fp48_exp_dig(), fp48_pck(), fp48_size_bin(), fp48_upk(), and gt_is_valid().
fp48_back_cyc()
void fp48_back_cyc (fp48_t c, const fp48_t a)
Decompresses a compressed cyclotomic extension field element.
Parameters
[out] c - the result.
[in] a - the 48-extension field element to decompress.
Definition at line 2347 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp48_cmp_dig(), fp8_add(), fp8_copy(), fp8_copy_sec(), fp8_dbl(), fp8_free, fp8_inv(), fp8_is_zero(), fp8_mul, fp8_mul_art(), fp8_new, fp8_null, fp8_set_dig(), fp8_sqr, fp8_sub(), fp_add_dig(), RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp48_read_bin(), and fp48_upk().
fp48_back_cyc_sim()
void fp48_back_cyc_sim (fp48_t c[], const fp48_t a[], int n)
Definition at line 2418 of file relic_fpx_cyc.c.
References ERR_CAUGHT, ERR_NO_MEMORY, fp48_cmp_dig(), fp8_add(), fp8_copy(), fp8_copy_sec(), fp8_dbl(), fp8_free, fp8_inv_sim(), fp8_is_zero(), fp8_mul, fp8_mul_art(), fp8_new, fp8_null, fp8_set_dig(), fp8_sqr, fp8_sub(), fp_add_dig(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by fp48_exp_cyc(), and fp48_exp_cyc_sps().
fp48_exp_cyc()
void fp48_exp_cyc (fp48_t c, const fp48_t a, const bn_t b)
Computes a power of a cyclotomic 48-extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 2505 of file relic_fpx_cyc.c.
References bn_bits(), bn_get_bit(), bn_ham(), bn_is_even(), bn_is_zero(), bn_rec_naf(), bn_sign(), ERR_CAUGHT, ERR_NO_MEMORY, fp48_back_cyc_sim(), fp48_copy(), fp48_free, fp48_inv_cyc(), fp48_mul, fp48_new, fp48_null, fp48_set_dig(), fp48_sqr_cyc, fp48_sqr_pck, RLC_ALLOCA, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FP_BITS, RLC_FREE, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by fp48_exp(), and fp48_exp_cyc_sim().
fp48_exp_cyc_sim()
void fp48_exp_cyc_sim (fp48_t e, const fp48_t a, const bn_t b, const fp48_t c, const bn_t d)
Computes a power of two cyclotomic 48-extension field elements.
Parameters
[out] e - the result.
[in] a - the first element to exponentiate.
[in] b - the first exponent.
[in] c - the second element to exponentiate.
[in] d - the second exponent.
Definition at line 2636 of file relic_fpx_cyc.c.
References bn_is_zero(), bn_rec_naf(), bn_sign(), ERR_CAUGHT, fp48_copy(), fp48_exp_cyc(), fp48_free, fp48_inv_cyc(), fp48_mul, fp48_new, fp48_null, fp48_set_dig(), fp48_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
fp48_exp_cyc_sps()
void fp48_exp_cyc_sps (fp48_t c, const fp48_t a, const int * b, size_t l, int s)
Computes a power of a cyclotomic 48-extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent in sparse form.
[in] l - the length of the exponent in sparse form.
[in] s - the sign of the exponent.
Definition at line 2738 of file relic_fpx_cyc.c.
References ERR_CAUGHT, ERR_NO_MEMORY, fp48_back_cyc_sim(), fp48_copy(), fp48_free, fp48_inv_cyc(), fp48_mul, fp48_new, fp48_null, fp48_set_dig(), fp48_sqr_pck, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by gt_is_valid(), and pp_exp_k48().
fp54_conv_cyc()
void fp54_conv_cyc (fp54_t c, const fp54_t a)
Converts a 54-extension field element to a cyclotomic element. Computes c = a^(p^18 - 1)*(p^9 + 1).
Parameters
[out] c - the result.
[in] a - a 54-extension field element.
Definition at line 2818 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp54_frb(), fp54_free, fp54_inv(), fp54_inv_cyc(), fp54_mul, fp54_new, fp54_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_exp_k54().
fp54_test_cyc()
int fp54_test_cyc (const fp54_t a)
Tests if a 54-extension field element belongs to the cyclotomic subgroup.
A cyclotomic element is one raised to the (p^18 - 1)(p^9 + 1)-th power.
Parameters
[in] a - the 54-extension field element to test.
Returns
1 if the extension field element is in the subgroup, 0 otherwise.
Definition at line 2849 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp54_cmp(), fp54_frb(), fp54_free, fp54_mul, fp54_new, fp54_null, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp54_exp_dig(), fp54_pck(), fp54_size_bin(), and fp54_upk().
fp54_back_cyc()
void fp54_back_cyc (fp54_t c, const fp54_t a)
Decompresses a compressed cyclotomic extension field element.
Parameters
[out] c - the result.
[in] a - the 54-extension field element to decompress.
Definition at line 2877 of file relic_fpx_cyc.c.
References ERR_CAUGHT, fp54_cmp_dig(), fp9_add(), fp9_copy(), fp9_copy_sec(), fp9_dbl(), fp9_free, fp9_inv(), fp9_is_zero(), fp9_mul, fp9_mul_art(), fp9_new, fp9_null, fp9_set_dig(), fp9_sqr, fp9_sub(), fp_add_dig(), RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp54_read_bin(), and fp54_upk().
fp54_back_cyc_sim()
void fp54_back_cyc_sim (fp54_t c[], const fp54_t a[], int n)
Definition at line 2950 of file relic_fpx_cyc.c.
References ERR_CAUGHT, ERR_NO_MEMORY, fp54_cmp_dig(), fp9_add(), fp9_copy(), fp9_copy_sec(), fp9_dbl(), fp9_free, fp9_inv_sim(), fp9_is_zero(), fp9_mul, fp9_mul_art(), fp9_new, fp9_null, fp9_set_dig(), fp9_sqr, fp9_sub(), fp_add_dig(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by fp54_exp_cyc(), and fp54_exp_cyc_sps().
fp54_exp_cyc()
void fp54_exp_cyc (fp54_t c, const fp54_t a, const bn_t b)
Computes a power of a cyclotomic 54-extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 3037 of file relic_fpx_cyc.c.
References bn_bits(), bn_get_bit(), bn_ham(), bn_is_even(), bn_is_zero(), bn_sign(), ERR_CAUGHT, ERR_NO_MEMORY, fp54_back_cyc_sim(), fp54_copy(), fp54_free, fp54_inv_cyc(), fp54_mul, fp54_new, fp54_null, fp54_set_dig(), fp54_sqr_cyc, fp54_sqr_pck, RLC_ALLOCA, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.
fp54_exp_cyc_sps()
void fp54_exp_cyc_sps (fp54_t c, const fp54_t a, const int * b, size_t l, int s)
Computes a power of a cyclotomic 54-extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent in sparse form.
[in] l - the length of the exponent in sparse form.
[in] s - the sign of the exponent.
Definition at line 3133 of file relic_fpx_cyc.c.
References ERR_CAUGHT, ERR_NO_MEMORY, fp54_back_cyc_sim(), fp54_copy(), fp54_free, fp54_inv_cyc(), fp54_mul, fp54_new, fp54_null, fp54_set_dig(), fp54_sqr_pck, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by pp_exp_k54().