RELIC: include/relic_bn.h File Reference
relic_bn.h File Reference
Multiple precision integer arithmetic
#include "relic_conf.h"
#include "relic_util.h"
#include "relic_types.h"
#include "relic_label.h"
Data Structures
struct bn_st
struct crt_st
Macros
#define RLC_BN_BITS ((size_t)BN_PRECI)
#define RLC_BN_DIGS ((size_t)RLC_CEIL(BN_PRECI, RLC_DIG))
#define RLC_BN_SIZE ((size_t)(2 * RLC_BN_DIGS + 2))
#define RLC_POS 0
#define RLC_NEG 1
#define bn_null(A)
#define bn_new(A)
#define bn_new_size(A, D)
#define bn_free(A)
#define crt_null(A)
#define crt_new(A)
#define crt_free(A)
#define bn_mul(C, A, B)
#define bn_sqr(C, A)
#define bn_mod_pre(U, M)
#define bn_mod(C, A, ...)
#define bn_mod_imp(C, A, M, U)
#define bn_mod_monty(C, A, M, U)
#define bn_mxp(C, A, B, M)
#define bn_gcd(C, A, B)
#define bn_gcd_ext(C, D, E, A, B)
#define bn_gen_prime(A, B)
Typedefs
typedef bn_st bn_t[1]
typedef crt_st crt_t[1]
Functions
void bn_make (bn_t a, size_t digits)
void bn_clean (bn_t a)
void bn_grow (bn_t a, size_t digits)
void bn_trim (bn_t a)
void bn_copy (bn_t c, const bn_t a)
void bn_abs (bn_t c, const bn_t a)
void bn_neg (bn_t c, const bn_t a)
int bn_sign (const bn_t a)
void bn_zero (bn_t a)
int bn_is_zero (const bn_t a)
int bn_is_even (const bn_t a)
size_t bn_bits (const bn_t a)
int bn_get_bit (const bn_t a, uint_t bit)
void bn_set_bit (bn_t a, uint_t bit, int value)
uint_t bn_ham (const bn_t a)
void bn_get_dig (dig_t *digit, const bn_t a)
void bn_set_dig (bn_t a, dig_t digit)
void bn_set_2b (bn_t a, size_t b)
void bn_rand (bn_t a, int sign, size_t bits)
void bn_rand_mod (bn_t a, const bn_t b)
void bn_print (const bn_t a)
size_t bn_size_str (const bn_t a, uint_t radix)
void bn_read_str (bn_t a, const char *str, size_t len, uint_t radix)
void bn_write_str (char *str, size_t len, const bn_t a, uint_t radix)
size_t bn_size_bin (const bn_t a)
void bn_read_bin (bn_t a, const uint8_t *bin, size_t len)
void bn_write_bin (uint8_t *bin, size_t len, const bn_t a)
size_t bn_size_raw (const bn_t a)
void bn_read_raw (bn_t a, const dig_t *raw, size_t len)
void bn_write_raw (dig_t *raw, size_t len, const bn_t a)
int bn_cmp_abs (const bn_t a, const bn_t b)
int bn_cmp_dig (const bn_t a, dig_t b)
int bn_cmp (const bn_t a, const bn_t b)
void bn_add (bn_t c, const bn_t a, const bn_t b)
void bn_add_dig (bn_t c, const bn_t a, dig_t b)
void bn_sub (bn_t c, const bn_t a, const bn_t b)
void bn_sub_dig (bn_t c, const bn_t a, const dig_t b)
void bn_mul_dig (bn_t c, const bn_t a, dig_t b)
void bn_mul_basic (bn_t c, const bn_t a, const bn_t b)
void bn_mul_comba (bn_t c, const bn_t a, const bn_t b)
void bn_mul_karat (bn_t c, const bn_t a, const bn_t b)
void bn_sqr_basic (bn_t c, const bn_t a)
void bn_sqr_comba (bn_t c, const bn_t a)
void bn_sqr_karat (bn_t c, const bn_t a)
void bn_dbl (bn_t c, const bn_t a)
void bn_hlv (bn_t c, const bn_t a)
void bn_lsh (bn_t c, const bn_t a, uint_t bits)
void bn_rsh (bn_t c, const bn_t a, uint_t bits)
void bn_div (bn_t c, const bn_t a, const bn_t b)
void bn_div_rem (bn_t c, bn_t d, const bn_t a, const bn_t b)
void bn_div_dig (bn_t c, const bn_t a, dig_t b)
void bn_div_rem_dig (bn_t c, dig_t *d, const bn_t a, const dig_t b)
void bn_mod_inv (bn_t c, const bn_t a, const bn_t b)
void bn_mod_inv_sim (bn_t *c, const bn_t *a, const bn_t b, int n)
void bn_mod_2b (bn_t c, const bn_t a, int b)
void bn_mod_dig (dig_t *c, const bn_t a, dig_t b)
void bn_mod_basic (bn_t c, const bn_t a, const bn_t m)
void bn_mod_pre_barrt (bn_t u, const bn_t m)
void bn_mod_barrt (bn_t c, const bn_t a, const bn_t m, const bn_t u)
void bn_mod_pre_monty (bn_t u, const bn_t m)
void bn_mod_monty_conv (bn_t c, const bn_t a, const bn_t m)
void bn_mod_monty_back (bn_t c, const bn_t a, const bn_t m)
void bn_mod_monty_basic (bn_t c, const bn_t a, const bn_t m, const bn_t u)
void bn_mod_monty_comba (bn_t c, const bn_t a, const bn_t m, const bn_t u)
void bn_mod_pre_pmers (bn_t u, const bn_t m)
void bn_mod_pmers (bn_t c, const bn_t a, const bn_t m, const bn_t u)
void bn_mxp_basic (bn_t c, const bn_t a, const bn_t b, const bn_t m)
void bn_mxp_slide (bn_t c, const bn_t a, const bn_t b, const bn_t m)
void bn_mxp_monty (bn_t c, const bn_t a, const bn_t b, const bn_t m)
void bn_mxp_dig (bn_t c, const bn_t a, dig_t b, const bn_t m)
void bn_mxp_crt (bn_t d, const bn_t a, const bn_t b, const bn_t c, const crt_t crt, int sqr)
void bn_mxp_sim (bn_t c, const bn_t a, const bn_t b, const bn_t d, const bn_t e, const bn_t m)
void bn_mxp_sim_few (bn_t c, const bn_t *a, const bn_t *b, const bn_t m, size_t n)
void bn_mxp_sim_lot (bn_t c, const bn_t *a, const bn_t *b, const bn_t m, size_t n)
void bn_srt (bn_t c, bn_t a)
void bn_gcd_basic (bn_t c, const bn_t a, const bn_t b)
void bn_gcd_lehme (bn_t c, const bn_t a, const bn_t b)
void bn_gcd_binar (bn_t c, const bn_t a, const bn_t b)
void bn_gcd_dig (bn_t c, const bn_t a, dig_t b)
void bn_gcd_ext_basic (bn_t c, bn_t d, bn_t e, const bn_t a, const bn_t b)
void bn_gcd_ext_lehme (bn_t c, bn_t d, bn_t e, const bn_t a, const bn_t b)
void bn_gcd_ext_binar (bn_t c, bn_t d, bn_t e, const bn_t a, const bn_t b)
void bn_gcd_ext_mid (bn_t c, bn_t d, bn_t e, bn_t f, const bn_t a, const bn_t b)
void bn_gcd_ext_dig (bn_t c, bn_t d, bn_t e, const bn_t a, dig_t b)
void bn_lcm (bn_t c, const bn_t a, const bn_t b)
int bn_smb_leg (const bn_t a, const bn_t b)
int bn_smb_jac (const bn_t a, const bn_t b)
int bn_is_prime (const bn_t a)
int bn_is_prime_basic (const bn_t a)
int bn_is_prime_rabin (const bn_t a)
int bn_is_prime_solov (const bn_t a)
void bn_gen_prime_basic (bn_t a, size_t bits)
void bn_gen_prime_safep (bn_t a, size_t bits)
void bn_gen_prime_stron (bn_t a, size_t bits)
int bn_gen_prime_factor (bn_t a, bn_t b, size_t abits, size_t bbits)
int bn_factor (bn_t c, const bn_t a)
int bn_is_factor (bn_t c, const bn_t a)
void bn_rec_win (uint8_t *win, size_t *len, const bn_t k, size_t w)
void bn_rec_slw (uint8_t *win, size_t *len, const bn_t k, size_t w)
void bn_rec_naf (int8_t *naf, size_t *len, const bn_t k, size_t w)
void bn_rec_tnaf (int8_t *tnaf, size_t *len, const bn_t k, int8_t u, size_t m, size_t w)
void bn_rec_rtnaf (int8_t *tnaf, size_t *len, const bn_t k, int8_t u, size_t m, size_t w)
void bn_rec_tnaf_get (uint8_t *t, int8_t *beta, int8_t *gama, int8_t u, size_t w)
void bn_rec_tnaf_mod (bn_t r0, bn_t r1, const bn_t k, int u, size_t m)
void bn_rec_reg (int8_t *naf, size_t *len, const bn_t k, size_t n, size_t w)
void bn_rec_jsf (int8_t *jsf, size_t *len, const bn_t k, const bn_t l)
void bn_rec_glv (bn_t k0, bn_t k1, const bn_t k, const bn_t n, const bn_t v1[], const bn_t v2[])
void bn_rec_frb (bn_t *ki, int sub, const bn_t k, const bn_t x, const bn_t n, int cof)
void bn_rec_sac (int8_t *b, size_t *len, bn_t *k, size_t c, size_t m, size_t n)
void bn_lag (bn_t *c, const bn_t *a, const bn_t b, size_t n)
void bn_evl (bn_t c, const bn_t *a, const bn_t x, const bn_t b, size_t n)
Detailed Description
Interface of the module for multiple precision integer arithmetic.
Definition in file relic_bn.h.
Macro Definition Documentation
RLC_BN_BITS
#define RLC_BN_BITS ((size_t)BN_PRECI)
Precision in bits of a multiple precision integer.
If the library is built with support for dynamic allocation, this constant represents the size in bits of the memory block allocated each time a multiple precision integer must grow. Otherwise, it represents the fixed fixed precision.
Definition at line 56 of file relic_bn.h.
Referenced by conf_print(), cp_rsapsi_ans(), cp_rsapsi_ask(), cp_shipsi_ans(), and cp_shipsi_ask().
RLC_BN_DIGS
#define RLC_BN_DIGS ((size_t)RLC_CEIL(BN_PRECI, RLC_DIG))
Size in digits of a block sufficient to store the required precision.
Definition at line 61 of file relic_bn.h.
Referenced by conf_print().
RLC_BN_SIZE
#define RLC_BN_SIZE ((size_t)(2 * RLC_BN_DIGS + 2))
Size in digits of a block sufficient to store a multiple precision integer.
Definition at line 67 of file relic_bn.h.
Referenced by bn_grow(), bn_make(), and bn_set_2b().
RLC_POS
#define RLC_POS 0
Positive sign of a multiple precision integer.
Definition at line 77 of file relic_bn.h.
Referenced by bn_abs(), bn_add_dig(), bn_clean(), bn_cmp(), bn_div_imp(), bn_gen_prime_basic(), bn_gen_prime_factor(), bn_gen_prime_safep(), bn_gen_prime_stron(), bn_is_prime_solov(), bn_lcm(), bn_make(), bn_mod_barrt(), bn_mod_monty_back(), bn_mod_monty_basic(), bn_mod_monty_comba(), bn_mod_monty_conv(), bn_mod_pmers(), bn_mod_pre_barrt(), bn_mod_pre_monty(), bn_mod_pre_pmers(), bn_read_bin(), bn_read_raw(), bn_read_str(), bn_rec_frb(), bn_set_2b(), bn_set_dig(), bn_size_str(), bn_sqr_basic(), bn_sqr_comba(), bn_sqr_karat_imp(), bn_sub(), bn_sub_dig(), bn_trim(), bn_write_str(), bn_zero(), cp_bbs_gen(), cp_bdpe_gen(), cp_ecdsa_ver(), cp_ecss_ver(), cp_lvprv_gen(), cp_lvpub_ask(), cp_pdprv_gen(), cp_pdpub_gen(), eb_mul_halve(), ed_map_ell2_5mod8(), ed_param_set(), ep2_mul_reg_gls(), ep_curve_set_endom(), ep_mul_combs_endom(), ep_mul_glv_imp(), ep_mul_reg_glv(), ep_mul_sim_endom(), fp_inv_divst(), fp_inv_jmpds(), fp_is_cub(), fp_prime_back(), fp_smb_basic(), fp_smb_binar(), fp_smb_divst(), gt_exp_reg_gls(), pp_exp_afg16(), pp_exp_bn(), pp_exp_fm(), pp_exp_k2(), pp_exp_k24(), pp_exp_sg(), and pp_exp_sm9().
RLC_NEG
#define RLC_NEG 1
Negative sign of a multiple precision integer.
Definition at line 82 of file relic_bn.h.
Referenced by bn_add_dig(), bn_cmp(), bn_cmp_dig(), bn_div_imp(), bn_div_rem_dig(), bn_mod_barrt(), bn_mod_inv(), bn_mod_pmers(), bn_mxp_basic(), bn_mxp_crt(), bn_mxp_monty(), bn_mxp_slide(), bn_print(), bn_read_str(), bn_rec_frb(), bn_rec_rtnaf(), bn_rec_tnaf(), bn_size_str(), bn_smb_jac(), bn_smb_leg(), bn_srt(), bn_sub(), bn_sub_dig(), bn_write_str(), cp_ghpe_dec(), cp_mpsb_sig(), cp_mpsb_ver(), cp_rabin_dec(), cp_rsa_gen(), eb_mul_basic(), eb_mul_fix_basic(), eb_mul_fix_combd(), eb_mul_fix_combs(), eb_mul_fix_kbltz(), eb_mul_fix_plain(), eb_mul_lnaf_imp(), eb_mul_lodah(), eb_mul_ltnaf_imp(), eb_mul_rnaf_imp(), eb_mul_rtnaf_imp(), eb_mul_sim_joint(), eb_mul_sim_kbltz(), eb_mul_sim_plain(), eb_mul_sim_trick(), ed_mul_basic(), ed_mul_combs_plain(), ed_mul_fix_basic(), ed_mul_fix_combd(), ed_mul_fix_plain(), ed_mul_monty(), ed_mul_naf_imp(), ed_mul_reg_imp(), ed_mul_sim_joint(), ed_mul_sim_lot(), ed_mul_sim_plain(), ed_mul_sim_trick(), ed_mul_slide(), ep2_mul_basic(), ep2_mul_fix_plain(), ep2_mul_gls_imp(), ep2_mul_naf_imp(), ep2_mul_reg_gls(), ep2_mul_reg_imp(), ep2_mul_sim_endom(), ep2_mul_sim_joint(), ep2_mul_sim_lot(), ep2_mul_sim_plain(), ep2_mul_slide(), ep3_mul_basic(), ep3_mul_fix_plain(), ep3_mul_gls_imp(), ep3_mul_naf_imp(), ep3_mul_reg_gls(), ep3_mul_reg_imp(), ep3_mul_sim_joint(), ep3_mul_sim_lot(), ep3_mul_sim_plain(), ep3_mul_sim_trick(), ep3_mul_slide(), ep4_mul_basic(), ep4_mul_fix_combd(), ep4_mul_fix_ordin(), ep4_mul_gls_imp(), ep4_mul_naf_imp(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), ep4_mul_sim_joint(), ep4_mul_sim_lot(), ep4_mul_sim_plain(), ep4_mul_sim_trick(), ep4_mul_slide(), ep8_mul_basic(), ep8_mul_fix_combd(), ep8_mul_fix_ordin(), ep8_mul_gls_imp(), ep8_mul_naf_imp(), ep8_mul_reg_gls(), ep8_mul_reg_imp(), ep8_mul_sim_joint(), ep8_mul_sim_lot(), ep8_mul_sim_plain(), ep8_mul_sim_trick(), ep8_mul_slide(), ep_curve_set_endom(), ep_mul_basic(), ep_mul_fix_plain(), ep_mul_reg_imp(), ep_mul_sim_endom(), ep_mul_sim_joint(), ep_mul_sim_lot_endom(), ep_mul_sim_lot_plain(), ep_mul_sim_plain(), ep_param_set(), fb_exp_basic(), fb_exp_monty(), fb_exp_slide(), fp12_exp(), fp12_exp_cyc(), fp12_exp_cyc_sim(), fp12_exp_cyc_sps(), fp16_exp(), fp16_exp_cyc(), fp16_exp_cyc_sim(), fp18_exp(), fp18_exp_cyc(), fp18_exp_cyc_sim(), fp18_exp_cyc_sps(), fp24_exp(), fp24_exp_cyc(), fp24_exp_cyc_sim(), fp24_exp_cyc_sps(), fp2_exp(), fp2_exp_cyc(), fp2_exp_cyc_sim(), fp3_exp(), fp48_exp(), fp48_exp_cyc(), fp48_exp_cyc_sim(), fp48_exp_cyc_sps(), fp4_exp(), fp54_exp(), fp54_exp_cyc(), fp54_exp_cyc_sps(), fp6_exp(), fp8_exp(), fp8_exp_cyc(), fp8_exp_cyc_sim(), fp9_exp(), fp_exp_basic(), fp_exp_monty(), fp_exp_slide(), fp_inv_binar(), fp_inv_exgcd(), fp_read_bin(), fp_read_str(), g1_is_valid(), g1_mul(), g1_mul_lcl(), g2_mul(), g2_mul_lcl(), gt_exp(), gt_exp_gls_naf(), gt_exp_gls_sac(), gt_exp_lcl(), gt_exp_reg_gls(), gt_exp_reg_sac(), gt_exp_sec(), mpc_mt_lcl(), mpc_mt_mul(), pp_exp_afg16(), pp_exp_bn(), pp_exp_fm(), pp_exp_k24(), pp_exp_sg(), pp_map_k24(), pp_map_k48(), pp_map_k54(), pp_map_oatep_k12(), pp_map_oatep_k16(), pp_map_oatep_k18(), pp_map_oatep_k8(), pp_map_sim_k24(), pp_map_sim_k48(), pp_map_sim_oatep_k12(), pp_map_sim_oatep_k16(), pp_map_sim_oatep_k18(), and pp_map_sim_oatep_k8().
bn_null
#define bn_null (A)
Value:
/* empty */
Initializes a multiple precision integer with a null value.
Parameters
[out] A - the multiple precision integer to initialize.
Definition at line 158 of file relic_bn.h.
Referenced by bn_div_dig(), bn_div_imp(), bn_div_rem_dig(), bn_factor(), bn_gcd_basic(), bn_gcd_binar(), bn_gcd_ext_basic(), bn_gcd_ext_binar(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_lehme(), bn_gen_prime_factor(), bn_gen_prime_stron(), bn_is_factor(), bn_is_prime_rabin(), bn_is_prime_solov(), bn_lag(), bn_lcm(), bn_mod_barrt(), bn_mod_inv(), bn_mod_inv_sim(), bn_mod_monty_back(), bn_mod_monty_basic(), bn_mod_monty_comba(), bn_mod_pmers(), bn_mul_basic(), bn_mul_comba(), bn_mul_karat_imp(), bn_mxp_basic(), bn_mxp_crt(), bn_mxp_dig(), bn_mxp_monty(), bn_mxp_sim(), bn_mxp_sim_few(), bn_mxp_sim_lot(), bn_mxp_slide(), bn_rand_mod(), bn_rec_frb(), bn_rec_glv(), bn_rec_jsf(), bn_rec_naf(), bn_rec_reg(), bn_rec_rtnaf(), bn_rec_sac(), bn_rec_tnaf(), bn_rec_tnaf_mod(), bn_size_str(), bn_smb_jac(), bn_smb_leg(), bn_sqr_basic(), bn_sqr_comba(), bn_sqr_karat_imp(), bn_srt(), bn_write_str(), cp_bbs_gen(), cp_bbs_sig(), cp_bbs_ver(), cp_bdpe_dec(), cp_bdpe_enc(), cp_bdpe_gen(), cp_bgn_dec(), cp_bgn_dec1(), cp_bgn_dec2(), cp_bgn_enc1(), cp_bgn_enc2(), cp_bgn_gen(), cp_bls_gen(), cp_clb_gen(), cp_clb_sig(), cp_clb_ver(), cp_cli_gen(), cp_cli_sig(), cp_cli_ver(), cp_cls_gen(), cp_cls_sig(), cp_cls_ver(), cp_cmlhs_gen(), cp_cmlhs_onv(), cp_cmlhs_sig(), cp_cmlhs_ver(), cp_ecdh_gen(), cp_ecdh_key(), cp_ecdsa_gen(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ecies_dec(), cp_ecies_enc(), cp_ecies_gen(), cp_ecmqv_gen(), cp_ecmqv_key(), cp_ecss_gen(), cp_ecss_sig(), cp_ecss_ver(), cp_ers_ext(), cp_ers_gen_key(), cp_ers_sig(), cp_ers_ver(), cp_etrs_ext(), cp_etrs_sig(), cp_etrs_uni(), cp_etrs_ver(), cp_ghpe_dec(), cp_ghpe_enc(), cp_ghpe_gen(), cp_ibe_enc(), cp_ibe_gen(), cp_lvprv_ask(), cp_lvprv_gen(), cp_lvpub_gen(), cp_mklhs_fun(), cp_mklhs_gen(), cp_mklhs_onv(), cp_mklhs_sig(), cp_mklhs_ver(), cp_mpsb_gen(), cp_mpsb_sig(), cp_mpsb_ver(), cp_mpss_gen(), cp_mpss_sig(), cp_mpss_ver(), cp_pbpsi_ans(), cp_pbpsi_ask(), cp_pbpsi_gen(), cp_pdprv_ask(), cp_pdprv_gen(), cp_pdpub_gen(), cp_phpe_add(), cp_phpe_dec(), cp_phpe_enc(), cp_pokdl_prv(), cp_pokdl_ver(), cp_pokor_prv(), cp_pokor_ver(), cp_psb_gen(), cp_psb_sig(), cp_psb_ver(), cp_pss_gen(), cp_pss_sig(), cp_rabin_dec(), cp_rabin_enc(), cp_rabin_gen(), cp_rsa_dec(), cp_rsa_enc(), cp_rsa_gen(), cp_rsa_sig(), cp_rsa_ver(), cp_rsapsi_ans(), cp_rsapsi_gen(), cp_rsapsi_int(), cp_shipsi_ans(), cp_shipsi_int(), cp_shpe_dec(), cp_shpe_enc(), cp_shpe_enc_prv(), cp_smlers_ext(), cp_smlers_ver(), cp_sokaka_gen(), cp_sokdl_sig(), cp_sokdl_ver(), cp_sokor_sig(), cp_sokor_ver(), cp_vbnn_gen(), cp_vbnn_gen_prv(), cp_vbnn_sig(), cp_vbnn_ver(), cp_zss_gen(), cp_zss_sig(), cp_zss_ver(), eb_map(), eb_mul_fix_combd(), eb_mul_fix_combs(), eb_mul_halve(), eb_mul_lodah(), eb_mul_pre_basic(), eb_mul_pre_combd(), eb_mul_pre_combs(), eb_mul_sim_trick(), eb_param_set(), eb_rand(), ed_map_dst(), ed_map_ell2_5mod8(), ed_mul_combs_plain(), ed_mul_dig(), ed_mul_fix_combd(), ed_mul_pre_basic(), ed_mul_pre_combd(), ed_mul_pre_combs(), ed_mul_reg_imp(), ed_mul_sim_trick(), ed_param_set(), ed_rand(), ep2_curve_set_map(), ep2_curve_set_twist(), ep2_frb(), ep2_map_basic(), ep2_map_from_field(), ep2_map_swift(), ep2_mul_cof(), ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep2_mul_dig(), ep2_mul_fix_basic(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_fix_lwnaf(), ep2_mul_gls_imp(), ep2_mul_monty(), ep2_mul_pre_basic(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_reg_gls(), ep2_mul_reg_imp(), ep2_mul_sim_endom(), ep2_mul_sim_gen(), ep2_mul_sim_joint(), ep2_mul_sim_lot(), ep2_mul_sim_trick(), ep2_pck(), ep2_rand(), ep2_upk(), ep3_curve_set_twist(), ep3_map(), ep3_mul_cof(), ep3_mul_cof_fm18(), ep3_mul_cof_k18(), ep3_mul_cof_sg18(), ep3_mul_dig(), ep3_mul_fix_basic(), ep3_mul_fix_combd(), ep3_mul_fix_combs(), ep3_mul_fix_lwnaf(), ep3_mul_gls_imp(), ep3_mul_monty(), ep3_mul_pre_basic(), ep3_mul_pre_combd(), ep3_mul_pre_combs(), ep3_mul_reg_gls(), ep3_mul_reg_imp(), ep3_mul_sim_lot(), ep3_mul_sim_trick(), ep3_rand(), ep4_curve_set_twist(), ep4_map(), ep4_mul_cof(), ep4_mul_cof_afg16(), ep4_mul_cof_b24(), ep4_mul_cof_fm16(), ep4_mul_cof_k16(), ep4_mul_dig(), ep4_mul_fix_basic(), ep4_mul_fix_combd(), ep4_mul_fix_combs(), ep4_mul_gls_imp(), ep4_mul_monty(), ep4_mul_pre_basic(), ep4_mul_pre_combd(), ep4_mul_pre_combs(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), ep4_mul_sim_lot(), ep4_mul_sim_trick(), ep4_rand(), ep8_curve_set_twist(), ep8_map(), ep8_mul_cof(), ep8_mul_dig(), ep8_mul_fix_basic(), ep8_mul_fix_combd(), ep8_mul_fix_combs(), ep8_mul_gls_imp(), ep8_mul_monty(), ep8_mul_pre_basic(), ep8_mul_pre_combd(), ep8_mul_pre_combs(), ep8_mul_reg_gls(), ep8_mul_reg_imp(), ep8_mul_sim_lot(), ep8_mul_sim_trick(), ep8_rand(), ep_curve_set_endom(), ep_curve_set_map(), ep_map_basic_impl(), ep_map_sswum_impl(), ep_map_swift_impl(), ep_mul_cof(), ep_mul_combs_endom(), ep_mul_combs_plain(), ep_mul_dig(), ep_mul_fix_basic(), ep_mul_fix_combd(), ep_mul_fix_lwnaf(), ep_mul_glv_imp(), ep_mul_monty(), ep_mul_naf_imp(), ep_mul_pre_basic(), ep_mul_pre_combd(), ep_mul_pre_combs(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_mul_sim_endom(), ep_mul_sim_gen(), ep_mul_sim_inter(), ep_mul_sim_joint(), ep_mul_sim_lot_endom(), ep_mul_sim_trick(), ep_mul_slide(), ep_param_set(), ep_pck(), ep_rand(), ep_upk(), fb_read_bin(), fb_read_str(), fb_size_str(), fb_write_bin(), fp12_exp_cyc_sim(), fp12_exp_dig(), fp16_exp_dig(), fp18_exp_dig(), fp24_exp_dig(), fp2_field_init(), fp2_mul_nor_basic(), fp2_srt(), fp3_field_init(), fp3_srt(), fp48_exp_dig(), fp4_field_init(), fp54_exp_dig(), fp8_exp_dig(), fp8_field_init(), fp_crt(), fp_inv_basic(), fp_inv_binar(), fp_inv_divst(), fp_inv_exgcd(), fp_inv_monty(), fp_is_cub(), fp_is_even(), fp_param_set(), fp_param_set_any_dense(), fp_prime_conv(), fp_prime_conv_dig(), fp_prime_set(), fp_prime_set_pairf(), fp_prime_set_pmers(), fp_print(), fp_read_bin(), fp_read_str(), fp_size_str(), fp_smb_basic(), fp_smb_divst(), fp_srt(), fp_write_bin(), fp_write_str(), g1_is_valid(), g1_mul(), g1_mul_bct(), g1_mul_gen(), g1_mul_lcl(), g2_is_valid(), g2_mul(), g2_mul_bct(), g2_mul_gen(), g2_mul_lcl(), gt_exp_bct(), gt_exp_dig(), gt_exp_gls_naf(), gt_exp_gls_sac(), gt_exp_lcl(), gt_exp_reg_gls(), gt_exp_reg_sac(), gt_exp_sim(), gt_is_valid(), mpc_mt_lcl(), mpc_mt_mul(), mpc_sss_gen(), mpc_sss_key(), pad_pkcs2(), pc_map_tri(), pp_exp_afg16(), pp_exp_b12(), pp_exp_bn(), pp_exp_fm(), pp_exp_fm16(), pp_exp_k1(), pp_exp_k2(), pp_exp_k24(), pp_exp_k48(), pp_exp_k54(), pp_exp_k8(), pp_exp_kss(), pp_exp_kss(), pp_exp_sg(), pp_exp_sm9(), pp_map_k24(), pp_map_k48(), pp_map_k54(), pp_map_oatep_k12(), pp_map_oatep_k16(), pp_map_oatep_k18(), pp_map_oatep_k8(), pp_map_sim_k24(), pp_map_sim_k48(), pp_map_sim_oatep_k12(), pp_map_sim_oatep_k16(), pp_map_sim_oatep_k18(), pp_map_sim_oatep_k8(), pp_map_sim_tatep_k1(), pp_map_sim_tatep_k12(), pp_map_sim_tatep_k16(), pp_map_sim_tatep_k18(), pp_map_sim_tatep_k2(), pp_map_sim_weilp_k1(), pp_map_sim_weilp_k12(), pp_map_sim_weilp_k16(), pp_map_sim_weilp_k18(), pp_map_sim_weilp_k2(), pp_map_tatep_k1(), pp_map_tatep_k12(), pp_map_tatep_k16(), pp_map_tatep_k18(), pp_map_tatep_k2(), pp_map_weilp_k1(), pp_map_weilp_k12(), pp_map_weilp_k16(), pp_map_weilp_k18(), and pp_map_weilp_k2().
bn_new
#define bn_new (A)
Value:
    bn_make(A, RLC_BN_SIZE);                                                \
Calls a function to allocate and initialize a multiple precision integer.
Parameters
[in,out] A - the multiple precision integer to initialize.
Exceptions
ERR_NO_MEMORY - if there is no available memory.
Definition at line 178 of file relic_bn.h.
Referenced by bn_div_dig(), bn_div_rem_dig(), bn_factor(), bn_gcd_basic(), bn_gcd_binar(), bn_gcd_ext_basic(), bn_gcd_ext_binar(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_lehme(), bn_gen_prime_factor(), bn_gen_prime_stron(), bn_is_factor(), bn_is_prime_rabin(), bn_is_prime_solov(), bn_lag(), bn_lcm(), bn_mod_barrt(), bn_mod_inv(), bn_mod_inv_sim(), bn_mod_monty_back(), bn_mod_pmers(), bn_mul_karat_imp(), bn_mxp_basic(), bn_mxp_crt(), bn_mxp_dig(), bn_mxp_monty(), bn_mxp_sim(), bn_mxp_sim_few(), bn_mxp_sim_lot(), bn_mxp_slide(), bn_rand_mod(), bn_rec_frb(), bn_rec_glv(), bn_rec_jsf(), bn_rec_naf(), bn_rec_reg(), bn_rec_rtnaf(), bn_rec_sac(), bn_rec_tnaf(), bn_rec_tnaf_mod(), bn_size_str(), bn_smb_jac(), bn_smb_leg(), bn_sqr_karat_imp(), bn_srt(), bn_write_str(), cp_bbs_gen(), cp_bbs_sig(), cp_bbs_ver(), cp_bdpe_dec(), cp_bdpe_enc(), cp_bdpe_gen(), cp_bgn_dec(), cp_bgn_dec1(), cp_bgn_dec2(), cp_bgn_enc1(), cp_bgn_enc2(), cp_bgn_gen(), cp_bls_gen(), cp_clb_gen(), cp_clb_sig(), cp_clb_ver(), cp_cli_gen(), cp_cli_sig(), cp_cli_ver(), cp_cls_gen(), cp_cls_sig(), cp_cls_ver(), cp_cmlhs_gen(), cp_cmlhs_onv(), cp_cmlhs_sig(), cp_cmlhs_ver(), cp_ecdh_gen(), cp_ecdh_key(), cp_ecdsa_gen(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ecies_dec(), cp_ecies_enc(), cp_ecies_gen(), cp_ecmqv_gen(), cp_ecmqv_key(), cp_ecss_gen(), cp_ecss_sig(), cp_ecss_ver(), cp_ers_ext(), cp_ers_gen_key(), cp_ers_sig(), cp_ers_ver(), cp_etrs_ext(), cp_etrs_sig(), cp_etrs_uni(), cp_etrs_ver(), cp_ghpe_dec(), cp_ghpe_enc(), cp_ghpe_gen(), cp_ibe_enc(), cp_ibe_gen(), cp_lvprv_ask(), cp_lvprv_gen(), cp_lvpub_gen(), cp_mklhs_fun(), cp_mklhs_gen(), cp_mklhs_onv(), cp_mklhs_sig(), cp_mklhs_ver(), cp_mpsb_gen(), cp_mpsb_sig(), cp_mpsb_ver(), cp_mpss_gen(), cp_mpss_sig(), cp_mpss_ver(), cp_pbpsi_ans(), cp_pbpsi_ask(), cp_pbpsi_gen(), cp_pdprv_ask(), cp_pdprv_gen(), cp_pdpub_gen(), cp_phpe_add(), cp_phpe_dec(), cp_phpe_enc(), cp_pokdl_prv(), cp_pokdl_ver(), cp_pokor_prv(), cp_pokor_ver(), cp_psb_gen(), cp_psb_sig(), cp_psb_ver(), cp_pss_gen(), cp_pss_sig(), cp_rabin_dec(), cp_rabin_enc(), cp_rabin_gen(), cp_rsa_dec(), cp_rsa_enc(), cp_rsa_gen(), cp_rsa_sig(), cp_rsa_ver(), cp_rsapsi_ans(), cp_rsapsi_gen(), cp_rsapsi_int(), cp_shipsi_ans(), cp_shipsi_int(), cp_shpe_dec(), cp_shpe_enc(), cp_shpe_enc_prv(), cp_smlers_ext(), cp_smlers_ver(), cp_sokaka_gen(), cp_sokdl_sig(), cp_sokdl_ver(), cp_sokor_sig(), cp_sokor_ver(), cp_vbnn_gen(), cp_vbnn_gen_prv(), cp_vbnn_sig(), cp_vbnn_ver(), cp_zss_gen(), cp_zss_sig(), cp_zss_ver(), eb_map(), eb_mul_fix_combd(), eb_mul_fix_combs(), eb_mul_halve(), eb_mul_lodah(), eb_mul_pre_basic(), eb_mul_pre_combd(), eb_mul_pre_combs(), eb_mul_sim_trick(), eb_param_set(), eb_rand(), ed_map_dst(), ed_map_ell2_5mod8(), ed_mul_combs_plain(), ed_mul_dig(), ed_mul_fix_combd(), ed_mul_pre_basic(), ed_mul_pre_combd(), ed_mul_pre_combs(), ed_mul_reg_imp(), ed_mul_sim_trick(), ed_param_set(), ed_rand(), ep2_curve_set_map(), ep2_curve_set_twist(), ep2_frb(), ep2_map_basic(), ep2_map_from_field(), ep2_map_swift(), ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep2_mul_dig(), ep2_mul_fix_basic(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_fix_lwnaf(), ep2_mul_gls_imp(), ep2_mul_monty(), ep2_mul_pre_basic(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_reg_gls(), ep2_mul_reg_imp(), ep2_mul_sim_endom(), ep2_mul_sim_gen(), ep2_mul_sim_joint(), ep2_mul_sim_lot(), ep2_mul_sim_trick(), ep2_pck(), ep2_rand(), ep2_upk(), ep3_curve_set_twist(), ep3_map(), ep3_mul_cof_fm18(), ep3_mul_cof_k18(), ep3_mul_cof_sg18(), ep3_mul_dig(), ep3_mul_fix_basic(), ep3_mul_fix_combd(), ep3_mul_fix_combs(), ep3_mul_fix_lwnaf(), ep3_mul_gls_imp(), ep3_mul_monty(), ep3_mul_pre_basic(), ep3_mul_pre_combd(), ep3_mul_pre_combs(), ep3_mul_reg_gls(), ep3_mul_reg_imp(), ep3_mul_sim_lot(), ep3_mul_sim_trick(), ep3_rand(), ep4_curve_set_twist(), ep4_map(), ep4_mul_cof_afg16(), ep4_mul_cof_b24(), ep4_mul_cof_fm16(), ep4_mul_cof_k16(), ep4_mul_dig(), ep4_mul_fix_basic(), ep4_mul_fix_combd(), ep4_mul_fix_combs(), ep4_mul_gls_imp(), ep4_mul_monty(), ep4_mul_pre_basic(), ep4_mul_pre_combd(), ep4_mul_pre_combs(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), ep4_mul_sim_lot(), ep4_mul_sim_trick(), ep4_rand(), ep8_curve_set_twist(), ep8_map(), ep8_mul_cof(), ep8_mul_dig(), ep8_mul_fix_basic(), ep8_mul_fix_combd(), ep8_mul_fix_combs(), ep8_mul_gls_imp(), ep8_mul_monty(), ep8_mul_pre_basic(), ep8_mul_pre_combd(), ep8_mul_pre_combs(), ep8_mul_reg_gls(), ep8_mul_reg_imp(), ep8_mul_sim_lot(), ep8_mul_sim_trick(), ep8_rand(), ep_curve_set_endom(), ep_curve_set_map(), ep_map_basic_impl(), ep_map_sswum_impl(), ep_map_swift_impl(), ep_mul_cof(), ep_mul_combs_endom(), ep_mul_combs_plain(), ep_mul_dig(), ep_mul_fix_basic(), ep_mul_fix_combd(), ep_mul_fix_lwnaf(), ep_mul_glv_imp(), ep_mul_monty(), ep_mul_naf_imp(), ep_mul_pre_basic(), ep_mul_pre_combd(), ep_mul_pre_combs(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_mul_sim_endom(), ep_mul_sim_gen(), ep_mul_sim_inter(), ep_mul_sim_joint(), ep_mul_sim_lot_endom(), ep_mul_sim_trick(), ep_mul_slide(), ep_param_set(), ep_pck(), ep_rand(), ep_upk(), fb_read_bin(), fb_read_str(), fb_size_str(), fb_write_bin(), fp12_exp_cyc_sim(), fp12_exp_dig(), fp16_exp_dig(), fp18_exp_dig(), fp24_exp_dig(), fp2_field_init(), fp2_mul_nor_basic(), fp2_srt(), fp3_field_init(), fp3_srt(), fp48_exp_dig(), fp4_field_init(), fp54_exp_dig(), fp8_exp_dig(), fp8_field_init(), fp_crt(), fp_inv_basic(), fp_inv_binar(), fp_inv_divst(), fp_inv_exgcd(), fp_inv_monty(), fp_is_cub(), fp_is_even(), fp_param_set(), fp_param_set_any_dense(), fp_prime_conv(), fp_prime_set(), fp_prime_set_pairf(), fp_prime_set_pmers(), fp_print(), fp_read_bin(), fp_read_str(), fp_size_str(), fp_smb_basic(), fp_smb_divst(), fp_srt(), fp_write_bin(), fp_write_str(), g1_is_valid(), g1_mul(), g1_mul_bct(), g1_mul_gen(), g1_mul_lcl(), g2_is_valid(), g2_mul(), g2_mul_bct(), g2_mul_gen(), g2_mul_lcl(), gt_exp_bct(), gt_exp_dig(), gt_exp_gls_naf(), gt_exp_gls_sac(), gt_exp_lcl(), gt_exp_reg_gls(), gt_exp_reg_sac(), gt_exp_sim(), gt_is_valid(), mpc_mt_lcl(), mpc_mt_mul(), mpc_sss_gen(), mpc_sss_key(), pad_pkcs2(), pc_map_tri(), pp_exp_afg16(), pp_exp_b12(), pp_exp_bn(), pp_exp_fm(), pp_exp_fm16(), pp_exp_k1(), pp_exp_k2(), pp_exp_k24(), pp_exp_k48(), pp_exp_k54(), pp_exp_k8(), pp_exp_kss(), pp_exp_kss(), pp_exp_sg(), pp_exp_sm9(), pp_map_k24(), pp_map_k48(), pp_map_k54(), pp_map_oatep_k12(), pp_map_oatep_k16(), pp_map_oatep_k18(), pp_map_oatep_k8(), pp_map_sim_k24(), pp_map_sim_k48(), pp_map_sim_oatep_k12(), pp_map_sim_oatep_k16(), pp_map_sim_oatep_k18(), pp_map_sim_oatep_k8(), pp_map_sim_tatep_k1(), pp_map_sim_tatep_k12(), pp_map_sim_tatep_k16(), pp_map_sim_tatep_k18(), pp_map_sim_tatep_k2(), pp_map_sim_weilp_k1(), pp_map_sim_weilp_k12(), pp_map_sim_weilp_k16(), pp_map_sim_weilp_k18(), pp_map_sim_weilp_k2(), pp_map_tatep_k1(), pp_map_tatep_k12(), pp_map_tatep_k16(), pp_map_tatep_k18(), pp_map_tatep_k2(), pp_map_weilp_k1(), pp_map_weilp_k12(), pp_map_weilp_k16(), pp_map_weilp_k18(), and pp_map_weilp_k2().
bn_new_size
#define bn_new_size (A, D)
Value:
    bn_make(A, D);                                                          \
Calls a function to allocate and initialize a multiple precision integer with the required precision in digits.
Parameters
[in,out] A - the multiple precision integer to initialize.
[in] D - the precision in digits.
Exceptions
ERR_NO_MEMORY - if there is no available memory.
ERR_PRECISION - if the required precision cannot be represented by the library.
Definition at line 202 of file relic_bn.h.
Referenced by bn_div_imp(), bn_mod_monty_basic(), bn_mod_monty_comba(), bn_mul_basic(), bn_mul_comba(), bn_mul_karat_imp(), bn_sqr_basic(), bn_sqr_comba(), and bn_sqr_karat_imp().
bn_free
#define bn_free (A)
Value:
/* empty */                                     \
Calls a function to clean and free a multiple precision integer.
Parameters
[in,out] A - the multiple precision integer to free.
Definition at line 221 of file relic_bn.h.
Referenced by bn_div_dig(), bn_div_imp(), bn_div_rem_dig(), bn_factor(), bn_gcd_basic(), bn_gcd_binar(), bn_gcd_ext_basic(), bn_gcd_ext_binar(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_lehme(), bn_gen_prime_factor(), bn_gen_prime_stron(), bn_is_factor(), bn_is_prime_rabin(), bn_is_prime_solov(), bn_lag(), bn_lcm(), bn_mod_barrt(), bn_mod_inv(), bn_mod_inv_sim(), bn_mod_monty_back(), bn_mod_monty_basic(), bn_mod_monty_comba(), bn_mod_pmers(), bn_mul_basic(), bn_mul_comba(), bn_mul_karat_imp(), bn_mxp_basic(), bn_mxp_crt(), bn_mxp_dig(), bn_mxp_monty(), bn_mxp_sim(), bn_mxp_sim_few(), bn_mxp_sim_lot(), bn_mxp_slide(), bn_rand_mod(), bn_rec_frb(), bn_rec_glv(), bn_rec_jsf(), bn_rec_naf(), bn_rec_reg(), bn_rec_rtnaf(), bn_rec_sac(), bn_rec_tnaf(), bn_rec_tnaf_mod(), bn_size_str(), bn_smb_jac(), bn_smb_leg(), bn_sqr_basic(), bn_sqr_comba(), bn_sqr_karat_imp(), bn_srt(), bn_write_str(), cp_bbs_gen(), cp_bbs_sig(), cp_bbs_ver(), cp_bdpe_dec(), cp_bdpe_enc(), cp_bdpe_gen(), cp_bgn_dec(), cp_bgn_dec1(), cp_bgn_dec2(), cp_bgn_enc1(), cp_bgn_enc2(), cp_bgn_gen(), cp_bls_gen(), cp_clb_gen(), cp_clb_sig(), cp_clb_ver(), cp_cli_gen(), cp_cli_sig(), cp_cli_ver(), cp_cls_gen(), cp_cls_sig(), cp_cls_ver(), cp_cmlhs_gen(), cp_cmlhs_onv(), cp_cmlhs_sig(), cp_cmlhs_ver(), cp_ecdh_gen(), cp_ecdh_key(), cp_ecdsa_gen(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ecies_dec(), cp_ecies_enc(), cp_ecies_gen(), cp_ecmqv_gen(), cp_ecmqv_key(), cp_ecss_gen(), cp_ecss_sig(), cp_ecss_ver(), cp_ers_ext(), cp_ers_gen_key(), cp_ers_sig(), cp_ers_ver(), cp_etrs_ext(), cp_etrs_sig(), cp_etrs_uni(), cp_etrs_ver(), cp_ghpe_dec(), cp_ghpe_enc(), cp_ghpe_gen(), cp_ibe_enc(), cp_ibe_gen(), cp_lvprv_ask(), cp_lvprv_gen(), cp_lvpub_gen(), cp_mklhs_fun(), cp_mklhs_gen(), cp_mklhs_onv(), cp_mklhs_sig(), cp_mklhs_ver(), cp_mpsb_gen(), cp_mpsb_sig(), cp_mpsb_ver(), cp_mpss_gen(), cp_mpss_sig(), cp_mpss_ver(), cp_pbpsi_ans(), cp_pbpsi_ask(), cp_pbpsi_gen(), cp_pdprv_ask(), cp_pdprv_gen(), cp_pdpub_gen(), cp_phpe_add(), cp_phpe_dec(), cp_phpe_enc(), cp_pokdl_prv(), cp_pokdl_ver(), cp_pokor_prv(), cp_pokor_ver(), cp_psb_gen(), cp_psb_sig(), cp_psb_ver(), cp_pss_gen(), cp_pss_sig(), cp_rabin_dec(), cp_rabin_enc(), cp_rabin_gen(), cp_rsa_dec(), cp_rsa_enc(), cp_rsa_gen(), cp_rsa_sig(), cp_rsa_ver(), cp_rsapsi_ans(), cp_rsapsi_gen(), cp_rsapsi_int(), cp_shipsi_ans(), cp_shipsi_int(), cp_shpe_dec(), cp_shpe_enc(), cp_shpe_enc_prv(), cp_smlers_ext(), cp_smlers_ver(), cp_sokaka_gen(), cp_sokdl_sig(), cp_sokdl_ver(), cp_sokor_sig(), cp_sokor_ver(), cp_vbnn_gen(), cp_vbnn_gen_prv(), cp_vbnn_sig(), cp_vbnn_ver(), cp_zss_gen(), cp_zss_sig(), cp_zss_ver(), eb_map(), eb_mul_fix_combd(), eb_mul_fix_combs(), eb_mul_halve(), eb_mul_lodah(), eb_mul_pre_basic(), eb_mul_pre_combd(), eb_mul_pre_combs(), eb_mul_sim_trick(), eb_param_set(), eb_rand(), ed_map_dst(), ed_map_ell2_5mod8(), ed_mul_combs_plain(), ed_mul_dig(), ed_mul_fix_combd(), ed_mul_pre_basic(), ed_mul_pre_combd(), ed_mul_pre_combs(), ed_mul_reg_imp(), ed_mul_sim_trick(), ed_param_set(), ed_rand(), ep2_curve_set_map(), ep2_curve_set_twist(), ep2_frb(), ep2_map_basic(), ep2_map_from_field(), ep2_map_swift(), ep2_mul_cof(), ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep2_mul_dig(), ep2_mul_fix_basic(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_fix_lwnaf(), ep2_mul_gls_imp(), ep2_mul_monty(), ep2_mul_pre_basic(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_reg_gls(), ep2_mul_reg_imp(), ep2_mul_sim_endom(), ep2_mul_sim_gen(), ep2_mul_sim_joint(), ep2_mul_sim_lot(), ep2_mul_sim_trick(), ep2_pck(), ep2_rand(), ep2_upk(), ep3_curve_set_twist(), ep3_map(), ep3_mul_cof(), ep3_mul_cof_fm18(), ep3_mul_cof_k18(), ep3_mul_cof_sg18(), ep3_mul_dig(), ep3_mul_fix_basic(), ep3_mul_fix_combd(), ep3_mul_fix_combs(), ep3_mul_fix_lwnaf(), ep3_mul_gls_imp(), ep3_mul_monty(), ep3_mul_pre_basic(), ep3_mul_pre_combd(), ep3_mul_pre_combs(), ep3_mul_reg_gls(), ep3_mul_reg_imp(), ep3_mul_sim_lot(), ep3_mul_sim_trick(), ep3_rand(), ep4_curve_set_twist(), ep4_map(), ep4_mul_cof(), ep4_mul_cof_afg16(), ep4_mul_cof_b24(), ep4_mul_cof_fm16(), ep4_mul_cof_k16(), ep4_mul_dig(), ep4_mul_fix_basic(), ep4_mul_fix_combd(), ep4_mul_fix_combs(), ep4_mul_gls_imp(), ep4_mul_monty(), ep4_mul_pre_basic(), ep4_mul_pre_combd(), ep4_mul_pre_combs(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), ep4_mul_sim_lot(), ep4_mul_sim_trick(), ep4_rand(), ep8_curve_set_twist(), ep8_map(), ep8_mul_cof(), ep8_mul_dig(), ep8_mul_fix_basic(), ep8_mul_fix_combd(), ep8_mul_fix_combs(), ep8_mul_gls_imp(), ep8_mul_monty(), ep8_mul_pre_basic(), ep8_mul_pre_combd(), ep8_mul_pre_combs(), ep8_mul_reg_gls(), ep8_mul_reg_imp(), ep8_mul_sim_lot(), ep8_mul_sim_trick(), ep8_rand(), ep_curve_set_endom(), ep_curve_set_map(), ep_map_basic_impl(), ep_map_sswum_impl(), ep_map_swift_impl(), ep_mul_cof(), ep_mul_combs_endom(), ep_mul_combs_plain(), ep_mul_dig(), ep_mul_fix_basic(), ep_mul_fix_combd(), ep_mul_fix_lwnaf(), ep_mul_glv_imp(), ep_mul_monty(), ep_mul_naf_imp(), ep_mul_pre_basic(), ep_mul_pre_combd(), ep_mul_pre_combs(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_mul_sim_endom(), ep_mul_sim_gen(), ep_mul_sim_inter(), ep_mul_sim_joint(), ep_mul_sim_lot_endom(), ep_mul_sim_trick(), ep_mul_slide(), ep_param_set(), ep_pck(), ep_rand(), ep_upk(), fb_read_bin(), fb_read_str(), fb_size_str(), fb_write_bin(), fp12_exp_cyc_sim(), fp12_exp_dig(), fp16_exp_dig(), fp18_exp_dig(), fp24_exp_dig(), fp2_field_init(), fp2_mul_nor_basic(), fp2_srt(), fp3_field_init(), fp3_srt(), fp48_exp_dig(), fp4_field_init(), fp54_exp_dig(), fp8_exp_dig(), fp8_field_init(), fp_crt(), fp_inv_basic(), fp_inv_binar(), fp_inv_divst(), fp_inv_exgcd(), fp_inv_monty(), fp_is_cub(), fp_is_even(), fp_param_set(), fp_param_set_any_dense(), fp_prime_conv(), fp_prime_set(), fp_prime_set_pairf(), fp_prime_set_pmers(), fp_print(), fp_read_bin(), fp_read_str(), fp_size_str(), fp_smb_basic(), fp_smb_divst(), fp_srt(), fp_write_bin(), fp_write_str(), g1_is_valid(), g1_mul(), g1_mul_bct(), g1_mul_gen(), g1_mul_lcl(), g2_is_valid(), g2_mul(), g2_mul_bct(), g2_mul_gen(), g2_mul_lcl(), gt_exp_bct(), gt_exp_dig(), gt_exp_gls_naf(), gt_exp_gls_sac(), gt_exp_lcl(), gt_exp_reg_gls(), gt_exp_reg_sac(), gt_exp_sim(), gt_is_valid(), mpc_mt_lcl(), mpc_mt_mul(), mpc_sss_gen(), mpc_sss_key(), pad_pkcs2(), pc_map_tri(), pp_exp_afg16(), pp_exp_b12(), pp_exp_bn(), pp_exp_fm(), pp_exp_fm16(), pp_exp_k1(), pp_exp_k2(), pp_exp_k24(), pp_exp_k48(), pp_exp_k54(), pp_exp_k8(), pp_exp_kss(), pp_exp_kss(), pp_exp_sg(), pp_exp_sm9(), pp_map_k24(), pp_map_k48(), pp_map_k54(), pp_map_oatep_k12(), pp_map_oatep_k16(), pp_map_oatep_k18(), pp_map_oatep_k8(), pp_map_sim_k24(), pp_map_sim_k48(), pp_map_sim_oatep_k12(), pp_map_sim_oatep_k16(), pp_map_sim_oatep_k18(), pp_map_sim_oatep_k8(), pp_map_sim_tatep_k1(), pp_map_sim_tatep_k12(), pp_map_sim_tatep_k16(), pp_map_sim_tatep_k18(), pp_map_sim_tatep_k2(), pp_map_sim_weilp_k1(), pp_map_sim_weilp_k12(), pp_map_sim_weilp_k16(), pp_map_sim_weilp_k18(), pp_map_sim_weilp_k2(), pp_map_tatep_k1(), pp_map_tatep_k12(), pp_map_tatep_k16(), pp_map_tatep_k18(), pp_map_tatep_k2(), pp_map_weilp_k1(), pp_map_weilp_k12(), pp_map_weilp_k16(), pp_map_weilp_k18(), and pp_map_weilp_k2().
crt_null
#define crt_null (A)
Value:
RLC_NULL(A)
Initializes a CRT moduli set with a null value.
Parameters
[out] A - the moduli to initialize.
Definition at line 230 of file relic_bn.h.
crt_new
#define crt_new (A)
Value:
    bn_new((A)->n);                                                         \
    bn_new((A)->dp);                                                        \
    bn_new((A)->dq);                                                        \
    bn_new((A)->p);                                                         \
    bn_new((A)->q);                                                         \
    bn_new((A)->qi);                                                        \
Calls a function to allocate and initialize a Rabin key pair.
Parameters
[out] A - the new key pair.
Definition at line 251 of file relic_bn.h.
crt_free
#define crt_free (A)
Value:
/* empty */
Calls a function to clean and free a Rabin key pair.
Parameters
[out] A - the key pair to clean and free.
Definition at line 280 of file relic_bn.h.
bn_mul
#define bn_mul (C, A, B)
Value:
bn_mul_comba(C, A, B)
Multiples two multiple precision integers. Computes c = a * b.
Parameters
[out] C - the result.
[in] A - the first multiple precision integer to multiply.
[in] B - the second multiple precision integer to multiply.
Definition at line 296 of file relic_bn.h.
Referenced by bn_evl(), bn_gcd_ext_basic(), bn_gcd_ext_binar(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gen_prime_factor(), bn_gen_prime_stron(), bn_lag(), bn_lcm(), bn_mod_barrt(), bn_mod_inv_sim(), bn_mod_pmers(), bn_mxp_basic(), bn_mxp_crt(), bn_mxp_dig(), bn_mxp_monty(), bn_mxp_sim_few(), bn_mxp_sim_lot(), bn_mxp_slide(), bn_rec_frb(), bn_rec_glv(), cp_bdpe_dec(), cp_bdpe_enc(), cp_bdpe_gen(), cp_bgn_dec(), cp_bgn_dec1(), cp_bgn_dec2(), cp_clb_sig(), cp_cli_sig(), cp_cls_sig(), cp_cmlhs_sig(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ecmqv_key(), cp_ecss_sig(), cp_etrs_sig(), cp_etrs_uni(), cp_etrs_ver(), cp_ghpe_dec(), cp_ghpe_enc(), cp_ghpe_gen(), cp_mpsb_sig(), cp_mpsb_ver(), cp_phpe_add(), cp_phpe_dec(), cp_phpe_enc(), cp_phpe_gen(), cp_pokdl_prv(), cp_pokor_prv(), cp_psb_sig(), cp_pss_sig(), cp_rabin_dec(), cp_rabin_gen(), cp_rsa_gen(), cp_rsapsi_gen(), cp_shipsi_ans(), cp_shipsi_gen(), cp_shpe_dec(), cp_shpe_enc(), cp_shpe_enc_prv(), cp_shpe_gen(), cp_sokdl_sig(), cp_sokor_sig(), cp_vbnn_gen_prv(), cp_vbnn_sig(), ep_curve_set_endom(), ep_mul_cof(), ep_param_set(), fp_inv_exgcd(), fp_param_set(), fp_prime_set_pairf(), g1_is_valid(), mpc_mt_gen(), mpc_mt_mul(), mpc_sss_key(), and pp_exp_afg16().
bn_sqr
#define bn_sqr (C, A)
Value:
bn_sqr_comba(C, A)
Computes the square of a multiple precision integer. Computes c = a * a.
Parameters
[out] C - the result.
[in] A - the multiple precision integer to square.
Definition at line 310 of file relic_bn.h.
Referenced by bn_gcd_ext_mid(), bn_is_prime_rabin(), bn_mxp_basic(), bn_mxp_crt(), bn_mxp_dig(), bn_mxp_monty(), bn_mxp_sim_few(), bn_mxp_slide(), bn_rec_frb(), bn_srt(), cp_bgn_dec(), cp_ghpe_dec(), cp_phpe_add(), cp_phpe_dec(), cp_phpe_enc(), cp_rabin_enc(), cp_shpe_dec(), cp_shpe_enc(), cp_shpe_enc_prv(), cp_shpe_gen(), ep_mul_cof(), ep_param_set(), fp3_srt(), fp_param_set(), fp_prime_set_pairf(), g1_is_valid(), and pp_exp_afg16().
bn_mod_pre
#define bn_mod_pre (U, M)
Value:
bn_mod_pre_monty(U, M)
Computes the auxiliar value derived from the modulus to be used during modular reduction.
Parameters
[out] U - the result.
[in] M - the modulus.
Definition at line 327 of file relic_bn.h.
Referenced by bn_mxp_basic(), bn_mxp_dig(), bn_mxp_monty(), bn_mxp_sim_few(), and bn_mxp_slide().
bn_mod
#define bn_mod (C, A, ...)
Value:
RLC_CAT(bn_mod, RLC_OPT(__VA_ARGS__))(C, A, __VA_ARGS__)
Reduces a multiple precision integer modulo another integer. If the number of arguments is 3, then simple division is used. If the number of arguments is 4, then a modular reduction algorithm is used and the fourth argument is an auxiliary value derived from the modulus. The variant with 4 arguments should be used when several modular reductions are computed with the same modulus. Computes c = a mod m.
Parameters
[out] C - the result.
[in] A - the multiple precision integer to reduce.
[in] ... - the modulus and an optional argument.
Definition at line 344 of file relic_bn.h.
Referenced by bn_evl(), bn_gcd_basic(), bn_gcd_lehme(), bn_is_factor(), bn_is_prime_rabin(), bn_is_prime_solov(), bn_lag(), bn_mod_barrt(), bn_mod_inv_sim(), bn_mod_monty_conv(), bn_mxp_basic(), bn_mxp_crt(), bn_mxp_dig(), bn_mxp_monty(), bn_mxp_sim_few(), bn_mxp_sim_lot(), bn_mxp_slide(), bn_rand_mod(), bn_rec_frb(), bn_smb_jac(), cp_bbs_gen(), cp_bbs_sig(), cp_bbs_ver(), cp_bdpe_enc(), cp_bgn_dec(), cp_bgn_dec1(), cp_bgn_dec2(), cp_clb_sig(), cp_clb_ver(), cp_cli_sig(), cp_cli_ver(), cp_cls_sig(), cp_cls_ver(), cp_cmlhs_sig(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ecmqv_key(), cp_ecss_sig(), cp_ecss_ver(), cp_ers_ext(), cp_etrs_sig(), cp_etrs_uni(), cp_etrs_ver(), cp_ghpe_dec(), cp_ghpe_enc(), cp_mklhs_fun(), cp_mklhs_onv(), cp_mklhs_ver(), cp_mpsb_sig(), cp_mpsb_ver(), cp_mpss_sig(), cp_phpe_add(), cp_phpe_dec(), cp_phpe_enc(), cp_phpe_gen(), cp_pokdl_prv(), cp_pokdl_ver(), cp_pokor_prv(), cp_pokor_ver(), cp_psb_sig(), cp_pss_sig(), cp_rabin_dec(), cp_rabin_enc(), cp_rsa_gen(), cp_shipsi_ans(), cp_shpe_dec(), cp_shpe_enc_prv(), cp_shpe_gen(), cp_smlers_ext(), cp_sokdl_sig(), cp_sokdl_ver(), cp_sokor_sig(), cp_sokor_ver(), cp_vbnn_gen_prv(), cp_vbnn_sig(), cp_vbnn_ver(), cp_zss_sig(), cp_zss_ver(), eb_mul_halve(), ep2_mul_fix_basic(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_fix_lwnaf(), ep2_mul_gls_imp(), ep2_mul_monty(), ep2_mul_reg_gls(), ep2_mul_sim_endom(), ep2_mul_sim_gen(), ep2_mul_sim_joint(), ep2_mul_sim_lot(), ep2_mul_sim_trick(), ep3_mul_fix_basic(), ep3_mul_fix_combd(), ep3_mul_fix_combs(), ep3_mul_fix_lwnaf(), ep3_mul_gls_imp(), ep3_mul_monty(), ep3_mul_reg_gls(), ep4_mul_fix_basic(), ep4_mul_fix_combs(), ep4_mul_gls_imp(), ep4_mul_monty(), ep4_mul_reg_gls(), ep8_mul_fix_basic(), ep8_mul_fix_combs(), ep8_mul_gls_imp(), ep8_mul_monty(), ep8_mul_reg_gls(), ep_mul_combs_endom(), ep_mul_combs_plain(), ep_mul_fix_basic(), ep_mul_fix_combd(), ep_mul_fix_lwnaf(), ep_mul_glv_imp(), ep_mul_monty(), ep_mul_naf_imp(), ep_mul_reg_glv(), ep_mul_sim_gen(), ep_mul_sim_inter(), ep_mul_sim_joint(), ep_mul_sim_lot_endom(), ep_mul_sim_trick(), ep_mul_slide(), fp12_exp_cyc_sim(), fp_prime_conv(), fp_prime_set(), g1_mul(), g1_mul_bct(), g1_mul_gen(), g1_mul_lcl(), g2_mul(), g2_mul_bct(), g2_mul_gen(), g2_mul_lcl(), gt_exp_bct(), gt_exp_gls_naf(), gt_exp_gls_sac(), gt_exp_lcl(), gt_exp_reg_gls(), gt_exp_reg_sac(), gt_exp_sim(), mpc_mt_bct(), mpc_mt_gen(), mpc_mt_lcl(), mpc_mt_mul(), and mpc_sss_key().
bn_mod_imp
#define bn_mod_imp (C, A, M, U)
Value:
bn_mod_monty(C, A, M, U)
Reduces a multiple precision integer modulo another integer. This macro should not be called directly. Use bn_mod with 4 arguments instead.
Parameters
[out] C - the result.
[in] A - the the multiple precision integer to reduce.
[in] M - the modulus.
[in] U - the auxiliar value derived from the modulus.
Definition at line 360 of file relic_bn.h.
bn_mod_monty
#define bn_mod_monty (C, A, M, U)
Value:
bn_mod_monty_comba(C, A, M, U)
Reduces a multiple precision integer modulo a positive integer using Montgomery reduction. Computes c = a * u^(-1) (mod m).
Parameters
[out] C - the result.
[in] A - the multiple precision integer to reduce.
[in] M - the modulus.
[in] U - the reciprocal of the modulus.
Definition at line 377 of file relic_bn.h.
Referenced by bn_mod_monty_back().
bn_mxp
#define bn_mxp (C, A, B, M)
Value:
bn_mxp_slide(C, A, B, M)
Exponentiates a multiple precision integer modulo another multiple precision integer. Computes c = a^b mod m. If Montgomery reduction is used, the basis must not be in Montgomery form.
Parameters
[out] C - the result.
[in] A - the basis.
[in] B - the exponent.
[in] M - the modulus.
Definition at line 393 of file relic_bn.h.
Referenced by bn_factor(), bn_gen_prime_stron(), bn_is_prime_rabin(), bn_is_prime_solov(), bn_mxp_crt(), bn_mxp_sim_lot(), bn_smb_leg(), cp_bdpe_dec(), cp_bdpe_enc(), cp_bdpe_gen(), cp_ghpe_dec(), cp_ghpe_enc(), cp_phpe_dec(), cp_phpe_enc(), cp_rabin_dec(), cp_rsa_dec(), cp_rsa_enc(), cp_rsa_sig(), cp_rsa_ver(), cp_rsapsi_ans(), cp_rsapsi_ask(), cp_rsapsi_int(), cp_shipsi_ans(), cp_shipsi_ask(), cp_shipsi_int(), cp_shpe_dec(), cp_shpe_enc(), cp_shpe_enc_prv(), cp_shpe_gen(), and ep_param_set().
bn_gcd
#define bn_gcd (C, A, B)
Value:
bn_gcd_basic(C, A, B)
Computes the greatest common divisor of two multiple precision integers. Computes c = gcd(a, b).
Parameters
[out] C - the result;
[in] A - the first multiple precision integer.
[in] B - the second multiple precision integer.
Definition at line 407 of file relic_bn.h.
Referenced by bn_factor(), bn_lcm(), cp_rsapsi_gen(), and cp_shipsi_gen().
bn_gcd_ext
#define bn_gcd_ext (C, D, E, A, B)
Value:
bn_gcd_ext_basic(C, D, E, A, B)
Computes the extended greatest common divisor of two multiple precision integers. This function can be used to compute multiplicative inverses. Computes c = gcd(a, b) and c = a * d + b * e.
Parameters
[out] C - the result;
[out] D - the cofactor of the first operand, cannot be NULL.
[out] E - the cofactor of the second operand, can be NULL.
[in] A - the first multiple precision integer.
[in] B - the second multiple precision integer.
Definition at line 426 of file relic_bn.h.
Referenced by bn_mod_inv(), cp_rabin_gen(), and cp_rsa_gen().
bn_gen_prime
#define bn_gen_prime (A, B)
Value:
bn_gen_prime_basic(A, B)
Generates a probable prime number.
Parameters
[out] A - the result.
[in] B - the length of the number in bits.
Definition at line 440 of file relic_bn.h.
Referenced by bn_gen_prime_factor(), cp_bdpe_gen(), cp_ghpe_gen(), cp_phpe_gen(), cp_rabin_gen(), cp_rsa_gen(), cp_rsapsi_gen(), cp_shipsi_gen(), cp_shpe_gen(), and fp_param_set_any_dense().
Typedef Documentation
bn_t
typedef bn_st bn_t[1]
Pointer to a multiple precision integer structure.
Definition at line 115 of file relic_bn.h.
crt_t
typedef crt_st crt_t[1]
Definition at line 143 of file relic_bn.h.
Function Documentation
bn_make()
void bn_make (bn_t a, size_t digits)
Initializes a previously allocated multiple precision integer.
Parameters
[out] a - the multiple precision integer to initialize.
[in] digits - the required precision in digits.
Exceptions
ERR_NO_MEMORY - if there is no available memory.
ERR_PRECISION - if the required precision cannot be represented by the library.
Definition at line 44 of file relic_bn_mem.c.
References ALIGN, ERR_NO_MEMORY, ERR_NO_PRECI, ERR_NO_VALID, RLC_BN_SIZE, RLC_MAX, RLC_POS, and RLC_THROW.
Referenced by eb_curve_init(), ed_curve_init(), ep2_curve_init(), ep3_curve_init(), ep4_curve_init(), ep8_curve_init(), ep_curve_init(), and fp_prime_init().
bn_clean()
void bn_clean (bn_t a)
Cleans a multiple precision integer.
Parameters
[out] a - the multiple precision integer to free.
Definition at line 95 of file relic_bn_mem.c.
References RLC_POS.
Referenced by eb_curve_clean(), ed_curve_clean(), ep2_curve_clean(), ep3_curve_clean(), ep4_curve_clean(), ep8_curve_clean(), ep_curve_clean(), and fp_prime_clean().
bn_grow()
void bn_grow (bn_t a, size_t digits)
Checks the current precision of a multiple precision integer and optionally expands its precision to a given size in digits.
Parameters
[out] a - the multiple precision integer to expand.
[in] digits - the number of digits to expand.
Exceptions
ERR_NO_MEMORY - if there is no available memory.
ERR_PRECISION - if the required precision cannot be represented by the library.
Definition at line 115 of file relic_bn_mem.c.
References ERR_NO_MEMORY, ERR_NO_PRECI, RLC_BN_SIZE, RLC_DIG, and RLC_THROW.
Referenced by bn_add_dig(), bn_add_imp(), bn_copy(), bn_dbl(), bn_lsh(), bn_mod_barrt(), bn_mul_dig(), bn_mxp_monty(), bn_rand(), bn_read_bin(), bn_read_raw(), bn_read_str(), bn_rsh(), bn_set_2b(), bn_set_bit(), bn_smb_jac(), bn_sub_dig(), bn_sub_imp(), and fp_prime_back().
bn_trim()
void bn_trim (bn_t a)
Adjust the number of valid digits of a multiple precision integer.
Parameters
[out] a - the multiple precision integer to adjust.
Definition at line 140 of file relic_bn_mem.c.
References RLC_POS.
Referenced by bn_add_dig(), bn_add_imp(), bn_copy(), bn_div_imp(), bn_hlv(), bn_lsh(), bn_mod_2b(), bn_mod_barrt(), bn_mod_monty_basic(), bn_mod_monty_comba(), bn_mul_basic(), bn_mul_comba(), bn_mul_dig(), bn_mul_karat_imp(), bn_rand(), bn_read_bin(), bn_read_raw(), bn_read_str(), bn_rsh(), bn_set_bit(), bn_sqr_basic(), bn_sqr_comba(), bn_sqr_karat_imp(), bn_sub_dig(), bn_sub_imp(), fp_inv_monty(), fp_prime_back(), fp_prime_set(), and fp_print().
bn_copy()
void bn_copy (bn_t c, const bn_t a)
Copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to copy.
Definition at line 49 of file relic_bn_util.c.
References bn_grow(), bn_trim(), and dv_copy().
Referenced by bn_abs(), bn_add_imp(), bn_div_dig(), bn_div_imp(), bn_div_rem_dig(), bn_factor(), bn_gcd_basic(), bn_gcd_binar(), bn_gcd_ext_basic(), bn_gcd_ext_binar(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_lehme(), bn_hlv(), bn_is_prime_rabin(), bn_is_prime_solov(), bn_lag(), bn_mod_2b(), bn_mod_barrt(), bn_mod_inv(), bn_mod_inv_sim(), bn_mod_monty_basic(), bn_mod_monty_comba(), bn_mod_pmers(), bn_mul_basic(), bn_mul_comba(), bn_mul_karat_imp(), bn_mxp_basic(), bn_mxp_dig(), bn_mxp_monty(), bn_mxp_sim(), bn_mxp_sim_few(), bn_mxp_sim_lot(), bn_mxp_slide(), bn_neg(), bn_rand_mod(), bn_rec_frb(), bn_rec_rtnaf(), bn_rec_sac(), bn_rec_tnaf(), bn_size_str(), bn_smb_jac(), bn_sqr_basic(), bn_sqr_comba(), bn_sqr_karat_imp(), bn_srt(), bn_sub_imp(), bn_write_str(), cp_bdpe_gen(), cp_etrs_ext(), cp_etrs_sig(), cp_etrs_uni(), cp_etrs_ver(), cp_ghpe_dec(), cp_ghpe_enc(), cp_mpsb_ver(), cp_pbpsi_ask(), cp_pbpsi_int(), cp_phpe_gen(), cp_pokor_prv(), cp_psb_sig(), cp_rabin_gen(), cp_rsa_gen(), cp_rsa_sig(), cp_rsapsi_int(), cp_shipsi_gen(), cp_shipsi_int(), cp_shpe_gen(), cp_sokor_sig(), eb_curve_get_cof(), eb_curve_get_ord(), eb_curve_set(), ed_curve_get_cof(), ed_curve_get_ord(), ed_param_set(), ep2_curve_get_cof(), ep2_curve_get_ord(), ep2_curve_set(), ep2_curve_set_twist(), ep3_curve_get_cof(), ep3_curve_get_ord(), ep3_curve_set(), ep3_curve_set_twist(), ep4_curve_get_cof(), ep4_curve_get_ord(), ep4_curve_set(), ep4_curve_set_twist(), ep8_curve_get_cof(), ep8_curve_get_ord(), ep8_curve_set(), ep8_curve_set_twist(), ep_curve_get_cof(), ep_curve_get_ord(), ep_curve_get_v1(), ep_curve_get_v2(), ep_curve_set(), ep_curve_set_endom(), fp_inv_binar(), fp_inv_exgcd(), fp_prime_get_par(), fp_prime_set(), fp_prime_set_pairf(), g1_mul_bct(), g2_mul_bct(), gt_exp_bct(), mpc_mt_bct(), mpc_mt_mul(), mpc_sss_gen(), and pad_pkcs2().
bn_abs()
void bn_abs (bn_t c, const bn_t a)
Returns the absolute value of a multiple precision integer.
Parameters
[out] c - the result.
[in] a - the argument of the absolute function.
Definition at line 62 of file relic_bn_util.c.
References bn_copy(), and RLC_POS.
Referenced by bn_div_imp(), bn_gcd_basic(), bn_gcd_binar(), bn_gcd_dig(), bn_gcd_ext_basic(), bn_gcd_ext_binar(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_lehme(), bn_mod_barrt(), bn_rec_frb(), bn_rec_glv(), bn_rec_jsf(), bn_rec_naf(), bn_rec_reg(), bn_rec_rtnaf(), bn_rec_tnaf(), bn_rec_tnaf_mod(), eb_mul_lodah(), ed_mul_reg_imp(), ep2_mul_monty(), ep2_mul_reg_imp(), ep3_mul_gls_imp(), ep3_mul_monty(), ep3_mul_reg_gls(), ep3_mul_reg_imp(), ep4_mul_monty(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), ep8_mul_monty(), ep8_mul_reg_gls(), ep8_mul_reg_imp(), ep_mul_combs_endom(), ep_mul_monty(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_mul_sim_endom(), fp12_exp_cyc_sim(), gt_exp_gls_naf(), gt_exp_gls_sac(), gt_exp_reg_gls(), gt_exp_reg_sac(), pp_exp_afg16(), and pp_exp_fm().
bn_neg()
void bn_neg (bn_t c, const bn_t a)
Inverts the sign of a multiple precision integer.
Parameters
[out] c - the result.
[out] a - the multiple precision integer to negate.
Definition at line 69 of file relic_bn_util.c.
References bn_copy(), and bn_is_zero().
Referenced by bn_div_imp(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_lehme(), bn_is_prime_solov(), bn_rec_frb(), bn_rec_glv(), bn_rec_tnaf_mod(), bn_smb_jac(), ep3_mul_gls_imp(), ep3_mul_reg_gls(), ep_curve_set_endom(), ep_mul_cof(), ep_mul_sim_lot_endom(), ep_param_set(), fp12_exp_cyc_sim(), fp_param_set(), g1_is_valid(), g2_is_valid(), gt_exp_gls_naf(), gt_exp_gls_sac(), gt_exp_reg_gls(), gt_exp_reg_sac(), and gt_is_valid().
bn_sign()
int bn_sign (const bn_t a)
Returns the sign of a multiple precision integer.
Parameters
[in] a - the multiple precision integer.
Returns
RLC_POS if the argument is positive and RLC_NEG otherwise.
Definition at line 78 of file relic_bn_util.c.
Referenced by bn_div_imp(), bn_div_rem_dig(), bn_gcd_ext_binar(), bn_mod_barrt(), bn_mod_inv(), bn_mod_monty_back(), bn_mod_monty_basic(), bn_mod_monty_comba(), bn_mod_monty_conv(), bn_mod_pmers(), bn_mod_pre_barrt(), bn_mod_pre_monty(), bn_mod_pre_pmers(), bn_mxp_basic(), bn_mxp_crt(), bn_mxp_monty(), bn_mxp_slide(), bn_rand_mod(), bn_rec_frb(), bn_rec_rtnaf(), bn_rec_tnaf(), bn_smb_jac(), bn_smb_leg(), bn_srt(), cp_ecdsa_ver(), cp_ecss_ver(), cp_ghpe_dec(), cp_mpsb_sig(), cp_mpsb_ver(), cp_rabin_dec(), cp_rsa_gen(), eb_mul_basic(), eb_mul_fix_basic(), eb_mul_fix_combd(), eb_mul_fix_combs(), eb_mul_fix_kbltz(), eb_mul_fix_plain(), eb_mul_lnaf_imp(), eb_mul_lodah(), eb_mul_ltnaf_imp(), eb_mul_rnaf_imp(), eb_mul_rtnaf_imp(), eb_mul_sim_joint(), eb_mul_sim_kbltz(), eb_mul_sim_plain(), eb_mul_sim_trick(), ed_mul_basic(), ed_mul_combs_plain(), ed_mul_fix_basic(), ed_mul_fix_combd(), ed_mul_fix_plain(), ed_mul_monty(), ed_mul_naf_imp(), ed_mul_reg_imp(), ed_mul_sim_joint(), ed_mul_sim_lot(), ed_mul_sim_plain(), ed_mul_sim_trick(), ed_mul_slide(), ep2_mul_basic(), ep2_mul_fix_plain(), ep2_mul_gls_imp(), ep2_mul_naf_imp(), ep2_mul_reg_gls(), ep2_mul_reg_imp(), ep2_mul_sim_endom(), ep2_mul_sim_joint(), ep2_mul_sim_lot(), ep2_mul_sim_plain(), ep2_mul_slide(), ep3_mul_basic(), ep3_mul_fix_plain(), ep3_mul_gls_imp(), ep3_mul_naf_imp(), ep3_mul_reg_gls(), ep3_mul_reg_imp(), ep3_mul_sim_joint(), ep3_mul_sim_lot(), ep3_mul_sim_plain(), ep3_mul_sim_trick(), ep3_mul_slide(), ep4_mul_basic(), ep4_mul_fix_combd(), ep4_mul_fix_ordin(), ep4_mul_gls_imp(), ep4_mul_naf_imp(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), ep4_mul_sim_joint(), ep4_mul_sim_lot(), ep4_mul_sim_plain(), ep4_mul_sim_trick(), ep4_mul_slide(), ep8_mul_basic(), ep8_mul_fix_combd(), ep8_mul_fix_ordin(), ep8_mul_gls_imp(), ep8_mul_naf_imp(), ep8_mul_reg_gls(), ep8_mul_reg_imp(), ep8_mul_sim_joint(), ep8_mul_sim_lot(), ep8_mul_sim_plain(), ep8_mul_sim_trick(), ep8_mul_slide(), ep_curve_set_endom(), ep_mul_basic(), ep_mul_combs_endom(), ep_mul_fix_plain(), ep_mul_glv_imp(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_mul_sim_endom(), ep_mul_sim_joint(), ep_mul_sim_lot_endom(), ep_mul_sim_lot_plain(), ep_mul_sim_plain(), ep_param_set(), fb_exp_basic(), fb_exp_monty(), fb_exp_slide(), fp12_exp(), fp12_exp_cyc(), fp12_exp_cyc_sim(), fp16_exp(), fp16_exp_cyc(), fp16_exp_cyc_sim(), fp18_exp(), fp18_exp_cyc(), fp18_exp_cyc_sim(), fp24_exp(), fp24_exp_cyc(), fp24_exp_cyc_sim(), fp2_exp(), fp2_exp_cyc(), fp2_exp_cyc_sim(), fp3_exp(), fp48_exp(), fp48_exp_cyc(), fp48_exp_cyc_sim(), fp4_exp(), fp54_exp(), fp54_exp_cyc(), fp6_exp(), fp8_exp(), fp8_exp_cyc(), fp8_exp_cyc_sim(), fp9_exp(), fp_exp_basic(), fp_exp_monty(), fp_exp_slide(), fp_inv_binar(), fp_inv_exgcd(), fp_read_bin(), fp_read_str(), g1_is_valid(), g1_mul(), g1_mul_lcl(), g2_mul(), g2_mul_lcl(), gt_exp(), gt_exp_gls_naf(), gt_exp_gls_sac(), gt_exp_lcl(), gt_exp_reg_gls(), gt_exp_reg_sac(), gt_exp_sec(), gt_is_valid(), mpc_mt_gen(), mpc_mt_lcl(), mpc_mt_mul(), pp_exp_afg16(), pp_exp_b12(), pp_exp_bn(), pp_exp_fm(), pp_exp_k24(), pp_exp_k48(), pp_exp_k54(), pp_exp_kss(), pp_exp_sg(), pp_map_k24(), pp_map_k48(), pp_map_k54(), pp_map_oatep_k12(), pp_map_oatep_k16(), pp_map_oatep_k18(), pp_map_oatep_k8(), pp_map_sim_k24(), pp_map_sim_k48(), pp_map_sim_oatep_k12(), pp_map_sim_oatep_k16(), pp_map_sim_oatep_k18(), and pp_map_sim_oatep_k8().
bn_zero()
void bn_zero (bn_t a)
Assigns zero to a multiple precision integer.
Parameters
[out] a - the multiple precision integer to assign.
Definition at line 82 of file relic_bn_util.c.
References dv_zero(), and RLC_POS.
Referenced by bn_div_imp(), bn_evl(), bn_gcd_ext_basic(), bn_gcd_ext_binar(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_lag(), bn_mod_2b(), bn_mod_barrt(), bn_mod_monty_basic(), bn_mod_monty_comba(), bn_mul_basic(), bn_mxp_basic(), bn_mxp_dig(), bn_mxp_monty(), bn_mxp_sim_few(), bn_mxp_sim_lot(), bn_mxp_slide(), bn_read_bin(), bn_read_str(), bn_rec_frb(), bn_rec_tnaf_mod(), bn_set_dig(), bn_sqr_basic(), bn_srt(), cp_etrs_ext(), cp_etrs_sig(), cp_ghpe_dec(), cp_mklhs_fun(), cp_mklhs_onv(), cp_mklhs_ver(), cp_mpsb_sig(), cp_mpsb_ver(), cp_rabin_enc(), cp_rsa_enc(), cp_rsa_sig(), ep_param_set(), fp_inv_binar(), fp_inv_exgcd(), fp_inv_monty(), and pad_pkcs2().
bn_is_zero()
int bn_is_zero (const bn_t a)
Tests if a multiple precision integer is zero or not.
Parameters
[in] a - the multiple precision integer to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 88 of file relic_bn_util.c.
Referenced by bn_bits(), bn_cmp(), bn_cmp_abs(), bn_div(), bn_div_dig(), bn_div_imp(), bn_div_rem(), bn_div_rem_dig(), bn_gcd_basic(), bn_gcd_binar(), bn_gcd_dig(), bn_gcd_ext_basic(), bn_gcd_ext_binar(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_lehme(), bn_is_even(), bn_is_factor(), bn_is_prime_rabin(), bn_mod_barrt(), bn_mod_pmers(), bn_mod_pre_barrt(), bn_mod_pre_pmers(), bn_mxp_basic(), bn_mxp_monty(), bn_mxp_sim_few(), bn_mxp_slide(), bn_neg(), bn_rand_mod(), bn_rec_jsf(), bn_rec_naf(), bn_rec_tnaf(), bn_size_str(), bn_smb_jac(), bn_write_str(), cp_bbs_gen(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ecss_sig(), cp_ecss_ver(), cp_etrs_ext(), cp_pokor_ver(), cp_rabin_dec(), cp_sokor_ver(), eb_mul_basic(), eb_mul_fix_basic(), eb_mul_fix_combd(), eb_mul_fix_combs(), eb_mul_fix_kbltz(), eb_mul_fix_plain(), eb_mul_halve(), eb_mul_lodah(), eb_mul_lwnaf(), eb_mul_rwnaf(), eb_mul_sim_gen(), eb_mul_sim_inter(), eb_mul_sim_joint(), eb_mul_sim_trick(), ed_mul_basic(), ed_mul_fix_basic(), ed_mul_gen(), ed_mul_lwnaf(), ed_mul_lwreg(), ed_mul_monty(), ed_mul_naf_imp(), ed_mul_sim_gen(), ed_mul_sim_inter(), ed_mul_sim_joint(), ed_mul_sim_trick(), ed_mul_slide(), ep2_mul_basic(), ep2_mul_fix_basic(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_fix_lwnaf(), ep2_mul_fix_plain(), ep2_mul_gen(), ep2_mul_lwnaf(), ep2_mul_lwreg(), ep2_mul_monty(), ep2_mul_sim_gen(), ep2_mul_sim_inter(), ep2_mul_sim_joint(), ep2_mul_sim_trick(), ep2_mul_slide(), ep2_upk(), ep3_mul_basic(), ep3_mul_fix_basic(), ep3_mul_fix_combd(), ep3_mul_fix_combs(), ep3_mul_fix_lwnaf(), ep3_mul_fix_plain(), ep3_mul_gen(), ep3_mul_lwnaf(), ep3_mul_lwreg(), ep3_mul_monty(), ep3_mul_sim_gen(), ep3_mul_sim_inter(), ep3_mul_sim_joint(), ep3_mul_sim_trick(), ep3_mul_slide(), ep4_mul_basic(), ep4_mul_fix_basic(), ep4_mul_fix_combd(), ep4_mul_fix_combs(), ep4_mul_fix_ordin(), ep4_mul_gen(), ep4_mul_lwnaf(), ep4_mul_lwreg(), ep4_mul_monty(), ep4_mul_sim_gen(), ep4_mul_sim_inter(), ep4_mul_sim_joint(), ep4_mul_sim_trick(), ep4_mul_slide(), ep8_mul_basic(), ep8_mul_fix_basic(), ep8_mul_fix_combd(), ep8_mul_fix_combs(), ep8_mul_fix_ordin(), ep8_mul_gen(), ep8_mul_lwnaf(), ep8_mul_lwreg(), ep8_mul_monty(), ep8_mul_sim_gen(), ep8_mul_sim_inter(), ep8_mul_sim_joint(), ep8_mul_sim_trick(), ep8_mul_slide(), ep_mul_basic(), ep_mul_fix_basic(), ep_mul_fix_combd(), ep_mul_fix_combs(), ep_mul_fix_lwnaf(), ep_mul_gen(), ep_mul_lwnaf(), ep_mul_lwreg(), ep_mul_monty(), ep_mul_sim_gen(), ep_mul_sim_inter(), ep_mul_sim_joint(), ep_mul_sim_trick(), ep_mul_slide(), ep_param_set(), fb_exp_basic(), fb_exp_monty(), fb_exp_slide(), fp12_exp(), fp12_exp_cyc(), fp12_exp_cyc_sim(), fp16_exp(), fp16_exp_cyc(), fp16_exp_cyc_sim(), fp18_exp(), fp18_exp_cyc(), fp18_exp_cyc_sim(), fp24_exp(), fp24_exp_cyc(), fp24_exp_cyc_sim(), fp2_exp(), fp2_exp_cyc(), fp2_exp_cyc_sim(), fp3_exp(), fp48_exp(), fp48_exp_cyc(), fp48_exp_cyc_sim(), fp4_exp(), fp54_exp(), fp54_exp_cyc(), fp6_exp(), fp8_exp(), fp8_exp_cyc(), fp8_exp_cyc_sim(), fp9_exp(), fp_exp_basic(), fp_exp_monty(), fp_exp_slide(), fp_inv_monty(), fp_prime_conv(), fp_read_bin(), fp_read_str(), gt_exp_gls_naf(), gt_exp_reg_gls(), and pad_pkcs2().
bn_is_even()
int bn_is_even (const bn_t a)
Tests if a multiple precision integer is even or odd.
Parameters
[in] a - the multiple precision integer to test.
Returns
1 if the argument is even, 0 otherwise.
Definition at line 98 of file relic_bn_util.c.
References bn_is_zero().
Referenced by bn_factor(), bn_gcd_binar(), bn_gcd_ext_binar(), bn_is_prime_rabin(), bn_mod_monty_back(), bn_mod_monty_basic(), bn_mod_monty_comba(), bn_mod_monty_conv(), bn_mod_pre_monty(), bn_rec_naf(), bn_rec_tnaf_mod(), bn_smb_jac(), cp_rsapsi_ans(), cp_rsapsi_ask(), cp_shipsi_ans(), cp_shipsi_ask(), ed_mul_reg_imp(), ep2_mul_reg_gls(), ep2_mul_reg_imp(), ep3_mul_gls_imp(), ep3_mul_reg_gls(), ep3_mul_reg_imp(), ep4_mul_cof_fm16(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), ep8_mul_reg_gls(), ep8_mul_reg_imp(), ep_mul_cof(), ep_mul_reg_glv(), ep_mul_reg_imp(), fp12_exp_cyc(), fp18_exp_cyc(), fp24_exp_cyc(), fp48_exp_cyc(), fp54_exp_cyc(), fp_is_even(), fp_prime_set(), g1_is_valid(), g2_is_valid(), gt_exp_gls_sac(), gt_exp_reg_gls(), gt_exp_reg_sac(), gt_is_valid(), and pp_exp_afg16().
bn_bits()
size_t bn_bits (const bn_t a)
Returns the number of bits of a multiple precision integer.
Parameters
[in] a - the multiple precision integer.
Returns
number of bits.
Definition at line 108 of file relic_bn_util.c.
References bn_is_zero(), RLC_DIG, and util_bits_dig().
Referenced by bn_gcd_ext_binar(), bn_gcd_ext_lehme(), bn_gcd_lehme(), bn_gen_prime_basic(), bn_gen_prime_factor(), bn_gen_prime_safep(), bn_gen_prime_stron(), bn_get_bit(), bn_ham(), bn_is_prime_rabin(), bn_is_prime_solov(), bn_mod_pmers(), bn_mod_pre_pmers(), bn_mxp_basic(), bn_mxp_monty(), bn_mxp_sim_few(), bn_mxp_slide(), bn_rand_mod(), bn_rec_frb(), bn_rec_glv(), bn_rec_jsf(), bn_rec_naf(), bn_rec_rtnaf(), bn_rec_sac(), bn_rec_slw(), bn_rec_tnaf(), bn_rec_win(), bn_size_str(), bn_srt(), cp_ecdh_key(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ecies_dec(), cp_ecies_enc(), cp_ecmqv_key(), cp_ecss_sig(), cp_ecss_ver(), cp_ghpe_dec(), cp_ghpe_enc(), cp_phpe_dec(), cp_phpe_enc(), cp_rsa_sig(), cp_rsa_ver(), cp_shpe_dec(), cp_shpe_enc(), cp_shpe_enc_prv(), eb_map(), eb_mul_basic(), eb_mul_fix_basic(), eb_mul_fix_combd(), eb_mul_fix_combs(), eb_mul_halve(), eb_mul_lodah(), eb_mul_pre_basic(), eb_mul_pre_combd(), eb_mul_pre_combs(), eb_mul_sim_joint(), ed_mul_basic(), ed_mul_combs_plain(), ed_mul_fix_basic(), ed_mul_fix_combd(), ed_mul_monty(), ed_mul_pre_basic(), ed_mul_pre_combd(), ed_mul_pre_combs(), ed_mul_sim_joint(), ed_mul_sim_lot(), ep2_mul_basic(), ep2_mul_fix_basic(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_monty(), ep2_mul_pre_basic(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_reg_gls(), ep2_mul_reg_imp(), ep2_mul_sim_joint(), ep3_mul_basic(), ep3_mul_fix_basic(), ep3_mul_fix_combd(), ep3_mul_fix_combs(), ep3_mul_gls_imp(), ep3_mul_monty(), ep3_mul_pre_basic(), ep3_mul_pre_combd(), ep3_mul_pre_combs(), ep3_mul_reg_gls(), ep3_mul_reg_imp(), ep3_mul_sim_joint(), ep4_mul_basic(), ep4_mul_fix_basic(), ep4_mul_fix_combd(), ep4_mul_fix_combs(), ep4_mul_monty(), ep4_mul_pre_basic(), ep4_mul_pre_combd(), ep4_mul_pre_combs(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), ep4_mul_sim_joint(), ep8_mul_basic(), ep8_mul_fix_basic(), ep8_mul_fix_combd(), ep8_mul_fix_combs(), ep8_mul_monty(), ep8_mul_pre_basic(), ep8_mul_pre_combd(), ep8_mul_pre_combs(), ep8_mul_reg_gls(), ep8_mul_reg_imp(), ep8_mul_sim_joint(), ep_curve_set_endom(), ep_mul_basic(), ep_mul_combs_endom(), ep_mul_combs_plain(), ep_mul_fix_basic(), ep_mul_fix_combd(), ep_mul_monty(), ep_mul_pre_basic(), ep_mul_pre_combd(), ep_mul_pre_combs(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_mul_sim_joint(), ep_mul_sim_lot_plain(), fb_exp_basic(), fb_exp_monty(), fb_read_str(), fp12_exp(), fp12_exp_cyc(), fp12_exp_cyc_sim(), fp12_exp_dig(), fp16_exp(), fp16_exp_cyc(), fp16_exp_dig(), fp18_exp(), fp18_exp_cyc(), fp18_exp_dig(), fp24_exp(), fp24_exp_cyc(), fp24_exp_dig(), fp2_exp(), fp2_exp_cyc(), fp3_exp(), fp48_exp(), fp48_exp_cyc(), fp48_exp_dig(), fp4_exp(), fp54_exp(), fp54_exp_cyc(), fp54_exp_dig(), fp6_exp(), fp8_exp(), fp8_exp_cyc(), fp8_exp_dig(), fp9_exp(), fp_exp_basic(), fp_exp_monty(), fp_prime_set_pairf(), g1_mul(), g2_mul(), gt_exp(), gt_exp_gls_sac(), gt_exp_reg_gls(), gt_exp_reg_sac(), gt_exp_sec(), pp_mil_k1(), pp_mil_k12(), pp_mil_k16(), pp_mil_k18(), pp_mil_k2(), pp_mil_k24(), pp_mil_k48(), pp_mil_k54(), pp_mil_k8(), pp_mil_lit_k12(), pp_mil_lit_k16(), pp_mil_lit_k18(), and pp_mil_lit_k2().
bn_get_bit()
int bn_get_bit (const bn_t a, uint_t bit)
Returns the bit stored in the given position on a multiple precision integer.
Parameters
[in] a - the multiple precision integer.
[in] bit - the bit position to read.
Returns
the bit value.
Definition at line 121 of file relic_bn_util.c.
References bn_bits(), and RLC_RIP.
Referenced by bn_ham(), bn_mxp_basic(), bn_mxp_monty(), bn_mxp_sim_few(), bn_rec_glv(), bn_rec_sac(), bn_rec_slw(), eb_mul_fix_basic(), eb_mul_fix_combd(), eb_mul_fix_combs(), eb_mul_lodah(), ed_map_ell2_5mod8(), ed_mul_combs_plain(), ed_mul_fix_basic(), ed_mul_fix_combd(), ed_mul_monty(), ed_param_set(), ep2_curve_set_map(), ep2_map_swift(), ep2_mul_fix_basic(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_monty(), ep3_map(), ep3_mul_fix_basic(), ep3_mul_fix_combd(), ep3_mul_fix_combs(), ep3_mul_monty(), ep4_map(), ep4_mul_fix_basic(), ep4_mul_fix_combd(), ep4_mul_fix_combs(), ep4_mul_monty(), ep8_map(), ep8_mul_fix_basic(), ep8_mul_fix_combd(), ep8_mul_fix_combs(), ep8_mul_monty(), ep_curve_set_map(), ep_mul_combs_endom(), ep_mul_combs_plain(), ep_mul_fix_basic(), ep_mul_fix_combd(), ep_mul_monty(), fb_exp_basic(), fb_exp_monty(), fp12_exp(), fp12_exp_cyc(), fp12_exp_cyc_sim(), fp16_exp(), fp18_exp(), fp18_exp_cyc(), fp24_exp(), fp24_exp_cyc(), fp2_exp(), fp2_sgn0(), fp3_exp(), fp48_exp(), fp48_exp_cyc(), fp4_exp(), fp54_exp(), fp54_exp_cyc(), fp6_exp(), fp8_exp(), fp9_exp(), fp_exp_basic(), fp_exp_monty(), pad_pkcs2(), pp_mil_k1(), pp_mil_k2(), pp_mil_lit_k12(), pp_mil_lit_k16(), pp_mil_lit_k18(), and pp_mil_lit_k2().
bn_set_bit()
void bn_set_bit (bn_t a, uint_t bit, int value)
Stores a bit in a given position on a multiple precision integer.
Parameters
[out] a - the multiple precision integer.
[in] bit - the bit position to store.
[in] value - the bit value.
Definition at line 137 of file relic_bn_util.c.
References bn_grow(), bn_trim(), and RLC_RIP.
Referenced by cp_ecmqv_key(), fp_param_set(), and pad_pkcs2().
bn_ham()
uint_t bn_ham (const bn_t a)
Returns the Hamming weight of a multiple precision integer.
Parameters
[in] a - the multiple precision integer.
Returns
the number of non-zero bits.
Definition at line 155 of file relic_bn_util.c.
References bn_bits(), and bn_get_bit().
Referenced by fp12_exp_cyc(), fp18_exp_cyc(), fp24_exp_cyc(), fp48_exp_cyc(), and fp54_exp_cyc().
bn_get_dig()
void bn_get_dig (dig_t * digit, const bn_t a)
Reads the first digit in a multiple precision integer.
Parameters
[out] digit - the result.
[in] a - the multiple precision integer.
Definition at line 165 of file relic_bn_util.c.
Referenced by bn_rec_jsf(), bn_rec_naf(), and bn_rec_reg().
bn_set_dig()
void bn_set_dig (bn_t a, dig_t digit)
Assigns a small positive constant to a multiple precision integer.
The constant must fit on a multiple precision digit, or dig_t type using only the number of bits specified on RLC_DIG.
Parameters
[out] a - the result.
[in] digit - the constant to assign.
Definition at line 169 of file relic_bn_util.c.
References bn_zero(), and RLC_POS.
Referenced by bn_div_imp(), bn_factor(), bn_gcd_dig(), bn_gcd_ext_basic(), bn_gcd_ext_binar(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gen_prime_factor(), bn_is_prime_rabin(), bn_is_prime_solov(), bn_lag(), bn_mod_barrt(), bn_mod_pre_monty(), bn_mxp_basic(), bn_mxp_dig(), bn_mxp_monty(), bn_mxp_sim_few(), bn_mxp_sim_lot(), bn_mxp_slide(), bn_rec_tnaf_mod(), cp_bdpe_enc(), cp_bdpe_gen(), cp_etrs_sig(), cp_etrs_uni(), cp_etrs_ver(), ed_mul_dig(), ep2_mul_dig(), ep3_mul_dig(), ep4_mul_dig(), ep8_mul_dig(), ep_mul_dig(), ep_param_set(), fp12_exp_dig(), fp16_exp_dig(), fp18_exp_dig(), fp24_exp_dig(), fp48_exp_dig(), fp54_exp_dig(), fp8_exp_dig(), fp_inv_binar(), fp_inv_divst(), fp_inv_exgcd(), fp_inv_monty(), fp_param_set(), fp_prime_set(), fp_prime_set_pairf(), fp_smb_divst(), gt_exp_dig(), mpc_sss_gen(), mpc_sss_key(), and pp_exp_k8().
bn_set_2b()
void bn_set_2b (bn_t a, size_t b)
Assigns a multiple precision integer to 2^b.
Parameters
[out] a - the result.
[in] b - the power of 2 to assign.
Definition at line 176 of file relic_bn_util.c.
References bn_grow(), ERR_NO_VALID, RLC_BN_SIZE, RLC_DIG, RLC_POS, RLC_RIP, and RLC_THROW.
Referenced by bn_mod_pre_barrt(), bn_mod_pre_pmers(), bn_srt(), cp_rsa_gen(), fp_inv_monty(), fp_param_set(), fp_prime_set(), and fp_prime_set_pmers().
bn_rand()
void bn_rand (bn_t a, int sign, size_t bits)
Assigns a random value to a multiple precision integer.
Parameters
[out] a - the multiple precision integer to assign.
[in] sign - the sign to be assigned (RLC_NEG or RLC_POS).
[in] bits - the number of bits.
Definition at line 194 of file relic_bn_util.c.
References bn_grow(), bn_trim(), rand_bytes(), and RLC_RIP.
Referenced by bn_gen_prime_basic(), bn_gen_prime_factor(), bn_gen_prime_safep(), bn_gen_prime_stron(), bn_is_prime_solov(), bn_rand_mod(), cp_bbs_gen(), cp_bdpe_gen(), cp_lvprv_gen(), cp_lvpub_ask(), cp_pdprv_gen(), cp_pdpub_gen(), and eb_mul_halve().
bn_rand_mod()
void bn_rand_mod (bn_t a, const bn_t b)
Assigns a non-zero random value to a multiple precision integer with absolute value smaller than a given modulus.
Parameters
[out] a - the multiple precision integer to assign.
[in] b - the modulus.
Definition at line 213 of file relic_bn_util.c.
References bn_bits(), bn_cmp_abs(), bn_copy(), bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, bn_rand(), bn_sign(), ERR_CAUGHT, RAND_DIST, RLC_CATCH_ANY, RLC_FINALLY, RLC_LT, RLC_THROW, and RLC_TRY.
Referenced by cp_bdpe_enc(), cp_bgn_enc1(), cp_bgn_enc2(), cp_bgn_gen(), cp_bls_gen(), cp_clb_gen(), cp_cli_gen(), cp_cls_gen(), cp_cmlhs_gen(), cp_cmlhs_sig(), cp_ecdh_gen(), cp_ecdsa_gen(), cp_ecdsa_sig(), cp_ecies_enc(), cp_ecies_gen(), cp_ecmqv_gen(), cp_ecss_gen(), cp_ecss_sig(), cp_ers_ext(), cp_ers_gen_key(), cp_ers_sig(), cp_etrs_sig(), cp_etrs_uni(), cp_ghpe_enc(), cp_ibe_enc(), cp_ibe_gen(), cp_lvprv_gen(), cp_lvpub_gen(), cp_mklhs_gen(), cp_mpsb_gen(), cp_mpsb_sig(), cp_mpsb_ver(), cp_mpss_gen(), cp_mpss_ver(), cp_pbpsi_ans(), cp_pbpsi_ask(), cp_pbpsi_gen(), cp_pdprv_gen(), cp_pdpub_gen(), cp_phpe_enc(), cp_pokdl_prv(), cp_pokor_prv(), cp_psb_gen(), cp_pss_gen(), cp_rsapsi_ans(), cp_rsapsi_ask(), cp_rsapsi_gen(), cp_shipsi_ans(), cp_shipsi_ask(), cp_shipsi_gen(), cp_shpe_enc(), cp_shpe_enc_prv(), cp_smlers_ext(), cp_sokaka_gen(), cp_sokdl_sig(), cp_sokor_sig(), cp_vbnn_gen(), cp_vbnn_gen_prv(), cp_vbnn_sig(), cp_zss_gen(), eb_rand(), ed_rand(), ep2_rand(), ep3_rand(), ep4_rand(), ep8_rand(), ep_rand(), mpc_mt_gen(), and mpc_sss_gen().
bn_print()
void bn_print (const bn_t a)
Prints a multiple precision integer to standard output.
Parameters
[in] a - the multiple precision integer to print.
Definition at line 233 of file relic_bn_util.c.
References RLC_NEG, util_print, and util_print_dig().
Referenced by fp_param_print().
bn_size_str()
size_t bn_size_str (const bn_t a, uint_t radix)
Returns the number of digits in radix necessary to store a multiple precision integer. The radix must be included in the interval [2, 64].
Parameters
[in] a - the multiple precision integer.
[in] radix - the radix.
Exceptions
ERR_NO_VALID - if the radix is invalid.
Returns
the number of digits in the given radix.
Definition at line 257 of file relic_bn_util.c.
References bn_bits(), bn_copy(), bn_div_dig(), bn_free, bn_is_zero(), bn_new, bn_null, ERR_CAUGHT, ERR_NO_VALID, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_POS, RLC_THROW, and RLC_TRY.
Referenced by bn_write_str(), fb_size_str(), and fp_size_str().
bn_read_str()
void bn_read_str (bn_t a, const char * str, size_t len, uint_t radix)
Reads a multiple precision integer from a string in a given radix. The radix must be included in the interval [2, 64].
Parameters
[out] a - the result.
[in] str - the string.
[in] len - the size of the string.
[in] radix - the radix.
Exceptions
ERR_NO_VALID - if the radix is invalid.
Definition at line 301 of file relic_bn_util.c.
References bn_add_dig(), bn_grow(), bn_mul_dig(), bn_trim(), bn_zero(), ERR_CAUGHT, ERR_NO_VALID, RLC_CATCH_ANY, RLC_CEIL, RLC_DIG, RLC_NEG, RLC_POS, RLC_THROW, RLC_TRY, RLC_UPP, util_bits_dig(), and util_conv_char().
Referenced by fb_read_str(), fp_param_set(), and fp_read_str().
bn_write_str()
void bn_write_str (char * str, size_t len, const bn_t a, uint_t radix)
Writes a multiple precision integer to a string in a given radix. The radix must be included in the interval [2, 64].
Parameters
[out] str - the string.
[in] len - the buffer capacity.
[in] a - the multiple integer to write.
[in] radix - the radix.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
ERR_NO_VALID - if the radix is invalid.
Definition at line 350 of file relic_bn_util.c.
References bn_copy(), bn_div_rem_dig(), bn_free, bn_is_zero(), bn_new, bn_null, bn_size_str(), ERR_CAUGHT, ERR_NO_BUFFER, ERR_NO_VALID, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_POS, RLC_THROW, RLC_TRY, and util_conv_char().
Referenced by fp_write_str().
bn_size_bin()
size_t bn_size_bin (const bn_t a)
Returns the number of bytes necessary to store a multiple precision integer.
Parameters
[in] a - the multiple precision integer.
Returns
the number of bytes.
Definition at line 416 of file relic_bn_util.c.
References RLC_DIG.
Referenced by bn_write_bin(), cp_bdpe_dec(), cp_bdpe_enc(), cp_ecdh_key(), cp_ecies_dec(), cp_ecies_enc(), cp_ecmqv_key(), cp_rabin_dec(), cp_rabin_enc(), cp_rsa_dec(), cp_rsa_enc(), cp_rsa_sig(), cp_rsa_ver(), and pad_pkcs2().
bn_read_bin()
void bn_read_bin (bn_t a, const uint8_t * bin, size_t len)
Reads a positive multiple precision integer from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Definition at line 430 of file relic_bn_util.c.
References bn_grow(), bn_trim(), bn_zero(), RLC_DIG, and RLC_POS.
Referenced by cp_bbs_sig(), cp_bbs_ver(), cp_bdpe_dec(), cp_clb_sig(), cp_clb_ver(), cp_cli_sig(), cp_cli_ver(), cp_cls_sig(), cp_cls_ver(), cp_cmlhs_sig(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ecss_sig(), cp_ecss_ver(), cp_pokdl_prv(), cp_pokdl_ver(), cp_pokor_prv(), cp_pokor_ver(), cp_rabin_dec(), cp_rabin_enc(), cp_rsa_dec(), cp_rsa_enc(), cp_rsa_sig(), cp_rsa_ver(), cp_rsapsi_ans(), cp_rsapsi_ask(), cp_shipsi_ans(), cp_shipsi_ask(), cp_sokdl_sig(), cp_sokdl_ver(), cp_sokor_sig(), cp_sokor_ver(), cp_vbnn_gen_prv(), cp_vbnn_sig(), cp_vbnn_ver(), cp_zss_sig(), cp_zss_ver(), eb_map(), ep2_map_basic(), ep2_map_swift(), ep3_map(), ep4_map(), ep8_map(), ep_map_basic_impl(), ep_map_swift_impl(), fb_read_bin(), fp_read_bin(), and pad_pkcs2().
bn_write_bin()
void bn_write_bin (uint8_t * bin, size_t len, const bn_t a)
Writes a positive multiple precision integer to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the multiple integer to write.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 460 of file relic_bn_util.c.
References bn_size_bin(), ERR_NO_BUFFER, RLC_DIG, and RLC_THROW.
Referenced by cp_bdpe_enc(), cp_ecdh_key(), cp_ecies_dec(), cp_ecies_enc(), cp_ecmqv_key(), cp_ecss_sig(), cp_ecss_ver(), cp_rabin_dec(), cp_rabin_enc(), cp_rsa_dec(), cp_rsa_enc(), cp_rsa_sig(), cp_rsa_ver(), cp_rsapsi_ans(), cp_rsapsi_ask(), cp_shipsi_ans(), cp_shipsi_ask(), fb_write_bin(), fp_write_bin(), and pad_pkcs2().
bn_size_raw()
size_t bn_size_raw (const bn_t a)
Returns the number of digits necessary to store a multiple precision integer.
Parameters
[in] a - the multiple precision integer.
Returns
the number of digits.
Definition at line 491 of file relic_bn_util.c.
bn_read_raw()
void bn_read_raw (bn_t a, const dig_t * raw, size_t len)
Reads a positive multiple precision integer from a digit vector.
Parameters
[out] a - the result.
[in] raw - the digit vector.
[in] len - the size of the string.
Definition at line 495 of file relic_bn_util.c.
References bn_grow(), bn_trim(), dv_copy(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_POS, RLC_THROW, and RLC_TRY.
Referenced by fb_size_str(), fb_write_bin(), fp3_field_init(), fp_inv_monty(), fp_print(), and pp_exp_k1().
bn_write_raw()
void bn_write_raw (dig_t * raw, size_t len, const bn_t a)
Writes a positive multiple precision integer to a byte vector.
Parameters
[out] raw - the digit vector.
[in] len - the buffer capacity.
[in] a - the multiple integer to write.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 507 of file relic_bn_util.c.
References ERR_NO_BUFFER, and RLC_THROW.
bn_cmp_abs()
int bn_cmp_abs (const bn_t a, const bn_t b)
Returns the result of an unsigned comparison between two multiple precision integers.
Parameters
[in] a - the first multiple precision integer.
[in] b - the second multiple precision integer.
Returns
RLC_LT if a < b, RLC_EQ if a == b and RLC_GT if a > b.
Definition at line 39 of file relic_bn_cmp.c.
References bn_is_zero(), dv_cmp(), RLC_EQ, RLC_GT, and RLC_LT.
Referenced by bn_add(), bn_cmp(), bn_div_imp(), bn_gcd_ext_binar(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_lehme(), bn_lcm(), bn_mod_barrt(), bn_mod_monty_basic(), bn_mod_monty_comba(), bn_mod_pmers(), bn_rand_mod(), and bn_sub().
bn_cmp_dig()
int bn_cmp_dig (const bn_t a, dig_t b)
Returns the result of a signed comparison between a multiple precision integer and a digit.
Parameters
[in] a - the multiple precision integer.
[in] b - the digit.
Returns
RLC_LT if a < b, RLC_EQ if a == b and RLC_GT if a > b.
Definition at line 55 of file relic_bn_cmp.c.
References RLC_EQ, RLC_GT, RLC_LT, and RLC_NEG.
Referenced by bn_factor(), bn_is_prime_basic(), bn_is_prime_rabin(), bn_is_prime_solov(), bn_mod_inv(), bn_mxp_basic(), bn_mxp_dig(), bn_mxp_monty(), bn_mxp_sim_few(), bn_mxp_sim_lot(), bn_mxp_slide(), bn_smb_jac(), bn_smb_leg(), bn_srt(), cp_bdpe_gen(), cp_ghpe_gen(), cp_rabin_gen(), cp_rsa_gen(), cp_rsapsi_gen(), cp_shipsi_gen(), eb_mul_halve(), ep_param_set(), fp_inv_binar(), fp_inv_exgcd(), g1_is_valid(), and pad_pkcs2().
bn_cmp()
int bn_cmp (const bn_t a, const bn_t b)
Returns the result of a signed comparison between two multiple precision integers.
Parameters
[in] a - the first multiple precision integer.
[in] b - the second multiple precision integer.
Returns
RLC_LT if a < b, RLC_EQ if a == b and RLC_GT if a > b.
Definition at line 75 of file relic_bn_cmp.c.
References bn_cmp_abs(), bn_is_zero(), RLC_EQ, RLC_GT, RLC_LT, RLC_NEG, and RLC_POS.
Referenced by bn_factor(), bn_gcd_binar(), bn_gcd_ext_binar(), bn_gcd_ext_mid(), bn_is_prime_rabin(), bn_is_prime_solov(), bn_mod_barrt(), bn_smb_leg(), bn_srt(), cp_bdpe_dec(), cp_ecdsa_ver(), cp_ecss_ver(), cp_ghpe_gen(), cp_mklhs_onv(), cp_mklhs_ver(), cp_phpe_gen(), cp_pokdl_ver(), cp_rabin_dec(), cp_rabin_gen(), cp_rsa_gen(), cp_rsapsi_gen(), cp_rsapsi_int(), cp_shipsi_gen(), cp_shipsi_int(), cp_shpe_gen(), cp_sokdl_ver(), cp_vbnn_ver(), ep2_pck(), ep2_upk(), ep_pck(), ep_upk(), fp_inv_binar(), fp_inv_monty(), and fp_read_bin().
bn_add()
void bn_add (bn_t c, const bn_t a, const bn_t b)
Adds two multiple precision integers. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first multiple precision integer to add.
[in] b - the second multiple precision integer to add.
Definition at line 119 of file relic_bn_add.c.
References bn_add_imp(), bn_cmp_abs(), bn_sub_imp(), and RLC_LT.
Referenced by bn_div_imp(), bn_evl(), bn_gcd_ext_binar(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_lehme(), bn_gen_prime_factor(), bn_gen_prime_stron(), bn_mod_barrt(), bn_mod_inv(), bn_mod_pmers(), bn_mul_karat_imp(), bn_mxp_crt(), bn_rec_frb(), bn_rec_glv(), bn_rec_rtnaf(), bn_rec_tnaf(), bn_rec_tnaf_mod(), bn_smb_jac(), bn_sqr_karat_imp(), bn_srt(), cp_bbs_sig(), cp_bgn_dec(), cp_clb_sig(), cp_cli_sig(), cp_cls_sig(), cp_cmlhs_sig(), cp_ecdsa_sig(), cp_ecmqv_key(), cp_ecss_sig(), cp_etrs_sig(), cp_ghpe_dec(), cp_mklhs_fun(), cp_mklhs_onv(), cp_mklhs_ver(), cp_mpsb_sig(), cp_mpsb_ver(), cp_mpss_sig(), cp_psb_sig(), cp_pss_sig(), cp_rabin_dec(), cp_rabin_enc(), cp_rsa_enc(), cp_rsa_gen(), cp_rsa_sig(), cp_shpe_enc(), cp_vbnn_gen_prv(), cp_vbnn_sig(), cp_zss_sig(), eb_mul_lodah(), ep2_mul_monty(), ep3_mul_gls_imp(), ep3_mul_monty(), ep3_mul_reg_gls(), ep4_mul_monty(), ep8_mul_monty(), ep_curve_set_endom(), ep_mul_cof(), ep_mul_monty(), fp3_srt(), fp_inv_binar(), fp_inv_exgcd(), fp_inv_monty(), fp_param_set(), fp_prime_set_pairf(), fp_prime_set_pmers(), g1_mul_bct(), g1_mul_lcl(), g2_mul_bct(), g2_mul_lcl(), gt_exp_bct(), gt_exp_gls_naf(), gt_exp_gls_sac(), gt_exp_lcl(), gt_exp_reg_gls(), gt_exp_reg_sac(), mpc_mt_bct(), mpc_mt_gen(), mpc_mt_lcl(), mpc_mt_mul(), mpc_sss_key(), and pad_pkcs2().
bn_add_dig()
void bn_add_dig (bn_t c, const bn_t a, dig_t b)
Adds a multiple precision integers and a digit. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to add.
[in] b - the digit to add.
Definition at line 145 of file relic_bn_add.c.
References bn_add1_low(), bn_grow(), bn_sub1_low(), bn_trim(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_NEG, RLC_POS, RLC_THROW, and RLC_TRY.
Referenced by bn_gen_prime_factor(), bn_gen_prime_safep(), bn_gen_prime_stron(), bn_read_str(), bn_rec_frb(), bn_rec_glv(), bn_rec_naf(), bn_rec_rtnaf(), bn_rec_sac(), bn_rec_tnaf(), cp_bdpe_dec(), cp_bdpe_gen(), cp_ghpe_enc(), cp_ghpe_gen(), cp_phpe_enc(), cp_rabin_dec(), cp_rabin_enc(), cp_rsa_gen(), cp_rsapsi_ans(), cp_rsapsi_ask(), cp_shipsi_ans(), cp_shipsi_ask(), cp_shpe_enc_prv(), cp_shpe_gen(), eb_map(), ed_param_set(), ep2_mul_reg_gls(), ep3_mul_cof_fm18(), ep3_mul_gls_imp(), ep3_mul_reg_gls(), ep4_mul_cof_b24(), ep4_mul_reg_gls(), ep8_mul_reg_gls(), ep_curve_set_endom(), ep_mul_cof(), ep_param_set(), fp2_srt(), fp_crt(), fp_inv_divst(), fp_param_set(), fp_prime_set(), fp_prime_set_pairf(), fp_prime_set_pmers(), fp_smb_divst(), fp_srt(), g1_is_valid(), gt_exp_gls_sac(), gt_exp_reg_sac(), pad_pkcs2(), pp_exp_afg16(), pp_exp_fm(), pp_exp_k2(), pp_exp_k8(), pp_exp_kss(), pp_map_oatep_k12(), and pp_map_sim_oatep_k12().
bn_sub()
void bn_sub (bn_t c, const bn_t a, const bn_t b)
Subtracts a multiple precision integer from another, that is, computes c = a - b.
Parameters
[out] c - the result.
[in] a - the multiple precision integer.
[in] b - the multiple precision integer to subtract.
Definition at line 182 of file relic_bn_add.c.
References bn_add_imp(), bn_cmp_abs(), bn_sub_imp(), RLC_LT, RLC_NEG, and RLC_POS.
Referenced by bn_div_imp(), bn_gcd_binar(), bn_gcd_ext_basic(), bn_gcd_ext_binar(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_lag(), bn_mod_barrt(), bn_mod_monty_basic(), bn_mod_monty_comba(), bn_mod_pmers(), bn_mod_pre_pmers(), bn_mul_karat_imp(), bn_mxp_crt(), bn_rec_frb(), bn_rec_glv(), bn_rec_rtnaf(), bn_rec_tnaf(), bn_rec_tnaf_mod(), bn_smb_leg(), bn_sqr_karat_imp(), bn_srt(), cp_bdpe_dec(), cp_bgn_dec(), cp_bgn_dec1(), cp_bgn_dec2(), cp_cmlhs_sig(), cp_ecss_sig(), cp_ers_ext(), cp_etrs_sig(), cp_etrs_uni(), cp_etrs_ver(), cp_ghpe_dec(), cp_mpsb_sig(), cp_mpsb_ver(), cp_pokdl_prv(), cp_pokor_prv(), cp_pokor_ver(), cp_rabin_dec(), cp_smlers_ext(), cp_sokdl_sig(), cp_sokor_sig(), cp_sokor_ver(), ep_curve_set_endom(), ep_param_set(), fp_inv_binar(), fp_inv_exgcd(), fp_param_set(), fp_prime_set_pairf(), fp_prime_set_pmers(), g1_mul_lcl(), g2_mul_lcl(), gt_exp_lcl(), mpc_mt_gen(), mpc_mt_lcl(), and mpc_sss_key().
bn_sub_dig()
void bn_sub_dig (bn_t c, const bn_t a, const dig_t b)
Subtracts a digit from a multiple precision integer. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the multiple precision integer.
[in] b - the digit to subtract.
Definition at line 209 of file relic_bn_add.c.
References bn_add1_low(), bn_grow(), bn_sub1_low(), bn_trim(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_NEG, RLC_POS, RLC_THROW, and RLC_TRY.
Referenced by bn_div_imp(), bn_factor(), bn_gen_prime_safep(), bn_gen_prime_stron(), bn_is_prime_rabin(), bn_is_prime_solov(), bn_mxp_crt(), bn_rec_frb(), bn_rec_naf(), bn_rec_rtnaf(), bn_rec_tnaf(), bn_rec_tnaf_mod(), bn_smb_leg(), cp_bdpe_gen(), cp_ghpe_dec(), cp_ghpe_gen(), cp_phpe_dec(), cp_phpe_gen(), cp_rsa_gen(), cp_shipsi_gen(), cp_shpe_dec(), cp_shpe_gen(), ed_map_ell2_5mod8(), ep4_mul_cof_b24(), ep_mul_cof(), ep_param_set(), fp2_field_init(), fp2_srt(), fp3_srt(), fp4_field_init(), fp8_field_init(), fp_crt(), fp_inv_basic(), fp_is_cub(), fp_param_set(), fp_prime_set(), fp_prime_set_pairf(), fp_prime_set_pmers(), fp_smb_basic(), g1_is_valid(), g2_is_valid(), gt_is_valid(), pp_exp_fm(), pp_exp_k1(), pp_exp_kss(), pp_map_sim_tatep_k2(), pp_map_sim_weilp_k1(), pp_map_sim_weilp_k12(), pp_map_sim_weilp_k16(), pp_map_sim_weilp_k18(), pp_map_sim_weilp_k2(), pp_map_tatep_k2(), pp_map_weilp_k12(), pp_map_weilp_k16(), pp_map_weilp_k18(), and pp_map_weilp_k2().
bn_mul_dig()
void bn_mul_dig (bn_t c, const bn_t a, dig_t b)
Multiplies a multiple precision integer by a digit. Computes c = a * b.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to multiply.
[in] b - the digit to multiply.
Definition at line 158 of file relic_bn_mul.c.
References bn_grow(), bn_mul1_low(), bn_trim(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_THROW, and RLC_TRY.
Referenced by bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_lehme(), bn_gen_prime_stron(), bn_mod_pmers(), bn_read_str(), bn_rec_frb(), bn_smb_jac(), cp_bdpe_gen(), cp_mklhs_fun(), ep3_mul_cof_sg18(), ep_mul_cof(), ep_param_set(), fp_param_set(), fp_prime_set_pairf(), g1_is_valid(), g2_is_valid(), gt_is_valid(), pp_map_oatep_k12(), and pp_map_sim_oatep_k12().
bn_mul_basic()
void bn_mul_basic (bn_t c, const bn_t a, const bn_t b)
Multiplies two multiple precision integers using Schoolbook multiplication.
Parameters
[out] c - the result.
[in] a - the first multiple precision integer to multiply.
[in] b - the second multiple precision integer to multiply.
Definition at line 172 of file relic_bn_mul.c.
References bn_copy(), bn_free, bn_mula_low(), bn_new_size, bn_null, bn_trim(), bn_zero(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by bn_mul_karat_imp().
bn_mul_comba()
void bn_mul_comba (bn_t c, const bn_t a, const bn_t b)
Multiplies two multiple precision integers using Comba multiplication.
Parameters
[out] c - the result.
[in] a - the first multiple precision integer to multiply.
[in] b - the second multiple precision integer to multiply.
Definition at line 207 of file relic_bn_mul.c.
References bn_copy(), bn_free, bn_muld_low(), bn_muln_low(), bn_new_size, bn_null, bn_trim(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by bn_mul_karat_imp(), and bn_sqr_karat_imp().
bn_mul_karat()
void bn_mul_karat (bn_t c, const bn_t a, const bn_t b)
Multiplies two multiple precision integers using Karatsuba multiplication.
Parameters
[out] c - the result.
[in] a - the first multiple precision integer to multiply.
[in] b - the second multiple precision integer to multiply.
Definition at line 243 of file relic_bn_mul.c.
References BN_KARAT, and bn_mul_karat_imp().
bn_sqr_basic()
void bn_sqr_basic (bn_t c, const bn_t a)
Computes the square of a multiple precision integer using Schoolbook squaring.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to square.
Definition at line 148 of file relic_bn_sqr.c.
References bn_copy(), bn_free, bn_new_size, bn_null, bn_sqra_low(), bn_trim(), bn_zero(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_POS, RLC_THROW, and RLC_TRY.
Referenced by bn_sqr_karat_imp().
bn_sqr_comba()
void bn_sqr_comba (bn_t c, const bn_t a)
Computes the square of a multiple precision integer using Comba squaring.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to square.
Definition at line 181 of file relic_bn_sqr.c.
References bn_copy(), bn_free, bn_new_size, bn_null, bn_sqrn_low(), bn_trim(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_POS, RLC_THROW, and RLC_TRY.
Referenced by bn_sqr_karat_imp().
bn_sqr_karat()
void bn_sqr_karat (bn_t c, const bn_t a)
Computes the square of a multiple precision integer using Karatsuba squaring.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to square.
Definition at line 211 of file relic_bn_sqr.c.
References BN_KARAT, and bn_sqr_karat_imp().
bn_dbl()
void bn_dbl (bn_t c, const bn_t a)
Doubles a multiple precision. Computes c = a + a.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to double.
Definition at line 39 of file relic_bn_shift.c.
References bn_grow(), bn_lsh1_low(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_THROW, and RLC_TRY.
Referenced by bn_gen_prime_stron(), bn_rec_frb(), bn_rec_tnaf_mod(), ep3_mul_gls_imp(), ep3_mul_reg_gls(), ep4_mul_cof_fm16(), ep_curve_set_endom(), fp_crt(), fp_inv_monty(), fp_param_set(), gt_exp_gls_naf(), gt_exp_gls_sac(), gt_exp_reg_gls(), gt_exp_reg_sac(), and pp_exp_afg16().
bn_hlv()
void bn_hlv (bn_t c, const bn_t a)
Halves a multiple precision. Computes c = floor(a / 2)
Parameters
[out] c - the result.
[in] a - the multiple precision integer to halve.
Definition at line 60 of file relic_bn_shift.c.
References bn_copy(), bn_rsh1_low(), and bn_trim().
Referenced by bn_gcd_binar(), bn_gcd_ext_binar(), bn_rec_jsf(), bn_rec_naf(), bn_rec_reg(), bn_rec_rtnaf(), bn_rec_sac(), bn_rec_tnaf(), bn_rec_tnaf_mod(), bn_srt(), ep2_pck(), ep2_upk(), ep4_mul_cof_fm16(), ep_curve_set_endom(), ep_mul_cof(), ep_pck(), ep_upk(), fp_inv_binar(), fp_prime_set(), fp_smb_basic(), g1_is_valid(), pp_exp_afg16(), and pp_exp_fm16().
bn_lsh()
void bn_lsh (bn_t c, const bn_t a, uint_t bits)
Shifts a multiple precision number to the left. Computes c = a * 2^bits. c = a * 2^bits.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to shift.
[in] bits - the number of bits to shift.
Definition at line 66 of file relic_bn_shift.c.
References bn_grow(), bn_lshb_low(), bn_trim(), dv_copy(), dv_lshd(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_RIP, RLC_THROW, and RLC_TRY.
Referenced by bn_gcd_binar(), bn_gcd_ext_binar(), bn_gen_prime_factor(), bn_gen_prime_safep(), bn_mod_barrt(), bn_mod_monty_conv(), bn_mul_karat_imp(), bn_sqr_karat_imp(), cp_rabin_enc(), eb_mul_halve(), ep_curve_set_endom(), fp_inv_divst(), fp_param_set(), fp_prime_set(), fp_prime_set_pairf(), fp_smb_divst(), pad_pkcs2(), and pp_exp_k8().
bn_rsh()
void bn_rsh (bn_t c, const bn_t a, uint_t bits)
Shifts a multiple precision number to the right. Computes c = floor(a / 2^bits).
Parameters
[out] c - the result.
[in] a - the multiple precision integer to shift.
[in] bits - the number of bits to shift.
Definition at line 97 of file relic_bn_shift.c.
References bn_grow(), bn_rshb_low(), bn_trim(), dv_copy(), dv_rshd(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_RIP, RLC_THROW, and RLC_TRY.
Referenced by bn_gcd_ext_lehme(), bn_gcd_lehme(), bn_gen_prime_safep(), bn_is_prime_rabin(), bn_is_prime_solov(), bn_mod_barrt(), bn_mod_pmers(), bn_rec_frb(), bn_rec_glv(), bn_rec_reg(), bn_smb_jac(), bn_smb_leg(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ecss_sig(), cp_ecss_ver(), cp_rabin_dec(), ed_map_ell2_5mod8(), ed_param_set(), fp2_srt(), fp3_srt(), fp_srt(), pad_pkcs2(), and pp_exp_k8().
bn_div()
void bn_div (bn_t c, const bn_t a, const bn_t b)
Divides a multiple precision integer by another multiple precision integer without producing the positive remainder. Computes c = floor(a / b).
Parameters
[out] c - the resulting quotient.
[in] a - the dividend.
[in] b - the divisor.
Exceptions
ERR_NO_VALID - if the divisor is zero.
Definition at line 135 of file relic_bn_div.c.
References bn_div_imp(), bn_is_zero(), ERR_NO_VALID, and RLC_THROW.
Referenced by bn_gcd_ext_binar(), bn_gcd_ext_lehme(), bn_lcm(), bn_mod_pre_barrt(), bn_mxp_crt(), bn_rec_frb(), cp_ghpe_dec(), cp_phpe_dec(), cp_shpe_dec(), cp_shpe_gen(), ep_curve_set_endom(), fp_prime_set_pairf(), pp_exp_k1(), and pp_exp_k2().
bn_div_rem()
void bn_div_rem (bn_t c, bn_t d, const bn_t a, const bn_t b)
Divides a multiple precision integer by another multiple precision integer and produces a positive remainder. Computes c = floor(a / b) and d = a mod b.
Parameters
[out] c - the resulting quotient.
[out] d - the positive remainder.
[in] a - the dividend.
[in] b - the divisor.
Exceptions
ERR_NO_VALID - if the divisor is zero.
Definition at line 143 of file relic_bn_div.c.
References bn_div_imp(), bn_is_zero(), ERR_NO_VALID, and RLC_THROW.
Referenced by bn_gcd_ext_basic(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_mod_basic(), and fp_inv_exgcd().
bn_div_dig()
void bn_div_dig (bn_t c, const bn_t a, dig_t b)
Divides a multiple precision integers by a digit without computing the remainder. Computes c = floor(a / b).
Parameters
[out] c - the resulting quotient.
[out] d - the remainder.
[in] a - the dividend.
[in] b - the divisor.
Exceptions
ERR_NO_VALID - if the divisor is zero.
Definition at line 151 of file relic_bn_div.c.
References bn_copy(), bn_div1_low(), bn_free, bn_is_zero(), bn_new, bn_null, ERR_CAUGHT, ERR_NO_VALID, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by bn_size_str(), cp_bdpe_dec(), cp_bdpe_gen(), cp_ghpe_dec(), ep3_mul_cof_fm18(), ep3_mul_cof_sg18(), ep_mul_cof(), ep_param_set(), fp2_field_init(), fp3_field_init(), fp3_srt(), fp4_field_init(), fp8_field_init(), fp_crt(), fp_is_cub(), fp_prime_set(), fp_prime_set_pairf(), g1_is_valid(), g2_is_valid(), gt_is_valid(), and pp_exp_fm().
bn_div_rem_dig()
void bn_div_rem_dig (bn_t c, dig_t * d, const bn_t a, const dig_t b)
Divides a multiple precision integers by a digit. Computes c = floor(a / b) and d = a mod b.
Parameters
[out] c - the resulting quotient.
[out] d - the remainder.
[in] a - the dividend.
[in] b - the divisor.
Exceptions
ERR_NO_VALID - if the divisor is zero.
Definition at line 186 of file relic_bn_div.c.
References bn_copy(), bn_div1_low(), bn_free, bn_is_zero(), bn_new, bn_null, bn_sign(), ERR_CAUGHT, ERR_NO_VALID, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by bn_mod_dig(), and bn_write_str().
bn_mod_inv()
void bn_mod_inv (bn_t c, const bn_t a, const bn_t b)
Computes the modular inverse of a multiple precision integer. Computes c such that a*c mod b = 1.
Parameters
[out] c - the result.
[in] a - the element to invert. param[in] b - the modulus.
Definition at line 39 of file relic_bn_inv.c.
References bn_add(), bn_cmp_dig(), bn_copy(), bn_free, bn_gcd_ext, bn_new, bn_null, bn_sign(), ERR_CAUGHT, ERR_NO_VALID, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by bn_mod_inv_sim(), bn_mxp_basic(), bn_mxp_monty(), bn_mxp_slide(), cp_bbs_sig(), cp_cmlhs_sig(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ghpe_dec(), cp_lvprv_ask(), cp_lvprv_gen(), cp_lvpub_gen(), cp_pdprv_ask(), cp_pdprv_gen(), cp_pdpub_gen(), cp_phpe_dec(), cp_phpe_gen(), cp_rsa_gen(), cp_shipsi_ans(), cp_shipsi_gen(), cp_shpe_dec(), cp_shpe_gen(), and cp_zss_sig().
bn_mod_inv_sim()
void bn_mod_inv_sim (bn_t * c, const bn_t * a, const bn_t b, int n)
Computes the modular inverse of multiple precision integers simultaneously. Computes c_i such that a_i * c_i mod b = 1.
Parameters
[out] c - the results.
[in] a - the elements to invert. param[in] b - the modulus.
[in] n - the number of elements.
Definition at line 67 of file relic_bn_inv.c.
References bn_copy(), bn_free, bn_mod, bn_mod_inv(), bn_mul, bn_new, bn_null, ERR_CAUGHT, ERR_NO_MEMORY, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by cp_etrs_sig(), cp_etrs_uni(), cp_etrs_ver(), and mpc_sss_key().
bn_mod_2b()
void bn_mod_2b (bn_t c, const bn_t a, int b)
Reduces a multiple precision integer modulo a power of 2. Computes c = a mod 2^b.
Parameters
[out] c - the result.
[in] a - the dividend.
[in] b - the exponent of the divisor.
Definition at line 40 of file relic_bn_mod.c.
References bn_copy(), bn_trim(), bn_zero(), RLC_DIG, RLC_MASK, and RLC_RIP.
Referenced by bn_mod_barrt(), bn_mod_pmers(), cp_ecmqv_key(), cp_ghpe_gen(), cp_rabin_dec(), cp_rabin_enc(), cp_rabin_gen(), eb_map(), and pad_pkcs2().
bn_mod_dig()
void bn_mod_dig (dig_t * c, const bn_t a, dig_t b)
Reduces a multiple precision integer modulo a digit. Computes c = a mod b.
Parameters
[out] c - the result.
[in] a - the dividend.
[in] b - the divisor.
Definition at line 67 of file relic_bn_mod.c.
References bn_div_rem_dig().
Referenced by bn_gcd_dig(), bn_is_prime_basic(), fp_crt(), fp_prime_set(), g2_is_valid(), and gt_is_valid().
bn_mod_basic()
void bn_mod_basic (bn_t c, const bn_t a, const bn_t m)
Reduces a multiple precision integer modulo an integer using straightforward division.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to reduce.
[in] m - the modulus.
Definition at line 71 of file relic_bn_mod.c.
References bn_div_rem().
bn_mod_pre_barrt()
void bn_mod_pre_barrt (bn_t u, const bn_t m)
Computes the reciprocal of the modulus to be used in the Barrett modular reduction algorithm.
Parameters
[out] u - the result.
[in] m - the modulus.
Definition at line 77 of file relic_bn_mod.c.
References bn_div(), bn_is_zero(), bn_set_2b(), bn_sign(), ERR_NO_VALID, RLC_DIG, RLC_POS, and RLC_THROW.
bn_mod_barrt()
void bn_mod_barrt (bn_t c, const bn_t a, const bn_t m, const bn_t u)
Reduces a multiple precision integer modulo a positive integer using Barrett reduction.
Parameters
[out] c - the result.
[in] a - the the multiple precision integer to reduce.
[in] m - the modulus.
[in] u - the reciprocal of the modulus.
Definition at line 87 of file relic_bn_mod.c.
References bn_abs(), bn_add(), bn_cmp(), bn_cmp_abs(), bn_copy(), bn_free, bn_grow(), bn_is_zero(), bn_lsh(), bn_mod, bn_mod_2b(), bn_mul, bn_muld_low(), bn_new, bn_null, bn_rsh(), bn_set_dig(), bn_sign(), bn_sub(), bn_trim(), bn_zero(), ERR_CAUGHT, ERR_NO_VALID, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_LT, RLC_NEG, RLC_POS, RLC_THROW, and RLC_TRY.
bn_mod_pre_monty()
void bn_mod_pre_monty (bn_t u, const bn_t m)
Computes the reciprocal of the modulus to be used in the Montgomery reduction algorithm.
Parameters
[out] u - the result.
[in] m - the modulus.
Exceptions
ERR_NO_VALID - if the modulus is even.
Definition at line 176 of file relic_bn_mod.c.
References bn_is_even(), bn_set_dig(), bn_sign(), ERR_NO_VALID, RLC_POS, and RLC_THROW.
Referenced by bn_mod_monty_back(), and fp_prime_set().
bn_mod_monty_conv()
void bn_mod_monty_conv (bn_t c, const bn_t a, const bn_t m)
Converts a multiple precision integer to Montgomery form.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to convert.
[in] m - the modulus.
Definition at line 199 of file relic_bn_mod.c.
References bn_is_even(), bn_lsh(), bn_mod, bn_sign(), ERR_NO_VALID, RLC_DIG, RLC_POS, and RLC_THROW.
Referenced by bn_mxp_basic(), bn_mxp_dig(), bn_mxp_monty(), bn_mxp_sim_few(), bn_mxp_slide(), and fp_inv_monty().
bn_mod_monty_back()
void bn_mod_monty_back (bn_t c, const bn_t a, const bn_t m)
Converts a multiple precision integer from Montgomery form.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to convert.
[in] m - the modulus.
Definition at line 210 of file relic_bn_mod.c.
References bn_free, bn_is_even(), bn_mod_monty, bn_mod_pre_monty(), bn_new, bn_null, bn_sign(), ERR_CAUGHT, ERR_NO_VALID, RLC_CATCH_ANY, RLC_FINALLY, RLC_POS, RLC_THROW, and RLC_TRY.
Referenced by bn_mxp_basic(), bn_mxp_dig(), bn_mxp_monty(), bn_mxp_sim_few(), bn_mxp_slide(), and fp_inv_monty().
bn_mod_monty_basic()
void bn_mod_monty_basic (bn_t c, const bn_t a, const bn_t m, const bn_t u)
Reduces a multiple precision integer modulo a positive integer using Montgomery reduction with Schoolbook multiplication.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to reduce.
[in] m - the modulus.
[in] u - the reciprocal of the modulus.
Definition at line 233 of file relic_bn_mod.c.
References bn_addn_low(), bn_cmp_abs(), bn_copy(), bn_free, bn_is_even(), bn_mula_low(), bn_new_size, bn_null, bn_sign(), bn_sub(), bn_subn_low(), bn_trim(), bn_zero(), ERR_CAUGHT, ERR_NO_VALID, RLC_CATCH_ANY, RLC_FINALLY, RLC_LT, RLC_POS, RLC_THROW, and RLC_TRY.
bn_mod_monty_comba()
void bn_mod_monty_comba (bn_t c, const bn_t a, const bn_t m, const bn_t u)
Reduces a multiple precision integer modulo a positive integer using Montgomery reduction with Comba multiplication.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to reduce.
[in] m - the modulus.
[in] u - the reciprocal of the modulus.
Definition at line 282 of file relic_bn_mod.c.
References bn_cmp_abs(), bn_copy(), bn_free, bn_is_even(), bn_modn_low(), bn_new_size, bn_null, bn_sign(), bn_sub(), bn_trim(), bn_zero(), ERR_CAUGHT, ERR_NO_VALID, RLC_CATCH_ANY, RLC_FINALLY, RLC_LT, RLC_POS, RLC_THROW, and RLC_TRY.
bn_mod_pre_pmers()
void bn_mod_pre_pmers (bn_t u, const bn_t m)
Computes u if the modulus has the form 2^b - u.
Parameters
[out] u - the result.
[in] m - the modulus.
Definition at line 321 of file relic_bn_mod.c.
References bn_bits(), bn_is_zero(), bn_set_2b(), bn_sign(), bn_sub(), ERR_NO_VALID, RLC_POS, and RLC_THROW.
bn_mod_pmers()
void bn_mod_pmers (bn_t c, const bn_t a, const bn_t m, const bn_t u)
Reduces a multiple precision integer modulo a positive integer using pseudo-Mersenne modular reduction.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to reduce.
[in] m - the modulus.
[in] u - the auxiliar value derived from the modulus.
Definition at line 331 of file relic_bn_mod.c.
References bn_add(), bn_bits(), bn_cmp_abs(), bn_copy(), bn_free, bn_is_zero(), bn_mod_2b(), bn_mul, bn_mul_dig(), bn_new, bn_null, bn_rsh(), bn_sign(), bn_sub(), ERR_CAUGHT, ERR_NO_VALID, RLC_CATCH_ANY, RLC_FINALLY, RLC_LT, RLC_NEG, RLC_POS, RLC_THROW, and RLC_TRY.
bn_mxp_basic()
void bn_mxp_basic (bn_t c, const bn_t a, const bn_t b, const bn_t m)
Exponentiates a multiple precision integer modulo a positive integer using the binary method.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
[in] m - the modulus.
Definition at line 49 of file relic_bn_mxp.c.
References bn_bits(), bn_cmp_dig(), bn_copy(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_mod_inv(), bn_mod_monty_back(), bn_mod_monty_conv(), bn_mod_pre, bn_mul, bn_new, bn_null, bn_set_dig(), bn_sign(), bn_sqr, bn_zero(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
bn_mxp_slide()
void bn_mxp_slide (bn_t c, const bn_t a, const bn_t b, const bn_t m)
Exponentiates a multiple precision integer modulo a positive integer using the sliding window method.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
[in] m - the modulus.
Definition at line 113 of file relic_bn_mxp.c.
References bn_bits(), bn_cmp_dig(), bn_copy(), bn_free, bn_is_zero(), bn_mod, bn_mod_inv(), bn_mod_monty_back(), bn_mod_monty_conv(), bn_mod_pre, bn_mul, bn_new, bn_null, bn_rec_slw(), bn_set_dig(), bn_sign(), bn_sqr, bn_zero(), ERR_CAUGHT, ERR_NO_MEMORY, RLC_ALLOCA, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_TABLE_SIZE, RLC_THROW, RLC_TRY, and util_bits_dig().
bn_mxp_monty()
void bn_mxp_monty (bn_t c, const bn_t a, const bn_t b, const bn_t m)
Exponentiates a multiple precision integer modulo a positive integer using the constant-time Montgomery powering ladder method.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
[in] m - the modulus.
Definition at line 229 of file relic_bn_mxp.c.
References bn_bits(), bn_cmp_dig(), bn_copy(), bn_free, bn_get_bit(), bn_grow(), bn_is_zero(), bn_mod, bn_mod_inv(), bn_mod_monty_back(), bn_mod_monty_conv(), bn_mod_pre, bn_mul, bn_new, bn_null, bn_set_dig(), bn_sign(), bn_sqr, bn_zero(), dv_swap_sec(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
bn_mxp_dig()
void bn_mxp_dig (bn_t c, const bn_t a, dig_t b, const bn_t m)
Exponentiates a multiple precision integer by a small power modulo a positive integer using the binary method.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
[in] m - the modulus.
Definition at line 403 of file relic_bn_mxp.c.
References bn_cmp_dig(), bn_copy(), bn_free, bn_mod, bn_mod_monty_back(), bn_mod_monty_conv(), bn_mod_pre, bn_mul, bn_new, bn_null, bn_set_dig(), bn_sqr, bn_zero(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, RLC_TRY, and util_bits_dig().
Referenced by cp_bdpe_dec(), and cp_bdpe_enc().
bn_mxp_crt()
void bn_mxp_crt (bn_t d, const bn_t a, const bn_t b, const bn_t c, const crt_t crt, int sqr)
Definition at line 314 of file relic_bn_mxp.c.
References bn_add(), bn_div(), bn_free, bn_mod, bn_mul, bn_mxp, bn_new, bn_null, bn_sign(), bn_sqr, bn_sub(), bn_sub_dig(), CORES, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by cp_phpe_dec(), cp_rsa_dec(), cp_rsa_sig(), cp_shipsi_ans(), and cp_shpe_dec().
bn_mxp_sim()
void bn_mxp_sim (bn_t c, const bn_t a, const bn_t b, const bn_t d, const bn_t e, const bn_t m)
Exponentiates simultaneously two integers modulo a positive integer using generalized Shamir's trick. Computes c = a^b * d^e mod m.
Parameters
[out] c - the result.
[in] a - the elements to exponentiate.
[in] b - the exponents.
[in] m - the modulus.
Definition at line 47 of file relic_bn_mxp_sim.c.
References bn_copy(), bn_free, bn_mxp_sim_few(), bn_new, bn_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
bn_mxp_sim_few()
void bn_mxp_sim_few (bn_t c, const bn_t * a, const bn_t * b, const bn_t m, size_t n)
Exponentiates simultaneously up to 8 integers modulo a positive integer using generalized Shamir's trick. Computes c = \prod a_i^{b_i} mod m.
Parameters
[out] c - the result.
[in] a - the elements to exponentiate.
[in] b - the exponents.
[in] m - the modulus.
Definition at line 80 of file relic_bn_mxp_sim.c.
References bn_bits(), bn_cmp_dig(), bn_copy(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_mod_monty_back(), bn_mod_monty_conv(), bn_mod_pre, bn_mul, bn_new, bn_null, bn_set_dig(), bn_sqr, bn_zero(), ERR_CAUGHT, ERR_NO_MEMORY, ERR_NO_VALID, RLC_ALLOCA, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FREE, RLC_MAX, RLC_THROW, and RLC_TRY.
Referenced by bn_mxp_sim(), and bn_mxp_sim_lot().
bn_mxp_sim_lot()
void bn_mxp_sim_lot (bn_t c, const bn_t * a, const bn_t * b, const bn_t m, size_t n)
Exponentiates simultaneously many integers modulo a positive integer using generalized Shamir's trick. Computes c = \prod a_i^{b_i} mod m.
Parameters
[out] c - the result.
[in] a - the elements to exponentiate.
[in] b - the integer scalars.
[in] m - the modulus.
[in] n - the number of elements to multiply.
Definition at line 171 of file relic_bn_mxp_sim.c.
References bn_cmp_dig(), bn_copy(), bn_free, bn_mod, bn_mul, bn_mxp, bn_mxp_sim_few(), bn_new, bn_null, bn_set_dig(), bn_zero(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, RLC_TRY, and XP_WIDTH.
bn_srt()
void bn_srt (bn_t c, bn_t a)
Extracts an approximate integer square-root of a multiple precision integer.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to extract.
Exceptions
ERR_NO_VALID - if the argument is negative.
Definition at line 39 of file relic_bn_srt.c.
References bn_add(), bn_bits(), bn_cmp(), bn_cmp_dig(), bn_copy(), bn_free, bn_hlv(), bn_new, bn_null, bn_set_2b(), bn_sign(), bn_sqr, bn_sub(), bn_zero(), ERR_CAUGHT, ERR_NO_VALID, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_GT, RLC_LT, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by bn_gcd_ext_mid().
bn_gcd_basic()
void bn_gcd_basic (bn_t c, const bn_t a, const bn_t b)
Computes the greatest common divisor of two multiple precision integers using the standard Euclidean algorithm.
Parameters
[out] c - the result;
[in] a - the first multiple precision integer.
[in] b - the second multiple precision integer.
Definition at line 40 of file relic_bn_gcd.c.
References bn_abs(), bn_copy(), bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
bn_gcd_lehme()
void bn_gcd_lehme (bn_t c, const bn_t a, const bn_t b)
Computes the greatest common divisor of two multiple precision integers using Lehmer's GCD algorithm.
Parameters
[out] c - the result;
[in] a - the first multiple precision integer.
[in] b - the second multiple precision integer.
Definition at line 160 of file relic_bn_gcd.c.
References bn_abs(), bn_add(), bn_bits(), bn_cmp_abs(), bn_copy(), bn_free, bn_gcd_ext_dig(), bn_is_zero(), bn_mod, bn_mul_dig(), bn_neg(), bn_new, bn_null, bn_rsh(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_GT, RLC_THROW, and RLC_TRY.
bn_gcd_binar()
void bn_gcd_binar (bn_t c, const bn_t a, const bn_t b)
Computes the greatest common divisor of two multiple precision integers using the Binary GCD algorithm.
Parameters
[out] c - the result;
[in] a - the first multiple precision integer.
[in] b - the second multiple precision integer.
Definition at line 623 of file relic_bn_gcd.c.
References bn_abs(), bn_cmp(), bn_copy(), bn_free, bn_hlv(), bn_is_even(), bn_is_zero(), bn_lsh(), bn_new, bn_null, bn_sub(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_LT, RLC_THROW, and RLC_TRY.
bn_gcd_dig()
void bn_gcd_dig (bn_t c, const bn_t a, dig_t b)
Computes the greatest common divisor of a multiple precision integer and a digit.
Parameters
[out] c - the result;
[in] a - the multiple precision integer.
[in] b - the digit.
Definition at line 949 of file relic_bn_gcd.c.
References bn_abs(), bn_is_zero(), bn_mod_dig(), and bn_set_dig().
Referenced by bn_gcd_ext_dig(), and cp_bdpe_gen().
bn_gcd_ext_basic()
void bn_gcd_ext_basic (bn_t c, bn_t d, bn_t e, const bn_t a, const bn_t b)
Computes the extended greatest common divisor of two multiple precision integer using the Euclidean algorithm.
Parameters
[out] c - the result.
[out] d - the cofactor of the first operand, can be NULL.
[out] e - the cofactor of the second operand, can be NULL.
[in] a - the first multiple precision integer.
[in] b - the second multiple precision integer.
Definition at line 77 of file relic_bn_gcd.c.
References bn_abs(), bn_copy(), bn_div_rem(), bn_free, bn_is_zero(), bn_mul, bn_new, bn_null, bn_set_dig(), bn_sub(), bn_zero(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
bn_gcd_ext_lehme()
void bn_gcd_ext_lehme (bn_t c, bn_t d, bn_t e, const bn_t a, const bn_t b)
Computes the greatest common divisor of two multiple precision integers using Lehmer's algorithm.
Parameters
[out] c - the result;
[out] d - the cofactor of the first operand, can be NULL.
[out] e - the cofactor of the second operand, can be NULL.
[in] a - the first multiple precision integer.
[in] b - the second multiple precision integer.
Definition at line 356 of file relic_bn_gcd.c.
References bn_abs(), bn_add(), bn_bits(), bn_cmp_abs(), bn_copy(), bn_div(), bn_div_rem(), bn_free, bn_gcd_ext_dig(), bn_is_zero(), bn_mul, bn_mul_dig(), bn_neg(), bn_new, bn_null, bn_rsh(), bn_set_dig(), bn_sub(), bn_zero(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_LT, RLC_THROW, and RLC_TRY.
bn_gcd_ext_binar()
void bn_gcd_ext_binar (bn_t c, bn_t d, bn_t e, const bn_t a, const bn_t b)
Computes the greatest common divisor of two multiple precision integers using the Binary algorithm.
Parameters
[out] c - the result;
[out] d - the cofactor of the first operand, can be NULL.
[out] e - the cofactor of the second operand, can be NULL.
[in] a - the first multiple precision integer.
[in] b - the second multiple precision integer.
Definition at line 683 of file relic_bn_gcd.c.
References bn_abs(), bn_add(), bn_bits(), bn_cmp(), bn_cmp_abs(), bn_copy(), bn_div(), bn_free, bn_hlv(), bn_is_even(), bn_is_zero(), bn_lsh(), bn_mul, bn_new, bn_null, bn_set_dig(), bn_sign(), bn_sub(), bn_zero(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_GT, RLC_LT, RLC_THROW, and RLC_TRY.
bn_gcd_ext_mid()
void bn_gcd_ext_mid (bn_t c, bn_t d, bn_t e, bn_t f, const bn_t a, const bn_t b)
Computes the extended greatest common divisor of two multiple precision integers halfway through the algorithm. Returns also two short vectors v1 = (c, d), v2 = (-e, f) useful to decompose an integer k into k0, k1 such that k = k_0 + k_1 * a (mod b).
Parameters
[out] c - the first component of the first vector.
[out] d - the second component of the first vector.
[out] e - the first component of the second vector.
[out] f - the second component of the second vector.
[in] a - the first multiple precision integer.
[in] b - the second multiple precision integer.
Definition at line 836 of file relic_bn_gcd.c.
References bn_abs(), bn_add(), bn_cmp(), bn_cmp_abs(), bn_copy(), bn_div_rem(), bn_free, bn_is_zero(), bn_mul, bn_neg(), bn_new, bn_null, bn_set_dig(), bn_sqr, bn_srt(), bn_sub(), bn_zero(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_GT, RLC_LT, RLC_THROW, and RLC_TRY.
Referenced by ep_curve_set_endom().
bn_gcd_ext_dig()
void bn_gcd_ext_dig (bn_t c, bn_t d, bn_t e, const bn_t a, dig_t b)
Computes the extended greatest common divisor of a multiple precision integer and a digit.
Parameters
[out] c - the result.
[out] d - the cofactor of the first operand, can be NULL.
[out] e - the cofactor of the second operand, can be NULL.
[in] a - the multiple precision integer.
[in] b - the digit.
Definition at line 973 of file relic_bn_gcd.c.
References bn_abs(), bn_copy(), bn_div_rem(), bn_free, bn_gcd_dig(), bn_is_zero(), bn_mul, bn_mul_dig(), bn_new, bn_null, bn_set_dig(), bn_sub(), bn_zero(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by bn_gcd_ext_lehme(), and bn_gcd_lehme().
bn_lcm()
void bn_lcm (bn_t c, const bn_t a, const bn_t b)
Computes the last common multiple of two multiple precision integers. Computes c = lcm(a, b).
Parameters
[out] c - the result.
[in] a - the first integer.
[in] b - the second integer.
Definition at line 38 of file relic_bn_lcm.c.
References bn_cmp_abs(), bn_div(), bn_free, bn_gcd, bn_mul, bn_new, bn_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_LT, RLC_POS, RLC_THROW, and RLC_TRY.
bn_smb_leg()
int bn_smb_leg (const bn_t a, const bn_t b)
Computes the Legendre symbol c = (a|b), b prime.
Parameters
[in] a - the first parameter.
[in] b - the second parameter.
Exceptions
ERR_NO_VALID - if there input is negative.
Returns
the result.
Definition at line 38 of file relic_bn_smb.c.
References bn_cmp(), bn_cmp_dig(), bn_free, bn_mxp, bn_new, bn_null, bn_rsh(), bn_sign(), bn_sub(), bn_sub_dig(), ERR_CAUGHT, ERR_NO_VALID, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
bn_smb_jac()
int bn_smb_jac (const bn_t a, const bn_t b)
Computes the Jacobi symbol c = (a|b).
Parameters
[in] a - the first parameter.
[in] b - the second parameter.
Exceptions
ERR_NO_VALID - if there input is even or negative.
Returns
the result.
Definition at line 79 of file relic_bn_smb.c.
References arch_lzcnt(), arch_tzcnt(), bn_add(), bn_cmp_dig(), bn_copy(), bn_free, bn_grow(), bn_is_even(), bn_is_zero(), bn_mod, bn_mul_dig(), bn_neg(), bn_new, bn_null, bn_rsh(), bn_sign(), dv_zero(), ERR_CAUGHT, ERR_NO_VALID, RLC_CATCH_ANY, RLC_DIG, RLC_EQ, RLC_FINALLY, RLC_HMASK, RLC_LMASK, RLC_MAX, RLC_MIN, RLC_NEG, RLC_SWAP, RLC_THROW, and RLC_TRY.
Referenced by bn_is_prime_solov().
bn_is_prime()
int bn_is_prime (const bn_t a)
Tests if a number is a probable prime.
Parameters
[in] a - the multiple precision integer to test.
Returns
1 if a is prime, 0 otherwise.
Definition at line 173 of file relic_bn_prime.c.
References bn_is_prime_basic(), and bn_is_prime_rabin().
Referenced by bn_gen_prime_basic(), bn_gen_prime_factor(), bn_gen_prime_safep(), bn_gen_prime_stron(), cp_bdpe_gen(), cp_rsapsi_ans(), cp_rsapsi_ask(), cp_shipsi_ans(), cp_shipsi_ask(), and fp_param_set_any_dense().
bn_is_prime_basic()
int bn_is_prime_basic (const bn_t a)
Tests if a number is prime using a series of trial divisions.
Parameters
[in] a - the number to test.
Returns
1 if a is a probable prime, 0 otherwise.
Definition at line 190 of file relic_bn_prime.c.
References BASIC_TESTS, bn_cmp_dig(), bn_mod_dig(), primes, and RLC_EQ.
Referenced by bn_is_prime(), and cp_bdpe_gen().
bn_is_prime_rabin()
int bn_is_prime_rabin (const bn_t a)
Tests if a number a > 2 is prime using the Miller-Rabin test with probability 2^(-80) of error.
Parameters
[in] a - the number to test.
Returns
1 if a is a probable prime, 0 otherwise.
Definition at line 211 of file relic_bn_prime.c.
References bn_bits(), bn_cmp(), bn_cmp_dig(), bn_copy(), bn_free, bn_is_even(), bn_is_zero(), bn_mod, bn_mxp, bn_new, bn_null, bn_rsh(), bn_set_dig(), bn_sqr, bn_sub_dig(), ERR_CAUGHT, primes, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_LT, RLC_THROW, and RLC_TRY.
Referenced by bn_is_prime().
bn_is_prime_solov()
int bn_is_prime_solov (const bn_t a)
Tests if a number a > 2 is prime using the Solovay-Strassen test with probability 2^(-80) of error.
Parameters
[in] a - the number to test.
Returns
1 if a is a probable prime, 0 otherwise.
Definition at line 336 of file relic_bn_prime.c.
References bn_bits(), bn_cmp(), bn_cmp_dig(), bn_copy(), bn_free, bn_mod, bn_mxp, bn_neg(), bn_new, bn_null, bn_rand(), bn_rsh(), bn_set_dig(), bn_smb_jac(), bn_sub_dig(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_LT, RLC_POS, RLC_THROW, and RLC_TRY.
bn_gen_prime_basic()
void bn_gen_prime_basic (bn_t a, size_t bits)
Generates a probable prime number.
Parameters
[out] a - the result.
[in] bits - the length of the number in bits.
Definition at line 404 of file relic_bn_prime.c.
References bn_bits(), bn_is_prime(), bn_rand(), and RLC_POS.
bn_gen_prime_safep()
void bn_gen_prime_safep (bn_t a, size_t bits)
Generates a probable prime number a with (a - 1)/2 also prime.
Parameters
[out] a - the result.
[in] bits - the length of the number in bits.
Definition at line 419 of file relic_bn_prime.c.
References bn_add_dig(), bn_bits(), bn_is_prime(), bn_lsh(), bn_rand(), bn_rsh(), bn_sub_dig(), and RLC_POS.
bn_gen_prime_stron()
void bn_gen_prime_stron (bn_t a, size_t bits)
Generates a probable prime number with (a - 1)/2, (a + 1)/2 and ((a - 1)/2 - 1)/2 also prime.
Parameters
[out] a - the result.
[in] bits - the length of the number in bits.
Definition at line 443 of file relic_bn_prime.c.
References bn_add(), bn_add_dig(), bn_bits(), bn_dbl(), bn_free, bn_is_prime(), bn_mul, bn_mul_dig(), bn_mxp, bn_new, bn_null, bn_rand(), bn_sub_dig(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_POS, RLC_THROW, and RLC_TRY.
bn_gen_prime_factor()
int bn_gen_prime_factor (bn_t a, bn_t b, size_t abits, size_t bbits)
Generates a probable prime number b, with (b-1) divisible by a probable large prime a.
Parameters
[out] a - the prime factor of (b-1).
[out] b - the prime result b.
[in] abits - the length of the factor a in bits.
[in] bbits - the length of the result in bits.
Definition at line 522 of file relic_bn_prime.c.
References bn_add(), bn_add_dig(), bn_bits(), bn_free, bn_gen_prime, bn_is_prime(), bn_lsh(), bn_mul, bn_new, bn_null, bn_rand(), bn_set_dig(), RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, RLC_POS, and RLC_TRY.
Referenced by cp_shpe_gen().
bn_factor()
int bn_factor (bn_t c, const bn_t a)
Tries to factorize an integer using Pollard (p - 1) factoring algorithm. The maximum length of the returned factor is 16 bits.
Parameters
[out] c - the resulting factor.
[in] a - the integer to fatorize.
Returns
1 if a factor is found and stored into c; 0 otherwise.
Definition at line 38 of file relic_bn_factor.c.
References bn_cmp(), bn_cmp_dig(), bn_copy(), bn_free, bn_gcd, bn_is_even(), bn_mxp, bn_new, bn_null, bn_set_dig(), bn_sub_dig(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_GT, RLC_LT, RLC_THROW, and RLC_TRY.
bn_is_factor()
int bn_is_factor (bn_t c, const bn_t a)
Tests if an integer divides other integer.
Parameters
[in] c - the factor.
[in] a - the integer.
Returns
1 if the first integer is a factor; 0 otherwise.
Definition at line 85 of file relic_bn_factor.c.
References bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
bn_rec_win()
void bn_rec_win (uint8_t * win, size_t * len, const bn_t k, size_t w)
Recodes a positive integer in window form. If a negative integer is given instead, its absolute value is taken.
Parameters
[out] win - the recoded integer.
[out] len - the number of bytes written.
[in] k - the integer to recode.
[in] w - the window size in bits.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 94 of file relic_bn_rec.c.
References bn_bits(), ERR_NO_BUFFER, get_bits(), RLC_CEIL, and RLC_THROW.
Referenced by eb_mul_sim_trick(), ed_mul_sim_trick(), ep2_mul_sim_trick(), ep3_mul_sim_trick(), ep4_mul_sim_trick(), ep8_mul_sim_trick(), and ep_mul_sim_trick().
bn_rec_slw()
void bn_rec_slw (uint8_t * win, size_t * len, const bn_t k, size_t w)
Recodes a positive integer in sliding window form. If a negative integer is given instead, its absolute value is taken.
Parameters
[out] win - the recoded integer.
[out] len - the number of bytes written.
[in] k - the integer to recode.
[in] w - the window size in bits.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 115 of file relic_bn_rec.c.
References bn_bits(), bn_get_bit(), ERR_NO_BUFFER, get_bits(), RLC_MAX, and RLC_THROW.
Referenced by bn_mxp_slide(), ed_mul_slide(), ep2_mul_slide(), ep3_mul_slide(), ep4_mul_slide(), ep8_mul_slide(), ep_mul_slide(), fb_exp_slide(), and fp_exp_slide().
bn_rec_naf()
void bn_rec_naf (int8_t * naf, size_t * len, const bn_t k, size_t w)
Recodes a positive integer in width-w Non-Adjacent Form. If a negative integer is given instead, its absolute value is taken.
Parameters
[out] naf - the recoded integer.
[out] len - the number of bytes written.
[in] k - the integer to recode.
[in] w - the window size in bits.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 146 of file relic_bn_rec.c.
References bn_abs(), bn_add_dig(), bn_bits(), bn_free, bn_get_dig(), bn_hlv(), bn_is_even(), bn_is_zero(), bn_new, bn_null, bn_sub_dig(), ERR_CAUGHT, ERR_NO_BUFFER, RLC_CATCH_ANY, RLC_FINALLY, RLC_MASK, RLC_THROW, and RLC_TRY.
Referenced by eb_mul_basic(), eb_mul_fix_plain(), eb_mul_halve(), eb_mul_lnaf_imp(), eb_mul_rnaf_imp(), eb_mul_sim_plain(), ed_mul_basic(), ed_mul_dig(), ed_mul_fix_plain(), ed_mul_naf_imp(), ed_mul_sim_lot(), ed_mul_sim_plain(), ep2_mul_basic(), ep2_mul_dig(), ep2_mul_fix_plain(), ep2_mul_gls_imp(), ep2_mul_naf_imp(), ep2_mul_sim_endom(), ep2_mul_sim_lot(), ep2_mul_sim_plain(), ep3_mul_basic(), ep3_mul_dig(), ep3_mul_fix_plain(), ep3_mul_naf_imp(), ep3_mul_sim_lot(), ep3_mul_sim_plain(), ep4_mul_basic(), ep4_mul_dig(), ep4_mul_fix_ordin(), ep4_mul_gls_imp(), ep4_mul_naf_imp(), ep4_mul_sim_lot(), ep4_mul_sim_plain(), ep8_mul_basic(), ep8_mul_dig(), ep8_mul_fix_ordin(), ep8_mul_gls_imp(), ep8_mul_naf_imp(), ep8_mul_sim_lot(), ep8_mul_sim_plain(), ep_mul_basic(), ep_mul_dig(), ep_mul_fix_plain(), ep_mul_glv_imp(), ep_mul_naf_imp(), ep_mul_sim_endom(), ep_mul_sim_lot_endom(), ep_mul_sim_lot_plain(), ep_mul_sim_plain(), fp12_exp_cyc(), fp12_exp_dig(), fp16_exp_cyc(), fp16_exp_cyc_sim(), fp16_exp_dig(), fp18_exp_cyc(), fp18_exp_cyc_sim(), fp18_exp_dig(), fp24_exp_cyc(), fp24_exp_cyc_sim(), fp24_exp_dig(), fp2_exp_cyc(), fp2_exp_cyc_sim(), fp48_exp_cyc(), fp48_exp_cyc_sim(), fp48_exp_dig(), fp54_exp_dig(), fp8_exp_cyc(), fp8_exp_cyc_sim(), fp8_exp_dig(), fp_prime_set_pairf(), g1_is_valid(), gt_exp_dig(), gt_exp_gls_naf(), pp_mil_k12(), pp_mil_k16(), pp_mil_k18(), pp_mil_k24(), pp_mil_k48(), pp_mil_k54(), and pp_mil_k8().
bn_rec_tnaf()
void bn_rec_tnaf (int8_t * tnaf, size_t * len, const bn_t k, int8_t u, size_t m, size_t w)
Recodes a positive integer in width-w \tau-NAF. If a negative integer is given instead, its absolute value is taken.
Parameters
[out] tnaf - the recoded integer.
[out] len - the number of bytes written.
[in] k - the integer to recode.
[in] u - the u curve parameter.
[in] m - the extension degree of the binary field.
[in] w - the window size in bits.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 425 of file relic_bn_rec.c.
References bn_abs(), bn_add(), bn_add_dig(), bn_bits(), bn_copy(), bn_free, bn_hlv(), bn_is_zero(), bn_new, bn_null, bn_rec_tnaf_get(), bn_rec_tnaf_mod(), bn_sign(), bn_sub(), bn_sub_dig(), ERR_CAUGHT, ERR_NO_BUFFER, RLC_CATCH_ANY, RLC_FINALLY, RLC_MASK, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by eb_mul_fix_kbltz(), eb_mul_ltnaf_imp(), eb_mul_rtnaf_imp(), and eb_mul_sim_kbltz().
bn_rec_rtnaf()
void bn_rec_rtnaf (int8_t * tnaf, size_t * len, const bn_t k, int8_t u, size_t m, size_t w)
Recodes a positive integer in regular fixed-length width-w \tau-NAF. If a negative integer is given instead, its absolute value is taken.
Parameters
[out] tnaf - the recoded integer.
[out] len - the number of bytes written.
[in] k - the integer to recode.
[in] u - the u curve parameter.
[in] m - the extension degree of the binary field.
[in] w - the window size in bits.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 556 of file relic_bn_rec.c.
References bn_abs(), bn_add(), bn_add_dig(), bn_bits(), bn_copy(), bn_free, bn_hlv(), bn_new, bn_null, bn_rec_tnaf_get(), bn_rec_tnaf_mod(), bn_sign(), bn_sub(), bn_sub_dig(), ERR_CAUGHT, ERR_NO_BUFFER, RLC_CATCH_ANY, RLC_CEIL, RLC_FINALLY, RLC_MASK, RLC_NEG, RLC_THROW, and RLC_TRY.
bn_rec_tnaf_get()
void bn_rec_tnaf_get (uint8_t * t, int8_t * beta, int8_t * gama, int8_t u, size_t w)
Write the constants needed for \tau-NAF recoding as a set of \alpha_u = \beta_u + \gamma_u * \tau elements.
Parameters
[out] t - the integer corresponding to \tau.
[out] beta - the first coefficients of the constants.
[out] gama - the second coefficients of the constants.
[in] u - the u curve parameter.
[in] w - the window size in bits.
Definition at line 220 of file relic_bn_rec.c.
Referenced by bn_rec_rtnaf(), and bn_rec_tnaf().
bn_rec_tnaf_mod()
void bn_rec_tnaf_mod (bn_t r0, bn_t r1, const bn_t k, int u, size_t m)
Computes the partial reduction k partmod d = r0 + r1 * t, where d = (t^m - 1)/(t - 1).
Parameters
[out] r0 - the first half of the result.
[out] r1 - the second half of the result.
[in] k - the number to reduce.
[in] u - the u curve parameter.
[in] m - the extension degree of the binary field.
Definition at line 353 of file relic_bn_rec.c.
References bn_abs(), bn_add(), bn_dbl(), bn_free, bn_hlv(), bn_is_even(), bn_neg(), bn_new, bn_null, bn_set_dig(), bn_sub(), bn_sub_dig(), bn_zero(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by bn_rec_rtnaf(), and bn_rec_tnaf().
bn_rec_reg()
void bn_rec_reg (int8_t * naf, size_t * len, const bn_t k, size_t n, size_t w)
Recodes a positive integer in regular fixed-length width-w NAF. If a negative integer is given instead, its absolute value is taken.
Parameters
[out] naf - the recoded integer.
[out] len - the number of bytes written.
[in] k - the integer to recode.
[in] n - the length of the recoding.
[in] w - the window size in bits.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 699 of file relic_bn_rec.c.
References bn_abs(), bn_free, bn_get_dig(), bn_hlv(), bn_new, bn_null, bn_rsh(), ERR_CAUGHT, ERR_NO_BUFFER, RLC_CATCH_ANY, RLC_CEIL, RLC_FINALLY, RLC_MASK, RLC_THROW, and RLC_TRY.
Referenced by ed_mul_reg_imp(), ep2_mul_reg_imp(), ep3_mul_reg_imp(), ep4_mul_reg_imp(), ep8_mul_reg_imp(), ep_mul_reg_glv(), ep_mul_reg_imp(), and gt_exp_reg_gls().
bn_rec_jsf()
void bn_rec_jsf (int8_t * jsf, size_t * len, const bn_t k, const bn_t l)
Recodes of a pair of positive integers in Joint Sparse Form. If negative integers are given instead, takes their absolute value.
Parameters
[out] jsf - the recoded pair of integers.
[out] len - the number of bytes written.
[in] k - the first integer to recode.
[in] l - the second integer to recode.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 752 of file relic_bn_rec.c.
References bn_abs(), bn_bits(), bn_free, bn_get_dig(), bn_hlv(), bn_is_zero(), bn_new, bn_null, ERR_CAUGHT, ERR_NO_BUFFER, RLC_CATCH_ANY, RLC_FINALLY, RLC_MASK, RLC_MAX, RLC_THROW, and RLC_TRY.
Referenced by eb_mul_sim_joint(), ed_mul_sim_joint(), ep2_mul_sim_joint(), ep3_mul_sim_joint(), ep4_mul_sim_joint(), ep8_mul_sim_joint(), and ep_mul_sim_joint().
bn_rec_glv()
void bn_rec_glv (bn_t k0, bn_t k1, const bn_t k, const bn_t n, const bn_t v1[], const bn_t v2[])
Recodes a positive integer into two parts k0,k1 such that k = k0 + phi(k1), where phi is an efficient curve endomorphism. If a negative integer is given instead, its absolute value is taken.
Parameters
[out] k0 - the first part of the result.
[out] k1 - the second part of the result.
[in] k - the integer to recode.
[in] n - the group order.
[in] v1 - the set of parameters v1 for the GLV method.
[in] v2 - the set of parameters v2 for the GLV method.
bn_rec_frb()
void bn_rec_frb (bn_t * ki, int sub, const bn_t k, const bn_t x, const bn_t n, int cof)
Recodes a scalar in subscalars according to Frobenius endomorphism.
Parameters
[out] ki - the recoded subscalars.
[in] sub - the number of subscalars.
[in] k - the scalar to recode.
[in] x - the elliptic curve parameter.
[in] n - the elliptic curve group order.
[in] cof - flag to indicate if it is a curve with cofactor 1.
Definition at line 936 of file relic_bn_rec.c.
References bn_abs(), bn_add(), bn_add_dig(), bn_bits(), bn_copy(), bn_dbl(), bn_div(), bn_free, bn_mod, bn_mul, bn_mul_dig(), bn_neg(), bn_new, bn_null, bn_rsh(), bn_sign(), bn_sqr, bn_sub(), bn_sub_dig(), bn_zero(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_POS, RLC_THROW, and RLC_TRY.
Referenced by ep2_mul_gls_imp(), ep2_mul_reg_gls(), ep2_mul_sim_endom(), ep2_mul_sim_lot(), ep3_mul_gls_imp(), ep3_mul_reg_gls(), ep3_mul_sim_lot(), ep4_mul_gls_imp(), ep4_mul_reg_gls(), ep4_mul_sim_lot(), ep8_mul_gls_imp(), ep8_mul_reg_gls(), ep8_mul_sim_lot(), fp12_exp_cyc_sim(), gt_exp_gls_naf(), gt_exp_gls_sac(), gt_exp_reg_gls(), and gt_exp_reg_sac().
bn_rec_sac()
void bn_rec_sac (int8_t * b, size_t * len, bn_t * k, size_t c, size_t m, size_t n)
Recodes subscalars in the signed aligned column representation..
Parameters
[out] b - the recoded subscalars.
[in] len - the length in bytes of the recoding.
[in] k - the subscalars to recode.
[in] c - the splitting factor.
[in] m - the number of subscalars to recode.
[in] n - the bit length of the group order.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 879 of file relic_bn_rec.c.
References bn_add_dig(), bn_bits(), bn_copy(), bn_free, bn_get_bit(), bn_hlv(), bn_new, bn_null, EP_BN, ep_curve_is_pairf(), ERR_CAUGHT, ERR_NO_BUFFER, ERR_NO_MEMORY, fp_prime_get_par(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_CEIL, RLC_FINALLY, RLC_FREE, RLC_MAX, RLC_THROW, and RLC_TRY.
Referenced by ep2_mul_reg_gls(), ep3_mul_gls_imp(), ep3_mul_reg_gls(), ep4_mul_reg_gls(), ep8_mul_reg_gls(), gt_exp_gls_sac(), and gt_exp_reg_sac().
bn_lag()
void bn_lag (bn_t * c, const bn_t * a, const bn_t b, size_t n)
Computes the coefficients of the polynomial representing the Lagrange interpolation for a modulus and a given set of roots. Computes c(x) = \prod_{0 <= i < n}(x - ai) mod q.
Parameters
[out] c - the coefficients of the polynomial.
[in] a - the set of roots.
[in] b - the modulus.
[in] n - the number of roots to interpolate.
Definition at line 39 of file relic_bn_lag.c.
References bn_copy(), bn_free, bn_mod, bn_mul, bn_new, bn_null, bn_set_dig(), bn_sub(), bn_zero(), ERR_CAUGHT, ERR_NO_MEMORY, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by cp_pbpsi_ask().
bn_evl()
void bn_evl (bn_t c, const bn_t * a, const bn_t x, const bn_t b, size_t n)
Evaluates an interpolated n-degree polynomial over a value in a modular way, given the (n+1) coefficients of the polynomial and the modulus. Computes c = a(x) mod q.
Parameters
[out] c - the result of the evaluation.
[in] a - the coefficients of the polynomial.
[in] x - the value to evaluate.
[in] b - the modulus.
[in] n - the degree of the polynomial.
Definition at line 87 of file relic_bn_lag.c.
References bn_add(), bn_mod, bn_mul, and bn_zero().
Referenced by mpc_sss_gen().