RELIC: src/pp/relic_pp_map_k2.c File Reference
relic_pp_map_k2.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_util.h"
Functions
static void pp_mil_k2 (fp2_t r, ep_t *t, ep_t *p, ep_t *q, int m, bn_t a)
static void pp_mil_lit_k2 (fp2_t r, ep_t *t, ep_t *p, ep_t *q, int m, bn_t a)
void pp_map_tatep_k2 (fp2_t r, const ep_t p, const ep_t q)
void pp_map_sim_tatep_k2 (fp2_t r, const ep_t *p, const ep_t *q, int m)
void pp_map_weilp_k2 (fp2_t r, const ep_t p, const ep_t q)
void pp_map_sim_weilp_k2 (fp2_t r, const ep_t *p, const ep_t *q, int m)
Detailed Description
Implementation of pairing computation for curves with embedding degree 2.
Definition in file relic_pp_map_k2.c.
Function Documentation
pp_mil_k2()
static void pp_mil_k2 (fp2_t r, ep_t * t, ep_t * p, ep_t * q, int m, bn_t a) static
Compute the Miller loop for pairings of type G_2 x G_1 over the bits of a given parameter.
Parameters
[out] r - the result.
[out] t - the resulting point.
[in] p - the first pairing argument in affine coordinates.
[in] q - the second pairing argument in affine coordinates.
[in] m - the number of pairings to evaluate.
[in] a - the loop parameter.
Definition at line 51 of file relic_pp_map_k2.c.
References bn_bits(), bn_get_bit(), ep_copy(), ep_free, ep_neg(), ep_new, ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp2_free, fp2_mul, fp2_new, fp2_null, fp2_sqr, fp2_zero(), pp_add_k2, pp_dbl_k2, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by pp_map_sim_tatep_k2(), pp_map_sim_weilp_k2(), pp_map_tatep_k2(), and pp_map_weilp_k2().
pp_mil_lit_k2()
static void pp_mil_lit_k2 (fp2_t r, ep_t * t, ep_t * p, ep_t * q, int m, bn_t a) static
Compute the Miller loop for pairings of type G_1 x G_2 over the bits of a given parameter.
Parameters
[out] r - the result.
[out] t - the resulting point.
[in] p - the first pairing argument in affine coordinates.
[in] q - the second pairing argument in affine coordinates.
[in] a - the loop parameter.
Definition at line 105 of file relic_pp_map_k2.c.
References bn_bits(), bn_get_bit(), ep_copy(), ep_neg(), ep_new, ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp2_free, fp2_mul, fp2_new, fp2_null, fp2_sqr, fp_copy(), pp_add_k2, pp_dbl_k2, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by pp_map_sim_weilp_k2(), and pp_map_weilp_k2().
pp_map_tatep_k2()
void pp_map_tatep_k2 (fp2_t r, const ep_t p, const ep_t q)
Computes the Tate pairing of two points in a parameterized elliptic curve with embedding degree 2.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 161 of file relic_pp_map_k2.c.
References bn_free, bn_new, bn_null, bn_sub_dig(), ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, fp2_set_dig(), pp_exp_k2(), pp_mil_k2(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_map_sim_tatep_k2()
void pp_map_sim_tatep_k2 (fp2_t r, const ep_t * p, const ep_t * q, int m)
Computes the Tate multi-pairing in a parameterized elliptic curve with embedding degree 2.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 197 of file relic_pp_map_k2.c.
References bn_free, bn_new, bn_null, bn_sub_dig(), ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp2_set_dig(), pp_exp_k2(), pp_mil_k2(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
pp_map_weilp_k2()
void pp_map_weilp_k2 (fp2_t r, const ep_t p, const ep_t q)
Computes the Weil pairing of two points in a parameterized elliptic curve with embedding degree 2.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 255 of file relic_pp_map_k2.c.
References bn_free, bn_new, bn_null, bn_sub_dig(), ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, fp2_free, fp2_inv(), fp2_inv_cyc(), fp2_mul, fp2_new, fp2_null, fp2_set_dig(), pp_mil_k2(), pp_mil_lit_k2(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_map_sim_weilp_k2()
void pp_map_sim_weilp_k2 (fp2_t r, const ep_t * p, const ep_t * q, int m)
Computes the Weil multi-pairing in a parameterized elliptic curve with embedding degree 2.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 309 of file relic_pp_map_k2.c.
References bn_free, bn_new, bn_null, bn_sub_dig(), ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp2_free, fp2_inv(), fp2_inv_cyc(), fp2_mul, fp2_new, fp2_null, fp2_set_dig(), pp_mil_k2(), pp_mil_lit_k2(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.