RELIC: src/pp/relic_pp_exp_k48.c File Reference
relic_pp_exp_k48.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_util.h"
Functions
void pp_exp_k48 (fp48_t c, fp48_t a)
Detailed Description
Implementation of the final exponentiation for curves of embedding degree 48.
Definition in file relic_pp_exp_k48.c.
Function Documentation
pp_exp_k48()
void pp_exp_k48 (fp48_t c, fp48_t a)
Computes the final exponentiation for a pairing defined over curves of embedding degree 48. Computes c = a^(p^48 - 1)/r.
Parameters
[out] c - the result.
[in] a - the extension field element to exponentiate.
Definition at line 40 of file relic_pp_exp_k48.c.
References bn_free, bn_new, bn_null, bn_sign(), ERR_CAUGHT, fp48_conv_cyc(), fp48_exp_cyc_sps(), fp48_frb(), fp48_free, fp48_inv_cyc(), fp48_mul, fp48_new, fp48_null, fp48_sqr_cyc, fp_prime_get_par(), fp_prime_get_par_sps(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by gt_rand(), pp_map_k48(), and pp_map_sim_k48().