RELIC: src/fb/relic_fb_param.c File Reference
relic_fb_param.c File Reference
Binary field arithmetic
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "relic_core.h"
#include "relic_conf.h"
#include "relic_dv.h"
#include "relic_fb.h"
#include "relic_util.h"
Functions
int fb_param_get (void)
void fb_param_set (int param)
void fb_param_set_any (void)
void fb_param_print (void)
Detailed Description
Implementation of the binary field modulus manipulation.
Definition in file relic_fb_param.c.
Function Documentation
fb_param_get()
int fb_param_get (void)
Definition at line 46 of file relic_fb_param.c.
References core_get(), and _ctx_t::fb_id.
fb_param_set()
void fb_param_set (int param)
Assigns a standard irreducible polynomial as modulo of the binary field.
Parameters
[in] param - the standardized polynomial identifier.
Definition at line 50 of file relic_fb_param.c.
References core_get(), ERR_NO_VALID, _ctx_t::fb_id, fb_poly_set_penta(), fb_poly_set_trino(), NIST_163, NIST_233, NIST_283, NIST_409, NIST_571, PENTA_128, PENTA_131, PENTA_251, PENTA_271, PENTA_64, PENTA_8, RLC_THROW, SECG_239, SQRT_163, SQRT_233, SQRT_239, SQRT_251, SQRT_283, SQRT_571, TRINO_113, TRINO_1223, TRINO_127, TRINO_193, TRINO_257, TRINO_271, TRINO_353, TRINO_367, TRINO_439, and TRINO_511.
Referenced by fb_param_set_any().
fb_param_set_any()
void fb_param_set_any (void)
Configures some finite field parameters for the current security level.
Definition at line 147 of file relic_fb_param.c.
References ERR_NO_FIELD, fb_param_set(), NIST_163, NIST_233, NIST_283, NIST_409, NIST_571, PENTA_128, PENTA_131, PENTA_251, PENTA_271, PENTA_64, PENTA_8, RLC_THROW, SECG_239, SQRT_163, SQRT_233, SQRT_239, SQRT_251, SQRT_283, SQRT_571, TRINO_113, TRINO_1223, TRINO_127, TRINO_193, TRINO_257, TRINO_271, TRINO_353, TRINO_367, TRINO_439, and TRINO_511.
fb_param_print()
void fb_param_print (void)
Prints the currently configured irreducible polynomial.
Definition at line 243 of file relic_fb_param.c.
References fb_poly_get_rdc(), RLC_FB_BITS, util_banner, and util_print.