RELIC: src/bn/relic_bn_mod.c File Reference
relic_bn_mod.c File Reference
Multiple precision integer arithmetic
#include "relic_core.h"
#include "relic_bn_low.h"
Functions
void bn_mod_2b (bn_t c, const bn_t a, int b)
void bn_mod_dig (dig_t *c, const bn_t a, dig_t b)
void bn_mod_basic (bn_t c, const bn_t a, const bn_t m)
void bn_mod_pre_barrt (bn_t u, const bn_t m)
void bn_mod_barrt (bn_t c, const bn_t a, const bn_t m, const bn_t u)
void bn_mod_pre_monty (bn_t u, const bn_t m)
void bn_mod_monty_conv (bn_t c, const bn_t a, const bn_t m)
void bn_mod_monty_back (bn_t c, const bn_t a, const bn_t m)
void bn_mod_monty_basic (bn_t c, const bn_t a, const bn_t m, const bn_t u)
void bn_mod_monty_comba (bn_t c, const bn_t a, const bn_t m, const bn_t u)
void bn_mod_pre_pmers (bn_t u, const bn_t m)
void bn_mod_pmers (bn_t c, const bn_t a, const bn_t m, const bn_t u)
Detailed Description
Implementation of the multiple precision integer modular reduction functions.
Definition in file relic_bn_mod.c.
Function Documentation
bn_mod_2b()
void bn_mod_2b (bn_t c, const bn_t a, int b)
Reduces a multiple precision integer modulo a power of 2. Computes c = a mod 2^b.
Parameters
[out] c - the result.
[in] a - the dividend.
[in] b - the exponent of the divisor.
Definition at line 40 of file relic_bn_mod.c.
References bn_copy(), bn_trim(), bn_zero(), RLC_DIG, RLC_MASK, and RLC_RIP.
Referenced by bn_mod_barrt(), bn_mod_pmers(), cp_ecmqv_key(), cp_ghpe_gen(), cp_rabin_dec(), cp_rabin_enc(), cp_rabin_gen(), eb_map(), and pad_pkcs2().
bn_mod_dig()
void bn_mod_dig (dig_t * c, const bn_t a, dig_t b)
Reduces a multiple precision integer modulo a digit. Computes c = a mod b.
Parameters
[out] c - the result.
[in] a - the dividend.
[in] b - the divisor.
Definition at line 67 of file relic_bn_mod.c.
References bn_div_rem_dig().
Referenced by bn_gcd_dig(), bn_is_prime_basic(), fp_crt(), fp_prime_set(), g2_is_valid(), and gt_is_valid().
bn_mod_basic()
void bn_mod_basic (bn_t c, const bn_t a, const bn_t m)
Reduces a multiple precision integer modulo an integer using straightforward division.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to reduce.
[in] m - the modulus.
Definition at line 71 of file relic_bn_mod.c.
References bn_div_rem().
bn_mod_pre_barrt()
void bn_mod_pre_barrt (bn_t u, const bn_t m)
Computes the reciprocal of the modulus to be used in the Barrett modular reduction algorithm.
Parameters
[out] u - the result.
[in] m - the modulus.
Definition at line 77 of file relic_bn_mod.c.
References bn_div(), bn_is_zero(), bn_set_2b(), bn_sign(), ERR_NO_VALID, RLC_DIG, RLC_POS, and RLC_THROW.
bn_mod_barrt()
void bn_mod_barrt (bn_t c, const bn_t a, const bn_t m, const bn_t u)
Reduces a multiple precision integer modulo a positive integer using Barrett reduction.
Parameters
[out] c - the result.
[in] a - the the multiple precision integer to reduce.
[in] m - the modulus.
[in] u - the reciprocal of the modulus.
Definition at line 87 of file relic_bn_mod.c.
References bn_abs(), bn_add(), bn_cmp(), bn_cmp_abs(), bn_copy(), bn_free, bn_grow(), bn_is_zero(), bn_lsh(), bn_mod, bn_mod_2b(), bn_mul, bn_muld_low(), bn_new, bn_null, bn_rsh(), bn_set_dig(), bn_sign(), bn_sub(), bn_trim(), bn_zero(), ERR_CAUGHT, ERR_NO_VALID, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_LT, RLC_NEG, RLC_POS, RLC_THROW, and RLC_TRY.
bn_mod_pre_monty()
void bn_mod_pre_monty (bn_t u, const bn_t m)
Computes the reciprocal of the modulus to be used in the Montgomery reduction algorithm.
Parameters
[out] u - the result.
[in] m - the modulus.
Exceptions
ERR_NO_VALID - if the modulus is even.
Definition at line 176 of file relic_bn_mod.c.
References bn_is_even(), bn_set_dig(), bn_sign(), ERR_NO_VALID, RLC_POS, and RLC_THROW.
Referenced by bn_mod_monty_back(), and fp_prime_set().
bn_mod_monty_conv()
void bn_mod_monty_conv (bn_t c, const bn_t a, const bn_t m)
Converts a multiple precision integer to Montgomery form.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to convert.
[in] m - the modulus.
Definition at line 199 of file relic_bn_mod.c.
References bn_is_even(), bn_lsh(), bn_mod, bn_sign(), ERR_NO_VALID, RLC_DIG, RLC_POS, and RLC_THROW.
Referenced by bn_mxp_basic(), bn_mxp_dig(), bn_mxp_monty(), bn_mxp_sim_few(), bn_mxp_slide(), and fp_inv_monty().
bn_mod_monty_back()
void bn_mod_monty_back (bn_t c, const bn_t a, const bn_t m)
Converts a multiple precision integer from Montgomery form.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to convert.
[in] m - the modulus.
Definition at line 210 of file relic_bn_mod.c.
References bn_free, bn_is_even(), bn_mod_monty, bn_mod_pre_monty(), bn_new, bn_null, bn_sign(), ERR_CAUGHT, ERR_NO_VALID, RLC_CATCH_ANY, RLC_FINALLY, RLC_POS, RLC_THROW, and RLC_TRY.
Referenced by bn_mxp_basic(), bn_mxp_dig(), bn_mxp_monty(), bn_mxp_sim_few(), bn_mxp_slide(), and fp_inv_monty().
bn_mod_monty_basic()
void bn_mod_monty_basic (bn_t c, const bn_t a, const bn_t m, const bn_t u)
Reduces a multiple precision integer modulo a positive integer using Montgomery reduction with Schoolbook multiplication.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to reduce.
[in] m - the modulus.
[in] u - the reciprocal of the modulus.
Definition at line 233 of file relic_bn_mod.c.
References bn_addn_low(), bn_cmp_abs(), bn_copy(), bn_free, bn_is_even(), bn_mula_low(), bn_new_size, bn_null, bn_sign(), bn_sub(), bn_subn_low(), bn_trim(), bn_zero(), ERR_CAUGHT, ERR_NO_VALID, RLC_CATCH_ANY, RLC_FINALLY, RLC_LT, RLC_POS, RLC_THROW, and RLC_TRY.
bn_mod_monty_comba()
void bn_mod_monty_comba (bn_t c, const bn_t a, const bn_t m, const bn_t u)
Reduces a multiple precision integer modulo a positive integer using Montgomery reduction with Comba multiplication.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to reduce.
[in] m - the modulus.
[in] u - the reciprocal of the modulus.
Definition at line 282 of file relic_bn_mod.c.
References bn_cmp_abs(), bn_copy(), bn_free, bn_is_even(), bn_modn_low(), bn_new_size, bn_null, bn_sign(), bn_sub(), bn_trim(), bn_zero(), ERR_CAUGHT, ERR_NO_VALID, RLC_CATCH_ANY, RLC_FINALLY, RLC_LT, RLC_POS, RLC_THROW, and RLC_TRY.
bn_mod_pre_pmers()
void bn_mod_pre_pmers (bn_t u, const bn_t m)
Computes u if the modulus has the form 2^b - u.
Parameters
[out] u - the result.
[in] m - the modulus.
Definition at line 321 of file relic_bn_mod.c.
References bn_bits(), bn_is_zero(), bn_set_2b(), bn_sign(), bn_sub(), ERR_NO_VALID, RLC_POS, and RLC_THROW.
bn_mod_pmers()
void bn_mod_pmers (bn_t c, const bn_t a, const bn_t m, const bn_t u)
Reduces a multiple precision integer modulo a positive integer using pseudo-Mersenne modular reduction.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to reduce.
[in] m - the modulus.
[in] u - the auxiliar value derived from the modulus.
Definition at line 331 of file relic_bn_mod.c.
References bn_add(), bn_bits(), bn_cmp_abs(), bn_copy(), bn_free, bn_is_zero(), bn_mod_2b(), bn_mul, bn_mul_dig(), bn_new, bn_null, bn_rsh(), bn_sign(), bn_sub(), ERR_CAUGHT, ERR_NO_VALID, RLC_CATCH_ANY, RLC_FINALLY, RLC_LT, RLC_NEG, RLC_POS, RLC_THROW, and RLC_TRY.