RELIC: src/bn/relic_bn_srt.c File Reference
relic_bn_srt.c File Reference
Multiple precision integer arithmetic
#include "relic_core.h"
#include "relic_bn_low.h"
Functions
void bn_srt (bn_t c, bn_t a)
Detailed Description
Implementation of the multiple precision integer square root extraction.
Definition in file relic_bn_srt.c.
Function Documentation
bn_srt()
void bn_srt (bn_t c, bn_t a)
Extracts an approximate integer square-root of a multiple precision integer.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to extract.
Exceptions
ERR_NO_VALID - if the argument is negative.
Definition at line 39 of file relic_bn_srt.c.
References bn_add(), bn_bits(), bn_cmp(), bn_cmp_dig(), bn_copy(), bn_free, bn_hlv(), bn_new, bn_null, bn_set_2b(), bn_sign(), bn_sqr, bn_sub(), bn_zero(), ERR_CAUGHT, ERR_NO_VALID, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_GT, RLC_LT, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by bn_gcd_ext_mid().