RELIC: src/fpx/relic_fp54_mul.c File Reference
relic_fp54_mul.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
Functions
void fp54_mul_basic (fp54_t c, const fp54_t a, const fp54_t b)
void fp54_mul_lazyr (fp54_t c, const fp54_t a, const fp54_t b)
void fp54_mul_dxs (fp54_t c, const fp54_t a, const fp54_t b)
void fp54_mul_art (fp54_t c, const fp54_t a)
Detailed Description
Implementation of multiplication in a 54-degree extension of a prime field.
Definition in file relic_fp54_mul.c.
Function Documentation
fp54_mul_basic()
void fp54_mul_basic (fp54_t c, const fp54_t a, const fp54_t b)
Multiples two 54-extension field elements using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the 54-extension field element.
[in] b - the 54-extension field element.
Definition at line 42 of file relic_fp54_mul.c.
References ERR_CAUGHT, fp18_add(), fp18_copy(), fp18_free, fp18_mul, fp18_mul_art(), fp18_new, fp18_null, fp18_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp54_mul_lazyr()
void fp54_mul_lazyr (fp54_t c, const fp54_t a, const fp54_t b)
Multiples two 54-extension field elements using lazy reduction.
Parameters
[out] c - the result.
[in] a - the 54-extension field element.
[in] b - the 54-extension field element.
Definition at line 109 of file relic_fp54_mul.c.
References ERR_CAUGHT, fp18_add(), fp18_copy(), fp18_free, fp18_mul, fp18_mul_art(), fp18_new, fp18_null, fp18_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp54_mul_dxs()
void fp54_mul_dxs (fp54_t c, const fp54_t a, const fp54_t b)
Multiples a dense 54-extension field element by a sparse element using basic arithmetic. Computes C = A * B.
Parameters
[out] c - the result.
[in] a - the dense 54-extension field element.
[in] b - the sparse 54-extension field element.
Definition at line 175 of file relic_fp54_mul.c.
References ERR_CAUGHT, fp18_add(), fp18_copy(), fp18_free, fp18_mul, fp18_mul_art(), fp18_mul_dxs, fp18_new, fp18_null, fp18_sub(), fp9_add(), fp9_copy(), fp9_mul, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_mil_k54().
fp54_mul_art()
void fp54_mul_art (fp54_t c, const fp54_t a)
Multiplies a 54-extension field element by the adjoined root.
Parameters
[out] c - the result.
[in] a - the 54-extension field element to multiply.
Definition at line 243 of file relic_fp54_mul.c.
References ERR_CAUGHT, fp18_copy(), fp18_free, fp18_mul_art(), fp18_new, fp18_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.