RELIC: src/cp/relic_cp_rsa.c File Reference
relic_cp_rsa.c File Reference
Cryptographic protocols
#include "relic.h"
Macros
#define RSA_PAD_LEN (2 * RLC_MD_LEN + 2)
#define RSA_PUB (02)
#define RSA_PRV (01)
#define RSA_PAD (0xFF)
#define RSA_PSS (0xBC)
#define RSA_ENC 1
#define RSA_DEC 2
#define RSA_SIG 3
#define RSA_VER 4
#define RSA_ENC_FIN 5
#define RSA_SIG_FIN 6
#define RSA_SIG_HASH 7
#define RSA_VER_HASH 8
Functions
static int pad_pkcs2 (bn_t m, size_t *p_len, size_t m_len, size_t k_len, int operation)
int cp_rsa_gen (rsa_t pub, rsa_t prv, size_t bits)
int cp_rsa_enc (uint8_t *out, size_t *out_len, const uint8_t *in, size_t in_len, const rsa_t pub)
int cp_rsa_dec (uint8_t *out, size_t *out_len, const uint8_t *in, size_t in_len, const rsa_t prv)
int cp_rsa_sig (uint8_t *sig, size_t *sig_len, const uint8_t *msg, size_t msg_len, int hash, const rsa_t prv)
int cp_rsa_ver (uint8_t *sig, size_t sig_len, const uint8_t *msg, size_t msg_len, int hash, const rsa_t pub)
Detailed Description
Implementation of the RSA cryptosystem.
Definition in file relic_cp_rsa.c.
Macro Definition Documentation
RSA_PAD_LEN
#define RSA_PAD_LEN (2 * RLC_MD_LEN + 2)
Length of chosen padding scheme.
Definition at line 44 of file relic_cp_rsa.c.
Referenced by cp_rsa_dec(), cp_rsa_enc(), cp_rsa_sig(), and cp_rsa_ver().
RSA_PUB
#define RSA_PUB (02)
Identifier for encrypted messages.
Definition at line 52 of file relic_cp_rsa.c.
RSA_PRV
#define RSA_PRV (01)
Identifier for signed messages.
Definition at line 57 of file relic_cp_rsa.c.
RSA_PAD
#define RSA_PAD (0xFF)
Byte used as padding unit.
Definition at line 62 of file relic_cp_rsa.c.
RSA_PSS
#define RSA_PSS (0xBC)
Byte used as padding unit in PSS signatures.
Definition at line 67 of file relic_cp_rsa.c.
Referenced by pad_pkcs2().
RSA_ENC
#define RSA_ENC 1
Identifier for encryption.
Definition at line 72 of file relic_cp_rsa.c.
Referenced by cp_rsa_enc(), and pad_pkcs2().
RSA_DEC
#define RSA_DEC 2
Identifier for decryption.
Definition at line 77 of file relic_cp_rsa.c.
Referenced by cp_rsa_dec(), and pad_pkcs2().
RSA_SIG
#define RSA_SIG 3
Identifier for signature.
Definition at line 82 of file relic_cp_rsa.c.
Referenced by cp_rsa_sig(), and pad_pkcs2().
RSA_VER
#define RSA_VER 4
Identifier for verification.
Definition at line 87 of file relic_cp_rsa.c.
Referenced by cp_rsa_ver(), and pad_pkcs2().
RSA_ENC_FIN
#define RSA_ENC_FIN 5
Identifier for second encryption step.
Definition at line 92 of file relic_cp_rsa.c.
Referenced by cp_rsa_enc(), and pad_pkcs2().
RSA_SIG_FIN
#define RSA_SIG_FIN 6
Identifier for second sining step.
Definition at line 97 of file relic_cp_rsa.c.
Referenced by cp_rsa_sig(), and pad_pkcs2().
RSA_SIG_HASH
#define RSA_SIG_HASH 7
Identifier for signature of a precomputed hash.
Definition at line 102 of file relic_cp_rsa.c.
Referenced by cp_rsa_sig(), and pad_pkcs2().
RSA_VER_HASH
#define RSA_VER_HASH 8
Identifier for verification of a precomputed hash.
Definition at line 107 of file relic_cp_rsa.c.
Referenced by cp_rsa_ver(), and pad_pkcs2().
Function Documentation
pad_pkcs2()
static int pad_pkcs2 (bn_t m, size_t * p_len, size_t m_len, size_t k_len, int operation) static
Applies or removes a PKCS#1 v2.1 encryption padding.
Parameters
[out] m - the buffer to pad.
[out] p_len - the number of added pad bytes.
[in] m_len - the message length in bytes.
[in] k_len - the key length in bytes.
[in] operation - flag to indicate the operation type.
Returns
RLC_ERR if errors occurred, RLC_OK otherwise.
Definition at line 424 of file relic_cp_rsa.c.
References bn_add(), bn_add_dig(), bn_cmp_dig(), bn_copy(), bn_free, bn_get_bit(), bn_is_zero(), bn_lsh(), bn_mod_2b(), bn_new, bn_null, bn_read_bin(), bn_rsh(), bn_set_bit(), bn_size_bin(), bn_write_bin(), bn_zero(), md_map, md_mgf(), rand_bytes(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FINALLY, RLC_FREE, RLC_MD_LEN, RLC_OK, RLC_TRY, RSA_DEC, RSA_ENC, RSA_ENC_FIN, RSA_PSS, RSA_SIG, RSA_SIG_FIN, RSA_SIG_HASH, RSA_VER, and RSA_VER_HASH.
Referenced by cp_rsa_dec(), cp_rsa_enc(), cp_rsa_sig(), and cp_rsa_ver().
cp_rsa_gen()
int cp_rsa_gen (rsa_t pub, rsa_t prv, size_t bits)
Generates a key pair for the RSA cryptosystem. Generates additional values for the CRT optimization if CP_CRT is on.
Parameters
[out] pub - the public key.
[out] prv - the private key.
[in] bits - the key length in bits.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 584 of file relic_cp_rsa.c.
References bn_add(), bn_add_dig(), bn_cmp(), bn_cmp_dig(), bn_copy(), bn_free, bn_gcd_ext, bn_gen_prime, bn_mod, bn_mod_inv(), bn_mul, bn_new, bn_null, bn_set_2b(), bn_sign(), bn_sub_dig(), RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FINALLY, RLC_LT, RLC_NEG, RLC_OK, and RLC_TRY.
cp_rsa_enc()
int cp_rsa_enc (uint8_t * out, size_t * out_len, const uint8_t * in, size_t in_len, const rsa_t pub)
Encrypts using the RSA cryptosystem.
Parameters
[out] out - the output buffer.
[in,out] out_len - the buffer capacity and number of bytes written.
[in] in - the input buffer.
[in] in_len - the number of bytes to encrypt.
[in] pub - the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 669 of file relic_cp_rsa.c.
References bn_add(), bn_free, bn_mxp, bn_new, bn_null, bn_read_bin(), bn_size_bin(), bn_write_bin(), bn_zero(), pad_pkcs2(), RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, RLC_TRY, RSA_ENC, RSA_ENC_FIN, and RSA_PAD_LEN.
cp_rsa_dec()
int cp_rsa_dec (uint8_t * out, size_t * out_len, const uint8_t * in, size_t in_len, const rsa_t prv)
Decrypts using the RSA cryptosystem. Uses the CRT optimization if CP_CRT is on.
Parameters
[out] out - the output buffer.
[in,out] out_len - the buffer capacity and number of bytes written.
[in] in - the input buffer.
[in] in_len - the number of bytes to decrypt.
[in] prv - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 728 of file relic_cp_rsa.c.
References bn_free, bn_mxp, bn_mxp_crt(), bn_new, bn_null, bn_read_bin(), bn_size_bin(), bn_write_bin(), pad_pkcs2(), RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, RLC_TRY, RSA_DEC, and RSA_PAD_LEN.
cp_rsa_sig()
int cp_rsa_sig (uint8_t * sig, size_t * sig_len, const uint8_t * msg, size_t msg_len, int hash, const rsa_t prv)
Signs using the basic RSA signature algorithm. The flag must be non-zero if the message being signed is already a hash value. Uses the CRT optimization if CP_CRT is on.
Parameters
[out] sig - the signature
[out] sig_len - the number of bytes written in the signature.
[in] msg - the message to sign.
[in] msg_len - the number of bytes to sign.
[in] hash - the flag to indicate the message format.
[in] prv - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 785 of file relic_cp_rsa.c.
References bn_add(), bn_bits(), bn_copy(), bn_free, bn_mxp, bn_mxp_crt(), bn_new, bn_null, bn_read_bin(), bn_size_bin(), bn_write_bin(), bn_zero(), ERR_CAUGHT, md_map, pad_pkcs2(), RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_MD_LEN, RLC_OK, RLC_THROW, RLC_TRY, RSA_PAD_LEN, RSA_SIG, RSA_SIG_FIN, and RSA_SIG_HASH.
cp_rsa_ver()
int cp_rsa_ver (uint8_t * sig, size_t sig_len, const uint8_t * msg, size_t msg_len, int hash, const rsa_t pub)
Verifies an RSA signature. The flag must be non-zero if the message being signed is already a hash value.
Parameters
[in] sig - the signature to verify.
[in] sig_len - the signature length in bytes.
[in] msg - the signed message.
[in] msg_len - the message length in bytes.
[in] hash - the flag to indicate the message format.
[in] pub - the public key.
Returns
a boolean value indicating if the signature is valid.
Definition at line 875 of file relic_cp_rsa.c.
References bn_bits(), bn_free, bn_mxp, bn_new, bn_null, bn_read_bin(), bn_size_bin(), bn_write_bin(), md_map, pad_pkcs2(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FREE, RLC_MAX, RLC_MD_LEN, RLC_OK, RLC_TRY, RSA_PAD_LEN, RSA_VER, RSA_VER_HASH, and util_cmp_sec().