RELIC: src/bn/relic_bn_util.c File Reference
relic_bn_util.c File Reference
Multiple precision integer arithmetic
#include <inttypes.h>
#include "relic_core.h"
Macros
#define RAND_DIST 40
Functions
void bn_copy (bn_t c, const bn_t a)
void bn_abs (bn_t c, const bn_t a)
void bn_neg (bn_t c, const bn_t a)
int bn_sign (const bn_t a)
void bn_zero (bn_t a)
int bn_is_zero (const bn_t a)
int bn_is_even (const bn_t a)
size_t bn_bits (const bn_t a)
int bn_get_bit (const bn_t a, uint_t bit)
void bn_set_bit (bn_t a, uint_t bit, int value)
uint_t bn_ham (const bn_t a)
void bn_get_dig (dig_t *c, const bn_t a)
void bn_set_dig (bn_t a, dig_t digit)
void bn_set_2b (bn_t a, size_t b)
void bn_rand (bn_t a, int sign, size_t bits)
void bn_rand_mod (bn_t a, const bn_t b)
void bn_print (const bn_t a)
size_t bn_size_str (const bn_t a, uint_t radix)
void bn_read_str (bn_t a, const char *str, size_t len, uint_t radix)
void bn_write_str (char *str, size_t len, const bn_t a, uint_t radix)
size_t bn_size_bin (const bn_t a)
void bn_read_bin (bn_t a, const uint8_t *bin, size_t len)
void bn_write_bin (uint8_t *bin, size_t len, const bn_t a)
size_t bn_size_raw (const bn_t a)
void bn_read_raw (bn_t a, const dig_t *raw, size_t len)
void bn_write_raw (dig_t *raw, size_t len, const bn_t a)
Detailed Description
Implementation of the multiple precision utilities.
Definition in file relic_bn_util.c.
Macro Definition Documentation
RAND_DIST
#define RAND_DIST 40
Statistical distance 1/2^\lambda between sampling and uniform distribution.
Definition at line 43 of file relic_bn_util.c.
Referenced by bn_rand_mod().
Function Documentation
bn_copy()
void bn_copy (bn_t c, const bn_t a)
Copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to copy.
Definition at line 49 of file relic_bn_util.c.
References bn_grow(), bn_trim(), and dv_copy().
Referenced by bn_abs(), bn_add_imp(), bn_div_dig(), bn_div_imp(), bn_div_rem_dig(), bn_factor(), bn_gcd_basic(), bn_gcd_binar(), bn_gcd_ext_basic(), bn_gcd_ext_binar(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_lehme(), bn_hlv(), bn_is_prime_rabin(), bn_is_prime_solov(), bn_lag(), bn_mod_2b(), bn_mod_barrt(), bn_mod_inv(), bn_mod_inv_sim(), bn_mod_monty_basic(), bn_mod_monty_comba(), bn_mod_pmers(), bn_mul_basic(), bn_mul_comba(), bn_mul_karat_imp(), bn_mxp_basic(), bn_mxp_dig(), bn_mxp_monty(), bn_mxp_sim(), bn_mxp_sim_few(), bn_mxp_sim_lot(), bn_mxp_slide(), bn_neg(), bn_rand_mod(), bn_rec_frb(), bn_rec_rtnaf(), bn_rec_sac(), bn_rec_tnaf(), bn_size_str(), bn_smb_jac(), bn_sqr_basic(), bn_sqr_comba(), bn_sqr_karat_imp(), bn_srt(), bn_sub_imp(), bn_write_str(), cp_bdpe_gen(), cp_etrs_ext(), cp_etrs_sig(), cp_etrs_uni(), cp_etrs_ver(), cp_ghpe_dec(), cp_ghpe_enc(), cp_mpsb_ver(), cp_pbpsi_ask(), cp_pbpsi_int(), cp_phpe_gen(), cp_pokor_prv(), cp_psb_sig(), cp_rabin_gen(), cp_rsa_gen(), cp_rsa_sig(), cp_rsapsi_int(), cp_shipsi_gen(), cp_shipsi_int(), cp_shpe_gen(), cp_sokor_sig(), eb_curve_get_cof(), eb_curve_get_ord(), eb_curve_set(), ed_curve_get_cof(), ed_curve_get_ord(), ed_param_set(), ep2_curve_get_cof(), ep2_curve_get_ord(), ep2_curve_set(), ep2_curve_set_twist(), ep3_curve_get_cof(), ep3_curve_get_ord(), ep3_curve_set(), ep3_curve_set_twist(), ep4_curve_get_cof(), ep4_curve_get_ord(), ep4_curve_set(), ep4_curve_set_twist(), ep8_curve_get_cof(), ep8_curve_get_ord(), ep8_curve_set(), ep8_curve_set_twist(), ep_curve_get_cof(), ep_curve_get_ord(), ep_curve_get_v1(), ep_curve_get_v2(), ep_curve_set(), ep_curve_set_endom(), fp_inv_binar(), fp_inv_exgcd(), fp_prime_get_par(), fp_prime_set(), fp_prime_set_pairf(), g1_mul_bct(), g2_mul_bct(), gt_exp_bct(), mpc_mt_bct(), mpc_mt_mul(), mpc_sss_gen(), and pad_pkcs2().
bn_abs()
void bn_abs (bn_t c, const bn_t a)
Returns the absolute value of a multiple precision integer.
Parameters
[out] c - the result.
[in] a - the argument of the absolute function.
Definition at line 62 of file relic_bn_util.c.
References bn_copy(), and RLC_POS.
Referenced by bn_div_imp(), bn_gcd_basic(), bn_gcd_binar(), bn_gcd_dig(), bn_gcd_ext_basic(), bn_gcd_ext_binar(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_lehme(), bn_mod_barrt(), bn_rec_frb(), bn_rec_glv(), bn_rec_jsf(), bn_rec_naf(), bn_rec_reg(), bn_rec_rtnaf(), bn_rec_tnaf(), bn_rec_tnaf_mod(), eb_mul_lodah(), ed_mul_reg_imp(), ep2_mul_monty(), ep2_mul_reg_imp(), ep3_mul_gls_imp(), ep3_mul_monty(), ep3_mul_reg_gls(), ep3_mul_reg_imp(), ep4_mul_monty(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), ep8_mul_monty(), ep8_mul_reg_gls(), ep8_mul_reg_imp(), ep_mul_combs_endom(), ep_mul_monty(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_mul_sim_endom(), fp12_exp_cyc_sim(), gt_exp_gls_naf(), gt_exp_gls_sac(), gt_exp_reg_gls(), gt_exp_reg_sac(), pp_exp_afg16(), and pp_exp_fm().
bn_neg()
void bn_neg (bn_t c, const bn_t a)
Inverts the sign of a multiple precision integer.
Parameters
[out] c - the result.
[out] a - the multiple precision integer to negate.
Definition at line 69 of file relic_bn_util.c.
References bn_copy(), and bn_is_zero().
Referenced by bn_div_imp(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_lehme(), bn_is_prime_solov(), bn_rec_frb(), bn_rec_glv(), bn_rec_tnaf_mod(), bn_smb_jac(), ep3_mul_gls_imp(), ep3_mul_reg_gls(), ep_curve_set_endom(), ep_mul_cof(), ep_mul_sim_lot_endom(), ep_param_set(), fp12_exp_cyc_sim(), fp_param_set(), g1_is_valid(), g2_is_valid(), gt_exp_gls_naf(), gt_exp_gls_sac(), gt_exp_reg_gls(), gt_exp_reg_sac(), and gt_is_valid().
bn_sign()
int bn_sign (const bn_t a)
Returns the sign of a multiple precision integer.
Parameters
[in] a - the multiple precision integer.
Returns
RLC_POS if the argument is positive and RLC_NEG otherwise.
Definition at line 78 of file relic_bn_util.c.
Referenced by bn_div_imp(), bn_div_rem_dig(), bn_gcd_ext_binar(), bn_mod_barrt(), bn_mod_inv(), bn_mod_monty_back(), bn_mod_monty_basic(), bn_mod_monty_comba(), bn_mod_monty_conv(), bn_mod_pmers(), bn_mod_pre_barrt(), bn_mod_pre_monty(), bn_mod_pre_pmers(), bn_mxp_basic(), bn_mxp_crt(), bn_mxp_monty(), bn_mxp_slide(), bn_rand_mod(), bn_rec_frb(), bn_rec_rtnaf(), bn_rec_tnaf(), bn_smb_jac(), bn_smb_leg(), bn_srt(), cp_ecdsa_ver(), cp_ecss_ver(), cp_ghpe_dec(), cp_mpsb_sig(), cp_mpsb_ver(), cp_rabin_dec(), cp_rsa_gen(), eb_mul_basic(), eb_mul_fix_basic(), eb_mul_fix_combd(), eb_mul_fix_combs(), eb_mul_fix_kbltz(), eb_mul_fix_plain(), eb_mul_lnaf_imp(), eb_mul_lodah(), eb_mul_ltnaf_imp(), eb_mul_rnaf_imp(), eb_mul_rtnaf_imp(), eb_mul_sim_joint(), eb_mul_sim_kbltz(), eb_mul_sim_plain(), eb_mul_sim_trick(), ed_mul_basic(), ed_mul_combs_plain(), ed_mul_fix_basic(), ed_mul_fix_combd(), ed_mul_fix_plain(), ed_mul_monty(), ed_mul_naf_imp(), ed_mul_reg_imp(), ed_mul_sim_joint(), ed_mul_sim_lot(), ed_mul_sim_plain(), ed_mul_sim_trick(), ed_mul_slide(), ep2_mul_basic(), ep2_mul_fix_plain(), ep2_mul_gls_imp(), ep2_mul_naf_imp(), ep2_mul_reg_gls(), ep2_mul_reg_imp(), ep2_mul_sim_endom(), ep2_mul_sim_joint(), ep2_mul_sim_lot(), ep2_mul_sim_plain(), ep2_mul_slide(), ep3_mul_basic(), ep3_mul_fix_plain(), ep3_mul_gls_imp(), ep3_mul_naf_imp(), ep3_mul_reg_gls(), ep3_mul_reg_imp(), ep3_mul_sim_joint(), ep3_mul_sim_lot(), ep3_mul_sim_plain(), ep3_mul_sim_trick(), ep3_mul_slide(), ep4_mul_basic(), ep4_mul_fix_combd(), ep4_mul_fix_ordin(), ep4_mul_gls_imp(), ep4_mul_naf_imp(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), ep4_mul_sim_joint(), ep4_mul_sim_lot(), ep4_mul_sim_plain(), ep4_mul_sim_trick(), ep4_mul_slide(), ep8_mul_basic(), ep8_mul_fix_combd(), ep8_mul_fix_ordin(), ep8_mul_gls_imp(), ep8_mul_naf_imp(), ep8_mul_reg_gls(), ep8_mul_reg_imp(), ep8_mul_sim_joint(), ep8_mul_sim_lot(), ep8_mul_sim_plain(), ep8_mul_sim_trick(), ep8_mul_slide(), ep_curve_set_endom(), ep_mul_basic(), ep_mul_combs_endom(), ep_mul_fix_plain(), ep_mul_glv_imp(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_mul_sim_endom(), ep_mul_sim_joint(), ep_mul_sim_lot_endom(), ep_mul_sim_lot_plain(), ep_mul_sim_plain(), ep_param_set(), fb_exp_basic(), fb_exp_monty(), fb_exp_slide(), fp12_exp(), fp12_exp_cyc(), fp12_exp_cyc_sim(), fp16_exp(), fp16_exp_cyc(), fp16_exp_cyc_sim(), fp18_exp(), fp18_exp_cyc(), fp18_exp_cyc_sim(), fp24_exp(), fp24_exp_cyc(), fp24_exp_cyc_sim(), fp2_exp(), fp2_exp_cyc(), fp2_exp_cyc_sim(), fp3_exp(), fp48_exp(), fp48_exp_cyc(), fp48_exp_cyc_sim(), fp4_exp(), fp54_exp(), fp54_exp_cyc(), fp6_exp(), fp8_exp(), fp8_exp_cyc(), fp8_exp_cyc_sim(), fp9_exp(), fp_exp_basic(), fp_exp_monty(), fp_exp_slide(), fp_inv_binar(), fp_inv_exgcd(), fp_read_bin(), fp_read_str(), g1_is_valid(), g1_mul(), g1_mul_lcl(), g2_mul(), g2_mul_lcl(), gt_exp(), gt_exp_gls_naf(), gt_exp_gls_sac(), gt_exp_lcl(), gt_exp_reg_gls(), gt_exp_reg_sac(), gt_exp_sec(), gt_is_valid(), mpc_mt_gen(), mpc_mt_lcl(), mpc_mt_mul(), pp_exp_afg16(), pp_exp_b12(), pp_exp_bn(), pp_exp_fm(), pp_exp_k24(), pp_exp_k48(), pp_exp_k54(), pp_exp_kss(), pp_exp_sg(), pp_map_k24(), pp_map_k48(), pp_map_k54(), pp_map_oatep_k12(), pp_map_oatep_k16(), pp_map_oatep_k18(), pp_map_oatep_k8(), pp_map_sim_k24(), pp_map_sim_k48(), pp_map_sim_oatep_k12(), pp_map_sim_oatep_k16(), pp_map_sim_oatep_k18(), and pp_map_sim_oatep_k8().
bn_zero()
void bn_zero (bn_t a)
Assigns zero to a multiple precision integer.
Parameters
[out] a - the multiple precision integer to assign.
Definition at line 82 of file relic_bn_util.c.
References dv_zero(), and RLC_POS.
Referenced by bn_div_imp(), bn_evl(), bn_gcd_ext_basic(), bn_gcd_ext_binar(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_lag(), bn_mod_2b(), bn_mod_barrt(), bn_mod_monty_basic(), bn_mod_monty_comba(), bn_mul_basic(), bn_mxp_basic(), bn_mxp_dig(), bn_mxp_monty(), bn_mxp_sim_few(), bn_mxp_sim_lot(), bn_mxp_slide(), bn_read_bin(), bn_read_str(), bn_rec_frb(), bn_rec_tnaf_mod(), bn_set_dig(), bn_sqr_basic(), bn_srt(), cp_etrs_ext(), cp_etrs_sig(), cp_ghpe_dec(), cp_mklhs_fun(), cp_mklhs_onv(), cp_mklhs_ver(), cp_mpsb_sig(), cp_mpsb_ver(), cp_rabin_enc(), cp_rsa_enc(), cp_rsa_sig(), ep_param_set(), fp_inv_binar(), fp_inv_exgcd(), fp_inv_monty(), and pad_pkcs2().
bn_is_zero()
int bn_is_zero (const bn_t a)
Tests if a multiple precision integer is zero or not.
Parameters
[in] a - the multiple precision integer to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 88 of file relic_bn_util.c.
Referenced by bn_bits(), bn_cmp(), bn_cmp_abs(), bn_div(), bn_div_dig(), bn_div_imp(), bn_div_rem(), bn_div_rem_dig(), bn_gcd_basic(), bn_gcd_binar(), bn_gcd_dig(), bn_gcd_ext_basic(), bn_gcd_ext_binar(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_lehme(), bn_is_even(), bn_is_factor(), bn_is_prime_rabin(), bn_mod_barrt(), bn_mod_pmers(), bn_mod_pre_barrt(), bn_mod_pre_pmers(), bn_mxp_basic(), bn_mxp_monty(), bn_mxp_sim_few(), bn_mxp_slide(), bn_neg(), bn_rand_mod(), bn_rec_jsf(), bn_rec_naf(), bn_rec_tnaf(), bn_size_str(), bn_smb_jac(), bn_write_str(), cp_bbs_gen(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ecss_sig(), cp_ecss_ver(), cp_etrs_ext(), cp_pokor_ver(), cp_rabin_dec(), cp_sokor_ver(), eb_mul_basic(), eb_mul_fix_basic(), eb_mul_fix_combd(), eb_mul_fix_combs(), eb_mul_fix_kbltz(), eb_mul_fix_plain(), eb_mul_halve(), eb_mul_lodah(), eb_mul_lwnaf(), eb_mul_rwnaf(), eb_mul_sim_gen(), eb_mul_sim_inter(), eb_mul_sim_joint(), eb_mul_sim_trick(), ed_mul_basic(), ed_mul_fix_basic(), ed_mul_gen(), ed_mul_lwnaf(), ed_mul_lwreg(), ed_mul_monty(), ed_mul_naf_imp(), ed_mul_sim_gen(), ed_mul_sim_inter(), ed_mul_sim_joint(), ed_mul_sim_trick(), ed_mul_slide(), ep2_mul_basic(), ep2_mul_fix_basic(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_fix_lwnaf(), ep2_mul_fix_plain(), ep2_mul_gen(), ep2_mul_lwnaf(), ep2_mul_lwreg(), ep2_mul_monty(), ep2_mul_sim_gen(), ep2_mul_sim_inter(), ep2_mul_sim_joint(), ep2_mul_sim_trick(), ep2_mul_slide(), ep2_upk(), ep3_mul_basic(), ep3_mul_fix_basic(), ep3_mul_fix_combd(), ep3_mul_fix_combs(), ep3_mul_fix_lwnaf(), ep3_mul_fix_plain(), ep3_mul_gen(), ep3_mul_lwnaf(), ep3_mul_lwreg(), ep3_mul_monty(), ep3_mul_sim_gen(), ep3_mul_sim_inter(), ep3_mul_sim_joint(), ep3_mul_sim_trick(), ep3_mul_slide(), ep4_mul_basic(), ep4_mul_fix_basic(), ep4_mul_fix_combd(), ep4_mul_fix_combs(), ep4_mul_fix_ordin(), ep4_mul_gen(), ep4_mul_lwnaf(), ep4_mul_lwreg(), ep4_mul_monty(), ep4_mul_sim_gen(), ep4_mul_sim_inter(), ep4_mul_sim_joint(), ep4_mul_sim_trick(), ep4_mul_slide(), ep8_mul_basic(), ep8_mul_fix_basic(), ep8_mul_fix_combd(), ep8_mul_fix_combs(), ep8_mul_fix_ordin(), ep8_mul_gen(), ep8_mul_lwnaf(), ep8_mul_lwreg(), ep8_mul_monty(), ep8_mul_sim_gen(), ep8_mul_sim_inter(), ep8_mul_sim_joint(), ep8_mul_sim_trick(), ep8_mul_slide(), ep_mul_basic(), ep_mul_fix_basic(), ep_mul_fix_combd(), ep_mul_fix_combs(), ep_mul_fix_lwnaf(), ep_mul_gen(), ep_mul_lwnaf(), ep_mul_lwreg(), ep_mul_monty(), ep_mul_sim_gen(), ep_mul_sim_inter(), ep_mul_sim_joint(), ep_mul_sim_trick(), ep_mul_slide(), ep_param_set(), fb_exp_basic(), fb_exp_monty(), fb_exp_slide(), fp12_exp(), fp12_exp_cyc(), fp12_exp_cyc_sim(), fp16_exp(), fp16_exp_cyc(), fp16_exp_cyc_sim(), fp18_exp(), fp18_exp_cyc(), fp18_exp_cyc_sim(), fp24_exp(), fp24_exp_cyc(), fp24_exp_cyc_sim(), fp2_exp(), fp2_exp_cyc(), fp2_exp_cyc_sim(), fp3_exp(), fp48_exp(), fp48_exp_cyc(), fp48_exp_cyc_sim(), fp4_exp(), fp54_exp(), fp54_exp_cyc(), fp6_exp(), fp8_exp(), fp8_exp_cyc(), fp8_exp_cyc_sim(), fp9_exp(), fp_exp_basic(), fp_exp_monty(), fp_exp_slide(), fp_inv_monty(), fp_prime_conv(), fp_read_bin(), fp_read_str(), gt_exp_gls_naf(), gt_exp_reg_gls(), and pad_pkcs2().
bn_is_even()
int bn_is_even (const bn_t a)
Tests if a multiple precision integer is even or odd.
Parameters
[in] a - the multiple precision integer to test.
Returns
1 if the argument is even, 0 otherwise.
Definition at line 98 of file relic_bn_util.c.
References bn_is_zero().
Referenced by bn_factor(), bn_gcd_binar(), bn_gcd_ext_binar(), bn_is_prime_rabin(), bn_mod_monty_back(), bn_mod_monty_basic(), bn_mod_monty_comba(), bn_mod_monty_conv(), bn_mod_pre_monty(), bn_rec_naf(), bn_rec_tnaf_mod(), bn_smb_jac(), cp_rsapsi_ans(), cp_rsapsi_ask(), cp_shipsi_ans(), cp_shipsi_ask(), ed_mul_reg_imp(), ep2_mul_reg_gls(), ep2_mul_reg_imp(), ep3_mul_gls_imp(), ep3_mul_reg_gls(), ep3_mul_reg_imp(), ep4_mul_cof_fm16(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), ep8_mul_reg_gls(), ep8_mul_reg_imp(), ep_mul_cof(), ep_mul_reg_glv(), ep_mul_reg_imp(), fp12_exp_cyc(), fp18_exp_cyc(), fp24_exp_cyc(), fp48_exp_cyc(), fp54_exp_cyc(), fp_is_even(), fp_prime_set(), g1_is_valid(), g2_is_valid(), gt_exp_gls_sac(), gt_exp_reg_gls(), gt_exp_reg_sac(), gt_is_valid(), and pp_exp_afg16().
bn_bits()
size_t bn_bits (const bn_t a)
Returns the number of bits of a multiple precision integer.
Parameters
[in] a - the multiple precision integer.
Returns
number of bits.
Definition at line 108 of file relic_bn_util.c.
References bn_is_zero(), RLC_DIG, and util_bits_dig().
Referenced by bn_gcd_ext_binar(), bn_gcd_ext_lehme(), bn_gcd_lehme(), bn_gen_prime_basic(), bn_gen_prime_factor(), bn_gen_prime_safep(), bn_gen_prime_stron(), bn_get_bit(), bn_ham(), bn_is_prime_rabin(), bn_is_prime_solov(), bn_mod_pmers(), bn_mod_pre_pmers(), bn_mxp_basic(), bn_mxp_monty(), bn_mxp_sim_few(), bn_mxp_slide(), bn_rand_mod(), bn_rec_frb(), bn_rec_glv(), bn_rec_jsf(), bn_rec_naf(), bn_rec_rtnaf(), bn_rec_sac(), bn_rec_slw(), bn_rec_tnaf(), bn_rec_win(), bn_size_str(), bn_srt(), cp_ecdh_key(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ecies_dec(), cp_ecies_enc(), cp_ecmqv_key(), cp_ecss_sig(), cp_ecss_ver(), cp_ghpe_dec(), cp_ghpe_enc(), cp_phpe_dec(), cp_phpe_enc(), cp_rsa_sig(), cp_rsa_ver(), cp_shpe_dec(), cp_shpe_enc(), cp_shpe_enc_prv(), eb_map(), eb_mul_basic(), eb_mul_fix_basic(), eb_mul_fix_combd(), eb_mul_fix_combs(), eb_mul_halve(), eb_mul_lodah(), eb_mul_pre_basic(), eb_mul_pre_combd(), eb_mul_pre_combs(), eb_mul_sim_joint(), ed_mul_basic(), ed_mul_combs_plain(), ed_mul_fix_basic(), ed_mul_fix_combd(), ed_mul_monty(), ed_mul_pre_basic(), ed_mul_pre_combd(), ed_mul_pre_combs(), ed_mul_sim_joint(), ed_mul_sim_lot(), ep2_mul_basic(), ep2_mul_fix_basic(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_monty(), ep2_mul_pre_basic(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_reg_gls(), ep2_mul_reg_imp(), ep2_mul_sim_joint(), ep3_mul_basic(), ep3_mul_fix_basic(), ep3_mul_fix_combd(), ep3_mul_fix_combs(), ep3_mul_gls_imp(), ep3_mul_monty(), ep3_mul_pre_basic(), ep3_mul_pre_combd(), ep3_mul_pre_combs(), ep3_mul_reg_gls(), ep3_mul_reg_imp(), ep3_mul_sim_joint(), ep4_mul_basic(), ep4_mul_fix_basic(), ep4_mul_fix_combd(), ep4_mul_fix_combs(), ep4_mul_monty(), ep4_mul_pre_basic(), ep4_mul_pre_combd(), ep4_mul_pre_combs(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), ep4_mul_sim_joint(), ep8_mul_basic(), ep8_mul_fix_basic(), ep8_mul_fix_combd(), ep8_mul_fix_combs(), ep8_mul_monty(), ep8_mul_pre_basic(), ep8_mul_pre_combd(), ep8_mul_pre_combs(), ep8_mul_reg_gls(), ep8_mul_reg_imp(), ep8_mul_sim_joint(), ep_curve_set_endom(), ep_mul_basic(), ep_mul_combs_endom(), ep_mul_combs_plain(), ep_mul_fix_basic(), ep_mul_fix_combd(), ep_mul_monty(), ep_mul_pre_basic(), ep_mul_pre_combd(), ep_mul_pre_combs(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_mul_sim_joint(), ep_mul_sim_lot_plain(), fb_exp_basic(), fb_exp_monty(), fb_read_str(), fp12_exp(), fp12_exp_cyc(), fp12_exp_cyc_sim(), fp12_exp_dig(), fp16_exp(), fp16_exp_cyc(), fp16_exp_dig(), fp18_exp(), fp18_exp_cyc(), fp18_exp_dig(), fp24_exp(), fp24_exp_cyc(), fp24_exp_dig(), fp2_exp(), fp2_exp_cyc(), fp3_exp(), fp48_exp(), fp48_exp_cyc(), fp48_exp_dig(), fp4_exp(), fp54_exp(), fp54_exp_cyc(), fp54_exp_dig(), fp6_exp(), fp8_exp(), fp8_exp_cyc(), fp8_exp_dig(), fp9_exp(), fp_exp_basic(), fp_exp_monty(), fp_prime_set_pairf(), g1_mul(), g2_mul(), gt_exp(), gt_exp_gls_sac(), gt_exp_reg_gls(), gt_exp_reg_sac(), gt_exp_sec(), pp_mil_k1(), pp_mil_k12(), pp_mil_k16(), pp_mil_k18(), pp_mil_k2(), pp_mil_k24(), pp_mil_k48(), pp_mil_k54(), pp_mil_k8(), pp_mil_lit_k12(), pp_mil_lit_k16(), pp_mil_lit_k18(), and pp_mil_lit_k2().
bn_get_bit()
int bn_get_bit (const bn_t a, uint_t bit)
Returns the bit stored in the given position on a multiple precision integer.
Parameters
[in] a - the multiple precision integer.
[in] bit - the bit position to read.
Returns
the bit value.
Definition at line 121 of file relic_bn_util.c.
References bn_bits(), and RLC_RIP.
Referenced by bn_ham(), bn_mxp_basic(), bn_mxp_monty(), bn_mxp_sim_few(), bn_rec_glv(), bn_rec_sac(), bn_rec_slw(), eb_mul_fix_basic(), eb_mul_fix_combd(), eb_mul_fix_combs(), eb_mul_lodah(), ed_map_ell2_5mod8(), ed_mul_combs_plain(), ed_mul_fix_basic(), ed_mul_fix_combd(), ed_mul_monty(), ed_param_set(), ep2_curve_set_map(), ep2_map_swift(), ep2_mul_fix_basic(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_monty(), ep3_map(), ep3_mul_fix_basic(), ep3_mul_fix_combd(), ep3_mul_fix_combs(), ep3_mul_monty(), ep4_map(), ep4_mul_fix_basic(), ep4_mul_fix_combd(), ep4_mul_fix_combs(), ep4_mul_monty(), ep8_map(), ep8_mul_fix_basic(), ep8_mul_fix_combd(), ep8_mul_fix_combs(), ep8_mul_monty(), ep_curve_set_map(), ep_mul_combs_endom(), ep_mul_combs_plain(), ep_mul_fix_basic(), ep_mul_fix_combd(), ep_mul_monty(), fb_exp_basic(), fb_exp_monty(), fp12_exp(), fp12_exp_cyc(), fp12_exp_cyc_sim(), fp16_exp(), fp18_exp(), fp18_exp_cyc(), fp24_exp(), fp24_exp_cyc(), fp2_exp(), fp2_sgn0(), fp3_exp(), fp48_exp(), fp48_exp_cyc(), fp4_exp(), fp54_exp(), fp54_exp_cyc(), fp6_exp(), fp8_exp(), fp9_exp(), fp_exp_basic(), fp_exp_monty(), pad_pkcs2(), pp_mil_k1(), pp_mil_k2(), pp_mil_lit_k12(), pp_mil_lit_k16(), pp_mil_lit_k18(), and pp_mil_lit_k2().
bn_set_bit()
void bn_set_bit (bn_t a, uint_t bit, int value)
Stores a bit in a given position on a multiple precision integer.
Parameters
[out] a - the multiple precision integer.
[in] bit - the bit position to store.
[in] value - the bit value.
Definition at line 137 of file relic_bn_util.c.
References bn_grow(), bn_trim(), and RLC_RIP.
Referenced by cp_ecmqv_key(), fp_param_set(), and pad_pkcs2().
bn_ham()
uint_t bn_ham (const bn_t a)
Returns the Hamming weight of a multiple precision integer.
Parameters
[in] a - the multiple precision integer.
Returns
the number of non-zero bits.
Definition at line 155 of file relic_bn_util.c.
References bn_bits(), and bn_get_bit().
Referenced by fp12_exp_cyc(), fp18_exp_cyc(), fp24_exp_cyc(), fp48_exp_cyc(), and fp54_exp_cyc().
bn_get_dig()
void bn_get_dig (dig_t * digit, const bn_t a)
Reads the first digit in a multiple precision integer.
Parameters
[out] digit - the result.
[in] a - the multiple precision integer.
Definition at line 165 of file relic_bn_util.c.
Referenced by bn_rec_jsf(), bn_rec_naf(), and bn_rec_reg().
bn_set_dig()
void bn_set_dig (bn_t a, dig_t digit)
Assigns a small positive constant to a multiple precision integer.
The constant must fit on a multiple precision digit, or dig_t type using only the number of bits specified on RLC_DIG.
Parameters
[out] a - the result.
[in] digit - the constant to assign.
Definition at line 169 of file relic_bn_util.c.
References bn_zero(), and RLC_POS.
Referenced by bn_div_imp(), bn_factor(), bn_gcd_dig(), bn_gcd_ext_basic(), bn_gcd_ext_binar(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gen_prime_factor(), bn_is_prime_rabin(), bn_is_prime_solov(), bn_lag(), bn_mod_barrt(), bn_mod_pre_monty(), bn_mxp_basic(), bn_mxp_dig(), bn_mxp_monty(), bn_mxp_sim_few(), bn_mxp_sim_lot(), bn_mxp_slide(), bn_rec_tnaf_mod(), cp_bdpe_enc(), cp_bdpe_gen(), cp_etrs_sig(), cp_etrs_uni(), cp_etrs_ver(), ed_mul_dig(), ep2_mul_dig(), ep3_mul_dig(), ep4_mul_dig(), ep8_mul_dig(), ep_mul_dig(), ep_param_set(), fp12_exp_dig(), fp16_exp_dig(), fp18_exp_dig(), fp24_exp_dig(), fp48_exp_dig(), fp54_exp_dig(), fp8_exp_dig(), fp_inv_binar(), fp_inv_divst(), fp_inv_exgcd(), fp_inv_monty(), fp_param_set(), fp_prime_set(), fp_prime_set_pairf(), fp_smb_divst(), gt_exp_dig(), mpc_sss_gen(), mpc_sss_key(), and pp_exp_k8().
bn_set_2b()
void bn_set_2b (bn_t a, size_t b)
Assigns a multiple precision integer to 2^b.
Parameters
[out] a - the result.
[in] b - the power of 2 to assign.
Definition at line 176 of file relic_bn_util.c.
References bn_grow(), ERR_NO_VALID, RLC_BN_SIZE, RLC_DIG, RLC_POS, RLC_RIP, and RLC_THROW.
Referenced by bn_mod_pre_barrt(), bn_mod_pre_pmers(), bn_srt(), cp_rsa_gen(), fp_inv_monty(), fp_param_set(), fp_prime_set(), and fp_prime_set_pmers().
bn_rand()
void bn_rand (bn_t a, int sign, size_t bits)
Assigns a random value to a multiple precision integer.
Parameters
[out] a - the multiple precision integer to assign.
[in] sign - the sign to be assigned (RLC_NEG or RLC_POS).
[in] bits - the number of bits.
Definition at line 194 of file relic_bn_util.c.
References bn_grow(), bn_trim(), rand_bytes(), and RLC_RIP.
Referenced by bn_gen_prime_basic(), bn_gen_prime_factor(), bn_gen_prime_safep(), bn_gen_prime_stron(), bn_is_prime_solov(), bn_rand_mod(), cp_bbs_gen(), cp_bdpe_gen(), cp_lvprv_gen(), cp_lvpub_ask(), cp_pdprv_gen(), cp_pdpub_gen(), and eb_mul_halve().
bn_rand_mod()
void bn_rand_mod (bn_t a, const bn_t b)
Assigns a non-zero random value to a multiple precision integer with absolute value smaller than a given modulus.
Parameters
[out] a - the multiple precision integer to assign.
[in] b - the modulus.
Definition at line 213 of file relic_bn_util.c.
References bn_bits(), bn_cmp_abs(), bn_copy(), bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, bn_rand(), bn_sign(), ERR_CAUGHT, RAND_DIST, RLC_CATCH_ANY, RLC_FINALLY, RLC_LT, RLC_THROW, and RLC_TRY.
Referenced by cp_bdpe_enc(), cp_bgn_enc1(), cp_bgn_enc2(), cp_bgn_gen(), cp_bls_gen(), cp_clb_gen(), cp_cli_gen(), cp_cls_gen(), cp_cmlhs_gen(), cp_cmlhs_sig(), cp_ecdh_gen(), cp_ecdsa_gen(), cp_ecdsa_sig(), cp_ecies_enc(), cp_ecies_gen(), cp_ecmqv_gen(), cp_ecss_gen(), cp_ecss_sig(), cp_ers_ext(), cp_ers_gen_key(), cp_ers_sig(), cp_etrs_sig(), cp_etrs_uni(), cp_ghpe_enc(), cp_ibe_enc(), cp_ibe_gen(), cp_lvprv_gen(), cp_lvpub_gen(), cp_mklhs_gen(), cp_mpsb_gen(), cp_mpsb_sig(), cp_mpsb_ver(), cp_mpss_gen(), cp_mpss_ver(), cp_pbpsi_ans(), cp_pbpsi_ask(), cp_pbpsi_gen(), cp_pdprv_gen(), cp_pdpub_gen(), cp_phpe_enc(), cp_pokdl_prv(), cp_pokor_prv(), cp_psb_gen(), cp_pss_gen(), cp_rsapsi_ans(), cp_rsapsi_ask(), cp_rsapsi_gen(), cp_shipsi_ans(), cp_shipsi_ask(), cp_shipsi_gen(), cp_shpe_enc(), cp_shpe_enc_prv(), cp_smlers_ext(), cp_sokaka_gen(), cp_sokdl_sig(), cp_sokor_sig(), cp_vbnn_gen(), cp_vbnn_gen_prv(), cp_vbnn_sig(), cp_zss_gen(), eb_rand(), ed_rand(), ep2_rand(), ep3_rand(), ep4_rand(), ep8_rand(), ep_rand(), mpc_mt_gen(), and mpc_sss_gen().
bn_print()
void bn_print (const bn_t a)
Prints a multiple precision integer to standard output.
Parameters
[in] a - the multiple precision integer to print.
Definition at line 233 of file relic_bn_util.c.
References RLC_NEG, util_print, and util_print_dig().
Referenced by fp_param_print().
bn_size_str()
size_t bn_size_str (const bn_t a, uint_t radix)
Returns the number of digits in radix necessary to store a multiple precision integer. The radix must be included in the interval [2, 64].
Parameters
[in] a - the multiple precision integer.
[in] radix - the radix.
Exceptions
ERR_NO_VALID - if the radix is invalid.
Returns
the number of digits in the given radix.
Definition at line 257 of file relic_bn_util.c.
References bn_bits(), bn_copy(), bn_div_dig(), bn_free, bn_is_zero(), bn_new, bn_null, ERR_CAUGHT, ERR_NO_VALID, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_POS, RLC_THROW, and RLC_TRY.
Referenced by bn_write_str(), fb_size_str(), and fp_size_str().
bn_read_str()
void bn_read_str (bn_t a, const char * str, size_t len, uint_t radix)
Reads a multiple precision integer from a string in a given radix. The radix must be included in the interval [2, 64].
Parameters
[out] a - the result.
[in] str - the string.
[in] len - the size of the string.
[in] radix - the radix.
Exceptions
ERR_NO_VALID - if the radix is invalid.
Definition at line 301 of file relic_bn_util.c.
References bn_add_dig(), bn_grow(), bn_mul_dig(), bn_trim(), bn_zero(), ERR_CAUGHT, ERR_NO_VALID, RLC_CATCH_ANY, RLC_CEIL, RLC_DIG, RLC_NEG, RLC_POS, RLC_THROW, RLC_TRY, RLC_UPP, util_bits_dig(), and util_conv_char().
Referenced by fb_read_str(), fp_param_set(), and fp_read_str().
bn_write_str()
void bn_write_str (char * str, size_t len, const bn_t a, uint_t radix)
Writes a multiple precision integer to a string in a given radix. The radix must be included in the interval [2, 64].
Parameters
[out] str - the string.
[in] len - the buffer capacity.
[in] a - the multiple integer to write.
[in] radix - the radix.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
ERR_NO_VALID - if the radix is invalid.
Definition at line 350 of file relic_bn_util.c.
References bn_copy(), bn_div_rem_dig(), bn_free, bn_is_zero(), bn_new, bn_null, bn_size_str(), ERR_CAUGHT, ERR_NO_BUFFER, ERR_NO_VALID, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_POS, RLC_THROW, RLC_TRY, and util_conv_char().
Referenced by fp_write_str().
bn_size_bin()
size_t bn_size_bin (const bn_t a)
Returns the number of bytes necessary to store a multiple precision integer.
Parameters
[in] a - the multiple precision integer.
Returns
the number of bytes.
Definition at line 416 of file relic_bn_util.c.
References RLC_DIG.
Referenced by bn_write_bin(), cp_bdpe_dec(), cp_bdpe_enc(), cp_ecdh_key(), cp_ecies_dec(), cp_ecies_enc(), cp_ecmqv_key(), cp_rabin_dec(), cp_rabin_enc(), cp_rsa_dec(), cp_rsa_enc(), cp_rsa_sig(), cp_rsa_ver(), and pad_pkcs2().
bn_read_bin()
void bn_read_bin (bn_t a, const uint8_t * bin, size_t len)
Reads a positive multiple precision integer from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Definition at line 430 of file relic_bn_util.c.
References bn_grow(), bn_trim(), bn_zero(), RLC_DIG, and RLC_POS.
Referenced by cp_bbs_sig(), cp_bbs_ver(), cp_bdpe_dec(), cp_clb_sig(), cp_clb_ver(), cp_cli_sig(), cp_cli_ver(), cp_cls_sig(), cp_cls_ver(), cp_cmlhs_sig(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ecss_sig(), cp_ecss_ver(), cp_pokdl_prv(), cp_pokdl_ver(), cp_pokor_prv(), cp_pokor_ver(), cp_rabin_dec(), cp_rabin_enc(), cp_rsa_dec(), cp_rsa_enc(), cp_rsa_sig(), cp_rsa_ver(), cp_rsapsi_ans(), cp_rsapsi_ask(), cp_shipsi_ans(), cp_shipsi_ask(), cp_sokdl_sig(), cp_sokdl_ver(), cp_sokor_sig(), cp_sokor_ver(), cp_vbnn_gen_prv(), cp_vbnn_sig(), cp_vbnn_ver(), cp_zss_sig(), cp_zss_ver(), eb_map(), ep2_map_basic(), ep2_map_swift(), ep3_map(), ep4_map(), ep8_map(), ep_map_basic_impl(), ep_map_swift_impl(), fb_read_bin(), fp_read_bin(), and pad_pkcs2().
bn_write_bin()
void bn_write_bin (uint8_t * bin, size_t len, const bn_t a)
Writes a positive multiple precision integer to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the multiple integer to write.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 460 of file relic_bn_util.c.
References bn_size_bin(), ERR_NO_BUFFER, RLC_DIG, and RLC_THROW.
Referenced by cp_bdpe_enc(), cp_ecdh_key(), cp_ecies_dec(), cp_ecies_enc(), cp_ecmqv_key(), cp_ecss_sig(), cp_ecss_ver(), cp_rabin_dec(), cp_rabin_enc(), cp_rsa_dec(), cp_rsa_enc(), cp_rsa_sig(), cp_rsa_ver(), cp_rsapsi_ans(), cp_rsapsi_ask(), cp_shipsi_ans(), cp_shipsi_ask(), fb_write_bin(), fp_write_bin(), and pad_pkcs2().
bn_size_raw()
size_t bn_size_raw (const bn_t a)
Returns the number of digits necessary to store a multiple precision integer.
Parameters
[in] a - the multiple precision integer.
Returns
the number of digits.
Definition at line 491 of file relic_bn_util.c.
bn_read_raw()
void bn_read_raw (bn_t a, const dig_t * raw, size_t len)
Reads a positive multiple precision integer from a digit vector.
Parameters
[out] a - the result.
[in] raw - the digit vector.
[in] len - the size of the string.
Definition at line 495 of file relic_bn_util.c.
References bn_grow(), bn_trim(), dv_copy(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_POS, RLC_THROW, and RLC_TRY.
Referenced by fb_size_str(), fb_write_bin(), fp3_field_init(), fp_inv_monty(), fp_print(), and pp_exp_k1().
bn_write_raw()
void bn_write_raw (dig_t * raw, size_t len, const bn_t a)
Writes a positive multiple precision integer to a byte vector.
Parameters
[out] raw - the digit vector.
[in] len - the buffer capacity.
[in] a - the multiple integer to write.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 507 of file relic_bn_util.c.
References ERR_NO_BUFFER, and RLC_THROW.