RELIC: src/eb/relic_eb_add.c File Reference
relic_eb_add.c File Reference
Elliptic curves over binary fields
#include "string.h"
#include "relic_core.h"
#include "relic_eb.h"
Functions
static void eb_add_basic_imp (eb_t r, const eb_t p, const eb_t q)
static void eb_add_projc_mix (eb_t r, const eb_t p, const eb_t q)
static void eb_add_projc_imp (eb_t r, const eb_t p, const eb_t q)
void eb_add_basic (eb_t r, const eb_t p, const eb_t q)
void eb_sub_basic (eb_t r, const eb_t p, const eb_t q)
void eb_add_projc (eb_t r, const eb_t p, const eb_t q)
void eb_sub_projc (eb_t r, const eb_t p, const eb_t q)
Detailed Description
Implementation of point addition on binary elliptic curves.
Definition in file relic_eb_add.c.
Function Documentation
eb_add_basic_imp()
static void eb_add_basic_imp (eb_t r, const eb_t p, const eb_t q) static
Adds two points represented in affine coordinates on an ordinary binary elliptic curve.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 51 of file relic_eb_add.c.
References BASIC, eb_curve_get_a(), eb_curve_opt_a(), eb_dbl_basic(), eb_set_infty(), ERR_CAUGHT, fb_add(), fb_add_dig(), fb_copy(), fb_free, fb_inv, fb_is_zero(), fb_mul, fb_new, fb_null, fb_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_ONE, RLC_THROW, RLC_TINY, RLC_TRY, and RLC_ZERO.
Referenced by eb_add_basic().
eb_add_projc_mix()
static void eb_add_projc_mix (eb_t r, const eb_t p, const eb_t q) static
Adds a point represented in affine coordinates to a point represented in projective coordinates.
Parameters
[out] r - the result.
[in] p - the affine point.
[in] q - the projective point.
Definition at line 139 of file relic_eb_add.c.
References BASIC, eb_curve_get_a(), eb_curve_opt_a(), eb_dbl_projc(), eb_set_infty(), ERR_CAUGHT, fb_add(), fb_copy(), fb_free, fb_is_zero(), fb_mul, fb_mul_dig(), fb_new, fb_null, fb_sqr, PROJC, RLC_CATCH_ANY, RLC_FINALLY, RLC_ONE, RLC_THROW, RLC_TINY, RLC_TRY, and RLC_ZERO.
Referenced by eb_add_projc_imp().
eb_add_projc_imp()
static void eb_add_projc_imp (eb_t r, const eb_t p, const eb_t q) static
Adds two points represented in projective coordinates on an ordinary binary elliptic curve.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 275 of file relic_eb_add.c.
References BASIC, eb_add_projc_mix(), eb_dbl_projc(), eb_set_infty(), ERR_CAUGHT, fb_add(), fb_free, fb_is_zero(), fb_mul, fb_new, fb_null, fb_sqr, PROJC, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by eb_add_projc().
eb_add_basic()
void eb_add_basic (eb_t r, const eb_t p, const eb_t q)
Adds two binary elliptic curve points represented in affine coordinates.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 402 of file relic_eb_add.c.
References eb_add_basic_imp(), eb_copy(), and eb_is_infty().
Referenced by eb_sub_basic().
eb_sub_basic()
void eb_sub_basic (eb_t r, const eb_t p, const eb_t q)
Subtracts a binary elliptic curve point from another, both points represented by affine coordinates.
Parameters
[out] r - the result.
[in] p - the first point.
[in] q - the second point.
Definition at line 416 of file relic_eb_add.c.
References BASIC, eb_add_basic(), eb_free, eb_neg_basic(), eb_new, eb_null, eb_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
eb_add_projc()
void eb_add_projc (eb_t r, const eb_t p, const eb_t q)
Adds two binary elliptic curve points represented in projective coordinates. Computes R = P + Q.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 446 of file relic_eb_add.c.
References eb_add_projc_imp(), eb_copy(), and eb_is_infty().
Referenced by eb_sub_projc().
eb_sub_projc()
void eb_sub_projc (eb_t r, const eb_t p, const eb_t q)
Subtracts a binary elliptic curve point from another, both points represented by projective coordinates.
Parameters
[out] r - the result.
[in] p - the first point.
[in] q - the second point.
Definition at line 460 of file relic_eb_add.c.
References eb_add_projc(), eb_free, eb_neg_projc(), eb_new, eb_null, eb_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.