RELIC: src/bn/relic_bn_add.c File Reference
relic_bn_add.c File Reference
Multiple precision integer arithmetic
#include "relic_core.h"
#include "relic_bn_low.h"
Functions
static void bn_add_imp (bn_t c, const bn_t a, const bn_t b)
static void bn_sub_imp (bn_t c, const bn_t a, const bn_t b)
void bn_add (bn_t c, const bn_t a, const bn_t b)
void bn_add_dig (bn_t c, const bn_t a, dig_t b)
void bn_sub (bn_t c, const bn_t a, const bn_t b)
void bn_sub_dig (bn_t c, const bn_t a, dig_t b)
Detailed Description
Implementation of the multiple precision addition and subtraction functions.
Definition in file relic_bn_add.c.
Function Documentation
bn_add_imp()
static void bn_add_imp (bn_t c, const bn_t a, const bn_t b) static
Adds two multiple precision integers, where a >= b.
Parameters
[out] c - the result.
[in] a - the first multiple precision integer to add.
[in] b - the second multiple precision integer to add.
Definition at line 46 of file relic_bn_add.c.
References bn_add1_low(), bn_addn_low(), bn_copy(), bn_grow(), bn_trim(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_THROW, and RLC_TRY.
Referenced by bn_add(), and bn_sub().
bn_sub_imp()
static void bn_sub_imp (bn_t c, const bn_t a, const bn_t b) static
Subtracts two multiple precision integers, where a >= b.
Parameters
[out] c - the result.
[in] a - the first multiple precision integer to subtract.
[in] b - the second multiple precision integer to subtract.
Definition at line 86 of file relic_bn_add.c.
References bn_copy(), bn_grow(), bn_sub1_low(), bn_subn_low(), bn_trim(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_THROW, and RLC_TRY.
Referenced by bn_add(), and bn_sub().
bn_add()
void bn_add (bn_t c, const bn_t a, const bn_t b)
Adds two multiple precision integers. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first multiple precision integer to add.
[in] b - the second multiple precision integer to add.
Definition at line 119 of file relic_bn_add.c.
References bn_add_imp(), bn_cmp_abs(), bn_sub_imp(), and RLC_LT.
Referenced by bn_div_imp(), bn_evl(), bn_gcd_ext_binar(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_lehme(), bn_gen_prime_factor(), bn_gen_prime_stron(), bn_mod_barrt(), bn_mod_inv(), bn_mod_pmers(), bn_mul_karat_imp(), bn_mxp_crt(), bn_rec_frb(), bn_rec_glv(), bn_rec_rtnaf(), bn_rec_tnaf(), bn_rec_tnaf_mod(), bn_smb_jac(), bn_sqr_karat_imp(), bn_srt(), cp_bbs_sig(), cp_bgn_dec(), cp_clb_sig(), cp_cli_sig(), cp_cls_sig(), cp_cmlhs_sig(), cp_ecdsa_sig(), cp_ecmqv_key(), cp_ecss_sig(), cp_etrs_sig(), cp_ghpe_dec(), cp_mklhs_fun(), cp_mklhs_onv(), cp_mklhs_ver(), cp_mpsb_sig(), cp_mpsb_ver(), cp_mpss_sig(), cp_psb_sig(), cp_pss_sig(), cp_rabin_dec(), cp_rabin_enc(), cp_rsa_enc(), cp_rsa_gen(), cp_rsa_sig(), cp_shpe_enc(), cp_vbnn_gen_prv(), cp_vbnn_sig(), cp_zss_sig(), eb_mul_lodah(), ep2_mul_monty(), ep3_mul_gls_imp(), ep3_mul_monty(), ep3_mul_reg_gls(), ep4_mul_monty(), ep8_mul_monty(), ep_curve_set_endom(), ep_mul_cof(), ep_mul_monty(), fp3_srt(), fp_inv_binar(), fp_inv_exgcd(), fp_inv_monty(), fp_param_set(), fp_prime_set_pairf(), fp_prime_set_pmers(), g1_mul_bct(), g1_mul_lcl(), g2_mul_bct(), g2_mul_lcl(), gt_exp_bct(), gt_exp_gls_naf(), gt_exp_gls_sac(), gt_exp_lcl(), gt_exp_reg_gls(), gt_exp_reg_sac(), mpc_mt_bct(), mpc_mt_gen(), mpc_mt_lcl(), mpc_mt_mul(), mpc_sss_key(), and pad_pkcs2().
bn_add_dig()
void bn_add_dig (bn_t c, const bn_t a, dig_t b)
Adds a multiple precision integers and a digit. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to add.
[in] b - the digit to add.
Definition at line 145 of file relic_bn_add.c.
References bn_add1_low(), bn_grow(), bn_sub1_low(), bn_trim(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_NEG, RLC_POS, RLC_THROW, and RLC_TRY.
Referenced by bn_gen_prime_factor(), bn_gen_prime_safep(), bn_gen_prime_stron(), bn_read_str(), bn_rec_frb(), bn_rec_glv(), bn_rec_naf(), bn_rec_rtnaf(), bn_rec_sac(), bn_rec_tnaf(), cp_bdpe_dec(), cp_bdpe_gen(), cp_ghpe_enc(), cp_ghpe_gen(), cp_phpe_enc(), cp_rabin_dec(), cp_rabin_enc(), cp_rsa_gen(), cp_rsapsi_ans(), cp_rsapsi_ask(), cp_shipsi_ans(), cp_shipsi_ask(), cp_shpe_enc_prv(), cp_shpe_gen(), eb_map(), ed_param_set(), ep2_mul_reg_gls(), ep3_mul_cof_fm18(), ep3_mul_gls_imp(), ep3_mul_reg_gls(), ep4_mul_cof_b24(), ep4_mul_reg_gls(), ep8_mul_reg_gls(), ep_curve_set_endom(), ep_mul_cof(), ep_param_set(), fp2_srt(), fp_crt(), fp_inv_divst(), fp_param_set(), fp_prime_set(), fp_prime_set_pairf(), fp_prime_set_pmers(), fp_smb_divst(), fp_srt(), g1_is_valid(), gt_exp_gls_sac(), gt_exp_reg_sac(), pad_pkcs2(), pp_exp_afg16(), pp_exp_fm(), pp_exp_k2(), pp_exp_k8(), pp_exp_kss(), pp_map_oatep_k12(), and pp_map_sim_oatep_k12().
bn_sub()
void bn_sub (bn_t c, const bn_t a, const bn_t b)
Subtracts a multiple precision integer from another, that is, computes c = a - b.
Parameters
[out] c - the result.
[in] a - the multiple precision integer.
[in] b - the multiple precision integer to subtract.
Definition at line 182 of file relic_bn_add.c.
References bn_add_imp(), bn_cmp_abs(), bn_sub_imp(), RLC_LT, RLC_NEG, and RLC_POS.
Referenced by bn_div_imp(), bn_gcd_binar(), bn_gcd_ext_basic(), bn_gcd_ext_binar(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_lag(), bn_mod_barrt(), bn_mod_monty_basic(), bn_mod_monty_comba(), bn_mod_pmers(), bn_mod_pre_pmers(), bn_mul_karat_imp(), bn_mxp_crt(), bn_rec_frb(), bn_rec_glv(), bn_rec_rtnaf(), bn_rec_tnaf(), bn_rec_tnaf_mod(), bn_smb_leg(), bn_sqr_karat_imp(), bn_srt(), cp_bdpe_dec(), cp_bgn_dec(), cp_bgn_dec1(), cp_bgn_dec2(), cp_cmlhs_sig(), cp_ecss_sig(), cp_ers_ext(), cp_etrs_sig(), cp_etrs_uni(), cp_etrs_ver(), cp_ghpe_dec(), cp_mpsb_sig(), cp_mpsb_ver(), cp_pokdl_prv(), cp_pokor_prv(), cp_pokor_ver(), cp_rabin_dec(), cp_smlers_ext(), cp_sokdl_sig(), cp_sokor_sig(), cp_sokor_ver(), ep_curve_set_endom(), ep_param_set(), fp_inv_binar(), fp_inv_exgcd(), fp_param_set(), fp_prime_set_pairf(), fp_prime_set_pmers(), g1_mul_lcl(), g2_mul_lcl(), gt_exp_lcl(), mpc_mt_gen(), mpc_mt_lcl(), and mpc_sss_key().
bn_sub_dig()
void bn_sub_dig (bn_t c, const bn_t a, const dig_t b)
Subtracts a digit from a multiple precision integer. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the multiple precision integer.
[in] b - the digit to subtract.
Definition at line 209 of file relic_bn_add.c.
References bn_add1_low(), bn_grow(), bn_sub1_low(), bn_trim(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_NEG, RLC_POS, RLC_THROW, and RLC_TRY.
Referenced by bn_div_imp(), bn_factor(), bn_gen_prime_safep(), bn_gen_prime_stron(), bn_is_prime_rabin(), bn_is_prime_solov(), bn_mxp_crt(), bn_rec_frb(), bn_rec_naf(), bn_rec_rtnaf(), bn_rec_tnaf(), bn_rec_tnaf_mod(), bn_smb_leg(), cp_bdpe_gen(), cp_ghpe_dec(), cp_ghpe_gen(), cp_phpe_dec(), cp_phpe_gen(), cp_rsa_gen(), cp_shipsi_gen(), cp_shpe_dec(), cp_shpe_gen(), ed_map_ell2_5mod8(), ep4_mul_cof_b24(), ep_mul_cof(), ep_param_set(), fp2_field_init(), fp2_srt(), fp3_srt(), fp4_field_init(), fp8_field_init(), fp_crt(), fp_inv_basic(), fp_is_cub(), fp_param_set(), fp_prime_set(), fp_prime_set_pairf(), fp_prime_set_pmers(), fp_smb_basic(), g1_is_valid(), g2_is_valid(), gt_is_valid(), pp_exp_fm(), pp_exp_k1(), pp_exp_kss(), pp_map_sim_tatep_k2(), pp_map_sim_weilp_k1(), pp_map_sim_weilp_k12(), pp_map_sim_weilp_k16(), pp_map_sim_weilp_k18(), pp_map_sim_weilp_k2(), pp_map_tatep_k2(), pp_map_weilp_k12(), pp_map_weilp_k16(), pp_map_weilp_k18(), and pp_map_weilp_k2().