RELIC: src/pp/relic_pp_map_k12.c File Reference
relic_pp_map_k12.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_util.h"
Functions
static void pp_mil_k12 (fp12_t r, ep2_t *t, ep2_t *q, ep_t *p, int m, bn_t a)
static void pp_mil_lit_k12 (fp12_t r, ep_t *t, ep_t *p, ep2_t *q, int m, bn_t a)
static void pp_fin_k12_oatep (fp12_t r, ep2_t t, const ep2_t q, const ep_t p)
void pp_map_tatep_k12 (fp12_t r, const ep_t p, const ep2_t q)
void pp_map_sim_tatep_k12 (fp12_t r, const ep_t *p, const ep2_t *q, int m)
void pp_map_weilp_k12 (fp12_t r, const ep_t p, const ep2_t q)
void pp_map_sim_weilp_k12 (fp12_t r, const ep_t *p, const ep2_t *q, int m)
void pp_map_oatep_k12 (fp12_t r, const ep_t p, const ep2_t q)
void pp_map_sim_oatep_k12 (fp12_t r, const ep_t *p, const ep2_t *q, int m)
Detailed Description
Implementation of pairing computation for curves with embedding degree 12.
Definition in file relic_pp_map_k12.c.
Function Documentation
pp_mil_k12()
static void pp_mil_k12 (fp12_t r, ep2_t * t, ep2_t * q, ep_t * p, int m, bn_t a) static
Compute the Miller loop for pairings of type G_2 x G_1 over the bits of a given parameter represented in sparse form.
Parameters
[out] r - the result.
[out] t - the resulting point.
[in] q - the vector of first arguments in affine coordinates.
[in] p - the vector of second arguments in affine coordinates.
[in] n - the number of pairings to evaluate.
[in] a - the loop parameter.
Definition at line 51 of file relic_pp_map_k12.c.
References bn_bits(), bn_rec_naf(), ep2_copy(), ep2_free, ep2_neg(), ep2_new, ep2_null, ep_free, ep_neg(), ep_new, ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp12_free, fp12_mul_dxs, fp12_new, fp12_null, fp12_sqr, fp12_zero(), fp_add, fp_neg, pp_add_k12, pp_dbl_k12, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by pp_map_oatep_k12(), pp_map_sim_oatep_k12(), pp_map_sim_weilp_k12(), and pp_map_weilp_k12().
pp_mil_lit_k12()
static void pp_mil_lit_k12 (fp12_t r, ep_t * t, ep_t * p, ep2_t * q, int m, bn_t a) static
Compute the Miller loop for pairings of type G_1 x G_2 over the bits of a given parameter.
Parameters
[out] r - the result.
[out] t - the resulting point.
[in] p - the first pairing argument in affine coordinates.
[in] q - the second pairing argument in affine coordinates.
[in] n - the number of pairings to evaluate.
[in] a - the loop parameter.
Definition at line 147 of file relic_pp_map_k12.c.
References bn_bits(), bn_get_bit(), ep2_free, ep2_neg(), ep2_new, ep2_null, ep_copy(), ERR_CAUGHT, ERR_NO_MEMORY, fp12_free, fp12_mul, fp12_new, fp12_null, fp12_sqr, fp12_zero(), pp_add_lit_k12(), pp_dbl_lit_k12(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by pp_map_sim_tatep_k12(), pp_map_sim_weilp_k12(), pp_map_tatep_k12(), and pp_map_weilp_k12().
pp_fin_k12_oatep()
static void pp_fin_k12_oatep (fp12_t r, ep2_t t, const ep2_t q, const ep_t p) static
Compute the final lines for optimal ate pairings.
Parameters
[out] r - the result.
[out] t - the resulting point.
[in] q - the first point of the pairing, in G_2.
[in] p - the second point of the pairing, in G_1.
Definition at line 199 of file relic_pp_map_k12.c.
References ep2_frb(), ep2_free, ep2_neg(), ep2_new, ep2_null, ERR_CAUGHT, fp12_free, fp12_mul_dxs, fp12_new, fp12_null, fp12_zero(), fp2_set_dig(), pp_add_k12, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_map_oatep_k12(), and pp_map_sim_oatep_k12().
pp_map_tatep_k12()
void pp_map_tatep_k12 (fp12_t r, const ep_t p, const ep2_t q)
Computes the Tate pairing of two points in a parameterized elliptic curve with embedding degree 12.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 239 of file relic_pp_map_k12.c.
References bn_free, bn_new, bn_null, ep2_free, ep2_is_infty(), ep2_new, ep2_norm(), ep2_null, ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, fp12_set_dig(), pp_exp_k12(), pp_mil_lit_k12(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_map_sim_tatep_k12()
void pp_map_sim_tatep_k12 (fp12_t r, const ep_t * p, const ep2_t * q, int m)
Computes the Tate multi-pairing in a parameterized elliptic curve with embedding degree 12.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 276 of file relic_pp_map_k12.c.
References bn_free, bn_new, bn_null, ep2_free, ep2_is_infty(), ep2_new, ep2_norm(), ep2_null, ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp12_set_dig(), pp_exp_k12(), pp_mil_lit_k12(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
pp_map_weilp_k12()
void pp_map_weilp_k12 (fp12_t r, const ep_t p, const ep2_t q)
Computes the Weil pairing of two points in a parameterized elliptic curve with embedding degree 12.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 333 of file relic_pp_map_k12.c.
References bn_free, bn_new, bn_null, bn_sub_dig(), ep2_free, ep2_is_infty(), ep2_new, ep2_norm(), ep2_null, ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, fp12_free, fp12_inv(), fp12_inv_cyc(), fp12_mul, fp12_new, fp12_null, fp12_set_dig(), pp_mil_k12(), pp_mil_lit_k12(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_map_sim_weilp_k12()
void pp_map_sim_weilp_k12 (fp12_t r, const ep_t * p, const ep2_t * q, int m)
Computes the Weil multi-pairing in a parameterized elliptic curve with embedding degree 12.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 387 of file relic_pp_map_k12.c.
References bn_free, bn_new, bn_null, bn_sub_dig(), ep2_free, ep2_is_infty(), ep2_new, ep2_norm(), ep2_null, ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp12_free, fp12_inv(), fp12_inv_cyc(), fp12_mul, fp12_new, fp12_null, fp12_set_dig(), pp_mil_k12(), pp_mil_lit_k12(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
pp_map_oatep_k12()
void pp_map_oatep_k12 (fp12_t r, const ep_t p, const ep2_t q)
Computes the optimal ate pairing of two points in a parameterized elliptic curve with embedding degree 12.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 463 of file relic_pp_map_k12.c.
References bn_add_dig(), bn_free, bn_mul_dig(), bn_new, bn_null, bn_sign(), ep2_free, ep2_is_infty(), ep2_neg(), ep2_new, ep2_norm(), ep2_null, EP_B12, EP_BN, ep_curve_is_pairf(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, fp12_inv_cyc(), fp12_set_dig(), fp_prime_get_par(), pp_exp_k12(), pp_fin_k12_oatep(), pp_mil_k12(), RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
pp_map_sim_oatep_k12()
void pp_map_sim_oatep_k12 (fp12_t r, const ep_t * p, const ep2_t * q, int m)
Computes the optimal ate multi-pairing in a parameterized elliptic curve with embedding degree 12.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 523 of file relic_pp_map_k12.c.
References bn_add_dig(), bn_free, bn_mul_dig(), bn_new, bn_null, bn_sign(), ep2_free, ep2_is_infty(), ep2_neg(), ep2_new, ep2_norm(), ep2_null, EP_B12, EP_BN, ep_curve_is_pairf(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp12_inv_cyc(), fp12_set_dig(), fp_prime_get_par(), pp_exp_k12(), pp_fin_k12_oatep(), pp_mil_k12(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.