RELIC: src/relic_test.c File Reference
relic_test.c File Reference
Core functions
#include "relic_test.h"
#include "relic_util.h"
#include "relic_core.h"
Macros
#define FAIL_COLOR 31
#define PASS_COLOR 32
#define CMD_SET 27
#define CMD_RESET 0
#define CMD_ATTR 1
Functions
static void cache_default_color (void)
static void fail_font (void)
static void pass_font (void)
static void reset_font (void)
void test_fail (void)
void test_pass (void)
Detailed Description
Implementation of useful test routines.
Definition in file relic_test.c.
Macro Definition Documentation
FAIL_COLOR
#define FAIL_COLOR 31
Color of the string printed when the test fails (red).
Definition at line 55 of file relic_test.c.
Referenced by fail_font().
PASS_COLOR
#define PASS_COLOR 32
Color of the string printed when the test passes (green).
Definition at line 64 of file relic_test.c.
Referenced by pass_font().
CMD_SET
#define CMD_SET 27
Command to set terminal colors.
Definition at line 70 of file relic_test.c.
Referenced by fail_font(), pass_font(), and reset_font().
CMD_RESET
#define CMD_RESET 0
Command to reset terminal colors.
Definition at line 75 of file relic_test.c.
Referenced by reset_font().
CMD_ATTR
#define CMD_ATTR 1
Print with bright attribute.
Definition at line 80 of file relic_test.c.
Referenced by fail_font(), and pass_font().
Function Documentation
cache_default_color()
static void cache_default_color (void) static
Copies default color to global variable.
Definition at line 85 of file relic_test.c.
Referenced by fail_font(), and pass_font().
fail_font()
static void fail_font (void) static
Changes font to test failure mode.
Definition at line 97 of file relic_test.c.
References cache_default_color(), CMD_ATTR, CMD_SET, FAIL_COLOR, and util_print.
Referenced by test_fail().
pass_font()
static void pass_font (void) static
Changes font to test pass mode.
Definition at line 112 of file relic_test.c.
References cache_default_color(), CMD_ATTR, CMD_SET, PASS_COLOR, and util_print.
Referenced by test_pass().
reset_font()
static void reset_font (void) static
Resets font to default.
Definition at line 127 of file relic_test.c.
References CMD_RESET, CMD_SET, and util_print.
Referenced by test_fail(), and test_pass().
test_fail()
void test_fail (void)
Prints a string indicating that the test failed.
Definition at line 142 of file relic_test.c.
References fail_font(), reset_font(), and util_print.
test_pass()
void test_pass (void)
Prints a string indicating that the test passed.
Definition at line 148 of file relic_test.c.
References pass_font(), reset_font(), and util_print.