RELIC: src/cp/relic_cp_ecdsa.c File Reference
relic_cp_ecdsa.c File Reference
Cryptographic protocols
#include "relic.h"
Functions
int cp_ecdsa_gen (bn_t d, ec_t q)
int cp_ecdsa_sig (bn_t r, bn_t s, const uint8_t *msg, size_t len, int hash, const bn_t d)
int cp_ecdsa_ver (const bn_t r, const bn_t s, const uint8_t *msg, size_t len, int hash, const ec_t q)
Detailed Description
Implementation of the ECDSA protocol.
Definition in file relic_cp_ecdsa.c.
Function Documentation
cp_ecdsa_gen()
int cp_ecdsa_gen (bn_t d, ec_t q)
Generates an ECDSA key pair.
Parameters
[out] d - the private key.
[in] q - the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_ecdsa.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), ec_curve_get_ord, ec_mul_gen, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
Referenced by cp_cmlhs_gen().
cp_ecdsa_sig()
int cp_ecdsa_sig (bn_t r, bn_t s, const uint8_t * msg, size_t len, int hash, const bn_t d)
Signs a message using ECDSA.
Parameters
[out] r - the first component of the signature.
[out] s - the second component of the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] hash - the flag to indicate the message format.
[in] d - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 61 of file relic_cp_ecdsa.c.
References bn_add(), bn_bits(), bn_free, bn_is_zero(), bn_mod, bn_mod_inv(), bn_mul, bn_new, bn_null, bn_rand_mod(), bn_read_bin(), bn_rsh(), ec_curve_get_ord, ec_free, ec_get_x, ec_mul_gen, ec_new, ec_null, md_map, RLC_CATCH_ANY, RLC_CEIL, RLC_ERR, RLC_FINALLY, RLC_MD_LEN, RLC_OK, and RLC_TRY.
Referenced by cp_cmlhs_sig().
cp_ecdsa_ver()
int cp_ecdsa_ver (const bn_t r, const bn_t s, const uint8_t * msg, size_t len, int hash, const ec_t q)
Verifies a message signed with ECDSA using the basic method.
Parameters
[out] r - the first component of the signature.
[out] s - the second component of the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] hash - the flag to indicate the message format.
[in] q - the public key.
Returns
a boolean value indicating if the signature is valid.
Definition at line 125 of file relic_cp_ecdsa.c.
References bn_bits(), bn_cmp(), bn_free, bn_is_zero(), bn_mod, bn_mod_inv(), bn_mul, bn_new, bn_null, bn_read_bin(), bn_rsh(), bn_sign(), dv_cmp_sec(), ec_curve_get_ord, ec_free, ec_get_x, ec_is_infty, ec_mul_sim_gen, ec_new, ec_null, ec_on_curve, ERR_CAUGHT, md_map, RLC_CATCH_ANY, RLC_CEIL, RLC_FINALLY, RLC_LT, RLC_MD_LEN, RLC_MIN, RLC_NE, RLC_POS, RLC_THROW, and RLC_TRY.
Referenced by cp_cmlhs_onv(), and cp_cmlhs_ver().