RELIC: src/md/sha224-256.c File Reference
sha224-256.c File Reference
#include "sha.h"
Macros
#define SHA256_SHR(bits, word)
#define SHA256_ROTL(bits, word)
#define SHA256_ROTR(bits, word)
#define SHA256_SIGMA0(word)
#define SHA256_SIGMA1(word)
#define SHA256_sigma0(word)
#define SHA256_sigma1(word)
#define SHA224_256AddLength(context, length)
Functions
static void SHA224_256Finalize (SHA256Context *context, uint8_t Pad_Byte)
static void SHA224_256PadMessage (SHA256Context *context, uint8_t Pad_Byte)
static void SHA224_256ProcessMessageBlock (SHA256Context *context)
static int SHA224_256Reset (SHA256Context *context, uint32_t *H0)
static int SHA224_256ResultN (SHA256Context *context, uint8_t Message_Digest[], int HashSize)
int SHA224Reset (SHA224Context *context)
int SHA224Input (SHA224Context *context, const uint8_t *message_array, unsigned int length)
int SHA224FinalBits (SHA224Context *context, const uint8_t message_bits, unsigned int length)
int SHA224Result (SHA224Context *context, uint8_t Message_Digest[SHA224HashSize])
int SHA256Reset (SHA256Context *context)
int SHA256Input (SHA256Context *context, const uint8_t *message_array, unsigned int length)
int SHA256FinalBits (SHA256Context *context, const uint8_t message_bits, unsigned int length)
int SHA256Result (SHA256Context *context, uint8_t Message_Digest[SHA256HashSize])
Variables
static uint32_t SHA224_H0 [SHA256HashSize/4]
static uint32_t SHA256_H0 [SHA256HashSize/4]
Macro Definition Documentation
SHA256_SHR
#define SHA256_SHR (bits, word)
Value:
((word) >> (bits))
Definition at line 42 of file sha224-256.c.
SHA256_ROTL
#define SHA256_ROTL (bits, word)
Value:
  (((word) << (bits)) | ((word) >> (32-(bits))))
Definition at line 43 of file sha224-256.c.
SHA256_ROTR
#define SHA256_ROTR (bits, word)
Value:
  (((word) >> (bits)) | ((word) << (32-(bits))))
Definition at line 45 of file sha224-256.c.
SHA256_SIGMA0
#define SHA256_SIGMA0 (word)
Value:
  (SHA256_ROTR( 2,word) ^ SHA256_ROTR(13,word) ^ SHA256_ROTR(22,word))
Definition at line 49 of file sha224-256.c.
Referenced by SHA224_256ProcessMessageBlock().
SHA256_SIGMA1
#define SHA256_SIGMA1 (word)
Value:
  (SHA256_ROTR( 6,word) ^ SHA256_ROTR(11,word) ^ SHA256_ROTR(25,word))
Definition at line 51 of file sha224-256.c.
Referenced by SHA224_256ProcessMessageBlock().
SHA256_sigma0
#define SHA256_sigma0 (word)
Value:
  (SHA256_ROTR( 7,word) ^ SHA256_ROTR(18,word) ^ SHA256_SHR( 3,word))
Definition at line 53 of file sha224-256.c.
Referenced by SHA224_256ProcessMessageBlock().
SHA256_sigma1
#define SHA256_sigma1 (word)
Value:
  (SHA256_ROTR(17,word) ^ SHA256_ROTR(19,word) ^ SHA256_SHR(10,word))
Definition at line 55 of file sha224-256.c.
Referenced by SHA224_256ProcessMessageBlock().
SHA224_256AddLength
#define SHA224_256AddLength (context, length)
Value:
  (addTemp = (context)->Length_Low, (context)->Corrupted = \
    (((context)->Length_Low += (length)) < addTemp) &&     \
    (++(context)->Length_High == 0) ? 1 : 0)
Definition at line 61 of file sha224-256.c.
Referenced by SHA256FinalBits(), and SHA256Input().
Function Documentation
SHA224_256Finalize()
static void SHA224_256Finalize (SHA256Context * context, uint8_t Pad_Byte) static
Definition at line 351 of file sha224-256.c.
References SHA256Context::Computed, SHA256Context::Length_High, SHA256Context::Length_Low, SHA256Context::Message_Block, SHA224_256PadMessage(), and SHA256_Message_Block_Size.
Referenced by SHA224_256ResultN(), and SHA256FinalBits().
SHA224_256PadMessage()
static void SHA224_256PadMessage (SHA256Context * context, uint8_t Pad_Byte) static
Definition at line 388 of file sha224-256.c.
References SHA256Context::Length_High, SHA256Context::Length_Low, SHA256Context::Message_Block, SHA256Context::Message_Block_Index, SHA224_256ProcessMessageBlock(), and SHA256_Message_Block_Size.
Referenced by SHA224_256Finalize().
SHA224_256ProcessMessageBlock()
static void SHA224_256ProcessMessageBlock (SHA256Context * context) static
Definition at line 442 of file sha224-256.c.
References G, SHA256Context::Intermediate_Hash, SHA256Context::Message_Block, SHA256Context::Message_Block_Index, SHA256_SIGMA0, SHA256_sigma0, SHA256_SIGMA1, SHA256_sigma1, SHA_Ch, and SHA_Maj.
Referenced by SHA224_256PadMessage(), and SHA256Input().
SHA224_256Reset()
static int SHA224_256Reset (SHA256Context * context, uint32_t * H0) static
Definition at line 528 of file sha224-256.c.
References SHA256Context::Computed, SHA256Context::Corrupted, SHA256Context::Intermediate_Hash, SHA256Context::Length_High, SHA256Context::Length_Low, SHA256Context::Message_Block_Index, shaNull, and shaSuccess.
Referenced by SHA224Reset(), and SHA256Reset().
SHA224_256ResultN()
static int SHA224_256ResultN (SHA256Context * context, uint8_t Message_Digest[], int HashSize) static
Definition at line 572 of file sha224-256.c.
References SHA256Context::Computed, SHA256Context::Corrupted, SHA256Context::Intermediate_Hash, SHA224_256Finalize(), shaNull, and shaSuccess.
Referenced by SHA224Result(), and SHA256Result().
SHA224Reset()
int SHA224Reset (SHA224Context * context)
Definition at line 102 of file sha224-256.c.
References SHA224_256Reset(), and SHA224_H0.
Referenced by md_map_sh224().
SHA224Input()
int SHA224Input (SHA224Context * context, const uint8_t * message_array, unsigned int length)
Definition at line 127 of file sha224-256.c.
References SHA256Input().
Referenced by md_map_sh224().
SHA224FinalBits()
int SHA224FinalBits (SHA224Context * context, const uint8_t message_bits, unsigned int length)
Definition at line 152 of file sha224-256.c.
References SHA256FinalBits().
SHA224Result()
int SHA224Result (SHA224Context * context, uint8_t Message_Digest[SHA224HashSize])
Definition at line 176 of file sha224-256.c.
References SHA224_256ResultN(), and SHA224HashSize.
Referenced by md_map_sh224().
SHA256Reset()
int SHA256Reset (SHA256Context * context)
Definition at line 195 of file sha224-256.c.
References SHA224_256Reset(), and SHA256_H0.
Referenced by md_map_sh256().
SHA256Input()
int SHA256Input (SHA256Context * context, const uint8_t * message_array, unsigned int length)
Definition at line 219 of file sha224-256.c.
References SHA256Context::Computed, SHA256Context::Corrupted, SHA256Context::Message_Block, SHA256Context::Message_Block_Index, SHA224_256AddLength, SHA224_256ProcessMessageBlock(), SHA256_Message_Block_Size, shaNull, shaStateError, and shaSuccess.
Referenced by md_map_sh256(), and SHA224Input().
SHA256FinalBits()
int SHA256FinalBits (SHA256Context * context, const uint8_t message_bits, unsigned int length)
Definition at line 271 of file sha224-256.c.
References SHA256Context::Computed, SHA256Context::Corrupted, SHA224_256AddLength, SHA224_256Finalize(), shaNull, shaStateError, and shaSuccess.
Referenced by SHA224FinalBits().
SHA256Result()
int SHA256Result (SHA256Context * context, uint8_t Message_Digest[SHA256HashSize])
Definition at line 328 of file sha224-256.c.
References SHA224_256ResultN(), and SHA256HashSize.
Referenced by md_map_sh256().
Variable Documentation
SHA224_H0
uint32_t SHA224_H0[SHA256HashSize/4] static
Initial value:
= {
    0xC1059ED8, 0x367CD507, 0x3070DD17, 0xF70E5939,
    0xFFC00B31, 0x68581511, 0x64F98FA7, 0xBEFA4FA4
}
Definition at line 77 of file sha224-256.c.
Referenced by SHA224Reset().
SHA256_H0
uint32_t SHA256_H0[SHA256HashSize/4] static
Initial value:
= {
  0x6A09E667, 0xBB67AE85, 0x3C6EF372, 0xA54FF53A,
  0x510E527F, 0x9B05688C, 0x1F83D9AB, 0x5BE0CD19
}
Definition at line 83 of file sha224-256.c.
Referenced by SHA256Reset().