RELIC: src/md/relic_md_kdf.c File Reference
relic_md_kdf.c File Reference
Hash functions
#include <string.h>
#include "relic_conf.h"
#include "relic_core.h"
#include "relic_util.h"
#include "relic_md.h"
Functions
static void nist_kdf (uint8_t *key, size_t key_len, const uint8_t *in, size_t in_len, dig_t value)
void md_mgf (uint8_t *key, size_t key_len, const uint8_t *in, size_t in_len)
void md_kdf (uint8_t *key, size_t key_len, const uint8_t *in, size_t in_len)
Detailed Description
Implementation of a Key Derivation Function and Mask Generation Function.
Definition in file relic_md_kdf.c.
Function Documentation
nist_kdf()
static void nist_kdf (uint8_t * key, size_t key_len, const uint8_t * in, size_t in_len, dig_t value) static
Definition at line 43 of file relic_md_kdf.c.
References ERR_NO_MEMORY, ERR_NO_VALID, md_map, RLC_ALLOCA, RLC_CEIL, RLC_FREE, RLC_MD_LEN, RLC_THROW, and util_conv_big().
Referenced by md_kdf(), and md_mgf().
md_mgf()
void md_mgf (uint8_t * mask, size_t mask_len, const uint8_t * in, size_t in_len)
Derives a mask from shared secret material through the PKCS#1 2.1 MGF1 function. This is the same as the standardized KDF1 key derivation function.
Parameters
[out] key - the resulting mask.
[in] key_len - the intended mask length in bytes.
[in] in - the shared secret.
[in] in_len - the length of the shared secret in bytes.
Definition at line 86 of file relic_md_kdf.c.
References nist_kdf().
Referenced by pad_pkcs2().
md_kdf()
void md_kdf (uint8_t * key, size_t key_len, const uint8_t * in, size_t in_len)
Derives a key from shared secret material through the standardized KDF2 function.
Parameters
[out] key - the resulting key.
[in] key_len - the intended key length in bytes.
[in] in - the shared secret.
[in] in_len - the length of the shared secret in bytes.
Definition at line 90 of file relic_md_kdf.c.
References nist_kdf().
Referenced by cp_ecdh_key(), cp_ecies_dec(), cp_ecies_enc(), cp_ecmqv_key(), and cp_sokaka_key().