RELIC: src/cp/relic_cp_ecmqv.c File Reference
relic_cp_ecmqv.c File Reference
Cryptographic protocols
#include "relic.h"
Functions
int cp_ecmqv_gen (bn_t d, ec_t q)
int cp_ecmqv_key (uint8_t *key, size_t key_len, const bn_t d1, const bn_t d2, const ec_t q2u, const ec_t q1v, const ec_t q2v)
Detailed Description
Implementation of the ECMQV protocol.
Definition in file relic_cp_ecmqv.c.
Function Documentation
cp_ecmqv_gen()
int cp_ecmqv_gen (bn_t d, ec_t q)
Generate an ECMQV key pair.
Should also be used to generate the ephemeral key pair.
Parameters
[out] d - the private key.
[out] q - the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_ecmqv.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), ec_curve_get_ord, ec_mul_gen, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_ecmqv_key()
int cp_ecmqv_key (uint8_t * key, size_t key_len, const bn_t d1, const bn_t d2, const ec_t q2u, const ec_t q1v, const ec_t q2v)
Derives a shared secret using ECMQV.
Parameters
[out] key - the shared key.
[int] key_len - the intended shared key length in bytes.
[in] d1 - the private key.
[in] d2 - the ephemeral private key.
[in] q2u - the ephemeral public key.
[in] q1v - the point received from the other party.
[in] q2v - the ephemeral point received from the party.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 61 of file relic_cp_ecmqv.c.
References bn_add(), bn_bits(), bn_free, bn_mod, bn_mod_2b(), bn_mul, bn_new, bn_null, bn_set_bit(), bn_size_bin(), bn_write_bin(), ec_curve_get_ord, ec_free, ec_get_x, ec_mul_sim, ec_new, ec_null, md_kdf(), RLC_CATCH_ANY, RLC_ERR, RLC_FC_BYTES, RLC_FINALLY, RLC_OK, and RLC_TRY.