RELIC: include/relic_bench.h File Reference
relic_bench.h File Reference
Automated benchmarks
#include "relic_conf.h"
#include "relic_label.h"
#include "relic_util.h"
#include <time.h>
Macros
#define BENCH_ONE(LABEL, FUNCTION, N)
#define BENCH_FEW(LABEL, FUNCTION, N)
#define BENCH_RUN(LABEL)
#define BENCH_END
#define BENCH_DIV(N)
#define BENCH_ADD(FUNCTION)
Typedefs
typedef clock_t ben_t
Functions
void bench_init (void)
void bench_clean (void)
void bench_overhead (void)
void bench_reset (void)
void bench_before (void)
void bench_after (void)
void bench_compute (int benches)
void bench_print (void)
ull_t bench_total (void)
Detailed Description
Interface of useful routines for benchmarking.
Definition in file relic_bench.h.
Macro Definition Documentation
BENCH_ONE
#define BENCH_ONE (LABEL, FUNCTION, N)
Value:
    bench_reset();                                                          \
    util_print("BENCH: " LABEL "%*c = ", (int)(32 - strlen(LABEL)), ' ');   \
    bench_before();                                                         \
    FUNCTION;                                                               \
    bench_after();                                                          \
    bench_compute(N);                                                       \
    bench_print();                                                          \
Runs a new benchmark once.
Parameters
[in] LABEL - the label for this benchmark.
[in] FUNCTION - the function to benchmark.
[in] N - the amortization factor.
Definition at line 66 of file relic_bench.h.
BENCH_FEW
#define BENCH_FEW (LABEL, FUNCTION, N)
Value:
    bench_reset();                                                          \
    util_print("BENCH: " LABEL "%*c = ", (int)(32 - strlen(LABEL)), ' ');   \
    bench_before();                                                         \
    for (int i = 0; i < BENCH; i++) {                                       \
        FUNCTION;                                                           \
    }                                                                       \
    bench_after();                                                          \
    bench_compute(BENCH * (N));                                             \
    bench_print();                                                          \
Runs a new benchmark a small number of times and prints the average timing amortized by N.
Parameters
[in] LABEL - the label for this benchmark.
[in] FUNCTION - the function to benchmark.
[in] N - the amortization factor.
Definition at line 83 of file relic_bench.h.
BENCH_RUN
#define BENCH_RUN (LABEL)
Value:
    bench_reset();                                                          \
    util_print("BENCH: " LABEL "%*c = ", (int)(32 - strlen(LABEL)), ' ');   \
    for (int _b = 0; _b < BENCH; _b++)  {                                   \
Runs a new benchmark.
Parameters
[in] LABEL - the label for this benchmark.
Definition at line 99 of file relic_bench.h.
BENCH_END
#define BENCH_END
Value:
    }                                                                       \
    bench_compute(BENCH * BENCH);                                           \
    bench_print()                                                           \
Prints the average timing of each execution in the chosen metric.
Definition at line 107 of file relic_bench.h.
BENCH_DIV
#define BENCH_DIV (N)
Value:
    }                                                                       \
    bench_compute(BENCH * BENCH * N);                                       \
    bench_print()                                                           \
Prints the average timing of each execution amortized by N.
Parameters
N - the amortization factor.
Definition at line 117 of file relic_bench.h.
BENCH_ADD
#define BENCH_ADD (FUNCTION)
Value:
    if (BENCH > 1) FUNCTION;                                                \
    bench_before();                                                         \
    for (int _b = 0; _b < BENCH; _b++) {                                    \
        FUNCTION;                                                           \
    }                                                                       \
    bench_after();                                                          \
Measures the time of one execution and adds it to the benchmark total.
Parameters
[in] FUNCTION - the function executed.
Definition at line 127 of file relic_bench.h.
Typedef Documentation
ben_t
typedef clock_t ben_t
Timer type.
Definition at line 155 of file relic_bench.h.
Function Documentation
bench_init()
void bench_init (void)
Initializes the benchmarking module.
Definition at line 131 of file relic_bench.c.
References core_get(), ERR_NO_FILE, and RLC_THROW.
Referenced by core_init().
bench_clean()
void bench_clean (void)
Finalizes the benchmarking module.
Definition at line 240 of file relic_bench.c.
References core_get().
Referenced by core_clean().
bench_overhead()
void bench_overhead (void)
Measures and prints benchmarking overhead.
Referenced by conf_print().
bench_reset()
void bench_reset (void)
Resets the benchmark data.
Parameters
[in] label - the benchmark label.
Definition at line 155 of file relic_bench.c.
References core_get(), and _ctx_t::total.
bench_before()
void bench_before (void)
Measures the time before a benchmark is executed.
Definition at line 161 of file relic_bench.c.
References arch_cycles(), _ctx_t::before, CLOCK, and core_get().
bench_after()
void bench_after (void)
Measures the time after a benchmark was started and adds it to the total.
Definition at line 175 of file relic_bench.c.
References _ctx_t::after, arch_cycles(), _ctx_t::before, CLOCK, core_get(), and _ctx_t::total.
bench_compute()
void bench_compute (int benches)
Computes the mean elapsed time between the start and the end of a benchmark.
Parameters
benches - the number of executed benchmarks.
Definition at line 206 of file relic_bench.c.
References core_get(), and _ctx_t::total.
bench_print()
void bench_print (void)
Prints the last benchmark.
Definition at line 219 of file relic_bench.c.
References core_get(), _ctx_t::total, and util_print.
bench_total()
ull_t bench_total (void)
Returns the result of the last benchmark.
Returns
the last benchmark.
Definition at line 236 of file relic_bench.c.
References core_get(), and _ctx_t::total.