RELIC: src/ep/relic_ep_map.c File Reference
relic_ep_map.c File Reference
Elliptic curves over prime fields
#include "relic_core.h"
#include "relic_md.h"
#include "relic_ep_map_tmpl.h"
Macros
#define MAP_STRING (const uint8_t *)"RELIC"
#define EP_MAP_CONVERT_BYTES(IDX)
#define EP_MAP_APPLY_MAP(PT)
Functions
TMPL_MAP_HORNER (fp, fp_st)
TMPL_MAP_ISOGENY_MAP (ep, fp, iso)
TMPL_MAP_SSWU (ep, fp, dig_t)
TMPL_MAP_SVDW (ep, fp, dig_t)
static void ep_map_basic_impl (ep_t p, const uint8_t *bytes, size_t len)
static void ep_map_sswum_impl (ep_t p, const uint8_t *bytes, size_t len, void(*const map_fn)(ep_t, const fp_t))
static void ep_map_swift_impl (ep_t p, const uint8_t *random, size_t len)
void ep_map_basic (ep_t p, const uint8_t *msg, size_t len)
void ep_map_sswum (ep_t p, const uint8_t *msg, size_t len)
void ep_map_swift (ep_t p, const uint8_t *msg, size_t len)
void ep_map_rnd (ep_t p, const uint8_t *uniform_bytes, size_t len)
Detailed Description
Implementation of hashing to a prime elliptic curve.
Definition in file relic_ep_map.c.
Macro Definition Documentation
MAP_STRING
#define MAP_STRING (const uint8_t *)"RELIC"
Domain separation string.
Definition at line 43 of file relic_ep_map.c.
Referenced by ep_map_basic(), ep_map_sswum(), and ep_map_swift().
EP_MAP_CONVERT_BYTES
#define EP_MAP_CONVERT_BYTES (IDX)
Value:
    do {                                                                    \
        bn_read_bin(k, bytes + IDX * elm, elm);                     \
        fp_prime_conv(t, k);                                                \
    } while (0)
Referenced by ep_map_sswum_impl().
EP_MAP_APPLY_MAP
#define EP_MAP_APPLY_MAP (PT)
Value:
    do {                                                                    \
        /* check sign of t */                                               \
        neg = fp_is_even(t);                                                \
        /* convert */                                                       \
        map_fn(PT, t);                                                      \
        /* compare sign of y and sign of t; fix if necessary */             \
        neg = neg != fp_is_even(PT->y);                                     \
        fp_neg(t, PT->y);                                                   \
        dv_copy_sec(PT->y, t, RLC_FP_DIGS, neg);                            \
    } while (0)
Referenced by ep_map_sswum_impl().
Function Documentation
TMPL_MAP_HORNER()
TMPL_MAP_HORNER (fp , fp_st)
Evaluate a polynomial represented by its coefficients over a using Horner's rule. Might promove to an API if needed elsewhere in the future.
Parameters
[out] c - the result.
[in] a - the input value.
[in] coeffs - the vector of coefficients in the polynomial.
[in] deg - the degree of the polynomial.
TMPL_MAP_ISOGENY_MAP()
TMPL_MAP_ISOGENY_MAP (ep , fp , iso)
Generic isogeny map evaluation for use with SSWU map.
TMPL_MAP_SSWU()
TMPL_MAP_SSWU (ep , fp , dig_t)
Simplified SWU mapping from Section 4 of "Fast and simple constant-time hashing to the BLS12-381 Elliptic Curve"
TMPL_MAP_SVDW()
TMPL_MAP_SVDW (ep , fp , dig_t)
Shallue–van de Woestijne map, based on the definition from draft-irtf-cfrg-hash-to-curve-06, Section 6.6.1
ep_map_basic_impl()
static void ep_map_basic_impl (ep_t p, const uint8_t * bytes, size_t len) static
Definition at line 77 of file relic_ep_map.c.
References BASIC, bn_free, bn_new, bn_null, bn_read_bin(), ep_mul_cof(), ep_rhs(), ERR_CAUGHT, fp_add_dig(), fp_free, fp_new, fp_null, fp_prime_conv(), fp_set_dig(), fp_smb, fp_srt(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep_map_basic(), and ep_map_rnd().
ep_map_sswum_impl()
static void ep_map_sswum_impl (ep_t p, const uint8_t * bytes, size_t len, void(* map_fn)(ep_t, const fp_t)) static
Maps an array of uniformly random bytes to a point in a prime elliptic curve. That array is expected to have a length suitable for two field elements plus extra bytes for uniformity.
Parameters
[out] p - the result.
[in] uniform_bytes - the array of uniform bytes to map.
[in] len - the array length in bytes.
[in] map_fn - the mapping function.
Definition at line 126 of file relic_ep_map.c.
References bn_free, bn_new, bn_null, ep_add, ep_free, EP_MAP_APPLY_MAP, EP_MAP_CONVERT_BYTES, ep_mul_cof(), ep_new, ep_norm(), ep_null, ep_param_level(), ERR_CAUGHT, fp_free, fp_new, fp_null, FP_PRIME, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, RLC_TRY, and TMPL_MAP_CALL_ISOMAP.
Referenced by ep_map_rnd(), and ep_map_sswum().
ep_map_swift_impl()
static void ep_map_swift_impl (ep_t p, const uint8_t * random, size_t len) static
Definition at line 193 of file relic_ep_map.c.
References BASIC, bn_free, bn_new, bn_null, bn_read_bin(), core_get(), _ctx_t::ep_b, ep_curve_get_a(), ep_curve_opt_a(), ep_curve_opt_b(), _ctx_t::ep_map_c, ep_mul_cof(), ep_rhs(), ep_set_infty(), ERR_CAUGHT, ERR_NO_VALID, fp_add, fp_add_dig(), fp_copy_sec(), fp_dbl, fp_free, fp_hlv, fp_inv, fp_inv_sim(), fp_is_even(), fp_is_sqr(), fp_is_zero(), fp_mul, fp_mul_dig(), fp_neg, fp_new, fp_null, fp_prime_conv(), fp_set_dig(), fp_sqr, fp_srt(), fp_sub, fp_sub_dig(), RLC_CATCH_ANY, RLC_FINALLY, RLC_ONE, RLC_THROW, RLC_TRY, and RLC_ZERO.
Referenced by ep_map_rnd(), and ep_map_swift().
ep_map_basic()
void ep_map_basic (ep_t p, const uint8_t * msg, size_t len)
Maps a byte array to a point in a prime elliptic curve using the hash and increment approach.
Parameters
[out] p - the result.
[in] msg - the byte array to map.
[in] len - the array length in bytes.
Definition at line 442 of file relic_ep_map.c.
References ep_map_basic_impl(), ep_param_level(), ERR_CAUGHT, FP_PRIME, MAP_STRING, md_xmd, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
ep_map_sswum()
void ep_map_sswum (ep_t p, const uint8_t * msg, size_t len)
Maps a byte array to a point in a prime elliptic curve using the (Simplified) Shallue-van de Woestijne-Ulas map.
Parameters
[out] p - the result.
[in] msg - the byte array to map.
[in] len - the array length in bytes.
Definition at line 463 of file relic_ep_map.c.
References ep_curve_is_ctmap(), ep_curve_opt_a(), ep_curve_opt_b(), ep_map_sswum_impl(), ep_param_level(), ERR_CAUGHT, FP_PRIME, MAP_STRING, md_xmd, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, RLC_TRY, and RLC_ZERO.
ep_map_swift()
void ep_map_swift (ep_t p, const uint8_t * msg, size_t len)
Maps a byte array to a point in a prime elliptic curve using the SwiftEC approach.
Parameters
[out] p - the result.
[in] msg - the byte array to map.
[in] len - the array length in bytes.
Definition at line 494 of file relic_ep_map.c.
References core_get(), ep_curve_is_super(), ep_map_swift_impl(), ep_param_level(), ERR_CAUGHT, ERR_NO_CONFIG, FP_PRIME, MAP_STRING, md_xmd, _ctx_t::mod18, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
ep_map_rnd()
void ep_map_rnd (ep_t p, const uint8_t * uniform_bytes, size_t len)
Maps a random byte array to a point in a prime elliptic curve.
Parameters
[out] p - the result.
[in] uniform_bytes - the random byte array to map.
[in] len - the array length in bytes.
Definition at line 527 of file relic_ep_map.c.
References ep_curve_is_ctmap(), ep_curve_opt_a(), ep_curve_opt_b(), ep_map_basic_impl(), ep_map_sswum_impl(), ep_map_swift_impl(), and RLC_ZERO.