RELIC: src/fpx/relic_fpx_util.c File Reference
relic_fpx_util.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fpx_low.h"
Functions
void fp2_copy (fp2_t c, const fp2_t a)
void fp2_copy_sec (fp2_t c, const fp2_t a, dig_t bit)
void fp2_zero (fp2_t a)
int fp2_is_zero (const fp2_t a)
void fp2_rand (fp2_t a)
void fp2_print (const fp2_t a)
int fp2_size_bin (fp2_t a, int pack)
void fp2_read_bin (fp2_t a, const uint8_t *bin, size_t len)
void fp2_write_bin (uint8_t *bin, size_t len, const fp2_t a, int pack)
void fp2_set_dig (fp2_t a, const dig_t b)
void fp3_copy (fp3_t c, const fp3_t a)
void fp3_copy_sec (fp3_t c, const fp3_t a, dig_t bit)
void fp3_zero (fp3_t a)
int fp3_is_zero (const fp3_t a)
void fp3_rand (fp3_t a)
void fp3_print (const fp3_t a)
int fp3_size_bin (fp3_t a)
void fp3_read_bin (fp3_t a, const uint8_t *bin, size_t len)
void fp3_write_bin (uint8_t *bin, size_t len, const fp3_t a)
void fp3_set_dig (fp3_t a, const dig_t b)
void fp4_copy (fp4_t c, const fp4_t a)
void fp4_copy_sec (fp4_t c, const fp4_t a, dig_t bit)
void fp4_zero (fp4_t a)
int fp4_is_zero (const fp4_t a)
void fp4_rand (fp4_t a)
void fp4_print (const fp4_t a)
int fp4_size_bin (fp4_t a)
void fp4_read_bin (fp4_t a, const uint8_t *bin, size_t len)
void fp4_write_bin (uint8_t *bin, size_t len, const fp4_t a)
void fp4_set_dig (fp4_t a, const dig_t b)
void fp6_copy (fp6_t c, const fp6_t a)
void fp6_copy_sec (fp6_t c, const fp6_t a, dig_t bit)
void fp6_zero (fp6_t a)
int fp6_is_zero (const fp6_t a)
void fp6_rand (fp6_t a)
void fp6_print (const fp6_t a)
int fp6_size_bin (fp6_t a)
void fp6_read_bin (fp6_t a, const uint8_t *bin, size_t len)
void fp6_write_bin (uint8_t *bin, size_t len, const fp6_t a)
void fp6_set_dig (fp6_t a, const dig_t b)
void fp8_copy (fp8_t c, const fp8_t a)
void fp8_copy_sec (fp8_t c, const fp8_t a, dig_t bit)
void fp8_zero (fp8_t a)
int fp8_is_zero (const fp8_t a)
void fp8_rand (fp8_t a)
void fp8_print (const fp8_t a)
int fp8_size_bin (fp8_t a, int pack)
void fp8_read_bin (fp8_t a, const uint8_t *bin, size_t len)
void fp8_write_bin (uint8_t *bin, size_t len, const fp8_t a, int pack)
void fp8_set_dig (fp8_t a, const dig_t b)
void fp9_copy (fp9_t c, const fp9_t a)
void fp9_copy_sec (fp9_t c, const fp9_t a, dig_t bit)
void fp9_zero (fp9_t a)
int fp9_is_zero (const fp9_t a)
void fp9_rand (fp9_t a)
void fp9_print (const fp9_t a)
int fp9_size_bin (fp9_t a)
void fp9_read_bin (fp9_t a, const uint8_t *bin, size_t len)
void fp9_write_bin (uint8_t *bin, size_t len, const fp9_t a)
void fp9_set_dig (fp9_t a, const dig_t b)
void fp12_copy (fp12_t c, const fp12_t a)
void fp12_copy_sec (fp12_t c, const fp12_t a, dig_t bit)
void fp12_zero (fp12_t a)
int fp12_is_zero (const fp12_t a)
void fp12_rand (fp12_t a)
void fp12_print (const fp12_t a)
int fp12_size_bin (fp12_t a, int pack)
void fp12_read_bin (fp12_t a, const uint8_t *bin, size_t len)
void fp12_write_bin (uint8_t *bin, size_t len, const fp12_t a, int pack)
void fp12_set_dig (fp12_t a, const dig_t b)
void fp16_copy (fp16_t c, const fp16_t a)
void fp16_copy_sec (fp16_t c, const fp16_t a, dig_t bit)
void fp16_zero (fp16_t a)
int fp16_is_zero (const fp16_t a)
void fp16_rand (fp16_t a)
void fp16_print (const fp16_t a)
int fp16_size_bin (fp16_t a, int pack)
void fp16_read_bin (fp16_t a, const uint8_t *bin, size_t len)
void fp16_write_bin (uint8_t *bin, size_t len, const fp16_t a, int pack)
void fp16_set_dig (fp16_t a, const dig_t b)
void fp18_copy (fp18_t c, const fp18_t a)
void fp18_copy_sec (fp18_t c, const fp18_t a, dig_t bit)
void fp18_zero (fp18_t a)
int fp18_is_zero (const fp18_t a)
void fp18_rand (fp18_t a)
void fp18_print (const fp18_t a)
int fp18_size_bin (fp18_t a, int pack)
void fp18_read_bin (fp18_t a, const uint8_t *bin, size_t len)
void fp18_write_bin (uint8_t *bin, size_t len, const fp18_t a, int pack)
void fp18_set_dig (fp18_t a, const dig_t b)
void fp24_copy (fp24_t c, const fp24_t a)
void fp24_copy_sec (fp24_t c, const fp24_t a, dig_t bit)
void fp24_zero (fp24_t a)
int fp24_is_zero (const fp24_t a)
void fp24_rand (fp24_t a)
void fp24_print (const fp24_t a)
int fp24_size_bin (fp24_t a, int pack)
void fp24_read_bin (fp24_t a, const uint8_t *bin, size_t len)
void fp24_write_bin (uint8_t *bin, size_t len, const fp24_t a, int pack)
void fp24_set_dig (fp24_t a, const dig_t b)
void fp48_copy (fp48_t c, const fp48_t a)
void fp48_copy_sec (fp48_t c, const fp48_t a, dig_t bit)
void fp48_zero (fp48_t a)
int fp48_is_zero (const fp48_t a)
void fp48_rand (fp48_t a)
void fp48_print (const fp48_t a)
int fp48_size_bin (fp48_t a, int pack)
void fp48_read_bin (fp48_t a, const uint8_t *bin, size_t len)
void fp48_write_bin (uint8_t *bin, size_t len, const fp48_t a, int pack)
void fp48_set_dig (fp48_t a, const dig_t b)
void fp54_copy (fp54_t c, const fp54_t a)
void fp54_copy_sec (fp54_t c, const fp54_t a, dig_t bit)
void fp54_zero (fp54_t a)
int fp54_is_zero (const fp54_t a)
void fp54_rand (fp54_t a)
void fp54_print (const fp54_t a)
int fp54_size_bin (fp54_t a, int pack)
void fp54_read_bin (fp54_t a, const uint8_t *bin, size_t len)
void fp54_write_bin (uint8_t *bin, size_t len, const fp54_t a, int pack)
void fp54_set_dig (fp54_t a, dig_t b)
Detailed Description
Implementation of utilities in extensions defined over prime fields.
Definition in file relic_fpx_util.c.
Function Documentation
fp2_copy()
void fp2_copy (fp2_t c, const fp2_t a)
Copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to copy.
Definition at line 39 of file relic_fpx_util.c.
References fp_copy().
Referenced by ep2_copy(), ep2_curve_mul_a(), ep2_curve_mul_b(), ep2_curve_set(), ep2_curve_set_map(), ep2_curve_set_twist(), ep2_map_swift(), ep2_neg(), ep2_norm_imp(), ep2_norm_sim(), ep2_pck(), ep2_rhs(), ep2_upk(), fp12_back_cyc(), fp12_back_cyc_sim(), fp12_mul_dxs_basic(), fp12_mul_dxs_lazyr(), fp12_sqr_unr(), fp2_exp(), fp2_exp_cyc(), fp2_exp_cyc_sim(), fp2_exp_dig(), fp2_frb(), fp2_inv_sim(), fp2_mul_frb(), fp2_mul_nor_basic(), fp2_pck(), fp2_srt(), fp2_upk(), fp4_add_dig(), fp4_copy(), fp4_inv_cyc(), fp4_mul_art(), fp4_srt(), fp4_sub_dig(), fp6_copy(), fp6_mul_art(), fp6_mul_basic(), fp6_mul_dxs(), pp_add_k8_projc_basic(), and pp_add_k8_projc_lazyr().
fp2_copy_sec()
void fp2_copy_sec (fp2_t c, const fp2_t a, dig_t bit)
Conditionally copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to copy.
[in] bit - the condition bit to evaluate.
Definition at line 44 of file relic_fpx_util.c.
References fp_copy_sec().
Referenced by ep2_map_swift(), ep2_mul_reg_gls(), ep2_mul_reg_imp(), fp12_back_cyc(), fp12_back_cyc_sim(), fp2_srt(), fp4_copy_sec(), fp4_srt(), and fp6_copy_sec().
fp2_zero()
void fp2_zero (fp2_t a)
Assigns zero to a quadratic extension field element.
Parameters
[out] a - the quadratic extension field element to zero.
Definition at line 49 of file relic_fpx_util.c.
References fp_zero().
Referenced by ep2_curve_mul_a(), ep2_curve_mul_b(), ep2_curve_set_twist(), ep2_map_basic(), ep2_pck(), ep2_read_bin(), ep2_set_infty(), ep4_curve_set_twist(), fp12_pck(), fp12_read_bin(), fp18_pck(), fp2_srt(), fp4_set_dig(), fp4_srt(), fp4_zero(), fp6_set_dig(), fp6_zero(), and pp_mil_k2().
fp2_is_zero()
int fp2_is_zero (const fp2_t a)
Tests if a quadratic extension field element is zero or not.
Parameters
[in] a - the quadratic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 54 of file relic_fpx_util.c.
References fp_is_zero().
Referenced by detect_opt(), detect_opt(), detect_opt(), ep2_is_infty(), ep2_map_swift(), ep4_curve_set_twist(), ep4_map(), fp12_back_cyc(), fp12_back_cyc_sim(), fp12_upk(), fp18_upk(), fp2_srt(), fp4_cmp_dig(), fp4_field_init(), fp4_is_zero(), fp4_srt(), fp6_cmp_dig(), and fp6_is_zero().
fp2_rand()
void fp2_rand (fp2_t a)
Assigns a random value to a quadratic extension field element.
Parameters
[out] a - the quadratic extension field element to assign.
Definition at line 58 of file relic_fpx_util.c.
References fp_rand().
Referenced by ep2_blind(), fp4_rand(), and fp6_rand().
fp2_print()
void fp2_print (const fp2_t a)
Prints a quadratic extension field element to standard output.
Parameters
[in] a - the quadratic extension field element to print.
Definition at line 63 of file relic_fpx_util.c.
References fp_print().
Referenced by ep2_print(), fp4_print(), and fp6_print().
fp2_size_bin()
int fp2_size_bin (fp2_t a, int pack)
Returns the number of bytes necessary to store a quadratic extension field element.
Parameters
[in] a - the extension field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 68 of file relic_fpx_util.c.
References fp2_test_cyc(), and RLC_FP_BYTES.
fp2_read_bin()
void fp2_read_bin (fp2_t a, const uint8_t * bin, size_t len)
Reads a quadratic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 80 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp2_upk(), fp_read_bin(), fp_set_bit(), fp_zero(), RLC_FP_BYTES, and RLC_THROW.
Referenced by ep2_read_bin(), fp12_read_bin(), fp4_read_bin(), and fp6_read_bin().
fp2_write_bin()
void fp2_write_bin (uint8_t * bin, size_t len, const fp2_t a, int pack)
Writes a quadratic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
[in] pack - the flag to indicate compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 97 of file relic_fpx_util.c.
References ERR_CAUGHT, ERR_NO_BUFFER, fp2_free, fp2_new, fp2_null, fp2_pck(), fp2_test_cyc(), fp_get_bit(), fp_write_bin(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.
Referenced by ep2_write_bin(), fp12_write_bin(), fp4_write_bin(), and fp6_write_bin().
fp2_set_dig()
void fp2_set_dig (fp2_t a, const dig_t b)
Assigns a quadratic extension field element to a digit.
Parameters
[in] a - the quadratic extension field element.
[in] b - the digit.
Definition at line 131 of file relic_fpx_util.c.
References fp_set_dig(), and fp_zero().
Referenced by detect_opt(), ep2_curve_set_map(), ep2_curve_set_twist(), ep2_map_basic(), ep2_map_swift(), ep2_mul_reg_gls(), ep2_mul_reg_imp(), ep2_norm_imp(), ep2_read_bin(), fp12_back_cyc(), fp12_back_cyc_sim(), fp2_exp(), fp2_exp_cyc(), fp2_exp_cyc_sim(), fp2_exp_dig(), fp2_field_init(), fp4_set_dig(), fp4_srt(), fp6_set_dig(), pp_fin_k12_oatep(), pp_map_sim_tatep_k2(), pp_map_sim_weilp_k2(), pp_map_tatep_k2(), pp_map_weilp_k2(), pp_norm_k12(), and pp_norm_k8().
fp3_copy()
void fp3_copy (fp3_t c, const fp3_t a)
Copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the cubic extension field element to copy.
Definition at line 136 of file relic_fpx_util.c.
References fp_copy().
Referenced by ep3_copy(), ep3_curve_mul_a(), ep3_curve_mul_b(), ep3_curve_set(), ep3_curve_set_twist(), ep3_map(), ep3_neg(), ep3_norm_imp(), ep3_norm_sim(), ep3_rhs(), fp18_back_cyc(), fp18_back_cyc_sim(), fp18_mul_dxs_basic(), fp18_mul_dxs_lazyr(), fp3_exp(), fp3_frb(), fp3_inv_sim(), fp3_mul_frb(), fp3_mul_nor(), fp3_srt(), fp9_copy(), fp9_mul_art(), fp9_mul_basic(), and fp9_mul_dxs().
fp3_copy_sec()
void fp3_copy_sec (fp3_t c, const fp3_t a, dig_t bit)
Conditionally copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the cubic extension field element to copy.
[in] bit - the condition bit to evaluate.
Definition at line 142 of file relic_fpx_util.c.
References fp_copy_sec().
Referenced by ep3_map(), ep3_mul_reg_gls(), ep3_mul_reg_imp(), fp18_back_cyc(), fp18_back_cyc_sim(), fp3_srt(), and fp9_copy_sec().
fp3_zero()
void fp3_zero (fp3_t a)
Assigns zero to a cubic extension field element.
Parameters
[out] a - the cubic extension field element to zero.
Definition at line 148 of file relic_fpx_util.c.
References fp_zero().
Referenced by ep3_curve_mul_a(), ep3_curve_mul_b(), ep3_curve_set_twist(), ep3_set_infty(), fp18_read_bin(), fp3_srt(), fp9_set_dig(), and fp9_zero().
fp3_is_zero()
int fp3_is_zero (const fp3_t a)
Tests if a cubic extension field element is zero or not.
Parameters
[in] a - the cubic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 154 of file relic_fpx_util.c.
References fp_is_zero().
Referenced by detect_opt(), ep3_is_infty(), ep3_map(), fp18_back_cyc(), fp18_back_cyc_sim(), fp3_srt(), fp9_cmp_dig(), and fp9_is_zero().
fp3_rand()
void fp3_rand (fp3_t a)
Assigns a random value to a cubic extension field element.
Parameters
[out] a - the cubic extension field element to assign.
Definition at line 158 of file relic_fpx_util.c.
References fp_rand().
Referenced by ep3_blind(), and fp9_rand().
fp3_print()
void fp3_print (const fp3_t a)
Prints a cubic extension field element to standard output.
Parameters
[in] a - the cubic extension field element to print.
Definition at line 164 of file relic_fpx_util.c.
References fp_print().
Referenced by ep3_print(), and fp9_print().
fp3_size_bin()
int fp3_size_bin (fp3_t a)
Returns the number of bytes necessary to store a cubic extension field element.
Parameters
[out] size - the result.
[in] a - the extension field element.
Definition at line 170 of file relic_fpx_util.c.
References RLC_FP_BYTES.
fp3_read_bin()
void fp3_read_bin (fp3_t a, const uint8_t * bin, size_t len)
Reads a cubic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 174 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp_read_bin(), RLC_FP_BYTES, and RLC_THROW.
Referenced by ep3_read_bin(), fp18_read_bin(), and fp9_read_bin().
fp3_write_bin()
void fp3_write_bin (uint8_t * bin, size_t len, const fp3_t a)
Writes a cubic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 184 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp_write_bin(), RLC_FP_BYTES, and RLC_THROW.
Referenced by ep3_write_bin(), fp18_write_bin(), and fp9_write_bin().
fp3_set_dig()
void fp3_set_dig (fp3_t a, const dig_t b)
Assigns a cubic extension field element to a digit.
Parameters
[in] a - the cubic extension field element.
[in] b - the digit.
Definition at line 194 of file relic_fpx_util.c.
References fp_set_dig(), and fp_zero().
Referenced by detect_opt(), ep3_curve_set_twist(), ep3_map(), ep3_mul_gls_imp(), ep3_mul_reg_gls(), ep3_mul_reg_imp(), ep3_norm_imp(), ep3_read_bin(), fp18_back_cyc(), fp18_back_cyc_sim(), fp3_exp(), fp3_field_init(), fp9_set_dig(), pp_mil_k54(), and pp_norm_k18().
fp4_copy()
void fp4_copy (fp4_t c, const fp4_t a)
Copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the quartic extension field element to copy.
Definition at line 200 of file relic_fpx_util.c.
References fp2_copy().
Referenced by ep4_copy(), ep4_curve_mul_a(), ep4_curve_mul_b(), ep4_curve_set(), ep4_curve_set_twist(), ep4_map(), ep4_neg(), ep4_norm_imp(), ep4_norm_sim(), ep4_rhs(), fp24_back_cyc(), fp24_back_cyc_sim(), fp4_exp(), fp4_frb(), fp4_inv_sim(), fp4_mul_frb(), fp8_copy(), fp8_inv_cyc(), fp8_mul_art(), fp8_srt(), pp_add_k16_projc_basic(), and pp_add_k16_projc_lazyr().
fp4_copy_sec()
void fp4_copy_sec (fp4_t c, const fp4_t a, dig_t bit)
Conditionally copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the quartic extension field element to copy.
[in] bit - the condition bit to evaluate.
Definition at line 205 of file relic_fpx_util.c.
References fp2_copy_sec().
Referenced by ep4_map(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), fp24_back_cyc(), fp24_back_cyc_sim(), fp8_copy_sec(), and fp8_srt().
fp4_zero()
void fp4_zero (fp4_t a)
Assigns zero to a quartic extension field element.
Parameters
[out] a - the quartic extension field element to zero.
Definition at line 210 of file relic_fpx_util.c.
References fp2_zero().
Referenced by ep4_curve_mul_a(), ep4_curve_mul_b(), ep4_curve_set_twist(), ep4_map(), ep4_set_infty(), fp24_pck(), fp24_read_bin(), fp4_srt(), fp8_set_dig(), fp8_srt(), and fp8_zero().
fp4_is_zero()
int fp4_is_zero (const fp4_t a)
Tests if a quartic extension field element is zero or not.
Parameters
[in] a - the quartic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 215 of file relic_fpx_util.c.
References fp2_is_zero().
Referenced by detect_opt(), detect_opt(), ep4_is_infty(), ep4_map(), ep8_map(), fp16_mul_dxs_basic(), fp16_mul_dxs_lazyr(), fp24_back_cyc(), fp24_back_cyc_sim(), fp24_upk(), fp4_srt(), fp8_cmp_dig(), fp8_field_init(), fp8_is_zero(), and fp8_srt().
fp4_rand()
void fp4_rand (fp4_t a)
Assigns a random value to a quartic extension field element.
Parameters
[out] a - the quartic extension field element to assign.
Definition at line 219 of file relic_fpx_util.c.
References fp2_rand().
Referenced by ep4_blind(), and fp8_rand().
fp4_print()
void fp4_print (const fp4_t a)
Prints a quartic extension field element to standard output.
Parameters
[in] a - the quartic extension field element to print.
Definition at line 224 of file relic_fpx_util.c.
References fp2_print().
Referenced by ep4_print(), and fp8_print().
fp4_size_bin()
int fp4_size_bin (fp4_t a)
Returns the number of bytes necessary to store a quartic extension field element.
Parameters
[out] size - the result.
[in] a - the extension field element.
Definition at line 229 of file relic_fpx_util.c.
References RLC_FP_BYTES.
fp4_read_bin()
void fp4_read_bin (fp4_t a, const uint8_t * bin, size_t len)
Reads a quartic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 233 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp2_read_bin(), RLC_FP_BYTES, and RLC_THROW.
Referenced by ep4_read_bin(), fp24_read_bin(), and fp8_read_bin().
fp4_write_bin()
void fp4_write_bin (uint8_t * bin, size_t len, const fp4_t a)
Writes a quartic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 242 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp2_write_bin(), RLC_FP_BYTES, and RLC_THROW.
Referenced by ep4_write_bin(), fp24_write_bin(), and fp8_write_bin().
fp4_set_dig()
void fp4_set_dig (fp4_t a, const dig_t b)
Assigns a quartic extension field element to a digit.
Parameters
[in] a - the quartic extension field element.
[in] b - the digit.
Definition at line 251 of file relic_fpx_util.c.
References fp2_set_dig(), and fp2_zero().
Referenced by detect_opt(), ep4_curve_set_twist(), ep4_map(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), ep4_norm_imp(), ep4_read_bin(), fp24_back_cyc(), fp24_back_cyc_sim(), fp4_exp(), fp4_field_init(), fp8_set_dig(), fp8_srt(), pp_norm_k16(), and pp_norm_k24().
fp6_copy()
void fp6_copy (fp6_t c, const fp6_t a)
Copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the sextic extension field element to copy.
Definition at line 256 of file relic_fpx_util.c.
References fp2_copy().
Referenced by fp12_copy(), fp12_inv_cyc(), fp12_mul_art(), fp12_upk_max(), fp6_exp(), and fp6_frb().
fp6_copy_sec()
void fp6_copy_sec (fp6_t c, const fp6_t a, dig_t bit)
Conditionally copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the sextic extension field element to copy.
[in] bit - the condition bit to evaluate.
Definition at line 262 of file relic_fpx_util.c.
References fp2_copy_sec().
Referenced by fp12_copy_sec().
fp6_zero()
void fp6_zero (fp6_t a)
Assigns zero to a sextic extension field element.
Parameters
[out] a - the sextic extension field element to zero.
Definition at line 268 of file relic_fpx_util.c.
References fp2_zero().
Referenced by fp12_pck_max(), fp12_set_dig(), fp12_upk_max(), and fp12_zero().
fp6_is_zero()
int fp6_is_zero (const fp6_t a)
Tests if a sextic extension field element is zero or not.
Parameters
[in] a - the sextic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 274 of file relic_fpx_util.c.
References fp2_is_zero().
Referenced by fp12_cmp_dig(), fp12_is_zero(), and fp12_upk_max().
fp6_rand()
void fp6_rand (fp6_t a)
Assigns a random value to a sextic extension field element.
Parameters
[out] a - the sextic extension field element to assign.
Definition at line 278 of file relic_fpx_util.c.
References fp2_rand().
Referenced by fp12_rand().
fp6_print()
void fp6_print (const fp6_t a)
Prints a sextic extension field element to standard output.
Parameters
[in] a - the sextic extension field element to print.
Definition at line 284 of file relic_fpx_util.c.
References fp2_print().
Referenced by fp12_print().
fp6_size_bin()
int fp6_size_bin (fp6_t a)
Returns the number of bytes necessary to store a quadratic extension field element.
Parameters
[out] size - the result.
[in] a - the extension field element.
Definition at line 290 of file relic_fpx_util.c.
References RLC_FP_BYTES.
fp6_read_bin()
void fp6_read_bin (fp6_t a, const uint8_t * bin, size_t len)
Reads a quadratic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 294 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp2_read_bin(), RLC_FP_BYTES, and RLC_THROW.
Referenced by fp12_read_bin().
fp6_write_bin()
void fp6_write_bin (uint8_t * bin, size_t len, const fp6_t a)
Writes a sextic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 304 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp2_write_bin(), RLC_FP_BYTES, and RLC_THROW.
Referenced by fp12_write_bin().
fp6_set_dig()
void fp6_set_dig (fp6_t a, const dig_t b)
Assigns a sextic extension field element to a digit.
Parameters
[in] a - the sextic extension field element.
[in] b - the digit.
Definition at line 314 of file relic_fpx_util.c.
References fp2_set_dig(), and fp2_zero().
Referenced by fp12_set_dig(), fp12_upk_max(), and fp6_exp().
fp8_copy()
void fp8_copy (fp8_t c, const fp8_t a)
Copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the octic extension field element to copy.
Definition at line 320 of file relic_fpx_util.c.
References fp4_copy().
Referenced by ep8_copy(), ep8_curve_mul_a(), ep8_curve_mul_b(), ep8_curve_set(), ep8_curve_set_twist(), ep8_map(), ep8_neg(), ep8_norm_imp(), ep8_norm_sim(), ep8_rhs(), fp16_copy(), fp16_inv_cyc(), fp16_mul_art(), fp16_srt(), fp24_copy(), fp24_mul_art(), fp24_mul_basic(), fp24_mul_dxs(), fp48_back_cyc(), fp48_back_cyc_sim(), fp48_mul_dxs(), fp8_exp(), fp8_exp_cyc(), fp8_exp_cyc_sim(), fp8_exp_dig(), fp8_frb(), fp8_inv_sim(), fp8_mul_frb(), and pp_exp_k8().
fp8_copy_sec()
void fp8_copy_sec (fp8_t c, const fp8_t a, dig_t bit)
Conditionally copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the octic extension field element to copy.
[in] bit - the condition bit to evaluate.
Definition at line 325 of file relic_fpx_util.c.
References fp4_copy_sec().
Referenced by ep8_map(), ep8_mul_reg_gls(), ep8_mul_reg_imp(), fp16_copy_sec(), fp24_copy_sec(), fp48_back_cyc(), and fp48_back_cyc_sim().
fp8_zero()
void fp8_zero (fp8_t a)
Assigns zero to an octic extension field element.
Parameters
[out] a - the octic extension field element to zero.
Definition at line 330 of file relic_fpx_util.c.
References fp4_zero().
Referenced by ep8_curve_mul_a(), ep8_curve_mul_b(), ep8_curve_set_twist(), ep8_set_infty(), fp16_set_dig(), fp16_srt(), fp16_zero(), fp24_set_dig(), fp24_zero(), fp48_pck(), fp48_read_bin(), fp8_srt(), and pp_mil_k8().
fp8_is_zero()
int fp8_is_zero (const fp8_t a)
Tests if an octic extension field element is zero or not.
Parameters
[in] a - the octic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 335 of file relic_fpx_util.c.
References fp4_is_zero().
Referenced by detect_opt(), ep8_is_infty(), ep8_map(), fp16_cmp_dig(), fp16_is_zero(), fp16_srt(), fp24_cmp_dig(), fp24_is_zero(), fp24_mul_dxs(), fp48_back_cyc(), fp48_back_cyc_sim(), fp48_upk(), and fp8_srt().
fp8_rand()
void fp8_rand (fp8_t a)
Assigns a random value to an octic extension field element.
Parameters
[out] a - the octic extension field element to assign.
Definition at line 339 of file relic_fpx_util.c.
References fp4_rand().
Referenced by ep8_blind(), fp16_rand(), and fp24_rand().
fp8_print()
void fp8_print (const fp8_t a)
Prints an octic extension field element to standard output.
Parameters
[in] a - the octic extension field element to print.
Definition at line 344 of file relic_fpx_util.c.
References fp4_print().
Referenced by ep8_print(), fp16_print(), and fp24_print().
fp8_size_bin()
int fp8_size_bin (fp8_t a, int pack)
Returns the number of bytes necessary to store an octic extension field element.
Parameters
[in] a - the extension field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 349 of file relic_fpx_util.c.
References fp8_test_cyc(), and RLC_FP_BYTES.
fp8_read_bin()
void fp8_read_bin (fp8_t a, const uint8_t * bin, size_t len)
Reads an octic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 361 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp4_read_bin(), RLC_FP_BYTES, and RLC_THROW.
Referenced by ep8_read_bin(), fp16_read_bin(), fp24_read_bin(), and fp48_read_bin().
fp8_write_bin()
void fp8_write_bin (uint8_t * bin, size_t len, const fp8_t a, int pack)
Writes an octic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
[in] pack - the flag to indicate compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 370 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp4_write_bin(), RLC_FP_BYTES, and RLC_THROW.
Referenced by ep8_write_bin(), fp16_write_bin(), fp24_write_bin(), and fp48_write_bin().
fp8_set_dig()
void fp8_set_dig (fp8_t a, const dig_t b)
Assigns an octic extension field element to a digit.
Parameters
[in] a - the octic extension field element.
[in] b - the digit.
Definition at line 379 of file relic_fpx_util.c.
References fp4_set_dig(), and fp4_zero().
Referenced by detect_opt(), ep8_curve_set_twist(), ep8_map(), ep8_mul_reg_gls(), ep8_mul_reg_imp(), ep8_norm_imp(), ep8_read_bin(), fp16_set_dig(), fp16_srt(), fp24_set_dig(), fp48_back_cyc(), fp48_back_cyc_sim(), fp8_exp(), fp8_exp_cyc(), fp8_exp_cyc_sim(), fp8_exp_dig(), fp8_field_init(), pp_map_oatep_k8(), pp_map_sim_oatep_k8(), and pp_norm_k48().
fp9_copy()
void fp9_copy (fp9_t c, const fp9_t a)
Copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the nonic extension field element to copy.
Definition at line 384 of file relic_fpx_util.c.
References fp3_copy().
Referenced by ep9_add_basic(), ep9_dbl_basic(), fp18_copy(), fp18_inv_cyc(), fp18_mul_art(), fp54_back_cyc(), fp54_back_cyc_sim(), fp54_mul_dxs(), fp9_exp(), fp9_frb(), fp9_inv_sim(), pp_add_k54_basic(), pp_dbl_k54_basic(), and pp_mil_k54().
fp9_copy_sec()
void fp9_copy_sec (fp9_t c, const fp9_t a, dig_t bit)
Conditionally copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the nonic extension field element to copy.
[in] bit - the condition bit to evaluate.
Definition at line 390 of file relic_fpx_util.c.
References fp3_copy_sec().
Referenced by fp18_copy_sec(), fp54_back_cyc(), and fp54_back_cyc_sim().
fp9_zero()
void fp9_zero (fp9_t a)
Assigns zero to a nonic extension field element.
Parameters
[out] a - the nonic extension field element to zero.
Definition at line 396 of file relic_fpx_util.c.
References fp3_zero().
Referenced by ep9_add_basic(), fp18_set_dig(), fp18_zero(), fp54_pck(), fp54_read_bin(), pp_dbl_k54_projc(), and pp_mil_k54().
fp9_is_zero()
int fp9_is_zero (const fp9_t a)
Tests if a nonic extension field element is zero or not.
Parameters
[in] a - the nonic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 402 of file relic_fpx_util.c.
References fp3_is_zero().
Referenced by ep9_add_basic(), fp18_cmp_dig(), fp18_is_zero(), fp54_back_cyc(), fp54_back_cyc_sim(), fp54_upk(), and pp_map_k54().
fp9_rand()
void fp9_rand (fp9_t a)
Assigns a random value to a nonic extension field element.
Parameters
[out] a - the nonic extension field element to assign.
Definition at line 406 of file relic_fpx_util.c.
References fp3_rand().
Referenced by fp18_rand().
fp9_print()
void fp9_print (const fp9_t a)
Prints a nonic extension field element to standard output.
Parameters
[in] a - the nonic extension field element to print.
Definition at line 412 of file relic_fpx_util.c.
References fp3_print().
Referenced by fp18_print().
fp9_size_bin()
int fp9_size_bin (fp9_t a)
Returns the number of bytes necessary to store a quadratic extension field element.
Parameters
[out] size - the result.
[in] a - the extension field element.
Definition at line 418 of file relic_fpx_util.c.
References RLC_FP_BYTES.
fp9_read_bin()
void fp9_read_bin (fp9_t a, const uint8_t * bin, size_t len)
Reads a quadratic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 422 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp3_read_bin(), RLC_FP_BYTES, and RLC_THROW.
Referenced by fp18_read_bin(), and fp54_read_bin().
fp9_write_bin()
void fp9_write_bin (uint8_t * bin, size_t len, const fp9_t a)
Writes a nonic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 432 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp3_write_bin(), RLC_FP_BYTES, and RLC_THROW.
Referenced by fp18_write_bin(), and fp54_write_bin().
fp9_set_dig()
void fp9_set_dig (fp9_t a, const dig_t b)
Assigns a nonic extension field element to a digit.
Parameters
[in] a - the nonic extension field element.
[in] b - the digit.
Definition at line 442 of file relic_fpx_util.c.
References fp3_set_dig(), and fp3_zero().
Referenced by ep3_curve_set_twist(), fp18_set_dig(), fp54_back_cyc(), fp54_back_cyc_sim(), fp9_exp(), and pp_mil_k54().
fp12_copy()
void fp12_copy (fp12_t c, const fp12_t a)
Copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to copy.
Definition at line 448 of file relic_fpx_util.c.
References fp6_copy().
Referenced by fp12_exp(), fp12_exp_cyc(), fp12_exp_cyc_sim(), fp12_exp_cyc_sps(), fp12_exp_dig(), fp12_frb(), fp12_pck(), fp12_pck_max(), fp12_upk(), fp12_upk_max(), and pp_exp_sm9().
fp12_copy_sec()
void fp12_copy_sec (fp12_t c, const fp12_t a, dig_t bit)
Conditionally copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to copy.
[in] bit - the condition bit to evaluate.
Definition at line 453 of file relic_fpx_util.c.
References fp6_copy_sec().
fp12_zero()
void fp12_zero (fp12_t a)
Assigns zero to a dodecic extension field element.
Parameters
[out] a - the dodecic extension field element to zero.
Definition at line 458 of file relic_fpx_util.c.
References fp6_zero().
Referenced by pp_fin_k12_oatep(), pp_mil_k12(), and pp_mil_lit_k12().
fp12_is_zero()
int fp12_is_zero (const fp12_t a)
Tests if a dodecic extension field element is zero or not.
Parameters
[in] a - the dodecic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 463 of file relic_fpx_util.c.
References fp6_is_zero().
fp12_rand()
void fp12_rand (fp12_t a)
Assigns a random value to a dodecic extension field element.
Parameters
[out] a - the dodecic extension field element to assign.
Definition at line 467 of file relic_fpx_util.c.
References fp6_rand().
fp12_print()
void fp12_print (const fp12_t a)
Prints a dodecic extension field element to standard output.
Parameters
[in] a - the dodecic extension field element to print.
Definition at line 472 of file relic_fpx_util.c.
References fp6_print().
fp12_size_bin()
int fp12_size_bin (fp12_t a, int pack)
Returns the number of bytes necessary to store a dodecic extension field element.
Parameters
[in] a - the extension field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 477 of file relic_fpx_util.c.
References fp12_test_cyc(), and RLC_FP_BYTES.
fp12_read_bin()
void fp12_read_bin (fp12_t a, const uint8_t * bin, size_t len)
Reads a dodecic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 489 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp12_back_cyc(), fp2_read_bin(), fp2_zero(), fp6_read_bin(), RLC_FP_BYTES, and RLC_THROW.
fp12_write_bin()
void fp12_write_bin (uint8_t * bin, size_t len, const fp12_t a, int pack)
Writes a dodecic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
[in] pack - the flag to indicate compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 509 of file relic_fpx_util.c.
References ERR_CAUGHT, ERR_NO_BUFFER, fp12_free, fp12_new, fp12_null, fp12_pck(), fp2_write_bin(), fp6_write_bin(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.
fp12_set_dig()
void fp12_set_dig (fp12_t a, const dig_t b)
Assigns a dodecic extension field element to a digit.
Parameters
[in] a - the dodecic extension field element.
[in] b - the digit.
Definition at line 540 of file relic_fpx_util.c.
References fp6_set_dig(), and fp6_zero().
Referenced by fp12_exp(), fp12_exp_cyc(), fp12_exp_cyc_sim(), fp12_exp_cyc_sps(), fp12_exp_dig(), pp_map_oatep_k12(), pp_map_sim_oatep_k12(), pp_map_sim_tatep_k12(), pp_map_sim_weilp_k12(), pp_map_tatep_k12(), and pp_map_weilp_k12().
fp16_copy()
void fp16_copy (fp16_t c, const fp16_t a)
Copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the sextadecic extension field element to copy.
Definition at line 545 of file relic_fpx_util.c.
References fp8_copy().
Referenced by fp16_exp(), fp16_exp_cyc(), fp16_exp_cyc_sim(), fp16_exp_dig(), fp16_frb(), fp16_inv_sim(), and pp_exp_afg16().
fp16_copy_sec()
void fp16_copy_sec (fp16_t c, const fp16_t a, dig_t bit)
Conditionally copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the sextadecic extension field element to copy.
[in] bit - the condition bit to evaluate.
Definition at line 550 of file relic_fpx_util.c.
References fp8_copy_sec().
fp16_zero()
void fp16_zero (fp16_t a)
Assigns zero to an sextadecic extension field element.
Parameters
[out] a - the sextadecic extension field element to zero.
Definition at line 555 of file relic_fpx_util.c.
References fp8_zero().
Referenced by fp16_srt(), pp_fin_k16_oatep(), pp_mil_k16(), and pp_mil_lit_k16().
fp16_is_zero()
int fp16_is_zero (const fp16_t a)
Tests if an sextadecic extension field element is zero or not.
Parameters
[in] a - the sextadecic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 560 of file relic_fpx_util.c.
References fp8_is_zero().
Referenced by fp16_srt().
fp16_rand()
void fp16_rand (fp16_t a)
Assigns a random value to an sextadecic extension field element.
Parameters
[out] a - the sextadecic extension field element to assign.
Definition at line 564 of file relic_fpx_util.c.
References fp8_rand().
fp16_print()
void fp16_print (const fp16_t a)
Prints an sextadecic extension field element to standard output.
Parameters
[in] a - the sextadecic extension field element to print.
Definition at line 569 of file relic_fpx_util.c.
References fp8_print().
fp16_size_bin()
int fp16_size_bin (fp16_t a, int pack)
Returns the number of bytes necessary to store an sextadecic extension field element.
Parameters
[in] a - the extension field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 574 of file relic_fpx_util.c.
References fp16_test_cyc(), and RLC_FP_BYTES.
fp16_read_bin()
void fp16_read_bin (fp16_t a, const uint8_t * bin, size_t len)
Reads an sextadecic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 586 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp8_read_bin(), RLC_FP_BYTES, and RLC_THROW.
fp16_write_bin()
void fp16_write_bin (uint8_t * bin, size_t len, const fp16_t a, int pack)
Writes an sextadecic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
[in] pack - the flag to indicate compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 595 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp8_write_bin(), RLC_FP_BYTES, and RLC_THROW.
fp16_set_dig()
void fp16_set_dig (fp16_t a, const dig_t b)
Assigns an sextadecic extension field element to a digit.
Parameters
[in] a - the sextadecic extension field element.
[in] b - the digit.
Definition at line 604 of file relic_fpx_util.c.
References fp8_set_dig(), and fp8_zero().
Referenced by fp16_exp(), fp16_exp_cyc(), fp16_exp_cyc_sim(), fp16_exp_dig(), pp_map_oatep_k16(), pp_map_sim_oatep_k16(), pp_map_sim_tatep_k16(), pp_map_sim_weilp_k16(), pp_map_tatep_k16(), and pp_map_weilp_k16().
fp18_copy()
void fp18_copy (fp18_t c, const fp18_t a)
Copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element to copy.
Definition at line 609 of file relic_fpx_util.c.
References fp9_copy().
Referenced by fp18_exp(), fp18_exp_cyc(), fp18_exp_cyc_sim(), fp18_exp_cyc_sps(), fp18_exp_dig(), fp18_frb(), fp18_pck(), fp18_upk(), fp54_copy(), fp54_mul_art(), fp54_mul_basic(), fp54_mul_dxs(), fp54_mul_lazyr(), and pp_exp_sg().
fp18_copy_sec()
void fp18_copy_sec (fp18_t c, const fp18_t a, dig_t bit)
Conditionally copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element to copy.
[in] bit - the condition bit to evaluate.
Definition at line 614 of file relic_fpx_util.c.
References fp9_copy_sec().
Referenced by fp54_copy_sec().
fp18_zero()
void fp18_zero (fp18_t a)
Assigns zero to an octdecic extension field element.
Parameters
[out] a - the octdecic extension field element to zero.
Definition at line 619 of file relic_fpx_util.c.
References fp9_zero().
Referenced by ep3_curve_set_twist(), fp54_set_dig(), fp54_zero(), pp_fin_k18_oatep(), pp_mil_k18(), and pp_mil_lit_k18().
fp18_is_zero()
int fp18_is_zero (const fp18_t a)
Tests if an octdecic extension field element is zero or not.
Parameters
[in] a - the octdecic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 624 of file relic_fpx_util.c.
References fp9_is_zero().
Referenced by fp54_cmp_dig(), and fp54_is_zero().
fp18_rand()
void fp18_rand (fp18_t a)
Assigns a random value to an octdecic extension field element.
Parameters
[out] a - the octdecic extension field element to assign.
Definition at line 628 of file relic_fpx_util.c.
References fp9_rand().
Referenced by fp54_rand().
fp18_print()
void fp18_print (const fp18_t a)
Prints an octdecic extension field element to standard output.
Parameters
[in] A - the octdecic extension field element to print.
Definition at line 633 of file relic_fpx_util.c.
References fp9_print().
Referenced by fp54_print().
fp18_size_bin()
int fp18_size_bin (fp18_t a, int pack)
Returns the number of bytes necessary to store a octdecic extension field element.
Parameters
[in] a - the extension field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 638 of file relic_fpx_util.c.
References fp18_test_cyc(), and RLC_FP_BYTES.
fp18_read_bin()
void fp18_read_bin (fp18_t a, const uint8_t * bin, size_t len)
Reads a octdecic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 650 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp18_back_cyc(), fp3_read_bin(), fp3_zero(), fp9_read_bin(), RLC_FP_BYTES, and RLC_THROW.
Referenced by fp54_read_bin().
fp18_write_bin()
void fp18_write_bin (uint8_t * bin, size_t len, const fp18_t a, int pack)
Writes a octdecic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
[in] pack - the flag to indicate compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 670 of file relic_fpx_util.c.
References ERR_CAUGHT, ERR_NO_BUFFER, fp18_free, fp18_new, fp18_null, fp18_pck(), fp3_write_bin(), fp9_write_bin(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.
Referenced by fp54_write_bin().
fp18_set_dig()
void fp18_set_dig (fp18_t a, const dig_t b)
Assigns an octdecic extension field element to a digit.
Parameters
[in] a - the octdecic extension field element.
[in] b - the digit.
Definition at line 701 of file relic_fpx_util.c.
References fp9_set_dig(), and fp9_zero().
Referenced by fp18_exp(), fp18_exp_cyc(), fp18_exp_cyc_sim(), fp18_exp_cyc_sps(), fp18_exp_dig(), fp54_set_dig(), pp_map_oatep_k18(), pp_map_sim_oatep_k18(), pp_map_sim_tatep_k18(), pp_map_sim_weilp_k18(), pp_map_tatep_k18(), and pp_map_weilp_k18().
fp24_copy()
void fp24_copy (fp24_t c, const fp24_t a)
Copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the 24-degree extension field element to copy.
Definition at line 706 of file relic_fpx_util.c.
References fp8_copy().
Referenced by fp24_exp(), fp24_exp_cyc(), fp24_exp_cyc_sim(), fp24_exp_cyc_sps(), fp24_exp_dig(), fp24_frb(), fp24_pck(), fp24_upk(), fp48_copy(), fp48_inv_cyc(), and fp48_mul_art().
fp24_copy_sec()
void fp24_copy_sec (fp24_t c, const fp24_t a, dig_t bit)
Conditionally copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the 24-degree extension field element to copy.
[in] bit - the condition bit to evaluate.
Definition at line 712 of file relic_fpx_util.c.
References fp8_copy_sec().
Referenced by fp48_copy_sec().
fp24_zero()
void fp24_zero (fp24_t a)
Assigns zero to a 24-degree extension field element.
Parameters
[out] a - the 24-degree extension field element to zero.
Definition at line 718 of file relic_fpx_util.c.
References fp8_zero().
Referenced by fp48_set_dig(), fp48_zero(), pp_dbl_k24_basic(), and pp_mil_k24().
fp24_is_zero()
int fp24_is_zero (const fp24_t a)
Tests if a 24-degree extension field element is zero or not.
Parameters
[in] a - the 24-degree extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 724 of file relic_fpx_util.c.
References fp8_is_zero().
Referenced by fp48_cmp_dig(), and fp48_is_zero().
fp24_rand()
void fp24_rand (fp24_t a)
Assigns a random value to a 24-degree extension field element.
Parameters
[out] A - the 24-degree extension field element to assign.
Definition at line 728 of file relic_fpx_util.c.
References fp8_rand().
Referenced by fp48_rand().
fp24_print()
void fp24_print (const fp24_t a)
Prints a 24-degree extension field element to standard output.
Parameters
[in] A - the 24-degree extension field element to print.
Definition at line 734 of file relic_fpx_util.c.
References fp8_print().
Referenced by fp48_print().
fp24_size_bin()
int fp24_size_bin (fp24_t a, int pack)
Returns the number of bytes necessary to store a 24-degree extension field element.
Parameters
[in] a - the extension field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 740 of file relic_fpx_util.c.
References fp24_test_cyc(), and RLC_FP_BYTES.
fp24_read_bin()
void fp24_read_bin (fp24_t a, const uint8_t * bin, size_t len)
Reads a 24-degree extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 752 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp24_back_cyc(), fp4_read_bin(), fp4_zero(), fp8_read_bin(), RLC_FP_BYTES, and RLC_THROW.
Referenced by fp48_read_bin().
fp24_write_bin()
void fp24_write_bin (uint8_t * bin, size_t len, const fp24_t a, int pack)
Writes a 24-degree extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
[in] pack - the flag to indicate compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 773 of file relic_fpx_util.c.
References ERR_CAUGHT, ERR_NO_BUFFER, fp24_free, fp24_new, fp24_null, fp24_pck(), fp4_write_bin(), fp8_write_bin(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.
Referenced by fp48_write_bin().
fp24_set_dig()
void fp24_set_dig (fp24_t a, const dig_t b)
Assigns a 24-degree extension field element to a digit.
Parameters
[in] a - the 24-degree extension field element.
[in] b - the digit.
Definition at line 805 of file relic_fpx_util.c.
References fp8_set_dig(), and fp8_zero().
Referenced by fp24_exp(), fp24_exp_cyc(), fp24_exp_cyc_sim(), fp24_exp_cyc_sps(), fp24_exp_dig(), fp48_set_dig(), pp_map_k24(), and pp_map_sim_k24().
fp48_copy()
void fp48_copy (fp48_t c, const fp48_t a)
Copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the 48-extension field element to copy.
Definition at line 811 of file relic_fpx_util.c.
References fp24_copy().
Referenced by fp48_exp(), fp48_exp_cyc(), fp48_exp_cyc_sim(), fp48_exp_cyc_sps(), fp48_exp_dig(), fp48_frb(), fp48_pck(), and fp48_upk().
fp48_copy_sec()
void fp48_copy_sec (fp48_t c, const fp48_t a, dig_t bit)
Conditionally copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the 48-degree extension field element to copy.
[in] bit - the condition bit to evaluate.
Definition at line 816 of file relic_fpx_util.c.
References fp24_copy_sec().
fp48_zero()
void fp48_zero (fp48_t a)
Assigns zero to a 48-extension field element.
Parameters
[out] a - the 48-extension field element to zero.
Definition at line 821 of file relic_fpx_util.c.
References fp24_zero().
Referenced by pp_add_k48_basic(), pp_dbl_k48_basic(), and pp_mil_k48().
fp48_is_zero()
int fp48_is_zero (const fp48_t a)
Tests if a 48-extension field element is zero or not.
Parameters
[in] a - the 48-extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 826 of file relic_fpx_util.c.
References fp24_is_zero().
fp48_rand()
void fp48_rand (fp48_t a)
Assigns a random value to a 48-extension field element.
Parameters
[out] a - the 48-extension field element to assign.
Definition at line 830 of file relic_fpx_util.c.
References fp24_rand().
fp48_print()
void fp48_print (const fp48_t a)
Prints a 48-extension field element to standard output.
Parameters
[in] a - the 48-extension field element to print.
Definition at line 835 of file relic_fpx_util.c.
References fp24_print().
fp48_size_bin()
int fp48_size_bin (fp48_t a, int pack)
Returns the number of bytes necessary to store a 48-extension field element.
Parameters
[in] a - the extension field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 840 of file relic_fpx_util.c.
References fp48_test_cyc(), and RLC_FP_BYTES.
fp48_read_bin()
void fp48_read_bin (fp48_t a, const uint8_t * bin, size_t len)
Reads a 48-extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 852 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp24_read_bin(), fp48_back_cyc(), fp8_read_bin(), fp8_zero(), RLC_FP_BYTES, and RLC_THROW.
fp48_write_bin()
void fp48_write_bin (uint8_t * bin, size_t len, const fp48_t a, int pack)
Writes a 48-extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
[in] pack - the flag to indicate compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 872 of file relic_fpx_util.c.
References ERR_CAUGHT, ERR_NO_BUFFER, fp24_write_bin(), fp48_free, fp48_new, fp48_null, fp48_pck(), fp8_write_bin(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.
fp48_set_dig()
void fp48_set_dig (fp48_t a, const dig_t b)
Assigns a 48-extension field element to a digit.
Parameters
[in] a - the 48-extension field element.
[in] b - the digit.
Definition at line 903 of file relic_fpx_util.c.
References fp24_set_dig(), and fp24_zero().
Referenced by fp48_exp(), fp48_exp_cyc(), fp48_exp_cyc_sim(), fp48_exp_cyc_sps(), fp48_exp_dig(), pp_map_k48(), and pp_map_sim_k48().
fp54_copy()
void fp54_copy (fp54_t c, const fp54_t a)
Copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the 54-extension field element to copy.
Definition at line 908 of file relic_fpx_util.c.
References fp18_copy().
Referenced by fp54_exp(), fp54_exp_cyc(), fp54_exp_cyc_sps(), fp54_exp_dig(), fp54_frb(), fp54_pck(), fp54_upk(), and pp_exp_k54().
fp54_copy_sec()
void fp54_copy_sec (fp54_t c, const fp54_t a, dig_t bit)
Conditionally copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the 54-degree extension field element to copy.
[in] bit - the condition bit to evaluate.
Definition at line 914 of file relic_fpx_util.c.
References fp18_copy_sec().
fp54_zero()
void fp54_zero (fp54_t a)
Assigns zero to a 54-extension field element.
Parameters
[out] a - the 54-extension field element to zero.
Definition at line 920 of file relic_fpx_util.c.
References fp18_zero().
Referenced by pp_add_k54_basic(), pp_dbl_k54_basic(), and pp_mil_k54().
fp54_is_zero()
int fp54_is_zero (const fp54_t a)
Tests if a 54-extension field element is zero or not.
Parameters
[in] a - the 54-extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 926 of file relic_fpx_util.c.
References fp18_is_zero().
fp54_rand()
void fp54_rand (fp54_t a)
Assigns a random value to a 54-extension field element.
Parameters
[out] a - the 54-extension field element to assign.
Definition at line 930 of file relic_fpx_util.c.
References fp18_rand().
fp54_print()
void fp54_print (const fp54_t a)
Prints a 54-extension field element to standard output.
Parameters
[in] a - the 54-extension field element to print.
Definition at line 936 of file relic_fpx_util.c.
References fp18_print().
fp54_size_bin()
int fp54_size_bin (fp54_t a, int pack)
Returns the number of bytes necessary to store a 54-extension field element.
Parameters
[in] a - the extension field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 942 of file relic_fpx_util.c.
References fp54_test_cyc(), and RLC_FP_BYTES.
fp54_read_bin()
void fp54_read_bin (fp54_t a, const uint8_t * bin, size_t len)
Reads a 54-extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 954 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp18_read_bin(), fp54_back_cyc(), fp9_read_bin(), fp9_zero(), RLC_FP_BYTES, and RLC_THROW.
fp54_write_bin()
void fp54_write_bin (uint8_t * bin, size_t len, const fp54_t a, int pack)
Writes a 54-extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
[in] pack - the flag to indicate compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 975 of file relic_fpx_util.c.
References ERR_CAUGHT, ERR_NO_BUFFER, fp18_write_bin(), fp54_free, fp54_new, fp54_null, fp54_pck(), fp9_write_bin(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.
fp54_set_dig()
void fp54_set_dig (fp54_t a, const dig_t b)
Assigns a 54-extension field element to a digit.
Parameters
[in] a - the 54-extension field element.
[in] b - the digit.
Definition at line 1007 of file relic_fpx_util.c.
References fp18_set_dig(), and fp18_zero().
Referenced by fp54_exp(), fp54_exp_cyc(), fp54_exp_cyc_sps(), fp54_exp_dig(), and pp_map_k54().