RELIC: src/rand/relic_rand_hashd.c File Reference
relic_rand_hashd.c File Reference
Pseudo-random number generators.
#include <stdlib.h>
#include <stdint.h>
#include "relic_conf.h"
#include "relic_core.h"
#include "relic_label.h"
#include "relic_rand.h"
#include "relic_md.h"
#include "relic_err.h"
Functions
static void rand_hash (uint8_t *out, size_t out_len, uint8_t *in, size_t in_len)
static int rand_inc (uint8_t *data, size_t size, int digit)
static int rand_add (uint8_t *state, uint8_t *hash, size_t size)
static void rand_gen (uint8_t *out, size_t out_len)
void rand_bytes (uint8_t *buf, size_t size)
void rand_seed (uint8_t *buf, size_t size)
Detailed Description
Implementation of the Hash_DRBG pseudo-random number generator.
Definition in file relic_rand_hashd.c.
Function Documentation
rand_hash()
static void rand_hash (uint8_t * out, size_t out_len, uint8_t * in, size_t in_len) static
Definition at line 56 of file relic_rand_hashd.c.
References ERR_NO_MEMORY, md_map, RLC_ALLOCA, RLC_CEIL, RLC_FREE, RLC_MD_LEN, RLC_MIN, RLC_THROW, and util_conv_big().
Referenced by rand_seed().
rand_inc()
static int rand_inc (uint8_t * data, size_t size, int digit) static
Accumulates a small integer in the internal state.
Parameters
[in,out] state - the internal state.
[in] digit - the small integer.
Definition at line 92 of file relic_rand_hashd.c.
Referenced by rand_bytes(), and rand_gen().
rand_add()
static int rand_add (uint8_t * state, uint8_t * hash, size_t size) static
Accumulates the hash value in the internal state.
Parameters
[in,out] state - the internal state.
[in] hash - the hash value.
Definition at line 109 of file relic_rand_hashd.c.
Referenced by rand_bytes().
rand_gen()
static void rand_gen (uint8_t * out, size_t out_len) static
Generates pseudo-random bytes by iterating the hash function.
Parameters
[out] out - the buffer to write.
[in] out_len - the number of bytes to write.
Definition at line 127 of file relic_rand_hashd.c.
References core_get(), md_map, rand_inc(), RLC_CEIL, RLC_MD_LEN, RLC_MIN, and RLC_RAND_SIZE.
Referenced by rand_bytes().
rand_bytes()
void rand_bytes (uint8_t * buf, size_t size)
Gathers pseudo-random bytes from the pseudo-random number generator.
Parameters
[out] buf - the buffer to write.
[in] size - the number of bytes to gather.
Exceptions
ERR_NO_VALID - if the required length is too large.
ERR_NO_READ - it the pseudo-random number generator cannot generate the specified number of bytes.
Definition at line 154 of file relic_rand_hashd.c.
References core_get(), _ctx_t::counter, ERR_NO_VALID, md_map, _ctx_t::rand, rand_add(), rand_gen(), rand_inc(), RLC_MD_LEN, RLC_RAND_SIZE, and RLC_THROW.
Referenced by bn_rand(), cp_cmlhs_gen(), fb_rand(), fp_rand(), pad_pkcs2(), and util_perm().
rand_seed()
void rand_seed (uint8_t * buf, size_t size)
Definition at line 177 of file relic_rand_hashd.c.
References core_get(), _ctx_t::counter, ERR_NO_MEMORY, ERR_NO_VALID, _ctx_t::rand, rand_hash(), RLC_ALLOCA, RLC_FREE, RLC_RAND_SIZE, RLC_THROW, and _ctx_t::seeded.
Referenced by rand_init().