RELIC: src/pp/relic_pp_map_k8.c File Reference
relic_pp_map_k8.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_util.h"
Functions
static void pp_mil_k8 (fp8_t r, ep2_t *t, ep2_t *q, ep_t *p, int m, bn_t a)
void pp_map_oatep_k8 (fp8_t r, const ep_t p, const ep2_t q)
void pp_map_sim_oatep_k8 (fp8_t r, const ep_t *p, const ep2_t *q, int m)
Detailed Description
Implementation of pairing computation for curves with embedding degree 8.
Definition in file relic_pp_map_k8.c.
Function Documentation
pp_mil_k8()
static void pp_mil_k8 (fp8_t r, ep2_t * t, ep2_t * q, ep_t * p, int m, bn_t a) static
Compute the Miller loop for pairings of type G_2 x G_1 over the bits of a given parameter represented in sparse form.
Parameters
[out] r - the result.
[out] t - the resulting point.
[in] q - the vector of first arguments in affine coordinates.
[in] p - the vector of second arguments in affine coordinates.
[in] n - the number of pairings to evaluate.
[in] s - the loop parameter in sparse form. @paramin] len - the length of the loop parameter.
Definition at line 52 of file relic_pp_map_k8.c.
References bn_bits(), bn_rec_naf(), ep2_copy(), ep2_free, ep2_neg(), ep2_new, ep2_null, ep_free, ep_neg(), ep_new, ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp8_free, fp8_mul, fp8_mul_dxs(), fp8_new, fp8_null, fp8_sqr, fp8_zero(), fp_copy(), fp_neg, pp_add_k8, pp_dbl_k8, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by pp_map_oatep_k8(), and pp_map_sim_oatep_k8().
pp_map_oatep_k8()
void pp_map_oatep_k8 (fp8_t r, const ep_t p, const ep2_t q)
Computes the optimal ate pairing of two points in a parameterized elliptic curve with embedding degree 8.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 124 of file relic_pp_map_k8.c.
References bn_free, bn_new, bn_null, bn_sign(), ep2_free, ep2_is_infty(), ep2_neg(), ep2_new, ep2_norm(), ep2_null, ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, fp8_inv_cyc(), fp8_set_dig(), fp_prime_get_par(), pp_exp_k8(), pp_mil_k8(), RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
pp_map_sim_oatep_k8()
void pp_map_sim_oatep_k8 (fp8_t r, const ep_t * p, const ep2_t * q, int m)
Computes the optimal ate multi-pairing in a parameterized elliptic curve with embedding degree 8.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 167 of file relic_pp_map_k8.c.
References bn_free, bn_new, bn_null, bn_sign(), ep2_is_infty(), ep2_neg(), ep2_new, ep2_norm(), ep2_null, ep4_free, ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp8_inv_cyc(), fp8_set_dig(), fp_prime_get_par(), pp_exp_k8(), pp_mil_k8(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.