RELIC: src/bn/relic_bn_gcd.c File Reference
relic_bn_gcd.c File Reference
Multiple precision integer arithmetic
#include "relic_core.h"
Functions
void bn_gcd_basic (bn_t c, const bn_t a, const bn_t b)
void bn_gcd_ext_basic (bn_t c, bn_t d, bn_t e, const bn_t a, const bn_t b)
void bn_gcd_lehme (bn_t c, const bn_t a, const bn_t b)
void bn_gcd_ext_lehme (bn_t c, bn_t d, bn_t e, const bn_t a, const bn_t b)
void bn_gcd_binar (bn_t c, const bn_t a, const bn_t b)
void bn_gcd_ext_binar (bn_t c, bn_t d, bn_t e, const bn_t a, const bn_t b)
void bn_gcd_ext_mid (bn_t c, bn_t d, bn_t e, bn_t f, const bn_t a, const bn_t b)
void bn_gcd_dig (bn_t c, const bn_t a, dig_t b)
void bn_gcd_ext_dig (bn_t c, bn_t d, bn_t e, const bn_t a, const dig_t b)
Detailed Description
Implementation of the multiple precision addition and subtraction functions.
Definition in file relic_bn_gcd.c.
Function Documentation
bn_gcd_basic()
void bn_gcd_basic (bn_t c, const bn_t a, const bn_t b)
Computes the greatest common divisor of two multiple precision integers using the standard Euclidean algorithm.
Parameters
[out] c - the result;
[in] a - the first multiple precision integer.
[in] b - the second multiple precision integer.
Definition at line 40 of file relic_bn_gcd.c.
References bn_abs(), bn_copy(), bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
bn_gcd_ext_basic()
void bn_gcd_ext_basic (bn_t c, bn_t d, bn_t e, const bn_t a, const bn_t b)
Computes the extended greatest common divisor of two multiple precision integer using the Euclidean algorithm.
Parameters
[out] c - the result.
[out] d - the cofactor of the first operand, can be NULL.
[out] e - the cofactor of the second operand, can be NULL.
[in] a - the first multiple precision integer.
[in] b - the second multiple precision integer.
Definition at line 77 of file relic_bn_gcd.c.
References bn_abs(), bn_copy(), bn_div_rem(), bn_free, bn_is_zero(), bn_mul, bn_new, bn_null, bn_set_dig(), bn_sub(), bn_zero(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
bn_gcd_lehme()
void bn_gcd_lehme (bn_t c, const bn_t a, const bn_t b)
Computes the greatest common divisor of two multiple precision integers using Lehmer's GCD algorithm.
Parameters
[out] c - the result;
[in] a - the first multiple precision integer.
[in] b - the second multiple precision integer.
Definition at line 160 of file relic_bn_gcd.c.
References bn_abs(), bn_add(), bn_bits(), bn_cmp_abs(), bn_copy(), bn_free, bn_gcd_ext_dig(), bn_is_zero(), bn_mod, bn_mul_dig(), bn_neg(), bn_new, bn_null, bn_rsh(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_GT, RLC_THROW, and RLC_TRY.
bn_gcd_ext_lehme()
void bn_gcd_ext_lehme (bn_t c, bn_t d, bn_t e, const bn_t a, const bn_t b)
Computes the greatest common divisor of two multiple precision integers using Lehmer's algorithm.
Parameters
[out] c - the result;
[out] d - the cofactor of the first operand, can be NULL.
[out] e - the cofactor of the second operand, can be NULL.
[in] a - the first multiple precision integer.
[in] b - the second multiple precision integer.
Definition at line 356 of file relic_bn_gcd.c.
References bn_abs(), bn_add(), bn_bits(), bn_cmp_abs(), bn_copy(), bn_div(), bn_div_rem(), bn_free, bn_gcd_ext_dig(), bn_is_zero(), bn_mul, bn_mul_dig(), bn_neg(), bn_new, bn_null, bn_rsh(), bn_set_dig(), bn_sub(), bn_zero(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_LT, RLC_THROW, and RLC_TRY.
bn_gcd_binar()
void bn_gcd_binar (bn_t c, const bn_t a, const bn_t b)
Computes the greatest common divisor of two multiple precision integers using the Binary GCD algorithm.
Parameters
[out] c - the result;
[in] a - the first multiple precision integer.
[in] b - the second multiple precision integer.
Definition at line 623 of file relic_bn_gcd.c.
References bn_abs(), bn_cmp(), bn_copy(), bn_free, bn_hlv(), bn_is_even(), bn_is_zero(), bn_lsh(), bn_new, bn_null, bn_sub(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_LT, RLC_THROW, and RLC_TRY.
bn_gcd_ext_binar()
void bn_gcd_ext_binar (bn_t c, bn_t d, bn_t e, const bn_t a, const bn_t b)
Computes the greatest common divisor of two multiple precision integers using the Binary algorithm.
Parameters
[out] c - the result;
[out] d - the cofactor of the first operand, can be NULL.
[out] e - the cofactor of the second operand, can be NULL.
[in] a - the first multiple precision integer.
[in] b - the second multiple precision integer.
Definition at line 683 of file relic_bn_gcd.c.
References bn_abs(), bn_add(), bn_bits(), bn_cmp(), bn_cmp_abs(), bn_copy(), bn_div(), bn_free, bn_hlv(), bn_is_even(), bn_is_zero(), bn_lsh(), bn_mul, bn_new, bn_null, bn_set_dig(), bn_sign(), bn_sub(), bn_zero(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_GT, RLC_LT, RLC_THROW, and RLC_TRY.
bn_gcd_ext_mid()
void bn_gcd_ext_mid (bn_t c, bn_t d, bn_t e, bn_t f, const bn_t a, const bn_t b)
Computes the extended greatest common divisor of two multiple precision integers halfway through the algorithm. Returns also two short vectors v1 = (c, d), v2 = (-e, f) useful to decompose an integer k into k0, k1 such that k = k_0 + k_1 * a (mod b).
Parameters
[out] c - the first component of the first vector.
[out] d - the second component of the first vector.
[out] e - the first component of the second vector.
[out] f - the second component of the second vector.
[in] a - the first multiple precision integer.
[in] b - the second multiple precision integer.
Definition at line 836 of file relic_bn_gcd.c.
References bn_abs(), bn_add(), bn_cmp(), bn_cmp_abs(), bn_copy(), bn_div_rem(), bn_free, bn_is_zero(), bn_mul, bn_neg(), bn_new, bn_null, bn_set_dig(), bn_sqr, bn_srt(), bn_sub(), bn_zero(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_GT, RLC_LT, RLC_THROW, and RLC_TRY.
Referenced by ep_curve_set_endom().
bn_gcd_dig()
void bn_gcd_dig (bn_t c, const bn_t a, dig_t b)
Computes the greatest common divisor of a multiple precision integer and a digit.
Parameters
[out] c - the result;
[in] a - the multiple precision integer.
[in] b - the digit.
Definition at line 949 of file relic_bn_gcd.c.
References bn_abs(), bn_is_zero(), bn_mod_dig(), and bn_set_dig().
Referenced by bn_gcd_ext_dig(), and cp_bdpe_gen().
bn_gcd_ext_dig()
void bn_gcd_ext_dig (bn_t c, bn_t d, bn_t e, const bn_t a, dig_t b)
Computes the extended greatest common divisor of a multiple precision integer and a digit.
Parameters
[out] c - the result.
[out] d - the cofactor of the first operand, can be NULL.
[out] e - the cofactor of the second operand, can be NULL.
[in] a - the multiple precision integer.
[in] b - the digit.
Definition at line 973 of file relic_bn_gcd.c.
References bn_abs(), bn_copy(), bn_div_rem(), bn_free, bn_gcd_dig(), bn_is_zero(), bn_mul, bn_mul_dig(), bn_new, bn_null, bn_set_dig(), bn_sub(), bn_zero(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by bn_gcd_ext_lehme(), and bn_gcd_lehme().