RELIC: src/pc/relic_pc_util.c File Reference
relic_pc_util.c File Reference
Pairing-based cryptography
#include "relic_pc.h"
#include "relic_core.h"
Macros
#define gt_rand_imp(A)
Functions
void gt_rand (gt_t a)
void gt_get_gen (gt_t g)
int g1_is_valid (const g1_t a)
int g2_is_valid (const g2_t a)
int gt_is_valid (const gt_t a)
Detailed Description
Implementation of pairing computation utilities.
Definition in file relic_pc_util.c.
Macro Definition Documentation
gt_rand_imp
#define gt_rand_imp (A)
Value:
RLC_CAT(RLC_GT_LOWER, rand)(A)
Internal macro to map GT function to basic FPX implementation. The final exponentiation from the pairing is used to move element to subgroup.
Parameters
[out] A - the element to assign.
Definition at line 44 of file relic_pc_util.c.
Referenced by gt_rand().
Function Documentation
gt_rand()
void gt_rand (gt_t a)
Assigns a random value to an element from G_T.
Parameters
[out] a - the element to assign.
Definition at line 50 of file relic_pc_util.c.
References gt_rand_imp, pp_exp_k1(), pp_exp_k12(), pp_exp_k16(), pp_exp_k18(), pp_exp_k2(), pp_exp_k24(), pp_exp_k48(), and pp_exp_k8().
Referenced by cp_mpsb_ver(), and cp_mpss_ver().
gt_get_gen()
void gt_get_gen (gt_t g)
Returns the generator for the group G_T.
Parameters
[out] g - the returned generator.
Definition at line 75 of file relic_pc_util.c.
References core_get(), and gt_copy.
Referenced by cp_bbs_gen(), cp_zss_gen(), and gt_exp_gen().
g1_is_valid()
int g1_is_valid (const g1_t a)
Checks if an element from G_1 is valid (has the right order).
Parameters
[in] a - the element to check.
Definition at line 79 of file relic_pc_util.c.
References bn_add_dig(), bn_cmp_dig(), bn_div_dig(), bn_free, bn_hlv(), bn_is_even(), bn_mul, bn_mul_dig(), bn_neg(), bn_new, bn_null, bn_rec_naf(), bn_sign(), bn_sqr, bn_sub_dig(), EP_AFG16, EP_B12, EP_B24, EP_B48, ep_copy(), ep_curve_get_cof(), ep_curve_is_pairf(), EP_FM16, EP_FM18, EP_K16, EP_K18, ep_psi(), EP_SG18, ERR_CAUGHT, fp_prime_get_par(), g1_add, g1_cmp, g1_dbl, g1_free, g1_is_infty, g1_mul_any, g1_mul_dig, g1_neg, g1_new, g1_norm, g1_null, g1_on_curve, g1_sub, pc_get_ord, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by cp_bbs_ver(), and g2_is_valid().
g2_is_valid()
int g2_is_valid (const g2_t a)
Checks if an element form G_2 is valid (has the right order).
Parameters
[in] a - the element to check.
Definition at line 268 of file relic_pc_util.c.
References B12_383, bn_div_dig(), bn_free, bn_is_even(), bn_mod_dig(), bn_mul_dig(), bn_neg(), bn_new, bn_null, bn_sub_dig(), core_get(), EP_AFG16, EP_B12, EP_B24, EP_B48, EP_BN, ep_curve_is_pairf(), EP_FM16, EP_FM18, EP_K16, EP_K18, EP_SG18, ERR_CAUGHT, fp_prime_get_par(), g1_is_valid(), g2_add, g2_cmp, g2_copy, g2_dbl, g2_frb, g2_free, g2_is_infty, g2_mul_any, g2_neg, g2_new, g2_null, g2_on_curve, g2_sub, pc_get_ord, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by cp_bls_ver().
gt_is_valid()
int gt_is_valid (const gt_t a)
Checks if an element form G_T is valid (has the right order).
Parameters
[in] a - the element to check.
Definition at line 459 of file relic_pc_util.c.
References B12_383, bn_div_dig(), bn_free, bn_is_even(), bn_mod_dig(), bn_mul_dig(), bn_neg(), bn_new, bn_null, bn_sign(), bn_sub_dig(), core_get(), EP_AFG16, EP_B12, EP_B24, EP_B48, EP_BN, ep_curve_is_pairf(), EP_FM16, EP_FM18, EP_K16, EP_K18, EP_SG18, ERR_CAUGHT, fp12_exp_cyc_sps(), fp12_test_cyc(), fp16_test_cyc(), fp18_exp_cyc_sps(), fp18_test_cyc(), fp24_exp_cyc_sps(), fp24_test_cyc(), fp48_exp_cyc_sps(), fp48_test_cyc(), fp_prime_get_par(), fp_prime_get_par_sps(), gt_cmp, gt_copy, gt_exp(), gt_frb, gt_free, gt_inv, gt_is_unity, gt_mul, gt_new, gt_null, gt_sqr, pc_get_ord, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by cp_lvprv_ver(), cp_lvpub_ver(), cp_pdprv_ver(), and cp_pdpub_ver().