RELIC: src/epx/relic_ep2_mul.c File Reference
relic_ep2_mul.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
static void ep2_mul_gls_imp (ep2_t r, const ep2_t p, const bn_t k)
static void ep2_mul_reg_gls (ep2_t r, const ep2_t p, const bn_t k)
static void ep2_mul_naf_imp (ep2_t r, const ep2_t p, const bn_t k)
static void ep2_mul_reg_imp (ep2_t r, const ep2_t p, const bn_t k)
void ep2_mul_basic (ep2_t r, const ep2_t p, const bn_t k)
void ep2_mul_slide (ep2_t r, const ep2_t p, const bn_t k)
void ep2_mul_monty (ep2_t r, const ep2_t p, const bn_t k)
void ep2_mul_lwnaf (ep2_t r, const ep2_t p, const bn_t k)
void ep2_mul_lwreg (ep2_t r, const ep2_t p, const bn_t k)
void ep2_mul_gen (ep2_t r, const bn_t k)
void ep2_mul_dig (ep2_t r, const ep2_t p, const dig_t k)
Detailed Description
Implementation of point multiplication on prime elliptic curves over a quadratic extension field.
Definition in file relic_ep2_mul.c.
Function Documentation
ep2_mul_gls_imp()
static void ep2_mul_gls_imp (ep2_t r, const ep2_t p, const bn_t k) static
Definition at line 43 of file relic_ep2_mul.c.
References bn_free, bn_mod, bn_new, bn_null, bn_rec_frb(), bn_rec_naf(), bn_sign(), ep2_add, ep2_curve_get_ord(), ep2_dbl, ep2_frb(), ep2_free, ep2_neg(), ep2_new, ep2_norm(), ep2_null, ep2_set_infty(), ep2_sub(), ep2_tab(), EP_BN, ep_curve_is_pairf(), ERR_CAUGHT, fp_prime_get_par(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by ep2_mul_lwnaf().
ep2_mul_reg_gls()
static void ep2_mul_reg_gls (ep2_t r, const ep2_t p, const bn_t k) static
Definition at line 129 of file relic_ep2_mul.c.
References BASIC, bn_add_dig(), bn_bits(), bn_free, bn_is_even(), bn_mod, bn_new, bn_null, bn_rec_frb(), bn_rec_sac(), bn_sign(), ep2_add, ep2_copy(), ep2_curve_get_ord(), ep2_dbl, ep2_frb(), ep2_free, ep2_neg(), ep2_new, ep2_norm(), ep2_norm_sim(), ep2_null, ep2_sub(), EP_ADD, EP_BN, ep_curve_is_pairf(), ERR_CAUGHT, fp2_copy_sec(), fp2_set_dig(), fp_prime_get_par(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_POS, RLC_THROW, RLC_TRY, and util_bits_dig().
Referenced by ep2_mul_lwreg().
ep2_mul_naf_imp()
static void ep2_mul_naf_imp (ep2_t r, const ep2_t p, const bn_t k) static
Definition at line 253 of file relic_ep2_mul.c.
References bn_rec_naf(), bn_sign(), ep2_add, ep2_dbl, ep2_free, ep2_neg(), ep2_new, ep2_norm(), ep2_null, ep2_set_infty(), ep2_sub(), ep2_tab(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by ep2_mul_lwnaf().
ep2_mul_reg_imp()
static void ep2_mul_reg_imp (ep2_t r, const ep2_t p, const bn_t k) static
Definition at line 304 of file relic_ep2_mul.c.
References BASIC, bn_abs(), bn_bits(), bn_free, bn_is_even(), bn_new, bn_null, bn_rec_reg(), bn_sign(), ep2_add, ep2_curve_get_ord(), ep2_dbl, ep2_free, ep2_neg(), ep2_new, ep2_norm(), ep2_null, ep2_set_infty(), ep2_sub(), ep2_tab(), EP_ADD, ERR_CAUGHT, fp2_copy_sec(), fp2_set_dig(), fp_copy_sec(), RLC_CATCH_ANY, RLC_CEIL, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by ep2_mul_lwreg().
ep2_mul_basic()
void ep2_mul_basic (ep2_t r, const ep2_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the binary method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 393 of file relic_ep2_mul.c.
References bn_bits(), bn_is_zero(), bn_rec_naf(), bn_sign(), ep2_add, ep2_dbl, ep2_free, ep2_is_infty(), ep2_mul_dig(), ep2_neg(), ep2_new, ep2_norm(), ep2_null, ep2_set_infty(), ep2_sub(), ERR_CAUGHT, ERR_NO_BUFFER, RLC_ALLOCA, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by ep2_frb(), ep2_mul_cof_b12(), and ep2_mul_cof_bn().
ep2_mul_slide()
void ep2_mul_slide (ep2_t r, const ep2_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the sliding window method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 451 of file relic_ep2_mul.c.
References bn_is_zero(), bn_rec_slw(), bn_sign(), ep2_add, ep2_copy(), ep2_dbl, ep2_free, ep2_is_infty(), ep2_neg(), ep2_new, ep2_norm(), ep2_norm_sim(), ep2_null, ep2_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_THROW, RLC_TRY, RLC_WIDTH, and util_bits_dig().
ep2_mul_monty()
void ep2_mul_monty (ep2_t r, const ep2_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the constant-time Montgomery ladder point multiplication method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 521 of file relic_ep2_mul.c.
References bn_abs(), bn_add(), bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_new, bn_null, dv_swap_sec(), ep2_add, ep2_blind(), ep2_curve_get_ord(), ep2_dbl, ep2_free, ep2_is_infty(), ep2_new, ep2_norm(), ep2_null, ep2_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_MAX, RLC_SEL, RLC_THROW, and RLC_TRY.
ep2_mul_lwnaf()
void ep2_mul_lwnaf (ep2_t r, const ep2_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the w-NAF method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 597 of file relic_ep2_mul.c.
References bn_is_zero(), ep2_is_infty(), ep2_mul_gls_imp(), ep2_mul_naf_imp(), ep2_set_infty(), and ep_curve_is_endom().
ep2_mul_lwreg()
void ep2_mul_lwreg (ep2_t r, const ep2_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using a regular method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 619 of file relic_ep2_mul.c.
References bn_is_zero(), ep2_is_infty(), ep2_mul_reg_gls(), ep2_mul_reg_imp(), ep2_set_infty(), and ep_curve_is_endom().
ep2_mul_gen()
void ep2_mul_gen (ep2_t r, const bn_t k)
Multiplies the generator of an elliptic curve over a qaudratic extension.
Parameters
[out] r - the result.
[in] k - the integer.
Definition at line 639 of file relic_ep2_mul.c.
References bn_is_zero(), ep2_curve_get_gen(), ep2_curve_get_tab(), ep2_free, ep2_mul, ep2_mul_fix, ep2_new, ep2_null, ep2_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep2_mul_sim_gen(), and ep2_rand().
ep2_mul_dig()
void ep2_mul_dig (ep2_t r, const ep2_t p, const dig_t k)
Multiplies a prime elliptic point by a small integer.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 666 of file relic_ep2_mul.c.
References bn_free, bn_new, bn_null, bn_rec_naf(), bn_set_dig(), ep2_add, ep2_copy(), ep2_dbl, ep2_free, ep2_is_infty(), ep2_new, ep2_norm(), ep2_null, ep2_set_infty(), ep2_sub(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep2_mul_basic().