RELIC: src/fb/relic_fb_exp.c File Reference
relic_fb_exp.c File Reference
Multiple precision integer arithmetic
#include <string.h>
#include "relic_conf.h"
#include "relic_core.h"
#include "relic_fb.h"
#include "relic_bn.h"
#include "relic_util.h"
Functions
void fb_exp_basic (fb_t c, const fb_t a, const bn_t b)
void fb_exp_slide (fb_t c, const fb_t a, const bn_t b)
void fb_exp_monty (fb_t c, const fb_t a, const bn_t b)
Detailed Description
Implementation of prime field exponentiation functions.
Definition in file relic_fb_exp.c.
Function Documentation
fb_exp_basic()
void fb_exp_basic (fb_t c, const fb_t a, const bn_t b)
Exponentiates a binary field element using the binary method.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 46 of file relic_fb_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), ERR_CAUGHT, fb_copy(), fb_free, fb_inv, fb_mul, fb_new, fb_null, fb_set_dig(), fb_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
fb_exp_slide()
void fb_exp_slide (fb_t c, const fb_t a, const bn_t b)
Exponentiates a binary field element using the sliding window method.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 89 of file relic_fb_exp.c.
References bn_is_zero(), bn_rec_slw(), bn_sign(), ERR_CAUGHT, fb_copy(), fb_free, fb_inv, fb_mul, fb_new, fb_null, fb_set_dig(), fb_sqr, RLC_CATCH_ANY, RLC_FB_BITS, RLC_FINALLY, RLC_NEG, RLC_THROW, RLC_TRY, RLC_WIDTH, and util_bits_dig().
fb_exp_monty()
void fb_exp_monty (fb_t c, const fb_t a, const bn_t b)
Exponentiates a binary field element using the constant-time Montgomery powering ladder method.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 156 of file relic_fb_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), dv_swap_sec(), ERR_CAUGHT, fb_copy(), fb_free, fb_inv, fb_mul, fb_new, fb_null, fb_set_dig(), fb_sqr, RLC_CATCH_ANY, RLC_FB_DIGS, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.