RELIC: src/epx/relic_ep2_util.c File Reference
relic_ep2_util.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
int ep2_is_infty (const ep2_t p)
void ep2_set_infty (ep2_t p)
void ep2_copy (ep2_t r, const ep2_t p)
void ep2_rand (ep2_t p)
void ep2_blind (ep2_t r, const ep2_t p)
void ep2_rhs (fp2_t rhs, const fp2_t x)
int ep2_on_curve (const ep2_t p)
void ep2_tab (ep2_t *t, const ep2_t p, int w)
void ep2_print (const ep2_t p)
size_t ep2_size_bin (const ep2_t a, int pack)
void ep2_read_bin (ep2_t a, const uint8_t *bin, size_t len)
void ep2_write_bin (uint8_t *bin, size_t len, const ep2_t a, int pack)
Detailed Description
Implementation of comparison for points on prime elliptic curves over a quadratic extension field.
Definition in file relic_ep2_util.c.
Function Documentation
ep2_is_infty()
int ep2_is_infty (const ep2_t p)
Tests if a point on an elliptic curve is at the infinity.
Parameters
[in] p - the point to test.
Returns
1 if the point is at infinity, 0 otherise.
Definition at line 39 of file relic_ep2_util.c.
References fp2_is_zero().
Referenced by ep2_add_basic(), ep2_add_jacob(), ep2_add_projc(), ep2_add_slp_basic(), ep2_cmp(), ep2_dbl_basic(), ep2_dbl_jacob(), ep2_dbl_projc(), ep2_dbl_slp_basic(), ep2_mul_basic(), ep2_mul_dig(), ep2_mul_lwnaf(), ep2_mul_lwreg(), ep2_mul_monty(), ep2_mul_sim_gen(), ep2_mul_sim_inter(), ep2_mul_sim_joint(), ep2_mul_sim_trick(), ep2_mul_slide(), ep2_neg(), ep2_norm(), ep2_norm_sim(), ep2_on_curve(), ep2_size_bin(), ep2_write_bin(), pp_map_oatep_k12(), pp_map_oatep_k8(), pp_map_sim_oatep_k12(), pp_map_sim_oatep_k8(), pp_map_sim_tatep_k12(), pp_map_sim_weilp_k12(), pp_map_tatep_k12(), pp_map_weilp_k12(), pp_norm_k12(), and pp_norm_k8().
ep2_set_infty()
void ep2_set_infty (ep2_t p)
Assigns an elliptic curve point to the point at infinity.
Parameters
[out] p - the point to assign.
Definition at line 43 of file relic_ep2_util.c.
References BASIC, and fp2_zero().
Referenced by ep2_dbl_basic(), ep2_dbl_jacob(), ep2_dbl_projc(), ep2_dbl_slp_basic(), ep2_map_swift(), ep2_mul_basic(), ep2_mul_dig(), ep2_mul_fix_basic(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_fix_lwnaf(), ep2_mul_fix_plain(), ep2_mul_gen(), ep2_mul_gls_imp(), ep2_mul_lwnaf(), ep2_mul_lwreg(), ep2_mul_monty(), ep2_mul_naf_imp(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_reg_imp(), ep2_mul_sim_dig(), ep2_mul_sim_endom(), ep2_mul_sim_joint(), ep2_mul_sim_lot(), ep2_mul_sim_plain(), ep2_mul_sim_trick(), ep2_mul_slide(), ep2_neg(), ep2_norm(), ep2_read_bin(), ep2_sub(), pp_norm_k12(), and pp_norm_k8().
ep2_copy()
void ep2_copy (ep2_t r, const ep2_t p)
Copies the second argument to the first argument.
Parameters
[out] q - the result.
[in] p - the elliptic curve point to copy.
Definition at line 50 of file relic_ep2_util.c.
References fp2_copy().
Referenced by ep2_add_basic(), ep2_add_jacob(), ep2_add_projc(), ep2_add_slp_basic(), ep2_blind(), ep2_cmp(), ep2_curve_get_gen(), ep2_curve_set_twist(), ep2_frb(), ep2_mul_dig(), ep2_mul_fix_combs(), ep2_mul_pre_basic(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_reg_gls(), ep2_mul_sim_joint(), ep2_mul_sim_lot(), ep2_mul_sim_trick(), ep2_mul_slide(), ep2_norm(), ep2_norm_imp(), ep2_tab(), pp_add_k12_basic(), pp_add_k8_basic(), pp_dbl_k12_basic(), pp_dbl_k8_basic(), pp_mil_k12(), pp_mil_k8(), pp_norm_k12(), and pp_norm_k8().
ep2_rand()
void ep2_rand (ep2_t p)
Assigns a random value to an elliptic curve point.
Parameters
[out] p - the elliptic curve point to assign.
Definition at line 57 of file relic_ep2_util.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), ep2_curve_get_ord(), ep2_mul_gen(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep2_blind()
void ep2_blind (ep2_t r, const ep2_t p)
Randomizes coordinates of an elliptic curve point.
Parameters
[out] r - the blinded prime elliptic curve point.
[in] p - the prime elliptic curve point to blind.
Definition at line 81 of file relic_ep2_util.c.
References ep2_copy(), ERR_CAUGHT, fp2_free, fp2_mul, fp2_new, fp2_null, fp2_rand(), fp2_sqr, JACOB, PROJC, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep2_mul_monty().
ep2_rhs()
void ep2_rhs (fp2_t rhs, const fp2_t x)
Computes the right-hand side of the elliptic curve equation at the x-coordinate of a certain prime elliptic curve point.
Parameters
[out] rhs - the result.
[in] x - the x-coordinate of the point.
Definition at line 112 of file relic_ep2_util.c.
References ep2_curve_get_a(), ep2_curve_get_b(), ep2_curve_opt_a(), ep2_curve_opt_b(), ERR_CAUGHT, fp2_add, fp2_add_dig(), fp2_copy(), fp2_free, fp2_mul, fp2_mul_dig(), fp2_new, fp2_null, fp2_sqr, fp2_sub_dig(), RLC_CATCH_ANY, RLC_FINALLY, RLC_MIN3, RLC_ONE, RLC_THROW, RLC_TINY, RLC_TRY, RLC_TWO, and RLC_ZERO.
Referenced by ep2_map_basic(), ep2_map_swift(), ep2_on_curve(), and ep2_upk().
ep2_on_curve()
int ep2_on_curve (const ep2_t p)
Tests if a point is in the curve.
Parameters
[in] p - the point to test.
Definition at line 177 of file relic_ep2_util.c.
References ep2_free, ep2_is_infty(), ep2_new, ep2_norm(), ep2_null, ep2_rhs(), ERR_CAUGHT, fp2_cmp(), fp2_sqr, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep2_read_bin().
ep2_tab()
void ep2_tab (ep2_t * t, const ep2_t p, int w)
Builds a precomputation table for multiplying a random prime elliptic point.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
[in] w - the window width.
Definition at line 200 of file relic_ep2_util.c.
References ep2_add, ep2_copy(), ep2_dbl, ep2_norm(), and ep2_norm_sim().
Referenced by ep2_mul_gls_imp(), ep2_mul_naf_imp(), ep2_mul_pre_lwnaf(), ep2_mul_reg_imp(), and ep2_mul_sim_plain().
ep2_print()
void ep2_print (const ep2_t p)
Prints an elliptic curve point.
Parameters
[in] p - the elliptic curve point to print.
Definition at line 221 of file relic_ep2_util.c.
References fp2_print().
ep2_size_bin()
size_t ep2_size_bin (const ep2_t a, int pack)
Returns the number of bytes necessary to store a prime elliptic curve point over a quadratic extension with optional point compression.
Parameters
[in] a - the prime field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 227 of file relic_ep2_util.c.
References ep2_free, ep2_is_infty(), ep2_new, ep2_norm(), ep2_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.
ep2_read_bin()
void ep2_read_bin (ep2_t a, const uint8_t * bin, size_t len)
Reads a prime elliptic curve point over a quadratic extension from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_VALID - if the encoded point is invalid.
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 255 of file relic_ep2_util.c.
References BASIC, ep2_on_curve(), ep2_set_infty(), ep2_upk(), ERR_NO_BUFFER, ERR_NO_VALID, fp2_read_bin(), fp2_set_dig(), fp2_zero(), fp_set_bit(), fp_zero(), RLC_FP_BYTES, and RLC_THROW.
ep2_write_bin()
void ep2_write_bin (uint8_t * bin, size_t len, const ep2_t a, int pack)
Writes a prime elliptic curve pointer over a quadratic extension to a byte vector in big-endian format with optional point compression.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the prime elliptic curve point to write.
[in] pack - the flag to indicate point compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 305 of file relic_ep2_util.c.
References ep2_free, ep2_is_infty(), ep2_new, ep2_norm(), ep2_null, ep2_pck(), ERR_CAUGHT, ERR_NO_BUFFER, fp2_write_bin(), fp_get_bit(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.