RELIC: src/ep/relic_ep_neg.c File Reference
relic_ep_neg.c File Reference
Elliptic curves over prime fields
#include "relic_core.h"
Functions
void ep_neg (ep_t r, const ep_t p)
Detailed Description
Implementation of the point negation on prime elliptic curves.
Definition in file relic_ep_neg.c.
Function Documentation
ep_neg()
void ep_neg (ep_t r, const ep_t p)
Negates a prime elliptic curve point.
Parameters
[out] r - the result.
[in] p - the point to negate.
Definition at line 38 of file relic_ep_neg.c.
References ep_is_infty(), ep_set_infty(), fp_copy(), and fp_neg.
Referenced by ep_mul_basic(), ep_mul_cof(), ep_mul_fix_plain(), ep_mul_glv_imp(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_mul_sim_endom(), ep_mul_sim_joint(), ep_mul_sim_lot_endom(), ep_mul_sim_lot_plain(), ep_sub(), pp_fin_k16_oatep(), pp_fin_k18_oatep(), pp_mil_k12(), pp_mil_k16(), pp_mil_k18(), pp_mil_k2(), pp_mil_k24(), pp_mil_k48(), pp_mil_k54(), pp_mil_k8(), and pp_mil_lit_k2().