RELIC: src/cp/relic_cp_pss.c File Reference
relic_cp_pss.c File Reference
Cryptographic protocols
#include "relic.h"
Functions
int cp_pss_gen (bn_t r, bn_t s, g2_t g, g2_t x, g2_t y)
int cp_pss_sig (g1_t a, g1_t b, const bn_t m, const bn_t r, const bn_t s)
int cp_pss_ver (const g1_t a, const g1_t b, const bn_t m, const g2_t g, const g2_t x, const g2_t y)
int cp_psb_gen (bn_t r, bn_t s[], g2_t g, g2_t x, g2_t y[], size_t l)
int cp_psb_sig (g1_t a, g1_t b, const bn_t ms[], const bn_t r, const bn_t s[], size_t l)
int cp_psb_ver (const g1_t a, const g1_t b, const bn_t ms[], const g2_t g, const g2_t x, const g2_t y[], size_t l)
Detailed Description
Implementation of the Pointcheval-Sanders signature protocols.
Definition in file relic_cp_pss.c.
Function Documentation
cp_pss_gen()
int cp_pss_gen (bn_t u, bn_t v, g2_t g, g2_t x, g2_t y)
Generates a key pair for the Pointcheval-Sanders simple signature (PSS) protocol.
Parameters
[out] u - the first part of the private key.
[out] v - the second part of the private key.
[out] g - the first part of the public key.
[out] x - the secpmd part of the public key.
[out] y - the third part of the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_pss.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), g2_mul(), g2_rand, pc_get_ord, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_pss_sig()
int cp_pss_sig (g1_t a, g1_t b, const bn_t m, const bn_t u, const bn_t v)
Signs a message using the PSS protocol.
Parameters
[out] a - the first part of the signature.
[out] b - the second part of the signature.
[in] m - the message to sign.
[in] u - the first part of the private key.
[in] v - the second part of the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 63 of file relic_cp_pss.c.
References bn_add(), bn_free, bn_mod, bn_mul, bn_new, bn_null, g1_get_ord, g1_mul(), g1_rand, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_pss_ver()
int cp_pss_ver (const g1_t a, const g1_t b, const bn_t m, const g2_t g, const g2_t x, const g2_t y)
Verifies a signature using the PSS protocol.
Parameters
[in] a - the first part of the signature.
[in] b - the second part of the signature.
[in] m - the message to sign.
[in] g - the first part of the public key.
[in] u - the second part of the public key.
[in] v - the third part of the public key.
Returns
a boolean value indicating the verification result.
Definition at line 91 of file relic_cp_pss.c.
References ERR_CAUGHT, g1_copy, g1_free, g1_is_infty, g1_new, g1_null, g2_add, g2_copy, g2_free, g2_mul(), g2_neg, g2_new, g2_norm, g2_null, gt_free, gt_is_unity, gt_new, gt_null, pc_map_sim, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
cp_psb_gen()
int cp_psb_gen (bn_t r, bn_t s[], g2_t g, g2_t x, g2_t y[], size_t l)
Definition at line 138 of file relic_cp_pss.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), g2_mul(), g2_rand, pc_get_ord, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_psb_sig()
int cp_psb_sig (g1_t a, g1_t b, const bn_t ms[], const bn_t r, const bn_t s[], size_t l)
Definition at line 165 of file relic_cp_pss.c.
References bn_add(), bn_copy(), bn_free, bn_mod, bn_mul, bn_new, bn_null, g1_mul(), g1_rand, pc_get_ord, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_psb_ver()
int cp_psb_ver (const g1_t a, const g1_t b, const bn_t ms[], const g2_t g, const g2_t x, const g2_t y[], size_t l)
Definition at line 205 of file relic_cp_pss.c.
References bn_free, bn_new, bn_null, ERR_CAUGHT, g1_copy, g1_free, g1_is_infty, g1_new, g1_null, g2_add, g2_copy, g2_free, g2_mul_sim_lot, g2_neg, g2_new, g2_norm, g2_null, gt_free, gt_is_unity, gt_new, gt_null, pc_get_ord, pc_map_sim, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.