RELIC: include/relic_epx.h File Reference
relic_epx.h File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_fpx.h"
#include "relic_ep.h"
#include "relic_types.h"
Data Structures
struct ep2_st
struct ep3_st
struct ep4_st
struct ep8_st
struct iso2_st
Macros
#define RLC_EPX_TABLE_BASIC (2 * RLC_FP_BITS + 1)
#define RLC_EPX_TABLE_COMBS (1 << RLC_DEPTH)
#define RLC_EPX_TABLE_COMBD (1 << (RLC_DEPTH + 1))
#define RLC_EPX_TABLE_LWNAF (1 << (RLC_DEPTH - 2))
#define RLC_EPX_TABLE RLC_EPX_TABLE_COMBS
#define RLC_EPX_TABLE_MAX RLC_MAX(RLC_EPX_TABLE_BASIC, RLC_EPX_TABLE_COMBD)
#define RLC_EPX_CTMAP_MAX 4
#define ep2_null(A)
#define ep2_new(A)
#define ep2_free(A)
#define ep3_null(A)
#define ep3_new(A)
#define ep3_free(A)
#define ep4_null(A)
#define ep4_new(A)
#define ep4_free(A)
#define ep8_null(A)
#define ep8_new(A)
#define ep8_free(A)
#define ep2_add(R, P, Q)
#define ep2_dbl(R, P)
#define ep2_mul(R, P, K)
#define ep2_mul_pre(T, P)
#define ep2_mul_fix(R, T, K)
#define ep2_mul_sim(R, P, K, Q, M)
#define ep2_mul_big(R, P, K)
#define ep2_map(R, S, L)
#define ep3_add(R, P, Q)
#define ep3_dbl(R, P)
#define ep3_mul(R, P, K)
#define ep3_mul_pre(T, P)
#define ep3_mul_fix(R, T, K)
#define ep3_mul_sim(R, P, K, Q, M)
#define ep3_mul_big(R, P, K)
#define ep4_add(R, P, Q)
#define ep4_dbl(R, P)
#define ep4_mul(R, P, K)
#define ep4_mul_pre(T, P)
#define ep4_mul_fix(R, T, K)
#define ep4_mul_sim(R, P, K, Q, M)
#define ep4_mul_big(R, P, K)
#define ep8_add(R, P, Q)
#define ep8_dbl(R, P)
#define ep8_mul(R, P, K)
#define ep8_mul_pre(T, P)
#define ep8_mul_fix(R, T, K)
#define ep8_mul_sim(R, P, K, Q, M)
#define ep8_mul_big(R, P, K)
Typedefs
typedef ep2_st ep2_t[1]
typedef ep3_st ep3_t[1]
typedef ep4_st ep4_t[1]
typedef ep8_st ep8_t[1]
typedef iso2_st * iso2_t
Functions
void ep2_curve_init (void)
void ep2_curve_clean (void)
fp_t * ep2_curve_get_a (void)
fp_t * ep2_curve_get_b (void)
int ep2_curve_opt_a (void)
int ep2_curve_opt_b (void)
void ep2_curve_mul_a (fp2_t c, const fp2_t a)
void ep2_curve_mul_b (fp2_t c, const fp2_t a)
int ep2_curve_is_twist (void)
int ep2_curve_is_ctmap (void)
void ep2_curve_get_gen (ep2_t g)
ep2_t * ep2_curve_get_tab (void)
void ep2_curve_get_ord (bn_t n)
void ep2_curve_get_cof (bn_t h)
iso2_t ep2_curve_get_iso (void)
void ep2_curve_set (const fp2_t a, const fp2_t b, const ep2_t g, const bn_t r, const bn_t h)
void ep2_curve_set_twist (int type)
int ep2_is_infty (const ep2_t p)
void ep2_set_infty (ep2_t p)
void ep2_copy (ep2_t r, const ep2_t p)
int ep2_cmp (const ep2_t p, const ep2_t q)
void ep2_rand (ep2_t p)
void ep2_blind (ep2_t r, const ep2_t p)
void ep2_rhs (fp2_t rhs, const fp2_t x)
int ep2_on_curve (const ep2_t p)
void ep2_tab (ep2_t *t, const ep2_t p, int w)
void ep2_print (const ep2_t p)
size_t ep2_size_bin (const ep2_t a, int pack)
void ep2_read_bin (ep2_t a, const uint8_t *bin, size_t len)
void ep2_write_bin (uint8_t *bin, size_t len, const ep2_t a, int pack)
void ep2_neg (ep2_t r, const ep2_t p)
void ep2_add_basic (ep2_t r, const ep2_t p, const ep2_t q)
void ep2_add_slp_basic (ep2_t r, fp2_t s, const ep2_t p, const ep2_t q)
void ep2_add_projc (ep2_t r, const ep2_t p, const ep2_t q)
void ep2_add_jacob (ep2_t r, const ep2_t p, const ep2_t q)
void ep2_sub (ep2_t r, const ep2_t p, const ep2_t q)
void ep2_dbl_basic (ep2_t r, const ep2_t p)
void ep2_dbl_slp_basic (ep2_t r, fp2_t s, const ep2_t p)
void ep2_dbl_projc (ep2_t r, const ep2_t p)
void ep2_dbl_jacob (ep2_t r, const ep2_t p)
void ep2_mul_basic (ep2_t r, const ep2_t p, const bn_t k)
void ep2_mul_slide (ep2_t r, const ep2_t p, const bn_t k)
void ep2_mul_monty (ep2_t r, const ep2_t p, const bn_t k)
void ep2_mul_lwnaf (ep2_t r, const ep2_t p, const bn_t k)
void ep2_mul_lwreg (ep2_t r, const ep2_t p, const bn_t k)
void ep2_mul_gen (ep2_t r, const bn_t k)
void ep2_mul_dig (ep2_t r, const ep2_t p, const dig_t k)
void ep2_mul_cof (ep2_t r, const ep2_t p)
void ep2_mul_pre_basic (ep2_t *t, const ep2_t p)
void ep2_mul_pre_yaowi (ep2_t *t, const ep2_t p)
void ep2_mul_pre_nafwi (ep2_t *t, const ep2_t p)
void ep2_mul_pre_combs (ep2_t *t, const ep2_t p)
void ep2_mul_pre_combd (ep2_t *t, const ep2_t p)
void ep2_mul_pre_lwnaf (ep2_t *t, const ep2_t p)
void ep2_mul_fix_basic (ep2_t r, const ep2_t *t, const bn_t k)
void ep2_mul_fix_yaowi (ep2_t r, const ep2_t *t, const bn_t k)
void ep2_mul_fix_nafwi (ep2_t r, const ep2_t *t, const bn_t k)
void ep2_mul_fix_combs (ep2_t r, const ep2_t *t, const bn_t k)
void ep2_mul_fix_combd (ep2_t r, const ep2_t *t, const bn_t k)
void ep2_mul_fix_lwnaf (ep2_t r, const ep2_t *t, const bn_t k)
void ep2_mul_sim_basic (ep2_t r, const ep2_t p, const bn_t k, const ep2_t q, const bn_t m)
void ep2_mul_sim_trick (ep2_t r, const ep2_t p, const bn_t k, const ep2_t q, const bn_t m)
void ep2_mul_sim_inter (ep2_t r, const ep2_t p, const bn_t k, const ep2_t q, const bn_t m)
void ep2_mul_sim_joint (ep2_t r, const ep2_t p, const bn_t k, const ep2_t q, const bn_t m)
void ep2_mul_sim_lot (ep2_t r, const ep2_t p[], const bn_t k[], size_t n)
void ep2_mul_sim_gen (ep2_t r, const bn_t k, const ep2_t q, const bn_t m)
void ep2_mul_sim_dig (ep2_t r, const ep2_t p[], const dig_t k[], size_t len)
void ep2_norm (ep2_t r, const ep2_t p)
void ep2_norm_sim (ep2_t *r, const ep2_t *t, int n)
void ep2_map_basic (ep2_t p, const uint8_t *msg, size_t len)
void ep2_map_sswum (ep2_t p, const uint8_t *msg, size_t len)
void ep2_map_swift (ep2_t p, const uint8_t *msg, size_t len)
void ep2_frb (ep2_t r, const ep2_t p, int i)
void ep2_pck (ep2_t r, const ep2_t p)
int ep2_upk (ep2_t r, const ep2_t p)
void ep3_curve_init (void)
void ep3_curve_clean (void)
fp_t * ep3_curve_get_a (void)
fp_t * ep3_curve_get_b (void)
int ep3_curve_opt_a (void)
int ep3_curve_opt_b (void)
void ep3_curve_mul_a (fp3_t c, const fp3_t a)
void ep3_curve_mul_b (fp3_t c, const fp3_t a)
int ep3_curve_is_twist (void)
void ep3_curve_get_gen (ep3_t g)
ep3_t * ep3_curve_get_tab (void)
void ep3_curve_get_ord (bn_t n)
void ep3_curve_get_cof (bn_t h)
void ep3_curve_set (const fp3_t a, const fp3_t b, const ep3_t g, const bn_t r, const bn_t h)
void ep3_curve_set_twist (int type)
int ep3_is_infty (const ep3_t p)
void ep3_set_infty (ep3_t p)
void ep3_copy (ep3_t r, const ep3_t p)
int ep3_cmp (const ep3_t p, const ep3_t q)
void ep3_rand (ep3_t p)
void ep3_blind (ep3_t r, const ep3_t p)
void ep3_rhs (fp3_t rhs, const fp3_t x)
int ep3_on_curve (const ep3_t p)
void ep3_tab (ep3_t *t, const ep3_t p, int w)
void ep3_print (const ep3_t p)
size_t ep3_size_bin (const ep3_t a, int pack)
void ep3_read_bin (ep3_t a, const uint8_t *bin, size_t len)
void ep3_write_bin (uint8_t *bin, size_t len, const ep3_t a, int pack)
void ep3_neg (ep3_t r, const ep3_t p)
void ep3_add_basic (ep3_t r, const ep3_t p, const ep3_t q)
void ep3_add_slp_basic (ep3_t r, fp3_t s, const ep3_t p, const ep3_t q)
void ep3_add_projc (ep3_t r, const ep3_t p, const ep3_t q)
void ep3_add_jacob (ep3_t r, const ep3_t p, const ep3_t q)
void ep3_sub (ep3_t r, const ep3_t p, const ep3_t q)
void ep3_dbl_basic (ep3_t r, const ep3_t p)
void ep3_dbl_slp_basic (ep3_t r, fp3_t s, const ep3_t p)
void ep3_dbl_projc (ep3_t r, const ep3_t p)
void ep3_dbl_jacob (ep3_t r, const ep3_t p)
void ep3_mul_basic (ep3_t r, const ep3_t p, const bn_t k)
void ep3_mul_slide (ep3_t r, const ep3_t p, const bn_t k)
void ep3_mul_monty (ep3_t r, const ep3_t p, const bn_t k)
void ep3_mul_lwnaf (ep3_t r, const ep3_t p, const bn_t k)
void ep3_mul_lwreg (ep3_t r, const ep3_t p, const bn_t k)
void ep3_mul_gen (ep3_t r, const bn_t k)
void ep3_mul_dig (ep3_t r, const ep3_t p, const dig_t k)
void ep3_mul_cof (ep3_t r, const ep3_t p)
void ep3_mul_pre_basic (ep3_t *t, const ep3_t p)
void ep3_mul_pre_yaowi (ep3_t *t, const ep3_t p)
void ep3_mul_pre_nafwi (ep3_t *t, const ep3_t p)
void ep3_mul_pre_combs (ep3_t *t, const ep3_t p)
void ep3_mul_pre_combd (ep3_t *t, const ep3_t p)
void ep3_mul_pre_lwnaf (ep3_t *t, const ep3_t p)
void ep3_mul_fix_basic (ep3_t r, const ep3_t *t, const bn_t k)
void ep3_mul_fix_yaowi (ep3_t r, const ep3_t *t, const bn_t k)
void ep3_mul_fix_nafwi (ep3_t r, const ep3_t *t, const bn_t k)
void ep3_mul_fix_combs (ep3_t r, const ep3_t *t, const bn_t k)
void ep3_mul_fix_combd (ep3_t r, const ep3_t *t, const bn_t k)
void ep3_mul_fix_lwnaf (ep3_t r, const ep3_t *t, const bn_t k)
void ep3_mul_sim_basic (ep3_t r, const ep3_t p, const bn_t k, const ep3_t q, const bn_t m)
void ep3_mul_sim_trick (ep3_t r, const ep3_t p, const bn_t k, const ep3_t q, const bn_t m)
void ep3_mul_sim_inter (ep3_t r, const ep3_t p, const bn_t k, const ep3_t q, const bn_t m)
void ep3_mul_sim_joint (ep3_t r, const ep3_t p, const bn_t k, const ep3_t q, const bn_t m)
void ep3_mul_sim_lot (ep3_t r, const ep3_t p[], const bn_t k[], int n)
void ep3_mul_sim_gen (ep3_t r, const bn_t k, const ep3_t q, const bn_t m)
void ep3_mul_sim_dig (ep3_t r, const ep3_t p[], const dig_t k[], size_t len)
void ep3_norm (ep3_t r, const ep3_t p)
void ep3_norm_sim (ep3_t *r, const ep3_t *t, int n)
void ep3_map (ep3_t p, const uint8_t *msg, size_t len)
void ep3_frb (ep3_t r, const ep3_t p, int i)
void ep3_pck (ep3_t r, const ep3_t p)
int ep3_upk (ep3_t r, const ep3_t p)
void ep4_curve_init (void)
void ep4_curve_clean (void)
fp2_t * ep4_curve_get_a (void)
fp2_t * ep4_curve_get_b (void)
int ep4_curve_opt_a (void)
int ep4_curve_opt_b (void)
void ep4_curve_mul_a (fp4_t c, const fp4_t a)
void ep4_curve_mul_b (fp4_t c, const fp4_t a)
int ep4_curve_is_twist (void)
void ep4_curve_get_gen (ep4_t g)
ep4_t * ep4_curve_get_tab (void)
void ep4_curve_get_ord (bn_t n)
void ep4_curve_get_cof (bn_t h)
void ep4_curve_set (const fp4_t a, const fp4_t b, const ep4_t g, const bn_t r, const bn_t h)
void ep4_curve_set_twist (int type)
int ep4_is_infty (const ep4_t p)
void ep4_set_infty (ep4_t p)
void ep4_copy (ep4_t r, const ep4_t p)
int ep4_cmp (const ep4_t p, const ep4_t q)
void ep4_rand (ep4_t p)
void ep4_blind (ep4_t r, const ep4_t p)
void ep4_rhs (fp4_t rhs, const fp4_t x)
int ep4_on_curve (const ep4_t p)
void ep4_tab (ep4_t *t, const ep4_t p, int w)
void ep4_print (const ep4_t p)
size_t ep4_size_bin (const ep4_t a, int pack)
void ep4_read_bin (ep4_t a, const uint8_t *bin, size_t len)
void ep4_write_bin (uint8_t *bin, size_t len, const ep4_t a, int pack)
void ep4_neg (ep4_t r, const ep4_t p)
void ep4_add_basic (ep4_t r, const ep4_t p, const ep4_t q)
void ep4_add_slp_basic (ep4_t r, fp4_t s, const ep4_t p, const ep4_t q)
void ep4_add_projc (ep4_t r, const ep4_t p, const ep4_t q)
void ep4_add_jacob (ep4_t r, const ep4_t p, const ep4_t q)
void ep4_sub (ep4_t r, const ep4_t p, const ep4_t q)
void ep4_dbl_basic (ep4_t r, const ep4_t p)
void ep4_dbl_slp_basic (ep4_t r, fp4_t s, const ep4_t p)
void ep4_dbl_projc (ep4_t r, const ep4_t p)
void ep4_dbl_jacob (ep4_t r, const ep4_t p)
void ep4_mul_basic (ep4_t r, const ep4_t p, const bn_t k)
void ep4_mul_slide (ep4_t r, const ep4_t p, const bn_t k)
void ep4_mul_monty (ep4_t r, const ep4_t p, const bn_t k)
void ep4_mul_lwnaf (ep4_t r, const ep4_t p, const bn_t k)
void ep4_mul_lwreg (ep4_t r, const ep4_t p, const bn_t k)
void ep4_mul_gen (ep4_t r, const bn_t k)
void ep4_mul_dig (ep4_t r, const ep4_t p, const dig_t k)
void ep4_mul_cof (ep4_t r, const ep4_t p)
void ep4_mul_pre_basic (ep4_t *t, const ep4_t p)
void ep4_mul_pre_yaowi (ep4_t *t, const ep4_t p)
void ep4_mul_pre_nafwi (ep4_t *t, const ep4_t p)
void ep4_mul_pre_combs (ep4_t *t, const ep4_t p)
void ep4_mul_pre_combd (ep4_t *t, const ep4_t p)
void ep4_mul_pre_lwnaf (ep4_t *t, const ep4_t p)
void ep4_mul_fix_basic (ep4_t r, const ep4_t *t, const bn_t k)
void ep4_mul_fix_yaowi (ep4_t r, const ep4_t *t, const bn_t k)
void ep4_mul_fix_nafwi (ep4_t r, const ep4_t *t, const bn_t k)
void ep4_mul_fix_combs (ep4_t r, const ep4_t *t, const bn_t k)
void ep4_mul_fix_combd (ep4_t r, const ep4_t *t, const bn_t k)
void ep4_mul_fix_lwnaf (ep4_t r, const ep4_t *t, const bn_t k)
void ep4_mul_sim_basic (ep4_t r, const ep4_t p, const bn_t k, const ep4_t q, const bn_t m)
void ep4_mul_sim_trick (ep4_t r, const ep4_t p, const bn_t k, const ep4_t q, const bn_t m)
void ep4_mul_sim_inter (ep4_t r, const ep4_t p, const bn_t k, const ep4_t q, const bn_t m)
void ep4_mul_sim_joint (ep4_t r, const ep4_t p, const bn_t k, const ep4_t q, const bn_t m)
void ep4_mul_sim_lot (ep4_t r, const ep4_t p[], const bn_t k[], size_t n)
void ep4_mul_sim_gen (ep4_t r, const bn_t k, const ep4_t q, const bn_t m)
void ep4_mul_sim_dig (ep4_t r, const ep4_t p[], const dig_t k[], size_t len)
void ep4_norm (ep4_t r, const ep4_t p)
void ep4_norm_sim (ep4_t *r, const ep4_t *t, int n)
void ep4_map (ep4_t p, const uint8_t *msg, size_t len)
void ep4_frb (ep4_t r, const ep4_t p, int i)
void ep4_pck (ep4_t r, const ep4_t p)
int ep4_upk (ep4_t r, const ep4_t p)
void ep8_curve_init (void)
void ep8_curve_clean (void)
fp4_t * ep8_curve_get_a (void)
fp4_t * ep8_curve_get_b (void)
int ep8_curve_opt_a (void)
int ep8_curve_opt_b (void)
void ep8_curve_mul_a (fp8_t c, const fp8_t a)
void ep8_curve_mul_b (fp8_t c, const fp8_t a)
int ep8_curve_is_twist (void)
void ep8_curve_get_gen (ep8_t g)
ep8_t * ep8_curve_get_tab (void)
void ep8_curve_get_ord (bn_t n)
void ep8_curve_get_cof (bn_t h)
void ep8_curve_set (const fp8_t a, const fp8_t b, const ep8_t g, const bn_t r, const bn_t h)
void ep8_curve_set_twist (int type)
int ep8_is_infty (const ep8_t p)
void ep8_set_infty (ep8_t p)
void ep8_copy (ep8_t r, const ep8_t p)
int ep8_cmp (const ep8_t p, const ep8_t q)
void ep8_rand (ep8_t p)
void ep8_blind (ep8_t r, const ep8_t p)
void ep8_rhs (fp8_t rhs, const fp8_t x)
int ep8_on_curve (const ep8_t p)
void ep8_tab (ep8_t *t, const ep8_t p, int w)
void ep8_print (const ep8_t p)
size_t ep8_size_bin (const ep8_t a, int pack)
void ep8_read_bin (ep8_t a, const uint8_t *bin, size_t len)
void ep8_write_bin (uint8_t *bin, size_t len, const ep8_t a, int pack)
void ep8_neg (ep8_t r, const ep8_t p)
void ep8_add_basic (ep8_t r, const ep8_t p, const ep8_t q)
void ep8_add_slp_basic (ep8_t r, fp8_t s, const ep8_t p, const ep8_t q)
void ep8_add_projc (ep8_t r, const ep8_t p, const ep8_t q)
void ep8_add_jacob (ep8_t r, const ep8_t p, const ep8_t q)
void ep8_sub (ep8_t r, const ep8_t p, const ep8_t q)
void ep8_dbl_basic (ep8_t r, const ep8_t p)
void ep8_dbl_slp_basic (ep8_t r, fp8_t s, const ep8_t p)
void ep8_dbl_projc (ep8_t r, const ep8_t p)
void ep8_dbl_jacob (ep8_t r, const ep8_t p)
void ep8_mul_basic (ep8_t r, const ep8_t p, const bn_t k)
void ep8_mul_slide (ep8_t r, const ep8_t p, const bn_t k)
void ep8_mul_monty (ep8_t r, const ep8_t p, const bn_t k)
void ep8_mul_lwnaf (ep8_t r, const ep8_t p, const bn_t k)
void ep8_mul_lwreg (ep8_t r, const ep8_t p, const bn_t k)
void ep8_mul_gen (ep8_t r, const bn_t k)
void ep8_mul_dig (ep8_t r, const ep8_t p, const dig_t k)
void ep8_mul_cof (ep8_t r, const ep8_t p)
void ep8_mul_pre_basic (ep8_t *t, const ep8_t p)
void ep8_mul_pre_yaowi (ep8_t *t, const ep8_t p)
void ep8_mul_pre_nafwi (ep8_t *t, const ep8_t p)
void ep8_mul_pre_combs (ep8_t *t, const ep8_t p)
void ep8_mul_pre_combd (ep8_t *t, const ep8_t p)
void ep8_mul_pre_lwnaf (ep8_t *t, const ep8_t p)
void ep8_mul_fix_basic (ep8_t r, const ep8_t *t, const bn_t k)
void ep8_mul_fix_yaowi (ep8_t r, const ep8_t *t, const bn_t k)
void ep8_mul_fix_nafwi (ep8_t r, const ep8_t *t, const bn_t k)
void ep8_mul_fix_combs (ep8_t r, const ep8_t *t, const bn_t k)
void ep8_mul_fix_combd (ep8_t r, const ep8_t *t, const bn_t k)
void ep8_mul_fix_lwnaf (ep8_t r, const ep8_t *t, const bn_t k)
void ep8_mul_sim_basic (ep8_t r, const ep8_t p, const bn_t k, const ep8_t q, const bn_t m)
void ep8_mul_sim_trick (ep8_t r, const ep8_t p, const bn_t k, const ep8_t q, const bn_t m)
void ep8_mul_sim_inter (ep8_t r, const ep8_t p, const bn_t k, const ep8_t q, const bn_t m)
void ep8_mul_sim_joint (ep8_t r, const ep8_t p, const bn_t k, const ep8_t q, const bn_t m)
void ep8_mul_sim_lot (ep8_t r, const ep8_t p[], const bn_t k[], size_t n)
void ep8_mul_sim_gen (ep8_t r, const bn_t k, const ep8_t q, const bn_t m)
void ep8_mul_sim_dig (ep8_t r, const ep8_t p[], const dig_t k[], size_t len)
void ep8_norm (ep8_t r, const ep8_t p)
void ep8_norm_sim (ep8_t *r, const ep8_t *t, int n)
void ep8_map (ep8_t p, const uint8_t *msg, size_t len)
void ep8_frb (ep8_t r, const ep8_t p, int i)
void ep8_pck (ep8_t r, const ep8_t p)
int ep8_upk (ep8_t r, const ep8_t p)
Detailed Description
Interface of the module for arithmetic on prime elliptic curves defined over extension fields.
The scalar multiplication functions are only guaranteed to work in the prime order subgroup used by pairings. If you need a generic scalar multiplication function, use epx_mul_big().
Definition in file relic_epx.h.
Macro Definition Documentation
RLC_EPX_TABLE_BASIC
#define RLC_EPX_TABLE_BASIC (2 * RLC_FP_BITS + 1)
Size of a precomputation table using the binary method.
Definition at line 55 of file relic_epx.h.
RLC_EPX_TABLE_COMBS
#define RLC_EPX_TABLE_COMBS (1 << RLC_DEPTH)
Size of a precomputation table using the single-table comb method.
Definition at line 60 of file relic_epx.h.
RLC_EPX_TABLE_COMBD
#define RLC_EPX_TABLE_COMBD (1 << (RLC_DEPTH + 1))
Size of a precomputation table using the double-table comb method.
Definition at line 65 of file relic_epx.h.
RLC_EPX_TABLE_LWNAF
#define RLC_EPX_TABLE_LWNAF (1 << (RLC_DEPTH - 2))
Size of a precomputation table using the w-(T)NAF method.
Definition at line 70 of file relic_epx.h.
RLC_EPX_TABLE
#define RLC_EPX_TABLE RLC_EPX_TABLE_COMBS
Size of a precomputation table using the chosen algorithm.
Definition at line 78 of file relic_epx.h.
RLC_EPX_TABLE_MAX
#define RLC_EPX_TABLE_MAX RLC_MAX(RLC_EPX_TABLE_BASIC, RLC_EPX_TABLE_COMBD)
Maximum size of a precomputation table.
Definition at line 91 of file relic_epx.h.
RLC_EPX_CTMAP_MAX
#define RLC_EPX_CTMAP_MAX 4
Maximum number of coefficients of an isogeny map polynomial. 4 is sufficient for a degree-3 isogeny polynomial.
Definition at line 98 of file relic_epx.h.
Referenced by ep2_curve_clean(), ep2_curve_get_coeffs(), and ep2_curve_init().
ep2_null
#define ep2_null (A)
Value:
RLC_NULL(A)
Initializes a point on an elliptic curve with a null value.
Parameters
[out] A - the point to initialize.
Definition at line 240 of file relic_epx.h.
Referenced by ep2_cmp(), ep2_curve_set_twist(), ep2_map_from_field(), ep2_mul_basic(), ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep2_mul_dig(), ep2_mul_gen(), ep2_mul_gls_imp(), ep2_mul_monty(), ep2_mul_naf_imp(), ep2_mul_reg_gls(), ep2_mul_reg_imp(), ep2_mul_sim_basic(), ep2_mul_sim_dig(), ep2_mul_sim_endom(), ep2_mul_sim_gen(), ep2_mul_sim_joint(), ep2_mul_sim_lot(), ep2_mul_sim_plain(), ep2_mul_sim_trick(), ep2_mul_slide(), ep2_on_curve(), ep2_size_bin(), ep2_sub(), ep2_write_bin(), pp_add_k12_basic(), pp_add_k8_basic(), pp_dbl_k12_basic(), pp_dbl_k8_basic(), pp_fin_k12_oatep(), pp_map_oatep_k12(), pp_map_oatep_k8(), pp_map_sim_oatep_k12(), pp_map_sim_oatep_k8(), pp_map_sim_tatep_k12(), pp_map_sim_weilp_k12(), pp_map_tatep_k12(), pp_map_weilp_k12(), pp_mil_k12(), pp_mil_k8(), and pp_mil_lit_k12().
ep2_new
#define ep2_new (A)
Value:
/* empty */
Calls a function to allocate a point on an elliptic curve.
Parameters
[out] A - the new point.
Exceptions
ERR_NO_MEMORY - if there is no available memory.
Definition at line 262 of file relic_epx.h.
Referenced by ep2_cmp(), ep2_curve_init(), ep2_curve_set_twist(), ep2_map_from_field(), ep2_mul_basic(), ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep2_mul_dig(), ep2_mul_gen(), ep2_mul_gls_imp(), ep2_mul_monty(), ep2_mul_naf_imp(), ep2_mul_reg_gls(), ep2_mul_reg_imp(), ep2_mul_sim_basic(), ep2_mul_sim_dig(), ep2_mul_sim_endom(), ep2_mul_sim_gen(), ep2_mul_sim_joint(), ep2_mul_sim_lot(), ep2_mul_sim_plain(), ep2_mul_sim_trick(), ep2_mul_slide(), ep2_on_curve(), ep2_size_bin(), ep2_sub(), ep2_write_bin(), pp_add_k12_basic(), pp_add_k8_basic(), pp_dbl_k12_basic(), pp_dbl_k8_basic(), pp_fin_k12_oatep(), pp_map_oatep_k12(), pp_map_oatep_k8(), pp_map_sim_oatep_k12(), pp_map_sim_oatep_k8(), pp_map_sim_tatep_k12(), pp_map_sim_weilp_k12(), pp_map_tatep_k12(), pp_map_weilp_k12(), pp_mil_k12(), pp_mil_k8(), and pp_mil_lit_k12().
ep2_free
#define ep2_free (A)
Value:
/* empty */
Calls a function to clean and free a point on an elliptic curve.
Parameters
[out] A - the point to free.
Definition at line 282 of file relic_epx.h.
Referenced by ep2_cmp(), ep2_curve_clean(), ep2_curve_set_twist(), ep2_map_from_field(), ep2_mul_basic(), ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep2_mul_dig(), ep2_mul_gen(), ep2_mul_gls_imp(), ep2_mul_monty(), ep2_mul_naf_imp(), ep2_mul_reg_gls(), ep2_mul_reg_imp(), ep2_mul_sim_basic(), ep2_mul_sim_dig(), ep2_mul_sim_endom(), ep2_mul_sim_gen(), ep2_mul_sim_joint(), ep2_mul_sim_lot(), ep2_mul_sim_plain(), ep2_mul_sim_trick(), ep2_mul_slide(), ep2_on_curve(), ep2_size_bin(), ep2_sub(), ep2_write_bin(), pp_add_k12_basic(), pp_add_k8_basic(), pp_dbl_k12_basic(), pp_dbl_k8_basic(), pp_fin_k12_oatep(), pp_map_oatep_k12(), pp_map_oatep_k8(), pp_map_sim_oatep_k12(), pp_map_sim_tatep_k12(), pp_map_sim_weilp_k12(), pp_map_tatep_k12(), pp_map_weilp_k12(), pp_mil_k12(), pp_mil_k8(), and pp_mil_lit_k12().
ep3_null
#define ep3_null (A)
Value:
RLC_NULL(A)
Initializes a point on an elliptic curve with a null value.
Parameters
[out] A - the point to initialize.
Definition at line 290 of file relic_epx.h.
Referenced by ep3_cmp(), ep3_curve_set_twist(), ep3_mul_basic(), ep3_mul_cof_fm18(), ep3_mul_cof_k18(), ep3_mul_cof_sg18(), ep3_mul_dig(), ep3_mul_gen(), ep3_mul_gls_imp(), ep3_mul_monty(), ep3_mul_naf_imp(), ep3_mul_reg_gls(), ep3_mul_reg_imp(), ep3_mul_sim_basic(), ep3_mul_sim_dig(), ep3_mul_sim_gen(), ep3_mul_sim_joint(), ep3_mul_sim_lot(), ep3_mul_sim_plain(), ep3_mul_sim_trick(), ep3_mul_slide(), ep3_on_curve(), ep3_psi(), ep3_size_bin(), ep3_sub(), ep3_write_bin(), pp_add_k18_basic(), pp_dbl_k18_basic(), pp_fin_k18_oatep(), pp_map_oatep_k18(), pp_map_sim_oatep_k18(), pp_map_sim_tatep_k18(), pp_map_sim_weilp_k18(), pp_map_tatep_k18(), pp_map_weilp_k18(), pp_mil_k18(), and pp_mil_lit_k18().
ep3_new
#define ep3_new (A)
Value:
/* empty */
Calls a function to allocate a point on an elliptic curve.
Parameters
[out] A - the new point.
Exceptions
ERR_NO_MEMORY - if there is no available memory.
Definition at line 312 of file relic_epx.h.
Referenced by ep3_cmp(), ep3_curve_init(), ep3_curve_set_twist(), ep3_mul_basic(), ep3_mul_cof_fm18(), ep3_mul_cof_k18(), ep3_mul_cof_sg18(), ep3_mul_dig(), ep3_mul_gen(), ep3_mul_gls_imp(), ep3_mul_monty(), ep3_mul_naf_imp(), ep3_mul_reg_gls(), ep3_mul_reg_imp(), ep3_mul_sim_basic(), ep3_mul_sim_dig(), ep3_mul_sim_gen(), ep3_mul_sim_joint(), ep3_mul_sim_lot(), ep3_mul_sim_plain(), ep3_mul_sim_trick(), ep3_mul_slide(), ep3_on_curve(), ep3_psi(), ep3_size_bin(), ep3_sub(), ep3_write_bin(), pp_add_k18_basic(), pp_dbl_k18_basic(), pp_fin_k18_oatep(), pp_map_oatep_k18(), pp_map_sim_oatep_k18(), pp_map_sim_tatep_k18(), pp_map_sim_weilp_k18(), pp_map_tatep_k18(), pp_map_weilp_k18(), pp_mil_k18(), and pp_mil_lit_k18().
ep3_free
#define ep3_free (A)
Value:
/* empty */
Calls a function to clean and free a point on an elliptic curve.
Parameters
[out] A - the point to free.
Definition at line 332 of file relic_epx.h.
Referenced by ep3_cmp(), ep3_curve_clean(), ep3_curve_set_twist(), ep3_mul_basic(), ep3_mul_cof_fm18(), ep3_mul_cof_k18(), ep3_mul_cof_sg18(), ep3_mul_dig(), ep3_mul_gen(), ep3_mul_gls_imp(), ep3_mul_monty(), ep3_mul_naf_imp(), ep3_mul_reg_gls(), ep3_mul_reg_imp(), ep3_mul_sim_basic(), ep3_mul_sim_dig(), ep3_mul_sim_gen(), ep3_mul_sim_joint(), ep3_mul_sim_lot(), ep3_mul_sim_plain(), ep3_mul_sim_trick(), ep3_mul_slide(), ep3_on_curve(), ep3_psi(), ep3_size_bin(), ep3_sub(), ep3_write_bin(), pp_add_k18_basic(), pp_dbl_k18_basic(), pp_fin_k18_oatep(), pp_map_oatep_k18(), pp_map_sim_oatep_k18(), pp_map_sim_tatep_k18(), pp_map_sim_weilp_k18(), pp_map_tatep_k18(), pp_map_weilp_k18(), pp_mil_k18(), and pp_mil_lit_k18().
ep4_null
#define ep4_null (A)
Value:
RLC_NULL(A)
Initializes a point on an elliptic curve with a null value.
Parameters
[out] A - the point to initialize.
Definition at line 340 of file relic_epx.h.
Referenced by ep4_cmp(), ep4_curve_set_twist(), ep4_mul_basic(), ep4_mul_cof_afg16(), ep4_mul_cof_b24(), ep4_mul_cof_fm16(), ep4_mul_cof_k16(), ep4_mul_dig(), ep4_mul_gen(), ep4_mul_gls_imp(), ep4_mul_monty(), ep4_mul_naf_imp(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), ep4_mul_sim_basic(), ep4_mul_sim_dig(), ep4_mul_sim_gen(), ep4_mul_sim_joint(), ep4_mul_sim_lot(), ep4_mul_sim_plain(), ep4_mul_sim_trick(), ep4_mul_slide(), ep4_on_curve(), ep4_psi(), ep4_size_bin(), ep4_sub(), ep4_write_bin(), pp_add_k16_basic(), pp_add_k24_basic(), pp_dbl_k16_basic(), pp_dbl_k24_basic(), pp_fin_k16_oatep(), pp_map_k24(), pp_map_oatep_k16(), pp_map_sim_k24(), pp_map_sim_oatep_k16(), pp_map_sim_tatep_k16(), pp_map_sim_weilp_k16(), pp_map_tatep_k16(), pp_map_weilp_k16(), pp_mil_k16(), pp_mil_k24(), and pp_mil_lit_k16().
ep4_new
#define ep4_new (A)
Value:
/* empty */
Calls a function to allocate a point on an elliptic curve.
Parameters
[out] A - the new point.
Exceptions
ERR_NO_MEMORY - if there is no available memory.
Definition at line 362 of file relic_epx.h.
Referenced by ep4_cmp(), ep4_curve_init(), ep4_curve_set_twist(), ep4_mul_basic(), ep4_mul_cof_afg16(), ep4_mul_cof_b24(), ep4_mul_cof_fm16(), ep4_mul_cof_k16(), ep4_mul_dig(), ep4_mul_gen(), ep4_mul_gls_imp(), ep4_mul_monty(), ep4_mul_naf_imp(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), ep4_mul_sim_basic(), ep4_mul_sim_dig(), ep4_mul_sim_gen(), ep4_mul_sim_joint(), ep4_mul_sim_lot(), ep4_mul_sim_plain(), ep4_mul_sim_trick(), ep4_mul_slide(), ep4_on_curve(), ep4_psi(), ep4_size_bin(), ep4_sub(), ep4_write_bin(), pp_add_k16_basic(), pp_add_k24_basic(), pp_dbl_k16_basic(), pp_dbl_k24_basic(), pp_fin_k16_oatep(), pp_map_k24(), pp_map_oatep_k16(), pp_map_sim_k24(), pp_map_sim_oatep_k16(), pp_map_sim_tatep_k16(), pp_map_sim_weilp_k16(), pp_map_tatep_k16(), pp_map_weilp_k16(), pp_mil_k16(), pp_mil_k24(), and pp_mil_lit_k16().
ep4_free
#define ep4_free (A)
Value:
/* empty */
Calls a function to clean and free a point on an elliptic curve.
Parameters
[out] A - the point to free.
Definition at line 382 of file relic_epx.h.
Referenced by ep4_cmp(), ep4_curve_clean(), ep4_curve_set_twist(), ep4_mul_basic(), ep4_mul_cof_afg16(), ep4_mul_cof_b24(), ep4_mul_cof_fm16(), ep4_mul_cof_k16(), ep4_mul_dig(), ep4_mul_gen(), ep4_mul_gls_imp(), ep4_mul_monty(), ep4_mul_naf_imp(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), ep4_mul_sim_basic(), ep4_mul_sim_dig(), ep4_mul_sim_gen(), ep4_mul_sim_joint(), ep4_mul_sim_lot(), ep4_mul_sim_plain(), ep4_mul_sim_trick(), ep4_mul_slide(), ep4_on_curve(), ep4_psi(), ep4_size_bin(), ep4_sub(), ep4_write_bin(), pp_add_k16_basic(), pp_add_k24_basic(), pp_dbl_k16_basic(), pp_dbl_k24_basic(), pp_fin_k16_oatep(), pp_map_k24(), pp_map_oatep_k16(), pp_map_sim_k24(), pp_map_sim_oatep_k16(), pp_map_sim_oatep_k8(), pp_map_sim_tatep_k16(), pp_map_sim_weilp_k16(), pp_map_tatep_k16(), pp_map_weilp_k16(), pp_mil_k16(), pp_mil_k24(), and pp_mil_lit_k16().
ep8_null
#define ep8_null (A)
Value:
RLC_NULL(A)
Initializes a point on an elliptic curve with a null value.
Parameters
[out] A - the point to initialize.
Definition at line 390 of file relic_epx.h.
Referenced by ep8_cmp(), ep8_curve_set_twist(), ep8_mul_basic(), ep8_mul_cof(), ep8_mul_dig(), ep8_mul_gen(), ep8_mul_gls_imp(), ep8_mul_monty(), ep8_mul_naf_imp(), ep8_mul_reg_gls(), ep8_mul_reg_imp(), ep8_mul_sim_basic(), ep8_mul_sim_dig(), ep8_mul_sim_gen(), ep8_mul_sim_joint(), ep8_mul_sim_lot(), ep8_mul_sim_plain(), ep8_mul_sim_trick(), ep8_mul_slide(), ep8_on_curve(), ep8_size_bin(), ep8_sub(), ep8_write_bin(), pp_add_k48_basic(), pp_dbl_k48_basic(), pp_map_k48(), pp_map_sim_k48(), and pp_mil_k48().
ep8_new
#define ep8_new (A)
Value:
/* empty */
Calls a function to allocate a point on an elliptic curve.
Parameters
[out] A - the new point.
Exceptions
ERR_NO_MEMORY - if there is no available memory.
Definition at line 412 of file relic_epx.h.
Referenced by ep8_cmp(), ep8_curve_init(), ep8_curve_set_twist(), ep8_mul_basic(), ep8_mul_cof(), ep8_mul_dig(), ep8_mul_gen(), ep8_mul_gls_imp(), ep8_mul_monty(), ep8_mul_naf_imp(), ep8_mul_reg_gls(), ep8_mul_reg_imp(), ep8_mul_sim_basic(), ep8_mul_sim_dig(), ep8_mul_sim_gen(), ep8_mul_sim_joint(), ep8_mul_sim_lot(), ep8_mul_sim_plain(), ep8_mul_sim_trick(), ep8_mul_slide(), ep8_on_curve(), ep8_size_bin(), ep8_sub(), ep8_write_bin(), pp_add_k48_basic(), pp_dbl_k48_basic(), pp_map_k48(), pp_map_sim_k48(), and pp_mil_k48().
ep8_free
#define ep8_free (A)
Value:
/* empty */
Calls a function to clean and free a point on an elliptic curve.
Parameters
[out] A - the point to free.
Definition at line 432 of file relic_epx.h.
Referenced by ep8_cmp(), ep8_curve_clean(), ep8_curve_set_twist(), ep8_mul_basic(), ep8_mul_cof(), ep8_mul_dig(), ep8_mul_gen(), ep8_mul_gls_imp(), ep8_mul_monty(), ep8_mul_naf_imp(), ep8_mul_reg_gls(), ep8_mul_reg_imp(), ep8_mul_sim_basic(), ep8_mul_sim_dig(), ep8_mul_sim_gen(), ep8_mul_sim_joint(), ep8_mul_sim_lot(), ep8_mul_sim_plain(), ep8_mul_sim_trick(), ep8_mul_slide(), ep8_on_curve(), ep8_size_bin(), ep8_sub(), ep8_write_bin(), pp_add_k48_basic(), pp_dbl_k48_basic(), pp_map_k48(), pp_map_sim_k48(), and pp_mil_k48().
ep2_add
#define ep2_add (R, P, Q)
Value:
ep2_add_projc(R, P, Q)
Adds two points in an elliptic curve over a quadratic extension field. Computes R = P + Q.
Parameters
[out] R - the result.
[in] P - the first point to add.
[in] Q - the second point to add.
Definition at line 446 of file relic_epx.h.
Referenced by ep2_map_from_field(), ep2_mul_basic(), ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep2_mul_dig(), ep2_mul_fix_basic(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_fix_plain(), ep2_mul_gls_imp(), ep2_mul_monty(), ep2_mul_naf_imp(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_reg_gls(), ep2_mul_reg_imp(), ep2_mul_sim_basic(), ep2_mul_sim_dig(), ep2_mul_sim_endom(), ep2_mul_sim_joint(), ep2_mul_sim_lot(), ep2_mul_sim_plain(), ep2_mul_sim_trick(), ep2_mul_slide(), ep2_sub(), and ep2_tab().
ep2_dbl
#define ep2_dbl (R, P)
Value:
ep2_dbl_projc(R, P)
Doubles a point in an elliptic curve over a quadratic extension field. Computes R = 2P.
Parameters
[out] R - the result.
[in] P - the point to double.
Definition at line 461 of file relic_epx.h.
Referenced by ep2_mul_basic(), ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep2_mul_dig(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_fix_plain(), ep2_mul_gls_imp(), ep2_mul_monty(), ep2_mul_naf_imp(), ep2_mul_pre_basic(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_reg_gls(), ep2_mul_reg_imp(), ep2_mul_sim_dig(), ep2_mul_sim_endom(), ep2_mul_sim_joint(), ep2_mul_sim_lot(), ep2_mul_sim_plain(), ep2_mul_sim_trick(), ep2_mul_slide(), and ep2_tab().
ep2_mul
#define ep2_mul (R, P, K)
Value:
ep2_mul_lwnaf(R, P, K)
Multiplies a point in an elliptic curve over a quadratic extension field. Computes R = [k]P.
Parameters
[out] R - the result.
[in] P - the point to multiply.
[in] K - the integer.
Definition at line 481 of file relic_epx.h.
Referenced by ep2_mul_gen(), ep2_mul_sim_basic(), ep2_mul_sim_gen(), ep2_mul_sim_inter(), ep2_mul_sim_joint(), and ep2_mul_sim_trick().
ep2_mul_pre
#define ep2_mul_pre (T, P)
Value:
ep2_mul_pre_combs(T, P)
Builds a precomputation table for multiplying a fixed prime elliptic point over a quadratic extension.
Parameters
[out] T - the precomputation table.
[in] P - the point to multiply.
Definition at line 496 of file relic_epx.h.
Referenced by ep2_curve_set(), and ep2_curve_set_twist().
ep2_mul_fix
#define ep2_mul_fix (R, T, K)
Value:
ep2_mul_fix_combs(R, T, K)
Multiplies a fixed prime elliptic point over a quadratic extension using a precomputation table. Computes R = [k]P.
Parameters
[out] R - the result.
[in] T - the precomputation table.
[in] K - the integer.
Definition at line 515 of file relic_epx.h.
Referenced by ep2_mul_gen().
ep2_mul_sim
#define ep2_mul_sim (R, P, K, Q, M)
Value:
ep2_mul_sim_inter(R, P, K, Q, M)
Multiplies and adds two prime elliptic curve points simultaneously. Computes R = [k]P + [l]Q.
Parameters
[out] R - the result.
[in] P - the first point to multiply.
[in] K - the first integer.
[in] Q - the second point to multiply.
[in] M - the second integer,
Definition at line 538 of file relic_epx.h.
Referenced by ep2_mul_sim_gen().
ep2_mul_big
#define ep2_mul_big (R, P, K)
Value:
ep2_mul_basic(R, P, K)
Multiplies a point in an elliptic curve over a quadratic extension field by an unrestricted integer scalar. Computes R = [k]P.
Parameters
[out] R - the result.
[in] P - the point to multiply.
[in] K - the integer.
Definition at line 551 of file relic_epx.h.
Referenced by ep2_mul_cof().
ep2_map
#define ep2_map (R, S, L)
Value:
ep2_map_sswum(R, S, L)
Hashes a byte string to a prime elliptic point or the right order. Computes R = H(s).
Parameters
[out] R - the result.
[in] S - the string to hash.
[in] L - the string length.
Definition at line 564 of file relic_epx.h.
ep3_add
#define ep3_add (R, P, Q)
Value:
ep3_add_projc(R, P, Q)
Adds two points in an elliptic curve over a cubic extension field. Computes R = P + Q.
Parameters
[out] R - the result.
[in] P - the first point to add.
[in] Q - the second point to add.
Definition at line 580 of file relic_epx.h.
Referenced by ep3_mul_basic(), ep3_mul_cof_fm18(), ep3_mul_cof_k18(), ep3_mul_cof_sg18(), ep3_mul_dig(), ep3_mul_fix_basic(), ep3_mul_fix_combd(), ep3_mul_fix_combs(), ep3_mul_fix_plain(), ep3_mul_gls_imp(), ep3_mul_monty(), ep3_mul_naf_imp(), ep3_mul_pre_combd(), ep3_mul_pre_combs(), ep3_mul_reg_gls(), ep3_mul_reg_imp(), ep3_mul_sim_basic(), ep3_mul_sim_dig(), ep3_mul_sim_joint(), ep3_mul_sim_lot(), ep3_mul_sim_plain(), ep3_mul_sim_trick(), ep3_mul_slide(), ep3_psi(), ep3_sub(), and ep3_tab().
ep3_dbl
#define ep3_dbl (R, P)
Value:
ep3_dbl_projc(R, P)
Doubles a point in an elliptic curve over a cubic extension field. Computes R = 2P.
Parameters
[out] R - the result.
[in] P - the point to double.
Definition at line 595 of file relic_epx.h.
Referenced by ep3_mul_basic(), ep3_mul_cof_fm18(), ep3_mul_cof_k18(), ep3_mul_cof_sg18(), ep3_mul_dig(), ep3_mul_fix_combd(), ep3_mul_fix_combs(), ep3_mul_fix_plain(), ep3_mul_gls_imp(), ep3_mul_monty(), ep3_mul_naf_imp(), ep3_mul_pre_basic(), ep3_mul_pre_combd(), ep3_mul_pre_combs(), ep3_mul_reg_gls(), ep3_mul_reg_imp(), ep3_mul_sim_dig(), ep3_mul_sim_joint(), ep3_mul_sim_lot(), ep3_mul_sim_plain(), ep3_mul_sim_trick(), ep3_mul_slide(), ep3_psi(), and ep3_tab().
ep3_mul
#define ep3_mul (R, P, K)
Value:
ep3_mul_lwnaf(R, P, K)
Multiplies a point in an elliptic curve over a cubic extension field. Computes R = [k]P.
Parameters
[out] R - the result.
[in] P - the point to multiply.
[in] K - the integer.
Definition at line 615 of file relic_epx.h.
Referenced by ep3_mul_gen(), ep3_mul_sim_basic(), ep3_mul_sim_gen(), ep3_mul_sim_inter(), ep3_mul_sim_joint(), and ep3_mul_sim_trick().
ep3_mul_pre
#define ep3_mul_pre (T, P)
Value:
ep3_mul_pre_combs(T, P)
Builds a precomputation table for multiplying a fixed prime elliptic point over a cubic extension.
Parameters
[out] T - the precomputation table.
[in] P - the point to multiply.
Definition at line 630 of file relic_epx.h.
Referenced by ep3_curve_set(), and ep3_curve_set_twist().
ep3_mul_fix
#define ep3_mul_fix (R, T, K)
Value:
ep3_mul_fix_combs(R, T, K)
Multiplies a fixed prime elliptic point over a cubic extension using a precomputation table. Computes R = [k]P.
Parameters
[out] R - the result.
[in] T - the precomputation table.
[in] K - the integer.
Definition at line 649 of file relic_epx.h.
Referenced by ep3_mul_gen().
ep3_mul_sim
#define ep3_mul_sim (R, P, K, Q, M)
Value:
ep3_mul_sim_inter(R, P, K, Q, M)
Multiplies and adds two prime elliptic curve points simultaneously. Computes R = [k]P + [l]Q.
Parameters
[out] R - the result.
[in] P - the first point to multiply.
[in] K - the first integer.
[in] Q - the second point to multiply.
[in] M - the second integer,
Definition at line 672 of file relic_epx.h.
Referenced by ep3_mul_sim_gen().
ep3_mul_big
#define ep3_mul_big (R, P, K)
Value:
ep3_mul_basic(R, P, K)
Multiplies a point in an elliptic curve over a cubic extension field by an unrestricted integer scalar. Computes R = [k]P.
Parameters
[out] R - the result.
[in] P - the point to multiply.
[in] K - the integer.
Definition at line 685 of file relic_epx.h.
Referenced by ep3_mul_cof().
ep4_add
#define ep4_add (R, P, Q)
Value:
ep4_add_projc(R, P, Q)
Adds two points in an elliptic curve over a quartic extension field. Computes R = P + Q.
Parameters
[out] R - the result.
[in] P - the first point to add.
[in] Q - the second point to add.
Definition at line 698 of file relic_epx.h.
Referenced by ep4_mul_basic(), ep4_mul_cof_afg16(), ep4_mul_cof_b24(), ep4_mul_cof_fm16(), ep4_mul_cof_k16(), ep4_mul_dig(), ep4_mul_fix_basic(), ep4_mul_fix_combd(), ep4_mul_fix_combs(), ep4_mul_fix_ordin(), ep4_mul_gls_imp(), ep4_mul_monty(), ep4_mul_naf_imp(), ep4_mul_pre_combd(), ep4_mul_pre_combs(), ep4_mul_pre_ordin(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), ep4_mul_sim_basic(), ep4_mul_sim_dig(), ep4_mul_sim_joint(), ep4_mul_sim_lot(), ep4_mul_sim_plain(), ep4_mul_sim_trick(), ep4_mul_slide(), ep4_sub(), and ep4_tab().
ep4_dbl
#define ep4_dbl (R, P)
Value:
ep4_dbl_projc(R, P)
Doubles a point in an elliptic curve over a quartic extension field. Computes R = 2P.
Parameters
[out] R - the result.
[in] P - the point to double.
Definition at line 713 of file relic_epx.h.
Referenced by ep4_mul_basic(), ep4_mul_cof_afg16(), ep4_mul_cof_b24(), ep4_mul_cof_fm16(), ep4_mul_cof_k16(), ep4_mul_dig(), ep4_mul_fix_combd(), ep4_mul_fix_combs(), ep4_mul_fix_ordin(), ep4_mul_gls_imp(), ep4_mul_monty(), ep4_mul_naf_imp(), ep4_mul_pre_basic(), ep4_mul_pre_combd(), ep4_mul_pre_combs(), ep4_mul_pre_ordin(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), ep4_mul_sim_dig(), ep4_mul_sim_joint(), ep4_mul_sim_lot(), ep4_mul_sim_plain(), ep4_mul_sim_trick(), ep4_mul_slide(), ep4_psi(), and ep4_tab().
ep4_mul
#define ep4_mul (R, P, K)
Value:
ep4_mul_lwnaf(R, P, K)
Multiplies a point in an elliptic curve over a quartic extension field. Computes R = [k]P.
Parameters
[out] R - the result.
[in] P - the point to multiply.
[in] K - the integer.
Definition at line 733 of file relic_epx.h.
Referenced by ep4_mul_gen(), ep4_mul_sim_basic(), ep4_mul_sim_gen(), ep4_mul_sim_inter(), ep4_mul_sim_joint(), and ep4_mul_sim_trick().
ep4_mul_pre
#define ep4_mul_pre (T, P)
Value:
ep4_mul_pre_combs(T, P)
Builds a precomputation table for multiplying a fixed prime elliptic point over a quartic extension.
Parameters
[out] T - the precomputation table.
[in] P - the point to multiply.
Definition at line 748 of file relic_epx.h.
Referenced by ep4_curve_set(), and ep4_curve_set_twist().
ep4_mul_fix
#define ep4_mul_fix (R, T, K)
Value:
ep4_mul_fix_combs(R, T, K)
Multiplies a fixed prime elliptic point over a quartic extension using a precomputation table. Computes R = [k]P.
Parameters
[out] R - the result.
[in] T - the precomputation table.
[in] K - the integer.
Definition at line 767 of file relic_epx.h.
Referenced by ep4_mul_gen().
ep4_mul_sim
#define ep4_mul_sim (R, P, K, Q, M)
Value:
ep4_mul_sim_inter(R, P, K, Q, M)
Multiplies and adds two prime elliptic curve points simultaneously. Computes R = [k]P + [l]Q.
Parameters
[out] R - the result.
[in] P - the first point to multiply.
[in] K - the first integer.
[in] Q - the second point to multiply.
[in] M - the second integer,
Definition at line 790 of file relic_epx.h.
Referenced by ep4_mul_sim_gen().
ep4_mul_big
#define ep4_mul_big (R, P, K)
Value:
ep4_mul_basic(R, P, K)
Multiplies a point in an elliptic curve over a quartic extension field by an unrestricted integer scalar. Computes R = [k]P.
Parameters
[out] R - the result.
[in] P - the point to multiply.
[in] K - the integer.
Definition at line 803 of file relic_epx.h.
Referenced by ep4_mul_cof().
ep8_add
#define ep8_add (R, P, Q)
Value:
ep8_add_projc(R, P, Q)
Adds two points in an elliptic curve over an octic extension field. Computes R = P + Q.
Parameters
[out] R - the result.
[in] P - the first point to add.
[in] Q - the second point to add.
Definition at line 816 of file relic_epx.h.
Referenced by ep8_mul_basic(), ep8_mul_cof(), ep8_mul_dig(), ep8_mul_fix_basic(), ep8_mul_fix_combd(), ep8_mul_fix_combs(), ep8_mul_fix_ordin(), ep8_mul_gls_imp(), ep8_mul_monty(), ep8_mul_naf_imp(), ep8_mul_pre_combd(), ep8_mul_pre_combs(), ep8_mul_pre_ordin(), ep8_mul_reg_gls(), ep8_mul_reg_imp(), ep8_mul_sim_basic(), ep8_mul_sim_dig(), ep8_mul_sim_joint(), ep8_mul_sim_lot(), ep8_mul_sim_plain(), ep8_mul_sim_trick(), ep8_mul_slide(), ep8_sub(), and ep8_tab().
ep8_dbl
#define ep8_dbl (R, P)
Value:
ep8_dbl_projc(R, P)
Doubles a point in an elliptic curve over an octic extension field. Computes R = 2P.
Parameters
[out] R - the result.
[in] P - the point to double.
Definition at line 831 of file relic_epx.h.
Referenced by ep8_mul_basic(), ep8_mul_cof(), ep8_mul_dig(), ep8_mul_fix_combd(), ep8_mul_fix_combs(), ep8_mul_fix_ordin(), ep8_mul_gls_imp(), ep8_mul_monty(), ep8_mul_naf_imp(), ep8_mul_pre_basic(), ep8_mul_pre_combd(), ep8_mul_pre_combs(), ep8_mul_pre_ordin(), ep8_mul_reg_gls(), ep8_mul_reg_imp(), ep8_mul_sim_dig(), ep8_mul_sim_joint(), ep8_mul_sim_lot(), ep8_mul_sim_plain(), ep8_mul_sim_trick(), ep8_mul_slide(), and ep8_tab().
ep8_mul
#define ep8_mul (R, P, K)
Value:
ep8_mul_lwnaf(R, P, K)
Multiplies a point in an elliptic curve over an octic extension field. Computes R = [k]P.
Parameters
[out] R - the result.
[in] P - the point to multiply.
[in] K - the integer.
Definition at line 851 of file relic_epx.h.
Referenced by ep8_mul_gen(), ep8_mul_sim_basic(), ep8_mul_sim_gen(), ep8_mul_sim_inter(), ep8_mul_sim_joint(), and ep8_mul_sim_trick().
ep8_mul_pre
#define ep8_mul_pre (T, P)
Value:
ep8_mul_pre_combs(T, P)
Builds a precomputation table for multiplying a fixed prime elliptic point over an octic extension.
Parameters
[out] T - the precomputation table.
[in] P - the point to multiply.
Definition at line 866 of file relic_epx.h.
Referenced by ep8_curve_set(), and ep8_curve_set_twist().
ep8_mul_fix
#define ep8_mul_fix (R, T, K)
Value:
ep8_mul_fix_combs(R, T, K)
Multiplies a fixed prime elliptic point over an octic extension using a precomputation table. Computes R = [k]P.
Parameters
[out] R - the result.
[in] T - the precomputation table.
[in] K - the integer.
Definition at line 885 of file relic_epx.h.
Referenced by ep8_mul_gen().
ep8_mul_sim
#define ep8_mul_sim (R, P, K, Q, M)
Value:
ep8_mul_sim_inter(R, P, K, Q, M)
Multiplies and adds two prime elliptic curve points simultaneously. Computes R = [k]P + [l]Q.
Parameters
[out] R - the result.
[in] P - the first point to multiply.
[in] K - the first integer.
[in] Q - the second point to multiply.
[in] M - the second integer,
Definition at line 908 of file relic_epx.h.
Referenced by ep8_mul_sim_gen().
ep8_mul_big
#define ep8_mul_big (R, P, K)
Value:
ep8_mul_basic(R, P, K)
Multiplies a point in an elliptic curve over an octic extension field by an unrestricted integer scalar. Computes R = [k]P.
Parameters
[out] R - the result.
[in] P - the point to multiply.
[in] K - the integer.
Definition at line 921 of file relic_epx.h.
Typedef Documentation
ep2_t
typedef ep2_st ep2_t[1]
Pointer to an elliptic curve point over a quadratic extension field.
Definition at line 123 of file relic_epx.h.
ep3_t
typedef ep3_st ep3_t[1]
Pointer to an elliptic curve point over a cubic extension field.
Definition at line 147 of file relic_epx.h.
ep4_t
typedef ep4_st ep4_t[1]
Pointer to an elliptic curve point over an octic extension field.
Definition at line 171 of file relic_epx.h.
ep8_t
typedef ep8_st ep8_t[1]
Pointer to an elliptic curve point over an octic extension field.
Definition at line 195 of file relic_epx.h.
iso2_t
typedef iso2_st* iso2_t
Pointer to isogeny map coefficients.
Definition at line 229 of file relic_epx.h.
Function Documentation
ep2_curve_init()
void ep2_curve_init (void)
Initializes the elliptic curve over quadratic extension.
Definition at line 562 of file relic_ep2_curve.c.
References iso2_st::a, iso2_st::b, bn_make(), core_get(), _ctx_t::ep2_a, _ctx_t::ep2_b, ep2_curve_get_iso(), _ctx_t::ep2_frb, _ctx_t::ep2_g, _ctx_t::ep2_h, _ctx_t::ep2_map_c, _ctx_t::ep2_map_u, ep2_new, _ctx_t::ep2_pre, _ctx_t::ep2_ptr, _ctx_t::ep2_r, fp2_new, RLC_EP_TABLE, RLC_EPX_CTMAP_MAX, RLC_FP_DIGS, ep2_st::x, iso2_st::xd, iso2_st::xn, ep2_st::y, iso2_st::yd, iso2_st::yn, and ep2_st::z.
Referenced by pp_map_init().
ep2_curve_clean()
void ep2_curve_clean (void)
Finalizes the elliptic curve over quadratic extension.
Definition at line 615 of file relic_ep2_curve.c.
References iso2_st::a, iso2_st::b, bn_clean(), core_get(), _ctx_t::ep2_a, _ctx_t::ep2_b, ep2_curve_get_iso(), _ctx_t::ep2_frb, ep2_free, _ctx_t::ep2_g, _ctx_t::ep2_h, _ctx_t::ep2_map_c, _ctx_t::ep2_map_u, _ctx_t::ep2_pre, _ctx_t::ep2_r, fp2_free, RLC_EP_TABLE, RLC_EPX_CTMAP_MAX, ep2_st::x, iso2_st::xd, iso2_st::xn, ep2_st::y, iso2_st::yd, iso2_st::yn, and ep2_st::z.
Referenced by pp_map_clean().
ep2_curve_get_a()
fp_t * ep2_curve_get_a (void)
Returns the 'a' coefficient of the currently configured elliptic curve.
Returns
the 'a' coefficient of the elliptic curve.
Definition at line 735 of file relic_ep2_curve.c.
References core_get(), and _ctx_t::ep2_a.
Referenced by ep2_map_swift(), and ep2_rhs().
ep2_curve_get_b()
fp_t * ep2_curve_get_b (void)
Returns the 'b' coefficient of the currently configured elliptic curve.
Parameters
[out] b - the 'b' coefficient of the elliptic curve.
Definition at line 739 of file relic_ep2_curve.c.
References core_get(), and _ctx_t::ep2_b.
Referenced by ep2_rhs(), pp_dbl_k12_projc_basic(), and pp_dbl_k12_projc_lazyr().
ep2_curve_opt_a()
int ep2_curve_opt_a (void)
Returns a optimization identifier based on the 'a' coefficient of the curve.
Returns
the optimization identifier.
Definition at line 652 of file relic_ep2_curve.c.
References core_get(), and _ctx_t::ep2_opt_a.
Referenced by ep2_curve_set_map(), ep2_frb(), ep2_map_from_field(), ep2_map_swift(), and ep2_rhs().
ep2_curve_opt_b()
int ep2_curve_opt_b (void)
Returns b optimization identifier based on the 'b' coefficient of the curve.
Returns
the optimization identifier.
Definition at line 656 of file relic_ep2_curve.c.
References core_get(), and _ctx_t::ep2_opt_b.
Referenced by ep2_curve_set_map(), ep2_map_from_field(), ep2_map_swift(), and ep2_rhs().
ep2_curve_mul_a()
void ep2_curve_mul_a (fp2_t c, const fp2_t a)
Multiplies a field element by the a-coefficient of the curve.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
Definition at line 660 of file relic_ep2_curve.c.
References core_get(), _ctx_t::ep2_a, ep2_curve_is_twist(), _ctx_t::ep2_opt_a, ep_curve_get_a(), ep_curve_opt_a(), fp2_copy(), fp2_dbl, fp2_mul, fp2_mul_art(), fp2_mul_dig(), fp2_zero(), fp_mul, RLC_EP_MTYPE, RLC_ONE, RLC_TINY, RLC_TWO, and RLC_ZERO.
Referenced by pp_dbl_k8_projc_basic(), and pp_dbl_k8_projc_lazyr().
ep2_curve_mul_b()
void ep2_curve_mul_b (fp2_t c, const fp2_t a)
Multiplies a field element by the b-coefficient of the curve.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
Definition at line 703 of file relic_ep2_curve.c.
References core_get(), _ctx_t::ep2_b, _ctx_t::ep2_opt_b, fp2_copy(), fp2_mul, fp2_mul_dig(), fp2_zero(), RLC_ONE, RLC_TINY, and RLC_ZERO.
ep2_curve_is_twist()
int ep2_curve_is_twist (void)
Tests if the configured elliptic curve is a twist.
Returns
the type of the elliptic curve twist, 0 if non-twisted curve.
Definition at line 723 of file relic_ep2_curve.c.
References core_get(), and _ctx_t::ep2_is_twist.
Referenced by ep2_curve_mul_a(), fp12_mul_dxs_basic(), fp12_mul_dxs_lazyr(), pp_add_k12_basic(), pp_add_k12_projc_basic(), pp_add_k12_projc_lazyr(), pp_add_k8_basic(), pp_add_k8_projc_basic(), pp_add_k8_projc_lazyr(), pp_add_lit_k12(), pp_dbl_k12_basic(), pp_dbl_k12_projc_basic(), pp_dbl_k12_projc_lazyr(), pp_dbl_k8_basic(), pp_dbl_k8_projc_basic(), pp_dbl_k8_projc_lazyr(), pp_dbl_k8_projc_lazyr_new(), pp_dbl_k8_projc_new(), and pp_dbl_lit_k12().
ep2_curve_is_ctmap()
int ep2_curve_is_ctmap (void)
Tests if the current curve should use an isogeny map for the SSWU map.
Returns
1 if the curve uses an isogeny, and 0 otherwise.
Definition at line 727 of file relic_ep2_curve.c.
References core_get(), and _ctx_t::ep2_is_ctmap.
Referenced by ep2_curve_set_map(), and ep2_map_from_field().
ep2_curve_get_gen()
void ep2_curve_get_gen (ep2_t g)
Returns the generator of the group of points in the elliptic curve.
Parameters
[out] g - the returned generator.
Definition at line 731 of file relic_ep2_curve.c.
References core_get(), and ep2_copy().
Referenced by ep2_mul_gen(), and ep2_mul_sim_gen().
ep2_curve_get_tab()
ep2_t * ep2_curve_get_tab (void)
Returns the precomputation table for the generator.
Returns
the table.
Definition at line 766 of file relic_ep2_curve.c.
References core_get(), and _ctx_t::ep2_ptr.
Referenced by ep2_curve_set(), ep2_curve_set_twist(), ep2_mul_gen(), and ep2_mul_sim_gen().
ep2_curve_get_ord()
void ep2_curve_get_ord (bn_t n)
Returns the order of the group of points in the elliptic curve.
Parameters
[out] n - the returned order.
Definition at line 743 of file relic_ep2_curve.c.
References bn_copy(), core_get(), _ctx_t::ep2_is_twist, _ctx_t::ep2_r, and ep_curve_get_ord().
Referenced by ep2_mul_fix_basic(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_fix_lwnaf(), ep2_mul_gls_imp(), ep2_mul_monty(), ep2_mul_pre_basic(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_reg_gls(), ep2_mul_reg_imp(), ep2_mul_sim_endom(), ep2_mul_sim_gen(), ep2_mul_sim_joint(), ep2_mul_sim_lot(), ep2_mul_sim_trick(), and ep2_rand().
ep2_curve_get_cof()
void ep2_curve_get_cof (bn_t h)
Returns the cofactor of the group order in the elliptic curve.
Parameters
[out] h - the returned cofactor.
Definition at line 752 of file relic_ep2_curve.c.
References bn_copy(), and core_get().
Referenced by ep2_mul_cof().
ep2_curve_get_iso()
iso2_t ep2_curve_get_iso (void)
Returns the isogeny map coefficients for use with the SSWU map.
Definition at line 756 of file relic_ep2_curve.c.
References core_get(), and _ctx_t::ep2_iso.
Referenced by ep2_curve_clean(), ep2_curve_init(), and ep2_curve_set_ctmap().
ep2_curve_set()
void ep2_curve_set (const fp2_t a, const fp2_t b, const ep2_t g, const bn_t r, const bn_t h)
Configures an elliptic curve over a quadratic extension by its coefficients.
Parameters
[in] a - the 'a' coefficient of the curve.
[in] b - the 'b' coefficient of the curve.
[in] g - the generator.
[in] r - the order of the group of points.
[in] h - the cofactor of the group order.
Definition at line 925 of file relic_ep2_curve.c.
References bn_copy(), core_get(), _ctx_t::ep2_a, _ctx_t::ep2_b, ep2_curve_get_tab(), _ctx_t::ep2_g, _ctx_t::ep2_h, _ctx_t::ep2_is_twist, ep2_mul_pre, ep2_norm(), _ctx_t::ep2_r, and fp2_copy().
ep2_curve_set_twist()
void ep2_curve_set_twist (int type)
Configures an elliptic curve by twisting the curve over the base prime field.
Parameters
- the type of twist (multiplicative or divisive)
Definition at line 776 of file relic_ep2_curve.c.
References ASSIGN, ASSIGNM, B12_P1150, B12_P377, B12_P381, B12_P383, B12_P446, B12_P455, B12_P638, BASIC, bn_copy(), bn_free, bn_new, bn_null, BN_P158, BN_P254, BN_P256, BN_P382, BN_P446, BN_P638, core_get(), detect_opt(), _ctx_t::ep2_a, _ctx_t::ep2_b, ep2_copy(), ep2_curve_get_tab(), ep2_curve_set_map(), _ctx_t::ep2_frb, ep2_free, _ctx_t::ep2_g, _ctx_t::ep2_h, _ctx_t::ep2_is_ctmap, _ctx_t::ep2_is_twist, _ctx_t::ep2_map_u, ep2_mul_pre, ep2_new, ep2_null, _ctx_t::ep2_opt_a, _ctx_t::ep2_opt_b, _ctx_t::ep2_r, ep_param_get(), ERR_CAUGHT, ERR_NO_VALID, fp2_copy(), fp2_free, fp2_inv(), fp2_new, fp2_null, _ctx_t::fp2_p1, fp2_set_dig(), fp2_zero(), fp_copy(), GMT8_P544, pc_core_calc(), RLC_CATCH_ANY, RLC_EP_DTYPE, RLC_EP_MTYPE, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, RLC_TRY, and SM9_P256.
Referenced by ep_param_set_any_pairf().
ep2_is_infty()
int ep2_is_infty (const ep2_t p)
Tests if a point on an elliptic curve is at the infinity.
Parameters
[in] p - the point to test.
Returns
1 if the point is at infinity, 0 otherise.
Definition at line 39 of file relic_ep2_util.c.
References fp2_is_zero().
Referenced by ep2_add_basic(), ep2_add_jacob(), ep2_add_projc(), ep2_add_slp_basic(), ep2_cmp(), ep2_dbl_basic(), ep2_dbl_jacob(), ep2_dbl_projc(), ep2_dbl_slp_basic(), ep2_mul_basic(), ep2_mul_dig(), ep2_mul_lwnaf(), ep2_mul_lwreg(), ep2_mul_monty(), ep2_mul_sim_gen(), ep2_mul_sim_inter(), ep2_mul_sim_joint(), ep2_mul_sim_trick(), ep2_mul_slide(), ep2_neg(), ep2_norm(), ep2_norm_sim(), ep2_on_curve(), ep2_size_bin(), ep2_write_bin(), pp_map_oatep_k12(), pp_map_oatep_k8(), pp_map_sim_oatep_k12(), pp_map_sim_oatep_k8(), pp_map_sim_tatep_k12(), pp_map_sim_weilp_k12(), pp_map_tatep_k12(), pp_map_weilp_k12(), pp_norm_k12(), and pp_norm_k8().
ep2_set_infty()
void ep2_set_infty (ep2_t p)
Assigns an elliptic curve point to the point at infinity.
Parameters
[out] p - the point to assign.
Definition at line 43 of file relic_ep2_util.c.
References BASIC, and fp2_zero().
Referenced by ep2_dbl_basic(), ep2_dbl_jacob(), ep2_dbl_projc(), ep2_dbl_slp_basic(), ep2_map_swift(), ep2_mul_basic(), ep2_mul_dig(), ep2_mul_fix_basic(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_fix_lwnaf(), ep2_mul_fix_plain(), ep2_mul_gen(), ep2_mul_gls_imp(), ep2_mul_lwnaf(), ep2_mul_lwreg(), ep2_mul_monty(), ep2_mul_naf_imp(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_reg_imp(), ep2_mul_sim_dig(), ep2_mul_sim_endom(), ep2_mul_sim_joint(), ep2_mul_sim_lot(), ep2_mul_sim_plain(), ep2_mul_sim_trick(), ep2_mul_slide(), ep2_neg(), ep2_norm(), ep2_read_bin(), ep2_sub(), pp_norm_k12(), and pp_norm_k8().
ep2_copy()
void ep2_copy (ep2_t r, const ep2_t p)
Copies the second argument to the first argument.
Parameters
[out] q - the result.
[in] p - the elliptic curve point to copy.
Definition at line 50 of file relic_ep2_util.c.
References fp2_copy().
Referenced by ep2_add_basic(), ep2_add_jacob(), ep2_add_projc(), ep2_add_slp_basic(), ep2_blind(), ep2_cmp(), ep2_curve_get_gen(), ep2_curve_set_twist(), ep2_frb(), ep2_mul_dig(), ep2_mul_fix_combs(), ep2_mul_pre_basic(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_reg_gls(), ep2_mul_sim_joint(), ep2_mul_sim_lot(), ep2_mul_sim_trick(), ep2_mul_slide(), ep2_norm(), ep2_norm_imp(), ep2_tab(), pp_add_k12_basic(), pp_add_k8_basic(), pp_dbl_k12_basic(), pp_dbl_k8_basic(), pp_mil_k12(), pp_mil_k8(), pp_norm_k12(), and pp_norm_k8().
ep2_cmp()
int ep2_cmp (const ep2_t p, const ep2_t q)
Compares two elliptic curve points.
Parameters
[in] p - the first elliptic curve point.
[in] q - the second elliptic curve point.
Returns
RLC_EQ if p == q and RLC_NE if p != q.
Definition at line 39 of file relic_ep2_cmp.c.
References ep2_copy(), ep2_free, ep2_is_infty(), ep2_new, ep2_null, ERR_CAUGHT, fp2_cmp(), fp2_mul, fp2_sqr, JACOB, PROJC, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_NE, RLC_THROW, and RLC_TRY.
ep2_rand()
void ep2_rand (ep2_t p)
Assigns a random value to an elliptic curve point.
Parameters
[out] p - the elliptic curve point to assign.
Definition at line 57 of file relic_ep2_util.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), ep2_curve_get_ord(), ep2_mul_gen(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep2_blind()
void ep2_blind (ep2_t r, const ep2_t p)
Randomizes coordinates of an elliptic curve point.
Parameters
[out] r - the blinded prime elliptic curve point.
[in] p - the prime elliptic curve point to blind.
Definition at line 81 of file relic_ep2_util.c.
References ep2_copy(), ERR_CAUGHT, fp2_free, fp2_mul, fp2_new, fp2_null, fp2_rand(), fp2_sqr, JACOB, PROJC, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep2_mul_monty().
ep2_rhs()
void ep2_rhs (fp2_t rhs, const fp2_t x)
Computes the right-hand side of the elliptic curve equation at the x-coordinate of a certain prime elliptic curve point.
Parameters
[out] rhs - the result.
[in] x - the x-coordinate of the point.
Definition at line 112 of file relic_ep2_util.c.
References ep2_curve_get_a(), ep2_curve_get_b(), ep2_curve_opt_a(), ep2_curve_opt_b(), ERR_CAUGHT, fp2_add, fp2_add_dig(), fp2_copy(), fp2_free, fp2_mul, fp2_mul_dig(), fp2_new, fp2_null, fp2_sqr, fp2_sub_dig(), RLC_CATCH_ANY, RLC_FINALLY, RLC_MIN3, RLC_ONE, RLC_THROW, RLC_TINY, RLC_TRY, RLC_TWO, and RLC_ZERO.
Referenced by ep2_map_basic(), ep2_map_swift(), ep2_on_curve(), and ep2_upk().
ep2_on_curve()
int ep2_on_curve (const ep2_t p)
Tests if a point is in the curve.
Parameters
[in] p - the point to test.
Definition at line 177 of file relic_ep2_util.c.
References ep2_free, ep2_is_infty(), ep2_new, ep2_norm(), ep2_null, ep2_rhs(), ERR_CAUGHT, fp2_cmp(), fp2_sqr, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep2_read_bin().
ep2_tab()
void ep2_tab (ep2_t * t, const ep2_t p, int w)
Builds a precomputation table for multiplying a random prime elliptic point.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
[in] w - the window width.
Definition at line 200 of file relic_ep2_util.c.
References ep2_add, ep2_copy(), ep2_dbl, ep2_norm(), and ep2_norm_sim().
Referenced by ep2_mul_gls_imp(), ep2_mul_naf_imp(), ep2_mul_pre_lwnaf(), ep2_mul_reg_imp(), and ep2_mul_sim_plain().
ep2_print()
void ep2_print (const ep2_t p)
Prints an elliptic curve point.
Parameters
[in] p - the elliptic curve point to print.
Definition at line 221 of file relic_ep2_util.c.
References fp2_print().
ep2_size_bin()
size_t ep2_size_bin (const ep2_t a, int pack)
Returns the number of bytes necessary to store a prime elliptic curve point over a quadratic extension with optional point compression.
Parameters
[in] a - the prime field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 227 of file relic_ep2_util.c.
References ep2_free, ep2_is_infty(), ep2_new, ep2_norm(), ep2_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.
ep2_read_bin()
void ep2_read_bin (ep2_t a, const uint8_t * bin, size_t len)
Reads a prime elliptic curve point over a quadratic extension from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_VALID - if the encoded point is invalid.
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 255 of file relic_ep2_util.c.
References BASIC, ep2_on_curve(), ep2_set_infty(), ep2_upk(), ERR_NO_BUFFER, ERR_NO_VALID, fp2_read_bin(), fp2_set_dig(), fp2_zero(), fp_set_bit(), fp_zero(), RLC_FP_BYTES, and RLC_THROW.
ep2_write_bin()
void ep2_write_bin (uint8_t * bin, size_t len, const ep2_t a, int pack)
Writes a prime elliptic curve pointer over a quadratic extension to a byte vector in big-endian format with optional point compression.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the prime elliptic curve point to write.
[in] pack - the flag to indicate point compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 305 of file relic_ep2_util.c.
References ep2_free, ep2_is_infty(), ep2_new, ep2_norm(), ep2_null, ep2_pck(), ERR_CAUGHT, ERR_NO_BUFFER, fp2_write_bin(), fp_get_bit(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.
ep2_neg()
void ep2_neg (ep2_t r, const ep2_t p)
Negates a point represented in affine coordinates in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[out] p - the point to negate.
Definition at line 39 of file relic_ep2_neg.c.
References ep2_is_infty(), ep2_set_infty(), fp2_copy(), and fp2_neg().
Referenced by ep2_mul_basic(), ep2_mul_fix_plain(), ep2_mul_gls_imp(), ep2_mul_naf_imp(), ep2_mul_reg_gls(), ep2_mul_reg_imp(), ep2_mul_sim_endom(), ep2_mul_sim_joint(), ep2_mul_sim_lot(), ep2_mul_slide(), ep2_sub(), pp_fin_k12_oatep(), pp_map_oatep_k12(), pp_map_oatep_k8(), pp_map_sim_oatep_k12(), pp_map_sim_oatep_k8(), pp_mil_k12(), pp_mil_k8(), and pp_mil_lit_k12().
ep2_add_basic()
void ep2_add_basic (ep2_t r, const ep2_t p, const ep2_t q)
Adds to points represented in affine coordinates in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 109 of file relic_ep2_add.c.
References ep2_copy(), and ep2_is_infty().
ep2_add_slp_basic()
void ep2_add_slp_basic (ep2_t r, fp2_t s, const ep2_t p, const ep2_t q)
Adds to points represented in affine coordinates in an elliptic curve over a quadratic extension and returns the computed slope.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 123 of file relic_ep2_add.c.
References ep2_copy(), and ep2_is_infty().
Referenced by pp_add_k12_basic(), and pp_add_k8_basic().
ep2_add_projc()
void ep2_add_projc (ep2_t r, const ep2_t p, const ep2_t q)
Adds two points represented in projective coordinates in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 141 of file relic_ep2_add.c.
References ep2_copy(), and ep2_is_infty().
ep2_add_jacob()
void ep2_add_jacob (ep2_t r, const ep2_t p, const ep2_t q)
Adds two points represented in Jacobian coordinates in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 159 of file relic_ep2_add.c.
References ep2_copy(), and ep2_is_infty().
ep2_sub()
void ep2_sub (ep2_t r, const ep2_t p, const ep2_t q)
Subtracts a point in an elliptic curve over a quadratic extension from another.
Parameters
[out] r - the result.
[in] p - the first point.
[in] q - the point to subtract.
Definition at line 175 of file relic_ep2_add.c.
References ep2_add, ep2_free, ep2_neg(), ep2_new, ep2_null, ep2_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep2_mul_basic(), ep2_mul_cof_b12(), ep2_mul_dig(), ep2_mul_fix_plain(), ep2_mul_gls_imp(), ep2_mul_naf_imp(), ep2_mul_reg_gls(), ep2_mul_reg_imp(), ep2_mul_sim_endom(), ep2_mul_sim_joint(), ep2_mul_sim_lot(), and ep2_mul_sim_plain().
ep2_dbl_basic()
void ep2_dbl_basic (ep2_t r, const ep2_t p)
Doubles a point represented in affine coordinates in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[int] p - the point to double.
Definition at line 86 of file relic_ep2_dbl.c.
References ep2_is_infty(), and ep2_set_infty().
ep2_dbl_slp_basic()
void ep2_dbl_slp_basic (ep2_t r, fp2_t s, const ep2_t p)
Doubles a point represented in affine coordinates in an elliptic curve over a quadratic extension and returns the computed slope.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the point to double.
Definition at line 94 of file relic_ep2_dbl.c.
References ep2_is_infty(), and ep2_set_infty().
Referenced by pp_dbl_k12_basic(), and pp_dbl_k8_basic().
ep2_dbl_projc()
void ep2_dbl_projc (ep2_t r, const ep2_t p)
Doubles a point represented in projective coordinates in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 107 of file relic_ep2_dbl.c.
References ep2_is_infty(), and ep2_set_infty().
ep2_dbl_jacob()
void ep2_dbl_jacob (ep2_t r, const ep2_t p)
Doubles a point represented in Jacobian coordinates in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 120 of file relic_ep2_dbl.c.
References ep2_is_infty(), and ep2_set_infty().
ep2_mul_basic()
void ep2_mul_basic (ep2_t r, const ep2_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the binary method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 393 of file relic_ep2_mul.c.
References bn_bits(), bn_is_zero(), bn_rec_naf(), bn_sign(), ep2_add, ep2_dbl, ep2_free, ep2_is_infty(), ep2_mul_dig(), ep2_neg(), ep2_new, ep2_norm(), ep2_null, ep2_set_infty(), ep2_sub(), ERR_CAUGHT, ERR_NO_BUFFER, RLC_ALLOCA, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by ep2_frb(), ep2_mul_cof_b12(), and ep2_mul_cof_bn().
ep2_mul_slide()
void ep2_mul_slide (ep2_t r, const ep2_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the sliding window method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 451 of file relic_ep2_mul.c.
References bn_is_zero(), bn_rec_slw(), bn_sign(), ep2_add, ep2_copy(), ep2_dbl, ep2_free, ep2_is_infty(), ep2_neg(), ep2_new, ep2_norm(), ep2_norm_sim(), ep2_null, ep2_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_THROW, RLC_TRY, RLC_WIDTH, and util_bits_dig().
ep2_mul_monty()
void ep2_mul_monty (ep2_t r, const ep2_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the constant-time Montgomery ladder point multiplication method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 521 of file relic_ep2_mul.c.
References bn_abs(), bn_add(), bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_new, bn_null, dv_swap_sec(), ep2_add, ep2_blind(), ep2_curve_get_ord(), ep2_dbl, ep2_free, ep2_is_infty(), ep2_new, ep2_norm(), ep2_null, ep2_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_MAX, RLC_SEL, RLC_THROW, and RLC_TRY.
ep2_mul_lwnaf()
void ep2_mul_lwnaf (ep2_t r, const ep2_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the w-NAF method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 597 of file relic_ep2_mul.c.
References bn_is_zero(), ep2_is_infty(), ep2_mul_gls_imp(), ep2_mul_naf_imp(), ep2_set_infty(), and ep_curve_is_endom().
ep2_mul_lwreg()
void ep2_mul_lwreg (ep2_t r, const ep2_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using a regular method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 619 of file relic_ep2_mul.c.
References bn_is_zero(), ep2_is_infty(), ep2_mul_reg_gls(), ep2_mul_reg_imp(), ep2_set_infty(), and ep_curve_is_endom().
ep2_mul_gen()
void ep2_mul_gen (ep2_t r, const bn_t k)
Multiplies the generator of an elliptic curve over a qaudratic extension.
Parameters
[out] r - the result.
[in] k - the integer.
Definition at line 639 of file relic_ep2_mul.c.
References bn_is_zero(), ep2_curve_get_gen(), ep2_curve_get_tab(), ep2_free, ep2_mul, ep2_mul_fix, ep2_new, ep2_null, ep2_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep2_mul_sim_gen(), and ep2_rand().
ep2_mul_dig()
void ep2_mul_dig (ep2_t r, const ep2_t p, const dig_t k)
Multiplies a prime elliptic point by a small integer.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 666 of file relic_ep2_mul.c.
References bn_free, bn_new, bn_null, bn_rec_naf(), bn_set_dig(), ep2_add, ep2_copy(), ep2_dbl, ep2_free, ep2_is_infty(), ep2_new, ep2_norm(), ep2_null, ep2_set_infty(), ep2_sub(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep2_mul_basic().
ep2_mul_cof()
void ep2_mul_cof (ep2_t r, const ep2_t p)
Multiplies a point in an elliptic curve over a quadratic extension field by the curve cofactor or a small multiple for which a short vector exists. In short, it takes a point in the curve to the large prime-order subgroup.
Parameters
[out] R - the result.
[in] P - the point to multiply.
Definition at line 152 of file relic_ep2_mul_cof.c.
References bn_free, bn_null, ep2_curve_get_cof(), ep2_mul_big, ep2_mul_cof_b12(), ep2_mul_cof_bn(), EP_B12, EP_BN, ep_curve_is_pairf(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep2_map_basic(), ep2_map_from_field(), and ep2_map_swift().
ep2_mul_pre_basic()
void ep2_mul_pre_basic (ep2_t * t, const ep2_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the binary method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 91 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, ep2_copy(), ep2_curve_get_ord(), ep2_dbl, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep2_mul_pre_yaowi()
void ep2_mul_pre_yaowi (ep2_t * t, const ep2_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using Yao's windowing method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
ep2_mul_pre_nafwi()
void ep2_mul_pre_nafwi (ep2_t * t, const ep2_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the NAF windowing method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
ep2_mul_pre_combs()
void ep2_mul_pre_combs (ep2_t * t, const ep2_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the single-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 151 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, ep2_add, ep2_copy(), ep2_curve_get_ord(), ep2_dbl, ep2_norm(), ep2_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_EP_TABLE_COMBS, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep2_mul_pre_combd()
void ep2_mul_pre_combd (ep2_t * t, const ep2_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the double-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 258 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, ep2_add, ep2_copy(), ep2_curve_get_ord(), ep2_dbl, ep2_norm(), ep2_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_EP_TABLE_COMBD, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep2_mul_pre_lwnaf()
void ep2_mul_pre_lwnaf (ep2_t * t, const ep2_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the w-(T)NAF method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 372 of file relic_ep2_mul_fix.c.
References ep2_tab(), and RLC_DEPTH.
ep2_mul_fix_basic()
void ep2_mul_fix_basic (ep2_t r, const ep2_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the binary method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 114 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_new, bn_null, ep2_add, ep2_curve_get_ord(), ep2_norm(), ep2_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep2_mul_fix_yaowi()
void ep2_mul_fix_yaowi (ep2_t r, const ep2_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and Yao's windowing method
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
ep2_mul_fix_nafwi()
void ep2_mul_fix_nafwi (ep2_t r, const ep2_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the w-(T)NAF method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
ep2_mul_fix_combs()
void ep2_mul_fix_combs (ep2_t r, const ep2_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the single-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 193 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_new, bn_null, ep2_add, ep2_copy(), ep2_curve_get_ord(), ep2_dbl, ep2_norm(), ep2_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep2_mul_fix_combd()
void ep2_mul_fix_combd (ep2_t r, const ep2_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the double-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 307 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_new, bn_null, ep2_add, ep2_curve_get_ord(), ep2_dbl, ep2_norm(), ep2_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep2_mul_fix_lwnaf()
void ep2_mul_fix_lwnaf (ep2_t r, const ep2_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the w-(T)NAF method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 376 of file relic_ep2_mul_fix.c.
References bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, ep2_curve_get_ord(), ep2_mul_fix_plain(), ep2_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep2_mul_sim_basic()
void ep2_mul_sim_basic (ep2_t r, const ep2_t p, const bn_t k, const ep2_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using scalar multiplication and point addition.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 256 of file relic_ep2_mul_sim.c.
References ep2_add, ep2_free, ep2_mul, ep2_new, ep2_norm(), ep2_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep2_mul_sim_trick()
void ep2_mul_sim_trick (ep2_t r, const ep2_t p, const bn_t k, const ep2_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using shamir's trick.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 281 of file relic_ep2_mul_sim.c.
References bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, bn_rec_win(), ep2_add, ep2_copy(), ep2_curve_get_ord(), ep2_dbl, ep2_free, ep2_is_infty(), ep2_mul, ep2_new, ep2_norm(), ep2_norm_sim(), ep2_null, ep2_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_CEIL, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_THROW, RLC_TRY, and RLC_WIDTH.
ep2_mul_sim_inter()
void ep2_mul_sim_inter (ep2_t r, const ep2_t p, const bn_t k, const ep2_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using interleaving of NAFs.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 375 of file relic_ep2_mul_sim.c.
References bn_is_zero(), ep2_is_infty(), ep2_mul, ep2_mul_sim_endom(), ep2_mul_sim_plain(), and ep_curve_is_endom().
ep2_mul_sim_joint()
void ep2_mul_sim_joint (ep2_t r, const ep2_t p, const bn_t k, const ep2_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using Solinas' Joint Sparse Form.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 402 of file relic_ep2_mul_sim.c.
References bn_bits(), bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, bn_rec_jsf(), bn_sign(), ep2_add, ep2_copy(), ep2_curve_get_ord(), ep2_dbl, ep2_free, ep2_is_infty(), ep2_mul, ep2_neg(), ep2_new, ep2_norm(), ep2_norm_sim(), ep2_null, ep2_set_infty(), ep2_sub(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, and RLC_TRY.
ep2_mul_sim_lot()
void ep2_mul_sim_lot (ep2_t r, const ep2_t p[], const bn_t k[], size_t n)
Multiplies simultaneously elements from a prime elliptic curve. Computes R = \Sum_i=0..n k_iP_i.
Parameters
[out] r - the result.
[out] p - the points to multiply.
[out] k - the integer scalars.
[out] n - the number of elements to multiply.
Definition at line 591 of file relic_ep2_mul_sim.c.
References bn_free, bn_mod, bn_new, bn_null, bn_rec_frb(), bn_rec_naf(), bn_sign(), ep2_add, ep2_copy(), ep2_curve_get_ord(), ep2_dbl, ep2_frb(), ep2_free, ep2_neg(), ep2_new, ep2_norm(), ep2_null, ep2_set_infty(), ep2_sub(), EP_BN, ep_curve_is_pairf(), ERR_CAUGHT, ERR_NO_MEMORY, fp_prime_get_par(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_FREE, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and util_bits_dig().
ep2_mul_sim_gen()
void ep2_mul_sim_gen (ep2_t r, const bn_t k, const ep2_t q, const bn_t m)
Multiplies and adds the generator and a prime elliptic curve point simultaneously. Computes R = [k]G + [l]Q.
Parameters
[out] r - the result.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 492 of file relic_ep2_mul_sim.c.
References bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, ep2_curve_get_gen(), ep2_curve_get_ord(), ep2_curve_get_tab(), ep2_free, ep2_is_infty(), ep2_mul, ep2_mul_gen(), ep2_mul_sim, ep2_mul_sim_endom(), ep2_mul_sim_plain(), ep2_new, ep2_null, ep_curve_is_endom(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep2_mul_sim_dig()
void ep2_mul_sim_dig (ep2_t r, const ep2_t p[], const dig_t k[], size_t len)
Multiplies prime elliptic curve points by small scalars. Computes R = \sum k_iP_i.
Parameters
[out] r - the result.
[in] p - the points to multiply.
[in] k - the small scalars.
[in] len - the number of points to multiply.
Definition at line 557 of file relic_ep2_mul_sim.c.
References ep2_add, ep2_dbl, ep2_free, ep2_new, ep2_norm(), ep2_null, ep2_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_MAX, RLC_THROW, RLC_TRY, and util_bits_dig().
ep2_norm()
void ep2_norm (ep2_t r, const ep2_t p)
Converts a point to affine coordinates.
Parameters
[out] r - the result.
[in] p - the point to convert.
Definition at line 97 of file relic_ep2_norm.c.
References BASIC, ep2_copy(), ep2_is_infty(), ep2_norm_imp(), and ep2_set_infty().
Referenced by ep2_curve_set(), ep2_map_from_field(), ep2_mul_basic(), ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep2_mul_dig(), ep2_mul_fix_basic(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_fix_plain(), ep2_mul_gls_imp(), ep2_mul_monty(), ep2_mul_naf_imp(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_reg_gls(), ep2_mul_reg_imp(), ep2_mul_sim_basic(), ep2_mul_sim_dig(), ep2_mul_sim_endom(), ep2_mul_sim_joint(), ep2_mul_sim_lot(), ep2_mul_sim_plain(), ep2_mul_sim_trick(), ep2_mul_slide(), ep2_on_curve(), ep2_size_bin(), ep2_tab(), ep2_write_bin(), pp_map_oatep_k12(), pp_map_oatep_k8(), pp_map_sim_oatep_k12(), pp_map_sim_oatep_k8(), pp_map_sim_tatep_k12(), pp_map_sim_weilp_k12(), pp_map_tatep_k12(), and pp_map_weilp_k12().
ep2_norm_sim()
void ep2_norm_sim (ep2_t * r, const ep2_t * t, int n)
Converts multiple points to affine coordinates.
Parameters
[out] r - the result.
[in] t - the points to convert.
[in] n - the number of points.
Definition at line 113 of file relic_ep2_norm.c.
References ep2_is_infty(), ep2_norm_imp(), ERR_CAUGHT, ERR_NO_MEMORY, fp2_copy(), fp2_free, fp2_inv_sim(), fp2_new, fp2_null, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by ep2_mul_reg_gls(), ep2_mul_sim_joint(), ep2_mul_sim_trick(), ep2_mul_slide(), and ep2_tab().
ep2_map_basic()
void ep2_map_basic (ep2_t p, const uint8_t * msg, size_t len)
Maps a byte array to a point in a prime elliptic curve using the hash and increment approach.
Parameters
[out] p - the result.
[in] msg - the byte array to map.
[in] len - the array length in bytes.
Definition at line 176 of file relic_ep2_map.c.
References BASIC, bn_free, bn_new, bn_null, bn_read_bin(), ep2_mul_cof(), ep2_rhs(), ERR_CAUGHT, fp2_add_dig(), fp2_free, fp2_is_sqr(), fp2_new, fp2_null, fp2_set_dig(), fp2_srt(), fp2_zero(), fp_prime_conv(), md_map, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_MD_LEN, RLC_MIN, RLC_THROW, and RLC_TRY.
ep2_map_sswum()
void ep2_map_sswum (ep2_t p, const uint8_t * msg, size_t len)
Maps a byte array to a point in a prime elliptic curve using the (Simplified) Shallue-van de Woestijne-Ulas map.
Parameters
[out] p - the result.
[in] msg - the byte array to map.
[in] len - the array length in bytes.
Definition at line 222 of file relic_ep2_map.c.
References ep2_map_from_field(), ep_param_level(), ERR_CAUGHT, ERR_NO_MEMORY, FP_PRIME, md_xmd, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
ep2_map_swift()
void ep2_map_swift (ep2_t p, const uint8_t * msg, size_t len)
Maps a byte array to a point in a prime elliptic curve using the SwiftEC approach.
Parameters
[out] p - the result.
[in] msg - the byte array to map.
[in] len - the array length in bytes.
Definition at line 248 of file relic_ep2_map.c.
References BASIC, bn_free, bn_get_bit(), bn_new, bn_null, bn_read_bin(), core_get(), _ctx_t::ep2_b, ep2_curve_get_a(), ep2_curve_opt_a(), ep2_curve_opt_b(), ep2_mul_cof(), ep2_rhs(), ep2_set_infty(), ep_curve_opt_a(), _ctx_t::ep_map_c, ep_param_level(), ERR_CAUGHT, ERR_NO_VALID, fp2_add, fp2_add_dig(), fp2_copy(), fp2_copy_sec(), fp2_dbl, fp2_free, fp2_inv(), fp2_inv_sim(), fp2_is_sqr(), fp2_is_zero(), fp2_mul, fp2_mul_dig(), fp2_neg(), fp2_new, fp2_null, fp2_set_dig(), fp2_sqr, fp2_srt(), fp2_sub, fp2_sub_dig(), fp_hlv, fp_is_even(), fp_is_zero(), fp_mul, FP_PRIME, fp_prime_back(), fp_prime_conv(), fp_sub_dig(), md_xmd, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_ONE, RLC_THROW, RLC_TRY, and RLC_ZERO.
ep2_frb()
void ep2_frb (ep2_t r, const ep2_t p, int i)
Computes a power of the Gailbraith-Lin-Scott homomorphism of a point represented in affine coordinates on a twisted elliptic curve over a quadratic exension. That is, Psi^i(P) = Twist(P)(Frob^i(unTwist(P)). On the trace-zero group of a quadratic twist, consists of a power of the Frobenius map of a point represented in affine coordinates in an elliptic curve over a quadratic exension. Computes Frob^i(P) = (p^i)P.
Parameters
[out] r - the result in affine coordinates.
[in] p - a point in affine coordinates.
[in] i - the power of the Frobenius map.
Definition at line 39 of file relic_ep2_frb.c.
References bn_free, bn_new, bn_null, core_get(), ep2_copy(), ep2_curve_opt_a(), _ctx_t::ep2_frb, ep2_mul_basic(), ERR_NO_MEMORY, fp2_frb(), fp2_mul, fp_prime_get_par(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, RLC_TRY, and RLC_ZERO.
Referenced by ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep2_mul_gls_imp(), ep2_mul_reg_gls(), ep2_mul_sim_endom(), ep2_mul_sim_lot(), and pp_fin_k12_oatep().
ep2_pck()
void ep2_pck (ep2_t r, const ep2_t p)
Compresses a point in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[in] p - the point to compress.
Definition at line 39 of file relic_ep2_pck.c.
References BASIC, bn_cmp(), bn_free, bn_hlv(), bn_new, bn_null, dv_copy(), ERR_CAUGHT, fp2_copy(), fp2_zero(), fp_prime_back(), fp_prime_get(), fp_set_bit(), fp_set_dig(), fp_zero(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_GT, RLC_THROW, and RLC_TRY.
Referenced by ep2_write_bin().
ep2_upk()
int ep2_upk (ep2_t r, const ep2_t p)
Decompresses a point in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[in] p - the point to decompress.
Returns
if the decompression was successful
Definition at line 73 of file relic_ep2_pck.c.
References BASIC, bn_cmp(), bn_free, bn_hlv(), bn_is_zero(), bn_new, bn_null, dv_copy(), ep2_rhs(), ERR_CAUGHT, fp2_copy(), fp2_free, fp2_neg(), fp2_new, fp2_null, fp2_srt(), fp_get_bit(), fp_prime_back(), fp_prime_get(), fp_set_dig(), fp_zero(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_GT, RLC_THROW, and RLC_TRY.
Referenced by ep2_read_bin().
ep3_curve_init()
void ep3_curve_init (void)
Initializes the elliptic curve over cubic extension.
Definition at line 212 of file relic_ep3_curve.c.
References bn_make(), core_get(), _ctx_t::ep3_a, _ctx_t::ep3_b, _ctx_t::ep3_frb, _ctx_t::ep3_g, _ctx_t::ep3_h, ep3_new, _ctx_t::ep3_pre, _ctx_t::ep3_ptr, _ctx_t::ep3_r, fp3_new, RLC_EP_TABLE, RLC_FP_DIGS, ep3_st::x, ep3_st::y, and ep3_st::z.
Referenced by pp_map_init().
ep3_curve_clean()
void ep3_curve_clean (void)
Finalizes the elliptic curve over cubic extension.
Definition at line 243 of file relic_ep3_curve.c.
References bn_clean(), core_get(), _ctx_t::ep3_a, _ctx_t::ep3_b, _ctx_t::ep3_frb, ep3_free, _ctx_t::ep3_g, _ctx_t::ep3_h, _ctx_t::ep3_pre, _ctx_t::ep3_r, fp3_free, RLC_EP_TABLE, ep3_st::x, ep3_st::y, and ep3_st::z.
Referenced by pp_map_clean().
ep3_curve_get_a()
fp_t * ep3_curve_get_a (void)
Returns the 'a' coefficient of the currently configured elliptic curve.
Returns
the 'a' coefficient of the elliptic curve.
Definition at line 323 of file relic_ep3_curve.c.
References core_get(), and _ctx_t::ep3_a.
Referenced by ep3_rhs().
ep3_curve_get_b()
fp_t * ep3_curve_get_b (void)
Returns the 'b' coefficient of the currently configured elliptic curve.
Parameters
[out] b - the 'b' coefficient of the elliptic curve.
Definition at line 327 of file relic_ep3_curve.c.
References core_get(), and _ctx_t::ep3_b.
Referenced by ep3_rhs(), pp_dbl_k18_projc_basic(), and pp_dbl_k18_projc_lazyr().
ep3_curve_opt_a()
int ep3_curve_opt_a (void)
Returns a optimization identifier based on the 'a' coefficient of the curve.
Returns
the optimization identifier.
Definition at line 264 of file relic_ep3_curve.c.
References core_get(), and _ctx_t::ep3_opt_a.
Referenced by ep3_rhs().
ep3_curve_opt_b()
int ep3_curve_opt_b (void)
Returns b optimization identifier based on the 'b' coefficient of the curve.
Returns
the optimization identifier.
Definition at line 268 of file relic_ep3_curve.c.
References core_get(), and _ctx_t::ep3_opt_b.
Referenced by ep3_rhs().
ep3_curve_mul_a()
void ep3_curve_mul_a (fp3_t c, const fp3_t a)
Multiplies a field element by the a-coefficient of the curve.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
Definition at line 272 of file relic_ep3_curve.c.
References core_get(), _ctx_t::ep3_a, _ctx_t::ep3_opt_a, fp3_copy(), fp3_dbl, fp3_mul, fp3_mul_dig(), fp3_zero(), RLC_ONE, RLC_TINY, RLC_TWO, and RLC_ZERO.
ep3_curve_mul_b()
void ep3_curve_mul_b (fp3_t c, const fp3_t a)
Multiplies a field element by the b-coefficient of the curve.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
Definition at line 295 of file relic_ep3_curve.c.
References core_get(), _ctx_t::ep3_b, _ctx_t::ep3_opt_b, fp3_copy(), fp3_mul, fp3_mul_dig(), fp3_zero(), RLC_ONE, RLC_TINY, and RLC_ZERO.
ep3_curve_is_twist()
int ep3_curve_is_twist (void)
Tests if the configured elliptic curve is a twist.
Returns
the type of the elliptic curve twist, 0 if non-twisted curve.
Definition at line 315 of file relic_ep3_curve.c.
References core_get(), and _ctx_t::ep3_is_twist.
Referenced by fp18_mul_dxs_lazyr(), pp_add_k18_basic(), pp_add_k18_projc_basic(), pp_add_k18_projc_lazyr(), pp_dbl_k18_basic(), pp_dbl_k18_projc_basic(), and pp_dbl_k18_projc_lazyr().
ep3_curve_get_gen()
void ep3_curve_get_gen (ep3_t g)
Returns the generator of the group of points in the elliptic curve.
Parameters
[out] g - the returned generator.
Definition at line 319 of file relic_ep3_curve.c.
References core_get(), and ep3_copy().
Referenced by ep3_mul_gen(), and ep3_mul_sim_gen().
ep3_curve_get_tab()
ep3_t * ep3_curve_get_tab (void)
Returns the precomputation table for the generator.
Returns
the table.
Definition at line 346 of file relic_ep3_curve.c.
References core_get(), and _ctx_t::ep3_ptr.
Referenced by ep3_curve_set(), ep3_curve_set_twist(), ep3_mul_gen(), and ep3_mul_sim_gen().
ep3_curve_get_ord()
void ep3_curve_get_ord (bn_t n)
Returns the order of the group of points in the elliptic curve.
Parameters
[out] n - the returned order.
Definition at line 331 of file relic_ep3_curve.c.
References bn_copy(), core_get(), _ctx_t::ep3_is_twist, _ctx_t::ep3_r, and ep_curve_get_ord().
Referenced by ep3_mul_fix_basic(), ep3_mul_fix_combd(), ep3_mul_fix_combs(), ep3_mul_fix_lwnaf(), ep3_mul_gls_imp(), ep3_mul_monty(), ep3_mul_pre_basic(), ep3_mul_pre_combd(), ep3_mul_pre_combs(), ep3_mul_reg_gls(), ep3_mul_reg_imp(), ep3_mul_sim_trick(), and ep3_rand().
ep3_curve_get_cof()
void ep3_curve_get_cof (bn_t h)
Returns the cofactor of the group order in the elliptic curve.
Parameters
[out] h - the returned cofactor.
Definition at line 340 of file relic_ep3_curve.c.
References bn_copy(), and core_get().
Referenced by ep3_mul_cof().
ep3_curve_set()
void ep3_curve_set (const fp3_t a, const fp3_t b, const ep3_t g, const bn_t r, const bn_t h)
Configures an elliptic curve over a cubic extension by its coefficients.
Parameters
[in] a - the 'a' coefficient of the curve.
[in] b - the 'b' coefficient of the curve.
[in] g - the generator.
[in] r - the order of the group of points.
[in] h - the cofactor of the group order.
Definition at line 467 of file relic_ep3_curve.c.
References bn_copy(), core_get(), _ctx_t::ep3_a, _ctx_t::ep3_b, ep3_curve_get_tab(), _ctx_t::ep3_g, _ctx_t::ep3_h, _ctx_t::ep3_is_twist, ep3_mul_pre, ep3_norm(), _ctx_t::ep3_r, and fp3_copy().
ep3_curve_set_twist()
void ep3_curve_set_twist (int type)
Configures an elliptic curve by twisting the curve over the base prime field.
Parameters
- the type of twist (multiplicative or divisive)
Definition at line 356 of file relic_ep3_curve.c.
References ASSIGN, BASIC, bn_copy(), bn_free, bn_new, bn_null, core_get(), detect_opt(), _ctx_t::ep3_a, _ctx_t::ep3_b, ep3_copy(), ep3_curve_get_tab(), _ctx_t::ep3_frb, ep3_free, _ctx_t::ep3_g, _ctx_t::ep3_h, _ctx_t::ep3_is_twist, ep3_mul_pre, ep3_new, ep3_null, _ctx_t::ep3_opt_a, _ctx_t::ep3_opt_b, _ctx_t::ep3_r, ep_param_get(), ERR_CAUGHT, ERR_NO_VALID, FM18_P768, fp18_free, fp18_inv(), fp18_new, fp18_null, fp18_zero(), fp3_copy(), fp3_free, fp3_inv(), fp3_mul_art(), fp3_new, fp3_null, _ctx_t::fp3_p1, fp3_set_dig(), fp3_zero(), fp9_set_dig(), fp_copy(), K18_P354, K18_P508, K18_P638, pc_core_calc(), RLC_CATCH_ANY, RLC_EP_DTYPE, RLC_EP_MTYPE, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, RLC_TRY, and SG18_P638.
Referenced by ep_param_set_any_pairf().
ep3_is_infty()
int ep3_is_infty (const ep3_t p)
Tests if a point on an elliptic curve is at the infinity.
Parameters
[in] p - the point to test.
Returns
1 if the point is at infinity, 0 otherise.
Definition at line 39 of file relic_ep3_util.c.
References fp3_is_zero().
Referenced by ep3_add_basic(), ep3_add_jacob(), ep3_add_projc(), ep3_add_slp_basic(), ep3_cmp(), ep3_dbl_basic(), ep3_dbl_jacob(), ep3_dbl_projc(), ep3_dbl_slp_basic(), ep3_mul_basic(), ep3_mul_dig(), ep3_mul_lwnaf(), ep3_mul_lwreg(), ep3_mul_monty(), ep3_mul_sim_gen(), ep3_mul_sim_inter(), ep3_mul_sim_joint(), ep3_mul_sim_trick(), ep3_mul_slide(), ep3_neg(), ep3_norm(), ep3_norm_sim(), ep3_on_curve(), ep3_psi(), ep3_size_bin(), ep3_write_bin(), pp_map_oatep_k18(), pp_map_sim_oatep_k18(), pp_map_sim_tatep_k18(), pp_map_sim_weilp_k18(), pp_map_tatep_k18(), pp_map_weilp_k18(), and pp_norm_k18().
ep3_set_infty()
void ep3_set_infty (ep3_t p)
Assigns an elliptic curve point to the point at infinity.
Parameters
[out] p - the point to assign.
Definition at line 43 of file relic_ep3_util.c.
References BASIC, and fp3_zero().
Referenced by ep3_dbl_basic(), ep3_dbl_jacob(), ep3_dbl_projc(), ep3_dbl_slp_basic(), ep3_map(), ep3_mul_basic(), ep3_mul_dig(), ep3_mul_fix_basic(), ep3_mul_fix_combd(), ep3_mul_fix_combs(), ep3_mul_fix_lwnaf(), ep3_mul_fix_plain(), ep3_mul_gen(), ep3_mul_gls_imp(), ep3_mul_lwnaf(), ep3_mul_lwreg(), ep3_mul_monty(), ep3_mul_naf_imp(), ep3_mul_pre_combd(), ep3_mul_pre_combs(), ep3_mul_reg_imp(), ep3_mul_sim_dig(), ep3_mul_sim_joint(), ep3_mul_sim_lot(), ep3_mul_sim_plain(), ep3_mul_sim_trick(), ep3_mul_slide(), ep3_neg(), ep3_norm(), ep3_psi(), ep3_read_bin(), ep3_sub(), and pp_norm_k18().
ep3_copy()
void ep3_copy (ep3_t r, const ep3_t p)
Copies the second argument to the first argument.
Parameters
[out] q - the result.
[in] p - the elliptic curve point to copy.
Definition at line 50 of file relic_ep3_util.c.
References fp3_copy().
Referenced by ep3_add_basic(), ep3_add_jacob(), ep3_add_projc(), ep3_add_slp_basic(), ep3_blind(), ep3_cmp(), ep3_curve_get_gen(), ep3_curve_set_twist(), ep3_frb(), ep3_mul_dig(), ep3_mul_fix_combs(), ep3_mul_gls_imp(), ep3_mul_pre_basic(), ep3_mul_pre_combd(), ep3_mul_pre_combs(), ep3_mul_reg_gls(), ep3_mul_sim_joint(), ep3_mul_sim_lot(), ep3_mul_sim_trick(), ep3_mul_slide(), ep3_norm(), ep3_norm_imp(), ep3_tab(), pp_add_k18_basic(), pp_dbl_k18_basic(), pp_mil_k18(), and pp_norm_k18().
ep3_cmp()
int ep3_cmp (const ep3_t p, const ep3_t q)
Compares two elliptic curve points.
Parameters
[in] p - the first elliptic curve point.
[in] q - the second elliptic curve point.
Returns
RLC_EQ if p == q and RLC_NE if p != q.
Definition at line 39 of file relic_ep3_cmp.c.
References ep3_copy(), ep3_free, ep3_is_infty(), ep3_new, ep3_null, ERR_CAUGHT, fp3_cmp(), fp3_mul, fp3_sqr, JACOB, PROJC, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_NE, RLC_THROW, and RLC_TRY.
ep3_rand()
void ep3_rand (ep3_t p)
Assigns a random value to an elliptic curve point.
Parameters
[out] p - the elliptic curve point to assign.
Definition at line 57 of file relic_ep3_util.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), ep3_curve_get_ord(), ep3_mul_gen(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep3_blind()
void ep3_blind (ep3_t r, const ep3_t p)
Randomizes coordinates of an elliptic curve point.
Parameters
[out] r - the blinded prime elliptic curve point.
[in] p - the prime elliptic curve point to blind.
Definition at line 81 of file relic_ep3_util.c.
References ep3_copy(), ERR_CAUGHT, fp3_free, fp3_mul, fp3_new, fp3_null, fp3_rand(), fp3_sqr, JACOB, PROJC, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep3_mul_monty().
ep3_rhs()
void ep3_rhs (fp3_t rhs, const fp3_t x)
Computes the right-hand side of the elliptic curve equation at the x-coordinate of a certain prime elliptic curve point.
Parameters
[out] rhs - the result.
[in] x - the x-coordinate of the point.
Definition at line 112 of file relic_ep3_util.c.
References ep3_curve_get_a(), ep3_curve_get_b(), ep3_curve_opt_a(), ep3_curve_opt_b(), ERR_CAUGHT, fp3_add, fp3_add_dig(), fp3_copy(), fp3_free, fp3_mul, fp3_mul_dig(), fp3_new, fp3_null, fp3_sqr, fp3_sub_dig(), fp_add_dig(), fp_sub_dig(), RLC_CATCH_ANY, RLC_FINALLY, RLC_MIN3, RLC_ONE, RLC_THROW, RLC_TINY, RLC_TRY, RLC_TWO, and RLC_ZERO.
Referenced by ep3_map(), and ep3_on_curve().
ep3_on_curve()
int ep3_on_curve (const ep3_t p)
Tests if a point is in the curve.
Parameters
[in] p - the point to test.
Definition at line 176 of file relic_ep3_util.c.
References ep3_free, ep3_is_infty(), ep3_new, ep3_norm(), ep3_null, ep3_rhs(), ERR_CAUGHT, fp3_cmp(), fp3_sqr, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep3_read_bin().
ep3_tab()
void ep3_tab (ep3_t * t, const ep3_t p, int w)
Builds a precomputation table for multiplying a random prime elliptic point.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
[in] w - the window width.
Definition at line 199 of file relic_ep3_util.c.
References ep3_add, ep3_copy(), ep3_dbl, ep3_norm(), and ep3_norm_sim().
Referenced by ep3_mul_naf_imp(), ep3_mul_pre_lwnaf(), ep3_mul_reg_imp(), and ep3_mul_sim_plain().
ep3_print()
void ep3_print (const ep3_t p)
Prints an elliptic curve point.
Parameters
[in] p - the elliptic curve point to print.
Definition at line 220 of file relic_ep3_util.c.
References fp3_print().
ep3_size_bin()
size_t ep3_size_bin (const ep3_t a, int pack)
Returns the number of bytes necessary to store a prime elliptic curve point over a cubic extension with optional point compression.
Parameters
[in] a - the prime field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 226 of file relic_ep3_util.c.
References ep3_free, ep3_is_infty(), ep3_new, ep3_norm(), ep3_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.
ep3_read_bin()
void ep3_read_bin (ep3_t a, const uint8_t * bin, size_t len)
Reads a prime elliptic curve point over a cubic extension from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_VALID - if the encoded point is invalid.
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 252 of file relic_ep3_util.c.
References BASIC, ep3_on_curve(), ep3_set_infty(), ERR_NO_BUFFER, ERR_NO_VALID, fp3_read_bin(), fp3_set_dig(), RLC_FP_BYTES, and RLC_THROW.
ep3_write_bin()
void ep3_write_bin (uint8_t * bin, size_t len, const ep3_t a, int pack)
Writes a prime elliptic curve pointer over a cubic extension to a byte vector in big-endian format with optional point compression.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the prime elliptic curve point to write.
[in] pack - the flag to indicate compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 286 of file relic_ep3_util.c.
References ep3_free, ep3_is_infty(), ep3_new, ep3_norm(), ep3_null, ERR_CAUGHT, ERR_NO_BUFFER, fp3_write_bin(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.
ep3_neg()
void ep3_neg (ep3_t r, const ep3_t p)
Negates a point represented in affine coordinates in an elliptic curve over a cubic extension.
Parameters
[out] r - the result.
[out] p - the point to negate.
Definition at line 39 of file relic_ep3_neg.c.
References ep3_is_infty(), ep3_set_infty(), fp3_copy(), and fp3_neg().
Referenced by ep3_mul_basic(), ep3_mul_cof_k18(), ep3_mul_fix_plain(), ep3_mul_gls_imp(), ep3_mul_naf_imp(), ep3_mul_reg_gls(), ep3_mul_reg_imp(), ep3_mul_sim_joint(), ep3_mul_sim_lot(), ep3_mul_sim_trick(), ep3_mul_slide(), ep3_sub(), pp_map_oatep_k18(), pp_map_sim_oatep_k18(), pp_mil_k18(), and pp_mil_lit_k18().
ep3_add_basic()
void ep3_add_basic (ep3_t r, const ep3_t p, const ep3_t q)
Adds to points represented in affine coordinates in an elliptic curve over a cubic extension.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 109 of file relic_ep3_add.c.
References ep3_copy(), and ep3_is_infty().
ep3_add_slp_basic()
void ep3_add_slp_basic (ep3_t r, fp3_t s, const ep3_t p, const ep3_t q)
Adds to points represented in affine coordinates in an elliptic curve over a cubic extension and returns the computed slope.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 123 of file relic_ep3_add.c.
References ep3_copy(), and ep3_is_infty().
Referenced by pp_add_k18_basic().
ep3_add_projc()
void ep3_add_projc (ep3_t r, const ep3_t p, const ep3_t q)
Adds two points represented in projective coordinates in an elliptic curve over a cubic extension.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 141 of file relic_ep3_add.c.
References ep3_copy(), and ep3_is_infty().
ep3_add_jacob()
void ep3_add_jacob (ep3_t r, const ep3_t p, const ep3_t q)
Adds two points represented in Jacobian coordinates in an elliptic curve over a cubic extension.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 159 of file relic_ep3_add.c.
References ep3_copy(), and ep3_is_infty().
ep3_sub()
void ep3_sub (ep3_t r, const ep3_t p, const ep3_t q)
Subtracts a point in an elliptic curve over a cubic extension from another.
Parameters
[out] r - the result.
[in] p - the first point.
[in] q - the point to subtract.
Definition at line 175 of file relic_ep3_add.c.
References ep3_add, ep3_free, ep3_neg(), ep3_new, ep3_null, ep3_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep3_mul_basic(), ep3_mul_cof_fm18(), ep3_mul_cof_k18(), ep3_mul_cof_sg18(), ep3_mul_dig(), ep3_mul_fix_plain(), ep3_mul_gls_imp(), ep3_mul_naf_imp(), ep3_mul_reg_gls(), ep3_mul_reg_imp(), ep3_mul_sim_joint(), ep3_mul_sim_lot(), ep3_mul_sim_plain(), and ep3_psi().
ep3_dbl_basic()
void ep3_dbl_basic (ep3_t r, const ep3_t p)
Doubles a point represented in affine coordinates in an elliptic curve over a cubic extension.
Parameters
[out] r - the result.
[int] p - the point to double.
Definition at line 86 of file relic_ep3_dbl.c.
References ep3_is_infty(), and ep3_set_infty().
ep3_dbl_slp_basic()
void ep3_dbl_slp_basic (ep3_t r, fp3_t s, const ep3_t p)
Doubles a point represented in affine coordinates in an elliptic curve over a cubic extension and returns the computed slope.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the point to double.
Definition at line 94 of file relic_ep3_dbl.c.
References ep3_is_infty(), and ep3_set_infty().
Referenced by pp_dbl_k18_basic().
ep3_dbl_projc()
void ep3_dbl_projc (ep3_t r, const ep3_t p)
Doubles a point represented in projective coordinates in an elliptic curve over a cubic extension.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 107 of file relic_ep3_dbl.c.
References ep3_is_infty(), and ep3_set_infty().
ep3_dbl_jacob()
void ep3_dbl_jacob (ep3_t r, const ep3_t p)
Doubles a point represented in Jacobian coordinates in an elliptic curve over a cubic extension.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 120 of file relic_ep3_dbl.c.
References ep3_is_infty(), and ep3_set_infty().
ep3_mul_basic()
void ep3_mul_basic (ep3_t r, const ep3_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the binary method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 467 of file relic_ep3_mul.c.
References bn_bits(), bn_is_zero(), bn_rec_naf(), bn_sign(), ep3_add, ep3_dbl, ep3_free, ep3_is_infty(), ep3_mul_dig(), ep3_neg(), ep3_new, ep3_norm(), ep3_null, ep3_set_infty(), ep3_sub(), ERR_CAUGHT, ERR_NO_BUFFER, RLC_ALLOCA, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by ep3_mul_cof_fm18(), ep3_mul_cof_k18(), and ep3_mul_cof_sg18().
ep3_mul_slide()
void ep3_mul_slide (ep3_t r, const ep3_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the sliding window method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 525 of file relic_ep3_mul.c.
References bn_is_zero(), bn_rec_slw(), bn_sign(), ep3_add, ep3_copy(), ep3_dbl, ep3_free, ep3_is_infty(), ep3_neg(), ep3_new, ep3_norm(), ep3_norm_sim(), ep3_null, ep3_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_THROW, RLC_TRY, RLC_WIDTH, and util_bits_dig().
ep3_mul_monty()
void ep3_mul_monty (ep3_t r, const ep3_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the constant-time Montgomery ladder point multiplication method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 596 of file relic_ep3_mul.c.
References bn_abs(), bn_add(), bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_new, bn_null, dv_swap_sec(), ep3_add, ep3_blind(), ep3_curve_get_ord(), ep3_dbl, ep3_free, ep3_is_infty(), ep3_new, ep3_norm(), ep3_null, ep3_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_MAX, RLC_SEL, RLC_THROW, and RLC_TRY.
ep3_mul_lwnaf()
void ep3_mul_lwnaf (ep3_t r, const ep3_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the w-NAF method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 678 of file relic_ep3_mul.c.
References bn_is_zero(), ep3_is_infty(), ep3_mul_gls_imp(), ep3_mul_naf_imp(), ep3_set_infty(), and ep_curve_is_endom().
ep3_mul_lwreg()
void ep3_mul_lwreg (ep3_t r, const ep3_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using a regular method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 700 of file relic_ep3_mul.c.
References bn_is_zero(), ep3_is_infty(), ep3_mul_reg_gls(), ep3_mul_reg_imp(), ep3_set_infty(), and ep_curve_is_endom().
ep3_mul_gen()
void ep3_mul_gen (ep3_t r, const bn_t k)
Multiplies the generator of an elliptic curve over a qaudratic extension.
Parameters
[out] r - the result.
[in] k - the integer.
Definition at line 720 of file relic_ep3_mul.c.
References bn_is_zero(), ep3_curve_get_gen(), ep3_curve_get_tab(), ep3_free, ep3_mul, ep3_mul_fix, ep3_new, ep3_null, ep3_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep3_mul_sim_gen(), and ep3_rand().
ep3_mul_dig()
void ep3_mul_dig (ep3_t r, const ep3_t p, const dig_t k)
Multiplies a prime elliptic point by a small integer.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 747 of file relic_ep3_mul.c.
References bn_free, bn_new, bn_null, bn_rec_naf(), bn_set_dig(), ep3_add, ep3_copy(), ep3_dbl, ep3_free, ep3_is_infty(), ep3_new, ep3_norm(), ep3_null, ep3_set_infty(), ep3_sub(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep3_mul_basic().
ep3_mul_cof()
void ep3_mul_cof (ep3_t r, const ep3_t p)
Multiplies a point in an elliptic curve over a cubic extension field by the curve cofactor or a small multiple for which a short vector exists. In short, it takes a point in the curve to the large prime-order subgroup.
Parameters
[out] R - the result.
[in] P - the point to multiply.
Definition at line 301 of file relic_ep3_mul_cof.c.
References bn_free, bn_null, ep3_curve_get_cof(), ep3_mul_big, ep3_mul_cof_fm18(), ep3_mul_cof_k18(), ep3_mul_cof_sg18(), ep_curve_is_pairf(), EP_FM18, EP_K18, EP_SG18, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep3_map().
ep3_mul_pre_basic()
void ep3_mul_pre_basic (ep3_t * t, const ep3_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the binary method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 91 of file relic_ep3_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, ep3_copy(), ep3_curve_get_ord(), ep3_dbl, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep3_mul_pre_yaowi()
void ep3_mul_pre_yaowi (ep3_t * t, const ep3_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using Yao's windowing method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
ep3_mul_pre_nafwi()
void ep3_mul_pre_nafwi (ep3_t * t, const ep3_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the NAF windowing method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
ep3_mul_pre_combs()
void ep3_mul_pre_combs (ep3_t * t, const ep3_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the single-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 151 of file relic_ep3_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, ep3_add, ep3_copy(), ep3_curve_get_ord(), ep3_dbl, ep3_norm(), ep3_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_EP_TABLE_COMBS, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep3_mul_pre_combd()
void ep3_mul_pre_combd (ep3_t * t, const ep3_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the double-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 258 of file relic_ep3_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, ep3_add, ep3_copy(), ep3_curve_get_ord(), ep3_dbl, ep3_norm(), ep3_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_EP_TABLE_COMBD, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep3_mul_pre_lwnaf()
void ep3_mul_pre_lwnaf (ep3_t * t, const ep3_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the w-(T)NAF method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 372 of file relic_ep3_mul_fix.c.
References ep3_tab(), and RLC_DEPTH.
ep3_mul_fix_basic()
void ep3_mul_fix_basic (ep3_t r, const ep3_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the binary method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 114 of file relic_ep3_mul_fix.c.
References bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_new, bn_null, ep3_add, ep3_curve_get_ord(), ep3_norm(), ep3_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep3_mul_fix_yaowi()
void ep3_mul_fix_yaowi (ep3_t r, const ep3_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and Yao's windowing method
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
ep3_mul_fix_nafwi()
void ep3_mul_fix_nafwi (ep3_t r, const ep3_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the w-(T)NAF method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
ep3_mul_fix_combs()
void ep3_mul_fix_combs (ep3_t r, const ep3_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the single-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 193 of file relic_ep3_mul_fix.c.
References bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_new, bn_null, ep3_add, ep3_copy(), ep3_curve_get_ord(), ep3_dbl, ep3_norm(), ep3_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep3_mul_fix_combd()
void ep3_mul_fix_combd (ep3_t r, const ep3_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the double-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 307 of file relic_ep3_mul_fix.c.
References bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_new, bn_null, ep3_add, ep3_curve_get_ord(), ep3_dbl, ep3_norm(), ep3_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep3_mul_fix_lwnaf()
void ep3_mul_fix_lwnaf (ep3_t r, const ep3_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the w-(T)NAF method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 376 of file relic_ep3_mul_fix.c.
References bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, ep3_curve_get_ord(), ep3_mul_fix_plain(), ep3_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep3_mul_sim_basic()
void ep3_mul_sim_basic (ep3_t r, const ep3_t p, const bn_t k, const ep3_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using scalar multiplication and point addition.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 149 of file relic_ep3_mul_sim.c.
References ep3_add, ep3_free, ep3_mul, ep3_new, ep3_norm(), ep3_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep3_mul_sim_trick()
void ep3_mul_sim_trick (ep3_t r, const ep3_t p, const bn_t k, const ep3_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using shamir's trick.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 174 of file relic_ep3_mul_sim.c.
References bn_free, bn_is_zero(), bn_new, bn_null, bn_rec_win(), bn_sign(), ep3_add, ep3_copy(), ep3_curve_get_ord(), ep3_dbl, ep3_free, ep3_is_infty(), ep3_mul, ep3_neg(), ep3_new, ep3_norm(), ep3_norm_sim(), ep3_null, ep3_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_CEIL, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
ep3_mul_sim_inter()
void ep3_mul_sim_inter (ep3_t r, const ep3_t p, const bn_t k, const ep3_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using interleaving of NAFs.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 267 of file relic_ep3_mul_sim.c.
References bn_is_zero(), ep3_is_infty(), ep3_mul, and ep3_mul_sim_plain().
ep3_mul_sim_joint()
void ep3_mul_sim_joint (ep3_t r, const ep3_t p, const bn_t k, const ep3_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using Solinas' Joint Sparse Form.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 285 of file relic_ep3_mul_sim.c.
References bn_bits(), bn_is_zero(), bn_rec_jsf(), bn_sign(), ep3_add, ep3_copy(), ep3_dbl, ep3_free, ep3_is_infty(), ep3_mul, ep3_neg(), ep3_new, ep3_norm(), ep3_norm_sim(), ep3_null, ep3_set_infty(), ep3_sub(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, and RLC_TRY.
ep3_mul_sim_lot()
void ep3_mul_sim_lot (ep3_t r, const ep3_t p[], const bn_t k[], int n)
Multiplies simultaneously elements from a prime elliptic curve. Computes R = \Sum_i=0..n k_iP_i.
Parameters
[out] r - the result.
[in] p - the points to multiply.
[in] k - the integer scalars.
[in] n - the number of elements to multiply.
Definition at line 426 of file relic_ep3_mul_sim.c.
References bn_free, bn_new, bn_null, bn_rec_frb(), bn_rec_naf(), bn_sign(), ep3_add, ep3_copy(), ep3_dbl, ep3_frb(), ep3_free, ep3_neg(), ep3_new, ep3_norm(), ep3_null, ep3_set_infty(), ep3_sub(), EP_BN, ep_curve_get_ord(), ep_curve_is_pairf(), ERR_CAUGHT, fp_prime_get_par(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_FREE, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and util_bits_dig().
ep3_mul_sim_gen()
void ep3_mul_sim_gen (ep3_t r, const bn_t k, const ep3_t q, const bn_t m)
Multiplies and adds the generator and a prime elliptic curve point simultaneously. Computes R = [k]G + [l]Q.
Parameters
[out] r - the result.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 360 of file relic_ep3_mul_sim.c.
References bn_is_zero(), ep3_curve_get_gen(), ep3_curve_get_tab(), ep3_free, ep3_is_infty(), ep3_mul, ep3_mul_gen(), ep3_mul_sim, ep3_mul_sim_plain(), ep3_new, ep3_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep3_mul_sim_dig()
void ep3_mul_sim_dig (ep3_t r, const ep3_t p[], const dig_t k[], size_t len)
Multiplies prime elliptic curve points by small scalars. Computes R = \sum k_iP_i.
Parameters
[out] r - the result.
[in] p - the points to multiply.
[in] k - the small scalars.
[in] len - the number of points to multiply.
Definition at line 392 of file relic_ep3_mul_sim.c.
References ep3_add, ep3_dbl, ep3_free, ep3_new, ep3_norm(), ep3_null, ep3_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_MAX, RLC_THROW, RLC_TRY, and util_bits_dig().
ep3_norm()
void ep3_norm (ep3_t r, const ep3_t p)
Converts a point to affine coordinates.
Parameters
[out] r - the result.
[in] p - the point to convert.
Definition at line 97 of file relic_ep3_norm.c.
References BASIC, ep3_copy(), ep3_is_infty(), ep3_norm_imp(), and ep3_set_infty().
Referenced by ep3_curve_set(), ep3_mul_basic(), ep3_mul_cof_fm18(), ep3_mul_cof_k18(), ep3_mul_cof_sg18(), ep3_mul_dig(), ep3_mul_fix_basic(), ep3_mul_fix_combd(), ep3_mul_fix_combs(), ep3_mul_fix_plain(), ep3_mul_gls_imp(), ep3_mul_monty(), ep3_mul_naf_imp(), ep3_mul_pre_combd(), ep3_mul_pre_combs(), ep3_mul_reg_gls(), ep3_mul_reg_imp(), ep3_mul_sim_basic(), ep3_mul_sim_dig(), ep3_mul_sim_joint(), ep3_mul_sim_lot(), ep3_mul_sim_plain(), ep3_mul_sim_trick(), ep3_mul_slide(), ep3_on_curve(), ep3_size_bin(), ep3_tab(), ep3_write_bin(), pp_map_oatep_k18(), pp_map_sim_oatep_k18(), pp_map_sim_tatep_k18(), pp_map_sim_weilp_k18(), pp_map_tatep_k18(), and pp_map_weilp_k18().
ep3_norm_sim()
void ep3_norm_sim (ep3_t * r, const ep3_t * t, int n)
Converts multiple points to affine coordinates.
Parameters
[out] r - the result.
[in] t - the points to convert.
[in] n - the number of points.
Definition at line 113 of file relic_ep3_norm.c.
References ep3_is_infty(), ep3_norm_imp(), ERR_CAUGHT, ERR_NO_MEMORY, fp3_copy(), fp3_free, fp3_inv_sim(), fp3_new, fp3_null, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by ep3_mul_gls_imp(), ep3_mul_reg_gls(), ep3_mul_sim_joint(), ep3_mul_sim_trick(), ep3_mul_slide(), and ep3_tab().
ep3_map()
void ep3_map (ep3_t p, const uint8_t * msg, size_t len)
Maps a byte array to a point in an elliptic curve over a cubic extension.
Parameters
[out] p - the result.
[in] msg - the byte array to map.
[in] len - the array length in bytes.
Definition at line 40 of file relic_ep3_map.c.
References BASIC, bn_free, bn_get_bit(), bn_new, bn_null, bn_read_bin(), core_get(), _ctx_t::ep3_b, ep3_mul_cof(), ep3_rhs(), ep3_set_infty(), _ctx_t::ep_map_c, ep_param_level(), ERR_CAUGHT, ERR_NO_VALID, fp3_add, fp3_copy(), fp3_copy_sec(), fp3_dbl, fp3_free, fp3_inv(), fp3_is_sqr(), fp3_is_zero(), fp3_mul, fp3_neg(), fp3_new, fp3_null, fp3_set_dig(), fp3_sqr, fp3_srt(), fp3_sub, fp_is_zero(), fp_mul, FP_PRIME, fp_prime_back(), fp_prime_conv(), md_xmd, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
ep3_frb()
void ep3_frb (ep3_t r, const ep3_t p, int i)
Computes a power of the Gailbraith-Lin-Scott homomorphism of a point represented in affine coordinates on a twisted elliptic curve over a cubic exension. That is, Psi^i(P) = Twist(P)(Frob^i(unTwist(P)). On the trace-zero group of a cubic twist, consists of a power of the Frobenius map of a point represented in affine coordinates in an elliptic curve over a cubic exension. Computes Frob^i(P) = (p^i)P.
Parameters
[out] r - the result in affine coordinates.
[in] p - a point in affine coordinates.
[in] i - the power of the Frobenius map.
Definition at line 39 of file relic_ep3_frb.c.
References core_get(), ep3_copy(), _ctx_t::ep3_frb, fp3_frb(), and fp3_mul.
Referenced by ep3_mul_cof_fm18(), ep3_mul_cof_k18(), ep3_mul_cof_sg18(), ep3_mul_sim_lot(), ep3_psi(), pp_fin_k18_oatep(), pp_map_sim_tatep_k18(), pp_map_sim_weilp_k18(), pp_map_tatep_k18(), and pp_map_weilp_k18().
ep3_pck()
void ep3_pck (ep3_t r, const ep3_t p)
Compresses a point in an elliptic curve over a cubic extension.
Parameters
[out] r - the result.
[in] p - the point to compress.
ep3_upk()
int ep3_upk (ep3_t r, const ep3_t p)
Decompresses a point in an elliptic curve over a cubic extension.
Parameters
[out] r - the result.
[in] p - the point to decompress.
Returns
if the decompression was successful
ep4_curve_init()
void ep4_curve_init (void)
Initializes the elliptic curve over quartic extension.
Definition at line 307 of file relic_ep4_curve.c.
References bn_make(), core_get(), _ctx_t::ep4_a, _ctx_t::ep4_b, _ctx_t::ep4_g, _ctx_t::ep4_h, ep4_new, _ctx_t::ep4_pre, _ctx_t::ep4_ptr, _ctx_t::ep4_r, fp4_new, RLC_EP_TABLE, RLC_FP_DIGS, ep4_st::x, ep4_st::y, and ep4_st::z.
Referenced by pp_map_init().
ep4_curve_clean()
void ep4_curve_clean (void)
Finalizes the elliptic curve over quartic extension.
Definition at line 335 of file relic_ep4_curve.c.
References bn_clean(), core_get(), _ctx_t::ep4_a, _ctx_t::ep4_b, ep4_free, _ctx_t::ep4_g, _ctx_t::ep4_h, _ctx_t::ep4_pre, _ctx_t::ep4_r, fp4_free, RLC_EP_TABLE, ep4_st::x, ep4_st::y, and ep4_st::z.
Referenced by pp_map_clean().
ep4_curve_get_a()
fp2_t * ep4_curve_get_a (void)
Returns the 'a' coefficient of the currently configured elliptic curve.
Returns
the 'a' coefficient of the elliptic curve.
Definition at line 430 of file relic_ep4_curve.c.
References core_get(), and _ctx_t::ep4_a.
Referenced by ep4_map(), and ep4_rhs().
ep4_curve_get_b()
fp2_t * ep4_curve_get_b (void)
Returns the 'b' coefficient of the currently configured elliptic curve.
Parameters
[out] b - the 'b' coefficient of the elliptic curve.
Definition at line 434 of file relic_ep4_curve.c.
References core_get(), and _ctx_t::ep4_b.
Referenced by ep4_rhs(), and pp_dbl_k24_projc().
ep4_curve_opt_a()
int ep4_curve_opt_a (void)
Returns a optimization identifier based on the 'a' coefficient of the curve.
Returns
the optimization identifier.
Definition at line 353 of file relic_ep4_curve.c.
References core_get(), and _ctx_t::ep4_opt_a.
Referenced by ep4_rhs().
ep4_curve_opt_b()
int ep4_curve_opt_b (void)
Returns b optimization identifier based on the 'b' coefficient of the curve.
Returns
the optimization identifier.
Definition at line 357 of file relic_ep4_curve.c.
References core_get(), and _ctx_t::ep4_opt_b.
Referenced by ep4_curve_set_twist(), and ep4_rhs().
ep4_curve_mul_a()
void ep4_curve_mul_a (fp4_t c, const fp4_t a)
Multiplies a field element by the a-coefficient of the curve.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
Definition at line 361 of file relic_ep4_curve.c.
References core_get(), _ctx_t::ep4_a, ep4_curve_is_twist(), _ctx_t::ep4_opt_a, _ctx_t::ep_opt_a, fp4_copy(), fp4_dbl(), fp4_mul, fp4_mul_art(), fp4_mul_dig(), fp4_zero(), RLC_EP_MTYPE, RLC_ONE, RLC_TINY, RLC_TWO, and RLC_ZERO.
Referenced by pp_dbl_k16_projc_basic(), and pp_dbl_k16_projc_lazyr().
ep4_curve_mul_b()
void ep4_curve_mul_b (fp4_t c, const fp4_t a)
Multiplies a field element by the b-coefficient of the curve.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
Definition at line 402 of file relic_ep4_curve.c.
References core_get(), _ctx_t::ep4_b, _ctx_t::ep4_opt_b, fp4_copy(), fp4_mul, fp4_mul_dig(), fp4_zero(), RLC_ONE, RLC_TINY, and RLC_ZERO.
ep4_curve_is_twist()
int ep4_curve_is_twist (void)
Tests if the configured elliptic curve is a twist.
Returns
the type of the elliptic curve twist, 0 if non-twisted curve.
Definition at line 422 of file relic_ep4_curve.c.
References core_get(), and _ctx_t::ep4_is_twist.
Referenced by ep4_curve_mul_a(), pp_add_k16_basic(), pp_add_k16_projc_basic(), pp_add_k16_projc_lazyr(), pp_add_k24_basic(), pp_add_k24_projc(), pp_add_lit_k16(), pp_dbl_k16_basic(), pp_dbl_k16_projc_basic(), pp_dbl_k16_projc_lazyr(), pp_dbl_k24_basic(), pp_dbl_k24_projc(), and pp_dbl_lit_k16().
ep4_curve_get_gen()
void ep4_curve_get_gen (ep4_t g)
Returns the generator of the group of points in the elliptic curve.
Parameters
[out] g - the returned generator.
Definition at line 426 of file relic_ep4_curve.c.
References core_get(), and ep4_copy().
Referenced by ep4_mul_gen(), and ep4_mul_sim_gen().
ep4_curve_get_tab()
ep4_t * ep4_curve_get_tab (void)
Returns the precomputation table for the generator.
Returns
the table.
Definition at line 453 of file relic_ep4_curve.c.
References core_get(), and _ctx_t::ep4_ptr.
Referenced by ep4_curve_set(), ep4_curve_set_twist(), ep4_mul_gen(), and ep4_mul_sim_gen().
ep4_curve_get_ord()
void ep4_curve_get_ord (bn_t n)
Returns the order of the group of points in the elliptic curve.
Parameters
[out] n - the returned order.
Definition at line 438 of file relic_ep4_curve.c.
References bn_copy(), core_get(), _ctx_t::ep4_is_twist, _ctx_t::ep4_r, and ep_curve_get_ord().
Referenced by ep4_mul_fix_basic(), ep4_mul_fix_combd(), ep4_mul_fix_combs(), ep4_mul_gls_imp(), ep4_mul_monty(), ep4_mul_pre_basic(), ep4_mul_pre_combd(), ep4_mul_pre_combs(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), ep4_mul_sim_trick(), and ep4_rand().
ep4_curve_get_cof()
void ep4_curve_get_cof (bn_t h)
Returns the cofactor of the group order in the elliptic curve.
Parameters
[out] h - the returned cofactor.
Definition at line 447 of file relic_ep4_curve.c.
References bn_copy(), and core_get().
Referenced by ep4_mul_cof().
ep4_curve_set()
void ep4_curve_set (const fp4_t a, const fp4_t b, const ep4_t g, const bn_t r, const bn_t h)
Configures an elliptic curve over a quartic extension by its coefficients.
Parameters
[in] a - the 'a' coefficient of the curve.
[in] b - the 'b' coefficient of the curve.
[in] g - the generator.
[in] r - the order of the group of points.
[in] h - the cofactor of the group order.
Definition at line 592 of file relic_ep4_curve.c.
References bn_copy(), core_get(), _ctx_t::ep4_a, _ctx_t::ep4_b, ep4_curve_get_tab(), _ctx_t::ep4_g, _ctx_t::ep4_h, _ctx_t::ep4_is_twist, ep4_mul_pre, ep4_norm(), _ctx_t::ep4_r, and fp4_copy().
ep4_curve_set_twist()
void ep4_curve_set_twist (int type)
Configures an elliptic curve by twisting the curve over the base prime field.
Parameters
- the type of twist (multiplicative or divisive)
Definition at line 463 of file relic_ep4_curve.c.
References AFG16_P510, AFG16_P766, ASSIGN, B24_P315, B24_P317, B24_P509, BASIC, bn_copy(), bn_free, bn_new, bn_null, core_get(), detect_opt(), _ctx_t::ep4_a, _ctx_t::ep4_b, ep4_copy(), ep4_curve_get_tab(), ep4_curve_opt_b(), ep4_free, _ctx_t::ep4_g, _ctx_t::ep4_h, _ctx_t::ep4_is_twist, ep4_mul_pre, ep4_new, ep4_null, _ctx_t::ep4_opt_a, _ctx_t::ep4_opt_b, _ctx_t::ep4_r, ep_param_get(), ERR_CAUGHT, ERR_NO_VALID, FM16_P765, fp2_is_zero(), _ctx_t::fp2_p2, fp2_zero(), fp4_copy(), fp4_free, fp4_inv(), fp4_new, fp4_null, _ctx_t::fp4_p1, fp4_set_dig(), fp4_zero(), fp_copy(), _ctx_t::frb4, K16_P330, K16_P766, pc_core_calc(), RLC_CATCH_ANY, RLC_EP_DTYPE, RLC_EP_MTYPE, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, RLC_TRY, and RLC_ZERO.
Referenced by ep_param_set_any_pairf().
ep4_is_infty()
int ep4_is_infty (const ep4_t p)
Tests if a point on an elliptic curve is at the infinity.
Parameters
[in] p - the point to test.
Returns
1 if the point is at infinity, 0 otherise.
Definition at line 39 of file relic_ep4_util.c.
References fp4_is_zero().
Referenced by ep4_add_basic(), ep4_add_jacob(), ep4_add_projc(), ep4_add_slp_basic(), ep4_cmp(), ep4_dbl_basic(), ep4_dbl_jacob(), ep4_dbl_projc(), ep4_dbl_slp_basic(), ep4_mul_basic(), ep4_mul_dig(), ep4_mul_lwnaf(), ep4_mul_lwreg(), ep4_mul_monty(), ep4_mul_sim_gen(), ep4_mul_sim_inter(), ep4_mul_sim_joint(), ep4_mul_sim_trick(), ep4_mul_slide(), ep4_neg(), ep4_norm(), ep4_norm_sim(), ep4_on_curve(), ep4_psi(), ep4_size_bin(), ep4_write_bin(), pp_map_k24(), pp_map_oatep_k16(), pp_map_sim_k24(), pp_map_sim_oatep_k16(), pp_map_sim_tatep_k16(), pp_map_sim_weilp_k16(), pp_map_tatep_k16(), pp_map_weilp_k16(), pp_norm_k16(), and pp_norm_k24().
ep4_set_infty()
void ep4_set_infty (ep4_t p)
Assigns an elliptic curve point to the point at infinity.
Parameters
[out] p - the point to assign.
Definition at line 43 of file relic_ep4_util.c.
References BASIC, and fp4_zero().
Referenced by ep4_dbl_basic(), ep4_dbl_jacob(), ep4_dbl_projc(), ep4_dbl_slp_basic(), ep4_map(), ep4_mul_basic(), ep4_mul_dig(), ep4_mul_fix_basic(), ep4_mul_fix_combd(), ep4_mul_fix_combs(), ep4_mul_fix_ordin(), ep4_mul_gen(), ep4_mul_gls_imp(), ep4_mul_lwnaf(), ep4_mul_lwreg(), ep4_mul_monty(), ep4_mul_naf_imp(), ep4_mul_pre_combd(), ep4_mul_pre_combs(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), ep4_mul_sim_dig(), ep4_mul_sim_joint(), ep4_mul_sim_lot(), ep4_mul_sim_plain(), ep4_mul_sim_trick(), ep4_mul_slide(), ep4_neg(), ep4_norm(), ep4_psi(), ep4_read_bin(), ep4_sub(), pp_norm_k16(), and pp_norm_k24().
ep4_copy()
void ep4_copy (ep4_t r, const ep4_t p)
Copies the second argument to the first argument.
Parameters
[out] q - the result.
[in] p - the elliptic curve point to copy.
Definition at line 50 of file relic_ep4_util.c.
References fp4_copy().
Referenced by ep4_add_basic(), ep4_add_jacob(), ep4_add_projc(), ep4_add_slp_basic(), ep4_blind(), ep4_cmp(), ep4_curve_get_gen(), ep4_curve_set_twist(), ep4_frb(), ep4_mul_dig(), ep4_mul_fix_combs(), ep4_mul_pre_basic(), ep4_mul_pre_combd(), ep4_mul_pre_combs(), ep4_mul_pre_ordin(), ep4_mul_reg_gls(), ep4_mul_sim_joint(), ep4_mul_sim_lot(), ep4_mul_sim_trick(), ep4_mul_slide(), ep4_norm(), ep4_norm_imp(), ep4_psi(), ep4_tab(), pp_add_k16_basic(), pp_add_k24_basic(), pp_dbl_k16_basic(), pp_dbl_k24_basic(), pp_mil_k16(), pp_mil_k24(), pp_norm_k16(), and pp_norm_k24().
ep4_cmp()
int ep4_cmp (const ep4_t p, const ep4_t q)
Compares two elliptic curve points.
Parameters
[in] p - the first elliptic curve point.
[in] q - the second elliptic curve point.
Returns
RLC_EQ if p == q and RLC_NE if p != q.
Definition at line 39 of file relic_ep4_cmp.c.
References ep4_copy(), ep4_free, ep4_is_infty(), ep4_new, ep4_null, ERR_CAUGHT, fp4_cmp(), fp4_mul, fp4_sqr, JACOB, PROJC, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_NE, RLC_THROW, and RLC_TRY.
ep4_rand()
void ep4_rand (ep4_t p)
Assigns a random value to an elliptic curve point.
Parameters
[out] p - the elliptic curve point to assign.
Definition at line 57 of file relic_ep4_util.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), ep4_curve_get_ord(), ep4_mul_gen(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep4_blind()
void ep4_blind (ep4_t r, const ep4_t p)
Randomizes coordinates of an elliptic curve point.
Parameters
[out] r - the blinded prime elliptic curve point.
[in] p - the prime elliptic curve point to blind.
Definition at line 81 of file relic_ep4_util.c.
References ep4_copy(), ERR_CAUGHT, fp4_free, fp4_mul, fp4_new, fp4_null, fp4_rand(), fp4_sqr, JACOB, PROJC, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep4_mul_monty().
ep4_rhs()
void ep4_rhs (fp4_t rhs, const fp4_t x)
Computes the right-hand side of the elliptic curve equation at the x-coordinate of a certain prime elliptic curve point.
Parameters
[out] rhs - the result.
[in] x - the x-coordinate of the point.
Definition at line 112 of file relic_ep4_util.c.
References ep4_curve_get_a(), ep4_curve_get_b(), ep4_curve_opt_a(), ep4_curve_opt_b(), ERR_CAUGHT, fp4_add(), fp4_copy(), fp4_free, fp4_mul, fp4_mul_dig(), fp4_new, fp4_null, fp4_sqr, fp_add_dig(), fp_sub_dig(), RLC_CATCH_ANY, RLC_FINALLY, RLC_MIN3, RLC_ONE, RLC_THROW, RLC_TINY, RLC_TRY, RLC_TWO, and RLC_ZERO.
Referenced by ep4_map(), and ep4_on_curve().
ep4_on_curve()
int ep4_on_curve (const ep4_t p)
Tests if a point is in the curve.
Parameters
[in] p - the point to test.
Definition at line 176 of file relic_ep4_util.c.
References ep4_free, ep4_is_infty(), ep4_new, ep4_norm(), ep4_null, ep4_rhs(), ERR_CAUGHT, fp4_cmp(), fp4_sqr, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep4_read_bin().
ep4_tab()
void ep4_tab (ep4_t * t, const ep4_t p, int w)
Builds a precomputation table for multiplying a random prime elliptic point.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
[in] w - the window width.
Definition at line 199 of file relic_ep4_util.c.
References ep4_add, ep4_copy(), ep4_dbl, ep4_norm(), and ep4_norm_sim().
Referenced by ep4_mul_gls_imp(), ep4_mul_naf_imp(), ep4_mul_reg_imp(), and ep4_mul_sim_plain().
ep4_print()
void ep4_print (const ep4_t p)
Prints an elliptic curve point.
Parameters
[in] p - the elliptic curve point to print.
Definition at line 220 of file relic_ep4_util.c.
References fp4_print().
ep4_size_bin()
size_t ep4_size_bin (const ep4_t a, int pack)
Returns the number of bytes necessary to store a prime elliptic curve point over a quartic extension with optional point compression.
Parameters
[in] a - the prime field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 226 of file relic_ep4_util.c.
References ep4_free, ep4_is_infty(), ep4_new, ep4_norm(), ep4_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.
ep4_read_bin()
void ep4_read_bin (ep4_t a, const uint8_t * bin, size_t len)
Reads a prime elliptic curve point over a quartic extension from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_VALID - if the encoded point is invalid.
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 252 of file relic_ep4_util.c.
References BASIC, ep4_on_curve(), ep4_set_infty(), ERR_NO_BUFFER, ERR_NO_VALID, fp4_read_bin(), fp4_set_dig(), RLC_FP_BYTES, and RLC_THROW.
ep4_write_bin()
void ep4_write_bin (uint8_t * bin, size_t len, const ep4_t a, int pack)
Writes a prime elliptic curve pointer over a quartic extension to a byte vector in big-endian format with optional point compression.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the prime elliptic curve point to write.
[in] pack - the flag to indicate compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 286 of file relic_ep4_util.c.
References ep4_free, ep4_is_infty(), ep4_new, ep4_norm(), ep4_null, ERR_CAUGHT, ERR_NO_BUFFER, fp4_write_bin(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.
ep4_neg()
void ep4_neg (ep4_t r, const ep4_t p)
Negates a point represented in affine coordinates in an elliptic curve over a quartic extension.
Parameters
[out] r - the result.
[out] p - the point to negate.
Definition at line 39 of file relic_ep4_neg.c.
References ep4_is_infty(), ep4_set_infty(), fp4_copy(), and fp4_neg().
Referenced by ep4_mul_basic(), ep4_mul_fix_combd(), ep4_mul_fix_ordin(), ep4_mul_gls_imp(), ep4_mul_naf_imp(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), ep4_mul_sim_joint(), ep4_mul_sim_lot(), ep4_mul_sim_trick(), ep4_mul_slide(), ep4_psi(), ep4_sub(), pp_map_oatep_k16(), pp_map_sim_oatep_k16(), pp_mil_k16(), pp_mil_k24(), and pp_mil_lit_k16().
ep4_add_basic()
void ep4_add_basic (ep4_t r, const ep4_t p, const ep4_t q)
Adds to points represented in affine coordinates in an elliptic curve over a quartic extension.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 109 of file relic_ep4_add.c.
References ep4_copy(), and ep4_is_infty().
ep4_add_slp_basic()
void ep4_add_slp_basic (ep4_t r, fp4_t s, const ep4_t p, const ep4_t q)
Adds to points represented in affine coordinates in an elliptic curve over a quartic extension and returns the computed slope.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 123 of file relic_ep4_add.c.
References ep4_copy(), and ep4_is_infty().
Referenced by pp_add_k16_basic(), and pp_add_k24_basic().
ep4_add_projc()
void ep4_add_projc (ep4_t r, const ep4_t p, const ep4_t q)
Adds two points represented in projective coordinates in an elliptic curve over a quartic extension.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 141 of file relic_ep4_add.c.
References ep4_copy(), and ep4_is_infty().
ep4_add_jacob()
void ep4_add_jacob (ep4_t r, const ep4_t p, const ep4_t q)
Adds two points represented in Jacobian coordinates in an elliptic curve over a quartic extension.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 159 of file relic_ep4_add.c.
References ep4_copy(), and ep4_is_infty().
ep4_sub()
void ep4_sub (ep4_t r, const ep4_t p, const ep4_t q)
Subtracts a point in an elliptic curve over a quartic extension from another.
Parameters
[out] r - the result.
[in] p - the first point.
[in] q - the point to subtract.
Definition at line 175 of file relic_ep4_add.c.
References ep4_add, ep4_free, ep4_neg(), ep4_new, ep4_null, ep4_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep4_mul_basic(), ep4_mul_cof_afg16(), ep4_mul_cof_b24(), ep4_mul_cof_fm16(), ep4_mul_cof_k16(), ep4_mul_dig(), ep4_mul_fix_ordin(), ep4_mul_gls_imp(), ep4_mul_naf_imp(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), ep4_mul_sim_joint(), ep4_mul_sim_lot(), ep4_mul_sim_plain(), and ep4_psi().
ep4_dbl_basic()
void ep4_dbl_basic (ep4_t r, const ep4_t p)
Doubles a point represented in affine coordinates in an elliptic curve over a quartic extension.
Parameters
[out] r - the result.
[int] p - the point to double.
Definition at line 86 of file relic_ep4_dbl.c.
References ep4_is_infty(), and ep4_set_infty().
ep4_dbl_slp_basic()
void ep4_dbl_slp_basic (ep4_t r, fp4_t s, const ep4_t p)
Doubles a point represented in affine coordinates in an elliptic curve over a quartic extension and returns the computed slope.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the point to double.
Definition at line 94 of file relic_ep4_dbl.c.
References ep4_is_infty(), and ep4_set_infty().
Referenced by pp_dbl_k16_basic(), and pp_dbl_k24_basic().
ep4_dbl_projc()
void ep4_dbl_projc (ep4_t r, const ep4_t p)
Doubles a point represented in projective coordinates in an elliptic curve over a quartic extension.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 107 of file relic_ep4_dbl.c.
References ep4_is_infty(), and ep4_set_infty().
ep4_dbl_jacob()
void ep4_dbl_jacob (ep4_t r, const ep4_t p)
Doubles a point represented in Jacobian coordinates in an elliptic curve over a quartic extension.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 120 of file relic_ep4_dbl.c.
References ep4_is_infty(), and ep4_set_infty().
ep4_mul_basic()
void ep4_mul_basic (ep4_t r, const ep4_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the binary method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 465 of file relic_ep4_mul.c.
References bn_bits(), bn_is_zero(), bn_rec_naf(), bn_sign(), ep4_add, ep4_dbl, ep4_free, ep4_is_infty(), ep4_mul_dig(), ep4_neg(), ep4_new, ep4_norm(), ep4_null, ep4_set_infty(), ep4_sub(), ERR_CAUGHT, ERR_NO_BUFFER, RLC_ALLOCA, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by ep4_mul_cof_afg16(), ep4_mul_cof_b24(), ep4_mul_cof_fm16(), and ep4_mul_cof_k16().
ep4_mul_slide()
void ep4_mul_slide (ep4_t r, const ep4_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the sliding window method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 523 of file relic_ep4_mul.c.
References bn_is_zero(), bn_rec_slw(), bn_sign(), ep4_add, ep4_copy(), ep4_dbl, ep4_free, ep4_is_infty(), ep4_neg(), ep4_new, ep4_norm(), ep4_norm_sim(), ep4_null, ep4_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_THROW, RLC_TRY, RLC_WIDTH, and util_bits_dig().
ep4_mul_monty()
void ep4_mul_monty (ep4_t r, const ep4_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the constant-time Montgomery ladder point multiplication method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 593 of file relic_ep4_mul.c.
References bn_abs(), bn_add(), bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_new, bn_null, dv_swap_sec(), ep4_add, ep4_blind(), ep4_curve_get_ord(), ep4_dbl, ep4_free, ep4_is_infty(), ep4_new, ep4_norm(), ep4_null, ep4_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_MAX, RLC_SEL, RLC_THROW, and RLC_TRY.
ep4_mul_lwnaf()
void ep4_mul_lwnaf (ep4_t r, const ep4_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the w-NAF method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 681 of file relic_ep4_mul.c.
References bn_is_zero(), ep4_is_infty(), ep4_mul_gls_imp(), ep4_mul_naf_imp(), ep4_set_infty(), and ep_curve_is_endom().
ep4_mul_lwreg()
void ep4_mul_lwreg (ep4_t r, const ep4_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using a regular method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 703 of file relic_ep4_mul.c.
References bn_is_zero(), ep4_is_infty(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), ep4_set_infty(), and ep_curve_is_endom().
ep4_mul_gen()
void ep4_mul_gen (ep4_t r, const bn_t k)
Multiplies the generator of an elliptic curve over a qaudratic extension.
Parameters
[out] r - the result.
[in] k - the integer.
Definition at line 723 of file relic_ep4_mul.c.
References bn_is_zero(), ep4_curve_get_gen(), ep4_curve_get_tab(), ep4_free, ep4_mul, ep4_mul_fix, ep4_new, ep4_null, ep4_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep4_mul_sim_gen(), and ep4_rand().
ep4_mul_dig()
void ep4_mul_dig (ep4_t r, const ep4_t p, const dig_t k)
Multiplies a prime elliptic point by a small integer.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 750 of file relic_ep4_mul.c.
References bn_free, bn_new, bn_null, bn_rec_naf(), bn_set_dig(), ep4_add, ep4_copy(), ep4_dbl, ep4_free, ep4_is_infty(), ep4_new, ep4_norm(), ep4_null, ep4_set_infty(), ep4_sub(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep4_mul_basic(), and ep4_mul_cof_k16().
ep4_mul_cof()
void ep4_mul_cof (ep4_t r, const ep4_t p)
Multiplies a point in an elliptic curve over a quartic extension field by the curve cofactor or a small multiple for which a short vector exists. In short, it takes a point in the curve to the large prime-order subgroup.
Parameters
[out] R - the result.
[in] P - the point to multiply.
Definition at line 350 of file relic_ep4_mul_cof.c.
References bn_free, bn_null, ep4_curve_get_cof(), ep4_mul_big, ep4_mul_cof_afg16(), ep4_mul_cof_b24(), ep4_mul_cof_fm16(), ep4_mul_cof_k16(), EP_AFG16, EP_B24, ep_curve_is_pairf(), EP_FM16, EP_K16, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep4_map().
ep4_mul_pre_basic()
void ep4_mul_pre_basic (ep4_t * t, const ep4_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the binary method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 119 of file relic_ep4_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, ep4_copy(), ep4_curve_get_ord(), ep4_dbl, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep4_mul_pre_yaowi()
void ep4_mul_pre_yaowi (ep4_t * t, const ep4_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using Yao's windowing method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
ep4_mul_pre_nafwi()
void ep4_mul_pre_nafwi (ep4_t * t, const ep4_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the NAF windowing method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
ep4_mul_pre_combs()
void ep4_mul_pre_combs (ep4_t * t, const ep4_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the single-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 179 of file relic_ep4_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, ep4_add, ep4_copy(), ep4_curve_get_ord(), ep4_dbl, ep4_norm(), ep4_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_EP_TABLE_COMBS, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep4_mul_pre_combd()
void ep4_mul_pre_combd (ep4_t * t, const ep4_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the double-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 286 of file relic_ep4_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, ep4_add, ep4_copy(), ep4_curve_get_ord(), ep4_dbl, ep4_norm(), ep4_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_EP_TABLE_COMBD, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep4_mul_pre_lwnaf()
void ep4_mul_pre_lwnaf (ep4_t * t, const ep4_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the w-(T)NAF method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 399 of file relic_ep4_mul_fix.c.
References ep4_mul_pre_ordin().
ep4_mul_fix_basic()
void ep4_mul_fix_basic (ep4_t r, const ep4_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the binary method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 142 of file relic_ep4_mul_fix.c.
References bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_new, bn_null, ep4_add, ep4_curve_get_ord(), ep4_norm(), ep4_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep4_mul_fix_yaowi()
void ep4_mul_fix_yaowi (ep4_t r, const ep4_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and Yao's windowing method
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
ep4_mul_fix_nafwi()
void ep4_mul_fix_nafwi (ep4_t r, const ep4_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the w-(T)NAF method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
ep4_mul_fix_combs()
void ep4_mul_fix_combs (ep4_t r, const ep4_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the single-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 221 of file relic_ep4_mul_fix.c.
References bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_new, bn_null, ep4_add, ep4_copy(), ep4_curve_get_ord(), ep4_dbl, ep4_norm(), ep4_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep4_mul_fix_combd()
void ep4_mul_fix_combd (ep4_t r, const ep4_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the double-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 335 of file relic_ep4_mul_fix.c.
References bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_new, bn_null, bn_sign(), ep4_add, ep4_curve_get_ord(), ep4_dbl, ep4_neg(), ep4_norm(), ep4_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
ep4_mul_fix_lwnaf()
void ep4_mul_fix_lwnaf (ep4_t r, const ep4_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the w-(T)NAF method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 403 of file relic_ep4_mul_fix.c.
References ep4_mul_fix_ordin().
ep4_mul_sim_basic()
void ep4_mul_sim_basic (ep4_t r, const ep4_t p, const bn_t k, const ep4_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using scalar multiplication and point addition.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 150 of file relic_ep4_mul_sim.c.
References ep4_add, ep4_free, ep4_mul, ep4_new, ep4_norm(), ep4_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep4_mul_sim_trick()
void ep4_mul_sim_trick (ep4_t r, const ep4_t p, const bn_t k, const ep4_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using shamir's trick.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 175 of file relic_ep4_mul_sim.c.
References bn_free, bn_is_zero(), bn_new, bn_null, bn_rec_win(), bn_sign(), ep4_add, ep4_copy(), ep4_curve_get_ord(), ep4_dbl, ep4_free, ep4_is_infty(), ep4_mul, ep4_neg(), ep4_new, ep4_norm(), ep4_norm_sim(), ep4_null, ep4_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_CEIL, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
ep4_mul_sim_inter()
void ep4_mul_sim_inter (ep4_t r, const ep4_t p, const bn_t k, const ep4_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using interleaving of NAFs.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 269 of file relic_ep4_mul_sim.c.
References bn_is_zero(), ep4_is_infty(), ep4_mul, and ep4_mul_sim_plain().
ep4_mul_sim_joint()
void ep4_mul_sim_joint (ep4_t r, const ep4_t p, const bn_t k, const ep4_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using Solinas' Joint Sparse Form.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 287 of file relic_ep4_mul_sim.c.
References bn_bits(), bn_is_zero(), bn_rec_jsf(), bn_sign(), ep4_add, ep4_copy(), ep4_dbl, ep4_free, ep4_is_infty(), ep4_mul, ep4_neg(), ep4_new, ep4_norm(), ep4_norm_sim(), ep4_null, ep4_set_infty(), ep4_sub(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, and RLC_TRY.
ep4_mul_sim_lot()
void ep4_mul_sim_lot (ep4_t r, const ep4_t p[], const bn_t k[], size_t n)
Multiplies simultaneously elements from a prime elliptic curve. Computes R = \Sum_i=0..n k_iP_i.
Parameters
[out] r - the result.
[in] p - the points to multiply.
[in] k - the integer scalars.
[in] n - the number of elements to multiply.
Definition at line 428 of file relic_ep4_mul_sim.c.
References bn_free, bn_new, bn_null, bn_rec_frb(), bn_rec_naf(), bn_sign(), ep4_add, ep4_copy(), ep4_dbl, ep4_frb(), ep4_free, ep4_neg(), ep4_new, ep4_norm(), ep4_null, ep4_set_infty(), ep4_sub(), EP_BN, ep_curve_get_ord(), ep_curve_is_pairf(), ERR_CAUGHT, fp_prime_get_par(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_FREE, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and util_bits_dig().
ep4_mul_sim_gen()
void ep4_mul_sim_gen (ep4_t r, const bn_t k, const ep4_t q, const bn_t m)
Multiplies and adds the generator and a prime elliptic curve point simultaneously. Computes R = [k]G + [l]Q.
Parameters
[out] r - the result.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 362 of file relic_ep4_mul_sim.c.
References bn_is_zero(), ep4_curve_get_gen(), ep4_curve_get_tab(), ep4_free, ep4_is_infty(), ep4_mul, ep4_mul_gen(), ep4_mul_sim, ep4_mul_sim_plain(), ep4_new, ep4_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep4_mul_sim_dig()
void ep4_mul_sim_dig (ep4_t r, const ep4_t p[], const dig_t k[], size_t len)
Multiplies prime elliptic curve points by small scalars. Computes R = \sum k_iP_i.
Parameters
[out] r - the result.
[in] p - the points to multiply.
[in] k - the small scalars.
[in] len - the number of points to multiply.
Definition at line 394 of file relic_ep4_mul_sim.c.
References ep4_add, ep4_dbl, ep4_free, ep4_new, ep4_norm(), ep4_null, ep4_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_MAX, RLC_THROW, RLC_TRY, and util_bits_dig().
ep4_norm()
void ep4_norm (ep4_t r, const ep4_t p)
Converts a point to affine coordinates.
Parameters
[out] r - the result.
[in] p - the point to convert.
Definition at line 97 of file relic_ep4_norm.c.
References BASIC, ep4_copy(), ep4_is_infty(), ep4_norm_imp(), and ep4_set_infty().
Referenced by ep4_curve_set(), ep4_mul_basic(), ep4_mul_cof_afg16(), ep4_mul_cof_b24(), ep4_mul_cof_fm16(), ep4_mul_cof_k16(), ep4_mul_dig(), ep4_mul_fix_basic(), ep4_mul_fix_combd(), ep4_mul_fix_combs(), ep4_mul_fix_ordin(), ep4_mul_gls_imp(), ep4_mul_monty(), ep4_mul_naf_imp(), ep4_mul_pre_combd(), ep4_mul_pre_combs(), ep4_mul_pre_ordin(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), ep4_mul_sim_basic(), ep4_mul_sim_dig(), ep4_mul_sim_joint(), ep4_mul_sim_lot(), ep4_mul_sim_plain(), ep4_mul_sim_trick(), ep4_mul_slide(), ep4_on_curve(), ep4_size_bin(), ep4_tab(), ep4_write_bin(), pp_map_k24(), pp_map_oatep_k16(), pp_map_sim_k24(), pp_map_sim_oatep_k16(), pp_map_sim_tatep_k16(), pp_map_sim_weilp_k16(), pp_map_tatep_k16(), and pp_map_weilp_k16().
ep4_norm_sim()
void ep4_norm_sim (ep4_t * r, const ep4_t * t, int n)
Converts multiple points to affine coordinates.
Parameters
[out] r - the result.
[in] t - the points to convert.
[in] n - the number of points.
Definition at line 113 of file relic_ep4_norm.c.
References ep4_is_infty(), ep4_norm_imp(), ERR_CAUGHT, ERR_NO_MEMORY, fp4_copy(), fp4_free, fp4_inv_sim(), fp4_new, fp4_null, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by ep4_mul_reg_gls(), ep4_mul_sim_joint(), ep4_mul_sim_trick(), ep4_mul_slide(), and ep4_tab().
ep4_map()
void ep4_map (ep4_t p, const uint8_t * msg, size_t len)
Maps a byte array to a point in an elliptic curve over a quartic extension.
Parameters
[out] p - the result.
[in] msg - the byte array to map.
[in] len - the array length in bytes.
Definition at line 40 of file relic_ep4_map.c.
References BASIC, bn_free, bn_get_bit(), bn_new, bn_null, bn_read_bin(), core_get(), _ctx_t::ep4_b, ep4_curve_get_a(), ep4_mul_cof(), ep4_rhs(), ep4_set_infty(), ep_curve_opt_a(), ep_curve_opt_b(), _ctx_t::ep_map_c, ep_param_level(), ERR_CAUGHT, ERR_NO_VALID, fp2_is_zero(), fp4_add(), fp4_copy(), fp4_copy_sec(), fp4_dbl(), fp4_free, fp4_inv(), fp4_inv_sim(), fp4_is_sqr(), fp4_is_zero(), fp4_mul, fp4_mul_dig(), fp4_neg(), fp4_new, fp4_null, fp4_set_dig(), fp4_sqr, fp4_srt(), fp4_sub(), fp4_zero(), fp_hlv, fp_is_even(), fp_is_zero(), fp_mul, FP_PRIME, fp_prime_back(), fp_prime_conv(), fp_sub_dig(), md_xmd, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, RLC_TRY, and RLC_ZERO.
ep4_frb()
void ep4_frb (ep4_t r, const ep4_t p, int i)
Computes a power of the Gailbraith-Lin-Scott homomorphism of a point represented in affine coordinates on a twisted elliptic curve over a quartic exension. That is, Psi^i(P) = Twist(P)(Frob^i(unTwist(P)). On the trace-zero group of a quartic twist, consists of a power of the Frobenius map of a point represented in affine coordinates in an elliptic curve over a quartic exension. Computes Frob^i(P) = (p^i)P.
Parameters
[out] r - the result in affine coordinates.
[in] p - a point in affine coordinates.
[in] i - the power of the Frobenius map.
Definition at line 39 of file relic_ep4_frb.c.
References ep4_copy(), fp4_frb(), and fp4_mul_frb().
Referenced by ep4_mul_cof_afg16(), ep4_mul_cof_b24(), ep4_mul_cof_fm16(), ep4_mul_cof_k16(), ep4_mul_sim_lot(), ep4_psi(), and pp_fin_k16_oatep().
ep4_pck()
void ep4_pck (ep4_t r, const ep4_t p)
Compresses a point in an elliptic curve over a quartic extension.
Parameters
[out] r - the result.
[in] p - the point to compress.
ep4_upk()
int ep4_upk (ep4_t r, const ep4_t p)
Decompresses a point in an elliptic curve over a quartic extension.
Parameters
[out] r - the result.
[in] p - the point to decompress.
Returns
if the decompression was successful
ep8_curve_init()
void ep8_curve_init (void)
Initializes the elliptic curve over octic extension.
Definition at line 170 of file relic_ep8_curve.c.
References bn_make(), core_get(), _ctx_t::ep8_a, _ctx_t::ep8_b, _ctx_t::ep8_g, _ctx_t::ep8_h, ep8_new, _ctx_t::ep8_pre, _ctx_t::ep8_ptr, _ctx_t::ep8_r, fp8_new, RLC_EP_TABLE, RLC_FP_DIGS, ep8_st::x, ep8_st::y, and ep8_st::z.
Referenced by pp_map_init().
ep8_curve_clean()
void ep8_curve_clean (void)
Finalizes the elliptic curve over octic extension.
Definition at line 198 of file relic_ep8_curve.c.
References bn_clean(), core_get(), _ctx_t::ep8_a, _ctx_t::ep8_b, ep8_free, _ctx_t::ep8_g, _ctx_t::ep8_h, _ctx_t::ep8_pre, _ctx_t::ep8_r, fp8_free, RLC_EP_TABLE, ep8_st::x, ep8_st::y, and ep8_st::z.
Referenced by pp_map_clean().
ep8_curve_get_a()
fp4_t * ep8_curve_get_a (void)
Returns the 'a' coefficient of the currently configured elliptic curve.
Returns
the 'a' coefficient of the elliptic curve.
Definition at line 275 of file relic_ep8_curve.c.
References core_get(), and _ctx_t::ep8_a.
Referenced by ep8_rhs().
ep8_curve_get_b()
fp4_t * ep8_curve_get_b (void)
Returns the 'b' coefficient of the currently configured elliptic curve.
Parameters
[out] b - the 'b' coefficient of the elliptic curve.
Definition at line 279 of file relic_ep8_curve.c.
References core_get(), and _ctx_t::ep8_b.
Referenced by ep8_rhs(), and pp_dbl_k48_projc().
ep8_curve_opt_a()
int ep8_curve_opt_a (void)
Returns a optimization identifier based on the 'a' coefficient of the curve.
Returns
the optimization identifier.
Definition at line 216 of file relic_ep8_curve.c.
References core_get(), and _ctx_t::ep8_opt_a.
Referenced by ep8_rhs().
ep8_curve_opt_b()
int ep8_curve_opt_b (void)
Returns b optimization identifier based on the 'b' coefficient of the curve.
Returns
the optimization identifier.
Definition at line 220 of file relic_ep8_curve.c.
References core_get(), and _ctx_t::ep8_opt_b.
Referenced by ep8_rhs().
ep8_curve_mul_a()
void ep8_curve_mul_a (fp8_t c, const fp8_t a)
Multiplies a field element by the a-coefficient of the curve.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
Definition at line 224 of file relic_ep8_curve.c.
References core_get(), _ctx_t::ep8_a, _ctx_t::ep8_opt_a, fp8_copy(), fp8_dbl(), fp8_mul, fp8_mul_dig(), fp8_zero(), RLC_ONE, RLC_TINY, RLC_TWO, and RLC_ZERO.
ep8_curve_mul_b()
void ep8_curve_mul_b (fp8_t c, const fp8_t a)
Multiplies a field element by the b-coefficient of the curve.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
Definition at line 247 of file relic_ep8_curve.c.
References core_get(), _ctx_t::ep8_b, _ctx_t::ep8_opt_b, fp8_copy(), fp8_mul, fp8_mul_dig(), fp8_zero(), RLC_ONE, RLC_TINY, and RLC_ZERO.
ep8_curve_is_twist()
int ep8_curve_is_twist (void)
Tests if the configured elliptic curve is a twist.
Returns
the type of the elliptic curve twist, 0 if non-twisted curve.
Definition at line 267 of file relic_ep8_curve.c.
References core_get(), and _ctx_t::ep8_is_twist.
ep8_curve_get_gen()
void ep8_curve_get_gen (ep8_t g)
Returns the generator of the group of points in the elliptic curve.
Parameters
[out] g - the returned generator.
Definition at line 271 of file relic_ep8_curve.c.
References core_get(), and ep8_copy().
Referenced by ep8_mul_gen(), and ep8_mul_sim_gen().
ep8_curve_get_tab()
ep8_t * ep8_curve_get_tab (void)
Returns the precomputation table for the generator.
Returns
the table.
Definition at line 298 of file relic_ep8_curve.c.
References core_get(), and _ctx_t::ep8_ptr.
Referenced by ep8_curve_set(), ep8_curve_set_twist(), ep8_mul_gen(), and ep8_mul_sim_gen().
ep8_curve_get_ord()
void ep8_curve_get_ord (bn_t n)
Returns the order of the group of points in the elliptic curve.
Parameters
[out] n - the returned order.
Definition at line 283 of file relic_ep8_curve.c.
References bn_copy(), core_get(), _ctx_t::ep8_is_twist, _ctx_t::ep8_r, and ep_curve_get_ord().
Referenced by ep8_mul_fix_basic(), ep8_mul_fix_combd(), ep8_mul_fix_combs(), ep8_mul_gls_imp(), ep8_mul_monty(), ep8_mul_pre_basic(), ep8_mul_pre_combd(), ep8_mul_pre_combs(), ep8_mul_reg_gls(), ep8_mul_reg_imp(), ep8_mul_sim_trick(), and ep8_rand().
ep8_curve_get_cof()
void ep8_curve_get_cof (bn_t h)
Returns the cofactor of the group order in the elliptic curve.
Parameters
[out] h - the returned cofactor.
Definition at line 292 of file relic_ep8_curve.c.
References bn_copy(), and core_get().
ep8_curve_set()
void ep8_curve_set (const fp8_t a, const fp8_t b, const ep8_t g, const bn_t r, const bn_t h)
Configures an elliptic curve over an octic extension by its coefficients.
Parameters
[in] a - the 'a' coefficient of the curve.
[in] b - the 'b' coefficient of the curve.
[in] g - the generator.
[in] r - the order of the group of points.
[in] h - the cofactor of the group order.
Definition at line 392 of file relic_ep8_curve.c.
References bn_copy(), core_get(), _ctx_t::ep8_a, _ctx_t::ep8_b, ep8_curve_get_tab(), _ctx_t::ep8_g, _ctx_t::ep8_h, _ctx_t::ep8_is_twist, ep8_mul_pre, ep8_norm(), _ctx_t::ep8_r, and fp8_copy().
ep8_curve_set_twist()
void ep8_curve_set_twist (int type)
Configures an elliptic curve by twisting the curve over the base prime field.
Parameters
- the type of twist (multiplicative or divisive)
Definition at line 308 of file relic_ep8_curve.c.
References ASSIGN, B48_P575, BASIC, bn_copy(), bn_free, bn_new, bn_null, core_get(), detect_opt(), _ctx_t::ep8_a, _ctx_t::ep8_b, ep8_copy(), ep8_curve_get_tab(), ep8_free, _ctx_t::ep8_g, _ctx_t::ep8_h, _ctx_t::ep8_is_twist, ep8_mul_pre, ep8_new, ep8_null, _ctx_t::ep8_opt_a, _ctx_t::ep8_opt_b, _ctx_t::ep8_r, ep_param_get(), ERR_CAUGHT, ERR_NO_VALID, fp8_copy(), fp8_free, fp8_inv(), fp8_new, fp8_null, _ctx_t::fp8_p1, fp8_set_dig(), fp8_zero(), fp_copy(), pc_core_calc(), RLC_CATCH_ANY, RLC_EP_DTYPE, RLC_EP_MTYPE, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.
Referenced by ep_param_set_any_pairf().
ep8_is_infty()
int ep8_is_infty (const ep8_t p)
Tests if a point on an elliptic curve is at the infinity.
Parameters
[in] p - the point to test.
Returns
1 if the point is at infinity, 0 otherise.
Definition at line 39 of file relic_ep8_util.c.
References fp8_is_zero().
Referenced by ep8_add_basic(), ep8_add_jacob(), ep8_add_projc(), ep8_add_slp_basic(), ep8_cmp(), ep8_dbl_basic(), ep8_dbl_jacob(), ep8_dbl_projc(), ep8_dbl_slp_basic(), ep8_mul_basic(), ep8_mul_dig(), ep8_mul_lwnaf(), ep8_mul_lwreg(), ep8_mul_monty(), ep8_mul_sim_gen(), ep8_mul_sim_inter(), ep8_mul_sim_joint(), ep8_mul_sim_trick(), ep8_mul_slide(), ep8_neg(), ep8_norm(), ep8_norm_sim(), ep8_on_curve(), ep8_size_bin(), ep8_write_bin(), pp_map_k48(), pp_map_sim_k48(), and pp_norm_k48().
ep8_set_infty()
void ep8_set_infty (ep8_t p)
Assigns an elliptic curve point to the point at infinity.
Parameters
[out] p - the point to assign.
Definition at line 43 of file relic_ep8_util.c.
References BASIC, and fp8_zero().
Referenced by ep8_dbl_basic(), ep8_dbl_jacob(), ep8_dbl_projc(), ep8_dbl_slp_basic(), ep8_map(), ep8_mul_basic(), ep8_mul_dig(), ep8_mul_fix_basic(), ep8_mul_fix_combd(), ep8_mul_fix_combs(), ep8_mul_fix_ordin(), ep8_mul_gen(), ep8_mul_gls_imp(), ep8_mul_lwnaf(), ep8_mul_lwreg(), ep8_mul_monty(), ep8_mul_naf_imp(), ep8_mul_pre_combd(), ep8_mul_pre_combs(), ep8_mul_reg_gls(), ep8_mul_reg_imp(), ep8_mul_sim_dig(), ep8_mul_sim_joint(), ep8_mul_sim_lot(), ep8_mul_sim_plain(), ep8_mul_sim_trick(), ep8_mul_slide(), ep8_neg(), ep8_norm(), ep8_read_bin(), ep8_sub(), and pp_norm_k48().
ep8_copy()
void ep8_copy (ep8_t r, const ep8_t p)
Copies the second argument to the first argument.
Parameters
[out] q - the result.
[in] p - the elliptic curve point to copy.
Definition at line 50 of file relic_ep8_util.c.
References fp8_copy().
Referenced by ep8_add_basic(), ep8_add_jacob(), ep8_add_projc(), ep8_add_slp_basic(), ep8_blind(), ep8_cmp(), ep8_curve_get_gen(), ep8_curve_set_twist(), ep8_frb(), ep8_mul_dig(), ep8_mul_fix_combs(), ep8_mul_pre_basic(), ep8_mul_pre_combd(), ep8_mul_pre_combs(), ep8_mul_pre_ordin(), ep8_mul_reg_gls(), ep8_mul_sim_joint(), ep8_mul_sim_lot(), ep8_mul_sim_trick(), ep8_mul_slide(), ep8_norm(), ep8_norm_imp(), ep8_tab(), pp_add_k48_basic(), pp_dbl_k48_basic(), pp_mil_k48(), and pp_norm_k48().
ep8_cmp()
int ep8_cmp (const ep8_t p, const ep8_t q)
Compares two elliptic curve points.
Parameters
[in] p - the first elliptic curve point.
[in] q - the second elliptic curve point.
Returns
RLC_EQ if p == q and RLC_NE if p != q.
Definition at line 39 of file relic_ep8_cmp.c.
References ep8_copy(), ep8_free, ep8_is_infty(), ep8_new, ep8_null, ERR_CAUGHT, fp8_cmp(), fp8_mul, fp8_sqr, JACOB, PROJC, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_NE, RLC_THROW, and RLC_TRY.
ep8_rand()
void ep8_rand (ep8_t p)
Assigns a random value to an elliptic curve point.
Parameters
[out] p - the elliptic curve point to assign.
Definition at line 57 of file relic_ep8_util.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), ep8_curve_get_ord(), ep8_mul_gen(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep8_blind()
void ep8_blind (ep8_t r, const ep8_t p)
Randomizes coordinates of an elliptic curve point.
Parameters
[out] r - the blinded prime elliptic curve point.
[in] p - the prime elliptic curve point to blind.
Definition at line 81 of file relic_ep8_util.c.
References ep8_copy(), ERR_CAUGHT, fp8_free, fp8_mul, fp8_new, fp8_null, fp8_rand(), fp8_sqr, JACOB, PROJC, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep8_mul_monty().
ep8_rhs()
void ep8_rhs (fp8_t rhs, const fp8_t x)
Computes the right-hand side of the elliptic curve equation at the x-coordinate of a certain prime elliptic curve point.
Parameters
[out] rhs - the result.
[in] x - the x-coordinate of the point.
Definition at line 112 of file relic_ep8_util.c.
References ep8_curve_get_a(), ep8_curve_get_b(), ep8_curve_opt_a(), ep8_curve_opt_b(), ERR_CAUGHT, fp8_add(), fp8_copy(), fp8_free, fp8_mul, fp8_new, fp8_null, fp8_sqr, fp_add_dig(), fp_sub_dig(), RLC_CATCH_ANY, RLC_FINALLY, RLC_MIN3, RLC_ONE, RLC_THROW, RLC_TINY, RLC_TRY, RLC_TWO, and RLC_ZERO.
Referenced by ep8_map(), and ep8_on_curve().
ep8_on_curve()
int ep8_on_curve (const ep8_t p)
Tests if a point is in the curve.
Parameters
[in] p - the point to test.
Definition at line 178 of file relic_ep8_util.c.
References ep8_free, ep8_is_infty(), ep8_new, ep8_norm(), ep8_null, ep8_rhs(), ERR_CAUGHT, fp8_cmp(), fp8_sqr, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep8_read_bin().
ep8_tab()
void ep8_tab (ep8_t * t, const ep8_t p, int w)
Builds a precomputation table for multiplying a random prime elliptic point.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
[in] w - the window width.
Definition at line 201 of file relic_ep8_util.c.
References ep8_add, ep8_copy(), ep8_dbl, ep8_norm(), and ep8_norm_sim().
Referenced by ep8_mul_gls_imp(), ep8_mul_naf_imp(), ep8_mul_reg_imp(), and ep8_mul_sim_plain().
ep8_print()
void ep8_print (const ep8_t p)
Prints an elliptic curve point.
Parameters
[in] p - the elliptic curve point to print.
Definition at line 222 of file relic_ep8_util.c.
References fp8_print().
ep8_size_bin()
size_t ep8_size_bin (const ep8_t a, int pack)
Returns the number of bytes necessary to store a prime elliptic curve point over an octic extension with optional point compression.
Parameters
[in] a - the prime field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 228 of file relic_ep8_util.c.
References ep8_free, ep8_is_infty(), ep8_new, ep8_norm(), ep8_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.
ep8_read_bin()
void ep8_read_bin (ep8_t a, const uint8_t * bin, size_t len)
Reads a prime elliptic curve point over an octic extension from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_VALID - if the encoded point is invalid.
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 254 of file relic_ep8_util.c.
References BASIC, ep8_on_curve(), ep8_set_infty(), ERR_NO_BUFFER, ERR_NO_VALID, fp8_read_bin(), fp8_set_dig(), RLC_FP_BYTES, and RLC_THROW.
ep8_write_bin()
void ep8_write_bin (uint8_t * bin, size_t len, const ep8_t a, int pack)
Writes a prime elliptic curve pointer over an octic extension to a byte vector in big-endian format with optional point compression.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the prime elliptic curve point to write.
[in] pack - the flag to indicate compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 288 of file relic_ep8_util.c.
References ep8_free, ep8_is_infty(), ep8_new, ep8_norm(), ep8_null, ERR_CAUGHT, ERR_NO_BUFFER, fp8_write_bin(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.
ep8_neg()
void ep8_neg (ep8_t r, const ep8_t p)
Negates a point represented in affine coordinates in an elliptic curve over an octic extension.
Parameters
[out] r - the result.
[out] p - the point to negate.
Definition at line 39 of file relic_ep8_neg.c.
References ep8_is_infty(), ep8_set_infty(), fp8_copy(), and fp8_neg().
Referenced by ep8_mul_basic(), ep8_mul_fix_combd(), ep8_mul_fix_ordin(), ep8_mul_gls_imp(), ep8_mul_naf_imp(), ep8_mul_reg_gls(), ep8_mul_reg_imp(), ep8_mul_sim_joint(), ep8_mul_sim_lot(), ep8_mul_sim_trick(), ep8_mul_slide(), ep8_sub(), and pp_mil_k48().
ep8_add_basic()
void ep8_add_basic (ep8_t r, const ep8_t p, const ep8_t q)
Adds to points represented in affine coordinates in an elliptic curve over a octic extension.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 109 of file relic_ep8_add.c.
References ep8_copy(), and ep8_is_infty().
ep8_add_slp_basic()
void ep8_add_slp_basic (ep8_t r, fp8_t s, const ep8_t p, const ep8_t q)
Adds to points represented in affine coordinates in an elliptic curve over a octic extension and returns the computed slope.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 123 of file relic_ep8_add.c.
References ep8_copy(), and ep8_is_infty().
Referenced by pp_add_k48_basic().
ep8_add_projc()
void ep8_add_projc (ep8_t r, const ep8_t p, const ep8_t q)
Adds two points represented in projective coordinates in an elliptic curve over an octic extension.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 141 of file relic_ep8_add.c.
References ep8_copy(), and ep8_is_infty().
ep8_add_jacob()
void ep8_add_jacob (ep8_t r, const ep8_t p, const ep8_t q)
Adds two points represented in Jacobian coordinates in an elliptic curve over an octic extension.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 159 of file relic_ep8_add.c.
References ep8_copy(), and ep8_is_infty().
ep8_sub()
void ep8_sub (ep8_t r, const ep8_t p, const ep8_t q)
Subtracts a point in an elliptic curve over an octic extension from another.
Parameters
[out] r - the result.
[in] p - the first point.
[in] q - the point to subtract.
Definition at line 175 of file relic_ep8_add.c.
References ep8_add, ep8_free, ep8_neg(), ep8_new, ep8_null, ep8_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep8_mul_basic(), ep8_mul_cof(), ep8_mul_dig(), ep8_mul_fix_ordin(), ep8_mul_gls_imp(), ep8_mul_naf_imp(), ep8_mul_reg_gls(), ep8_mul_reg_imp(), ep8_mul_sim_joint(), ep8_mul_sim_lot(), and ep8_mul_sim_plain().
ep8_dbl_basic()
void ep8_dbl_basic (ep8_t r, const ep8_t p)
Doubles a point represented in affine coordinates in an elliptic curve over an octic extension.
Parameters
[out] r - the result.
[int] p - the point to double.
Definition at line 86 of file relic_ep8_dbl.c.
References ep8_is_infty(), and ep8_set_infty().
ep8_dbl_slp_basic()
void ep8_dbl_slp_basic (ep8_t r, fp8_t s, const ep8_t p)
Doubles a point represented in affine coordinates in an elliptic curve over an octic extension and returns the computed slope.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the point to double.
Definition at line 94 of file relic_ep8_dbl.c.
References ep8_is_infty(), and ep8_set_infty().
Referenced by pp_dbl_k48_basic().
ep8_dbl_projc()
void ep8_dbl_projc (ep8_t r, const ep8_t p)
Doubles a point represented in projective coordinates in an elliptic curve over an octic extension.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 107 of file relic_ep8_dbl.c.
References ep8_is_infty(), and ep8_set_infty().
ep8_dbl_jacob()
void ep8_dbl_jacob (ep8_t r, const ep8_t p)
Doubles a point represented in Jacobian coordinates in an elliptic curve over an octic extension.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 120 of file relic_ep8_dbl.c.
References ep8_is_infty(), and ep8_set_infty().
ep8_mul_basic()
void ep8_mul_basic (ep8_t r, const ep8_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the binary method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 412 of file relic_ep8_mul.c.
References bn_bits(), bn_is_zero(), bn_rec_naf(), bn_sign(), ep8_add, ep8_dbl, ep8_free, ep8_is_infty(), ep8_mul_dig(), ep8_neg(), ep8_new, ep8_norm(), ep8_null, ep8_set_infty(), ep8_sub(), ERR_CAUGHT, ERR_NO_BUFFER, RLC_ALLOCA, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by ep8_mul_cof().
ep8_mul_slide()
void ep8_mul_slide (ep8_t r, const ep8_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the sliding window method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 470 of file relic_ep8_mul.c.
References bn_is_zero(), bn_rec_slw(), bn_sign(), ep8_add, ep8_copy(), ep8_dbl, ep8_free, ep8_is_infty(), ep8_neg(), ep8_new, ep8_norm(), ep8_norm_sim(), ep8_null, ep8_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_THROW, RLC_TRY, RLC_WIDTH, and util_bits_dig().
ep8_mul_monty()
void ep8_mul_monty (ep8_t r, const ep8_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the constant-time Montgomery ladder point multiplication method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 540 of file relic_ep8_mul.c.
References bn_abs(), bn_add(), bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_new, bn_null, dv_swap_sec(), ep8_add, ep8_blind(), ep8_curve_get_ord(), ep8_dbl, ep8_free, ep8_is_infty(), ep8_new, ep8_norm(), ep8_null, ep8_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_MAX, RLC_SEL, RLC_THROW, and RLC_TRY.
ep8_mul_lwnaf()
void ep8_mul_lwnaf (ep8_t r, const ep8_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the w-NAF method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 622 of file relic_ep8_mul.c.
References bn_is_zero(), ep8_is_infty(), ep8_mul_gls_imp(), ep8_mul_naf_imp(), ep8_set_infty(), and ep_curve_is_endom().
ep8_mul_lwreg()
void ep8_mul_lwreg (ep8_t r, const ep8_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using a regular method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 644 of file relic_ep8_mul.c.
References bn_is_zero(), ep8_is_infty(), ep8_mul_reg_gls(), ep8_mul_reg_imp(), ep8_set_infty(), and ep_curve_is_endom().
ep8_mul_gen()
void ep8_mul_gen (ep8_t r, const bn_t k)
Multiplies the generator of an elliptic curve over a qaudratic extension.
Parameters
[out] r - the result.
[in] k - the integer.
Definition at line 664 of file relic_ep8_mul.c.
References bn_is_zero(), ep8_curve_get_gen(), ep8_curve_get_tab(), ep8_free, ep8_mul, ep8_mul_fix, ep8_new, ep8_null, ep8_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep8_mul_sim_gen(), and ep8_rand().
ep8_mul_dig()
void ep8_mul_dig (ep8_t r, const ep8_t p, const dig_t k)
Multiplies a prime elliptic point by a small integer.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 691 of file relic_ep8_mul.c.
References bn_free, bn_new, bn_null, bn_rec_naf(), bn_set_dig(), ep8_add, ep8_copy(), ep8_dbl, ep8_free, ep8_is_infty(), ep8_new, ep8_norm(), ep8_null, ep8_set_infty(), ep8_sub(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep8_mul_basic().
ep8_mul_cof()
void ep8_mul_cof (ep8_t r, const ep8_t p)
Multiplies a point in an elliptic curve over an octic extension field by the curve cofactor or a small multiple for which a short vector exists. In short, it takes a point in the curve to the large prime-order subgroup.
Parameters
[out] R - the result.
[in] P - the point to multiply.
Definition at line 40 of file relic_ep8_mul_cof.c.
References bn_free, bn_new, bn_null, ep8_add, ep8_dbl, ep8_frb(), ep8_free, ep8_mul_basic(), ep8_new, ep8_norm(), ep8_null, ep8_sub(), ERR_CAUGHT, fp_prime_get_par(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep8_map().
ep8_mul_pre_basic()
void ep8_mul_pre_basic (ep8_t * t, const ep8_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the binary method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 119 of file relic_ep8_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, ep8_copy(), ep8_curve_get_ord(), ep8_dbl, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep8_mul_pre_yaowi()
void ep8_mul_pre_yaowi (ep8_t * t, const ep8_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using Yao's windowing method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
ep8_mul_pre_nafwi()
void ep8_mul_pre_nafwi (ep8_t * t, const ep8_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the NAF windowing method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
ep8_mul_pre_combs()
void ep8_mul_pre_combs (ep8_t * t, const ep8_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the single-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 179 of file relic_ep8_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, ep8_add, ep8_copy(), ep8_curve_get_ord(), ep8_dbl, ep8_norm(), ep8_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_EP_TABLE_COMBS, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep8_mul_pre_combd()
void ep8_mul_pre_combd (ep8_t * t, const ep8_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the double-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 286 of file relic_ep8_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, ep8_add, ep8_copy(), ep8_curve_get_ord(), ep8_dbl, ep8_norm(), ep8_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_EP_TABLE_COMBD, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep8_mul_pre_lwnaf()
void ep8_mul_pre_lwnaf (ep8_t * t, const ep8_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the w-(T)NAF method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 399 of file relic_ep8_mul_fix.c.
References ep8_mul_pre_ordin().
ep8_mul_fix_basic()
void ep8_mul_fix_basic (ep8_t r, const ep8_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the binary method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 142 of file relic_ep8_mul_fix.c.
References bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_new, bn_null, ep8_add, ep8_curve_get_ord(), ep8_norm(), ep8_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep8_mul_fix_yaowi()
void ep8_mul_fix_yaowi (ep8_t r, const ep8_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and Yao's windowing method
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
ep8_mul_fix_nafwi()
void ep8_mul_fix_nafwi (ep8_t r, const ep8_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the w-(T)NAF method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
ep8_mul_fix_combs()
void ep8_mul_fix_combs (ep8_t r, const ep8_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the single-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 221 of file relic_ep8_mul_fix.c.
References bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_new, bn_null, ep8_add, ep8_copy(), ep8_curve_get_ord(), ep8_dbl, ep8_norm(), ep8_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep8_mul_fix_combd()
void ep8_mul_fix_combd (ep8_t r, const ep8_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the double-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 335 of file relic_ep8_mul_fix.c.
References bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_new, bn_null, bn_sign(), ep8_add, ep8_curve_get_ord(), ep8_dbl, ep8_neg(), ep8_norm(), ep8_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
ep8_mul_fix_lwnaf()
void ep8_mul_fix_lwnaf (ep8_t r, const ep8_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the w-(T)NAF method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 403 of file relic_ep8_mul_fix.c.
References ep8_mul_fix_ordin().
ep8_mul_sim_basic()
void ep8_mul_sim_basic (ep8_t r, const ep8_t p, const bn_t k, const ep8_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using scalar multiplication and point addition.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 149 of file relic_ep8_mul_sim.c.
References ep8_add, ep8_free, ep8_mul, ep8_new, ep8_norm(), ep8_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep8_mul_sim_trick()
void ep8_mul_sim_trick (ep8_t r, const ep8_t p, const bn_t k, const ep8_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using shamir's trick.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 174 of file relic_ep8_mul_sim.c.
References bn_free, bn_is_zero(), bn_new, bn_null, bn_rec_win(), bn_sign(), ep8_add, ep8_copy(), ep8_curve_get_ord(), ep8_dbl, ep8_free, ep8_is_infty(), ep8_mul, ep8_neg(), ep8_new, ep8_norm(), ep8_norm_sim(), ep8_null, ep8_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_CEIL, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
ep8_mul_sim_inter()
void ep8_mul_sim_inter (ep8_t r, const ep8_t p, const bn_t k, const ep8_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using interleaving of NAFs.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 268 of file relic_ep8_mul_sim.c.
References bn_is_zero(), ep8_is_infty(), ep8_mul, and ep8_mul_sim_plain().
ep8_mul_sim_joint()
void ep8_mul_sim_joint (ep8_t r, const ep8_t p, const bn_t k, const ep8_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using Solinas' Joint Sparse Form.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 286 of file relic_ep8_mul_sim.c.
References bn_bits(), bn_is_zero(), bn_rec_jsf(), bn_sign(), ep8_add, ep8_copy(), ep8_dbl, ep8_free, ep8_is_infty(), ep8_mul, ep8_neg(), ep8_new, ep8_norm(), ep8_norm_sim(), ep8_null, ep8_set_infty(), ep8_sub(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, and RLC_TRY.
ep8_mul_sim_lot()
void ep8_mul_sim_lot (ep8_t r, const ep8_t p[], const bn_t k[], size_t n)
Multiplies simultaneously elements from a prime elliptic curve. Computes R = \Sum_i=0..n k_iP_i.
Parameters
[out] r - the result.
[in] p - the points to multiply.
[in] k - the integer scalars.
[in] n - the number of elements to multiply.
Definition at line 427 of file relic_ep8_mul_sim.c.
References bn_free, bn_new, bn_null, bn_rec_frb(), bn_rec_naf(), bn_sign(), ep8_add, ep8_copy(), ep8_dbl, ep8_frb(), ep8_free, ep8_neg(), ep8_new, ep8_norm(), ep8_null, ep8_set_infty(), ep8_sub(), EP_BN, ep_curve_get_ord(), ep_curve_is_pairf(), ERR_CAUGHT, fp_prime_get_par(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_FREE, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and util_bits_dig().
ep8_mul_sim_gen()
void ep8_mul_sim_gen (ep8_t r, const bn_t k, const ep8_t q, const bn_t m)
Multiplies and adds the generator and a prime elliptic curve point simultaneously. Computes R = [k]G + [l]Q.
Parameters
[out] r - the result.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 361 of file relic_ep8_mul_sim.c.
References bn_is_zero(), ep8_curve_get_gen(), ep8_curve_get_tab(), ep8_free, ep8_is_infty(), ep8_mul, ep8_mul_gen(), ep8_mul_sim, ep8_mul_sim_plain(), ep8_new, ep8_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep8_mul_sim_dig()
void ep8_mul_sim_dig (ep8_t r, const ep8_t p[], const dig_t k[], size_t len)
Multiplies prime elliptic curve points by small scalars. Computes R = \sum k_iP_i.
Parameters
[out] r - the result.
[in] p - the points to multiply.
[in] k - the small scalars.
[in] len - the number of points to multiply.
Definition at line 393 of file relic_ep8_mul_sim.c.
References ep8_add, ep8_dbl, ep8_free, ep8_new, ep8_norm(), ep8_null, ep8_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_MAX, RLC_THROW, RLC_TRY, and util_bits_dig().
ep8_norm()
void ep8_norm (ep8_t r, const ep8_t p)
Converts a point to affine coordinates.
Parameters
[out] r - the result.
[in] p - the point to convert.
Definition at line 97 of file relic_ep8_norm.c.
References BASIC, ep8_copy(), ep8_is_infty(), ep8_norm_imp(), and ep8_set_infty().
Referenced by ep8_curve_set(), ep8_mul_basic(), ep8_mul_cof(), ep8_mul_dig(), ep8_mul_fix_basic(), ep8_mul_fix_combd(), ep8_mul_fix_combs(), ep8_mul_fix_ordin(), ep8_mul_gls_imp(), ep8_mul_monty(), ep8_mul_naf_imp(), ep8_mul_pre_combd(), ep8_mul_pre_combs(), ep8_mul_pre_ordin(), ep8_mul_reg_gls(), ep8_mul_reg_imp(), ep8_mul_sim_basic(), ep8_mul_sim_dig(), ep8_mul_sim_joint(), ep8_mul_sim_lot(), ep8_mul_sim_plain(), ep8_mul_sim_trick(), ep8_mul_slide(), ep8_on_curve(), ep8_size_bin(), ep8_tab(), ep8_write_bin(), pp_map_k48(), and pp_map_sim_k48().
ep8_norm_sim()
void ep8_norm_sim (ep8_t * r, const ep8_t * t, int n)
Converts multiple points to affine coordinates.
Parameters
[out] r - the result.
[in] t - the points to convert.
[in] n - the number of points.
Definition at line 113 of file relic_ep8_norm.c.
References ep8_is_infty(), ep8_norm_imp(), ERR_CAUGHT, ERR_NO_MEMORY, fp8_copy(), fp8_free, fp8_inv_sim(), fp8_new, fp8_null, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by ep8_mul_reg_gls(), ep8_mul_sim_joint(), ep8_mul_sim_trick(), ep8_mul_slide(), and ep8_tab().
ep8_map()
void ep8_map (ep8_t p, const uint8_t * msg, size_t len)
Maps a byte array to a point in an elliptic curve over an octic extension.
Parameters
[out] p - the result.
[in] msg - the byte array to map.
[in] len - the array length in bytes.
Definition at line 40 of file relic_ep8_map.c.
References BASIC, bn_free, bn_get_bit(), bn_new, bn_null, bn_read_bin(), core_get(), _ctx_t::ep8_b, ep8_mul_cof(), ep8_rhs(), ep8_set_infty(), _ctx_t::ep_map_c, ep_param_level(), ERR_CAUGHT, ERR_NO_VALID, fp4_is_zero(), fp8_add(), fp8_copy(), fp8_copy_sec(), fp8_dbl(), fp8_free, fp8_inv(), fp8_is_sqr(), fp8_is_zero(), fp8_mul, fp8_neg(), fp8_new, fp8_null, fp8_set_dig(), fp8_sqr, fp8_srt(), fp8_sub(), fp_is_zero(), fp_mul, FP_PRIME, fp_prime_back(), fp_prime_conv(), md_xmd, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
ep8_frb()
void ep8_frb (ep8_t r, const ep8_t p, int i)
Computes a power of the Gailbraith-Lin-Scott homomorphism of a point represented in affine coordinates on a twisted elliptic curve over a octic exension. That is, Psi^i(P) = Twist(P)(Frob^i(unTwist(P)). On the trace-zero group of an octic twist, consists of a power of the Frobenius map of a point represented in affine coordinates in an elliptic curve over an octic exension. Computes Frob^i(P) = (p^i)P.
Parameters
[out] r - the result in affine coordinates.
[in] p - a point in affine coordinates.
[in] i - the power of the Frobenius map.
Definition at line 39 of file relic_ep8_frb.c.
References ep8_copy(), fp8_frb(), and fp8_mul_frb().
Referenced by ep8_mul_cof(), ep8_mul_gls_imp(), ep8_mul_reg_gls(), and ep8_mul_sim_lot().
ep8_pck()
void ep8_pck (ep8_t r, const ep8_t p)
Compresses a point in an elliptic curve over an octic extension.
Parameters
[out] r - the result.
[in] p - the point to compress.
ep8_upk()
int ep8_upk (ep8_t r, const ep8_t p)
Decompresses a point in an elliptic curve over an octic extension.
Parameters
[out] r - the result.
[in] p - the point to decompress.
Returns
if the decompression was successful