RELIC: include/relic_ed.h File Reference
relic_ed.h File Reference
Edwards curves over prime fields.
#include "relic_fp.h"
#include "relic_bn.h"
#include "relic_types.h"
#include "relic_label.h"
Data Structures
struct ed_st
Macros
#define RLC_ED_TABLE_BASIC (RLC_FP_BITS + 1)
#define RLC_ED_TABLE_COMBS (1 << RLC_DEPTH)
#define RLC_ED_TABLE_COMBD (1 << (RLC_DEPTH + 1))
#define RLC_ED_TABLE_LWNAF (1 << (RLC_DEPTH - 2))
#define RLC_ED_TABLE RLC_ED_TABLE_COMBS
#define RLC_ED_TABLE_MAX RLC_MAX(RLC_ED_TABLE_BASIC, RLC_ED_TABLE_COMBD)
#define ed_null(A)
#define ed_new(A)
#define ed_free(A)
#define ed_neg(R, P)
#define ed_add(R, P, Q)
#define ed_sub(R, P, Q)
#define ed_dbl(R, P)
#define ed_mul(R, P, K)
#define ed_mul_pre(T, P)
#define ed_mul_fix(R, T, K)
#define ed_mul_sim(R, P, K, Q, M)
Typedefs
typedef ed_st ed_t[1]
Enumerations
enum { CURVE_ED25519 = 1 }
Functions
void ed_param_set (int param)
int ed_param_set_any (void)
int ed_param_get (void)
void ed_curve_get_ord (bn_t r)
void ed_curve_get_gen (ed_t g)
const ed_t * ed_curve_get_tab (void)
void ed_curve_get_cof (bn_t h)
void ed_param_print (void)
int ed_param_level (void)
void ed_rand (ed_t p)
void ed_blind (ed_t r, const ed_t p)
void ed_rhs (fp_t rhs, const fp_t p)
void ed_copy (ed_t r, const ed_t p)
int ed_cmp (const ed_t p, const ed_t q)
void ed_set_infty (ed_t p)
int ed_is_infty (const ed_t p)
void ed_neg_basic (ed_t r, const ed_t p)
void ed_neg_projc (ed_t r, const ed_t p)
void ed_add_basic (ed_t r, const ed_t p, const ed_t q)
void ed_add_projc (ed_t r, const ed_t p, const ed_t q)
void ed_add_extnd (ed_t r, const ed_t p, const ed_t q)
void ed_sub_basic (ed_t r, const ed_t p, const ed_t q)
void ed_sub_projc (ed_t r, const ed_t p, const ed_t q)
void ed_sub_extnd (ed_t r, const ed_t p, const ed_t q)
void ed_dbl_basic (ed_t r, const ed_t p)
void ed_dbl_projc (ed_t r, const ed_t p)
void ed_dbl_extnd (ed_t r, const ed_t p)
void ed_norm (ed_t r, const ed_t p)
void ed_norm_sim (ed_t *r, const ed_t *t, int n)
void ed_map (ed_t p, const uint8_t *msg, size_t len)
void ed_map_dst (ed_t p, const uint8_t *msg, size_t len, const uint8_t *dst, size_t dst_len)
void ed_curve_init (void)
void ed_curve_clean (void)
void ed_mul_pre_basic (ed_t *t, const ed_t p)
void ed_mul_pre_yaowi (ed_t *t, const ed_t p)
void ed_mul_pre_nafwi (ed_t *t, const ed_t p)
void ed_mul_pre_combs (ed_t *t, const ed_t p)
void ed_mul_pre_combd (ed_t *t, const ed_t p)
void ed_mul_pre_lwnaf (ed_t *t, const ed_t p)
void ed_mul_fix_basic (ed_t r, const ed_t *t, const bn_t k)
void ed_mul_fix_yaowi (ed_t r, const ed_t *t, const bn_t k)
void ed_mul_fix_nafwi (ed_t r, const ed_t *t, const bn_t k)
void ed_mul_fix_combs (ed_t r, const ed_t *t, const bn_t k)
void ed_mul_fix_combd (ed_t r, const ed_t *t, const bn_t k)
void ed_mul_fix_lwnaf (ed_t r, const ed_t *t, const bn_t k)
void ed_mul_fix_lwnaf_mixed (ed_t r, const ed_t *t, const bn_t k)
void ed_mul_gen (ed_t r, const bn_t k)
void ed_mul_dig (ed_t r, const ed_t p, dig_t k)
void ed_mul_sim_basic (ed_t r, const ed_t p, const bn_t k, const ed_t q, const bn_t m)
void ed_mul_sim_trick (ed_t r, const ed_t p, const bn_t k, const ed_t q, const bn_t m)
void ed_mul_sim_inter (ed_t r, const ed_t p, const bn_t k, const ed_t q, const bn_t m)
void ed_mul_sim_joint (ed_t r, const ed_t p, const bn_t k, const ed_t q, const bn_t m)
void ed_mul_sim_lot (ed_t r, const ed_t p[], const bn_t k[], int n)
void ed_mul_sim_gen (ed_t r, const bn_t k, const ed_t q, const bn_t m)
void ed_tab (ed_t *t, const ed_t p, int w)
void ed_print (const ed_t p)
int ed_on_curve (const ed_t p)
size_t ed_size_bin (const ed_t a, int pack)
void ed_read_bin (ed_t a, const uint8_t *bin, size_t len)
void ed_write_bin (uint8_t *bin, size_t len, const ed_t a, int pack)
void ed_mul_basic (ed_t r, const ed_t p, const bn_t k)
void ed_mul_slide (ed_t r, const ed_t p, const bn_t k)
void ed_mul_monty (ed_t r, const ed_t p, const bn_t k)
void ed_mul_lwnaf (ed_t r, const ed_t p, const bn_t k)
void ed_mul_lwreg (ed_t r, const ed_t p, const bn_t k)
void ed_pck (ed_t r, const ed_t p)
int ed_upk (ed_t r, const ed_t p)
Detailed Description
Interface of the module for arithmetic on elliptic curves.
Definition in file relic_ed.h.
Macro Definition Documentation
RLC_ED_TABLE_BASIC
#define RLC_ED_TABLE_BASIC (RLC_FP_BITS + 1)
Size of a precomputation table using the binary method.
Definition at line 62 of file relic_ed.h.
RLC_ED_TABLE_COMBS
#define RLC_ED_TABLE_COMBS (1 << RLC_DEPTH)
Size of a precomputation table using the single-table comb method.
Definition at line 67 of file relic_ed.h.
Referenced by ed_mul_pre_combs().
RLC_ED_TABLE_COMBD
#define RLC_ED_TABLE_COMBD (1 << (RLC_DEPTH + 1))
Size of a precomputation table using the double-table comb method.
Definition at line 72 of file relic_ed.h.
RLC_ED_TABLE_LWNAF
#define RLC_ED_TABLE_LWNAF (1 << (RLC_DEPTH - 2))
Size of a precomputation table using the w-(T)NAF method.
Definition at line 77 of file relic_ed.h.
RLC_ED_TABLE
#define RLC_ED_TABLE RLC_ED_TABLE_COMBS
Size of a precomputation table using the chosen algorithm.
Definition at line 85 of file relic_ed.h.
Referenced by ed_curve_init(), and ed_param_set().
RLC_ED_TABLE_MAX
#define RLC_ED_TABLE_MAX RLC_MAX(RLC_ED_TABLE_BASIC, RLC_ED_TABLE_COMBD)
Maximum size of a precomputation table.
Definition at line 98 of file relic_ed.h.
ed_null
#define ed_null (A)
Value:
/* empty */
Initializes a point on an Edwards curve with a null value.
Parameters
[out] A - the point to initialize.
Definition at line 146 of file relic_ed.h.
Referenced by ed_cmp(), ed_map_dst(), ed_mul_basic(), ed_mul_dig(), ed_mul_gen(), ed_mul_monty(), ed_mul_naf_imp(), ed_mul_reg_imp(), ed_mul_sim_basic(), ed_mul_sim_gen(), ed_mul_sim_joint(), ed_mul_sim_lot(), ed_mul_sim_plain(), ed_mul_sim_trick(), ed_mul_slide(), ed_on_curve(), ed_param_set(), ed_sub_basic(), ed_sub_extnd(), ed_sub_projc(), and ed_write_bin().
ed_new
#define ed_new (A)
Value:
/* empty */
Calls a function to allocate a point on an Edwards curve.
Parameters
[out] A - the new point.
Exceptions
ERR_NO_MEMORY - if there is no available memory.
Definition at line 165 of file relic_ed.h.
Referenced by ed_cmp(), ed_map_dst(), ed_mul_basic(), ed_mul_dig(), ed_mul_gen(), ed_mul_monty(), ed_mul_naf_imp(), ed_mul_reg_imp(), ed_mul_sim_basic(), ed_mul_sim_gen(), ed_mul_sim_joint(), ed_mul_sim_lot(), ed_mul_sim_plain(), ed_mul_sim_trick(), ed_mul_slide(), ed_on_curve(), ed_param_set(), ed_sub_basic(), ed_sub_extnd(), ed_sub_projc(), and ed_write_bin().
ed_free
#define ed_free (A)
Value:
/* empty */
Calls a function to clean and free a point on an Edwards curve.
Parameters
[out] A - the point to free.
Definition at line 182 of file relic_ed.h.
Referenced by ed_map_dst(), ed_mul_basic(), ed_mul_dig(), ed_mul_gen(), ed_mul_monty(), ed_mul_naf_imp(), ed_mul_reg_imp(), ed_mul_sim_basic(), ed_mul_sim_gen(), ed_mul_sim_joint(), ed_mul_sim_lot(), ed_mul_sim_plain(), ed_mul_sim_trick(), ed_mul_slide(), ed_on_curve(), ed_param_set(), ed_sub_basic(), ed_sub_extnd(), ed_sub_projc(), and ed_write_bin().
ed_neg
#define ed_neg (R, P)
Value:
ed_neg_projc(R, P)
Negates an Edwards elliptic curve point. Computes R = -P.
Parameters
[out] R - the result.
[in] P - the point to negate.
Definition at line 195 of file relic_ed.h.
Referenced by ed_mul_basic(), ed_mul_combs_plain(), ed_mul_fix_basic(), ed_mul_fix_combd(), ed_mul_fix_plain(), ed_mul_monty(), ed_mul_naf_imp(), ed_mul_reg_imp(), ed_mul_sim_joint(), ed_mul_sim_lot(), ed_mul_sim_trick(), and ed_mul_slide().
ed_add
#define ed_add (R, P, Q)
Value:
ed_add_projc(R, P, Q)
Adds two Edwards elliptic curve points. Computes R = P + Q.
Parameters
[out] R - the result.
[in] P - the first point to add.
[in] Q - the second point to add.
Definition at line 208 of file relic_ed.h.
Referenced by ed_map_dst(), ed_mul_basic(), ed_mul_combs_plain(), ed_mul_dig(), ed_mul_fix_basic(), ed_mul_fix_combd(), ed_mul_fix_plain(), ed_mul_monty(), ed_mul_naf_imp(), ed_mul_pre_combd(), ed_mul_pre_combs(), ed_mul_reg_imp(), ed_mul_sim_basic(), ed_mul_sim_joint(), ed_mul_sim_lot(), ed_mul_sim_plain(), ed_mul_sim_trick(), ed_mul_slide(), and ed_tab().
ed_sub
#define ed_sub (R, P, Q)
Value:
ed_sub_projc(R, P, Q)
Subtracts an Edwards elliptic curve point from another. Computes R = P - Q.
Parameters
[out] R - the result.
[in] P - the first point.
[in] Q - the second point.
Definition at line 223 of file relic_ed.h.
Referenced by ed_mul_basic(), ed_mul_dig(), ed_mul_fix_plain(), ed_mul_naf_imp(), ed_mul_reg_imp(), ed_mul_sim_joint(), ed_mul_sim_lot(), and ed_mul_sim_plain().
ed_dbl
#define ed_dbl (R, P)
Value:
ed_dbl_projc(R, P)
Doubles an Edwards elliptic curve point. Computes R = 2P.
Parameters
[out] R - the result.
[in] P - the point to double.
Definition at line 237 of file relic_ed.h.
Referenced by ed_map_dst(), ed_mul_basic(), ed_mul_combs_plain(), ed_mul_dig(), ed_mul_fix_combd(), ed_mul_fix_plain(), ed_mul_monty(), ed_mul_naf_imp(), ed_mul_pre_basic(), ed_mul_pre_combd(), ed_mul_pre_combs(), ed_mul_reg_imp(), ed_mul_sim_joint(), ed_mul_sim_lot(), ed_mul_sim_plain(), ed_mul_sim_trick(), ed_mul_slide(), and ed_tab().
ed_mul
#define ed_mul (R, P, K)
Value:
ed_mul_lwnaf(R, P, K)
Multiplies an Edwards elliptic curve point by an integer. Computes R = [k]P.
Parameters
[out] R - the result.
[in] P - the point to multiply.
[in] K - the integer.
Definition at line 514 of file relic_ed.h.
Referenced by ed_mul_gen(), ed_mul_sim_basic(), ed_mul_sim_gen(), ed_mul_sim_inter(), ed_mul_sim_joint(), and ed_mul_sim_trick().
ed_mul_pre
#define ed_mul_pre (T, P)
Value:
ed_mul_pre_combs(T, P)
Builds a precomputation table for multiplying a fixed Edwards elliptic point.
Parameters
[out] T - the precomputation table.
[in] P - the point to multiply.
Definition at line 528 of file relic_ed.h.
Referenced by ed_param_set().
ed_mul_fix
#define ed_mul_fix (R, T, K)
Value:
ed_mul_fix_combs(R, T, K)
Multiplies a fixed Edwards elliptic point using a precomputation table. Computes R = [k]P.
Parameters
[out] R - the result.
[in] T - the precomputation table.
[in] K - the integer.
Definition at line 546 of file relic_ed.h.
Referenced by ed_mul_gen().
ed_mul_sim
#define ed_mul_sim (R, P, K, Q, M)
Value:
ed_mul_sim_inter(R, P, K, Q, M)
Multiplies and adds two Edwards elliptic curve points simultaneously. Computes R = [k]P + [m]Q.
Parameters
[out] R - the result.
[in] P - the first point to multiply.
[in] K - the first integer.
[in] Q - the second point to multiply.
[in] M - the second integer,
Definition at line 568 of file relic_ed.h.
Referenced by ed_mul_sim_gen().
Typedef Documentation
ed_t
typedef ed_st ed_t[1]
Pointer to an elliptic curve point.
Definition at line 127 of file relic_ed.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Prime elliptic curve identifiers.
Enumerator
CURVE_ED25519
ED25519 Edwards curve.
Definition at line 51 of file relic_ed.h.
Function Documentation
ed_param_set()
void ed_param_set (int param)
Configures an Edwards curve by its parameter identifier.
Parameters
- the parameter identifier.
Definition at line 71 of file relic_ed_param.c.
References ASSIGN_ED, BASIC, bn_add_dig(), bn_copy(), bn_free, bn_get_bit(), bn_new, bn_null, bn_rsh(), core_get(), CURVE_ED25519, dv_copy(), ed_copy(), ed_curve_get_tab(), ed_free, _ctx_t::ed_g, _ctx_t::ed_h, _ctx_t::ed_id, _ctx_t::ed_map_c, ed_mul_pre, ed_new, ed_null, _ctx_t::ed_pre, _ctx_t::ed_ptr, _ctx_t::ed_r, ERR_CAUGHT, ERR_NO_VALID, fp_add_dig(), fp_exp, fp_mul, fp_neg, fp_prime_back(), fp_prime_get(), fp_prime_get_2ad(), fp_read_str(), fp_set_dig(), fp_srt(), PRIME_25519, RLC_CATCH_ANY, RLC_ED_TABLE, RLC_FINALLY, RLC_FP_BYTES, RLC_FP_DIGS, RLC_POS, RLC_THROW, and RLC_TRY.
Referenced by ed_param_set_any().
ed_param_set_any()
int ed_param_set_any (void)
Configures some set of curve parameters for the current security level.
Definition at line 172 of file relic_ed_param.c.
References CURVE_ED25519, ed_param_set(), RLC_ERR, and RLC_OK.
ed_param_get()
int ed_param_get (void)
Returns the parameter identifier of the currently configured Edwards elliptic curve.
Returns
the parameter identifier.
Definition at line 182 of file relic_ed_param.c.
References core_get(), and _ctx_t::ed_id.
Referenced by ed_map_dst(), ed_param_level(), and ed_param_print().
ed_curve_get_ord()
void ed_curve_get_ord (bn_t r)
Returns the order of the group of points in the Edwards curve.
Parameters
[out] r - the returned order.
Definition at line 59 of file relic_ed_curve.c.
References bn_copy(), and core_get().
Referenced by ed_mul_combs_plain(), ed_mul_fix_combd(), ed_mul_pre_basic(), ed_mul_pre_combd(), ed_mul_pre_combs(), ed_mul_sim_trick(), and ed_rand().
ed_curve_get_gen()
void ed_curve_get_gen (ed_t g)
Returns the generator of the group of points in the curve.
Parameters
[out] g - the returned generator.
Definition at line 55 of file relic_ed_curve.c.
References core_get(), and ed_copy().
Referenced by ed_mul_gen(), and ed_mul_sim_gen().
ed_curve_get_tab()
const ed_t * ed_curve_get_tab (void)
Returns the precomputation table for the generator.
Returns
the table.
Definition at line 67 of file relic_ed_curve.c.
References core_get(), and _ctx_t::ed_ptr.
Referenced by ed_mul_gen(), ed_mul_sim_gen(), and ed_param_set().
ed_curve_get_cof()
void ed_curve_get_cof (bn_t h)
Returns the cofactor of the Edwards elliptic curve.
Parameters
[out] n - the returned cofactor.
Definition at line 63 of file relic_ed_curve.c.
References bn_copy(), and core_get().
ed_param_print()
void ed_param_print (void)
Prints the current configured Edwards elliptic curve.
Definition at line 194 of file relic_ed_param.c.
References CURVE_ED25519, ed_param_get(), and util_banner.
ed_param_level()
int ed_param_level (void)
Returns the current security level.
Definition at line 186 of file relic_ed_param.c.
References CURVE_ED25519, and ed_param_get().
Referenced by ed_map_dst().
ed_rand()
void ed_rand (ed_t p)
Assigns a random value to an Edwards elliptic curve point.
Parameters
[out] p - the Edwards elliptic curve point to assign.
Definition at line 82 of file relic_ed_util.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), ed_curve_get_ord(), ed_mul_gen(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ed_blind()
void ed_blind (ed_t r, const ed_t p)
Randomizes coordinates of a prime elliptic curve point.
Parameters
[out] r - the blinded Edwards elliptic curve point.
[in] p - the Edwards elliptic curve point to blind.
Definition at line 104 of file relic_ed_util.c.
References ed_copy(), ERR_CAUGHT, fp_free, fp_mul, fp_new, fp_null, fp_rand(), PROJC, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ed_rhs()
void ed_rhs (fp_t rhs, const fp_t p)
Computes the right-hand side of the elliptic curve equation at the x-coordinate of a certain Edwards elliptic curve point.
Parameters
[out] rhs - the result.
[in] x - the x-coordinate of the point.
Definition at line 131 of file relic_ed_util.c.
References core_get(), fp_mul, fp_sqr, and fp_sub_dig().
Referenced by ed_on_curve().
ed_copy()
void ed_copy (ed_t r, const ed_t p)
Copies the second argument to the first argument.
Parameters
[out] q - the result.
[in] p - the Edwards elliptic curve point to copy.
Definition at line 71 of file relic_ed_util.c.
References fp_copy().
Referenced by ed_blind(), ed_cmp(), ed_curve_get_gen(), ed_mul_combs_plain(), ed_mul_monty(), ed_mul_pre_basic(), ed_mul_pre_combd(), ed_mul_pre_combs(), ed_mul_sim_joint(), ed_mul_sim_trick(), ed_mul_slide(), ed_norm(), ed_param_set(), and ed_tab().
ed_cmp()
int ed_cmp (const ed_t p, const ed_t q)
Compares two Edwards elliptic curve points.
Parameters
[in] p - the first Edwards elliptic curve point.
[in] q - the second Edwards elliptic curve point.
Returns
RLC_EQ if p == q and RLC_NE if p != q.
Definition at line 44 of file relic_ed_cmp.c.
References BASIC, ed_copy(), ed_new, ed_norm(), ed_null, ep_free, ERR_CAUGHT, fp_cmp(), fp_mul, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_NE, RLC_THROW, and RLC_TRY.
ed_set_infty()
void ed_set_infty (ed_t p)
Assigns an Edwards elliptic curve point to the point at infinity.
Parameters
[out] p - the point to assign.
Definition at line 61 of file relic_ed_util.c.
References fp_set_dig(), fp_zero(), and PROJC.
Referenced by ed_curve_init(), ed_mul_basic(), ed_mul_dig(), ed_mul_fix_basic(), ed_mul_fix_combd(), ed_mul_fix_plain(), ed_mul_gen(), ed_mul_lwnaf(), ed_mul_lwreg(), ed_mul_monty(), ed_mul_naf_imp(), ed_mul_pre_combd(), ed_mul_pre_combs(), ed_mul_reg_imp(), ed_mul_sim_joint(), ed_mul_sim_lot(), ed_mul_sim_plain(), ed_mul_sim_trick(), ed_mul_slide(), ed_neg_basic(), ed_neg_projc(), ed_norm(), ed_read_bin(), ed_sub_basic(), ed_sub_extnd(), and ed_sub_projc().
ed_is_infty()
int ed_is_infty (const ed_t p)
Tests if a point on an Edwards elliptic curve is at the infinity.
Parameters
[in] p - the point to test.
Returns
1 if the point is at infinity, 0 otherise.
Definition at line 44 of file relic_ed_util.c.
References BASIC, ERR_NO_VALID, fp_cmp(), fp_cmp_dig(), fp_is_zero(), RLC_EQ, and RLC_THROW.
Referenced by ed_mul_basic(), ed_mul_dig(), ed_mul_lwnaf(), ed_mul_lwreg(), ed_mul_monty(), ed_mul_sim_gen(), ed_mul_sim_inter(), ed_mul_sim_joint(), ed_mul_sim_trick(), ed_mul_slide(), ed_neg_basic(), ed_neg_projc(), ed_norm(), ed_norm_sim(), ed_on_curve(), ed_size_bin(), and ed_write_bin().
ed_neg_basic()
void ed_neg_basic (ed_t r, const ed_t p)
Negates an Edwards elliptic curve point represented by affine coordinates.
Parameters
[out] r - the result.
[in] p - the point to negate.
Definition at line 40 of file relic_ed_neg.c.
References BASIC, ed_is_infty(), ed_set_infty(), fp_copy(), and fp_neg.
Referenced by ed_sub_basic().
ed_neg_projc()
void ed_neg_projc (ed_t r, const ed_t p)
Negates an Edwards elliptic curve point represented by projective coordinates.
Parameters
[out] r - the result.
[in] p - the point to negate.
Definition at line 56 of file relic_ed_neg.c.
References ed_is_infty(), ed_set_infty(), fp_copy(), and fp_neg.
Referenced by ed_sub_extnd(), and ed_sub_projc().
ed_add_basic()
void ed_add_basic (ed_t r, const ed_t p, const ed_t q)
Adds two Edwards elliptic curve points represented in affine coordinates.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 44 of file relic_ed_add.c.
References BASIC, core_get(), ERR_CAUGHT, fp_add, fp_add_dig(), fp_copy(), fp_free, fp_inv, fp_mul, fp_neg, fp_new, fp_null, fp_sub, fp_sub_dig(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ed_sub_basic().
ed_add_projc()
void ed_add_projc (ed_t r, const ed_t p, const ed_t q)
Adds two Edwards elliptic curve points represented in projective coordinates.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 125 of file relic_ed_add.c.
References core_get(), ERR_CAUGHT, fp_add, fp_free, fp_mul, fp_new, fp_null, fp_sqr, fp_sub, PROJC, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ed_sub_projc().
ed_add_extnd()
void ed_add_extnd (ed_t r, const ed_t p, const ed_t q)
Adds two Edwards elliptic curve points represented in exteded coordinates.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 230 of file relic_ed_add.c.
References core_get(), ERR_CAUGHT, EXTND, fp_add, fp_free, fp_mul, fp_new, fp_null, fp_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ed_sub_extnd().
ed_sub_basic()
void ed_sub_basic (ed_t r, const ed_t p, const ed_t q)
Subtracts an Edwards elliptic curve point from another, both points represented by affine coordinates..
Parameters
[out] r - the result.
[in] p - the first point.
[in] q - the second point.
Definition at line 96 of file relic_ed_add.c.
References BASIC, ed_add_basic(), ed_free, ed_neg_basic(), ed_new, ed_null, ed_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ed_sub_projc()
void ed_sub_projc (ed_t r, const ed_t p, const ed_t q)
Subtracts an Edwards elliptic curve point from another, both represented by projective coordinates.
Parameters
[out] r - the result.
[in] p - the first point.
[in] q - the second point.
Definition at line 202 of file relic_ed_add.c.
References ed_add_projc(), ed_free, ed_neg_projc(), ed_new, ed_null, ed_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ed_sub_extnd()
void ed_sub_extnd (ed_t r, const ed_t p, const ed_t q)
Subtracts an Edwards elliptic curve point from another, both represented by extended coordinates.
Parameters
[out] r - the result.
[in] p - the first point.
[in] q - the second point.
Definition at line 296 of file relic_ed_add.c.
References ed_add_extnd(), ed_free, ed_neg_projc(), ed_new, ed_null, ed_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ed_dbl_basic()
void ed_dbl_basic (ed_t r, const ed_t p)
Doubles an Edwards elliptic curve point represented in affine coordinates.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 42 of file relic_ed_dbl.c.
References BASIC, core_get(), ERR_CAUGHT, fp_add_dig(), fp_copy(), fp_dbl, fp_free, fp_inv, fp_mul, fp_neg, fp_new, fp_null, fp_sqr, fp_sub, fp_sub_dig(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ed_dbl_projc()
void ed_dbl_projc (ed_t r, const ed_t p)
Doubles an Edwards elliptic curve point represented in projective coordinates.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 95 of file relic_ed_dbl.c.
References core_get(), ERR_CAUGHT, fp_add, fp_dbl, fp_free, fp_mul, fp_new, fp_null, fp_sqr, fp_sub, PROJC, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ed_dbl_extnd()
void ed_dbl_extnd (ed_t r, const ed_t p)
Doubles an Edwards elliptic curve point represented in extended coordinates.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 168 of file relic_ed_dbl.c.
References core_get(), ERR_CAUGHT, EXTND, fp_add, fp_dbl, fp_free, fp_mul, fp_new, fp_null, fp_sqr, fp_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ed_norm()
void ed_norm (ed_t r, const ed_t p)
Converts a point to affine coordinates.
Parameters
[out] r - the result.
[in] p - the point to convert.
Definition at line 70 of file relic_ed_norm.c.
References BASIC, ed_copy(), ed_is_infty(), ed_norm_imp(), and ed_set_infty().
Referenced by ed_cmp(), ed_map_dst(), ed_mul_basic(), ed_mul_combs_plain(), ed_mul_dig(), ed_mul_fix_basic(), ed_mul_fix_combd(), ed_mul_fix_plain(), ed_mul_monty(), ed_mul_naf_imp(), ed_mul_pre_combd(), ed_mul_pre_combs(), ed_mul_reg_imp(), ed_mul_sim_basic(), ed_mul_sim_joint(), ed_mul_sim_lot(), ed_mul_sim_plain(), ed_mul_sim_trick(), ed_mul_slide(), ed_on_curve(), ed_tab(), and ed_write_bin().
ed_norm_sim()
void ed_norm_sim (ed_t * r, const ed_t * t, int n)
Converts multiple points to affine coordinates.
Parameters
[out] r - the result.
[in] t - the points to convert.
[in] n - the number of points.
Definition at line 86 of file relic_ed_norm.c.
References ed_is_infty(), ed_norm_imp(), ERR_CAUGHT, ERR_NO_MEMORY, fp_copy(), fp_free, fp_inv_sim(), fp_new, fp_null, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by ed_mul_pre_basic(), ed_mul_pre_combd(), ed_mul_pre_combs(), ed_mul_sim_joint(), ed_mul_sim_trick(), ed_mul_slide(), and ed_tab().
ed_map()
void ed_map (ed_t p, const uint8_t * msg, size_t len)
Maps a byte array to a point in an Edwards elliptic curve.
Parameters
[out] p - the result.
[in] msg - the byte array to map.
[in] len - the array length in bytes.
Definition at line 258 of file relic_ed_map.c.
References ed_map_dst().
ed_map_dst()
void ed_map_dst (ed_t p, const uint8_t * msg, size_t len, const uint8_t * dst, size_t dst_len)
Maps a byte array to a point in an Edwards elliptic curve using an explicit domain separation tag.
Parameters
[out] p - the result.
[in] msg - the byte array to map.
[in] len - the array length in bytes.
[in] dst - the domain separation tag.
[in] dst_len - the domain separation tag length in bytes.
Definition at line 190 of file relic_ed_map.c.
References BASIC, bn_free, bn_new, bn_null, CURVE_ED25519, ed_add, ed_dbl, ed_free, ED_MAP_CONVERT_BYTES, ed_map_ell2_5mod8(), ed_new, ed_norm(), ed_null, ed_param_get(), ed_param_level(), ERR_CAUGHT, ERR_NO_VALID, fp_free, fp_mul, fp_new, fp_null, FP_PRIME, md_xmd, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by ed_map().
ed_curve_init()
void ed_curve_init (void)
Initializes the Edwards elliptic curve arithmetic module.
Definition at line 35 of file relic_ed_curve.c.
References bn_make(), core_get(), _ctx_t::ed_g, _ctx_t::ed_h, _ctx_t::ed_pre, _ctx_t::ed_ptr, _ctx_t::ed_r, ed_set_infty(), RLC_ED_TABLE, and RLC_FP_DIGS.
Referenced by core_init().
ed_curve_clean()
void ed_curve_clean (void)
Finalizes the Edwards elliptic curve arithmetic module.
Definition at line 47 of file relic_ed_curve.c.
References bn_clean(), core_get(), _ctx_t::ed_h, and _ctx_t::ed_r.
Referenced by core_clean().
ed_mul_pre_basic()
void ed_mul_pre_basic (ed_t * t, const ed_t p)
Builds a precomputation table for multiplying a fixed Edwards elliptic point using the binary method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 162 of file relic_ed_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, ed_copy(), ed_curve_get_ord(), ed_dbl, ed_norm_sim(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ed_mul_pre_yaowi()
void ed_mul_pre_yaowi (ed_t * t, const ed_t p)
Builds a precomputation table for multiplying a fixed Edwards elliptic point using Yao's windowing method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
ed_mul_pre_nafwi()
void ed_mul_pre_nafwi (ed_t * t, const ed_t p)
Builds a precomputation table for multiplying a fixed Edwards elliptic point using the NAF windowing method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
ed_mul_pre_combs()
void ed_mul_pre_combs (ed_t * t, const ed_t p)
Builds a precomputation table for multiplying a fixed Edwards elliptic point using the single-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 210 of file relic_ed_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, ed_add, ed_copy(), ed_curve_get_ord(), ed_dbl, ed_norm(), ed_norm_sim(), ed_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_ED_TABLE_COMBS, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ed_mul_pre_combd()
void ed_mul_pre_combd (ed_t * t, const ed_t p)
Builds a precomputation table for multiplying a fixed Edwards elliptic point using the double-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 256 of file relic_ed_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, ed_add, ed_copy(), ed_curve_get_ord(), ed_dbl, ed_norm(), ed_norm_sim(), ed_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ed_mul_pre_lwnaf()
void ed_mul_pre_lwnaf (ed_t * t, const ed_t p)
Builds a precomputation table for multiplying a fixed Edwards elliptic point using the w-(T)NAF method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 363 of file relic_ed_mul_fix.c.
References ed_tab(), and RLC_DEPTH.
ed_mul_fix_basic()
void ed_mul_fix_basic (ed_t r, const ed_t * t, const bn_t k)
Multiplies a fixed Edwards elliptic point using a precomputation table and the binary method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 187 of file relic_ed_mul_fix.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), ed_add, ed_neg, ed_norm(), ed_set_infty(), and RLC_NEG.
ed_mul_fix_yaowi()
void ed_mul_fix_yaowi (ed_t r, const ed_t * t, const bn_t k)
Multiplies a fixed Edwards elliptic point using a precomputation table and Yao's windowing method
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
ed_mul_fix_nafwi()
void ed_mul_fix_nafwi (ed_t r, const ed_t * t, const bn_t k)
Multiplies a fixed Edwards elliptic point using a precomputation table and the w-(T)NAF method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
ed_mul_fix_combs()
void ed_mul_fix_combs (ed_t r, const ed_t * t, const bn_t k)
Multiplies a fixed Edwards elliptic point using a precomputation table and the single-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 249 of file relic_ed_mul_fix.c.
References ed_mul_combs_plain().
ed_mul_fix_combd()
void ed_mul_fix_combd (ed_t r, const ed_t * t, const bn_t k)
Multiplies a fixed Edwards elliptic point using a precomputation table and the double-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 304 of file relic_ed_mul_fix.c.
References bn_bits(), bn_free, bn_get_bit(), bn_new, bn_null, bn_sign(), ed_add, ed_curve_get_ord(), ed_dbl, ed_neg, ed_norm(), ed_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
ed_mul_fix_lwnaf()
void ed_mul_fix_lwnaf (ed_t r, const ed_t * t, const bn_t k)
Multiplies a fixed Edwards elliptic point using a precomputation table and the w-(T)NAF method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 367 of file relic_ed_mul_fix.c.
References ed_mul_fix_plain().
ed_mul_fix_lwnaf_mixed()
void ed_mul_fix_lwnaf_mixed (ed_t r, const ed_t * t, const bn_t k)
Multiplies a fixed Edwards elliptic point using a precomputation table and the w-(T)NAF mixed coordinate method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
ed_mul_gen()
void ed_mul_gen (ed_t r, const bn_t k)
Multiplies the generator of an Edwards elliptic curve by an integer.
Parameters
[out] r - the result.
[in] k - the integer.
Definition at line 402 of file relic_ed_mul.c.
References bn_is_zero(), ed_curve_get_gen(), ed_curve_get_tab(), ed_free, ed_mul, ed_mul_fix, ed_new, ed_null, ed_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ed_mul_sim_gen(), and ed_rand().
ed_mul_dig()
void ed_mul_dig (ed_t r, const ed_t p, dig_t k)
Multiplies an Edwards elliptic curve point by a small positive integer.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 428 of file relic_ed_mul.c.
References bn_free, bn_new, bn_null, bn_rec_naf(), bn_set_dig(), ed_add, ed_dbl, ed_free, ed_is_infty(), ed_new, ed_norm(), ed_null, ed_set_infty(), ed_sub, ERR_CAUGHT, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ed_mul_sim_basic()
void ed_mul_sim_basic (ed_t r, const ed_t p, const bn_t k, const ed_t q, const bn_t m)
Multiplies and adds two Edwards elliptic curve points simultaneously using scalar multiplication and point addition.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 150 of file relic_ed_mul_sim.c.
References ed_add, ed_free, ed_mul, ed_new, ed_norm(), ed_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ed_mul_sim_trick()
void ed_mul_sim_trick (ed_t r, const ed_t p, const bn_t k, const ed_t q, const bn_t m)
Multiplies and adds two Edwards elliptic curve points simultaneously using shamir's trick.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 175 of file relic_ed_mul_sim.c.
References bn_free, bn_is_zero(), bn_new, bn_null, bn_rec_win(), bn_sign(), ed_add, ed_copy(), ed_curve_get_ord(), ed_dbl, ed_free, ed_is_infty(), ed_mul, ed_neg, ed_new, ed_norm(), ed_norm_sim(), ed_null, ed_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_CEIL, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
ed_mul_sim_inter()
void ed_mul_sim_inter (ed_t r, const ed_t p, const bn_t k, const ed_t q, const bn_t m)
Multiplies and adds two Edwards elliptic curve points simultaneously using interleaving of NAFs.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 267 of file relic_ed_mul_sim.c.
References bn_is_zero(), ed_is_infty(), ed_mul, and ed_mul_sim_plain().
ed_mul_sim_joint()
void ed_mul_sim_joint (ed_t r, const ed_t p, const bn_t k, const ed_t q, const bn_t m)
Multiplies and adds two Edwards elliptic curve points simultaneously using Solinas' Joint Sparse Form.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 286 of file relic_ed_mul_sim.c.
References bn_bits(), bn_is_zero(), bn_rec_jsf(), bn_sign(), ed_add, ed_copy(), ed_dbl, ed_free, ed_is_infty(), ed_mul, ed_neg, ed_new, ed_norm(), ed_norm_sim(), ed_null, ed_set_infty(), ed_sub, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, and RLC_TRY.
ed_mul_sim_lot()
void ed_mul_sim_lot (ed_t r, const ed_t p[], const bn_t k[], int n)
Multiplies and adds multiple Edwards elliptic curve points simultaneously. Computes R = \Sum_i=0..n [k_i]P_i.
Parameters
[out] r - the result.
[out] p - the elements to multiply.
[out] k - the integer scalars.
[out] n - the number of elements to multiply.
Definition at line 394 of file relic_ed_mul_sim.c.
References bn_bits(), bn_rec_naf(), bn_sign(), ed_add, ed_dbl, ed_free, ed_neg, ed_new, ed_norm(), ed_null, ed_set_infty(), ed_sub, ERR_CAUGHT, ERR_NO_MEMORY, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_MAX, RLC_NEG, RLC_THROW, and RLC_TRY.
ed_mul_sim_gen()
void ed_mul_sim_gen (ed_t r, const bn_t k, const ed_t q, const bn_t m)
Multiplies and adds the generator and an Edwards elliptic curve point simultaneously. Computes R = [k]G + [m]Q.
Parameters
[out] r - the result.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer.
Definition at line 361 of file relic_ed_mul_sim.c.
References bn_is_zero(), ed_curve_get_gen(), ed_curve_get_tab(), ed_free, ed_is_infty(), ed_mul, ed_mul_gen(), ed_mul_sim, ed_mul_sim_plain(), ed_new, ed_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ed_tab()
void ed_tab (ed_t * t, const ed_t p, int w)
Builds a precomputation table for multiplying a random Edwards elliptic point.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
[in] w - the window width.
Definition at line 175 of file relic_ed_util.c.
References ed_add, ed_copy(), ed_dbl, ed_norm(), and ed_norm_sim().
Referenced by ed_mul_naf_imp(), ed_mul_pre_lwnaf(), ed_mul_reg_imp(), and ed_mul_sim_plain().
ed_print()
void ed_print (const ed_t p)
Prints an Edwards elliptic curve point.
Parameters
[in] p - the Edwards elliptic curve point to print.
Definition at line 192 of file relic_ed_util.c.
References fp_print().
ed_on_curve()
int ed_on_curve (const ed_t p)
Tests if a point is in the curve.
Parameters
[in] p - the point to test.
Definition at line 138 of file relic_ed_util.c.
References core_get(), ed_free, ed_is_infty(), ed_new, ed_norm(), ed_null, ed_rhs(), ERR_CAUGHT, fp_cmp(), fp_is_zero(), fp_mul, fp_sqr, fp_sub_dig(), RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ed_read_bin().
ed_size_bin()
size_t ed_size_bin (const ed_t a, int pack)
Returns the number of bytes necessary to store an Edwards elliptic curve point with optional point compression.
Parameters
[in] a - the Edwards field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 201 of file relic_ed_util.c.
References ed_is_infty(), and RLC_FP_BYTES.
ed_read_bin()
void ed_read_bin (ed_t a, const uint8_t * bin, size_t len)
Reads an Edwards elliptic curve point from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_VALID - if the encoded point is invalid.
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 216 of file relic_ed_util.c.
References BASIC, ed_on_curve(), ed_set_infty(), ed_upk(), ERR_NO_BUFFER, ERR_NO_VALID, fp_mul, fp_read_bin(), fp_set_bit(), fp_set_dig(), fp_sqr, fp_zero(), RLC_FP_BYTES, and RLC_THROW.
ed_write_bin()
void ed_write_bin (uint8_t * bin, size_t len, const ed_t a, int pack)
Writes an Edwards elliptic curve point to a byte vector in big-endian format with optional point compression.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the Edwards elliptic curve point to write.
[in] pack - the flag to indicate point compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 271 of file relic_ed_util.c.
References ed_free, ed_is_infty(), ed_new, ed_norm(), ed_null, ed_pck(), ERR_CAUGHT, ERR_NO_BUFFER, fp_get_bit(), fp_write_bin(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.
ed_mul_basic()
void ed_mul_basic (ed_t r, const ed_t p, const bn_t k)
Multiplies an Edwards elliptic point by an integer using the binary method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 203 of file relic_ed_mul.c.
References bn_bits(), bn_is_zero(), bn_rec_naf(), bn_sign(), ed_add, ed_dbl, ed_free, ed_is_infty(), ed_neg, ed_new, ed_norm(), ed_null, ed_set_infty(), ed_sub, ERR_CAUGHT, ERR_NO_BUFFER, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.
ed_mul_slide()
void ed_mul_slide (ed_t r, const ed_t p, const bn_t k)
Multiplies an Edwards elliptic point by an integer using the sliding window method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 254 of file relic_ed_mul.c.
References bn_is_zero(), bn_rec_slw(), bn_sign(), ed_add, ed_copy(), ed_dbl, ed_free, ed_is_infty(), ed_neg, ed_new, ed_norm(), ed_norm_sim(), ed_null, ed_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_THROW, RLC_TRY, RLC_WIDTH, and util_bits_dig().
ed_mul_monty()
void ed_mul_monty (ed_t r, const ed_t p, const bn_t k)
Multiplies an Edwards elliptic point by an integer using the constant-time Montgomery ladder point multiplication method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 324 of file relic_ed_mul.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), dv_swap_sec(), ed_add, ed_copy(), ed_dbl, ed_free, ed_is_infty(), ed_neg, ed_new, ed_norm(), ed_null, ed_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_NEG, RLC_THROW, and RLC_TRY.
ed_mul_lwnaf()
void ed_mul_lwnaf (ed_t r, const ed_t p, const bn_t k)
Multiplies an Edwards elliptic point by an integer using the w-NAF method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 378 of file relic_ed_mul.c.
References bn_is_zero(), ed_is_infty(), ed_mul_naf_imp(), and ed_set_infty().
ed_mul_lwreg()
void ed_mul_lwreg (ed_t r, const ed_t p, const bn_t k)
Multiplies an Edwards elliptic point by an integer using a regular method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 391 of file relic_ed_mul.c.
References bn_is_zero(), ed_is_infty(), ed_mul_reg_imp(), and ed_set_infty().
ed_pck()
void ed_pck (ed_t r, const ed_t p)
Compresses a point.
Parameters
[out] r - the result.
[in] p - the point to compress.
Definition at line 38 of file relic_ed_pck.c.
References BASIC, fp_copy(), fp_get_bit(), fp_norm(), fp_set_bit(), fp_set_dig(), and fp_zero().
Referenced by ed_write_bin().
ed_upk()
int ed_upk (ed_t r, const ed_t p)
Decompresses a point.
Parameters
[out] r - the result.
[in] p - the point to decompress.
Returns
if the decompression was successful
Definition at line 48 of file relic_ed_pck.c.
References BASIC, core_get(), ERR_CAUGHT, fp_copy(), fp_free, fp_get_bit(), fp_inv, fp_mul, fp_neg, fp_new, fp_norm(), fp_null, fp_set_dig(), fp_sqr, fp_srt(), fp_sub, fp_sub_dig(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ed_read_bin().