RELIC: src/bn/relic_bn_prime.c File Reference
relic_bn_prime.c File Reference
Multiple precision integer arithmetic
#include "relic_core.h"
Macros
#define BASIC_TESTS ((int)(sizeof(primes)/sizeof(dig_t)))
Functions
int bn_is_prime (const bn_t a)
int bn_is_prime_basic (const bn_t a)
int bn_is_prime_rabin (const bn_t a)
int bn_is_prime_solov (const bn_t a)
void bn_gen_prime_basic (bn_t a, size_t bits)
void bn_gen_prime_safep (bn_t a, size_t bits)
void bn_gen_prime_stron (bn_t a, size_t bits)
int bn_gen_prime_factor (bn_t a, bn_t b, size_t abits, size_t bbits)
Variables
static const dig_t primes []
Detailed Description
Implementation of the prime number generation and testing functions.
Strong prime generation is based on Gordon's Algorithm, taken from Handbook of Applied Cryptography.
Definition in file relic_bn_prime.c.
Macro Definition Documentation
BASIC_TESTS
#define BASIC_TESTS ((int)(sizeof(primes)/sizeof(dig_t)))
Number of trial division tests.
Definition at line 44 of file relic_bn_prime.c.
Referenced by bn_is_prime_basic().
Function Documentation
bn_is_prime()
int bn_is_prime (const bn_t a)
Tests if a number is a probable prime.
Parameters
[in] a - the multiple precision integer to test.
Returns
1 if a is prime, 0 otherwise.
Definition at line 173 of file relic_bn_prime.c.
References bn_is_prime_basic(), and bn_is_prime_rabin().
Referenced by bn_gen_prime_basic(), bn_gen_prime_factor(), bn_gen_prime_safep(), bn_gen_prime_stron(), cp_bdpe_gen(), cp_rsapsi_ans(), cp_rsapsi_ask(), cp_shipsi_ans(), cp_shipsi_ask(), and fp_param_set_any_dense().
bn_is_prime_basic()
int bn_is_prime_basic (const bn_t a)
Tests if a number is prime using a series of trial divisions.
Parameters
[in] a - the number to test.
Returns
1 if a is a probable prime, 0 otherwise.
Definition at line 190 of file relic_bn_prime.c.
References BASIC_TESTS, bn_cmp_dig(), bn_mod_dig(), primes, and RLC_EQ.
Referenced by bn_is_prime(), and cp_bdpe_gen().
bn_is_prime_rabin()
int bn_is_prime_rabin (const bn_t a)
Tests if a number a > 2 is prime using the Miller-Rabin test with probability 2^(-80) of error.
Parameters
[in] a - the number to test.
Returns
1 if a is a probable prime, 0 otherwise.
Definition at line 211 of file relic_bn_prime.c.
References bn_bits(), bn_cmp(), bn_cmp_dig(), bn_copy(), bn_free, bn_is_even(), bn_is_zero(), bn_mod, bn_mxp, bn_new, bn_null, bn_rsh(), bn_set_dig(), bn_sqr, bn_sub_dig(), ERR_CAUGHT, primes, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_LT, RLC_THROW, and RLC_TRY.
Referenced by bn_is_prime().
bn_is_prime_solov()
int bn_is_prime_solov (const bn_t a)
Tests if a number a > 2 is prime using the Solovay-Strassen test with probability 2^(-80) of error.
Parameters
[in] a - the number to test.
Returns
1 if a is a probable prime, 0 otherwise.
Definition at line 336 of file relic_bn_prime.c.
References bn_bits(), bn_cmp(), bn_cmp_dig(), bn_copy(), bn_free, bn_mod, bn_mxp, bn_neg(), bn_new, bn_null, bn_rand(), bn_rsh(), bn_set_dig(), bn_smb_jac(), bn_sub_dig(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_LT, RLC_POS, RLC_THROW, and RLC_TRY.
bn_gen_prime_basic()
void bn_gen_prime_basic (bn_t a, size_t bits)
Generates a probable prime number.
Parameters
[out] a - the result.
[in] bits - the length of the number in bits.
Definition at line 404 of file relic_bn_prime.c.
References bn_bits(), bn_is_prime(), bn_rand(), and RLC_POS.
bn_gen_prime_safep()
void bn_gen_prime_safep (bn_t a, size_t bits)
Generates a probable prime number a with (a - 1)/2 also prime.
Parameters
[out] a - the result.
[in] bits - the length of the number in bits.
Definition at line 419 of file relic_bn_prime.c.
References bn_add_dig(), bn_bits(), bn_is_prime(), bn_lsh(), bn_rand(), bn_rsh(), bn_sub_dig(), and RLC_POS.
bn_gen_prime_stron()
void bn_gen_prime_stron (bn_t a, size_t bits)
Generates a probable prime number with (a - 1)/2, (a + 1)/2 and ((a - 1)/2 - 1)/2 also prime.
Parameters
[out] a - the result.
[in] bits - the length of the number in bits.
Definition at line 443 of file relic_bn_prime.c.
References bn_add(), bn_add_dig(), bn_bits(), bn_dbl(), bn_free, bn_is_prime(), bn_mul, bn_mul_dig(), bn_mxp, bn_new, bn_null, bn_rand(), bn_sub_dig(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_POS, RLC_THROW, and RLC_TRY.
bn_gen_prime_factor()
int bn_gen_prime_factor (bn_t a, bn_t b, size_t abits, size_t bbits)
Generates a probable prime number b, with (b-1) divisible by a probable large prime a.
Parameters
[out] a - the prime factor of (b-1).
[out] b - the prime result b.
[in] abits - the length of the factor a in bits.
[in] bbits - the length of the result in bits.
Definition at line 522 of file relic_bn_prime.c.
References bn_add(), bn_add_dig(), bn_bits(), bn_free, bn_gen_prime, bn_is_prime(), bn_lsh(), bn_mul, bn_new, bn_null, bn_rand(), bn_set_dig(), RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, RLC_POS, and RLC_TRY.
Referenced by cp_shpe_gen().
Variable Documentation
primes
const dig_t primes[] static
Small prime numbers table.
Definition at line 49 of file relic_bn_prime.c.
Referenced by bn_is_prime_basic(), and bn_is_prime_rabin().