RELIC: src/ed/relic_ed_mul_fix.c File Reference
relic_ed_mul_fix.c File Reference
Edwards curves over prime fields.
#include "relic_core.h"
Functions
static void ed_mul_fix_plain (ed_t r, const ed_t *t, const bn_t k)
static void ed_mul_combs_plain (ed_t r, const ed_t *t, const bn_t k)
void ed_mul_pre_basic (ed_t *t, const ed_t p)
void ed_mul_fix_basic (ed_t r, const ed_t *t, const bn_t k)
void ed_mul_pre_combs (ed_t *t, const ed_t p)
void ed_mul_fix_combs (ed_t r, const ed_t *t, const bn_t k)
void ed_mul_pre_combd (ed_t *t, const ed_t p)
void ed_mul_fix_combd (ed_t r, const ed_t *t, const bn_t k)
void ed_mul_pre_lwnaf (ed_t *t, const ed_t p)
void ed_mul_fix_lwnaf (ed_t r, const ed_t *t, const bn_t k)
Detailed Description
Implementation of fixed point multiplication on prime elliptic Edwards curves.
Version
$Id$
Definition in file relic_ed_mul_fix.c.
Function Documentation
ed_mul_fix_plain()
static void ed_mul_fix_plain (ed_t r, const ed_t * t, const bn_t k) static
Multiplies a binary elliptic curve point by an integer using the w-NAF mixed coordinate method.
Parameters
[out] r - the result.
[in] t - the precomputed table.
[in] k - the integer.
Definition at line 49 of file relic_ed_mul_fix.c.
References bn_rec_naf(), bn_sign(), ed_add, ed_dbl, ed_neg, ed_norm(), ed_set_infty(), ed_sub, EXTND, RLC_DEPTH, RLC_FP_BITS, and RLC_NEG.
Referenced by ed_mul_fix_lwnaf().
ed_mul_combs_plain()
static void ed_mul_combs_plain (ed_t r, const ed_t * t, const bn_t k) static
Multiplies a prime elliptic curve point by an integer using the COMBS method.
Parameters
[out] r - the result.
[in] t - the precomputed table.
[in] k - the integer.
Definition at line 99 of file relic_ed_mul_fix.c.
References bn_bits(), bn_free, bn_get_bit(), bn_new, bn_null, bn_sign(), ed_add, ed_copy(), ed_curve_get_ord(), ed_dbl, ed_neg, ed_norm(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by ed_mul_fix_combs().
ed_mul_pre_basic()
void ed_mul_pre_basic (ed_t * t, const ed_t p)
Builds a precomputation table for multiplying a fixed Edwards elliptic point using the binary method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 162 of file relic_ed_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, ed_copy(), ed_curve_get_ord(), ed_dbl, ed_norm_sim(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ed_mul_fix_basic()
void ed_mul_fix_basic (ed_t r, const ed_t * t, const bn_t k)
Multiplies a fixed Edwards elliptic point using a precomputation table and the binary method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 187 of file relic_ed_mul_fix.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), ed_add, ed_neg, ed_norm(), ed_set_infty(), and RLC_NEG.
ed_mul_pre_combs()
void ed_mul_pre_combs (ed_t * t, const ed_t p)
Builds a precomputation table for multiplying a fixed Edwards elliptic point using the single-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 210 of file relic_ed_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, ed_add, ed_copy(), ed_curve_get_ord(), ed_dbl, ed_norm(), ed_norm_sim(), ed_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_ED_TABLE_COMBS, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ed_mul_fix_combs()
void ed_mul_fix_combs (ed_t r, const ed_t * t, const bn_t k)
Multiplies a fixed Edwards elliptic point using a precomputation table and the single-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 249 of file relic_ed_mul_fix.c.
References ed_mul_combs_plain().
ed_mul_pre_combd()
void ed_mul_pre_combd (ed_t * t, const ed_t p)
Builds a precomputation table for multiplying a fixed Edwards elliptic point using the double-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 256 of file relic_ed_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, ed_add, ed_copy(), ed_curve_get_ord(), ed_dbl, ed_norm(), ed_norm_sim(), ed_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ed_mul_fix_combd()
void ed_mul_fix_combd (ed_t r, const ed_t * t, const bn_t k)
Multiplies a fixed Edwards elliptic point using a precomputation table and the double-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 304 of file relic_ed_mul_fix.c.
References bn_bits(), bn_free, bn_get_bit(), bn_new, bn_null, bn_sign(), ed_add, ed_curve_get_ord(), ed_dbl, ed_neg, ed_norm(), ed_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
ed_mul_pre_lwnaf()
void ed_mul_pre_lwnaf (ed_t * t, const ed_t p)
Builds a precomputation table for multiplying a fixed Edwards elliptic point using the w-(T)NAF method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 363 of file relic_ed_mul_fix.c.
References ed_tab(), and RLC_DEPTH.
ed_mul_fix_lwnaf()
void ed_mul_fix_lwnaf (ed_t r, const ed_t * t, const bn_t k)
Multiplies a fixed Edwards elliptic point using a precomputation table and the w-(T)NAF method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 367 of file relic_ed_mul_fix.c.
References ed_mul_fix_plain().