RELIC: src/cp/relic_cp_rabin.c File Reference
relic_cp_rabin.c File Reference
Cryptographic protocols
#include "relic.h"
Macros
#define RABIN_PAD_LEN 8
#define RABIN_PAD (0xFF)
Functions
int cp_rabin_gen (rabin_t pub, rabin_t prv, size_t bits)
int cp_rabin_enc (uint8_t *out, size_t *out_len, const uint8_t *in, size_t in_len, const rabin_t pub)
int cp_rabin_dec (uint8_t *out, size_t *out_len, const uint8_t *in, size_t in_len, const rabin_t prv)
Detailed Description
Implementation of the Rabin cryptosystem.
Definition in file relic_cp_rabin.c.
Macro Definition Documentation
RABIN_PAD_LEN
#define RABIN_PAD_LEN 8
Length in bytes of added redundancy.
Definition at line 41 of file relic_cp_rabin.c.
Referenced by cp_rabin_dec(), and cp_rabin_enc().
RABIN_PAD
#define RABIN_PAD (0xFF)
Byte used as padding unit in ciphertext.
Definition at line 46 of file relic_cp_rabin.c.
Referenced by cp_rabin_dec(), and cp_rabin_enc().
Function Documentation
cp_rabin_gen()
int cp_rabin_gen (rabin_t pub, rabin_t prv, size_t bits)
Generates a key pair for the Rabin cryptosystem.
Parameters
[out] pub - the public key.
[out] prv - the private key,
[in] bits - the key length in bits.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 52 of file relic_cp_rabin.c.
References bn_cmp(), bn_cmp_dig(), bn_copy(), bn_free, bn_gcd_ext, bn_gen_prime, bn_mod_2b(), bn_mul, bn_new, bn_null, RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FINALLY, RLC_LT, RLC_OK, and RLC_TRY.
cp_rabin_enc()
int cp_rabin_enc (uint8_t * out, size_t * out_len, const uint8_t * in, size_t in_len, const rabin_t pub)
Encrypts using the Rabin cryptosystem.
Parameters
[out] out - the output buffer.
[in,out] out_len - the buffer capacity and number of bytes written.
[in] in - the input buffer.
[in] in_len - the number of bytes to encrypt.
[in] pub - the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 98 of file relic_cp_rabin.c.
References bn_add(), bn_add_dig(), bn_free, bn_lsh(), bn_mod, bn_mod_2b(), bn_new, bn_null, bn_read_bin(), bn_size_bin(), bn_sqr, bn_write_bin(), bn_zero(), RABIN_PAD, RABIN_PAD_LEN, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_rabin_dec()
int cp_rabin_dec (uint8_t * out, size_t * out_len, const uint8_t * in, size_t in_len, const rabin_t prv)
Decrypts using the Rabin cryptosystem.
Parameters
[out] out - the output buffer.
[in,out] out_len - the buffer capacity and number of bytes written.
[in] in - the input buffer.
[in] in_len - the number of bytes to decrypt.
[in] prv - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 150 of file relic_cp_rabin.c.
References bn_add(), bn_add_dig(), bn_cmp(), bn_free, bn_is_zero(), bn_mod, bn_mod_2b(), bn_mul, bn_mxp, bn_new, bn_null, bn_read_bin(), bn_rsh(), bn_sign(), bn_size_bin(), bn_sub(), bn_write_bin(), RABIN_PAD, RABIN_PAD_LEN, RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FINALLY, RLC_NEG, RLC_OK, and RLC_TRY.