RELIC: src/cp/relic_cp_ecdh.c File Reference
relic_cp_ecdh.c File Reference
Cryptographic protocols
#include "relic.h"
Functions
int cp_ecdh_gen (bn_t d, ec_t q)
int cp_ecdh_key (uint8_t *key, size_t key_len, const bn_t d, const ec_t q)
Detailed Description
Implementation of the ECDH protocol.
Definition in file relic_cp_ecdh.c.
Function Documentation
cp_ecdh_gen()
int cp_ecdh_gen (bn_t d, ec_t q)
Generates an ECDH key pair.
Parameters
[out] d - the private key.
[in] q - the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_ecdh.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), ec_curve_get_ord, ec_mul_gen, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_ecdh_key()
int cp_ecdh_key (uint8_t * key, size_t key_len, const bn_t d, const ec_t q)
Derives a shared secret using ECDH.
Parameters
[out] key - the shared key.
[int] key_len - the intended shared key length in bytes.
[in] d - the private key.
[in] q - the point received from the other party.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 61 of file relic_cp_ecdh.c.
References bn_bits(), bn_free, bn_new, bn_null, bn_size_bin(), bn_write_bin(), ec_curve_get_cof, ec_free, ec_get_x, ec_is_infty, ec_mul, ec_mul_dig, ec_new, ec_null, ERR_CAUGHT, md_kdf(), RLC_CATCH_ANY, RLC_DIG, RLC_ERR, RLC_FC_BYTES, RLC_FINALLY, RLC_OK, RLC_THROW, and RLC_TRY.