RELIC: src/epx/relic_ep2_add.c File Reference
relic_ep2_add.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
#include "relic_ep_add_tmpl.h"
Functions
TMPL_ADD_BASIC_IMP (ep2, fp2)
TMPL_ADD_PROJC_MIX (ep2, fp2)
TMPL_ADD_PROJC_IMP (ep2, fp2)
TMPL_ADD_JACOB_MIX (ep2, fp2)
TMPL_ADD_JACOB_IMP (ep2, fp2)
void ep2_add_basic (ep2_t r, const ep2_t p, const ep2_t q)
void ep2_add_slp_basic (ep2_t r, fp2_t s, const ep2_t p, const ep2_t q)
void ep2_add_projc (ep2_t r, const ep2_t p, const ep2_t q)
void ep2_add_jacob (ep2_t r, const ep2_t p, const ep2_t q)
void ep2_sub (ep2_t r, const ep2_t p, const ep2_t q)
Detailed Description
Implementation of addition on prime elliptic curves over a quadratic extension field.
Definition in file relic_ep2_add.c.
Function Documentation
TMPL_ADD_BASIC_IMP()
TMPL_ADD_BASIC_IMP (ep2 , fp2)
Adds two points represented in affine coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the first point to add.
[in] q - the second point to add.
TMPL_ADD_PROJC_MIX()
TMPL_ADD_PROJC_MIX (ep2 , fp2)
Adds a point represented in homogeneous coordinates to a point represented in affine coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[in] p - the projective point.
[in] q - the affine point.
TMPL_ADD_PROJC_IMP()
TMPL_ADD_PROJC_IMP (ep2 , fp2)
Adds two points represented in homogeneous coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
TMPL_ADD_JACOB_MIX()
TMPL_ADD_JACOB_MIX (ep2 , fp2)
Adds a point represented in Jacobian coordinates to a point represented in affine coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[in] p - the projective point.
[in] q - the affine point.
TMPL_ADD_JACOB_IMP()
TMPL_ADD_JACOB_IMP (ep2 , fp2)
Adds two points represented in Jacobian coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
ep2_add_basic()
void ep2_add_basic (ep2_t r, const ep2_t p, const ep2_t q)
Adds to points represented in affine coordinates in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 109 of file relic_ep2_add.c.
References ep2_copy(), and ep2_is_infty().
ep2_add_slp_basic()
void ep2_add_slp_basic (ep2_t r, fp2_t s, const ep2_t p, const ep2_t q)
Adds to points represented in affine coordinates in an elliptic curve over a quadratic extension and returns the computed slope.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 123 of file relic_ep2_add.c.
References ep2_copy(), and ep2_is_infty().
Referenced by pp_add_k12_basic(), and pp_add_k8_basic().
ep2_add_projc()
void ep2_add_projc (ep2_t r, const ep2_t p, const ep2_t q)
Adds two points represented in projective coordinates in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 141 of file relic_ep2_add.c.
References ep2_copy(), and ep2_is_infty().
ep2_add_jacob()
void ep2_add_jacob (ep2_t r, const ep2_t p, const ep2_t q)
Adds two points represented in Jacobian coordinates in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 159 of file relic_ep2_add.c.
References ep2_copy(), and ep2_is_infty().
ep2_sub()
void ep2_sub (ep2_t r, const ep2_t p, const ep2_t q)
Subtracts a point in an elliptic curve over a quadratic extension from another.
Parameters
[out] r - the result.
[in] p - the first point.
[in] q - the point to subtract.
Definition at line 175 of file relic_ep2_add.c.
References ep2_add, ep2_free, ep2_neg(), ep2_new, ep2_null, ep2_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep2_mul_basic(), ep2_mul_cof_b12(), ep2_mul_dig(), ep2_mul_fix_plain(), ep2_mul_gls_imp(), ep2_mul_naf_imp(), ep2_mul_reg_gls(), ep2_mul_reg_imp(), ep2_mul_sim_endom(), ep2_mul_sim_joint(), ep2_mul_sim_lot(), and ep2_mul_sim_plain().