RELIC: src/pp/relic_pp_add_k48.c File Reference
relic_pp_add_k48.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_util.h"
Functions
void pp_add_k48_basic (fp48_t l, ep8_t r, const ep8_t q, const ep_t p)
void pp_add_k48_projc (fp48_t l, ep8_t r, const ep8_t q, const ep_t p)
Detailed Description
Implementation of Miller addition for curves with embedding degree 48.
Definition in file relic_pp_add_k48.c.
Function Documentation
pp_add_k48_basic()
void pp_add_k48_basic (fp48_t l, ep8_t r, const ep8_t q, const ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 48 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 42 of file relic_pp_add_k48.c.
References ep8_add_slp_basic(), ep8_copy(), ep8_free, ep8_new, ep8_null, ERR_CAUGHT, fp48_zero(), fp8_free, fp8_mul, fp8_new, fp8_null, fp8_sub(), fp_mul, fp_neg, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_add_k48_projc()
void pp_add_k48_projc (fp48_t l, ep8_t r, const ep8_t q, const ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 48 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 84 of file relic_pp_add_k48.c.
References ERR_CAUGHT, fp8_add(), fp8_free, fp8_mul, fp8_new, fp8_null, fp8_sqr, fp8_sub(), fp_mul, fp_neg, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.