RELIC: src/fp/relic_fp_cmp.c File Reference
relic_fp_cmp.c File Reference
Prime field arithmetic
#include "relic_core.h"
#include "relic_fp_low.h"
Functions
int fp_cmp_dig (const fp_t a, dig_t b)
int fp_cmp (const fp_t a, const fp_t b)
Detailed Description
Implementation of the prime field comparison functions.
Definition in file relic_fp_cmp.c.
Function Documentation
fp_cmp_dig()
int fp_cmp_dig (const fp_t a, dig_t b)
Returns the result of a signed comparison between a prime field element and a digit.
Parameters
[in] a - the prime field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 38 of file relic_fp_cmp.c.
References ERR_CAUGHT, fp_cmp(), fp_free, fp_new, fp_null, fp_prime_conv_dig(), RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by detect_opt(), ed_is_infty(), fp2_cmp_dig(), fp3_cmp_dig(), fp_crt(), fp_is_cub(), fp_smb_basic(), and fp_srt().
fp_cmp()
int fp_cmp (const fp_t a, const fp_t b)
Returns the result of a comparison between two prime field elements.
Parameters
[in] a - the first prime field element.
[in] b - the second prime field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 57 of file relic_fp_cmp.c.
References ERR_CAUGHT, fp_free, fp_is_zero(), fp_new, fp_norm(), fp_null, fp_sub, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_NE, RLC_THROW, and RLC_TRY.
Referenced by detect_opt(), ed_cmp(), ed_is_infty(), ed_map_ell2_5mod8(), ed_on_curve(), ep_cmp(), ep_on_curve(), fp2_cmp(), fp3_cmp(), fp_cmp_dig(), fp_crt(), fp_srt(), pp_add_k1_basic(), pp_add_k1_projc(), and pp_map_weilp_k1().