RELIC: src/fp/relic_fp_util.c File Reference
relic_fp_util.c File Reference
Prime field arithmetic
#include "relic_core.h"
#include "relic_fp_low.h"
Functions
void fp_copy (fp_t c, const fp_t a)
void fp_copy_sec (fp_t c, const fp_t a, dig_t bit)
void fp_zero (fp_t a)
int fp_is_zero (const fp_t a)
int fp_is_even (const fp_t a)
int fp_get_bit (const fp_t a, uint_t bit)
void fp_set_bit (fp_t a, uint_t bit, int value)
size_t fp_bits (const fp_t a)
void fp_set_dig (fp_t c, dig_t a)
void fp_rand (fp_t a)
void fp_norm (fp_t c, const fp_t a)
void fp_print (const fp_t a)
size_t fp_size_str (const fp_t a, uint_t radix)
void fp_read_str (fp_t a, const char *str, size_t len, uint_t radix)
void fp_write_str (char *str, size_t len, const fp_t a, uint_t radix)
void fp_read_bin (fp_t a, const uint8_t *bin, size_t len)
void fp_write_bin (uint8_t *bin, size_t len, const fp_t a)
Detailed Description
Implementation of the prime field utilities.
Definition in file relic_fp_util.c.
Function Documentation
fp_copy()
void fp_copy (fp_t c, const fp_t a)
Copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the prime field element to copy.
Definition at line 39 of file relic_fp_util.c.
References dv_copy(), and RLC_FP_DIGS.
Referenced by ed_add_basic(), ed_copy(), ed_dbl_basic(), ed_neg_basic(), ed_neg_projc(), ed_norm_imp(), ed_norm_sim(), ed_pck(), ed_upk(), ep2_curve_set_twist(), ep3_curve_set_twist(), ep4_curve_set_twist(), ep8_curve_set_twist(), ep_copy(), ep_curve_mul_a(), ep_curve_mul_b(), ep_curve_set(), ep_curve_set_endom(), ep_curve_set_map(), ep_neg(), ep_norm_imp(), ep_norm_sim(), ep_pck(), ep_rhs(), ep_upk(), fp12_mul_dxs_basic(), fp12_mul_dxs_lazyr(), fp18_mul_dxs_basic(), fp18_mul_dxs_lazyr(), fp2_add_dig(), fp2_copy(), fp2_field_init(), fp2_frb(), fp2_inv_cyc(), fp2_mul_art(), fp2_mul_frb(), fp2_pck(), fp2_srt(), fp2_sub_dig(), fp2_upk(), fp3_add_dig(), fp3_copy(), fp3_field_init(), fp3_inv(), fp3_mul_art(), fp3_mul_frb(), fp3_sub_dig(), fp4_field_init(), fp4_mul_frb(), fp8_field_init(), fp8_mul_frb(), fp_crt(), fp_exp_basic(), fp_exp_dig(), fp_exp_monty(), fp_exp_slide(), fp_hlv_basic(), fp_inv_divst(), fp_inv_jmpds(), fp_inv_monty(), fp_inv_sim(), fp_lsh(), fp_norm(), fp_rdc_basic(), fp_rsh(), fp_smb_binar(), fp_smb_divst(), fp_smb_jmpds(), fp_srt(), fp_trs(), pp_add_k16_basic(), pp_add_k8_basic(), pp_dbl_k12_basic(), pp_dbl_k16_basic(), pp_dbl_k18_basic(), pp_dbl_k24_basic(), pp_dbl_k2_basic(), pp_dbl_k48_basic(), pp_dbl_k54_basic(), pp_dbl_k54_projc(), pp_dbl_k8_basic(), pp_fin_k16_oatep(), pp_mil_k16(), pp_mil_k54(), pp_mil_k8(), and pp_mil_lit_k2().
fp_copy_sec()
void fp_copy_sec (fp_t c, const fp_t a, dig_t bit)
Conditionally copies a field element to another field element.
Parameters
[out] c - the destination. @paraim[in] a - the source.
[in] bit - the condition bit to evaluate.
Definition at line 43 of file relic_fp_util.c.
References dv_copy_sec(), and RLC_FP_DIGS.
Referenced by ed_map_ell2_5mod8(), ed_mul_reg_imp(), ep2_mul_reg_imp(), ep3_mul_reg_imp(), ep4_mul_reg_imp(), ep8_mul_reg_imp(), ep_map_swift_impl(), ep_mul_reg_glv(), ep_mul_reg_imp(), fp16_srt(), fp2_copy_sec(), fp2_srt(), fp3_copy_sec(), fp_inv_divst(), fp_inv_jmpds(), fp_smb_divst(), fp_srt(), and fp_trs().
fp_zero()
void fp_zero (fp_t a)
Assigns zero to a prime field element.
Parameters
[out] a - the prime field element to asign.
Definition at line 47 of file relic_fp_util.c.
References dv_zero(), and RLC_FP_DIGS.
Referenced by ed_pck(), ed_read_bin(), ed_set_infty(), ep2_pck(), ep2_read_bin(), ep2_upk(), ep_curve_mul_a(), ep_curve_mul_b(), ep_param_set(), ep_pck(), ep_read_bin(), ep_set_infty(), fp2_field_init(), fp2_pck(), fp2_read_bin(), fp2_set_dig(), fp2_srt(), fp2_zero(), fp3_field_init(), fp3_set_dig(), fp3_zero(), fp_crt(), fp_inv_divst(), fp_inv_monty(), fp_neg_basic(), fp_prime_conv(), fp_prime_conv_dig(), fp_read_bin(), fp_read_str(), fp_smb_divst(), fp_smb_jmpds(), fp_srt(), and pp_dbl_lit_k12().
fp_is_zero()
int fp_is_zero (const fp_t a)
Tests if a prime field element is zero or not.
Parameters
[in] a - the prime field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 51 of file relic_fp_util.c.
References fp_prime_get(), and RLC_FP_DIGS.
Referenced by detect_opt(), detect_opt(), detect_opt(), detect_opt(), detect_opt(), ed_is_infty(), ed_map_ell2_5mod8(), ed_on_curve(), ep2_curve_set_map(), ep2_map_swift(), ep3_map(), ep4_map(), ep8_map(), ep_curve_set_endom(), ep_curve_set_map(), ep_is_infty(), ep_map_swift_impl(), ep_param_set(), fp2_cmp_dig(), fp2_is_zero(), fp2_sgn0(), fp2_srt(), fp3_cmp_dig(), fp3_field_init(), fp3_is_zero(), fp_cmp(), fp_crt(), fp_inv_basic(), fp_inv_binar(), fp_inv_divst(), fp_inv_exgcd(), fp_inv_jmpds(), fp_inv_lower(), fp_inv_monty(), fp_is_cub(), fp_is_sqr(), fp_neg_basic(), fp_smb_binar(), fp_smb_divst(), fp_srt(), pp_add_k1_basic(), pp_add_k1_projc(), pp_dbl_k1_basic(), pp_dbl_k1_projc(), and pp_mil_k1().
fp_is_even()
int fp_is_even (const fp_t a)
Tests if a prime field element is even or odd.
Parameters
[in] a - the prime field element to test.
Returns
1 if the argument is even, 0 otherwise.
Definition at line 66 of file relic_fp_util.c.
References bn_free, bn_is_even(), bn_new, bn_null, ERR_CAUGHT, fp_prime_back(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep2_map_swift(), ep4_map(), ep_map_swift_impl(), and fp_srt().
fp_get_bit()
int fp_get_bit (const fp_t a, uint_t bit)
Reads the bit stored in the given position on a prime field element.
Parameters
[in] a - the prime field element.
[in] bit - the bit position.
Returns
the bit value.
Definition at line 87 of file relic_fp_util.c.
References RLC_RIP.
Referenced by ed_pck(), ed_upk(), ed_write_bin(), ep2_upk(), ep2_write_bin(), ep_pck(), ep_upk(), ep_write_bin(), fp2_pck(), fp2_upk(), and fp2_write_bin().
fp_set_bit()
void fp_set_bit (fp_t a, uint_t bit, int value)
Stores a bit in a given position on a prime field element.
Parameters
[out] a - the prime field element.
[in] bit - the bit position.
[in] value - the bit value.
Definition at line 95 of file relic_fp_util.c.
References RLC_RIP.
Referenced by ed_pck(), ed_read_bin(), ep2_pck(), ep2_read_bin(), ep_pck(), ep_read_bin(), fp2_pck(), and fp2_read_bin().
fp_bits()
size_t fp_bits (const fp_t a)
Returns the number of bits of a prime field element.
Parameters
[in] a - the prime field element.
Returns
the number of bits.
Definition at line 110 of file relic_fp_util.c.
References RLC_DIG_LOG, RLC_FP_DIGS, and util_bits_dig().
Referenced by detect_opt(), detect_opt(), detect_opt(), detect_opt(), detect_opt(), and fp2_upk().
fp_set_dig()
void fp_set_dig (fp_t c, dig_t a)
Assigns a small positive constant to a prime field element.
The constant must fit on a multiple precision digit, or dig_t type using only the number of bits specified on RLC_DIG.
Parameters
[out] c - the result.
[in] a - the constant to assign.
Definition at line 120 of file relic_fp_util.c.
References fp_prime_conv_dig().
Referenced by cp_cmlhs_sig(), cp_cmlhs_ver(), ed_map_ell2_5mod8(), ed_norm_imp(), ed_param_set(), ed_pck(), ed_read_bin(), ed_set_infty(), ed_upk(), ep2_pck(), ep2_upk(), ep_curve_set_map(), ep_curve_set_plain(), ep_map_basic_impl(), ep_map_swift_impl(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_norm_imp(), ep_param_set(), ep_pck(), ep_read_bin(), ep_upk(), fp12_upk_max(), fp2_field_init(), fp2_set_dig(), fp2_srt(), fp3_field_init(), fp3_set_dig(), fp_add_dig(), fp_crt(), fp_exp_basic(), fp_exp_dig(), fp_exp_monty(), fp_exp_slide(), fp_inv_divst(), fp_prime_set(), fp_sub_dig(), pp_add_k1_basic(), pp_add_k1_projc(), pp_dbl_k1_basic(), pp_dbl_k1_projc(), pp_map_sim_tatep_k1(), pp_map_sim_weilp_k1(), pp_map_tatep_k1(), pp_map_weilp_k1(), and pp_mil_k1().
fp_rand()
void fp_rand (fp_t a)
Assigns a random value to a prime field element.
Parameters
[out] a - the prime field element to assign.
Definition at line 124 of file relic_fp_util.c.
References dv_cmp(), fp_prime_get(), fp_subm_low(), rand_bytes(), RLC_FP_BITS, RLC_FP_DIGS, RLC_LT, and RLC_RIP.
Referenced by ed_blind(), ep_blind(), fp2_rand(), and fp3_rand().
fp_norm()
void fp_norm (fp_t c, const fp_t a)
Normalizes a prime field element to a representative in [0, p - 1].
Parameters
[out] c - the normalized field element.
[in] a - the field element to normalize-
Definition at line 140 of file relic_fp_util.c.
References dv_cmp(), fp_copy(), fp_prime_get(), fp_subn_low(), RLC_FP_DIGS, and RLC_LT.
Referenced by ed_pck(), ed_upk(), fp_cmp(), fp_prime_back(), and fp_print().
fp_print()
void fp_print (const fp_t a)
Prints a prime field element to standard output.
Parameters
[in] a - the prime field element to print.
Definition at line 147 of file relic_fp_util.c.
References bn_free, bn_new, bn_null, bn_read_raw(), bn_trim(), ERR_CAUGHT, fp_norm(), fp_prime_back(), fp_prime_get(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, RLC_TRY, util_print, and util_print_dig().
Referenced by ed_print(), ep_print(), fp2_print(), and fp3_print().
fp_size_str()
size_t fp_size_str (const fp_t a, uint_t radix)
Returns the number of digits in radix necessary to store a multiple precision integer. The radix must be a power of 2 included in the interval [2, 64].
Parameters
[in] a - the prime field element.
[in] radix - the radix.
Exceptions
ERR_NO_VALID - if the radix is invalid.
Returns
the number of digits in the given radix.
Definition at line 187 of file relic_fp_util.c.
References bn_free, bn_new, bn_null, bn_size_str(), ERR_CAUGHT, fp_prime_back(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp_read_str()
void fp_read_str (fp_t a, const char * str, size_t len, uint_t radix)
Reads a prime field element from a string in a given radix. The radix must be a power of 2 included in the interval [2, 64].
Parameters
[out] a - the result.
[in] str - the string.
[in] len - the size of the string.
[in] radix - the radix.
Exceptions
ERR_NO_VALID - if the radix is invalid.
Definition at line 209 of file relic_fp_util.c.
References bn_free, bn_is_zero(), bn_new, bn_null, bn_read_str(), bn_sign(), ERR_CAUGHT, fp_neg, fp_prime_conv(), fp_prime_conv_dig(), fp_zero(), RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by ed_param_set(), ep2_curve_get_coeffs(), ep2_curve_set_ctmap(), ep_param_get_coeffs(), and ep_param_set_ctmap().
fp_write_str()
void fp_write_str (char * str, size_t len, const fp_t a, uint_t radix)
Writes a prime field element to a string in a given radix. The radix must be a power of 2 included in the interval [2, 64].
Parameters
[out] str - the string.
[in] len - the buffer capacity.
[in] a - the prime field element to write.
[in] radix - the radix.
Exceptions
ERR_BUFFER - if the buffer capacity is insufficient.
ERR_NO_VALID - if the radix is invalid.
Definition at line 238 of file relic_fp_util.c.
References bn_free, bn_new, bn_null, bn_write_str(), ERR_CAUGHT, fp_prime_back(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp_read_bin()
void fp_read_bin (fp_t a, const uint8_t * bin, size_t len)
Reads a prime field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not RLC_FP_BYTES.
Definition at line 257 of file relic_fp_util.c.
References bn_cmp(), bn_free, bn_is_zero(), bn_new, bn_null, bn_read_bin(), bn_sign(), core_get(), ERR_CAUGHT, ERR_NO_BUFFER, ERR_NO_VALID, fp_prime_conv(), fp_prime_conv_dig(), fp_zero(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_LT, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by ed_read_bin(), ep_read_bin(), fp2_read_bin(), and fp3_read_bin().
fp_write_bin()
void fp_write_bin (uint8_t * bin, size_t len, const fp_t a)
Writes a prime field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the prime field element to write.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not RLC_FP_BYTES.
Definition at line 294 of file relic_fp_util.c.
References bn_free, bn_new, bn_null, bn_write_bin(), ERR_CAUGHT, ERR_NO_BUFFER, fp_prime_back(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.
Referenced by ed_write_bin(), ep_write_bin(), fp2_write_bin(), and fp3_write_bin().