RELIC: src/fb/relic_fb_inv.c File Reference
relic_fb_inv.c File Reference
Binary field arithmetic
#include "relic_core.h"
#include "relic_fb.h"
#include "relic_fb_low.h"
#include "relic_bn_low.h"
#include "relic_util.h"
#include "relic_rand.h"
Functions
void fb_inv_basic (fb_t c, const fb_t a)
void fb_inv_binar (fb_t c, const fb_t a)
void fb_inv_exgcd (fb_t c, const fb_t a)
void fb_inv_almos (fb_t c, const fb_t a)
void fb_inv_itoht (fb_t c, const fb_t a)
void fb_inv_bruch (fb_t c, const fb_t a)
void fb_inv_ctaia (fb_t c, const fb_t a)
void fb_inv_lower (fb_t c, const fb_t a)
void fb_inv_sim (fb_t *c, const fb_t *a, int n)
Detailed Description
Implementation of binary field inversion functions.
Definition in file relic_fb_inv.c.
Function Documentation
fb_inv_basic()
void fb_inv_basic (fb_t c, const fb_t a)
Inverts a binary field element using Fermat's Little Theorem.
Parameters
[out] c - the result.
[in] a - the binary field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 45 of file relic_fb_inv.c.
References ERR_CAUGHT, ERR_NO_VALID, fb_copy(), fb_free, fb_is_zero(), fb_mul, fb_new, fb_null, fb_set_dig(), fb_sqr, RLC_CATCH_ANY, RLC_FB_BITS, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fb_inv_binar()
void fb_inv_binar (fb_t c, const fb_t a)
Inverts a binary field element using the binary method.
Parameters
[out] c - the result.
[in] a - the binary field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 112 of file relic_fb_inv.c.
References bn_rsh1_low(), dv_free, dv_new, dv_null, dv_zero(), ERR_CAUGHT, ERR_NO_VALID, fb_add(), fb_addd_low(), fb_copy(), fb_is_zero(), fb_poly_add(), fb_poly_get(), RLC_CATCH_ANY, RLC_DIG, RLC_FB_BITS, RLC_FB_DIGS, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fb_inv_exgcd()
void fb_inv_exgcd (fb_t c, const fb_t a)
Inverts a binary field element using the Extended Euclidean algorithm.
Parameters
[out] c - the result.
[in] a - the binary field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 218 of file relic_fb_inv.c.
References dv_free, dv_new, dv_zero(), ERR_CAUGHT, ERR_NO_VALID, fb_addd_low(), fb_bits(), fb_copy(), fb_is_zero(), fb_lsha_low(), fb_null, fb_poly_get(), RLC_CATCH_ANY, RLC_DIG_LOG, RLC_FB_BITS, RLC_FB_DIGS, RLC_FINALLY, RLC_RIP, RLC_THROW, RLC_TRY, and util_bits_dig().
fb_inv_almos()
void fb_inv_almos (fb_t c, const fb_t a)
Inverts a binary field element using the Almost Inverse algorithm.
Parameters
[out] c - the result.
[in] a - the binary field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 339 of file relic_fb_inv.c.
References bn_rsh1_low(), dv_free, dv_new, dv_null, dv_zero(), ERR_CAUGHT, ERR_NO_VALID, fb_addd_low(), fb_addn_low(), fb_copy(), fb_is_zero(), fb_poly_add(), fb_poly_get(), fb_set_dig(), RLC_CATCH_ANY, RLC_DIG, RLC_FB_BITS, RLC_FB_DIGS, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fb_inv_itoht()
void fb_inv_itoht (fb_t c, const fb_t a)
Inverts a binary field element using Itoh-Tsuji inversion.
Parameters
[out] c - the result.
[in] a - the binary field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 439 of file relic_fb_inv.c.
References ERR_CAUGHT, ERR_NO_MEMORY, ERR_NO_VALID, fb_copy(), fb_free, fb_is_zero(), fb_itr, fb_mul, fb_new, fb_null, fb_poly_get_chain(), fb_poly_tab_sqr(), fb_sqr, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FB_BITS, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
fb_inv_bruch()
void fb_inv_bruch (fb_t c, const fb_t a)
Inverts a binary field element using the hardware-friendly Brunner-Curiger-Hofstetter algorithm.
Parameters
[out] c - the result.
[in] a - the binary field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 508 of file relic_fb_inv.c.
References ERR_CAUGHT, ERR_NO_VALID, fb_add(), fb_copy(), fb_free, fb_is_zero(), fb_lsh(), fb_new, fb_null, fb_poly_get(), fb_rsh(), fb_set_dig(), fb_zero(), RLC_CATCH_ANY, RLC_DIG, RLC_FB_BITS, RLC_FB_DIGS, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fb_inv_ctaia()
void fb_inv_ctaia (fb_t c, const fb_t a)
Inverts a binary field element in constant-time using the Wu-Wu-Shieh-Hwang algorithm.
Parameters
[out] c - the result.
[in] a - the binary field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 580 of file relic_fb_inv.c.
References ERR_CAUGHT, ERR_NO_VALID, fb_copy(), fb_free, fb_is_zero(), fb_new, fb_null, fb_poly_add(), fb_poly_get(), fb_rsh(), fb_set_dig(), fb_zero(), RLC_CATCH_ANY, RLC_FB_BITS, RLC_FB_DIGS, RLC_FINALLY, RLC_SEL, RLC_THROW, and RLC_TRY.
fb_inv_lower()
void fb_inv_lower (fb_t c, const fb_t a)
Inverts a binary field element using a direct call to the lower layer.
Parameters
[out] c - the result.
[in] a - the binary field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 649 of file relic_fb_inv.c.
References ERR_NO_VALID, fb_invn_low(), fb_is_zero(), and RLC_THROW.
fb_inv_sim()
void fb_inv_sim (fb_t * c, const fb_t * a, int n)
Inverts multiple binary field elements.
Parameters
[out] c - the result.
[in] a - the binary field elements to invert.
[in] n - the number of elements.
Definition at line 659 of file relic_fb_inv.c.
References ERR_CAUGHT, ERR_NO_MEMORY, fb_copy(), fb_free, fb_inv, fb_mul, fb_new, fb_null, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by eb_norm_sim().