RELIC: src/pp/relic_pp_norm.c File Reference
relic_pp_norm.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_md.h"
#include "relic_pp.h"
#include "relic_conf.h"
#include "relic_fp_low.h"
Functions
void pp_norm_k1 (ep_t r, const ep_t p)
void pp_norm_k2 (ep_t r, const ep_t p)
void pp_norm_k8 (ep2_t r, const ep2_t p)
void pp_norm_k12 (ep2_t r, const ep2_t p)
void pp_norm_k16 (ep4_t r, const ep4_t p)
void pp_norm_k18 (ep3_t r, const ep3_t p)
void pp_norm_k24 (ep4_t r, const ep4_t p)
void pp_norm_k48 (ep8_t r, const ep8_t p)
Detailed Description
Implementation of point normalization for points used in pairing computation.
Definition in file relic_pp_norm.c.
Function Documentation
pp_norm_k1()
void pp_norm_k1 (ep_t c, const ep_t a)
Normalizes the accumulator point used inside pairing computation defined over curves of embedding degree 1.
Parameters
[out] r - the resulting point.
[in] p - the point to normalize.
Definition at line 42 of file relic_pp_norm.c.
References ep_norm().
pp_norm_k2()
void pp_norm_k2 (ep_t c, const ep_t a)
Normalizes the accumulator point used inside pairing computation defined over curves of embedding degree 2.
Parameters
[out] r - the resulting point.
[in] p - the point to normalize.
Definition at line 46 of file relic_pp_norm.c.
References ep_norm().
pp_norm_k8()
void pp_norm_k8 (ep2_t c, const ep2_t a)
Normalizes the accumulator point used inside pairing computation defined over curves of embedding degree 8.
Parameters
[out] r - the resulting point.
[in] p - the point to normalize.
Definition at line 50 of file relic_pp_norm.c.
References BASIC, ep2_copy(), ep2_is_infty(), ep2_set_infty(), fp2_inv(), fp2_mul, and fp2_set_dig().
pp_norm_k12()
void pp_norm_k12 (ep2_t c, const ep2_t a)
Normalizes the accumulator point used inside pairing computation defined over curves of embedding degree 12.
Parameters
[out] r - the resulting point.
[in] p - the point to normalize.
Definition at line 70 of file relic_pp_norm.c.
References BASIC, ep2_copy(), ep2_is_infty(), ep2_set_infty(), fp2_inv(), fp2_mul, and fp2_set_dig().
pp_norm_k16()
void pp_norm_k16 (ep4_t c, const ep4_t a)
Normalizes the accumulator point used inside pairing computation defined over curves of embedding degree 16.
Parameters
[out] r - the resulting point.
[in] p - the point to normalize.
Definition at line 89 of file relic_pp_norm.c.
References BASIC, ep4_copy(), ep4_is_infty(), ep4_set_infty(), ep_curve_opt_b(), fp4_inv(), fp4_mul, fp4_set_dig(), and RLC_ZERO.
pp_norm_k18()
void pp_norm_k18 (ep3_t c, const ep3_t a)
Normalizes the accumulator point used inside pairing computation defined over curves of embedding degree 18.
Parameters
[out] r - the resulting point.
[in] p - the point to normalize.
Definition at line 111 of file relic_pp_norm.c.
References BASIC, ep3_copy(), ep3_is_infty(), ep3_set_infty(), fp3_inv(), fp3_mul, and fp3_set_dig().
Referenced by pp_fin_k18_oatep().
pp_norm_k24()
void pp_norm_k24 (ep4_t c, const ep4_t a)
Normalizes the accumulator point used inside pairing computation defined over curves of embedding degree 24.
Parameters
[out] r - the resulting point.
[in] p - the point to normalize.
Definition at line 130 of file relic_pp_norm.c.
References BASIC, ep4_copy(), ep4_is_infty(), ep4_set_infty(), fp4_inv(), fp4_mul, and fp4_set_dig().
pp_norm_k48()
void pp_norm_k48 (ep8_t c, const ep8_t a)
Normalizes the accumulator point used inside pairing computation defined over curves of embedding degree 48.
Parameters
[out] r - the resulting point.
[in] p - the point to normalize.
Definition at line 149 of file relic_pp_norm.c.
References BASIC, ep8_copy(), ep8_is_infty(), ep8_set_infty(), fp8_inv(), fp8_mul, and fp8_set_dig().