RELIC: include/relic_dv.h File Reference
relic_dv.h File Reference
Digit vector handling
#include "relic_bn.h"
#include "relic_conf.h"
#include "relic_types.h"
#include "relic_util.h"
#include "relic_label.h"
Macros
#define RLC_DV_MAX (RLC_MAX(FP_PRIME, FB_POLYN))
#define RLC_DV_DIGS (RLC_MAX(RLC_CEIL(RLC_DV_MAX, RLC_DIG), RLC_BN_SIZE))
#define RLC_DV_BYTES (RLC_DV_DIGS * (RLC_DIG / 8))
#define dv_null(A)
#define dv_new(A)
#define dv_free(A)
Typedefs
typedef rlc_align dig_t dv_t[RLC_DV_DIGS+RLC_PAD(RLC_DV_BYTES)/(RLC_DIG/8)]
Functions
void dv_print (const dig_t *a, size_t digits)
void dv_zero (dig_t *a, size_t digits)
void dv_copy (dig_t *c, const dig_t *a, size_t digits)
void dv_copy_sec (dig_t *c, const dig_t *a, size_t digits, dig_t bit)
void dv_swap_sec (dig_t *c, dig_t *a, size_t digits, dig_t bit)
int dv_cmp (const dig_t *a, const dig_t *b, size_t size)
int dv_cmp_sec (const dig_t *a, const dig_t *b, size_t size)
void dv_lshd (dig_t *c, const dig_t *a, size_t size, uint_t digits)
void dv_rshd (dig_t *c, const dig_t *a, size_t size, uint_t digits)
Detailed Description
Interface of the module for manipulating temporary double-precision digit vectors.
Definition in file relic_dv.h.
Macro Definition Documentation
RLC_DV_MAX
#define RLC_DV_MAX (RLC_MAX(FP_PRIME, FB_POLYN))
Size in bits of the largest field element.
Definition at line 56 of file relic_dv.h.
RLC_DV_DIGS
#define RLC_DV_DIGS (RLC_MAX(RLC_CEIL(RLC_DV_MAX, RLC_DIG), RLC_BN_SIZE))
Size in digits of a temporary vector.
A temporary vector has enough size to store a multiplication/squaring result produced by any module.
Definition at line 77 of file relic_dv.h.
Referenced by dv_zero().
RLC_DV_BYTES
#define RLC_DV_BYTES (RLC_DV_DIGS * (RLC_DIG / 8))
Size in bytes of a temporary vector.
Definition at line 82 of file relic_dv.h.
dv_null
#define dv_null (A)
Value:
/* empty */
Initializes a digit vector with a null value.
Parameters
[out] A - the digit vector to initialize.
Definition at line 107 of file relic_dv.h.
Referenced by eb_mul_lodah(), fb_inv_almos(), fb_inv_binar(), fb_mul_basic(), fb_mul_dig(), fb_mul_karat(), fb_mul_karat_imp(), fb_mul_lodah(), fb_rdc_basic(), fb_sqr_basic(), fb_sqr_quick(), fp2_mul_basic(), fp3_mul_basic(), fp3_sqr_basic(), fp_inv_divst(), fp_inv_jmpds(), fp_mul_basic(), fp_mul_comba(), fp_mul_dig(), fp_mul_karat(), fp_mul_karat_imp(), fp_prime_back(), fp_rdc_basic(), fp_smb_binar(), fp_smb_divst(), fp_smb_jmpds(), fp_sqr_basic(), fp_sqr_comba(), fp_sqr_karat(), fp_sqr_karat_imp(), pp_add_k2_projc_lazyr(), and pp_dbl_k2_projc_lazyr().
dv_new
#define dv_new (A)
Value:
/* empty */
Calls a function to allocate a temporary double-precision digit vector.
Parameters
[out] A - the double-precision result.
Definition at line 120 of file relic_dv.h.
Referenced by eb_mul_lodah(), fb_inv_almos(), fb_inv_binar(), fb_inv_exgcd(), fb_mul_basic(), fb_mul_dig(), fb_mul_karat(), fb_mul_karat_imp(), fb_mul_lodah(), fb_rdc_basic(), fb_sqr_basic(), fb_sqr_quick(), fp2_mul_basic(), fp3_mul_basic(), fp3_sqr_basic(), fp_inv_divst(), fp_inv_jmpds(), fp_mul_basic(), fp_mul_comba(), fp_mul_dig(), fp_mul_karat(), fp_mul_karat_imp(), fp_prime_back(), fp_prime_conv_dig(), fp_rdc_basic(), fp_smb_binar(), fp_smb_divst(), fp_smb_jmpds(), fp_sqr_basic(), fp_sqr_comba(), fp_sqr_karat(), fp_sqr_karat_imp(), pp_add_k2_projc_lazyr(), and pp_dbl_k2_projc_lazyr().
dv_free
#define dv_free (A)
Value:
(void)A
Calls a function to clean and free a temporary double-precision digit vector.
Parameters
[out] A - the temporary digit vector to clean and free.
Definition at line 131 of file relic_dv.h.
Referenced by eb_mul_lodah(), fb_inv_almos(), fb_inv_binar(), fb_inv_exgcd(), fb_mul_dig(), fb_mul_karat(), fb_mul_karat_imp(), fb_mul_lodah(), fb_sqr_basic(), fb_sqr_quick(), fp2_mul_basic(), fp3_mul_basic(), fp3_sqr_basic(), fp_inv_divst(), fp_inv_jmpds(), fp_mul_basic(), fp_mul_comba(), fp_mul_dig(), fp_mul_karat(), fp_mul_karat_imp(), fp_prime_back(), fp_prime_conv_dig(), fp_rdc_basic(), fp_smb_binar(), fp_smb_divst(), fp_smb_jmpds(), fp_sqr_karat(), fp_sqr_karat_imp(), pp_add_k2_projc_lazyr(), and pp_dbl_k2_projc_lazyr().
Typedef Documentation
dv_t
typedef rlc_align dig_t dv_t[RLC_DV_DIGS+RLC_PAD(RLC_DV_BYTES)/(RLC_DIG/8)]
Represents a temporary double-precision digit vector.
Definition at line 92 of file relic_dv.h.
Function Documentation
dv_print()
void dv_print (const dig_t * a, size_t digits)
Prints a temporary digit vector.
Parameters
[in] a - the temporary digit vector to print.
[in] digits - the number of digits to print.
Definition at line 41 of file relic_dv_util.c.
References util_print, and util_print_dig().
dv_zero()
void dv_zero (dig_t * a, size_t digits)
Assigns zero to a temporary double-precision digit vector.
Parameters
[out] a - the temporary digit vector to assign.
[in] digits - the number of words to initialize with zero.
Definition at line 52 of file relic_dv_util.c.
References ERR_NO_PRECI, RLC_DV_DIGS, and RLC_THROW.
Referenced by bn_smb_jac(), bn_zero(), eb_mul_lodah(), fb_inv_almos(), fb_inv_binar(), fb_inv_exgcd(), fb_mul_basic(), fb_mul_karat(), fb_zero(), fp_inv_divst(), fp_inv_jmpds(), fp_inv_monty(), fp_mul_basic(), fp_mul_karat(), fp_mul_karat_imp(), fp_prime_back(), fp_prime_conv(), fp_prime_conv_dig(), fp_smb_binar(), fp_smb_divst(), fp_smb_jmpds(), fp_sqr_basic(), fp_sqr_karat(), fp_sqr_karat_imp(), and fp_zero().
dv_copy()
void dv_copy (dig_t * c, const dig_t * a, size_t digits)
Copies some digits from a digit vector to another digit vector.
Parameters
[out] c - the destination.
[in] a - the source.
[in] digits - the number of digits to copy.
Definition at line 69 of file relic_dv_util.c.
Referenced by bn_copy(), bn_lsh(), bn_mul_karat_imp(), bn_read_raw(), bn_rsh(), bn_sqr_karat_imp(), eb_map(), ed_map_ell2_5mod8(), ed_param_set(), ep2_pck(), ep2_upk(), ep_pck(), ep_upk(), fb_copy(), fb_read_str(), fp16_mul_dxs_lazyr(), fp16_mul_unr(), fp16_sqr_unr(), fp18_sqr_unr(), fp24_mul_unr(), fp24_sqr_unr(), fp2_field_init(), fp2_srt(), fp3_srt(), fp4_field_init(), fp8_field_init(), fp8_mul_dxs(), fp8_mul_unr(), fp8_sqr_unr(), fp_copy(), fp_crt(), fp_inv_basic(), fp_inv_binar(), fp_inv_divst(), fp_inv_exgcd(), fp_inv_jmpds(), fp_inv_monty(), fp_is_cub(), fp_mul_karat_imp(), fp_prime_back(), fp_prime_conv(), fp_prime_conv_dig(), fp_prime_set(), fp_rdc_basic(), fp_smb_basic(), fp_smb_binar(), fp_smb_divst(), fp_smb_jmpds(), fp_srt(), and pp_exp_k2().
dv_copy_sec()
void dv_copy_sec (dig_t * c, const dig_t * a, size_t digits, dig_t bit)
Conditionally copies some digits from a digit vector to another digit vector.
Parameters
[out] c - the destination. @paraim[in] a - the source.
[in] digits - the number of digits to copy.
[in] bit - the condition bit to evaluate.
Definition at line 73 of file relic_dv_util.c.
Referenced by ed_map_ell2_5mod8(), ep_mul_reg_glv(), fp_copy_sec(), fp_inv_divst(), and fp_inv_jmpds().
dv_swap_sec()
void dv_swap_sec (dig_t * c, dig_t * a, size_t digits, dig_t bit)
Conditionally swap two digit vectors.
Parameters
[in,out] c - the destination. @paraim[in,out] a - the source.
[in] digits - the number of digits to copy.
[in] bit - the condition bit to evaluate.
Definition at line 83 of file relic_dv_util.c.
Referenced by bn_mxp_monty(), eb_mul_lodah(), ed_mul_monty(), ep2_mul_monty(), ep3_mul_monty(), ep4_mul_monty(), ep8_mul_monty(), ep_mul_monty(), fb_exp_monty(), fp_exp_monty(), and fp_inv_divst().
dv_cmp()
int dv_cmp (const dig_t * a, const dig_t * b, size_t size)
Returns the result of a comparison between two digit vectors.
Parameters
[in] a - the first digit vector.
[in] b - the second digit vector.
[in] size - the length in digits of the vectors.
Returns
RLC_LT if a < b, RLC_EQ if a == b and RLC_GT if a > b.
Definition at line 94 of file relic_dv_util.c.
References RLC_EQ, RLC_GT, and RLC_LT.
Referenced by bn_cmp_abs(), fp_add_basic(), fp_add_dig(), fp_dbl_basic(), fp_inv_monty(), fp_norm(), fp_rand(), and fp_smb_divst().
dv_cmp_sec()
int dv_cmp_sec (const dig_t * a, const dig_t * b, size_t size)
Compares two digit vectors in constant time.
Parameters
[in] a - the first digit vector.
[in] b - the second digit vector.
[in] size - the length in digits of the vectors.
Returns
RLC_EQ if they are equal and RLC_NE otherwise.
Definition at line 109 of file relic_dv_util.c.
References RLC_EQ, and RLC_NE.
Referenced by cp_ecdsa_ver(), cp_ecss_ver(), fb_cmp(), fp_smb_divst(), and fp_smb_jmpds().
dv_lshd()
void dv_lshd (dig_t * c, const dig_t * a, size_t size, uint_t digits)
Allocates and initializes a temporary double-precision digit vector.
Parameters
[out] a - the new temporary digit vector.
[in] digits - the required precision in digits.
Exceptions
ERR_NO_MEMORY - if there is no available memory.
ERR_PRECISION - if the required precision cannot be represented by the library. Cleans and frees a temporary double-precision digit vector.
Parameters
[out] a - the temporary digit vector to clean and free. Shifts a digit vector to the left by some digits. Computes c = a << (digits * RLC_DIG).
[out] c - the result.
[in] a - the digit vector to shift.
[in] size - the number of digits to shift.
[in] digits - the shift amount.
Definition at line 135 of file relic_dv_util.c.
Referenced by bn_lsh(), fb_lsh(), and fp_lsh().
dv_rshd()
void dv_rshd (dig_t * c, const dig_t * a, size_t size, uint_t digits)
Shifts a digit vector to the right by some digits. Computes c = a >> (digits * RLC_DIG).
Parameters
[out] c - the result.
[in] a - the digit vector to shift.
[in] size - the number of digits to shift.
[in] digits - the shift amount.
Definition at line 119 of file relic_dv_util.c.
Referenced by bn_rsh(), fb_rsh(), and fp_rsh().