RELIC: src/cp/relic_cp_cmlhs.c File Reference
relic_cp_cmlhs.c File Reference
Cryptographic protocols
#include "relic.h"
Functions
int cp_cmlhs_init (g1_t h)
int cp_cmlhs_gen (bn_t x[], gt_t hs[], size_t len, uint8_t prf[], size_t plen, bn_t sk, g2_t pk, bn_t d, g2_t y, int bls)
int cp_cmlhs_sig (g1_t sig, g2_t z, g1_t a, g1_t c, g1_t r, g2_t s, const bn_t msg, const char *data, int label, const bn_t x, const g1_t h, const uint8_t prf[], size_t plen, const bn_t d, const bn_t sk, int bls)
int cp_cmlhs_fun (g1_t a, g1_t c, const g1_t as[], const g1_t cs[], const dig_t f[], size_t len)
int cp_cmlhs_evl (g1_t r, g2_t s, const g1_t rs[], const g2_t ss[], const dig_t f[], size_t len)
int cp_cmlhs_ver (const g1_t r, const g2_t s, const g1_t *sig, const g2_t *z, const g1_t *a, const g1_t *c, const bn_t m, const char *data, const g1_t h, const int *label, const gt_t *hs[], const dig_t *f[], const size_t *flen, const g2_t *y, const g2_t *pk, size_t slen, int bls)
void cp_cmlhs_off (gt_t vk, const g1_t h, const int label[], const gt_t *hs[], const dig_t *f[], const size_t flen[], size_t slen)
int cp_cmlhs_onv (const g1_t r, const g2_t s, const g1_t sig[], const g2_t z[], const g1_t a[], const g1_t c[], const bn_t msg, const char *data, const g1_t h, const gt_t vk, const g2_t y[], const g2_t pk[], size_t slen, int bls)
Detailed Description
Implementation of context-hiding linearly homomophic signature protocol.
Definition in file relic_cp_cmlhs.c.
Function Documentation
cp_cmlhs_init()
int cp_cmlhs_init (g1_t h)
Initialize the Context-hiding Multi-key Homomorphic Signature scheme (CMLHS). The scheme due to Schabhuser et al. signs a vector of messages.
Parameters
[out] h - the random element (message as one component).
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_cmlhs.c.
References g1_rand, and RLC_OK.
cp_cmlhs_gen()
int cp_cmlhs_gen (bn_t x[], gt_t hs[], size_t len, uint8_t prf[], size_t plen, bn_t sk, g2_t pk, bn_t d, g2_t y, int bls)
Definition at line 43 of file relic_cp_cmlhs.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), cp_bls_gen(), cp_ecdsa_gen(), g1_free, g1_get_gen, g1_new, g1_null, g2_free, g2_get_gen, g2_mul_gen(), g2_new, g2_null, g2_set_g1, gt_exp(), gt_free, gt_new, gt_null, pc_get_ord, pc_map, rand_bytes(), RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_cmlhs_sig()
int cp_cmlhs_sig (g1_t sig, g2_t z, g1_t a, g1_t c, g1_t r, g2_t s, const bn_t msg, const char * data, int label, const bn_t x, const g1_t h, const uint8_t prf[], size_t plen, const bn_t d, const bn_t sk, int bls)
Definition at line 100 of file relic_cp_cmlhs.c.
References bn_add(), bn_free, bn_mod, bn_mod_inv(), bn_mul, bn_new, bn_null, bn_rand_mod(), bn_read_bin(), bn_sub(), cp_bls_sig(), cp_ecdsa_sig(), ERR_NO_MEMORY, fp_prime_conv(), fp_set_dig(), g1_add, g1_free, g1_mul(), g1_mul_gen(), g1_new, g1_norm, g1_null, g2_mul_gen(), g2_neg, g2_size_bin, g2_write_bin, md_hmac(), pc_get_ord, RLC_ALLOCA, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_FREE, RLC_MD_LEN, RLC_OK, RLC_PC_BYTES, RLC_THROW, and RLC_TRY.
cp_cmlhs_fun()
int cp_cmlhs_fun (g1_t a, g1_t c, const g1_t as[], const g1_t cs[], const dig_t f[], size_t len)
Definition at line 189 of file relic_cp_cmlhs.c.
References g1_mul_sim_dig, and RLC_OK.
cp_cmlhs_evl()
int cp_cmlhs_evl (g1_t r, g2_t s, const g1_t rs[], const g2_t ss[], const dig_t f[], size_t len)
Definition at line 199 of file relic_cp_cmlhs.c.
References g1_mul_sim_dig, g2_mul_sim_dig, and RLC_OK.
cp_cmlhs_ver()
int cp_cmlhs_ver (const g1_t r, const g2_t s, const g1_t * sig, const g2_t * z, const g1_t * a, const g1_t * c, const bn_t m, const char * data, const g1_t h, const int * label, const gt_t * hs[], const dig_t * f[], const size_t * flen, const g2_t * y, const g2_t * pk, size_t slen, int bls)
Verifies a CMLHS signature over a set of messages.
Parameters
[in] r - the first component of the homomorphic signature.
[in] s - the second component of the homomorphic signature.
[in] sig - the BLS signatures.
[in] z - the powers of the outputs of the PRF.
[in] a - the vector of first components of the signatures.
[in] c - the vector of second components of the signatures.
[in] msg - the combined message.
[in] data - the dataset identifier.
[in] h - the random element (message has one component).
[in] label - the integer labels.
[in] hs - the hash values, one per label.
[in] f - the linear coefficients in the function.
[in] flen - the number of coefficients.
[in] y - the public elements of the users.
[in] pk - the public keys of the users.
[in] slen - the number of signatures.
[in] bls - the flag for selecting BLS or ECDSA.
Returns
a boolean value indicating the verification result.
Definition at line 209 of file relic_cp_cmlhs.c.
References bn_free, bn_new, bn_null, cp_bls_ver(), cp_ecdsa_ver(), ERR_CAUGHT, ERR_NO_MEMORY, fp_prime_back(), fp_set_dig(), g1_add, g1_free, g1_get_gen, g1_mul(), g1_new, g1_norm, g1_null, g1_set_g2, g1_set_infty, g2_free, g2_get_gen, g2_new, g2_null, g2_size_bin, g2_write_bin, gt_cmp, gt_exp_dig(), gt_free, gt_mul, gt_new, gt_null, pc_get_ord, pc_map, pc_map_sim, RLC_ALLOCA, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
cp_cmlhs_off()
void cp_cmlhs_off (gt_t vk, const g1_t h, const int label[], const gt_t * hs[], const dig_t * f[], const size_t flen[], size_t slen)
Definition at line 307 of file relic_cp_cmlhs.c.
References ERR_CAUGHT, gt_exp_dig(), gt_free, gt_mul, gt_new, gt_null, gt_set_unity, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
cp_cmlhs_onv()
int cp_cmlhs_onv (const g1_t r, const g2_t s, const g1_t sig[], const g2_t z[], const g1_t a[], const g1_t c[], const bn_t msg, const char * data, const g1_t h, const gt_t vk, const g2_t y[], const g2_t pk[], size_t slen, int bls)
Definition at line 330 of file relic_cp_cmlhs.c.
References bn_free, bn_new, bn_null, cp_bls_ver(), cp_ecdsa_ver(), ERR_CAUGHT, ERR_NO_MEMORY, fp_prime_back(), g1_add, g1_free, g1_get_gen, g1_mul(), g1_new, g1_norm, g1_null, g1_set_g2, g1_set_infty, g2_free, g2_get_gen, g2_new, g2_null, g2_size_bin, g2_write_bin, gt_cmp, gt_free, gt_mul, gt_new, gt_null, pc_get_ord, pc_map, pc_map_sim, RLC_ALLOCA, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.