RELIC: include/relic_fb.h File Reference
relic_fb.h File Reference
Binary field arithmetic
#include "relic_bn.h"
#include "relic_dv.h"
#include "relic_conf.h"
#include "relic_types.h"
Macros
#define RLC_FB_BITS ((size_t)FB_POLYN)
#define RLC_FB_DIGS ((size_t)RLC_CEIL(RLC_FB_BITS, RLC_DIG))
#define RLC_FB_BYTES ((size_t)RLC_CEIL(RLC_FB_BITS, 8))
#define RLC_FB_TABLE_BASIC (1)
#define RLC_FB_TABLE_QUICK ((RLC_DIG / 4) * RLC_FB_DIGS * 16)
#define RLC_FB_TABLE RLC_FB_TABLE_QUICK
#define RLC_FB_TABLE_MAX RLC_FB_TABLE_QUICK
#define fb_null(A)
#define fb_new(A)
#define fb_free(A)
#define fb_mul(C, A, B)
#define fb_sqr(C, A)
#define fb_srt(C, A)
#define fb_rdc(C, A)
#define fb_trc(A)
#define fb_slv(C, A)
#define fb_inv(C, A)
#define fb_exp(C, A, B)
#define fb_itr_pre(T, B)
#define fb_itr(C, A, ...)
#define fb_itr_imp(C, A, B, T)
Typedefs
typedef rlc_align dig_t fb_t[RLC_FB_DIGS+RLC_PAD(RLC_FB_BYTES)/(RLC_DIG/8)]
typedef rlc_align dig_t fb_st[RLC_FB_DIGS+RLC_PAD(RLC_FB_BYTES)/(RLC_DIG/8)]
Enumerations
enum {
PENTA_8 = 1 , PENTA_64 , TRINO_113 , TRINO_127 ,
PENTA_128 , PENTA_131 , NIST_163 , SQRT_163 ,
TRINO_193 , NIST_233 , SQRT_233 , SECG_239 ,
SQRT_239 , SQRT_251 , PENTA_251 , TRINO_257 ,
TRINO_271 , PENTA_271 , NIST_283 , SQRT_283 ,
TRINO_353 , TRINO_367 , NIST_409 , TRINO_439 ,
TRINO_511 , NIST_571 , SQRT_571 , TRINO_1223
}
Functions
void fb_poly_init (void)
void fb_poly_clean (void)
dig_t * fb_poly_get (void)
void fb_poly_set_dense (const fb_t f)
void fb_poly_set_trino (int a)
void fb_poly_set_penta (int a, int b, int c)
dig_t * fb_poly_get_srz (void)
const dig_t * fb_poly_tab_srz (int i)
const fb_st * fb_poly_tab_sqr (int i)
const int * fb_poly_get_chain (int *len)
void fb_poly_get_rdc (int *a, int *b, int *c)
void fb_poly_get_trc (int *a, int *b, int *c)
const dig_t * fb_poly_get_slv (void)
void fb_param_set (int param)
void fb_param_set_any (void)
void fb_param_print (void)
void fb_poly_add (fb_t c, const fb_t a)
void fb_copy (fb_t c, const fb_t a)
void fb_neg (fb_t c, const fb_t a)
void fb_zero (fb_t a)
int fb_is_zero (const fb_t a)
int fb_get_bit (const fb_t a, uint_t bit)
void fb_set_bit (fb_t a, uint_t bit, int value)
void fb_set_dig (fb_t c, dig_t a)
size_t fb_bits (const fb_t a)
void fb_rand (fb_t a)
void fb_print (const fb_t a)
size_t fb_size_str (const fb_t a, uint_t radix)
void fb_read_str (fb_t a, const char *str, size_t len, uint_t radix)
void fb_write_str (char *str, size_t len, const fb_t a, uint_t radix)
void fb_read_bin (fb_t a, const uint8_t *bin, size_t len)
void fb_write_bin (uint8_t *bin, size_t len, const fb_t a)
int fb_cmp (const fb_t a, const fb_t b)
int fb_cmp_dig (const fb_t a, dig_t b)
void fb_add (fb_t c, const fb_t a, const fb_t b)
void fb_add_dig (fb_t c, const fb_t a, dig_t b)
void fb_mul_basic (fb_t c, const fb_t a, const fb_t b)
void fb_mul_integ (fb_t c, const fb_t a, const fb_t b)
void fb_mul_lodah (fb_t c, const fb_t a, const fb_t b)
void fb_mul_dig (fb_t c, const fb_t a, dig_t b)
void fb_mul_karat (fb_t c, const fb_t a, const fb_t b)
void fb_sqr_basic (fb_t c, const fb_t a)
void fb_sqr_integ (fb_t c, const fb_t a)
void fb_sqr_quick (fb_t c, const fb_t a)
void fb_lsh (fb_t c, const fb_t a, uint_t bits)
void fb_rsh (fb_t c, const fb_t a, uint_t bits)
void fb_rdc_basic (fb_t c, dv_t a)
void fb_rdc_quick (fb_t c, dv_t a)
void fb_srt_basic (fb_t c, const fb_t a)
void fb_srt_quick (fb_t c, const fb_t a)
dig_t fb_trc_basic (const fb_t a)
dig_t fb_trc_quick (const fb_t a)
void fb_inv_basic (fb_t c, const fb_t a)
void fb_inv_binar (fb_t c, const fb_t a)
void fb_inv_exgcd (fb_t c, const fb_t a)
void fb_inv_almos (fb_t c, const fb_t a)
void fb_inv_itoht (fb_t c, const fb_t a)
void fb_inv_bruch (fb_t c, const fb_t a)
void fb_inv_ctaia (fb_t c, const fb_t a)
void fb_inv_lower (fb_t c, const fb_t a)
void fb_inv_sim (fb_t *c, const fb_t *a, int n)
void fb_exp_2b (fb_t c, const fb_t a, int b)
void fb_exp_basic (fb_t c, const fb_t a, const bn_t b)
void fb_exp_slide (fb_t c, const fb_t a, const bn_t b)
void fb_exp_monty (fb_t c, const fb_t a, const bn_t b)
void fb_slv_basic (fb_t c, const fb_t a)
void fb_slv_quick (fb_t c, const fb_t a)
void fb_itr_basic (fb_t c, const fb_t a, int b)
void fb_itr_pre_quick (fb_st *t, int b)
void fb_itr_quick (fb_t c, const fb_t a, const fb_st *t)
Detailed Description
Interface of module for binary field arithmetic.
Definition in file relic_fb.h.
Macro Definition Documentation
RLC_FB_BITS
#define RLC_FB_BITS ((size_t)FB_POLYN)
Precision in bits of a binary field element.
Definition at line 51 of file relic_fb.h.
Referenced by conf_print(), eb_map(), eb_mul_fix_kbltz(), eb_mul_fix_plain(), eb_mul_halve(), eb_mul_lnaf_imp(), eb_mul_ltnaf_imp(), eb_mul_rnaf_imp(), eb_mul_rtnaf_imp(), eb_mul_sim_joint(), eb_mul_sim_kbltz(), eb_mul_sim_plain(), eb_mul_sim_trick(), fb_exp_slide(), fb_inv_almos(), fb_inv_basic(), fb_inv_binar(), fb_inv_bruch(), fb_inv_ctaia(), fb_inv_exgcd(), fb_inv_itoht(), fb_mul_basic(), fb_param_print(), fb_poly_set_penta(), fb_poly_set_trino(), fb_rand(), fb_rdc_basic(), fb_read_str(), fb_slv_basic(), fb_srt_basic(), fb_trc_basic(), find_chain(), find_solve(), find_srz(), and find_trace().
RLC_FB_DIGS
#define RLC_FB_DIGS ((size_t)RLC_CEIL(RLC_FB_BITS, RLC_DIG))
Size in digits of a block sufficient to store a binary field element.
Definition at line 56 of file relic_fb.h.
Referenced by conf_print(), eb_curve_init(), eb_map(), eb_mul_lodah(), fb_bits(), fb_cmp(), fb_cmp_dig(), fb_copy(), fb_exp_monty(), fb_inv_almos(), fb_inv_binar(), fb_inv_bruch(), fb_inv_ctaia(), fb_inv_exgcd(), fb_is_zero(), fb_itr_pre_quick(), fb_lsh(), fb_mul_basic(), fb_mul_karat(), fb_poly_add(), fb_print(), fb_rand(), fb_rdc_basic(), fb_rsh(), fb_size_str(), fb_write_bin(), and fb_zero().
RLC_FB_BYTES
#define RLC_FB_BYTES ((size_t)RLC_CEIL(RLC_FB_BITS, 8))
Size in bytes of a block sufficient to store a binary field element.
Definition at line 61 of file relic_fb.h.
Referenced by eb_map(), eb_param_set(), eb_read_bin(), eb_size_bin(), eb_write_bin(), fb_read_bin(), and fb_write_bin().
RLC_FB_TABLE_BASIC
#define RLC_FB_TABLE_BASIC (1)
Size of a precomputation table for repeated squaring/square-root using the trivial approach.
Definition at line 129 of file relic_fb.h.
RLC_FB_TABLE_QUICK
#define RLC_FB_TABLE_QUICK ((RLC_DIG / 4) * RLC_FB_DIGS * 16)
Size of a precomputation table for repeated squaring/square-root using the faster approach.
Definition at line 135 of file relic_fb.h.
RLC_FB_TABLE
#define RLC_FB_TABLE RLC_FB_TABLE_QUICK
Size of a precomputation table for repeated squaring/square-root using the chosen algorithm.
Definition at line 144 of file relic_fb.h.
RLC_FB_TABLE_MAX
#define RLC_FB_TABLE_MAX RLC_FB_TABLE_QUICK
Maximum size of a precomputation table.
Definition at line 153 of file relic_fb.h.
fb_null
#define fb_null (A)
Value:
/* empty */
Initializes a binary field element with a null value.
Parameters
[out] A - the binary field element to initialize.
Definition at line 184 of file relic_fb.h.
Referenced by eb_add_basic_imp(), eb_add_projc_imp(), eb_add_projc_mix(), eb_blind(), eb_dbl_basic_imp(), eb_dbl_projc_imp(), eb_hlv(), eb_map(), eb_mul_halve(), eb_neg_projc(), eb_norm_sim(), eb_on_curve(), eb_param_set(), eb_rhs(), eb_upk(), fb2_inv(), fb2_mul(), fb2_mul_nor(), fb_exp_basic(), fb_exp_monty(), fb_exp_slide(), fb_inv_basic(), fb_inv_bruch(), fb_inv_ctaia(), fb_inv_exgcd(), fb_inv_itoht(), fb_inv_sim(), fb_itr_pre_quick(), fb_mul_basic(), fb_poly_set_penta(), fb_poly_set_trino(), fb_slv_basic(), fb_trc_basic(), fb_write_str(), find_solve(), and find_trace().
fb_new
#define fb_new (A)
Value:
/* empty */
Calls a function to allocate a binary field element.
Parameters
[out] A - the new binary field element.
Exceptions
ERR_NO_MEMORY - if there is no available memory.
Definition at line 198 of file relic_fb.h.
Referenced by eb_add_basic_imp(), eb_add_projc_imp(), eb_add_projc_mix(), eb_blind(), eb_dbl_basic_imp(), eb_dbl_projc_imp(), eb_hlv(), eb_map(), eb_mul_halve(), eb_neg_projc(), eb_norm_sim(), eb_on_curve(), eb_param_set(), eb_rhs(), eb_upk(), fb2_inv(), fb2_mul(), fb2_mul_nor(), fb_exp_basic(), fb_exp_monty(), fb_exp_slide(), fb_inv_basic(), fb_inv_bruch(), fb_inv_ctaia(), fb_inv_itoht(), fb_inv_sim(), fb_itr_pre_quick(), fb_mul_basic(), fb_poly_set_penta(), fb_poly_set_trino(), fb_slv_basic(), fb_trc_basic(), fb_write_str(), find_solve(), and find_trace().
fb_free
#define fb_free (A)
Value:
/* empty */
Calls a function to free a binary field element.
Parameters
[out] A - the binary field element to clean and free.
Definition at line 209 of file relic_fb.h.
Referenced by eb_add_basic_imp(), eb_add_projc_imp(), eb_add_projc_mix(), eb_blind(), eb_dbl_basic_imp(), eb_dbl_projc_imp(), eb_hlv(), eb_map(), eb_mul_halve(), eb_neg_projc(), eb_norm_sim(), eb_on_curve(), eb_param_set(), eb_rhs(), eb_upk(), fb2_inv(), fb2_mul(), fb2_mul_nor(), fb_exp_basic(), fb_exp_monty(), fb_exp_slide(), fb_inv_basic(), fb_inv_bruch(), fb_inv_ctaia(), fb_inv_itoht(), fb_inv_sim(), fb_itr_pre_quick(), fb_mul_basic(), fb_poly_set_penta(), fb_poly_set_trino(), fb_rdc_basic(), fb_slv_basic(), fb_trc_basic(), fb_write_str(), find_solve(), and find_trace().
fb_mul
#define fb_mul (C, A, B)
Value:
fb_mul_lodah(C, A, B)
Multiples two binary field elements. Computes c = a * b.
Parameters
[out] C - the result.
[in] A - the first binary field element to multiply.
[in] B - the second binary field element to multiply.
Definition at line 226 of file relic_fb.h.
Referenced by eb_add_basic_imp(), eb_add_projc_imp(), eb_add_projc_mix(), eb_blind(), eb_cmp(), eb_dbl_basic_imp(), eb_dbl_projc_imp(), eb_hlv(), eb_map(), eb_mul_halve(), eb_mul_lodah(), eb_neg_projc(), eb_norm_hlv(), eb_norm_imp(), eb_on_curve(), eb_pck(), eb_rhs(), eb_upk(), fb2_inv(), fb2_mul(), fb_exp_basic(), fb_exp_monty(), fb_exp_slide(), fb_inv_basic(), fb_inv_itoht(), and fb_inv_sim().
fb_sqr
#define fb_sqr (C, A)
Value:
fb_sqr_quick(C, A)
Squares a binary field element. Computes c = a * a.
Parameters
[out] C - the result.
[in] A - the binary field element to square.
Definition at line 238 of file relic_fb.h.
Referenced by eb_add_basic_imp(), eb_add_projc_imp(), eb_add_projc_mix(), eb_blind(), eb_cmp(), eb_dbl_basic_imp(), eb_dbl_projc_imp(), eb_frb(), eb_map(), eb_mul_lodah(), eb_mul_rtnaf_imp(), eb_norm_imp(), eb_on_curve(), eb_rhs(), eb_upk(), fb2_inv(), fb2_sqr(), fb_exp_basic(), fb_exp_monty(), fb_exp_slide(), fb_inv_basic(), fb_inv_itoht(), fb_itr_basic(), fb_itr_pre_quick(), fb_slv_basic(), fb_srt_basic(), fb_trc_basic(), find_solve(), find_srz(), and find_trace().
fb_srt
#define fb_srt (C, A)
Value:
fb_srt_quick(C, A)
Extracts the square root of a binary field element. Computes c = a^(1/2).
Parameters
[out] C - the result.
[in] A - the binary field element.
Definition at line 252 of file relic_fb.h.
Referenced by eb_hlv(), eb_mul_halve(), fb_itr_basic(), and fb_itr_pre_quick().
fb_rdc
#define fb_rdc (C, A)
Value:
fb_rdc_quick(C, A)
Reduces a multiplication result modulo a binary irreducible polynomial. Computes c = a mod f(z).
Parameters
[out] C - the result.
[in] A - the multiplication result to reduce.
Definition at line 265 of file relic_fb.h.
Referenced by fb_mul_basic(), fb_mul_karat(), fb_mul_lodah(), fb_sqr_basic(), and fb_sqr_quick().
fb_trc
#define fb_trc (A)
Value:
fb_trc_quick(A)
Compute the trace of a binary field element. Computes c = Tr(a).
Parameters
[in] A - the binary field element.
Returns
the trace of the binary field element.
Definition at line 277 of file relic_fb.h.
Referenced by eb_hlv(), eb_map(), eb_mul_halve(), eb_upk(), fb2_slv(), fb_slv_basic(), and fb_slv_quick().
fb_slv
#define fb_slv (C, A)
Value:
fb_slv_quick(C, A)
Solves a quadratic equation for c, Tr(a) = 0. Computes c such that c^2 + c = a.
Parameters
[out] C - the result.
[in] A - the binary field element.
Definition at line 290 of file relic_fb.h.
Referenced by eb_hlv(), eb_map(), eb_mul_halve(), eb_upk(), and fb2_slv().
fb_inv
#define fb_inv (C, A)
Value:
fb_inv_exgcd(C, A)
Inverts a binary field element. Computes c = a^{-1}.
Parameters
[out] C - the result.
[in] A - the binary field element to invert.
Definition at line 304 of file relic_fb.h.
Referenced by eb_add_basic_imp(), eb_dbl_basic_imp(), eb_map(), eb_mul_lodah(), eb_norm_imp(), eb_pck(), eb_upk(), fb2_inv(), fb_exp_basic(), fb_exp_monty(), fb_exp_slide(), and fb_inv_sim().
fb_exp
#define fb_exp (C, A, B)
Value:
fb_exp_slide(C, A, B)
Exponentiates a binary field element. Computes c = a^b.
Parameters
[out] C - the result.
[in] A - the basis.
[in] B - the exponent.
Definition at line 327 of file relic_fb.h.
fb_itr_pre
#define fb_itr_pre (T, B)
Value:
fb_itr_pre_quick(T, B)
Precomputed the table for repeated squaring/square-root.
Parameters
[out] T - the table.
[in] B - the exponent.
Definition at line 341 of file relic_fb.h.
Referenced by find_chain().
fb_itr
#define fb_itr (C, A, ...)
Value:
RLC_CAT(fb_itr, RLC_OPT(__VA_ARGS__)) (C, A, __VA_ARGS__)
Computes the repeated Frobenius (squaring) or inverse Frobenius (square-root) of a binary field element. If the number of arguments is 3, then simple consecutive squaring/square-root is used. If the number of arguments if 4, then a table-based method is used and the fourth argument is a pointer fo the precomputed table. The variant with 4 arguments should be used when several 2^k/2^-k powers are computed with the same k. Computes c = a^(2^b), where b can be positive or negative.
Parameters
[out] C - the result.
[in] A - the binary field element to exponentiate.
[in] B - the exponent.
[in] ... - the modulus and an optional argument.
Definition at line 358 of file relic_fb.h.
Referenced by fb_inv_itoht().
fb_itr_imp
#define fb_itr_imp (C, A, B, T)
Value:
fb_itr_quick(C, A, T)
Reduces a multiple precision integer modulo another integer. This macro should not be called directly. Use bn_mod() with 4 arguments instead.
Parameters
[out] C - the result.
[in] A - the binary field element to exponentiate.
[in] B - the exponent.
[in] T - the precomputed table for the exponent.
Definition at line 372 of file relic_fb.h.
Typedef Documentation
fb_t
typedef rlc_align dig_t fb_t[RLC_FB_DIGS+RLC_PAD(RLC_FB_BYTES)/(RLC_DIG/8)]
Represents a binary field element.
Definition at line 164 of file relic_fb.h.
fb_st
typedef rlc_align dig_t fb_st[RLC_FB_DIGS+RLC_PAD(RLC_FB_BYTES)/(RLC_DIG/8)]
Represents a binary field element with automatic memory allocation.
Definition at line 172 of file relic_fb.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Finite field identifiers.
Enumerator
PENTA_8
AES pentaonimal.
PENTA_64
Toy pentanomial.
TRINO_113
Hankerson's trinomial for GLS curves.
TRINO_127
Hankerson's trinomial for GLS curves.
PENTA_128
GCM pentanomial
PENTA_131
Pentanomial for ECC2K-130 challenge.
NIST_163
NIST 163-bit fast reduction polynomial.
SQRT_163
Square-root friendly 163-bit polynomial.
TRINO_193
Example with 193 bits for Itoh-Tsuji.
NIST_233
NIST 233-bit fast reduction polynomial.
SQRT_233
Square-root friendly 233-bit polynomial.
SECG_239
SECG 239-bit fast reduction polynomial.
SQRT_239
Square-root friendly 239-bit polynomial.
SQRT_251
Square-root friendly 251-bit polynomial.
PENTA_251
eBATS curve_2_251 pentanomial.
TRINO_257
Hankerson's trinomial for halving curve.
TRINO_271
Scott's 271-bit pairing-friendly trinomial.
PENTA_271
Scott's 271-bit pairing-friendly pentanomial.
NIST_283
NIST 283-bit fast reduction polynomial.
SQRT_283
Square-root friendly 283-bit polynomial.
TRINO_353
Scott's 271-bit pairing-friendly trinomial.
TRINO_367
Detrey's trinomial for genus 2 curves.
NIST_409
NIST 409-bit fast reduction polynomial.
TRINO_439
Hankerson's trinomial for genus 2 curves.
TRINO_511
Custom 511-bit fast reduction polynomial.
NIST_571
NIST 571-bit fast reduction polynomial.
SQRT_571
Square-root friendly 571-bit polynomial.
TRINO_1223
Scott's 1223-bit pairing-friendly trinomial.
Definition at line 66 of file relic_fb.h.
Function Documentation
fb_poly_init()
void fb_poly_init (void)
Initializes the binary field arithmetic layer.
Definition at line 314 of file relic_fb_poly.c.
References core_get(), _ctx_t::fb_na, _ctx_t::fb_nb, _ctx_t::fb_nc, _ctx_t::fb_pa, _ctx_t::fb_pb, _ctx_t::fb_pc, _ctx_t::fb_poly, and fb_zero().
Referenced by core_init().
fb_poly_clean()
void fb_poly_clean (void)
Finalizes the binary field arithmetic layer.
Definition at line 322 of file relic_fb_poly.c.
Referenced by core_clean().
fb_poly_get()
dig_t * fb_poly_get (void)
Returns the irreducible polynomial f(z) configured for the binary field.
Returns
the irreducible polynomial.
Definition at line 325 of file relic_fb_poly.c.
References core_get(), and _ctx_t::fb_poly.
Referenced by fb_inv_almos(), fb_inv_binar(), fb_inv_bruch(), fb_inv_ctaia(), fb_inv_exgcd(), and fb_rdc_basic().
fb_poly_set_dense()
void fb_poly_set_dense (const fb_t f)
Configures the irreducible polynomial of the binary field as a dense polynomial.
Parameters
[in] f - the new irreducible polynomial.
Definition at line 357 of file relic_fb_poly.c.
References core_get(), _ctx_t::fb_na, _ctx_t::fb_nb, _ctx_t::fb_nc, _ctx_t::fb_pa, _ctx_t::fb_pb, _ctx_t::fb_pc, and fb_poly_set().
fb_poly_set_trino()
void fb_poly_set_trino (int a)
Configures a trinomial as the irreducible polynomial by its non-zero coefficients. The other coefficients are RLC_FB_BITS and 0.
Parameters
[in] a - the second coefficient.
Definition at line 364 of file relic_fb_poly.c.
References core_get(), ERR_CAUGHT, fb_free, _ctx_t::fb_na, _ctx_t::fb_nb, _ctx_t::fb_nc, fb_new, fb_null, _ctx_t::fb_pa, _ctx_t::fb_pb, _ctx_t::fb_pc, fb_poly_set(), fb_set_bit(), fb_zero(), RLC_CATCH_ANY, RLC_DIG_LOG, RLC_FB_BITS, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fb_param_set().
fb_poly_set_penta()
void fb_poly_set_penta (int a, int b, int c)
Configures a pentanomial as the binary field modulo by its non-zero coefficients. The other coefficients are RLC_FB_BITS and 0.
Parameters
[in] a - the second coefficient.
[in] b - the third coefficient.
[in] c - the fourth coefficient.
Definition at line 392 of file relic_fb_poly.c.
References core_get(), ERR_CAUGHT, fb_free, _ctx_t::fb_na, _ctx_t::fb_nb, _ctx_t::fb_nc, fb_new, fb_null, _ctx_t::fb_pa, _ctx_t::fb_pb, _ctx_t::fb_pc, fb_poly_set(), fb_set_bit(), fb_zero(), RLC_CATCH_ANY, RLC_DIG_LOG, RLC_FB_BITS, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fb_param_set().
fb_poly_get_srz()
dig_t * fb_poly_get_srz (void)
Returns the square root of z.
Returns
the square root of z.
Definition at line 425 of file relic_fb_poly.c.
References core_get(), and _ctx_t::fb_srz.
fb_poly_tab_srz()
const dig_t * fb_poly_tab_srz (int i)
Returns sqrt(z) * (i represented as a polynomial).
Returns
the precomputed result.
Definition at line 442 of file relic_fb_poly.c.
References core_get(), and _ctx_t::fb_tab_srz.
fb_poly_tab_sqr()
const fb_st * fb_poly_tab_sqr (int i)
Returns a table for accelerating repeated squarings.
Parameters
the number of the table.
Returns
the precomputed result.
Definition at line 433 of file relic_fb_poly.c.
References core_get(), and _ctx_t::fb_tab_sqr.
Referenced by fb_inv_itoht(), and find_chain().
fb_poly_get_chain()
const int * fb_poly_get_chain (int * len)
Returns an addition chain for (RLC_FB_BITS - 1).
Parameters
[out] len - the number of elements in the addition chain.
Returns
a pointer to the addition chain.
Definition at line 482 of file relic_fb_poly.c.
References _ctx_t::chain, _ctx_t::chain_len, core_get(), and RLC_TERMS.
Referenced by fb_inv_itoht().
fb_poly_get_rdc()
void fb_poly_get_rdc (int * a, int * b, int * c)
Returns the non-zero coefficients of the configured trinomial or pentanomial. If b is -1, the irreducible polynomial configured is a trinomial. The other coefficients are RLC_FB_BITS and 0.
Parameters
[out] a - the second coefficient.
[out] b - the third coefficient.
[out] c - the fourth coefficient.
Definition at line 467 of file relic_fb_poly.c.
References core_get(), _ctx_t::fb_pa, _ctx_t::fb_pb, and _ctx_t::fb_pc.
Referenced by fb_param_print().
fb_poly_get_trc()
void fb_poly_get_trc (int * a, int * b, int * c)
Returns the non-zero bits used to compute the trace function. The -1 coefficient is the last coefficient.
Parameters
[out] a - the first coefficient.
[out] b - the second coefficient.
[out] c - the third coefficient.
Definition at line 456 of file relic_fb_poly.c.
References core_get(), _ctx_t::fb_ta, _ctx_t::fb_tb, and _ctx_t::fb_tc.
fb_poly_get_slv()
const dig_t * fb_poly_get_slv (void)
Returns the table of precomputed half-traces.
Returns
the table of half-traces.
Definition at line 474 of file relic_fb_poly.c.
References core_get(), and _ctx_t::fb_half.
fb_param_set()
void fb_param_set (int param)
Assigns a standard irreducible polynomial as modulo of the binary field.
Parameters
[in] param - the standardized polynomial identifier.
Definition at line 50 of file relic_fb_param.c.
References core_get(), ERR_NO_VALID, _ctx_t::fb_id, fb_poly_set_penta(), fb_poly_set_trino(), NIST_163, NIST_233, NIST_283, NIST_409, NIST_571, PENTA_128, PENTA_131, PENTA_251, PENTA_271, PENTA_64, PENTA_8, RLC_THROW, SECG_239, SQRT_163, SQRT_233, SQRT_239, SQRT_251, SQRT_283, SQRT_571, TRINO_113, TRINO_1223, TRINO_127, TRINO_193, TRINO_257, TRINO_271, TRINO_353, TRINO_367, TRINO_439, and TRINO_511.
Referenced by fb_param_set_any().
fb_param_set_any()
void fb_param_set_any (void)
Configures some finite field parameters for the current security level.
Definition at line 147 of file relic_fb_param.c.
References ERR_NO_FIELD, fb_param_set(), NIST_163, NIST_233, NIST_283, NIST_409, NIST_571, PENTA_128, PENTA_131, PENTA_251, PENTA_271, PENTA_64, PENTA_8, RLC_THROW, SECG_239, SQRT_163, SQRT_233, SQRT_239, SQRT_251, SQRT_283, SQRT_571, TRINO_113, TRINO_1223, TRINO_127, TRINO_193, TRINO_257, TRINO_271, TRINO_353, TRINO_367, TRINO_439, and TRINO_511.
fb_param_print()
void fb_param_print (void)
Prints the currently configured irreducible polynomial.
Definition at line 243 of file relic_fb_param.c.
References fb_poly_get_rdc(), RLC_FB_BITS, util_banner, and util_print.
fb_poly_add()
void fb_poly_add (fb_t c, const fb_t a)
Adds a binary field element and the irreducible polynomial. Computes c = a + f(z).
Parameters
[out] c - the destination.
[in] a - the binary field element.
Definition at line 329 of file relic_fb_poly.c.
References core_get(), fb_add(), fb_copy(), _ctx_t::fb_na, _ctx_t::fb_nb, _ctx_t::fb_nc, _ctx_t::fb_pa, _ctx_t::fb_pb, _ctx_t::fb_pc, _ctx_t::fb_poly, and RLC_FB_DIGS.
Referenced by fb_inv_almos(), fb_inv_binar(), fb_inv_ctaia(), and fb_mul_basic().
fb_copy()
void fb_copy (fb_t c, const fb_t a)
Copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the binary field element to copy.
Definition at line 77 of file relic_fb_util.c.
References dv_copy(), and RLC_FB_DIGS.
Referenced by eb_add_basic_imp(), eb_add_projc_mix(), eb_copy(), eb_curve_set(), eb_dbl_basic_imp(), eb_dbl_projc_imp(), eb_hlv(), eb_mul_halve(), eb_mul_lodah(), eb_neg_basic(), eb_neg_projc(), eb_norm_hlv(), eb_norm_imp(), eb_norm_sim(), eb_pck(), eb_rhs(), eb_upk(), fb2_mul_nor(), fb_exp_basic(), fb_exp_monty(), fb_exp_slide(), fb_inv_almos(), fb_inv_basic(), fb_inv_binar(), fb_inv_bruch(), fb_inv_ctaia(), fb_inv_exgcd(), fb_inv_itoht(), fb_inv_sim(), fb_itr_basic(), fb_itr_pre_quick(), fb_lsh(), fb_mul_basic(), fb_poly_add(), fb_poly_set(), fb_rdc_basic(), fb_read_bin(), fb_rsh(), fb_slv_basic(), fb_srt_basic(), fb_trc_basic(), fb_write_str(), find_solve(), and find_trace().
fb_neg()
void fb_neg (fb_t c, const fb_t a)
Negates a binary field element.
Parameters
[out] c - the result.
[out] a - the binary field element to negate.
fb_zero()
void fb_zero (fb_t a)
Assigns zero to a binary field element.
Parameters
[out] a - the binary field element to assign.
Definition at line 81 of file relic_fb_util.c.
References dv_zero(), and RLC_FB_DIGS.
Referenced by eb_curve_init(), eb_mul_halve(), eb_param_set(), eb_read_bin(), eb_set_infty(), fb_inv_bruch(), fb_inv_ctaia(), fb_itr_pre_quick(), fb_mul_basic(), fb_poly_init(), fb_poly_set_penta(), fb_poly_set_trino(), fb_read_str(), fb_set_dig(), find_solve(), and find_trace().
fb_is_zero()
int fb_is_zero (const fb_t a)
Tests if a binary field element is zero or not.
Parameters
[in] a - the binary field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 85 of file relic_fb_util.c.
References RLC_FB_DIGS.
Referenced by detect_opt(), eb_add_basic_imp(), eb_add_projc_imp(), eb_add_projc_mix(), eb_is_infty(), eb_mul_lodah(), fb_inv_almos(), fb_inv_basic(), fb_inv_binar(), fb_inv_bruch(), fb_inv_ctaia(), fb_inv_exgcd(), fb_inv_itoht(), fb_inv_lower(), fb_write_str(), and find_trace().
fb_get_bit()
int fb_get_bit (const fb_t a, uint_t bit)
Reads the bit stored in the given position on a binary field element.
Parameters
[in] a - the binary field element.
[in] bit - the bit position.
Returns
the bit value.
Definition at line 96 of file relic_fb_util.c.
References RLC_RIP.
Referenced by eb_pck(), eb_upk(), eb_write_bin(), fb_mul_basic(), and fb_rdc_basic().
fb_set_bit()
void fb_set_bit (fb_t a, uint_t bit, int value)
Stores a bit in a given position on a binary field element.
Parameters
[out] a - the binary field element.
[in] bit - the bit position.
[in] value - the bit value.
Definition at line 104 of file relic_fb_util.c.
References RLC_RIP.
Referenced by eb_mul_sim_kbltz(), eb_param_set(), eb_read_bin(), fb_poly_set_penta(), fb_poly_set_trino(), find_solve(), and find_trace().
fb_set_dig()
void fb_set_dig (fb_t c, dig_t a)
Assigns a small positive polynomial to a binary field element.
The degree of the polynomial must be smaller than RLC_DIG.
Parameters
[out] c - the result.
[in] a - the small polynomial to assign.
Definition at line 129 of file relic_fb_util.c.
References fb_zero().
Referenced by eb_frb(), eb_hlv(), eb_map(), eb_mul_halve(), eb_mul_lnaf_imp(), eb_mul_lodah(), eb_norm_imp(), eb_norm_sim(), eb_pck(), eb_read_bin(), eb_tab(), eb_upk(), fb_exp_basic(), fb_exp_monty(), fb_exp_slide(), fb_inv_almos(), fb_inv_basic(), fb_inv_bruch(), fb_inv_ctaia(), fb_itr_pre_quick(), and find_srz().
fb_bits()
size_t fb_bits (const fb_t a)
Returns the number of bits of a binary field element.
Parameters
[in] a - the binary field element.
Returns
the number of bits.
Definition at line 119 of file relic_fb_util.c.
References RLC_DIG_LOG, RLC_FB_DIGS, and util_bits_dig().
Referenced by detect_opt(), fb_inv_exgcd(), fb_mul_basic(), and fb_rdc_basic().
fb_rand()
void fb_rand (fb_t a)
Assigns a random value to a binary field element.
Parameters
[out] a - the binary field element to assign.
Definition at line 134 of file relic_fb_util.c.
References rand_bytes(), RLC_FB_BITS, RLC_FB_DIGS, RLC_MASK, and RLC_RIP.
Referenced by eb_blind(), and eb_mul_lodah().
fb_print()
void fb_print (const fb_t a)
Prints a binary field element to standard output.
Parameters
[in] a - the binary field element to print.
Definition at line 146 of file relic_fb_util.c.
References RLC_FB_DIGS, util_print, and util_print_dig().
Referenced by eb_print().
fb_size_str()
size_t fb_size_str (const fb_t a, uint_t radix)
Returns the number of digits in radix necessary to store a binary field element. The radix must be a power of 2 included in the interval [2, 64].
Parameters
[in] a - the binary field element.
[in] radix - the radix.
Exceptions
ERR_NO_VALID - if the radix is invalid.
Returns
the number of digits in the given radix.
Definition at line 157 of file relic_fb_util.c.
References bn_free, bn_new, bn_null, bn_read_raw(), bn_size_str(), ERR_CAUGHT, ERR_NO_VALID, RLC_CATCH_ANY, RLC_FB_DIGS, RLC_FINALLY, RLC_THROW, RLC_TRY, and valid_radix().
Referenced by fb_write_str().
fb_read_str()
void fb_read_str (fb_t a, const char * str, size_t len, uint_t radix)
Reads a binary field element from a string in a given radix. The radix must be a power of 2 included in the interval [2, 64].
Parameters
[out] a - the result.
[in] str - the string.
[in] len - the size of the string.
[in] radix - the radix.
Exceptions
ERR_NO_VALID - if the radix is invalid.
ERR_NO_BUFFER - if the string is too long.
Definition at line 185 of file relic_fb_util.c.
References bn_bits(), bn_free, bn_new, bn_null, bn_read_str(), dv_copy(), ERR_CAUGHT, ERR_NO_BUFFER, ERR_NO_VALID, fb_zero(), RLC_CATCH_ANY, RLC_FB_BITS, RLC_FINALLY, RLC_THROW, RLC_TRY, and valid_radix().
fb_write_str()
void fb_write_str (char * str, size_t len, const fb_t a, uint_t radix)
Writes a binary field element to a string in a given radix. The radix must be a power of 2 included in the interval [2, 64].
Parameters
[out] str - the string.
[in] len - the buffer capacity.
[in] a - the binary field element to write.
[in] radix - the radix.
Exceptions
ERR_NO_VALID - if the radix is invalid.
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 214 of file relic_fb_util.c.
References ERR_CAUGHT, ERR_NO_BUFFER, ERR_NO_VALID, fb_copy(), fb_free, fb_is_zero(), fb_new, fb_null, fb_rshb_low(), fb_size_str(), log_radix(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, RLC_TRY, util_conv_char(), and valid_radix().
fb_read_bin()
void fb_read_bin (fb_t a, const uint8_t * bin, size_t len)
Reads a binary field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.,
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not RLC_FP_BYTES.
Definition at line 273 of file relic_fb_util.c.
References bn_free, bn_new, bn_null, bn_read_bin(), ERR_CAUGHT, ERR_NO_BUFFER, fb_copy(), RLC_CATCH_ANY, RLC_FB_BYTES, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by eb_read_bin().
fb_write_bin()
void fb_write_bin (uint8_t * bin, size_t len, const fb_t a)
Writes a binary field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the binary field element to write.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not RLC_FP_BYTES.
Definition at line 298 of file relic_fb_util.c.
References bn_free, bn_new, bn_null, bn_read_raw(), bn_write_bin(), ERR_CAUGHT, ERR_NO_BUFFER, RLC_CATCH_ANY, RLC_FB_BYTES, RLC_FB_DIGS, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by eb_write_bin().
fb_cmp()
int fb_cmp (const fb_t a, const fb_t b)
Returns the result of a comparison between two binary field elements.
Parameters
[in] a - the first binary field element.
[in] b - the second binary field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 50 of file relic_fb_cmp.c.
References dv_cmp_sec(), and RLC_FB_DIGS.
Referenced by eb_cmp(), and eb_on_curve().
fb_cmp_dig()
int fb_cmp_dig (const fb_t a, dig_t b)
Returns the result of a comparison between a binary field element and a small binary field element.
Parameters
[in] a - the binary field element.
[in] b - the small binary field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 40 of file relic_fb_cmp.c.
References RLC_EQ, RLC_FB_DIGS, and RLC_NE.
Referenced by detect_opt(), and eb_curve_set().
fb_add()
void fb_add (fb_t c, const fb_t a, const fb_t b)
Adds two binary field elements. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first binary field element to add.
[in] b - the second binary field element to add.
Definition at line 44 of file relic_fb_add.c.
References fb_addn_low().
Referenced by eb_add_basic_imp(), eb_add_projc_imp(), eb_add_projc_mix(), eb_dbl_basic_imp(), eb_dbl_projc_imp(), eb_hlv(), eb_mul_halve(), eb_mul_lodah(), eb_neg_basic(), eb_neg_projc(), eb_norm_hlv(), eb_on_curve(), eb_rhs(), fb2_inv(), fb2_mul(), fb2_mul_nor(), fb2_slv(), fb2_sqr(), fb_inv_binar(), fb_inv_bruch(), fb_mul_basic(), fb_poly_add(), fb_slv_basic(), fb_trc_basic(), find_solve(), and find_trace().
fb_add_dig()
void fb_add_dig (fb_t c, const fb_t a, dig_t b)
Adds a binary field element and a small binary field element. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the binary field element to add.
[in] b - the small binary field element to add.
Definition at line 48 of file relic_fb_add.c.
References fb_add1_low().
Referenced by eb_add_basic_imp(), eb_dbl_basic_imp(), eb_hlv(), eb_mul_lodah(), eb_rhs(), eb_upk(), fb2_slv(), fb_slv_basic(), and fb_slv_quick().
fb_mul_basic()
void fb_mul_basic (fb_t c, const fb_t a, const fb_t b)
Multiples two binary field elements using Shift-and-add multiplication.
Parameters
[out] c - the result.
[in] a - the first binary field element to multiply.
[in] b - the second binary field element to multiply.
Definition at line 188 of file relic_fb_mul.c.
References dv_new, dv_null, dv_zero(), ERR_CAUGHT, fb_add(), fb_bits(), fb_copy(), fb_free, fb_get_bit(), fb_lsh1_low(), fb_new, fb_null, fb_poly_add(), fb_rdc, fb_zero(), RLC_CATCH_ANY, RLC_FB_BITS, RLC_FB_DIGS, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fb_mul_integ()
void fb_mul_integ (fb_t c, const fb_t a, const fb_t b)
Multiples two binary field elements using multiplication integrated with modular reduction.
Parameters
[out] c - the result.
[in] a - the first binary field element to multiply.
[in] b - the second binary field element to multiply.
Definition at line 236 of file relic_fb_mul.c.
References fb_mulm_low().
fb_mul_lodah()
void fb_mul_lodah (fb_t c, const fb_t a, const fb_t b)
Multiples two binary field elements using Lopez-Dahab multiplication.
Parameters
[out] c - the result.
[in] a - the first binary field element to multiply.
[in] b - the second binary field element to multiply.
Definition at line 244 of file relic_fb_mul.c.
References dv_free, dv_new, dv_null, ERR_CAUGHT, fb_muln_low(), fb_rdc, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fb_mul_dig()
void fb_mul_dig (fb_t c, const fb_t a, dig_t b)
Multiplies a binary field element by a small binary field element.
Parameters
[out] c - the result.
[in] a - the binary field element.
[in] b - the small binary field element to multiply.
Definition at line 290 of file relic_fb_mul.c.
References dv_free, dv_new, dv_null, ERR_CAUGHT, fb_mul1_low(), fb_rdc1_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by eb_add_projc_mix(), eb_dbl_projc_imp(), eb_rhs(), and find_srz().
fb_mul_karat()
void fb_mul_karat (fb_t c, const fb_t a, const fb_t b)
Multiples two binary field elements using Karatsuba multiplication.
Parameters
[out] c - the result.
[in] a - the first binary field element.
[in] b - the second binary field element.
Definition at line 267 of file relic_fb_mul.c.
References dv_free, dv_new, dv_null, dv_zero(), ERR_CAUGHT, FB_KARAT, fb_mul_karat_imp(), fb_rdc, RLC_CATCH_ANY, RLC_FB_DIGS, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fb_sqr_basic()
void fb_sqr_basic (fb_t c, const fb_t a)
Squares a binary field element using bit-manipulation squaring.
Parameters
[out] c - the result.
[in] a - the binary field element to square.
Definition at line 47 of file relic_fb_sqr.c.
References dv_free, dv_new, dv_null, ERR_CAUGHT, fb_rdc, fb_sqrn_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fb_sqr_integ()
void fb_sqr_integ (fb_t c, const fb_t a)
Squares a binary field element with integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the binary field element to square.
Definition at line 91 of file relic_fb_sqr.c.
References fb_sqrm_low().
fb_sqr_quick()
void fb_sqr_quick (fb_t c, const fb_t a)
Squares a binary field element using table-based squaring.
Parameters
[out] c - the result.
[in] a - the binary field element to square.
Definition at line 69 of file relic_fb_sqr.c.
References dv_free, dv_new, dv_null, ERR_CAUGHT, fb_rdc, fb_sqrl_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fb_lsh()
void fb_lsh (fb_t c, const fb_t a, uint_t bits)
Shifts a binary field element to the left. Computes c = a * z^bits mod f(z).
Parameters
[out] c - the result.
[in] a - the binary field element to shift.
[in] bits - the number of bits to shift.
Definition at line 41 of file relic_fb_shift.c.
References dv_lshd(), fb_copy(), fb_lsh1_low(), fb_lshb_low(), RLC_FB_DIGS, and RLC_RIP.
Referenced by fb_inv_bruch(), and fb_itr_pre_quick().
fb_rsh()
void fb_rsh (fb_t c, const fb_t a, uint_t bits)
Shifts a binary field element to the right. Computes c = a / (z^bits).
Parameters
[out] c - the result.
[in] a - the binary field element to shift.
[in] bits - the number of bits to shift.
Definition at line 66 of file relic_fb_shift.c.
References dv_rshd(), fb_copy(), fb_rsh1_low(), fb_rshb_low(), RLC_FB_DIGS, and RLC_RIP.
Referenced by fb_inv_bruch(), fb_inv_ctaia(), and find_solve().
fb_rdc_basic()
void fb_rdc_basic (fb_t c, dv_t a)
Reduces a multiplication result modulo an irreducible polynomial using shift-and-add modular reduction.
Parameters
[out] c - the result.
[in] a - the multiplication result to reduce.
Definition at line 50 of file relic_fb_rdc.c.
References dv_new, dv_null, ERR_CAUGHT, fb_addd_low(), fb_bits(), fb_copy(), fb_free, fb_get_bit(), fb_lshb_low(), fb_poly_get(), RLC_CATCH_ANY, RLC_FB_BITS, RLC_FB_DIGS, RLC_FINALLY, RLC_RIP, RLC_THROW, and RLC_TRY.
fb_rdc_quick()
void fb_rdc_quick (fb_t c, dv_t a)
Reduces a multiplication result modulo a trinomial or pentanomial.
Parameters
[out] c - the result.
[in] a - the multiplication result to reduce.
Definition at line 100 of file relic_fb_rdc.c.
References fb_rdcn_low().
fb_srt_basic()
void fb_srt_basic (fb_t c, const fb_t a)
Extracts the square root of a binary field element using repeated squaring. Computes c = a^{1/2}.
Parameters
[out] c - the result.
[in] a - the binary field element to take a square root.
Definition at line 46 of file relic_fb_srt.c.
References fb_copy(), fb_sqr, and RLC_FB_BITS.
fb_srt_quick()
void fb_srt_quick (fb_t c, const fb_t a)
Extracts the square root of a binary field element using a fast square root extraction algorithm.
Parameters
[out] c - the result.
[in] a - the binary field element to take a square root.
Definition at line 60 of file relic_fb_srt.c.
References fb_srtn_low().
fb_trc_basic()
dig_t fb_trc_basic (const fb_t a)
Computes the trace of a binary field element using repeated squaring. Returns Tr(a).
Parameters
[in] a - the binary field element.
Returns
the trace of the binary field element.
Definition at line 40 of file relic_fb_trc.c.
References ERR_CAUGHT, fb_add(), fb_copy(), fb_free, fb_new, fb_null, fb_sqr, RLC_CATCH_ANY, RLC_FB_BITS, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fb_trc_quick()
dig_t fb_trc_quick (const fb_t a)
Computes the trace of a binary field element using a fast trace computation algorithm. Returns Tr(a).
Parameters
[in] a - the binary field element.
Returns
the trace of the binary field element.
Definition at line 71 of file relic_fb_trc.c.
References fb_trcn_low().
fb_inv_basic()
void fb_inv_basic (fb_t c, const fb_t a)
Inverts a binary field element using Fermat's Little Theorem.
Parameters
[out] c - the result.
[in] a - the binary field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 45 of file relic_fb_inv.c.
References ERR_CAUGHT, ERR_NO_VALID, fb_copy(), fb_free, fb_is_zero(), fb_mul, fb_new, fb_null, fb_set_dig(), fb_sqr, RLC_CATCH_ANY, RLC_FB_BITS, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fb_inv_binar()
void fb_inv_binar (fb_t c, const fb_t a)
Inverts a binary field element using the binary method.
Parameters
[out] c - the result.
[in] a - the binary field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 112 of file relic_fb_inv.c.
References bn_rsh1_low(), dv_free, dv_new, dv_null, dv_zero(), ERR_CAUGHT, ERR_NO_VALID, fb_add(), fb_addd_low(), fb_copy(), fb_is_zero(), fb_poly_add(), fb_poly_get(), RLC_CATCH_ANY, RLC_DIG, RLC_FB_BITS, RLC_FB_DIGS, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fb_inv_exgcd()
void fb_inv_exgcd (fb_t c, const fb_t a)
Inverts a binary field element using the Extended Euclidean algorithm.
Parameters
[out] c - the result.
[in] a - the binary field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 218 of file relic_fb_inv.c.
References dv_free, dv_new, dv_zero(), ERR_CAUGHT, ERR_NO_VALID, fb_addd_low(), fb_bits(), fb_copy(), fb_is_zero(), fb_lsha_low(), fb_null, fb_poly_get(), RLC_CATCH_ANY, RLC_DIG_LOG, RLC_FB_BITS, RLC_FB_DIGS, RLC_FINALLY, RLC_RIP, RLC_THROW, RLC_TRY, and util_bits_dig().
fb_inv_almos()
void fb_inv_almos (fb_t c, const fb_t a)
Inverts a binary field element using the Almost Inverse algorithm.
Parameters
[out] c - the result.
[in] a - the binary field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 339 of file relic_fb_inv.c.
References bn_rsh1_low(), dv_free, dv_new, dv_null, dv_zero(), ERR_CAUGHT, ERR_NO_VALID, fb_addd_low(), fb_addn_low(), fb_copy(), fb_is_zero(), fb_poly_add(), fb_poly_get(), fb_set_dig(), RLC_CATCH_ANY, RLC_DIG, RLC_FB_BITS, RLC_FB_DIGS, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fb_inv_itoht()
void fb_inv_itoht (fb_t c, const fb_t a)
Inverts a binary field element using Itoh-Tsuji inversion.
Parameters
[out] c - the result.
[in] a - the binary field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 439 of file relic_fb_inv.c.
References ERR_CAUGHT, ERR_NO_MEMORY, ERR_NO_VALID, fb_copy(), fb_free, fb_is_zero(), fb_itr, fb_mul, fb_new, fb_null, fb_poly_get_chain(), fb_poly_tab_sqr(), fb_sqr, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FB_BITS, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
fb_inv_bruch()
void fb_inv_bruch (fb_t c, const fb_t a)
Inverts a binary field element using the hardware-friendly Brunner-Curiger-Hofstetter algorithm.
Parameters
[out] c - the result.
[in] a - the binary field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 508 of file relic_fb_inv.c.
References ERR_CAUGHT, ERR_NO_VALID, fb_add(), fb_copy(), fb_free, fb_is_zero(), fb_lsh(), fb_new, fb_null, fb_poly_get(), fb_rsh(), fb_set_dig(), fb_zero(), RLC_CATCH_ANY, RLC_DIG, RLC_FB_BITS, RLC_FB_DIGS, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fb_inv_ctaia()
void fb_inv_ctaia (fb_t c, const fb_t a)
Inverts a binary field element in constant-time using the Wu-Wu-Shieh-Hwang algorithm.
Parameters
[out] c - the result.
[in] a - the binary field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 580 of file relic_fb_inv.c.
References ERR_CAUGHT, ERR_NO_VALID, fb_copy(), fb_free, fb_is_zero(), fb_new, fb_null, fb_poly_add(), fb_poly_get(), fb_rsh(), fb_set_dig(), fb_zero(), RLC_CATCH_ANY, RLC_FB_BITS, RLC_FB_DIGS, RLC_FINALLY, RLC_SEL, RLC_THROW, and RLC_TRY.
fb_inv_lower()
void fb_inv_lower (fb_t c, const fb_t a)
Inverts a binary field element using a direct call to the lower layer.
Parameters
[out] c - the result.
[in] a - the binary field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 649 of file relic_fb_inv.c.
References ERR_NO_VALID, fb_invn_low(), fb_is_zero(), and RLC_THROW.
fb_inv_sim()
void fb_inv_sim (fb_t * c, const fb_t * a, int n)
Inverts multiple binary field elements.
Parameters
[out] c - the result.
[in] a - the binary field elements to invert.
[in] n - the number of elements.
Definition at line 659 of file relic_fb_inv.c.
References ERR_CAUGHT, ERR_NO_MEMORY, fb_copy(), fb_free, fb_inv, fb_mul, fb_new, fb_null, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by eb_norm_sim().
fb_exp_2b()
void fb_exp_2b (fb_t c, const fb_t a, int b)
Exponentiates a binary field element through consecutive squaring. Computes c = a^(2^b).
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
fb_exp_basic()
void fb_exp_basic (fb_t c, const fb_t a, const bn_t b)
Exponentiates a binary field element using the binary method.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 46 of file relic_fb_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), ERR_CAUGHT, fb_copy(), fb_free, fb_inv, fb_mul, fb_new, fb_null, fb_set_dig(), fb_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
fb_exp_slide()
void fb_exp_slide (fb_t c, const fb_t a, const bn_t b)
Exponentiates a binary field element using the sliding window method.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 89 of file relic_fb_exp.c.
References bn_is_zero(), bn_rec_slw(), bn_sign(), ERR_CAUGHT, fb_copy(), fb_free, fb_inv, fb_mul, fb_new, fb_null, fb_set_dig(), fb_sqr, RLC_CATCH_ANY, RLC_FB_BITS, RLC_FINALLY, RLC_NEG, RLC_THROW, RLC_TRY, RLC_WIDTH, and util_bits_dig().
fb_exp_monty()
void fb_exp_monty (fb_t c, const fb_t a, const bn_t b)
Exponentiates a binary field element using the constant-time Montgomery powering ladder method.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 156 of file relic_fb_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), dv_swap_sec(), ERR_CAUGHT, fb_copy(), fb_free, fb_inv, fb_mul, fb_new, fb_null, fb_set_dig(), fb_sqr, RLC_CATCH_ANY, RLC_FB_DIGS, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
fb_slv_basic()
void fb_slv_basic (fb_t c, const fb_t a)
Solves a quadratic equation for a, Tr(a) = 0 by repeated squarings and additions.
Parameters
[out] c - the result.
[in] a - the binary field element to solve.
Definition at line 46 of file relic_fb_slv.c.
References ERR_CAUGHT, fb_add(), fb_add_dig(), fb_copy(), fb_free, fb_new, fb_null, fb_sqr, fb_trc, RLC_CATCH_ANY, RLC_FB_BITS, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fb_slv_quick()
void fb_slv_quick (fb_t c, const fb_t a)
Solves a quadratic equation for a, Tr(a) = 0 with precomputed half-traces.
Parameters
[out] c - the result.
[in] a - the binary field element to solve.
Definition at line 78 of file relic_fb_slv.c.
References fb_add_dig(), fb_slvn_low(), and fb_trc.
fb_itr_basic()
void fb_itr_basic (fb_t c, const fb_t a, int b)
Computes the iterated squaring/square-root of a binary field element by consecutive squaring/square-root. Computes c = a^(2^b).
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 46 of file relic_fb_itr.c.
References fb_copy(), fb_sqr, and fb_srt.
fb_itr_pre_quick()
void fb_itr_pre_quick (fb_st * t, int b)
Precomputes a table for iterated squaring/square-root of a binary field element.
Parameters
[out] t - the precomputed table.
[in] b - the exponent.
Definition at line 59 of file relic_fb_itr.c.
References ERR_CAUGHT, fb_copy(), fb_free, fb_lsh(), fb_new, fb_null, fb_set_dig(), fb_sqr, fb_srt, fb_zero(), RLC_CATCH_ANY, RLC_DIG, RLC_FB_DIGS, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fb_itr_quick()
void fb_itr_quick (fb_t c, const fb_t a, const fb_st * t)
Computes the iterated squaring/square-root of a binary field element by a table based method. Computes c = a^(2^b).
Parameters
[out] c - the result.
[in] a - the basis.
[in] t - the precomputed table.
Definition at line 93 of file relic_fb_itr.c.
References fb_itrn_low().