RELIC: src/pp/relic_pp_map_k54.c File Reference
relic_pp_map_k54.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_util.h"
Functions
static void pp_mil_k54 (fp54_t r, const fp9_t qx, const fp9_t qy, const ep_t p, const bn_t a)
void pp_map_k54 (fp54_t r, const ep_t p, const fp9_t qx, const fp9_t qy)
Detailed Description
Implementation of pairing computation for curves with embedding degree 54.
Definition in file relic_pp_map_k54.c.
Function Documentation
pp_mil_k54()
static void pp_mil_k54 (fp54_t r, const fp9_t qx, const fp9_t qy, const ep_t p, const bn_t a) static
Definition at line 40 of file relic_pp_map_k54.c.
References bn_bits(), bn_rec_naf(), core_get(), ep_free, ep_neg(), ep_new, ep_null, ERR_CAUGHT, fp3_mul, fp3_mul_nor(), fp3_set_dig(), fp54_free, fp54_mul, fp54_mul_dxs(), fp54_new, fp54_null, fp54_sqr, fp54_zero(), fp9_copy(), fp9_frb(), fp9_free, fp9_inv(), fp9_mul, fp9_neg(), fp9_new, fp9_null, fp9_set_dig(), fp9_zero(), fp_add, fp_copy(), fp_mul, fp_neg, pp_add_k54, pp_dbl_k54, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_THROW, and RLC_TRY.
Referenced by pp_map_k54().
pp_map_k54()
void pp_map_k54 (fp54_t r, const ep_t p, const fp9_t qx, const fp9_t qy)
Computes the Optimal Ate pairing of two points in a parameterized elliptic curve with embedding degree 54.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 165 of file relic_pp_map_k54.c.
References bn_free, bn_new, bn_null, bn_sign(), ep_curve_is_pairf(), ep_is_infty(), EP_SG54, ERR_CAUGHT, fp54_inv_cyc(), fp54_set_dig(), fp9_is_zero(), fp_prime_get_par(), pp_exp_k54(), pp_mil_k54(), RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.