RELIC: src/bn/relic_bn_smb.c File Reference
relic_bn_smb.c File Reference
Multiple precision integer arithmetic
#include "relic_core.h"
Functions
int bn_smb_leg (const bn_t a, const bn_t b)
int bn_smb_jac (const bn_t a, const bn_t b)
Detailed Description
Implementation of Legendre and Jacobi symbols.
Definition in file relic_bn_smb.c.
Function Documentation
bn_smb_leg()
int bn_smb_leg (const bn_t a, const bn_t b)
Computes the Legendre symbol c = (a|b), b prime.
Parameters
[in] a - the first parameter.
[in] b - the second parameter.
Exceptions
ERR_NO_VALID - if there input is negative.
Returns
the result.
Definition at line 38 of file relic_bn_smb.c.
References bn_cmp(), bn_cmp_dig(), bn_free, bn_mxp, bn_new, bn_null, bn_rsh(), bn_sign(), bn_sub(), bn_sub_dig(), ERR_CAUGHT, ERR_NO_VALID, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
bn_smb_jac()
int bn_smb_jac (const bn_t a, const bn_t b)
Computes the Jacobi symbol c = (a|b).
Parameters
[in] a - the first parameter.
[in] b - the second parameter.
Exceptions
ERR_NO_VALID - if there input is even or negative.
Returns
the result.
Definition at line 79 of file relic_bn_smb.c.
References arch_lzcnt(), arch_tzcnt(), bn_add(), bn_cmp_dig(), bn_copy(), bn_free, bn_grow(), bn_is_even(), bn_is_zero(), bn_mod, bn_mul_dig(), bn_neg(), bn_new, bn_null, bn_rsh(), bn_sign(), dv_zero(), ERR_CAUGHT, ERR_NO_VALID, RLC_CATCH_ANY, RLC_DIG, RLC_EQ, RLC_FINALLY, RLC_HMASK, RLC_LMASK, RLC_MAX, RLC_MIN, RLC_NEG, RLC_SWAP, RLC_THROW, and RLC_TRY.
Referenced by bn_is_prime_solov().