RELIC: src/fpx/relic_fp12_mul.c File Reference
relic_fp12_mul.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
Functions
static void fp6_mul_dxs_unr_lazyr (dv6_t c, const fp6_t a, const fp6_t b)
void fp12_mul_basic (fp12_t c, const fp12_t a, const fp12_t b)
void fp12_mul_dxs_basic (fp12_t c, const fp12_t a, const fp12_t b)
void fp12_mul_unr (dv12_t c, const fp12_t a, const fp12_t b)
void fp12_mul_lazyr (fp12_t c, const fp12_t a, const fp12_t b)
void fp12_mul_dxs_lazyr (fp12_t c, const fp12_t a, const fp12_t b)
void fp12_mul_art (fp12_t c, const fp12_t a)
Detailed Description
Implementation of multiplication in a dodecic extension of a prime field.
Definition in file relic_fp12_mul.c.
Function Documentation
fp6_mul_dxs_unr_lazyr()
static void fp6_mul_dxs_unr_lazyr (dv6_t c, const fp6_t a, const fp6_t b) inline static
Definition at line 42 of file relic_fp12_mul.c.
References dv2_free, dv2_new, dv2_null, ERR_CAUGHT, fp2_addc_low(), fp2_addm_low(), fp2_free, fp2_muln_low(), fp2_new, fp2_nord_low(), fp2_null, fp2_subc_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp12_mul_dxs_lazyr().
fp12_mul_basic()
void fp12_mul_basic (fp12_t c, const fp12_t a, const fp12_t b)
Multiples two dodecic extension field elements using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element.
[in] b - the dodecic extension field element.
Definition at line 99 of file relic_fp12_mul.c.
References ERR_CAUGHT, fp6_add(), fp6_free, fp6_mul, fp6_mul_art(), fp6_new, fp6_null, fp6_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp12_mul_dxs_basic()
void fp12_mul_dxs_basic (fp12_t c, const fp12_t a, const fp12_t b)
Multiples a dense dodecic extension field element by a sparse element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the dense dodecic extension field element.
[in] b - the sparse dodecic extension field element.
Definition at line 140 of file relic_fp12_mul.c.
References ep2_curve_is_twist(), ERR_CAUGHT, fp2_add, fp2_copy(), fp2_mul, fp2_mul_nor, fp6_add(), fp6_free, fp6_mul_art(), fp6_mul_dxs(), fp6_new, fp6_null, fp6_sub(), fp_add, fp_copy(), fp_mul, RLC_CATCH_ANY, RLC_EP_DTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp12_mul_unr()
void fp12_mul_unr (dv12_t c, const fp12_t a, const fp12_t b)
Multiples two dodecic extension field elements without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element.
[in] b - the dodecic extension field element.
Definition at line 227 of file relic_fp12_mul.c.
References dv6_free, dv6_new, dv6_null, ERR_CAUGHT, fp2_addc_low(), fp2_nord_low(), fp2_subc_low(), fp6_add(), fp6_free, fp6_mul_unr(), fp6_new, fp6_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp12_mul_lazyr().
fp12_mul_lazyr()
void fp12_mul_lazyr (fp12_t c, const fp12_t a, const fp12_t b)
Multiples two dodecic extension field elements using lazy reduction.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element.
[in] b - the dodecic extension field element.
Definition at line 280 of file relic_fp12_mul.c.
References dv12_free, dv12_new, dv12_null, ERR_CAUGHT, fp12_mul_unr(), fp2_rdcn_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp12_mul_dxs_lazyr()
void fp12_mul_dxs_lazyr (fp12_t c, const fp12_t a, const fp12_t b)
Multiples a dense dodecic extension field element by a sparse element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the dense dodecic extension field element.
[in] b - the sparse dodecic extension field element.
Definition at line 299 of file relic_fp12_mul.c.
References dv6_free, dv6_new, dv6_null, ep2_curve_is_twist(), ERR_CAUGHT, fp2_add, fp2_addc_low(), fp2_copy(), fp2_muln_low(), fp2_nord_low(), fp2_rdcn_low(), fp2_subc_low(), fp6_add(), fp6_free, fp6_mul_dxs_unr_lazyr(), fp6_new, fp6_null, fp_add, fp_copy(), fp_muln_low(), RLC_CATCH_ANY, RLC_EP_DTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp12_mul_art()
void fp12_mul_art (fp12_t c, const fp12_t a)
Multiplies a dodecic extension field element by the adjoined root.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to multiply.
Definition at line 398 of file relic_fp12_mul.c.
References ERR_CAUGHT, fp6_copy(), fp6_free, fp6_mul_art(), fp6_new, fp6_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.