RELIC: src/epx/relic_ep2_mul_sim.c File Reference
relic_ep2_mul_sim.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
static void ep2_mul_sim_endom (ep2_t r, const ep2_t p, const bn_t k, const ep2_t q, const bn_t m)
static void ep2_mul_sim_plain (ep2_t r, const ep2_t p, const bn_t k, const ep2_t q, const bn_t m, const ep2_t *t)
void ep2_mul_sim_basic (ep2_t r, const ep2_t p, const bn_t k, const ep2_t q, const bn_t l)
void ep2_mul_sim_trick (ep2_t r, const ep2_t p, const bn_t k, const ep2_t q, const bn_t m)
void ep2_mul_sim_inter (ep2_t r, const ep2_t p, const bn_t k, const ep2_t q, const bn_t m)
void ep2_mul_sim_joint (ep2_t r, const ep2_t p, const bn_t k, const ep2_t q, const bn_t m)
void ep2_mul_sim_gen (ep2_t r, const bn_t k, const ep2_t q, const bn_t m)
void ep2_mul_sim_dig (ep2_t r, const ep2_t p[], const dig_t k[], size_t len)
void ep2_mul_sim_lot (ep2_t r, const ep2_t p[], const bn_t k[], size_t n)
Detailed Description
Implementation of simultaneous point multiplication on a prime elliptic curve over a quadratic extension field.
Definition in file relic_ep2_mul_sim.c.
Function Documentation
ep2_mul_sim_endom()
static void ep2_mul_sim_endom (ep2_t r, const ep2_t p, const bn_t k, const ep2_t q, const bn_t m) static
Multiplies and adds two prime elliptic curve points simultaneously, optionally choosing the first point as the generator depending on an optional table of precomputed points.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer.
[in] t - the pointer to the precomputed table.
Definition at line 55 of file relic_ep2_mul_sim.c.
References bn_free, bn_mod, bn_new, bn_null, bn_rec_frb(), bn_rec_naf(), bn_sign(), ep2_add, ep2_curve_get_ord(), ep2_dbl, ep2_frb(), ep2_free, ep2_neg(), ep2_new, ep2_norm(), ep2_null, ep2_set_infty(), ep2_sub(), EP_BN, ep_curve_is_pairf(), ERR_CAUGHT, fp_prime_get_par(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by ep2_mul_sim_gen(), and ep2_mul_sim_inter().
ep2_mul_sim_plain()
static void ep2_mul_sim_plain (ep2_t r, const ep2_t p, const bn_t k, const ep2_t q, const bn_t m, const ep2_t * t) static
Multiplies and adds two prime elliptic curve points simultaneously, optionally choosing the first point as the generator depending on an optional table of precomputed points.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer.
[in] t - the pointer to the precomputed table.
Definition at line 162 of file relic_ep2_mul_sim.c.
References bn_rec_naf(), bn_sign(), ep2_add, ep2_dbl, ep2_free, ep2_new, ep2_norm(), ep2_null, ep2_set_infty(), ep2_sub(), ep2_tab(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by ep2_mul_sim_gen(), and ep2_mul_sim_inter().
ep2_mul_sim_basic()
void ep2_mul_sim_basic (ep2_t r, const ep2_t p, const bn_t k, const ep2_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using scalar multiplication and point addition.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 256 of file relic_ep2_mul_sim.c.
References ep2_add, ep2_free, ep2_mul, ep2_new, ep2_norm(), ep2_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep2_mul_sim_trick()
void ep2_mul_sim_trick (ep2_t r, const ep2_t p, const bn_t k, const ep2_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using shamir's trick.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 281 of file relic_ep2_mul_sim.c.
References bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, bn_rec_win(), ep2_add, ep2_copy(), ep2_curve_get_ord(), ep2_dbl, ep2_free, ep2_is_infty(), ep2_mul, ep2_new, ep2_norm(), ep2_norm_sim(), ep2_null, ep2_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_CEIL, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_THROW, RLC_TRY, and RLC_WIDTH.
ep2_mul_sim_inter()
void ep2_mul_sim_inter (ep2_t r, const ep2_t p, const bn_t k, const ep2_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using interleaving of NAFs.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 375 of file relic_ep2_mul_sim.c.
References bn_is_zero(), ep2_is_infty(), ep2_mul, ep2_mul_sim_endom(), ep2_mul_sim_plain(), and ep_curve_is_endom().
ep2_mul_sim_joint()
void ep2_mul_sim_joint (ep2_t r, const ep2_t p, const bn_t k, const ep2_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using Solinas' Joint Sparse Form.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 402 of file relic_ep2_mul_sim.c.
References bn_bits(), bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, bn_rec_jsf(), bn_sign(), ep2_add, ep2_copy(), ep2_curve_get_ord(), ep2_dbl, ep2_free, ep2_is_infty(), ep2_mul, ep2_neg(), ep2_new, ep2_norm(), ep2_norm_sim(), ep2_null, ep2_set_infty(), ep2_sub(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, and RLC_TRY.
ep2_mul_sim_gen()
void ep2_mul_sim_gen (ep2_t r, const bn_t k, const ep2_t q, const bn_t m)
Multiplies and adds the generator and a prime elliptic curve point simultaneously. Computes R = [k]G + [l]Q.
Parameters
[out] r - the result.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 492 of file relic_ep2_mul_sim.c.
References bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, ep2_curve_get_gen(), ep2_curve_get_ord(), ep2_curve_get_tab(), ep2_free, ep2_is_infty(), ep2_mul, ep2_mul_gen(), ep2_mul_sim, ep2_mul_sim_endom(), ep2_mul_sim_plain(), ep2_new, ep2_null, ep_curve_is_endom(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep2_mul_sim_dig()
void ep2_mul_sim_dig (ep2_t r, const ep2_t p[], const dig_t k[], size_t len)
Multiplies prime elliptic curve points by small scalars. Computes R = \sum k_iP_i.
Parameters
[out] r - the result.
[in] p - the points to multiply.
[in] k - the small scalars.
[in] len - the number of points to multiply.
Definition at line 557 of file relic_ep2_mul_sim.c.
References ep2_add, ep2_dbl, ep2_free, ep2_new, ep2_norm(), ep2_null, ep2_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_MAX, RLC_THROW, RLC_TRY, and util_bits_dig().
ep2_mul_sim_lot()
void ep2_mul_sim_lot (ep2_t r, const ep2_t p[], const bn_t k[], size_t n)
Multiplies simultaneously elements from a prime elliptic curve. Computes R = \Sum_i=0..n k_iP_i.
Parameters
[out] r - the result.
[out] p - the points to multiply.
[out] k - the integer scalars.
[out] n - the number of elements to multiply.
Definition at line 591 of file relic_ep2_mul_sim.c.
References bn_free, bn_mod, bn_new, bn_null, bn_rec_frb(), bn_rec_naf(), bn_sign(), ep2_add, ep2_copy(), ep2_curve_get_ord(), ep2_dbl, ep2_frb(), ep2_free, ep2_neg(), ep2_new, ep2_norm(), ep2_null, ep2_set_infty(), ep2_sub(), EP_BN, ep_curve_is_pairf(), ERR_CAUGHT, ERR_NO_MEMORY, fp_prime_get_par(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_FREE, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and util_bits_dig().