RELIC: src/eb/relic_eb_mul.c File Reference
relic_eb_mul.c File Reference
Elliptic curves over binary fields
#include "relic_core.h"
#include "relic_fb_low.h"
Functions
static void eb_mul_ltnaf_imp (eb_t r, const eb_t p, const bn_t k)
static void eb_mul_lnaf_imp (eb_t r, const eb_t p, const bn_t k)
static void eb_mul_rtnaf_imp (eb_t r, const eb_t p, const bn_t k)
static void eb_mul_rnaf_imp (eb_t r, const eb_t p, const bn_t k)
void eb_mul_basic (eb_t r, const eb_t p, const bn_t k)
void eb_mul_lodah (eb_t r, const eb_t p, const bn_t k)
void eb_mul_lwnaf (eb_t r, const eb_t p, const bn_t k)
void eb_mul_rwnaf (eb_t r, const eb_t p, const bn_t k)
void eb_mul_halve (eb_t r, const eb_t p, const bn_t k)
void eb_mul_gen (eb_t r, const bn_t k)
void eb_mul_dig (eb_t r, const eb_t p, dig_t k)
Detailed Description
Implementation of point multiplication on binary elliptic curves.
Definition in file relic_eb_mul.c.
Function Documentation
eb_mul_ltnaf_imp()
static void eb_mul_ltnaf_imp (eb_t r, const eb_t p, const bn_t k) static
Multiplies a binary elliptic curve point by an integer using the w-TNAF method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 51 of file relic_eb_mul.c.
References bn_rec_tnaf(), bn_sign(), eb_add, eb_copy(), eb_curve_opt_a(), eb_frb(), eb_free, eb_neg, eb_new, eb_norm(), eb_null, eb_sub, eb_tab(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FB_BITS, RLC_FINALLY, RLC_NEG, RLC_THROW, RLC_TRY, RLC_WIDTH, and RLC_ZERO.
Referenced by eb_mul_lwnaf().
eb_mul_lnaf_imp()
static void eb_mul_lnaf_imp (eb_t r, const eb_t p, const bn_t k) static
Multiplies a binary elliptic curve point by an integer using the left-to-right w-NAF method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 123 of file relic_eb_mul.c.
References BASIC, bn_rec_naf(), bn_sign(), eb_add, eb_copy(), eb_dbl, eb_free, eb_neg, eb_new, eb_norm(), eb_null, eb_set_infty(), eb_sub, eb_tab(), ERR_CAUGHT, fb_set_dig(), RLC_CATCH_ANY, RLC_FB_BITS, RLC_FINALLY, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by eb_mul_lwnaf().
eb_mul_rtnaf_imp()
static void eb_mul_rtnaf_imp (eb_t r, const eb_t p, const bn_t k) static
Multiplies a binary elliptic curve point by an integer using the w-TNAF method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 194 of file relic_eb_mul.c.
References BASIC, bn_rec_tnaf(), bn_sign(), eb_add, eb_copy(), eb_curve_opt_a(), eb_frb(), eb_free, eb_neg, eb_new, eb_norm(), eb_norm_sim(), eb_null, eb_set_infty(), eb_sub, ERR_CAUGHT, fb_sqr, RLC_CATCH_ANY, RLC_FB_BITS, RLC_FINALLY, RLC_NEG, RLC_THROW, RLC_TRY, RLC_WIDTH, and RLC_ZERO.
Referenced by eb_mul_rwnaf().
eb_mul_rnaf_imp()
static void eb_mul_rnaf_imp (eb_t r, const eb_t p, const bn_t k) static
Multiplies a binary elliptic curve point by an integer using the right-to-left w-NAF method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 494 of file relic_eb_mul.c.
References BASIC, bn_rec_naf(), bn_sign(), eb_add, eb_copy(), eb_dbl, eb_free, eb_mul_dig(), eb_neg, eb_new, eb_norm(), eb_null, eb_set_infty(), eb_sub, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FB_BITS, RLC_FINALLY, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by eb_mul_rwnaf().
eb_mul_basic()
void eb_mul_basic (eb_t r, const eb_t p, const bn_t k)
Multiplies a binary elliptic point by an integer using the binary method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 618 of file relic_eb_mul.c.
References bn_bits(), bn_is_zero(), bn_rec_naf(), bn_sign(), eb_add, eb_dbl, eb_free, eb_is_infty(), eb_neg, eb_new, eb_norm(), eb_null, eb_set_infty(), eb_sub, ERR_CAUGHT, ERR_NO_BUFFER, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.
eb_mul_lodah()
void eb_mul_lodah (eb_t r, const eb_t p, const bn_t k)
Multiplies a binary elliptic point by an integer using the constant-time Lopez-Dahab point multiplication method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 668 of file relic_eb_mul.c.
References BASIC, bn_abs(), bn_add(), bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_new, bn_null, bn_sign(), dv_free, dv_new, dv_null, dv_swap_sec(), dv_zero(), eb_curve_get_b(), eb_curve_get_ord(), eb_curve_opt_b(), eb_neg, eb_set_infty(), ERR_CAUGHT, fb_add(), fb_add_dig(), fb_addd_low(), fb_addn_low(), fb_copy(), fb_inv, fb_is_zero(), fb_mul, fb_mul1_low(), fb_muln_low(), fb_rand(), fb_rdcn_low(), fb_set_dig(), fb_sqr, fb_sqrl_low(), RLC_CATCH_ANY, RLC_FB_DIGS, RLC_FINALLY, RLC_MAX, RLC_NEG, RLC_ONE, RLC_SEL, RLC_THROW, RLC_TINY, RLC_TRY, and RLC_ZERO.
eb_mul_lwnaf()
void eb_mul_lwnaf (eb_t r, const eb_t p, const bn_t k)
Multiplies a binary elliptic point by an integer using the left-to-right w-NAF method. If the binary curve is a Koblitz curve, w-TNAF is used.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 857 of file relic_eb_mul.c.
References bn_is_zero(), eb_curve_is_kbltz(), eb_is_infty(), eb_mul_lnaf_imp(), eb_mul_ltnaf_imp(), and eb_set_infty().
eb_mul_rwnaf()
void eb_mul_rwnaf (eb_t r, const eb_t p, const bn_t k)
Multiplies a binary elliptic point by an integer using the right-to-left w-NAF method. If the binary curve is a Koblitz curve, w-TNAF is used.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 879 of file relic_eb_mul.c.
References bn_is_zero(), eb_curve_is_kbltz(), eb_is_infty(), eb_mul_rnaf_imp(), eb_mul_rtnaf_imp(), eb_set_infty(), ERR_NO_CONFIG, and RLC_THROW.
eb_mul_halve()
void eb_mul_halve (eb_t r, const eb_t p, const bn_t k)
Multiplies a binary elliptic point by an integer using the halving method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 907 of file relic_eb_mul.c.
References bn_bits(), bn_cmp_dig(), bn_free, bn_is_zero(), bn_lsh(), bn_mod, bn_new, bn_null, bn_rand(), bn_rec_naf(), eb_add, eb_copy(), eb_curve_get_a(), eb_curve_get_b(), eb_curve_get_cof(), eb_curve_get_ord(), eb_dbl, eb_free, eb_hlv(), eb_is_infty(), eb_new, eb_norm(), eb_null, eb_set_infty(), eb_sub, ERR_CAUGHT, fb_add(), fb_copy(), fb_free, fb_mul, fb_new, fb_null, fb_set_dig(), fb_slv, fb_srt, fb_trc, fb_zero(), HALVE, RLC_CATCH_ANY, RLC_FB_BITS, RLC_FINALLY, RLC_GT, RLC_POS, RLC_THROW, RLC_TRY, and RLC_WIDTH.
eb_mul_gen()
void eb_mul_gen (eb_t r, const bn_t k)
Multiplies the generator of a binary elliptic curve by an integer.
Parameters
[out] r - the result.
[in] k - the integer.
Definition at line 1085 of file relic_eb_mul.c.
References eb_curve_get_gen(), eb_curve_get_tab(), eb_free, eb_mul, eb_mul_fix, eb_new, eb_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by eb_mul_sim_gen(), and eb_rand().
eb_mul_dig()
void eb_mul_dig (eb_t r, const eb_t p, const dig_t k)
Multiplies a binary elliptic point by a small positive integer.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 1107 of file relic_eb_mul.c.
References eb_add, eb_copy(), eb_dbl, eb_free, eb_is_infty(), eb_new, eb_norm(), eb_null, eb_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, RLC_TRY, and util_bits_dig().
Referenced by eb_map(), and eb_mul_rnaf_imp().