RELIC: src/pp/relic_pp_dbl_k2.c File Reference
relic_pp_dbl_k2.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
#include "relic_util.h"
Functions
void pp_dbl_k2_basic (fp2_t l, ep_t r, const ep_t p, const ep_t q)
void pp_dbl_k2_projc_basic (fp2_t l, ep_t r, const ep_t p, const ep_t q)
void pp_dbl_k2_projc_lazyr (fp2_t l, ep_t r, const ep_t p, const ep_t q)
Detailed Description
Implementation of Miller doubling for curves of embedding degree 2.
Definition in file relic_pp_dbl_k2.c.
Function Documentation
pp_dbl_k2_basic()
void pp_dbl_k2_basic (fp2_t l, ep_t r, const ep_t p, const ep_t q)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 2 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] p - the point to double.
[in] q - the affine point to evaluate the line function.
Definition at line 44 of file relic_pp_dbl_k2.c.
References ep_copy(), ep_dbl_slp_basic(), ep_free, ep_new, ep_null, ERR_CAUGHT, fp_add, fp_copy(), fp_free, fp_mul, fp_new, fp_null, fp_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_dbl_k2_projc_basic()
void pp_dbl_k2_projc_basic (fp2_t l, ep_t r, const ep_t p, const ep_t q)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 2 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] p - the point to double.
[in] q - the affine point to evaluate the line function.
Definition at line 75 of file relic_pp_dbl_k2.c.
References ERR_CAUGHT, fp_add, fp_dbl, fp_free, fp_mul, fp_new, fp_null, fp_sqr, fp_sub, JACOB, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_dbl_k2_projc_lazyr()
void pp_dbl_k2_projc_lazyr (fp2_t l, ep_t r, const ep_t p, const ep_t q)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 2 using projective coordinates and lazy reduction.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] p - the point to double.
[in] q - the affine point to evaluate the line function.
Definition at line 164 of file relic_pp_dbl_k2.c.
References dv_free, dv_new, dv_null, ERR_CAUGHT, fp_add, fp_addc_low(), fp_dbl, fp_free, fp_mul, fp_muln_low(), fp_new, fp_null, fp_rdcn_low(), fp_sqr, fp_sqrn_low(), fp_sub, fp_subc_low(), fp_subm_low(), JACOB, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.