RELIC: src/bn/relic_bn_sqr.c File Reference
relic_bn_sqr.c File Reference
Multiple precision integer arithmetic
#include "relic_core.h"
#include "relic_bn_low.h"
Functions
static void bn_sqr_karat_imp (bn_t c, const bn_t a, uint_t level)
void bn_sqr_basic (bn_t c, const bn_t a)
void bn_sqr_comba (bn_t c, const bn_t a)
void bn_sqr_karat (bn_t c, const bn_t a)
Detailed Description
Implementation of the multiple precision arithmetic squaring functions.
Definition in file relic_bn_sqr.c.
Function Documentation
bn_sqr_karat_imp()
static void bn_sqr_karat_imp (bn_t c, const bn_t a, uint_t level) static
Computes the square of a multiple precision integer using recursive Karatsuba squaring.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to square.
[in] level - the number of Karatsuba steps to apply.
Definition at line 50 of file relic_bn_sqr.c.
References bn_add(), bn_copy(), bn_free, bn_lsh(), bn_mul_comba(), bn_new, bn_new_size, bn_null, bn_sqr_basic(), bn_sqr_comba(), bn_sqr_karat_imp(), bn_sub(), bn_trim(), dv_copy(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_POS, RLC_THROW, RLC_TRY, and bn_st::used.
Referenced by bn_sqr_karat(), and bn_sqr_karat_imp().
bn_sqr_basic()
void bn_sqr_basic (bn_t c, const bn_t a)
Computes the square of a multiple precision integer using Schoolbook squaring.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to square.
Definition at line 148 of file relic_bn_sqr.c.
References bn_copy(), bn_free, bn_new_size, bn_null, bn_sqra_low(), bn_trim(), bn_zero(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_POS, RLC_THROW, and RLC_TRY.
Referenced by bn_sqr_karat_imp().
bn_sqr_comba()
void bn_sqr_comba (bn_t c, const bn_t a)
Computes the square of a multiple precision integer using Comba squaring.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to square.
Definition at line 181 of file relic_bn_sqr.c.
References bn_copy(), bn_free, bn_new_size, bn_null, bn_sqrn_low(), bn_trim(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_POS, RLC_THROW, and RLC_TRY.
Referenced by bn_sqr_karat_imp().
bn_sqr_karat()
void bn_sqr_karat (bn_t c, const bn_t a)
Computes the square of a multiple precision integer using Karatsuba squaring.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to square.
Definition at line 211 of file relic_bn_sqr.c.
References BN_KARAT, and bn_sqr_karat_imp().