RELIC: src/ed/relic_ed_map.c File Reference
relic_ed_map.c File Reference
Edwards curves over prime fields.
#include "relic_core.h"
#include "relic_md.h"
Macros
#define ED_MAP_CONVERT_BYTES(IDX)
Functions
void ed_map_ell2_5mod8 (ed_t p, fp_t t)
void ed_map_dst (ed_t p, const uint8_t *msg, size_t len, const uint8_t *dst, size_t dst_len)
void ed_map (ed_t p, const uint8_t *msg, size_t len)
Detailed Description
Implementation of hashing to a prime elliptic curve.
Version
$Id$
Definition in file relic_ed_map.c.
Macro Definition Documentation
ED_MAP_CONVERT_BYTES
#define ED_MAP_CONVERT_BYTES (IDX)
Value:
    do {                                                                                 \
        bn_read_bin(k, pseudo_random_bytes + IDX * len_per_elm, len_per_elm);            \
        fp_prime_conv(t, k);                                                             \
    } while (0)
Referenced by ed_map_dst().
Function Documentation
ed_map_ell2_5mod8()
void ed_map_ell2_5mod8 (ed_t p, fp_t t)
Definition at line 40 of file relic_ed_map.c.
References BASIC, bn_free, bn_get_bit(), bn_new, bn_null, bn_rsh(), bn_sub_dig(), core_get(), dv_copy(), dv_copy_sec(), _ctx_t::ed_map_c, ERR_CAUGHT, fp_add, fp_add_dig(), fp_cmp(), fp_copy_sec(), fp_dbl, fp_exp, fp_free, fp_inv, fp_is_zero(), fp_mul, fp_neg, fp_new, fp_null, fp_prime_back(), fp_prime_get(), fp_set_dig(), fp_sqr, fp_sub, PROJC, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FP_DIGS, RLC_POS, RLC_THROW, and RLC_TRY.
Referenced by ed_map_dst().
ed_map_dst()
void ed_map_dst (ed_t p, const uint8_t * msg, size_t len, const uint8_t * dst, size_t dst_len)
Maps a byte array to a point in an Edwards elliptic curve using an explicit domain separation tag.
Parameters
[out] p - the result.
[in] msg - the byte array to map.
[in] len - the array length in bytes.
[in] dst - the domain separation tag.
[in] dst_len - the domain separation tag length in bytes.
Definition at line 190 of file relic_ed_map.c.
References BASIC, bn_free, bn_new, bn_null, CURVE_ED25519, ed_add, ed_dbl, ed_free, ED_MAP_CONVERT_BYTES, ed_map_ell2_5mod8(), ed_new, ed_norm(), ed_null, ed_param_get(), ed_param_level(), ERR_CAUGHT, ERR_NO_VALID, fp_free, fp_mul, fp_new, fp_null, FP_PRIME, md_xmd, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by ed_map().
ed_map()
void ed_map (ed_t p, const uint8_t * msg, size_t len)
Maps a byte array to a point in an Edwards elliptic curve.
Parameters
[out] p - the result.
[in] msg - the byte array to map.
[in] len - the array length in bytes.
Definition at line 258 of file relic_ed_map.c.
References ed_map_dst().