RELIC: src/pp/relic_pp_dbl_k12.c File Reference
relic_pp_dbl_k12.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
#include "relic_util.h"
Functions
void pp_dbl_k12_basic (fp12_t l, ep2_t r, const ep2_t q, const ep_t p)
void pp_dbl_k12_projc_basic (fp12_t l, ep2_t r, const ep2_t q, const ep_t p)
void pp_dbl_k12_projc_lazyr (fp12_t l, ep2_t r, const ep2_t q, const ep_t p)
void pp_dbl_lit_k12 (fp12_t l, ep_t r, const ep_t p, const ep2_t q)
Detailed Description
Implementation of Miller doubling for curves of embedding degree 12.
Definition in file relic_pp_dbl_k12.c.
Function Documentation
pp_dbl_k12_basic()
void pp_dbl_k12_basic (fp12_t l, ep2_t r, const ep2_t q, const ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 44 of file relic_pp_dbl_k12.c.
References ep2_copy(), ep2_curve_is_twist(), ep2_dbl_slp_basic(), ep2_free, ep2_new, ep2_null, ERR_CAUGHT, fp2_free, fp2_mul, fp2_new, fp2_null, fp2_sub, fp_copy(), fp_mul, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_dbl_k12_projc_basic()
void pp_dbl_k12_projc_basic (fp12_t l, ep2_t r, const ep2_t q, const ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 84 of file relic_pp_dbl_k12.c.
References ep2_curve_get_b(), ep2_curve_is_twist(), ep_curve_opt_b(), ERR_CAUGHT, fp2_add, fp2_dbl, fp2_free, fp2_mul, fp2_new, fp2_null, fp2_sqr, fp2_sub, fp_add, fp_hlv, fp_mul, fp_sub, PROJC, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, RLC_TRY, and RLC_TWO.
pp_dbl_k12_projc_lazyr()
void pp_dbl_k12_projc_lazyr (fp12_t l, ep2_t r, const ep2_t q, const ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using projective coordinates and lazy reduction.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 237 of file relic_pp_dbl_k12.c.
References dv2_free, dv2_new, dv2_null, ep2_curve_get_b(), ep2_curve_is_twist(), ep_curve_opt_b(), ERR_CAUGHT, fp2_add, fp2_addd_low(), fp2_dbl, fp2_free, fp2_mul, fp2_new, fp2_null, fp2_rdcn_low(), fp2_sqr, fp2_sqrn_low(), fp2_sub, fp2_subc_low(), fp_add, fp_hlv, fp_mul, fp_sub, PROJC, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, RLC_TRY, and RLC_TWO.
pp_dbl_lit_k12()
void pp_dbl_lit_k12 (fp12_t l, ep_t r, const ep_t p, const ep2_t q)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve twist with embedding degree 12 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] p - the point to double.
[in] q - the affine point to evaluate the line function.
Definition at line 405 of file relic_pp_dbl_k12.c.
References ep2_curve_is_twist(), ep_curve_get_b(), ERR_CAUGHT, fp2_add, fp2_dbl, fp_add, fp_dbl, fp_free, fp_mul, fp_new, fp_null, fp_sqr, fp_sub, fp_zero(), PROJC, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_mil_lit_k12().