RELIC: src/md/relic_md_sha224.c File Reference
relic_md_sha224.c File Reference
Hash functions
#include "relic_conf.h"
#include "relic_core.h"
#include "relic_md.h"
#include "sha.h"
Functions
void md_map_sh224 (uint8_t *hash, const uint8_t *msg, size_t len)
Detailed Description
Implementation of the SHA-224 hash function.
Definition in file relic_md_sha224.c.
Function Documentation
md_map_sh224()
void md_map_sh224 (uint8_t * hash, const uint8_t * msg, size_t len)
Computes the SHA-224 hash function.
Parameters
[out] hash - the digest.
[in] msg - the message to hash.
[in] len - the message length in bytes.
Definition at line 43 of file relic_md_sha224.c.
References ERR_NO_VALID, RLC_THROW, SHA224Input(), SHA224Reset(), SHA224Result(), and shaSuccess.