RELIC: src/fp/relic_fp_mul.c File Reference
relic_fp_mul.c File Reference
Prime field arithmetic
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_bn_low.h"
Functions
static void fp_mul_karat_imp (dv_t c, const fp_t a, const fp_t b, size_t size, uint_t level)
void fp_mul_dig (fp_t c, const fp_t a, dig_t b)
void fp_mul_basic (fp_t c, const fp_t a, const fp_t b)
void fp_mul_comba (fp_t c, const fp_t a, const fp_t b)
void fp_mul_integ (fp_t c, const fp_t a, const fp_t b)
void fp_mul_karat (fp_t c, const fp_t a, const fp_t b)
Detailed Description
Implementation of the prime field multiplication functions.
Definition in file relic_fp_mul.c.
Function Documentation
fp_mul_karat_imp()
static void fp_mul_karat_imp (dv_t c, const fp_t a, const fp_t b, size_t size, uint_t level) static
Multiplies two prime field elements using recursive Karatsuba multiplication.
Parameters
[out] c - the result.
[in] a - the first prime field element.
[in] b - the second prime field element.
[in] size - the number of digits to multiply.
[in] level - the number of Karatsuba steps to apply.
Definition at line 51 of file relic_fp_mul.c.
References bn_add1_low(), bn_addn_low(), bn_mula_low(), bn_muln_low(), bn_sub1_low(), bn_subn_low(), dv_copy(), dv_free, dv_new, dv_null, dv_zero(), ERR_CAUGHT, fp_mul_karat_imp(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp_mul_karat(), and fp_mul_karat_imp().
fp_mul_dig()
void fp_mul_dig (fp_t c, const fp_t a, dig_t b)
Multiplies a prime field element by a digit. Computes c = a * b.
Parameters
[out] c - the result.
[in] a - the prime field element.
[in] b - the digit to multiply.
Definition at line 162 of file relic_fp_mul.c.
References dv_free, dv_new, dv_null, ERR_CAUGHT, fp_mul, fp_prime_conv_dig(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep_curve_mul_a(), ep_curve_mul_b(), ep_curve_set_map(), ep_map_swift_impl(), fp2_inv(), fp2_mul_dig(), and fp3_mul_dig().
fp_mul_basic()
void fp_mul_basic (fp_t c, const fp_t a, const fp_t b)
Multiples two prime field elements using Schoolbook multiplication.
Parameters
[out] c - the result.
[in] a - the first prime field element to multiply.
[in] b - the second prime field element to multiply.
Definition at line 181 of file relic_fp_mul.c.
References dv_free, dv_new, dv_null, dv_zero(), ERR_CAUGHT, fp_mula_low(), fp_rdc, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
fp_mul_comba()
void fp_mul_comba (fp_t c, const fp_t a, const fp_t b)
Multiples two prime field elements using Comba multiplication.
Parameters
[out] c - the result.
[in] a - the first prime field element to multiply.
[in] b - the second prime field element to multiply.
Definition at line 211 of file relic_fp_mul.c.
References dv_free, dv_new, dv_null, ERR_CAUGHT, fp_muln_low(), fp_rdc, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp_mul_integ()
void fp_mul_integ (fp_t c, const fp_t a, const fp_t b)
Multiples two prime field elements using multiplication integrated with modular reduction.
Parameters
[out] c - the result.
[in] a - the first prime field element to multiply.
[in] b - the second prime field element to multiply.
Definition at line 235 of file relic_fp_mul.c.
References fp_mulm_low().
fp_mul_karat()
void fp_mul_karat (fp_t c, const fp_t a, const fp_t b)
Multiples two prime field elements using Karatsuba multiplication.
Parameters
[out] c - the result.
[in] a - the first prime field element to multiply.
[in] b - the second prime field element to multiply.
Definition at line 243 of file relic_fp_mul.c.
References dv_free, dv_new, dv_null, dv_zero(), ERR_CAUGHT, FP_KARAT, fp_mul_karat_imp(), fp_muln_low(), fp_rdc, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.