RELIC: src/bn/relic_bn_shift.c File Reference
relic_bn_shift.c File Reference
Multiple precision integer arithmetic
#include "relic_core.h"
#include "relic_bn_low.h"
Functions
void bn_dbl (bn_t c, const bn_t a)
void bn_hlv (bn_t c, const bn_t a)
void bn_lsh (bn_t c, const bn_t a, uint_t bits)
void bn_rsh (bn_t c, const bn_t a, uint_t bits)
Detailed Description
Implementation of the multiple precision arithmetic shift functions.
Definition in file relic_bn_shift.c.
Function Documentation
bn_dbl()
void bn_dbl (bn_t c, const bn_t a)
Doubles a multiple precision. Computes c = a + a.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to double.
Definition at line 39 of file relic_bn_shift.c.
References bn_grow(), bn_lsh1_low(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_THROW, and RLC_TRY.
Referenced by bn_gen_prime_stron(), bn_rec_frb(), bn_rec_tnaf_mod(), ep3_mul_gls_imp(), ep3_mul_reg_gls(), ep4_mul_cof_fm16(), ep_curve_set_endom(), fp_crt(), fp_inv_monty(), fp_param_set(), gt_exp_gls_naf(), gt_exp_gls_sac(), gt_exp_reg_gls(), gt_exp_reg_sac(), and pp_exp_afg16().
bn_hlv()
void bn_hlv (bn_t c, const bn_t a)
Halves a multiple precision. Computes c = floor(a / 2)
Parameters
[out] c - the result.
[in] a - the multiple precision integer to halve.
Definition at line 60 of file relic_bn_shift.c.
References bn_copy(), bn_rsh1_low(), and bn_trim().
Referenced by bn_gcd_binar(), bn_gcd_ext_binar(), bn_rec_jsf(), bn_rec_naf(), bn_rec_reg(), bn_rec_rtnaf(), bn_rec_sac(), bn_rec_tnaf(), bn_rec_tnaf_mod(), bn_srt(), ep2_pck(), ep2_upk(), ep4_mul_cof_fm16(), ep_curve_set_endom(), ep_mul_cof(), ep_pck(), ep_upk(), fp_inv_binar(), fp_prime_set(), fp_smb_basic(), g1_is_valid(), pp_exp_afg16(), and pp_exp_fm16().
bn_lsh()
void bn_lsh (bn_t c, const bn_t a, uint_t bits)
Shifts a multiple precision number to the left. Computes c = a * 2^bits. c = a * 2^bits.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to shift.
[in] bits - the number of bits to shift.
Definition at line 66 of file relic_bn_shift.c.
References bn_grow(), bn_lshb_low(), bn_trim(), dv_copy(), dv_lshd(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_RIP, RLC_THROW, and RLC_TRY.
Referenced by bn_gcd_binar(), bn_gcd_ext_binar(), bn_gen_prime_factor(), bn_gen_prime_safep(), bn_mod_barrt(), bn_mod_monty_conv(), bn_mul_karat_imp(), bn_sqr_karat_imp(), cp_rabin_enc(), eb_mul_halve(), ep_curve_set_endom(), fp_inv_divst(), fp_param_set(), fp_prime_set(), fp_prime_set_pairf(), fp_smb_divst(), pad_pkcs2(), and pp_exp_k8().
bn_rsh()
void bn_rsh (bn_t c, const bn_t a, uint_t bits)
Shifts a multiple precision number to the right. Computes c = floor(a / 2^bits).
Parameters
[out] c - the result.
[in] a - the multiple precision integer to shift.
[in] bits - the number of bits to shift.
Definition at line 97 of file relic_bn_shift.c.
References bn_grow(), bn_rshb_low(), bn_trim(), dv_copy(), dv_rshd(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_RIP, RLC_THROW, and RLC_TRY.
Referenced by bn_gcd_ext_lehme(), bn_gcd_lehme(), bn_gen_prime_safep(), bn_is_prime_rabin(), bn_is_prime_solov(), bn_mod_barrt(), bn_mod_pmers(), bn_rec_frb(), bn_rec_glv(), bn_rec_reg(), bn_smb_jac(), bn_smb_leg(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ecss_sig(), cp_ecss_ver(), cp_rabin_dec(), ed_map_ell2_5mod8(), ed_param_set(), fp2_srt(), fp3_srt(), fp_srt(), pad_pkcs2(), and pp_exp_k8().