RELIC: src/ed/relic_ed_pck.c File Reference
relic_ed_pck.c File Reference
Elliptic curves over prime fields
#include "relic_core.h"
Functions
void ed_pck (ed_t r, const ed_t p)
int ed_upk (ed_t r, const ed_t p)
Detailed Description
Implementation of point compression on Edwards elliptic curves.
Definition in file relic_ed_pck.c.
Function Documentation
ed_pck()
void ed_pck (ed_t r, const ed_t p)
Compresses a point.
Parameters
[out] r - the result.
[in] p - the point to compress.
Definition at line 38 of file relic_ed_pck.c.
References BASIC, fp_copy(), fp_get_bit(), fp_norm(), fp_set_bit(), fp_set_dig(), and fp_zero().
Referenced by ed_write_bin().
ed_upk()
int ed_upk (ed_t r, const ed_t p)
Decompresses a point.
Parameters
[out] r - the result.
[in] p - the point to decompress.
Returns
if the decompression was successful
Definition at line 48 of file relic_ed_pck.c.
References BASIC, core_get(), ERR_CAUGHT, fp_copy(), fp_free, fp_get_bit(), fp_inv, fp_mul, fp_neg, fp_new, fp_norm(), fp_null, fp_set_dig(), fp_sqr, fp_srt(), fp_sub, fp_sub_dig(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ed_read_bin().