RELIC: src/ep/relic_ep_mul_sim.c File Reference
relic_ep_mul_sim.c File Reference
Elliptic curves over prime fields
#include "relic_core.h"
Functions
static void ep_mul_sim_endom (ep_t r, const ep_t p, const bn_t k, const ep_t q, const bn_t m, const ep_t *t)
void ep_mul_sim_lot_endom (ep_t r, const ep_t p[], const bn_t k[], int n)
static void ep_mul_sim_plain (ep_t r, const ep_t p, const bn_t k, const ep_t q, const bn_t m, const ep_t *t)
void ep_mul_sim_lot_plain (ep_t r, const ep_t p[], const bn_t k[], int n)
void ep_mul_sim_basic (ep_t r, const ep_t p, const bn_t k, const ep_t q, const bn_t m)
void ep_mul_sim_trick (ep_t r, const ep_t p, const bn_t k, const ep_t q, const bn_t m)
void ep_mul_sim_inter (ep_t r, const ep_t p, const bn_t k, const ep_t q, const bn_t m)
void ep_mul_sim_joint (ep_t r, const ep_t p, const bn_t k, const ep_t q, const bn_t m)
void ep_mul_sim_gen (ep_t r, const bn_t k, const ep_t q, const bn_t m)
void ep_mul_sim_dig (ep_t r, const ep_t p[], const dig_t k[], int n)
void ep_mul_sim_lot (ep_t r, const ep_t p[], const bn_t k[], int n)
Detailed Description
Implementation of simultaneous point multiplication on binary elliptic curves.
Definition in file relic_ep_mul_sim.c.
Function Documentation
ep_mul_sim_endom()
static void ep_mul_sim_endom (ep_t r, const ep_t p, const bn_t k, const ep_t q, const bn_t m, const ep_t * t) static
Multiplies and adds two prime elliptic curve points simultaneously, optionally choosing the first point as the generator depending on an optional table of precomputed points.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer.
[in] t - the pointer to the precomputed table.
Definition at line 55 of file relic_ep_mul_sim.c.
References bn_abs(), bn_free, bn_new, bn_null, bn_rec_glv(), bn_rec_naf(), bn_sign(), ep_add, ep_curve_get_ord(), ep_curve_get_v1(), ep_curve_get_v2(), ep_dbl, ep_free, ep_neg(), ep_new, ep_norm(), ep_null, ep_psi(), ep_set_infty(), ep_sub(), ep_tab(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_POS, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by ep_mul_sim_gen(), and ep_mul_sim_inter().
ep_mul_sim_lot_endom()
void ep_mul_sim_lot_endom (ep_t r, const ep_t p[], const bn_t k[], int n)
Multiplies and adds multiple elliptic curve points simultaneously. Computes R = \Sum_i=0..n [k_i]P_i.
Parameters
[out] r - the result.
[out] p - the elements to multiply.
[out] k - the integer scalars.
[out] n - the number of elements to multiply.
Definition at line 266 of file relic_ep_mul_sim.c.
References bn_free, bn_mod, bn_neg(), bn_new, bn_null, bn_rec_glv(), bn_rec_naf(), bn_sign(), ep_add, ep_copy(), ep_curve_get_ord(), ep_curve_get_v1(), ep_curve_get_v2(), ep_dbl, ep_free, ep_neg(), ep_new, ep_norm(), ep_null, ep_psi(), ep_set_infty(), ep_sub(), ERR_CAUGHT, ERR_NO_MEMORY, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_FREE, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and util_bits_dig().
Referenced by ep_mul_sim_lot().
ep_mul_sim_plain()
static void ep_mul_sim_plain (ep_t r, const ep_t p, const bn_t k, const ep_t q, const bn_t m, const ep_t * t) static
Multiplies and adds two prime elliptic curve points simultaneously, optionally choosing the first point as the generator depending on an optional table of precomputed points.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer.
[in] t - the pointer to the precomputed table.
Definition at line 489 of file relic_ep_mul_sim.c.
References bn_rec_naf(), bn_sign(), ep_add, ep_dbl, ep_free, ep_new, ep_norm(), ep_null, ep_set_infty(), ep_sub(), ep_tab(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by ep_mul_sim_gen(), and ep_mul_sim_inter().
ep_mul_sim_lot_plain()
void ep_mul_sim_lot_plain (ep_t r, const ep_t p[], const bn_t k[], int n)
Multiplies and adds multiple elliptic curve points simultaneously. Computes R = \Sum_i=0..n [k_i]P_i.
Parameters
[out] r - the result.
[out] p - the elements to multiply.
[out] k - the integer scalars.
[out] n - the number of elements to multiply.
Definition at line 587 of file relic_ep_mul_sim.c.
References bn_bits(), bn_rec_naf(), bn_sign(), ep_add, ep_dbl, ep_free, ep_neg(), ep_new, ep_norm(), ep_null, ep_set_infty(), ep_sub(), ERR_CAUGHT, ERR_NO_MEMORY, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_MAX, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by ep_mul_sim_lot().
ep_mul_sim_basic()
void ep_mul_sim_basic (ep_t r, const ep_t p, const bn_t k, const ep_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using scalar multiplication and point addition.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 654 of file relic_ep_mul_sim.c.
References ep_add, ep_free, ep_mul, ep_new, ep_norm(), ep_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep_mul_sim_trick()
void ep_mul_sim_trick (ep_t r, const ep_t p, const bn_t k, const ep_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using shamir's trick.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 679 of file relic_ep_mul_sim.c.
References bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, bn_rec_win(), ep_add, ep_copy(), ep_curve_get_ord(), ep_dbl, ep_free, ep_is_infty(), ep_mul, ep_new, ep_norm(), ep_norm_sim(), ep_null, ep_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_CEIL, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_THROW, RLC_TRY, and RLC_WIDTH.
ep_mul_sim_inter()
void ep_mul_sim_inter (ep_t r, const ep_t p, const bn_t k, const ep_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using interleaving of NAFs.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 773 of file relic_ep_mul_sim.c.
References bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, ep_curve_get_ord(), ep_curve_is_endom(), ep_is_infty(), ep_mul, ep_mul_sim_endom(), ep_mul_sim_plain(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep_mul_sim_joint()
void ep_mul_sim_joint (ep_t r, const ep_t p, const bn_t k, const ep_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using Solinas' Joint Sparse Form.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 828 of file relic_ep_mul_sim.c.
References bn_bits(), bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, bn_rec_jsf(), bn_sign(), ep_add, ep_copy(), ep_curve_get_ord(), ep_dbl, ep_free, ep_is_infty(), ep_mul, ep_neg(), ep_new, ep_norm(), ep_norm_sim(), ep_null, ep_set_infty(), ep_sub(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, and RLC_TRY.
ep_mul_sim_gen()
void ep_mul_sim_gen (ep_t r, const bn_t k, const ep_t q, const bn_t m)
Multiplies and adds the generator and a prime elliptic curve point simultaneously. Computes R = [k]G + [m]Q.
Parameters
[out] r - the result.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer.
Definition at line 918 of file relic_ep_mul_sim.c.
References bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, ep_curve_get_gen(), ep_curve_get_ord(), ep_curve_get_tab(), ep_curve_is_endom(), ep_free, ep_is_infty(), ep_mul, ep_mul_gen(), ep_mul_sim, ep_mul_sim_endom(), ep_mul_sim_plain(), ep_new, ep_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep_mul_sim_dig()
void ep_mul_sim_dig (ep_t r, const ep_t p[], const dig_t k[], int n)
Multiplies prime elliptic curve points by small scalars. Computes R = \Sum_i=0..n [k_i]P_i.
Parameters
[out] r - the result.
[in] p - the points to multiply.
[in] k - the small scalars.
[in] n - the number of points to multiply.
Definition at line 983 of file relic_ep_mul_sim.c.
References ep_add, ep_dbl, ep_free, ep_new, ep_norm(), ep_null, ep_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_MAX, RLC_THROW, RLC_TRY, and util_bits_dig().
ep_mul_sim_lot()
void ep_mul_sim_lot (ep_t r, const ep_t p[], const bn_t k[], int n)
Multiplies and adds multiple elliptic curve points simultaneously. Computes R = \Sum_i=0..n [k_i]P_i.
Parameters
[out] r - the result.
[out] p - the elements to multiply.
[out] k - the integer scalars.
[out] n - the number of elements to multiply.
Definition at line 1017 of file relic_ep_mul_sim.c.
References ep_curve_is_endom(), ep_mul_sim_lot_endom(), ep_mul_sim_lot_plain(), and ep_set_infty().