RELIC: src/ed/relic_ed_util.c File Reference
relic_ed_util.c File Reference
Edwards curves over prime fields.
#include <assert.h>
#include "relic_core.h"
#include "relic_label.h"
#include "relic_md.h"
Functions
int ed_is_infty (const ed_t p)
void ed_set_infty (ed_t p)
void ed_copy (ed_t r, const ed_t p)
void ed_rand (ed_t p)
void ed_blind (ed_t r, const ed_t p)
void ed_rhs (fp_t rhs, const fp_t x)
int ed_on_curve (const ed_t p)
void ed_tab (ed_t *t, const ed_t p, int w)
void ed_print (const ed_t p)
size_t ed_size_bin (const ed_t a, int pack)
void ed_read_bin (ed_t a, const uint8_t *bin, size_t len)
void ed_write_bin (uint8_t *bin, size_t len, const ed_t a, int pack)
Detailed Description
Implementation of the Edwards elliptic curve utilities.
Version
$Id$
Definition in file relic_ed_util.c.
Function Documentation
ed_is_infty()
int ed_is_infty (const ed_t p)
Tests if a point on an Edwards elliptic curve is at the infinity.
Parameters
[in] p - the point to test.
Returns
1 if the point is at infinity, 0 otherise.
Definition at line 44 of file relic_ed_util.c.
References BASIC, ERR_NO_VALID, fp_cmp(), fp_cmp_dig(), fp_is_zero(), RLC_EQ, and RLC_THROW.
Referenced by ed_mul_basic(), ed_mul_dig(), ed_mul_lwnaf(), ed_mul_lwreg(), ed_mul_monty(), ed_mul_sim_gen(), ed_mul_sim_inter(), ed_mul_sim_joint(), ed_mul_sim_trick(), ed_mul_slide(), ed_neg_basic(), ed_neg_projc(), ed_norm(), ed_norm_sim(), ed_on_curve(), ed_size_bin(), and ed_write_bin().
ed_set_infty()
void ed_set_infty (ed_t p)
Assigns an Edwards elliptic curve point to the point at infinity.
Parameters
[out] p - the point to assign.
Definition at line 61 of file relic_ed_util.c.
References fp_set_dig(), fp_zero(), and PROJC.
Referenced by ed_curve_init(), ed_mul_basic(), ed_mul_dig(), ed_mul_fix_basic(), ed_mul_fix_combd(), ed_mul_fix_plain(), ed_mul_gen(), ed_mul_lwnaf(), ed_mul_lwreg(), ed_mul_monty(), ed_mul_naf_imp(), ed_mul_pre_combd(), ed_mul_pre_combs(), ed_mul_reg_imp(), ed_mul_sim_joint(), ed_mul_sim_lot(), ed_mul_sim_plain(), ed_mul_sim_trick(), ed_mul_slide(), ed_neg_basic(), ed_neg_projc(), ed_norm(), ed_read_bin(), ed_sub_basic(), ed_sub_extnd(), and ed_sub_projc().
ed_copy()
void ed_copy (ed_t r, const ed_t p)
Copies the second argument to the first argument.
Parameters
[out] q - the result.
[in] p - the Edwards elliptic curve point to copy.
Definition at line 71 of file relic_ed_util.c.
References fp_copy().
Referenced by ed_blind(), ed_cmp(), ed_curve_get_gen(), ed_mul_combs_plain(), ed_mul_monty(), ed_mul_pre_basic(), ed_mul_pre_combd(), ed_mul_pre_combs(), ed_mul_sim_joint(), ed_mul_sim_trick(), ed_mul_slide(), ed_norm(), ed_param_set(), and ed_tab().
ed_rand()
void ed_rand (ed_t p)
Assigns a random value to an Edwards elliptic curve point.
Parameters
[out] p - the Edwards elliptic curve point to assign.
Definition at line 82 of file relic_ed_util.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), ed_curve_get_ord(), ed_mul_gen(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ed_blind()
void ed_blind (ed_t r, const ed_t p)
Randomizes coordinates of a prime elliptic curve point.
Parameters
[out] r - the blinded Edwards elliptic curve point.
[in] p - the Edwards elliptic curve point to blind.
Definition at line 104 of file relic_ed_util.c.
References ed_copy(), ERR_CAUGHT, fp_free, fp_mul, fp_new, fp_null, fp_rand(), PROJC, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ed_rhs()
void ed_rhs (fp_t rhs, const fp_t p)
Computes the right-hand side of the elliptic curve equation at the x-coordinate of a certain Edwards elliptic curve point.
Parameters
[out] rhs - the result.
[in] x - the x-coordinate of the point.
Definition at line 131 of file relic_ed_util.c.
References core_get(), fp_mul, fp_sqr, and fp_sub_dig().
Referenced by ed_on_curve().
ed_on_curve()
int ed_on_curve (const ed_t p)
Tests if a point is in the curve.
Parameters
[in] p - the point to test.
Definition at line 138 of file relic_ed_util.c.
References core_get(), ed_free, ed_is_infty(), ed_new, ed_norm(), ed_null, ed_rhs(), ERR_CAUGHT, fp_cmp(), fp_is_zero(), fp_mul, fp_sqr, fp_sub_dig(), RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ed_read_bin().
ed_tab()
void ed_tab (ed_t * t, const ed_t p, int w)
Builds a precomputation table for multiplying a random Edwards elliptic point.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
[in] w - the window width.
Definition at line 175 of file relic_ed_util.c.
References ed_add, ed_copy(), ed_dbl, ed_norm(), and ed_norm_sim().
Referenced by ed_mul_naf_imp(), ed_mul_pre_lwnaf(), ed_mul_reg_imp(), and ed_mul_sim_plain().
ed_print()
void ed_print (const ed_t p)
Prints an Edwards elliptic curve point.
Parameters
[in] p - the Edwards elliptic curve point to print.
Definition at line 192 of file relic_ed_util.c.
References fp_print().
ed_size_bin()
size_t ed_size_bin (const ed_t a, int pack)
Returns the number of bytes necessary to store an Edwards elliptic curve point with optional point compression.
Parameters
[in] a - the Edwards field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 201 of file relic_ed_util.c.
References ed_is_infty(), and RLC_FP_BYTES.
ed_read_bin()
void ed_read_bin (ed_t a, const uint8_t * bin, size_t len)
Reads an Edwards elliptic curve point from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_VALID - if the encoded point is invalid.
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 216 of file relic_ed_util.c.
References BASIC, ed_on_curve(), ed_set_infty(), ed_upk(), ERR_NO_BUFFER, ERR_NO_VALID, fp_mul, fp_read_bin(), fp_set_bit(), fp_set_dig(), fp_sqr, fp_zero(), RLC_FP_BYTES, and RLC_THROW.
ed_write_bin()
void ed_write_bin (uint8_t * bin, size_t len, const ed_t a, int pack)
Writes an Edwards elliptic curve point to a byte vector in big-endian format with optional point compression.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the Edwards elliptic curve point to write.
[in] pack - the flag to indicate point compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 271 of file relic_ed_util.c.
References ed_free, ed_is_infty(), ed_new, ed_norm(), ed_null, ed_pck(), ERR_CAUGHT, ERR_NO_BUFFER, fp_get_bit(), fp_write_bin(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.