RELIC: src/fpx/relic_fp4_sqr.c File Reference
relic_fp4_sqr.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
Functions
void fp4_sqr_basic (fp4_t c, const fp4_t a)
void fp4_sqr_unr (dv4_t c, const fp4_t a)
void fp4_sqr_lazyr (fp4_t c, const fp4_t a)
Detailed Description
Implementation of squaring in a quartic extension of a prime field.
Definition in file relic_fp4_sqr.c.
Function Documentation
fp4_sqr_basic()
void fp4_sqr_basic (fp4_t c, const fp4_t a)
Computes the squares of a quartic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the quartic extension field element to square.
Definition at line 42 of file relic_fp4_sqr.c.
References ERR_CAUGHT, fp2_add, fp2_dbl, fp2_free, fp2_mul, fp2_mul_nor, fp2_new, fp2_null, fp2_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp4_sqr_unr()
void fp4_sqr_unr (dv4_t c, const fp4_t a)
Computes the square of a quartic extension field element without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the quartic extension field element to square.
Definition at line 73 of file relic_fp4_sqr.c.
References dv2_free, dv2_new, dv2_null, ERR_CAUGHT, fp2_addc_low(), fp2_addm_low(), fp2_free, fp2_new, fp2_norh_low(), fp2_null, fp2_sqrn_low(), fp2_subc_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp12_sqr_unr(), fp24_sqr_cyc_lazyr(), fp24_sqr_pck_lazyr(), fp4_sqr_lazyr(), and fp8_sqr_unr().
fp4_sqr_lazyr()
void fp4_sqr_lazyr (fp4_t c, const fp4_t a)
Computes the square of a quartic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the quartic extension field element to square.
Definition at line 110 of file relic_fp4_sqr.c.
References dv4_free, dv4_new, dv4_null, ERR_CAUGHT, fp2_rdcn_low(), fp4_sqr_unr(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.