RELIC: src/bn/relic_bn_mxp.c File Reference
relic_bn_mxp.c File Reference
Multiple precision integer arithmetic
#include "relic_core.h"
Macros
#define RLC_TABLE_SIZE 64
Functions
void bn_mxp_basic (bn_t c, const bn_t a, const bn_t b, const bn_t m)
void bn_mxp_slide (bn_t c, const bn_t a, const bn_t b, const bn_t m)
void bn_mxp_monty (bn_t c, const bn_t a, const bn_t b, const bn_t m)
void bn_mxp_crt (bn_t d, const bn_t a, const bn_t b, const bn_t c, const crt_t crt, int sqr)
void bn_mxp_dig (bn_t c, const bn_t a, dig_t b, const bn_t m)
Detailed Description
Implementation of the multiple precision exponentiation functions.
Definition in file relic_bn_mxp.c.
Macro Definition Documentation
RLC_TABLE_SIZE
#define RLC_TABLE_SIZE 64
Size of precomputation table.
Definition at line 41 of file relic_bn_mxp.c.
Referenced by bn_mxp_slide().
Function Documentation
bn_mxp_basic()
void bn_mxp_basic (bn_t c, const bn_t a, const bn_t b, const bn_t m)
Exponentiates a multiple precision integer modulo a positive integer using the binary method.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
[in] m - the modulus.
Definition at line 49 of file relic_bn_mxp.c.
References bn_bits(), bn_cmp_dig(), bn_copy(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_mod_inv(), bn_mod_monty_back(), bn_mod_monty_conv(), bn_mod_pre, bn_mul, bn_new, bn_null, bn_set_dig(), bn_sign(), bn_sqr, bn_zero(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
bn_mxp_slide()
void bn_mxp_slide (bn_t c, const bn_t a, const bn_t b, const bn_t m)
Exponentiates a multiple precision integer modulo a positive integer using the sliding window method.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
[in] m - the modulus.
Definition at line 113 of file relic_bn_mxp.c.
References bn_bits(), bn_cmp_dig(), bn_copy(), bn_free, bn_is_zero(), bn_mod, bn_mod_inv(), bn_mod_monty_back(), bn_mod_monty_conv(), bn_mod_pre, bn_mul, bn_new, bn_null, bn_rec_slw(), bn_set_dig(), bn_sign(), bn_sqr, bn_zero(), ERR_CAUGHT, ERR_NO_MEMORY, RLC_ALLOCA, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_TABLE_SIZE, RLC_THROW, RLC_TRY, and util_bits_dig().
bn_mxp_monty()
void bn_mxp_monty (bn_t c, const bn_t a, const bn_t b, const bn_t m)
Exponentiates a multiple precision integer modulo a positive integer using the constant-time Montgomery powering ladder method.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
[in] m - the modulus.
Definition at line 229 of file relic_bn_mxp.c.
References bn_bits(), bn_cmp_dig(), bn_copy(), bn_free, bn_get_bit(), bn_grow(), bn_is_zero(), bn_mod, bn_mod_inv(), bn_mod_monty_back(), bn_mod_monty_conv(), bn_mod_pre, bn_mul, bn_new, bn_null, bn_set_dig(), bn_sign(), bn_sqr, bn_zero(), dv_swap_sec(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
bn_mxp_crt()
void bn_mxp_crt (bn_t d, const bn_t a, const bn_t b, const bn_t c, const crt_t crt, int sqr)
Definition at line 314 of file relic_bn_mxp.c.
References bn_add(), bn_div(), bn_free, bn_mod, bn_mul, bn_mxp, bn_new, bn_null, bn_sign(), bn_sqr, bn_sub(), bn_sub_dig(), CORES, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by cp_phpe_dec(), cp_rsa_dec(), cp_rsa_sig(), cp_shipsi_ans(), and cp_shpe_dec().
bn_mxp_dig()
void bn_mxp_dig (bn_t c, const bn_t a, dig_t b, const bn_t m)
Exponentiates a multiple precision integer by a small power modulo a positive integer using the binary method.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
[in] m - the modulus.
Definition at line 403 of file relic_bn_mxp.c.
References bn_cmp_dig(), bn_copy(), bn_free, bn_mod, bn_mod_monty_back(), bn_mod_monty_conv(), bn_mod_pre, bn_mul, bn_new, bn_null, bn_set_dig(), bn_sqr, bn_zero(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, RLC_TRY, and util_bits_dig().
Referenced by cp_bdpe_dec(), and cp_bdpe_enc().