RELIC: src/cp/relic_cp_phpe.c File Reference
relic_cp_phpe.c File Reference
Cryptographic protocols
#include "relic.h"
Functions
int cp_phpe_gen (bn_t pub, phpe_t prv, size_t bits)
int cp_phpe_add (bn_t r, const bn_t c, const bn_t d, const bn_t pub)
int cp_phpe_enc (bn_t c, const bn_t m, const bn_t pub)
int cp_phpe_dec (bn_t m, const bn_t c, const phpe_t prv)
Detailed Description
Implementation of Paillier's Homomorphic Probabilistic Encryption.
Definition in file relic_cp_phpe.c.
Function Documentation
cp_phpe_gen()
int cp_phpe_gen (bn_t pub, phpe_t prv, size_t bits)
Generates a key pair for Paillier's Homomorphic Probabilistic Encryption.
Parameters
[out] pub - the public key.
[out] prv - the private key.
[in] bits - the key length in bits.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_phpe.c.
References bn_cmp(), bn_copy(), bn_gen_prime, bn_mod, bn_mod_inv(), bn_mul, bn_sub_dig(), RLC_EQ, and RLC_OK.
cp_phpe_add()
int cp_phpe_add (bn_t r, const bn_t c, const bn_t d, const bn_t pub)
Evaluated a homomorphic addition using the Paillier cryptosystem.
Parameters
[out] r - the resulting ciphertext.
[in] c - the first ciphertext as an integer to multiply.
[in] d - the second ciphertext as an integer to multiply.
[in] pub - the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 77 of file relic_cp_phpe.c.
References bn_free, bn_mod, bn_mul, bn_new, bn_null, bn_sqr, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_phpe_enc()
int cp_phpe_enc (bn_t c, const bn_t m, const bn_t pub)
Encrypts using the Paillier cryptosystem.
Parameters
[out] c - the ciphertext, represented as an integer.
[in] m - the plaintext as an integer.
[in] pub - the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 100 of file relic_cp_phpe.c.
References bn_add_dig(), bn_bits(), bn_free, bn_mod, bn_mul, bn_mxp, bn_new, bn_null, bn_rand_mod(), bn_sqr, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_phpe_dec()
int cp_phpe_dec (bn_t m, const bn_t c, const phpe_t prv)
Decrypts using the Paillier cryptosystem.
Parameters
[out] m - the plaintext, represented as an integer.
[in] c - the ciphertex as an integer.
[in] prv - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 143 of file relic_cp_phpe.c.
References bn_bits(), bn_div(), bn_free, bn_mod, bn_mod_inv(), bn_mul, bn_mxp, bn_mxp_crt(), bn_new, bn_null, bn_sqr, bn_sub_dig(), RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.