RELIC: src/fpx/relic_fp2_mul.c File Reference
relic_fp2_mul.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
Functions
void fp2_mul_basic (fp2_t c, const fp2_t a, const fp2_t b)
void fp2_mul_nor_basic (fp2_t c, const fp2_t a)
void fp2_mul_integ (fp2_t c, const fp2_t a, const fp2_t b)
void fp2_mul_nor_integ (fp2_t c, const fp2_t a)
void fp2_mul_art (fp2_t c, const fp2_t a)
void fp2_mul_frb (fp2_t c, const fp2_t a, int i, int j)
void fp2_mul_dig (fp2_t c, const fp2_t a, dig_t b)
Detailed Description
Implementation of multiplication in a quadratic extension of a prime field.
Definition in file relic_fp2_mul.c.
Function Documentation
fp2_mul_basic()
void fp2_mul_basic (fp2_t c, const fp2_t a, const fp2_t b)
Multiples two quadratic extension field elements using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the first quadratic extension field element.
[in] b - the second quadratic extension field element.
Definition at line 42 of file relic_fp2_mul.c.
References dv_free, dv_new, dv_null, ERR_CAUGHT, fp_add, fp_addc_low(), fp_muln_low(), fp_prime_get_qnr(), fp_rdc, fp_subc_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp2_mul_nor_basic()
void fp2_mul_nor_basic (fp2_t c, const fp2_t a)
Multiplies a quadratic extension field element by a quadratic/cubic non-residue.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to multiply.
Definition at line 104 of file relic_fp2_mul.c.
References bn_free, bn_new, bn_null, ERR_CAUGHT, ERR_NO_VALID, fp2_add, fp2_copy(), fp2_dbl, fp2_field_get_qnr(), fp2_free, fp2_mul_art(), fp2_new, fp2_null, fp_add, fp_neg, fp_prime_get_mod8(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp2_mul_integ()
void fp2_mul_integ (fp2_t c, const fp2_t a, const fp2_t b)
Multiples two quadratic extension field elements using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the first quadratic extension field element.
[in] b - the second quadratic extension field element.
Definition at line 167 of file relic_fp2_mul.c.
References fp2_mulm_low().
fp2_mul_nor_integ()
void fp2_mul_nor_integ (fp2_t c, const fp2_t a)
Multiplies a quadratic extension field element by a quadratic/cubic non-residue using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to multiply.
Definition at line 171 of file relic_fp2_mul.c.
References fp2_norm_low().
fp2_mul_art()
void fp2_mul_art (fp2_t c, const fp2_t a)
Multiplies a quadratic extension field element by the adjoined root. Computes c = a * i.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to multiply.
Definition at line 177 of file relic_fp2_mul.c.
References ERR_CAUGHT, fp_add, fp_copy(), fp_free, fp_neg, fp_new, fp_null, fp_prime_get_qnr(), fp_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep2_curve_mul_a(), fp2_mul_nor_basic(), and pp_dbl_k8_projc_new().
fp2_mul_frb()
void fp2_mul_frb (fp2_t c, const fp2_t a, int i, int j)
Multiplies a quadratic extension field element by a power of the constant needed to compute a power of the Frobenius map.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
[in] i - the power of the Frobenius map.
[in] j - the power of the constant.
Definition at line 211 of file relic_fp2_mul.c.
References core_get(), ERR_CAUGHT, fp2_copy(), fp2_free, fp2_mul, fp2_new, fp2_null, _ctx_t::fp2_p1, _ctx_t::fp2_p2, fp_copy(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp12_frb(), fp16_frb(), fp24_frb(), fp48_frb(), fp4_frb(), fp6_frb(), and fp8_frb().
fp2_mul_dig()
void fp2_mul_dig (fp2_t c, const fp2_t a, dig_t b)
Multiplies a quadratic extension field element by a digit. Computes c = a * b.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element.
[in] b - the digit to multiply.
Definition at line 254 of file relic_fp2_mul.c.
References fp_mul_dig().
Referenced by ep2_curve_mul_a(), ep2_curve_mul_b(), ep2_curve_set_map(), ep2_map_swift(), ep2_rhs(), and fp4_mul_dig().