RELIC: src/fpx/relic_fpx_field.c File Reference
relic_fpx_field.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fpx_low.h"
Functions
int fp2_field_get_qnr ()
int fp3_field_get_cnr ()
void fp2_field_init (void)
void fp3_field_init (void)
void fp4_field_init ()
void fp8_field_init ()
Detailed Description
Implementation of configuration for prime field extensions.
Definition in file relic_fpx_field.c.
Function Documentation
fp2_field_get_qnr()
int fp2_field_get_qnr (void)
Return the integer part (u) of the quadratic non-residue (i + u).
Definition at line 39 of file relic_fpx_field.c.
References core_get(), and _ctx_t::qnr2.
Referenced by fp2_mul_nor_basic().
fp3_field_get_cnr()
int fp3_field_get_cnr (void)
Return the integer part (u) of the cubic non-residue (j + u).
Definition at line 52 of file relic_fpx_field.c.
References _ctx_t::cnr3, core_get(), fp_param_get(), and K18_638.
Referenced by fp3_field_init(), fp3_mul_frb(), and fp3_mul_nor().
fp2_field_init()
void fp2_field_init (void)
Initializes the quadratic extension field arithmetic module.
Definition at line 65 of file relic_fpx_field.c.
References bn_div_dig(), bn_free, bn_new, bn_null, bn_sub_dig(), core_get(), dv_copy(), ERR_CAUGHT, fp2_exp(), fp2_free, fp2_mul, fp2_mul_nor, fp2_new, fp2_null, _ctx_t::fp2_p1, _ctx_t::fp2_p2, fp2_set_dig(), fp2_sqr, fp2_srt(), fp_copy(), fp_prime_get(), fp_set_dig(), fp_zero(), _ctx_t::qnr2, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, RLC_TRY, and util_bits_dig().
Referenced by fp_prime_calc().
fp3_field_init()
void fp3_field_init (void)
Initializes the cubic extension field arithmetic module.
Definition at line 173 of file relic_fpx_field.c.
References bn_div_dig(), bn_free, bn_new, bn_null, bn_read_raw(), _ctx_t::cnr3, core_get(), ERR_CAUGHT, fp3_exp(), fp3_field_get_cnr(), fp3_free, fp3_mul, fp3_mul_nor(), fp3_new, fp3_null, _ctx_t::fp3_p0, _ctx_t::fp3_p1, _ctx_t::fp3_p2, fp3_set_dig(), fp3_sqr, fp3_srt(), fp_copy(), fp_exp, fp_is_zero(), fp_neg, fp_prime_get(), fp_prime_get_cnr(), fp_set_dig(), fp_sqr, fp_zero(), _ctx_t::frb3, _ctx_t::qnr2, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, RLC_TRY, and util_bits_dig().
Referenced by fp_prime_calc().
fp4_field_init()
void fp4_field_init (void)
Initializes the quartic extension field arithmetic module.
Definition at line 303 of file relic_fpx_field.c.
References bn_div_dig(), bn_free, bn_new, bn_null, bn_sub_dig(), core_get(), dv_copy(), ERR_CAUGHT, fp2_is_zero(), fp4_exp(), fp4_free, fp4_mul_art(), fp4_new, fp4_null, _ctx_t::fp4_p1, fp4_set_dig(), fp_copy(), fp_prime_get(), _ctx_t::frb4, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
Referenced by fp_prime_calc().
fp8_field_init()
void fp8_field_init (void)
Initializes the octic extension field arithmetic module.
Definition at line 339 of file relic_fpx_field.c.
References bn_div_dig(), bn_free, bn_new, bn_null, bn_sub_dig(), core_get(), dv_copy(), ERR_CAUGHT, fp4_is_zero(), fp8_exp(), fp8_free, fp8_mul_art(), fp8_new, fp8_null, _ctx_t::fp8_p1, fp8_set_dig(), fp_copy(), fp_prime_get(), _ctx_t::frb8, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
Referenced by fp_prime_calc().