RELIC: src/fpx/relic_fp18_mul.c File Reference
relic_fp18_mul.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
Functions
static void fp9_mul_dxs_unr_lazyr (dv9_t c, const fp9_t a, const fp9_t b)
void fp18_mul_basic (fp18_t c, const fp18_t a, const fp18_t b)
void fp18_mul_dxs_basic (fp18_t c, const fp18_t a, const fp18_t b)
void fp18_mul_unr (dv18_t c, const fp18_t a, const fp18_t b)
void fp18_mul_lazyr (fp18_t c, const fp18_t a, const fp18_t b)
void fp18_mul_dxs_lazyr (fp18_t c, const fp18_t a, const fp18_t b)
void fp18_mul_art (fp18_t c, const fp18_t a)
Detailed Description
Implementation of multiplication in a octodecic extension of a prime field.
Definition in file relic_fp18_mul.c.
Function Documentation
fp9_mul_dxs_unr_lazyr()
static void fp9_mul_dxs_unr_lazyr (dv9_t c, const fp9_t a, const fp9_t b) inline static
Definition at line 42 of file relic_fp18_mul.c.
References dv3_free, dv3_new, dv3_null, ERR_CAUGHT, fp3_addc_low(), fp3_addm_low(), fp3_free, fp3_muln_low(), fp3_new, fp3_nord_low(), fp3_null, fp3_subc_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp18_mul_dxs_lazyr().
fp18_mul_basic()
void fp18_mul_basic (fp18_t c, const fp18_t a, const fp18_t b)
Multiples two octdecic extension field elements using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element.
[in] b - the octdecic extension field element.
Definition at line 99 of file relic_fp18_mul.c.
References ERR_CAUGHT, fp9_add(), fp9_free, fp9_mul, fp9_mul_art(), fp9_new, fp9_null, fp9_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp18_mul_dxs_basic()
void fp18_mul_dxs_basic (fp18_t c, const fp18_t a, const fp18_t b)
Multiples a dense octdecic extension field element by a sparse element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the dense octdecic extension field element.
[in] b - the sparse octdecic extension field element.
Definition at line 140 of file relic_fp18_mul.c.
References ERR_CAUGHT, fp3_add, fp3_copy(), fp3_mul, fp3_mul_nor(), fp9_add(), fp9_free, fp9_mul_art(), fp9_mul_dxs(), fp9_new, fp9_null, fp9_sub(), fp_add, fp_copy(), fp_mul, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp18_mul_unr()
void fp18_mul_unr (dv18_t c, const fp18_t a, const fp18_t b)
Multiples two octdecic extension field elements without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element.
[in] b - the octdecic extension field element.
Definition at line 203 of file relic_fp18_mul.c.
References dv9_free, dv9_new, dv9_null, ERR_CAUGHT, fp3_addc_low(), fp3_nord_low(), fp3_subc_low(), fp9_add(), fp9_free, fp9_mul_unr(), fp9_new, fp9_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp18_mul_lazyr().
fp18_mul_lazyr()
void fp18_mul_lazyr (fp18_t c, const fp18_t a, const fp18_t b)
Multiples two octdecic extension field elements using lazy reduction.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element.
[in] b - the octdecic extension field element.
Definition at line 256 of file relic_fp18_mul.c.
References dv18_free, dv18_new, dv18_null, ERR_CAUGHT, fp18_mul_unr(), fp3_rdcn_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp18_mul_dxs_lazyr()
void fp18_mul_dxs_lazyr (fp18_t c, const fp18_t a, const fp18_t b)
Multiples a dense octdecic extension field element by a sparse element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the dense octdecic extension field element.
[in] b - the sparse octdecic extension field element.
Definition at line 276 of file relic_fp18_mul.c.
References dv9_free, dv9_new, dv9_null, ep3_curve_is_twist(), ERR_CAUGHT, fp3_add, fp3_addc_low(), fp3_copy(), fp3_muln_low(), fp3_nord_low(), fp3_rdcn_low(), fp3_subc_low(), fp9_add(), fp9_free, fp9_mul_dxs_unr_lazyr(), fp9_new, fp9_null, fp_add, fp_copy(), fp_muln_low(), RLC_CATCH_ANY, RLC_EP_DTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp18_mul_art()
void fp18_mul_art (fp18_t c, const fp18_t a)
Multiplies an octdecic extension field element by the adjoined root.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element to multiply.
Definition at line 380 of file relic_fp18_mul.c.
References ERR_CAUGHT, fp9_copy(), fp9_free, fp9_mul_art(), fp9_new, fp9_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp54_inv(), fp54_mul_art(), fp54_mul_basic(), fp54_mul_dxs(), fp54_mul_lazyr(), fp54_sqr_basic(), and fp54_sqr_lazyr().