RELIC: src/cp/relic_cp_mklhs.c File Reference
relic_cp_mklhs.c File Reference
Cryptographic protocols
#include "relic.h"
Functions
int cp_mklhs_gen (bn_t sk, g2_t pk)
int cp_mklhs_sig (g1_t s, const bn_t m, const char *data, const char *id, const char *tag, const bn_t sk)
int cp_mklhs_fun (bn_t mu, const bn_t m[], const dig_t f[], size_t len)
int cp_mklhs_evl (g1_t sig, const g1_t s[], const dig_t f[], size_t len)
int cp_mklhs_ver (const g1_t sig, const bn_t m, const bn_t mu[], const char *data, const char *id[], const char *tag[], const dig_t *f[], const size_t flen[], const g2_t pk[], size_t slen)
int cp_mklhs_off (g1_t h[], dig_t ft[], const char *id[], const char *tag[], const dig_t *f[], const size_t flen[], size_t slen)
int cp_mklhs_onv (const g1_t sig, const bn_t m, const bn_t mu[], const char *data, const char *id[], const g1_t h[], const dig_t ft[], const g2_t pk[], size_t slen)
Detailed Description
Implementation of the multi-key linearly homomophic signature protocol.
Definition in file relic_cp_mklhs.c.
Function Documentation
cp_mklhs_gen()
int cp_mklhs_gen (bn_t sk, g2_t pk)
Generates a key pair for the Multi-Key Homomorphic Signature (MKLHS) scheme.
Parameters
[out] sk - the private key for the signature scheme.
[out] pk - the public key for the signature scheme.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_mklhs.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), g2_mul_gen(), pc_get_ord, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_mklhs_sig()
int cp_mklhs_sig (g1_t s, const bn_t m, const char * data, const char * id, const char * tag, const bn_t sk)
Signs a message using the MKLHS.
Parameters
[out] s - the resulting signature.
[in] m - the message to sign.
[in] data - the dataset identifier.
[in] id - the identity.
[in] tag - the tag.
[in] sk - the private key for the signature scheme.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 60 of file relic_cp_mklhs.c.
References bn_free, bn_new, bn_null, ERR_NO_MEMORY, g1_add, g1_free, g1_map, g1_mul_gen(), g1_mul_sec, g1_new, g1_norm, g1_null, pc_get_ord, RLC_ALLOCA, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_FREE, RLC_MAX, RLC_OK, RLC_THROW, and RLC_TRY.
cp_mklhs_fun()
int cp_mklhs_fun (bn_t mu, const bn_t m[], const dig_t f[], size_t len)
Definition at line 104 of file relic_cp_mklhs.c.
References bn_add(), bn_free, bn_mod, bn_mul_dig(), bn_new, bn_null, bn_zero(), pc_get_ord, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_mklhs_evl()
int cp_mklhs_evl (g1_t sig, const g1_t s[], const dig_t f[], size_t len)
Definition at line 133 of file relic_cp_mklhs.c.
References g1_mul_sim_dig, and RLC_OK.
cp_mklhs_ver()
int cp_mklhs_ver (const g1_t sig, const bn_t m, const bn_t mu[], const char * data, const char * id[], const char * tag[], const dig_t * f[], const size_t flen[], const g2_t pk[], size_t slen)
Definition at line 141 of file relic_cp_mklhs.c.
References bn_add(), bn_cmp(), bn_free, bn_mod, bn_new, bn_null, bn_zero(), ERR_CAUGHT, ERR_NO_MEMORY, g1_add, g1_free, g1_map, g1_mul_gen(), g1_mul_sim_dig, g1_new, g1_norm_sim, g1_null, g2_free, g2_get_gen, g2_new, g2_null, gt_cmp, gt_free, gt_new, gt_null, pc_get_ord, pc_map, pc_map_sim, RLC_ALLOCA, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FREE, RLC_MAX, RLC_THROW, and RLC_TRY.
cp_mklhs_off()
int cp_mklhs_off (g1_t h[], dig_t ft[], const char * id[], const char * tag[], const dig_t * f[], const size_t flen[], size_t slen)
Definition at line 243 of file relic_cp_mklhs.c.
References ERR_NO_MEMORY, g1_free, g1_map, g1_mul_sim_dig, g1_new, g1_null, RLC_ALLOCA, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_FREE, RLC_MAX, RLC_OK, RLC_THROW, and RLC_TRY.
cp_mklhs_onv()
int cp_mklhs_onv (const g1_t sig, const bn_t m, const bn_t mu[], const char * data, const char * id[], const g1_t h[], const dig_t ft[], const g2_t pk[], size_t slen)
Definition at line 291 of file relic_cp_mklhs.c.
References bn_add(), bn_cmp(), bn_free, bn_mod, bn_new, bn_null, bn_zero(), ERR_CAUGHT, ERR_NO_MEMORY, g1_add, g1_free, g1_map, g1_mul_dig, g1_mul_gen(), g1_new, g1_norm_sim, g1_null, g2_free, g2_get_gen, g2_new, g2_null, gt_cmp, gt_free, gt_new, gt_null, pc_get_ord, pc_map, pc_map_sim, RLC_ALLOCA, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FREE, RLC_MAX, RLC_THROW, and RLC_TRY.