RELIC: src/ep/relic_ep_add.c File Reference
relic_ep_add.c File Reference
Elliptic curves over prime fields
#include "relic_core.h"
#include "relic_ep_add_tmpl.h"
Functions
TMPL_ADD_BASIC_IMP (ep, fp)
TMPL_ADD_PROJC_MIX (ep, fp)
TMPL_ADD_PROJC_IMP (ep, fp)
TMPL_ADD_JACOB_MIX (ep, fp)
TMPL_ADD_JACOB_IMP (ep, fp)
void ep_add_basic (ep_t r, const ep_t p, const ep_t q)
void ep_add_slp_basic (ep_t r, fp_t s, const ep_t p, const ep_t q)
void ep_add_projc (ep_t r, const ep_t p, const ep_t q)
void ep_add_jacob (ep_t r, const ep_t p, const ep_t q)
void ep_sub (ep_t r, const ep_t p, const ep_t q)
Detailed Description
Implementation of the point addition on prime elliptic curves.
Definition in file relic_ep_add.c.
Function Documentation
TMPL_ADD_BASIC_IMP()
TMPL_ADD_BASIC_IMP (ep , fp)
Adds two points represented in affine coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the first point to add.
[in] q - the second point to add.
TMPL_ADD_PROJC_MIX()
TMPL_ADD_PROJC_MIX (ep , fp)
Adds a point represented in homogeneous coordinates to a point represented in affine coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[in] p - the projective point.
[in] q - the affine point.
TMPL_ADD_PROJC_IMP()
TMPL_ADD_PROJC_IMP (ep , fp)
Adds two points represented in homogeneous coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
TMPL_ADD_JACOB_MIX()
TMPL_ADD_JACOB_MIX (ep , fp)
Adds a point represented in Jacobian coordinates to a point represented in affine coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[in] p - the projective point.
[in] q - the affine point.
TMPL_ADD_JACOB_IMP()
TMPL_ADD_JACOB_IMP (ep , fp)
Adds two points represented in Jacobian coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
ep_add_basic()
void ep_add_basic (ep_t r, const ep_t p, const ep_t q)
Adds two prime elliptic curve points represented in affine coordinates.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 108 of file relic_ep_add.c.
References ep_copy(), and ep_is_infty().
ep_add_slp_basic()
void ep_add_slp_basic (ep_t r, fp_t s, const ep_t p, const ep_t q)
Adds two prime elliptic curve points represented in affine coordinates and returns the computed slope.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 122 of file relic_ep_add.c.
References ep_copy(), and ep_is_infty().
Referenced by pp_add_k1_basic(), and pp_add_k2_basic().
ep_add_projc()
void ep_add_projc (ep_t r, const ep_t p, const ep_t q)
Adds two prime elliptic curve points represented in projective coordinates.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 140 of file relic_ep_add.c.
References ep_copy(), and ep_is_infty().
ep_add_jacob()
void ep_add_jacob (ep_t r, const ep_t p, const ep_t q)
Adds two prime elliptic curve points represented in Jacobian coordinates.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 158 of file relic_ep_add.c.
References ep_copy(), and ep_is_infty().
ep_sub()
void ep_sub (ep_t r, const ep_t p, const ep_t q)
Subtracts a prime elliptic curve point from another.
Parameters
[out] r - the result.
[in] p - the first point.
[in] q - the second point.
Definition at line 174 of file relic_ep_add.c.
References ep_add, ep_free, ep_neg(), ep_new, ep_null, ep_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep_mul_basic(), ep_mul_cof(), ep_mul_combs_endom(), ep_mul_dig(), ep_mul_fix_plain(), ep_mul_glv_imp(), ep_mul_naf_imp(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_mul_sim_endom(), ep_mul_sim_joint(), ep_mul_sim_lot_endom(), ep_mul_sim_lot_plain(), and ep_mul_sim_plain().