RELIC: src/pp/relic_pp_map_k48.c File Reference
relic_pp_map_k48.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_util.h"
Functions
static void pp_mil_k48 (fp48_t r, ep8_t *t, ep8_t *q, ep_t *p, int m, bn_t a)
void pp_map_k48 (fp48_t r, const ep_t p, const ep8_t q)
void pp_map_sim_k48 (fp48_t r, const ep_t *p, const ep8_t *q, int m)
Detailed Description
Implementation of pairing computation for curves with embedding degree 48.
Definition in file relic_pp_map_k48.c.
Function Documentation
pp_mil_k48()
static void pp_mil_k48 (fp48_t r, ep8_t * t, ep8_t * q, ep_t * p, int m, bn_t a) static
Compute the Miller loop for pairings of type G_2 x G_1 over the bits of a given parameter represented in sparse form.
Parameters
[out] r - the result.
[out] t - the resulting point.
[in] q - the vector of first arguments in affine coordinates.
[in] p - the vector of second arguments in affine coordinates.
[in] n - the number of pairings to evaluate.
[in] a - the loop parameter.
Definition at line 51 of file relic_pp_map_k48.c.
References bn_bits(), bn_rec_naf(), ep8_copy(), ep8_free, ep8_neg(), ep8_new, ep8_null, ep_free, ep_neg(), ep_new, ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp48_free, fp48_mul_dxs(), fp48_new, fp48_null, fp48_sqr, fp48_zero(), fp_add, fp_neg, pp_add_k48, pp_dbl_k48, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by pp_map_k48(), and pp_map_sim_k48().
pp_map_k48()
void pp_map_k48 (fp48_t r, const ep_t p, const ep8_t q)
Computes the Optimal Ate pairing of two points in a parameterized elliptic curve with embedding degree 48.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 142 of file relic_pp_map_k48.c.
References bn_free, bn_new, bn_null, bn_sign(), ep8_free, ep8_is_infty(), ep8_new, ep8_norm(), ep8_null, EP_B48, ep_curve_is_pairf(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, fp48_inv_cyc(), fp48_set_dig(), fp_prime_get_par(), pp_exp_k48(), pp_mil_k48(), RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
pp_map_sim_k48()
void pp_map_sim_k48 (fp48_t r, const ep_t * p, const ep8_t * q, int m)
Computes the optimal ate multi-pairing in a parameterized elliptic curve with embedding degree 48.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 188 of file relic_pp_map_k48.c.
References bn_free, bn_new, bn_null, bn_sign(), ep8_free, ep8_is_infty(), ep8_new, ep8_norm(), ep8_null, EP_B48, ep_curve_is_pairf(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp48_inv_cyc(), fp48_set_dig(), fp_prime_get_par(), pp_exp_k48(), pp_mil_k48(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.