RELIC: src/fpx/relic_fpx_pck.c File Reference
relic_fpx_pck.c File Reference
Prime field extensions.
#include "relic_core.h"
Functions
void fp2_pck (fp2_t c, const fp2_t a)
int fp2_upk (fp2_t c, const fp2_t a)
void fp12_pck (fp12_t c, const fp12_t a)
int fp12_upk (fp12_t c, const fp12_t a)
void fp12_pck_max (fp12_t c, const fp12_t a)
int fp12_upk_max (fp12_t c, const fp12_t a)
void fp18_pck (fp18_t c, const fp18_t a)
int fp18_upk (fp18_t c, const fp18_t a)
void fp24_pck (fp24_t c, const fp24_t a)
int fp24_upk (fp24_t c, const fp24_t a)
void fp48_pck (fp48_t c, const fp48_t a)
int fp48_upk (fp48_t c, const fp48_t a)
void fp54_pck (fp54_t c, const fp54_t a)
int fp54_upk (fp54_t c, const fp54_t a)
Detailed Description
Implementation of finite field compression in extension fields.
Definition in file relic_fpx_pck.c.
Function Documentation
fp2_pck()
void fp2_pck (fp2_t c, const fp2_t a)
Compresses an extension field element.
Parameters
[out] c - the result.
[in] a - the extension field element to compress.
Definition at line 38 of file relic_fpx_pck.c.
References fp2_copy(), fp2_test_cyc(), fp_copy(), fp_get_bit(), fp_set_bit(), and fp_zero().
Referenced by fp2_write_bin().
fp2_upk()
int fp2_upk (fp2_t c, const fp2_t a)
Decompresses a quadratic extension field element.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element.
Returns
if the decompression was successful
Definition at line 48 of file relic_fpx_pck.c.
References ERR_CAUGHT, fp2_copy(), fp_bits(), fp_copy(), fp_free, fp_get_bit(), fp_neg, fp_new, fp_null, fp_sqr, fp_srt(), fp_sub_dig(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp2_read_bin().
fp12_pck()
void fp12_pck (fp12_t c, const fp12_t a)
Compresses a dodecic extension field element.
Parameters
[out] r - the result.
[in] p - the dodecic extension field element to compress.
Definition at line 87 of file relic_fpx_pck.c.
References fp12_copy(), fp12_test_cyc(), and fp2_zero().
Referenced by fp12_write_bin().
fp12_upk()
int fp12_upk (fp12_t c, const fp12_t a)
Decompresses a dodecic extension field element.
Parameters
[out] r - the result.
[in] p - the dodecic extension field element to decompress.
Returns
if the decompression was successful
Definition at line 95 of file relic_fpx_pck.c.
References fp12_back_cyc(), fp12_copy(), fp12_test_cyc(), and fp2_is_zero().
fp12_pck_max()
void fp12_pck_max (fp12_t c, const fp12_t a)
Compresses a dodecic extension field element at the maximum rate.
Parameters
[out] r - the result.
[in] p - the dodecic extension field element to compress.
Definition at line 109 of file relic_fpx_pck.c.
References fp12_copy(), fp12_test_cyc(), fp2_add_dig(), fp6_inv(), fp6_mul, and fp6_zero().
fp12_upk_max()
int fp12_upk_max (fp12_t c, const fp12_t a)
Decompresses a dodecic extension field element at the maximum rate.
Parameters
[out] r - the result.
[in] p - the dodecic extension field element to decompress.
Returns
if the decompression was successful
Definition at line 122 of file relic_fpx_pck.c.
References ERR_CAUGHT, fp12_copy(), fp12_free, fp12_inv(), fp12_mul, fp12_new, fp12_null, fp12_test_cyc(), fp6_copy(), fp6_is_zero(), fp6_set_dig(), fp6_zero(), fp_neg, fp_set_dig(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp18_pck()
void fp18_pck (fp18_t c, const fp18_t a)
Compresses a octdecic extension field element.
Parameters
[out] r - the result.
[in] p - the octdecic extension field element to compress.
Definition at line 158 of file relic_fpx_pck.c.
References fp18_copy(), fp18_test_cyc(), and fp2_zero().
Referenced by fp18_write_bin().
fp18_upk()
int fp18_upk (fp18_t c, const fp18_t a)
Decompresses a octdecic extension field element.
Parameters
[out] r - the result.
[in] p - the octdecic extension field element to decompress.
Returns
if the decompression was successful
Definition at line 166 of file relic_fpx_pck.c.
References fp18_back_cyc(), fp18_copy(), fp18_test_cyc(), and fp2_is_zero().
fp24_pck()
void fp24_pck (fp24_t c, const fp24_t a)
Compresses a 24-extension field element.
Parameters
[out] c - the result.
[in] a - the 24-extension field element to compress.
Definition at line 180 of file relic_fpx_pck.c.
References fp24_copy(), fp24_test_cyc(), and fp4_zero().
Referenced by fp24_write_bin().
fp24_upk()
int fp24_upk (fp24_t c, const fp24_t a)
Decompresses a 24-extension field element.
Parameters
[out] c - the result.
[in] a - the 24-extension field element to decompress.
Returns
if the decompression was successful
Definition at line 188 of file relic_fpx_pck.c.
References fp24_back_cyc(), fp24_copy(), fp24_test_cyc(), and fp4_is_zero().
fp48_pck()
void fp48_pck (fp48_t c, const fp48_t a)
Compresses a 48-extension field element.
Parameters
[out] c - the result.
[in] a - the 48-extension field element to compress.
Definition at line 202 of file relic_fpx_pck.c.
References fp48_copy(), fp48_test_cyc(), and fp8_zero().
Referenced by fp48_write_bin().
fp48_upk()
int fp48_upk (fp48_t c, const fp48_t a)
Decompresses a 48-extension field element.
Parameters
[out] c - the result.
[in] a - the 48-extension field element to decompress.
Returns
if the decompression was successful
Definition at line 210 of file relic_fpx_pck.c.
References fp48_back_cyc(), fp48_copy(), fp48_test_cyc(), and fp8_is_zero().
fp54_pck()
void fp54_pck (fp54_t c, const fp54_t a)
Compresses a 54-extension field element.
Parameters
[out] c - the result.
[in] a - the 54-extension field element to compress.
Definition at line 224 of file relic_fpx_pck.c.
References fp54_copy(), fp54_test_cyc(), and fp9_zero().
Referenced by fp54_write_bin().
fp54_upk()
int fp54_upk (fp54_t c, const fp54_t a)
Decompresses a 54-extension field element.
Parameters
[out] c - the result.
[in] a - the 54-extension field element to decompress.
Returns
if the decompression was successful
Definition at line 232 of file relic_fpx_pck.c.
References fp54_back_cyc(), fp54_copy(), fp54_test_cyc(), and fp9_is_zero().