RELIC: src/fpx/relic_fp48_sqr.c File Reference
relic_fp48_sqr.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
Functions
void fp48_sqr_basic (fp48_t c, const fp48_t a)
void fp48_sqr_cyc_basic (fp48_t c, const fp48_t a)
void fp48_sqr_pck_basic (fp48_t c, const fp48_t a)
void fp48_sqr_lazyr (fp48_t c, const fp48_t a)
void fp48_sqr_cyc_lazyr (fp48_t c, const fp48_t a)
void fp48_sqr_pck_lazyr (fp48_t c, const fp48_t a)
Detailed Description
Implementation of squaring in a dodecic extension of a prime field.
Definition in file relic_fp48_sqr.c.
Function Documentation
fp48_sqr_basic()
void fp48_sqr_basic (fp48_t c, const fp48_t a)
Computes the square of a 48-extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the 48-extension field element to square.
Definition at line 42 of file relic_fp48_sqr.c.
References ERR_CAUGHT, fp24_add(), fp24_dbl(), fp24_free, fp24_mul, fp24_mul_art(), fp24_new, fp24_null, fp24_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp48_sqr_cyc_basic()
void fp48_sqr_cyc_basic (fp48_t c, const fp48_t a)
Computes the square of a cyclotomic 48-extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 69 of file relic_fp48_sqr.c.
References ERR_CAUGHT, fp8_add(), fp8_dbl(), fp8_free, fp8_mul_art(), fp8_new, fp8_null, fp8_sqr, fp8_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp48_sqr_pck_basic()
void fp48_sqr_pck_basic (fp48_t c, const fp48_t a)
Computes the square of a compressed cyclotomic extension field element.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 158 of file relic_fp48_sqr.c.
References ERR_CAUGHT, fp8_add(), fp8_dbl(), fp8_free, fp8_mul_art(), fp8_new, fp8_null, fp8_sqr, fp8_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp48_sqr_lazyr()
void fp48_sqr_lazyr (fp48_t c, const fp48_t a)
Computes the square of a 48-extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the 48-extension field element to square.
Definition at line 232 of file relic_fp48_sqr.c.
References ERR_CAUGHT, fp24_add(), fp24_dbl(), fp24_free, fp24_mul, fp24_mul_art(), fp24_new, fp24_null, fp24_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp48_sqr_cyc_lazyr()
void fp48_sqr_cyc_lazyr (fp48_t c, const fp48_t a)
Computes the square of a cyclotomic 48-extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 260 of file relic_fp48_sqr.c.
References ERR_CAUGHT, fp8_add(), fp8_dbl(), fp8_free, fp8_mul_art(), fp8_new, fp8_null, fp8_sqr, fp8_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp48_sqr_pck_lazyr()
void fp48_sqr_pck_lazyr (fp48_t c, const fp48_t a)
Computes the square of a compressed cyclotomic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 349 of file relic_fp48_sqr.c.
References dv8_free, dv8_new, dv8_null, ERR_CAUGHT, fp2_addc_low(), fp2_nord_low(), fp2_rdcn_low(), fp2_subc_low(), fp8_add(), fp8_dbl(), fp8_free, fp8_mul_art(), fp8_new, fp8_null, fp8_sqr, fp8_sqr_unr(), fp8_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.