RELIC: src/fpx/relic_fp9_mul.c File Reference
relic_fp9_mul.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fpx_low.h"
Functions
void fp9_mul_basic (fp9_t c, const fp9_t a, const fp9_t b)
void fp9_mul_unr (dv9_t c, const fp9_t a, const fp9_t b)
void fp9_mul_lazyr (fp9_t c, const fp9_t a, const fp9_t b)
void fp9_mul_dxs (fp9_t c, const fp9_t a, const fp9_t b)
void fp9_mul_art (fp9_t c, const fp9_t a)
Detailed Description
Implementation of multiplication in a nonic extension of a prime field.
Definition in file relic_fp9_mul.c.
Function Documentation
fp9_mul_basic()
void fp9_mul_basic (fp9_t c, const fp9_t a, const fp9_t b)
Multiples two nonic extension field elements.
Parameters
[out] c - the result.
[in] a - the nonic extension field element.
[in] b - the nonic extension field element.
Definition at line 41 of file relic_fp9_mul.c.
References ERR_CAUGHT, fp3_add, fp3_copy(), fp3_free, fp3_mul, fp3_mul_nor(), fp3_new, fp3_null, fp3_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp9_mul_unr()
void fp9_mul_unr (dv9_t c, const fp9_t a, const fp9_t b)
Multiples two nonic extension field elements without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the nonic extension field element.
[in] b - the nonic extension field element.
Definition at line 112 of file relic_fp9_mul.c.
References dv3_free, dv3_new, dv3_null, ERR_CAUGHT, fp3_addc_low(), fp3_addm_low(), fp3_free, fp3_muln_low(), fp3_new, fp3_nord_low(), fp3_null, fp3_subc_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp18_mul_unr(), and fp9_mul_lazyr().
fp9_mul_lazyr()
void fp9_mul_lazyr (fp9_t c, const fp9_t a, const fp9_t b)
Multiples two nonic extension field elements using lazy reduction.
Parameters
[out] c - the result.
[in] a - the nonic extension field element.
[in] b - the nonic extension field element.
Definition at line 185 of file relic_fp9_mul.c.
References dv9_free, dv9_new, dv9_null, ERR_CAUGHT, fp3_rdcn_low(), fp9_mul_unr(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp9_mul_dxs()
void fp9_mul_dxs (fp9_t c, const fp9_t a, const fp9_t b)
Multiples a dense nonic extension field element by a sparse element.
Parameters
[out] c - the result.
[in] a - a nonic extension field element.
[in] b - a sparse nonic extension field element.
Definition at line 205 of file relic_fp9_mul.c.
References ERR_CAUGHT, fp3_add, fp3_copy(), fp3_free, fp3_mul, fp3_mul_nor(), fp3_new, fp3_null, fp3_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp18_mul_dxs_basic().
fp9_mul_art()
void fp9_mul_art (fp9_t c, const fp9_t a)
Multiplies a nonic extension field element by the adjoined root.
Parameters
[out] c - the result.
[in] a - the nonic extension field element to multiply.
Definition at line 262 of file relic_fp9_mul.c.
References ERR_CAUGHT, fp3_copy(), fp3_free, fp3_mul_nor(), fp3_new, fp3_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp18_inv(), fp18_mul_art(), fp18_mul_basic(), fp18_mul_dxs_basic(), fp18_sqr_basic(), fp54_back_cyc(), fp54_back_cyc_sim(), fp54_frb(), fp54_sqr_cyc_basic(), fp54_sqr_cyc_lazyr(), fp54_sqr_pck_basic(), and fp54_sqr_pck_lazyr().