RELIC: src/cp/relic_cp_bbs.c File Reference
relic_cp_bbs.c File Reference
Cryptographic protocols
#include "relic.h"
Functions
int cp_bbs_gen (bn_t d, g2_t q, gt_t z)
int cp_bbs_sig (g1_t s, const uint8_t *msg, size_t len, int hash, const bn_t d)
int cp_bbs_ver (g1_t s, const uint8_t *msg, size_t len, int hash, const g2_t q, const gt_t z)
Detailed Description
Implementation of the Boneh-Boyen short signature protocol.
Definition in file relic_cp_bbs.c.
Function Documentation
cp_bbs_gen()
int cp_bbs_gen (bn_t d, g2_t q, gt_t z)
Generates a key pair for the Boneh-Boyen (BB) signature protocol.
Parameters
[out] d - the private key.
[out] q - the first component of the public key.
[out] z - the second component of the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_bbs.c.
References bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, bn_rand(), g2_mul_gen(), gt_get_gen(), pc_get_ord, pc_param_level, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, RLC_POS, and RLC_TRY.
cp_bbs_sig()
int cp_bbs_sig (g1_t s, const uint8_t * msg, size_t len, int hash, const bn_t d)
Signs a message using the BB protocol.
Parameters
[out] s - the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] hash - the flag to indicate the message format.
[in] d - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 70 of file relic_cp_bbs.c.
References bn_add(), bn_free, bn_mod, bn_mod_inv(), bn_new, bn_null, bn_read_bin(), g1_mul_gen(), md_map, pc_get_ord, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_MD_LEN, RLC_OK, and RLC_TRY.
cp_bbs_ver()
int cp_bbs_ver (g1_t s, const uint8_t * msg, size_t len, int hash, const g2_t q, const gt_t z)
Verifies a message signed with the BB protocol.
Parameters
[in] s - the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] hash - the flag to indicate the message format.
[out] q - the first component of the public key.
[out] z - the second component of the public key.
Returns
a boolean value indicating the verification result.
Definition at line 112 of file relic_cp_bbs.c.
References bn_free, bn_mod, bn_new, bn_null, bn_read_bin(), ERR_CAUGHT, g1_is_valid(), g2_add, g2_free, g2_mul_gen(), g2_new, g2_norm, g2_null, gt_cmp, gt_free, gt_new, gt_null, md_map, pc_get_ord, pc_map, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_MD_LEN, RLC_THROW, and RLC_TRY.