RELIC: src/fpx/relic_fp3_mul.c File Reference
relic_fp3_mul.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
Functions
void fp3_mul_basic (fp3_t c, const fp3_t a, const fp3_t b)
void fp3_mul_integ (fp3_t c, const fp3_t a, const fp3_t b)
void fp3_mul_art (fp3_t c, const fp3_t a)
void fp3_mul_nor (fp3_t c, const fp3_t a)
void fp3_mul_frb (fp3_t c, const fp3_t a, int i, int j)
void fp3_mul_dig (fp3_t c, const fp3_t a, dig_t b)
Detailed Description
Implementation of multiplication in a cubic extension of a prime field.
Definition in file relic_fp3_mul.c.
Function Documentation
fp3_mul_basic()
void fp3_mul_basic (fp3_t c, const fp3_t a, const fp3_t b)
Multiples two cubic extension field elements using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the first cubic extension field element.
[in] b - the second cubic extension field element.
Definition at line 42 of file relic_fp3_mul.c.
References dv_free, dv_new, dv_null, ERR_CAUGHT, fp_add, fp_addc_low(), fp_addd_low(), fp_muln_low(), fp_prime_get_cnr(), fp_rdc, fp_subc_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp3_mul_integ()
void fp3_mul_integ (fp3_t c, const fp3_t a, const fp3_t b)
Multiples two cubic extension field elements using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the first cubic extension field element.
[in] b - the second cubic extension field element.
Definition at line 146 of file relic_fp3_mul.c.
References fp3_mulm_low().
fp3_mul_art()
void fp3_mul_art (fp3_t c, const fp3_t a)
Multiplies a cubic extension field element by the adjoined root. Computes c = a * j.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to multiply.
Definition at line 152 of file relic_fp3_mul.c.
References ERR_CAUGHT, fp_add, fp_copy(), fp_free, fp_new, fp_null, fp_prime_get_cnr(), fp_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep3_curve_set_twist(), and fp3_mul_nor().
fp3_mul_nor()
void fp3_mul_nor (fp3_t c, const fp3_t a)
Multiplies a cubic extension field element by a cubic non-residue.
Parameters
[out] c - the result.
[in] a - the cubic extension field element to multiply.
Definition at line 180 of file relic_fp3_mul.c.
References ERR_CAUGHT, fp3_add, fp3_copy(), fp3_dbl, fp3_field_get_cnr(), fp3_free, fp3_mul_art(), fp3_new, fp3_null, fp3_sub, fp_prime_get_mod18(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp18_back_cyc(), fp18_back_cyc_sim(), fp18_mul_dxs_basic(), fp18_sqr_cyc_basic(), fp18_sqr_cyc_lazyr(), fp18_sqr_pck_basic(), fp18_sqr_pck_lazyr(), fp3_field_init(), fp3_mul_frb(), fp9_inv(), fp9_mul_art(), fp9_mul_basic(), fp9_mul_dxs(), fp9_sqr_basic(), and pp_mil_k54().
fp3_mul_frb()
void fp3_mul_frb (fp3_t c, const fp3_t a, int i, int j)
Multiplies a cubic extension field element by a power of the constant needed to compute a power of the Frobenius map. If the flag is zero, the map is computed on the cubic extension directly; otherwise the map is computed on a higher extension.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
[in] i - the power of the Frobenius map.
[in] j - the power of the constant.
Definition at line 226 of file relic_fp3_mul.c.
References core_get(), ERR_CAUGHT, fp3_copy(), fp3_field_get_cnr(), fp3_free, fp3_mul, fp3_mul_nor(), fp3_new, fp3_null, _ctx_t::fp3_p0, _ctx_t::fp3_p1, _ctx_t::fp3_p2, fp_copy(), fp_mul, _ctx_t::frb3, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp18_frb(), fp3_frb(), fp54_frb(), and fp9_frb().
fp3_mul_dig()
void fp3_mul_dig (fp3_t c, const fp3_t a, dig_t b)
Multiplies a cubic extension field element by a digit. Computes c = a * b.
Parameters
[out] c - the result.
[in] a - the cubic extension field element.
[in] b - the digit to multiply.
Definition at line 303 of file relic_fp3_mul.c.
References fp_mul_dig().
Referenced by ep3_curve_mul_a(), ep3_curve_mul_b(), and ep3_rhs().