RELIC: src/epx/relic_ep2_map.c File Reference
relic_ep2_map.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
#include "relic_md.h"
#include "relic_ep_map_tmpl.h"
Macros
#define EP2_MAP_CONVERT_BYTES(IDX)
#define EP2_MAP_APPLY_MAP(PT)
Functions
static int fp2_sgn0 (const fp2_t t, bn_t k)
static void ep2_map_from_field (ep2_t p, const uint8_t *r, size_t len)
void ep2_map_basic (ep2_t p, const uint8_t *msg, size_t len)
void ep2_map_sswum (ep2_t p, const uint8_t *msg, size_t len)
void ep2_map_swift (ep2_t p, const uint8_t *msg, size_t len)
Detailed Description
Implementation of hashing to a prime elliptic curve over a quadratic extension field.
Definition in file relic_ep2_map.c.
Macro Definition Documentation
EP2_MAP_CONVERT_BYTES
#define EP2_MAP_CONVERT_BYTES (IDX)
Value:
        do {                                                                \
            bn_read_bin(k, r + 2 * IDX * lpe, lpe);                         \
            fp_prime_conv(t[0], k);                                         \
            bn_read_bin(k, r + (2 * IDX + 1) * lpe, lpe);                   \
            fp_prime_conv(t[1], k);                                         \
        } while (0)
Referenced by ep2_map_from_field().
EP2_MAP_APPLY_MAP
#define EP2_MAP_APPLY_MAP (PT)
Value:
        do {                                                                \
            /* sign of t */                                                 \
            neg = fp2_sgn0(t, k);                                           \
            /* convert */                                                   \
            map_fn(PT, t);                                                  \
            /* compare sign of y to sign of t; fix if necessary */          \
            neg = neg != fp2_sgn0(PT->y, k);                                \
            fp2_neg(t, PT->y);                                              \
            fp2_copy_sec(PT->y, t, neg);                                    \
        } while (0)
Referenced by ep2_map_from_field().
Function Documentation
fp2_sgn0()
static int fp2_sgn0 (const fp2_t t, bn_t k) inline static
Evaluate a polynomial represented by its coefficients using Horner's rule.
Parameters
[out] c - the result.
[in] a - the input value.
[in] coeffs - the vector of coefficients in the polynomial.
[in] len - the degree of the polynomial. Generic isogeny map evaluation for use with SSWU map. Simplified SWU mapping. Shallue–van de Woestijne map.
Definition at line 69 of file relic_ep2_map.c.
References bn_get_bit(), fp_is_zero(), and fp_prime_back().
ep2_map_from_field()
static void ep2_map_from_field (ep2_t p, const uint8_t * r, size_t len) static
Maps a byte array to a point in an elliptic curve over a quadratic extension using an explicit domain separation tag.
Parameters
[out] p - the result.
[in] msg - the byte array to map.
[in] len - the array length in bytes.
[in] dst - the domain separatoin tag.
[in] dst_len - the domain separation tag length in bytes.
Definition at line 92 of file relic_ep2_map.c.
References bn_free, bn_new, bn_null, ep2_add, ep2_curve_is_ctmap(), ep2_curve_opt_a(), ep2_curve_opt_b(), ep2_free, EP2_MAP_APPLY_MAP, EP2_MAP_CONVERT_BYTES, ep2_mul_cof(), ep2_new, ep2_norm(), ep2_null, ep_param_level(), ERR_CAUGHT, ERR_NO_VALID, fp2_free, fp2_new, fp2_null, FP_PRIME, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, RLC_TRY, RLC_ZERO, and TMPL_MAP_CALL_ISOMAP.
Referenced by ep2_map_sswum().
ep2_map_basic()
void ep2_map_basic (ep2_t p, const uint8_t * msg, size_t len)
Maps a byte array to a point in a prime elliptic curve using the hash and increment approach.
Parameters
[out] p - the result.
[in] msg - the byte array to map.
[in] len - the array length in bytes.
Definition at line 176 of file relic_ep2_map.c.
References BASIC, bn_free, bn_new, bn_null, bn_read_bin(), ep2_mul_cof(), ep2_rhs(), ERR_CAUGHT, fp2_add_dig(), fp2_free, fp2_is_sqr(), fp2_new, fp2_null, fp2_set_dig(), fp2_srt(), fp2_zero(), fp_prime_conv(), md_map, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_MD_LEN, RLC_MIN, RLC_THROW, and RLC_TRY.
ep2_map_sswum()
void ep2_map_sswum (ep2_t p, const uint8_t * msg, size_t len)
Maps a byte array to a point in a prime elliptic curve using the (Simplified) Shallue-van de Woestijne-Ulas map.
Parameters
[out] p - the result.
[in] msg - the byte array to map.
[in] len - the array length in bytes.
Definition at line 222 of file relic_ep2_map.c.
References ep2_map_from_field(), ep_param_level(), ERR_CAUGHT, ERR_NO_MEMORY, FP_PRIME, md_xmd, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
ep2_map_swift()
void ep2_map_swift (ep2_t p, const uint8_t * msg, size_t len)
Maps a byte array to a point in a prime elliptic curve using the SwiftEC approach.
Parameters
[out] p - the result.
[in] msg - the byte array to map.
[in] len - the array length in bytes.
Definition at line 248 of file relic_ep2_map.c.
References BASIC, bn_free, bn_get_bit(), bn_new, bn_null, bn_read_bin(), core_get(), _ctx_t::ep2_b, ep2_curve_get_a(), ep2_curve_opt_a(), ep2_curve_opt_b(), ep2_mul_cof(), ep2_rhs(), ep2_set_infty(), ep_curve_opt_a(), _ctx_t::ep_map_c, ep_param_level(), ERR_CAUGHT, ERR_NO_VALID, fp2_add, fp2_add_dig(), fp2_copy(), fp2_copy_sec(), fp2_dbl, fp2_free, fp2_inv(), fp2_inv_sim(), fp2_is_sqr(), fp2_is_zero(), fp2_mul, fp2_mul_dig(), fp2_neg(), fp2_new, fp2_null, fp2_set_dig(), fp2_sqr, fp2_srt(), fp2_sub, fp2_sub_dig(), fp_hlv, fp_is_even(), fp_is_zero(), fp_mul, FP_PRIME, fp_prime_back(), fp_prime_conv(), fp_sub_dig(), md_xmd, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_ONE, RLC_THROW, RLC_TRY, and RLC_ZERO.