RELIC: src/fpx/relic_fp9_sqr.c File Reference
relic_fp9_sqr.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
Functions
void fp9_sqr_basic (fp9_t c, const fp9_t a)
void fp9_sqr_unr (dv9_t c, const fp9_t a)
void fp9_sqr_lazyr (fp9_t c, const fp9_t a)
Detailed Description
Implementation of squaring in a nonic extension of a prime field.
Definition in file relic_fp9_sqr.c.
Function Documentation
fp9_sqr_basic()
void fp9_sqr_basic (fp9_t c, const fp9_t a)
Computes the squares of a nonic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the nonic extension field element to square.
Definition at line 42 of file relic_fp9_sqr.c.
References ERR_CAUGHT, fp3_add, fp3_dbl, fp3_free, fp3_mul, fp3_mul_nor(), fp3_new, fp3_null, fp3_sqr, fp3_sub, fp_hlv, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp9_sqr_unr()
void fp9_sqr_unr (dv9_t c, const fp9_t a)
Computes the square of a nonic extension field element without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the nonic extension field element to square.
Definition at line 115 of file relic_fp9_sqr.c.
References dv3_free, dv3_new, dv3_null, ERR_CAUGHT, fp3_addc_low(), fp3_addm_low(), fp3_dblm_low(), fp3_free, fp3_muln_low(), fp3_new, fp3_nord_low(), fp3_null, fp3_sqrn_low(), fp3_subc_low(), fp3_subm_low(), fp_hlvd_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp18_sqr_unr(), fp54_sqr_pck_lazyr(), and fp9_sqr_lazyr().
fp9_sqr_lazyr()
void fp9_sqr_lazyr (fp9_t c, const fp9_t a)
Computes the square of a nonic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the nonic extension field element to square.
Definition at line 204 of file relic_fp9_sqr.c.
References dv9_free, dv9_new, dv9_null, ERR_CAUGHT, fp3_rdcn_low(), fp9_sqr_unr(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.