RELIC: src/fp/relic_fp_shift.c File Reference
relic_fp_shift.c File Reference
Prime field arithmetic
#include "relic_core.h"
#include "relic_fp_low.h"
Functions
void fp_lsh (fp_t c, const fp_t a, uint_t bits)
void fp_rsh (fp_t c, const fp_t a, uint_t bits)
Detailed Description
Implementation of the prime field arithmetic shift functions.
Definition in file relic_fp_shift.c.
Function Documentation
fp_lsh()
void fp_lsh (fp_t c, const fp_t a, uint_t bits)
Shifts a prime field element number to the left. Computes c = a * 2^bits.
Parameters
[out] c - the result.
[in] a - the prime field element to shift.
[in] bits - the number of bits to shift.
Definition at line 39 of file relic_fp_shift.c.
References dv_lshd(), fp_copy(), fp_lsh1_low(), fp_lshb_low(), RLC_FP_DIGS, and RLC_RIP.
fp_rsh()
void fp_rsh (fp_t c, const fp_t a, uint_t bits)
Shifts a prime field element to the right. Computes c = floor(a / 2^bits).
Parameters
[out] c - the result.
[in] a - the prime field element to shift.
[in] bits - the number of bits to shift.
Definition at line 65 of file relic_fp_shift.c.
References dv_rshd(), fp_copy(), fp_rsh1_low(), fp_rshb_low(), RLC_FP_DIGS, and RLC_RIP.