RELIC: src/fb/relic_fb_sqr.c File Reference
relic_fb_sqr.c File Reference
Binary field arithmetic
#include <string.h>
#include "relic_core.h"
#include "relic_conf.h"
#include "relic_fb.h"
#include "relic_fb_low.h"
#include "relic_bn_low.h"
#include "relic_util.h"
Functions
void fb_sqr_basic (fb_t c, const fb_t a)
void fb_sqr_quick (fb_t c, const fb_t a)
void fb_sqr_integ (fb_t c, const fb_t a)
Detailed Description
Implementation of the binary field squaring.
Definition in file relic_fb_sqr.c.
Function Documentation
fb_sqr_basic()
void fb_sqr_basic (fb_t c, const fb_t a)
Squares a binary field element using bit-manipulation squaring.
Parameters
[out] c - the result.
[in] a - the binary field element to square.
Definition at line 47 of file relic_fb_sqr.c.
References dv_free, dv_new, dv_null, ERR_CAUGHT, fb_rdc, fb_sqrn_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fb_sqr_quick()
void fb_sqr_quick (fb_t c, const fb_t a)
Squares a binary field element using table-based squaring.
Parameters
[out] c - the result.
[in] a - the binary field element to square.
Definition at line 69 of file relic_fb_sqr.c.
References dv_free, dv_new, dv_null, ERR_CAUGHT, fb_rdc, fb_sqrl_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fb_sqr_integ()
void fb_sqr_integ (fb_t c, const fb_t a)
Squares a binary field element with integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the binary field element to square.
Definition at line 91 of file relic_fb_sqr.c.
References fb_sqrm_low().