RELIC: src/pp/relic_pp_exp_k54.c File Reference
relic_pp_exp_k54.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_util.h"
Functions
void pp_exp_k54 (fp54_t c, fp54_t a)
Detailed Description
Implementation of the final exponentiation for curves of embedding degree 54.
Definition in file relic_pp_exp_k54.c.
Function Documentation
pp_exp_k54()
void pp_exp_k54 (fp54_t c, fp54_t a)
Computes the final exponentiation for a pairing defined over curves of embedding degree 54. Computes c = a^(p^54 - 1)/r.
Parameters
[out] c - the result.
[in] a - the extension field element to exponentiate.
Definition at line 41 of file relic_pp_exp_k54.c.
References bn_free, bn_new, bn_null, bn_sign(), ERR_CAUGHT, fp54_conv_cyc(), fp54_copy(), fp54_exp_cyc_sps(), fp54_frb(), fp54_free, fp54_inv_cyc(), fp54_mul, fp54_new, fp54_null, fp54_sqr, fp54_sqr_cyc, fp_prime_get_par(), fp_prime_get_par_sps(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_map_k54().