RELIC: src/fpx/relic_fp4_mul.c File Reference
relic_fp4_mul.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
Functions
void fp4_mul_basic (fp4_t c, const fp4_t a, const fp4_t b)
void fp4_mul_unr (dv4_t c, const fp4_t a, const fp4_t b)
void fp4_mul_lazyr (fp4_t c, const fp4_t a, const fp4_t b)
void fp4_mul_art (fp4_t c, const fp4_t a)
void fp4_mul_frb (fp4_t c, const fp4_t a, int i, int j)
void fp4_mul_dig (fp4_t c, const fp4_t a, dig_t b)
Detailed Description
Implementation of multiplication in a quartic extension of a prime field.
Definition in file relic_fp4_mul.c.
Function Documentation
fp4_mul_basic()
void fp4_mul_basic (fp4_t c, const fp4_t a, const fp4_t b)
Multiples two quartic extension field elements.
Parameters
[out] c - the result.
[in] a - the quartic extension field element.
[in] b - the quartic extension field element.
Definition at line 42 of file relic_fp4_mul.c.
References ERR_CAUGHT, fp2_add, fp2_free, fp2_mul, fp2_mul_nor, fp2_new, fp2_null, fp2_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp4_mul_unr()
void fp4_mul_unr (dv4_t c, const fp4_t a, const fp4_t b)
Multiples two quartic extension field elements without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the quartic extension field element.
[in] b - the quartic extension field element.
Definition at line 87 of file relic_fp4_mul.c.
References dv2_free, dv2_new, dv2_null, ERR_CAUGHT, fp2_addc_low(), fp2_addm_low(), fp2_free, fp2_muln_low(), fp2_new, fp2_nord_low(), fp2_null, fp2_subc_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp12_sqr_unr(), fp16_mul_dxs_lazyr(), fp4_mul_lazyr(), fp8_mul_dxs(), and fp8_mul_unr().
fp4_mul_lazyr()
void fp4_mul_lazyr (fp4_t c, const fp4_t a, const fp4_t b)
Multiples two quartic extension field elements using lazy reduction.
Parameters
[out] c - the result.
[in] a - the quartic extension field element.
[in] b - the quartic extension field element.
Definition at line 123 of file relic_fp4_mul.c.
References dv4_free, dv4_new, dv4_null, ERR_CAUGHT, fp2_rdcn_low(), fp4_mul_unr(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp4_mul_art()
void fp4_mul_art (fp4_t c, const fp4_t a)
Multiplies a quartic extension field element by the adjoined root.
Parameters
[out] c - the result.
[in] a - the quartic extension field element to multiply.
Definition at line 142 of file relic_fp4_mul.c.
References ERR_CAUGHT, fp2_copy(), fp2_free, fp2_mul_nor, fp2_new, fp2_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep4_curve_mul_a(), fp16_frb(), fp16_mul_dxs_basic(), fp24_back_cyc(), fp24_back_cyc_sim(), fp24_frb(), fp24_sqr_cyc_basic(), fp24_sqr_cyc_lazyr(), fp24_sqr_pck_basic(), fp24_sqr_pck_lazyr(), fp48_frb(), fp4_field_init(), fp4_mul_frb(), fp8_frb(), fp8_inv(), fp8_mul_art(), fp8_mul_basic(), fp8_sqr_basic(), fp8_sqr_cyc(), fp8_srt(), pp_add_k24_basic(), pp_add_k24_projc(), pp_dbl_k24_basic(), and pp_dbl_k24_projc().
fp4_mul_frb()
void fp4_mul_frb (fp4_t c, const fp4_t a, int i, int j)
Multiplies a quartic extension field element by a power of the constant needed to compute a power of the Frobenius map.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
[in] i - the power of the Frobenius map.
[in] j - the power of the constant.
Definition at line 161 of file relic_fp4_mul.c.
References core_get(), ep_curve_is_pairf(), EP_FM16, ERR_CAUGHT, ERR_NO_VALID, fp2_free, fp2_mul, fp2_new, fp2_null, fp4_copy(), fp4_mul_art(), fp_copy(), fp_prime_get_mod18(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep4_frb().
fp4_mul_dig()
void fp4_mul_dig (fp4_t c, const fp4_t a, dig_t b)
Multiplies a quartic extension field element by a digit. Computes c = a * b.
Parameters
[out] c - the result.
[in] a - the quartic extension field element.
[in] b - the digit to multiply.
Definition at line 199 of file relic_fp4_mul.c.
References fp2_mul_dig().
Referenced by ep4_curve_mul_a(), ep4_curve_mul_b(), ep4_map(), ep4_rhs(), and fp8_mul_dig().