RELIC: src/fpx/relic_fp6_mul.c File Reference
relic_fp6_mul.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fpx_low.h"
Functions
void fp6_mul_basic (fp6_t c, const fp6_t a, const fp6_t b)
void fp6_mul_unr (dv6_t c, const fp6_t a, const fp6_t b)
void fp6_mul_lazyr (fp6_t c, const fp6_t a, const fp6_t b)
void fp6_mul_dxs (fp6_t c, const fp6_t a, const fp6_t b)
void fp6_mul_art (fp6_t c, const fp6_t a)
Detailed Description
Implementation of multiplication in a sextic extension of a prime field.
Definition in file relic_fp6_mul.c.
Function Documentation
fp6_mul_basic()
void fp6_mul_basic (fp6_t c, const fp6_t a, const fp6_t b)
Multiples two sextic extension field elements.
Parameters
[out] c - the result.
[in] a - the sextic extension field element.
[in] b - the sextic extension field element.
Definition at line 41 of file relic_fp6_mul.c.
References ERR_CAUGHT, fp2_add, fp2_copy(), fp2_free, fp2_mul, fp2_mul_nor, fp2_new, fp2_null, fp2_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp6_mul_unr()
void fp6_mul_unr (dv6_t c, const fp6_t a, const fp6_t b)
Multiples two sextic extension field elements without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the sextic extension field element.
[in] b - the sextic extension field element.
Definition at line 113 of file relic_fp6_mul.c.
References dv2_free, dv2_new, dv2_null, ERR_CAUGHT, fp2_addc_low(), fp2_addm_low(), fp2_addn_low(), fp2_free, fp2_muln_low(), fp2_new, fp2_nord_low(), fp2_null, fp2_subc_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp12_mul_unr(), and fp6_mul_lazyr().
fp6_mul_lazyr()
void fp6_mul_lazyr (fp6_t c, const fp6_t a, const fp6_t b)
Multiples two sextic extension field elements using lazy reduction.
Parameters
[out] c - the result.
[in] a - the sextic extension field element.
[in] b - the sextic extension field element.
Definition at line 191 of file relic_fp6_mul.c.
References dv6_free, dv6_new, dv6_null, ERR_CAUGHT, fp2_rdcn_low(), fp6_mul_unr(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp6_mul_dxs()
void fp6_mul_dxs (fp6_t c, const fp6_t a, const fp6_t b)
Multiples a dense sextic extension field element by a sparse element.
Parameters
[out] c - the result.
[in] a - a sextic extension field element.
[in] b - a sparse sextic extension field element.
Definition at line 211 of file relic_fp6_mul.c.
References ERR_CAUGHT, fp2_add, fp2_copy(), fp2_free, fp2_mul, fp2_mul_nor, fp2_new, fp2_null, fp2_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp12_mul_dxs_basic().
fp6_mul_art()
void fp6_mul_art (fp6_t c, const fp6_t a)
Multiplies a sextic extension field element by the adjoined root.
Parameters
[out] c - the result.
[in] a - the sextic extension field element to multiply.
Definition at line 268 of file relic_fp6_mul.c.
References ERR_CAUGHT, fp2_copy(), fp2_free, fp2_mul_nor, fp2_new, fp2_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp12_inv(), fp12_mul_art(), fp12_mul_basic(), fp12_mul_dxs_basic(), and fp12_sqr_basic().