RELIC: src/ed/relic_ed_dbl.c File Reference
relic_ed_dbl.c File Reference
Edwards curves over prime fields.
#include "relic_core.h"
#include "relic_label.h"
Functions
void ed_dbl_basic (ed_t r, const ed_t p)
void ed_dbl_projc (ed_t r, const ed_t p)
void ed_dbl_extnd (ed_t r, const ed_t p)
Detailed Description
Implementation of the point doubling on prime elliptic twisted Edwards curves.
Version
$Id$
Definition in file relic_ed_dbl.c.
Function Documentation
ed_dbl_basic()
void ed_dbl_basic (ed_t r, const ed_t p)
Doubles an Edwards elliptic curve point represented in affine coordinates.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 42 of file relic_ed_dbl.c.
References BASIC, core_get(), ERR_CAUGHT, fp_add_dig(), fp_copy(), fp_dbl, fp_free, fp_inv, fp_mul, fp_neg, fp_new, fp_null, fp_sqr, fp_sub, fp_sub_dig(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ed_dbl_projc()
void ed_dbl_projc (ed_t r, const ed_t p)
Doubles an Edwards elliptic curve point represented in projective coordinates.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 95 of file relic_ed_dbl.c.
References core_get(), ERR_CAUGHT, fp_add, fp_dbl, fp_free, fp_mul, fp_new, fp_null, fp_sqr, fp_sub, PROJC, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ed_dbl_extnd()
void ed_dbl_extnd (ed_t r, const ed_t p)
Doubles an Edwards elliptic curve point represented in extended coordinates.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 168 of file relic_ed_dbl.c.
References core_get(), ERR_CAUGHT, EXTND, fp_add, fp_dbl, fp_free, fp_mul, fp_new, fp_null, fp_sqr, fp_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.