RELIC: src/pp/relic_pp_dbl_k8.c File Reference
relic_pp_dbl_k8.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
#include "relic_util.h"
Functions
void pp_dbl_k8_basic (fp8_t l, ep2_t r, const ep2_t q, const ep_t p)
void pp_dbl_k8_projc_new (fp8_t l, ep2_t r, const ep2_t q, const ep_t p)
void pp_dbl_k8_projc_basic (fp8_t l, ep2_t r, const ep2_t q, const ep_t p)
void pp_dbl_k8_projc_lazyr (fp8_t l, ep2_t r, const ep2_t q, const ep_t p)
void pp_dbl_k8_projc_lazyr_new (fp8_t l, ep2_t r, const ep2_t q, const ep_t p)
Detailed Description
Implementation of Miller doubling for curves of embedding degree 8.
Definition in file relic_pp_dbl_k8.c.
Function Documentation
pp_dbl_k8_basic()
void pp_dbl_k8_basic (fp8_t l, ep2_t r, const ep2_t q, const ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 8 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 44 of file relic_pp_dbl_k8.c.
References ep2_copy(), ep2_curve_is_twist(), ep2_dbl_slp_basic(), ep2_free, ep2_new, ep2_null, ERR_CAUGHT, fp2_free, fp2_mul, fp2_new, fp2_null, fp2_sub, fp_copy(), fp_mul, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_dbl_k8_projc_new()
void pp_dbl_k8_projc_new (fp8_t l, ep2_t r, const ep2_t q, const ep_t p)
Definition at line 84 of file relic_pp_dbl_k8.c.
References ep2_curve_is_twist(), ERR_CAUGHT, fp2_add, fp2_free, fp2_mul, fp2_mul_art(), fp2_new, fp2_null, fp2_sqr, fp2_sub, fp_hlv, fp_mul, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_dbl_k8_projc_basic()
void pp_dbl_k8_projc_basic (fp8_t l, ep2_t r, const ep2_t q, const ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 8 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 153 of file relic_pp_dbl_k8.c.
References ep2_curve_is_twist(), ep2_curve_mul_a(), ERR_CAUGHT, fp2_add, fp2_dbl, fp2_free, fp2_mul, fp2_new, fp2_null, fp2_sqr, fp2_sub, fp_mul, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_dbl_k8_projc_lazyr()
void pp_dbl_k8_projc_lazyr (fp8_t l, ep2_t r, const ep2_t q, const ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 8 using projective coordinates and lazy reduction.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 243 of file relic_pp_dbl_k8.c.
References dv2_free, dv2_new, dv2_null, ep2_curve_is_twist(), ep2_curve_mul_a(), ERR_CAUGHT, fp2_add, fp2_dbl, fp2_free, fp2_mul, fp2_new, fp2_null, fp2_sqr, fp2_sub, fp_mul, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_dbl_k8_projc_lazyr_new()
void pp_dbl_k8_projc_lazyr_new (fp8_t l, ep2_t r, const ep2_t q, const ep_t p)
Definition at line 336 of file relic_pp_dbl_k8.c.
References dv2_new, dv2_null, ep2_curve_is_twist(), ERR_CAUGHT, fp2_addc_low(), fp2_free, fp2_mul, fp2_muln_low(), fp2_new, fp2_nord_low(), fp2_null, fp2_rdcn_low(), fp2_sqr, fp2_sqrn_low(), fp2_sub, fp2_subc_low(), fp_hlvd_low(), fp_mul, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.